### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#10003]
Following commit is causing CI failure. I am creating it to trace it.

https://github.com/Azure/azure-cli/commit/1b80e0dcfebb2e7f37293686d580baf62e64ce17

Please note that the line in **bold** was not appearing in any previous logs, and it's causing the problem.

2019-07-18T16:00:05.8723480Z ==> Downloading https://files.pythonhosted.org/packages/58/40/0d783e14112e064127063fbf5d1fe1351723e5dfe9d6daad346a305f6c49/xmltodict-0.12.0.tar.gz
2019-07-18T16:00:06.0815760Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli--xmltodict-20190718-858-cvhhxr/xmltodict-0.12.0
2019-07-18T16:00:08.2286870Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/azure-cli
2019-07-18T16:00:16.6449430Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/azure-cli-telemetry
2019-07-18T16:00:18.9656220Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/azure-cli-core
2019-07-18T16:00:21.5483660Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/azure-cli-nspkg
2019-07-18T16:00:23.8293370Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/azure-cli-command_modules-nspkg
**2019-07-18T16:00:26.0537800Z ==> /usr/local/Cellar/azure-cli/2.0.69/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/command_modules/azure-cli-sql/**
2019-07-18T16:00:27.0033290Z Last 15 lines from /Users/vsts/Library/Logs/Homebrew/azure-cli/136.pip:
2019-07-18T16:00:27.0077810Z Created temporary directory: /private/tmp/pip-install-0x4wrx96
2019-07-18T16:00:27.0078290Z Cleaning up...
2019-07-18T16:00:27.0087390Z Removed build tracker '/private/tmp/pip-req-tracker-7j9boz0_'
**2019-07-18T16:00:27.0088670Z ERROR: Directory '/private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/command_modules/azure-cli-sql/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.**
2019-07-18T16:00:27.0089210Z Exception information:
2019-07-18T16:00:27.0089590Z Traceback (most recent call last):
2019-07-18T16:00:27.0093040Z   File "/usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
2019-07-18T16:00:27.0093520Z     status = self.run(options, args)
2019-07-18T16:00:27.0094590Z   File "/usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 326, in run
2019-07-18T16:00:27.0095030Z     self.name, wheel_cache
2019-07-18T16:00:27.0099740Z   File "/usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 268, in populate_requirement_set
2019-07-18T16:00:27.0100510Z     wheel_cache=wheel_cache
2019-07-18T16:00:27.0101660Z   File "/usr/local/Cellar/azure-cli/2.0.69/libexec/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 248, in install_req_from_line
2019-07-18T16:00:27.0102730Z     "nor 'pyproject.toml' found." % name
2019-07-18T16:00:27.0104290Z pip._internal.exceptions.InstallationError: Directory '/private/tmp/azure-cli-20190718-858-w465wf/Azure-azure-cli-31ad54e/src/command_modules/azure-cli-sql/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
2019-07-18T16:00:32.7789710Z 
2019-07-18T16:00:32.7790640Z Do not report this issue to Homebrew/brew or Homebrew/core!
2019-07-18T16:00:32.7790980Z 
2019-07-18T16:00:33.2858230Z ##[error]Bash exited with code '1'.
2019-07-18T16:00:33.2936750Z ##[section]Finishing: Bash Script
2019-07-18T16:00:33.2993800Z ##[section]Starting: Checkout

**Comment by zikalino** [comment]
The issue was caused by test recording checked into wrong folder:

Fix is here
 https://github.com/Azure/azure-cli/pull/10005

Additionally I have created this issue to cleanup homebrew:

https://github.com/Azure/azure-cli/issues/10006

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
Fixed by #10005
