### ISSUE TITLE
az acr login failed bad handshake

### ISSUE THREAD

**Issue by insan6983** [Azure/azure-cli#10004]
I have an issue with login to a Azure Container Registry using Az acr login
Issue seems limited to my PC only.
I'm using PowerShell 7 preview in Windows 10. (PowerShell 5 is corrupted so I'm using 7 instead)

I can login to other container registry ‘droecoprodskilluiregistry' in subscription 217d614e-293a-4b09-b8c4-4e2f2ff78037 

but **az acr login** error happens only when logging in draskilluipreview

Is there a problem with my PowerShell and AzCLI environment?

Error messages below :
PS > az acr login --name draskilluipreview
Could not connect to the registry login server 'draskilluipreview.azurecr.io'. Please verify that the registry exists and the URL 'https://draskilluipreview.azurecr.io/v2/' is reachable from your environment.
 

PS > az acr check-health --name draskilluipreview --ignore-errors
Docker daemon status: available
Docker version: Docker version 18.09.2, build 6247962
This will pull the image mcr.microsoft.com/mcr/hello-world:latest. Proceed? (y/n): y
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK

ACR CLI version: 2.2.9

An error occurred: HELM_COMMAND_ERROR

Please verify if Helm is installed.

DNS lookup to draskilluipreview.azurecr.io at IP 13.75.36.2 : OK
The command failed with an unexpected error. Here is the traceback:
 
HTTPSConnectionPool(host='draskilluipreview.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\connection.py", line 344, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\contrib\pyopenssl.py", line 462, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='draskilluipreview.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 566, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 624, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 617, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 594, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\commands\__init__.py", line 303, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-core\azure\cli\core\__init__.py", line 470, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-acr\azure\cli\command_modules\acr\check_health.py", line 270, in acr_check_health
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-acr\azure\cli\command_modules\acr\check_health.py", line 258, in _check_health_connectivity
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\azure-cli-acr\azure\cli\command_modules\acr\check_health.py", line 191, in _get_registry_status
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='draskilluipreview.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by yugangw-msft** [comment]
You are under proxy, please follow the [tip](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy)
