### ISSUE TITLE
az acr login fails under proxy

### ISSUE THREAD

**Issue by insan6983** [Azure/azure-cli#10068]
**Is your feature request related to a problem? Please describe.**
When logging in to a Azure container registry, we can use $ az acr login -n registry_name
I found that az acr login fails under proxy environment.

HTTPSConnectionPool(host='draskilluipreview.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

**Describe the solution you'd like**
I'm requesting to improve az acr command to work well in proxy environment.

**Describe alternatives you've considered**

Setting below env variables is workaround. 
set ADAL_PYTHON_SSL_NO_VERIFY="true"
set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION="true"

**Comment by yugangw-msft** [comment]
Nothing ACR commands can do. Please follow the [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) to configure the certificate.
