### ISSUE TITLE
[webapp] - az.cmd webapp deployment source config-zip intermittently fails to connect

### ISSUE THREAD

**Issue by vicpon** [Azure/azure-cli#10061]
**Describe the bug**
When running az webapp deployment source config-zip, often times (more than 50% of the time) it errors out because it can't connect to the scm service.

**To Reproduce**
Run the following command:
```bash
az.cmd webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $APP_NAME --src dist.zip
```

When it errors out, I get this error:
```
HTTPSConnectionPool(host='[my-domain].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object a
t 0x0539F170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0539F170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[my-domain].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connectio
n.VerifiedHTTPSConnection object at 0x0539F170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\__init__.py", line 388, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\__init__.py", line 381, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\__init__.py", line 357, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\__init__.py", line 442, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 263, in enable_zip_deploy
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\api.py", line 116, in post
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[my-domain].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connec
tion.VerifiedHTTPSConnection object at 0x0539F170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

**Expected behavior**
I expect the deployment to complete without any errors.

**Environment summary**
Install Method: MSI
Azure CLI 2.0.54
Windows 10 Professional
bash or powershell, same error

**Additional context**
None

**Comment by btardif** [comment]
@tjprescott we are going to investigate this issue, thanks for reporting.

**Comment by panchagnula** [comment]
@vicpon can you try this with the latest version of CLI & see if you are still seeing the same problem. We have had several fixes/updates to this command so would be worth it to try with the latest version. thank you.

**Comment by vicpon** [comment]
> @vicpon can you try this with the latest version of CLI & see if you are still seeing the same problem. We have had several fixes/updates to this command so would be worth it to try with the latest version. thank you.

Updated to Azure CLI 2.0.69 (latest of this writing) but I get the same error:

```
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='[my app].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0
x0581A590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0581A590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wv3ha_9g\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[my app].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.V
erifiedHTTPSConnection object at 0x0581A590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 578, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 629, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 606, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\custom.py", line 322, in enable_zip_deploy
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2324, in _check_zip_deployment_status
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[my app].scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connectio
n.VerifiedHTTPSConnection object at 0x0581A590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

It may be worth noting that before the `deployment` command is run it runs these two commands successfully:

```
az.cmd webapp config appsettings set --resource-group $RESOURCE_GROUP --name $APP_NAME --settings HOST='0.0.0.0'
az.cmd webapp config appsettings set --resource-group $RESOURCE_GROUP --name $APP_NAME --settings NODE_ENV=$NODE_ENV
```

Also, I'm deploying to a B1 Linux instance with 100 ACUs, in case it's a resource contraint of the VM.

**Comment by vicpon** [comment]
It looks like the deployment succeeded this last time, after I updated to the lastest CLI. It's now timing out getting the deployment status, instead of timing out when deploying, as it was doing before. At least now it deploys so even if it doesn't return that status it's not as urgent a bug.

**Comment by panchagnula** [comment]
@vicpon thanks for the quick response, when you say that the command now fails with fetching status, do you see the same error as earlier or are you seeing something else? can you share the error?
Note we also have a --timeout parameter support which keeps the polling for the status until the custom timeout runs out. Check if this helps. thank you.

**Comment by vicpon** [comment]
> @vicpon thanks for the quick response, when you say that the command now fails with fetching status, do you see the same error as earlier or are you seeing something else? can you share the error?
> Note we also have a --timeout parameter support which keeps the polling for the status until the custom timeout runs out. Check if this helps. thank you.

The error message is above. You can see that the endpoint it fails on is now the deploy status endpoint (`/api/deployments/latest`), where before it was on `/api/zipdeploy?isAsync=true`.

I tried it 3 times in a row and it only failed once with the `getaddrinfo` error.

**Comment by panchagnula** [comment]
@vicpon when you repro this error - getting status fails - can you navigate to your scm site
which would be https://<appname>.scm.azurewebsites.net/api/deployments/latest & see if you hit the same error?

**Comment by panchagnula** [comment]
closing this since we haven't heard back on this. if this still happens please open a new one issue but before doing that please go to the scm site https://<appname>.scm.azurewebsites.net/newui

& on top right you should the the most recent deployment  - click ViewLogs & share info from it if possible
