### ISSUE TITLE
prompt-toolkit 2.0.9 breaks az interactive

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#10088]
## Describe the bug

Caused by: https://github.com/Azure/azure-cli/pull/9940

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 603, in execute
    raise ex
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli\core\commands\__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli\command_modules\interactive\custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions\interactive\azext_interactive\__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive\azext_interactive\azclishell\app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Update to prompt toolkit 2.0.9:
- `az interactive`

## Expected Behavior

Should not fail.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.7.3
Shell: python.exe

azure-cli 2.0.69

Extensions:
interactive 0.4.3

```

**Comment by tjprescott** [comment]
Interestingly, if I uninstall prompt-toolkit entirely, everything runs just fine. I'm not sure why we have this dependency at all.

**Comment by JaimePolo** [comment]
I'm having the same issue, but uninstalling prompt_toolkit does not solve it.

**Comment by HelgesenJan** [comment]
How do I uninstall prompt_toolkit?

**Comment by HelgesenJan** [comment]
How would I go about uninstalling prompt_toolkit? I'm new to Azure CLI

**Comment by HelgesenJan** [comment]
How would I go about uninstalling prompt_toolkit? I'm new to Azure CLI

**Comment by tjprescott** [comment]
`pip uninstall prompt-toolkit`

**Comment by hepais-microsoft** [comment]
This generates another error... by the way, in my case I"m using the BASH shell from within the Azure Console

**ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/wcwidth-0.1.7.dist-info'
Consider using the `--user` option or check the permissions.**

**Comment by hepais-microsoft** [comment]
> pip uninstall prompt-toolkit

The above command does not work on the local Windows 10 PowerShell since pip is not installed there.

It also doesn't work on the Azure Console BASH shell because it generates a warning:
WARNING: Skipping prompt-toolkit as it is not installed.

Hence the fix doesn't work in the above two cases...

**Comment by hepais-microsoft** [comment]
Hello folks,

The problem is still there:
I removed the prompt_toolkit by running 'pip uninstall prompt_toolkit'
Also removed the interactive extension by running 'az extension remove --name interactive

**Comment by hepais-microsoft** [comment]
Confirmed removal by running 'az extension list' and verifying the list was empty.
And reinstalled interactive.

Tried it on : https://shell.azure.com/ and in the built-in shell on https://ms.portal.azure.com/#home

The problem is not fixed.

**Comment by hepais-microsoft** [comment]
I also reinstalled the AZURE shell by running:
curl -L https://aka.ms/InstallAzureCli | bash

The problem IS STILL THERE. NOT FIXED.

**Comment by code4clouds** [comment]
The problem even shows on the Azure Cloud Shell CLI (Bash & PS).  How was it fixed?

``` bash
VERBOSE: Authenticating to Azure ...
VERBOSE: Building your Azure drive ...
Azure:/
PS Azure:\> az interactive
This command is in preview. It may be changed/removed in a future release.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/julio/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/julio/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

To open an issue, please run: 'az feedback'
Azure:/

```

**Comment by jsalaman** [comment]
Why this is closed if the issue is still there in latest Azure Cli version?:

```
PS C:\Users\under\AppData\Local\Google\Cloud SDK> az interactive
This command is in preview. It may be changed/removed in a future release.
Installing the Interactive extension...
The installed extension 'interactive' is in preview.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\interactive\custom.py", line 41, in start_shell
  File "C:\Users\under\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "C:\Users\under\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

**Comment by srdubin** [comment]
Same issue on OSX:


### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Expected Behavior

interactive mode would start 
## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70

Extensions:
interactive 0.4.3

```
## Additional Context

**Comment by yugangw-msft** [comment]
Folks,  first apologize for breaking this. I have merged this fix to be released on Aug 13. We have also started to investigate for why CI didn't catch this regression.  Meanwhile if you can't revert back to the older build, the manual workaround will be :
      
    1. If you installed through `pip`, run `pip uninstall prompt-toolkit`
    2. If you installed through Windows installer, delete `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\prompt_toolkit`
    3. If you installed through Linux bundle, find the installation location and delete the package folder. Say for Ubuntu, the folder would be `/opt/az/lib/python3.6/site-packages/prompt_toolkit`
