### ISSUE TITLE
Error with cli invoice view

### ISSUE THREAD

**Issue by crank99** [Azure/azure-cli#10083]
## Describe the bug

**Command Name**
`az billing invoice list`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/ebee13f6-6e99-492d-aacb-b276fdcc9e6e/providers/Microsoft.Billing/invoices?api-version=2018-03-01-preview (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\contrib\pyopenssl.py", line 453, in wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\pyOpenSSL\OpenSSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\pyOpenSSL\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connection.py", line 344, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\contrib\pyopenssl.py", line 459, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 667, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/ebee13f6-6e99-492d-aacb-b276fdcc9e6e/providers/Microsoft.Billing/invoices?api-version=2018-03-01-preview (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\universal_http\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/ebee13f6-6e99-492d-aacb-b276fdcc9e6e/providers/Microsoft.Billing/invoices?api-version=2018-03-01-preview (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 367, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\paging.py", line 143, in __next__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\paging.py", line 129, in advance_page
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-billing\azure\mgmt\billing\operations\invoices_operations.py", line 116, in internal_paging
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\service_client.py", line 336, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\__init__.py", line 197, in run
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\requests.py", line 72, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\pipeline\requests.py", line 193, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\universal_http\requests.py", line 328, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\universal_http\requests.py", line 140, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\exceptions.py", line 51, in raise_with_traceback
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\msrest\msrest\universal_http\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\adapters.py", line 514, in send
msrest.exceptions.ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/ebee13f6-6e99-492d-aacb-b276fdcc9e6e/providers/Microsoft.Billing/invoices?api-version=2018-03-01-preview (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az billing invoice list`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli                         2.0.62

```

**Comment by yugangw-msft** [comment]
You are running behind a proxy. Please check out the [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) for how to set up appropriately.
