### ISSUE TITLE
webapp:azure appsettings with json file in azure cli

### ISSUE THREAD

**Issue by hmdazeem** [Azure/azure-cli#10105]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by hmdazeem** [comment]
az webapp config set -n wex-xxx-xxxx-xxx-xxx  -g rax-xxx-xxx  --settings apiAppId=https://xxx-xxx-xx.onmicrosoft.com/xx-xx-xxda-6xxx-4xxx-axxx-fxxxxxxxx 
when am running this command from azure cli am getting following  error like 



ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\knack\knack\cli.py", line 197, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-core\azure\cli\core\commands\__init__.py", line 373, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-core\azure\cli\core\commands\__init__.py", line 347, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-core\azure\cli\core\__init__.py", line 440, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 153, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)


Please give any suggestion to solve this     

Thanks

**Comment by yugangw-msft** [comment]
@panchagnula, can you please take a quick look?

**Comment by panchagnula** [comment]
@hmdazeem looking at this az webapp config set -n wex-xxx-xxxx-xxx-xxx -g rax-xxx-xxx --settings apiAppId=https://xxx-xxx-xx.onmicrosoft.com/xx-xx-xxda-6xxx-4xxx-axxx-fxxxxxxxx

the command is not using a json file have you tried creating a json object in a local.json file & pass this file as input? I am going to try the example you have & get back to you as well.

**Comment by panchagnula** [comment]
Closing this since we haven't heard back, try passing a valid JSON object as an input , NOTE: don't use the format that portal uses In configuration, that is not the signature of the object on the backend API. You can check https://resources.azure.com to get the Json object
