### ISSUE TITLE
`az dls fs *` commands fail with 'ConnectionError'

### ISSUE THREAD

**Issue by jochenvw** [Azure/azure-cli#10118]
### **This is autogenerated. Please review and update as needed.**

I've deployed and ADLSgen2 store and now I would like to create file systems inside. 
Storage creation command:

```
az storage account create -n [name]-g [resource-group] --sku Standard_LRS --kind StorageV2 --hierarchical-namespace true
```
Note that the location is *westeurope* for this storage account.

Works fine - now trying to run `az dls fs` commands like:
```
az dls fs create --account [accountname] --path /test
az dls fs show --account [accountname] --path /
```
Gives the following error message:

```
HTTP error: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='[storagename].azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/test123?OP=GETFILESTATUS&api-version=2018-09-01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05C0BFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",),)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially       
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\dls\custom.py", line 143, in create_adls_item
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-datalake-store\azure\datalake\store\core.py", line 601, in exists
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-datalake-store\azure\datalake\store\core.py", line 204, in info
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-datalake-store\azure\datalake\store\lib.py", line 432, in call
azure.datalake.store.exceptions.DatalakeRESTException: HTTP error: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='[storagename].azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/test123?OP=GETFILESTATUS&api-version=2018-09-01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05C0BFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",),)
```

Is there a somewhere or am I doing something wrong?

## Describe the bug

**Command Name**
`az dls fs list`

**Errors:**
```
az dls fs list: error: the following arguments are required: --path
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.70

Extensions:
interactive 0.4.3
storage-preview 0.2.8

```

**Comment by adewaleo** [comment]
Commands shouldn't throw stack traces, at worst we should have logic to cleanly handle this error

**Comment by HarshGandhiNL** [comment]
@adewaleo - As suggested, I tried to use the above command and "create file system command combinations as under
1) az dls fs create --account "abcxyz123" --path "/test1"
2) az dls fs create --account "abcxyz123" --folder --path "/test1"
3) az dls fs create --account "abcxyz123" --folder --path "/"
4) az dls fs create --account "abcxyz123"  --path "/"
" in storage account created in West US 2 and West Central US but it fails with exactly same error as above. Hope this helps to troubleshoot.

**Comment by HarshGandhiNL** [comment]
So this issue is not in specific region.

**Comment by adewaleo** [comment]
@HarshGandhiNL I am not sure if you are responding to my comment or someone else's. I left my previous comment to guide whoever will eventually fix the issue. I was acknowledging that this is a bug because a stack trace was thrown.

Hopefully an owner of DLS or member from the CLI team, would be able to help address your issue. I am no longer a member of the CLI team.

**Comment by akharit** [comment]
I think this is trying to access gen2 account using gen1 commands? 

This is not supported so will not work.

**Comment by lisardggY** [comment]
Is there anywhere to keep updated about when gen2 will be supported by CLI? Judging by the DNS suffix in the error description, it's almost certainly accessing gen1 stores, but is there any alternative? The standard blob api (`az storage blob *`) give an error (with stack trace, again):

`Blob API is not yet supported for hierarchical namespace accounts. ErrorCode: BlobApiNotYetSupportedForHierarchicalNamespaceAccounts`

**Comment by akharit** [comment]
@lisardggY Sorry wasn't clear. The first line 
`az storage account create -n [name]-g [resource-group] --sku Standard_LRS --kind StorageV2 --hierarchical-namespace true`

reads on creating a storagev2 account and then trying to access it as adls gen1 storage account, which will not work.

**Comment by akharit** [comment]
Please close this if there aren't any other asks. This seems to be a user error i.e. trying to use adls gen1 commands for adls gen2 account.
