### ISSUE TITLE
Using 2.0.67 worked in DevOps. 5 hours later, 2.0.69 did not: authentication issue

### ISSUE THREAD

**Issue by jdluzen** [Azure/azure-cli#10126]
**Describe the bug**
Today, when using `az` 2.0.67 on Linux in a DevOps pipeline, I was successfully able to upload to my Azure storage blob static site. 5 hours later, DevOps had automatically updated `az` to 2.0.69, and now I am unable to upload. It fails with:
```
ERROR: azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=<a uuid> Retry policy did not allow for a retry: Server-Timestamp=Fri, 02 Aug 2019 02:15:40 GMT, Server-Request-ID=<a uuid>, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:<a uuid>Time:2019-08-02T02:15:40.4961862Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '<base64 data>' is not the same as any computed signature. Server used following string to sign: 'PUT257x-ms-blob-type:BlockBlobx-ms-client-request-id:<a uuid>x-ms-date:Fri, 02 Aug 2019 02:15:40 GMTx-ms-version:2018-11-09/<my storage account name>/$web/assets/theme/styles/skins/_pink-dark.scss'.</AuthenticationErrorDetail></Error>.
ERROR: 
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
                
DEBUG: Event: CommandInvoker.OnFilterResult []
ERROR: cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: cli.azure.cli.core.util : 'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
ERROR: 'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

**To Reproduce**
```
DEBUG: Command arguments: ['storage', 'blob', 'upload', '--debug', '--auth-mode', 'key', '--file', './assets/theme/styles/skins/_pink-dark.scss', '--container-name', '$web', '--name', './assets/theme/styles/skins/_pink-dark.scss', '--account-name', '<my storage account name>', '--account-key', '<my base64 key from the Blob Storage Access keys tab>']
```

**Expected behavior**
My files were uploaded.

**Environment summary**
Azure DevOps Hosted Ubuntu 16.04

**Comment by jdluzen** [comment]
I was able to work around this. The logs suggest that something may have been wrong with the request, including the signature. The `--file` argument has the filename which includes the initial `./`. Removing the dot slash lets it continue.
