### ISSUE TITLE
az account get-access-token does not work in Cloud Shell for some resources

### ISSUE THREAD

**Issue by rich617** [Azure/azure-cli#10165]
## Describe the bug

The command `az account get-access-token` works in the downloaded Azure CLI for the resource types `https://database.windows.net/` and `https://ossrdbms-aad.database.windows.net`, but it does not work for these resources in Cloud Shell. Instead, it results in the exception reported below. 

The weird thing is that it works fine in Cloud Shell (and downloaded) for other resource types such as `https://graph.windows.net/`. 

It is not clear to me what the difference is between the resources that work in Cloud Shell and those that do not work, nor do I know how to debug the issue. I checked the code, and it appears that Cloud Shell and downloadable versions of CLI appear to be using the same clientId ("Xplat client ID"). If they were using different client IDs, that would explain the difference. 

I can see that the Cloud Shell CLI uses a different flow for get_raw_token. Any advice on how to debug this would be appreciated.

**Command Name**
`az account get-access-token`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Launch Cloud Shell from the Azure Portal.
- `az account get-access-token --resource https://database.windows.net/`

## Expected Behavior

Should return a JSON structure containing a valid access token for the Portal logged-in user containing the audience claim value `https://database.windows.net/`.

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70

```

**Comment by yugangw-msft** [comment]
@maertendMSFT, when cloud shell would be able to supply the token for resources of  `https://database.windows.net/` and `https://ossrdbms-aad.database.windows.net`?

**Comment by yugangw-msft** [comment]
We will reactive when cloud shell supports it. This is not a CLI issue.

**Comment by bpelikan** [comment]
The same for own App registration e.g.:

 `Application ID URI` : `api://own-apim`


---

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 61, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 600, in get_raw_token
    creds = self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 373, in _get_token_from_cloud_shell
    auth = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

**Comment by rich617** [comment]
For reference, in case anyone else has this issue or is looking into it:

First, there is a workaround, which is to enter the command "az login" into the Cloud Shell command prompt, and then follow the instructions to open the authentication page and paste in the given verification code. After doing that, "az account get-access-token --resource" will work in Cloud Shell as it does in the on-prem Azure CLI. 

Second, in order for a resource to be supported out-of-the-box in Cloud Shell, there must be a registered resource mapping in the Portal codebase for it. So, this is not an issue in the Azure CLI code, but rather an issue where the mapping does not exist in the Portal code. For this reason, it is likely that the "az login" workaround will be needed in Cloud Shell for all but well-known resource names.
