### ISSUE TITLE
Interactive failed with an unexpected error

### ISSUE THREAD

**Issue by PuffTMD** [Azure/azure-cli#10163]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.70

**Describe the bug**
the following error occurs after entering `az interactive`.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/user1/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/user1/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

**To Reproduce**
type `az interactive`  .

**Expected behavior**
Enter interactive mode.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
az --version
azure-cli                         2.0.70

command-modules-nspkg               2.0.3
core                              2.0.70
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.11.0
interactive                        0.4.3
application-insights               0.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/user1/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 25 2019, 08:54:21)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**Comment by gamesbrainiac** [comment]
I have the same problem

**Comment by code4clouds** [comment]
fyi... @yugangw-msft posted a workaround in #10088.

**Comment by yugangw-msft** [comment]
dupe to #10088
