### ISSUE TITLE
cannot publish function on fedora 30 using official packages

### ISSUE THREAD

**Issue by rodrigotactech** [Azure/azure-cli#10194]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'NoneType' object has no attribute 'server_farm_id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -n {} -g {} --src {}`

## Environment Summary
```
Linux-5.1.20-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 2.7.16
Shell: bash

azure-cli 2.0.70

```

**Comment by rodrigotactech** [comment]
it is just and uncontrolled ex. The real problem was some bad params given.
It should be nice if the Error is controlled and tells you something usefull

**Comment by yugangw-msft** [comment]
@panchagnula, why AppService sercice end doesn't throw when there is the plan doesn't exist?

**Comment by panchagnula** [comment]
Assigning to functions team to triage & comment

**Comment by ahmedelnably** [comment]
@ankitkumarr can you please take a look at this?

**Comment by MarkHerhold** [comment]
I'm having the same issue on MacOS.

```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.72_1/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 289, in enable_zip_deploy_functionapp
    parse_plan_id = parse_resource_id(app.server_farm_id)
AttributeError: 'NoneType' object has no attribute 'server_farm_id'
```

Version:
```
az --version
azure-cli                         2.0.72

command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python'
Extensions directory '/Users/mherhold/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Sep  7 2019, 18:29:04) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by BrixSat** [comment]
Same with latest.
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/xarevision/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Oct 11 2019, 09:04:53) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by BrixSat** [comment]
Same error with latest
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/mherhold/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Oct 11 2019, 09:04:53) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by navba-MSFT** [comment]
@rodrigotactech Apologies for the late reply. Could you please let me know if you are still facing the same issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of Az CLI? Awaiting you reply.
