### ISSUE TITLE
Api not available error for az vm list-ip-addresses

### ISSUE THREAD

**Issue by dbilleci-lightstream** [Azure/azure-cli#10231]
````
root@api-b-1-stage-cae-vm:/home/ubuntu# az vm list-ip-addresses --ids /subscriptions/XXXXX/resourceGroups/Api-B-Stage-Cae-Rg/providers/Microsoft.Compute/virtualMachines/Api-B-0-Stage-Cae-Vm /subscriptions/XXXXX/resourceGroups/Api-B-Stage-Cae-Rg/providers/Microsoft.Compute/virtualMachines/Api-B-1-Stage-Cae-Vm
/subscriptions/XXXXX/resourceGroups/Api-B-Stage-Cae-Rg/providers/Microsoft.Compute/virtualMachines/Api-B-0-Stage-Cae-Vm: "APIVersion 2019-04-01 is not available"
/subscriptions/XXXXX/resourceGroups/Api-B-Stage-Cae-Rg/providers/Microsoft.Compute/virtualMachines/Api-B-1-Stage-Cae-Vm: "APIVersion 2019-04-01 is not available"

root@api-b-1-stage-cae-vm:/home/ubuntu# az vm list-ip-addresses
The command failed with an unexpected error. Here is the traceback:

APIVersion 2019-04-01 is not available
Traceback (most recent call last):
  File "/opt/ansible/env/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/ansible/env/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 777, in list_vm_ip_addresses
    nics = network_client.network_interfaces.list_all()
  File "/opt/ansible/env/lib/python3.6/site-packages/azure/mgmt/network/network_management_client.py", line 2022, in network_interfaces
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-04-01 is not available

To open an issue, please run: 'az feedback'

root@api-b-1-stage-cae-vm:/home/ubuntu# az --version
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/opt/ansible/env/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
````

**Comment by dbilleci-lightstream** [comment]
working in 2.0.71 - closing

**Comment by qwordy** [comment]
Could you add `--debug` to the end of your command and provide the output? Thanks.
