### ISSUE TITLE
az resource tag crashed

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#10246]
I have tried following command:

az resource tag --ids  /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg1 --tags xxx=yyy

It crashed with following stacktrace:

The command failed with an unexpected error. Here is the traceback:

'namespace'
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 578, in execute
    raise ex
  File "/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 636, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 629, in _run_job
    six.reraise(*sys.exc_info())
  File "/env/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 606, in _run_job
    result = cmd_copy(params)
  File "/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/azure-cli/src/azure-cli/azure/cli/command_modules/resource/custom.py", line 928, in tag_resource
    [_get_rsrc_util_from_parsed_id(cmd.cli_ctx, id_dict, api_version).tag(tags) for id_dict in parsed_ids])
  File "/azure-cli/src/azure-cli/azure/cli/command_modules/resource/custom.py", line 928, in <listcomp>
    [_get_rsrc_util_from_parsed_id(cmd.cli_ctx, id_dict, api_version).tag(tags) for id_dict in parsed_ids])
  File "/azure-cli/src/azure-cli/azure/cli/command_modules/resource/custom.py", line 802, in _get_rsrc_util_from_parsed_id
    api_version)
  File "/azure-cli/src/azure-cli/azure/cli/command_modules/resource/custom.py", line 1802, in __init__
    api_version = _ResourceUtils._resolve_api_version_by_id(self.rcf, resource_id)
  File "/azure-cli/src/azure-cli/azure/cli/command_modules/resource/custom.py", line 2005, in _resolve_api_version_by_id
    namespace = parts.get('child_namespace_1', parts['namespace'])
KeyError: 'namespace'

**Comment by MyronFanQiu** [comment]
In my understanding, the `az resource` is to create an Azure resource instead of Azure resource group. Meanwhile, I checked this command `az resource tag`, look like the `--ids` must be a resource id.

**Comment by Juliehzl** [comment]
`az resource tag ` is used to add tags for resources and `az group tag` is used to add tags for resource group. But maybe we can provide more accurate description for these commands.
