### ISSUE TITLE
unable to set key vault access policy to user assigned identity using service principal

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10266]
## description
As a developer, I would like to provision MSI (user assigned identity) and grant access to read key vault using service principal (terraform)

## steps 

1. create spn with owner for current subscription 
``` shell
 az ad sp create-for-rbac --name terraform-spn --role owner --keyvault mykeyvault --cert terraform-spn-cert
```
2. grant kv access policy to newly created spn
``` shell
az keyvault set-policy `
        -n $settings.kv.name `
        --key-permissions backup create decrypt delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey `
        --object-id $terraformSpn.objectId | Out-Null
    az keyvault set-policy `
        -n $settings.kv.name `
        --certificate-permissions backup create delete deleteissuers get getissuers import list listissuers managecontacts manageissuers purge recover restore setissuers update `
        --object-id $terraformSpn.objectId | Out-Null
    az keyvault set-policy `
        -n $settings.kv.name `
        --secret-permissions backup delete get list purge recover restore set `
        --object-id $terraformSpn.objectId | Out-Null
    az keyvault set-policy `
        -n $settings.kv.name `
        --storage-permissions backup delete deletesas get getsas list listsas purge recover regeneratekey restore set setsas update `
        --object-id $terraformSpn.objectId | Out-Null
```
3. login as service principal
``` bash
az login --service-principal `
        --username "http://$ServicePrincipalName" `
        --password $clientSecret.value `
        --tenant $TenantId 
```
4. create a new identity 
``` bash
az identity create -g $settings.global.resourceGroup.name -n $settings.kv.reader
```
5. grant reader permission to kv secret
```bash
az keyvault set-policy -n $settings.kv.name --certificate-permissions get list --spn $identity.clientId
```

## errors from last step 
Insufficient privileges to complete the operation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9d9728-0246-49a5-3f24-b954c50fbb83
* Version Independent ID: 0c1ed853-aeb9-bab5-41e1-70ecfea00b6e
* Content: [az identity](https://docs.microsoft.com/en-us/cli/azure/identity?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/identity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/identity.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
Reproed. When logged in as Service Principal, setting policy via `--spn <clientId>` will look for the `objectId` (also called `principalId`) from `<clientId>` (also called `service principal name`) using Graph API and get denied. We will work internally for a fix.

**Comment by smartpcr** [comment]
thank you @jiasli for help, I am unblocked. :)

**Comment by Shto1337** [comment]
Hello,

This issue still persists today(even with Contributor type of access on a Service Principal) and the workaround is still valid. 

`az keyvault set-policy --name "${KEYVAULT_NAME}" --secret-permissions get --spn "${USER_ASSIGNED_CLIENT_ID}"
The command failed with an unexpected error. Here is the traceback:
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 1011, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2023-03-27T19:24:57","request-id":"3a30af7d-b97f-438f-b34e-c743eef5958c","client-request-id":"3a30af7d-b97f-438f-b34e-c743eef5958c"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 897, in set_policy
    object_id = _object_id_args_helper(cmd.cli_ctx, object_id, spn, upn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 876, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 354, in _get_object_id
    return _get_object_id_by_spn(graph_client, spn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 312, in _get_object_id_by_spn
    accounts = list(graph_client.service_principal_list(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
    result = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.`

Would it be possible in having an actual fix instead of having a workaround?

Some Microsoft articles actually depend on this type of commands/information such as https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity#create-a-managed-identity-and-grant-permissions-to-access-the-secret

Thank you!

**Comment by thomasgebets** [comment]
I can confirm, this issue still exists with the following command: 
az keyvault set-policy -n $keyVaultName --key-permissions get list --secret-permissions get list --spn $applicationId

The script is executed by another service principle as the one added to the keyvaults policy

`2025-03-07T15:16:43.2753953Z ERROR: Insufficient privileges to complete the operation.
2025-03-07T15:16:43.2754348Z Traceback (most recent call last):
2025-03-07T15:16:43.2754912Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
2025-03-07T15:16:43.2755906Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1007, in send_raw_request
2025-03-07T15:16:43.2756780Z azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2025-03-07T15:16:47","request-id":"7d881e25-43c8-4029-8119-2468de10b07e","client-request-id":"7d881e25-43c8-4029-8119-2468de10b07e"}}})
2025-03-07T15:16:43.2757338Z 
2025-03-07T15:16:43.2757652Z The above exception was the direct cause of the following exception:
2025-03-07T15:16:43.2757823Z 
2025-03-07T15:16:43.2758077Z Traceback (most recent call last):
2025-03-07T15:16:43.2758506Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2025-03-07T15:16:43.2759087Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
2025-03-07T15:16:43.2759714Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
2025-03-07T15:16:43.2760326Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
2025-03-07T15:16:43.2760952Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
2025-03-07T15:16:43.2761558Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2025-03-07T15:16:43.2762179Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 928, in set_policy
2025-03-07T15:16:43.2762819Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 907, in _object_id_args_helper
2025-03-07T15:16:43.2763472Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 356, in _get_object_id
2025-03-07T15:16:43.2764118Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 314, in _get_object_id_by_spn
2025-03-07T15:16:43.2764785Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
2025-03-07T15:16:43.2765451Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
2025-03-07T15:16:43.2766323Z azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.
2025-03-07T15:16:43.2770243Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2025-03-07T15:16:43.4871643Z [INFO] Successfully created Key Vault Access Policies for the Power BI Service Principle.
2025-03-07T15:16:43.5477658Z 
2025-03-07T15:16:43.5646800Z ##[error]WARNING: Preview version of extension is enabled by default for extension installation now. Will be disabled in future release. 
WARNING: Please run 'az config set extension.dynamic_install_allow_preview=true or false' to config it specifically. 
WARNING: The command requires the extension datafactory. It will be installed first.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1007, in send_raw_request
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2025-03-07T15:16:47","request-id":"7d881e25-43c8-4029-8119-2468de10b07e","client-request-id":"7d881e25-43c8-4029-8119-2468de10b07e"}}})

2025-03-07T15:16:43.5658359Z ##[error]Script has output to stderr. Failing as failOnStdErr is set to true.`
