### ISSUE TITLE
Unable to load extension 'storage-preview' for azure-cli 2.0.71

### ISSUE THREAD

**Issue by thatguylong** [Azure/azure-cli#10274]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.71

**Describe the bug**
After upgrading to azure-cli 2.0.71, commands that I run gives me a

```
lphan@thatguylong-2 ~ $ az account set -s < subscription >
Unable to load extension 'storage-preview'. Use --debug for more information.
error message.
```

The only one that does not seem to produce that error is:

```
lphan@thatguylong-2 ~ $ az --version
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
storage-preview                    0.1.6

Python location '/usr/local/Cellar/azure-cli/2.0.71/libexec/bin/python'
Extensions directory '/Users/lphan/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Aug 15 2019, 06:16:55) 
[Clang 11.0.0 (clang-1100.0.20.17)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

Here is the debug:

```
Found 1 extensions: ['storage-preview']
Extensions directory: '/Users/lphan/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.71 min_required=2.0.43 max_required=None
Event: CommandLoader.OnLoadCommandTable []
Event: MainLoader.OnFailedExtensionLoad []
Unable to load extension 'storage-preview'. Use --debug for more information.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 202, in _update_command_table_from_extensions
    _load_extension_command_loader(self, args, ext_mod)
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 958, in _load_extension_command_loader
    return _load_command_loader(loader, args, ext, '')
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 944, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "/Users/lphan/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 33, in load_command_table
    load_command_table(self, args)
  File "/Users/lphan/.azure/cliextensions/storage-preview/azext_storage_preview/commands.py", line 36, in load_command_table
    custom_command_type=storage_account_custom_type) as g:
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 446, in command_group
    return self._command_group_cls(self, group_name, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 1058, in __init__
    merged_kwargs = self._merge_kwargs(kwargs, base_kwargs=command_loader.module_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 1082, in _merge_kwargs
    return _merge_kwargs(kwargs, base, CLI_COMMAND_KWARGS)
  File "/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 1033, in _merge_kwargs
    raise TypeError('unrecognized kwargs: {}'.format(unrecognized_kwargs))
TypeError: unrecognized kwargs: ['min_profile']

Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1108a1170>]
```

**To Reproduce**
Upgrade to latest. Run az commands

**Expected behavior**
To not get the `Unable to load extension 'storage-preview'. Use --debug for more information.` error.

**Comment by Juliehzl** [comment]
@thatguylong  Can storage-preview extension be loaded before you upgrading azure cli to 2.0.71? If yes, what is the version of your azure cli? 
Can you upgrade your storage-preview extension first? Storage-preview 0.1.6 is too old and maybe roved in profile... For me, storage-preview 2.0.8 works well with azure cli 2.0.71.

**Comment by thatguylong** [comment]
@Juliehzl that seemed to resolve it. Thank you.

```
lphan@thatguylong-2 ~ $ az extension update --name storage-preview
Unable to load extension 'storage-preview'. Use --debug for more information.
lphan@thatguylong-2 ~ $ az extension list
[
  {
    "extensionType": "whl",
    "name": "storage-preview",
    "version": "0.2.8"
  }
]
lphan@thatguylong-2 ~ $ 
```
