### ISSUE TITLE
webapp:Try start webjob on a slot but not working

### ISSUE THREAD

**Issue by johannesoenema** [Azure/azure-cli#10301]
### Describe the bug

**Command Name**
`az webapp webjob continuous start`

**Error**
```console
2019-08-22T08:51:28.1877358Z ERROR: cli.azure.cli.core.util : dictionary update sequence element #0 has length 1; 2 is required
2019-08-22T08:51:28.1883493Z Traceback (most recent call last):
2019-08-22T08:51:28.1884640Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\knack\knack\cli.py", line 206, in invoke
2019-08-22T08:51:28.1891911Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
2019-08-22T08:51:28.1893349Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
2019-08-22T08:51:28.1913087Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 652, in _run_job
2019-08-22T08:51:28.1923380Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
2019-08-22T08:51:28.1937511Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
2019-08-22T08:51:28.1948085Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
2019-08-22T08:51:28.1949325Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
2019-08-22T08:51:28.1971934Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2357, in start_continuous_webjob
2019-08-22T08:51:28.1981701Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-mgmt-web\azure\mgmt\web\operations\web_apps_operations.py", line 3321, in start_continuous_web_job
2019-08-22T08:51:28.2041890Z ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

### To Reproduce
Steps to reproduce the behavior. Note: Command arguments have been redacted.

* Run: `az webapp webjob continuous start --webjob-name {} --name {} --resource-group {} --slot {}`

### Expected behavior
Start webjob in a slot

### Environment summary
```
Using build step in Azure DevOps
Python (Windows) 3.6.6
Shell: cmd.exe

azure-cli                         2.0.71
```

### Additional context
Same issue as [this one](https://github.com/Azure/azure-cli/issues/9116). It has been fixed for stopping a webjob, but it seems still broken for starting a webjob.

**Comment by johannesoenema** [comment]
I just found out that the fix is in the dev branch: https://github.com/Azure/azure-cli/commit/983c48365929e9f907cee6be3ebccbb4a4d7dfc2

Do you know when it will be released?

**Comment by panchagnula** [comment]
This the release cycle tracking the fix https://github.com/Azure/azure-cli/milestone/71
