### ISSUE TITLE
az aks browse - aks dashboard not configured to listen on http port 9090

### ISSUE THREAD

**Issue by graemechristie** [Azure/azure-cli#10345]
**Describe the bug**
az aks browse appears to be tunnelling http port 9090 from the kubernetes-dashboard pod to local port 8001, however aks currently appears to be running kubernetes dashboard listening on https port 8443.

**To Reproduce**
Create a new aks cluster `<clustername>` in resource group `<resourcegroup>`, then run `aks browse -g <resourcegroup> -n <clustername>` 

**Expected behaviour**
A browser window will open at http://localhost:8001 showing the kubernetes dashboard

**Environment summary**
Verified with az command line version 2.0.32  on windows, linux (wsl) and OSX.
kubectl version: 1.15.3
kubernetes version: verified on 1.14.3 and 1.14.6

**Additional context**
az aks browse was working as expected yesterday. I assume that the kubernetes dashboard deployment has been updated on our cluster automatically ... ?

Deploying a new cluster today (v 1.14.6) also sees the kubernetes dashboard  running on https port 8443.

```
[gchristie@mbp ~]$ kubectl describe services kubernetes-dashboard --namespace=kube-system
Name:              kubernetes-dashboard
Namespace:         kube-system
Labels:            addonmanager.kubernetes.io/mode=Reconcile
                   k8s-app=kubernetes-dashboard
                   kubernetes.io/cluster-service=true
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubern...
Selector:          k8s-app=kubernetes-dashboard
Type:              ClusterIP
IP:                10.253.16.34
Port:              <unset>  443/TCP
TargetPort:        https/TCP
Endpoints:         10.254.1.11:8443
Session Affinity:  None
Events:            <none>
```

-----

```
kubectl get pods -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-69b5b66fd8-bfg7g                1/1     Running   0          11h
coredns-69b5b66fd8-qt59v                1/1     Running   0          11h
coredns-autoscaler-65d7986c6b-vbq47     1/1     Running   0          21d
kube-proxy-4pmq4                        1/1     Running   0          11h
kube-proxy-w6wkx                        1/1     Running   0          11h
kubernetes-dashboard-674c5dbd96-rctnj   1/1     Running   0          21m
metrics-server-66dbbb67db-scf7s         1/1     Running   2          21d
omsagent-nnlx4                          1/1     Running   0          21d
omsagent-rs-565cfcdf7b-f95fs            1/1     Running   0          21d
omsagent-z5cm9                          1/1     Running   0          21d
tiller-deploy-547959b956-lwxs2          1/1     Running   0          21d
tunnelfront-67dd645dbb-sqm6h            1/1     Running   0          22h```
```

-----

```
[gchristie@mbp ~]$ kubectl describe pod kubernetes-dashboard-674c5dbd96-rctn -n kube-system
Name:                 kubernetes-dashboard-674c5dbd96-rctnj
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 aks-nodepool1-38285984-vmss000000/172.24.146.4
Start Time:           Tue, 27 Aug 2019 16:13:51 +0800
Labels:               k8s-app=kubernetes-dashboard
                      kubernetes.io/cluster-service=true
                      pod-template-hash=674c5dbd96
Annotations:          <none>
Status:               Running
IP:                   10.254.1.11
Controlled By:        ReplicaSet/kubernetes-dashboard-674c5dbd96
Containers:
  main:
    Container ID:  docker://4d9fd76bcc07fbd7f2cce7f8e2feb243caa25be98d9ad1076d5a9f4903a4219b
    Image:         aksrepos.azurecr.io/mirror/kubernetes-dashboard-amd64:v1.10.1
    Image ID:      docker-pullable://aksrepos.azurecr.io/mirror/kubernetes-dashboard-amd64@sha256:0ae6b69432e78069c5ce2bcde0fe409c5c4d6f0f4d9cd50a17974fea38898747
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
      --enable-skip-login
    State:          Running
      Started:      Tue, 27 Aug 2019 16:13:53 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  500Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Liveness:  http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  npencaks-npencaks-6ee946-a7a806b6.hcp.australiasoutheast.azmk8s.io
      KUBERNETES_PORT:               tcp://npencaks-npencaks-6ee946-a7a806b6.hcp.australiasoutheast.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://npencaks-npencaks-6ee946-a7a806b6.hcp.australiasoutheast.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       npencaks-npencaks-6ee946-a7a806b6.hcp.australiasoutheast.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-4h55r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubernetes-dashboard-token-4h55r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-4h55r
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                        Message
  ----    ------     ----  ----                                        -------
  Normal  Scheduled  23m   default-scheduler                           Successfully assigned kube-system/kubernetes-dashboard-674c5dbd96-rctnj to aks-nodepool1-38285984-vmss000000
  Normal  Pulled     23m   kubelet, aks-nodepool1-38285984-vmss000000  Container image "aksrepos.azurecr.io/mirror/kubernetes-dashboard-amd64:v1.10.1" already present on machine
  Normal  Created    23m   kubelet, aks-nodepool1-38285984-vmss000000  Created container main
  Normal  Started    23m   kubelet, aks-nodepool1-38285984-vmss000000  Started container main
```

--------

```
az aks browse -g <redacted> -n <redacted>
Merged "<redacted>" as current context in /var/folders/nt/f6v0pdx11z18_t5gm8wg1rgmq9rvc2/T/tmprglk94rw
Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Forwarding from 127.0.0.1:8001 -> 9090
Forwarding from [::1]:8001 -> 9090
Handling connection for 8001
Handling connection for 8001
E0827 16:38:22.752454   94836 portforward.go:400] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod c9b7c152ed6e885247103ad228972c85b3b735e52e64abbd437fd7875e176f9c, uid : exit status 1: 2019/08/27 08:38:22 socat[96850] E connect(6, AF=2 127.0.0.1:9090, 16): Connection refused
E0827 16:38:22.752456   94836 portforward.go:400] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod c9b7c152ed6e885247103ad228972c85b3b735e52e64abbd437fd7875e176f9c, uid : exit status 1: 2019/08/27 08:38:22 socat[96849] E connect(6, AF=2 127.0.0.1:9090, 16): Connection refused
Handling connection for 8001
E0827 16:38:22.934446   94836 portforward.go:400] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod c9b7c152ed6e885247103ad228972c85b3b735e52e64abbd437fd7875e176f9c, uid : exit status 1: 2019/08/27 08:38:22 socat[96852] E connect(6, AF=2 127.0.0.1:9090, 16): Connection refused
Handling connection for 8001
Handling connection for 8001
E0827 16:38:28.055712   94836 portforward.go:400] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod c9b7c152ed6e885247103ad228972c85b3b735e52e64abbd437fd7875e176f9c, uid : exit status 1: 2019/08/27 08:38:28 socat[97050] E connect(6, AF=2 127.0.0.1:9090, 16): Connection refused
```

**Comment by graemechristie** [comment]
We are in region australiasoutheast, if that is of any consequence.

**Comment by moh-abk** [comment]
Having this same issue also

**Comment by matthewhartstonge** [comment]
Also happening on `az cli@2.0.71` and `az cli@2.0.72`, this appeared after upgrading to `k8s@1.13.10`, but we are also getting a cert invalid error.

![Capture](https://user-images.githubusercontent.com/6119549/63819831-f25f7700-c99a-11e9-8e4e-2448124967fe.PNG)

**Comment by graemechristie** [comment]
> Ironically, so far as a weird side effect, I've found that proxying this way also holds the connection to the dashboard open for longer than 5 minutes for those of you who happen to work in kube all day. 👌

I've noticed this too. I can even disconnect my machine, go home, come back the next day, plug it back into the network and my kubectl proxy connection is still up.

**Comment by graemechristie** [comment]
For me, the above script worked great, I did need to add a "start" command before the line launching chrome so it launched in the background and the script continued.

```
@echo off

kubectl config use-context RESOURCE_NAME
start "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default
kubectl proxy --port 8001
pause
```

**Comment by graemechristie** [comment]
I just realised I was not running the latest version of the azure cli in my original post. Have updated, and now az aks browse gets the following. 

```
PS C:\Users\gchristie> az aks browse -g <redacted> -n <redacted>                                                                                                                                            The behavior of this command has been altered by the following extension: aks-preview                                                                                                                   Merged "<redacted>" as current context in C:\Users\GCHRIS~1\AppData\Local\Temp\tmpyoma5puw                                                                                                                Proxy running on http://127.0.0.1:8001/                                                                                                                                                                 Press CTRL+C to close the tunnel...                                                                                                                                                                     Exception in thread Thread-1:                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                        File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner                                                                                                   self.run()                                                                                                                                                                                            File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run                                                                                                                self._target(*self._args, **self._kwargs)
  File "C:\Users\gchristie\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 92, in wait_then_open
    urlopen(url, context=_ssl_context())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 297, in
```

**Comment by seanmck** [comment]
This was a temporary issue caused by shifting the dashboard to serve from an HTTPS endpoint (on port 8443) for RBAC clusters prior to the associated CLI changes going out. We've reverted the service side change for now until the updated CLI is released.

**Comment by RoyKimYYZ** [comment]
This issue is still happening with kubernetes cluster version 1.16.4. I was able to load k8s dashboard with the workaround mentioned and updated by az CLI. Is this an issue on the service side?

**Comment by sebader** [comment]
same here with both, 1.16.4 and also 1.17.0
@seanmck  could you please take a look? thanks!

**Comment by RoyKimYYZ** [comment]
I to managed to resolve this issue by updating my Az CLI (windows) and doing az aks brows ...

**Comment by wdrdres3qew5ts21** [comment]
I also confront the problem too that I can only use AZ cli from powershell only inorder to access :8001 dashboard but in WSL sometime i will not work even though how many time you restart your computer it still didn't work !
The way to fix this problem is using 
```
wsl --shutdown
```
then restart your wsl with docker integration again and then you can run AZ CLI inside WSL and access dashboard proxy through localhost 😎😎😎
