### ISSUE TITLE
az webapp deployment source config-zip and App Service Environment (ASEv2)

### ISSUE THREAD

**Issue by vaibhavramdasi** [Azure/azure-cli#10380]
**Describe the bug**
I'm trying to deploy a web app using azure devops and azure cli task. The app is hosted in App Service Environment(ILB ASE). It seems that az cli cannot reach the scm endpoint for webapp hosted in ASEv2.

**To Reproduce**
`az webapp deployment source config-zip -g rgname -n webappname --src drop/api.zip
`

**Expected behavior**
Deployment should succeed

**Environment summary**
Azure Devops Hosted Pipeline Agent
vs-2017-windows2016
azure cli 1.* task
**Additional context**
Error log:
2019-08-30T12:03:06.8048301Z WARNING: Getting scm site credentials for zip deployment
2019-08-30T12:03:08.1854465Z WARNING: Starting zip deployment. This operation can take a while to complete ...
2019-08-30T12:03:08.1988529Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-08-30T12:03:08.1989314Z 
2019-08-30T12:03:08.2428073Z ERROR: HTTPSConnectionPool(host='webappname.scm.asedomain.local', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04273EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2019-08-30T12:03:08.2428469Z Traceback (most recent call last):
2019-08-30T12:03:08.2428680Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connection.py", line 159, in _new_conn
2019-08-30T12:03:08.2428873Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\util\connection.py", line 57, in create_connection
2019-08-30T12:03:08.2429108Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
2019-08-30T12:03:08.2429301Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2019-08-30T12:03:08.2429475Z socket.gaierror: [Errno 11001] getaddrinfo failed
2019-08-30T12:03:08.2429619Z 
2019-08-30T12:03:08.2429918Z During handling of the above exception, another exception occurred:
2019-08-30T12:03:08.2430057Z 
2019-08-30T12:03:08.2430545Z Traceback (most recent call last):
2019-08-30T12:03:08.2430868Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connectionpool.py", line 600, in urlopen
2019-08-30T12:03:08.2431292Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connectionpool.py", line 343, in _make_request
2019-08-30T12:03:08.2431549Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
2019-08-30T12:03:08.2431798Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connection.py", line 301, in connect
2019-08-30T12:03:08.2432265Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connection.py", line 168, in _new_conn
2019-08-30T12:03:08.2432550Z urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x04273EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
2019-08-30T12:03:08.2432736Z 
2019-08-30T12:03:08.2432939Z During handling of the above exception, another exception occurred:
2019-08-30T12:03:08.2433097Z 
2019-08-30T12:03:08.2433293Z Traceback (most recent call last):
2019-08-30T12:03:08.2433506Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\adapters.py", line 449, in send
2019-08-30T12:03:08.2433764Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\connectionpool.py", line 638, in urlopen
2019-08-30T12:03:08.2434027Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-q_27sn_r\urllib3\urllib3\util\retry.py", line 399, in increment
2019-08-30T12:03:08.2434539Z urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webappname.scm.asedomain.local', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04273EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2019-08-30T12:03:08.2435032Z 
2019-08-30T12:03:08.2435214Z During handling of the above exception, another exception occurred:
2019-08-30T12:03:08.2435698Z 
2019-08-30T12:03:08.2435840Z Traceback (most recent call last):
2019-08-30T12:03:08.2436092Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\knack\knack\cli.py", line 206, in invoke
2019-08-30T12:03:08.2436307Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
2019-08-30T12:03:08.2436543Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
2019-08-30T12:03:08.2437481Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
2019-08-30T12:03:08.2437713Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\six\six.py", line 693, in reraise
2019-08-30T12:03:08.2437937Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
2019-08-30T12:03:08.2438143Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
2019-08-30T12:03:08.2438525Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
2019-08-30T12:03:08.2438895Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli\azure\cli\command_modules\appservice\custom.py", line 325, in enable_zip_deploy
2019-08-30T12:03:08.2439114Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\api.py", line 116, in post
2019-08-30T12:03:08.2439378Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\api.py", line 60, in request
2019-08-30T12:03:08.2439570Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\sessions.py", line 533, in request
2019-08-30T12:03:08.2439926Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\sessions.py", line 646, in send
2019-08-30T12:03:08.2440299Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\requests\requests\adapters.py", line 516, in send
2019-08-30T12:03:08.2440823Z requests.exceptions.ConnectionError: HTTPSConnectionPool(host='webappname.scm.asedomain.local', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04273EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2019-08-30T12:03:08.2441243Z WARNING: 
2019-08-30T12:03:08.2441447Z To open an issue, please run: 'az feedback'
2019-08-30T12:03:08.3521214Z

**Comment by panchagnula** [comment]
The Zip Delployment command needs to talk to scm directly and due to the NSG rules on ILB ASE this will not work until you run the command from within the VNET.
