### ISSUE TITLE
Exception on launch of az interactive and then no command completion or suggestion

### ISSUE THREAD

**Issue by bodaduk** [Azure/azure-cli#10402]
**Describe the bug**
Exception on launch of az interactive and then no command completion or suggestion

**To Reproduce**
Install Azure CLI 2.0.72
run 'az interactive'

**Expected behavior**
No errors or exceptions on launching  az interactive and then command completion / suggestion

**Environment summary**
Install Method (MSI) on clean 1903 Windows 10 Ent run in PowerShell

azure-cli                         2.0.72

command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
interactive                        0.4.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\candidate\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**Comment by bodaduk** [comment]
Apologies, here is the exception:

PS C:\Users\candidate> az interactive
This command is in preview. It may be changed/removed in a future release.
az>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\candidate\.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "C:\Users\candidate\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)
  File "C:\Users\candidate\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 49, in load_arguments
    command.load_arguments()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\commands\__init__.py", line 290, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\commands.py", line 97, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\__init__.py", line 488, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\__init__.py", line 528, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module--------
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked----------------------------------------------------
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli\azure\cli\command_modules\apim\custom.py", line 9, in <module>-----------------------------------------------------------------------------------------------------
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
[cmd] + [param] +"??[query]": Inject jmespath query from previous command
az>>

**Comment by marcelboccato** [comment]
Same issue here...
