### ISSUE TITLE
[Component] az component update throws error but succeeds

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1049]
On a VM with the Ubuntu LTS image alias, running `az component update --additional-component iot` results in a stack trace:

```
Exception:
Traceback (most recent call last):
  File "/opt/az/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/az/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/opt/az/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/az/local/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/opt/az/lib/python2.7/site-packages/azure/__init__.py'
```

Running instead `sudo az component update --additional-component iot` I get the following:
```
Command "/opt/az/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SRJtuq/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" --no-user-cfg install --record /tmp/pip-9cQQXu-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/az/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-SRJtuq/cryptography/
```

However, after running with sudo, IoT is installed.

**Comment by derekbekoe** [comment]
Looks like it was an apt-get install and not on Mac.
The Permission Denied error is because you don't have permissions to run that command as the packages are installed in a global location, just like you had to do `sudo apt-get install azure-cli` in the first place.
I have created https://github.com/Azure/azure-cli/issues/1050 so that we don't show the full stacktrace.

@tjprescott: What OS/version did you try to run `sudo az component update --additional-component iot` on? I don't see the issue on Ubuntu 14:04

**Comment by tjprescott** [comment]
This was using the apt-get install with the UbuntuLTS image alias (which I believe is 14.04).
