### ISSUE TITLE
Cannot run az commands in powershell or cmd.exe after upgrade

### ISSUE THREAD

**Issue by BillMincey** [Azure/azure-cli#10580]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Cannot run az commands in powershell or cmd.exe after upgrade

**To Reproduce**
Install latest MSI
Run PowerShell as administrator
execute **az login**

receive this error:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli\azure\cli\__main__.py", line 13, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\__init__.py", line 20, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\knack\knack\preview.py", line 6, in <module>
ImportError: cannot import name 'StatusTag'

**Expected behavior**
Login to azure

**Environment summary**
Install Method: MSI 
CLI version (`az --version`) does not work - latest version from MSI download 
OS version: Win 10 Enterprise 1903 build 18362.356
Shell Type: Powershell and cmd.exe

**Additional context**

**Comment by jiasli** [comment]
Tested with a new Windows 10 Pro 1809 VM which runs CLI correctly. Please remove `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` and reinstall.
