### ISSUE TITLE
Error when getting ER connection list

### ISSUE THREAD

**Issue by sajitsasi** [Azure/azure-cli#10660]
## Describe the bug

**Command Name**
`az network express-route gateway connection show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'child_name_1'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 311, in parse_ids_arguments
    getattr(namespace, arg.name).append(parts[arg.type.settings['id_part']])
KeyError: 'child_name_1'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network express-route gateway connection show --ids {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.68 *

Extensions:
appconfig 0.5.0
azure-firewall 0.1.2
eventgrid 0.4.3
subscription 0.1.3
virtual-network-tap 0.1.0

```

**Comment by MyronFanQiu** [comment]
@sajitsasi Thanks. For this command we shouldn't expose `--ids`. We will fix it.
