### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by centiqmurphy** [Azure/azure-cli#10697]
## Describe the bug

**Command Name**
`az keyvault list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/mmurphy/.local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/mmurphy/.local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'unicode' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault list --verbose`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.74

```

**Comment by achandmsft** [comment]
Hi @centiqmurphy, Thanks for reporting this issue. An underlying error is probably being swallowed by a format mismatch. Could you please run the command with '--debug' and let us know what you get?

**Comment by centiqmurphy** [comment]
they error happened when running in azure cli that had been pip installed, reinstalling azure cli with apt removes issue and creates a new one.  
the current issue i get when runnning the same code is "'str' object has no attribute 'get'". this code runs fine on others running the same wsl enviroment

**Comment by centiqmurphy** [comment]
unexpected token at 'ERROR: The command failed with an unexpected error. Here is the traceback:

      ERROR: 'str' object has no attribute 'get'
      Traceback (most recent call last):
        File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
          cmd_result = self.invocation.execute(args)
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
          raise ex
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
          results.append(self._run_job(expanded_arg, cmd_copy))
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
          six.reraise(*sys.exc_info())
        File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
          raise value
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 601, in _run_job
          result = list(result)
        File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
          self.advance_page()
        File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
          self._response = self._get_next(self.next_link)
        File "/opt/az/lib/python3.6/site-packages/azure/mgmt/network/v2019_02_01/operations/virtual_networks_operations.py", line 504, in internal_paging
          response = self._client.send(request, stream=False, **operation_config)
        File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
          pipeline_response = self.config.pipeline.run(request, **kwargs)
        File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
          return first_node.send(pipeline_request, **kwargs)  # type: ignore
        File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
          response = self.next.send(request, **kwargs)
        File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
          self._creds.signed_session(session)
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
          scheme, token, _ = self._token_retriever()
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 539, in _retrieve_token
          use_cert_sn_issuer)
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 915, in retrieve_token_for_service_principal
          self.load_adal_token_cache()
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 944, in load_adal_token_cache
          self._load_service_principal_creds(all_entries)
        File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 971, in _load_service_principal_creds
          if c.get(_SERVICE_PRINCIPAL_ID):
      AttributeError: 'str' object has no attribute 'get'
      WARNING:
      To open an issue, please run: 'az feedback'
      ' (JSON::ParserError)

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
First, from the call stack, it doesn't seem to be a keyvault command, but vnet:
```
File "/opt/az/lib/python3.6/site-packages/azure/mgmt/network/v2019_02_01/operations/virtual_networks_operations.py", line 504, in internal_paging
response = self._client.send(request, stream=False, **operation_config)
```

Please share the full command that results in this error. 

Second, it looks like `~\.azure\accessTokens.json` is corrupted, that's why json fails to parse it. The correct format is:

```json
[
    {
        "servicePrincipalId": "4750d6b9-xxxx-xxxx-xxxx-88b0862f55b9",
        "servicePrincipalTenant": "",
        "accessToken": ""
    }
]
```

Please clear the access token and re-login:

```
az account clear
az login
```

**Comment by yonzhan** [comment]
Solution provided
