### ISSUE TITLE
CI: travis task of 'Integration for profiles' is failing

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#10721]
I am disabling this task, meanwhile let us investigate for the root cause 
Note, we have 2 tasks on this. Python 2.7 one works; while 3.6 is failing
```
az cloud list-profiles -otsv
azdev verify package $share_folder/build/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('six==1.12'), {'astroid'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/azdev", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('six==1.12'), {'astroid'})
The command "./scripts/ci/test_profile_integration.sh" exited with 1.
cache.2
store build cache
```

**Comment by fengzhou-msft** [comment]
will look into details next week after national holidays

**Comment by fengzhou-msft** [comment]
Based on the message `pkg_resources.ContextualVersionConflict: (six 1.11.0 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('six==1.12'), {'astroid'})`, it seems six 1.11.0 was installed on the machine but the requirements file needs six==1.12.

**Comment by fengzhou-msft** [comment]
Why previous builds succeed and recent builds fail?
Previously when running `pip install $ALL_MODULES`, [azure-cli is installed before azure-cli-core](https://travis-ci.org/Azure/azure-cli/jobs/591298798#L875), and recently [the order reversed](https://travis-ci.org/Azure/azure-cli/jobs/592562968#L875). [azure-cli requires `six~=1.12` ](https://github.com/Azure/azure-cli/blob/84d81aee7f5bfe0264561203429f4131960bc625/src/azure-cli/setup.py#L145) while [azure-cli-core only requires `six`](https://github.com/Azure/azure-cli/blob/84d81aee7f5bfe0264561203429f4131960bc625/src/azure-cli-core/setup.py#L70). The version of the dependency to be installed seems to be determined by the the first setup.py when install(needs to verify). Since six 1.11.0 is already installed, it meets `six` and six 1.12.0 will not be installed for recent builds.
