### ISSUE TITLE
AZ Logging status check not working

### ISSUE THREAD

**Issue by C4P-KorbenDallas** [Azure/azure-cli#10759]
## Describe the bug

**Command Name**
`az storage logging show`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='azcgfingestion.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0541E510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0541E510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='azcgfingestion.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0541E510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 269, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_http\httpclient.py", line 92, in perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='azcgfingestion.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0541E510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 375, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\arm.py", line 744, in show_exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\operations\logging.py", line 15, in get_logging
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\services_wrapper.py", line 29, in get_logging
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\queue\queueservice.py", line 372, in get_queue_service_properties
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 311, in _perform_request
azure.common.AzureException: HTTPSConnectionPool(host='azcgfingestion.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0541E510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az storage logging show --account-name {} --account-key {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62 *

```

**Comment by Juliehzl** [comment]
Hi @C4P-KorbenDallas, can you check the supported storage service of your storage account type? I think that maybe your storage account don't support queue service, therefore you cannot query from azcgfingestion.queue.core.windows.net. But here blob, queue and table host will be query by default,  and you can use `--services` to define the storage services you want to retrieve logging.

**Comment by C4P-KorbenDallas** [comment]
Hi @Juliehzl 

Well, if that's the reason then I would expect that message to be returned by that command, when i execute it, it hangs and no response.

When i add "--services b" to the command, it works and returns :
{
  "blob": {
    "delete": true,
    "read": true,
    "retentionPolicy": {
      "days": 7,
      "enabled": true
    },
    "version": "1.0",
    "write": true
  }
}

is thatthe logging settings for a storage account?

**Comment by Juliehzl** [comment]
@C4P-KorbenDallas Yes. We will improve the error message to give user the right guide.
