### ISSUE TITLE
Bug: `az account show` or`az account set --help` give `tuple index out of range`

### ISSUE THREAD

**Issue by peterchoo** [Azure/azure-cli#10803]
## Describe the bug

**Command Name**
`az account show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


tuple index out of range
Traceback (most recent call last):
  File "/home/pchoo/.local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/pchoo/.local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 527, in execute
    self.parser.load_command_table(self.commands_loader)
  File "/home/pchoo/.local/lib/python2.7/site-packages/azure/cli/core/parser.py", line 118, in load_command_table
    command_name, ex.args[0].dest, ex.message))  # pylint: disable=no-member
IndexError: tuple index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account show --debug`

## Environment Summary
```
Linux-5.0.0-31-generic-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.15+
Shell: bash

azure-cli 2.0.65 *

```
## Additional Context

azure-cli installed via pip: `pip install azure-cli==2.0.65 --user`

**Comment by haroldrandom** [comment]
Sorry, I **cannot** reproduce the situation under the same environment you are in.

Have you tried a newer version of azure-cli ? Or help me with more information.

**Comment by peterchoo** [comment]
I thought I had included it in the issue, I installed the `azure-cli` through `pip`.

My intention was to be able to create a virtualenv containing certain versions of tools related to specific customer projects.

I have since re-installed the `azure-cli` through `apt` following [these instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions), but with `sudo apt install azure-cli=2.0.65-1~bionic` and I no-longer receive this issue.

**Comment by haroldrandom** [comment]
@peterchoo Thanks for updating Additional Context in the autogenerated. That's the critical step I missed to reproduce your situation.

Now I tried 2.0.66, 2.0.67, 2.0.68, 2.0.69, 2.0.70  in the same environment:
 
- Linux-5.0.0-31-generic-x86_64-with-Ubuntu-18.04-bionic
- Python 2.7.15+
- Shell: bash

And the problem you report disappeared.

So, I would suggest you upgrade a newer version of azure-cli in your environment.

The bug seems weird and related to the packaging. But if the version is your insistence, we will dig into it.
For now, I would suggest you to try a newer version such that can keep you move on.

**Comment by fengzhou-msft** [comment]
I can reproduce the bug with 2.0.65, but not with latest 2.0.74. This could be a bug that was fixed in later versions after 2.0.65. Not an issue with packaging, I'm going to unassign with myself.

**Comment by fengzhou-msft** [comment]
The stacktrace was misleading because it's the info for an exception inside exception handler caused by `ex.args[0].dest`. The real stacktrace for the issue is :
```
Traceback (most recent call last):                                                                                                                                                                                      
File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/parser.py", line 118, in load_command_table                                                                                                                 
param = AzCliCommandParser._add_argument(command_parser, arg)                                                                                                                                                       
File "/usr/local/lib/python2.7/dist-packages/knack/parser.py", line 65, in _add_argument                                                                                                                                
return obj.add_argument(*scrubbed_options_list, **argparse_options)                                                                                                                                                 
File "/usr/lib/python2.7/argparse.py", line 1312, in add_argument                                                                                                                                                       
return self._add_action(action)                                                                                                                                                                                     
File "/usr/lib/python2.7/argparse.py", line 1686, in _add_action                                                                                                                                                        
self._optionals._add_action(action)                                                                                                                                                                                 
File "/usr/lib/python2.7/argparse.py", line 1513, in _add_action                                                                                                                                                        
action = super(_ArgumentGroup, self)._add_action(action)                                                                                                                                                            
File "/usr/lib/python2.7/argparse.py", line 1326, in _add_action                                                                                                                                                        
self._check_conflict(action)                                                                                                                                                                                        
File "/usr/lib/python2.7/argparse.py", line 1464, in _check_conflict                                                                                                                                                    
conflict_handler(action, confl_optionals)                                                                                                                                                                           
File "/usr/lib/python2.7/argparse.py", line 1471, in _handle_conflict_error                                                                                                                                             
raise ArgumentError(action, message % conflict_string)                                                                                                                                                            
**ArgumentError: argument --subscription: conflicting option string(s): --subscription**
```
After debugging, the options passed in is:
```
[('show_auth_for_sdk', <knack.arguments.CLICommandArgument object at 0x7f5ec3e4bf90>), 
('_subscription', <knack.arguments.CLICommandArgument object at 0x7f5ec3e9f690>), 
('cmd', <knack.arguments.CLICommandArgument object at 0x7f5ec3e4bd10>), 
('subscription', <knack.arguments.CLICommandArgument object at 0x7f5ec3e4bf10>)]
```

**Comment by peterchoo** [comment]
Thanks for looking into it.  For my purposes, I will just have to manually manage which version is installed when working with a particular project.  I will at some point investigate updating the CLI version with this project, but for now it has to remain version-locked.

**Comment by yonzhan** [comment]
@peterchoo Was this issue resolved ?

**Comment by peterchoo** [comment]
@yonzhan I think the [response](https://github.com/Azure/azure-cli/issues/10803#issuecomment-542085605) from @fengzhou-msft has shown that there wont be a readily available method for installing the version our project is currently tied to via PIP.  We will either look at bumping up a single version or just live with installing via OS native package manager.

I don't think it is worth looking at any further. Thank you!
