### ISSUE TITLE
ERROR: The command failed with an unexpected error. Here is the traceback:

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/azure-cli#10804]
**Describe the bug**
When running the az aks get-credentials command from an azure devops agent we get error:
```
2019-10-10T14:33:26.1661711Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-10-10T14:33:26.1661972Z 
2019-10-10T14:33:26.1682228Z ERROR: 'users'
2019-10-10T14:33:26.1682400Z Traceback (most recent call last):
2019-10-10T14:33:26.1682791Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2019-10-10T14:33:26.1682838Z     cmd_result = self.invocation.execute(args)
2019-10-10T14:33:26.1683102Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
2019-10-10T14:33:26.1683204Z     raise ex
2019-10-10T14:33:26.1683641Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
2019-10-10T14:33:26.1683999Z     results.append(self._run_job(expanded_arg, cmd_copy))
2019-10-10T14:33:26.1684278Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
2019-10-10T14:33:26.1684429Z     six.reraise(*sys.exc_info())
2019-10-10T14:33:26.1684659Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2019-10-10T14:33:26.1684700Z     raise value
2019-10-10T14:33:26.1684993Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
2019-10-10T14:33:26.1685038Z     result = cmd_copy(params)
2019-10-10T14:33:26.1685469Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
2019-10-10T14:33:26.1685511Z     return self.handler(*args, **kwargs)
2019-10-10T14:33:26.1686193Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
2019-10-10T14:33:26.1686240Z     return op(**command_args)
2019-10-10T14:33:26.1686543Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1887, in aks_get_credentials
2019-10-10T14:33:26.1686638Z     _print_or_merge_credentials(path, kubeconfig, overwrite_existing, context_name)
2019-10-10T14:33:26.1686925Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2775, in _print_or_merge_credentials
2019-10-10T14:33:26.1686973Z     merge_kubernetes_configurations(path, temp_path, overwrite_existing, context_name)
2019-10-10T14:33:26.1687256Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1178, in merge_kubernetes_configurations
2019-10-10T14:33:26.1687531Z     _handle_merge(existing, addition, 'users', replace)
2019-10-10T14:33:26.1687804Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1112, in _handle_merge
2019-10-10T14:33:26.1687895Z     if existing[key] is None:
2019-10-10T14:33:26.1688097Z KeyError: 'users'
2019-10-10T14:33:26.1688147Z WARNING: 
2019-10-10T14:33:26.1688349Z To open an issue, please run: 'az feedback'
2019-10-10T14:33:26.3028463Z ##[error]Bash exited with code '1'.
```

**To Reproduce**
Steps to reproduce the behavior.
az login
az aks get-credentials --resource-group $RG --name $NAME --overwrite-existing

**Expected behavior**
I would expect that the config file is correctly downloaded

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
azure-cli version: 2.0.74
OS: ubunt 16.04
shell type: bash
install method: apt-get

**Additional context**
When I run the command locally it works fine. And when logging into the azure devops agent (kubectl exec) and running the command it also works.
Don't know if itt is a combination of the az cli and azure devops maybe.

**Comment by bramvdklinkenberg** [comment]
Some extra info: I run the same script in Azure Devops on 4 different environment. 1 or 2 out of 4 it fails. It is on random environments that it fails.
And again when I run it locally on my macbook it works fine all the time, and when directly executing it in the pod myself it works as well. 
It's a weird issue and hard to troubleshoot and say it is the cli, or it is aks or azure devops..

**Comment by bramvdklinkenberg** [comment]
See #10812
