### ISSUE TITLE
az webapp up fails with AttributeError 'NoneType' object has no attribute 'resource_group'

### ISSUE THREAD

**Issue by nnja** [Azure/azure-cli#10818]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**

Get an error saying `Webapp NAME already exits. The command will deploy contents to the existing app` even though the web app with this name **does not exist**

```
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 485, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 2793, in webapp_up
    current_rg = app_details.resource_group
AttributeError: 'NoneType' object has no attribute 'resource_group'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up` or `az webapp up -n` or `az webapp up -n -g`

## Expected Behavior

A new web app with the given name is created.

## Environment Summary
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74

Extensions:
db-up 0.1.13

```
## Additional Context

See related:
- [**https://github.com/Azure/azure-cli/issues/10802**](https://github.com/Azure/azure-cli/issues/10802)
- [**https://github.com/Azure/azure-cli/issues/10713**](https://github.com/Azure/azure-cli/issues/10713)

**Comment by nnja** [comment]
@panchagnula confirmed that upgrading the cli resolved this particular issue

```
$ az --version
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
db-up                             0.1.13
```

**Comment by leestott** [comment]
Hi So the site https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update on still has 2.0.74 

The latest update to 2.0.75 is available from this site https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update

**Comment by sonnehansen** [comment]
Hi, 
I encounter the same issue also with azure-cli 2.0.75:
```
$ az --version
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4
```



Following your [example](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python), I get:
```
/python-docs-hello-world$ az webapp up -n Hello
Webapp Hello already exits. The command will deploy contents to the existing app
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2793, in webapp_up
    current_rg = app_details.resource_group
AttributeError: 'NoneType' object has no attribute 'resource_group' 
```

I am using WSL  (Windows 10 v 1709) with Ubuntu 18.04.

**Comment by jamesallen74** [comment]
Same issue with azure-cli 2.0.76 using a sandbox on this tutorial

https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service?pivots=csharp

I am trying the run the az webapp up command as well, with parameters of course.

az --version says 2.0.76 and that I have the latest

**Comment by TheEngineeringAlgorist** [comment]
> Same issue with azure-cli 2.0.76 using a sandbox on this tutorial
> 
> https://docs.microsoft.com/en-us/learn/modules/host-a-web-app-with-azure-app-service/6-exercise-deploy-your-code-to-app-service?pivots=csharp
> 
> I am trying the run the az webapp up command as well, with parameters of course.
> 
> az --version says 2.0.76 and that I have the latest

I created a new ticket here:

https://github.com/Azure/azure-cli/issues/11089

**Comment by baddevotions** [comment]
same issue here: step 2:

https://docs.microsoft.com/en-gb/learn/modules/develop-app-that-queries-azure-sql/5-exercise-connect-aspnet-to-azure-sql

**Comment by JumaSudo** [comment]
Same...

> @Azure:~/contoso-pets/src/ContosoPets.Ui$ az webapp up
Webapp webapp238173089 already exists. The command will deploy contents to the existing app.
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55,in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2993,in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1390,in create_app_service_plan
    sku = _normalize_sku(sku)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 20, in_normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

To open an issue, please run: 'az feedback'
