### ISSUE TITLE
Error encountered when Issuing az interactive command on PS or CMD

### ISSUE THREAD

**Issue by bahreex** [Azure/azure-cli#10816]
## Describe the bug
Error encountered when Issuing az interactive command on PS or CMD. I have tried on multiple machines. The error is as shown in the screenshot attached from PS Console.

**Command Name**
`az interactive`

**Errors:**

 PS>az interactive                                                                                                    This command is in preview. It may be changed/removed in a future release.
az>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Bahree\.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "C:\Users\Bahree\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)-----------------------------------------------------------------------------------
  File "C:\Users\Bahree\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 49, in load_arguments-----------------------------------------------------------------------------------------------------------
    command.load_arguments()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 291, in load_arguments  : use commands outside the application
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\commands.py", line 97, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 488, in default_arguments_loader : do a step by step tutorial of example
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 528, in get_op_handler           : set a scope, and scopes can be chained with spaces
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                Hit [enter] to refresh
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli\azure\cli\command_modules\apim\custom.py", line 9, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74

Extensions:
interactive 0.4.3
resource-graph 1.0.0

```
## Additional Context

![image](https://user-images.githubusercontent.com/5578341/66665906-1df9a080-ec6d-11e9-9655-342a7495a899.png)

**Comment by yonzhan** [comment]
@jiasli  please take a look.

**Comment by jiasli** [comment]
This issue is already addressed. If it still happens, please let us know.
