### ISSUE TITLE
After running one-command Ubuntu install, CLI fails with Python module error

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-cli#10920]
**Describe the bug**
I ran the one-command install from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest on Ubuntu Bionic.  The install appeared to succeed, but when I then ran the `az` command it failed with a Python module load error.  The last few lines of the load error (full stack trace below) were:

```
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**To Reproduce**
1. Create an Ubuntu Bionic virtual machine on Windows 10.
2. Run `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`
3. Run `az --version`

**Expected behavior**
Should print `2.0.75` and component version info.

**Environment summary**
Install Method: See repro steps above
OS version: Ubuntu 18.04.2 LTS running in a VM
Shell Type: bash
Also has Python 2.7.15 installed
**NOTE:** I tried running `az feedback` but it failed with the same error

**Additional context**
Terminal output:

```
itowlson@itowlson-ubuntu1604desktop:~$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
apt-get update
Hit:1 http://nz.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://nz.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:3 http://nz.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease              
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Reading package lists... Done
apt-get install -y apt-transport-https lsb-release gnupg curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lsb-release is already the newest version (9.20170808ubuntu1).
curl is already the newest version (7.58.0-2ubuntu3.8).
gnupg is already the newest version (2.2.4-1ubuntu1.2).
apt-transport-https is already the newest version (1.6.12).
0 upgraded, 0 newly installed, 0 to remove and 164 not upgraded.
set +v
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg
gpg: WARNING: unsafe ownership on homedir '/home/itowlson/.gnupg'
set +v
CLI_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" \
    > /etc/apt/sources.list.d/azure-cli.list
apt-get update
Hit:1 http://nz.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://nz.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:3 http://packages.microsoft.com/repos/vscode stable InRelease              
Hit:4 http://nz.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Get:5 https://packages.microsoft.com/repos/azure-cli bionic InRelease [3,944 B]
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Get:7 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages [7,106 B]
Fetched 11.1 kB in 1s (13.0 kB/s)
Reading package lists... Done
set +v
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 164 not upgraded.
Need to get 0 B/45.5 MB of archives.
After this operation, 453 MB of additional disk space will be used.
Selecting previously unselected package azure-cli.
(Reading database ... 243044 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.0.75-1~bionic_all.deb ...
Unpacking azure-cli (2.0.75-1~bionic) ...
Setting up azure-cli (2.0.75-1~bionic) ...

itowlson@itowlson-ubuntu1604desktop:~$ az --version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/itowlson/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/home/itowlson/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 9, in <module>
    from azure.cli.core import configure_logging, get_az_logger
  File "/home/itowlson/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 11, in <module>
    from .azlogging import get_az_logger, configure_logging
  File "/home/itowlson/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/azlogging.py", line 28, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by itowlson** [comment]
I tracked down the problem.  There was an existing file named `az` with the executable bit in my `~/bin` directory, which was taking precedence over the installed Azure CLI.  Removing this file and restarting the shell fixed the problem.  Apologies for the false alarm.
