### ISSUE TITLE
The latest "interactive" extension (0.4.3) outputs an error in the latest CLI (2.0.75)

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-cli#10933]
**Command Name**
`az interactive`

**Errors:**
```
az>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
...
```

## To Reproduce:
Just run `az interactive`.

## Expected Behavior
Interactive mode should start without errors.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

Extensions:
azure-devops 0.13.0
interactive 0.4.3
resource-graph 1.0.0

```

**Comment by yonzhan** [comment]
@jiasli this is an issue raised by Aleksandar. Please take a look.

**Comment by jiasli** [comment]
The most inner error is `ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'`. @zikalino, could you take a look at this packaging issue?

**Comment by marckassay** [comment]
Just a moment ago, I executed `az interactive` for the first time and received the following:
```
E:\> az interactive
This command is in preview. It may be changed/removed in a future release.
Installing the Interactive extension...
The installed extension 'interactive' is in preview.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\interactive\custom.py", line 41, in start_shell
  File "C:\Users\marck\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "C:\Users\marck\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

To open an issue, please run: 'az feedback'
```
```
E:\> az --version
azure-cli                         2.0.70 *

command-modules-nspkg               2.0.3
core                              2.0.70 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Extensions:
interactive                        0.4.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\marck\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 updates available. Consider updating your CLI installation.
```

I attempted to upgrade but the Azure CLI wizard failed doing so.

**Comment by yonzhan** [comment]
@fengzhou-msft to take a look.

**Comment by fengzhou-msft** [comment]
should be fixed with https://github.com/Azure/azure-cli/pull/10623, will release with next version (scheduled next week).
