### ISSUE TITLE
az login --identity : The command failed with an unexpected error.

### ISSUE THREAD

**Issue by Abdelkrim** [Azure/azure-cli#10998]
## Describe the bug

**Command Name**
`az login --identity`

**Errors:**

The command failed with an unexpected error. Here is the traceback:

HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DB5B10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\util\connection.py", line 80, in create_connection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\util\connection.py", line 70, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connectionpool.py", line 354, in _make_request
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connection.py", line 181, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x04DB5B10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2bnqpf73\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DB5B10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli\azure\cli\command_modules\profile\custom.py", line 125, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\_profile.py", line 326, in find_subscriptions_in_vm_with_msi
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\msrestazure\msrestazure\azure_active_directory.py", line 592, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\msrestazure\msrestazure\azure_active_directory.py", line 600, in set_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\msrestazure\msrestazure\azure_active_directory.py", line 649, in get_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\msrestazure\msrestazure\azure_active_directory.py", line 685, in _retrieve_token_from_imds_with_retry
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DB5B10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.75

```

**Comment by jiasli** [comment]
Where is the command being executed, a local machine or VM? `169.254.169.254` is only for VM's [managed identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview). To use `az` locally, run `az login`.

**Comment by Abdelkrim** [comment]
@jiasli the command was executed on a local machine

**Comment by jiasli** [comment]
Managed identity can only be used on Azure resources, such as VM, App Service. See: https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview

`169.254.169.254` is the Azure Instance Metadata Service (IMDS) endpoint which is only available on Azure resources. See https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http. It is not available on a local machine, so you can't use managed identity on a local machine.

To sign in Azure CLI on a local machine, you need to use user or service principal account:

- User: https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively
- Service principal: https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-service-principal
