### ISSUE TITLE
az webapp: zip deployment fails for app service on linux

### ISSUE THREAD

**Issue by rick-hayek** [Azure/azure-cli#11024]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip --name myappname --resource-group mygroup --src myzipfile --slot Staging`

**Errors:**
2019-10-29T15:11:51.1449664Z WARNING: Getting scm site credentials for zip deployment
2019-10-29T15:11:53.0219789Z WARNING: Starting zip deployment. This operation can take a while to complete ...
2019-10-29T15:11:58.8718918Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-10-29T15:11:58.8719286Z 
2019-10-29T15:11:58.9040656Z ERROR: Expecting value: line 1 column 1 (char 0)
2019-10-29T15:11:58.9040907Z Traceback (most recent call last):
2019-10-29T15:11:58.9041431Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 206, in invoke
2019-10-29T15:11:58.9042107Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
2019-10-29T15:11:58.9042589Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
2019-10-29T15:11:58.9043160Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
2019-10-29T15:11:58.9043587Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\six\six.py", line 693, in reraise
2019-10-29T15:11:58.9044016Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
2019-10-29T15:11:58.9044463Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
2019-10-29T15:11:58.9045006Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
2019-10-29T15:11:58.9045485Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli\azure\cli\command_modules\appservice\custom.py", line 353, in enable_zip_deploy
2019-10-29T15:11:58.9049123Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2356, in _check_zip_deployment_status
2019-10-29T15:11:58.9049324Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\requests\requests\models.py", line 889, in json
2019-10-29T15:11:58.9049465Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 354, in loads
2019-10-29T15:11:58.9049560Z     return _default_decoder.decode(s)
2019-10-29T15:11:58.9049682Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
2019-10-29T15:11:58.9049776Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-10-29T15:11:58.9049925Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 357, in raw_decode
2019-10-29T15:11:58.9050027Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2019-10-29T15:11:58.9050160Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-10-29T15:11:58.9050240Z WARNING: 
2019-10-29T15:11:58.9050334Z To open an issue, please run: 'az feedback'

## To Reproduce:
I'm trying to deploy azure web app via zip deployment. 
I'm running the powershell script on azure devops. this error does not occur every deployment, but i did see it very often. usually I did a redeployment to solve the failure, but you may want to look into it

- _Put any pre-requisite steps here..._

## Environment Summary
```
The pipeline agent is Azure Pipelines Hosted VS2017 image. here's some version information you may need:
Powershell Core
Version: 6.2.2
Azure CLI
Version: 2.0.71


```

**Comment by Juliehzl** [comment]
cc @AzureAppServiceCLI @antcp

**Comment by panchagnula** [comment]
Can you please re-try & let us know if this still repros? thank you.

**Comment by panchagnula** [comment]
Please reopen if this is still an issue. Thanks!

**Comment by AhmedFujitsu** [comment]
Hello i have a problem in Azure CLI Shell
when i try to execute the command line  az webapp up \
>     --resource-group learn-c08c2760-4c68-4a1e-8384-60e02b1c0458 \
>     --sku F1 \
>     --name $WEBAPPNAME i recieved this error can some help me please
The command failed with an unexpected error. Here is the traceback:

[Errno 2] No such file or directory: '/home/ahmed_kamalet/CoursesWebApp.csproj'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2914, in webapp_up
    os_name = detect_os_form_src(src_dir)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 340, in detect_os_form_src
    lang_details = get_lang_from_content(src_dir)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 145, in get_lang_from_content
    runtime_lang = detect_dotnet_lang(package_netcore_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 159, in detect_dotnet_lang
    parsed_file = ET.parse(csproj_path)
  File "/opt/az/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/opt/az/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ahmed_kamalet/CoursesWebApp.csproj'
