### ISSUE TITLE
Extension install fails with Python 3.8

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#11041]
Code causing issue:
https://github.com/Azure/azure-cli/blob/adfa863776a58dee4a00dd1c8580f9baa9ec157a/src/azure-cli-core/azure/cli/core/_session.py#L46

Failure Stack:
[command]/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/runner/runners/2.159.2/work/_temp/933db641-54e8-49de-b9c3-3cd06c29c07c.ps1'
installing  /Users/runner/runners/2.159.2/work/1/a/extension/azure-devops-cli-extension/azure_devops-0.14.0-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 546, in get_default_cli
    return AzCli(cli_name='az',
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/Users/runner/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/azure/cli/core/_session.py", line 46, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'

Failure can be seem at:
https://dev.azure.com/ms/azure-devops-cli-extension/_build/results?buildId=45473

Helpful link:
https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8

**Comment by jiasli** [comment]
This is known issue. We are adding Python 3.8 support: https://github.com/Azure/azure-cli/pull/10777

**Comment by jiasli** [comment]
We have fixed this issue by adding Python 3.8 support: #10777

**Comment by olivierchatry** [comment]
Would be nice to release a version quickly with this fix if possible.
