### ISSUE TITLE
unable to create role assignment using aad group object id

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#11081]
## Describe the bug

**Command Name**
``` bash
contributor_object_id="26adae4e-4a0f-4ba6-957e-2fb700793da2"
SCOPE_ID="subscriptions/f921dcc4-9d2c-4b73-a12e-8c3ca091af03/resourceGroups/sace-dev-rg/providers/Microsoft.Insights/components/sace-dev-ai"

az role assignment create --role Contributor --assignee-object-id $contributor_object_id --scope $SCOPE_ID
```

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

list index out of range
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 141, in create_role_assignment
    assignee_principal_type=assignee_principal_type)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 160, in _create_role_assignment
    assignee_principal_type)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/_multi_api_adaptor.py", line 54, in create_role_assignment
    return client.create(scope, assignment_name, parameters)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/mgmt/authorization/v2018_09_01_preview/operations/role_assignments_operations.py", line 327, in create
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: RoleAssignmentExists
Message: The role assignment already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.75/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 144, in create_role_assignment
    return list_role_assignments(cmd, assignee, role, resource_group_name, scope)[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment create --role {} --assignee-object-id {} --scope {}`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.75

Extensions:
dev-spaces 1.0.3
application-insights 0.1.1

```
## Additional Context

NOTE:
when I list assignment, it's empty

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by yonzhan** [comment]
add to S169

**Comment by qianwens** [comment]
@smartpcr I can not repro your issue with latest Az CLI. Could you please help run your command with --debug and provide the output to us for further investigation?

**Comment by yonzhan** [comment]
@smartpcr any update?
