### ISSUE TITLE
Mariadb Server Log Download Error when Download come closer to 38 Mb

### ISSUE THREAD

**Issue by leocamar** [Azure/azure-cli#11119]
## Describe the bug

**Command Name**
`az mariadb server-logs download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/custom.py", line 392, in _download_log_files
    urlretrieve(f.url, f.name)
  File "/opt/az/lib/python3.6/urllib/request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "/opt/az/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/opt/az/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/opt/az/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/az/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/az/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/opt/az/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Log file must be greater than 50 Mb_
- `az mariadb server-logs download --name {} --resource-group {} --server {}`

## Environment Summary
```
Linux-5.0.0-1023-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by navba-MSFT** [comment]
@leocamar Apologies for the late reply. Could you please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the CLI and try to run the same command again ? More Info [here](https://docs.microsoft.com/en-us/cli/azure/mariadb/server-logs?view=azure-cli-latest#az-mariadb-server-logs-download).

This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@leocamar This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by leocamar** [comment]
I don’t have this issue anymore.
