### ISSUE TITLE
az apim list Fails

### ISSUE THREAD

**Issue by AshWilliams** [Azure/azure-cli#11164]
## Describe the bug

**Command Name**
`az apim list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\__init__.py", line 292, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\apim\__init__.py", line 28, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\apim\_params.py", line 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76

Extensions:
aks-preview 0.4.18
azure-devops 0.12.0

```

**Comment by srikanthnd** [comment]
I get the same exact error message.  At first I thought may be this is in preview, but it is not. Actually, not only az apim list, basically any command throws the same exception.

![image](https://user-images.githubusercontent.com/9609176/68867222-c334e800-06f5-11ea-9f51-3e5ef36ed5e9.png)

**Comment by PramodValavala-MSFT** [comment]
@AshWilliams Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
