### ISSUE TITLE
az backup protection backup-now targeting Azure VM fails with error "argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by rejectshop-dgilbert** [Azure/azure-cli#11179]
## Describe the bug

**Command Name**
`az backup protection backup-now`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az account set --subscription {}`
- `az backup protection backup-now --debug --resource-group {} --vault-name {} --item-name {} --retain-until {}`

## Expected Behavior

azure-cli initiates snapshot & vault of VM identified by --item-name parameter.

## Environment Summary
```
Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.76

```

**Comment by Raghuveer-Yadav-Gadula** [comment]
faced a similar issue pasting the logs in here
PS C:\Users\v-ragya> az backup protection backup-now --resource-group att-test --vault-name att-vault --item-name ubuntu --retain-until 14-01-2019
az : Command group 'backup' is in preview. It may be changed/removed in a future release.
At line:1 char:1
+ az backup protection backup-now --resource-group att-test --vault-nam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Command group '...future release.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\__init__.py", line 487, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\backup\custom_base.py", line 85, in backup_now
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\backup\custom_base.py", line 43, in show_item
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\backup\custom_common.py", line 48, in show_item
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\backup\custom_help.py", line 350, in 
validate_and_extract_container_type
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\backup\custom_help.py", line 41, in 
is_native_name
TypeError: argument of type 'NoneType' is not iterable
WARNING: 
To open an issue, please run: 'az feedback'

**Comment by sambitratha** [comment]
Can you please try using the same command with 2 additional parameters --container-name and --backup-management-type i.e.
~~~
az backup protection backup-now --resource-group {} --vault-name {} --container-name {} --item-name {} --backup-management-type {}
~~~

PS You can also avoid having to use --backup-management-type parameter by giving full container name 

Hope this helps, Thanks

**Comment by Raghuveer-Yadav-Gadula** [comment]
Thanks Sambit for the reply, but i was able to figure out the root cause for the error,  and also the 'backup' in azure is still in preview mode the error exists.
When i try a different command it did go through successfully. below the is the 

> `az backup protection backup-now --backup-management-type AzureIaasVM --resource-group att-test --vault-name att-vault --container-name ubuntu --item-name ubuntu --retain-until 31-12-2019```

didn't get the time to update this thread though:)

**Comment by rejectshop-dgilbert** [comment]
> Can you please try using the same command with 2 additional parameters --container-name and --backup-management-type i.e.
> 
> ```
> az backup protection backup-now --resource-group {} --vault-name {} --container-name {} --item-name {} --backup-management-type {}
> ```
> 
> PS You can also avoid having to use --backup-management-type parameter by giving full container name
> 
> Hope this helps, Thanks

Can confirm that adding --container-name _{full container name}_ is a successful work-around.

**Comment by Raghuveer-Yadav-Gadula** [comment]
@rejectshop-dgilbert thanks for the reply,  the root cause for the failure for my case likely that i didn't mention the --backup-management type , container name and the retention date(the retention date works in conjunction with the subscription end date as well). 

Since i'm no longer having the subscription handy, wouldn't be able to re-pro the same, will have to give a try later.

but a further read is available at [https://docs.microsoft.com/en-us/cli/azure/backup/policy?view=azure-cli-latest#az-backup-policy-create]

makes sense that  --container-name parameter value could be the deciding factor, but again per the above KB link it's also coupled with --backup-management type

PS: az backup cli is till preview stage ,so it is expected to be buggy intially:)

**Comment by pvrk** [comment]
If container name if friendly user-name, then backup management type is required. There is container-full-name also given as part of container list response. If that is given, backup management type is not required.

**Comment by Raghuveer-Yadav-Gadula** [comment]
@pvrk if you see the previous comments by @sambitratha , similart and i  replied the same to it
