### ISSUE TITLE
Cannot create eventgrid subscription

### ISSUE THREAD

**Issue by iocuydi** [Azure/azure-cli#11176]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.76

Hello, I'm trying to deploy an azure function that responds to blob uploads via eventgrid as specified here:  https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#azure-cli
I'm doing this by creating an event grid subscription.
I can successfully create an eventgrid functionapp, using az functionapp create. Next I need to create an eventgrid subscription using az eventgrid event-subscription create. This requires an argument "endpoint" which needs a system key. How can I get this system key programmatically? I'd like to do this either using some sdk, or the azure cli.
I have tried two method so far:
**To Reproduce**
Method 1: Rest call to get system key
SUB=/subscriptions/<MY_SUB>/resourceGroups/<MY_RG>/providers/Microsoft.Web/sites/<MY_FUNC>

az rest --method post --uri "<SUB>/host/default/listKeys?api-version=2018-11-01" --query systemKeys.eventgrid_extension --output tsv

This command always fails with the following error:
Bad Request({"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null})
Method 2: Kudu management API

I've tried using the "getEventGridExtensionKey" method listed here:  https://github.com/paolosalvatori/blob-event-grid-function-app#scripts
this command always fails with the following error:
Invoke-WebRequest : A positional parameter cannot be found that accepts argument '--user'.

Any help with either of these, or alternative suggestions, would be greatly appreciated. Thanks!

**Expected behavior**
I would like to somehow be able to create an eventgrid subscription via azure cli.

**Environment summary**
I've tried this with latest version of azure cli on windows, mac, linux, and windows wsl. They all give the same error :(

**Additional context**
Azure account is on pay as you go plan.

**Comment by jfggdl** [comment]
Thank you for creating this issue.  We are working on your question and we should be sharing our findings.

**Comment by iocuydi** [comment]
Thanks for the prompt attention! I wanted to add a little more information. I managed to get the system key a few times with the above method 1 (az rest), but then it began to fail again. Strangely, when I returned a few hours later, it worked again, and then failed again. It seems almost random.

When I fail to get the key, the kudu logstream looks like this: 

`System.InvalidOperationException: Repository has more than 10 non-decryptable secrets backups (host). 
2019-11-12T06:14:17.978541301Z: [INFO]     at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.PersistSecretsAsync[T](T secrets, String keyScope, Boolean isNonDecryptable) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 471
2019-11-12T06:14:17.978553301Z: [INFO]     at Microsoft.Azure.WebJobs.Script.WebHost.SecretManager.GetHostSecretsAsync() in /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/SecretManager.cs:line 108
2019-11-12T06:14:17.978557501Z: [INFO]     at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetOrCreateExtensionKey(String extensionName) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 74
2019-11-12T06:14:17.978560901Z: [INFO]     at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetExtensionWebHookRoute(String extensionName) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 66
2019-11-12T06:14:17.978564501Z: [INFO]     at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider.GetUrl(IExtensionConfigProvider extension) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs:line 51`

I can include more if needed, but it is very lengthy. The issue seems to be with having too many secrets? But I only have ever registered 3 secrets in my keyvault.

Additionally, when I do successfully get the key, my final call of "az eventgrid event-subscription create..." typically fails with the following message:
`Deployment failed. Correlation ID: ###. The attempt to validate the provided endpoint https://MYFUNC.azurewebsites.net/runtime/webhooks/EventGrid
 failed. For more details, visit https://aka.ms/esvalidation.`

I did get both commands to work in conjunction _once_ and create a subscription, but I have been unable to replicate this despite setting all conditions the same... 
Before relying on this in a production case where we may need to change or create new subscriptions on short notice, I'd like to see it work consistently, or at least understand the cases under which it will fail. 

Please let me know if you want further information regarding my errors or setup, happy to help.

**Comment by ahamad-MS** [comment]
Thanks for reaching out. The issue is more specifically related to Azure Functions and its support (SDK or cli) for exposing the Event Grid Subscription URL with the system key to the customer. Currently, this URL is available through the portal UX though. 

We are transfering this issue to the Function Team to provide the proper answer/triage but in the meantime, you can get the required information by going to portal--> Function App--> Choose you function App--> Expand Functions--> Choose EventGridTrigger function --> Integrate --> copy the URL from "Event Grid Subscription URL"--> Use this url as a parameter for the endpoint in event grid cli command.

HTH

**Comment by ahmedelnably** [comment]
cc/ @mathewc
We also have the following issue to track having a command to get the function keys
https://github.com/Azure/azure-cli/issues/2999

**Comment by scgbear** [comment]
There an update on this issue? The linked issue in Azure Functions has been closed, but I'm definitely hitting the issue when trying to use the az eventgrid event-subscription create command. It sometimes works, sometimes doesn't. When it errors, it's claiming the function needs to exist, yet it clearly does exist. Function is started and running. When I look at the Activity log of the Function App I can see the failures to list the Host keys with a "BadRequest" error.

**Comment by ahamad-MS** [comment]
@AlexGhiondea Can you please route this issue to the proper contact in Function team. I added Daria Grigoriu as Ahmed used to report to her.

This is not Azure Event Grid issue and related to Azure Functions. I am not sure why the original issue #2999 was closed. Hopefully Daria can help here.

**Comment by navba-MSFT** [comment]
@iocuydi Apologies for the late reply. Could you please let me know if you are still facing this issue ? Awaiting your reply.
