### ISSUE TITLE
az billing invoice show throws "unauthorized" and "TypeError: string indices must be integers" exceptions

### ISSUE THREAD

**Issue by pekkaar** [Azure/azure-cli#11207]
**Describe the bug**
The command `az billing invoice show` and `az billing invoice list` throws the following exception:

```
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\six\six.py", line 693, in reraise
    value = tp()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\arm.py", line 738, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\arm.py", line 750, in show_exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\arm.py", line 736, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\billing\custom.py", line 16, in cli_billing_get_invoice
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-mgmt-billing\azure\mgmt\billing\operations\invoices_operations.py", line 241, in get_latest
azure.mgmt.billing.models._models.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\knack\knack\cli.py", line 218, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\__init__.py", line 99, in exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\util.py", line 50, in handle_exception
TypeError: string indices must be integers
```

**To Reproduce**
Performed `az login` successfully, then `az account set -s` with my preferred subscription (that is Active and available to me), and then the above `az billing invoice` statements that throw the exceptions.

**Expected behavior**
I would expect `az billing invoice list` to list all invoices in the set subscription, and `az billing invoice show` to provide more details on one of these... and if I miss any required additional parameters e.g. `--subscription`, then tell this to me without an exception.

**Environment summary**
Windows 10 Enterprise 18362.449, CLI version is 2.0.76 installed as MSI

**Comment by ramaganesan-rg** [comment]
working with the team to assign the right owner

**Comment by yonzhan** [comment]
move to S165.

**Comment by yonzhan** [comment]
move to S166.

**Comment by asarkar84** [comment]
This looks like an authorization issue, we need to know the subscription id to see what went wrong. The command az billing invoice list uses below rest API. We need few more details to investigate further:
- Please go to the following link: https://docs.microsoft.com/en-us/rest/api/billing/2017-04-24-preview/invoices/list
- Click on the "Try It" link and "Run" it after selecting the Subscription. 
- Share the response header and body.

![image](https://user-images.githubusercontent.com/33848291/74892959-f95eb500-533f-11ea-95a6-45a6dd6f0248.png)

**Comment by pekkaar** [comment]
Thanks for the feedback. I just tried "az billing invoice list" and now it
works! I am not sure what changed since last Nov. I have had the exact same
permissions to the subscriptions.

Anyway, thanks for the effort and information.

Kind regards,
Peter

**Comment by asarkar84** [comment]
Glad to see that the issue is resolved for you.

**Comment by houk-ms** [comment]
#14830
