### ISSUE TITLE
az login TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-cli#11236]
## Describe the bug

Related to issue #6091 but on Windows and #9326
This is Python3 issue, installed on Python2 and it works there.

```text
$ az login
WARNING: You have logged in. Now let us find all the subscriptions to which you have access...
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 603, in execute
    raise ex
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "C:\Users\ehazar\AppData\Roaming\Python\Python36\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 147, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 190, in find_subscriptions_on_login
    tenant, self._ad_resource_uri, authority_url)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 797, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 839, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 761, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
WARNING:
To open an issue, please run: 'az feedback'
```

**Command Name**
`az login`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 603, in execute
    raise ex
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli\core\commands\__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
azure\cli\core\_profile.py, ln 797, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
azure\cli\core\_profile.py, ln 839, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
azure\cli\core\_profile.py, ln 761, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.9
Shell: bash.exe

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
Hi @dashesy, I tested in Anaconda but can't repro this issue. 

In your case, CLI failes at https://github.com/Azure/azure-cli/blob/eb96e96b7f9ce1a56851bdd0c7f56285a31bb733/src/azure-cli-core/azure/cli/core/_profile.py#L761

Could you run `pip list | findstr resource` to check if the correct version of `azure-mgmt-resource` is installed? 

```
>pip list | findstr resource
azure-mgmt-resource                   4.0.0
```

**Comment by dashesy** [comment]
I had installed on a fresh Conda environment with `pip install azure-cli`. Will try to repro again.

**Comment by dashesy** [comment]
I did a fresh install of Miniconda (latests) and Python3.

Same issue:

```text
$ az login
WARNING: You have logged in. Now let us find all the subscriptions to which you have access...
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 603, in execute
    raise ex
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "C:\Users\ehazar\AppData\Roaming\Python\Python36\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\commands\__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 147, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 190, in find_subscriptions_on_login
    tenant, self._ad_resource_uri, authority_url)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 797, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 839, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "C:\ProgramData\Miniconda3\envs\py3\lib\site-packages\azure\cli\core\_profile.py", line 761, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
WARNING:
To open an issue, please run: 'az feedback'
```

This is mgmt-resource version:

```bash
$ pip list \| findstr resource                                                                                                                                                                                                                                                   azure-mgmt-resource                   4.0.0
```

How to re-create:

1. Install Conda
```bash
$ conda --version                                                                                                                                                                                                                                                               conda 4.7.12
```

2. Update conda

```bash
conda update conda
```

3. Install the venv and activate it:

```bash
conda create --name py3 python=3.6
conda activate py3
```

4. upgrade pip

```bash
pip install --upgrade
```

If your pip is broken need to use this instead:

```bash
python -m pip install -U --force-reinstall pip
# or
easy_install -U pip
```

Now install the same package that had issue, stated in the issue:

```bash
pip install azure-cli==2.0.76
```

**Comment by dashesy** [comment]
While looking at the `pip install azure-cli` I saw some `requirement already satisfied` that were using `%APPDAATA%` path, as well as in the above trace. I noticed that even though `C:\ProgramData\Miniconda3` was used for most, suddenly there is a `C:\Users\ehazar\AppData\Roaming\Python\Python36\site-packages\six.py` which was odd.

I went back and re-installed Miniconda after manually deleting `%APPDATA%\Python` and installed `azure-cli` again, this time logging succeeded!

So I think a previous installation of Miniconda (for User instead of System) was left in `%APPDATA%` that was causing this confusion. This means: at least one of the requirements of `azure-cli` is updated and `azure-cli` needs the updated dependency, even though in the `requirements` file there is no version requirement. 

Will close the issue, because repro needs a pip freeze that I forgot to do before trying the fresh install!

**Comment by jiasli** [comment]
Hi @dashesy , thanks for sharing the details. This is indeed very odd to me. Azure CLI does have requirement on versions:

https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/src/azure-cli/setup.py#L117

If the issue happens again, it will be helpful to capture all packages' install location using `pip list -v`.

**Comment by jiasli** [comment]
Hi @dashesy , thanks for sharing the details. This is indeed very odd to me. Azure CLI does have requirement on versions:

https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/src/azure-cli/setup.py#L117

If the issue happens again, it will be helpful to capture all packages' install locations using `pip list -v`.
