### ISSUE TITLE
Not able to batch-upload all my files

### ISSUE THREAD

**Issue by nachten** [Azure/azure-cli#11252]
Trying to upload a static HTML files to azure storage blob ($web) 

+/- 60% works and after that I got the error below ... 

## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch --account-name {} --auth-mode {} --account-key {} --destination {} --source {} --debug`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74 *

```

**Comment by nachten** [comment]
Problem solved after updating azure-cli :)
