### ISSUE TITLE
az webapp up failed on WSL (debian)

### ISSUE THREAD

**Issue by ronflima** [Azure/azure-cli#11313]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/_create_util.py, ln 192, in parse_netcore_version
    parsed_file = ET.parse(file_path)
python3.7/xml/etree/ElementTree.py, ln 1197, in parse
    tree.parse(source, parser)
python3.7/xml/etree/ElementTree.py, ln 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-9.11
Python 3.7.4
Shell: bash

azure-cli 2.0.76

```

**Comment by ronflima** [comment]
New updates:

I was following [this tutorial](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-html) using shtml as I have stated. After renaming all files to .html extension, I tried again:

`az webapp up --location brazilsouth --name my-app`

I got the following stack trace:

```python
webapp my-app doesn't exist
Creating Resource group 'ronaldo_rg_Windows_brazilsouth' ...
Resource group creation complete
Creating AppServicePlan 'ronaldo_asp_Windows_brazilsouth_0' ...
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by panchagnula** [comment]
Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76
