### ISSUE TITLE
ArchLinux package for official repository

### ISSUE THREAD

**Issue by artkpv** [Azure/azure-cli#11427]
Hello, thanks for the tool for Azure!

**Is your feature request related to a problem? Please describe.**

There is AUR package for Azure CLI, https://aur.archlinux.org/packages/python-azure-cli/ and other. The AUR package is community driven. To install it I needed to manually do `git clone`, `makepkg -si` on each dependency. There are a lot of them (generally from pip). So I'm not sure I did all correctly, in fact I run it for every missing dependency at the end of the list. Now I'm getting this `acs` error for each command (see below). And `az interactive` breaks with the following erorr.

```
[I] ➜ az acr check-health 
Error loading command module 'acs'
An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.

Please refer to https://aka.ms/acr/errors#docker_command_error for more information.

```
2)
```
[I] ➜ az interactive
Error loading command module 'acs'
This command is in preview. It may be changed/removed in a future release.
az>> Error loading command module 'acs'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/art/.azure/cliextensions/interactive/azext_interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/home/art/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)----------------------------------------------------------------------------------------------------
  File "/home/art/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 49, in load_arguments
    command.load_arguments()------------------------------------------------------------------------------------------------------------
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()------------------------------------------------------------------------------------------
  File "/usr/lib/python3.8/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()mespath query from previous command
  File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 490, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 530, in get_op_handler
    op = import_module(mod_to_import)cope, and scopes can be chained with spaces
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 17, in <module>
    from ._stream_utils import stream_logs
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/acr/_stream_utils.py", line 12, in <module>
    from azure.storage.blob import AppendBlobService
ImportError: cannot import name 'AppendBlobService' from 'azure.storage.blob' (/usr/lib/python3.8/site-packages/azure/storage/blob/__init__.py)
```

**Describe the solution you'd like**

Could we have a package in the official ArchLinux repository with Azure CLI with all dependancies installed?

**Describe alternatives you've considered**

There is manual install (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest). But as the tool is frequently updated and has dependencies it would be great to have auto install. 

Probably some virtualization (docker image?) would work.

**Additional context**

**Comment by haroldrandom** [comment]
@fengzhou-msft Pleas take a look here. About ArchLinux request

**Comment by artkpv** [comment]
Please see this discussion, https://bbs.archlinux.org/viewtopic.php?id=250991. The point is Azure CLI can be only promoted by the community by casting the votes for a package (https://aur.archlinux.org/packages/python-azure-cli/). So seems we can close this issue.
