### ISSUE TITLE
Possible values for --disk-type

### ISSUE THREAD

**Issue by NenoLoje** [Azure/azure-cli#11445]
&gt; --disk-type
&gt; Storage type to use for virtual machine.

Could we add what the possible values are, please?

Thanks!
--Neno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5457fd-c38a-6fb8-1df4-24a15e6ba787
* Version Independent ID: ef65acdc-464a-08c7-b013-d9e3f1560977
* Content: [az lab vm](https://docs.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/lab/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/lab/_help.py)
* Service: **devtest-lab**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by nielsvbrecht** [comment]
Since I was unable to find the solution, even in this GitHub issue;
The possible values I know of are: 'Standard' is for HDD and 'StandardSSD'.

**Comment by ggorge-etiqa** [comment]
> Since I was unable to find the solution, even in this GitHub issue; The possible values I know of are: 'Standard' is for HDD and 'StandardSSD'.

```
The command failed with an unexpected error. Here is the traceback:
Expect <class 'bool'>, got Standard (<class 'str'>)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 155, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/lab/aaz/latest/lab/_create_environment.py", line 49, in _handler
    super()._handler(command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 159, in _handler
    self.ctx = AAZCommandCtx(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command_ctx.py", line 30, in __init__
    cmd_arg.apply(self.args, dest)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 58, in apply
    self._assign_data(args, data, dest, *keys)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 73, in _assign_data
    arg[key] = data
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 48, in process_data
    raise AAZInvalidValueError('Expect {}, got {} ({})'.format(self.DataType, data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'bool'>, got Standard (<class 'str'>)
```
With az version:
```
{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.30.1",
    "ssh": "2.0.5"
  }
}
