### ISSUE TITLE
Error configuration function app with powershell object for --settings

### ISSUE THREAD

**Issue by ajklotz** [Azure/azure-cli#11552]
## Describe the bug
Errors configuring application settings using a powershell object

**Command Name**
`az functionapp config appsettings set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure\cli\core\util.py, ln 244, in shell_safe_json_parse
CLI2\lib\json\__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
CLI2\lib\json\decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
CLI2\lib\json\decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

...

azure\cli\core\__init__.py, ln 485, in default_command_handler
cli\command_modules\appservice\custom.py, ln 219, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
I created a Powershell object

`$applicationSettings @(  
       "name" = "value"
       "name2" = "value"
)`

- _Put any pre-requisite steps here..._
- `az functionapp config appsettings set --name {} --resource-group {} --settings $applicationSettings --subscription {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76 *

```

**Comment by ajklotz** [comment]
I'm trying to use a powershell object or json file to upload multiple application settings in a single `az functionapp config appsettings set` command as stated in this post.

https://github.com/Azure/azure-cli/issues/7245

**Comment by ahmedelnably** [comment]
You'll need to use the json format inside your json file and di
`az functionapp config appsettings set --name <appname> -g <resourcegroup> --settings @settingsfile.json`

The content of the json file should be
[
  {
    "name": "Setting1",
    "slotSetting": false,
    "value": "Setting1value"
  },
  {
    "name": "Setting2",
    "slotSetting": false,
    "value": "Setting2value"
  }
]

**Comment by ajklotz** [comment]
@ahmedelnably Two problems:

`az functionapp config appsettings set --name $functionAppName --resource-group $rg --settings @queueProcessorSettings.json --subscription $subscriptionName `

Powershell is not happy with the reference to the json file with @ symbol. Results in error

`At C:\WBSRC\wbdigital\CI\functionAppSettings.ps1:5 char:95
+ ... pName --resource-group $rg --settings @queueProcessorSettings.json -- ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@queueProcessorSettings' can be used only as an argument to a command. To reference variables in an expression use '$queueProcessorSettings'.`

If I wrap the json file in quotes, I still get the error that started this issue.

`az functionapp config appsettings set --name $functionAppName --resource-group $rg --settings "@queueProcessorSettings.json" --subscription $subscriptionName`

Results in:
`The command failed with an unexpected error. Here is the traceback:

not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\util.py", line 244, in shell_safe_json_parse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\util.py", line 250, in shell_safe_json_parse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    @queueProcessorSettings.json
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\custom.py", line 208, in update_app_settings
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\util.py", line 252, in shell_safe_json_parse
knack.util.CLIError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 652, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\custom.py", line 219, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)`

The powershell script and json file are in the same directory and this is my content of the json file:

`[
  {
    "name": "JSONTEST",
    "value": "VAL",
    "slotSetting": false
  }
]`

**Comment by ajklotz** [comment]
I just discovered that my problem was an incorrect file name. My json file was named with an extra letter and I was able to upload the configurations, oops! But I did have to wrap the name of the json file in quotes. So this works:

`az functionapp config appsettings set --name $functionAppName --resource-group $rg --settings "@queueProcessingAppSettings.json" --subscription $subscriptionName`

**Comment by akousmata** [comment]
I have tried this several times using Windows PowerShell ISE and I alwasy get the same error message:

not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\util.py", line 394, in shell_safe_json_parse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\util.py", line 400, in shell_safe_json_parse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    @mySettings.json
    ^
SyntaxError: invalid syntax
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 225, in update_app_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\util.py", line 402, in shell_safe_json_parse
knack.util.CLIError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yh2ypeu1\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yh2ypeu1\six\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 776, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 236, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)
To open an issue, please run: 'az feedback'

Azure CLI command:
`az webapp config appsettings set -g MyGroup -n MyAppName --settings "@mySettings.json"`

mySettings.json:
`[
    {
        "name": "Test:Value1",
        "slotSetting": true,
        "value": "slot1Test"
    },
    {
        "name": "Test:Value2",
        "slotSetting": false,
        "value": "nonSlotTest"
    }
]`

Have double and triple checks names, etc. the script and settings file are in the same folder.  Fails with or without double quotes around the file name, am I missing something here?

**Comment by akousmata** [comment]
Nevermind, so another check to do is make sure that if you are executing in an IDE such as Windows Powershell ISE, make sure you're executing the script (i.e. hitting the "Run Script" or F5) while the IDE is navigated to the scripts folder.  I had the folder/script open in the editor, and thought I had been running it from the same folder, but when you execute in PS, it supplies the full path to the script as part of executing the script.  So once I navigated to the script in the console, then ran it from there, manually, it picked up the file just fine.
