### ISSUE TITLE
az aks update fails with exception about missing "azure.mgmt.containerservice.v2019_08_01" module

### ISSUE THREAD

**Issue by CCostaT** [Azure/azure-cli#11564]
## Description
Running the "az aks update" command to configure ACR integration for existing AKS clusters fails with an exception about a missing "azure.mgmt.containerservice.v2019_08_01" module.

I was trying to follow this [guide](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration)

**Command Name**
`az aks update`

**Errors:**
```
No module named 'azure.mgmt.containerservice.v2019_08_01'
Traceback (most recent call last):
pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 523, in execute
azure\cli\core\__init__.py, ln 291, in load_arguments
cli\core\commands\__init__.py, ln 290, in load_arguments
pip-install-qxmmnr17\knack\knack\commands.py, ln 97, in load_arguments
azure\cli\core\__init__.py, ln 488, in default_arguments_loader
azure\cli\core\__init__.py, ln 528, in get_op_handler
...
cliextensions\aks-preview\azext_aks_preview\custom.py, ln 75, in <module>
    from ._helpers import _populate_api_server_access_profile, _set_load_balancer_sku, _set_vm_set_type
cliextensions\aks-preview\azext_aks_preview\_helpers.py, ln 8, in <module>
    from azure.mgmt.containerservice.v2019_08_01.models import ManagedClusterAPIServerAccessProfile
ModuleNotFoundError: No module named 'azure.mgmt.containerservice.v2019_08_01'
```

## To Reproduce:

- `az aks update -h`

## Expected Behavior
Show the help information for the update command

## Environment Summary
```
Windows-10-10.0.15063-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.72

Extensions:
aks-preview 0.4.24
application-insights 0.1.1

```

**Comment by jluk** [comment]
@CCostaT can you share the full update command you're making? Also how did you create the cluster with ACR integration was it via a different client?

cc @sauryadas wondering if this is impacted by the diff in ACR support only in core cli

**Comment by CCostaT** [comment]
@jluk The update command was `az aks update -n devk8sclut -g tcrg--attach-acr tcacr`
But this is unrelated. Just installing the preview feature using `az extension add --name aks-preview` will cause all `az aks` commands to fail.

Here's the output of `az aks -h`:
```
PS C:\Users\ccostat\KedaAzFunc> az aks -h
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.containerservice.v2019_08_01'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\commands\__init__.py", line 549, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\parser.py", line 259, in parse_args
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 1024, in __call__
    parser.print_help()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\parser.py", line 157, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\parser.py", line 249, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\_help.py", line 148, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\help.py", line 691, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\help.py", line 232, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\_help.py", line 238, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\_help_loaders.py", line 153, in versioned_load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\help.py", line 177, in load
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\knack\knack\parser.py", line 240, in __getattribute__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\__init__.py", line 494, in default_description_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qxmmnr17\azure-cli-core\azure\cli\core\__init__.py", line 528, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\tiago.costa\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 75, in <module>
    from ._helpers import _populate_api_server_access_profile, _set_load_balancer_sku, _set_vm_set_type
  File "C:\Users\tiago.costa\.azure\cliextensions\aks-preview\azext_aks_preview\_helpers.py", line 8, in <module>
    from azure.mgmt.containerservice.v2019_08_01.models import ManagedClusterAPIServerAccessProfile
ModuleNotFoundError: No module named 'azure.mgmt.containerservice.v2019_08_01
```

**Comment by jluk** [comment]
@CCostaT I **think** the `--attach-acr` command set I believe is only in core cli, when using the extension it will check the extension cmd set and fail. Going to ask someone to look into this.

Can you try
1. Updating core cli to 2.0.77
1. Retry aks cmds with preview turned on

**Comment by CCostaT** [comment]
@jluk Alright, it looks like updating to version 2.0.77 fixed the issue. I don't get any errors anymore :) 
Thank you!

**Comment by jluk** [comment]
Thanks for confirm @CCostaT ! Closing as a result :)
