### ISSUE TITLE
az ad commands fail in cloud shell instance of Windows Terminal

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#11590]
Keep getting this failure:
~~~
The command failed with an unexpected error. Here is the traceback:

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 487, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/signed_in_user_operations.py", line 77, in get
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 543, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 376, in _get_token_from_cloud_shell
    auth = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
~~~

Using Windows Terminal v0.7.3451.0

**Comment by haroldrandom** [comment]
@jiasli Please take a look

**Comment by jiasli** [comment]
What is the command being executed? Could you run the command with `--debug` and share the output? Thank you.

**Comment by brandonh-msft** [comment]
~~~
brandon@Azure:~$ az ad sp create-for-rbac --debug
Command arguments: ['ad', 'sp', 'create-for-rbac', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f43a1407d08>, <function OuEvent: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchLoaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.020 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.002 seconds.
Loaded module 'appservice' in 0.009 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.008 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.007 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.031 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.005 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.008 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.030 seconds.
Loaded module 'vm' in 0.016 seconds.
Loaded all modules in 0.265 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/brandon/.azure/cliextensions'
Found 1 extensions: ['eventgrid']
Extensions directory: '/home/brandon/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.78 min_required=2.0.24 max_required=None
Event: MainLoader.OnFailedExtensionLoad []
Unable to load extension 'eventgrid'. Use --debug for more information.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 207, in _update_command_table_from_extens    _load_extension_command_loader(self, args, ext_mod)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 969, in _load_extension_command_    return _load_command_loader(loader, args, ext, '')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 955, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "/home/brandon/.azure/cliextensions/eventgrid/azext_eventgrid/__init__.py", line 22, in load_command_table
    load_command_table(self, args)
  File "/home/brandon/.azure/cliextensions/eventgrid/azext_eventgrid/commands.py", line 25, in load_command_table
    with self.command_group('eventgrid topic', topics_mgmt_util, client_factory=topics_factory) as g:
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in command_group
    return self._command_group_cls(self, group_name, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 1069, in __init__
    merged_kwargs = self._merge_kwargs(kwargs, base_kwargs=command_loader.module_kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 1093, in _merge_kwargs
    return _merge_kwargs(kwargs, base, CLI_COMMAND_KWARGS)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 1044, in _merge_kwargs
    raise TypeError('unrecognized kwargs: {}'.format(unrecognized_kwargs))
TypeError: unrecognized kwargs: ['min_profile']

Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f43a0754400>]
az_command_data_logger : command args: ad sp create-for-rbac --debug
metadata file logging enabled - writing logs to '/home/brandon/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_paraEvent: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f43a07Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f439e8586a8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f43a0f3fbf8>, <function CLmsrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Getting management service client client_type=AuthorizationManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.async_paging : Paging async iterator protocol is not available for ApplicationPaged
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 400 103
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'rmsrestazure.azure_active_directory : MSI: Failed to retrieve a token from 'http://localhost:50342/oauth2/token' with ancli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 490, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1318, in create_service_pri    credential_description='rbac')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 733, in create_application
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 733, in <listcomp>
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 155, in intern    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 543, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 376, in _get_token_from_cloud_shell
    auth = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 490, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1318, in create_service_pri    credential_description='rbac')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 733, in create_application
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 733, in <listcomp>
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 155, in intern    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 543, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 376, in _get_token_from_cloud_shell
    auth = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
cli.azure.cli.core.util :
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2438 in cache
telemetry.check : Negative: The /home/brandon/.azure/telemetry.txt was modified at 2020-01-07 16:58:31.178964, which incommand ran in 31.002 seconds.
~~~

**Comment by arrownj** [comment]
Hi @brandonh-msft , it seems that it failed to get token due to network issue. Could you please help check whether only `az ad sp create-for-rbac` failed with this error or all the commands would fail with the same error ? It probably because that the network is not fine.

**Comment by brandonh-msft** [comment]
I don't think a network issue would result in an HTTP 400; it'd be something else like "connection refused" / "could not connect"

**Comment by brandonh-msft** [comment]
`az account list` works fine:

```
brandon@Azure:~$ az account list
Unable to load extension 'eventgrid'. Use --debug for more information.
A few accounts are skipped as they don't have 'Enabled' state. Use '--all' to display them.
[
  {
    "cloudName": "AzureCloud",
...
```

**Comment by arrownj** [comment]
Hi @brandonh-msft , `az accout list` would only retrieve data from local cache, there is no web request for this command. Could you please try another command such as `az ad group create` with --debug ? And there is no problem with the `localhost` url for MSI authentication, it will do some redirect thing in background.

**Comment by jiasli** [comment]
Same issue as https://github.com/Azure/azure-cli/issues/11749

`400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token` is a known issue of Cloud Shell that it intermittently fails with this error. 

To solve it, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

**Comment by brandonh-msft** [comment]
> To solve it, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

I _have_ run `az login` ...

**Comment by brandonh-msft** [comment]
ok so after getting a Cloud Shell
~~~
Requesting a cloud shell instance...
Succeeded.
Requesting a terminal (this might take a while)...

Welcome to Azure Cloud Shell

Type "az" to use Azure CLI
~~~

I then ran `az login`
~~~
brandon@Azure:~$ az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code B766AURYA to authenicate.
[
  {
...
~~~

followed by `az account set` and then my `create-for-rbac` call:

~~~
brandon@Azure:~$ az account set --subscription 0c...
brandon@Azure:~$ az ad sp create-for-rbac
Creating a role assignment under the scope of "/subscriptions/0c..."
  Retrying role assignment creation: 1/36
{
  "appId": "...",
  "displayName": "azure-cli-2020-03-10-18-36-14",
  "name": "http://azure-cli-2020-03-10-18-36-14",
  "password": "...",
  "tenant": "..."
}
~~~

So it appears to succeed then.

Seems like instead of closing #11749 we should work to resolve this problem with Cloud Shell that, after prompting for my tenant and getting an instance, I'm not _really_ logged in (despite being able to issue many commands).

Could we move this issue to another repo/project where it can be triaged/tracked/fixed?

**Comment by yungezz** [comment]
HI @brandonh-msft do you know where's cloudshell repo? This is not Azure CLI issue, but cloudshell issue. would like to close the issue here.

**Comment by brandonh-msft** [comment]
sorry no idea; not even sure there is one

**Comment by jiasli** [comment]
It's not that you are not logged in. Azure CLI on Cloud Shell is logged in with MSI, but Cloud Shell fails to return the token occasionally. 

Cloud Shell uses a private VSTS repo https://msazure.visualstudio.com/One/_git/compute-CloudShell?version=GBmaster (Need permission to access). We do have a thread with them about this issue.

**Comment by brandonh-msft** [comment]
> Cloud Shell uses a private VSTS repo https://msazure.visualstudio.com/One/_git/compute-CloudShell?version=GBmaster (Need permission to access). We do have a thread with them about this issue.

Thanks for this information. I have access, do we have an open work item for it? Should I create one and reference this GitHub issue?

**Comment by jiasli** [comment]
@brandonh-msft, I don't have too much experience on creating work items there. We only have email communication with Cloud Shell team.

**Comment by arrownj** [comment]
Close this issue first ,the cloud shell issue will be traced in #11749 .
