### ISSUE TITLE
az acr login and az feedback not working on Fedora31

### ISSUE THREAD

**Issue by davqu** [Azure/azure-cli#11819]
[~]$ az acr login
The command failed with an unexpected error. Here is the traceback:

No module named '_cffi_backend'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 528, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 496, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 10, in <module>
    from ._utils import (
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/_utils.py", line 28, in <module>
    from ._archive_utils import upload_source_code, check_remote_source_code
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 15, in <module>
    from azure.storage.blob import BlockBlobService
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/storage/blob/__init__.py", line 6, in <module>
    from .appendblobservice import AppendBlobService
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/storage/blob/appendblobservice.py", line 30, in <module>
    from ._deserialization import (
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/storage/blob/_deserialization.py", line 40, in <module>
    from ._encryption import _decrypt_blob
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/storage/blob/_encryption.py", line 13, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
  File "/usr/lib64/az/lib/python3.6/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'

To open an issue, please run: 'az feedback'

   [9] az acr login: FAILURE. Ran: 2 mins ago. 

Enter the number of the command you would like to create an issue for. Enter q to quit: 9
The command failed with an unexpected error. Here is the traceback:

cannot import name '_psutil_linux' from 'psutil' (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 769, in handle_feedback
    res = _prompt_issue(recent_commands)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 751, in _prompt_issue
    prefix, url, original_issue = _build_issue_info_tup(recent_command_list[ans])
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 529, in _build_issue_info_tup
    format_dict["shell"] = "Shell: {}".format(_get_parent_proc_name())
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 488, in _get_parent_proc_name
    import psutil
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py", line 95, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from 'psutil' (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)

To open an issue, please run: 'az feedback'

**Comment by yugangw-msft** [comment]
> ModuleNotFoundError: No module named '_cffi_backend'

This is not ACR or feedback related, rather a general platform issue that whether or not CLI works on Fedora31. CC @fengzhou-msft @achandmsft

**Comment by yonzhan** [comment]
issue triaged.

**Comment by fengzhou-msft** [comment]
@davqu Please run `yum install python3-cffi` and retry.

**Comment by davqu** [comment]
Thank You. Now it runs.
