### ISSUE TITLE
Failed to get acess token

### ISSUE THREAD

**Issue by ogerardin** [Azure/azure-cli#11829]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /00add7eb-02c0-4384-9428-f6710a5626e3/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x052D4A70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Traceback (most recent call last):
pip-install-q_27sn_r\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.71

Extensions:
interactive 0.4.3

```

**Comment by jsntcy** [comment]
@jiasli, please help take a look, thanks.

**Comment by jiasli** [comment]
Per the error message, this seems to be connection issue. Could you run this command to see if you can connect to `https://login.microsoftonline.com`?

```
python -c "import urllib.request; print(urllib.request.urlopen('https://login.microsoftonline.com').info())"
```

**Comment by ogerardin** [comment]
Indeed there seems to be the problem, but it was working until a few days ago... I may add that I'm behind a corporate proxy.

```
Traceback (most recent call last):
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\oge\scoop\apps\python\current\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\oge\scoop\apps\python\current\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\oge\scoop\apps\python\current\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\oge\scoop\apps\python\current\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```

**Comment by jiasli** [comment]
In that case, it may be possible that your corporate's default network is blocking Azure endpoints. Is https://login.microsoftonline.com/ accessible from a web browser?

If proxy is needed for internet access, you may check [Working behind a proxy](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) and let me know if the issue is solved. Thanks.

**Comment by ogerardin** [comment]
I tried again just now and got a different error:

```
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed
 or reset their password. The grant was issued on '2019-10-01T09:01:26.6448468Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2019-12-30T07:33:09.0000000Z'.\r\nTrace ID: 2778c3b3-acb9-4b7f-9aff-a1cadaebb700\r\nCorrelation ID:
 8cc030f0-335b-4056-9d42-0b45312d6d2a\r\nTimestamp: 2020-01-14 11:09:42Z","error_codes":[50173],"timestamp":"2020-01-14 11:09:42Z","trace_id":"2778c3b3-acb9-4b7f-9aff-a1cadaebb700","correlation_id":"8cc030f0-335b-4056-9d42-0b45312d6d2a","error_uri":"https://login
.microsoftonline.com/error?code=50173"}
```

So I did `az login` again and then `az account get-access-token` worked as expected...

I'm a bit puzzled as to what happened there, but anyway all is good now.

**Comment by jiasli** [comment]
This may be due to some change on your company's directory. Re-login is the typical solution to solve such kinds of issues. Glad to know it is working for you. 😃

**Comment by lexothink** [comment]
This works for me... 
https://github.com/Azure/azure-cli/issues/24952#issuecomment-1361130310
