### ISSUE TITLE
az eventhubs eventhub authorization-rule create cannot supply rights

### ISSUE THREAD

**Issue by n3rd253** [Azure/azure-cli#11870]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Trying to supply "Listen Manage Send" to the --rights property in the azure CLI ends in the following:

Arguments
    --eventhub-name     [Required] : Name of EventHub.
    --name -n           [Required] : Name of EventHub AuthorizationRule.
    --namespace-name    [Required] : Name of Namespace.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    **--rights            [Required] : Space-separated list of Authorization rule rights.  Allowed
                                     values: Listen, Manage, Send.**

**To Reproduce**
az eventhubs eventhub authorization-rule create providing Listen Manage Send as rights

**Expected behavior**
Rights are added as the documentation claims

**Comment by n3rd253** [comment]
Above error is providing --rights "Listen Manage Send"

Just providing --rights Listen Manage Send, ends in

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/mgmt/eventhub/v2017_04_01/operations/event_hubs_operations.py", line 451, in create_or_update_authorization_rule
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.eventhub.v2017_04_01.models.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/usr/local/Cellar/azure-cli/2.0.80/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 64, in handle_exception
    error = response_dict['error']
TypeError: string indices must be integers

**Comment by houk-ms** [comment]
#14830
