### ISSUE TITLE
Error when adding multiple databases to a failover group

### ISSUE THREAD

**Issue by colutti** [Azure/azure-cli#11889]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.79

**Describe the bug**
I am trying to add several databases hosted in elastic pools to a failover group, but I am getting an error.

**To Reproduce**
Powershell:

$databases = (az sql db list --resource-group <hidden_value> --server <hidden_value> | ConvertFrom-Json) | Where-Object { ($_.failoverGroupId -eq $null) -and ($_.elasticPoolName -ne $null) } | Select-Object -Property name | ForEach-Object { "$($_.name)" }

az sql failover-group update --name <hidden_value> --resource-group<hidden_value> --server <hidden_value>--add-db $databases

**Expected behavior**
Databases should be added to the failover.

**Environment summary**
Installed with brew on a macOS latest version 

**Traceback**

The command failed with an unexpected error. Here is the traceback:

list index out of range
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 769, in handle_feedback
    res = _prompt_issue(recent_commands)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 751, in _prompt_issue
    prefix, url, original_issue = _build_issue_info_tup(recent_command_list[ans])
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 539, in _build_issue_info_tup
    res = _get_minified_issue_url(command_log_file, format_dict.copy(), is_ext, ext_name, capacity)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 600, in _get_minified_issue_url
    minified_errors.set_capacity(
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 366, in set_capacity
    self._minified_error = self._get_minified_errors()
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 404, in _get_minified_errors
    errors_string = self._minify_by_removing_lines(errors_string)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/feedback/custom.py", line 467, in _minify_by_removing_lines
    if not (".py" in lines[mid] and ", ln" in lines[mid]):
IndexError: list index out of range

**Comment by colutti** [comment]
Also, the documentation found [here](https://docs.microsoft.com/en-us/cli/azure/sql/failover-group?view=azure-cli-latest#az-sql-failover-group-update) states that the --add-db accepts a list of databases, but does not specify how we should pass this list. The documentation should be updated with this info and an example.

**Comment by colutti** [comment]
Btw, $databases has a list of databases being one per line like:

xxxx
xxxx
xxxx
xxxx

I have also tried a json string like `"['db1','db2']"` and it did not work

**Comment by jeroenterheerdt** [comment]
@colutti thanks for the feedback. please give me a moment to look into this.

**Comment by jeroenterheerdt** [comment]
@maboja-msft.

**Comment by pilarragorri** [comment]
Hey @colutti , probably after 8 months you got your things sorted out.
But just in case, and if another poor soul runs on this issue again

AZ Cli expects the DBs to be sent with just the name separated by blank spaces

i.e -- `az sql failover-group update --add-db mydb1 mydb2 --name myfg1--resource-group myrg1--server mysrv1`

Is it documented? Nope , and I hope MSFT will fix that 
@jeroenterheerdt  maybe updating the docs or with some examples

As with many things --debug is your friend, since you can see which API endpoint AZ Cli is trying to hit and with what payload.
