### ISSUE TITLE
API Management Issue (az apim)

### ISSUE THREAD

**Issue by Frontarolli** [Azure/azure-cli#11890]
I can't run az apim commands (create, list, show, etc)
Could you please inform how to solve it?

## Describe the bug

**Command Name**
`az apim create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 528, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 300, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\apim\__init__.py", line 28, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\apim\_params.py", line 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim create`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.80

Extensions:
front-door 1.0.2
interactive 0.4.3

```

**Comment by dearsi-mocha** [comment]
The current work around: https://dearsi-mocha.github.io/cloudsauce/2020/04/23/azure-apim-cli-woes/

**Comment by yonzhan** [comment]
apim

**Comment by PramodValavala-MSFT** [comment]
@Frontarolli Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
