### ISSUE TITLE
az apim list doesn't work

### ISSUE THREAD

**Issue by wi5nia** [Azure/azure-cli#11941]
## Describe the bug

**Command Name**
`az apim list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli-core\azure\cli\core\__init__.py", line 294, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\apim\__init__.py", line 28, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-mjd5h3hf\azure-cli\azure\cli\command_modules\apim\_params.py", line 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77 *

Extensions:
azure-devops 0.16.0

```

**Comment by PramodValavala-MSFT** [comment]
@wi5nia Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
