### ISSUE TITLE
az aks install-cli fails behind corporate proxy

### ISSUE THREAD

**Issue by GerhardRuckriegel** [Azure/azure-cli#11952]
Command arguments: ['aks', 'install-cli', '--debug', '--verbose']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x034630C0>, <function OutputProducer.on_global_arguments at 0x03311C90>, <function CLIQuery.on_global_arguments at 0x03341D68>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.031 seconds.
Loaded module 'acs' in 0.024 seconds.
Loaded module 'advisor' in 0.009 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.015 seconds.
Loaded module 'apim' in 0.011 seconds.
Loaded module 'appconfig' in 0.011 seconds.
Loaded module 'appservice' in 0.020 seconds.
Loaded module 'backup' in 0.011 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.023 seconds.
Loaded module 'batchai' in 0.012 seconds.
Loaded module 'billing' in 0.010 seconds.
Loaded module 'botservice' in 0.013 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.013 seconds.
Loaded module 'cloud' in 0.010 seconds.
Loaded module 'cognitiveservices' in 0.010 seconds.
Loaded module 'configure' in 0.009 seconds.
Loaded module 'consumption' in 0.013 seconds.
Loaded module 'container' in 0.011 seconds.
Loaded module 'cosmosdb' in 0.016 seconds.
Loaded module 'deploymentmanager' in 0.014 seconds.
Loaded module 'dla' in 0.020 seconds.
Loaded module 'dls' in 0.015 seconds.
Loaded module 'dms' in 0.011 seconds.
Loaded module 'eventgrid' in 0.011 seconds.
Loaded module 'eventhubs' in 0.013 seconds.
Loaded module 'extension' in 0.013 seconds.
Loaded module 'feedback' in 0.010 seconds.
Loaded module 'find' in 0.011 seconds.
Loaded module 'hdinsight' in 0.011 seconds.
Loaded module 'interactive' in 0.005 seconds.
Loaded module 'iot' in 0.014 seconds.
Loaded module 'iotcentral' in 0.008 seconds.
Loaded module 'keyvault' in 0.014 seconds.
Loaded module 'kusto' in 0.011 seconds.
Loaded module 'lab' in 0.014 seconds.
Loaded module 'managedservices' in 0.008 seconds.
Loaded module 'maps' in 0.010 seconds.
Loaded module 'monitor' in 0.018 seconds.
Loaded module 'natgateway' in 0.010 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.021 seconds.
Loaded module 'network' in 0.048 seconds.
Loaded module 'policyinsights' in 0.009 seconds.
Loaded module 'privatedns' in 0.014 seconds.
Loaded module 'profile' in 0.010 seconds.
Loaded module 'rdbms' in 0.014 seconds.
Loaded module 'redis' in 0.009 seconds.
Loaded module 'relay' in 0.012 seconds.
Loaded module 'reservations' in 0.012 seconds.
Loaded module 'resource' in 0.016 seconds.
Loaded module 'role' in 0.013 seconds.
Loaded module 'search' in 0.009 seconds.
Loaded module 'security' in 0.012 seconds.
Loaded module 'servicebus' in 0.015 seconds.
Loaded module 'servicefabric' in 0.010 seconds.
Loaded module 'signalr' in 0.010 seconds.
Loaded module 'sql' in 0.017 seconds.
Loaded module 'sqlvm' in 0.011 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.048 seconds.
Loaded module 'vm' in 0.031 seconds.
Loaded all modules in 0.851 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\gr28\.azure\cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x034A2C00>]
az_command_data_logger : command args: aks install-cli --debug --verbose
metadata file logging enabled - writing logs to 'C:\Users\gr28\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x034C21E0>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x034DA8A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x034DA930>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04254A08>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03311CD8>, <function CLIQuery.handle_query_parameter at 0x03341DB0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x034DA8E8>, <function handler at 0x04325B70>]
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\acs\custom.py", line 317, in k8s_install_cli
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\acs\custom.py", line 317, in k8s_install_cli
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

HTTP_PROXY and HTTPS_PROXY are set in the powershell session

**Comment by GerhardRuckriegel** [comment]
works with cmd.exe but not from powershell

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168

**Comment by qianwens** [comment]
@GerhardRuckriegel , this error happens because CLI failed to access endpoint https://storage.googleapis.com/kubernetes-release/release/stable.txt. Could you please help check if you can access this file in your powershell?

**Comment by GerhardRuckriegel** [comment]
Curl works from powershell

Regards,
Gerhard Ruckriegel
Tool Product Manager
Global Services, CTO, Architecture & Security, Nokia
Gerhard.Ruckriegel@nokia.com<mailto:Gerhard.Ruckriegel@nokia.com>

Nokia Solutions and Networks GmbH & Co. KG Thurn-und-Taxis-Straße 10, 90411 Nürnberg Sitz der Gesellschaft: München / Registered office: Munich Registergericht: München / Commercial registry: Munich, HRA 88537 WEEE-Reg.-Nr.: DE 52984304 Persönlich haftende Gesellschafterin / General Partner: Nokia Solutions and Networks Management GmbH Geschäftsleitung / Board of Directors: Dr. Wolfgang Hackenberg, Ralf Niederberger Vorsitzender des Aufsichtsrats / Chairman of supervisory board: Hans-Jürgen Bill Sitz der Gesellschaft: München / Registered office: Munich Registergericht: München / Commercial registry: Munich, HRB 163416

**Comment by qianwens** [comment]
Assign to AKS team to investigate this issue. Install Kubernetes CLI failed.

**Comment by fengzhou-msft** [comment]
cc @Azure/aks-pm

**Comment by yonzhan** [comment]
@Azure/aks-pm any update?

**Comment by bpdohall** [comment]
@GerhardRuckriegel - do your proxy settings include the request schema? (e.g. prefixed with `http://` and/or `https://` as appropriate)?

Also there is a suggestion to use lower case environment variable names with urllib when running on windows (ref: https://stackoverflow.com/a/8287752/4601453).

**Comment by jiasli** [comment]
Close due to no response.
