### ISSUE TITLE
Very ugly error message when using az account logging update command on a Storage Account of kind BlobStorage or sku.tier Premium

### ISSUE THREAD

**Issue by hulseware** [Azure/azure-cli#11969]
If you try to exeute az account logging update with a Premium storage account or with a BlobStorage storage account, you will get an error similar to the following:

az>> az storage logging show --account-name xxxxxxxxxxx --subscription xx-xxx-xxx
The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='xxxxxxxxxx.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00DFC830>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00DFC830>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxxxxxxxx.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00DFC830>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 321, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\_http\httpclient.py", line 92, in perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxxxxxxxx.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00DFC830>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bhulse\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 662, in cli_execute
    result = invocation.execute(args)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 652, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\arm.py", line 750, in show_exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\storage\operations\logging.py", line 15, in get_logging
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\storage\services_wrapper.py", line 29, in get_logging
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\queue\queueservice.py", line 372, in get_queue_service_properties
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 430, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 361, in _perform_request
azure.common.AzureException: HTTPSConnectionPool(host='xxxxxxxxxxx.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00DFC830>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))

**I would have expected a simple error message along the lines of:**
**Premium Storage accounts do not support logging**
**BlobStorage storage accounts do not support logging.**
I though I was having a problem with api quotas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237378a-a708-8e2f-3c8c-0bc8b623d21c
* Version Independent ID: c4e27b67-9605-60f5-899d-8ffd727079b2
* Content: [az storage logging](https://docs.microsoft.com/en-us/cli/azure/storage/logging?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168

**Comment by Juliehzl** [comment]
Hi @hulseware,  sorry for late response first.
There are several points to clarify here:
1. Are you using `az interactive` to run cli commands?
 2. When I try to reproduce your issue with normal cli (not in interactive mode), I only get one exception not four exceptions like what in your scenario. Here is what I get:
```
HTTPSConnectionPool(host='zuhblob.queue.core.windows.net', port=443): Max retries exceeded with url: /?restype=service&comp=properties (Caused by NewConnectionError('<urllib3.connection.HTTPSConnect
ion object at 0x000001F15CE28288>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
3. Your suggestion is very valuable to us. As you mentioned, the error occurs because of specific storage account type. Actually it is caused by default value (bqt) in --services parameter:
- BlobStorage doesn't support logging for queue service;
- PremiumStorage doesn't support logging for blob/queue/table services.
I will refine the error message to make it point to wrong storage account type.

**Comment by hulseware** [comment]
1.  Yes, I use az interactive while developing the right cli commands to add to utilities targeted at maintaining better security across the subscriptions I am managing for my team. So the extra tracebacks were coming from the az interactive tool.
  2.  Yes, I believe that message is what I see when running via the normal command line.

Thanks for working to make the error message more descriptive of the real problem!
