### ISSUE TITLE
Can't run from PowerShell

### ISSUE THREAD

**Issue by centreboard** [Azure/azure-cli#11979]
## Describe the bug
Can't run any `az` command from PowerShell (either 5.1 or 7-rc2) 
Works fine from `cmd`

**Errors:**
```
> az 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\__main__.py", line 33, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 547, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\azlogging.py", line 30, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 28, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\extension\__init__.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\config.py", line 39, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\util.py", line 108, in ensure_dir
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\util.py", line 105, in ensure_dir
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'H:\\\\'
```

## Expected Behavior
Runs fine in a powershell prompt.
This used to work fine for me, though I can't remember whether I've used it since I previously updated the az cli and rebooted.

## Environment Summary
Installed from MSI.
Persists when uninstall and reinstalled.
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe / pwsh.exe

azure-cli 2.0.80

Extensions:
alias 0.5.2
application-insights 0.1.1
azure-devops 0.16.0

```

**Comment by centreboard** [comment]
Sorry I think this is a issue for PCs in my network where `HOMEDRIVE` has been mapped to `H:` despite that drive not existing, and this was the first command where the issue occurred (I later had the same symptoms of looking for `H:` in pwsh and not cmd with `git config`).
