### ISSUE TITLE
webapp:ERROR: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by CoderKooke** [Azure/azure-cli#12008]
Hi ... I am getting this error running the below command:

`az webapp config connection-string set -n myapp -g webapps -t SQLAzure --settings sql1 = $connectionString`

The traceback is below

az : ERROR: The command failed with an unexpected error. Here is the traceback:
At line:1 char:1
+ az webapp config connection-string set -n myapp -g webapps - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The comm... the traceback::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli\azure\cli\command_modules\appservice\custom.py", line 981, in update_connection_strings
ValueError: not enough values to unpack (expected 2, got 1)

Many thanks for you help

**Comment by panchagnula** [comment]
when running this command follow the example here az webapp config connection-string set -g MyResourceGroup -n MyUniqueApp -t mysql \
    --settings mysql1='Server=myServer;Database=myDB;Uid=myUser;Pwd=myPwd;'

https://docs.microsoft.com/en-us/cli/azure/webapp/config/connection-string?view=azure-cli-latest#az-webapp-config-connection-string-set

**Comment by panchagnula** [comment]
Closing due to lack of response on this.

**Comment by kiriasCMNH** [comment]
Hi, in the docs the example refers to a mysql connection string tho, i am having issues trying to set a connection string that has " inside it, as for example a connection string that is commonly used for entity framework.

**Comment by xqiu** [comment]
If in windows command line for sqlserver, need to use double quote instead of single quote, i.e.
~~~
az webapp config connection-string set -g %groupname% -n %nameprefix%backend -t SQLServer --settings DefaultConnection="Server=tcp:%nameprefix%dbsvr.database.windows.net,1433;Initial Catalog=%nameprefix%db;Persist Security Info=False;User ID=%myadminuser%;Password=%MyPassWord%;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
~~~
