### ISSUE TITLE
az signalr show - 'CommandResultItem' object is not iterable

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#12056]
## Describe the bug

**Command Name**
`az signalr show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- use the command below to point to a **non-existing** signalr
- `az signalr show --subscription {} --name non-existing-signalr --resource-group {} --output json`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.79 *

Extensions:
alias 0.5.2
azure-devops 0.16.0

```

**Comment by stan-sz** [comment]
Duplicate of #9904
