### ISSUE TITLE
az webapp create command is not working.

### ISSUE THREAD

**Issue by selvan123** [Azure/azure-cli#12055]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
Please run 'az login' to setup account.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --name {} --resource-group {} --plan {} --runtime {}`

## Environment Summary
```
Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Shell: bash

azure-cli 2.0.81

```

**Comment by selvan123** [comment]
The command failed with an unexpected error. Here is the traceback:

update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 135, in create_webapp
    match['setter'](cmd, match, site_config)
TypeError: update_site_config() takes 2 positional arguments but 3 were given


This is the error that I am facing, its urgent please comment.

**Comment by TomBonnerAtTFL** [comment]
Seeing the same issue consistently in our CI.

Version:
```
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Windows\ServiceProfiles\NetworkService\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

Output:
```
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\appservice\custom.py", line 135, in create_webapp
TypeError: update_site_config() takes 2 positional arguments but 3 were given
```

**Comment by arrownj** [comment]
@selvan123 , thanks for reporting, we are looking at it.

**Comment by hassanalbudairiqts** [comment]
Same issue, I tried to create a service plan using the following command
az webapp create --resource-group {} --plan {} --name {} --runtime "PHP|7.0" --deployment-local-git
and got the following error
update_site_config() takes 2 positional arguments but 3 were given

**Comment by panchagnula** [comment]
Rootcause same as #12159. please use the Edge builds

**Comment by TPIvan** [comment]
new issue created https://github.com/Azure/azure-cli/issues/13690
