### ISSUE TITLE
image-copy-extension 0.2.3 failing during snapshot creation

### ISSUE THREAD

**Issue by ashamanx1** [Azure/azure-cli#12067]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
Required parameter 'storageAccountId' is missing (null).
```

## To Reproduce:

 az image copy --source-resource-group <redacted> --source-object-name EX_Analytics-1 --target-location australiaeast --target-reso
urce-group "<redacted>" --cleanup
Getting os disk id of the source vm/image
Creating source snapshot
command failed: ['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'EX_Analytics-1_os_disk_snapshot', '--resource-group', '<redacted>', '--source', '<redacted>', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: Required parameter 'storageAccountId' is missing (null).

The command failed with an unexpected error. Here is the traceback:

Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'EX_Analytics-1_os_disk_snapshot', '--resource-group', '<redacted>', '--source', '<redacted>', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-0u_uiwkq\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\Some User\.azure\cliextensions\image-copy-extension\azext_imagecopy\custom.py", line 83, in imagecopy
    run_cli_command(cli_cmd)
  File "C:\Users\Some User\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 46, in run_cli_command
    raise ex
  File "C:\Users\Some User\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'EX_Analytics-1_os_disk_snapshot', '--resource-group', '<redacted>', '--source', <redacted>, '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 1.

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80 *

Extensions:
image-copy-extension 0.2.3

```

**Comment by arrownj** [comment]
Hi @qwordy , could you please help check this ?

**Comment by ashamanx1** [comment]
An update: it works if you include '--source-type vm' but fails if you leave it out or use '--source-type image'

**Comment by qwordy** [comment]
Version 0.2.4 should have fixed this issue.
```
0.2.4
++++++
* Fix copying an image originally created from a blob (create a snapshot with the source storage account id)
```
