### ISSUE TITLE
az apim create does not work

### ISSUE THREAD

**Issue by cpatterson26** [Azure/azure-cli#12081]
## Describe the bug

**Command Name**
`az apim create -h`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 528, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\__init__.py", line 300, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\apim\__init__.py", line 28, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\apim\_params.py", line 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim create`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
@cpatterson26 , thanks for reporting, we are looking at it.

**Comment by PramodValavala-MSFT** [comment]
@cpatterson26 Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
