### ISSUE TITLE
'bool' object has no attribute 'provider'

### ISSUE THREAD

**Issue by patriziotomato** [Azure/azure-cli#12104]
## Describe the bug

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
'bool' object has no attribute 'provider'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/appservice/custom.py, ln 704, in list_runtimes
    return [s['displayName'] for s in runtime_helper.stacks]
cli/command_modules/appservice/custom.py, ln 2159, in stacks
    self._load_stacks()
cli/command_modules/appservice/custom.py, ln 2180, in _load_stacks
    raw_stacks = self._client.provider.get_available_stacks(os_type_selected=os_type, raw=True)
AttributeError: 'bool' object has no attribute 'provider'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list-runtimes --linux`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
@patriziotomato , thanks for reporting, we are looking at this ?

**Comment by oasalonen** [comment]
Same issue here. Just updated to az 2.0.81.

```bash
The command failed with an unexpected error. Here is the traceback:

'bool' object has no attribute 'provider'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\knack\knack\cli.py", line 206, in invoke   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\six\six.py", line 703, in reraise          File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\appservice\custom.py", line 704, in list_runtimes
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2159, in stacks
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-1o1fsnhi\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2180, in _load_stacks
AttributeError: 'bool' object has no attribute 'provider'
```

**Comment by christiannwamba** [comment]
I can confirm that the issue does not exist when you run from Cloud shell through the Azure portal.

But it does show up when you run the command on a local machine.

**Comment by dadams0641** [comment]
Confirming as well. RHEL7 just updated to 2.0.81

```
az webapp list-runtimes

The command failed with an unexpected error. Here is the traceback:

'bool' object has no attribute 'provider'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 704, in list_runtimes
    return [s['displayName'] for s in runtime_helper.stacks]
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2159, in stacks
    self._load_stacks()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2180, in _load_stacks
    raw_stacks = self._client.provider.get_available_stacks(os_type_selected=os_type, raw=True)
AttributeError: 'bool' object has no attribute 'provider'

To open an issue, please run: 'az feedback'
```

```
az --version
azure-cli                         2.0.81 *

command-modules-nspkg              2.0.3
core                              2.0.81 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
log-analytics                      0.1.4
```

**Comment by panchagnula** [comment]
we had a regression with 2.0.81 - we have since fixed up the list-runtimes command - if you can try it with latest version please let us know. Thanks!
