### ISSUE TITLE
Trying to use azure shell - encountering [Errno 30] Read-only file system error

### ISSUE THREAD

**Issue by KjWhal** [Azure/azure-cli#12110]
I am attempting to follow along with: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/terraform-install-configure

On trying to set the subscription I am getting the following, and googling is providing several cases of other people asking the same question, without resolution. How do I resolve?

[Errno 30] Read-only file system: '/home/kevin/.azure/commands/2020-02-10.02-41-53.account_set.417.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 486, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 80, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 101, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/kevin/.azure/commands/2020-02-10.02-41-53.account_set.417.log'

## To Reproduce:
Browse to shell.azure.com and sign up a pay-as-you-go subscription

- _Put any pre-requisite steps here..._
- `az account set --subscription {}`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by KjWhal** [comment]
Tried again this morning - seems to work fine. A provisioning issue perhaps?

**Comment by wbpluto** [comment]
Maybe it's due to the failure of Authentication. Please try to login manually by running: az login
