### ISSUE TITLE
"az aks create" is failed due to failing to encode character u'\u2018'

### ISSUE THREAD

**Issue by oomichi** [Azure/azure-cli#12138]
## Describe the bug

"az aks create" command was failed like the following:

**Command Name**
`az aks create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'ascii' codec can't encode character u'\u2018' in position 706: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 706: ordinal not in range(128)
```

**Version**
I believe az command is the latest at this time:
```
$ az --version
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/bin/python'
Extensions directory '/home/ubuntu/.azure/cliextensions'

Python (Linux) 2.7.15+ (default, Oct  7 2019, 17:39:04)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

* DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
A future version of Azure CLI will drop support for Python 2.7.


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
```

**Comment by arrownj** [comment]
@oomichi , thanks for reporting, we are looking at this.

**Comment by sayak1711** [comment]
Facing same issue

**Comment by sayak1711** [comment]
I managed to resolve it after uninstalling and reinstalling azure cli from [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). Then I reinstalled kubectl. Then all worked fine.

**Comment by oomichi** [comment]
I confirmed I don't face this issue with multiple creations of AKS cluster at this time.
I am not sure the reason, the Azure stops to return a response which includes invalid string?

**Comment by oomichi** [comment]
I faced this issue today like
```
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
The command failed with an unexpected error. Here is the traceback:

'ascii' codec can't encode character u'\u2018' in position 714: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 714: ordinal not in range(128)

To open an issue, please run: 'az feedback'
```

**Comment by oomichi** [comment]
This issue still happens today:
```
Waiting for AAD role to propagate[################################    ]  90.0000%Could not create a role assignment for subnet. Are you an Owner on this subscription?
The command failed with an unexpected error. Here is the traceback:

'ascii' codec can't encode character u'\u2018' in position 713: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 713: ordinal not in range(128)

To open an issue, please run: 'az feedback'
```

**Comment by oomichi** [comment]
Character data handling is different between python 2 and python 3.
After started using "az" command of python 3 with the following way, I don't face this issue.
```
$ sudo pip install virtualenv
$ mkdir azure-cli-with-python3
$ which python3
$ cd azure-cli-with-python3
$ virtualenv -p /usr/bin/python3.6 .
$ source ./bin/activate
$ sudo apt install python3-dev
$ pip install azure-cli
$ az --version
(Confirm azure-cli works under Python 3)
azure-cli                          2.5.1

...

Python (Linux) 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0]
```
