### ISSUE TITLE
Edge url results in 404

### ISSUE THREAD

**Issue by TomBonnerAtTFL** [Azure/azure-cli#12179]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
In `README.md`, the information for Edge builds uses the URL "https://azurecliprod.blob.core.windows.net/edge", which results now at a 404 (Blob not found).

**To Reproduce**
Try run follow the steps in "Edge Builds" `pip3 install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge --upgrade-strategy=eager`, the output error should be:

```
Exception:
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/env/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/env/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/env/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/env/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/env/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/env/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/env/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/env/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/env/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/env/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/env/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: The specified blob does not exist. for url: https://azurecliprod.blob.core.windows.net/edge/azure-mgmt-maps/
```

**Expected behavior**
Honestly don't know what the output should be, but it should install `az cli` without error.

**Environment summary**
`pip install` on a Windows container over Window's ssh from Windows client. I also checked the URL on my host-computer and it also resulted in a 404.

**Comment by arrownj** [comment]
Hi @fengzhou-msft , could you please help take a look at it?

**Comment by fengzhou-msft** [comment]
@TomBonnerAtTFL you may be running a lower version of pip. Please upgrade with `pip3 install --upgrade pip` first.

**Comment by TomBonnerAtTFL** [comment]
@fengzhou-msft is correct, a fresh install of `pip3` does not see the issue. I guess the error message from `pip` could be more helpful, but oh well, live and learn.

Thank you for your time.
