### ISSUE TITLE
Error getting token for azure in vs

### ISSUE THREAD

**Issue by Chibuzor27** [Azure/azure-cli#12176]
I get this error when trying to run my function code in vs

It breaks at this point
builder.AddAzureKeyVault(
                    $"https://{builtConfig[KeyVaultName]}.vault.azure.net/",
                    keyVaultClient,
                    new DefaultKeyVaultSecretManager());
builder.Build();

Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: 'Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{tenantId}. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{tenantId}. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{tenantId}. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{tenantId}. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.áThe token was issued on 2019-10-21T15:04:52.3852838Z and was inactive for 90.00:00:00.\r\nTrace ID: ad2019fc-11f5-4d9f-a308-d25554b51300\r\nCorrelation ID: 619e9cc0-ee0b-4d73-9fb5-ca2dad24acc2\r\nTimestamp: 2020-02-13 09:50:46Z","error_codes":[700082],"timestamp":"2020-02-13 09:50:46Z","trace_id":"ad2019fc-11f5-4d9f-a308-d25554b51300","correlation_id":"619e9cc0-ee0b-4d73-9fb5-ca2dad24acc2","error_uri":"https://login.microsoftonline.com/error?code=700082"}
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli\azure\cli\command_modules\profile\custom.py", line 75, in get_access_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\_profile.py", line 604, in get_raw_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\_profile.py", line 913, in retrieve_token_for_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\authentication_context.py", line 145, in acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\authentication_context.py", line 128, in _acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\authentication_context.py", line 143, in token_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\token_request.py", line 347, in get_token_from_cache_with_refresh
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\token_request.py", line 127, in _find_token_from_cache
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\cache_driver.py", line 199, in find
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\cache_driver.py", line 184, in _refresh_entry_if_necessary
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\cache_driver.py", line 160, in _acquire_new_token_from_mrrt
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\token_request.py", line 137, in _get_token_with_token_response
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\token_request.py", line 339, in _get_token_with_refresh_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\token_request.py", line 112, in _oauth_get_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\adal\adal\oauth2_client.py", line 289, in get_token
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity.áThe token was issued on 2019-10-21T15:04:52.3852838Z and was inactive for 90.00:00:00.\r\nTrace ID: ad2019fc-11f5-4d9f-a308-d25554b51300\r\nCorrelation ID: 619e9cc0-ee0b-4d73-9fb5-ca2dad24acc2\r\nTimestamp: 2020-02-13 09:50:46Z","error_codes":[700082],"timestamp":"2020-02-13 09:50:46Z","trace_id":"ad2019fc-11f5-4d9f-a308-d25554b51300","correlation_id":"619e9cc0-ee0b-4d73-9fb5-ca2dad24acc2","error_uri":"https://login.microsoftonline.com/error?code=700082"}
WARNING: 
To open an issue, please run: 'az feedback'

'

**Comment by arrownj** [comment]
Hi @bim-msft , could you please help take a look at it?

**Comment by bim-msft** [comment]
@Chibuzor27 It seems that you are facing some login issues, could you try to re-login?

**Comment by Chibuzor27** [comment]
I've been able to proceed. I had to run az login and re-authenticate.
Thank you very much.
    On Monday, 17 February 2020, 15:11:20 GMT, Bin Ma <notifications@github.com> wrote:  
 
 
@Chibuzor27 It seems that you are facing some login issues, could you try to re-login?

**Comment by bim-msft** [comment]
@Chibuzor27 According to the error log: `The refresh token has expired due to inactivity`. It means that your refresh token is expired, you may obtain it again or just re-login/re-authenticate.
Issue closed, if you have anything else unresolved, feel free to reopen and ask me again, thanks!

**Comment by LuisFcoOrtiz** [comment]
I did az login and the error persists... The Azure documentation is so bad.

**Comment by jiasli** [comment]
@LuisFcoOrtiz, the original error `AADSTS700082: The refresh token has expired due to inactivity` is caused by Conditional Access policy. I provided more info at https://github.com/Azure/azure-cli/issues/16641#issuecomment-767457267.

Are you seeing the same error? If not, could you create a new issue?

**Comment by LuisFcoOrtiz** [comment]
@jiasli  Finally I could resolve it. The key was going to ( %HOMEPATH%/.azure/) and delete the azure-secret.json. And this works for me. Thanks for all!

**Comment by jiasli** [comment]
`azure-secret.json` is not used by Azure CLI but `azure-maven-plugins` (https://github.com/microsoft/azure-maven-plugins/issues/705). If you can reproduce it, please create a new issue and share the error message. Thanks.
