### ISSUE TITLE
`az vm create` template exception results in `AttributeError: 'str' object has no attribute 'message'`

### ISSUE THREAD

**Issue by nyetwurk** [Azure/azure-cli#12199]
**Describe the bug**
```
msrest.exceptions : The template deployment 'vm_deploy_6wgE9OwiPdB6N2bH7t9TZfzPo0YBZmja' is not valid according to the validation procedure. The tracking id is '61a349e3-9cfa-4a75-989c-f1e4cfb9bd46'. See inner errors for details.
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 804, in create_vm
    LongRunningOperation(cmd.cli_ctx)(client.create_or_update(resource_group_name, deployment_name, properties))
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message) # NTL
AttributeError: 'str' object has no attribute 'message'
```
**To Reproduce**
`az vm create` an instance that would generate a quota error

**Expected behavior**
A simple error, not a big backtrace dump.
Likely simply
```
InvalidTemplateDeployment
```

**Environment summary**
apt install on debian buster
`2.0.81-1~buster`

workaround diff:
```diff
diff --git a/src/azure-cli-core/azure/cli/core/commands/arm.py b/src/azure-cli-core/azure/cli/core/commands/arm.py
index d0fdd3c52..1cd110464 100644
--- a/src/azure-cli-core/azure/cli/core/commands/arm.py
+++ b/src/azure-cli-core/azure/cli/core/commands/arm.py
@@ -100,7 +100,7 @@ class ArmTemplateBuilder(object):

 def handle_template_based_exception(ex):
     try:
-        raise CLIError(ex.inner_exception.error.message)
+        raise CLIError(ex.inner_exception.error)
     except AttributeError:
         raise CLIError(ex)
```

**Comment by arrownj** [comment]
@nyetwurk , thanks for reporting, we are looking at it.

**Comment by devigned** [comment]
Looks like this is affecting AKS-Engine as well.

**Comment by nyetwurk** [comment]
```
--- /opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py-dist	2020-02-19 17:34:04.707335477 +0000
+++ /opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py	2020-02-19 17:44:13.587230027 +0000
@@ -117,7 +117,7 @@
             for error_info in self.additionalInfo:
                 error_str += "\n\t{}".format(str(error_info).replace("\n", "\n\t"))
         error_bytes = error_str.encode()
-        return error_bytes.decode('ascii')
+        return error_bytes.decode('utf8')

     @classmethod
     def _get_subtype_map(cls):
```
solves the problem for me.

**Comment by nyetwurk** [comment]
The root cause is that the error message for going over quota contains non-ascii characters ("Details" is surrounded by smart single quotes).
https://github.com/Azure/azure-cli/pull/12200/commits/0fdb2b8d096858c7fb05f83117b0629fa7465e5b#r381434412

**Comment by nyetwurk** [comment]
Root cause is described here https://github.com/Azure/msrestazure-for-python/issues/140

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/issues/12315
https://github.com/Azure/azure-cli/issues/12207
These issues report similar problems

**Comment by qwordy** [comment]
Azure CLI 2.4.0 has been released. It fixes this issue.
