### ISSUE TITLE
Assigning Azure Policy with parameters via the CLI fails

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-cli#12298]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.1.0

**Describe the bug**

Unable to assign a policy with parameters. The following error is returned:
```
The command failed with an unexpected error. Here is the traceback:

Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1328, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1114, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1137, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 577, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1298, in _deserialize
    self._deserialize(local_type, value)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1307, in _deserialize
    return self.deserialize_data(data, response)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1490, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1537, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1537, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1503, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1338, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1328, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1114, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1137, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 1351, in create_policy_assignment
    createdAssignment = policy_client.policy_assignments.create(scope, name or uuid.uuid4(), assignment)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/azure/mgmt/resource/policy/v2019_09_01/operations/_policy_assignments_operations.py", line 174, in create
    body_content = self._serialize.body(parameters, 'PolicyAssignment')
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 579, in body
    raise_with_traceback(
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 577, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1298, in _deserialize
    self._deserialize(local_type, value)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1307, in _deserialize
    return self.deserialize_data(data, response)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1490, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1537, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1537, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1503, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1338, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1328, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1114, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/usr/local/Cellar/azure-cli/2.1.0/libexec/lib/python3.8/site-packages/msrest/serialization.py", line 1137, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**To Reproduce**
Steps to reproduce the behavior.
1. Get the policy details with `az policy definition list --query "[?displayName=='Append tag and its default value']"`
1. Assign the policy using the CLI
`az policy assignment create --name 'append-department-tag' --display-name 'Append Department tag to resources in demo RG' --scope '/subscriptions/.../resourceGroups/...' --policy '...' -p '{"tagName":"Department","tagValue":"MyDepartment"}'`

**Expected behavior**

Policy is assigned to the resource group

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
CLI version 2.1.0
MacOS Catalina 10.15.3

**Additional context**

**Comment by yonzhan** [comment]
add to S167.

**Comment by zhoxing-ms** [comment]
@toddysm Hi, the reason for this problem is that the format of parameter `-p` is incorrect. The correct format should be  ` -p "{ \"tagName\": { \"value\": \"Department\" } , \"tagValue\": { \"value\": \"MyDepartment\" } }"`
Specific parameter writing guide can refer to the document:  [click](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#parameters)
