### ISSUE TITLE
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

### ISSUE THREAD

**Issue by azurecli** [Azure/azure-cli#12315]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version    2.1.0

**Describe the bug**

az vm create failed 

**To Reproduce**

az account set --subscription "PSE - Dev - Experimental [R&D]"
az vm create   --resource-group eval-eus-sb-performance-rg   --name MRFClient02z2   --image "/subscriptions/5f3fdd41-8063-4938-b491-052a59849925/resourceGroups/eval-eus-sb-performance-rg/providers/Microsoft.Compute/images/LNKD-CentOS7-4.19-r06-image"  --admin-username mrftesting --vnet-name perf-east-vnet   --subnet perf-east-subnet   --size Standard_D32_v3   --zone 2   --nsg perf-nsg   --boot-diagnostics-storage perfeaststdstorage   --public-ip-sku Standard  --accelerated-networking true  --ssh-key-values "/home/mjzhang/Downloads/winston_id_rsa.pub"  --query publicIpAddress   -o tsv

**Expected behavior**
vm should be created successfully.

**Environment summary**
az --version
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/home/mjzhang/project/azure_cli/py36-venv/bin/python3'
Extensions directory '/home/mjzhang/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Additional context**

**Comment by azurecli** [comment]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 830, in create_vm
    LongRunningOperation(cmd.cli_ctx)(client.create_or_update(resource_group_name, deployment_name, properties))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/usr/lib64/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/usr/lib64/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 913: ordinal not in range(128)
Call stack:
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'vm_deploy_UWlETX2KC1zSzajrBIH9rTff92DRsH5E' is not valid according to the validation procedure. The tracking id is '84e79720-537b-4b77-99c8-156c1a597854'. See inner errors for details.",)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 830, in create_vm
    LongRunningOperation(cmd.cli_ctx)(client.create_or_update(resource_group_name, deployment_name, properties))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/log.py", line 78, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/usr/lib64/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/usr/lib64/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 913: ordinal not in range(128)
Call stack:
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'vm_deploy_UWlETX2KC1zSzajrBIH9rTff92DRsH5E' is not valid according to the validation procedure. The tracking id is '84e79720-537b-4b77-99c8-156c1a597854'. See inner errors for details.",)
Arguments: ()

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by eisber** [comment]
I had a similar error. Changing to utf-8 from ascii fixed it for me:

/anaconda/envs/py37_default/lib/python3.7/site-packages/msrestazure/azure_exceptions.py:120

**Comment by edwardsp** [comment]
I am seeing this as well.  You can easily reproduce this with any ARM template where you don't have enough quota for the resources.

**Comment by qwordy** [comment]
Simillar issue #12207

**Comment by qwordy** [comment]
https://github.com/Azure/msrestazure-for-python/issues/140
There is an issue in msrestzure to ask for a fix.

**Comment by qwordy** [comment]
Azure CLI 2.4.0 has been released. It fixes this issue.
