### ISSUE TITLE
az vm create wont work with --image 'MicrosoftSQLServer:SQL2017-WS2016:Standard:14.1.200114'

### ISSUE THREAD

**Issue by dariuszbz** [Azure/azure-cli#12361]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I try to run:
    az vm create    -n  'xxxxx' `
                    -g  'xxxxx' `
                    --admin-password 'xxxxx' `
                    --admin-username 'xxxxx' `
                    --vnet-name 'xxxxx' `
                    --subnet 'xxxxx' `
                    --image 'MicrosoftSQLServer:SQL2017-WS2016:Standard:14.1.200114' `
                    -l  'NorthEurope' 
and getting:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\command_modules\vm\custom.py", line 830, in create_vm
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-mgmt-resource\azure\mgmt\resource\resources\v2019_07_01\operations\_deployments_operations.py", line 2695, in create_or_update
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-mgmt-resource\azure\mgmt\resource\resources\v2019_07_01\operations\_deployments_operations.py", line 2642, in _create_or_update_initial
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\arm.py", line 103, in handle_template_based_exception
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\arm.py", line 105, in handle_template_based_exception
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\msrestazure\msrestazure\azure_exceptions.py", line 193, in __str__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\msrestazure\msrestazure\azure_exceptions.py", line 120, in __str__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 912: ordinal not in range(128)
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 218, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 107, in exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\util.py", line 47, in handle_exception
Message: CloudError("The template deployment 'vm_deploy_TBgw6rQGH9rQGc8PZCMcXEZ940UNVRVF' is not valid according to the validation procedure. The tracking id is 'b4704780-3edc-4c0a-9d63-13f562dd71eb'. See inner errors for details.",)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\command_modules\vm\custom.py", line 830, in create_vm
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-mgmt-resource\azure\mgmt\resource\resources\v2019_07_01\operations\_deployments_operations.py", line 2695, in create_or_update
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-mgmt-resource\azure\mgmt\resource\resources\v2019_07_01\operations\_deployments_operations.py", line 2642, in _create_or_update_initial
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\arm.py", line 103, in handle_template_based_exception
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\arm.py", line 105, in handle_template_based_exception
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\log.py", line 78, in format
    msg = str(self.msg)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\msrestazure\msrestazure\azure_exceptions.py", line 193, in __str__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\msrestazure\msrestazure\azure_exceptions.py", line 120, in __str__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 912: ordinal not in range(128)
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 218, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 107, in exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\util.py", line 47, in handle_exception
Message: CloudError("The template deployment 'vm_deploy_TBgw6rQGH9rQGc8PZCMcXEZ940UNVRVF' is not valid according to the validation procedure. The tracking id is 'b4704780-3edc-4c0a-9d63-13f562dd71eb'. See inner errors for details.",)
Arguments: ()

**To Reproduce**
Steps to reproduce the behavior.
run above

**Expected behavior**
vm is created based on image

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
windows server,
visual studio code powershell integrated terminal (latest updates),
Python 3.8.0
az version - 
  "azure-cli": "2.1.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.1.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.29",
    "dev-spaces": "1.0.3"

**Additional context**
to get the image list available run:
az vm image list --sku Standard --offer SQL2017-WS2016  --publisher MicrosoftSQLServer --location NorthEurope --all -o table

**Comment by dariuszbz** [comment]
Ok I found:
it works with python 3.5.2.

thanks ......

**Comment by yungezz** [comment]
hi @dariuszbz is it ok to close the issue now?

**Comment by dariuszbz** [comment]
Hi @yungezz I think you have to install the proper python version with az, or check the python version to give the proper error message to the user.
But it's ok for me to close. It's working now with the python 3.5.2.
