### ISSUE TITLE
Table output unavailable error after running az aks get-upgrades

### ISSUE THREAD

**Issue by enginaar** [Azure/azure-cli#12366]
## Describe the bug

**Command Name**
`az aks get-upgrades`

**Errors:**
```
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

## To Reproduce:

Run the following command
`az aks get-upgrades --resource-group {resourceName} --name {clusterName} --output table`

## Expected Behavior

Following result is expected
```
Name     ResourceGroup     MasterVersion    NodePoolVersion    Upgrades
-------  ----------------  ---------------  -----------------  ---------------
default  myResourceGroup   1.14.8           1.14.8             1.15.5, 1.15.7
```
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6

azure-cli 2.1.0

```
## Additional Context
1. Same error when the same command executed in Cloud Shell.
2. See result below when executed using --debug flag.
```
...
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x048FAD20>, <function _x509_from_base64_to_hex_transform at 0x048FAD68>]
Event: CommandInvoker.OnFilterResult []
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\output.py", line 56, in format_table
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\command_modules\acs\_format.py", line 89, in aks_upgrades_table_format
TypeError: 'NoneType' object is not subscriptable

cli.azure.cli.core.util : Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger : exit code: 1
```
3. JSON output below shows there are upgrades available.
```
{
  "agentPoolProfiles": null,
  "controlPlaneProfile": {
    "kubernetesVersion": "1.14.8",
    "name": null,
    "osType": "Linux",
    "upgrades": [
      {
        "isPreview": null,
        "kubernetesVersion": "1.15.7"
      },
      {
        "isPreview": null,
        "kubernetesVersion": "1.15.5"
      }
    ]
  },
  "id": "/subscriptions/cb3ec624-50d8-450f-a367-d24d39587cce/resourcegroups/EY/providers/Microsoft.ContainerService/managedClusters/engsks/upgradeprofiles/default",
  "name": "default",
  "resourceGroup": "EY",
  "type": "Microsoft.ContainerService/managedClusters/upgradeprofiles"
}
```

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it

**Comment by frachel** [comment]
I still get this error using the Azure Cloud shell.

`
frank_rachel@Azure:~$ az version
{
  "azure-cli": "2.24.0",
  "azure-cli-core": "2.24.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.4.53",
    "resource-graph": "1.1.0",
    "ssh": "0.1.5"
  }
}
frank_rachel@Azure:~$ az aks get-upgrades --resource-group petst-rg --name petst-aks -o table
The behavior of this command has been altered by the following extension: aks-preview
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
frank_rachel@Azure:~$
`

**Comment by mcwienczek** [comment]
still not working for me as well. 

```
❯ az aks get-versions --location westeurope --output table
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

Azure CLI version: 
```
❯ az version
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by usejfijaj** [comment]
Same here!

`➜  ~ az aks list -o table
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
➜  ~ az version
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
➜  ~`

**Comment by jiasli** [comment]
The latest `tabulate` issue is tracked at https://github.com/Azure/azure-cli/issues/20348.

**Comment by in-bharath** [comment]
interesting, instead of output table, if we change it to output json, am seeing the results in json format

**Comment by dekkermg** [comment]
Could it be that it fails if you are at the latest version and there are no upgrades?
