### ISSUE TITLE
az sql server wait: "The command failed with an unexpected error"

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-cli#12409]
**Describe the bug**
az sql server wait: "The command failed with an unexpected error"

**To Reproduce**
1) Create a server
`az sql server create --resource-group dbEnvironmentMigrator-Group-117891603-2020-03-02 --name dbEnvironmentMigrator-Server-117891603-2020-03-02 --location northeurope --admin-user redacted --admin-password redacted `

2) Wait for that server to be ready
`az sql server wait --custom "state=='Ready'" --name dbEnvironmentMigrator-Server-117891603-2020-03-02 --resource-group dbEnvironmentMigrator-Group-117891603-2020-03-02`

**Expected behavior**
The wait command waits without error

**Environment summary**
Azure DevOps hosted build agent

**Error Information**

> 2020-03-02T13:32:08.1279728Z ERROR: The command failed with an unexpected error. Here is the traceback:
2020-03-02T13:32:08.1280755Z 
2020-03-02T13:32:08.1807130Z ERROR: 'NoneType' object has no attribute 'casefold'
2020-03-02T13:32:08.1808207Z Traceback (most recent call last):
2020-03-02T13:32:08.1809163Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2020-03-02T13:32:08.1809902Z     cmd_result = self.invocation.execute(args)
2020-03-02T13:32:08.1810829Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
2020-03-02T13:32:08.1811458Z     raise ex
2020-03-02T13:32:08.1812296Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
2020-03-02T13:32:08.1813079Z     results.append(self._run_job(expanded_arg, cmd_copy))
2020-03-02T13:32:08.1814010Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
2020-03-02T13:32:08.1814812Z     six.reraise(*sys.exc_info())
2020-03-02T13:32:08.1816270Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2020-03-02T13:32:08.1816852Z     raise value
2020-03-02T13:32:08.1817791Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
2020-03-02T13:32:08.1818386Z     result = cmd_copy(params)
2020-03-02T13:32:08.1819278Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
2020-03-02T13:32:08.1819894Z     return self.handler(*args, **kwargs)
2020-03-02T13:32:08.1820809Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 684, in handler
2020-03-02T13:32:08.1821652Z     if provisioning_state.casefold() == 'failed':
2020-03-02T13:32:08.1822770Z AttributeError: 'NoneType' object has no attribute 'casefold'

**Comment by yonzhan** [comment]
sql

**Comment by a-vishar** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/12313
