### ISSUE TITLE
consecutive set-tier commands errors with "Too many files open"

### ISSUE THREAD

**Issue by nitrosx** [Azure/azure-cli#12447]
## Describe the bug

**Command Name**
`az storage blob set-tier`

**Errors:**
```
HTTPSConnectionPool(host='pittprodrnel.blob.core.windows.net', port=443): Max retries exceeded with url: /rnel-archive-alan-20200304104704/ECoG_Correlation_Plots/DS012R01_CHN_56_corr.emf?comp=tier (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a98b6e128>: Failed to establish a new connection: [Errno 24] Too many open files',))
HTTPSConnectionPool(host='pittprodrnel.blob.core.windows.net', port=443): Max retries exceeded with url: /rnel-archive-alan-20200304104704/ECoG_Correlation_Plots/DS012R01_CHN_56_corr.emf?comp=tier (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9a98b6e128>: Failed to establish a new connection: [Errno 24] Too many open files',))
...
2020-03-04 11:27:42 INFO     containerBlobTier : Command : storage blob set-tier --container-name rnel-archive-alan-20200304104704 --account-name xxxxx --account-key xxxx --output none --tier Archive --name xxxx
The command failed with an unexpected error. Here is the traceback:

[Errno 24] Too many open files: '.azure/commands/2020-03-04.11-27-42.unknown_command.23182.log'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/knack/cli.py", line 206, in invoke
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 486, in execute
  File "/usr/local/lib/python3.5/dist-packages/knack/cli.py", line 162, in raise_event
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/azlogging.py", line 80, in init_command_file_logging
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/azlogging.py", line 101, in _init_command_logfile_handlers
  File "/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
OSError: [Errno 24] Too many open files: '.azure/commands/2020-03-04.11-27-42.unknown_command.23182.log'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob set-tier --container-name {} --account-name {} --account-key {} --output {} --tier {} --name {}`

## Environment Summary
```
Linux-4.8.0-53-generic-x86_64-with-LinuxMint-18.2-sonya
Python 3.5.2

azure-cli 2.1.0

```

**Comment by yungezz** [comment]
HI @Juliehzl could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
@nitrosx , I cannot reproduce this error with the same command. Could you please help provide more information to help us to investigate?
