### ISSUE TITLE
aks create failed

### ISSUE THREAD

**Issue by cpriyanga** [Azure/azure-cli#12489]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
pip-install-2ombfg7z\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 608, in execute
cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
cli\core\commands\__init__.py, ln 659, in _run_job
Temp\pip-install-2ombfg7z\six\six.py, ln 696, in reraise
cli\core\commands\__init__.py, ln 636, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
...
pip-install-2ombfg7z\requests\requests\hooks.py, ln 31, in dispatch_hook
msrest\msrest\universal_http\requests.py, ln 275, in user_hook_cb
pip-install-2ombfg7z\msrestazure\msrestazure\tools.py, ln 57, in register_rp_hook
pip-install-2ombfg7z\msrestazure\msrestazure\tools.py, ln 102, in _register_rp
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --vm-set-type {} --load-balancer-sku {} --location {} --kubernetes-version {} --network-plugin {} --vnet-subnet-id {} --service-cidr {} --dns-service-ip {} --docker-bridge-address {} --generate-ssh-keys`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.78 *

```

**Comment by cpriyanga** [comment]
PS C:\Users\pc081g> az aks create --resource-group aksworkshop --name $AKS_CLUSTER_NAME --vm-set-type VirtualMachineScaleSets --load-balancer-sku standard --location eastus --kubernetes-version $VERSION --network-pl
ugin azure --vnet-subnet-id $SUBNET_ID --service-cidr 10.2.0.0/24 --dns-service-ip 10.2.0.10 --docker-bridge-address 172.17.0.1/16 --generate-ssh-keys
SSH key files 'C:\Users\pc081g\.ssh\id_rsa' and 'C:\Users\pc081g\.ssh\id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
AAD role propagation done[############################################]  100.0000%The command failed with an unexpected error. Here is the traceback:

'registrationState'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\six\six.py", line 696, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli\azure\cli\command_modules\acs\custom.py", line 1791, in aks_create
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-cli-core\azure\cli\core\util.py", line 370, in sdk_no_wait
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-mgmt-containerservice\azure\mgmt\containerservice\v2019_10_01\operations\_managed_clusters_operations.py", line 600, in create_or_update
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\azure-mgmt-containerservice\azure\mgmt\containerservice\v2019_10_01\operations\_managed_clusters_operations.py", line 546, in _create_or_update_initial
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\service_client.py", line 336, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\__init__.py", line 197, in run
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\requests.py", line 72, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\pipeline\requests.py", line 193, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\universal_http\requests.py", line 333, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\universal_http\requests.py", line 142, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\requests\requests\sessions.py", line 653, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\requests\requests\hooks.py", line 31, in dispatch_hook
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrest\msrest\universal_http\requests.py", line 275, in user_hook_cb
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrestazure\msrestazure\tools.py", line 57, in register_rp_hook
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2ombfg7z\msrestazure\msrestazure\tools.py", line 102, in _register_rp
KeyError: 'registrationState'

**Comment by yonzhan** [comment]
aks
