### ISSUE TITLE
az group list-The command failed with an unexpected error.

### ISSUE THREAD

**Issue by hlinh1988** [Azure/azure-cli#12505]
## Describe the bug

The command failed with an unexpected error. Here is the traceback:

[Errno 5] Input/output error: '/home/hlinh1988/.azure/commands/2020-03-09.11-03-04.group_list.476.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 486, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 80, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 101, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 5] Input/output error: '/home/hlinh1988/.azure/commands/2020-03-09.11-03-04.group_list.476.log'

To open an issue, please run: 'az feedback'

## To Reproduce:
az group list --query "[?starts_with(name,'az30004')]".name --output tsv 

- _Put any pre-requisite steps here..._
AZ_300T02_Lab_Mod03_Configuring: Exercise 5: Remove lab resources 

## Expected Behavior
List all created Resource-group

## Environment Summary
```
Bash shell on Cloud shell

## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
add to S167.

**Comment by zhoxing-ms** [comment]
@hlinh1988 The format `"[?starts_with(name,'az30004')]".name` of `--query` parameter is incorrect, please try changing it to `"[?starts_with(name,'az30004')].name"`

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
