### ISSUE TITLE
az 2.2.0 does not appear to be compatible with Python 3.5

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-cli#12525]
**Describe the bug**
az 2.2.0 does not appear to be compatible with Python 3.5.

**To Reproduce**
Run `azdev linter` on a custom extension using Python 3.5.9.  The latest az published at https://packages.microsoft.com/repos/azure-cli started breaking this.  It looks like a Python 3.6-style format string at azure/cli/command_modules/cdn/custom.py line 113 is to blame.

**Expected behavior**
Either builds with 3.5 should work, or 3.5 should not be marked as supported.

**Environment summary**
VSTS pipeline, latest Ubuntu, python 3.5.9, az 2.2.0.

**Comment by jim-minter** [comment]
Here's the traceback I get:

```
ERROR: invalid syntax (custom.py, line 113)
Traceback (most recent call last):
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/knack/invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/knack/commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/knack/commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azdev/operations/linter/__init__.py", line 83, in run_linter
    create_invoker_and_load_cmds_and_args(az_cli)
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/core/file_util.py", line 76, in create_invoker_and_load_cmds_and_args
    invoker.commands_loader.load_arguments()
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/core/__init__.py", line 294, in load_arguments
    cmd.load_arguments()  # this loads the arguments via reflection
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/core/__init__.py", line 496, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vsts/work/1/s/gopath/src/github.com/Azure/ARO-RP/pyenv3.5/lib/python3.5/site-packages/azure/cli/command_modules/cdn/custom.py", line 113
    raise CLIError(f"endpoint {endpoint_name} does not have a CDN WAF policy link.", endpoint_name)
```

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks.

**Comment by fengzhou-msft** [comment]
Thanks for reporting this issue. While format string could be fixed quickly, the underlying CLI framework `knack` that Azure CLI depends on has [dropped support for 3.5](https://github.com/microsoft/knack/pull/182/files#diff-d9ae695c8119e58c2ec435b6deae2d53R10) recently.

The CI tests for 3.5 was removed for over a year and the [prerequisites](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#prerequisites) of our install instruction also indicates requirement of  3.6+. We should remove 3.5 from the classifier.
