### ISSUE TITLE
az notification-hub authorization-rule create --rights does not allow for multiple comma delimited values

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#12590]
**Problem:** The ability to create a new authorization rule with > 1 **-- right** doesn’t seem to be working.  

**Published Extensions Reference Documentation**
https://docs.microsoft.com/en-us/cli/azure/ext/notification-hub/notification-hub/authorization-rule?view=azure-cli-latest#ext-notification-hub-az-notification-hub-authorization-rule-create
“
--rights
The rights associated with the rule. _**Separated by comma.**_
“

**Testing**
**This syntax does work**
az notification-hub authorization-rule create --resource-group spnhubrg --namespace-name spnhubns2 --notification-hub-name spfcmtutorial1nhub --name spnhub1key **--rights Listen**

**This syntax does work**
az notification-hub authorization-rule create --resource-group spnhubrg --namespace-name spnhubns2 --notification-hub-name spfcmtutorial1nhub --name spnhub3key **--rights Send**

**This syntax does NOT work (no space after comma)**
az notification-hub authorization-rule create --resource-group spnhubrg --namespace-name spnhubns2 --notification-hub-name spfcmtutorial1nhub --name spnhub2key **--rights Listen,Send**

**This syntax does NOT work (space after comma)**
az notification-hub authorization-rule create --resource-group spnhubrg --namespace-name spnhubns2 --notification-hub-name spfcmtutorial1nhub --name spnhub2key **--rights Listen, Send**

**This syntax does NOT work** (testing to see if “listen” and “send” are not a valid combination)
az notification-hub authorization-rule create --resource-group spnhubrg --namespace-name spnhubns2 --notification-hub-name spfcmtutorial1nhub --name spnhub2key **--rights Listen, Send,Manage**

**Example Error message**
“
The command failed with an unexpected error. Here is the traceback:

**'Listen,Send' is not valid value** for enum <enum 'AccessRights'>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 911, in serialize_enum
    enum_obj(result)
  File "/opt/az/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/opt/az/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/opt/az/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'Listen,Send' is not a valid AccessRights

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/home/delora/.azure/cliextensions/notification-hub/azext_notification_hub/custom.py", line 261, in create_or_update_authorization_rule_notificationhubs_hub
    return client.create_or_update_authorization_rule(resource_group_name=resource_group_name, namespace_name=namespace_name, notification_hub_name=notification_hub_name, authorization_rule_name=rule_name, properties=body)
  File "/home/delora/.azure/cliextensions/notification-hub/azext_notification_hub/vendored_sdks/notificationhubs/operations/notification_hubs_operations.py", line 511, in create_or_update_authorization_rule
    body_content = self._serialize.body(parameters, 'SharedAccessAuthorizationRuleCreateOrUpdateParameters')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 580, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 452, in _serialize
    target_obj, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 715, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 489, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 715, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 489, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 708, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 786, in serialize_iter
    serialized.append(self.serialize_data(d, iter_type, **kwargs))
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 703, in serialize_data
    return Serializer.serialize_enum(data, enum_obj=enum_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 918, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'Listen,Send' is not valid value for enum <enum 'AccessRights'>
“

**Comment by yonzhan** [comment]
notification-hub

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to follow up on this? thanks.

**Comment by fengzhou-msft** [comment]
@dbradish-microsoft Thanks for spotting this. The help message is not correct. When we use list in CLI, the common pattern is to separate by space. I have fixed the help message and provided examples in this [PR](https://github.com/Azure/azure-cli-extensions/pull/1380/files#). If you search rights, you'll see the changes.
