### ISSUE TITLE
Update failed on Bash on Windows

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1272]
Tried to update from b7 and got a failure.  Is this a known issue (upgrading from b7) or a bug? 

```
$ az --version
azure-cli (0.1.0b7)

component (0.1.0b7)
configure (0.1.0b7)
core (0.1.0b7)
feedback (0.1.0b7)
network (0.1.0b7)
profile (0.1.0b7)
resource (0.1.0b7)
role (0.1.0b7)
storage (0.1.0b7)
vm (0.1.0b7)

Python (Linux) 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
$ az component update
Exception:
Traceback (most recent call last):
  File "/opt/az/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/az/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/opt/az/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/opt/az/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/opt/az/bin/easy_install'
$ sudo -H az component update
Command "/opt/az/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KbZudi/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" --no-user-cfg install --record /tmp/pip-z_36ZO-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/az/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-KbZudi/cryptography/
```

**Comment by derekbekoe** [comment]
@JasonRShaver Can you run this with `--debug` and `--show-logs` and post the output.

**Comment by johanste** [comment]
@JasonRShaver, which version of pip are you using?

**Comment by derekbekoe** [comment]
I've investigated this and it was because the apt-get install was used to install b7 and when updating, the native dependencies weren't installed.

Use `sudo apt-get update && sudo apt-get install azure-cli` to get the latest version.

Alternatively, install the native dependencies first:
```
$ sudo apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev
$ az component update
```

**Comment by derekbekoe** [comment]
Closing as:
- The reason was explained in my comment above.
- Debian package does not support `az component update` now.
