### ISSUE TITLE
Artifact downloads lots of errors and failures

### ISSUE THREAD

**Issue by shemminger** [Azure/azure-cli#12748]
Having lots of issues downloading packages. It always generates lots of noisy retry errors, and sometimes dies altogether.

Example:

$ az artifacts universal download \
>   --organization "https://msazure.visualstudio.com/" ...

Universal Packages is currently in preview.
Ignoring --cache-directory because the cache is not yet supported on OS "Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)".

[https://vsblobprodeussu2shard35.blob.core.windows.net/XXXXXXXXXXXXXXX] Try 1/5, retryable exception caught. Retrying in 00:00:01.
[https://vsblobprodeussu2shard29.blob.core.windows.net/XXXXXXXXXXXXXXX] Try 1/5, retryable exception caught. Retrying in 00:00:01.

...
d8-session-c2866ccb-98ec4818-b672fde2-c21b9d37] Try 1/5, non-retryable exception caught. Throwing. Details:
Task was requested to be canceled.
[https://vsblobprodeussu2shard25.blob.core.windows.net/XXXXXXXX] Try 1/5, retryable exception caught. Retrying in 00:00:01.
Encountered an unexpected error.
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Name or service not known) (Name or service not known))
 ---> System.AggregateException: One or more errors occurred. (Name or service not known) (Name or service not known)
 ---> System.Net.Http.HttpRequestException: Name or service not known
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Content.Common.ArtifactHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent c

**Comment by yonzhan** [comment]
Artifact

**Comment by mattduguid** [comment]
Similar issue, is random though, some runs works fine, some runs get this error, not changing anything in the pipeline

##[error]Error: An unexpected error occurred while trying to push the package. Exit code(17) and error({"@t":"2020-09-15T21:50:57.0002997Z","@m":"Ignoring --cache-directory because the cache is not yet supported on OS \"Linux 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC

**Comment by AlexChongMicrosoft** [comment]
> Similar issue, is random though, some runs works fine, some runs get this error, not changing anything in the pipeline
> 
> ##[error]Error: An unexpected error occurred while trying to push the package. Exit code(17) and error({"@t":"2020-09-15T21:50:57.0002997Z","@m":"Ignoring --cache-directory because the cache is not yet supported on OS "Linux 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC

Hi, I found a similar issue and a possible reason. May I know do you have any other pipeline\jobs update the same package?
