### ISSUE TITLE
az login fails with "NotImplementedError: APIVersion 2019-06-01 is not available"

### ISSUE THREAD

**Issue by facetoe** [Azure/azure-cli#12779]
## Describe the bug

Whenever I try to execute `az login` the command fails due to error below.

**Command Name**
`az login`

**Errors:**
```
APIVersion 2019-06-01 is not available
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 836, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
azure/cli/core/_profile.py, ln 867, in _find_using_common_tenant
    tenants = client.tenants.list()
mgmt/resource/subscriptions/subscription_client.py, ln 122, in tenants
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`

## Expected Behavior
I am logged in

## Environment Summary
```
Linux-5.4.19-100.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 3.7.6

azure-cli 2.1.0 *

```

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
It looks like the `azure-mgmt-resource` package installed is not the latest version. 

May I know how Azure CLI is installed? If via pip, could you check the version of `azure-mgmt-resource`?

```
> pip list | grep azure-mgmt-resource

azure-mgmt-resource                   8.0.1
```

**Comment by facetoe** [comment]
Sure:

```
pip3 list | grep azure-mgmt-resource
azure-mgmt-resource                             8.0.1 
```

**Comment by jiasli** [comment]
That's a little bit weird. Looks like the path in the callstack is truncated: `mgmt/resource/subscriptions/subscription_client.py`. 

The [8.1 SDK](https://github.com/Azure/azure-sdk-for-python/blob/26555afc237a5478dd9b3d13f98d3d657335251a/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py#L137-L138) does have:

```py
        elif api_version == '2019-06-01':
            from .v2019_06_01.operations import TenantsOperations as OperationClass
```

I can partially reproduce it by removing these two lines from my local SDK file `D:\cli\env38\Lib\site-packages\azure\mgmt\resource\subscriptions\_subscription_client.py`:

```
> az login
You have logged in. Now let us find all the subscriptions to which you have access...
Not able to launch a browser to log you in, falling back to device code...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HT8Q8A88U to authenticate.
The command failed with an unexpected error. Here is the traceback:

APIVersion 2019-06-01 is not available
Traceback (most recent call last):
  File "d:\cli\knack\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 625, in execute
    raise ex
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "D:\cli\env38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\profile\custom.py", line 142, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 202, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_through_interactive_flow(
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 844, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 877, in _find_using_common_tenant
    tenants = client.tenants.list()
  File "d:\cli\env38\lib\site-packages\azure\mgmt\resource\subscriptions\_subscription_client.py", line 138, in tenants
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

Could you check this file on the local machine and see it is corrupted somehow? If so, try `pip install --force-reinstall azure-mgmt-resource`

**Comment by jiasli** [comment]
If you still see this issue after updating, please let us know.
