### ISSUE TITLE
TSV output unable to decode non-ascii characters

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1277]
```
$ az resource group list -otsv
'ascii' codec can't encode characters in position 67-69: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/main.py", line 39, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result)
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/core/_output.py", line 107, in out
    output = self.formatter(obj)
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/core/_output.py", line 80, in format_tsv
    return TsvOutput.dump(result_list)
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/core/_output.py", line 311, in dump
    TsvOutput._dump_row(item, io)
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/core/_output.py", line 296, in _dump_row
    TsvOutput._dump_obj(value, stream)
  File "/Users/debekoe/demo1/lib/python2.7/site-packages/azure/cli/core/_output.py", line 278, in _dump_obj
    stream.write(str(data))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 67-69: ordinal not in range(128)
```

Python version: Python 2.7.10

Component versions:
azure-cli (0.1.0b8+1.dev20161108)
azure-cli-appservice (0.1.0b8+1.dev20161108)
azure-cli-cloud (0.1.0b8+1.dev20161108)
azure-cli-component (0.1.0b8+1.dev20161108)
azure-cli-configure (0.1.0b8+1.dev20161108)
azure-cli-context (0.1.0b8+1.dev20161108)
azure-cli-core (0.1.0b8+1.dev20161108)
azure-cli-feedback (0.1.0b8+1.dev20161108)
azure-cli-network (0.1.0b8+1.dev20161108)
azure-cli-profile (0.1.0b8+1.dev20161108)
azure-cli-resource (0.1.0b8+1.dev20161108)
azure-cli-role (0.1.0b8+1.dev20161108)
azure-cli-storage (0.1.0b8+1.dev20161108)
azure-cli-vm (0.1.0b8+1.dev20161108)

**Comment by derekbekoe** [comment]
Some of the resource group names returns had non-english characters.
