### ISSUE TITLE
Certificate-based authentication with Service Pricipal cannot read certificate

### ISSUE THREAD

**Issue by brainbug89** [Azure/azure-cli#12868]
**Describe the bug**

When trying to login via `az login --service-principal --username <APP_ID> --tenant <TENANT_ID> --password certs/azureserviceprincipal.pem --debug` this error message appears:
`[Errno 13] Permission denied: 'certs/azureserviceprincipal.pem'`

Permissions of the cert file are: `-rw-rw-rw-`
Same happens for the generated file `/home/<USER>/snap/azure-cli/7/tmpm75r64sm.pem`

**To Reproduce**

1. Create new SP with `az ad sp create-for-rbac --name ServicePrincipalName --create-cert` ([source](https://docs.microsoft.com/de-de/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#create-a-service-principal))
1. Copy generated cert file: `cp /home/<USER>/snap/azure-cli/7/tmpm75r64sm.pem certs/azureserviceprincipal.pem `
1. Try to login: `az login --service-principal --username <APP_ID> --tenant <TENANT_ID> --password certs/azureserviceprincipal.pem` (replace username and tenant with actual values)

**Expected behavior**

Login with the generated certificate should work.

**Environment summary**

Install Method: `$ sudo snap install azure-cli --classic --candidate`
az version:
```
azure-cli (2.0.25)

[...]

Python location '/snap/azure-cli/7/usr/bin/python3'
Extensions directory '/home/<USER>/snap/azure-cli/7/.azure/cliextensions'

Python (Linux) 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
```
OS version: Ubuntu 19.10
Shell: bash/zsh

**Additional context**

Debug output:
```
$ az login --service-principal --username <APP_ID> --tenant <TENANT_ID> --password certs/azureserviceprincipal.pem --debug

Command arguments: ['login', '--service-principal', '--username', '<APP_ID>', '--tenant', '<TENANT_ID>', '--password', 'certs/azureserviceprincipal.pem', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5c61d00d90>, <function OutputProducer.on_global_arguments at 0x7f5c62fdeb70>, <function CLIQuery.on_global_arguments at 0x7f5c6201b7b8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7f5c61d00e18>]
Installed command modules ['acr', 'acs', 'advisor', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.003 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.002 seconds.
Loaded module 'appservice' in 0.005 seconds.
Loaded module 'backup' in 0.007 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.029 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.490 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.003 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.006 seconds.
Loaded module 'dla' in 0.097 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'lab' in 0.150 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.028 seconds.
Loaded module 'profile' in 0.020 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'sql' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.094 seconds.
Loaded module 'vm' in 0.034 seconds.
Loaded all modules in 1.038 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/<USER>/snap/azure-cli/7/.azure/cliextensions'
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7f5c61b6e840>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f5c60b78620>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f5c62fdebf8>, <function CLIQuery.handle_query_parameter at 0x7f5c6201b840>]
attempting to read file /home/<USER>/snap/azure-cli/7/.azure/accessTokens.json as utf-8-sig
[Errno 13] Permission denied: 'certs/azureserviceprincipal.pem'
Traceback (most recent call last):
  File "/snap/azure-cli/7/lib/python3.5/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/snap/azure-cli/7/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/command_modules/profile/custom.py", line 135, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 145, in find_subscriptions_on_login
    sp_auth = ServicePrincipalAuth(password)
  File "/snap/azure-cli/7/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 882, in __init__
    with open(certificate_file, 'r') as file_reader:
PermissionError: [Errno 13] Permission denied: 'certs/azureserviceprincipal.pem'
```

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by jiasli** [comment]
You are using a very old version of Azure CLI - 2.0.25 installed by snap, which is not supported anymore. Could you install the latest Azure CLI following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest ?

I am not able to reproduce on the latest Azure CLI:

```sh
$ az ad sp create-for-rbac --name app0615 --create-cert

Changing "app0615" to a valid URI of "http://app0615", which is the required format used for service principal names
Creating a role assignment under the scope of "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590"
  Retrying role assignment creation: 1/36
Please copy /home/admin/tmpitnyahwe.pem to a safe place. When you run 'az login', provide the file path in the --password argument
{
  "appId": "a77826e2-b393-4243-a758-1030e5f211d6",
  "displayName": "app0615",
  "fileWithCertAndPrivateKey": "/home/admin/tmpitnyahwe.pem",
  "name": "http://app0615",
  "password": null,
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
}

$ ls -l tmpitnyahwe.pem
-rw-rw-r-- 1 jladmin jladmin 2677 Jun 15 05:29 tmpitnyahwe.pem

$ az login --service-principal --username a77826e2-b393-4243-a758-1030e5f211d6 --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a --password /home/admin/tmpitnyahwe.pem
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "id": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
    "isDefault": true,
    "managedByTenants": [
      {
        "tenantId": "2f4a9838-26b7-47ee-be60-ccc1fdec5953"
      }
    ],
    "name": "AzureSDKTest",
    "state": "Enabled",
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "user": {
      "name": "a77826e2-b393-4243-a758-1030e5f211d6",
      "type": "servicePrincipal"
    }
  }
```
