### ISSUE TITLE
error referencing acs when installing acr

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1287]
When installing on Windows
```
az component update --add acs --private
az component update --add acr --private
Error loading command module 'acs'
```

**Comment by SteveLasker** [comment]
And the errors continue:
```
az component update --add webapp --private
Error loading command module 'acs'
az component update --add container --private
Error loading command module 'acs'
Error loading command module 'webapp'
```

**Comment by troydai** [comment]
what's the version of `az` you're using?

**Comment by SteveLasker** [comment]
I'm doing the following:
```
AZURE_COMPONENT_PACKAGE_INDEX_URL= https://azureclinightly.blob.core.windows.net/packages
pip install --pre azure-cli --extra-index-url https://azureclinightly.blob.core.windows.net/packages
az component update --add acs --private
az component update --add acr --private
az component update --add webapp --private
az component update --add container --private
```

**Comment by yugangw-msft** [comment]
`az component update --add webapp --private` is not required

**Comment by lostintangent** [comment]
I see the same `Error loading command module 'acs'` error, when using the latest nightly CLI build (`0.1.0b8+1.dev20161109`) on macOS. When I run `az acs -h`, I notice that the `dcos` subgroup isn't displayed anymore, so it's almost like the `acs` module was reverted to an older version than I previously had before upgrading the CLI.

**Comment by yugangw-msft** [comment]
//cc:@derekbokoe
Till yesterday, the change on ACS modules was to use new versions of compute sdk. @lostintangent does your machine have existing nightly installed?

**Comment by lostintangent** [comment]
This is the output of running `az --version`. Interestingly enough, I just noticed that the version of the ACS module is oddly old, which is strange since I know that I updated it since then, so it seems like it got rolled back or something odd.

```
azure-cli (0.1.0b8+1.dev20161109)

acr (0.1.0b8+1.dev20161109)
acs (0.0.1+1.dev20161023)
appservice (0.1.0b8+1.dev20161109)
cloud (0.1.0b8+1.dev20161109)
component (0.1.0b8+1.dev20161109)
configure (0.1.0b8+1.dev20161109)
container (0.1.0b8+1.dev20161109)
context (0.1.0b8+1.dev20161109)
core (0.1.0b8+1.dev20161109)
feedback (0.1.0b8+1.dev20161109)
network (0.1.0b8+1.dev20161109)
profile (0.1.0b8+1.dev20161109)
resource (0.1.0b8+1.dev20161109)
role (0.1.0b8+1.dev20161109)
storage (0.1.0b8+1.dev20161109)
vm (0.1.0b8+1.dev20161109)
```

**Comment by SteveLasker** [comment]
@yugangw-msft do we have an update? I need the acr, acs and appservice apis to work for the Connect() keynotes

**Comment by yugangw-msft** [comment]
@derekbekoe, could you please take a look why we bring down the oldest version `0.0.1+1.dev20161023`, rather, rather the latest `0.1.0b8+1.dev20161110`? To me we might have a bug at `az component update`

**Comment by yugangw-msft** [comment]
And this version mismatch directly causes the old `acs` module is not able to invoke common api which had signature change recently
```bash
Error loading command module 'acs'
Traceback (most recent call last):
  File "C:\Users\yugangw\cli\clienv\lib\site-packages\azure\cli\core\commands\__init__.py", line 214, in get_command_table
    import_module('azure.cli.command_modules.' + mod).load_commands()
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\yugangw\cli\clienv\lib\site-packages\azure\cli\command_modules\acs\__init__.py", line 11, in <module>
    import azure.cli.command_modules.acs.generated
  File "C:\Users\yugangw\cli\clienv\lib\site-packages\azure\cli\command_modules\acs\generated.py", line 11, in <module>
    cli_command('acs dcos browse', dcos_browse)
TypeError: cli_command() missing 1 required positional argument: 'operation'
```

**Comment by derekbekoe** [comment]
For some reason, pip was choosing an older version of the `acs` module to install.
I have deleted the old versions of the nightly 'acs' module so now it installs the latest version.

```
$ az --version
azure-cli (0.1.0b8+1.dev20161110)

acs (0.1.0b8+1.dev20161110)
appservice (0.1.0b8+1.dev20161110)
cloud (0.1.0b8+1.dev20161110)
component (0.1.0b8+1.dev20161110)
configure (0.1.0b8+1.dev20161110)
context (0.1.0b8+1.dev20161110)
core (0.1.0b8+1.dev20161110)
feedback (0.1.0b8+1.dev20161110)
network (0.1.0b8+1.dev20161110)
profile (0.1.0b8+1.dev20161110)
resource (0.1.0b8+1.dev20161110)
role (0.1.0b8+1.dev20161110)
storage (0.1.0b8+1.dev20161110)
vm (0.1.0b8+1.dev20161110)
```

**Comment by yugangw-msft** [comment]
@derekbekoe, thanks. Looks like it is glitch caused by `acs` module didn't start from pre-release for 3 days and then switched to pre-release later, this caused the old non-pre-release version always got picked up
