### ISSUE TITLE
az disk create issue

### ISSUE THREAD

**Issue by george1991lt** [Azure/azure-cli#12896]
## Describe the bug

**Command Name**
`az disk create`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'import_enum'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-vm\azure\cli\command_modules\vm\custom.py", line 257, in create_managed_disk
AttributeError: 'NoneType' object has no attribute 'import_enum'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az disk create --resource-group {} --name {} --source {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62 *

```

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by qwordy** [comment]
2.0.62 is old. Can you install the latest version of Azure CLI and rerun it?

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
Any update?

**Comment by george1991lt** [comment]
I updated Azure CLI and worked for me

Kind regards,

George Antoniou
Senior Systems Engineer
ZEBRA Consultants Ltd



[cid:image001.jpg@01D62CF0.A401C180]
www.zebrac.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.zebrac.com%2F&data=02%7C01%7Cv-ogetow%40microsoft.com%7C3901b822131544edec4408d7e074affb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637224664096418482&sdata=igrLfFkKuMbxQnVtWytdq%2B0mJAGBMwSBszsn6c%2B%2B7IE%3D&reserved=0>
T: +357 22028128
F: +357 22028129
M: +357 96841765
E: georgea@zebrac.com<mailto:georgea@zebrac.com>

[cid:image002.png@01D62CF0.A401C180]<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.facebook.com%2FZEBRAConsultants&data=02%7C01%7Cv-ogetow%40microsoft.com%7C3901b822131544edec4408d7e074affb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637224664096418482&sdata=70rDZUSSeRcR1SctEUQQ8EHOfloqqQbHdcE73XEOeZA%3D&reserved=0> [cid:image003.png@01D62CF0.A401C180] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fzebra-consultants-ltd&data=02%7C01%7Cv-ogetow%40microsoft.com%7C3901b822131544edec4408d7e074affb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637224664096428477&sdata=IbA4d0Gm2CDbXQovXyaHlIpdGdeS415b7YRlYuNztAM%3D&reserved=0>  [cid:image004.png@01D62CF0.A401C180] <https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Ftwitter.com%2Fzebrac&data=02%7C01%7Cv-ogetow%40microsoft.com%7C3901b822131544edec4408d7e074affb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637224664096428477&sdata=j26u8vWwA55jZUUdmEbFokRi1HUorNU11%2F9X5HRiAUk%3D&reserved=0>
[cid:image005.png@01D62CF0.A401C180]

**Comment by qwordy** [comment]
Glad to know that.
BTW, the images are not shown correctly in Github.
