### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'U:\\\\'

### ISSUE THREAD

**Issue by graydwarf** [Azure/azure-cli#12907]
I'm following the instructions found here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

and when I type 'az login' like this:
C:\Users\me\source\repos> az login

I get this error message:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli\azure\cli\__main__.py", line 33, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\__init__.py", line 585, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\azlogging.py", line 30, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\commands\__init__.py", line 28, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\azure-cli-core\azure\cli\core\extension\__init__.py", line 18, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\knack\knack\config.py", line 39, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\knack\knack\util.py", line 111, in ensure_dir
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_1mlo87m\knack\knack\util.py", line 108, in ensure_dir
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'U:\\\\'
```

***edit - ignore this statement and see below. - I searched through env vars for anything U: related and found nothing. I have no U: drives although I could have easily had one given our overzealous IT department. 
***

Pretty sure this worked a few months back when I was stepping through it. I was just coming back to it and the documentation said it was ok to rerun the installer so I did.

I tried uninstalling and reinstalling. Same issue.

I do have a network U:\ drive where my user profile is stored apparently. IT thing. Think I may have saw a related issue to this. ... 

*** Edit
Looked for existing issues open or closed and I'm not seeing any clear solutions. Any help would be appreciated.
***

**Comment by qianwens** [comment]
@jiasli please help take a look.

**Comment by jiasli** [comment]
Per the source code, https://github.com/Azure/azure-cli/blob/2e4010d6576b9334498b9b3c48e6aa50f145e8d6/src/azure-cli-core/azure/cli/core/_environment.py#L9

Azure CLI uses the value of `AZURE_CONFIG_DIR` as the config folder. Could you check if the value has been changed?

```
# cmd
echo %AZURE_CONFIG_DIR%

# PowerShell
echo $env:AZURE_CONFIG_DIR
```

**Comment by graydwarf** [comment]
> Per the source code,
> 
> https://github.com/Azure/azure-cli/blob/2e4010d6576b9334498b9b3c48e6aa50f145e8d6/src/azure-cli-core/azure/cli/core/_environment.py#L9
> 
> Azure CLI uses the value of `AZURE_CONFIG_DIR` as the config folder. Could you check if the value has been changed?
> 
> ```
> # cmd
> echo %AZURE_CONFIG_DIR%
> 
> # PowerShell
> echo $env:AZURE_CONFIG_DIR
> ```

Nothing is returned by either. echoing %temp% returns the path as expected in both.

**Comment by jiasli** [comment]
Looks like we are hitting the same issue as https://github.com/Azure/azure-cli/issues/9562.

Could you share your env vars?

```sh
# cmd
set

# pwsh
ls Env:
```

It could be caused by `HOME` env var being changed, thus causing `expanduser` to return `HOME`'s value as `~`. This issue only happens on Python 3.6 which is bundled with Azure CLI. 

https://github.com/python/cpython/blob/3.6/Lib/ntpath.py#L324-L325

```py
    if 'HOME' in os.environ:
        userhome = os.environ['HOME']
```

`HOME` support is later removed by PR https://github.com/python/cpython/pull/12282. `expanduser` on Python 3.8 doesn't have this issue anymore. 

https://github.com/python/cpython/blob/3.8/Lib/ntpath.py#L304-L305

```py
    if 'USERPROFILE' in os.environ:
        userhome = os.environ['USERPROFILE']
```

**Comment by jiasli** [comment]
Thanks @laserljy for another finding. 

As cygwin is setting `HOME` as `C:\cygwin64\home\<user>`, this interferes with `expanduser('~')` on Python < 3.8, thus causing Azure CLI to save config files to `C:\cygwin64\home\<user>\.azure` instead. 

To save Azure CLI config to the real `~\.azure` while keeping `HOME` working or cygwin, you may install Azure CLI with Python 3.8 as discussed above, but make sure `python` and `pip` are the Windows ones, not cygwin ones:

```pwsh
> where.exe python
C:\Users\<user>\AppData\Local\Programs\Python\Python38\python.exe
C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\python.exe
> where.exe pip
C:\Users\<user>\AppData\Local\Programs\Python\Python38\Scripts\pip.exe
```

You can tweak `PATH` env var to choose the correct `python` and `pip` to use.
