### ISSUE TITLE
Subscription:                 /bin/sh: az: command not found child_process.js:669     throw err;     ^  Error: Command failed: az account show

### ISSUE THREAD

**Issue by RajeevTomar** [Azure/azure-cli#12953]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by qianwens** [comment]
@jiasli  to take a look.

**Comment by yonzhan** [comment]
add to S169

**Comment by RajeevTomar** [comment]
I am getting this issue when try to debug remotely using dbgproxy.
Full Log:

Error: Command failed: az account show
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at shell (/usr/local/lib/node_modules/cloud-debug-tools/dbgproxy-impl.js:18:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/cloud-debug-tools/dbgproxy-impl.js:97:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by jiasli** [comment]
Looks like you are invoking `az` with Node.js `child_process.js`. I am not an expert in Node.js, but you may check if `az` in on the `PATH` of Node.js. In Bash, please run 

```sh
$ which az
/usr/bin/az
```

Then try the full path `/usr/bin/az` in your script.

**Comment by yonzhan** [comment]
@RajeevTomar was your issue resolved by above?

**Comment by RajeevTomar** [comment]
No. 
I am trying to debug azure function remotely in VS code.
when i call below command it throw the error i posted earlier.
dbgproxy my-function.azurewebsites.net

**Comment by jiasli** [comment]
@RajeevTomar, could you provide the information as suggested in https://github.com/Azure/azure-cli/issues/12953#issuecomment-611981402? Also, as this is not really related to Azure CLI itself, you may open a support ticket to Azure Function team to get the right expert to look at it.

**Comment by RajeevTomar** [comment]
Thank you for your support.
I will create the ticket to Azure function Team.
