### ISSUE TITLE
az backup protect enable-for-azurefileshare fails

### ISSUE THREAD

**Issue by hscofield** [Azure/azure-cli#13051]
BEGIN TEMPLATE
===============
**If possible, a browser will be opened to aka.ms/azcli/issues to create an issue.**
**You can also run `az feedback --verbose` to emit the full issue draft to stderr.**
**Azure CLI repo: aka.ms/azcli/issues**
**Azure CLI Extensions repo: aka.ms/azcli/ext/issues**

## Describe the bug
Attempting to assign a Azure File share to a backup policy is providing an error.  The Policy is for the type Azure File Share, and it actually also fails on the using the cloud shell as well.  I have been able to add the file share to the policy via the web GUI, but this is being added to automation, so need to be able to via az cli.

**Command Name**
`az backup protection enable-for-azurefileshare`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_base.py", line 301, in enable_for_azurefileshare
    storage_account, policy_name)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_afs.py", line 66, in enable_for_AzureFileShare
    container_uri = helper.get_protection_container_uri_from_id(protectable_item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection enable-for-azurefileshare --azure-file-share {} --policy-name {} --storage-account {} --resource-group {} --vault-name {}`

## Environment Summary
```
Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-redhat-7.7-Maipo
Python 3.6.8
Installer: RPM

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
backup

**Comment by hscofield** [comment]
Tested this with az cli 2.4.0 and still does not work.

**Comment by pvrk** [comment]
@sambitratha : Can you please take a look on this?

**Comment by sambitratha** [comment]
@hscofield  i see you're using a previous version of Azure cli. This was a bug introduced in CLI because of service changes. It has been fixed in the latest release 2.6.0. Please upgrade Azure CLI and check if you're still facing this issue.

**Comment by pvrk** [comment]
@hscofield : A gentle reminder. Please check and update.

**Comment by pvrk** [comment]
Closing this bug since we have verified that this is fixed. Can re-open if this issue re-occurs with version >= 2.6.0
