### ISSUE TITLE
az account list-locations fails

### ISSUE THREAD

**Issue by systo** [Azure/azure-cli#13073]
## Describe the bug

**Command Name**
``az account list-locations

**Errors:**

The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/alex/.azure/commands/2020-04-17.19-30-28.account_list-location.202.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 486, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 80, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 101, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/alex/.azure/commands/2020-04-17.19-30-28.account_list-location.202.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks

**Comment by arrownj** [comment]
Hi @systo , could you please help check the permission in `/home/alex/.azure`? It's an exception throwed by logging. It's wired that the file is read-only.

**Comment by arrownj** [comment]
Hi @systo , I will close this issue first as there are no more input. You can reopen it if you still encounter it, or you can just submit a new one.
