### ISSUE TITLE
az sql server ad-admin create failure

### ISSUE THREAD

**Issue by troyridge** [Azure/azure-cli#13077]
## Describe the bug
Fails with error below

**Command Name**
`az sql server ad-admin create`

**Errors:**
```
az sql server ad-admin create: error: the following arguments are required: --display-name/-u, --object-id/-i
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

- `az sql server ad-admin create --displayname {} --objectid {} --resource-group {} --server {} --subscription {}`

## Environment Summary
```azure-cli 2.2.0 *

```
## Additional Context
The command failed with an unexpected error. Here is the traceback:

create_or_update() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/sql/custom.py", line 2074, in server_ad_admin_set
    properties=kwargs)
TypeError: create_or_update() missing 1 required positional argument: 'parameters'

**Comment by yonzhan** [comment]
sql

**Comment by demiliani** [comment]
Same error.

**Comment by nirmal5202** [comment]
try running those commands separately.
Here is one approach: 
`az sql server ad-admin create --display-name/-u
 az sql server ad-admin create --object-id/-i`

**Comment by RakeshMohanMSFT** [comment]
@troyridge This is fixed. Please upgrade to the latest version of az cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
