### ISSUE TITLE
Error: "Could not find a version that satisfies the requirement azure-cli" on azure ubuntu

### ISSUE THREAD

**Issue by chaliy** [Azure/azure-cli#1308]
Not sure if this correct place to report this issue, but let me try.

Installation using PIP files on VM create in Azure using UbuntuLTS alias (Ubuntu Server: 14.04LTS)

```
ops@chaliy-linux-temp:~$ sudo pip3 install azure-cli
Downloading/unpacking azure-cli
  Could not find a version that satisfies the requirement azure-cli (from versions: 0.1.0b4, 0.1.0b7, 0.1.0b8)
Cleaning up...
No distributions matching the version for azure-cli
Storing debug log for failure in /home/ops/.pip/pip.log
ops@chaliy-linux-temp:~$ sudo pip install azure-cli
Downloading/unpacking azure-cli
  Could not find a version that satisfies the requirement azure-cli (from versions: 0.1.0b4, 0.1.0b7, 0.1.0b8)
Cleaning up...
No distributions matching the version for azure-cli
Storing debug log for failure in /home/ops/.pip/pip.log
```
And
```
ops@chaliy-linux-temp:~$ cat /home/ops/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Sun Nov 13 11:47:43 2016
Downloading/unpacking azure-cli
  Getting page https://pypi.python.org/simple/azure-cli/
  URLs to search for versions for azure-cli:
  * https://pypi.python.org/simple/azure-cli/
  Analyzing links from page https://pypi.python.org/simple/azure-cli/
    Found link https://pypi.python.org/packages/43/96/89adf026ed3a849b4fa00aeda1d4a32d0c7d6195167d5bff96d72fb8c278/azure-cli-0.1.0b4.tar.gz#md5=24bfdb7f0f5828c62874230f83e72a80 (from https://pypi.python.org/simple/azure-cli/), version: 0.1.0b4
    Found link https://pypi.python.org/packages/8b/eb/38cdea1b151b09b779a8659272ca44ae0e942a9faa81ab6e7d5de648ffa4/azure-cli-0.1.0b7.tar.gz#md5=be4c3350c08b7260cdd6d5c2bd216373 (from https://pypi.python.org/simple/azure-cli/), version: 0.1.0b7
    Found link https://pypi.python.org/packages/93/d9/64ed394f8995addfa60256cd37f03a68b1ac34ab301f160c8d2444d2af13/azure-cli-0.1.0b8.tar.gz#md5=d435e281728616cdd8e4a09a53543b38 (from https://pypi.python.org/simple/azure-cli/), version: 0.1.0b8
  Ignoring link https://pypi.python.org/packages/43/96/89adf026ed3a849b4fa00aeda1d4a32d0c7d6195167d5bff96d72fb8c278/azure-cli-0.1.0b4.tar.gz#md5=24bfdb7f0f5828c62874230f83e72a80 (from https://pypi.python.org/simple/azure-cli/), version 0.1.0b4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/8b/eb/38cdea1b151b09b779a8659272ca44ae0e942a9faa81ab6e7d5de648ffa4/azure-cli-0.1.0b7.tar.gz#md5=be4c3350c08b7260cdd6d5c2bd216373 (from https://pypi.python.org/simple/azure-cli/), version 0.1.0b7 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/93/d9/64ed394f8995addfa60256cd37f03a68b1ac34ab301f160c8d2444d2af13/azure-cli-0.1.0b8.tar.gz#md5=d435e281728616cdd8e4a09a53543b38 (from https://pypi.python.org/simple/azure-cli/), version 0.1.0b8 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement azure-cli (from versions: 0.1.0b4, 0.1.0b7, 0.1.0b8)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for azure-cli
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for azure-cli
```

**Comment by derekbekoe** [comment]
@chaliy What version of pip did you have installed?

The version of pip that comes with `apt-get install pip/pip3` is not recent. I got 1.5.4 which was released in 2014.
Older versions of pip did not install pre-release packages by default.

I recommend upgrading pip:
```
$ pip/pip3 install --upgrade pip
```

---

Steps to Reproduce:
1. Create an UbuntuLTS VM - `az vm create -g <RG> -n <NAME> --image UbuntuLTS`
2. SSH to VM
3. `sudo apt-get update && sudo apt-get install python3-pip`
4. Show pip version
```
$ pip3 --version
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
```
```
$ pip3 install azure-cli
Downloading/unpacking azure-cli
  Could not find a version that satisfies the requirement azure-cli (from versions: 0.1.0b4, 0.1.0b7, 0.1.0b8)
Cleaning up...
No distributions matching the version for azure-cli
```

Pip Release Notes - https://pip.pypa.io/en/stable/news/

**Comment by derekbekoe** [comment]
Alternatively, use `pip install --pre azure-cli`.

**Comment by derekbekoe** [comment]
Marking this as FAQ and closing.
In old versions of pip, the `--pre` flag is required. Alternatively, upgrade pip.

**Comment by chaliy** [comment]
Thank you, this works.

**Comment by Jumaev** [comment]
λ pip install forms
Collecting forms
  Could not find a version that satisfies the requirement forms (from versions: )
No matching distribution found for forms

Same problem i am facing... any suggestions

**Comment by LEUMUS** [comment]
i have a similar problem but with installing python-xmpp, help me out

1.ERROR: Could not find a version that satisfies the requirement xmpp (from versions: none)
2.ERROR: No matching distribution found for xmpp

**Comment by lokesh-infolob** [comment]
ERROR: Could not find a version that satisfies the requirement azure.mgmt.spring (from versions: none)
ERROR: No matching distribution found for azure.mgmt.spring
