### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'

### ISSUE THREAD

**Issue by lexguy20** [Azure/azure-cli#13093]
I am trying to generate sas token as:
az iot hub generate-sas-token --duration 3600 -n <hub name>
and getting following error:
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1324, in iot_hub_monitor_events
    repair=repair, login=login, content_type=content_type, device_query=device_query)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 1366, in _iot_hub_monitor_events
    target = get_iot_hub_connection_string(cmd, hub_name, resource_group_name, include_events=True, login=login)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/common/_azure.py", line 112, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
  File "/home/nraza/.azure/cliextensions/azure-cli-iot-ext/azext_iot/_factory.py", line 28, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'

Any idea? Thanks

**Comment by yonzhan** [comment]
iot hub

**Comment by jlian** [comment]
@digimaun and @iluican can you take a look?

**Comment by digimaun** [comment]
This is an expected issue - there was a breaking change in Azure CLI due to updating the IoT Hub mgmt SDK (related to the SDK itself). Older versions of the IoT extension will face this issue but updating should resolve as the submitter has pointed out.

BTW it is highly recommended you delete the deprecated `azure-cli-iot-ext` and install `azure-iot` (go forward modern extension Id for Azure IoT).

We're working in the background on making that more clear in various docs and references.

**Comment by digimaun** [comment]
#please-close

**Comment by askanymark** [comment]
I'm getting the same error with `azure-iot` extension:

```python
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/arm.py", line 738, in handler
    client = factory(context_copy.cli_ctx) if factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/iot/_client_factory.py", line 9, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```
It happens, when I try to execute this command:

`az iot hub show --query properties.eventHubEndpoints.events.endpoint --name "HubNameHere"`

**Comment by digimaun** [comment]
Hi @askanymark . That command is actually not coming from the IoT extension, its from the base CLI. Not sure what your Azure CLI version is -- can you try upgrading and re-running the same command? I am unable to repro the issue with the same command using Azure CLI `2.5.1` (also have `azure-iot` 0.9.1 installed but that's a side point).

**Comment by askanymark** [comment]
@digimaun, I reinstalled through `apt`, as the `curl` way on Ubuntu doesn't work for me at the moment. Says `azure-cli` repo doesn't have a release file:

```bash
Err:19 https://packages.microsoft.com/repos/azure-cli focal Release
  404  Not Found [IP: 40.85.80.91 443]
```

My CLI version is 2.0.81 and extension is 0.9.1. I'll try reinstalling as described [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).

**Comment by MikeWilcoxMicrosoft** [comment]
Hmm.. 

$ az extension remove --name azure-cli-iot-ext
The extension azure-cli-iot-ext is not installed.
$ az extension add --name azure-cli-iot-ext
An error occurred. Pip failed with status code 1. Use --debug for more information.
$

**Comment by aliyevmirzakhan** [comment]
This issue is still persistent even with new `azure-iot` extension (see below)
`az iot hub policy show --name service --query primaryKey --hub-name <My IoT hub name>`


`
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 484, in default_command_handler
    client = client_factory(cmd.cli_ctx, command_args) if client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/iot/_client_factory.py", line 9, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
`

**Comment by digimaun** [comment]
@aliyevmirzakhan What version of Azure CLI are you using? This command `az iot hub policy show` does not come from the `azure-iot` extension it is coming from the base CLI. Please try updating your Az CLI installation and try the command again.
