### ISSUE TITLE
Webapp:az zip deploy through pipelines succeeds, but reports failure after loop.

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-cli#13141]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
https://bitbucket.org/microsoft/azure-web-apps-deploy/src/master/pipe/pipe.sh

Inside the "run az webapp deployment" command, the zip is deployed and unpacked. Then that command seems to loop on a query to "GET /api/deployments/latest HTTP/1.1" It will loop while it gets a 202 response, until finally it gets a 503, at which time python just breaks trying to parse the response. 

```
INFO: Running deployment command...
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): XXXXX.scm.azurewebsites.net:443
DEBUG: urllib3.connectionpool : https://XXXXX.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 202 557
INFO: Running deployment command...
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): XXXXX.scm.azurewebsites.net:443
DEBUG: urllib3.connectionpool : https://XXXXX.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 202 557
INFO: Running deployment command...
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): XXXXX.scm.azurewebsites.net:443
DEBUG: urllib3.connectionpool : https://XXXXX.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 202 557
INFO: Running deployment command...
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): XXXXX.scm.azurewebsites.net:443
DEBUG: urllib3.connectionpool : https://XXXXX.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 503 326
ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
  
```

**To Reproduce**
deploy a zip to an app service using the same command as the bitbucket pipeline?

**Expected behavior**
after successful deployment, success is reported.

**Environment summary**
Bitbucket pipeline docker

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
bug

**Comment by panchagnula** [comment]
please run command with --timeout parameter to increase the time out so that we don't timeout & throw a warning message since we were not able to get the status of the long running operation.
