### ISSUE TITLE
az interactive failed to run

### ISSUE THREAD

**Issue by fookslala2004** [Azure/azure-cli#13210]
gerald@Azure:~$ az interactive
The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/gerald/.azure/commands/2020-04-27.15-41-59.interactive.354.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 486, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 80, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 101, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/gerald/.azure/commands/2020-04-27.15-41-59.interactive.354.log'

**Comment by yonzhan** [comment]
interactive

**Comment by jiasli** [comment]
Let's centralize similar issues to https://github.com/Azure/azure-cli/issues/13855.
