### ISSUE TITLE
az extension add -n aro --index https://az.aroapp.io/stable  fails

### ISSUE THREAD

**Issue by jarielpa** [Azure/azure-cli#13241]
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\\.azure\cliextensions\aro\pyreadline-2.1-py3.6.egg-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\log.py", line 64, in format
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %c requires int or char
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 624, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\operations.py", line 224, in add_extension
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\operations.py", line 177, in _augment_telemetry_with_ext_info
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 73, in version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 133, in get_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 85, in metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 151, in get_metadata
Message: 'extension % contains invalid metadata for Python Package'
Arguments: ('aro',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\\.azure\cliextensions\aro\pyreadline-2.1-py3.6.egg-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\log.py", line 64, in format
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %c requires int or char
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 624, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\operations.py", line 226, in add_extension
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 111, in experimental
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 85, in metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 151, in get_metadata
Message: 'extension % contains invalid metadata for Python Package'
Arguments: ('aro',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\<name>\.azure\cliextensions\aro\pyreadline-2.1-py3.6.egg-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\log.py", line 64, in format
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %c requires int or char
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 624, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\operations.py", line 229, in add_extension
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 98, in preview
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 85, in metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 151, in get_metadata
Message: 'extension % contains invalid metadata for Python Package'
Arguments: ('aro',)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add -n aro --index https://az.aroapp.io/stable  fails

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.0

Extensions:
aro 3.1.0

```

**Comment by haroldrandom** [comment]
I guess the reason is the same as https://github.com/Azure/azure-cli/issues/13240.

Sincerely sorry for the incovenience, we fixed it #13222
The next release would be tomorrow.

If it's blocking for now, please try our Azure CLI edge build https://github.com/Azure/azure-cli#edge-builds to unblock you

**Comment by haroldrandom** [comment]
As far as I know, aro has onboarded to Azure CLI core, maybe a workaround could be `az aro -h`.

**Comment by haroldrandom** [comment]
As a workaround, installing older version of Azure CLI could fix.
You could try `pip install azure-cli==2.4.0` if you are in a Python (virtual) env. but this could polute your env if you have other Python depencies in the same Python env.
Another option for windows is to download [2.4.0 in MSI format](https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.4.0.msi) if you are using MSI installation. Better uninstall the previous version before install a new one.

**Comment by haroldrandom** [comment]
New Azure CLI 2.5.1 is released the bug should be fixed, please upgrade to the newer version.

Sorry for the trouble. We should be more careful. :(
