### ISSUE TITLE
Current Windows CLI Download produces error output

### ISSUE THREAD

**Issue by snapfisher** [Azure/azure-cli#13256]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.5.0, downloaded on 29-April-20

**Describe the bug**
Whenever I run a command, I receive logging error output.  For example, here is simply az --version:

PS C:\Users\pfisher> az --version
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\pfisher\.azure\cliextensions\azure-cli-iot-ext\paho_mqtt-1.5.0-py3.6.egg-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\log.py", line 64, in format
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %c requires int or char
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 207, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 107, in show_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\util.py", line 200, in get_az_version_string
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 73, in version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 133, in get_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 85, in metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 151, in get_metadata
Message: 'extension % contains invalid metadata for Python Package'
Arguments: ('azure-cli-iot-ext',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\pfisher\.azure\cliextensions\azure-cli-iot-ext\pyrsistent-0.15.7-py3.6.egg-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 993, in emit
    msg = self.format(record)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\log.py", line 64, in format
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 839, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 576, in format
    record.message = record.getMessage()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %c requires int or char
Call stack:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 207, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 107, in show_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\util.py", line 200, in get_az_version_string
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 73, in version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 133, in get_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 85, in metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 151, in get_metadata
Message: 'extension % contains invalid metadata for Python Package'
Arguments: ('azure-cli-iot-ext',)
azure-cli                          2.5.0

command-modules-nspkg              2.0.3
core                               2.5.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-cli-iot-ext                 1.14.0
azure-devops                      1.25.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\pfisher\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

But I get something similar on every command

**To Reproduce**
Install and run a command

**Expected behavior**
I should not receive the error output

**Environment summary**
MSI Install on Windows 10.

**Additional context**

**Comment by snapfisher** [comment]
I have no idea why lines in the above are crossed through, I just copied it from PowerShell.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look, thanks

**Comment by fengzhou-msft** [comment]
will release a fix in 2.5.1 today.

**Comment by fengzhou-msft** [comment]
Fix is released. Please try with azure-cli 2.5.1.
