### ISSUE TITLE
az role definition update returns unexpected error

### ISSUE THREAD

**Issue by philspokas** [Azure/azure-cli#13299]
## Describe the bug
Execute az role definition update with what appears to be a valid role definition json returns unexpected error with traceback

**Command Name**
``az role definition update --role-definition "customrole.json"

**Errors:**
The command failed with an unexpected error. Here is the traceback:

'roleName'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\command_modules\role\custom.py", line 56, in update_role_definition
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli\azure\cli\command_modules\role\custom.py", line 85, in _create_update_role_definition
KeyError: 'roleName'

## To Reproduce:
1. create a valid custom role json
2. execute az role definition create with the json file
3. update the json with the id of the custom role
4. run execute az role definition update with the json file

## Expected Behavior
command doesn't throw an exception, rather describes what's wrong with the json or command syntax 

Note that making what look like valid updates to the json fail similarly. These were backed out to verify the basics of create and then update.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.0 *

Extensions:
application-insights 0.1.1
azure-devops 1.25.6
dev-spaces 1.0.3

```

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Hi @philspokas , actually the formats of `az role definition update` and `az role definition create` are different. You can reference #14411 where @jiasli gave us a very clear explanation.

**Comment by arrownj** [comment]
Hi @philspokas , I will close this issue first. Please reach us if you have other concerns. Thanks
