### ISSUE TITLE
AZ commands fail in Azure Cloud Shell

### ISSUE THREAD

**Issue by stgraves** [Azure/azure-cli#13338]
## Describe the bug
Created an AKS cluster using Azure Cloud Shell
Closed browser window for Azure Cloud Shell
Removed cloud-shell-storage-southcentralus resource group
Opened new browser window and connected to Azure Cloud Shell
Installed Azure CLI
Run an "az" command fails with an error

**Command Name**
az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

**Errors:**
The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/steven/.azure/commands/2020-05-05.14-45-51.aks_get-credentials.342.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 510, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 84, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 106, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/steven/.azure/commands/2020-05-05.14-45-51.aks_get-credentials.342.log'

## Expected Behavior
Expect az commands to successfully run

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
connectedk8s 0.1.3
k8sconfiguration 0.1.6
aks-preview 0.4.44


<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
seems duplicated with https://github.com/Azure/azure-cli/issues/13334

**Comment by Jen7714** [comment]
Closing this issue for now as it seems to relate to the issue mentioned above.
