### ISSUE TITLE
'read-only file system' error when trying to delete group from azure cli 

### ISSUE THREAD

**Issue by lemonez** [Azure/azure-cli#13334]
I was trying to delete the storage that had been created to do a tutorial (maybe I was not supposed to...I'm just learning how this works) and it gave me the Python error message below.

The command failed with an unexpected error. 
*Command Name**
`az group delete`

**Errors:**
```
az group delete: error: argument --name/-n/--resource-group/-g: expected one argument
```

## To Reproduce:
(traceback...)

$ az group delete --name "cloud-shell-storage-westus"
Are you sure you want to perform this operation? (y/n): y
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 996, in emit
    self.flush()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 976, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 50, in <module>
    az_cli.logging.end_cmd_metadata_logging(exit_code)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 178, in end_cmd_metadata_logging
    self.command_metadata_logger.info("exit code: %s", exit_code)
Message: 'exit code: %s'
Arguments: (0,)

$ az group list
The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/ezra/.azure/commands/2020-05-05.06-17-04.group_list.579.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 510, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 84, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 106, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/ezra/.azure/commands/2020-05-05.06-17-04.group_list.579.log'

## Expected Behavior

I thought it would delete the cloud storage just as it had deleted a resource group, but now I see that the cloud storage was probably supposed to persist across sessions so that you can save scripts, etc.

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yungezz** [comment]
hi @lemonez are you trying to delete "cloud-shell-storage-westus" inside cloudshell?

**Comment by lemonez** [comment]
Hi @yonzhan  yes I thought I should delete the storage so as not to accrue charges. I then realized that storage is super cheap, so it is probably unnecessary, but it still seemed buggy to not be able to if I wanted to.

**Comment by jiasli** [comment]
Let's centralize similar issues to https://github.com/Azure/azure-cli/issues/13855.

**Comment by navba-MSFT** [comment]
@lemonez Apologies for the delayed response. Could you please let us know if you are still facing the same issue?

refer #Azure/azure-cli#13855 for the similar issue. Awaiting your reply.

**Comment by lemonez** [comment]
Hi, thanks for the follow-up. I'm sorry, this was so long ago that I have no idea what exact commands / steps I'd need to take to try to repro this. I am not currently affected by this issue.

**Comment by navba-MSFT** [comment]
@lemonez Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
