### ISSUE TITLE
az container exec in azure devops throws (25, 'Inappropriate ioctl for device')

### ISSUE THREAD

**Issue by peturh** [Azure/azure-cli#13352]
Az version 2.3.1

**Describe the bug**

When trying to use Azure DevOps Pipelines Azure CLI task `az container exec` the shell outputs errors.

**To Reproduce**

`az container exec --resource-group myRG --name myImageName --exec-command ./run.sh`

**Expected behavior**

To be able to display the output of the container.

**Environment summary**

Azure Devops free agent running Ubuntu 18.04

**Additional context**

This error message is thrown:

```
 [command]/bin/bash /home/vsts/work/_temp/azureclitaskscript1588671209398.sh
 The command failed with an unexpected error. Here is the traceback:
 
 (25, 'Inappropriate ioctl for device')
 Traceback (most recent call last):
   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
     cmd_result = self.invocation.execute(args)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
     raise ex
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
     results.append(self._run_job(expanded_arg, cmd_copy))
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
     six.reraise(*sys.exc_info())
   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
     raise value
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
     result = cmd_copy(params)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
     return self.handler(*args, **kwargs)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
     return op(**command_args)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 621, in container_exec
     _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 655, in _start_exec_pipe
     oldtty = termios.tcgetattr(sys.stdin)
 termios.error: (25, 'Inappropriate ioctl for device')
 
 To open an issue, please run: 'az feedback'
```

**Comment by dasumner** [comment]
Was there any progress on this issue?

**Comment by fastpolygon** [comment]
@peturh This issue only seems to occur when executing `az container exec` from an Azure CLI task on an Ubuntu Agent.  These tasks succeed (or at least do not fail from an ioctl error) when run from a **vs2017-win2016** agent, which may serve as a workaround.

**Comment by peturh** [comment]
> @peturh This issue only seems to occur when executing `az container exec` from an Azure CLI task on an Ubuntu Agent. These tasks succeed (or at least do not fail from an ioctl error) when run from a **vs2017-win2016** agent, which may serve as a workaround.

That stopped the ioctl error, however, now the logs are cut of half way. Any idea?

**Comment by natdan** [comment]
Is there any movement on this issue (and linked here)? I'm still seeing it in ubuntu-latest (I think it is 20.04) and az version 2.16 in the agents... Is there any other workaround?
BTW same commands issued from my local computer's shell work well...

**Comment by kufelm** [comment]
Any news?

**Comment by yonzhan** [comment]
container instance service team should look into this

**Comment by dkkapur** [comment]
tagging appropriate person for followup! @macolso

**Comment by molafson** [comment]
I get a similar error when running `az container exec` using the Azure/CLI Github action (https://github.com/marketplace/actions/azure-cli-action)

```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Not a tty')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 624, in container_exec
    _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 658, in _start_exec_pipe
    oldtty = termios.tcgetattr(sys.stdin)
termios.error: (25, 'Not a tty')
```

**Comment by miqm** [comment]
@macolso - any update on this?

**Comment by gary-x0pa** [comment]
Still facing this error now.

**Comment by gary-x0pa** [comment]
In the end I emulated tty using the following
```
script --return --quiet -c "az container exec --resource-group myRG --name myImageName --exec-command ./run.sh'" /dev/null
```

**Comment by lotaezhao** [comment]
This is still a problem even with Azure CLI 2.29.0 using Azure DevOps agent ubuntu-latest image. This issue has been open for over a year and a half and we still can't run 'az container exec' commands on linux.

As a workaround I will try to run the task on a windows agent but most of the steps need to run on a Linux agent so I will have to split this one out.

**Comment by vgan** [comment]
I noticed something strange about this, I can run container exec commands on my Ubuntu 20.04.3 LTS shell ok while I'm logged in via SSH. I only see this error when I try to schedule via cron.

**Comment by navba-MSFT** [comment]
@peturh Apologies for the late reply. Could you please confirm if you are still running into this issue ? Awaiting your reply.

**Comment by bcouavoux** [comment]
Hi,

I don't have exactly the same error but it looks like it. On my pipeline with the ubuntu-latest hosted agent and with the az container exec command :

az container exec --resource-group $rgContainer --name $containerControllerName --exec-command $command 

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 637, in container_exec
    _start_exec_pipe_linux(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 673, in _start_exec_pipe_linux
    old_tty = termios.tcgetattr(stdin_fd)
termios.error: (25, 'Inappropriate ioctl for device')
To open an issue, please run: 'az feedback'

The command work perfectly on the azure cloud shell

**Comment by melezhik** [comment]
I have this error on `2.34.1` az cli version

```
azure-cli                         2.34.1 *

core                              2.34.1 *
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
```

**Comment by michaelelleby** [comment]
@navba-MSFT this is still an issue, please reopen this issue.

**Comment by pletnes** [comment]
We had the same yesterday, a project with the exact same setup on azure devops.

**Comment by mcapinha-mxp** [comment]
I've just had the exact same issue yesterday, using `az containerapp exec`

**Comment by dsfrederic** [comment]
Same issue here!

**Comment by ggeorgovassilis** [comment]
Why is this issue closed?

**Comment by derik-roby** [comment]
Same issue here

**Comment by vandanchev** [comment]
Faced the same issue and managed to work around it by switching to `Invoke-AzContainerInstanceCommand`

**Comment by paddymccallan-izon** [comment]
Still seeing issue

**Comment by paddymccallan-izon** [comment]
only way I could get this to work at all was using ubuntu-latest image on azure pipeline, and thanks to @gary-x0pa's answer above. Previously had setup linux vm and had used ntfy to trigger post commands but was unable to get past that even with  `script --return --quiet`


```
- task: AzureCLI@2
  displayName: 'Run Post-Install Script in Container'
  inputs:
    azureSubscription: 'EdgeService'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      script --return --quiet \
        -c "az container exec \
            --resource-group group_name \
            --name $(imageName) \
        /dev/null
```

**Comment by esdccs1** [comment]
Getting this issue running against container app on an azure devops Ubuntu 22.04 agent

     az containerapp exec -n my-container -g my-rg   --command "./manage.py my_command"


```
Please ensure there is an alive replica. 
Exception in thread Thread-1 (read_ssh):
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/containerapp/_ssh_utils.py", line 123, in read_ssh
    _resize_terminal(connection)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/containerapp/_ssh_utils.py", line 154, in _resize_terminal
    size = os.get_terminal_size()
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
    mode = tcgetattr(fd)
           ^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

**Comment by programista-zacny** [comment]
I'm trying to
`az containerapp exec --subscription subscription -g group -n name --command "cat /etc/hosts" >> test.log` and it fails...
```
Exception in thread Thread-1 (read_ssh):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.58.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/containerapp/_ssh_utils.py", line 123, in read_ssh
    _resize_terminal(connection)
  File "/opt/homebrew/Cellar/azure-cli/2.58.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/containerapp/_ssh_utils.py", line 154, in _resize_terminal
    size = os.get_terminal_size()
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by steindor** [comment]
Still an issue!
