### ISSUE TITLE
az aks browse not working

### ISSUE THREAD

**Issue by techsaau** [Azure/azure-cli#13362]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
[WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 631, in execute
cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
cli\core\commands\__init__.py, ln 688, in _run_job
Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 665, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
azure\cli\core\__init__.py, ln 574, in default_command_handler
...
    with Popen(*popenargs, **kwargs) as process:
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {} --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yungezz** [comment]
duplicating with https://github.com/Azure/azure-cli/issues/8972

**Comment by techsaau** [comment]
@yungezz  In #8972, It was issue of python 64bit. But I'm using 32 bit only. 




azure-cli                          2.5.1
command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory {}

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by yungezz** [comment]
thanks @techsaau for the info

**Comment by djsly** [comment]
@techsaau  for testing purposes, could you try running with the `disable_browser` flag to false ?

from your error message, it seems the the CLI isn't able to start your local browser.

**Comment by djsly** [comment]
the CLI uses the following python library: 
https://docs.python.org/2/library/webbrowser.html

could you try this in a Python Shell ?

```
>>> import webbrowser
>>> webbrowser.open_new_tab("https://github.com")
```

**Comment by techsaau** [comment]
@djsly  Same response after using disable_browser flag:

The command failed with an unexpected error. Here is the traceback:

[WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\command_modules\acs\custom.py", line 1530, in aks_browse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application



I tried below commands and they worked fine:
>>> import webbrowser
>>> webbrowser.open_new_tab("https://github.com")

**Comment by techsaau** [comment]
@yungezz Can you help in this

**Comment by navba-MSFT** [comment]
@techsaau Apologies for the late reply. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the Azure CLI and let us know if you are still facing this issue ? Awaiting your reply.
