### ISSUE TITLE
azure cloud shell Error

### ISSUE THREAD

**Issue by idris135** [Azure/azure-cli#13387]
## Describe the bug

**Command Name**
az help

**Errors:**

The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/mohamed/.azure/commands/2020-05-08.02-06-37.unknown_command.637.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 510, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 84, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 106, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/mohamed/.azure/commands/2020-05-08.02-06-37.unknown_command.637.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az help`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yungezz** [comment]
duplicate https://github.com/Azure/azure-cli/issues/13338

**Comment by jiasli** [comment]
Let's centralize similar issues to https://github.com/Azure/azure-cli/issues/13855.

**Comment by maertendMSFT** [comment]
Please close as there is a centralized issue tracking the root of this error.
