### ISSUE TITLE
Error creating vmss

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#13480]
## Describe the bug

**Command Name**
az vmss create -n 500vmss -g 500vmss --instance-count 500 --image Win2016Datacenter

**Errors:**
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2461, in create_vmss
    sdk_no_wait(no_wait, client.create_or_update, resource_group_name, deployment_name, properties))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 391, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 680, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 918: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 227, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 109, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 55, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'vmss_deploy_cQOoMkc0d8i7LQPhbYkPXK6ME9AJZOZa' is not valid according to the validation procedure. The tracking id is '7b37b961-1313-4ef0-bbfd-0d29df4a3e49'. See inner errors for details.",)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2461, in create_vmss
    sdk_no_wait(no_wait, client.create_or_update, resource_group_name, deployment_name, properties))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 391, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 680, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/site-packages/knack/log.py", line 64, in format
    msg = logging.StreamHandler.format(self, record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 918: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 227, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 109, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 55, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'vmss_deploy_cQOoMkc0d8i7LQPhbYkPXK6ME9AJZOZa' is not valid according to the validation procedure. The tracking id is '7b37b961-1313-4ef0-bbfd-0d29df4a3e49'. See inner errors for details.",)
Arguments: ()

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create -n {} -g {} --instance-count {} --image {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
Would you please update to latest version of Azure CLI and try it again.
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 918: ordinal not in range(128)
```
I can't see the real error message now. The codec is fixed in a recent version of msrestazure.

**Comment by qwordy** [comment]
Any update?

**Comment by fitzgeraldsteele** [comment]
With upgraded cli, seems to be working!
```
fisteele@caroldanvers:/mnt/c/Users/fisteele$ az --version
azure-cli                          2.5.1

command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3
```
Python location '/opt/az/bin/python3'
Extensions directory '/home/fisteele/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Apr 30 2020, 06:21:47)
[GCC 7.5.0]

**Comment by qwordy** [comment]
COOL!
