### ISSUE TITLE
ACS Kubernetes get-credentials fails with a getaddrinfo failed error

### ISSUE THREAD

**Issue by dbarentine** [Azure/azure-cli#1350]
I created an ACS Kubernetes cluster via the Azure portal but when I try to use "az acs kubernetes get-credentials" to set up kubectl config I get the following error:

[Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\python27_x64\lib\site-packages\azure\cli\main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\python27_x64\lib\site-packages\azure\cli\core\application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "C:\python27_x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 274, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\python27_x64\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 329, in acs_get_credentials
    '.kube/config', path)
  File "C:\python27_x64\lib\site-packages\azure\cli\command_modules\acs\acs_client.py", line 22, in SecureCopy
    ssh.connect(host, username=user, key_filename=os.path.join(home, '.ssh', 'id_rsa'))
  File "C:\python27_x64\lib\site-packages\paramiko\client.py", line 296, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\python27_x64\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
gaierror: [Errno 11001] getaddrinfo failed

In the "C:\python27_x64\Lib\site-packages\azure\cli\command_modules\acs\custom.py" it is hardcoded to look for a server in the format of k8s-masters so in my case it tried to connect via: db-kube-k8s-masters.westus.cloudapp.azure.com. But the DNS name created in the portal was db-kubemgmt.westus.cloudapp.azure.com.

It also is hardcoded to try and connect using azureuser as the username. I had created mine with a different name.

The correct information is all available when I get the container service via "az acs show". So it seems like the get-credentials command should either look it up using that or allow me to override the default user and DNS Url.

I was running a nightly build from last night:
> az --version
azure-cli (0.1.0b9+1.dev20161115)

acr (0.1.0b9+1.dev20161115)
acs (0.1.0b9+1.dev20161115)
appservice (0.1.0b9+1.dev20161115)
cloud (0.1.0b9+1.dev20161115)
component (0.1.0b9+1.dev20161115)
configure (0.1.0b9+1.dev20161115)
container (0.1.0b9+1.dev20161115)
context (0.1.0b9+1.dev20161115)
core (0.1.0b9+1.dev20161115)
feedback (0.1.0b9+1.dev20161115)
network (0.1.0b9+1.dev20161115)
profile (0.1.0b9+1.dev20161115)
resource (0.1.0b9+1.dev20161115)
role (0.1.0b9+1.dev20161115)
storage (0.1.0b9+1.dev20161115)
vm (0.1.0b9+1.dev20161115)

**Comment by mayurid** [comment]
@brendanburns to take a look.

**Comment by brendandburns** [comment]
acknowledged.

**Comment by mmercan** [comment]
azure-cli (2.0.24)

acr (2.0.18)
acs (2.0.23)
advisor (0.1.1)
appservice (0.1.23)
backup (1.0.4)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.24)
cosmosdb (0.1.16)
dla (0.0.16)
dls (0.0.19)
eventgrid (0.1.7)
extension (0.0.7)
feedback (2.0.7)
find (0.2.8)
interactive (0.3.12)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.14)
monitor (0.0.14)
network (2.0.20)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.10)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.20)
role (2.0.16)
servicefabric (0.0.8)
sql (2.0.18)
storage (2.0.22)
vm (2.0.23)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mmercan\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**I am still getting** 


[Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 292, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 882, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 903, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\acs_client.py", line 72, in secure_copy
    ssh.connect(host, username=user, pkey=pkey, sock=proxy)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\client.py", line 329, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by tjprescott** [comment]
@mmercan please try updating to 2.0.25 and see if this fixes your problem.

**Comment by mmercan** [comment]
az acs create --orchestrator-type=kubernetes  --resource-group test-wink8s-rg  --name=test-wink8s  --agent-count=3  --generate-ssh-keys --windows --admin-username azureuser  --admin-password {{admin_password)) --service-principal {{my_client_id}} --client-secret {{client_secret}} --location eastus

az acs kubernetes get-credentials --resource-group=test-wink8s-rg --name=test-wink8s

**I already have done that last night and test it same result**

azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

 az acs kubernetes get-credentials --resource-group=test-wink8s-rg --name=test-wink8s
[Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 292, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 884, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 905, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\acs_client.py", line 72, in secure_copy
    ssh.connect(host, username=user, pkey=pkey, sock=proxy)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\client.py", line 329, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed


**I created an azure VM and installed edge, same result**

azure-cli (2.0.27.dev10321)

acr (2.0.20.dev10321)
acs (2.0.26.dev10321)
advisor (0.1.1)
appservice (0.1.25.dev10321)
backup (1.0.6)
batch (3.1.9.dev10321)
batchai (0.1.5.dev10321)
billing (0.1.7)
cdn (0.0.12.dev10321)
cloud (2.0.12.dev10321)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1+dev.8775)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.27.dev10321)
cosmosdb (0.1.17.dev10321)
dla (0.0.18.dev10321)
dls (0.0.19)
eventgrid (0.1.9.dev10321)
extension (0.0.8.dev10321)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15.dev10321)
iot (0.1.16)
keyvault (2.0.17.dev10321)
lab (0.0.16.dev10321)
monitor (0.1.1.dev10321)
network (2.0.22.dev10321)
nspkg (3.0.1+dev.8775)
profile (2.0.18.dev10321)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22.dev10321)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20.dev10321)
storage (2.0.24.dev10321)
vm (2.0.26.dev10321)

Python location 'C:\Python27\python.exe'
Extensions directory 'C:\Users\mmercan\.azure\cliextensions'

Python (Windows) 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


[Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 318, in execute
    six.reraise(*sys.exc_info())
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 291, in execute
    result = cmd(params)
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Python27\lib\site-packages\azure\cli\core\__init__.py", line 348, in default_command_handler
    result = op(**command_args)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 884, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 905, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acs\acs_client.py", line 72, in secure_copy
    ssh.connect(host, username=user, pkey=pkey, sock=proxy)
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 329, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 200, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
gaierror: [Errno 11001] getaddrinfo failed
