### ISSUE TITLE
az login rhel76 error loading modules (2.0.77)

### ISSUE THREAD

**Issue by packerwhathappened** [Azure/azure-cli#13532]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Section u'AzureCloud' already exists
Traceback (most recent call last):
  File "/home/t187106/venv/lib/python2.7/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/t187106/venv/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
DuplicateSectionError: Section u'AzureCloud' already exists
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-3.10.0-957.35.2.el7.x86_64-x86_64-with-redhat-7.6-Maipo
Python 2.7.5
Shell: bash

azure-cli 2.0.77

```

**Comment by yonzhan** [comment]
add to S170

**Comment by qianwens** [comment]
@packerwhathappened , python2 is not supported by Azure CLI now, could you please help install python 3 and try again?
