### ISSUE TITLE
az backup protection enable-for-azurefileshare error on adding second fileshare

### ISSUE THREAD

**Issue by EvilSmiff** [Azure/azure-cli#13549]
This occurs on adding a backup to the second fileshare on a storage account.

## Describe the bug

**Command Name**
`az backup protection enable-for-azurefileshare`

**Errors:**
```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/backup/custom_afs.py, ln 66, in enable_for_AzureFileShare
    container_uri = helper.get_protection_container_uri_from_id(protectable_item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection enable-for-azurefileshare --azure-file-share {} --policy-name {} --storage-account {} --subscription {} --resource-group {} --vault-name {}`

## Environment Summary
```
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 3.6.8
Installer: RPM

azure-cli 2.5.1

Extensions:
azure-firewall 0.1.3

```

**Comment by yonzhan** [comment]
backup

**Comment by EvilSmiff** [comment]
This is actually taking place on the first fileshare creation now as well, however, it has been working previously using the same az cli code so something has changed.  I'm not aware of any updates to the host OS we are using - except a change to the az cli version after this started to occur.

**Comment by pvrk** [comment]
@sambitratha : Is this something that we have recently fixed with the latest release? Can you please take a look?

**Comment by sambitratha** [comment]
@EvilSmiff i see you're using a previous version of Azure cli. This was a bug introduced in CLI because of service changes. It has been fixed in the latest release 2.6.0. Please upgrade Azure CLI and check if you're still facing this issue.

**Comment by EvilSmiff** [comment]
Hi @sambitratha: I've just updated to 2.6.0 and can confirm that this works once again.  Thanks all.

**Comment by twllight** [comment]
Hello,

I've updated my azure cli to version 2.7.0 and this seems to persist:

```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_base.py", line 305, in enable_for_azurefileshare
    storage_account, policy_name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom_afs.py", line 66, in enable_for_AzureFileShare
    container_uri = helper.get_protection_container_uri_from_id(protectable_item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```
```└ $ ▶ az --version
azure-cli                          2.7.0

command-modules-nspkg              2.0.3
core                               2.7.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/baumkir/.azure/cliextensions'

Python (Linux) 3.6.10 (default, May 29 2020, 08:10:14)
[GCC 7.5.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```
