### ISSUE TITLE
No module named 'knack.experimental' error after upgrading azdev

### ISSUE THREAD

**Issue by audunn** [Azure/azure-cli#13594]
**Describe the bug**
No module named 'knack.experimental' error after upgrading azdev

note created an issue in azure-cli-dev-tools regading this but no one seems to look at issues there https://github.com/Azure/azure-cli-dev-tools/issues/198

**To Reproduce**
```
on dev branch of azure-cli pull latest
pip install azdev
azdev setup -c
❯ azdev style netappfiles

===============
| Style Check |
===============

No module named 'knack.experimental'
Traceback (most recent call last):
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\azdev\operations\style.py", line 34, in check_style
    selected_modules = get_path_table(include_only=modules)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\azdev\utilities\path.py", line 193, in get_path_table
    from azure.cli.core.extension import EXTENSIONS_DIR  # pylint: disable=import-error
  File "c:\users\audunn\source\repos\audunn\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 23, in <module>
    from knack.experimental import ExperimentalItem
ModuleNotFoundError: No module named 'knack.experimental'

❯ az login show
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\audunn\source\repos\audunn\azure-cli\src\azure-cli\azure\cli\__main__.py", line 13, in <module>
    from azure.cli.core import get_default_cli
  File "c:\users\audunn\source\repos\audunn\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 23, in <module>
    from knack.experimental import ExperimentalItem
ModuleNotFoundError: No module named 'knack.experimental'
```

**Expected behavior**
No error is shown and azdev and az commands are executed

**Environment summary**
power shell core on windows 10 

**Additional context**

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@audunn  please run `azdev setup-c` again

**Comment by audunn** [comment]
> @audunn please run `azdev setup-c` again

Thank you for your suggestion, I have already tried that and tried again unfortunately with the same result.

**Comment by audunn** [comment]
Hi, any other tips or trick I could try to fix this, Please note this is blocking my work in delivering an urgent fix to address issue for a high profile MSFT customer/prospect.

**Comment by haroldrandom** [comment]
@audunn Could you list your current knack version at your venv? You could manually uninstall the older version knack and install it `pip install kanck=={certain version}` to fix this.

**Comment by audunn** [comment]
> @audunn Could you list your current knack version at your venv? You could manually uninstall the older version knack and install it `pip install kanck=={certain version}` to fix this. The certain version should align with the one azure-cli is using

Thank you @haroldrandom  this tip was very helpful with this. I had assumed it was updated as part of the process and  I thought I already did pip install knack but this seemed to help.  

There is regarding our modules SDK version incompatibility. I have updated the requirements files and setup.py any idea how to get it to pick up the newer SDK version that has the functionality we need? 
Should we update and SDK version using pip or should the azdev setup -c  or something else take care of that via the requirements?

`ERROR: azure-cli 2.6.0 has requirement azure-mgmt-netapp~=10.0.0, but you'll have azure-mgmt-netapp 0.8.0 which is incompatible.`

**Comment by haroldrandom** [comment]
Well. I guess I could algin the dependencies requirements with Azure CLI for knack. but I guess it's a permernant problem because pip take care of the cache. So, guess there won't be a perfect solution I think :(

**Comment by haroldrandom** [comment]
I remeber that new version azdev has leveraged requirement.*.txt already. https://github.com/Azure/azure-cli/pull/13431, https://github.com/Azure/azure-cli-dev-tools/pull/194
Most requirements are listed explicitly in platform-specific requirements.txt.

You could upgrade to newer azdev to fix this problem during development.

**Comment by audunn** [comment]
yes, it is fixed now, thank you very much @haroldrandom

**Comment by haroldrandom** [comment]
Closed as revolved. If anything missing, please feel free to reopen.
