### ISSUE TITLE
ASDK environment az login failure

### ISSUE THREAD

**Issue by Matt45D** [Azure/azure-cli#13642]
#12648  Describe the bug
Getting a python iterable error when attempting to az login into my Azure Stack Development Kit environment. I get prompted to input my password and then after entering it, I get the following error down below.

**Command Name**
`az login`

**Errors:**
The command failed with an unexpected error. Here is the traceback:

```
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yf22vmg2\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yf22vmg2\six\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 545, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\profile\custom.py", line 150, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\_profile.py", line 240, in find_subscriptions_on_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\_profile.py", line 276, in _normalize_properties
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az cloud register
- az cloud set
- az cloud update
- `az login -u {} --tenant {}`

## Expected Behavior
Following the `az login -u {} --tenant {}` command, you get prompted for your password and then you successfully login into your environment.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

```

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
The lines with problem are https://github.com/Azure/azure-cli/blob/80c7bc79d416007d86848650b149d5fa24783c19/src/azure-cli-core/azure/cli/core/_profile.py#L275-L276

This is a known issue of the `resources` Resource Provider: https://github.com/Azure/azure-rest-api-specs/issues/9567.

**Solution**: Please select the correct profile with `az cloud set --name xxx --profile xxx`.

Meanwhile, I will try to make the code of Azure CLI more robust on this kind of server issue.

**Comment by Matt45D** [comment]
Hi,

Just to confirm it was an issue with using the incorrect API version profile. It would definitely be great if the Azure CLI was able to give more detailed error messages to indicate that it was an issue with API versions.

Thanks for the help,

Matt

**Comment by Matt45D** [comment]
Hi,

Just to confirm it was an issue with using the incorrect API version profile. It would definitely be great if the Azure CLI was able to give more detailed error messages to indicate that it was an issue with API versions.

Thanks for the help,

Matt

**Comment by jiasli** [comment]
Thanks for the advice. However, this is not really Azure CLI's fault. 

> Just to confirm it was an issue with using the incorrect API version profile. It would definitely be great if the Azure CLI was able to give more detailed error messages to indicate that it was an issue with API versions.

If `2019-06-01` is not supported by Azure Stack, the API should return an error, instead of returning the incorrect response which doesn't comply with the [`subscriptions.json`](https://github.com/Azure/azure-rest-api-specs/blob/76b6bd1989a8248987219b840f525b02e07807dc/specification/resources/resource-manager/Microsoft.Resources/stable/2019-06-01/subscriptions.json#L271-L277) REST spec. 

For example, you may click the <kbd>Try It</kbd> button on [Subscriptions - List API](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list) and use an incorrect API version:

```http
GET https://management.azure.com/subscriptions?api-version=2020-01-02

{
  "error": {
    "code": "InvalidApiVersionParameter",
    "message": "The api-version '2020-01-02' is invalid. The supported versions are '2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
  }
}
```

In this case, the error message will be revealed by Azure CLI. We will work with ARM team to fix this incorrect behavior.

**Comment by jiasli** [comment]
Error message is improved in https://github.com/Azure/azure-cli/pull/15550.
