### ISSUE TITLE
Jmespath: object projection is broken

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1365]
The following command returns nothing. If you remove the `OrderedDict` in our [query.py](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/extensions/query.py#L40), things works. 
```bash
az vm show -g vm -n vm-1 --query "{n:name}"
```
Either `Jmespath` or us have bug, which need to be fixed anyway

**Comment by derekbekoe** [comment]
I would refer to this commit - https://github.com/Azure/azure-cli/commit/adaf6447990e2e6f28dd9baf9f1b41c73bd8d46c.
Commit description:
"Avoid unexpected reordering of dictionaries from how it was specified in the JMESPath expression for the --query parameter.

Especially annoying when using the tsv output formatter...."

cc: @johanste

**Comment by derekbekoe** [comment]
On version `0.1.0b9`, I get a stack trace.

```
$ az vm show -g myrg -n abcdefg --query '{n:name}'
Circular reference detected
Traceback (most recent call last):
  File "/Users/debekoe/Library/Python/2.7/lib/python/site-packages/azure/cli/main.py", line 39, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result)
  File "/Users/debekoe/Library/Python/2.7/lib/python/site-packages/azure/cli/core/_output.py", line 107, in out
    output = self.formatter(obj)
  File "/Users/debekoe/Library/Python/2.7/lib/python/site-packages/azure/cli/core/_output.py", line 39, in format_json
    separators=(',', ': ')) + '\n'
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 295, in _iterencode_list
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
```
