### ISSUE TITLE
az functionapp update - NoneType' object has no attribute 'kind

### ISSUE THREAD

**Issue by maxleonalbrecht** [Azure/azure-cli#13683]
## The Bug

While trying to update a function app, it fails with the following errors

**Command Name**
`az functionapp update`

**Errors:**
```
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
Temp\pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 625, in execute
azure\cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 680, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 659, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure\cli\core\commands\arm.py, ln 567, in handler
azure\cli\core\commands\__init__.py, ln 437, in cached_put
azure\cli\core\commands\__init__.py, ln 432, in _put_operation
azure\cli\command_modules\appservice\custom.py, ln 616, in set_functionapp
AttributeError: 'NoneType' object has no attribute 'kind'
```

## To Reproduce:

- `az functionapp update --resource-group $resourceGroupName --name $functionApp`

## Expected Behavior

Update a function app

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1 *

```

**Comment by maxleonalbrecht** [comment]
You need to set -subscription $subscription, than the error will not exists.

**Please add this in the examples.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
functionapp

**Comment by fabiocav** [comment]
Closing as resolved.

**Comment by fcavaco** [comment]
having this exact error, but cannot see anywhere what the solution was?!
- tried to add --subscription but did not work out.
- The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 61, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in cached_put
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 441, in _put_operation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 686, in set_functionapp
AttributeError: 'NoneType' object has no attribute 'kind'

**Comment by fcavaco** [comment]
just to add in case someone goes through same problem as myself... --subscription is the subscription name, not its id. :)
