### ISSUE TITLE
Webapp:"az webapp config container set" truncates "docker-registry-server-password" if it contains >

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cli#13696]
## Describe the bug

When using `az webapp config container set` with a `docker-registry-server-password` that contains a `>` (and I'm assuming other similar characters), the password is truncated just before the `>`:

## To Reproduce:
```
az webapp config container set -n "app-name" -g "rg-name" --docker-custom-image-name "image-name" --docker-registry-server-url "registry-url" --docker-registry-server-user "registry-user" --docker-registry-server-password "a_password_with_>_this_will_be_truncated"
```

As a workaround, one can wrap the password in a second pair of double quotes and escape the inner pair:

```
az webapp config container set -n "app-name" -g "rg-name" --docker-custom-image-name "image-name" --docker-registry-server-url "registry-url" --docker-registry-server-user "registry-user" --docker-registry-server-password "`"a_password_with_>_this_will_not_be_truncated`""
```

## Expected Behavior

The password should not require special treatment when it includes a `>` or other "special" characters.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

```

**Comment by kentcb** [comment]
Just noticed I had an untracked file in my repo. The name, curiously, was the contents of the password after the `>`. So I guess the `>` is causing the output to redirect despite the quotes. Maybe this is a PS bug??

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by panchagnula** [comment]
Thanks for the update - we will check if this is an API issue. Also are you running CLI commands using PowerShell? if so can you try using a bash or normal command line and let us know if you see the same issue? Thanks.

**Comment by kentcb** [comment]
Ugh, I'm trying to but keep getting a useless error from the command:

```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yf22vmg2\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-yf22vmg2\six\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 545, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 1151, in update_container_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 905, in _add_fx_version
AttributeError: 'NoneType' object has no attribute 'reserved'
```
I know I had this in the past and it turned out to be my resource group name was incorrect. But it's definitely correct now and I'm still getting it. Also double-checked all other details and it all looks fine.

**Comment by panchagnula** [comment]
@kentcb   are you trying to run this on a non linux app? reserved is a property set to true on Linux apps. Also you can run the command with --debug flag at the & this would give you detailed error message.

**Comment by kentcb** [comment]
@panchagnula Yeah, it's a linux app. When running with `--debug` I get an error about resource group not found, even though it is definitely listed in the portal. I tried logging out and in again with `az`, but still get the error.

Bizarrely, if I do `az group list`, my RG is _not_ there but all the other RGs shown alongside mine in the portal _is_ there. Similarly, `az group show --name "my-rg-name"` tells me the RG could not be found. They're all in the same subscription so I am 💯 confused right now.

**Comment by panchagnula** [comment]
@kentcb make sure to check az account show to check the default subscription you are using with CLI given this is not specific to webapp command I am assuming you are not using the right subscription the RG is a part of.

**Comment by kentcb** [comment]
@panchagnula Sorry for the delay - so much going on!

I've just tried this at a `cmd.exe` and it indeed works, so it's definitely a weird Powershell (both PS Core and "regular" PS) issue.

**Comment by panchagnula** [comment]
Thanks please check this documentation hopefully this helps on how to escape this property while using PS https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues
