### ISSUE TITLE
az backup protection backup-now

### ISSUE THREAD

**Issue by ggg333** [Azure/azure-cli#13733]
Running in to following error when i try to enable manual backup using "az backup protection backup-now"

Command group 'backup' is in preview. It may be changed/removed in a future release.
The command failed with an unexpected error. Here is the traceback:

argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/ganesh.palanisamy/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 663, in cli_execute
    result = invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_base.py", line 94, in backup_now
    item = show_item(cmd, items_client, resource_group_name, vault_name, container_name, item_name,
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_base.py", line 49, in show_item
    return common.show_item(cmd, client, resource_group_name, vault_name, container_name, name,
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_common.py", line 48, in show_item
    container_type = custom_help.validate_and_extract_container_type(container_name, backup_management_type)
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_help.py", line 365, in validate_and_extract_container_type
    if not is_native_name(container_name) and backup_management_type is None:
  File "/usr/local/Cellar/azure-cli/2.6.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_help.py", line 41, in is_native_name
    return ";" in name
TypeError: argument of type 'NoneType' is not iterable

To open an issue, please run: 'az feedback'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48754d22-3349-4e45-a315-126569fe9047
* Version Independent ID: 72e517fa-8000-0ec4-1b33-853901d75cb2
* Content: [az backup protection](https://docs.microsoft.com/en-us/cli/azure/backup/protection?view=azure-cli-latest#az-backup-protection-backup-now)
* Content Source: [src/azure-cli/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ggg333** [comment]
Answered in https://github.com/Azure/azure-cli/issues/11179 hence closing this
