### ISSUE TITLE
Powershell issue 

### ISSUE THREAD

**Issue by kiranhanu9** [Azure/azure-cli#13848]
When I run any command some read only issue is happening :

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 47, in load
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/kiran/.azure/az.sess'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 643, in get_default_cli
    help_cls=AzCliHelp)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 69, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 61, in load
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/kiran/.azure/az.sess'

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
Seems to be similar to https://github.com/Azure/azure-cli/issues/138550=.

**Comment by yonzhan** [comment]
tracked on #13855 and close this one.
