### ISSUE TITLE
az role definition update failed 

### ISSUE THREAD

**Issue by motim6026** [Azure/azure-cli#13878]
Get this error when try to update custom role using az cli 

az : The command failed with an unexpected error. Here is the traceback:
At line:1 char:1
+ az role definition update --role-definition $file.FullName;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command fai... the traceback::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
'roleName'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\command_modules\role\custom.py", line 56, in update_role_definition
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\command_modules\role\custom.py", line 85, in _create_update_role_definition
KeyError: 'roleName'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e649cf-40e3-1b9e-141a-c62d244eda61
* Version Independent ID: 78ea89c1-7c56-e33b-d10a-dae05642aa34
* Content: [az role definition](https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by motim6026** [comment]
Hi, 
any update?

**Comment by arrownj** [comment]
Hi @motim6026 , actually the formats of `az role definition update` and `az role definition create` are different. You can reference #14411 where @jiasli Jiashuo Li FTE gave us a very clear explanation. So please use a valid json format to update the role definition. You can get an example from `az role definition update -h`.
