### ISSUE TITLE
ImportError: No module named packages.urllib3

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1387]
On Ubuntu / Bash on Windows, users may run into the above error message with modules not loading due to an import error.

(created this issue to track https://github.com/Azure/msrest-for-python/issues/3 as that potentially could be the cause)

Full stack trace:
```
ERROR: Error loading command module 'appservice'
DEBUG: Traceback (most recent call last):
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 214, in get_command_table
    import_module('azure.cli.command_modules.' + mod).load_commands()
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/command_modules/appservice/__init__.py", line 12, in load_commands
    import azure.cli.command_modules.appservice.commands #pylint: disable=redefined-outer-name
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/command_modules/appservice/commands.py", line 8, in <module>
    from azure.cli.core.commands.arm import cli_generic_update_command
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 16, in <module>
    from azure.cli.core.commands.client_factory import get_mgmt_service_client
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/core/commands/client_factory.py", line 7, in <module>
    from azure.cli.core._profile import Profile, CLOUD
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 17, in <module>
    from azure.cli.core.adal_authentication import AdalAuthentication
  File "/home/ls/.local/lib/python2.7/site-packages/azure/cli/core/adal_authentication.py", line 9, in <module>
    from msrest.authentication import Authentication
  File "/home/ls/.local/lib/python2.7/site-packages/msrest/__init__.py", line 27, in <module>
    from .configuration import Configuration
  File "/home/ls/.local/lib/python2.7/site-packages/msrest/configuration.py", line 39, in <module>
    from .pipeline import (
  File "/home/ls/.local/lib/python2.7/site-packages/msrest/pipeline.py", line 36, in <module>
    from requests.packages.urllib3 import Retry
ImportError: No module named packages.urllib3
```

**Comment by tjprescott** [comment]
@derekbekoe is this still an issue?

**Comment by derekbekoe** [comment]
Marked as FAQ.
