### ISSUE TITLE
az aks install-cli errpr

### ISSUE THREAD

**Issue by cepcruzz** [Azure/azure-cli#13915]
## Describe the bug

Can't download and installed kubectl

**Command Name**
`az aks install`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/az/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/az/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/opt/az/lib/python3.6/http/client.py", line 1423, in connect
    server_hostname=server_hostname)
  File "/opt/az/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/az/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/opt/az/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/az/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 321, in k8s_install_cli
    version = urlopen(source_url + '/stable.txt', context=context).read()
  File "/opt/az/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/az/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/az/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli

## Expected Behavior
Download and install kubectl, the Kubernetes command-line tool.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
aks

**Comment by djsly** [comment]
on OSX

```
✖ sudo az aks install-cli
Password:
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/darwin/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
```

with 

```
azure-cli                          2.6.0 *

command-modules-nspkg              2.0.3
core                               2.6.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.50

Python location '/usr/local/Cellar/azure-cli/2.6.0/libexec/bin/python'
Extensions directory '/Users/sylvain_boily/.azure/cliextensions'

Python (Darwin) 3.8.2 (default, Mar 11 2020, 00:29:50) 
[Clang 11.0.0 (clang-1100.0.33.17)]

Legal docs and information: aka.ms/AzureCliLegal
```
@cepcruzz , can you paste full `az --version` output

**Comment by djsly** [comment]
one difference I have, I'm running Python3.8

from a certificate point of view,it looks normal and healthy

<img width="535" alt="Screen Shot 2020-06-15 at 9 03 00 PM" src="https://user-images.githubusercontent.com/4981802/84720310-bad2b300-af4b-11ea-9614-9d866bf3470e.png">
<img width="485" alt="Screen Shot 2020-06-15 at 9 03 04 PM" src="https://user-images.githubusercontent.com/4981802/84720312-bc03e000-af4b-11ea-9fe5-4bc21832e7ae.png">

**Comment by seanmck** [comment]
Closing as not-actionable. Please reopen if there is a clear repro.
