### ISSUE TITLE
az acr login - NotImplementedError: APIVersion 2019-12-01-preview is not available

### ISSUE THREAD

**Issue by ezwiefel** [Azure/azure-cli#13927]
## Describe the bug
Logging into ACR isn't working due to API Version Error

**Command Name**
`az acr login`

**Errors:**
```
APIVersion 2019-12-01-preview is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 19, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/container_registry_management_client.py, ln 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-12-01-preview is not available
```

## To Reproduce:
- `az acr login -n {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.9
Installer: PIP

azure-cli 2.6.0 *
azure-cli-ml 1.5.0

Extensions:
azure-cli-ml 1.5.0

```

**Comment by yonzhan** [comment]
acr

**Comment by jikuma** [comment]
@ezwiefel can you please help me with registry name and registry location.

**Comment by ezwiefel** [comment]
@jikuma I don't remember which registry name and location were causing the issues

**Comment by yugangw-msft** [comment]
This is a setup issue, not ACR issue. In short, the azure-mgmt-containerregsitry was not pulled down. @ezwiefel, please tell us how you installed the CLI.
@fengzhou-msft

**Comment by ezwiefel** [comment]
@yugangw-msft I believe it was the default installation on the Azure Machine Learning Compute Instance

**Comment by fengzhou-msft** [comment]
@ezwiefel can you run `pip show azure-mgmt-containerregistry` to check the version?

**Comment by harshbangad** [comment]
Hi, I get the same error during az acr login --name *name* while running it on jupyter terminal of my compute instance.
Any workaround?

@fengzhou-msft 

Here is the version of container registry- 
The 
azureuser@dockertest4:/mnt/batch/tasks/shared/LS_root/mounts/clusters/dockertest4/code$ pip show azure-mgmt-containerregistry
Name: azure-mgmt-containerregistry
Version: 2.8.0
Summary: Microsoft Azure Container Registry Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /anaconda/envs/azureml_py36/lib/python3.6/site-packages
Requires: azure-common, msrest, msrestazure
Required-by: azureml-core, azure-cli

**Comment by azeltov** [comment]
This is still an issue on compute instances. I have it working on my mac. I tried update to latest az cli and az ml cli and also updating pip azure -mgmt-containerregistry and still have the same issue. 
az acr login --name amldbxsummitf07c5365
The command failed with an unexpected error. Here is the traceback:

APIVersion 2019-12-01-preview is not available
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 236, in acr_login
    password=password)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 417, in get_login_credentials
    is_login_context=True)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 310, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_utils.py", line 107, in get_registry_by_name
    client = cf_acr_registries(cli_ctx)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/acr/_client_factory.py", line 19, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/mgmt/containerregistry/container_registry_management_client.py", line 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-12-01-preview is not available

To open an issue, please run: 'az feedback'

**Comment by hermandr** [comment]
I would like to confirm that this is still an issue

**Comment by fengzhou-msft** [comment]
Please try this [workaround](https://github.com/Azure/azure-cli/issues/15627#issuecomment-716129300).

**Comment by yungezz** [comment]
hi @ezwiefel does above solution work for you? let us know how it works. it's an issue of specific version of azure cli, fixed in latest releases.
