### ISSUE TITLE
Keyvault commands don't handle auth errors gracefully

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1403]
Looks like `key_vault_authentication.py` isn't behaving the save as the general `adal_authentication.py`.

With other commands such as `vm list`, I get:
```
$ az vm list
Credentials have expired due to inactivity. Please run 'az login'
```

With keyvault, I get:
```
$ az keyvault secret show --vault-name VAULT_NAME -n SECRET_NAME
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The refresh token has expired due to it being revoked. ......}
Traceback (most recent call last):
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py", line 66, in _execute_command
    result = op(client, **kwargs)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/keyvaultclient/generated/key_vault_client.py", line 1415, in get_secret
    response = self._client.send(request, header_parameters, **operation_config)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/requests/models.py", line 297, in prepare
    self.prepare_auth(auth, url)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/requests/models.py", line 490, in prepare_auth
    r = auth(self)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/keyvaultclient/key_vault_authentication.py", line 47, in __call__
    self.set_authorization_header(request, challenge)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/keyvaultclient/key_vault_authentication.py", line 54, in set_authorization_header
    challenge.get_scope())
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py", line 57, in get_token
    return Profile().get_login_credentials(resource)[0]._token_retriever() # pylint: disable=protected-access
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/_profile.py", line 241, in <lambda>
    username_or_sp_id, account[_TENANT_ID], resource)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/_profile.py", line 399, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/authentication_context.py", line 126, in acquire_token
    return self._acquire_token(token_func)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/authentication_context.py", line 109, in _acquire_token
    return token_func(self)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/authentication_context.py", line 124, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/token_request.py", line 350, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/cache_driver.py", line 182, in find
    is_resource_tenant_specific)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/cache_driver.py", line 171, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/cache_driver.py", line 153, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/token_request.py", line 138, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/token_request.py", line 342, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.5/site-packages/adal/oauth2_client.py", line 281, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The refresh token has expired due to it being revoked. ......
```

**Comment by tjprescott** [comment]
This is true. KeyVault marches to its own beat.
