### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__name__'

### ISSUE THREAD

**Issue by praveen-pk** [Azure/azure-cli#14054]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/storage/_client_factory.py, ln 27, in get_storage_data_service_client
    return get_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
cli/core/commands/client_factory.py, ln 178, in get_data_service_client
    logger.debug('Getting data service client service_type=%s', service_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage container create --name {}`

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.2.5
Python 3.8.3
Installer: RPM

azure-cli 2.7.0

Extensions:
azure-devops 0.17.0

$ cat /etc/os-release
NAME=Fedora
VERSION="32 (Container Image)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Container Image)"

$ rpm -qa | grep azure
azure-cli-2.7.0-1.el7.x86_64

```

**Comment by praveen-pk** [comment]
Following is the complete stack trace:

`$ az storage container create --name testing
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 257, in new_handler
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 40, in create_container
    client = blob_data_service_factory(cmd.cli_ctx, kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 76, in blob_data_service_factory
    return generic_data_service_factory(cli_ctx, blob_service, kwargs.pop('account_name', None),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 36, in generic_data_service_factory
    return get_storage_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 27, in get_storage_data_service_client
    return get_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 178, in get_data_service_client
    logger.debug('Getting data service client service_type=%s', service_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'

To open an issue, please run: 'az feedback'
`

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @praveen-pk, could you provide more information with `--debug` in your command?

**Comment by praveen-pk** [comment]
@Juliehzl  is the trace with --debug.
```
$ az storage container create --name testing --debug
Command arguments: ['storage', 'container', 'create', '--name', 'testing', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f0de41675e0>, <function OutputProducer.on_global_arguments at 0x7f0de3f6dc10>, <function CLIQuery.on_global_arguments at 0x7f0de3e6c280>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.013 seconds.
Loaded module 'acs' in 0.021 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.010 seconds.
Loaded module 'apim' in 0.004 seconds.
Loaded module 'appconfig' in 0.005 seconds.
Loaded module 'appservice' in 0.022 seconds.
Loaded module 'aro' in 0.012 seconds.
Loaded module 'backup' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.284 seconds.
Loaded module 'batchai' in 0.006 seconds.
Loaded module 'billing' in 0.004 seconds.
Loaded module 'botservice' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.009 seconds.
Loaded module 'cloud' in 0.005 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.005 seconds.
Loaded module 'container' in 0.007 seconds.
Loaded module 'cosmosdb' in 0.016 seconds.
Loaded module 'deploymentmanager' in 0.005 seconds.
Loaded module 'dla' in 0.010 seconds.
Loaded module 'dls' in 0.006 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.007 seconds.
Loaded module 'eventhubs' in 0.006 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.003 seconds.
Loaded module 'hdinsight' in 0.006 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.010 seconds.
Loaded module 'iotcentral' in 0.004 seconds.
Loaded module 'keyvault' in 0.013 seconds.
Loaded module 'kusto' in 0.005 seconds.
Loaded module 'lab' in 0.010 seconds.
Loaded module 'managedservices' in 0.004 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.020 seconds.
Loaded module 'natgateway' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.010 seconds.
Loaded module 'network' in 0.070 seconds.
Loaded module 'policyinsights' in 0.004 seconds.
Loaded module 'privatedns' in 0.010 seconds.
Loaded module 'profile' in 0.003 seconds.
Loaded module 'rdbms' in 0.018 seconds.
Loaded module 'redis' in 0.004 seconds.
Loaded module 'relay' in 0.008 seconds.
Loaded module 'reservations' in 0.004 seconds.
Loaded module 'resource' in 0.018 seconds.
Loaded module 'role' in 0.011 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.006 seconds.
Loaded module 'servicebus' in 0.010 seconds.
Loaded module 'servicefabric' in 0.008 seconds.
Loaded module 'signalr' in 0.005 seconds.
Loaded module 'sql' in 0.017 seconds.
Loaded module 'sqlvm' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.066 seconds.
Loaded module 'vm' in 0.075 seconds.
Loaded all modules in 0.921 seconds. (note: there's always an overhead with the first module loaded)
Found 1 extensions: ['azure-devops']
Extension compatibility result: is_compatible=True cli_core_version=2.7.0 min_required=2.0.69 max_required=None
Extensions directory: '/home/prapal/.azure/cliextensions/azure-devops'
Loaded extension 'azure-devops' in 1.092 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f0de31810d0>]
az_command_data_logger : command args: storage container create --name {} --debug
metadata file logging enabled - writing logs to '/home/prapal/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f0de2e0ed30>]
Event: CommandLoader.OnLoadArguments []
/usr/lib64/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f0de2e0edc0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f0de2e0ef70>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f0de29e4430>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f0de3f6dca0>, <function CLIQuery.handle_query_parameter at 0x7f0de3e6c310>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f0de2e0ee50>, <function handler at 0x7f0de28b8700>, <function DevCommandsLoader.post_parse_args at 0x7f0de1f5d160>]
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 257, in new_handler
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 40, in create_container
    client = blob_data_service_factory(cmd.cli_ctx, kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 76, in blob_data_service_factory
    return generic_data_service_factory(cli_ctx, blob_service, kwargs.pop('account_name', None),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 36, in generic_data_service_factory
    return get_storage_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 27, in get_storage_data_service_client
    return get_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 178, in get_data_service_client
    logger.debug('Getting data service client service_type=%s', service_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 257, in new_handler
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 40, in create_container
    client = blob_data_service_factory(cmd.cli_ctx, kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 76, in blob_data_service_factory
    return generic_data_service_factory(cli_ctx, blob_service, kwargs.pop('account_name', None),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 36, in generic_data_service_factory
    return get_storage_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 27, in get_storage_data_service_client
    return get_data_service_client(cli_ctx, service, name, key, connection_string, sas_token,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 178, in get_data_service_client
    logger.debug('Getting data service client service_type=%s', service_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
cli.azure.cli.core.util :
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f0de3181310>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 5301 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/bin/python3 /usr/lib64/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/${user}/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 2.696 seconds.
```

**Comment by yungezz** [comment]
#14287

**Comment by Juliehzl** [comment]
Hi @evelyn-ys, could you help follow up this issue?

**Comment by evelyn-ys** [comment]
Hi @praveen-pk, this may caused by `azure.multiapi.storage` dependency not found. Maybe you reinstall this package with some wrong version or you uninstall this package accidentally.

I have refined our code(#16993 ) to expose the real exception which is `ModuleNotFoundError: No module named 'azure.multiapi.storage.v2018_11_09'` instead of `AttributeError: 'NoneType' object has no attribute '__name__'`. Hope this will help you debug more clearly.
