### ISSUE TITLE
Webapp:Misleading error on CLI command 'az webapp config container set'

### ISSUE THREAD

**Issue by unbreakableIce** [Azure/azure-cli#14055]
When I ran the command:

**az webapp config container set --name web-app-name --resource-group resource-group --docker-custom-image-name image-repo:latest --docker-registry-server-url https://serverurl.azurecr.io --docker-registry-server-user user --docker-registry-server-password passord**

I received the following error /traceback

The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 1151, in update_container_settings
    _add_fx_version(cmd, resource_group_name, name, docker_custom_image_name, slot)
  File "/usr/local/Cellar/azure-cli/2.7.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 905, in _add_fx_version
    linux_fx = fx_version if web_app.reserved else None
AttributeError: 'NoneType' object has no attribute 'reserved'

When I ran the same command with the --debug option: I found the following response from the REST api call:
**msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/web-app' under resource group 'example-RG' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}**
With the same traceback

The issue was that I was putting the wrong web app Id (it didnt exist), but the error was misleading. Can we update the error to be more accurate?

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
#14287

**Comment by panchagnula** [comment]
@calvinsID can we close this since seems like the linked PR fixes this issue?
