### ISSUE TITLE
setup: pip is broken after uninstall 'azure-cli'

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1406]
`pip list` is broken after uninstall the `azure-cli`, same with `install`, so you can't reinstall

```bash
(env27) admins-MacBook-Pro-2:az admin$ pip uninstall azure-cli
Uninstalling azure-cli-0.1.0b9:
  /Users/admin/az/env27/bin/az
  /Users/admin/az/env27/bin/az.bat
  /Users/admin/az/env27/bin/az.completion.sh
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/__init__.py
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/__init__.pyc
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/__main__.py
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/__main__.pyc
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/command_modules/__init__.py
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/command_modules/__init__.pyc
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/main.py
  /Users/admin/az/env27/lib/python2.7/site-packages/azure/cli/main.pyc
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9-py3.5-nspkg.pth
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/DESCRIPTION.rst
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/INSTALLER
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/METADATA
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/RECORD
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/WHEEL
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/metadata.json
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/namespace_packages.txt
  /Users/admin/az/env27/lib/python2.7/site-packages/azure_cli-0.1.0b9.dist-info/top_level.txt
Proceed (y/n)? y
  Successfully uninstalled azure-cli-0.1.0b9
(env27) admins-MacBook-Pro-2:az admin$ pip list
Traceback (most recent call last):
  File "/Users/admin/az/env27/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/Users/admin/az/env27/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/Users/admin/az/env27/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/admin/az/env27/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/admin/az/env27/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'azure'
```

**Comment by derekbekoe** [comment]
@yugangw-msft Can you add the version of pip you had installed?

**Comment by yugangw-msft** [comment]
It is 9.0.1

**Comment by MathiasVandePol** [comment]
I had the same problem. Can you try sudo pip install --upgrade --no-deps --force-reinstall azure-cli
