### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by yijiangzhu** [Azure/azure-cli#14071]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.10
Installer: 

azure-cli 2.8.0

```

**Comment by yungezz** [comment]
hi @yijiangzhu could you pls share error you met?

**Comment by yijiangzhu** [comment]
[/glops/programs]#az aks install-cli
The command failed with an unexpected error. Here is the traceback:

<urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/glops/programs/python3.6/lib/python3.6/http/client.py", line 1423, in connect
    server_hostname=server_hostname)
  File "/glops/programs/python3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/glops/programs/python3.6/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/glops/programs/python3.6/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/glops/programs/python3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/root/lib/azure-cli/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/root/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 319, in k8s_install_cli
    version = urlopen(source_url + '/stable.txt', context=context).read()
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/glops/programs/python3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by seanmck** [comment]
Looks like a transient network issue.
