### ISSUE TITLE
Exception in container registry login command

### ISSUE THREAD

**Issue by AftabSaraz** [Azure/azure-cli#14089]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
Login failed.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1 *

```

**Comment by AftabSaraz** [comment]
he command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='whitelabelprod.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1664, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='whitelabelprod.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 625, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 682, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 531, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/custom.py", line 176, in acr_login
    login_server, username, password = get_login_credentials(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 410, in get_login_credentials
    return _get_credentials(cmd,
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 365, in _get_credentials
    return login_server, EMPTY_GUID, _get_aad_token(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 196, in _get_aad_token
    token_params = _handle_challenge_phase(
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 85, in _handle_challenge_phase
    challenge = requests.get('https://' + login_server + '/v2/', verify=(not should_disable_connection_verify()))
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.3.1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='whitelabelprod.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

**Comment by yonzhan** [comment]
acr

**Comment by toddysm** [comment]
@AftabSaraz would you mind updating the Azure CLI with `brew update && brew upgrade azure-cli` and try again? You seem to be running an outdated version of azure-cli (2.3.1), the latest is 2.8.0 I have on my machine and it is able to connect. 

Let us know if you are experiencing the issue after upgrade and we can investigate.

**Comment by AftabSaraz** [comment]
Ok sure, let me update Azure CLI. Thank you.

**Comment by yugangw-msft** [comment]
This is less likely on ACR, rather on proxy server. Please run other command to cross check like "az group list". 
Meanwhile, i am closing this issue, but please reopen it if it is indeed ACR command issue.
