### ISSUE TITLE
**Sorry but this problem still persistent if you using "Jenkins Docker in Docker"**

### ISSUE THREAD

**Issue by wdrdres3qew5ts21** [Azure/azure-cli#14151]
**Sorry but this problem still persistent if you using "Jenkins Docker in Docker"** 

![image](https://user-images.githubusercontent.com/25000903/86135028-7da61d80-bb14-11ea-932e-49c851da5c9a.png)

![image](https://user-images.githubusercontent.com/25000903/86134254-97933080-bb13-11ea-8a40-2f8f4f825519.png)

![image](https://user-images.githubusercontent.com/25000903/86134392-c14c5780-bb13-11ea-9760-af5da654239e.png)

![image](https://user-images.githubusercontent.com/25000903/86134621-112b1e80-bb14-11ea-9d22-e55cd7c52590.png)]

because Jenkins didn't give you "root user" to the container because security issues in privilege escalation attack !
So if you type anycommand relate to "root user" you will get broken output even "whoami" command !!!
The way to fix is you give additional user argument to container while run it on Jenkins pipeline
```
agent {
   docker {
        image 'mcr.microsoft.com/azure-cli:2.8.0'
        args "--user root --privileged"
    }
}
```

![image](https://user-images.githubusercontent.com/25000903/86135462-0cb33580-bb15-11ea-8928-a91a1c73680e.png)

You will fix this problem !!! But why do "Azure CLI need root user ?"
I don't know about internal code in Azure CLI so hope Microsoft Team can help to fix this problem without needed az bin executed as root.
Thank you very much 😭😭😭

_Originally posted by @wdrdres3qew5ts21 in https://github.com/Azure/azure-cli/issues/613#issuecomment-651812788_

**Comment by yonzhan** [comment]
Jenkins

**Comment by jiasli** [comment]
Hi @wdrdres3qew5ts21, Azure CLI is never designed to be run as root only.

#613 is talking about a separate issue.

The config directory should be your `HOME` folder + `/.azure`, such as `/home/foo/.azure`:

https://github.com/Azure/azure-cli/blob/3b4d10d473a8d72dc2a1607478beb14424ce2004/src/azure-cli-core/azure/cli/core/_environment.py#L10-L12

But in your case, it is `/.azure`:

```
PermissionError: [Errno 13] Permission denied: '/.azure'
```

Could you please check if your `HOME` environment variable has been somehow corrupted? 

```sh
$ echo $HOME
/home/foo
```

**Comment by wdrdres3qew5ts21** [comment]
I already try $HOME enviroment variable it still working fine.
But it located to    "/ "  directory thay perhaps why my error is:  
```
PermissionError: [Errno 13] Permission denied: '/.azure'
```
Because 
```
The config directory should be your HOME folder + /.azure
```
![image](https://user-images.githubusercontent.com/25000903/86256349-6cc3dd80-bbe2-11ea-9863-6b400926af6b.png)

**Comment by fengzhou-msft** [comment]
Try to run the docker as a non-root user with `-u` option: https://github.com/Azure/azure-cli#docker

**Comment by wdrdres3qew5ts21** [comment]
Sorry for late in reply your message I already try both way it still didn't work.
It seem like I must create new Dockerfile base on AzureCLI by myself If I really want to run with another user than Root user.
```
--user $(id -u):$(id -g) -v ${HOME}:/home/az -e HOME=/home/az
```
![image](https://user-images.githubusercontent.com/25000903/87522770-37be8d00-c6b0-11ea-8446-47cc4efe0e26.png)
![image](https://user-images.githubusercontent.com/25000903/87522825-4dcc4d80-c6b0-11ea-9c4a-0421a55943db.png)
```
--user $UID:$GID
```
![image](https://user-images.githubusercontent.com/25000903/87522941-73f1ed80-c6b0-11ea-84da-d910542f5560.png)
![image](https://user-images.githubusercontent.com/25000903/87523007-85d39080-c6b0-11ea-9b4e-86030ff61af6.png)

**Comment by fengzhou-msft** [comment]
According to this [answer](https://stackoverflow.com/a/42822143/2100487), docker-workflow-plugin hardcoded the --user to be the result of whoami, so you actually don't need to provide --user again. In your case, it's an unknown user to the conatiner with uid 1000. Then the home(~) directory falls back to the root directory /. You need `args '-v ${HOME}:/home/az -e HOME=/home/az'` to make user 1000 have the right permission of the home directory inside the docker.

**Comment by wdrdres3qew5ts21** [comment]
Thank you for your help but I think this might be the complicate problem one because now I got stuck at the first problem again that 
```
az aks install-cli
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl"
Connection error while attempting to download client ([Errno 13] Permission denied: '/usr/local/bin/kubectl')
```

![image](https://user-images.githubusercontent.com/25000903/88151184-91810300-cc2c-11ea-9927-cdd41c777b71.png)
The last resort left is must use Root user...
because same problem again "whoami" didn't work so sudo didn't work too.

**Comment by ktibi** [comment]
Hello same issue here,

Need to be root with -u 0 for execute this image in jenkins.

**Comment by guillaume-roche** [comment]
Hello,

I ran into the same issue. Perhaps a cleaner workaround is to override the Azure configuration directory thanks to the `AZURE_CONFIG_DIR` environment variable. See https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-file.

I set it to the workspace directory as it should always be writeable:
```
environment {
    AZURE_CONFIG_DIR = "${env.WORKSPACE}/.azure"
}
```

**Comment by Vinaysv18** [comment]
use USER root this worked for me

**Comment by kumaravelpsandeza** [comment]
> 

This worked for me

**Comment by zammitjohn** [comment]
> Hello,
> 
> I ran into the same issue. Perhaps a cleaner workaround is to override the Azure configuration directory thanks to the `AZURE_CONFIG_DIR` environment variable. See https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-file.
> 
> I set it to the workspace directory as it should always be writeable:
> 
> ```
> environment {
>     AZURE_CONFIG_DIR = "${env.WORKSPACE}/.azure"
> }
> ```
> 
> This way, there is no need to pass additional arguments to the docker.

This worked for me - probably the best solution.

**Comment by till** [comment]
This also happens when I use `az bicep install` in GitHub Actions:

```yaml
    - uses: azure/cli@v2
      with:
        azcliversion: 2.72.0
        inlineScript: |
          echo "Installed"

    - run: az bicep install
```

```
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/_session.py", line 37, in load
    with open(self.filename, 'r', encoding=self._encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.azure/azureProfile.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/az/lib/python3.12/site-packages/azure/cli/__main__.py", line 30, in <module>
    az_cli = get_default_cli()
             ^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/__init__.py", line 955, in get_default_cli
    return AzCli(cli_name='az',
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/__init__.py", line 80, in __init__
    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/_session.py", line 50, in load
    self.save()
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/_session.py", line 54, in save
    with open(self.filename, 'w', encoding=self._encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/runner/.azure/azureProfile.json'
```

I also tried 2.76.0 — same error.

**Comment by till** [comment]
When I add this to my workflow it works:

```yaml
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

I can't even. 😂
