### ISSUE TITLE
[Network] The latest module in dev branch is broken

### ISSUE THREAD

**Issue by MehaKaushik** [Azure/azure-cli#14194]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Network module's vnet commands are broken in the latest dev branch. Calling any command from the module fails bcz of a code error. 

**To Reproduce**
az network vnet {create, list} 

Both fail with:
(env) PS D:\azure-cli> az network vnet list
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "D:\azure-cli\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 446, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "d:\azure-cli\src\azure-cli\azure\cli\command_modules\network\__init__.py", line 39, in load_arguments
    load_arguments(self, command)
  File "d:\azure-cli\src\azure-cli\azure\cli\command_modules\network\_params.py", line 123, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

**Expected behavior**
The command should throw error for the lack of parameters provided. If all the params are provided the command should succeed.

**Environment summary**
CLI version
(env) PS D:\azure-cli> az --version
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4
testsdk                            0.2.4

Extensions:
virtual-wan                        0.1.3

Python location 'D:\azure-cli\env\Scripts\python.exe'
Extensions directory 'C:\Users\mekaushi\.azure\cliextensions'

Python (Windows) 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Additional context**

**Comment by MehaKaushik** [comment]
Additional stack:

(env) PS D:\azure-cli> az network private-link-resource list
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "D:\azure-cli\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 446, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "d:\azure-cli\src\azure-cli\azure\cli\command_modules\network\__init__.py", line 39, in load_arguments
    load_arguments(self, command)
  File "d:\azure-cli\src\azure-cli\azure\cli\command_modules\network\_params.py", line 123, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
@MehaKaushik Please use `azdev setup` to setup the environment again. It need new version of azure-mgmt-network.

**Comment by MehaKaushik** [comment]
@MyronFanQiu  my environment summary is:
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.2
Installer: PIP

azure-cli 2.8.0

Extensions:
virtual-wan 0.1.3

```

This after azdev setup on the latest master. I still see the issue.

**Comment by MyronFanQiu** [comment]
latest `dev` branch? it should work. We have seen such error message several times. Could you run `pip show azure-mgmt-network`?

**Comment by MehaKaushik** [comment]
(env2) PS D:\azure-cli> pip show azure-mgmt-network
Name: azure-mgmt-network
Version: 11.0.0
Summary: Microsoft Azure Network Management Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: d:\azure-cli\env2\lib\site-packages
Requires: msrestazure, azure-common, msrest
Required-by: azure-cli

I updated the azdev and now I am getting new error: 
(env2) PS D:\azure-cli> azdev test

=============
| Run Tests |
=============

No module named 'azure.cli'
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\program files (x86)\python38-32\lib\site-packages\knack\invocation.py", line 225, in execute
    cmd_result = parsed_args.func(params)
  File "c:\program files (x86)\python38-32\lib\site-packages\knack\commands.py", line 148, in __call__
    return self.handler(*args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\knack\commands.py", line 255, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Users\mekaushi\AppData\Roaming\Python\Python38\site-packages\azdev\operations\tests\__init__.py", line 46, in run_tests
    path_table = get_path_table()
  File "C:\Users\mekaushi\AppData\Roaming\Python\Python38\site-packages\azdev\utilities\path.py", line 193, in get_path_table
    from azure.cli.core.extension import EXTENSIONS_DIR  # pylint: disable=import-error
ModuleNotFoundError: No module named 'azure.cli'

**Comment by MyronFanQiu** [comment]
fixed offline
