### ISSUE TITLE
ACR Rotate Key - 'NoneType' object has no attribute 'key_identifier'

### ISSUE THREAD

**Issue by Silvenga** [Azure/azure-cli#14196]
## Describe the bug

The command fails with a stacktrace.

**Command Name**
`acr encryption rotate-key`

**Errors:**

```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'key_identifier'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 513, in rotate_key
    registry.encryption.key_vault_properties.key_identifier = key_encryption_key
AttributeError: 'NoneType' object has no attribute 'key_identifier'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Setup:
```bash
az acr create \
    --name acr \
    --sku Basic \
    --admin-enabled false

az keyvault create \
    --name kv \
    --bypass AzureServices \
    --enable-purge-protection true \
    --enable-soft-delete true \
    --enabled-for-deployment true \
    --enabled-for-disk-encryption true \
    --enabled-for-template-deployment true \
    --sku standard

az keyvault key create \
    --name acr \
    --vault-name kv
```

```bash
ACR_KEY_URL=$(az keyvault key list-versions \
    --name acr \
    --vault-name kv \
    --query '[].kid' -o tsv)

# Is this required?
az acr identity assign \
    --name acr \
    --identities '[system]'

az acr encryption rotate-key \
    --name acr \
    --identity '[system]' \
    --key-encryption-key $ACR_KEY_URL
```

## Expected Behavior

Encryption should be enabled with the system assigned identity and vault key.

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

Extensions:
aks-preview 0.4.53

```

**Comment by Silvenga** [comment]
Ah, this might be due to using a sku of basic for the registry. Either way, I feel that a stack trace should never be given.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yugangw-msft** [comment]
Will polish the error, and yes this is because the registry is not yet encrypted

**Comment by Silvenga** [comment]
Not yet encrypted? Is there another way to enable encryption? It appears that the `[system]` managed identity isn't an option for registry identity when creating the registry. That option is only available afterwards (at least the command currently fails).

The docs suggest that using `rotate-key` can both rotate keys and update encryption settings, and the `update` command doesn't have any documented options for encryption.

**Comment by yugangw-msft** [comment]
Before encrypting existing registry gets supported, you need to enable encryption through user assigned identity first, and then rotate to system assigned identity. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-customer-managed-keys#create-a-registry-with-customer-managed-key

**Comment by Silvenga** [comment]
Ah, got it. Thanks for that insight.
