### ISSUE TITLE
AZ ACR TASK CREATION ERROR: Traceback (most recent call last):

### ISSUE THREAD

**Issue by sandeepmindwave** [Azure/azure-cli#14207]
`Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/task.py", line 200, in acr_task_create
    task_create_parameters=task_create_parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_tasks_operations.py", line 265, in create
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_tasks_operations.py", line 215, in _create_initial
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.containerregistry.v2019_06_01_preview.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Not Found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 44, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 31, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 226, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 106, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 94, in handle_exception
    error = response_dict['error']
TypeError: string indices must be integers
`
WHILE CREATING ACR TASKER 

`az acr task create     --registry stagingregistry     --name staging     --image rstagingregistry.azurecr.io/rstage:{{.Run.ID}}     --image stagingregistry.azurecr.io/stage:latest     --context https://github.com/SANDEEP/STAGING-app.git#Devops      --file Dockerfile     --git-access-token 734e56b549ac5a57makmcamw167
`

**Comment by yonzhan** [comment]
ACR

**Comment by yugangw-msft** [comment]
Please investigate

**Comment by huanwu** [comment]
@sandeepmindwave , thanks for the report. To make it work, you need enable either the commit-trigger or base-image trigger when using the git-access-token. It works if adding "--commit-trigger-enabled false --base-image-trigger-enabled true" in the end of your command. But there's a bug in our side, it should give you the clear error message.

**Comment by huanwu** [comment]
@yugangw-msft I filed another issue by my investigation.  When the status is not expected, it is supposed to throw the error detail. But the cli util failed to parse the error from the ex response.

**Comment by lucassimoesmaistro** [comment]
> @sandeepmindwave , thanks for the report. To make it work, you need enable either the commit-trigger or base-image trigger when using the git-access-token. It works if adding "--commit-trigger-enabled false --base-image-trigger-enabled true" in the end of your command. But there's a bug in our side, it should give you the clear error message.

It works for me.

**Comment by timja** [comment]
Hi is there any progress on this?

While `--commit-trigger-enabled false --base-image-trigger-enabled true`

`--commit-trigger-enabled true` doesn't work, so it seems I can't create a task with a commit trigger enabled?

**Comment by huanwu** [comment]
@timja The commit trigger works. The above issue is caused by an invalid git-access-token I think. We have problem to parse the error as the issue filed in https://github.com/Azure/azure-cli/issues/14343. It works if everything is right.

**Comment by houk-ms** [comment]
#14830

**Comment by timja** [comment]
The actual issue in my case was that the PAT I was using didn’t have admin access to the repo

**Comment by sandeepmindwave** [comment]
> @sandeepmindwave , thanks for the report. To make it work, you need enable either the commit-trigger or base-image trigger when using the git-access-token. It works if adding "--commit-trigger-enabled false --base-image-trigger-enabled true" in the end of your command. But there's a bug in our side, it should give you the clear error message.

@ thanks for replay , i am facing new issue, this command working` **--commit-trigger-enabled false --base-image-trigger-enabled true**` but auto trigger is not working while i get new commit tasker is not running

**Comment by navba-MSFT** [comment]
@sandeepmindwave Apologies for the late reply. Could you please let us know if you still need assistance on this issue ? Awaiting your reply.
