### ISSUE TITLE
'list' object has no attribute 'name'

### ISSUE THREAD

**Issue by jarens7** [Azure/azure-cli#14379]
Trying to run any 'az backup restore restore-disks' command produces this error, tried in PS5, PS7, and Cloudshell.

`The command failed with an unexpected error. Here is the traceback:

'list' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-lt3pwpnx\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-lt3pwpnx\six\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 776, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\backup\custom_base.py", line 299, in restore_disks
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\backup\custom.py", line 445, in restore_disks
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\backup\custom.py", line 306, in show_item
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\backup\custom.py", line 332, in list_items
AttributeError: 'list' object has no attribute 'name'
`

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@jarens7 : Can you please make sure that the parameters passed are correct values? Particularly for recovery point name you can use [```az backup recoverypoint show```](https://docs.microsoft.com/cli/azure/backup/recoverypoint?view=azure-cli-latest#az-backup-recoverypoint-show) command to make sure that the recovery point exists and valid.

**Comment by jarens7** [comment]
> @jarens7 : Can you please make sure that the parameters passed are correct values? Particularly for recovery point name you can use [`az backup recoverypoint show`](https://docs.microsoft.com/cli/azure/backup/recoverypoint?view=azure-cli-latest#az-backup-recoverypoint-show) command to make sure that the recovery point exists and valid.

Yes when I'm using the 'name' field from the 'az backup recovery point' show  command like this:

`
    "location": null,
    "name": "9977524400204",
    "properties": {
      "isInstantIlrSessionActive": false,
      "isManagedVirtualMachine": true,
` 

This gives me the original error.

**Comment by jarens7** [comment]
I got it figured out, the issue was the container name needed to be the result of "az backup item list --resource-group common --vault-name BackupMain --backup-management-type AzureIaasVM --container-name openvpn" for example. I was using the same name for both the 'container name' and 'item name' when in fact the container name needed to be in the format of "IaasVMContainer;iaasvmcontainerv2;management_zone;openvpn" \
   --item-name "VM;iaasvmcontainerv2;management_zone;openvpn" for example.
Thanks!

**Comment by pvrk** [comment]
@jarens7 : Thanks. Ideally, there are 2 combinations. One which uses the full name like you mentioned above "IaasVMContainer;...." and "VM;iaasvmcontainerv2....". Another is to just give friendly name and backup-management-type AzureIaaSVM. I see that you have tried with native/full name approach. Can you please also try with friendly name (then container name and item name can be the same) along with backup management type parameter?

**Comment by pvrk** [comment]
@jarens7 : A gentle reminder

**Comment by pvrk** [comment]
@jarens7 : Another gentle reminder.

**Comment by pvrk** [comment]
Closing this issue since it is fixed for the customer.
