### ISSUE TITLE
azure issue feedback

### ISSUE THREAD

**Issue by aiden-liu** [Azure/azure-cli#14456]
## Describe the bug

**Command Name**
`terraform --version`

**Errors:**
The command failed with an unexpected error. Here is the traceback:

[Errno 5] Input/output error: '/home/lau/.azure/commands/2020-07-22.05-32-22.account_show.225.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 5] Input/output error: '/home/lau/.azure/commands/2020-07-22.05-32-22.account_show.225.log'

To open an issue, please run: 'az feedback'
The command failed with an unexpected error. Here is the traceback:

[Errno 5] Input/output error: '/home/lau/.azure/commands/2020-07-22.05-32-23.account_show.232.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 5] Input/output error: '/home/lau/.azure/commands/2020-07-22.05-32-23.account_show.232.log'

To open an issue, please run: 'az feedback'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior

Return the version

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

```

**Comment by yungezz** [comment]
hi @aiden-liu could you pls share more repro steps? `terraform --version` is terraform command, not azure cli. while your stacktrace is from azure cli.

**Comment by aiden-liu** [comment]
Hi @yungezz after changing privileges of folder "~/.azure/commands" and reconnected to bash, it doesn't show any more. Still not sure why this happened in the first place since I left all the folder privileges to default. As the command does not pop error any more, I suggest to close this issue.

**Comment by yungezz** [comment]
thanks
