### ISSUE TITLE
Issue while copying image files from Azure Blob storage to Azure ML workspace directory

### ISSUE THREAD

**Issue by RehanShahid** [Azure/azure-cli#14530]
Issue while copying image files from Azure Blob storage to Azure ML workspace directory

**Comment by RehanShahid** [comment]
az storage copy --source-blob azure_blob_source_path --destination-file-path ./destination_path
This command is in preview. It may be changed/removed in a future release.
The command failed with an unexpected error. Here is the traceback:

Not valid file
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 85, in storage_copy
    source_blob, source_share, source_file_path, source_local_path)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 78, in get_url_with_sas
    raise ValueError('Not valid file')
ValueError: Not valid file

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
Hi @RehanShahid, your --source value should be valid source url.

**Comment by RehanShahid** [comment]
Thanks @Juliehzl . It is valid source url. Problem is resolved now using :
az storage copy -s source_path -d destination_path --recursive
