### ISSUE TITLE
Unable to perform a file share in azure

### ISSUE THREAD

**Issue by azuresg** [Azure/azure-cli#14579]
I am trying to perform a file share upload in Azure. I am using Katacoda to perform this. The command should have: the account name, account key, share name, source, and path parameters correctly so that the file (index.php) is uploaded to the created directory. The share and directory inside share has same name sgfileshare1.

The path specified in the "source" is downloaded using the command : git clone https://github.com/Azure-Samples/php-docs-hello-world

This is the command I gave : 
az storage file upload --account-name aazure1988 --account-key hDY99b3mLc9ykk+Gas3TCMk1ghS6gvIXyMJOdS+cQ/EjI+RBFCAGKl5DOSTK6jcu9brPS2h1Nn5FfV6FAbCNbg== --share-name sgfileshare1 --source "/home/scrapbook/tutorial/php-docs-hello-world/index.php" --path "aazure1988.file.core.windows.net/sgfileshare1/sgfileshare1/"

However, this is throwing errors (System cannot find the specified path (for both source and path). Can someone please guide me on this. This is a lab session and i have to include source and path.

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help with this issue ? Thanks

**Comment by azuresg** [comment]
I performed a new file share with the below command :  

az storage file upload --account-name wdssd1 --account-key JNXZi+CJhorIxagJFAyOCnVCXoA3xlfb6g+xAQy2nxPT8yxWfjQfkyrXtweu39Cefmj3Nbf8xer00YSBNHR43Q== --share-name wdfileshare --source "/home/scrapbook/tutorial/php-docs-hello-world/index.php" --path "SGDirectory/index.php"

The error message was : 

HTTPSConnectionPool(host='wdssd1.file.core.windows.net', port=443): Max retries exceeded with url: /wdfileshare/SGDirectory/index.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3205b1358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3205b1358>: Failed to establish anew connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wdssd1.file.core.windows.net', port=443): Max retries exceeded with url: /wdfileshare/SGDirectory/index.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3205b1358>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 269, in _perform_request
    response = self._httpclient.perform_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_http/httpclient.py", line 92, in perform_request
    proxies=self.proxies)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wdssd1.file.core.windows.net', port=443): Max retries exceeded with url: /wdfileshare/SGDirectory/index.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3205b1358>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/file/fileservice.py", line 1647, in create_file_from_path
    max_connections, timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/file/fileservice.py", line 1821, in create_file_from_stream
    timeout
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/file/fileservice.py", line 1596, in create_file
    self._perform_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 311, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: HTTPSConnectionPool(host='wdssd1.file.core.windows.net', port=443): Max retries exceeded with url: /wdfileshare/SGDirectory/index.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd3205b1358>: Failed to establish a new connection: [Errno -2] Name or service not known',))

What should i do to rectify this connection error.

**Comment by Juliehzl** [comment]
Hi @azuresg, if you want to upload files to file share, the directory in  path should exist, otherwise it cannot get parent name.

Could you show more about your environment information with `az --version`? it seems you are using very old azure cli.
