### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.redhatopenshift.operations'

### ISSUE THREAD

**Issue by kwoodson** [Azure/azure-cli#14614]
**Describe the bug**
I have created PR https://github.com/Azure/azure-cli/pull/14535 to enhance our latest updates to the aro module.  I have passed all module tests with `azdev test aro`.  

The CI is failing with the following error message:
```
Verifying profile: 2017-03-09-profile
Loading all commands, arguments, and help...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.11/x64/bin/azdev", line 11, in <module>
    load_entry_point('azure-cli-dev-tools', 'console_scripts', 'azdev')()
  File "/home/vsts/work/1/s/tools/automation/__main__.py", line 25, in main
    args.func(args)
  File "/home/vsts/work/1/s/tools/automation/verify/verify_load_all.py", line 27, in verify_load_all
    create_invoker_and_load_cmds_and_args(az_cli)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/file_util.py", line 76, in create_invoker_and_load_cmds_and_args
    invoker.commands_loader.load_arguments()
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 454, in load_arguments
    cmd.load_arguments()  # this loads the arguments via reflection
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 597, in generic_wait_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 402, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.redhatopenshift.operations'
```
**To Reproduce**
The CI run is reproducing this every time.

**Expected behavior**
Pass the CI tests.

**Environment summary**

git clone azure-cli
python3 -m venv env
source ./env/bin/activate
pip install azdev
azdev setup -c

`azdev test aro`

**Additional context**

When calling the `./scripts/ci/test_profile_integration.sh` script locally, this fails with:
```
...
pkg_resources.VersionConflict: (azure-cli 2.10.0.dev20200731183502 (/home/kwoodson/git/azure-cli/src/azure-cli), Requirement.parse('azure-cli==2.10.0'))
...
pkg_resources.DistributionNotFound: The 'azure-cli==2.10.0' distribution was not found and is required by the application
```

The CI fails on the `test_profile_integration.sh` script specifically on the `2017-03-09-profile`.  It does pass on the `latest`.  

Any assistance would be great, thanks!

**Comment by yonzhan** [comment]
add to S174

**Comment by haroldrandom** [comment]
@kwoodson You could checkout azure-mgmt-openshift 0.1.0, I believe there is no operation module inside azure/mgmt/redhatopenshift/. There might be some bugs while releasing this package.
Please verify.

**Comment by haroldrandom** [comment]
https://github.com/Azure/azure-cli/pull/14535/files?file-filters%5B%5D=.py#r463926021

**Comment by yungezz** [comment]
cc @fengzhou-msft since it's openshift modules

**Comment by kwoodson** [comment]
Adding back in the resource_type statement fixed the error.
