### ISSUE TITLE
Unable to get `az cli cloud register --cloud-config` to work

### ISSUE THREAD

**Issue by carlowahlstedt** [Azure/azure-cli#14653]
**Describe the bug**
Unable to use the `--cloud-config` option to register a new cloud.

**To Reproduce**
1. Run `az cloud show -n AzureUSGovernment -o json >> cloud.json`
1. Delete the isActive and name entries in the cloud.json file
1. Run `az cloud register -n test --cloud-config @"./cloud.json"`

Error:
```
The following endpoints are required for the CLI to function and were not specified on the command line, in the cloud config or could not be autodetected.
Specify them on the command line or through the cloud config file:
--endpoint-resource-manager, --endpoint-active-directory, --endpoint-active-directory-resource-id, --endpoint-active-directory-graph-resource-id
```

**Expected behavior**
A new cloud is registered

**Environment summary**
brew install
v2.10.1
macOS 10.15.6
zsh

**Additional context**
[link to docs](https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest#az-cloud-register)

**Comment by qwordy** [comment]
@fengzhou-msft

**Comment by niralishah130** [comment]
Hi team. I'm on Azure Global team. This issue is blocking us from testing a customer deliverable. Is there anyway to escalate getting help here? Appreciate your time here.

**Comment by fengzhou-msft** [comment]
@niralishah130 based on the current design, you cannot use the json output from `az cloud show` directly. Instead the json file should be similar to the options but with camel case or snake case. So a json file looks like this:
```
{
  'endpointResourceManager':'',
  'endpointActiveDirectory':'',
  'suffixAcrLoginServerEndpoint':'',
  'suffixKeyvaultDns':'',
  ...
}
```

**Comment by carlowahlstedt** [comment]
@fengzhou-msft when I change the cloud.json file to have the contents you put above it fails:
```
az cloud register -n test --cloud-config @"./cloud.json"
The command failed with an unexpected error. Here is the traceback:

dictionary keys changed during iteration
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/cloud/custom.py", line 90, in register_cloud
    c = _build_cloud(cmd.cli_ctx, cloud_name, cloud_config=cloud_config,
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/cloud/custom.py", line 42, in _build_cloud
    for key in cloud_config:
RuntimeError: dictionary keys changed during iteration

To open an issue, please run: 'az feedback'
```

I had previously tried all different forms of the json but without luck and all the same error as above without using the format that is output from showing an endpoint as json. I tried with dashes, without, etc. My specific json used for the above error is:
```json
{
  "endpointResourceManager": "https://management.usgovcloudapi.net/",
  "endpointActiveDirectory": "https://login.microsoftonline.us",
  "suffixAcrLoginServerEndpoint": ".azurecr.us",
  "suffixKeyvaultDns": ".vault.usgovcloudapi.net"
}
```

**Comment by niralishah130** [comment]
@fengzhou-msft @qwordy the JSON file suggested did not work, as you can see above. Any other suggestions?

**Comment by fengzhou-msft** [comment]
@niralishah130 there was some bug to handle the camel case which failed silently on Python 3.6 and now raises an error in your Python 3.8 environment. I will submit a PR to fix it.
For now, please use the following snake case:
```
{
      "endpoint_resource_manager": "https://management.usgovcloudapi.net/",
      "endpoint_active_directory": "https://login.microsoftonline.us",
      "suffix_acr_login_server_endpoint": ".azurecr.us",
      "suffix_keyvault_dns": ".vault.usgovcloudapi.net"
}
```

**Comment by carlowahlstedt** [comment]
Looks like that also does not work. Any other suggestions?
```
az cloud register -n test --cloud-config @"./cloud.json"
The command failed with an unexpected error. Here is the traceback:

dictionary keys changed during iteration
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/cloud/custom.py", line 90, in register_cloud
    c = _build_cloud(cmd.cli_ctx, cloud_name, cloud_config=cloud_config,
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/cloud/custom.py", line 42, in _build_cloud
    for key in cloud_config:
RuntimeError: dictionary keys changed during iteration

To open an issue, please run: 'az feedback'
```

cloud.json:
```
{
      "endpoint_resource_manager": "https://management.usgovcloudapi.net/",
      "endpoint_active_directory": "https://login.microsoftonline.us",
      "suffix_acr_login_server_endpoint": ".azurecr.us",
      "suffix_keyvault_dns": ".vault.usgovcloudapi.net"
}
```

**Comment by fengzhou-msft** [comment]
@carlowahlstedt It looks like the code itself cannot pass in Python 3.8. Please do not use the config file for Python 3.8 before we release the fix. You can specify the endpoint with command options:
`az cloud register -n test --endpoint-resource-manager "https://management.usgovcloudapi.net/" --endpoint-active-directory "https://login.microsoftonline.us" --suffix-acr-login-server-endpoint ".azurecr.us" --suffix-keyvault-dns ".vault.usgovcloudapi.net"`

**Comment by fengzhou-msft** [comment]
Azure CLI 2.11.0 will be released on Aug 25 and you should be able to register a cloud with the output from `az cloud show`.
