### ISSUE TITLE
Webapp:az webapp create failed with an unexpected error after upgrade to azure-cli 2.10.1

### ISSUE THREAD

**Issue by NiekGr** [Azure/azure-cli#14758]
Dear Sir/Madam,

**Command Name**
`az webapp create`

**Errors:**
```
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : 'configs'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 167, in create_webapp
    match['setter'](cmd=cmd, stack=match, site_config=site_config)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2527, in update_site_config
    for k, v in stack['configs'].items():
KeyError: 'configs'
'configs'
```

**Describe the bug**
Our release pipeline runs on hosted Azure DevOps agents. Releases that worked fine yesterday, do not work anymore.
It looks like the DevOps agents have upgraded azure-cli from 2.9.1 to 2.10.1.

The scripts are run on Powershell Core running on ubuntu-20.4 agents, but I have also tried ubuntu-18.04.

**To Reproduce**
Upgrade azure-cli from 2.9.1 to 2.10.1 and use `az webapp create`

**Expected behavior**
No errors

**Environment summary**
```
[command]/usr/bin/az --version
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.6.10 (default, Aug  6 2020, 08:50:24) 
[GCC 7.5.0]
```

Thank you.

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
hi @arrownj could you pls also help to have a look at this issue? Thanks.

**Comment by arrownj** [comment]
Hi @calvinsID , could you please help with this issue ? It seems to have something to do [this](https://github.com/Azure/azure-cli/blob/58b68dd9e3feaca20254540ed77653a187537fd7/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L167) update.

**Comment by calvinsID** [comment]
@NiekGr sorry for the inconvenience caused. working on a fix

**Comment by NiekGr** [comment]
@calvinsID thank you for your fast respond. When can we expect azure-cli 1.10.2 to be available on the Azure DevOps agents?
In the meantime what can I do to workaround this issue?

**Comment by eholman** [comment]
I see 2.11.0 is released at August 25, 2020 but the DevOps agents is currently using 2.10.1 so it's still an issue.

Is there any workaround available? I couldn't find any command to set it separately. 

Also `az upgrade` doesn't work in the pipeline, so that doesn't help:
``` 
az: 'upgrade' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
##[error]Script failed with exit code: 1
```

**Comment by yonzhan** [comment]
@fengzhou-msft  to help with
