### ISSUE TITLE
AZ Login and Request call fails when there is a value in the environment variables for proxy (all_proxy, https_proxy, http_proxy)

### ISSUE THREAD

**Issue by esnell-midmark** [Azure/azure-cli#14812]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
403 error when a proxy is in place
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',))) 

**To Reproduce**
have a value set in all_proxy
This is set when a company uses secure tools, e.g. ZScaler 
e.g. all_proxy=123.123.123.123:9400
enter az login
select the account to use
return to the CLI CMD window and a 403 is shown.

To succeed
set all_proxy=
and then execute az login

you can reproduce the same error by executing
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"

**Expected behavior**
When executing az login from the CLI CMD line a successful login should result in being shown the login page at https://login.microsoftonline.com/
and then success with the available subscriptions shown in the CLI command window

**Environment summary**

**Additional context**
Details of a request call shown below
executed first with value in all_proxy and executed second without a value.
first fails and second is successful (200)

"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\connectionpool.py", line 597, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\connectionpool.py", line 807, in _prepare_proxy
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\connection.py", line 324, in connect
  File "http\client.py", line 919, in _tunnel
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\connectionpool.py", line 641, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-zeusizwz\requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>set all_proxy=

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
200

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>

**Comment by yonzhan** [comment]
add to S175

**Comment by ddeimeke** [comment]
Hi!

I am facing the same problem, when is a solution expected to be delivered?

Cheers

Dirk

**Comment by MaddyMicrosoft** [comment]
The 403 Tunnel connection failed is the proxy refusing the CONNECT tunnel to login.microsoftonline.com, before any Azure endpoint is reached. As covered on #5841, the CLI delegates HTTP to Python requests/urllib3, which honor HTTP_PROXY/HTTPS_PROXY/ALL_PROXY - there's nothing CLI-side to change. 
The fix is proxy-side: allow the Entra sign-in endpoints through, or exclude them with NO_PROXY (clearing all_proxy, as you found, is the blunt version). Closing as not a CLI bug.
