### ISSUE TITLE
Webapp:Setting Custom Entity Framework Connection String type via CLI fails

### ISSUE THREAD

**Issue by MrBirdJesus** [Azure/azure-cli#14826]
## Describe the bug

**Command Name**
`az webapp config connection-string set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\command_modules\appservice\custom.py", line 1082, in update_connection_strings
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a new Resource Group
- Create a new Web App
- Run the following command: `az webapp config connection-string set --name [Name of WebApp] --resource-group [Resource Group] --connection-string-type Custom --settings DataEntities=[Entity Framework Connection String]`

## Expected Behavior
A new connection string to be set via CLI with the type of Custom.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

Extensions:
application-insights 0.1.8
azure-devops 0.17.0
logic 0.1.0

```
## Additional Context
I'm able to use the exact connection string via the portal with the type of "Custom" fine.

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Assigning it to myself to repro

**Comment by calvinsID** [comment]
@MrBirdJesus can you try putting your settings under quotation marks like so: `--settings DataEntities=**'**[Entity Framework Connection String]**'**`

**Comment by MrBirdJesus** [comment]
> @MrBirdJesus can you try putting your settings under quotation marks like so: `--settings DataEntities='[Entity Framework Connection String]'`

Passing a raw string like that works. It's not a workaround I can use in this instance however as I need to build the connection string based on variables and parameters passed to a Powershell script during resource group deployment. I was trying to pass it as `--settings DataEntities=$entityFrameworkConnectionString`

**Comment by seligj95** [comment]
Unable to repro. @MrBirdJesus - can you please let us know if this is still an issue?

**Comment by seligj95** [comment]
closing due to no response. please re-open if this is still an issue.
