### ISSUE TITLE
Storage Blob Upload - Error: path should be string...

### ISSUE THREAD

**Issue by gregberns** [Azure/azure-cli#14851]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
command_modules/storage/operations/blob.py, ln 418, in upload_block_blob
    if os.path.isfile(file_path) and os.stat(file_path).st_size > 50000 * 4 * 1024 * 1024:
../lib/python3.8/genericpath.py, ln 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

## To Reproduce:

Just trying to upload some files to blob storage for the first time for a static website `$web`.

- `az storage blob upload-batch --auth-mode login -s ~/Downloads/upload -d "http://<my storage account>.blob.core.windows.net/$web`

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.10.0 *

```

**Comment by gregberns** [comment]
Update:
This supposedly was reported in #14641 and 'fixed' in hotfix version 2.10.1
https://github.com/Azure/azure-cli/issues/14641#issuecomment-669938641

After updating with `brew update && brew upgrade azure-cli`

```
az -v
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.10.1/libexec/bin/python'
Extensions directory '/Users/gb/.azure/cliextensions'

Python (Darwin) 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

```
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:1063: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py:2719: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/common/_connection.py:82: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/cosmosdb/v2017_04_17/common/_connection.py:91: SyntaxWarning: "is" with a literal. Did you mean "=="?
  self.protocol = self.protocol if parsed_url.scheme is '' else parsed_url.scheme
The command failed with an unexpected error. Here is the traceback:

container_name should not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 325, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 297, in storage_blob_upload_batch
    include, result = _upload_blob(cmd, client, file_path=src, container_name=destination_container_name,
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/util.py", line 225, in wrapper
    return True, func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 281, in _upload_blob
    return upload_blob(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 451, in upload_blob
    return type_func[blob_type]()
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 444, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 449, in create_blob_from_path
    _validate_not_none('container_name', container_name)
  File "/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/common/_error.py", line 130, in _validate_not_none
    raise ValueError(_ERROR_VALUE_NONE.format(param_name))
ValueError: container_name should not be None.
```
