### ISSUE TITLE
Cannot upload folder to $root container while the folder has child folder and files inside

### ISSUE THREAD

**Issue by AmoebaCell** [Azure/azure-cli#14869]
## Describe the bug

**Command Name**
``
az storage blob upload-batch --account-name jianbingstorage --source source -d $root --account-key xxxxxxxxx
**Errors:**
The requested URI does not represent any resource on the server. ErrorCode: InvalidUri
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:d095f5c7-a01e-0074-2476-77a0f4000000
Time:2020-08-21T04:51:57.6233540Z</Message><UriPath>https://jianbingstorage.blob.core.windows.net/$root/test/b-nogamma.png</UriPath></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 652, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\__init__.py", line 248, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\__init__.py", line 191, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\operations\blob.py", line 271, in storage_blob_upload_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\util.py", line 218, in wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\operations\blob.py", line 247, in _upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\operations\blob.py", line 360, in upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli\azure\cli\command_modules\storage\operations\blob.py", line 353, in upload_block_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 470, in create_blob_from_path
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 589, in create_blob_from_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 1108, in _put_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 430, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 358, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 344, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: The requested URI does not represent any resource on the server. ErrorCode: InvalidUri
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:d095f5c7-a01e-0074-2476-77a0f4000000
Time:2020-08-21T04:51:57.6233540Z</Message><UriPath>https://jianbingstorage.blob.core.windows.net/$root/test/b-nogamma.png</UriPath></Error>

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
1. Create $root container in blob storage.
2. ln local driver, create a folder. And then, create sub-folder inside.
3. Put file in the folder the sub-folder.
4. Try to use the az storage blob upload-batch --account-name storageAccount --account-key storageKey --source localFolder -d $root

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
The upload should be able to recursively upload related content.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.70 *

Extensions:
resource-graph 1.0.0

```

**Comment by Juliehzl** [comment]
Hi @AmoebaCell, could you upgrade your azure cli to latest version and try again?
Here is install instruction https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.

**Comment by AmoebaCell** [comment]
![image](https://user-images.githubusercontent.com/46150839/91000875-bfc37b00-e5fc-11ea-881f-91d7c6d5b0db.png)

az version info
{
  "azure-cli": "2.10.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.10.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "resource-graph": "1.0.0"
  }
}

source folder structure: 1 sub folder (test) which has 4 files. And 5 files in source folder.
uploading command: az storage blob upload-batch --account-name xxxxxxx --account-key xxxxxxx -s source -d $root

account key has been changed after the verification.

**Comment by AmoebaCell** [comment]
Find the information from link: https://docs.microsoft.com/en-us/rest/api/storageservices/working-with-the-root-container#managing-the-root-container -> Important: **A blob in the root container cannot include a forward slash (/) in its name.**
Based on this information, does it mean "sub-virtual folder is not supported in $root", am I understanding correct?

**Comment by Juliehzl** [comment]
Hi @AmoebaCell, you are right for general storage account you cannot upload blobs with sub-virtual folder which has '/' in blob name.
