### ISSUE TITLE
az interactive: cannot import name 'BlockBlobService' from 'azure.storage.blob'

### ISSUE THREAD

**Issue by ashutoshvarma** [Azure/azure-cli#14908]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az interactive`

## Environment Summary
```
Linux-5.7.13-975.native-x86_64-with-glibc2.29
Python 3.8.5
Installer: PIP

azure-cli 2.5.1

Extensions:
interactive 0.4.4

```
## Additional Context

To resolve this I followed #13539 and uninstall prompt_toolkit (which was installed earlier with ipython). That fix the above error but a new error keep popping inside az interactive session.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/oreki/.azure/cliextensions/interactive/azext_interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/home/oreki/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)
  File "/home/oreki/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 49, in load_arguments
    command.load_arguments()
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 309, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3.8/site-packages/knack/commands.py", line 105, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 577, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 617, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module------------------------------------------------------------------------------------------------
    return _bootstrap._gcd_import(name[level:], package, level)                       *
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                     *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                   *
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked-------------------------------------------------------------------------------------------------
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/acr/custom.py", line 10, in <module>----------------------------------------------------------------------
    from ._utils import (   : use commands outside the application
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/acr/_utils.py", line 29, in <module>
    from ._archive_utils import upload_source_code, check_remote_source_code
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 15, in <module>
    from azure.storage.blob import BlockBlobServicethe previous command
ImportError: cannot import name 'BlockBlobService' from 'azure.storage.blob' (/usr/lib/python3.8/site-packages/azure/storage/blob/__init__.py)
```

**Comment by yonzhan** [comment]
add to backlog

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at the missing package issue? thanks

**Comment by fengzhou-msft** [comment]
@ashutoshvarma can you update to the latest azure-cli? `azure-storage-blob` is replaced by `azure-multiapi-storage`.

**Comment by ashutoshvarma** [comment]
Ok. I will report after updating az cli
