### ISSUE TITLE
Azure cli alway append error message when execute az command with --help parameter

### ISSUE THREAD

**Issue by bz-wow** [Azure/azure-cli#14939]
Installed Azure cli v2.11.0 from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli.

Hyper-V System: 
Windows 10 Enterprise, version 2004, build 19041.450

Issue:
Run "az --help" or "az -h" in cmd window, it always displays the help info, and after a short while, it then prints the following error.

> For more specific examples, use: az find "az "

The command failed with an unexpected error. Here is the traceback:

'pypi'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cqhwq_hi\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 579, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cqhwq_hi\knack\parser.py", line 262, in parse_args
  File "argparse.py", line 1734, in parse_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\parser.py", line 280, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1972, in _parse_known_args
  File "argparse.py", line 1912, in consume_optional
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1024, in __call__
  File "argparse.py", line 2366, in print_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\parser.py", line 178, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cqhwq_hi\knack\parser.py", line 252, in format_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\_help.py", line 179, in show_help
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\util.py", line 318, in show_updates_available
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\util.py", line 239, in get_az_version_string
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\util.py", line 213, in get_cached_latest_versions
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\util.py", line 194, in _update_latest_from_github
KeyError: 'pypi'

To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment]
installing

**Comment by fengzhou-msft** [comment]
@bz-wow can you check whether you can visit `https://raw.githubusercontent.com/Azure/azure-cli/master/src/azure-cli-core/setup.py`?

As a workaround, you can modify the `~/.azure/versionCheck.json` file with the following content:
`{"versions": {"azure-cli": {"local": "2.11.0", "pypi": "2.11.0"}, "telemetry": {"local": "1.0.5", "pypi": "1.0.5"}, "core": {"local": "2.11.0", "pypi": "2.11.0"}}, "update_time": "2020-08-27 21:41:07.181109", "check_time": "2020-08-27 21:41:09.931759"}`
