### ISSUE TITLE
Crash when running az keyvault list using a managed identity

### ISSUE THREAD

**Issue by A30004028** [Azure/azure-cli#14941]
## Describe the bug

**Command Name**
`az keyvault list`

**Errors:**
```
get_token() takes 1 positional argument but 2 were given
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
    response = self.next.send(request)
azure/core/pipeline/_base.py, ln 69, in send
    _await_result(self._policy.on_request, request)
azure/core/pipeline/_tools.py, ln 29, in await_result
    result = func(*args, **kwargs)
core/pipeline/policies/_authentication.py, ln 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
TypeError: get_token() takes 1 positional argument but 2 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Assign a system managed identity to a VM
- Give it access to a key vault
- on the VM, log into az cli using `az login --identity`
- `az keyvault list  tsv --query '[].name'`

## Environment Summary
```
Linux-5.3.0-1035-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.0

```

**Comment by A30004028** [comment]
Also fails when running only `az keyvault list`

**Comment by A30004028** [comment]
Full trace

```The command failed with an unexpected error. Here is the traceback:

get_token() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 782, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/custom.py", line 196, in list_keyvault
    return list(vault_list)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 122, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 74, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/keyvault/v2019_09_01/operations/_vaults_operations.py", line 842, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 436, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
TypeError: get_token() takes 1 positional argument but 2 were given

**Comment by jim-minter** [comment]
cc @Makdaam .  ARO has seen also this issue, it broke our deployment pipelines.

**Comment by fengzhou-msft** [comment]
@bim-msft can you take a look at this issue?

**Comment by Makdaam** [comment]
I checked on our RHEL7 VMs in Azure.
I'm getting the same exception with get_token arguments from 2.11.0 installed via RPM from the https://packages.microsoft.com/yumrepos/azure-cli repo. 
2.10.1 (previous to 2.11 in the repository) and earlier versions installed via RPM work as expected (they return the keyvault data).

**Comment by yungezz** [comment]
cc @houk-ms  since this is a typical non-actionable error code

**Comment by bim-msft** [comment]
@A30004028 @jim-minter @Makdaam It's a keyvault authentication bug involved in version 2.11.0, please downgrade your CLI to 2.10.1 and lock the version temporarily. We are fixing this, sorry for the inconvenience.

**Comment by jkvbe** [comment]
There is the same bug in blob storage. I found the following instances:

`az storage blob list`
`az storage blob show`

upload, download, snapshot,... work fine.

**Comment by bim-msft** [comment]
Adding @Juliehzl for storage commands.

**Comment by jkvbe** [comment]
Note that with CLI version 2.10.1 _az storage blob list_ works, but _az storage blob show_ doesn't.

**Comment by Juliehzl** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/15118

**Comment by Juliehzl** [comment]
please try with edge build https://github.com/Azure/azure-cli#edge-builds now and official release will be available on 9/22

**Comment by stazz** [comment]
For those still waiting for fix, the workaround for _az storage blob show_ is to downgrade to `2.2.0` (I admit I didn't try _all_ versions between current newest and 2.2.0, but 2.2.0 worked).

**Comment by yungezz** [comment]
hi @bim-msft is this issue ok to close the issue now?

**Comment by bim-msft** [comment]
Resolved
