### ISSUE TITLE
az functionapp crashes in WSL2

### ISSUE THREAD

**Issue by JesHansen** [Azure/azure-cli#14970]
## Describe the bug
Using Ubuntu-20.04 in WSL2. After installing azure-cli with 
```
sudo apt install azure-cli -y
```
I'm able to login, create resource groups, create storage accounts etc. However, the az functionapp subcommands seems to be broken. az feedback --verbose gave the following output: 

**Command Name**
`az functionapp create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named 'decorator'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fabric/connection.py", line 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 528, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 496, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/appservice/custom.py", line 25, in <module>
    from fabric import Connection
  File "/usr/lib/python3/dist-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/lib/python3/dist-packages/fabric/connection.py", line 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp create -n {} -g {} --storage-account {} --app-insights {} --compumption-plan-location {} --runtime {}`

## Expected Behavior
I expected a function app to be created, but had a crash happen instead.

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
functionapp

**Comment by fengzhou-msft** [comment]
Duplicate with #14011. Please follow the [instruction](https://github.com/Azure/azure-cli/issues/14011#issue-640943121) to upgrade your azure-cli.

**Comment by JesHansen** [comment]
Thanks @fengzhou-msft, upgrading solved the issue.
