### ISSUE TITLE
az 2.11.1 az vmss diagnostics set fails 'NoneType' object has no attribute 'storage_profile'

### ISSUE THREAD

**Issue by hobdell-SAP** [Azure/azure-cli#15075]
## Describe the bug

**Command Name**
`az vmss diagnostics set`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

First, I set environment variables for the`_vmssdiagnosticsstorageaccount` and the `_vmssname`.
Then I ran these commands (note: MacOS, so the `date` command is not GNU).

```
$ _EXPIRY=$(date -jf "%a %d %b %Y %T %Z" -v "+1m" "$(date)" +"%Y-%m-%dT%H:%MZ") && echo "Expiry: $_EXPIRY"
$ _SAS="$(az storage account generate-sas --expiry "${_EXPIRY}" --permissions adclpruw --resource-types sco --services btfq  --account-name "${_vmssdiagnosticsstorageaccount}")"
$ az vmss diagnostics get-default-config --debug -o json > config.json 2> protected-config.json
$ sed -e "s#__DIAGNOSTIC_STORAGE_ACCOUNT__#${__vmssdiagnosticsstorageaccount}#g" -i bk ./config.json
$ sed -e "s#__VM_OR_VMSS_RESOURCE_ID__#${_vmssname}#g" -i bk ./config.json
$ sed -e "s/__STORAGE_ACCOUNT_NAME__/${_vmssname}/" -i bk ./protected-config.json
$ sed -e "s/__SAS_TOKEN_WITHOUT_LEADING_QUESTION_MARK__/$(echo "$_SAS"|sed -e 's/\&/\\&/g')/" -i bk ./protected-config.json
$ vi protected-config.json #Delete the first line, which reads: "Protected settings with storage account info is required to work with the default configurations, e.g.", and save the file.

# Both of the following commands fail:
$ az vmss diagnostics set --vmss-name "${_vmssname}"  --settings config.json --protected-settings protected-config.json
$ az vmss diagnostics set --vmss-name "${_vmssname}"  --settings @./config.json --protected-settings @./protected-config.json
```

- _Put any pre-requisite steps here..._
- subscription, resource group set as defaults (using `az config --default group=xyz`, etc). 

## Expected Behavior

Diagnostics are set on the VMSS.

## Observed Behaviour

Command fails with a traceback:

```

'NoneType' object has no attribute 'storage_profile'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 782, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 2878, in set_vmss_diagnostics_extension
    is_linux_os = _is_linux_os(vmss.virtual_machine_profile)
  File "/usr/local/Cellar/azure-cli/2.11.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 173, in _is_linux_os
    os_type = vm.storage_profile.os_disk.os_type.value if vm.storage_profile.os_disk.os_type else None
AttributeError: 'NoneType' object has no attribute 'storage_profile'
```

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.11.1

```
## Additional Context
I upgraded azure-cli from 2.0.12:
``` 
brew upgrade azure-cli
```
Then I had to re-link it:
```
brew link --overwrite azure-cli
```
This also didn't work, so then I ran `azure upgrade` (which finally worked).

**Comment by yungezz** [comment]
cc @houk-ms

**Comment by yungezz** [comment]
#14287

**Comment by qwordy** [comment]
Will be fixed on 12/29/2020.
