### ISSUE TITLE
webapp deployment fails with getaddrinfo errors

### ISSUE THREAD

**Issue by q00u** [Azure/azure-cli#15108]
## Describe the bug

Zip deployment from the command line ultimately fails, every time. I'm going off the instructions on https://docs.microsoft.com/en-us/azure/app-service/deploy-zip and don't appear to be missing anything. But, it still fails at `getaddrinfo`

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responses with status code 202
The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='isssalesdemo.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07061290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 159, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\util\connection.py", line 57, in create_connection
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 301, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x07061290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-hb486cm7\urllib3\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='isssalesdemo.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07061290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\custom.py", line 343, in enable_zip_deploy_webapp
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\custom.py", line 388, in enable_zip_deploy
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2484, in _check_zip_deployment_status
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\api.py", line 75, in get
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-umfcm_n2\requests\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='isssalesdemo.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07061290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76 *

```
## Additional Context

It works if I zipdeploy from https://(my app).scm.azurewebsites.net/ZipDeployUI just not from the cli. So I know the .zip is correct.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@calvinsID when you get a chance can you check this error "Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07061290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))" seems like the command is failing trying to make a call to the Kudu for checking status of deployment.

**Comment by btardif** [comment]
@sarsharma lets try and repro this, close if no repro with latest CLI version

**Comment by sarsharma** [comment]
Unable to repro this issue with the latest CLI
