### ISSUE TITLE
Webapp:Pipeline fails with an unexpected error ['int' object is not iterable]

### ISSUE THREAD

**Issue by bauca** [Azure/azure-cli#15167]
## Describe the bug

**Command Name**
`az webapp config appsettings set -n $Env:WebAppName -g $Env:ResourceGroup --settings "InstrumentationEngine_EXTENSION_VERSION=~1" "XDT_MicrosoftApplicationInsights_BaseExtensions=~1"`

**Errors:**
The command failed with an unexpected error. Here is the traceback:

**'int' object is not iterable**
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cqhwq_hi\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-b47qj8aq\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_c27a1q9\azure\cli\core\__init__.py", line 782, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-5dayjeuz\azure\cli\command_modules\appservice\custom.py", line 257, in update_app_settings
TypeError: 'int' object is not iterable

## To Reproduce:
`             - task: AzureCLI@2
              displayName: 'Azure CLI : Create App Plan and App with Application Insights'
              inputs:
                azureSubscription:  'MySubscriptionID-Hidden'
                scriptType: pscore
                scriptPath: '$(Pipeline.Workspace)/DeployArtifact/MyScriptName-Hidden.ps1'
                addSpnToEnvironment: true`
Running a pipeline with the following command in a azure powershell script within a AzureCLI@2 task.
`az webapp config appsettings set -n $Env:WebAppName -g $Env:ResourceGroup --settings "InstrumentationEngine_EXTENSION_VERSION=~1" "XDT_MicrosoftApplicationInsights_BaseExtensions=~1"`

## Expected Behavior
Pipeline runs sucessfully.
## Environment Summary
```
Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] *

```

**Comment by yonzhan** [comment]
webapp

**Comment by pmolinam** [comment]
I'm facing this issue aswell.
Is a netcore3.1 function running on a Windows host.
The **az functionapp config appsettings set** command is running on a Ubuntu 1604 agent

Any solutions here?

**Comment by seligj95** [comment]
Please update to the latest CLI and let us know if you are still facing this issue.

**Comment by bauca** [comment]
This is too old, I can't even verity that anymore, for me, it can be closed.
