### ISSUE TITLE
Webapp:Az webapp up fails when it's executed from a directory in the root.

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#15199]
## Expected behavior
- I can run az webapp up from a directoy in root as long as the directory has valid code to deploy...

## Observed behavior
- az webapp up fails when it's executed from a directory in the root.

![2020-09-17_11h18_07](https://user-images.githubusercontent.com/4119816/93511685-0a70a400-f8d8-11ea-8d11-d15a284b67c9.gif)

## Suggestions

- this scenario should work, if there a technical limitation that I'm not seeing it should at least fail gracefully
- We can do an error message like:
  - "Deploying form <current directory> is not supported.... for more info see <some aka.ms link>"

## Command output

C:\Demo2>az webapp up -n bk-dot-net-test
The webapp 'bk-dot-net-test' doesn't exist
Creating webapp 'bk-dot-net-test' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir C:\Demo2 ...
The command failed with an unexpected error. Here is the traceback:

[Errno 13] Permission denied: 'C:\\\\Demo2.zip'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mtleih48\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yndvnbfi\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-a_t_wugh\azure\cli\core\__init__.py", line 782, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yndvnbfi\azure\cli\command_modules\appservice\custom.py", line 3638, in webapp_up
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yndvnbfi\azure\cli\command_modules\appservice\_create_util.py", line 37, in zip_contents_from_dir
  File "zipfile.py", line 1113, in __init__
PermissionError: [Errno 13] Permission denied: 'C:\\\\Demo2.zip'

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
We agreed to use TEMP folder for ZIP generation
