### ISSUE TITLE
Upload to blob always fails with authentication error

### ISSUE THREAD

**Issue by skingd** [Azure/azure-cli#15232]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I have a storage blob that I can, with the account used, upload, download and delete blobs from the portal without any issue. I've confirmed the account is being used and functional. I've run az login tons of times and can read all the data including from the blob.

I'm calling the following command to upload:

az storage blob upload --account-name $STORAGE_ACCOUNT --container-name $CONTAINER --name $NAME --file $EXPORT_PATH --auth-mode login

The error is:
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.

Happens with every account I try. If I use the depricated --auth-mode key  it works just fine.
**To Reproduce**

1. Create storage account
2. Assign permissions to proper account
3. Create file
4. Run blob upload command

**Expected behavior**

This should initiate blob upload
**Environment summary**

Windows 10 pro with pip installed Azure CLI v2.11.1 
**Additional context**

**Comment by yonzhan** [comment]
add to S176

**Comment by Juliehzl** [comment]
Hi @skingd, may I know your RABC role to the storage account?
To avoid this issue, please make sure you have "Storage Blob Data Contributor" or higher role to the storage account. Here is the document to assign RBAC role https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal.

In addition, if you are the owner of storage account, using `az storage account keys list` to get your storage account key and add `--account-key ` in your upload command.

**Comment by skingd** [comment]
> Hi @skingd, may I know your RABC role to the storage account?
> To avoid this issue, please make sure you have "Storage Blob Data Contributor" or higher role to the storage account. Here is the document to assign RBAC role https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal.
> 
> In addition, if you are the owner of storage account, using `az storage account keys list` to get your storage account key and add `--account-key ` in your upload command

The managed identity has reader and blob contributor. My account has owner and the command still doesn't work. I'm not comfortable putting the storage account key on a public forum, but I can engaged over Teams for more details if needed.

**Comment by Juliehzl** [comment]
Hi @skingd, if you have concern about account key, you could set environment variable AZURE_STORAGE_KEY with account key. CLI will query the key autimatically.

But for `--auth-mode login`, if it has Storage Blob Data Contributor role, it should work with upload operation.  Could you make sure the right role assigned and share the debug log with us using `--debug` in your command?

**Comment by skingd** [comment]
Here is the debug message:

`Command arguments: ['storage', 'blob', 'upload', '--account-name', 'zw2ssprdstaroleaudit', '--container-name', 'audits', '--name', '10.13.2020_azure_role_audit.csv', '--file', 'C:\\Audits\\10.13.2020_azure_role_audit.csv', '--auth-mode', 'login', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001C8520378B8>, <function OutputProducer.on_global_arguments at 0x000001C85234A288>, <function CLIQuery.on_global_arguments at 0x000001C852377EE8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'storage': ['azure.cli.command_modules.storage']
Loading command modules:
Name                  Load Time    Groups  Commands
storage                   0.031        51       229
Total (1)                 0.031        51       229
These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_ai_did_you_mean_this']  
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0  
Loaded 51 groups, 229 commands.
Found a match in the command table.
Raw command  : storage blob upload
Command table: storage blob upload
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001C853BD3828>]
az_command_data_logger : command args: storage blob upload --account-name {} --container-name {} --name {} --file {} --auth-mode {} --debug
metadata file logging enabled - writing logs to 'C:\Users\sking\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001C853EC8E58>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x000001C853F30B88>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001C853F30C18>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001C853F30D38>]Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001C85234A318>, <function CLIQuery.handle_query_parameter at 0x000001C852377F78>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x000001C853F30AF8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001C853F30CA8>]
attempting to read file C:\Users\sking\.azure\accessTokens.json as utf-8-sig
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - Authority:Performing instance discovery: ...
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - Authority:Performing static instance discovery
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - Authority:Authority validated via static instance discovery
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Found 9 potential entries.
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Resource specific token found.
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'UiCRiGxXaX4TCX9o1MuogdesHtXVoY2gOvHoVcqV/kE=', RefreshTokenId: b'IgDBlhB7slHPYvEoPblZLAIP+X83R9dZGVc9fSQEy5s='
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Cached token is expired at 2020-10-05 14:29:03.924578.  Refreshing
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - TokenRequest:called to refresh a token from the cache   
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - TokenRequest:Getting a new token from a refresh token   
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /78c203fa-fb8a-4eae-bc56-3936897f05a1/oauth2/token HTTP/1.1" 200 3468
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - OAuth2Client:Get Token Server returned this correlation_id: 3e7eb537-4c15-4697-80ac-6f7efa277a43
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Created new cache entry from refresh response.
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Removing entry.
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Adding entry AccessTokenId: b'wPsTLNzGPZXqWtYjx9gnHNKB8R2fr/xOQQzXLzxgVuQ=', RefreshTokenId: b'rt/2DH+sYnxEUCS3WYRJ7NnQ85W3RlamZNzNmsLQGT4='
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Updating 8 cached refresh tokens
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Remove many: 8
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Add many: 8
adal-python : 3e7eb537-4c15-4697-80ac-6f7efa277a43 - CacheDriver:Returning token refreshed after expiry.     
Getting data service client service_type=BlockBlobService
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=41f01374-0d7c-11eb-9298-b42e99a09a0e Outgoing request: Method=PUT, Path=/audits/10.13.2020_azure_role_audit.csv, Query={'timeout': None}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': 
None, 'If-Match': None, 'If-None-Match': None, 'x-ms-blob-cache-control': None, 'x-ms-blob-content-type': 'application/vnd.ms-excel', 'x-ms-blob-content-disposition': None, 'x-ms-blob-content-md5': None, 'x-ms-blob-content-encoding': None, 'x-ms-blob-content-language': None, 'Content-Length': '1772807', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.7.4; Windows 10) AZURECLI/2.12.0 (PIP)', 'x-ms-client-request-id': '41360fd8-0d7c-11eb-b894-b42e99a09a0e', 'x-ms-date': 'Tue, 13 Oct 2020 17:48:09 GMT'}.
urllib3.connectionpool : Starting new HTTPS connection (1): zw2ssprdstaroleaudit.blob.core.windows.net:443   
urllib3.connectionpool : https://zw2ssprdstaroleaudit.blob.core.windows.net:443 "PUT /audits/10.13.2020_azure_role_audit.csv HTTP/1.1" 403 422
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=41f01374-0d7c-11eb-9298-b42e99a09a0e Receiving Response: Server-Timestamp=Tue, 13 Oct 2020 17:48:10 GMT, Server-Request-ID=1bf5614e-e01e-0009-1989-a171c7000000, HTTP Status Code=403, Message=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Headers={'content-length': '422', 'content-type': 'application/xml', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '1bf5614e-e01e-0009-1989-a171c7000000', 'x-ms-error-code': 'AuthenticationFailed', 'date': 'Tue, 13 Oct 2020 17:48:10 GMT'}.       
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=41f01374-0d7c-11eb-9298-b42e99a09a0e Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Tue, 13 Oct 2020 17:48:10 GMT, Server-Request-ID=1bf5614e-e01e-0009-1989-a171c7000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:1bf5614e-e01e-0009-1989-a171c7000000Time:2020-10-13T17:48:10.9688900Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=41f01374-0d7c-11eb-9298-b42e99a09a0e Retry policy did not allow for a retry: Server-Timestamp=Tue, 13 Oct 2020 17:48:10 GMT, Server-Request-ID=1bf5614e-e01e-0009-1989-a171c7000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:1bf5614e-e01e-0009-1989-a171c7000000Time:2020-10-13T17:48:10.9688900Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>.  
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
    raise ex
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\command_modules\storage\__init__.py", line 334, in new_handler
    raise ex
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\core\__init__.py", 
line 784, in default_command_handler
    return op(**command_args)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\command_modules\storage\operations\blob.py", line 474, in upload_blob
    return type_func[blob_type]()
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\cli\command_modules\storage\operations\blob.py", line 467, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 470, in create_blob_from_path
    timeout=timeout)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 589, in create_blob_from_stream
    timeout=timeout)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 1108, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 430, in _perform_request
    raise ex
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 358, in _perform_request
    raise ex
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "C:\Users\sking\AppData\Local\Programs\Python\Python37\lib\site-packages\azure\multiapi\storage\v2018_11_09\common\_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError:
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.


cli.azure.cli.core.azclierror : ServiceError:
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.

ServiceError:
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.

Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001C853C07168>, <function _create_token_credential.<locals>._cancel_timer_event_handler at 0x000001C8562311F8>]
az_command_data_logger : exit code: 1
Command ran in 1.833 seconds (init: 0.097, invoke: 1.735)
telemetry.save : Save telemetry record of length 3089 in cache
telemetry.check : Negative: The C:\Users\sking\.azure\telemetry.txt was modified at 2020-10-13 10:42:35.945032, which in less than 600.000000 s`

Confirmed that blob contributor role is assigned to the manged identity.

**Comment by Juliehzl** [comment]
Hi @skingd, your role assignment should be fine, but still cannot reproduce your issue and may need more information. Could you share the file content to upload? 
@xiafu-msft could you see the log in SRP for request id 1bf5614e-e01e-0009-1989-a171c7000000?

**Comment by skingd** [comment]
> Hi @skingd, your role assignment should be fine, but still cannot reproduce your issue and may need more information. Could you share the file content to upload?
> @xiafu-msft could you see the log in SRP for request id 1bf5614e-e01e-0009-1989-a171c7000000?

Sorry for the delay. Holidays and illness.

I've validated the permissions and added some extra to no avail. If you're available, I can teams/skype meet so you can see the configuration. I have MI working with .net core both on-prem and in Azure Functions to write blobs just fine - no issues at all. Just seems to be PS that is struggling.

**Comment by Juliehzl** [comment]
HI @skingd, feel free to ping me via teams when you are available
