### ISSUE TITLE
az aks install-cli ignores --install-location flag for kubelogin

### ISSUE THREAD

**Issue by ahoka** [Azure/azure-cli#15244]
~~~
$ az aks install-cli --only-show-errors --install-location "${PWD}/kubectl"
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpd01x3msv/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 325, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version, kubelogin_install_location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 436, in k8s_install_kubelogin    shutil.move(download_path, install_location)
  File "/opt/az/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/opt/az/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/az/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'
~~~

## Expected Behavior

az should work without root privileges.

## Environment Summary
```
Linux-5.4.0-1026-azure-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.0

```

**Comment by ahoka** [comment]
Disregard that, I need to use --kubelogin-install-location. You just broke backward compatibility...
