### ISSUE TITLE
CLI argument parsing IndexError with `=`

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1529]
I typed `=` instead of `-` and the CLI crashed showing a stacktrace.

```
$ az storage blob list =c ''
string index out of range
Traceback (most recent call last):
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli/azure/cli/main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 99, in execute
    if noun[0] == '-':
IndexError: string index out of range
```

**Comment by tjprescott** [comment]
The problem here is actually not with the = sign. It is trying to find a '-' in ''.
