### ISSUE TITLE
az deployment group create error message regressed in 2.12.1

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-cli#15346]
## Describe the bug

**Command Name**

`az deployment group create`

**Errors:**

```
Command arguments: ['deployment', 'group', 'create', '--name', 'd9764fa9-8de7-4fab-b628-a86f1ab29b25', '--resource-group', 'euw-apipt-dev-rg-03', '--template-file', './azuredeploy.json', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f4ff4e4c950>, <function OutputProducer.on_global_arguments at 0x7f4ff499d6a8>, <function CLIQuery.on_global_arguments at 0x7f4ff4730950>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
Loading command modules:
Name                  Load Time    Groups  Commands
resource                  0.030        34       158
Total (1)                 0.030        34       158
Loaded 34 groups, 158 commands.
Found a match in the command table.
Raw command  : deployment group create
Command table: deployment group create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f4ff3bb86a8>]
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f4ff3b2fea0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f4ff3b3dd90>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f4ff3b3de18>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f4ff3b2fd08>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f4ff499d730>, <function CLIQuery.handle_query_parameter at 0x7f4ff47309d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f4ff3b3dd08>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f4ff3b3dea0>]
attempting to read file ./azuredeploy.json as utf-8-sig
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
{'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f4ff1002b70>, 'parameters': {}, 'mode': 'Incremental'}}
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0fbe9ddf-04bf-4b96-bdc6-032844dfaa9c/resourcegroups/euw-apipt-dev-rg-03/providers/Microsoft.Resources/deployments/d9764fa9-8de7-4fab-b628-a86f1ab29b25/validate?api-version=2020-06-01'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-5.4.0-1026-azure-x86_64-with-debian-buster-sid) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-resource/10.2.0 Azure-SDK-For-Python AZURECLI/2.12.1 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : b'{"properties": {"parameters": {}, "mode": "Incremental", template:{\n  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",\n  "contentVersion": "1.0.0.0",\n  "parameters": {\n  },\n  "variables": {\n  },\n  "resources": [\n    {\n      "type": "Microsoft.Storage/storageAccounts",\n      "name": "euwapiptdevst02",\n      "apiVersion": "2018-11-01",\n      "location": "[resourceGroup().location]",\n      "kind": "StorageV2",\n      "sku": {\n        "name": "Standard_LRS"\n      }\n    }\n  ]\n}\n}}'
attempting to read file /home/tda/.azure/accessTokens.json as utf-8-sig
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - Authority:Performing instance discovery: ...
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - Authority:Performing static instance discovery
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - Authority:Authority validated via static instance discovery
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Found 3 potential entries.
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Resource specific token found.
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'E08V7r1IB8svqR8VBpweMaIORYcVOlJxleFtJr5/q+M=', RefreshTokenId: b'm1XwGdY02GYcb+M1IupdjZfcn4yggWm9dp2Oop1Re1U='
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Cached token is expired at 2020-09-28 16:00:55.514153.  Refreshing
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - TokenRequest:called to refresh a token from the cache
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /f6dd1854-a44d-45a5-9537-c809a5d76c74/oauth2/token HTTP/1.1" 200 3075
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - OAuth2Client:Get Token Server returned this correlation_id: d205e6f7-9fe5-48ee-93b3-f2ee721d57e9
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Created new cache entry from refresh response.
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Removing entry.
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Adding entry AccessTokenId: b'iInGG3eFHowTLaJG08EGEbojikOaDwDw1d0UDe1Kw6g=', RefreshTokenId: b'6Knz+rnBsSgR7jzxsX+4Mgwxxn1Lw6ssimKEH7AwwTI='
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Updating 2 cached refresh tokens
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Remove many: 2
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Add many: 2
adal-python : d205e6f7-9fe5-48ee-93b3-f2ee721d57e9 - CacheDriver:Returning token refreshed after expiry.
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "POST /subscriptions/0fbe9ddf-04bf-4b96-bdc6-032844dfaa9c/resourcegroups/euw-apipt-dev-rg-03/providers/Microsoft.Resources/deployments/d9764fa9-8de7-4fab-b628-a86f1ab29b25/validate?api-version=2020-06-01 HTTP/1.1" 400 597
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '7b5fd8ef-180a-41cf-afbb-567f09f184f5'
msrest.http_logger :     'x-ms-correlation-request-id': '7b5fd8ef-180a-41cf-afbb-567f09f184f5'
msrest.http_logger :     'x-ms-routing-request-id': 'NORTHEUROPE:20200929T090928Z:7b5fd8ef-180a-41cf-afbb-567f09f184f5'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 29 Sep 2020 09:09:28 GMT'
msrest.http_logger :     'Content-Length': '597'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.","details":[{"code":"PreflightValidationCheckFailed","message":"Preflight validation failed. Please refer to the details for the specific errors.","details":[{"code":"StorageAccountInAnotherResourceGroup","target":"euwapiptdevst02","message":"The account euwapiptdevst02 is already in another resource group in this susbscription."}]}]}}
msrest.exceptions : The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 378, in initialize
    self._operation.set_initial_status(initial_response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 218, in set_initial_status
    self._raise_if_bad_http_status_and_method(response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 140, in _raise_if_bad_http_status_and_method
    "Invalid return status for {!r} operation".format(self.method))
msrestazure.polling.arm_polling.BadStatus: Invalid return status for 'POST' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 507, in deploy_arm_template_at_resource_group
    no_prompt=no_prompt)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 542, in _deploy_arm_template_at_resource_group
    validation_poller = mgmt_client.validate(resource_group_name, deployment_name, deployment)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_deployments_operations.py", line 3261, in validate
    return LROPoller(self._client, raw_result, get_long_running_output, polling_method)
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 130, in __init__
    self._polling_method.initialize(self._client, self._response, deserialization_callback)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 381, in initialize
    raise CloudError(initial_response)
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.

cli.azure.cli.core.azclierror : ValidationError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.
ValidationError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'd9764fa9-8de7-4fab-b628-a86f1ab29b25' is not valid according to the validation procedure. The tracking id is '7b5fd8ef-180a-41cf-afbb-567f09f184f5'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f4ff3bb88c8>]
Command ran in 4.026 seconds (init: 0.998, invoke: 3.028)

```

## To Reproduce:

Create the following arm template:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
  "variables": {
  },
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "name": "euwapiptdevst02",
      "apiVersion": "2018-11-01",
      "location": "[resourceGroup().location]",
      "kind": "StorageV2",
      "sku": {
        "name": "Standard_LRS"
      }
    }
  ]
}
```

Run the command:

`az deployment group create --name $(uuidgen) --resource-group euw-apipt-dev-rg-03 --template-file ./azuredeploy.json --debug`

## Expected Behavior

CLI should report back an error indicating the resource (storage account) already exists.

```
msrest.http_logger : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'testdeploy' is not valid according to the validation procedure. The tracking id is '27de7bab-4670-4c96-be92-9a82d75d16fc'. See inner errors for details.","details":[{"code":"PreflightValidationCheckFailed","message":"Preflight validation failed. Please refer to the details for the specific errors.","details":[{"code":"StorageAccountInAnotherResourceGroup","target":"euwapiptdevst02","message":"The account euwapiptdevst02 is already in another resource group in this susbscription."}]}]}}
msrest.exceptions : The template deployment 'testdeploy' is not valid according to the validation procedure. The tracking id is '27de7bab-4670-4c96-be92-9a82d75d16fc'. See inner errors for details.
cli.azure.cli.core.util : Azure Error: InvalidTemplateDeployment
Message: The template deployment 'testdeploy' is not valid according to the validation procedure. The tracking id is '27de7bab-4670-4c96-be92-9a82d75d16fc'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'testdeploy' is not valid according to the validation procedure. The tracking id is '27de7bab-4670-4c96-be92-9a82d75d16fc'. See inner errors for details.
Exception Details:
	Error Code: PreflightValidationCheckFailed
	Message: Preflight validation failed. Please refer to the details for the specific errors.
cli.azure.cli.core.util : Azure Error: PreflightValidationCheckFailed
Message: Preflight validation failed. Please refer to the details for the specific errors.
Exception Details:
	Error Code: StorageAccountInAnotherResourceGroup
	Message: The account euwapiptdevst02 is already in another resource group in this susbscription.
	Target: euwapiptdevst02
Azure Error: PreflightValidationCheckFailed
Message: Preflight validation failed. Please refer to the details for the specific errors.
Exception Details:
	Error Code: StorageAccountInAnotherResourceGroup
	Message: The account euwapiptdevst02 is already in another resource group in this susbscription.
	Target: euwapiptdevst02
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fdc9f3641e0>]
az_command_data_logger : exit code: 1
Command ran in 0.992 seconds (init: 0.141, invoke: 0.851)
telemetry.save : Save telemetry record of length 5862 in cache
```

## Environment Summary
```
Linux-5.4.0-1026-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.1

```
## Additional Context

This works in version:

```
app # az --version
azure-cli                         2.11.1 *

core                              2.11.1 *
telemetry                          1.0.5 *

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.10 (default, May 21 2020, 05:54:39) 
[GCC 9.2.0]


```

**Comment by yonzhan** [comment]
deployment

**Comment by noelbundick** [comment]
Issue persists in `2.13.0`, the CLI error message is not actionable without using `--debug` and visually parsing the HTTP response

Template w/ an error:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "functions": [],
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Web/staticSites",
      "apiVersion": "2020-06-01",
      "name": "noelbundick",
      "location": "[resourceGroup().location]",
      "sku": {
        "tier": "Free"
      },
      "properties": {
        "repositoryUrl": "https://github.com/noelbundick/website",
        "branch": "main",
        "customDomains": [
          "www.noelbundick.com"
        ]
      }
    }
  ],
  "outputs": {}
}
```

Submitting a deployment:

```
noel@Azure:~$ az deployment group create -g staticsite --template-file site.json
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'site' is not valid according to the validation procedure. The tracking id is '552f65bb-341d-4a07-af12-029d97bd74ee'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.
```

Full details

```
noel@Azure:~$ az deployment group create -g staticsite --template-file site.json --debug
Command arguments: ['deployment', 'group', 'create', '-g', 'staticsite', '--template-file', 'site.json', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3468904950>, <function OutputProducer.on_global_arguments at 0x7f34684556a8>, <function CLIQuery.on_global_arguments at 0x7f34681e7950>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
Loading command modules:
Name                  Load Time    Groups  Commands
resource                  0.012        35       164
Total (1)                 0.012        35       164
These extensions are not installed and will be skipped: ['azext_ai_did_you_mean_this']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
ai-examples               0.160         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
Total (1)                 0.160         1         1
Loaded 36 groups, 165 commands.
Found a match in the command table.
Raw command  : deployment group create
Command table: deployment group create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f3467691620>]
az_command_data_logger : command args: deployment group create -g {} --template-file {} --debug
metadata file logging enabled - writing logs to '/home/noel/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f3467641400>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f3467612f28>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f34675a8048>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f34675a8158>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3468455730>, <function CLIQuery.handle_query_parameter at 0x7f34681e79d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f3467612ea0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f34675a80d0>]
attempting to read file site.json as utf-8-sig
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
{'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f3465aef3c8>, 'parameters': {}, 'mode': 'Incremental'}}
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/7a458fa8-81c7-438f-a27e-2e11fdf4ecca/resourcegroups/staticsite/providers/Microsoft.Resources/deployments/site/validate?api-version=2020-06-01'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid) msrest/0.6.18 cloud-shell/1.0 msrest_azure/0.6.3 azure-mgmt-resource/10.2.0 Azure-SDK-For-Python AZURECLI/2.13.0 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : b'{"properties": {"parameters": {}, "mode": "Incremental", template:{\n  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",\n  "contentVersion": "1.0.0.0",\n  "parameters": {},\n  "functions": [],\n  "variables": {},\n  "resources": [\n    {\n      "type": "Microsoft.Web/staticSites",\n      "apiVersion": "2020-06-01",\n      "name": "noelbundick",\n      "location": "[resourceGroup().location]",\n"sku": {\n        "tier": "Free"\n      },\n      "properties": {\n        "repositoryUrl": "https://github.com/noelbundick/website",\n        "branch": "main",\n        "customDomains": [\n          "www.noelbundick.com"\n        ]\n      }\n    }\n  ],\n  "outputs": {}\n}}}'
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2006
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2006
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "POST /subscriptions/7a458fa8-81c7-438f-a27e-2e11fdf4ecca/resourcegroups/staticsite/providers/Microsoft.Resources/deployments/site/validate?api-version=2020-06-01 HTTP/1.1" 400 441
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1198'
msrest.http_logger :     'x-ms-request-id': '4d2f6097-6704-42a7-9e51-f2f8b41224e5'
msrest.http_logger :     'x-ms-correlation-request-id': '4d2f6097-6704-42a7-9e51-f2f8b41224e5'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20201025T203431Z:4d2f6097-6704-42a7-9e51-f2f8b41224e5'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Sun, 25 Oct 2020 20:34:31 GMT'
msrest.http_logger :     'Content-Length': '441'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"InvalidSkuName","message":"Invalid skuName."}]}]}}
msrest.exceptions : The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 378, in initialize
    self._operation.set_initial_status(initial_response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 218, in set_initial_status
    self._raise_if_bad_http_status_and_method(response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 140, in _raise_if_bad_http_status_and_method
    "Invalid return status for {!r} operation".format(self.method))
msrestazure.polling.arm_polling.BadStatus: Invalid return status for 'POST' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 511, in deploy_arm_template_at_resource_group
    no_prompt=no_prompt, template_spec=template_spec)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 546, in _deploy_arm_template_at_resource_group
    validation_poller = mgmt_client.validate(resource_group_name, deployment_name, deployment)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_deployments_operations.py", line 3261, in validate
    return LROPoller(self._client, raw_result, get_long_running_output, polling_method)
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 130, in __init__
    self._polling_method.initialize(self._client, self._response, deserialization_callback)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 381, in initialize
    raise CloudError(initial_response)
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: Azure Error: InvalidTemplateDeployment
Message: The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.

cli.azure.cli.core.azclierror : Azure Error: InvalidTemplateDeployment
Message: The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'site' is not valid according to the validation procedure. The tracking id is '4d2f6097-6704-42a7-9e51-f2f8b41224e5'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f3467691840>]
az_command_data_logger : exit code: 1
Command ran in 0.961 seconds (init: 0.147, invoke: 0.814)
telemetry.save : Save telemetry record of length 3313 in cache
telemetry.check : Negative: The /home/noel/.azure/telemetry.txt was modified at 2020-10-25 20:25:49.618736, which in less than 600.000000 s
```

Likewise, I expect the CLI to expand the inner error details and return a meaningful error message with both the code and message. In this case, `InvalidSkuName` / `Invalid skuName.`, respectively
