### ISSUE TITLE
az logic workflow list errors out after adding ips to access control list

### ISSUE THREAD

**Issue by donantoniosantos** [Azure/azure-cli#15417]
**Describe the bug**

After adding IPs to the access control list and running `az logic workflow list` , I would get the following:

```
az logic workflow list
Command group 'logic' is experimental and not covered by customer support. Please use with discretion.
The command failed with an unexpected error. Here is the traceback:

Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
Traceback (most recent call last):
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1360, in _deserialize
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1518, in deserialize_data
KeyError: 'FlowAccessControlConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\six\six.py", line 703, in reraise
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\commands\__init__.py", line 678, in _run_job
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-core\azure\core\paging.py", line 122, in __next__
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\azure-core\azure\core\paging.py", line 77, in __next__
  File "C:\Users\.\.azure\cliextensions\logic\azext_logic\vendored_sdks\logic\operations\_workflow_operations.py", line 96, in extract_data
    deserialized = self._deserialize('WorkflowListResult', pipeline_response)
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1294, in __call__
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1360, in _deserialize
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1516, in deserialize_data
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1547, in deserialize_iter
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1547, in <listcomp>
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1529, in deserialize_data
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1364, in _deserialize
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\exceptions.py", line 51, in raise_with_traceback
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1360, in _deserialize
  File "C:\Users\vs~1\AppData\Local\Temp\pip-install-d4ph977u\msrest\msrest\serialization.py", line 1518, in deserialize_data
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'

To open an issue, please run: 'az feedback'
```

**To Reproduce**

add an IP range to the access controls of a logic app workflow and run `az logic workflow list`
**Expected behavior**

Expecting to show details of logic workflow resources

**Environment summary**

```
azure-cli                          2.5.0 *

command-modules-nspkg              2.0.3
core                               2.5.0 *
nspkg                              3.0.4
telemetry                          1.0.4 *

Extensions:
logic                              0.1.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory [removed]

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Additional context**

**Comment by yonzhan** [comment]
logic

**Comment by donantoniosantos** [comment]
@yonzhan hello, know of any updates on this by chance?

**Comment by yonzhan** [comment]
logic service team will take a look.
