### ISSUE TITLE
Extracting the Universal Packages tooling fails inside container

### ISSUE THREAD

**Issue by sheigel** [Azure/azure-cli#15428]
## Describe the bug

**Command Name**
`az artifacts universal publish       --organization https://dev.azure.com/orgname/     --project="projectname"     --scope project     --feed feedname     --name my-first-package     --version 0.0.1     --description "Welcome to Universal Packages"     --path ./sqlpackage.zip`

**Errors:**
```
An error occurred while extracting the Universal Packages tooling: [Errno 2] No such file or directory: '/root/.azure/azuredevops/cli/tools/artifacttool/d708283a-ad69-464d-a538-d8628cab4145/native\\amd64\\libbz2.so.1.0'
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.172/artifacttool': '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.172/artifacttool'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/artifacts/universal.py", line 56, in publish_package
    return artifact_tool.publish_universal(organization, project, feed, name, version, description, path)
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 54, in publish_universal
    return self.run_artifacttool(organization, args, "Publishing")
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 68, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 72, in run
    self.start(command_args, env)
  File "/root/.azure/cliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 39, in start
    env=env)
  File "/opt/az/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/az/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.172/artifacttool': '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.172/artifacttool'
```

## To Reproduce:
On a windows machine running a ubuntu based linux container execute the artifact publish command

## Environment Summary
```
Linux-4.19.76-linuxkit-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.1

Extensions:
azure-devops 0.18.0
databricks 0.5.0

```

**Comment by yonzhan** [comment]
artifacts
