### ISSUE TITLE
Error when running  az container logs ('ascii' codec can't encode character)

### ISSUE THREAD

**Issue by joelfransson** [Azure/azure-cli#15437]
## Describe the bug

**Command Name**
`az container logs`

**Errors:**
```
'ascii' codec can't encode character '\xf6' in position 11556: ordinal not in range(128)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/container/custom.py, ln 552, in container_logs
    print(log.content)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 11556: ordinal not in range(128)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container logs --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-45-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.1

```

**Comment by yonzhan** [comment]
container

**Comment by hahazhugithub** [comment]
Same issue we are encountering

**ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ascii' codec can't encode character '\u2192' in position 1181: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
**

**Comment by yonzhan** [comment]
container instance service team should look into this
