### ISSUE TITLE
UnexpectedError - "No module named 'azure.mgmt.network.v2018_08_01'"

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#15431]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
No module named 'azure.mgmt.network.v2018_08_01'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-tuw8_17y\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-unpacked-wheel-cpn0gwyu\six.py, ln 703, in reraise
...
cli\command_modules\container\custom.py, ln 286, in _get_vnet_network_profile
azure\mgmt\network\_network_management_client.py, ln 5336, in subnets
ModuleNotFoundError: No module named 'azure.mgmt.network.v2018_08_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az container create --cpu {} --environment-variables {} {} {} {} --image {} --location {} --memory {} --name {} --ports {} --registry-password {} --registry-username {} --resource-group {} --subnet {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.12.1

```
## Additional Context

I try re-installing the Azure CLI, but the error remains.
And the same command works well when executed via the Cloud Shell.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by martyglaubitz** [comment]
I encountered the same issue seems to be releated to the Network parameters (--vnet and --subnet) when left out, the container creation works, but then you can't update the network anymore...

**Comment by mdufourneaud4datagalaxy** [comment]
What is strange, is that the same script works well when executed via the cloud shell.
I am wondering what are the differences between the 2 environments 🤔

**Comment by martyglaubitz** [comment]
@mdufourneaud4datagalaxy i guess the cloud shell runs a different python Version?

**Comment by cerginio** [comment]
For me this script is working from local CLI, but fails from AzureDevops release pipeline (see below).
Agents used from Azure Pipelines pool:
**vs2017-win2016
windows-2019**

------------ Azure CLI script -------------
az container create `
--name curitydev3-hello-world `
--resource-group "CurityDev3" `
--image "mcr.microsoft.com/azuredocs/aci-helloworld" `
--ports 80, 443 `
--vnet "curitydev3-VNET" `
--subnet containerSubnet `
--cpu 1 --memory 1.5 --os-type Linux `
--debug


From the logs I got the version using locally:
  **azure.mgmt.network.v2019_04_01**

----------------------------------------------- log ----------------------------------------------------
2020-10-23T09:38:54.4839040Z [command]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1603445904382.ps1'"
2020-10-23T09:39:01.3233943Z UnexpectedError: The command failed with an unexpected error. Here is the traceback:
2020-10-23T09:39:01.3351682Z No module named 'azure.mgmt.network.v2018_08_01'
2020-10-23T09:39:01.3353119Z Traceback (most recent call last):
2020-10-23T09:39:01.3353875Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tuw8_17y\knack\cli.py", line 215, in invoke
2020-10-23T09:39:01.3355161Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 654, in execute
2020-10-23T09:39:01.3356422Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
2020-10-23T09:39:01.3358414Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 711, in _run_job
2020-10-23T09:39:01.3359468Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-cpn0gwyu\six.py", line 703, in reraise
2020-10-23T09:39:01.3360578Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 688, in _run_job
2020-10-23T09:39:01.3361536Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\commands\__init__.py", line 325, in __call__
2020-10-23T09:39:01.3362566Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v8nptj_b\azure\cli\core\__init__.py", line 784, in default_command_handler
2020-10-23T09:39:01.3363613Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-s56abhv8\azure\cli\command_modules\container\custom.py", line 190, in create_container
2020-10-23T09:39:01.3364722Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-s56abhv8\azure\cli\command_modules\container\custom.py", line 286, in _get_vnet_network_profile
2020-10-23T09:39:01.3365845Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-v0h_67b1\azure\mgmt\network\_network_management_client.py", line 5336, in subnets
2020-10-23T09:39:01.3366918Z ModuleNotFoundError: No module named 'azure.mgmt.network.v2018_08_01'
2020-10-23T09:39:01.3367504Z To open an issue, please run: 'az feedback'

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by garin** [comment]
I have similar issue.

```
RESOURCE_GROUP="myresource"
VNET_NAME="myvnet"
INFRASTRUCTURE_SUBNET=`az network vnet subnet show --resource-group ${RESOURCE_GROUP} --vnet-name $VNET_NAME --name infrastructure-subnet --query "id" -o tsv | tr -d '[:space:]'`
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No module named 'azure.mgmt.network.v2021_08_01'
```

I'm already upgrade to 2.39.0

```
% az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
containerapp                      0.3.10
azure-devops                      0.24.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource               21.0.0

Python location '/usr/bin/python3'
Extensions directory '/home/yyy/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0]
```
