### ISSUE TITLE
az vm boot-diagnostics get-boot-log: 'StorageAccountListKeysResult' object has no attribute 'key1'

### ISSUE THREAD

**Issue by ashikv** [Azure/azure-cli#1544]
I am unable to use az vm boot-diagnostics get-boot-log, it breaks on attempt to use key1:

'StorageAccountListKeysResult' object has no attribute 'key1'
Traceback (most recent call last):
  File "/home/vashik/src/python/azure/.env/lib/python3.5/site-packages/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/vashik/src/python/azure/.env/lib/python3.5/site-packages/azure/cli/core/application.py", line 140, in execute
    result = expanded_arg.func(params)
  File "/home/vashik/src/python/azure/.env/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 274, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/vashik/src/python/azure/.env/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 484, in get_boot_log
    keys.key1,
AttributeError: 'StorageAccountListKeysResult' object has no attribute 'key1'

**Comment by ashikv** [comment]
```diff --git a/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py b/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
index 1d19168..a89a375 100644
--- a/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
+++ b/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py
@@ -481,7 +481,7 @@ def get_boot_log(resource_group_name, vm_name):
     storage_client = get_data_service_client(
         BlockBlobService,
         storage_account.name,
-        keys.key1,
+        keys.keys[0],
         endpoint_suffix=CLOUD.suffixes.storage_endpoint) # pylint: disable=no-member

     class StreamWriter(object): # pylint: disable=too-few-public-methods
```

**Comment by tjprescott** [comment]
PR #1568 merged so this is fixed. Thanks @ashikv for your contribution!
