### ISSUE TITLE
az storage directory create python error

### ISSUE THREAD

**Issue by cmrkz** [Azure/azure-cli#15601]
## Describe the bug

**Command Name**
`az storage directory create`

**Errors:**
```
'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
storage/v2018_11_09/common/storageclient.py, ln 358, in _perform_request
    raise ex
storage/v2018_11_09/common/storageclient.py, ln 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
storage/v2018_11_09/common/_error.py, ln 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: Bad Request
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
...
</BODY></HTML>



storage/v2018_11_09/common/storageclient.py, ln 374, in _perform_request
    if isinstance(ex, AzureHttpError) and expected_errors is not None and ex.error_code in expected_errors:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage directory create --account-name {} --account-key {} --share-name {} --name {}`

## Expected Behavior
Create fileshare storage directory

## Environment Summary
```
Linux-4.14.177-139.254.amzn2.x86_64-x86_64-with-glibc2.2.5
Python 3.7.6
Installer: RPM

azure-cli 2.10.0 *

```

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
Hi @cmrkz, could you share your debug info with `--debug` in your command?

**Comment by yonzhan** [comment]
Hi @cmrkz, any feedback?

**Comment by cmrkz** [comment]
Here's the debug output

Command arguments: ['storage', 'directory', 'create', '--account-name', '', '--account-key', '', '--share-name', '', '--name', '', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fc8f037a710>, <function OutputProducer.on_global_arguments at 0x7fc8ef7523b0>, <function CLIQuery.on_global_arguments at 0x7fc8efc033b0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'storage': ['azure.cli.command_modules.storage']
Loading command modules:
Name                  Load Time    Groups  Commands
storage                   0.075        52       238
Total (1)                 0.075        52       238
Loaded 52 groups, 238 commands.
Found a match in the command table.
Raw command  : storage directory create
Command table: storage directory create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fc8ebec0440>]
az_command_data_logger : command args: storage directory create --account-name {} --account-key {} --share-name {} --name {} --debug
metadata file logging enabled - writing logs to '/home/e489yh/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fc8eb1c1b90>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fc8ead407a0>]
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 479, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 36, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 570, in load_arguments
    "Options include: {}. Can be combined.".format(get_include_help_string(t_blob_include)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 589, in get_include_help_string
    for include in include_list:
TypeError: 'NoneType' object is not iterable

cli.azure.cli.core.azclierror : CLIInternalError: The command failed with an unexpected error. Here is the traceback:
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror : 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 479, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 36, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 570, in load_arguments
    "Options include: {}. Can be combined.".format(get_include_help_string(t_blob_include)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 589, in get_include_help_string
    for include in include_list:
TypeError: 'NoneType' object is not iterable
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 479, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 36, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 570, in load_arguments
    "Options include: {}. Can be combined.".format(get_include_help_string(t_blob_include)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 589, in get_include_help_string
    for include in include_list:
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fc8ebecc3b0>]
az_command_data_logger : exit code: 1
Command ran in 1.507 seconds (init: 0.306, invoke: 1.200)
telemetry.save : Save telemetry record of length 9106 in cache
telemetry.check : Negative: The /home/username/.azure/telemetry.txt was modified at 2020-10-29 16:09:23.968902, which in less than 600.000000 s

**Comment by Juliehzl** [comment]
Hi @cmrkz, thanks a lot for your information.
As debug log, it is caused be None type for include_list. But in our code, we already make sure it is not None as below:
https://github.com/Azure/azure-cli/blob/fbb99ba30690e3bac7df563ba6bf7d5a80e453d1/src/azure-cli/azure/cli/command_modules/storage/_validators.py#L585-L589

I have tried the command with version 2.10.0 and there is no error occurred. 
```
zuh@HUILI-DESKTOP  ~                                                                            [15:25]
❯ az storage directory create -n dirsc -s test --account-name xxxx --account-key xxxxx
{
  "created": true
}
zuh@HUILI-DESKTOP  ~                                                                            [15:32]
❯ az --version
azure-cli                         2.10.0 *
```
If possible, could you upgrade to latest version and try again.

**Comment by Juliehzl** [comment]
if error still occurs, could you show me your package version for `azure-multiapi-storage`?
