### ISSUE TITLE
Sudo required to run az

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#15638]
**Describe the bug**

`az` throws this:

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/home/jon/.azure/commandIndex.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 509, in execute
    self.commands_loader.load_command_table(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in load_command_table
    command_index.update(self.command_table)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 556, in update
    self.INDEX[self._COMMAND_INDEX_VERSION] = __version__
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/home/jon/.azure/commandIndex.json'
```

**To Reproduce**

Install az on wsl2 ubuntu 20/focal using one line install script

run `az`

It works if I run `sudo az`

**Expected behavior**

Sudo not required to run az

Was working that way before. Not sure what changed.

**Environment summary**

one liner install.

**Additional context**

**Comment by jiasli** [comment]
Could you run

```
stat /home/jon/.azure/commandIndex.json
```

It looks like you somehow lost permission to this file.

**Comment by jongio** [comment]
I ran `sudo rm /home/jon/.azure/commandIndex.json` and then re-ran `az` and it works.

Thank you.

**Comment by jiasli** [comment]
It looks like you ran `az` before with `sudo` which will create/update `~/.azure/commandIndex.json` with `Uid: (    0/    root)`.

I am able to repro with

```sh
$ sudo rm ~/.azure/commandIndex.json

$ sudo az

$ stat ~/.azure/commandIndex.json
  File: .azure/commandIndex.json
  Size: 4961            Blocks: 32         IO Block: 4096   regular file
Device: 2h/2d   Inode: 28710447624542741  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-10-23 16:03:50.096954200 +0800
Modify: 2020-10-23 16:03:50.903954200 +0800
Change: 2020-10-23 16:03:50.903954200 +0800
 Birth: -

$ az
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/home/user2/.azure/commandIndex.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 509, in execute
    self.commands_loader.load_command_table(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in load_command_table
    command_index.update(self.command_table)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 556, in update
    self.INDEX[self._COMMAND_INDEX_VERSION] = __version__
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/home/user2/.azure/commandIndex.json'
To open an issue, please run: 'az feedback'
```

To get unblocked, run

```sh
$ sudo rm ~/.azure/commandIndex.json

$ az
```

**Comment by uthsab** [comment]
@jiasli I am facing  the same issue. I installed az using the official document steps - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command

I need to delete /home/azureuser/.azure to be able to use az without sudo after the installation. Is this the expected behavior? 
This steps appears to be a mitigation / workaround, is the resolution for this issue planned?

**Comment by jiasli** [comment]
@uthsab, 

> This steps appears to be a mitigation / workaround, is the resolution for this issue planned?

This is not an Azure CLI bug.

You only need to use `sudo` for this command:

```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

However, please don't 

- run `sudo -i` or `sudo -s` before `az login`
- run `sudo az login`
