### ISSUE TITLE
ImportError: cannot import name 'on_windows' on typing "az"

### ISSUE THREAD

**Issue by christianfelixmerz** [Azure/azure-cli#15659]
**Describe the bug**
On typing az and hitting enter, following error comes up:

Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\__main__.py", line 9, in <module>
    import azure.cli.main
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\main.py", line 10, in <module>
    from azure.cli.core.application import APPLICATION, Configuration
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 18, in <module>
    import azure.cli.core.commands.progress as progress
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\progress.py", line 9, in <module>
    import humanfriendly
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\humanfriendly\__init__.py", line 24, in <module>
    from humanfriendly.tables import format_pretty_table as format_table  # NOQA
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\humanfriendly\tables.py", line 32, in <module>
    from humanfriendly.terminal import (
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-oxvacpiw\humanfriendly\terminal\__init__.py", line 45, in <module>

**Environment summary**
Windows10
Testet on Newest Powershell and Developer Command Prompt

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to have a look? thanks

**Comment by fengzhou-msft** [comment]
@christianfelixmerz how did you install azure cli? Do you know which version you installed?

**Comment by christianfelixmerz** [comment]
@fengzhou-msft I installed the latest .msi package. Tested with 2.13 and 2.14

**Comment by fengzhou-msft** [comment]
@christianfelixmerz there may be some very old CLI version installed before based on the error trace(we no longer have files like `cli_main.py` and the file format for CLI code became `pyc` in msi since at least over one year ago). Please clean up the `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` directory and reinstall the latest CLI version.

**Comment by christianfelixmerz** [comment]
@fengzhou-msft that fixed the issue and az command works now, thanks for the hint
