### ISSUE TITLE
az servicebus namespace authorization-rule keys list produces python traceback if the name is not found

### ISSUE THREAD

**Issue by snapfisher** [Azure/azure-cli#15653]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Using the command "az servicebus namespace authorization-rule keys list" if the name specified is not found, the CLI incorrectly produces python traceback lines.  It should just say that the name is not found.

**To Reproduce**
az servicebus namespace authorization-rule keys list --name {incorrect-name)--namespace-name {correct-value} --resource-group {correct value)

**Expected behavior**
no output should be produced, or a message saying that the name is not found.  No python tracebacks should appear.

**Environment summary**
Windows MSI, version 2.5.1

**Additional context**
The output looks like this:

**Comment by snapfisher** [comment]
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\six\six.py", line 703, in reraise
    raise value
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 665, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\commands\__init__.py", line 324, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 574, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-mgmt-servicebus\azure\mgmt\servicebus\operations\namespaces_operations.py", line 870, in list_keys
azure.mgmt.servicebus.models._models.ErrorResponseException: Operation returned an invalid status code 'Not Found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\__main__.py", line 41, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli\azure\cli\__main__.py", line 30, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 226, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 151, in exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\util.py", line 82, in handle_exception
TypeError: string indices must be integers

**Comment by snapfisher** [comment]
I have no idea why those line are struct through.  Some sort of github goofiness

**Comment by yonzhan** [comment]
servicebus

**Comment by yungezz** [comment]
cc @houk-ms @chenlomis , user would like to see errors directly instead of tracestack.

**Comment by v-Ajnava** [comment]
fixed, please use latest release
