### ISSUE TITLE
Webapp:az webapp config ssl upload - cannot read from /tmp directory in WSL2

### ISSUE THREAD

**Issue by mpowrie** [Azure/azure-cli#15672]
I have Ubuntu 20.04 running on WSL2.

I get a FileNotFoundError when trying to upload a file from /tmp/, despite the file being there.
Command used:

$ az webapp config ssl upload --certificate-file /tmp/my.file.pfx --certificate-password mypasswprd -g myresourcegroup --name myapp
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/tmp/my.file.pfx'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-lhx4371t\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7avbl0u7\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-w2r544p3\azure\cli\command_modules\appservice\custom.py", line 2316, in upload_ssl_cert
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/my.file.pfx'
To open an issue, please run: 'az feedback'

(a test of  $ stat /tmp/my.file.pfx lists the file statistics).

Version of az cli: 2.13..0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az_webapp_config_ssl_upload)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by mpowrie** [comment]
Thanks! I've since noticed that I have the Azure CLI installed in both WSL2 and Windows, and typing "az" from WSL2 actually runs the Windows Azure CLI instance, so it can't see any Linux directories.

**Comment by panchagnula** [comment]
@mpowrie is this resolved now - there was a known issue with the Ubuntu CLI package - can you try the latest version of CLI & let us know if you are still seeing this? Thanks!

**Comment by panchagnula** [comment]
Closing due to lack of response. Please open new issue if this still persists with the latest version of CLI. Thanks!
