### ISSUE TITLE
Az Storage Blob Copy Start does not support SASConnectionString whereas other az storage blob commands do.

### ISSUE THREAD

**Issue by krishnagupta21** [Azure/azure-cli#15722]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I generated a SASConnectionString that looks like this:
```
$ConnectionString = '"BlobEndpoint=https://<accountName>.blob.core.windows.net/;QueueEndpoint=https://<accountName>.queue.core.windows.net/;FileEndpoint=https://<accountName>.file.core.windows.net/;TableEndpoint=https://<accountName>.table.core.windows.net/;SharedAccessSignature=sv=<ss>&ss=<ss>&se=<se>&spr=https&sig=<sig>"'
```

I am trying to authenticate the copy command as follows:
```
az storage blob copy start  `
--account-name <accountName> `
--source-container <source> `
--source-blob <blob-name> `
 --destination-blob <dest-blob-name> `
--destination-container <container>`
 --connection-string $ConnectionString
```

However, this returns the following error:
```
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:1c2d9191-f01e-0021-3b0f-ae6f7c000000
Time:2020-10-29T16:22:40.5248427Z</Message></Error>
```

When I try to use the same connection string for the following command, it works.
```
az storage blob download-batch `
-d <destination-folder> `
-s <source-folder> `
--connection-string $ConnectionString
```

**To Reproduce**

Try running both the commands with same SASConnectionString and the copy command will fail whereas the download-batch will work.

**Expected behavior**

The az storage blob copy start should work just like the az storage blob download-batch command and should be able to use the SAS ConnectionString

**Environment summary**

az version

{
  "azure-cli": "2.14.0",
  "azure-cli-core": "2.14.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "storage-preview": "0.4.0"
  }
}

**Additional context**

Note that the az storage copy command works with the Access Key Connection String. However, I specifically want to use the Connection String that contains the SAS token.

**Comment by yonzhan** [comment]
Storage

**Comment by Juliehzl** [comment]
Hi @krishnagupta21, `--connection-string` is used for destination storage account for `blob copy start` command.  It can be used to source only when the source storage account and destination storage account is the same one. To authenticate source blob in another storage account, you have to use `--source-account-key` or `--source-sas` with `--source-account-name`.

**Comment by krishnagupta21** [comment]
@Juliehzl I am using the same source and destination storage account.
Since its the same account I'm able to use just the  `--sas-token` for authentication. I'm also able to use
`--connection-string '"DefaultEndpointsProtocol=https;AccountName=<accountName>;AccountKey=<accessKey>EndpointSuffix=core.windows.net"'`

Thats why I think that the connection string with sas token should also be supported in this case.

**Comment by Juliehzl** [comment]
could you provide more info with`--debug` in your command? I cannot reproduce the issue now. I could copy with connection string for same account as below:
```
az storage blob copy start --destination-blob test.txt --destination-container test \
--source-blob a.txt --source-container test4 --account-name zuhdefault  \
--connection-string $connectionString
```

**Comment by krishnagupta21** [comment]
```
Command arguments: ['storage', 'blob', 'copy', 'start', '--account-name', 'testst', '--source-container', 'models', '--source-blob', 'project/test.bin', '--destination-blob', 'project_training_data/dest-test.bin', '--destination-container', 'azureml-blobstore-128a7bfb-fadb-42f1-9ecc-b8bc7b7b2244', '--connection-string', 'BlobEndpoint=https://testst.blob.core.windows.net/;QueueEndpoint=https://testst.queue.core.windows.net/;FileEndpoint=https://testst.file.core.windows.net/;TableEndpoint=https://testst.table.core.windows.net/;SharedAccessSignature=<sas>', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0319BA50>, <function OutputProducer.on_global_arguments at 0x0332AED0>, <function CLIQuery.on_global_arguments at 0x0334FED0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'storage': ['azure.cli.command_modules.storage', 'azext_storage_preview']
Loading command modules:
Name                  Load Time    Groups  Commands
storage                   0.204        52       238
Total (1)                 0.204        52       238
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Event: CommandLoader.OnLoadCommandTable []
storage-preview           0.089         9        25  C:\Users\u6070455\.azure\cliextensions\storage-preview
Total (1)                 0.089         9        25
Loaded 58 groups, 260 commands.
Found a match in the command table.
Raw command  : storage blob copy start
Command table: storage blob copy start
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x035E1DB0>]
az_command_data_logger : command args: storage blob copy start --account-name {} --source-container {} --source-blob {} --destination-blob {} --destination-container {} --connection-string {} --debug
metadata file logging enabled - writing logs to 'C:\Users\u6070455\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0363D858>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x0363DE88>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0363DED0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0363DF60>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0332AF18>, <function CLIQuery.handle_query_parameter at 0x0334FF18>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x0363DE40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0363DF18>]
Getting data service client service_type=BlockBlobService
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=24930fc0-1d2f-11eb-af9a-4c1d9639097b Outgoing request: Method=PUT, Path=/azureml-blobstore-128a7bfb-fadb-42f1-9ecc-b8bc7b7b2244/project_training_data/dest-test.bin, Query={'timeout': None, 'sv': '2019-12-12', 'ss': 'bfqt', 'srt': 'sco', 'sp': 'rwdlacupx', 'se': '2020-11-03T01:10:07Z', 'st': '2020-11-02T17:10:07Z', 'spr': 'https', 'sig': 'REDACTED'}, Headers={'x-ms-copy-source': 'https://None.blob.core.windows.net/models/project/test.bin?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2020-11-03T01%3A10%3A07Z&st=2020-11-02T17%3A10%3A07Z&spr=https&sig=REDACTED', 'x-ms-source-if-modified-since': None, 'x-ms-source-if-unmodified-since': None, 'x-ms-source-if-match': None, 'x-ms-source-if-none-match': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-lease-id': None, 'x-ms-source-lease-id': None, 'x-ms-access-tier': None, 'x-ms-requires-sync': None, 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.8; Windows 10) AZURECLI/2.14.0 (MSI)', 'x-ms-client-request-id': '21508ef6-1d2f-11eb-8ec1-4c1d9639097b', 'x-ms-date': 'Mon, 02 Nov 2020 17:16:27 GMT'}.
urllib3.connectionpool : Starting new HTTPS connection (1): testst.blob.core.windows.net:443
urllib3.connectionpool : https://testst.blob.core.windows.net:443 "PUT /azureml-blobstore-128a7bfb-fadb-42f1-9ecc-b8bc7b7b2244/project_training_data/dest-test.bin?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2020-11-03T01%3A10%3A07Z&st=2020-11-02T17%3A10%3A07Z&spr=https&sig=plz016tN155u5NeWCC9X53cY2UjAoZfmnolyS44mcEw%3D HTTP/1.1" 403 322
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=24930fc0-1d2f-11eb-af9a-4c1d9639097b Receiving Response: Server-Timestamp=Mon, 02 Nov 2020 17:16:29 GMT, Server-Request-ID=c3533efb-a01e-006f-223b-b1ea0d000000, HTTP Status Code=403, Message=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Headers={'content-length': '322', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': 'c3533efb-a01e-006f-223b-b1ea0d000000', 'x-ms-version': '2018-11-09', 'x-ms-error-code': 'CannotVerifyCopySource', 'date': 'Mon, 02 Nov 2020 17:16:29 GMT'}.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=24930fc0-1d2f-11eb-af9a-4c1d9639097b Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Mon, 02 Nov 2020 17:16:29 GMT, Server-Request-ID=c3533efb-a01e-006f-223b-b1ea0d000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:c3533efb-a01e-006f-223b-b1ea0d000000Time:2020-11-02T17:16:30.4882390Z</Message></Error>.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=24930fc0-1d2f-11eb-af9a-4c1d9639097b Retry policy did not allow for a retry: Server-Timestamp=Mon, 02 Nov 2020 17:16:29 GMT, Server-Request-ID=c3533efb-a01e-006f-223b-b1ea0d000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:c3533efb-a01e-006f-223b-b1ea0d000000Time:2020-11-02T17:16:30.4882390Z</Message></Error>.
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-49qlvzn7\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-q3fk5_cg\azure\cli\command_modules\storage\__init__.py", line 341, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\blob\blockblobservice.py", line 1018, in copy_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\blob\baseblobservice.py", line 3261, in _copy_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 430, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 358, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 344, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ponmp39n\azure\multiapi\storage\v2018_11_09\common\_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c3533efb-a01e-006f-223b-b1ea0d000000
Time:2020-11-02T17:16:30.4882390Z</Message></Error>

cli.azure.cli.core.azclierror : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c3533efb-a01e-006f-223b-b1ea0d000000
Time:2020-11-02T17:16:30.4882390Z</Message></Error>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c3533efb-a01e-006f-223b-b1ea0d000000
Time:2020-11-02T17:16:30.4882390Z</Message></Error>
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x035E1ED0>]
az_command_data_logger : exit code: 1
Command ran in 9.795 seconds (init: 1.089, invoke: 8.706)
telemetry.save : Save telemetry record of length 3536 in cache
```
