### ISSUE TITLE
Azure synapse Cli: ImportError: cannot import name 'RoleAssignmentOptions'

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-cli#15863]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running `az synapse role assignment list --workspace-name 'workspacename'` in my ubuntu wsl and getting the below error 

>>>Command arguments: ['synapse', 'role', 'assignment', 'list', '--workspace-name', 'usedctoardwsa0k', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f4960a1fd90>, <function OutputProducer.on_global_arguments at 0x7f4960a87d90>, <function CLIQuery.on_global_arguments at 0x7f49609e80d0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'synapse': ['azext_synapse', 'azure.cli.command_modules.synapse']
Loading command modules:
Name                  Load Time    Groups  Commands
synapse                   0.039        22        89
Total (1)                 0.039        22        89
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
synapse                   0.034        10        39  /home/jayendran/.azure/cliextensions/synapse
Total (1)                 0.034        10        39  
Loaded 22 groups, 89 commands.
Found a match in the command table.
Raw command  : synapse role assignment list
Command table: synapse role assignment list
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f49607aeae8>]
az_command_data_logger : command args: synapse role assignment list --workspace-name {} --debug
metadata file logging enabled - writing logs to '/home/jayendran/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f4960763b70>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f49606e3ae8>]
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 787, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 827, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/operations/accesscontrol.py", line 7, in <module>
    from azure.synapse.accesscontrol.models import RoleAssignmentOptions
ImportError: cannot import name 'RoleAssignmentOptions'

>>>cli.azure.cli.core.azclierror : CLIInternalError: The command failed with an unexpected error. Here is the traceback:
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror : cannot import name 'RoleAssignmentOptions'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 787, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 827, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/operations/accesscontrol.py", line 7, in <module>
    from azure.synapse.accesscontrol.models import RoleAssignmentOptions
ImportError: cannot import name 'RoleAssignmentOptions'
cannot import name 'RoleAssignmentOptions'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 787, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 827, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/operations/accesscontrol.py", line 7, in <module>
    from azure.synapse.accesscontrol.models import RoleAssignmentOptions
ImportError: cannot import name 'RoleAssignmentOptions'
To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f49607aed08>]
az_command_data_logger : exit code: 1
Command ran in 6.629 seconds (init: 0.995, invoke: 5.634)
Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

>>> During handling of the above exception, another exception occurred:

>>> Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 482, in _get_session_id
    process = psutil.Process()
>>> AttributeError: module 'psutil' has no attribute 'Process'

>>> telemetry.save : Save telemetry record of length 11874 in cache
>>>telemetry.check : Negative: The /home/jayendran/.azure/telemetry.txt was modified at 2020-11-10 21:03:34.412215, which >>> in less than 600.000000 s

**To Reproduce**

**Expected behavior**

**Environment summary**

Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.14.2

Extensions:
synapse 0.3.0

**Additional context**

**Comment by yonzhan** [comment]
synapse

**Comment by jayendranarumugam** [comment]
The installation was went wrong. Once I reinstalled the azure cli correctly all working fine now. So closing this issue
