### ISSUE TITLE
run-command invoke - returns host Python errors

### ISSUE THREAD

**Issue by sedatesoftware** [Azure/azure-cli#15878]
## Describe the bug

**Command Name**
`az vm run-command invoke`

**Errors:**
```
'VirtualMachinesOperations' object has no attribute 'run_command'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/vm/custom.py, ln 1984, in vm_run_command_invoke
    return run_command_invoke(cmd, resource_group_name, vm_name, command_id, scripts, parameters)
cli/command_modules/vm/custom.py, ln 1978, in run_command_invoke
    return client.virtual_machines.run_command(resource_group_name, vm_vmss_name,
AttributeError: 'VirtualMachinesOperations' object has no attribute 'run_command'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az account set -s <subscription id>`
- `az vm run-command invoke -g {} -n {} --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world`

The issue occurred against multiple Linux targets.  The script from the documentation example has the same error.
## Expected Behavior
Script should return exit code zero and echo text.

## Environment Summary
```
Latest patches applied in WSL instances.
Instance 1:
Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.6
Installer: PIP
azure-cli 2.14.1 *
azure-cli 2.14.2 *

Instance 2:
Linux-4.19.128-microsoft-standard-x86_64-with-fedora-31-Generic
Python 3.7.9
Installer: RPM
azure-cli 2.14.2

Extensions:
azure-devops 0.18.0

```
## Additional Context
This issue has only started occurring in the last few days.

**Comment by yungezz** [comment]
hi @qwordy could you pls help to look at the issue? thanks

**Comment by qwordy** [comment]
I downloaded 2.14.2 and ran the command. I got
```
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n",
      "time": null
    }
  ]
}
```
Can you add `--debug` and append logs here?

**Comment by sedatesoftware** [comment]
@qwordy run again with ```--debug``` parameter as requested.
On a Debian based WSL instance (az --version = 2.14.1):
```Command arguments: ['vm', 'run-command', 'invoke', '-g', '<group name>', '-n', '<vm name>', '--command-id', 'RunShellScript', '--scripts', 'echo $1 $2', '--parameters', 'hello', 'world', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fd91001a940>, <function OutputProducer.on_global_arguments at 0x7fd90ff44670>, <function CLIQuery.on_global_arguments at 0x7fd90feebc10>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'vm': ['azure.cli.command_modules.vm']
Loading command modules:
Name                  Load Time    Groups  Commands
vm                        0.206        43       219
Total (1)                 0.206        43       219
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0
Loaded 43 groups, 219 commands.
Found a match in the command table.
Raw command  : vm run-command invoke
Command table: vm run-command invoke
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fd90f761280>]
az_command_data_logger : command args: vm run-command invoke -g {} -n {} --command-id {} --scripts {} --parameters {} {} --debug
metadata file logging enabled - writing logs to '/home/user/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fd90f78a790>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fd90f6dea60>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fd90f6deaf0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fd90f6dec10>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fd90ff44700>, <function CLIQuery.handle_query_parameter at 0x7fd90feebca0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fd90f6de160>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fd90f6deb80>]
Getting management service client client_type=ComputeManagementClient
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1984, in vm_run_command_invoke
    return run_command_invoke(cmd, resource_group_name, vm_name, command_id, scripts, parameters)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1978, in run_command_invoke
    return client.virtual_machines.run_command(resource_group_name, vm_vmss_name,
AttributeError: 'VirtualMachinesOperations' object has no attribute 'run_command'

cli.azure.cli.core.azclierror : CLIInternalError: The command failed with an unexpected error. Here is the traceback:
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror : 'VirtualMachinesOperations' object has no attribute 'run_command'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1984, in vm_run_command_invoke
    return run_command_invoke(cmd, resource_group_name, vm_name, command_id, scripts, parameters)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1978, in run_command_invoke
    return client.virtual_machines.run_command(resource_group_name, vm_vmss_name,
AttributeError: 'VirtualMachinesOperations' object has no attribute 'run_command'
'VirtualMachinesOperations' object has no attribute 'run_command'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1984, in vm_run_command_invoke
    return run_command_invoke(cmd, resource_group_name, vm_name, command_id, scripts, parameters)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1978, in run_command_invoke
    return client.virtual_machines.run_command(resource_group_name, vm_vmss_name,
AttributeError: 'VirtualMachinesOperations' object has no attribute 'run_command'
To open an issue, please run: 'az feedback'
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fd90f7614c0>]
az_command_data_logger : exit code: 1
Command ran in 0.660 seconds (init: 0.082, invoke: 0.578)
telemetry.save : Save telemetry record of length 10638 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/bin/python3 /usr/lib/python3/dist-packages/azure/cli/telemetry/__init__.py /home/user/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
```

On the Fedora based WSL instance (az --version = 2.14.2) it worked:
```
Command arguments: ['vm', 'run-command', 'invoke', '-g', '<name>', '-n', '<name>', '--command-id', 'RunShellScript', '--scripts', 'echo $1 $2', '--parameters', 'hello', 'world', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f19e7e897a0>, <function OutputProducer.on_global_arguments at 0x7f19e7b9a4d0>, <function CLIQuery.on_global_arguments at 0x7f19e7c7e4d0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'vm': ['azure.cli.command_modules.vm']
Loading command modules:
Name                  Load Time    Groups  Commands
vm                        0.697        43       219
Total (1)                 0.697        43       219
Loaded 43 groups, 219 commands.
Found a match in the command table.
Raw command  : vm run-command invoke
Command table: vm run-command invoke
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f19e74e64d0>]
az_command_data_logger : command args: vm run-command invoke -g {} -n {} --command-id {} --scripts {} --parameters {} {} --debug
metadata file logging enabled - writing logs to '/home/user/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f19e72eddd0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f19e70eb050>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f19e70eb0e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f19e70eb200>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f19e7b9a560>, <function CLIQuery.handle_query_parameter at 0x7f19e7c7e5f0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f19e70e2f80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f19e70eb170>]
Getting management service client client_type=ComputeManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
attempting to read file /home/user/.azure/accessTokens.json as utf-8-sig
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - Authority:Performing instance discovery: ...
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - Authority:Performing static instance discovery
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - Authority:Authority validated via static instance discovery
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - CacheDriver:Found 2 potential entries.
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - CacheDriver:Resource specific token found.
adal-python : 53fffd89-efce-4f4b-a875-ad6a633ec935 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'uTXW99VJipA3GF+EKbJPV5U72dS/4Wrfan/f3B81ERw=', RefreshTokenId: b'I2fCPJeGP8cve1wGHSyRl3GUGxnOBHNRNGgfRJkvM+G='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/<Subscription ID>/resourceGroups/<group name>/providers/Microsoft.Compute/virtualMachines/<vm name>/runCommand?api-version=2020-06-01'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '145'
msrest.http_logger :     'User-Agent': 'python/3.7.9 (Linux-4.19.128-microsoft-standard-x86_64-with-fedora-31-Generic) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-compute/14.0.0 Azure-SDK-For-Python AZURECLI/2.14.2 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : {"commandId": "RunShellScript", "script": ["echo $1 $2"], "parameters": [{"name": "arg1", "value": "hello"}, {"name": "arg2", "value": "world"}]}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "POST /subscriptions/<subscription id>/resourceGroups/<name>/providers/Microsoft.Compute/virtualMachines/<name>/runCommand?api-version=2020-06-01 HTTP/1.1" 202 0
msrest.http_logger : Response status: 202
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Location': 'https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?monitor=true&api-version=2020-06-01'
msrest.http_logger :     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?api-version=2020-06-01'
msrest.http_logger :     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/UpdateVM3Min;239,Microsoft.Compute/UpdateVM30Min;1199'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-request-id': '46db63ba-0580-4d4a-9a03-c802dac0d76f'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-correlation-request-id': '2c3727b5-2540-4554-9c32-ad76e73c6bc1'
msrest.http_logger :     'x-ms-routing-request-id': 'AUSTRALIAEAST:20201117T024145Z:2c3727b5-2540-4554-9c32-ad76e73c6bc1'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 17 Nov 2020 02:41:44 GMT'
msrest.http_logger :     'Content-Length': '0'
msrest.http_logger : Response content:
msrest.http_logger :
msrest.service_client : Accept header absent and forced to application/json
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - Authority:Performing instance discovery: ...
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - Authority:Performing static instance discovery
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - Authority:Authority validated via static instance discovery
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - CacheDriver:Found 2 potential entries.
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - CacheDriver:Resource specific token found.
adal-python : 46bee043-8d4d-4d39-b1ef-51848075d09e - CacheDriver:Returning token from cache lookup, AccessTokenId: b'uTXW99VJipA3GF+EKbJPV5U72dS/4Wrfan/f3B81ERw=', RefreshTokenId: b'I2fCPJeGP8cve1wGHSyRl3GUGxnOBHNRNGgfRJkvM+G='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?api-version=2020-06-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'x-ms-client-request-id': '6caa4100-287e-11eb-870a-00155d5af5af'
msrest.http_logger :     'User-Agent': 'python/3.7.9 (Linux-4.19.128-microsoft-standard-x86_64-with-fedora-31-Generic) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-compute/14.0.0 Azure-SDK-For-Python AZURECLI/2.14.2 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?api-version=2020-06-01 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperation3Min;14997,Microsoft.Compute/GetOperation30Min;29992'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-request-id': '6a270391-8458-4926-8cd9-83bca4a25417'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '11955'
msrest.http_logger :     'x-ms-correlation-request-id': 'bd845722-7951-43a6-8dd2-a95b2108ca7c'
msrest.http_logger :     'x-ms-routing-request-id': 'AUSTRALIAEAST:20201117T024215Z:bd845722-7951-43a6-8dd2-a95b2108ca7c'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 17 Nov 2020 02:42:15 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {
  "startTime": "2020-11-17T02:41:45.1782106+00:00",
  "endTime": "2020-11-17T02:42:10.3673282+00:00",
  "status": "Succeeded",
  "properties": {
    "output": {
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "level": "Info",
      "displayStatus": "Provisioning succeeded",
      "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n"
    }
  ]
}
  },
  "name": "46db63ba-0580-4d4a-9a03-c802dac0d76f"
}
msrest.service_client : Accept header absent and forced to application/json
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - Authority:Performing instance discovery: ...
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - Authority:Performing static instance discovery
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - Authority:Authority validated via static instance discovery
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - CacheDriver:Found 2 potential entries.
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - CacheDriver:Resource specific token found.
adal-python : edf1d766-00d0-4dc0-b88f-8f87612eb60c - CacheDriver:Returning token from cache lookup, AccessTokenId: b'uTXW99VJipA3GF+EKbJPV5U72dS/4Wrfan/f3B81ERw=', RefreshTokenId: b'I2fCPJeGP8cve1wGHSyRl3GUGxnOBHNRNGgfRJkvM+G='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?monitor=true&api-version=2020-06-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'x-ms-client-request-id': '6caa4100-287e-11eb-870a-00155d5af5af'
msrest.http_logger :     'User-Agent': 'python/3.7.9 (Linux-4.19.128-microsoft-standard-x86_64-with-fedora-31-Generic) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-compute/14.0.0 Azure-SDK-For-Python AZURECLI/2.14.2 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/<subscription id>/providers/Microsoft.Compute/locations/australiaeast/operations/46db63ba-0580-4d4a-9a03-c802dac0d76f?monitor=true&api-version=2020-06-01 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperation3Min;14996,Microsoft.Compute/GetOperation30Min;29991'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-request-id': '46751e25-66f2-44d4-911c-1fc9fa392730'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '11954'
msrest.http_logger :     'x-ms-correlation-request-id': 'd53cb4c8-1ec7-4d83-b394-6cfe403f9c13'
msrest.http_logger :     'x-ms-routing-request-id': 'AUSTRALIAEAST:20201117T024215Z:d53cb4c8-1ec7-4d83-b394-6cfe403f9c13'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 17 Nov 2020 02:42:15 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"value":[{"code":"ProvisioningState/succeeded","level":"Info","displayStatus":"Provisioning succeeded","message":"Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n"}]}
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f19e70c9b00>, <function _x509_from_base64_to_hex_transform at 0x7f19e70c9b90>]
Event: CommandInvoker.OnFilterResult []
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n",
      "time": null
    }
  ]
}
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f19e74f1680>]
az_command_data_logger : exit code: 0
Command ran in 34.397 seconds (init: 0.296, invoke: 34.101)
telemetry.save : Save telemetry record of length 2925 in cache
telemetry.check : Negative: The /home/user/.azure/telemetry.txt was modified at 2020-11-17 13:35:15.989733, which in less than 600.000000 s
```

Upgrading az-cli on the Debian instance failed.
```ERROR: azure-cli-core 2.14.2 has requirement azure-mgmt-core==1.2.0, but you'll have azure-mgmt-core 1.2.2 which is incompatible.
ERROR: azure-cli-core 2.14.2 has requirement msrestazure>=0.6.3, but you'll have msrestazure 0.6.2 which is incompatible.
```

**Comment by qwordy** [comment]
I run it in Windows. Let me try it on Debian WSL as well.

**Comment by qwordy** [comment]
I run it in WSL Ubuntu 20.04 LTS. No error. I think the problem is that the dependency is not installed correctly. azure-mgmt-compute==18.1.0.
```
az vm run-command invoke -g fy -n vm1 --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world
{- Finished ..
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n",
      "time": null
    }
  ]
}
```
