### ISSUE TITLE
HTTP Error 403: rate limit exceeded - az aks install cli

### ISSUE THREAD

**Issue by bkozub** [Azure/azure-cli#15932]
**Describe the bug**
Sometimes when using bitbucket pipelines from ```mcr.microsoft.com/azure-cli:latest``` image i get the 403 Error while 
```az aks install cli``` command is executed 

**To Reproduce**

occurs randomly

**Expected behavior**
aks cli is installed

**Environment summary**

**Additional context**
```+ az aks install-cli
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.19.4/bin/linux/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
HTTP Error 403: rate limit exceeded
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 329, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version, kubelogin_install_location)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 407, in k8s_install_kubelogin
    latest_release = urlopen(latest_release_url, context=context).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded```

**Comment by yonzhan** [comment]
aks

**Comment by waldekmanual** [comment]
any new about this?

**Comment by henrykironde** [comment]
I am getting the same error https://github.com/weecology/DeepForest-pytorch/pull/41/checks?check_run_id=2179945044

**Comment by kemmemha** [comment]
Is there any update on this issue? We are also encountering this issue pretty regularely. It appears in CI / CD after 50 installations "az aks install-cli".
We use `--base-src-url` and `-l` over an Artifactory server with the hope to prevent this from happening but we same error occurs.

**Comment by phenixita** [comment]
Hi team, any news on this?
I'm working with a customer and we're facing the same issue.

**Comment by phenixita** [comment]
I suppose the limitation is the rate limit on Google servers, from where the cli downloads the tools. [Source code](https://github.com/Azure/azure-cli/blob/c997395f476e7ab3700ec29fea470b72160c91cb/src/azure-cli/azure/cli/command_modules/acs/custom.py#L350)

**Comment by Stateofminf** [comment]
8080

**Comment by stan-sz** [comment]
See also #19965

**Comment by timbodeit** [comment]
Suggested solution: Rather than increasing rate limits by IP, provide a second variant of the [azure-cli](https://mcr.microsoft.com/en-us/product/azure-cli/about) Docker container, that already comes with the aks cli preinstalled. That way, pipelines based on Microsoft's Docker images wouldn't need to manually install it manually on each run in the first place.

@bkozub Would that resolve the issue for you as well?

Rel: https://github.com/Azure/azure-cli/issues/19965#issuecomment-1688162845

**Comment by ekbaramundi** [comment]
This problem is now already 4 years old, and still no updates on this?
We are regulary facing this issue...

**Comment by ekbaramundi** [comment]
Any new updates on this case? We still encounter this issue!

**Comment by fjbejarano-nn** [comment]
> Is there any update on this issue? We are also encountering this issue pretty regularely. It appears in CI / CD after 50 installations "az aks install-cli". We use `--base-src-url` and `-l` over an Artifactory server with the hope to prevent this from happening but we same error occurs.
> 
> The issue seems to appear because kubelogin (even if used with -l parameter) is calling the Github API if it downloads the latest version:
> 
> https://github.com/Azure/azure-cli/blob/edb293b58607450c64b634935c094405c995c212/src/azure-cli/azure/cli/command_modules/acs/custom.py#L438
> 
> so there is still 1 call to the Github API which will (if used too many times) exceed the rate limit.

I have the same problem with recent installation. In hashicorp packer, when you installed pluging, this issue happened but they implemented a variable with a github token. You can now execute the installation with a parameter with that github token and the rate is incremented drasticaly and all plugins are installed but I don't know if we can use a param with a github token in the installation of az aks install-cli.

**Comment by mymichu** [comment]
We noticed the same behaviour/issue in our build infrastructure where we build docker images. Is there any update on this issue?

**Comment by safronau** [comment]
Any update?

**Comment by levess007** [comment]
any update on this? the issue is still present

**Comment by bite-weldon** [comment]
I've got this issue too when I use `az aks install-cli` in my workflow 

![Image](https://github.com/user-attachments/assets/2a4115e5-00ad-4025-829c-4d05998a0014)

**Comment by ankur-kapoor-uk** [comment]
Any update on this issue. We do face same error very often. In last few weeks at least 3-4 times we have been blocked for few hours until the issue automatically resolves.

**Comment by junwen-shift** [comment]
Any update?

**Comment by FumingZhang** [comment]
kubelogin is hosted on GitHub. I think there is nothing special that can be done from the cli client perspective, as this is a limitation of GitHub itself.
 
> The primary rate limit for unauthenticated requests is 60 requests per hour.

https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users

**Comment by AbhinavKU** [comment]
From the product side, it should support accepting a parameter and logic in code (e.g., --gh-token) that allows users to provide a GitHub token, thereby increasing the API rate limit for authenticated requests.

#feature-request

**Comment by ankur-kapoor-uk** [comment]
Just for awareness, an easy fix is to avoid using the latest version and instead passing the cli version to be installed instead of asking for latest.

**Comment by uluzox** [comment]
> Just for awareness, an easy fix is to avoid using the latest version and instead passing the cli version to be installed instead of asking for latest.

Thanks, that worked:

```shell
az aks install-cli --kubelogin-version "${KUBELOGIN_VERSION}"
```

**Comment by mbifeld** [comment]
A `--gh-token parameter` was added in https://github.com/Azure/azure-cli/pull/32536 to resolve the rate limiting issues on downloading kubelogin. It will be available in the [January Az CLI 2.82 release](https://github.com/Azure/azure-cli/milestone/164). Thank you all for your patience on this long running issue!
