### ISSUE TITLE
WebApp:Creation of an ssl certificate for an App Service ('az webapp config ssl create') results in an 'UnkownError'

### ISSUE THREAD

**Issue by nbfr** [Azure/azure-cli#16041]
**Describe the bug**
The creation of an ssl certificate for an App Service via the command _az webapp config ssl create_ results in an _UnknownError_.

**To Reproduce**
Create a Resource Group, App Service Plan (Linux) and App Service.
Create a CNAME record and add a hostname to the app service:
`
az webapp config hostname add --resource-group {{resource-group-name}} --webapp-name {{app-service-name}} --hostname {{hostname}}
`

When trying to create an ssl certificate an error is returned:
`az webapp config ssl create --hostname {{hostname}} --name {{app-service-name}} --resource-group {{resource-group-name}}`

Result: 'UnknownError: Unknown error'

**Expected behavior**
There should be no error and an ssl certificate should be created in the App Service.

**Environment summary**
Install method: MSI
CLI Version: 2.15.1
OS Version: Windows 10
Shell: cmd.exe

**Comment by yonzhan** [comment]
webapp

**Comment by BastienPerdriau** [comment]
Hi,
I have the same error message here, but with a small difference : despite the error, the SSL certificate is indeed created (I can see it in the Portal after a few seconds).
A small difference here, I'm using a Windows ASP instead of a Linux one.

If it can help, here it is the stack trace from the --debug : 

```
msrest.exceptions : Unknown error
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2lthyver\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 717, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nxci6mib\azure\cli\command_modules\appservice\commands.py", line 37, in _ex_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nxci6mib\azure\cli\command_modules\appservice\custom.py", line 2456, in create_managed_ssl_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-la0x4ia1\azure\mgmt\web\v2019_08_01\operations\_certificates_operations.py", line 300, in create_or_update
azure.mgmt.web.v2019_08_01.models._models.DefaultErrorResponseException: Unknown error
```

**Comment by samsmithnz** [comment]
Same problem here too. Is this still on schedule for s179?
