### ISSUE TITLE
'az aks stop' gives No module named 'azure.cli.core.azclierror' error. tried re-installing azure cli but not helping

### ISSUE THREAD

**Issue by ameetkonnur** [Azure/azure-cli#16113]
## Describe the bug

**Command Name**
`az aks stop`

**Errors:**
```
No module named 'azure.cli.core.azclierror'
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 477, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py, ln 39, in load_arguments
    from ._params import load_arguments
.azure/cliextensions/aks-preview/azext_aks_preview/_params.py, ln 18, in <module>
    from ._validators import (
.azure/cliextensions/aks-preview/azext_aks_preview/_validators.py, ln 17, in <module>
    from azure.cli.core.azclierror import InvalidArgumentValueError
ModuleNotFoundError: No module named 'azure.cli.core.azclierror'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks stop -n {} -g {}`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.1 *

Extensions:
aks-preview 0.4.68

```

**Comment by yungezz** [comment]
hi @houk-ms could you pls help to have a look firstly? thanks

**Comment by houk-ms** [comment]
@ameetkonnur Thanks for reporting the issue.
The reason is new error types were used in AKS extensions, while the minCliCoreVersion was not changed accordingly. 
It will be fixed soon.

**Comment by ebele25** [comment]
Hi,
Are there any updates on this error "_**No module named 'azure.cli.core.azclierror**_"?

**Comment by fengzhou-msft** [comment]
Please upgrade to the latest version of `azure-cli`. You can run `az upgrade` if your current version >= 2.11.0.

**Comment by fengzhou-msft** [comment]
The fix for the `aks-preview` extension is released. Please upgrade the extension if you do not wish to upgrade your `azure-cli` version.

**Comment by houk-ms** [comment]
@ameetkonnur The issue should be resolved, just close the issue here. You can reopen it if there are still problems.

**Comment by ebele25** [comment]
thanks, I will upgrade and retry

**Comment by anjani40612000** [comment]
Hi I am also getting similar error for az login. Below is my Azure Cli version.

azure-cli                         2.19.1 *

core                              2.19.1 *
telemetry                          1.0.6

C:\Users>az login

The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.core.vendored_sdks.subscriptions.v2019_11_01.operations._subscription_client_operations'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\profile\custom.py", line 162, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 197, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 880, in find_through_authorization_code_flow
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 925, in _find_using_common_tenant
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\_subscription_client.py", line 160, in tenants
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\__init__.py", line 9, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\_subscription_client.py", line 21, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\operations\__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'azure.cli.core.vendored_sdks.subscriptions.v2019_11_01.operations._subscription_client_operations'
