### ISSUE TITLE
az acs kubernetes get-credentials needs appended 'mgmt' to DNS prefix

### ISSUE THREAD

**Issue by DonMartin76** [Azure/azure-cli#1618]
When using the command from [the Kubernetes tutorial](https://docs.microsoft.com/de-de/azure/container-service/container-service-kubernetes-walkthrough) to get credentials, it should be mentioned that the DNS prefix you specify when creating the container service and the one you need to specify when doing

`az acs kubernetes get-credentials --dns-prefix=<...>`

are not the same; it seems you must append `mgmt` to the latter. E.g., I create a Kubernetes Cluster with DNS prefix `mykube`, then I need to get the credentials using `--dns-prefix=mykubemgmt`, which is rather confusing.

**Important**: I created my Kubernetes cluster using the Portal directly, not via the `az` command line tooling (including creating my own Service Principal and such). This also means that my `acs` name was prefixed with `containerservice-<what I wrote>`.

The error message you get otherwise is just this (here on macOS Sierra):

```bash
[Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/azure/cli/main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 275, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/azure/cli/command_modules/acs/custom.py", line 477, in k8s_get_credentials
    '.kube/config', path_candidate)
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/azure/cli/command_modules/acs/acs_client.py", line 21, in SecureCopy
    ssh.connect(host, username=user, key_filename=os.path.join(home, '.ssh', 'id_rsa'))
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/paramiko/client.py", line 296, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/paramiko/client.py", line 200, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
gaierror: [Errno 8] nodename nor servname provided, or not known
```

I also tried the client in docker (which uses Python 3.5); there the error message looks like this:

```bash
[Errno -2] Name does not resolve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 142, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 275, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/acs/custom.py", line 511, in k8s_get_credentials
    '.kube/config', path_candidate)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/acs/acs_client.py", line 21, in SecureCopy
    ssh.connect(host, username=user, key_filename=os.path.join(home, '.ssh', 'id_rsa'))
  File "/usr/local/lib/python3.5/site-packages/paramiko/client.py", line 296, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/local/lib/python3.5/site-packages/paramiko/client.py", line 200, in _families_and_addresses
    addrinfos = socket.getaddrinfo(hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/local/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

So either this is a documentation thing, or the behavior of the `az` cli tool has changed, or both. Right now, I'd say it's confusing.

**Update**: It works (with the changes I made in a PR) if you create the cluster using the `az` command line; so it seems the Container Services UI in the portal uses a different template than the `az` command line does.

**Comment by jesushernandez** [comment]
I also noticed this. If the cluster is created via the portal, `mgmt` needs to be appended to your dns prefix when specifying `--dns-prefix` in `az acs kubernetes get-credentials`. What's a reasonable fix for this? There's a bit of inconsistency between the docs, what the portal does and what the cli does.

**Comment by brendandburns** [comment]
Using `--dns-prefix` is deprecated, just use `--resource-group` and `--name` and it will pull the relevant info from the API.

(and yes, I need to update docs too...)

**Comment by dtzar** [comment]
I went ahead and fixed [the documentation for the walkthrough](https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough) via this [existing PR I already had open](https://github.com/Microsoft/azure-docs/pull/324) for awhile to update the docker-machine.  So hopefully you can just approve both @dlepow and @mlearned?

**Comment by dtzar** [comment]
@DonMartin76 @jesushernandez or @brendandburns are there any other documents you know of which need to be updated that reference az acs kubernetes get-credentials and is the update I provided to the docs sufficient to close this issue out?

**Comment by dtzar** [comment]
Arg. just saw @DonMartin76 PR https://github.com/Microsoft/azure-docs/pull/342/files

**Comment by jesushernandez** [comment]
The confusing part for me was the documentation, so 👍  (disclaimer: I can't test that command right now, but I believe it just works as stated in the new documentation).

**Comment by dtzar** [comment]
@brendandburns It appears we are getting a new error now even when using the proper --resource-group and --name for the service.  I've tried on two different az installs (0.1.1b2+dev) and (0.1.1b1) and two fresh az acs create of clusters, with and without an SSH key that has/no password.

```
Authentication failed.
Traceback (most recent call last):
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 35, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 146, in execute
    result = expanded_arg.func(params)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 295, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 534, in k8s_get_credentials
    '.kube/config', path_candidate)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 21, in SecureCopy
    ssh.connect(host, username=user, key_filename=os.path.join(home, '.ssh', 'id_rsa'))
  File "/usr/local/az/local/lib/python2.7/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/local/az/local/lib/python2.7/site-packages/paramiko/client.py", line 621, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

**Comment by alex88** [comment]
@dtzar how do you specify the ssh key? Parameters let you select just the user, not the ssh key, I think it's the same as #1605

**Comment by dtzar** [comment]
Ah I figured it out - if you used anything other than id_rsa for your SSH key, then it will not properly authorize.  The solution is to use --ssh-key-file with the switch to the SSH key used to provision the cluster.

**Comment by alex88** [comment]
@dtzar is it in azure cli? I've installed it today and I cannot see it

```
➜  ~ az acs kubernetes get-credentials --help

Command
    az acs kubernetes get-credentials

Arguments
    --acs-info
    --dns-prefix
    --file -f          : Default: /Users/alex/.kube/config.
    --location -l      : Location.
    --name -n          : ACS cluster name.
    --resource-group -g: Name of resource group.
    --user

Global Arguments
    --debug            : Increase logging verbosity to show all debug logs.
    --help -h          : Show this help message and exit.
    --output -o        : Output format.  Allowed values: json, jsonc, list, table, tsv.  Default:
                         json.
    --query            : JMESPath query string. See http://jmespath.org/ for more information and
                         examples.
    --verbose          : Increase logging verbosity. Use --debug for full debug logs.
```

**Comment by dtzar** [comment]
Looks like this switch is new.  I'm using the latest via the docker image.
azure-cli (0.1.1b2+dev)
acs (0.1.1b1+dev)
I can see that --ssh-key-file is NOT present in 
azure-cli (0.1.1b1)
acs (0.1.1b1)

**Comment by alex88** [comment]
Oh I see, I've

```
azure-cli (0.1.1b2)
acr (0.1.1b1)
acs (0.1.1b1)
```

anyway, I've downloaded the config file from the master machine and it's now working, thanks

**Comment by dtzar** [comment]
@yugangw-msft or others - I think we are good to close out this issue now.
