### ISSUE TITLE
AssertionError: Expected 1 module to load starting with 'azext_': got []

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#16188]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "C:\yfy\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 509, in execute
    self.commands_loader.load_command_table(args)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 436, in load_command_table
    _update_command_table_from_extensions(ext_suppressions)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 307, in _update_command_table_from_extensions
    check_version_compatibility(ext.get_metadata())
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 147, in get_metadata
    azext_metadata = WheelExtension.get_azext_metadata(ext_dir)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 173, in get_azext_metadata
    ext_modname = get_extension_modname(ext_dir=ext_dir)
  File "c:\yfy\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 295, in get_extension_modname
    "'{}': got {}".format(EXTENSIONS_MOD_PREFIX, pos_mods))
AssertionError: Expected 1 module to load starting with 'azext_': got []
```
After debugging code, I find a solution. Remove extension folder in .azure. However, a normal user is not willing to and is not able to debug code. We can have a command to repair Azure CLI and reset environment.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by qwordy** [comment]
Thank you for your feedback!

**Comment by jiasli** [comment]
> After debugging code, I find a solution.

It will be very helpful if you can share more detail about your investigation. 

I checked the source code, this seems to be due to a corrupted extension installation that **the folder starting with `azext_` (`EXTENSIONS_MOD_PREFIX`) is missing**.

https://github.com/Azure/azure-cli/blob/04210197837bbceb547f86df7f086a42c96e0d2a/src/azure-cli-core/azure/cli/core/extension/__init__.py#L289-L296

For example, `ext_dir` is `C:\Users\username\.azure\cliextensions\account` but it doesn't contain the folder `azext_account`. The correct troubleshooting path is to figure out **why the extension installation gets corrupted** in the first place.

**Comment by fengzhou-msft** [comment]
The issue is likely to be caused by running tests in parallel. We have tests to add and remove the `spring-cloud` extension:
https://github.com/Azure/azure-cli/blob/85d96b07e386ffa56da5e96541b5caebee607a82/src/azure-cli/azure/cli/command_modules/monitor/tests/latest/test_monitor_autoscale.py#L319-L326

Other tests may throw the above error when the extension is removed while loading it.

**Comment by qwordy** [comment]
Right. I was testing network module. It needs eventgrid extension. Then Azure CLI broken.

**Comment by dwissaaj** [comment]
how to fix this error I got it too.

`The command failed with an unexpected error. Here is the traceback:
Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []`

**Comment by twright-msft** [comment]
I got into this state because of the following:
1) ```az extension add --source``` <file path to custom extension .whl>
2) Use that extension in a python runtime (in this case via Azure Data Studio notebook)
3) ```az extension remove -n``` <name of extension>
4) extension failed to delete on of the files in the ~/.azurebecause/cliextensions/<extensionname> directory because python was still using it.  Sorry, don't have the error message anymore but it said something about that it couldnt delete the file and that I could try manually deleting it.
5) Now ```az extension remove``` doesnt work anymore.  Nor do related commands like even ```az extension list``` or even ```az extension -h``` with the above error reported by others.

My solution:  kill the python process (or whatever process is holding a file in the cliextensions/<extensionname> directory), delete the file and clieextensions/<extensionname> directory manually.  HTH somebody.

Would be nice if az handled these partially deleted extensions better.

**Comment by jiasli** [comment]
@twright-msft, thanks for the detailed information. We will put this in our backlog and fix it when we have time.

In fact, you don't need to delete the whole `~/.azure/cliextensions` folder. You may simply detect the specific extension folder that is causing the problem, such as `~/.azure/cliextensions/account` for the extension `account`.

Please see [Concurrent builds](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#concurrent-builds) if you want to run Azure CLI instances concurrently.
