### ISSUE TITLE
Issue updating Azure CLI extensions

### ISSUE THREAD

**Issue by nameier** [Azure/azure-cli#16210]
## Describe the bug

**Command Name**
`az extension update`

**Errors:**
```
An error occurred whilst updating.
An error occurred. Pip failed with status code 1. Use --debug for more information.
Failed to update. Rolled vm-repair back to 0.3.1.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension update -n {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.15.1 *

Extensions:
image-copy-extension 0.2.1
maintenance 1.0.1
vm-repair 0.3.1

```

**Comment by nameier** [comment]
Full debug log below:

```
az extension update -n vm-repair --debug
Command arguments: ['extension', 'update', '-n', 'vm-repair', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f12e9cb7510>, <function OutputProducer.on_global_arguments at 0x7f12e93718c8>, <function CLIQuery.on_global_arguments at 0x7f12e938e9d8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'extension': ['azure.cli.command_modules.extension']
Loading command modules:
Name                  Load Time    Groups  Commands
extension                 0.002         1         7
Total (1)                 0.002         1         7
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0
Loaded 1 groups, 7 commands.
Found a match in the command table.
Raw command  : extension update
Command table: extension update
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f12e75af620>]
az_command_data_logger : command args: extension update -n {} --debug
metadata file logging enabled - writing logs to '/home/nathan/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f12e75642f0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f12e75469d8>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f12e7546a60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f12e7546b70>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f12e9371950>, <function CLIQuery.handle_query_parameter at 0x7f12e938ea60>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f12e7546950>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f12e7546ae8>]
urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 657656
Candidates ['vm_repair-0.2.6-py2.py3-none-any.whl', 'vm_repair-0.2.7-py2.py3-none-any.whl', 'vm_repair-0.3.1-py2.py3-none-any.whl', 'vm_repair-0.3.2-py2.py3-none-any.whl', 'vm_repair-0.3.3-py2.py3-none-any.whl', 'vm_repair-0.3.4-py2.py3-none-any.whl']
Candidates ['vm_repair-0.2.6-py2.py3-none-any.whl', 'vm_repair-0.2.7-py2.py3-none-any.whl', 'vm_repair-0.3.1-py2.py3-none-any.whl', 'vm_repair-0.3.2-py2.py3-none-any.whl', 'vm_repair-0.3.3-py2.py3-none-any.whl', 'vm_repair-0.3.4-py2.py3-none-any.whl']
Candidates ['vm_repair-0.2.6-py2.py3-none-any.whl', 'vm_repair-0.2.7-py2.py3-none-any.whl', 'vm_repair-0.3.1-py2.py3-none-any.whl', 'vm_repair-0.3.2-py2.py3-none-any.whl', 'vm_repair-0.3.3-py2.py3-none-any.whl', 'vm_repair-0.3.4-py2.py3-none-any.whl']
Skipping 'vm_repair-0.2.6-py2.py3-none-any.whl' as 0.2.6 not greater than current version 0.3.1
Skipping 'vm_repair-0.2.7-py2.py3-none-any.whl' as 0.2.7 not greater than current version 0.3.1
Skipping 'vm_repair-0.3.1-py2.py3-none-any.whl' as 0.3.1 not greater than current version 0.3.1
Candidates ['vm_repair-0.3.4-py2.py3-none-any.whl', 'vm_repair-0.3.3-py2.py3-none-any.whl', 'vm_repair-0.3.2-py2.py3-none-any.whl']
Choosing the latest of the remaining candidates.
Chosen {'downloadUrl': 'https://azurecliprod.blob.core.windows.net/cli-extensions/vm_repair-0.3.4-py2.py3-none-any.whl', 'filename': 'vm_repair-0.3.4-py2.py3-none-any.whl', 'metadata': {'azext.isPreview': False, 'azext.minCliCoreVersion': '2.0.67', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'caiddev@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/master/src/vm-repair'}}}, 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'vm-repair', 'summary': 'Auto repair commands to fix VMs.', 'version': '0.3.4'}, 'sha256Digest': 'b5964a8ed60193dc73e9109763af7cbb0162c029dbd81ed9ec5a7f20fa48ee7d'}
Backing up the current extension: /home/nathan/.azure/cliextensions/vm-repair to /tmp/tmpgy18pfiy/vm-repair
Extension source is url? True
Downloading https://azurecliprod.blob.core.windows.net/cli-extensions/vm_repair-0.3.4-py2.py3-none-any.whl to /tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliprod.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliprod.blob.core.windows.net:443 "GET /cli-extensions/vm_repair-0.3.4-py2.py3-none-any.whl HTTP/1.1" 200 32536
Downloaded to /tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl
Validating the extension /tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl
Checksum of /tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl is OK
Validation successful on /tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl
Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
Linux distro check: Found in list file: https://packages.microsoft.com/repos/azure-cli/
Linux distro check: Reported by API: focal
Linux distro check: Mismatch distribution name in /etc/apt/sources.list.d/azure-cli.list file
Linux distro check: If command fails, install the appropriate package for your distribution or change the above file accordingly.
Linux distro check: /etc/apt/sources.list.d/azure-cli.list has 'https://packages.microsoft.com/repos/azure-cli/', current distro is 'focal'
Executing pip with args: ['install', '--target', '/home/nathan/.azure/cliextensions/vm-repair', '/tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl']
Running: ['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/home/nathan/.azure/cliextensions/vm-repair', '/tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 18, in <module>
    from pip._internal.download import PipSession
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/download.py", line 38, in <module>
    from pip._internal.utils.glibc import libc_ver
  File "/opt/az/lib/python3.6/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
    import ctypes
  File "/opt/az/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

Command '['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/home/nathan/.azure/cliextensions/vm-repair', '/tmp/tmpdyvc4mwt/vm_repair-0.3.4-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Pip failed so deleting anything we might have installed at /home/nathan/.azure/cliextensions/vm-repair
An error occurred whilst updating.
An error occurred. Pip failed with status code 1. Use --debug for more information.
Copying /tmp/tmpgy18pfiy/vm-repair to /home/nathan/.azure/cliextensions/vm-repair
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/operations.py", line 321, in update_extension
    pip_extra_index_urls=pip_extra_index_urls, pip_proxy=pip_proxy)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/operations.py", line 161, in _add_whl_ext
    'Use --debug for more information.'.format(pip_status_code))
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/extension/custom.py", line 35, in update_extension_cmd
    pip_extra_index_urls=pip_extra_index_urls, pip_proxy=pip_proxy)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/operations.py", line 331, in update_extension
    raise CLIError('Failed to update. Rolled {} back to {}.'.format(extension_name, cur_version))
knack.util.CLIError: Failed to update. Rolled vm-repair back to 0.3.1.

cli.azure.cli.core.azclierror : Failed to update. Rolled vm-repair back to 0.3.1.
Failed to update. Rolled vm-repair back to 0.3.1.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f12e75af840>]
az_command_data_logger : exit code: 1
Command ran in 19.245 seconds (init: 0.187, invoke: 19.057)
telemetry.save : Save telemetry record of length 3059 in cache
```
