### ISSUE TITLE
Permission issue while installing AKS Client [kubectl]

### ISSUE THREAD

**Issue by balavivek143** [Azure/azure-cli#16352]
## Describe the bug
Permission issue while exeucting az command to install kubectl in azure cloud shell

**az aks install-cli --install-location ./kubectl**
``

**Errors:**
Downloading client to "./kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl"
Please ensure that . is in your search PATH, so the `kubectl` command can be found.
Downloading client to "/tmp/tmpnis7wt12/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.7/kubelogin.zip"
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpnis7wt12/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 349, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version, kubelogin_install_location, kubelogin_base_src_url)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 463, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/az/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/opt/az/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/az/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `Followed same steps give in the Official documents to create a new AKS instance https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough. Encountered above error when trying to download the client from aks`

## Expected Behavior
Command execution without error. And kubectl software download in specified location and enable kubectl commands.

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/16070

**Comment by navba-MSFT** [comment]
@balavivek143 Apologies for the late reply. The error is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions) if you don't have the full access to the cloud shell environment. So you can follow the below steps:

To install kubectl (specific version) in a specified path in the home folder, for example:

>XXXX/Azure:~$ az aks install-cli **--install-location** mykubetools/kubectl1.19.1 --client-version 1.19.1 **--kubelogin-install-location** mykubetools/kubelogin

**Output**
Downloading client to "mykubetools/kubectl1.19.1" from [https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl]
Please ensure that mykubetools is in your search PATH, so the kubectl1.19.1 command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from [https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip]

Please ensure that mykubetools is in your search **PATH**, so the kubelogin command can be found.

>XXXX/Azure:~$ ./mykubetools/kubectl1.19.1 version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Hope this helps. Please let me know if you have any further questions on this.
