### ISSUE TITLE
Cannot update vpn-gateway with address prefixes

### ISSUE THREAD

**Issue by bridgetcdavis** [Azure/azure-cli#1637]
It is required for a vpn-gateway to have an address prefix before a Root Cert can be added. I need to be able to assign address prefixes to the gateway for Point-to-Site to work at all. I see "address prefixes" is not a field when creating the vpn-gateway. I can only add them after the vpn-gateway has been created by using the "update" command. However, when I run the command:
```
az network vpn-gateway update -n PythonP2Sgw -g TestingPortalRG --address-prefixes {"127.0.0.0
/28"}
```
it gives me this error:
```
Parameter 'body' can not be None.
Traceback (most recent call last):
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 279, in handler
    opres = setter(client, **getterargs) if client else setter(**getterargs)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/mgmt/network/operations/virtual_network_gateways_operations.py", line 86, in create_or_update
    body_content = self._serialize.body(parameters, 'VirtualNetworkGateway')
  File "/usr/local/az/local/lib/python2.7/site-packages/msrest/serialization.py", line 302, in body
    raise ValidationError("required", "body", True)
ValidationError: Parameter 'body' can not be None.
```

**Comment by tjprescott** [comment]
`az network vpn-gateway update -n PythonP2Sgw -g TestingPortalRG --address-prefixes 127.0.0.0/28`

Should work fine. If you want a list of addresses, they should be space separated:
`az network vpn-gateway update -n PythonP2Sgw -g TestingPortalRG --address-prefixes 127.0.0.0/28 125.0.0.0/28`

**Comment by bridgetcdavis** [comment]
I ran exactly that and received the same error.
`az network vpn-gateway update -n PythonP2Sgw -g TestingPortalRG --address-prefixes 127.0.0.0/28
````
Parameter 'body' can not be None.
Traceback (most recent call last):
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 33, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 279, in handler
    opres = setter(client, **getterargs) if client else setter(**getterargs)
  File "/usr/local/az/local/lib/python2.7/site-packages/azure/mgmt/network/operations/virtual_network_gateways_operations.py", line 86, in create_or_update
    body_content = self._serialize.body(parameters, 'VirtualNetworkGateway')
  File "/usr/local/az/local/lib/python2.7/site-packages/msrest/serialization.py", line 302, in body
    raise ValidationError("required", "body", True)
ValidationError: Parameter 'body' can not be None.
```

**Comment by tjprescott** [comment]
I've confirmed that this works correctly on the latest build. PR #1539 renamed `vpn-gateway` to `vnet-gateway`, so if you update your network component to the latest, it should work fine.

`az network vnet-gateway update -n PythonP2Sgw -g TestingPortalRG --address-prefixes 127.0.0.0/28`
