### ISSUE TITLE
`az feedback` truncates the call stack

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#16386]
**Describe the bug**
`az feedback` truncates the call stack of errors, like in #16373.

For example, if `az demo style` raises an `Exception` at

https://github.com/Azure/azure-cli/blob/821c01375e9f3aa513b221116c4f1f44b823d8ba/src/azure-cli/azure/cli/command_modules/util/custom.py#L175

```py
raise Exception()
```

The original call stack is 

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\cli\env38\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in execute
    raise ex
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "D:\cli\env38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\util\custom.py", line 176, in demo_style
    raise Exception()
Exception
```

But `az feedback` reports it as

```
Traceback (most recent call last):
env38\lib\site-packages\knack\cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
azure\cli\core\commands\__init__.py, ln 659, in execute
    raise ex
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
azure\cli\core\commands\__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
cli\env38\lib\site-packages\six.py, ln 703, in reraise
    raise value
azure\cli\core\commands\__init__.py, ln 693, in _run_job
    result = cmd_copy(params)
azure\cli\core\commands\__init__.py, ln 330, in __call__
    return self.handler(*args, **kwargs)
azure-cli-core\azure\cli\core\__init__.py, ln 784, in default_command_handler
    return op(**command_args)
azure\cli\command_modules\util\custom.py, ln 176, in demo_style
    raise Exception()
Exception
```

This leads to difficulty in troubleshooting, especially for packaging problems.

**Comment by yonzhan** [comment]
feedback
