### ISSUE TITLE
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by Chakravarthi-Lolla** [Azure/azure-cli#16392]
2020-12-30T04:48:44.4025899Z CLIInternalError: The command failed with an unexpected error. Here is the traceback:
2020-12-30T04:48:44.4028567Z 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
2020-12-30T04:48:44.4029698Z Traceback (most recent call last):
2020-12-30T04:48:44.4030507Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
2020-12-30T04:48:44.4030943Z     cmd_result = self.invocation.execute(args)
2020-12-30T04:48:44.4031652Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
2020-12-30T04:48:44.4032067Z     raise ex
2020-12-30T04:48:44.4032917Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
2020-12-30T04:48:44.4033462Z     results.append(self._run_job(expanded_arg, cmd_copy))
2020-12-30T04:48:44.4034211Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
2020-12-30T04:48:44.4034667Z     six.reraise(*sys.exc_info())
2020-12-30T04:48:44.4035287Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
2020-12-30T04:48:44.4035661Z     raise value
2020-12-30T04:48:44.4036325Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
2020-12-30T04:48:44.4036779Z     result = cmd_copy(params)
2020-12-30T04:48:44.4037465Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
2020-12-30T04:48:44.4037951Z     return self.handler(*args, **kwargs)
2020-12-30T04:48:44.4038679Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
2020-12-30T04:48:44.4039144Z     return op(**command_args)
2020-12-30T04:48:44.4039849Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2221, in set_user
2020-12-30T04:48:44.4040428Z     return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
2020-12-30T04:48:44.4041277Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2208, in _reset_windows_admin
2020-12-30T04:48:44.4041865Z     poller = client.virtual_machine_extensions.create_or_update(resource_group_name,
2020-12-30T04:48:44.4042809Z AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
2020-12-30T04:48:44.4043455Z To open an issue, please run: 'az feedback'
2020-12-30T04:48:44.5195925Z ##[error]Script failed with exit code: 1

**Comment by fengzhou-msft** [comment]
@qwordy can you take a look?

**Comment by qwordy** [comment]
@Chakravarthi-Lolla Which version of Azure CLI do you use? And can you share your command?

**Comment by srinisbook** [comment]
~$ az --version
azure-cli                         2.17.0

core                              2.17.0
telemetry                          1.0.6

command: 
az vm user update   --username $user   --password $passwd   --name $VirtualMachineName   --resource-group $ResourceGroup

**Comment by mikkovkivisto** [comment]
@qwordy  Any news on this?

**Comment by qwordy** [comment]
I tried and no error. I am using 2.18.0. It will be released on 1/19. Could you try again after the new version is released?

**Comment by mikkovkivisto** [comment]
> I tried and no error. I am using 2.18.0. It will be released on 1/19. Could you try again after the new version is released?

Sure, I'll test once its available in one of the DevOps agents we are using

**Comment by lapontec** [comment]
Same error here, I'm using 2.18.0

Version:
az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Extensions:
interactive                        0.4.4
desktopvirtualization               0.1.0

Error:
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
.
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 2211, in _reset_windows_admin
    poller = client.virtual_machine_extensions.create_or_update(resource_group_name,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'

**Comment by qwordy** [comment]
Same issue: https://github.com/Azure/azure-cli/issues/16962

**Comment by estoel81** [comment]
What is the status of this issue?

**Comment by qwordy** [comment]
It has been fixed in next release on 3/23.
