### ISSUE TITLE
Trying to run az webapp deployment user set on M1 Mac

### ISSUE THREAD

**Issue by sshingler** [Azure/azure-cli#16414]
## Describe the bug

**Command Name**
`az webapp deployment user set`

**Errors:**
```
dlopen(/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
...
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment user set --user-name {} --password {}`

## Environment Summary
```
macOS-11.1-arm64-arm-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.17.0

```

**Comment by sshingler** [comment]
Full traceback:

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
dlopen(/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 315, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 787, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 827, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/homebrew/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 26, in <module>
    import OpenSSL.crypto
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(/opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.17.0/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@sshingler do you see this error only on this command do other commands work? if so can you clean up & re-install CLI on MACOS?

**Comment by panchagnula** [comment]
@yonzhan are there any known issues with installing & using CLI on M1 Mac?

**Comment by yonzhan** [comment]
@fengzhou-msft to help with installing.

**Comment by yungezz** [comment]
hi @sshingler could you share how CLI is installed? it seems dependency pacakges missed. Re-install might help. let us know how it works. cc @fengzhou-msft
