### ISSUE TITLE
accessTokens Permission denied

### ISSUE THREAD

**Issue by benoitboheas** [Azure/azure-cli#16433]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
[Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'
Traceback (most recent call last):
Temp\pip-install-rg707cll\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-rg707cll\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\profile\custom.py, ln 147, in login
azure-cli-core\azure\cli\core\_profile.py, ln 219, in find_subscriptions_on_login
azure-cli-core\azure\cli\core\_profile.py, ln 893, in persist_cached_creds
azure-cli-core\azure\cli\core\_profile.py, ln 898, in flush_to_disk
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.73

```

**Comment by yonzhan** [comment]
az login

**Comment by jiasli** [comment]
Similar to #15638. Could you follow the troubleshooting steps provided in #15638 and let us know if that solves the issue?

**Comment by benoitboheas** [comment]
PS C:\WINDOWS\system32> az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
The command failed with an unexpected error. Here is the traceback:

[Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli\azure\cli\command_modules\profile\custom.py", line 147, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 219, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 893, in persist_cached_creds
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 898, in flush_to_disk
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'

To open an issue, please run: 'az feedback'
PS C:\WINDOWS\system32> az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DHBBPZP5S to authenticate.
The command failed with an unexpected error. Here is the traceback:

[Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli\azure\cli\command_modules\profile\custom.py", line 147, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 219, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 893, in persist_cached_creds
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rg707cll\azure-cli-core\azure\cli\core\_profile.py", line 898, in flush_to_disk
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\FKDK7307\\.azure\\accessTokens.json'

To open an issue, please run: 'az feedback'
