### ISSUE TITLE
az aks update --attach-acr fails with argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-cli#16479]
**Describe the bug**
_az aks update -n $CLUSTER_NAME -g $RG_NAME --attach-acr $ACR_NAME_ fails with below exception

`The behavior of this command has been altered by the following extension: aks-preview
AAD role propagation done[############################################]  100.0000%CLIInternalError: The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-igh1xymj\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\sanjayd\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 1495, in aks_update
    monitoring_addon_enabled = CONST_MONITORING_ADDON_NAME in instance.addon_profiles and \
TypeError: argument of type 'NoneType' is not iterable`

It seems the aks identity is being added as ImagePull role but then it fails with the exception.

**To Reproduce**
az aks update -n $CLUSTER_NAME -g $RG_NAME --attach-acr $ACR_NAME

**Expected behavior**
Should not throw exception post successful assignment of the role

**Environment summary**
Windows:
{
  "azure-cli": "2.17.1",
  "azure-cli-core": "2.17.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.71",
    "application-insights": "0.1.13",
    "kusto": "0.2.0"
  }
}

**Additional context**
I have not yet tried deploying an image from ACR to AKS post this ACR attach, shall update if I see any issue in that.

**Comment by yonzhan** [comment]
aks

**Comment by zeljko-bilandzija1979** [comment]
I had a same errors and after I removed aks-preview extension (az extension remove --name aks-preview) errors gone.

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you still seeing this issue
