### ISSUE TITLE
az command fails with unexpected error in azure-cli

### ISSUE THREAD

**Issue by intel-ohara** [Azure/azure-cli#16529]
## Describe the bug

**Command Name**
`az account list`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 5] Input/output error: '/home/shigeyoshi_ohara/.azure/commands/2021-01-14.00-11-23.account_list.252.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 516, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 5] Input/output error: '/home/shigeyoshi_ohara/.azure/commands/2021-01-14.00-11-23.account_list.252.log'
```

## To Reproduce:
I didn't have any problem when I used azure-cli yesterday. When I execute "az iot hub create ..." today, I got an unexpected failure. Then, I logged out and log in my Azure account. I tried same command and "az account list", but both failed.

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-iot-ext 0.8.10
azure-cli-ml 1.19.0

Extensions:
azure-cli-iot-ext 0.8.10
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yonzhan** [comment]
account

**Comment by jiasli** [comment]
`OSError: [Errno 5] Input/output error` indicates your file system is corrupted. Please try deleting it with 

```
rm /home/shigeyoshi_ohara/.azure/commands/2021-01-14.00-11-23.account_list.252.log
```
If the file can't be deleted, you may use `fsck` to check for bad sectors. See https://askubuntu.com/questions/65830/errno-5-input-output-error-when-trying-to-install-ubuntu
