### ISSUE TITLE
Error when creating image for image-gallery from image in different resource group

### ISSUE THREAD

**Issue by TobiMichael96** [Azure/azure-cli#16534]
## Error when creating image for image-gallery from image

I try to create an image for an image-gallery from an image in a different resource group. 

**az sig image-version create**
```
az sig image-version create \
   --resource-group rg-name \
   --gallery-name gallyer-name\
   --gallery-image-definition image-definition \
   --gallery-image-version 1.0.2 \
   --managed-image "/subscriptions/id/resourceGroups/rg-name/providers/Microsoft.Compute/images/image-name"
```

**Errors:**

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 3276, in create_image_version
    external_bearer_token = external_tokens[0][0] + ' ' + external_tokens[0][1]
TypeError: 'NoneType' object is not subscriptable
```

## To Reproduce:

Create a virtual machine, deallocate it, generalize it, create an image from it.

## Expected Behavior

It should create an image inside an image-gallery.

## Environment Summary
```
macOS-11.1-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.17.1

Extensions:
azure-devops 0.18.0

```

**Comment by TobiMichael96** [comment]
I think this can be closed as this error is pretty similar to the one here: #16466.

So I guess it will be fixed with the new version.

Can you guys confirm this?

**Comment by yungezz** [comment]
hi @qwordy could you pls help to confirm?

**Comment by qwordy** [comment]
@TobiMichael96 Thank you for reporting this issue. It was fixed by https://github.com/Azure/azure-cli/commit/72c2203957760402e115e2056d018aa7a520d7bc.
Release date: 01/19/2021

**Comment by qwordy** [comment]
> 
> 
> I think this can be closed as this error is pretty similar to the one here: #16466.
> 
> So I guess it will be fixed with the new version.
> 
> Can you guys confirm this?

Yes, you are right.
