### ISSUE TITLE
Create ExpressRoute Gateway connection fails without --propagated-route-tables

### ISSUE THREAD

**Issue by NikoMix** [Azure/azure-cli#16615]
**Describe the bug**
When executing following command with valid parameters 
az network express-route gateway connection create --gateway-name <name> --name <name> --peering <peering> --resource-group <resource-group>

**To Reproduce**
az network express-route gateway connection create --gateway-name <name> --name <name> --peering <peering> --resource-group <resource-group> (basically anything without the optional, preview arugment: --propagated-route-tables) so the method create_express_route_connection is called with the default Parameter  propagated_route_tables=None

**Expected behavior**
Create a new ExpressRoute Gateway connection

**Environment summary**
Install Method: MSI / Windows &
Azure Cloud Shell 

**Additional context**
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
   results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 2654, in create_express_route_connection
    ids=[SubResource(id=propagated_route_table) for propagated_route_table in propagated_route_tables]
TypeError: 'NoneType' object is not iterable

**Comment by yungezz** [comment]
ropuotet to appropriate team

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by jsntcy** [comment]
Fix this line https://github.com/Azure/azure-cli/blob/7270756c6b2a7a3db3e5ee948154cfcbfd0a8c1c/src/azure-cli/azure/cli/command_modules/network/custom.py#L2654 to `ids=[SubResource(id=propagated_route_table) for propagated_route_table in propagated_route_tables] if propagated_route_tables else None`

**Comment by amsgeodis** [comment]
@yonzhan Do you know when your fix will be in place?

**Comment by yonzhan** [comment]
Since we are on Chinese New Year holiday from 2.11 to 2.17, please expect a delay in response from us. @msyyc will take a look and let you know after holiday.

**Comment by msyyc** [comment]
we will fix it at this sprint.
