### ISSUE TITLE
Can't deploy azure function app.

### ISSUE THREAD

**Issue by edmlbox** [Azure/azure-cli#16645]
## Describe the bug
I was able to deploy my azure function app for months without any problem but today it's just impossible.
**Command Name**
``
 az functionapp deployment source config-zip -g Res001 -n res002 --src C:\Users\Admin\Desktop\azure\azure.zip
**Errors:**
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='res002.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6ADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connection.py", line 160, in _new_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\util\connection.py", line 80, in create_connection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\util\connection.py", line 70, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connectionpool.py", line 603, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connectionpool.py", line 344, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connectionpool.py", line 843, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connection.py", line 316, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connection.py", line 169, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x05F6ADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\connectionpool.py", line 641, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ce49rpvu\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='res002.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6ADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-s5x_2dzp\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py", line 786, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\appservice\custom.py", line 389, in enable_zip_deploy_functionapp
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\appservice\custom.py", line 422, in enable_zip_deploy
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\api.py", line 116, in post
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\api.py", line 60, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-kwr6xmq7\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='res002.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05F6ADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

```

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@Hazhzeng can you please take a look at this?

**Comment by Hazhzeng** [comment]
Hi @edmlbox,

Sorry for the late reply. Does this issue still persist? Please check to login https://res002.scm.azurewebsites.net from your browser and see if you can receive any response. This may just be a network hiccup but not an Azure CLI issue.

**Comment by edmlbox** [comment]
Everyting ok now.
