### ISSUE TITLE
az datafactory linked-service create not working

### ISSUE THREAD

**Issue by vladris** [Azure/azure-cli#16646]
I am trying to create a linked service using Azure CLI in PowerShell Core.

My JSON file is `adx.json`:
```
{
    "type": "AzureDataExplorer",
    "typeProperties": {
        "endpoint": "...",
        "tenant": "...",
        "servicePrincipalId": "...",
        "servicePrincipalKey": "...",
        "database": "..."
    }
}
```

I am using the following command:
```
az datafactory linked-service create --factory-name "..."  --resource-group "..." --name adx --properties "@./adx.json"
```
This fails with:

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py", line 1416, in _deserialize
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py", line 1181, in rest_key_case_insensitive_extractor
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py", line 1210, in attribute_key_case_insensitive_extractor
AttributeError: 'str' object has no attribute 'get'
```

I'm using Azure CLI version 2.18.0 of Azure CLI in PowerShell Core.

**Comment by yonzhan** [comment]
datafactory

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by vladris** [comment]
Hey @fengzhou-msft, any news on this?

**Comment by fengzhou-msft** [comment]
@vladris sorry for the delay. The issue is caused by the generated vendored SDK. I'm working with codegen Team on a fix.

**Comment by qiaozha** [comment]
a correct example would look like this. The servicePrincipalKey is not a string type. it should be a SecretBase type.  
```
{
    "type": "AzureDataExplorer",
    "tenant": "",
    "service_principal_id": "",
    "service_principal_key": {
        "type": "SecureString",
        "value": "aaaa"
    },
    "endpoint": "",
    "database": ""
}
```

**Comment by qiaozha** [comment]
```
{
    "type": "AzureDataExplorer",
    "typeProperties": {
        "endpoint": "...",
        "tenant": "...",
        "servicePrincipalId": "...",
        "servicePrincipalKey": {
            "type": "SecureString",
            "value": "aaaa"
        },
        "database": "..."
    }
}
```

This way works too.

**Comment by vladris** [comment]
Can confirm that this works. Thanks a lot!
