### ISSUE TITLE
az login fails: TypeError: object.__new__() takes exactly one argument (the type to instantiate)

### ISSUE THREAD

**Issue by barto90** [Azure/azure-cli#16675]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
object.__new__() takes exactly one argument (the type to instantiate)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
azure/mgmt/core/_pipeline_client.py, ln 50, in __init__
    kwargs["policies"] = self._default_policies(**kwargs)
azure/mgmt/core/_pipeline_client.py, ln 61, in _default_policies
    ContentDecodePolicy(**kwargs),
usr/lib/python3.8/typing.py, ln 875, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --password {} --tenant {}`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.5
Installer: PIP

azure-cli 2.18.0

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
This issue has been reported before in https://github.com/Azure/azure-sdk-for-python/issues/12203.

When `ContentDecodePolicy` doesn't have `__init__`, passing non-empty `**kwargs` is equivalent to passing them to `object()` which causes the failure in `typing.py`.

```py
class Generic:
    def __new__(cls, *args, **kwds):
        if super().__new__ is object.__new__ and cls.__init__ is not object.__init__:
            obj = super().__new__(cls)
        else:
            obj = super().__new__(cls, *args, **kwds)
```

`ContentDecodePolicy.__init__` was added by https://github.com/Azure/azure-sdk-for-python/pull/9595:

```py
class ContentDecodePolicy(SansIOHTTPPolicy):
    def __init__(self, response_encoding=None, **kwargs):  # pylint: disable=unused-argument
        # type: (Optional[str], Any) -> None
        self._response_encoding = response_encoding
```

So could you verify the version of [`azure-core`](https://pypi.org/project/azure-core/) in your environment to make sure it is the latest 1.10.0?

```
pip list | grep azure-core
pip install --upgrade azure-core
```

**Comment by barto90** [comment]
azure-core is already installed with version 1.10.0 

Please see the results:
pip list | grep azure-core
azure-core                                       1.10.0

Did a pip install with --force 

No result. The same error occurs

**Comment by jiasli** [comment]
This is very weird. @barto90, could you share the full error message?

`azure-core` 1.10.0's `ContentDecodePolicy` does have `__init__` defined:

https://github.com/Azure/azure-sdk-for-python/blob/azure-core_1.10.0/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L463-L477

```py
class ContentDecodePolicy(SansIOHTTPPolicy):
    ...
    def __init__(self, response_encoding=None, **kwargs):  # pylint: disable=unused-argument
        # type: (Optional[str], Any) -> None
        self._response_encoding = response_encoding
```

Could you run `cat` on `_universal.py` and see if it has the same content as the above file?

**Comment by barto90** [comment]
@jiasli 

It seems the file does contain the mentioned class. See;

class ContentDecodePolicy(SansIOHTTPPolicy):
    """Policy for decoding unstreamed response content.

    :param response_encoding: The encoding to use if known for this service (will disable auto-detection)
    :type response_encoding: str
    """
    # Accept "text" because we're open minded people...
    JSON_REGEXP = re.compile(r'^(application|text)/([0-9a-z+.]+\+)?json$')

    # Name used in context
    CONTEXT_NAME = "deserialized_data"

    def __init__(self, response_encoding=None, **kwargs):  # pylint: disable=unused-argument
        # type: (Optional[str], Any) -> None
        self._response_encoding = response_encoding

The full error message which is shown is;

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
object.__new__() takes exactly one argument (the type to instantiate)
Traceback (most recent call last):
  File "/home/bpas/.local/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/home/bpas/.local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 154, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 210, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_from_service_principal_id(
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 901, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 995, in _find_using_specific_tenant
    client = self._arm_client_factory(token_credential)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 842, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/cli/core/vendored_sdks/subscriptions/_subscription_client.py", line 66, in __init__
    self._client = ARMPipelineClient(base_url=base_url, config=self._config, **kwargs)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/mgmt/core/_pipeline_client.py", line 50, in __init__
    kwargs["policies"] = self._default_policies(**kwargs)
  File "/home/bpas/.local/lib/python3.8/site-packages/azure/mgmt/core/_pipeline_client.py", line 61, in _default_policies
    ContentDecodePolicy(**kwargs),
  File "/usr/lib/python3.8/typing.py", line 875, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)

**Comment by jiasli** [comment]
That's weird, I didn't see any reason `if super().__new__ is object.__new__ and cls.__init__ is not object.__init__` is evaluated to `False`.

Do you see the same error if you use `python` to directly run this script:

```py
from azure.core.pipeline.policies import ContentDecodePolicy

ContentDecodePolicy(name="value")
```

I also added a debug line in `typing.py`,

```py 
        print(super().__new__, object.__new__, cls.__init__, object.__init__, args, kwds)  # Added this line
        if super().__new__ is object.__new__ and cls.__init__ is not object.__init__:
            obj = super().__new__(cls)
        else:
            obj = super().__new__(cls, *args, **kwds)
        return obj
```

The above script should show 

```
<built-in method __new__ of type object at 0x00007FFD709FAB50> <built-in method __new__ of type object at 0x00007FFD709FAB50> <function ContentDecodePolicy.__init__ at 0x00000283DECF55E0> <slot wrapper '__init__' of 'object' objects> () {'name': 'value'}
```

**Comment by barto90** [comment]
When I run the python script directly it gives me the following output

 python3 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    ContentDecodePolicy(name="value")
  File "/usr/lib/python3.8/typing.py", line 875, in __new__
    obj = super().__new__(cls, *args, **kwds)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)

I haven't had time to test the debug line

**Comment by jiasli** [comment]
Well, at least we can narrow down the issue to Azure Python SDK. 

> I haven't had time to test the debug line

No hurry. Please take your time. 😊

**Comment by barto90** [comment]
Sorry jiasli,

Appreciate your effort but I don't seem to find a moment to work on this. Is the debug line required? If so I need some more time. 

My apologies.

**Comment by jiasli** [comment]
@barto90, don't worry, we can keep this issue opened. As we are not seeing other users reporting this issue, so it is very likely related to the environment.

**Comment by MaddyMicrosoft** [comment]
This couldn't be reproduced when filed and no further reports followed, and the auth stack has since moved to MSAL. Closing as stale; if a similar error appears on current CLI, please open a fresh issue with a full traceback.
