### ISSUE TITLE
az sf cluster certificate add command fails

### ISSUE THREAD

**Issue by Skido8** [Azure/azure-cli#16734]
## Describe the bug

**Command Name**
`az sf cluster certificate add`

**Errors:**
```
'VirtualMachineScaleSetExtension' object has no attribute 'type1'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
Local\Temp\pip-unpacked-wheel-igh1xymj\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 693, in _run_job
cli\core\commands\__init__.py, ln 330, in __call__
azure\cli\core\__init__.py, ln 784, in default_command_handler
cli\command_modules\servicefabric\custom.py, ln 478, in add_cluster_cert
cli\command_modules\servicefabric\custom.py, ln 1063, in _get_cluster_vmss_by_node_type
cli\command_modules\servicefabric\custom.py, ln 1235, in _get_sf_vm_extension
cli\command_modules\servicefabric\custom.py, ln 1236, in <listcomp>
AttributeError: 'VirtualMachineScaleSetExtension' object has no attribute 'type1'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf cluster certificate add -g {} -c {} --secret-identifier {} --vault-name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

```

**Comment by yonzhan** [comment]
sf

**Comment by mbactol3** [comment]
+1 same issue 
azure cli on powershell 
azure-cli                         2.17.1 *
core                              2.17.1 *
PSVersion                      5.1.19041.610  

`az sf cluster certificate add -g $sfResourceGroup -c $sfClusterName --secret-identifier $sfCertSecretId`
```
az : CLIInternalError: The command failed with an unexpected error. Here is the traceback:
At line:1 char:1
+ az sf cluster certificate add -g $sfResourceGroup -c $sfClusterName - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CLIInternalErro... the traceback::String) [], RemoteException
  + FullyQualifiedErrorId : NativeCommandError
 
'VirtualMachineScaleSetExtension' object has no attribute 'type1'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-igh1xymj\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\servicefabric\custom.py", line 478, in add_cluster_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\servicefabric\custom.py", line 1063, in _get_cluster_vmss_by_node_type
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\servicefabric\custom.py", line 1235, in _get_sf_vm_extension
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\servicefabric\custom.py", line 1236, in <listcomp>
AttributeError: 'VirtualMachineScaleSetExtension' object has no attribute 'type1'
To open an issue, please run: 'az feedback'
```

**Comment by mbactol3** [comment]
Traced it down to an issue with the script being run for the extension.  Once the error in the script was fixed it seemed to work.

**Comment by mwesigwaguma** [comment]
this command was removed by ServiceFabric team. Closing
