### ISSUE TITLE
az ts export always fails

### ISSUE THREAD

**Issue by willynagel** [Azure/azure-cli#16736]
Az ts export -g <resourcegroupname> --name <templatespecname --output-folder <outputfolder> always fails with:

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'TemplateSpec' object has no attribute 'template'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 717, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 710, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-in8b2jw5\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_skkczbr\azure\cli\command_modules\resource\custom.py", line 1888, in export_template_spec
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_skkczbr\azure\cli\command_modules\resource\_packing_engine.py", line 185, in unpack
AttributeError: 'TemplateSpec' object has no attribute 'template'

Tested on az cli 2.16.0 and 2.18.0.

This started this week, last week the command ran successfully.

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
Hi @detienne20 Could you please help to take a look at this issue~

**Comment by detienne20** [comment]
@willynagel I believe this is the result of attempting to export a template spec instead of a template spec version. Exporting a template spec is not possible. Please retry this command with --version.  I will work on improving the error message, thank you for the feedback!

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
