### ISSUE TITLE
Can not use "--network-profile" with IP address type "Public"

### ISSUE THREAD

**Issue by czmirek** [Azure/azure-cli#16737]
## Describe the bug
Even with `--ip-address Private` i'm getting error message that IP address type is "Public"
Location: West Europe

**Command Name**
`az container create`

**Errors:**
```
Can not use "--network-profile" with IP address type "Public".
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create or have an existing networking profile pointing on a specific subnet.
- `az container create --resource-group myresourcegroup --ip-address Private --name testcli --image nginx --network-profile profilename`

## Expected Behavior
Container is created.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

Extensions:
azure-devops 0.18.0

```
## Additional Context
I swear this used to work.  Below is the details of the networking profile.
```
[
  {
    "containerNetworkInterfaceConfigurations": [
      {
        "containerNetworkInterfaces": [
          {
            "id": "***",
            "resourceGroup": "myresourcegroup"
          },
          {
            "id": "***",
            "resourceGroup": "myresourcegroup"
          }
        ],
        "etag": "W/\"f993fb7a-d846-48f4-9fb7-4cc70b9f8691\"",
        "id": "***",
        "ipConfigurations": [
          {
            "etag": "W/\"f993fb7a-d846-48f4-9fb7-4cc70b9f8691\"",
            "id": "***",
            "name": "ci_subnet_ipconf",
            "provisioningState": "Succeeded",
            "resourceGroup": "myresourcegroup",
            "subnet": {
              "addressPrefix": null,
              "addressPrefixes": null,
              "delegations": null,
              "etag": null,
              "id": "***",
              "ipAllocations": null,
              "ipConfigurationProfiles": null,
              "ipConfigurations": null,
              "name": null,
              "natGateway": null,
              "networkSecurityGroup": null,
              "privateEndpointNetworkPolicies": null,
              "privateEndpoints": null,
              "privateLinkServiceNetworkPolicies": null,
              "provisioningState": null,
              "purpose": null,
              "resourceGroup": "vnet-resource-group",
              "resourceNavigationLinks": null,
              "routeTable": null,
              "serviceAssociationLinks": null,
              "serviceEndpointPolicies": null,
              "serviceEndpoints": null
            },
            "type": "Microsoft.Network/networkProfiles/containerNetworkInterfaceConfigurations/ipConfigurations"
          }
        ],
        "name": "ci_subnet_cni",
        "provisioningState": "Succeeded",
        "resourceGroup": "myresourcegroup",
        "type": "Microsoft.Network/networkProfiles/containerNetworkInterfaceConfigurations"
      }
    ],
    "containerNetworkInterfaces": [
      {
        "container": {
          "id": "",
          "resourceGroup": "myresourcegroup"
        },
        "containerNetworkInterfaceConfiguration": {
          "containerNetworkInterfaces": null,
          "etag": null,
          "id": "***",
          "ipConfigurations": null,
          "name": null,
          "provisioningState": null,
          "resourceGroup": "myresourcegroup",
          "type": null
        },
        "etag": "W/\"f993fb7a-d846-48f4-9fb7-4cc70b9f8691\"",
        "id": "***",
        "ipConfigurations": [],
        "name": "bec970e9-3411-4377-9960-ef1492f790d2_ci_subnet_cni",
        "provisioningState": "Succeeded",
        "resourceGroup": "myresourcegroup",
        "type": "Microsoft.Network/networkProfiles/containerNetworkInterfaces"
      },
      {
        "container": {
          "id": "***",
          "resourceGroup": "myresourcegroup"
        },
        "containerNetworkInterfaceConfiguration": {
          "containerNetworkInterfaces": null,
          "etag": null,
          "id": "***",
          "ipConfigurations": null,
          "name": null,
          "provisioningState": null,
          "resourceGroup": "myresourcegroup",
          "type": null
        },
        "etag": "W/\"f993fb7a-d846-48f4-9fb7-4cc70b9f8691\"",
        "id": "***",
        "ipConfigurations": [],
        "name": "63beb899-e461-4a7b-a70e-20e9fc4ccd40_ci_subnet_cni",
        "provisioningState": "Succeeded",
        "resourceGroup": "myresourcegroup",
        "type": "Microsoft.Network/networkProfiles/containerNetworkInterfaces"
      }
    ],
    "etag": "W/\"f993fb7a-d846-48f4-9fb7-4cc70b9f8691\"",
    "id": "***",
    "location": "westeurope",
    "name": "profilename",
    "provisioningState": "Succeeded",
    "resourceGroup": "myresourcegroup",
    "resourceGuid": "***",
    "tags": {},
    "type": "Microsoft.Network/networkProfiles"
  }
]
```

**Comment by davehcdn** [comment]
We experienced the same thing today.  If you try with --debug and --verbose you might be able to track the course of actions / API calls which may reveal why there is this conflict.

Obviously a bug.

**Comment by yonzhan** [comment]
container

**Comment by czmirek** [comment]
I've run the command with `--debug` and `--verbose` and it seems that this is might be the same bug as #16735 but I can't really tell. This is the output.

```
```
cli.knack.cli: Command arguments: ['container', 'create', '--resource-group', 'mb-dev-rg', '--ip-address', 'Private', '--name', 'testcli', '--image', 'nginx', '--network-profile', 'mfd_tom_devops_container_network_profile', '--debug', '--verbose']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0338BB70>, <function OutputProducer.on_global_arguments at 0x03528030>, <function CLIQuery.on_global_arguments at 0x0353EF60>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'container': ['azure.cli.command_modules.container']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: container                 0.004         1        11
cli.azure.cli.core: Total (1)                 0.004         1        11
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 11 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : container create
cli.azure.cli.core: Command table: container create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0376B150>]
az_command_data_logger: command args: container create --resource-group {} --ip-address {} --name {} --image {} --network-profile {} --debug --verbose
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Mirek\.azure\commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x037C4BB8>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x037C4A50>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x037C4CD8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x037D1300>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03528078>, <function CLIQuery.handle_query_parameter at 0x0353EFA8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x037C4A08>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x037D12B8>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': 'REDACTED'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'container create'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--resource-group --ip-address --name --image --network-profile --debug --verbose'
cli.azure.cli.core.adal_authentication: AdalAuthentication.signed_session invoked by Track 1 SDK
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file C:\Users\Mirek\.azure\accessTokens.json as utf-8-sig
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - Authority:Performing instance discovery: ...
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - Authority:Performing static instance discovery
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - Authority:Authority validated via static instance discovery
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - TokenRequest:Getting token with client credentials.
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - TokenRequest:No user_id passed for cache query
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - CacheDriver:Found 0 potential entries.
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /REDACTED/oauth2/token HTTP/1.1" 200 1466
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - OAuth2Client:Get Token Server returned this correlation_id: ba2279de-64ed-4b3d-b152-375b0926cc42
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - CacheDriver:Adding entry AccessTokenId: REDACTED
adal-python: ba2279de-64ed-4b3d-b152-375b0926cc42 - CacheDriver:Added entry is MRRT
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/REDACTED/resourcegroups/mb-dev-rg?api-version=2020-10-01'
msrest.http_logger: Request method: 'GET'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'User-Agent': 'python/3.6.8 (Windows-10-10.0.19041-SP0) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python AZURECLI/2.18.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/REDACTED/resourcegroups/mb-dev-rg?api-version=2020-10-01 HTTP/1.1" 200 279
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
msrest.http_logger:     'x-ms-request-id': '5519ee56-aa7b-478d-8c94-9c80d2c22105'
msrest.http_logger:     'x-ms-correlation-request-id': '5519ee56-aa7b-478d-8c94-9c80d2c22105'
msrest.http_logger:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20210204T140709Z:5519ee56-aa7b-478d-8c94-9c80d2c22105'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Thu, 04 Feb 2021 14:07:08 GMT'
msrest.http_logger:     'Content-Length': '279'
msrest.http_logger: Response content:
msrest.http_logger: {"id":"/subscriptions/REDACTED/resourceGroups/mb-dev-rg","name":"mb-dev-rg","type":"Microsoft.Resources/resourceGroups","location":"westeurope","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.commands.validators: using location 'westeurope' from resource group 'mb-dev-rg'
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 647, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\invocation.py", line 115, in _validation
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 855, in _validate_arg_level
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\container\_validators.py", line 86, in validate_network_profile
knack.util.CLIError: Can not use "--network-profile" with IP address type "Public".

cli.azure.cli.core.azclierror: Can not use "--network-profile" with IP address type "Public".
cli.azure.cli.core.azclierror: Can not use "--network-profile" with IP address type "Public".
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0376B270>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.295 seconds (init: 0.157, invoke: 1.138)
telemetry.save: Save telemetry record of length 3118 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\Mirek\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
``````

**Comment by AAdamCCox** [comment]
Getting the same issue here, which is a shame because using an ARM template for this is a real pain :(

**Comment by davehcdn** [comment]
Just remove the --ip-address Private if you are specifying a Network Profile and it should create it with a private IP anyways - that might be a workaround - it seemed to work for us.

**Comment by AAdamCCox** [comment]
Thanks @davehcdn you're right, created successfully now!

**Comment by bd-clara** [comment]
Can we get a fix for this ?
