### ISSUE TITLE
az ad app - CLIInternalError on adding Graph permissions

### ISSUE THREAD

**Issue by joshhighet** [Azure/azure-cli#16868]
## Adding MS Graph Permissions causing `CLIInternalError`

`ValueError: not enough values to unpack`

**Command Name**
```
az ad app permission add \
--id *id* \
--api 00000003-0000-0000-c000-000000000000 \
--api-permissions Directory.Read.All
```

**Errors:**

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 714, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.18.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/custom.py", line 935, in add_permission
    access_id, access_type = e.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Executing the command above results in the above error.

## Environment Summary
```
macOS-11.2-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.18.0 *

Extensions:
logic 0.1.0
application-insights 0.1.9

```

**Comment by yonzhan** [comment]
Graph

**Comment by joshhighet** [comment]
happy birthday #16868  🥳🙌🎂 🍰🎈🎉 🎁

**Comment by jiasli** [comment]
You have provided incorrect value for `--api-permissions`. Please see the help message with `az ad app permission add --help` or check https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az-ad-app-permission-add.
