### ISSUE TITLE
az login fails

### ISSUE THREAD

**Issue by wpoely86** [Azure/azure-cli#16873]
## Describe the bug

Run on Fedora 33 with the new 2.19.

**Command Name**
`az login`

**Errors:**
```
cannot import name 'ARMHttpLoggingPolicy' from 'azure.mgmt.core.policies' (/usr/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
core/vendored_sdks/subscriptions/_subscription_client.py, ln 17, in <module>
    from ._configuration import SubscriptionClientConfiguration
core/vendored_sdks/subscriptions/_configuration.py, ln 15, in <module>
    from azure.mgmt.core.policies import ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMHttpLoggingPolicy' from 'azure.mgmt.core.policies' (/usr/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.10.13-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.1
Installer: RPM

azure-cli 2.19.0

```

**Comment by wpoely86** [comment]
After removing `python3-azure-sdk-5.0.0-3.fc33.noarch`, it works again.

Seems like a conflict. This RPM installs under a `az` subdir instead of properly into the python3 tree?

**Comment by yonzhan** [comment]
Account

**Comment by anjani40612000** [comment]
Hi i am getting below error for az login.  Below is my azure cli version installed.

C:\Users>az -v
azure-cli                         2.19.1 *

core                              2.19.1 *
telemetry                          1.0.6

The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.core.vendored_sdks.subscriptions.v2019_11_01.operations._subscription_client_operations'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 664, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 727, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 720, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 698, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\commands\__init__.py", line 331, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py", line 816, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-7as_bwui\azure\cli\command_modules\profile\custom.py", line 162, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 204, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 892, in find_through_interactive_flow
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\_profile.py", line 925, in _find_using_common_tenant
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\_subscription_client.py", line 160, in tenants
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\__init__.py", line 9, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\_subscription_client.py", line 21, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-8u6uejh7\azure\cli\core\vendored_sdks\subscriptions\v2019_11_01\operations\__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'azure.cli.core.vendored_sdks.subscriptions.v2019_11_01.operations._subscription_client_operations'

**Comment by MaddyMicrosoft** [comment]
The import/module errors in this thread are local install and packaging conflicts rather than CLI code bugs (on Fedora, the distro python3-azure-sdk RPM shadowing the pip packages; on Windows, a corrupted or partial install). A clean reinstall of the CLI should resolve them, and the vendored SDK layer these errors touch has since been rewritten, so they don't occur on current CLI. Closing on that basis; if this recurs on a clean install of the latest CLI, please open a fresh issue.
