### ISSUE TITLE
az login fails with ECONNRESET

### ISSUE THREAD

**Issue by ThoughtHopper** [Azure/azure-cli#16942]
**Describe the bug**
Running `az login` on WSL2 fails with 'Connection aborted' after choosing user in the browser.

**Environment summary**
Host:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362

Guest:
Ubuntu 18.04 LTS
Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Tool:
azure-cli                         2.19.1
core                              2.19.1
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Feb 10 2021, 05:17:43)
[GCC 7.5.0]

**Additional context**
Running it with the --debug flag
```
cli.azure.cli.core._profile: You have logged in. Now let us find all the subscriptions to which you have access...
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
azure.core.pipeline.policies._universal: Request method: 'GET'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': 'e468b4fc-6fcc-11eb-8ac3-00155d2cdc23'
azure.core.pipeline.policies._universal:     'CommandName': 'login'
azure.core.pipeline.policies._universal:     'ParameterSetName': '--debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.19.1 (DEB) azsdk-python-azure-mgmt-resource/0.1.0 Python/3.6.10 (Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
.......
urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
.......
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
.......
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  ....
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 284, in send
    raise error
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))

cli.azure.cli.core.azclierror: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
cli.azure.cli.core.azclierror: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f6245f2d840>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 13.394 seconds (init: 0.086, invoke: 13.308)
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 509, in get_current_account_user
    active_account = self.get_subscription()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 518, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 57, in _decorator
    val = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 530, in _get_user_azure_id
    return _get_profile().get_current_account_user()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 511, in get_current_account_user
    raise CLIError('There are no active accounts.')
knack.util.CLIError: There are no active accounts.

cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 540, in _get_azure_subscription_id
    return _get_profile().get_subscription_id()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 535, in get_subscription_id
    return self.get_subscription(subscription)[_SUBSCRIPTION_ID]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 518, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.
```

**Other comments**

I've tried with the --use-device-code and it does not work either. Similar error.

**Comment by yonzhan** [comment]
Account

**Comment by ThoughtHopper** [comment]
Workaround found.

Using a proxy as instructed here:
https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy
With HTTPS_PROXY environment variable set.

This leads me to believe that there is a problem with the WSL environment.
I used Wireshark and when the error occurs its the management.azure.com server that closes the connection.
Unfortunately I can't easily see the request without a proxy.

**Comment by ThoughtHopper** [comment]
I have 'az' installed in my Host machine. It seems that installing it in the WSL leads to some issues.

I uninstalled the azure-cli package from WSL. It automatically defaulted to use the one from Windows
*(/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az)* and all my login problems went away...

**Comment by jiasli** [comment]
Hi @ThoughtHopper, do you have a proxy setup in WSL? Azure CLI should work with WSL correctly when there is no proxy.

Also, can you reach `https://management.azure.com/` directly without using `az`?

```sh
$ /opt/az/bin/python3 -c "import requests; print(requests.get('https://management.azure.com/').status_code)"
400
```
