### ISSUE TITLE
Internal server error when performing ARO creation. 

### ISSUE THREAD

**Issue by danielpenagos** [Azure/azure-cli#16963]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
We are creating a new private cluster and we are getting an internal server error. 

**To Reproduce**
The same as available at https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster

**Expected behavior**
Cluster created successfully.

**Environment summary**
Neither azure cli from the azure portal, or azure cli locally worked. 

**Additional context**
az aro create --resource-group $RESOURCEGROUP --name $CLUSTER --vnet $VNET --master-subnet $MASTER_SUBNET --worker-subnet $WORKER_SUBNET --apiserver-visibility Private --ingress-visibility Private --location $LOCATION --domain $DOMAIN

msrest.service_client: Accept header absent and forced to application/json
cli.azure.cli.core.adal_authentication: AdalAuthentication.signed_session invoked by Track 1 SDK
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4283
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {​​​​​​​​​​​​​​​'resource': 'https://management.core.windows.net/'}​​​​​​​​​​​​​​​
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4283
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {​​​​​​​​​​​​​​​'resource': 'https://management.core.windows.net/'}​​​​​​​​​​​​​​​
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6?api-version=2020-04-30'
msrest.http_logger: Request method: 'GET'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'x-ms-client-request-id': '6aad581a-7158-11eb-9935-0a580af4ab99'
msrest.http_logger:     'User-Agent': 'python/3.6.10 (Linux-4.15.0-1106-azure-x86_64-with-debian-10.2) msrest/0.6.18 cloud-shell/1.0 msrest_azure/0.6.3 azure-mgmt-redhatopenshift/0.1.0 Azure-SDK-For-Python AZURECLI/2.19.0 (DEB)'
msrest.http_logger: Request body:
msrest.http_logger: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6?api-version=2020-04-30 HTTP/1.1" 200 None
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Transfer-Encoding': 'chunked'
msrest.http_logger:     'Content-Type': 'application/json'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'X-Ms-Request-Id': '2461f4b1-ffae-4728-8a1f-1c97b5b17ca9'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11983'
msrest.http_logger:     'x-ms-correlation-request-id': 'e2ce9a1d-6cba-49c0-ba6d-aba5613b87df'
msrest.http_logger:     'x-ms-routing-request-id': 'EASTUS:20210217T194838Z:e2ce9a1d-6cba-49c0-ba6d-aba5613b87df'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Wed, 17 Feb 2021 19:48:38 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {​​​​​​​​​​​​​​​
    "id": "/subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6",
    "name": "6edec432-692d-49ad-88bc-89dc8ccde6b6",
    "status": "Creating",
    "startTime": "2021-02-17T19:43:37.820477429Z"
}​​​​​​​​​​​​​​​

msrest.service_client: Accept header absent and forced to application/json
cli.azure.cli.core.adal_authentication: AdalAuthentication.signed_session invoked by Track 1 SDK
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4283
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {​​​​​​​​​​​​​​​'resource': 'https://management.core.windows.net/'}​​​​​​​​​​​​​​​
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 4283
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {​​​​​​​​​​​​​​​'resource': 'https://management.core.windows.net/'}​​​​​​​​​​​​​​​
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6?api-version=2020-04-30'
msrest.http_logger: Request method: 'GET'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'x-ms-client-request-id': '6aad581a-7158-11eb-9935-0a580af4ab99'
msrest.http_logger:     'User-Agent': 'python/3.6.10 (Linux-4.15.0-1106-azure-x86_64-with-debian-10.2) msrest/0.6.18 cloud-shell/1.0 msrest_azure/0.6.3 azure-mgmt-redhatopenshift/0.1.0 Azure-SDK-For-Python AZURECLI/2.19.0 (DEB)'
msrest.http_logger: Request body:
msrest.http_logger: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6?api-version=2020-04-30 HTTP/1.1" 200 None
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Transfer-Encoding': 'chunked'
msrest.http_logger:     'Content-Type': 'application/json'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'X-Ms-Request-Id': '6b1f9997-b728-4586-9006-e0d547bd184d'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11982'
msrest.http_logger:     'x-ms-correlation-request-id': 'cba2141b-e9fc-4874-bad4-45e4e932ff2f'
msrest.http_logger:     'x-ms-routing-request-id': 'EASTUS:20210217T194908Z:cba2141b-e9fc-4874-bad4-45e4e932ff2f'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Wed, 17 Feb 2021 19:49:07 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {​​​​​​​​​​​​​​​
    "id": "/subscriptions/9903d123-7039-4e81-89ac-c0868612d6b8/providers/microsoft.redhatopenshift/locations/eastus2/operationsstatus/6edec432-692d-49ad-88bc-89dc8ccde6b6",
    "name": "6edec432-692d-49ad-88bc-89dc8ccde6b6",
    "status": "Failed",
    "startTime": "2021-02-17T19:43:37.820477429Z",
    "endTime": "2021-02-17T19:48:38.984016351Z",
    "error": {​​​​​​​​​​​​​​​
        "code": "InternalServerError",
        "message": "Internal server error."
    }​​​​​​​​​​​​​​​
}​​​​​​​​​​​​​​​

msrest.exceptions: Internal server error.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 390, in run
    self._poll()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 418, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.polling.arm_polling.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 989, in __call__
    result = poller.result()
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 183, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 201, in wait
    raise self._exception  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 152, in _start
    self._polling_method.run()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 400, in run
    raise CloudError(self._response)
msrestazure.azure_exceptions.CloudError: Azure Error: InternalServerError
Message: Internal server error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {​​​​​​​​​​​​​​​}​​​​​​​​​​​​​​​'.format(cmd_copy.name))(result)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 993, in __call__
    handle_long_running_operation_exception(client_exception)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 134, in handle_long_running_operation_exception
    raise cli_error
knack.util.CLIError: Deployment failed. Correlation ID: cba2141b-e9fc-4874-bad4-45e4e932ff2f. Internal server error.

cli.azure.cli.core.azclierror: Deployment failed. Correlation ID: cba2141b-e9fc-4874-bad4-45e4e932ff2f. Internal server error.
cli.azure.cli.core.azclierror: Deployment failed. Correlation ID: cba2141b-e9fc-4874-bad4-45e4e932ff2f. Internal server error.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f25dbe8d840>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 337.178 seconds (init: 0.121, invoke: 337.057)
telemetry.save: Save telemetry record of length 6720 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/csanchdi/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by yonzhan** [comment]
aro

**Comment by mjudeikis** [comment]
@danielpenagos Thanks for this! We checked logs and we see some issues with Worker pool Subnet CIRD.
Can you please share you subnet definition here so we can identify code fix? Our code was not able to find CIDR assigned to worker subnet and errored. I dont quite understan how this could happen in the first place.  

If you not comfortable sharing vnet/subnet json here, please raise incident with MSFT and ask to forward "directly to ARO SRE (not CEE)" with this issue reference. Thanks!!

**Comment by mbifeld** [comment]
Closing as no response from the original author, and it seems the follow-up question about more detailed InternalServerErrors has been answered.
