### ISSUE TITLE
Do not understand Python error from functionapp script

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Azure/azure-cli#17041]
## Describe the bug

Trying to use the script in this sample : https://github.com/mspnp/cloud-design-patterns/tree/master/claim-check/code-samples/sample-1 but its failing at the `config-zip` step with an error I do not understand.

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
config-zip: functionapp deployment source asccuccfunctionapp
WARNING: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
WARNING: Waiting SCM site to be updated with the latest app settings
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: HTTPSConnectionPool(host='asccuccfunctionapp.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.8/3.8.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.8/3.8.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.8/3.8.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.8/3.8.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='asccuccfunctionapp.scm.azurewebsites.net', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 698, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 816, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 389, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 519, in remove_remote_build_app_settings
    scm_is_up_to_date = validate_app_settings_in_scm(
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 995, in validate_app_settings_in_scm
    scm_settings = _get_app_settings_from_scm(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/utils.py", line 66, in call
    raise exception
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/utils.py", line 62, in call
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 1024, in _get_app_settings_from_scm
    response = requests.get(settings_url, headers=headers, auth=(username, password), timeout=3)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --name {} --resource-group {} --src {} -o {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.19.1

Extensions:
storage-preview 0.2.9
eventgrid 0.4.9

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of azure cli [> 2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
