### ISSUE TITLE
Trying to create a dynamic monitor metric alert returns The api-version '2018-03-01' is invalid on MacOS version 2.19.1

### ISSUE THREAD

**Issue by gabriel-kohen-by** [Azure/azure-cli#17099]
## Describe the bug
Trying to create a dynamic metric alerts fails on API version error

**Command Name**
`az monitor metrics alert create`

**Errors:**
```
(InvalidApiVersionParameter) The api-version '2018-03-01' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

## To Reproduce:
* Set the envs variables. 
* Run:
```
az monitor metrics alert create --name "${AZURE_APP_ENV_NAME}-500-errors-alert" --resource-group "${RESOURCE_GROUP}" \
    --scopes "${webappResourceId}" \
    --condition "total microsoft.web/sites.http5xx > dynamic high 3 of 4" \
    --evaluation-frequency 5m \
    --window-size 5m \
    --severity 2 \
    --action "${myActionGroupId}" \
    --description "${AZURE_APP_ENV_NAME} 500 Errors"
```
- _Put any pre-requisite steps here..._
- Set your `RESOURCE_GROUP` , `webappResourceId`, `myActionGroupId`, 'AZURE_APP_ENV_NAME' environment variables.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.19.1

Extensions:
logic 0.1.2
application-insights 0.1.13

```

**Comment by kairu-ms** [comment]
Hi @gabriel-kohen-by. I cannot reproduce your question. Can you run command
```
az cloud set -n AzureCloud --profile latest -h
```
And try again?

**Comment by gabriel-kohen-by** [comment]
@kairu-ms , do you mean `az cloud set -n AzureCloud --profile latest` ? What you had specified is giving the help for the command.
`az cloud show` outputs:
```
{
  "endpoints": {
    "activeDirectory": "https://login.microsoftonline.com",
    "activeDirectoryDataLakeResourceId": "https://datalake.azure.net/",
    "activeDirectoryGraphResourceId": "https://graph.windows.net/",
    "activeDirectoryResourceId": "https://management.core.windows.net/",
    "appInsightsResourceId": "https://api.applicationinsights.io",
    "appInsightsTelemetryChannelResourceId": "https://dc.applicationinsights.azure.com/v2/track",
    "attestationResourceId": "https://attest.azure.net",
    "batchResourceId": "https://batch.core.windows.net/",
    "gallery": "https://gallery.azure.com/",
    "logAnalyticsResourceId": "https://api.loganalytics.io",
    "management": "https://management.core.windows.net/",
    "mediaResourceId": "https://rest.media.azure.net",
    "microsoftGraphResourceId": "https://graph.microsoft.com/",
    "ossrdbmsResourceId": "https://ossrdbms-aad.database.windows.net",
    "portal": "https://portal.azure.com",
    "resourceManager": "https://management.azure.com/",
    "sqlManagement": "https://management.core.windows.net:8443/",
    "synapseAnalyticsResourceId": "https://dev.azuresynapse.net",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json"
  },
  "isActive": true,
  "name": "AzureCloud",
  "profile": "latest",
  "suffixes": {
    "acrLoginServerEndpoint": ".azurecr.io",
    "attestationEndpoint": ".attest.azure.net",
    "azureDatalakeAnalyticsCatalogAndJobEndpoint": "azuredatalakeanalytics.net",
    "azureDatalakeStoreFileSystemEndpoint": "azuredatalakestore.net",
    "keyvaultDns": ".vault.azure.net",
    "mariadbServerEndpoint": ".mariadb.database.azure.com",
    "mhsmDns": ".managedhsm.azure.net",
    "mysqlServerEndpoint": ".mysql.database.azure.com",
    "postgresqlServerEndpoint": ".postgres.database.azure.com",
    "sqlServerHostname": ".database.windows.net",
    "storageEndpoint": "core.windows.net",
    "storageSyncEndpoint": "afs.azure.net",
    "synapseAnalyticsEndpoint": ".dev.azuresynapse.net"
  }
}
``` 
The debug of my `alert` command is. Please advise:
```
cli.knack.cli: Command arguments: ['monitor', 'metrics', 'alert', 'create', '--name', 'byconfservicepltna-500-errors-alert', '--resource-group', '', '--scopes', '/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/Microsoft.Web/sites/bydashservicepltna', '--condition', 'total microsoft.web/sites.http5xx > dynamic high 3 of 4', '--evaluation-frequency', '5m', '--window-size', '5m', '--severity', '2', '--action', '/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/microsoft.insights/actionGroups/lui-portal-core', '--description', 'byconfservicepltna 500 Errors', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105810160>, <function OutputProducer.on_global_arguments at 0x105888310>, <function CLIQuery.on_global_arguments at 0x1058ceaf0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'monitor': ['azure.cli.command_modules.monitor', 'azext_applicationinsights']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: monitor                   0.007        32       132
cli.azure.cli.core: Total (1)                 0.007        32       132
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: application-insights      0.003         9        24  /Users/gabrielkohen/.azure/cliextensions/application-insights
cli.azure.cli.core: Total (1)                 0.003         9        24  
cli.azure.cli.core: Loaded 40 groups, 156 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : monitor metrics alert create
cli.azure.cli.core: Command table: monitor metrics alert create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x105e3e0d0>]
az_command_data_logger: command args: monitor metrics alert create --name {} --resource-group {} --scopes {} --condition {} --evaluation-frequency {} --window-size {} --severity {} --action {} --description {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/gabrielkohen/.azure/commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x105e7caf0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x105ed5700>]
cli.knack.commands: Configured default 'rg-by-lui-shared-test-eus2-01' for arg resource_group_name
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x105ed5790>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x105ed58b0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1058883a0>, <function CLIQuery.handle_query_parameter at 0x1058ceb80>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x105ec2dc0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x105ed5820>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=MonitorManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /Users/gabrielkohen/.azure/accessTokens.json as utf-8-sig
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - Authority:Performing instance discovery: ...
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - Authority:Performing static instance discovery
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - Authority:Authority validated via static instance discovery
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - TokenRequest:Getting token with client credentials.
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - TokenRequest:No user_id passed for cache query
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - CacheDriver:Found 0 potential entries.
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /c9536685-1262-420b-a94b-4f5420284680/oauth2/token HTTP/1.1" 200 1533
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - OAuth2Client:Get Token Server returned this correlation_id: c8ae6c79-4022-4b16-a974-6f54a9f739f9
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - CacheDriver:Adding entry AccessTokenId: b'm1hQJ1CxDjX2dfqAU7y/WoVlznQAyxCebLVa564kGPI='
adal-python: c8ae6c79-4022-4b16-a974-6f54a9f739f9 - CacheDriver:Added entry is MRRT
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups//providers/Microsoft.Insights/metricAlerts/byconfservicepltna-500-errors-alert?api-version=2018-03-01'
azure.core.pipeline.policies._universal: Request method: 'PUT'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json'
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'Content-Length': '947'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': '09fa6396-7a86-11eb-8fcd-3af9d3de94e2'
azure.core.pipeline.policies._universal:     'CommandName': 'monitor metrics alert create'
azure.core.pipeline.policies._universal:     'ParameterSetName': '--name --resource-group --scopes --condition --evaluation-frequency --window-size --severity --action --description --debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.19.1 (HOMEBREW) azsdk-python-azure-mgmt-monitor/2.0.0 Python/3.8.8 (macOS-10.15.7-x86_64-i386-64bit)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: {"location": "global", "properties": {"description": "byconfservicepltna 500 Errors", "severity": 2, "enabled": true, "scopes": ["/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/Microsoft.Web/sites/bydashservicepltna"], "evaluationFrequency": "PT5M", "windowSize": "PT5M", "criteria": {"odata.type": "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria", "allOf": [{"criterionType": "DynamicThresholdCriterion", "name": "cond0", "metricName": "http5xx", "metricNamespace": "microsoft.web/sites", "timeAggregation": "Total", "dimensions": [], "operator": "GreaterThan", "alertSensitivity": "High", "failingPeriods": {"numberOfEvaluationPeriods": 4.0, "minFailingPeriodsToAlert": 3.0}}]}, "actions": [{"actionGroupId": "/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/microsoft.insights/actionGroups/lui-portal-core"}]}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups//providers/Microsoft.Insights/metricAlerts/byconfservicepltna-500-errors-alert?api-version=2018-03-01 HTTP/1.1" 400 597
azure.core.pipeline.policies._universal: Response status: 400
azure.core.pipeline.policies._universal: Response headers:
azure.core.pipeline.policies._universal:     'Cache-Control': 'no-cache'
azure.core.pipeline.policies._universal:     'Pragma': 'no-cache'
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json; charset=utf-8'
azure.core.pipeline.policies._universal:     'Expires': '-1'
azure.core.pipeline.policies._universal:     'x-ms-failure-cause': 'gateway'
azure.core.pipeline.policies._universal:     'x-ms-request-id': 'feed66bd-e2da-44d9-85fe-d38b4946f94f'
azure.core.pipeline.policies._universal:     'x-ms-correlation-request-id': 'feed66bd-e2da-44d9-85fe-d38b4946f94f'
azure.core.pipeline.policies._universal:     'x-ms-routing-request-id': 'CANADAEAST:20210301T120248Z:feed66bd-e2da-44d9-85fe-d38b4946f94f'
azure.core.pipeline.policies._universal:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
azure.core.pipeline.policies._universal:     'X-Content-Type-Options': 'nosniff'
azure.core.pipeline.policies._universal:     'Date': 'Mon, 01 Mar 2021 12:02:48 GMT'
azure.core.pipeline.policies._universal:     'Content-Length': '597'
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2018-03-01' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 719, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 698, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 816, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/monitor/operations/metric_alert.py", line 62, in create_metric_alert
    return client.create_or_update(resource_group_name, rule_name, MetricAlertResource(**kwargs))
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/mgmt/monitor/v2018_03_01/operations/_metric_alerts_operations.py", line 306, in create_or_update
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2018-03-01' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

cli.azure.cli.core.azclierror: (InvalidApiVersionParameter) The api-version '2018-03-01' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
cli.azure.cli.core.azclierror: (InvalidApiVersionParameter) The api-version '2018-03-01' is invalid. The supported versions are '2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x105e3e310>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.039 seconds (init: 0.079, invoke: 0.959)
telemetry.save: Save telemetry record of length 3795 in cache
telemetry.check: Negative: The /Users/gabrielkohen/.azure/telemetry.txt was modified at 2021-03-01 06:57:20.369101, which in less than 600.000000 s
```

**Comment by kairu-ms** [comment]
Hi @gabriel-kohen-by, thanks to provide the debug information. I find that the value of --resource-group is an empty string in the debug log.
```
cli.knack.cli: Command arguments: ['monitor', 'metrics', 'alert', 'create', '--name', 'byconfservicepltna-500-errors-alert', '--resource-group', '', '--scopes', '/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/Microsoft.Web/sites/bydashservicepltna', '--condition', 'total microsoft.web/sites.http5xx > dynamic high 3 of 4', '--evaluation-frequency', '5m', '--window-size', '5m', '--severity', '2', '--action', '/subscriptions/ad1e9f34-2525-4721-8777-445d89a891c7/resourceGroups/rg-by-lui-shared-test-eus2-01/providers/microsoft.insights/actionGroups/lui-portal-core', '--description', 'byconfservicepltna 500 Errors', '--debug']
```
 I think that cause the problem. Can you try again?

**Comment by gabriel-kohen-by** [comment]
That indeed was the issue @kairu-ms. Thank you. On a side note it's worth adding a warning to the command about the RG missing rather than give a, bit misleading, API version error.
Appreciate the great product. This issue can be closed.
