### ISSUE TITLE
WebApp:Serialization issue with az webapp config access-restriction add

### ISSUE THREAD

**Issue by designerfh** [Azure/azure-cli#17135]
## Describe the bug

**Command Name**
`az webapp config access-restriction add`

**Errors:**
```
'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
Traceback (most recent call last):
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 987, in serialize_enum
enum.py, ln 293, in __call__
enum.py, ln 535, in __new__
enum.py, ln 548, in _missing_
ValueError: 'ServiceTag' is not a valid IpFilterTag

...

Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 771, in serialize_data
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 994, in serialize_enum
msrest.exceptions.SerializationError: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config access-restriction add --resource-group {} --name {} --action {} --description {} --rule-name {} --ip-address {} --priority {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
aks-preview 0.5.0
front-door 1.0.11
storage-preview 0.7.0
webapp 0.3.1

```
## Additional Context
This is reproducible when using the ServiceTag preview functionality. Add a ServiceTag access restriction through the Azure Portal or via ARM Template.  Once you have a ServiceTag based access-restriction added to the webapp, the az webapp config access-restriction commands throw serialization errors. See Issue #16559 also.

**Comment by panchagnula** [comment]
@madsd  do you have an idea art this - is this because Service Tag support is currently not available on SDK version of Python used on CLI?

**Comment by madsd** [comment]
@panchagnula Yes, ServiceTag is missing in the IpFilterTag enum in the current SDK.

**Comment by vachillo** [comment]
also seeing this same error when calling `az functionapp config container set --docker-custom-image-name <image>`

full stack trace:
```
The command failed with an unexpected error. Here is the traceback:

'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
ValueError: 'ServiceTag' is not a valid IpFilterTag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 987, in serialize_enum
    enum_obj(result)
  File "/tools/azurecli/python/python3.7/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/tools/azurecli/python/python3.7/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/tools/azurecli/python/python3.7/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/tools/azurecli/python/python3.7/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'ServiceTag' is not a valid IpFilterTag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 545, in default_command_handler
    return op(**command_args)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1176, in update_container_settings_functionapp
    multicontainer_config_file=None, slot=slot)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1151, in update_container_settings
    _add_fx_version(cmd, resource_group_name, name, docker_custom_image_name, slot)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 908, in _add_fx_version
    linux_fx_version=linux_fx, windows_fx_version=windows_fx, slot=slot)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1004, in update_site_configs
    return _generic_site_operation(cmd.cli_ctx, resource_group_name, name, 'update_configuration', slot, configs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/cli/command_modules/appservice/_appservice_utils.py", line 17, in _generic_site_operation
    name, extra_parameter))
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/azure/mgmt/web/v2019_08_01/operations/_web_apps_operations.py", line 2843, in update_configuration
    body_content = self._serialize.body(site_config, 'SiteConfigResource')
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 629, in body
    return self._serialize(data, data_type, **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 484, in _serialize
    target_obj, data_type, **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 783, in serialize_data
    return self._serialize(data, **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 776, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 860, in serialize_iter
    serialized.append(self.serialize_data(d, iter_type, **kwargs))
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 783, in serialize_data
    return self._serialize(data, **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 771, in serialize_data
    return Serializer.serialize_enum(data, enum_obj=enum_type)
  File "/tools/azurecli/azurecli-2.17.1/env-2.17.1/lib/python3.7/site-packages/msrest/serialization.py", line 994, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
```
