### ISSUE TITLE
Error during az storage container generate-sas: self.account_key should not be None 

### ISSUE THREAD

**Issue by adiun** [Azure/azure-cli#17176]
## Describe the bug

**Command Name**
```
end=`date -d "5 minutes" '+%Y-%m-%dT%H:%M:%SZ'`
`az storage container generate-sas -n '$web' --account-name $1 --https-only --permissions dlrw --expiry $end -otsv`
```

Note this command is being run in Azure Pipelines (see below for repro steps)

**Errors:**
```
WARNING: There are no credentials provided in your command and environment, we will query for the account key inside your storage account. 
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: self.account_key should not be None.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 719, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 338, in new_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 698, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 816, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 666, in generate_container_shared_access_signature
    user_delegation_key=user_delegation_key)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 421, in generate_container_shared_access_signature
    _validate_not_none('self.account_key', self.account_key)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_error.py", line 130, in _validate_not_none
    raise ValueError(_ERROR_VALUE_NONE.format(param_name))
ValueError: self.account_key should not be None.
To open an issue, please run: 'az feedback'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Create an Azure DevOps Pipeline that uses a stage like this:

```yaml
parameters:
  - name: appStorageAccountName
    type: string
  - name: azureSubscription
    type: string

stages:
  - stage: Deploy
    displayName: Deploy Artifacts
    jobs:
      - deployment: Deploy
        environment: Dev
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: ${{parameters.azureSubscription}}
                    scriptLocation: inlineScript
                    scriptType: bash
                    inlineScript: |
                      end=`date -d "5 minutes" '+%Y-%m-%dT%H:%M:%SZ'`
                      sas=`az storage container generate-sas -n '$web' --account-name $1 --https-only --permissions dlrw --expiry $end -otsv`
                    arguments: ${{parameters.appStorageAccountName}}
                  displayName: Generate SAS
```

## Expected Behavior

No error. This was passing 3 hours ago for us and now it is failing consistently. Output still contains the warning, but it succeeded with no `ERROR`s:

```
WARNING: There are no credentials provided in your command and environment, we will query for the account key inside your storage account. 
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
```

## Environment Summary
Azure Pipelines hosted agent `ubuntu-latest`

Details from `az-version`:
```
azure-cli                         2.19.1 *

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

core                              2.19.1 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.6.10 (default, Feb 10 2021, 05:17:27) 
[GCC 9.3.0]
```

**Comment by adiun** [comment]
Note, I was able to install a newer version `2.20.0` in the Azure Pipelines hosted agent via:

```bash
sudo apt-get update
sudo apt install -y --allow-downgrades azure-cli=2.20.0-1~focal
```

However this didn't fix the issue.

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @adiun. Thanks for reaching out to us.

As you can see from the `WARNING` message, we will query for the `account key` inside your storage account as only `account name` is provided and the storage server need credentials to authenticate. If we can't succeed to query `account key` from the account name provided, then the command will fail.

Most likely `--account-name $1` reference some not existing storage account. Can you run `az storage account keys list --account-name $1` to check whether the account exist or not and whether querying `account key` succeed or not.

**Comment by bondib** [comment]
As I noted in #9346 -
I can verify this issue occurs when you try to run the command and your AZ is logged in to a different subscription than where your storage account is.
The thing is users do not understand why it suddenly occurs and why the command just stops working (and the error message is misleading).

I think the error message should be more descriptive (not just a key error failure) and say something like "Make sure you are logged in to the same subscription as your storage account is in"

**Comment by adiun** [comment]
Yes, the storage account didn't exist in that subscription which caused this error. Sorry for the delay in follow-up.

I totally agree with @bondib - the error message needs to be fixed since it made me think there was some internal error, especially since it contains:

```
ERROR: The command failed with an unexpected error. 
To open an issue, please run: 'az feedback'
```

**Comment by yonzhan** [comment]
@evelyn-ys will fix the error message in this sprint.

**Comment by evelyn-ys** [comment]
Thanks @bondib @adiun 
PR #17200 has added warning message like this:
```bash
> az storage container generate-sas --account-name notexist -n mycontainer
There are no credentials provided in your command and environment, we will query for the account key inside your storage account.
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli.
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.

Skip querying account key due to failure: Storage account 'notexist' not found.
The command failed with an unexpected error. Here is the traceback:
self.account_key should not be None.
Traceback (most recent call last):
```
