### ISSUE TITLE
az storage fs file list --recursive false error

### ISSUE THREAD

**Issue by Filip232** [Azure/azure-cli#17205]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to get a list of files in my blob storage with `az storage fs file list` command, and i dont want to list files from subdirectories, so i am using `--recursive false` flag and saving it to a file. When it is executing command on azure pipline with azure CLI (version 1, inline script) it says:

```
2021-03-04T12:14:12.5157760Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-03-04T12:14:12.5158869Z ERROR: strptime() argument 1 must be str, not None
2021-03-04T12:14:12.5159589Z Traceback (most recent call last):
2021-03-04T12:14:12.5161370Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
2021-03-04T12:14:12.5162619Z     cmd_result = self.invocation.execute(args)
2021-03-04T12:14:12.5163989Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
2021-03-04T12:14:12.5164836Z     raise ex
2021-03-04T12:14:12.5166102Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
2021-03-04T12:14:12.5167316Z     results.append(self._run_job(expanded_arg, cmd_copy))
2021-03-04T12:14:12.5168689Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
2021-03-04T12:14:12.5169567Z     return cmd_copy.exception_handler(ex)
2021-03-04T12:14:12.5170886Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 352, in new_handler
2021-03-04T12:14:12.5171701Z     raise ex
2021-03-04T12:14:12.5172906Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
2021-03-04T12:14:12.5173728Z     result = cmd_copy(params)
2021-03-04T12:14:12.5174992Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
2021-03-04T12:14:12.5176036Z     return self.handler(*args, **kwargs)
2021-03-04T12:14:12.5177364Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in default_command_handler
2021-03-04T12:14:12.5178239Z     return op(**command_args)
2021-03-04T12:14:12.5179629Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/fs_file.py", line 76, in list_fs_files
2021-03-04T12:14:12.5180502Z     result = next(pages)
2021-03-04T12:14:12.5181661Z   File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 84, in __next__
2021-03-04T12:14:12.5182605Z     self.continuation_token, self._current_page = self._extract_data(self._response)
2021-03-04T12:14:12.5184148Z   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 61, in _extract_data_cb
2021-03-04T12:14:12.5185205Z     self.current_page = [self._build_item(item) for item in self.path_list]
2021-03-04T12:14:12.5186801Z   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 61, in <listcomp>
2021-03-04T12:14:12.5187881Z     self.current_page = [self._build_item(item) for item in self.path_list]
2021-03-04T12:14:12.5189488Z   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 70, in _build_item
2021-03-04T12:14:12.5191017Z     path = PathProperties._from_generated(item)  # pylint: disable=protected-access
2021-03-04T12:14:12.5192587Z   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_models.py", line 215, in _from_generated
2021-03-04T12:14:12.5193853Z     path_prop.last_modified = datetime.strptime(generated.last_modified, "%a, %d %b %Y %H:%M:%S %Z")
2021-03-04T12:14:12.5194849Z TypeError: strptime() argument 1 must be str, not None
```
it was working until 10am (gmt+1) 4th march.

**To Reproduce**
create blob storage, create directory and subdirectory inside with some files, go to azure pipline create azure CLI task verion 1.0, inline script run command `az storage fs file list --account-name xxx --account-key yyy -f dir  --recursive false>list.txt`

`az storage blob upload --account-name xxx --account-key yyy -f list.txt -c dir -n list.txt`

**Expected behavior**
It should save a list of files and directories inside dir directory in a file called list.txt

**Environment summary**
Azure pipline release, 
agent job: ubuntu 16.04
task: azure CLI veriosn 1.0 inline script

**Additional context**
it was working until 10am (gmt+1) 4th march

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @Filip232, I cannot reproduce your issue. As you can see, I could list without expanding subfolder.
![image](https://user-images.githubusercontent.com/49508232/110563458-506f3c00-8186-11eb-96ea-b25728a2ac34.png)

May I know you azure cli version? and could you provide more information with `--debug` in your command?

**Comment by Juliehzl** [comment]
I am testing with latest azure cli.

**Comment by yonzhan** [comment]
Hi @Filip232, any update for debug info?

**Comment by alextmeyer** [comment]
I am hitting this as well with azure-cli version 2.21.0.

```
az storage fs file list --account-name <> --file-system <> --query '[].{datetime:lastModified, size:contentLength, file:name}' --recursive false
```

```
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/<>/resourceGroups/<>/providers/Microsoft.Storage/storageAccounts/<>/listKeys?api-version=2021-01-01&$expand=kerb HTTP/1.1" 200 None
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Request URL: 'https://<>.dfs.core.windows.net/<>?resource=filesystem&recursive=false&maxResults=5000'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Request method: 'GET'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Request headers:
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-version': '2020-02-10'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Accept': 'application/json'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'User-Agent': 'AZURECLI/2.21.0 (HOMEBREW) azsdk-python-storage-dfs/12.2.2 Python/3.8.8 (macOS-10.15.7-x86_64-i386-64bit)'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-client-request-id': '<<>>'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'CommandName': 'storage fs file list'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'ParameterSetName': '--account-name --file-system --query --recursive --debug'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-date': 'Tue, 06 Apr 2021 20:57:15 GMT'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Authorization': '<>'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Request body:
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: None
urllib3.connectionpool: Starting new HTTPS connection (1): <>.dfs.core.windows.net:443
urllib3.connectionpool: https://<>.dfs.core.windows.net:443 "GET /<>?resource=filesystem&recursive=false&maxResults=5000 HTTP/1.1" 200 None
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Response status: 200
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Response headers:
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Transfer-Encoding': 'chunked'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Content-Type': 'application/json;charset=utf-8'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Server': 'Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-request-id': '<<>>'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-version': '2020-02-10'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'x-ms-client-request-id': '<<>>'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies:     'Date': 'Tue, 06 Apr 2021 20:57:14 GMT'
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: Response content:
azure.multiapi.storagev2.filedatalake.v2020_02_10._shared.policies: {"paths":[{"isDirectory":"true","name":"<<>>"},{"isDirectory":"true","name":"<<>>"},{"isDirectory":"true","name":"<<>>"}]}

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 352, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/fs_file.py", line 76, in list_fs_files
    result = next(pages)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 61, in _extract_data_cb
    self.current_page = [self._build_item(item) for item in self.path_list]
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 61, in <listcomp>
    self.current_page = [self._build_item(item) for item in self.path_list]
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_list_paths_helper.py", line 70, in _build_item
    path = PathProperties._from_generated(item)  # pylint: disable=protected-access
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_models.py", line 215, in _from_generated
    path_prop.last_modified = datetime.strptime(generated.last_modified, "%a, %d %b %Y %H:%M:%S %Z")
TypeError: strptime() argument 1 must be str, not None
```

**Comment by Juliehzl** [comment]
@alextmeyer, are you using `az storage fs file list` to list on blob storage account?
`az storage fs` related commands are for ADLS Gen2 storage account, which has hierarchical namespace enabled. In such storage account, the response content do have `lastModified` filed and in python SDK it could use this property. But you get the error, which is raised in python SDK because of None value for `lastModified`, so I am guessing you are not using ADLS Gen2 storage account.

In your response, it only has `"paths":[{"isDirectory":"true","name":"<<>>"},{"isDirectory":"true","name":"<<>>"},{"isDirectory":"true","name":"<<>>"}]}`, which means you are listing directories with `--recursive false` and your account should not be ADLS Gen2 storage account because the response content is different from ADLS Gen2.

Anyway, if you are normal storage account and want to list blob container. If yes, you should use `az storage blob list` not `az storage fs file list`.

**Comment by yonzhan** [comment]
@alextmeyer, any feedback or update?

**Comment by alextmeyer** [comment]
Sorry thanks for following up @Juliehzl and @yonzhan.

You are correct that we're not using ADLS Gen2 across the board, encountered the suggestion to use the `az storage fs file` commands when working with `az storage blob directory` commands and found them to largely work with some limitations, but just moved everything back to `az storage blob` commands and handled the specific cases we required.

**Comment by Juliehzl** [comment]
I see. Thanks for your feedback.
