### ISSUE TITLE
unable to create a variable to store resource group name, and a resource group for resources

### ISSUE THREAD

**Issue by ngshukun** [Azure/azure-cli#17215]
## Describe the bug
unable to to create RG via Bash Cloudshell

**Command Name**
RG=<resource group name>
az group create --name $RG --location <location>

**Errors:**
```
unrecognized arguments: Asia
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/ng/.azure/commands/2021-03-05.07-53-29.group_create.417.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 517, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 173, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 117, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/ng/.azure/commands/2021-03-05.07-53-29.group_create.417.log'

## Expected Behavior
resource create in desired location

## Environment Summary
```
Linux-4.15.0-1108-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
ai-examples 0.2.5

```

**Comment by usrme** [comment]
Use [command substitution](https://www.gnu.org/software/bash/manual/bash.html#Command-Substitution) in Bash.

Based on your example it should be `RG=$(az group create --name "$RG" --location Asia)`.

**Comment by yonzhan** [comment]
ARM
