### ISSUE TITLE
Issue connecting to a data lake store using az cli

### ISSUE THREAD

**Issue by marnheus** [Azure/azure-cli#17227]
## Describe the bug
I’m trying to use az cli to manage a Data Lake storage. I get the same error on every try with any command (tested with az storage fs directory create, delete or list)

**Command Name**
`az storage fs directory list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


from_connection_string() missing 1 required positional argument: 'conn_str'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-363drsgw\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\storage\__init__.py", line 312, in new_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 536, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\storage\_client_factory.py", line 242, in cf_adls_file_system
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\storage\_client_factory.py", line 231, in cf_adls_service
TypeError: from_connection_string() missing 1 required positional argument: 'conn_str'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage fs directory list -f {} --account-name {} --account-key {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0

Extensions:
datafactory 0.1.0

```
## Additional Context
I’m working on a tightly controlled environment. I don’t know if it can affect anything

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Could you upgrade to latest azure cli with `az upgrade`? There is no issue in latest version.
