### ISSUE TITLE
az login command is randomly getting failed

### ISSUE THREAD

**Issue by arunkp89** [Azure/azure-cli#17222]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az login command is failing to connect intermittently. Ran the debug log during the time of the issue and we are getting below messages.

DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f5219d038c8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 74.692 seconds (init: 0.381, invoke: 74.311)
INFO: cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 509, in get_current_account_user
    active_account = self.get_subscription()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 518, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 57, in _decorator
    val = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 530, in _get_user_azure_id
    return _get_profile().get_current_account_user()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 511, in get_current_account_user
    raise CLIError('There are no active accounts.')
knack.util.CLIError: There are no active accounts.

INFO: cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 540, in _get_azure_subscription_id
    return _get_profile().get_subscription_id()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 535, in get_subscription_id
    return self.get_subscription(subscription)[_SUBSCRIPTION_ID]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 518, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

INFO: telemetry.save: Save telemetry record of length 2812 in cache
INFO: telemetry.check: Returns Positive.
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/richard/.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

**To Reproduce**
When entering #az login in Ubuntu VMs, the command fails to succeed.

**Expected behavior**
az login command should work

**Environment summary**

azure-cli                         2.20.0

core                              2.20.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/richard/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Feb 26 2021, 06:44:03)
[GCC 7.5.0]

**Additional context**
Found a similar github issue: https://github.com/Azure/azure-cli/issues/14773, but the solution is not working in this case.

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
It looks like the log has been truncated. Do you mind sharing the full DEBUG log, especially the original error message?

Many thanks for the information.
