### ISSUE TITLE
Get a traceback when trying to retrieve serial log from Secure boot VM

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#17235]
I am deployed a Redhat 8.3 gen2 VM with Secure Boot enabled and I am getting the following error when I am trying to retrieve the Serial log, the Serial log for this VM is present and I can download it from the Portal.

## Version
```
johan@Azure:~$ az --version
azure-cli                         2.20.0

core                              2.20.0
telemetry                          1.0.6
```

## Error
```
johan@Azure:~$ az vm boot-diagnostics get-boot-log -g r83t -n r83t
The command failed with an unexpected error. Here is the traceback:
'RetrieveBootDiagnosticsDataResult' object has no attribute 'done'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1501, in get_boot_log
    uris = LongRunningOperation(cmd.cli_ctx)(poller)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 958, in __call__
    while not poller.done():
AttributeError: 'RetrieveBootDiagnosticsDataResult' object has no attribute 'done'
To open an issue, please run: 'az feedback
```

**Comment by yungezz** [comment]
hi @qwordy, could you pls have a look? thanks

**Comment by qwordy** [comment]
Will open an investigation.
