### ISSUE TITLE
Cant Execute "az ad group list"

### ISSUE THREAD

**Issue by jpattina** [Azure/azure-cli#17327]
## Describe the bug

**Command Name**
`az ad group list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 239, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py", line 148, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py", line 40, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 202, in encode
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ad group list`

## Expected Behavior

list of groups in active directory output

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```

**Comment by yonzhan** [comment]
graph

**Comment by jpattina** [comment]
As far as I can tell, when there are no groups to list this command gets stuck and doesn't output anything until it crashes

**Comment by jiasli** [comment]
`MemoryError` is similar to https://github.com/Azure/azure-cli/issues/15268#issuecomment-772388341.

But for the "gets-stuck" issue, I need some more time to investigate and repro it.
