### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'api_version'

### ISSUE THREAD

**Issue by avaranovich** [Azure/azure-cli#1734]
Installed from the install script, and  _az login_ gives
```

__init__() got an unexpected keyword argument 'api_version'
Traceback (most recent call last):
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/application.py", line 139, in execute
    result = expanded_arg.func(params)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 275, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 67, in login
    tenant)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 102, in find_subscriptions_on_login
    self._management_resource_uri)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 317, in find_through_interactive_flow
    context = self._create_auth_context(_COMMON_TENANT)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 338, in _create_auth_context
    return self._auth_context_factory(authority, token_cache)
  File "/home/andrei/.local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 61, in <lambda>
    api_version=None)
TypeError: __init__() got an unexpected keyword argument 'api_version'

```

**Comment by johanste** [comment]
My guess would be that there is a mismatch between packages. @derekbekoe, can you please take a look?

**Comment by derekbekoe** [comment]
@avaranovich What's the output from the following two commands?
`az --version`

`pip list`

**Comment by derekbekoe** [comment]
I've looked into this.
The CLI requires `adal>=0.4.3`. I suspect you have a version less than this.

In https://github.com/Azure/azure-cli/pull/1389, we updated to adal 0.4.3 which includes a new keyword argument `api_version.`

Upgrade with `pip install --user --upgrade azure-cli`.

**Comment by derekbekoe** [comment]
Closing for inactivity.
Please reopen if that didn't fix your issue.

**Comment by avaranovich** [comment]
adal dependency was indeed the root of the issue
