### ISSUE TITLE
az vm user update failed with an unexpected error

### ISSUE THREAD

**Issue by henti** [Azure/azure-cli#17372]
## Describe the bug

Created a 2016-Datacenter server and setup some new users, Then did system updates and rebooted. After reboot I could not log in anymore. 

Tried to reset password to log back in. 

**Command Name**
`az vm user update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2244, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2231, in _reset_windows_admin
    poller = client.virtual_machine_extensions.create_or_update(resource_group_name,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm user update -u {} -p {} -n {} -g {}`

## Environment Summary
```
Linux-5.4.0-67-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
storage-blob-preview 0.3.0
image-copy-extension 0.2.8

```

**Comment by yungezz** [comment]
hi @qwordy, is this issue fixed in latest version?

**Comment by qwordy** [comment]
@henti Thank you for reporting it. This issue is fixed in the coming version on 3/23/2021.
It is fixed by https://github.com/Azure/azure-cli/pull/17257.
