### ISSUE TITLE
Application gateway: unable to create rewrite rule without headers rewrites

### ISSUE THREAD

**Issue by Saaman** [Azure/azure-cli#17373]
# Describe the bug

The command is throwing an error when trying to create a rewrite rule with no request-headers nor response-headers configurations. Therefore, it is possible (at least in the Azure portal) to create such a rule with only an url rewrite. Should it then be possible to do the same thing using the CLI?

#### command name
`az network application-gateway rewrite-rule create`
#### Errors
```
az : ERROR: usage error: --response-headers HEADER=VALUE | --request-headers HEADER=VALUE
```
# To Reproduce
- On an Application Gateway (location: Canada East, Tier: WAF V2)
- Create a rewrite-rule set: `az network application-gateway rewrite-rule set create --gateway-name {} -g {} -n "myRewriteRuleSet"`
- Create a rewrite-rule on this set: `az network application-gateway rewrite-rule create --gateway-name {} --rule-set-name "myRewriteRuleSet" -n "myRewriteRule" -g {} --enable-reroute $true --modified-path "{var_uri_path_1}/something/{var_uri_path_2}"`

### Error

```
az : DEBUG: cli.knack.cli: Command arguments: ['network', 'application-gateway', 'rewrite-rule', 'create', 
'--gateway-name', '****', '--rule-set-name', 'myRewriteRuleSet', '-n', 
'myRewriterule', '-g', '****', '--enable-reroute', 'True', '--modified-path', 
'{var_uri_path_1}/something/{var_uri_path_2}', '--debug']
At C:\Users\****\Downloads\script rewrite rule.ps1:10 char:1
+ az network application-gateway rewrite-rule create --gateway-name $ag ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG: cli.knac...2}', '--debug']:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 
0x0362AC48>, <function OutputProducer.on_global_arguments at 0x036C6108>, <function CLIQuery.on_global_arguments at 
0x036E1078>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.natgateway', 
'azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: natgateway                0.005         3         6
DEBUG: cli.azure.cli.core: network                   0.348       130       598
DEBUG: cli.azure.cli.core: privatedns                0.006        14        66
DEBUG: cli.azure.cli.core: Total (3)                 0.358       147       670
DEBUG: cli.azure.cli.core: Loaded 145 groups, 670 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : network application-gateway rewrite-rule create
DEBUG: cli.azure.cli.core: Command table: network application-gateway rewrite-rule create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 
0x03A0D3D8>]
INFO: az_command_data_logger: command args: network application-gateway rewrite-rule create --gateway-name {} 
--rule-set-name {} -n {} -g {} --enable-reroute {} --modified-path {} --debug
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 
'C:\Users\*****\.azure\commands'.
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function 
register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03A64FA8>, <function 
register_global_query_examples_argument.<locals>.register_query_examples at 0x03A6E738>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function 
register_ids_argument.<locals>.add_ids_arguments at 0x03A6E780>, <function 
register_cache_arguments.<locals>.add_cache_arguments at 0x03A6E810>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 
0x036C6150>, <function CLIQuery.handle_query_parameter at 0x036E10C0>, <function 
register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03A6E150>, <function 
register_ids_argument.<locals>.parse_ids_arguments at 0x03A6E7C8>]
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 660, in 
execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 723, in 
_run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 716, in 
_run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-l7ikczg1\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 694, in 
_run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 331, in 
__call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\__init__.py", line 808, in 
default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\command_modules\network\custom.py", line 
1000, in create_ag_rewrite_rule
knack.util.CLIError: usage error: --response-headers HEADER=VALUE | --request-headers HEADER=VALUE
ERROR: cli.azure.cli.core.azclierror: usage error: --response-headers HEADER=VALUE | --request-headers HEADER=VALUE
ERROR: cli.azure.cli.core.azclierror: usage error: --response-headers HEADER=VALUE | --request-headers HEADER=VALUE
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03A0D4F8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 0.866 seconds (init: 0.177, invoke: 0.689)
INFO: telemetry.save: Save telemetry record of length 3190 in cache
WARNING: telemetry.check: Negative: The C:\Users\*****\.azure\telemetry.txt was modified at 2021-03-19 
11:49:20.867059, which in less than 600.000000 s
```

## Environment
```
Windows 10 Enterprise 64-bit 20H2 19042.804
Powershell 5.1.19041.610
Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

azure-cli                         2.20.0
core                              2.20.0
telemetry                         1.0.6
```
## Additionnal information
The code generating this error is here:
https://github.com/Azure/azure-cli/blob/b6ffdc153bec5ef46259f57538128d6ae6b406c9/src/azure-cli/azure/cli/command_modules/network/custom.py#L999

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Thank you for your feedback  and we will check it soon.

**Comment by Saaman** [comment]
Thanks a lot! 😃

**Comment by msyyc** [comment]
FYI. It is permitted without '--request-headers' and '--response-headers'. We will delete the unnecessary parameters check soon :  
## Additionnal information
The code generating this error is here:
https://github.com/Azure/azure-cli/blob/b6ffdc153bec5ef46259f57538128d6ae6b406c9/src/azure-cli/azure/cli/command_modules/network/custom.py#L999

**Comment by 00Kai0** [comment]
@Saaman, I tried to remove this check and tested. But service API didn't allow this request.
```
(ApplicationGatewayRewriteRuleSetActionSetInRewriteRuleCannotBeEmpty) ActionSet is a required field in a RewriteRule.
```

[test script](https://github.com/00Kai0/azure-cli/blob/fix-issue-17373/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L1344)
[custom.py](https://github.com/00Kai0/azure-cli/blob/fix-issue-17373/src/azure-cli/azure/cli/command_modules/network/custom.py#L1044)

**Comment by Saaman** [comment]
I was hoping that adding a `--modified-path` option the the command line was producing a valid rewrite rule. It's not the case?
In the portal, we have 3 different choices of rewrite types: 
![image](https://user-images.githubusercontent.com/660686/118705260-0473ef80-b7e6-11eb-9551-6c0ee44e816f.png)
It seemed to me that `--modified-path` was referring to this "url" rewrite type

**Comment by 00Kai0** [comment]
@Saaman , I see. I have created a PR for it :)
