### ISSUE TITLE
UnicodeError thrown when using az login without browser

### ISSUE THREAD

**Issue by hoangelos** [Azure/azure-cli#17444]
UnicodeError thrown when you do an az login with a username and password. I was using lhomebrew on my Mac, and thought it was related, so I  

docker run -it mcr.microsoft.com/azure-cli

And got the same error. 

bash-5.0# az login -u peter.halliday@walgreens.com -p ************
The command failed with an unexpected error. Here is the traceback:
'ascii' codec can't encode characters in position 1617-1618: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 162, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 215, in find_subscriptions_on_login
    username, password, tenant, self._ad_resource_uri)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 885, in find_from_user_account
    token_entry = context.acquire_token_with_username_password(resource, username, password, _CLIENT_ID)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 285, in get_token_with_username_password
    token = self._get_token_username_password_federated(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 258, in _get_token_username_password_federated
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 210, in _perform_username_password_for_access_token_exchange
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 197, in _perform_wstrust_exchange
    result = wstrust.acquire_token(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py", line 169, in acquire_token
    return self._handle_rstr(resp.text)
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py", line 126, in _handle_rstr
    wstrust_resp.parse()
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_response.py", line 238, in parse
    token_found = self._parse_token_by_re(self._response)
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_response.py", line 217, in _parse_token_by_re
    return tokens[0].encode('us-ascii'), token_types[0]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1617-1618: ordinal not in range(128)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error is raised by ADAL:

https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/f1bc11d5b6e0ace54d7f5ed6972a098547638df2/adal/wstrust_response.py#L217

```py
                return tokens[0].encode('us-ascii'), token_types[0]
```

Transferring to ADAL repo https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/250

**Comment by rayluo** [comment]
Hi @hoangelos , would you mind alter this:

> File "/usr/local/lib/python3.6/site-packages/adal/wstrust_response.py", line 217, in _parse_token_by_re

and change that line from:

```python
return tokens[0].encode('us-ascii'), token_types[0]
```

to

```python
return tokens[0].encode('utf-8'), token_types[0]
```

and let us know how it pans out?

If that still won't work, we would need you to add one more line `open("/tmp/saml.txt", "w").write(tokens[0])` before it, and then send that /tmp/saml.txt file to my email, so that we can follow up with further investigation.

**Comment by hoangelos** [comment]
@rayluo I made that change and it worked.

**Comment by jiasli** [comment]
Thanks @hoangelos for the confirmation. I will close this issue from Azure CLI side.

**Comment by rayluo** [comment]
@jiasli, [ADAL 1.2.7 is released to PyPI](https://pypi.org/project/adal/) with [such bugfix](https://github.com/AzureAD/azure-activedirectory-library-for-python/releases/tag/1.2.7). Now it is your turn to pull in that package to ship such improvement to customers.
