### ISSUE TITLE
WebApp:az webapp deploy throws error after successful copy

### ISSUE THREAD

**Issue by tapanp** [Azure/azure-cli#17447]
## Describe the bug
I tried to copy my spring boot webapp.jar (size: ~213Mb) using following command  

```az webapp deploy --name plan2test --resource-group xxx-rg --src-path path_to_local_webapp.jar --type static --target-path path_to_local_webapp.jar --verbose```

az --version
```
>az --version
azure-cli                         2.20.0 *

core                              2.20.0 *
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\tpandya\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

While transfer was successful, I got following error on command line:

**Command Name**
`az webapp deploy`

**Errors:**
```
Object of type 'frozenset' is not JSON serializable
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py, ln 239, in invoke
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py, ln 148, in out
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py, ln 40, in format_json
json\__init__.py, ln 238, in dumps
json\encoder.py, ln 201, in encode
json\encoder.py, ln 430, in _iterencode
json\encoder.py, ln 404, in _iterencode_dict
json\encoder.py, ln 404, in _iterencode_dict
json\encoder.py, ln 404, in _iterencode_dict
json\encoder.py, ln 437, in _iterencode
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py, ln 32, in default
json\encoder.py, ln 180, in default
TypeError: Object of type 'frozenset' is not JSON serializable
```

console output:
```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Initiating deployment
Deploying from local path: xxx.jar
Deployment API: https://xxx.scm.azurewebsites.net/api/publish?type=static&path=./xxx.jar
Deployment has completed successfully
The command failed with an unexpected error. Here is the traceback:
Object of type 'frozenset' is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 239, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py", line 148, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py", line 40, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
  File "json\encoder.py", line 430, in _iterencode
  File "json\encoder.py", line 404, in _iterencode_dict
  File "json\encoder.py", line 404, in _iterencode_dict
  File "json\encoder.py", line 404, in _iterencode_dict
  File "json\encoder.py", line 437, in _iterencode
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\output.py", line 32, in default
  File "json\encoder.py", line 180, in default
TypeError: Object of type 'frozenset' is not JSON serializable
To open an issue, please run: 'az feedback'
Command ran in 118.052 seconds (init: 0.278, invoke: 117.774)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- stop web app using az webapp stop
- try to copy webapp jar using above mentioned command

- _Put any pre-requisite steps here..._
- `az webapp deploy --name {} --resource-group {} --src-path {} --type {} --target-path {} --verbose`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0 *

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Same issue has been tracking under #17228. Closing this as a duplicate. For more details please refer to #17228
