### ISSUE TITLE
az connectedk8s connect crashes with native module load error

### ISSUE THREAD

**Issue by daweim0** [Azure/azure-cli#17467]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp36-win32.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp36-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp36-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
...
```

here is the full error message: (not sure if I should leave the above auto-generated one as is)
```
PS C:\Users\damichel> az connectedk8s connect --name davidArcTest1 --resource-group AzureArcTest
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp36-win32.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp36-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp36-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 558, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 478, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 315, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\commands.py", line 106, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 787, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 827, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\damichel\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 20, in <module>
    from Crypto.IO import PEM
  File "C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\IO\PEM.py", line 39, in <module>
    from Crypto.Hash import MD5
  File "C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Hash\MD5.py", line 47, in <module>
    """)
  File "C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp36-win32.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp36-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp36-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\damichel\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\damichel\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az connectedk8s connect --name {} --resource-group {}`

## Expected Behavior

no error

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
aks-preview 0.5.0
azure-iot 0.9.4
connectedk8s 1.0.0
interactive 0.4.4
k8s-configuration 1.0.0
resource-graph 1.1.0

```

**Comment by yungezz** [comment]
hi @fengzhou-msft could you have a look firstly is it related to cryptography ? thanks

**Comment by fengzhou-msft** [comment]
The Crypto dependency is from the extension, route to service team to take a look.

**Comment by jiasli** [comment]
Same as #18424
