### ISSUE TITLE
unable to create vnet within learn sandbox

### ISSUE THREAD

**Issue by angethom** [Azure/azure-cli#17517]
angel_lizthomas@Azure:~$ az network vnet create \
>     --resource-group learn-14748ef1-c605-488d-8038-81acd19ceb1e \
>     --name CoreServicesVnet \
>     --address-prefix 10.20.0.0/16 \
>     --location westus
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/angel_lizthomas/.azure/commands/2021-03-30.14-10-29.network_vnet_create.273.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233,in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 517, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 173,in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint:disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 117, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/angel_lizthomas/.azure/commands/2021-03-30.14-10-29.network_vnet_create.273.log'

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@angethom what is the version of azure-cli? ('az -v' could help)

**Comment by kairu-ms** [comment]
It works in latest version of CLI. Please update your cli by command
```
az upgrade
```
