### ISSUE TITLE
Azure CLI ADO Extension installation : An error occurred. Pip failed with status code 2. Use --debug for more information.

### ISSUE THREAD

**Issue by bucheron88** [Azure/azure-cli#17529]
Thanks in advance for your help

**Describe the bug**
Az CLI version 2.21 fails with Pip error on extension install. (e.g. az extension add --name azure-devops)
cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 2. Use --debug for more information.

**To Reproduce**
az extension add --name azure-devops

**Expected behavior**
No failure

**Environment summary**
Az CLI Version: 2.21
Windows Server 2019
Python (Windows) 3.6.8
Proxy/Firewall OK.

[Log.txt](https://github.com/Azure/azure-cli/files/6236432/Log.txt)

**Comment by yungezz** [comment]
hi @bucheron88 could you pls run `az extension add --name azure-devops --debug` to help trouble shooting?

**Comment by bucheron88** [comment]
> hi @bucheron88 could you pls run `az extension add --name azure-devops --debug` to help trouble shooting?

Hi @yungezz , the result of the --debug mode is in the log.txt file attached in my initial message. Thanks

**Comment by jiasli** [comment]
Judging from the debug log, it looks like your user name `EXT$DE~1.AD` is corrupting `pip` and causing problem:

```
Collecting chardet<5,>=3.0.2
  Created temporary directory: C:\Users\EXT$DE~1.AD\AppData\Local\Temp\2\pip-unpack-2c22umtj
  ...
Installing collected packages: six, python-dateutil, distro, isodate, oauthlib, certifi, urllib3, idna, chardet, requests, requests-oauthlib, msrest, azure-devops
ERROR: Exception:
Traceback (most recent call last):
  File "distutils\util.py", line 202, in subst_vars
  File "re.py", line 191, in sub
  File "distutils\util.py", line 199, in _subst
  File "os.py", line 669, in __getitem__
KeyError: 'DE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\locations.py", line 125, in distutils_scheme
    i.finalize_options()
  File "distutils\command\install.py", line 307, in finalize_options
  File "distutils\command\install.py", line 475, in expand_basedirs
  File "distutils\command\install.py", line 469, in _expand_attrs
  File "distutils\util.py", line 204, in subst_vars
ValueError: invalid variable '$'DE''
Removed build tracker: 'C:\\Users\\EXT$DE~1.AD\\AppData\\Local\\Temp\\2\\pip-req-tracker-838w_95f'
```

On my machine it looks like

```
Successfully installed azure-devops-0.18.0 certifi-2020.12.5 chardet-4.0.0 distro-1.3.0 idna-2.10 isodate-0.6.0 msrest-0.6.21 oauthlib-3.1.0 python-dateutil-2.7.3 requests-2.25.1 requests-oauthlib-1.3.0 six-1.16.0 urllib3-1.26.4
Removed build tracker: 'C:\\Users\\myname\\AppData\\Local\\Temp\\pip-req-tracker-dix46qow'
```

Is it possible to use a user name that only consists of `[a-zA-Z0-9]` and try again?

**Comment by NormanGarciaV** [comment]
Hi guys...

I am having the same problem when trying to install the ADO extension.  The error is actually "An error occurred. Pip failed with status code 1."

Check the username, is all letters, no luck there for me.
I uninstalled the CLI, deleted the reminding files, reinstall it, no luck.

Following the log files, wondering if the name of the extension gets lost at certain point, based on the log below where the --name {} with nothing inside the curve brackets.

CMD-LOG-LINE-BEGIN 23192 | 2024-05-09 14:27:46,282 | INFO | az_command_data_logger | command args: extension add --name {} --debug
CMD-LOG-LINE-BEGIN 23192 | 2024-05-09 14:28:05,512 | ERROR | az_command_data_logger | An error occurred. Pip failed with status code 1. Use --debug for more information.
CMD-LOG-LINE-BEGIN 23192 | 2024-05-09 14:28:05,513 | INFO | az_command_data_logger | exit code: 1


But yet, in the debug output, I can see it reads the parameter.

PS Z:\> az extension add --name azure-devops --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'azure-devops', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
