### ISSUE TITLE
Error attempting to update a log-analytics export

### ISSUE THREAD

**Issue by NetworkAdministratorsALI** [Azure/azure-cli#17532]
## Describe the bug

**Command Name**
`az monitor log-analytics workspace data-export update`

**Errors:**
```
Cannot deserialize content-type: text/plain
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
...
site-packages/msrest/pipeline/universal.py, ln 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
site-packages/msrest/pipeline/universal.py, ln 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- az monitor log-analytics workspace data-export update --name SentinelArchive --resource-group AccessLex-Azure-Datacenter -- 'workspace-name ALexAzureSentinal --tables AuditLogs AWSCloudTrail AzureActivity BehaviorAnalytics CommonSecurityLog ComputerGroup ConfigurationChange ConfigurationData DeviceEvents DeviceFileEvents DeviceInfo DeviceLogonEvents DeviceNetworkEvents DeviceNetworkInfo DeviceProcessEvents DeviceRegistryEvents Event IntuneDevices IntuneOperationalLogs McasShadowItReporting OfficeActivity Operation ProtectionStatus SecurityAlert SecurityBaseline SecurityBaselineSummary SecurityEvent SecurityIncident ServiceMapComputer_CL ServiceMapProcess_CL SigninLogs Update UpdateSummary VMBoundPort VMComputer VMConnection VMProcess WVDConnections WVDErrors WVDFeeds'

## Environment Summary
```
Linux-4.15.0-1111-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by NetworkAdministratorsALI** [comment]
Note, this is being done by Azure CLI

**Comment by NetworkAdministratorsALI** [comment]
Full error details:
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 567, in handler
    result = cached_put(cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 450, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 444, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/loganalytics/operations/_data_exports_operations.py", line 185, in create_or_update
    error = self._deserialize(_models.DataExportErrorResponse, response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1541, in _unpack_content
    raw_data.headers
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
Same as https://github.com/Azure/azure-cli/issues/17231
