### ISSUE TITLE
az container exec: Not a tty

### ISSUE THREAD

**Issue by yvespp** [Azure/azure-cli#17530]
**Describe the bug**
I'm running `az container exec` on our CI/CD inside a docker container to test my app. az cli throws this exception because there is no tty:
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
(25, 'Not a tty')
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 623, in container_exec
    _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 657, in _start_exec_pipe
    oldtty = termios.tcgetattr(sys.stdin)
termios.error: (25, 'Not a tty')
```
I can't add a tty because it runs inside our CI/CD.

Similar to this issue https://github.com/Azure/azure-cli/issues/15225

**To Reproduce**

Run az cli inside a container without attching tty (-t) and then run `az container exec`
```
docker run mcr.microsoft.com/azure-cli az container exec --resource-group $RG --name $ACI_NAME --exec-command "ls -la"
```

**Expected behavior**
`az container exec` should also work without a tty.
In docker I have to explicitly add `-t` to enable tty but with `az container exec` it's allways enabled.

**Environment summary**

* GitLab runner container
* az cli 2.16.0

**Comment by dkkapur** [comment]
tagging appropriate person for followup! @macolso

**Comment by alersrt** [comment]
Any update with this issue? Got the same trouble with GitLab runner container.

**Comment by alersrt** [comment]
Why wouldn't provide option what would allowed to run this command in non-interactive mode? I mean I understand that this feature is supposed to be interactive like starting a shell and do some manual work. However its necessary sometime run in-container process without any interaction, like a some scheduled jobs, etc.. Yes, you can say that we need to split our workflow on several containers and use necessary... But there is no any possibility to specify scheduling for such stuff inside the one container group. More over, its necessary sometime to have control not only on scheduling but also on manual job starting.

It would be good to have this feature:
```bash
az container exec ... --exec-command "scheduled_script.sh" --non-interactive
```
So we would be able to run background processes inside container without any interaction.

**Comment by alersrt** [comment]
Okay, I finally managed this trouble out. As workaround we can use [integration][1] between Docker and Azure. We can use `docker exec <container> <comand>` for executing process inside deployed container.

[1]: https://docs.docker.com/cloud/aci-integration/

**Comment by onionhammer** [comment]
Any update on this? I would like to be able to exec a bash script running in a container via a github action and I'm receiving "Inappropriate ioctl for device"

**Comment by cgraf-spiria** [comment]
As a workaround, I invoke it like this:
```bash
script -q -c 'az container exec --name <Name> --resource-group <GroupName> --exec-command "<Command>"'
```

And https://github.com/Azure/azure-cli/issues/26175  is a duplicate of this issue
