### ISSUE TITLE
issue az  az network application-gateway address-pool update command

### ISSUE THREAD

**Issue by garimasingh** [Azure/azure-cli#17591]
## Describe the bug

**Command Name**
`az network application-gateway address-pool update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway address-pool update -g {} --gateway-name {} -n {} --subscription {} --add {} {}`
 example command 
az network application-gateway address-pool update -g MyResourceGroup --gateway-name MyAppGateway -n MyAddressPool \
    --add backendAddresses "{ "ip_address": "{10.0.0.13}" }"

it doesnt work as expected

## Environment Summary
```
Linux-3.10.0-1160.21.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo
Python 2.7.5
Shell: bash

azure-cli 2.0.72

```

**Comment by garimasingh** [comment]
seems like the quotes need an escape character found the answer in another issue
