### ISSUE TITLE
Expected 1 module to load starting with 'azext_': got [] Azure-cli-ml

### ISSUE THREAD

**Issue by dwissaaj** [Azure/azure-cli#17643]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I install Azure-cli-ml but i got and bug or error when I try to log my web app

**Expected behavior**
Expected to success remove the extention so i can login or log,but the remove it self got bug

`
User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az login
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az feedback
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az extension remove -n azure-cli-ml
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

#User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az login
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az feedback
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

User@DESKTOP-TA09C83 MINGW64 ~/Desktop
$ az extension remove -n azure-cli-ml
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 515, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 424, in load_command_table
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 318, in _update_command_table_from_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 305, in _filter_modname
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 309, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To open an issue, please run: 'az feedback'

`
#16188

**Comment by fengzhou-msft** [comment]
@dwissaaj please clean up your extension folder manually. It's `%USERPROFILE%\.azure\cliextensions`.

**Comment by mjudeikis** [comment]
`azdev extension repo list` and `azdev extension repo remove` worked for me.
