### ISSUE TITLE
az extension add for Application Insights produces Directory not empty error.

### ISSUE THREAD

**Issue by MarkAtAgilliance** [Azure/azure-cli#17654]
## Describe the bug
Adding extension for app insights to a deployment script has started to error.  Has been working up to now.  The script is run from a Windows Server build server.  The script is initiated from DevOps release pipeline.

Error is 'The command failed with an unexpected error. Here is the traceback:  ERROR: [WinError 145] The directory is not empty.  '

See below for output.

**Command Name**
`az extension add -n application-insights --only-show-errors `

or 

`az extension add --upgrade -n application-insights --only-show-errors `

**Errors:**

2021-04-12T21:51:35.4438426Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-04-12T21:51:35.4460346Z ERROR: [WinError 145] The directory is not empty: 'C:\\windows\\ServiceProfiles\\NetworkService\\AppData\\Local\\Temp\\tmpwtvhhesq\\azext_applicationinsights\\vendored_sdks\\applicationinsights\\models'
2021-04-12T21:51:35.4462016Z Traceback (most recent call last):
2021-04-12T21:51:35.4463132Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2021-04-12T21:51:35.4472606Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 660, in execute
2021-04-12T21:51:35.4473602Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
2021-04-12T21:51:35.4474427Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 716, in _run_job
2021-04-12T21:51:35.4477480Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 703, in reraise
2021-04-12T21:51:35.4478348Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 694, in _run_job
2021-04-12T21:51:35.4479552Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 331, in __call__
2021-04-12T21:51:35.4481079Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 811, in default_command_handler
2021-04-12T21:51:35.4505900Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 18, in add_extension_cmd
2021-04-12T21:51:35.4506763Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 327, in add_extension
2021-04-12T21:51:35.4507533Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 136, in _add_whl_ext
2021-04-12T21:51:35.4517954Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 84, in _validate_whl_extension
2021-04-12T21:51:35.4518584Z   File "shutil.py", line 500, in rmtree
2021-04-12T21:51:35.4519042Z   File "shutil.py", line 390, in _rmtree_unsafe
2021-04-12T21:51:35.4519439Z   File "shutil.py", line 390, in _rmtree_unsafe
2021-04-12T21:51:35.4519826Z   File "shutil.py", line 390, in _rmtree_unsafe
2021-04-12T21:51:35.4520240Z   [Previous line repeated 1 more time]
2021-04-12T21:51:35.4520618Z   File "shutil.py", line 399, in _rmtree_unsafe
2021-04-12T21:51:35.4521009Z   File "shutil.py", line 397, in _rmtree_unsafe
2021-04-12T21:51:35.4521743Z OSError: [WinError 145] The directory is not empty: 'C:\\windows\\ServiceProfiles\\NetworkService\\AppData\\Local\\Temp\\tmpwtvhhesq\\azext_applicationinsights\\vendored_sdks\\applicationinsights\\models'
2021-04-12T21:51:35.5294904Z To open an issue, please run: 'az feedback'
2021-04-12T21:51:39.6967856Z ERROR: The command requires the extension application-insights. Unable to prompt for extension install confirmation as no tty available. Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
No error, loads the extension, continues.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0 *

Extensions:
application-insights 0.1.13

```

**Comment by MarkAtAgilliance** [comment]
Seems like there is a change to behavior and need to set.  Did not see this in any release notes tho.
az config set extension.use_dynamic_install=yes_without_prompt
