### ISSUE TITLE
az ts export -s {} --output-folder {}

### ISSUE THREAD

**Issue by Svessir** [Azure/azure-cli#17759]
## Describe the bug
az ts export is throwing an error for valid input:
*az ts export -s /subscriptions/{}/resourceGroups/{}/providers/Microsoft.Resources/templateSpecs/{}/versions/{} --output-folder ./exported*

**Command Name**
`az ts export`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 657, in execute
    raise ex
cli/core/commands/__init__.py, ln 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
    result = cmd_copy(params)
cli/core/commands/__init__.py, ln 328, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 807, in default_command_handler
    return op(**command_args)
cli/command_modules/resource/custom.py, ln 1963, in export_template_spec
    return unpack(cmd, exported_template, output_folder, (str(name) + '.JSON'))
cli/command_modules/resource/_packing_engine.py, ln 195, in unpack
    for artifact in getattr(packaged_template, 'Artifacts'):
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ts export -s {} --output-folder {}`

## Expected Behavior
The templates in *-s "/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Resources/templateSpecs/{}/versions/{}"* should have been exported to the destination specified by the *--output-folder* param

## Environment Summary
```
Linux-5.4.0-71-generic-x86_64-with-glibc2.27
Python 3.8.0
Installer: PIP

azure-cli 2.22.0 *

Extensions:
azure-devops 0.18.0
azure-iot 0.10.10

```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
Resource

**Comment by zhoxing-ms** [comment]
@detienne20 could you please help to have a look at this issue~

**Comment by usrme** [comment]
Seeing the same error message as of yesterday, which is weird as the command has been in use for quite some time now... For some reason some template specs have the `artifacts` property defined and some don't, which trips up the underlying Python code.

**Comment by usrme** [comment]
@detienne20, despite #17890 being successfully resolved I am still seeing issue even with 2.23.0:

```
# az ts export --name {} --resource-group {} --version {} --output-folder .
Command group 'ts' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 1967, in export_template_spec
    return unpack(cmd, exported_template, output_folder, (str(name) + '.JSON'))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/resource/_packing_engine.py", line 195, in unpack
    for artifact in getattr(packaged_template, 'Artifacts'):
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'
bash-5.1# az version
{
  "azure-cli": "2.23.0",
  "azure-cli-core": "2.23.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

The template spec in question does **not** have any artifacts defined:

![Screenshot_20210510_093853](https://user-images.githubusercontent.com/5902545/117616298-99864100-b173-11eb-9fd9-f1e617520095.png)

**Comment by johndowns** [comment]
I have this issue too. Happy for you to ping me internally if you want to see the debug output.

**Comment by zhoxing-ms** [comment]
@detienne20 Any update for this issue?

**Comment by Svessir** [comment]
Any update?

**Comment by yonzhan** [comment]
@detienne20

**Comment by detienne20** [comment]
Thank you for your patience, the fix for this is in progress and will be released soon.
