### ISSUE TITLE
[Sql] az sql elastic-pools database -h command throws

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-cli#1777]
```
(env) vishrut@mac azure-cli (master) $ az sql elastic-pools -h

Group
    az sql elastic-pools: Commands to manage database elastic pools.

Subgroups:
    database   : Command to manage databases activities in database elastic pools.
    recommended

Commands:
    create     : Creates a new Azure SQL elastic pool or updates an existing Azure SQL elastic pool.
    delete     : Deletes the Azure SQL elastic pool.
    list       : Returns information about Azure SQL elastic pools.
    show       : Gets information about an Azure SQL elastic pool.
    update     : Update a database elastic pool.

(env) vishrut@mac azure-cli (master) $ az sql elastic-pools database -h

Command
    az sql elastic-pools database: Command to manage databases activities in database elastic pools.

Arguments
'GroupHelpFile' object has no attribute 'parameters'
Traceback (most recent call last):
  File "/Users/vishrut/repos/azure-cli/src/azure-cli/azure/cli/main.py", line 35, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/vishrut/repos/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 119, in execute
    args = self.parser.parse_args(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 1016, in __call__
    parser.print_help()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/argparse.py", line 2358, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/vishrut/repos/azure-cli/src/azure-cli-core/azure/cli/core/parser.py", line 160, in format_help
    is_group)
  File "/Users/vishrut/repos/azure-cli/src/azure-cli-core/azure/cli/core/_help.py", line 30, in show_help
    print_detailed_help(help_file)
  File "/Users/vishrut/repos/azure-cli/src/azure-cli-core/azure/cli/core/_help.py", line 56, in print_detailed_help
    print_arguments(help_file)
  File "/Users/vishrut/repos/azure-cli/src/azure-cli-core/azure/cli/core/_help.py", line 79, in print_arguments
    if not help_file.parameters:
AttributeError: 'GroupHelpFile' object has no attribute 'parameters'

```

**cc:**
@troydai

**Comment by troydai** [comment]
Addressed this issue with @vishrutshah. He will send out fix soon. Assign to him.

**Comment by vishrutshah** [comment]
Closing this as fix has been checked-in to master.
