### ISSUE TITLE
Enabling AKS virtual node add-on fails with python error

### ISSUE THREAD

**Issue by brobichaud** [Azure/azure-cli#17791]
## Describe the bug
Attempting to enable the virtual node addon to an AKS cluster results in a python error

**Command Name**
az aks enable-addons

**Errors:**
AAD role propagation done[############################################]  100.0000%The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 807, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2368, in aks_enable_addons
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1794, in _add_virtual_node_role_assignment
AttributeError: 'NoneType' object has no attribute 'rpartition'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
1. Cluster already existed, running k8s v1.18.14
2. Add subnet to exiting VNet via: az network vnet subnet create --resource-group myresgrp --vnet-name myvnetname --name virtual-subnet --address-prefixes 10.241.0.0/16
3. Enable virtual nodes in cluster: az aks enable-addons --resource-group myclusterresgrp --name mycluster --addons virtual-node --subnet-name virtual-subnet
- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
Expected the addon to be enabled successfully

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI
azure-cli 2.22.1

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by HowardHoffman** [comment]
Bump.  I'm producing the same error today with a similar command.
In my case the command is
```
az aks enable-addons --addons azure-keyvault-secrets-provider --enable-secret-rotation --rotation-poll-interval 5m -n myCluster -g myResourceGroup
```

**Comment by mbifeld** [comment]
Hi @brobichaud and @HowardHoffman, is this issue still occurring?

**Comment by mbifeld** [comment]
Closing as outdated based on no response from the original author. Please reopen / tag me if this issue is still present. Thank you.
