### ISSUE TITLE
Unable to Install Machine Learning CLI Extension

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-cli#17842]
## Describe the bug
Unable to install Machine Learning CLI extension. 

**Command Name**
`az extension add`

**Errors:**
```
ValidationError: An error occurred. Pip failed with status code 1. Use --debug for more information.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add -n azure-cli-ml --debug`

## Expected Behavior
Machine Learning CLI extension gets installed.

## Environment Summary
```
macOS-10.16-x86_64-i386-64bit
Python 3.9.0
Installer: HOMEBREW

azure-cli 2.12.1 *

Extensions:
azure-devops 0.18.0
resource-graph 1.1.0

```
## Additional Context
Error message when running with the `debug` flag.
```
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-cli-ml to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement azureml-core~=1.27.0 (from azureml-cli-common)
ERROR: No matching distribution found for azureml-core~=1.27.0
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 357, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('azureml-core~=1.27.0'), parent=LinkCandidate('https://files.pythonhosted.org/packages/5e/38/76ab4b8c970535cd17655a9ec2ef2dc9570f48ec7ed741cabcb7ade325cf/azureml_cli_common-1.27.0-py3-none-any.whl#sha256=ef25614bf74fa1838130978d72b7e9918ad9b1532bc9c6228f8bb73eb58d228d (from https://pypi.org/simple/azureml-cli-common/) (requires-python:>=3.5,<4)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.12.1_1/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for azureml-core~=1.27.0

```

**Comment by yungezz** [comment]
add @fengzhou-msft to have a look.

**Comment by BigCat20196** [comment]
Hi @zhusulai  could you pls uninstall Azure CLI and install latest version? thanks.

On my computer, this extension can be installed correctly.
Environment Summary:
- Windows 10 Enterprise 21H1 19043.928
- Python 3.8.8
- Installer: pip
- azure-cli 2.23.0

Please kindly let us know if it solves the issue.
If this issue cannot be solved after trying, it may be recorded as an issue caused by a MAC OS.
