### ISSUE TITLE
Updating a storage account to use a customer managed key from a managed HSM fails with a cryptic error

### ISSUE THREAD

**Issue by grahamhayes** [Azure/azure-cli#17914]
## Describe the bug

Updating a storage account to use a customer managed key from a managed HSM fails with a cryptic error "(KeyVaultPolicyError) Keyvault policy recoverable is not set"

**Command Name**
```shell
az storage account update \
    --name <sa name> \
    --resource-group <rg> \
    --encryption-key-name <key name> \
    --encryption-key-source Microsoft.Keyvault \
    --encryption-key-vault https://<managed hsm name>.managedhsm.azure.net/
```

**Errors:**
`(KeyVaultPolicyError) Keyvault policy recoverable is not set`

<details>
  <summary>Debug output: Click to expand</summary>
<pre>
cli.knack.cli: Command arguments: ['storage', 'account', 'update', '--name', '<snip>', '--resource-group', '<snip>', '--encryption-key-name', '<snip>', '--encryption-key-source', 'Microsoft.Keyvault', '--encryption-key-vault', 'https://<snip>.managedhsm.azure.net/', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x106e240d0>, <function OutputProducer.on_global_arguments at 0x106eb4310>, <function CLIQuery.on_global_arguments at 0x106ecfaf0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.107        52       242
cli.azure.cli.core: Total (1)                 0.107        52       242
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 52 groups, 242 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account update
cli.azure.cli.core: Command table: storage account update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1076e5b80>]
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10770a040>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x107749310>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x107749ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x107749dc0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x106eb43a0>, <function CLIQuery.handle_query_parameter at 0x106ecfb80>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x107749c10>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x107749d30>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /Users/<snip>/.azure/accessTokens.json as utf-8-sig
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - Authority:Performing instance discovery: ...
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - Authority:Performing static instance discovery
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - Authority:Authority validated via static instance discovery
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - CacheDriver:Found 16 potential entries.
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - CacheDriver:Resource specific token found.
adal-python: 7a851132-2838-446d-93cf-65fe1a03f12f - CacheDriver:Returning token from cache lookup, AccessTokenId: b'rORPKKa9OncOoPUhb0DWSKZWXHGXBoS8o9wM0lG4ePU=', RefreshTokenId: b'AGmliy6GdNhtd9Ym2/yQ0bb2Res7539SLZKm0SVJ+Zg='
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Storage/storageAccounts/<snip>?api-version=2021-01-01'
azure.core.pipeline.policies._universal: Request method: 'GET'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': 'c1f05bbc-a840-11eb-a37d-acde48001122'
azure.core.pipeline.policies._universal:     'CommandName': 'storage account update'
azure.core.pipeline.policies._universal:     'ParameterSetName': '--name --resource-group --encryption-key-name --encryption-key-source --encryption-key-vault --debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.22.1 (HOMEBREW) azsdk-python-azure-mgmt-storage/17.0.0 Python/3.8.9 (macOS-10.15.7-x86_64-i386-64bit)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Storage/storageAccounts/<snip>?api-version=2021-01-01 HTTP/1.1" 200 None
azure.core.pipeline.policies._universal: Response status: 200
azure.core.pipeline.policies._universal: Response headers:
azure.core.pipeline.policies._universal:     'Cache-Control': 'no-cache'
azure.core.pipeline.policies._universal:     'Pragma': 'no-cache'
azure.core.pipeline.policies._universal:     'Transfer-Encoding': 'chunked'
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json'
azure.core.pipeline.policies._universal:     'Content-Encoding': 'gzip'
azure.core.pipeline.policies._universal:     'Expires': '-1'
azure.core.pipeline.policies._universal:     'Vary': 'Accept-Encoding'
azure.core.pipeline.policies._universal:     'x-ms-request-id': '3a0a34b7-4ac5-4146-8cb2-a3f7f30ceae8'
azure.core.pipeline.policies._universal:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
azure.core.pipeline.policies._universal:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
azure.core.pipeline.policies._universal:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
azure.core.pipeline.policies._universal:     'x-ms-correlation-request-id': '152111b6-139a-4d32-b327-40431543c925'
azure.core.pipeline.policies._universal:     'x-ms-routing-request-id': 'NORTHEUROPE:20210428T164248Z:152111b6-139a-4d32-b327-40431543c925'
azure.core.pipeline.policies._universal:     'X-Content-Type-Options': 'nosniff'
azure.core.pipeline.policies._universal:     'Date': 'Wed, 28 Apr 2021 16:42:47 GMT'
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {"identity":{"principalId":"<snip>","tenantId":"<snip>","type":"SystemAssigned"},"sku":{"name":"Standard_LRS","tier":"Standard"},"kind":"StorageV2","id":"/subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Storage/storageAccounts/<snip>","name":"<snip>","type":"Microsoft.Storage/storageAccounts","location":"northeurope","tags":{},"properties":{"privateEndpointConnections":[],"minimumTlsVersion":"TLS1_2","allowBlobPublicAccess":true,"allowSharedKeyAccess":true,"networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[],"ipRules":[],"defaultAction":"Allow"},"supportsHttpsTrafficOnly":true,"encryption":{"requireInfrastructureEncryption":true,"services":{"file":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-28T15:44:59.0346191Z"},"table":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-28T15:44:59.0346191Z"},"queue":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-28T15:44:59.0346191Z"},"blob":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-28T15:44:59.0346191Z"}},"keySource":"Microsoft.Storage"},"accessTier":"Hot","provisioningState":"Succeeded","creationTime":"2021-04-28T15:44:58.9565118Z","primaryEndpoints":{"dfs":"https://<snip>.dfs.core.windows.net/","web":"https://<snip>.z16.web.core.windows.net/","blob":"https://<snip>.blob.core.windows.net/","queue":"https://<snip>.queue.core.windows.net/","table":"https://<snip>.table.core.windows.net/","file":"https://<snip>.file.core.windows.net/"},"primaryLocation":"northeurope","statusOfPrimary":"available"}}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - Authority:Performing instance discovery: ...
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - Authority:Performing static instance discovery
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - Authority:Authority validated via static instance discovery
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - CacheDriver:Found 16 potential entries.
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - CacheDriver:Resource specific token found.
adal-python: cfe548bd-3952-4cea-a469-e19b8fd17d26 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'rORPKKa9OncOoPUhb0DWSKZWXHGXBoS8o9wM0lG4ePU=', RefreshTokenId: b'AGmliy6GdNhtd9Ym2/yQ0bb2Res7539SLZKm0SVJ+Zg='
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Storage/storageAccounts/<snip>?api-version=2021-01-01'
azure.core.pipeline.policies._universal: Request method: 'PATCH'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json'
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'Content-Length': '650'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': 'c1f05bbc-a840-11eb-a37d-acde48001122'
azure.core.pipeline.policies._universal:     'CommandName': 'storage account update'
azure.core.pipeline.policies._universal:     'ParameterSetName': '--name --resource-group --encryption-key-name --encryption-key-source --encryption-key-vault --debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.22.1 (HOMEBREW) azsdk-python-azure-mgmt-storage/17.0.0 Python/3.8.9 (macOS-10.15.7-x86_64-i386-64bit)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: {"sku": {"name": "Standard_LRS"}, "tags": {}, "properties": {"encryption": {"services": {"blob": {"enabled": true, "keyType": "Account"}, "file": {"enabled": true, "keyType": "Account"}, "table": {"enabled": true, "keyType": "Account"}, "queue": {"enabled": true, "keyType": "Account"}}, "keySource": "Microsoft.Keyvault", "requireInfrastructureEncryption": true, "keyvaultproperties": {"keyname": "<snip>", "keyvaulturi": "https://<snip>.managedhsm.azure.net/"}}, "accessTier": "Hot", "supportsHttpsTrafficOnly": true, "networkAcls": {"bypass": "AzureServices", "virtualNetworkRules": [], "ipRules": [], "defaultAction": "Allow"}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Storage/storageAccounts/<snip>?api-version=2021-01-01 HTTP/1.1" 400 91
azure.core.pipeline.policies._universal: Response status: 400
azure.core.pipeline.policies._universal: Response headers:
azure.core.pipeline.policies._universal:     'Cache-Control': 'no-cache'
azure.core.pipeline.policies._universal:     'Pragma': 'no-cache'
azure.core.pipeline.policies._universal:     'Content-Length': '91'
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json'
azure.core.pipeline.policies._universal:     'Expires': '-1'
azure.core.pipeline.policies._universal:     'x-ms-request-id': 'f5708903-d1f9-4ac5-98e8-6db02a596b32'
azure.core.pipeline.policies._universal:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
azure.core.pipeline.policies._universal:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
azure.core.pipeline.policies._universal:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
azure.core.pipeline.policies._universal:     'x-ms-correlation-request-id': '68fb5bd8-2ea1-4816-a602-614b192cdabb'
azure.core.pipeline.policies._universal:     'x-ms-routing-request-id': 'NORTHEUROPE:20210428T164249Z:68fb5bd8-2ea1-4816-a602-614b192cdabb'
azure.core.pipeline.policies._universal:     'X-Content-Type-Options': 'nosniff'
azure.core.pipeline.policies._universal:     'Date': 'Wed, 28 Apr 2021 16:42:48 GMT'
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {"error":{"code":"KeyVaultPolicyError","message":"Keyvault policy recoverable is not set"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 566, in handler
    result = cached_put(cmd, setter, **setterargs)
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/usr/local/Cellar/azure-cli/2.22.1/libexec/lib/python3.8/site-packages/azure/mgmt/storage/v2021_01_01/operations/_storage_accounts_operations.py", line 440, in update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (KeyVaultPolicyError) Keyvault policy recoverable is not set
</pre>
</details>

HSM Key Details:

```json
{
  "attributes": {
    "created": "2021-04-28T15:51:48+00:00",
    "enabled": true,
    "expires": null,
    "exportable": false,
    "notBefore": null,
    "recoverableDays": 90,
    "recoveryLevel": "Recoverable+Purgeable",
    "updated": "2021-04-28T15:51:48+00:00"
  },
  "key": {
    "crv": null,
    "d": null,
    "dp": null,
    "dq": null,
    "e": "AQAB",
    "k": null,
    "keyOps": [
      "wrapKey",
      "unwrapKey"
    ],
    "kid": "https://<snip>.managedhsm.azure.net/keys/<snip>/<snip>",
    "kty": "RSA-HSM",
    "n": "<snip>",
    "p": null,
    "q": null,
    "qi": null,
    "t": null,
    "x": null,
    "y": null
  },
  "managed": null,
  "tags": null
}
```

HSM Details:

```json 
{
  "id": "/subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.KeyVault/managedHSMs/<snip>",
  "location": "northeurope",
  "name": "<snip>",
  "properties": {
    "createMode": null,
    "enablePurgeProtection": true,
    "enableSoftDelete": true,
    "hsmUri": "https://<snip>.managedhsm.azure.net/",
    "initialAdminObjectIds": [
      "<snip>"
    ],
    "provisioningState": "Succeeded",
    "softDeleteRetentionInDays": 90,
    "statusMessage": "The Managed HSM is provisioned and ready to use.",
    "tenantId": "<snip>"
  },
  "resourceGroup": "<snip>",
  "sku": {
    "family": "B",
    "name": "Standard_B1"
  },
  "tags": {},
  "type": "Microsoft.KeyVault/managedHSMs"
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create Managed HSM and enable purge protection
- Create Storage Account
- Assign Storage Account MSI to HSM Access role for required key
- Run command above

## Expected Behavior
Enable BYOK CMK using the key stored in the Managed HSM

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.1

Extensions:
aks-preview 0.5.10
azure-devops 0.18.0
resource-graph 1.1.0
custom-providers 0.1.0
interactive 0.4.4
costmanagement 0.1.1

```

**Comment by yonzhan** [comment]
Storage

**Comment by grahamhayes** [comment]
@yonzhan - Is this a feature request, or a bug? It seems like something is failing. The error needing to be better is a related issue (and also a bug I would argue)

**Comment by yonzhan** [comment]
@Juliehzl will help with this issue after Labor Day holiday in China.

**Comment by evelyn-ys** [comment]
Not sure if 'Keyvault policy recoverable' has been enabled for MHSM. Need service team to confirm.

**Comment by evelyn-ys** [comment]
hsm keys should be "recoverable+purgeable" now
