### ISSUE TITLE
az functionapp update fails with Attribute error

### ISSUE THREAD

**Issue by PolarFox** [Azure/azure-cli#17947]
## Describe the bug
Tried working with functionapp update command. Traceback followed.

**Command Name**
`az functionapp update`

**Errors:**
```
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 231, in invoke
azure\cli\core\commands\__init__.py, ln 657, in execute
azure\cli\core\commands\__init__.py, ln 720, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 712, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 61, in _ex_handler
azure\cli\core\commands\__init__.py, ln 691, in _run_job
azure\cli\core\commands\__init__.py, ln 328, in __call__
azure\cli\core\commands\arm.py, ln 566, in handler
azure\cli\core\commands\__init__.py, ln 447, in cached_put
azure\cli\core\commands\__init__.py, ln 441, in _put_operation
azure\cli\command_modules\appservice\custom.py, ln 694, in set_functionapp
AttributeError: 'NoneType' object has no attribute 'kind'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp update -n {} -g {}`

## Expected Behavior
Not traceback.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

Extensions:
application-insights 0.1.13
interactive 0.4.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by kmadof** [comment]
Not sure if this is releated, but I got this exception

```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1518, in create_functionapp_slot
    poller = client.web_apps.begin_create_or_update_slot(resource_group_name, name, slot_def, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 12138, in begin_create_or_update_slot
    **kwargs
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 12067, in _create_or_update_slot_initial
    body_content = self._serialize.body(site_envelope, 'Site')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 623, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

Calling:

```
az functionapp deployment slot create --name $functionAppNameWithSlots --resource-group $rgName --slot "staging"
```

**Comment by apawast** [comment]
@PolarFox has this issue persisted for you?

**Comment by apawast** [comment]
@kmadof this issue is unrelated, please open a separate ticket. Thanks!
