### ISSUE TITLE
az functionapp create fails when using Docker az cli

### ISSUE THREAD

**Issue by vdesabou** [Azure/azure-cli#17948]
## Describe the bug

I've this [test](https://github.com/vdesabou/kafka-docker-playground/blob/master/connect/connect-azure-functions-sink/azure-functions.sh) which used to work successfully but now is failing constantly with stack trace below.
It fails when using docker version of `az` CLI (latest image `mcr.microsoft.com/azure-cli`)

**Command Name**

```
$ docker run -v /tmp:/tmp -v $HOME/.azure:/home/az/.azure -e HOME=/home/az --rm -i mcr.microsoft.com/azure-cli az functionapp create --verbose --consumption-plan-location $AZURE_REGION --name $AZURE_FUNCTIONS_NAME --resource-group $AZURE_RESOURCE_GROUP --runtime node --storage-account $AZURE_STORAGE_NAME --runtime-version 12 --functions-version 3
```

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/usr/local/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/util.py", line 512, in shell_safe_json_parse
    return ast.literal_eval(json_or_dict_string)
  File "/usr/local/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    AzureWebJobsDashboard=DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=pgvsaboulinf611;AccountKey=xxxxxxxxxxxxx/EotBQDGpN0T3bNR/tY4Fj9Xd94kQQ/V2UCvt59waq799EQ0sDjug5Qn1MofRQ8+9WsSMwJg==
                         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 807, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 3039, in create_function
    ['AzureWebJobsDashboard={}'.format(con_string)])
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 256, in update_app_settings
    temp = shell_safe_json_parse(s)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/util.py", line 525, in shell_safe_json_parse
    parent_proc = get_parent_proc_name().lower()
AttributeError: 'NoneType' object has no attribute 'lower'
To open an issue, please run: 'az feedback'
INFO: Command ran in 10.787 seconds (init: 0.256, invoke: 10.531)
```

Note: if not using `az` docker version (image `mcr.microsoft.com/azure-cli`), it works fine locally with my `az` CLI (same version):

```
az --version              
azure-cli                         2.22.1

core                              2.22.1
telemetry                          1.0.6

Extensions:
storage-preview                    0.2.9

Python location '/usr/local/Cellar/azure-cli/2.22.1/libexec/bin/python'
Extensions directory '/Users/vsaboulin/.azure/cliextensions'

Python (Darwin) 3.8.9 (default, Apr  3 2021, 01:51:00) 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

Main difference is Python versions:

```
$ az --version
azure-cli                         2.22.1

core                              2.22.1
telemetry                          1.0.6

Extensions:
storage-preview                    0.2.9

Python location '/usr/local/Cellar/azure-cli/2.22.1/libexec/bin/python'
Extensions directory '/Users/vsaboulin/.azure/cliextensions'

Python (Darwin) 3.8.9 (default, Apr  3 2021, 01:51:00) 
[Clang 12.0.0 (clang-1200.0.32.29)]

$ docker run -v /tmp:/tmp -v $HOME/.azure:/home/az/.azure -e HOME=/home/az --rm -i mcr.microsoft.com/azure-cli az --version                 

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
azure-cli                         2.22.1

core                              2.22.1
telemetry                          1.0.6

Extensions:
storage-preview                    0.2.9

Python location '/usr/local/bin/python'
Extensions directory '/home/az/.azure/cliextensions'

Python (Linux) 3.6.10 (default, May 21 2020, 05:54:39) 
[GCC 9.2.0]
```

## To Reproduce:

Run https://github.com/vdesabou/kafka-docker-playground/blob/master/connect/connect-azure-functions-sink/azure-functions.sh

## Expected Behavior

Works as before

## Environment Summary

```
macOS-11.2.1-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.1

Extensions:
storage-preview 0.2.9

```

**Comment by yonzhan** [comment]
route to service team

**Comment by apawast** [comment]
@gzuber could you please help investigate this?

**Comment by vdesabou** [comment]
This is still failing. Let me know if you require any additional details, this is 100% reproducible so I can easily add debug traces for example.

**Comment by vdesabou** [comment]
I don't see anymore the issue with latest version:

```
docker run -v /tmp:/tmp -v $HOME/.azure:/home/az/.azure -e HOME=/home/az --rm -i mcr.microsoft.com/azure-cli az "version"
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "storage-preview": "0.2.9"
  }
}
```

Closing
