### ISSUE TITLE
az group broke on Linux

### ISSUE THREAD

**Issue by gekap** [Azure/azure-cli#17956]
I tried the command 
```
az group
```
and I got the below exception

```
LIInternalError: The command failed with an unexpected error. Here is the traceback:
The operation 'azure.mgmt.resource.resources.v2020_10_01.operations#ResourceGroupsOperations.delete' is invalid.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'ResourceGroupsOperations' has no attribute 'delete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 584, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 262, in parse_args
    return super(CLICommandParser, self).parse_args(args)
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 289, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.9/argparse.py", line 1940, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1219, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 289, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1940, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1104, in __call__
    parser.print_help()
  File "/usr/lib/python3.9/argparse.py", line 2560, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 200, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 249, in format_help
    self.cli_help.show_help(self.prog.split()[0],
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help.py", line 171, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/usr/lib/python3/dist-packages/knack/help.py", line 254, in __init__
    child.load(options)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help.py", line 299, in load
    loader.versioned_load(self, options)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/usr/lib/python3/dist-packages/knack/help.py", line 199, in load
    description = getattr(options, 'description', None)
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 242, in __getattribute__
    self.description = self._description() \
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 795, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.resource.resources.v2020_10_01.operations#ResourceGroupsOperations.delete' is invalid.
```

**Comment by yonzhan** [comment]
ARM
