### ISSUE TITLE
Azure CLI version 2.23.0 - Error

### ISSUE THREAD

**Issue by tirendra-reddy** [Azure/azure-cli#17982]
Hi

```
The command failed with an unexpected error. Here is the traceback:
DLL load failed while importing win32file: The specified module could not be found.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/feedback/custom.py", line 581, in handle_feedback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/feedback/custom.py", line 562, in _prompt_issue
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/feedback/custom.py", line 370, in _build_issue_info_tup
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/feedback/custom.py", line 434, in _get_az_version_summary
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 345, in get_az_version_string
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 332, in _get_local_versions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 256, in get_installed_cli_distributions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/__init__.py", line 9, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/__init__.py", line 4, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/portalocker.py", line 9, in <module>
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```
After the upgrade to version 2.23.0 this happens will all commands,  the CLI seems to be missing a module.

System Spec:
OS : Windows 10
Python V3.9.4

Hope you can find a fix soon.

Thanks,
T

**Comment by jiasli** [comment]
Azure CLI currently doesn't work with Python 3.9 yet. We are working on it (https://github.com/Azure/azure-cli/pull/17368). 😉

**Comment by tirendra-reddy** [comment]
Thank you @jiasli . I will wait for the PR to go through :)

**Comment by jiasli** [comment]
Sorry I misunderstood the issue. Investigating in https://github.com/Azure/azure-cli/issues/17986.
