### ISSUE TITLE
Exception while running az webapp log tail 

### ISSUE THREAD

**Issue by freedev** [Azure/azure-cli#18014]
A couple of days ago I started to have the following error while running 

az webapp log tail --name <appname> --resource-group <resource group>

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 2343, in _get_log
    logger.warning(chunk.decode(encoding='utf-8', errors='replace')
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'end'
```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
looking in to the issue.

**Comment by Kotasudhakarreddy** [comment]
Able to repro this issue. Will consider this future releases.

**Comment by Kotasudhakarreddy** [comment]
#17988 this should fix the issue reported. Fix would be released in [S187](https://github.com/Azure/azure-cli/milestone/105).

**Comment by Kotasudhakarreddy** [comment]
@hbgaldino yes the issue is persists in `azure-cli 2.23.0`. Fix will be pushed in the next release   [S187](https://github.com/Azure/azure-cli/milestone/105)( will be released on 05/25/2021)

**Comment by freedev** [comment]
Hi, waiting for the next release is there any valuable alternative to az webapp log tail  ?

**Comment by Kotasudhakarreddy** [comment]
@freedev  It is a breaking change in CLI release `2.23.0`. To unblock your current work, you can downgrade to CLI `2.22.0` or below. It should work.

**Comment by freedev** [comment]
@Kotasudhakarreddy thanks for the suggestion. I have macos, and with `brew` it seems is not possibile install an older version of `azure-cli`... I'll update the thread if I find one.

**Comment by freedev** [comment]
Update - I found this suggestion https://github.com/Azure/azure-cli/issues/13331 but trying to install the 2.22.0 I found this:

```
brew install -s https://raw.githubusercontent.com/azclibot/homebrew-core/azcli2.22.0/Formula/azure-cli.rb
Traceback (most recent call last):
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of azure-cli formula file from an arbitrary URL is unsupported!  (UsageError)
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of azure-cli formula file from an arbitrary URL is unsupported!  (UsageError)
```

**Comment by florianchevallier** [comment]
@freedev : did you find a way to downgrade on Mac ?

**Comment by freedev** [comment]
Hi @florianchevallier , I had to remove azure-cli with brew and install it (globally) with pip3

    brew uninstall azure-cli
    pip3 install azure-cli==2.22.0
