### ISSUE TITLE
az webapp log tail issue

### ISSUE THREAD

**Issue by rcarbajal01** [Azure/azure-cli#18020]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Command Name
az webapp log tail

Errors:

The command failed with an unexpected error. Here is the traceback:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2345, in _get_log
    .decode(std_encoding, errors='replace'), end='')  # each line of log has CRLF.
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'end'

**To Reproduce**
z webapp log tail  --resource-group learn-565a662c-2e49-4d9a-9fab-7db9d0ac5631 --name <your app name>

**Expected behavior**
Receive the "Welcome, you are now connected to log-streaming service" message.

**Environment summary**
<!--- Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Azure Cloud Shell
Sandbox

**Additional context**
https://docs.microsoft.com/en-us/learn/modules/capture-application-logs-app-service/5-view-live-application-logging-activity-with-the-log-streaming-service-using-azure-cli

**Comment by BigCat20196** [comment]
Hi @rcarbajal01 After my test, I can get the expected results.

Environment Summary:
- Python 3.8.8
- Installer: pip
- azure-cli 2.23.0

Pls check the prerequisites for using the `az webapp log tail` command.
You need to create a webapp and app service plan first.

Exanples:

> az group create -n MyResourceGroup -l westus
> az appservice plan create --resource-group MyResourceGroup -n Myplan
> az webapp create -g MyResourceGroup  -p Myplan-n MyUniqueAppName
> az webapp log tail --name MyUniqueAppName  --resource-group MyResourceGroup 

Please refer to https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az_webapp_log_tail

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
#17988 this should fix the issue reported. Fix would be released in [S187](https://github.com/Azure/azure-cli/milestone/105). Post release please file a new issue if this is still a problem.

**Comment by Json2CSharp** [comment]
i did the same, i created a web app and app service plan and tried to run the command but still give the error above
