### ISSUE TITLE
Azure deployment using Bicep and French characters: 'utf-8' codec can't decode byte 0x82

### ISSUE THREAD

**Issue by slapointe** [Azure/azure-cli#18029]
## Describe the bug

**Command Name**
`az deployment mg create`

**Errors:**

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 791, in what_if_deploy_arm_template_at_management_group
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 935, in _prepare_deployment_what_if_properties
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 903, in _prepare_deployment_properties_unmodified
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 82, in run_bicep_command  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 212, in _run_command    
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1197: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 100, in handle_template_based_exception
AttributeError: 'UnicodeDecodeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially       
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 102, in handle_template_based_exception
knack.util.CLIError: 'utf-8' codec can't decode byte 0x82 in position 1197: invalid start byte

cli.azure.cli.core.azclierror: 'utf-8' codec can't decode byte 0x82 in position 1197: invalid start byte
az_command_data_logger: 'utf-8' codec can't decode byte 0x82 in position 1197: invalid start byte
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03D8F388>]
az_command_data_logger: exit code: 1

## To Reproduce:
save this content to a bicep file named _azcli-bicep-bug.bicep_
```
targetScope = 'managementGroup'

var policyAssignmentName = substring(replace(guid('0473574d-2d43-4217-aefe-941fcdf7e684'), '-', ''), 0, 23)

resource policyAssignment 'Microsoft.Authorization/policyAssignments@2020-09-01' = {
  name: policyAssignmentName
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/0473574d-2d43-4217-aefe-941fcdf7e684'
    displayName: 'AzCLI and Bicep encoding bug'
    description: 'AzCLI and Bicep encoding bug'
    enforcementMode: 'Default'
    parameters: {
      listOfAllowedLocations: {
        value: [
          'canadaeast'
          'canadacentral'
        ]
      }
    }
    nonComplianceMessages:[
      {
        message: 'La région qui a été choisi n\'est pas valide...'
      }
    ]
  }
}
```
az deployment mg what-if --management-group-id mymg --location canadaeast -f .\azcli-bicep-bug.bicep

## Expected Behavior
Success deploying the bicep file with French characters

## Environment Summary
azure-cli 2.23.0
Bicep CLI version 0.3.255 (589f0375df)

Extensions:
[]

## Additional Context
Performing a `az bicep build` to generate the json + `az deployment mg create` from that json works

**Comment by yonzhan** [comment]
route to service team

**Comment by zhoxing-ms** [comment]
@shenglol This is a issue related to bicep, could you please take a look~

**Comment by shenglol** [comment]
Yeah I'll fix this. We should change 'utf-8' to unicode.
