### ISSUE TITLE
WebApp:staticwebapp appsettings set broken in az-cli 2.23.0

### ISSUE THREAD

**Issue by aressler38** [Azure/azure-cli#18033]
## Describe the bug

**Command Name**
`az staticwebapp appsettings set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
create_or_update_static_site_function_app_settings() missing 1 required positional argument: 'app_settings'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 124, in set_staticsite_function_app_settings
TypeError: create_or_update_static_site_function_app_settings() missing 1 required positional argument: 'app_settings'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az staticwebapp appsettings set -n staticwebappname --setting-names foo=bar`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

Extensions:
application-insights 0.1.13

```

**Comment by yonzhan** [comment]
route to service team to help with.

**Comment by Kotasudhakarreddy** [comment]
Assigning to static web apps team to triage & fix. Thanks @anthonychu , @miwebst

**Comment by aressler38** [comment]
Did you fix it yet?

**Comment by miwebst** [comment]
The PR is merged, @panchagnula do you know when this will become available?

**Comment by panchagnula** [comment]
> The PR is merged, @panchagnula do you know when this will become available?

Upcoming //BUILD release https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#app-service
