### ISSUE TITLE
issue with az login -i

### ISSUE THREAD

**Issue by c5289076** [Azure/azure-cli#18037]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:



Traceback (most recent call last):
  File "/opt/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -i`

## Environment Summary
```
Linux-4.4.180-94.113-default-x86_64-with-SuSE-12-x86_64
Python 2.7.17
Shell: bash

azure-cli 2.0.81

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by MaddyMicrosoft** [comment]
Closing as stale. The stack trace references Python 2.7, which Azure CLI dropped support for years ago. If `az login -i` still fails on a supported Python version, please open a fresh issue.
