### ISSUE TITLE
"az vm image terms accept" failure in AzureUSGovernment soverign cloud when using --urn to identify image 

### ISSUE THREAD

**Issue by avlind** [Azure/azure-cli#18044]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When connected with to Azure Government using `az cli` when I go to accept the terms of a Marketplace image with `az vm image terms accept --urn {your image urn}` it throws the below error:
>(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2020-12->01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, >2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019->07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01'. The supported locations are 'usgoviowa, >usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'.

**To Reproduce**
1. Log into Azure Government 
2. Launch a new Cloud Shell session
3. Run the following command: ` az vm image terms accept --urn cisco:cisco-csr-1000v:16_10-payg-sec:16.10.120190108 --debug`

**Expected behavior**
I would expect to be able to accept the license terms programmatically with the above command.

**Environment summary**
1. Leveraging AZ CLI 2.23.0, from within an Azure Government Cloud Shell Session (pre-installed)

**Additional context**
N/A

**Comment by yungezz** [comment]
seems caused by reosurce API version upgrading.

**Comment by adamdost-msft** [comment]
Super excited for this to be patched in August. Lot's of automation around marketplace terms agreement. Please reach out if you need someone to test the newest build

**Comment by zhoxing-ms** [comment]
@avlind @adamdost-msft  Hi, it seems that this issue cannot be reproduced in the latest version of CLI. Could you please upgrade the CLI version and then try again? You can use the command `az upgrade` to upgrade CLI.

If you can reproduce this issue in the latest version, please send me the debug log by email. My email address is Zhou.Xing@microsoft, thanks

**Comment by adamdost-msft** [comment]
Current version i'm using is 2.26.0 as that's what is available via CloudShell in MAG. If 2.26.1 has this fixed then I will need to have the CloudShell team upgrade it to 2.26.1.

**Comment by zhoxing-ms** [comment]
@adamdost-msft This issue is not fixed in `2.26.1`. Actually, this issue can't be reproduced in version `2.26.0` on my side. Can you reproduce it in version `2.26.0`?

**Comment by adamdost-msft** [comment]
Yes I can. Here is the debug output from version 2.26.0 in Azure Government. 

````bash
cli.knack.cli: Command arguments: ['vm', 'image', 'terms', 'accept', '--urn', 'cisco:cisco-csr-1000v:16_10-payg-sec:16.10.120190108', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa470483bf8>, <function OutputProducer.on_global_arguments at 0x7fa4703b9730>, <function CLIQuery.on_global_arguments at 0x7fa4703d1840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.123        45       235
cli.azure.cli.core: Total (1)                 0.123        45       235
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.082         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.082         1         1
cli.azure.cli.core: Loaded 46 groups, 236 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vm image terms accept
cli.azure.cli.core: Command table: vm image terms accept
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa46fefc048>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/adam/.azure/commands/2021-07-24.22-06-49.vm_image_terms_accept.271.log'.
az_command_data_logger: command args: vm image terms accept --urn {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa46ff20f28>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fa46fe89158>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa46fe891e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa46fe892f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa4703b97b8>, <function CLIQuery.handle_query_parameter at 0x7fa4703d18c8>,<function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fa46fe890d0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa46fe89268>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SubscriptionClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.usgovcloudapi.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.usgovcloudapi.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2464
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.usgovcloudapi.net/'}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2464
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.usgovcloudapi.net/'}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.usgovcloudapi.net/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7167979e-eccb-11eb-a890-0a580af4cd9f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm image terms accept'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--urn --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (DEB) azsdk-python-azure-mgmt-resource/18.0.0 Python/3.6.10 (Linux-5.4.0-1055-azure-x86_64-with-debian-10.2) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.usgovcloudapi.net:443
urllib3.connectionpool: https://management.usgovcloudapi.net:443 "GET /subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations?api-version=2019-11-01 HTTP/1.1" 200 735
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '43335063-551c-442b-8bbf-62822dc585d3'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '43335063-551c-442b-8bbf-62822dc585d3'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'USDODEAST:20210724T220650Z:43335063-551c-442b-8bbf-62822dc585d3'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 24 Jul 2021 22:06:50 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '735'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/global","name":"global","displayName":"Global","regionalDisplayName":"Global","metadata":{"regionType":"Logical","regionCategory":"Other"}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usdodcentral","name":"usdodcentral","displayName":"USDoD Central","regionalDisplayName":"(US) USDoD Central","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-93.6091","latitude":"41.6005","physicalLocation":"Iowa","pairedRegion":[{"name":"usdodeast","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usdodeast"}]}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usdodeast","name":"usdodeast","displayName":"USDoD East","regionalDisplayName":"(US) USDoD East","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-78.3875","latitude":"36.6676","physicalLocation":"Virginia","pairedRegion":[{"name":"usdodcentral","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usdodcentral"}]}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovarizona","name":"usgovarizona","displayName":"USGov Arizona","regionalDisplayName":"(US) USGov Arizona","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-112.0740","latitude":"33.4484","physicalLocation":"Arizona","pairedRegion":[{"name":"usgovtexas","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovtexas"}]}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgoviowa","name":"usgoviowa","displayName":"USGov Iowa","regionalDisplayName":"(US) USGov Iowa","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-93.6208","latitude":"41.5908","physicalLocation":"Iowa","pairedRegion":[{"name":"usgovvirginia","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovvirginia"}]}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovtexas","name":"usgovtexas","displayName":"USGov Texas","regionalDisplayName":"(US) USGov Texas","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-98.4936","latitude":"29.4241","physicalLocation":"Texas","pairedRegion":[{"name":"usgovarizona","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovarizona"}]}},{"id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovvirginia","name":"usgovvirginia","displayName":"USGov Virginia","regionalDisplayName":"(US) USGov Virginia","metadata":{"regionType":"Physical","regionCategory":"Other","geographyGroup":"US","longitude":"-79.8164","latitude":"37.3719","physicalLocation":"Virginia","pairedRegion":[{"name":"usgovtexas","id":"/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/locations/usgovtexas"}]}}]}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.usgovcloudapi.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.usgovcloudapi.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2464
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.usgovcloudapi.net/'}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2464
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.usgovcloudapi.net/'}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.usgovcloudapi.net/subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/providers/Microsoft.Compute/locations/global/publishers/cisco/artifacttypes/vmimage/offers/cisco-csr-1000v/skus/16_10-payg-sec/versions/16.10.120190108?api-version=2021-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7167979e-eccb-11eb-a890-0a580af4cd9f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm image terms accept'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--urn --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (DEB) azsdk-python-azure-mgmt-compute/21.0.0 Python/3.6.10 (Linux-5.4.0-1055-azure-x86_64-with-debian-10.2) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.usgovcloudapi.net:443
urllib3.connectionpool: https://management.usgovcloudapi.net:443 "GET /subscriptions/827ed6d0-6545-432d-ac5e-75c4078da112/providers/Microsoft.Compute/locations/global/publishers/cisco/artifacttypes/vmimage/offers/cisco-csr-1000v/skus/16_10-payg-sec/versions/16.10.120190108?api-version=2021-03-01 HTTP/1.1" 400 564
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '05354e05-8ce1-4d21-af95-f004dd27b619'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '05354e05-8ce1-4d21-af95-f004dd27b619'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'USDODEAST:20210724T220650Z:05354e05-8ce1-4d21-af95-f004dd27b619'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 24 Jul 2021 22:06:49 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '564'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'usgoviowa, usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1949, in accept_terms
    return _accept_cancel_terms(cmd, urn, publisher, offer, plan, True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1925, in _accept_cancel_terms
    publisher, offer, plan = _terms_prepare(cmd, urn, publisher, offer, plan)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1912, in _terms_prepare
    image = show_vm_image(cmd, urn)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1862, in show_vm_image
    return client.virtual_machine_images.get(location, publisher, offer, sku, version)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/compute/v2021_03_01/operations/_virtual_machine_images_operations.py", line 108, in get
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'usgoviowa, usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'.

cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'usgoviowa, usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'.
az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'usgoviowa, usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa46fefc268>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.735 seconds (init: 0.109, invoke: 1.626)
telemetry.save: Save telemetry record of length 3594 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/adam/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
````

**Comment by adamdost-msft** [comment]
We can start an email thread internally if you'd prefer @zhoxing-ms

**Comment by zhoxing-ms** [comment]
@adamdost-msft Yes, you can delete the debug log information here, and we will exchange these information by internally email later. My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
> (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2021-03-01' for type 'locations/publishers'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2020-09-30, 2020-12-01, 2021-03-01, 2021-04-01, 2021-07-01'. The supported locations are 'usgoviowa, usgovvirginia, usdodcentral, usdodeast, usgovtexas, usgovarizona'

Because this error is returned by the REST service, it is a service issue. Therefore, Therefore, it needs the service team to investigate the cause of this error
**'x-ms-correlation-request-id': '05354e05-8ce1-4d21-af95-f004dd27b619'**

**Comment by jaylabell** [comment]
@olayemio Could you please look into this issue?

**Comment by olayemio** [comment]
@amjads1 can you look into this as it is a Marketplace image issue

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by yonzhan** [comment]
@amjads1 any update for this issue?

**Comment by amjads1** [comment]
@yonzhan I think you are already part of the on-going email thread on this topic for latest updates.

@avlind We have some potential leads where the issue could be but trying to validate with the CLI team and update back as soon as I have more information.

**Comment by zhoxing-ms** [comment]
@avlind Could you use `az upgrade --yes` to upgrade the CLI to latest version **(2.28.0)** and try again? If you still can reproduce this issue, please add parameter `--debug` to the original command and send me the printed debug log. 
My email address is Zhou.Xing@microsoft.com, thanks

**Comment by adamdost-msft** [comment]
Followed up internally

**Comment by avlind** [comment]
Confirming, that in my test using 2.28.0 CLI from Azure Government Cloud Shell, I was able to run the previously impacted CLI command to accept terms based on URN.

**Comment by zhoxing-ms** [comment]
@avlind OK, so may I ask can this issue be closed?
