### ISSUE TITLE
keyvault hsm backup fails

### ISSUE THREAD

**Issue by dano0b** [Azure/azure-cli#18049]
## Describe the bug

My user got HSM Admin permissions, I tried to give further permissions. I tried the empty HSM and with multiple created Keys.

HSM is initialized following: https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli

**Command Name**
`az keyvault backup start`

**Errors:**
```
Operation returned an invalid status 'OK'

```

more details:
```
adal-python: {} - CacheDriver:Returning token from cache lookup, AccessTokenId: {}', RefreshTokenId: b'{}'
urllib3.connectionpool: https://{}.managedhsm.azure.net:443 "POST /backup?api-version=7.2-preview HTTP/1.1" 202 216
urllib3.connectionpool: https://{}.managedhsm.azure.net:443 "GET /backup/{}/pending HTTP/1.1" 200 235
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 482, in run
    self._poll()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 521, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 121, in keyvault_command_handler
    LongRunningOperation(self.command_loader.cli_ctx, 'Starting {}'.format(name))(result))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 999, in __call__
    raise exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 987, in __call__
    result = poller.result()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 502, in run
    error=err
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'OK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 138, in keyvault_command_handler
    return keyvault_exception_handler(self.command_loader, ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 51, in keyvault_exception_handler
    raise CLIError(ex)
knack.util.CLIError: Operation returned an invalid status 'OK'

cli.azure.cli.core.azclierror: Operation returned an invalid status 'OK'
az_command_data_logger: Operation returned an invalid status 'OK'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- sas=`az storage container generate-sas --account-name {} --as-user --auth-mode login --expiry 2021-05-13 --name {} --permissions acdlrw`
- `az keyvault backup start --hsm-name {} --storage-account-name {} --blob-container-name {} -t $sas`

## Expected Behavior
* some objects in the storage container
* successful backup
* no error message

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
azure-devops 0.18.0
account 0.2.1

```

**Comment by yungezz** [comment]
hi @houk-ms, could you have a look?

**Comment by dano0b** [comment]
Wonder why this is a feature-request since it is a documented process from https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/backup-restore#full-backup .

**Comment by evelyn-ys** [comment]
Service Attention for LRO return invalid status 'OK'

**Comment by vasanthrajams** [comment]
This has been fixed already. Requesting to use the the latest SDK and try again.

**Comment by dano0b** [comment]
It would have been great to inform when this was fixed and link to that issue. 

Anyway, I had some time to test the backup and restore and it worked with the latest azure cli version. One step closer to use the managed HSM for production.
