### ISSUE TITLE
`az functionapp identity assign` throws "'NoneType' object is not callable" when assigning a user-assigned identity

### ISSUE THREAD

**Issue by jackhorton** [Azure/azure-cli#18077]
## Describe the bug

**Command Name**
`az functionapp identity assign`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 789, in assign_identity
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 706, in assign_identity
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 782, in setter
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp identity assign --subscription {} --resource-group {} --name {} --identities "/my/user/assigned/identity" "[system]"`

## Environment Summary
```
Windows-10-10.0.21376-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

Extensions:
application-insights 0.1.13
azure-devops 0.18.0

```

**Comment by jackhorton** [comment]
I have confirmed that this is a regression in 2.23.0, I can't repro in the 2.22.1 docker container

**Comment by whephner** [comment]
We are seeing this in az webapp identity as well. and it does work in 2.22.1 as well.

**Comment by panchagnula** [comment]
This was reported on a previous version as well https://github.com/Azure/azure-cli/issues/17296

**Comment by yungezz** [comment]
#14287
