### ISSUE TITLE
az webapp log tail not working at all

### ISSUE THREAD

**Issue by Json2CSharp** [Azure/azure-cli#18073]
## Describe the bug
1 - Create any dot net core web app
2 - Publish any dotnet core web app from visual studio
3 - try to run `az webapp log tail`

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/hilal/.azure/commands/2021-05-13.14-52-16.webapp_log_tail.230.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 514, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/hilal/.azure/commands/2021-05-13.14-52-16.webapp_log_tail.230.log'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1 - Create any dot net core web app
2 - Publish any dotnet core web app from visual studio
3 - try to run `az webapp log tail`

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by adammpolak** [comment]
I am having this same issue:

```
Configuring default logging for the app, if not already enabled
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 2343, in _get_log
    logger.warning(chunk.decode(encoding='utf-8', errors='replace')
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'end'```

**Comment by Kotasudhakarreddy** [comment]
#17988 this should fix the issue reported. Fix would be released in S187. Post release please file a new issue if this is still a problem.
