### ISSUE TITLE
Python 3.4.1 support?

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1810]
```
root@2f9e71d26478:/usr/src/python# python --version
Python 3.4.1
root@2f9e71d26478:/usr/src/python# pip install azure-cli
...
root@2f9e71d26478:/usr/src/python# az
/usr/local/bin/python: Error while finding spec for 'azure.cli' (<class 'ValueError'>: azure.cli.__spec__ is None)
root@2f9e71d26478:/usr/src/python# 
```

Seeing `Error while finding spec for 'azure.cli' (<class 'ValueError'>: azure.cli.__spec__ is None)` error on Python 3.4.1.

Should investigate.

**Comment by derekbekoe** [comment]
There was a change in import logic in Python 3.4.1 -https://docs.python.org/3/whatsnew/3.4.html#whatsnew-pep-451.

Also, `importlib.find_loader()` was introduced (and then later deprecated) which produces a similar error to above - https://docs.python.org/3/library/importlib.html#importlib.find_loader.

```
>>> importlib.find_loader('pip')
<_frozen_importlib.SourceFileLoader object at 0x7f8c0a1f1a90>
>>> importlib.find_loader('azure')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 70, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: azure.__loader__ is None
>>> importlib.find_loader('azure.cli')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 70, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: azure.cli.__loader__ is None
```

Related:
http://bugs.python.org/issue17099

3.4.1 was released in 2014.
"A newer bugfix release, 3.4.3, is currently available. Its use is recommended."
https://www.python.org/download/releases/3.4.1/

Current recommendation is to upgrade Python version.
