### ISSUE TITLE
Getting an issue while assigning User Identity to Function App using az cli

### ISSUE THREAD

**Issue by ravitellakula** [Azure/azure-cli#18139]
## Describe the bug

**Command Name**
`az functionapp identity assign`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 789, in assign_identity
    webapp = _assign_identity(cmd.cli_ctx, getter, setter, role, scope)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 706, in assign_identity
    resource = setter(resource)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 782, in setter
    webapp.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp identity assign -g {} -n {} --identities {}`

## Environment Summary
```
macOS-11.3.1-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
webapp 0.3.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Hi @ravitellakula sorry you ran into this -- can you try updating to 2.24.0? This should be fixed in that cli version

**Comment by panchagnula** [comment]
this should be fixed - please open a new issue if this still occurs with latest cli version
