### ISSUE TITLE
Error during 'azure site create [name] --git'

### ISSUE THREAD

**Issue by uashra** [Azure/azure-cli#1816]
`$ azure site create Honey-ConUHacks --git`
```
$ cat /home/username/.azure/azure.err
2017-01-21T22:36:02.362Z:
{ Error: The server encountered an internal error. There is a bright chance that the site may be actually created.
Please execute: 'azure site list' to verify that the created site: 'undefined' appears in the list.
 If it does not appear in the list then, retry the request.

  <<< async stack >>>
  at createSite__4 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient.js:294:37)
  at createSite (/usr/lib/node_modules/azure-cli/lib/commands/asm/site.js:402:36)
  at __4 (/usr/lib/node_modules/azure-cli/lib/commands/asm/site.js:244:13)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:814:23)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)
  stack: [Getter/Setter],
  code: 'InternalError',
  statusCode: 500,
  requestId: '71bdb4c9a19b37358c7e2ec371498b8f',
  __frame: 
   { name: 'createSite__4',
     line: 275,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient.js',
     prev: 
      { name: 'createSite',
        line: 382,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/site.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 20,
        col: 35 },
     calls: 0,
     active: false,
     offset: 19,
     col: 36 },
  rawStack: [Getter] }
Error: The server encountered an internal error. There is a bright chance that the site may be actually created.
Please execute: 'azure site list' to verify that the created site: 'undefined' appears in the list.
 If it does not appear in the list then, retry the request.

  <<< async stack >>>
  at createSite__4 (/usr/lib/node_modules/azure-cli/lib/commands/asm/websites/websitesclient.js:294:37)
  at createSite (/usr/lib/node_modules/azure-cli/lib/commands/asm/site.js:402:36)
  at __4 (/usr/lib/node_modules/azure-cli/lib/commands/asm/site.js:244:13)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/serviceclient.js:814:23)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)
```

# References

[1] https://conuhacks.io/

**Comment by johanste** [comment]
This repository is for Azure CLI 2.0. The reported issue is for the xplat CLI. Please open the issue at https://github.com/Azure/azure-xplat-cli/issues.
