### ISSUE TITLE
Bug when I try to run exercise https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

### ISSUE THREAD

**Issue by Andrew-netizen** [Azure/azure-cli#18160]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 390, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 522, in remove_remote_build_app_settings
    should_contain=app_settings_should_contain)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 980, in validate_app_settings_in_scm
    scm_settings = _get_app_settings_from_scm(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 74, in call
    raise exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 70, in call
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1011, in _get_app_settings_from_scm
    return response.json() or {}
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```
## Additional Context

<!--Please don't rem

**Comment by Andrew-netizen** [comment]
This was found when trying to complete the Microsoft Learning course https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Hi @Andrew-netizen sorry you ran into this -- I'm currently looking into some issues we've seen with the `config-zip` command and will update the issue when I know more. Thanks for letting us know!

**Comment by panchagnula** [comment]
@Andrew-netizen was this issue resolved? Does this still repro on the latest version of CLI?
