### ISSUE TITLE
Failure during 'az bicep upgrade'

### ISSUE THREAD

**Issue by bbuchmeier** [Azure/azure-cli#18177]
## Describe the bug

**Command Name**
`az bicep upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/Users/bbuchmeier/.azure/bin/bicep'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 3287, in upgrade_bicep_cli
    ensure_bicep_installation(release_tag=latest_release_tag)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_bicep.py", line 93, in ensure_bicep_installation
    installed_version = _get_bicep_installed_version(installation_path)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_bicep.py", line 171, in _get_bicep_installed_version
    installed_version_output = _run_command(bicep_executable_path, ["--version"])
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_bicep.py", line 205, in _run_command
    process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/bbuchmeier/.azure/bin/bicep'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep upgrade`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by bbuchmeier** [comment]
bump. For more context, I have done  clean install of python, Azure CLI, as well as bicep, and this is still an issue.

**Comment by bbuchmeier** [comment]
Closing this issue. I had to manually delete the /.azure folder on my mac and then do a fresh install of azure-cli as well as bicep. Solved the issue. Not sure why uninstalling bicep and the cli did not remove the files in conflict in the first place.
