### ISSUE TITLE
Error while running Terraform & Git commands

### ISSUE THREAD

**Issue by Prab0101** [Azure/azure-cli#18183]
## Describe the bug

There are 2 issues

Issue1) While trying to clone the repository,  I am getting the following errors

fatal: could not create work tree dir 'terraform-on-azure': No such file or directory

Or

fatal: could not create work tree dir 'terraform-on-azure': Host is down

Issue 2) A normal command on cloudshell is giving following error

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/prabhjot/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 586, in handle_feedback
    show_updates_available(new_line_before=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 434, in show_updates_available
    VERSIONS[_VERSION_CHECK_TIME] = str(datetime.datetime.now())
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/prabhjot/.azure/versionCheck.json

**Command Name**
``Terraform Version``
``git clone``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
@jiasli for awareness
