### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by aleksve** [Azure/azure-cli#18197]
## Describe the bug

**Command Name**
`az iot hub list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2020-03-01 is not available
Traceback (most recent call last):
  File "/home/veksler/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/command_modules/iot/custom.py", line 463, in iot_hub_list
    return client.iot_hub_resource.list_by_subscription()
  File "/usr/lib/python3/dist-packages/azure/mgmt/iothub/_iot_hub_client.py", line 175, in iot_hub_resource
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2020-03-01 is not available

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub list`

## Environment Summary
```
Linux-5.8.0-53-generic-x86_64-with-glibc2.29
Python 3.8.5
Installer: 

azure-cli 2.23.0

Extensions:
azure-iot 0.10.11
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to service team
