### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'api_version'

### ISSUE THREAD

**Issue by aleksve** [Azure/azure-cli#18198]
## Describe the bug

**Command Name**
`az iot hub list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'api_version'
Traceback (most recent call last):
  File "/home/veksler/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/command_modules/iot/_client_factory.py", line 10, in iot_hub_service_factory
    return get_mgmt_service_client(cli_ctx, ResourceType.MGMT_IOTHUB)
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/home/veksler/.local/lib/python3.8/site-packages/azure/cli/core/commands/client_factory.py", line 222, in _get_mgmt_service_client
    client = client_type(cred, subscription_id, **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub list`

## Environment Summary
```
Linux-5.8.0-53-generic-x86_64-with-glibc2.29
Python 3.8.5
Installer: 

azure-cli 2.23.0

Extensions:
azure-iot 0.10.11

```

**Comment by yonzhan** [comment]
route to service team

**Comment by aleksve** [comment]
Possibly because of azure-cli package with version 2.0.81 provided by the universe repository, ref https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
