### ISSUE TITLE
Can't connect with az container exec on some containers

### ISSUE THREAD

**Issue by entrustfunding-dev** [Azure/azure-cli#18214]
## Describe the bug

I can connect using Connect at portal.azure.com. 

I can connect to some other Containers using az container exec. The only thing that I'm noticing is the container instances I can't connect to are running in eastus. 

  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 684, in _cycle_exec_pipe
    sys.stdout.write(data)
TypeError: write() argument must be str, not bytes

**Command Name**
`az container exec`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
write() argument must be str, not bytes
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 623, in container_exec
    _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 666, in _start_exec_pipe
    if not _cycle_exec_pipe(ws):
  File "/usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 684, in _cycle_exec_pipe
    sys.stdout.write(data)
TypeError: write() argument must be str, not bytes

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec --resource-group {} --name {} --exec-command {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0 *

Extensions:
interactive 0.4.4

```

**Comment by entrustfunding-dev** [comment]
decoding data for the write seems to fix this /usr/local/Cellar/azure-cli/2.23.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py 

sys.stdout.write(data.decode("utf-8"))

For the Homebrew install

**Comment by yonzhan** [comment]
route to service team
