### ISSUE TITLE
Creating NodeJS function app throws an error

### ISSUE THREAD

**Issue by jkpl** [Azure/azure-cli#18245]
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/usr/lib64/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 512, in shell_safe_json_parse
    return ast.literal_eval(json_or_dict_string)
  File "/usr/lib64/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    AzureWebJobsDashboard=DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=[REDACTED];AccountKey=[REDACTED]
                         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 3021, in create_function
    update_app_settings(cmd, functionapp.resource_group, functionapp.name,
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 258, in update_app_settings
    temp = shell_safe_json_parse(s)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 525, in shell_safe_json_parse
    parent_proc = get_parent_proc_name().lower()
AttributeError: 'NoneType' object has no attribute 'lower'

```

Note that I deliberately redacted the Azure Storage shared key details.

## To Reproduce:

- `az group create --name {} --location {}`
- `az storage account create --name {} --location {} --resource-group {} --sku Standard_LRS`
- `az functionapp create --resource-group {} --consumption-plan-location {} --runtime node --runtime-version 14 --functions-version 3 --name {} --storage-account {} --os-type Linux --assign-identity '[system]'`

The issue is also reproduced without the `'[system]'` parameter or the whole `--assign-identity` parameter.

## Expected Behavior

Expected the command to complete without any errors and print the function app details. Fortunately, it seems that the function app (along with the consumption plan and app insights) was created successfully. However, it seems that the managed identity wasn't created as would have been expected from the `--assign-identity` flag. A separate `az functionapp identity assign` call is required to complete the managed identity assignment.

## Environment Summary
```
Linux-5.12.5-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.5
Installer: RPM

azure-cli 2.23.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Thanks for reporting this -- I'll take a look and see if I can reproduce

**Comment by jkpl** [comment]
Cheers! Let me know if you need any further insight.

**Comment by panchagnula** [comment]
@jkpl please open a new issue if this is still occurring with the latest version of CLI
