### ISSUE TITLE
cant login after python update on debian buster

### ISSUE THREAD

**Issue by x4FF3** [Azure/azure-cli#18279]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
find_subscriptions_on_login() got an unexpected keyword argument 'scopes'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/command_modules/profile/custom.py", line 161, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
TypeError: find_subscriptions_on_login() got an unexpected keyword argument 'scopes'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.4.106-1-pve-x86_64-with-debian-10.9
Python 3.7.3
Installer: PIP

azure-cli 2.12.0 *

```

**Comment by yonzhan** [comment]
@jiasli for awareness
