### ISSUE TITLE
az container create --file doesn't work (2.24.0)

### ISSUE THREAD

**Issue by SecDWizar** [Azure/azure-cli#18290]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az container create --file doesn't work  on version 2.24.0, without --file it does, on 2.22.1 --file does work
```
cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'ResourcesOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 113, in create_container
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 407, in _create_update_from_file
```

**To Reproduce**
try any of the reference yaml in the docs with 2.24.0 version

**Expected behavior**
aci deployment

**Environment summary**
Windows, regular installer

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by VicOnt22** [comment]
Issue appears when doing example from 
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml

**Comment by jiasli** [comment]
Duplicate of #18276
