### ISSUE TITLE
az container exec failed

### ISSUE THREAD

**Issue by huaqiwen** [Azure/azure-cli#18297]
## Describe the bug

**Command Name**
`az container exec`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
write() argument must be str, not bytes
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 623, in container_exec
    _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 666, in _start_exec_pipe
    if not _cycle_exec_pipe(ws):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 684, in _cycle_exec_pipe
    sys.stdout.write(data)
TypeError: write() argument must be str, not bytes

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec -g {} --name {} --exec-command {}`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.23.0 *

```

**Comment by huaqiwen** [comment]
Tried upgrading az version, no luck:
```
$ az version
{
  "azure-cli": "2.24.0",
  "azure-cli-core": "2.24.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by yonzhan** [comment]
route to service team
