### ISSUE TITLE
Azure CLI az ad app update --id --set throws cannot deserialize error

### ISSUE THREAD

**Issue by vduarteUF** [Azure/azure-cli#18318]
## Describe the bug

**Command Name**
`az ad app update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Cannot deserialize as [OAuth2Permission] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [OAuth2Permission] an object of type <class 'str'>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.DeserializationError: Cannot deserialize as [OAuth2Permission] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in cached_put
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 441, in _put_operation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1090, in patch_application
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/graphrbac/operations/applications_operations.py", line 321, in patch
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [OAuth2Permission] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [OAuth2Permission] an object of type <class 'str'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Return JSON data into a variable using ConvertTo-Json -Compress
- e.g. $json = ConvertTo-Json -InputObject @($oauth2Permissions) -Compress
- concat the app manifest keyword and the serialized JSON string
- `az ad app update --id {} --set "oauth2Permissions=[]"` or
- `az ad app update --id {} --add oauth2Permissions $json`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0 *

```
## Additional Context
https://github.com/Azure/azure-cli/issues/9919#issuecomment-521199577

See the work from an Azure developer above.

I want pass in the json configuration for the oauth2permissions as a serialized string for an existing application. My current workflow includes the command:
```
az ad app update --id --set oauth2Permissions=@{fileName}.json
```
This is a problem because I have to write JSON files to disk in order to read them.

**Comment by vduarteUF** [comment]
@jiasli I included your comment above about generic deserialization. Is there something wrong with the way I'm following your work?

**Comment by vduarteUF** [comment]
I tried implementing generic deserialization as Jiashuo mentioned but I still get an error. Script only works with the following logic:
```powershell
$json = ConvertTo-Json -InputObject @($oauth2Permissions)
$json | Out-File -FilePath .\{fileName}.json
az ad app update --id {xxx} --set oauth2Permissions=@.\{fileName}.json
```
It would be much easier to serialize a JSON string in local memory than have to overwrite files to disk. Will this support be added next patch?

**Comment by vduarteUF** [comment]
I finally figured out how to implement the generic serialization. Y'all can close this issue unless you intend to update the documentation for Microsoft docs or provide better support in the CLI.

**JSON format**
First, the update command can ONLY serialize JSON strings which are escaped with a backslash. For example, I hard code this string for OAuth2Permissions and replace the default values later.
```powershell
$json = '{\"adminConsentDescription\": \"{adminDesc}\",\"adminConsentDisplayName\": \"{adminName}\",\"id\": \"{id}\",\"isEnabled\": true,\"lang\": null,\"origin\": \"Application\",\"type\": \"{type}\",\"userConsentDescription\": \"{userDesc}\",\"userConsentDisplayName\": \"{userName}\",\"value\": \"{value}\"}'
```
**Azure CLI support**
The az update command will throw an error unless the JSON string is perfectly serialized. After that, the structure has to align with an application's manifest. Here are examples of a few ways I have been able to update permissions from a powershell script.
```powershell
az ad app update --id {xxx} --set oauth2Permissions=@{fileName}.json
az ad app update --id {xxx} --set oauth2Permissions=[]
az ad app update --id {xxx} --set oauth2Permissions[0].isEnabled=false
az ad app update --id {xxx} --set oauth2Permissions=[$json]
```

**Comment by jiasli** [comment]
You may always use `--debug` to see how CLI receives the argument.

The `SerializationError` you are seeing is caused by a known PowerShell issue (https://github.com/Azure/azure-cli/issues/15529) which we have documented at https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively.

**Comment by vduarteUF** [comment]
> You may always use `--debug` to see how CLI receives the argument.
> 
> The `SerializationError` you are seeing is caused by a known PowerShell issue (#15529) which we have documented at https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively.

Thanks for the links! I'll remember the --debug parameter in the future. Hopefully this helps anyone until the issue is patched.
