### ISSUE TITLE
aks check acr crash

### ISSUE THREAD

**Issue by phenixita** [Azure/azure-cli#18314]
## Describe the bug
When I try to execute the following command I get an error.

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
invalid literal for int() with base 10: '16+'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1573, in aks_check_acr
ValueError: invalid literal for int() with base 10: '16+'

```

## To Reproduce:
I have a public AKS cluster (no private config) and it's attached to my ACR (with az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-name>).
 
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.0 *

Extensions:
azure-devops 0.18.0
dev-spaces 1.0.5

```

**Comment by phenixita** [comment]
![image](https://user-images.githubusercontent.com/17789308/120310750-04401d80-c2d7-11eb-9d01-c8161acb5ab2.png)

**Comment by yonzhan** [comment]
route to service team
