### ISSUE TITLE
ValueError: time data 

### ISSUE THREAD

**Issue by Tirth27** [Azure/azure-cli#18333]
### **Facing issue when registering for ACR**
> 

## I got the below error when I tried to run

**Command Name**
`az acr login --name <registry-name>`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
time data '2021-06-02T11:50:19.845Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 251, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 411, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 310, in _get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 106, in get_registry_by_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 85, in get_resource_group_name_by_registry_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 40, in _arm_get_resource_by_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/parameters.py", line 138, in get_resources_in_subscription
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2020_10_01/operations/_resources_operations.py", line 474, in get_next
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 211, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/core/policies/_base.py", line 47, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  [Previous line repeated 1 more time]
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_redirect.py", line 158, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 445, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 69, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_tools.py", line 29, in await_result
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_authentication.py", line 93, in on_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/adal_authentication.py", line 101, in get_token
  File "_strptime.py", line 568, in _strptime_datetime
  File "_strptime.py", line 349, in _strptime
ValueError: time data '2021-06-02T11:50:19.845Z' does not match format '%Y-%m-%d %H:%M:%S.%f'

```

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by iamjasonp** [comment]
@CarolineNB can you please take a look? Thank you!

**Comment by CarolineNB** [comment]
Similar issue here with possible workaround: #16457 

It seems to be related to the core library parsing of the datetime. @yungezz, do you mind taking a look? Thank you!

**Comment by jiasli** [comment]
ADAL never returns `expiresOn` in `2021-06-02T11:50:19.845Z` format

https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/35f9e003bed47936a1df3c6eb696691dc1fa91c3/adal/oauth2_client.py#L183-L187

```py
        expires_in = wire_response.get(OAuth2.ResponseParameters.EXPIRES_IN)
        if expires_in:
            now = datetime.now()
            soon = timedelta(seconds=expires_in)
            wire_response[OAuth2.ResponseParameters.EXPIRES_ON] = str(now + soon)
```

See the definition of [`datetime.__str__()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.__str__) and [`datetime.isoformat`](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat).

It is very likely that some other application modified `~/.azure/accessTokens.json` and set `expiresOn` to something like `2021-06-15T15:14:21.082940Z`. I can get the same error by changing `expiresOn`:

```diff
- 2021-06-15 15:14:21.082940
+ 2021-06-15T15:14:21.082940Z
```

**Comment by Tirth27** [comment]
Thank you @jiasli, running `az account clear`  and `az login` solved my issue.

**Comment by marcelo321** [comment]
@jiasli @CarolineNB,

Is there any other solution other than to login again? I use az cli with a lot of scripts and automation and this is totally breaking it, having to log out and log in again is not a very good solution to this problem that comes back every few weeks.

**Comment by jiasli** [comment]
@marcelo321, you may manually edit the `~/.azure/accessTokens.json` file to make the time match ADAL standard, but ADAL-based Azure CLI along with its `~/.azure/accessTokens.json` have been deprecated and not supported anymore. Please see https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows
