### ISSUE TITLE
`cached_put` doesn't work with ARM Extension resources

### ISSUE THREAD

**Issue by jonathan-innis** [Azure/azure-cli#18337]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
My `begin_create_or_update` command is defined as below:
```
 def begin_create_or_update(
        self,
        resource_group_name,  # type: str
        cluster_rp,  # type: Union[str, "_models.Enum0"]
        cluster_resource_name,  # type: Union[str, "_models.Enum1"]
        cluster_name,  # type: str
        flux_configuration_name,  # type: str
        flux_configuration,  # type: "_models.FluxConfiguration"
        **kwargs  # type: Any
    ):
```
Having this number of arguments for extension resources does not seem to be supported as running:
```cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, name, cluster_rp, cluster_type, cluster_name)```
fails with 
```
expected 2 args, got 5: ('joinnis-test', 'my-config', 'Microsoft.Kubernetes', 'connectedClusters', 'my-cluster')
```

**To Reproduce**
Use `cached_put` as described above

**Expected behavior**
`cached_put` and `cached_get` should support resources that have more than the resource_group and resource_name as required parameters for their operations calls

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
```Python
 def begin_create_or_update(
        self,
        resource_group_name,  # type: str
        cluster_rp,  # type: Union[str, "_models.Enum0"]
        cluster_resource_name,  # type: Union[str, "_models.Enum1"]
        cluster_name,  # type: str
        flux_configuration_name,  # type: str
        flux_configuration,  # type: "_models.FluxConfiguration"
        **kwargs  # type: Any
    ):
```
```Python
cached_put(..., resource_group_name, name, cluster_rp, cluster_type, cluster_name)
```
@jonathan-innis Hi, it seems that the parameters passed in the `*args` from method `cached_put` seems not the same as the parameter defined in the operation method `begin_create_or_update`. Please keep them consistent, or use `**kwargs` to pass in parameters

**Comment by zhoxing-ms** [comment]
And the third positional argument should pass in the object to be cached, but the `flux_configuration` looks like is just a parameter defined in method `begin_create_or_update`.

**Comment by zhoxing-ms** [comment]
@jonathan-innis For how to use `cached_put`, please refer to the doc [doc link](https://github.com/Azure/azure-cli/blob/master/doc/command_guidelines.md#overcoming-service-limitations)

**Comment by jonathan-innis** [comment]
> > cached_put(cmd, client.begin_create_or_update, flux_configuration ...)
> 
> And the third positional argument should pass in the object to be cached, but the `flux_configuration` looks like is just a parameter defined in method `begin_create_or_update`.

@zhoxing-ms This is not correct, `flux_configuration` here is the object so this is not the problem

**Comment by jonathan-innis** [comment]
> ```python
>  def begin_create_or_update(
>         self,
>         resource_group_name,  # type: str
>         cluster_rp,  # type: Union[str, "_models.Enum0"]
>         cluster_resource_name,  # type: Union[str, "_models.Enum1"]
>         cluster_name,  # type: str
>         flux_configuration_name,  # type: str
>         flux_configuration,  # type: "_models.FluxConfiguration"
>         **kwargs  # type: Any
>     ):
> ```
> 
> ```python
> cached_put(..., resource_group_name, name, cluster_rp, cluster_type, cluster_name)
> ```
> 
> @jonathan-innis Hi, it seems that the parameters passed in the `*args` from method `cached_put` seems not the same as the parameter defined in the operation method `begin_create_or_update`. Please keep them consistent, or use `**kwargs` to pass in parameters

@zhoxing-ms I have tried the above, but this does not work due to the source in the function [here](https://github.com/Azure/azure-cli/blob/48cc5e5393bcb1c84f51b84114a189d5cd854285/src/azure-cli-core/azure/cli/core/commands/__init__.py#L121)

**Comment by zhoxing-ms** [comment]
@jonathan-innis Hi, this code has not been submitted to the public repository, right? Could you please show me the specific code link for your change?

**Comment by jonathan-innis** [comment]
@zhoxing-ms Sure, this code exists in master too [here](https://github.com/Azure/azure-cli/blob/5975b2312d8f990df66c1a75b3e41f7387afb437/src/azure-cli-core/azure/cli/core/commands/__init__.py#L121)

**Comment by zhoxing-ms** [comment]
@jonathan-innis what I mean is the following code:
> def begin_create_or_update(
        self,
        resource_group_name,  # type: str
        cluster_rp,  # type: Union[str, "_models.Enum0"]
        cluster_resource_name,  # type: Union[str, "_models.Enum1"]
        cluster_name,  # type: str
        flux_configuration_name,  # type: str
        flux_configuration,  # type: "_models.FluxConfiguration"
        **kwargs  # type: Any
    ):
> cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, name, cluster_rp, cluster_type, cluster_name)

**Comment by jonathan-innis** [comment]
ah, got it. Not it is not yet in the public repository. You can view it on a fork [here](https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/joinnis/k8s-config/src/k8s-config/azext_k8s_config/custom.py#L72).

**Comment by zhoxing-ms** [comment]
> And the third positional argument should pass in the object to be cached, but the flux_configuration looks like is just a parameter defined in method begin_create_or_update.

@jonathan-innis Hi, it seems that the position of the parameters passed into `cached_put` does not match the position of the parameters defined in the method `begin_create_or_update`.

You need to adjust the order of parameters as follows, and supplement the missing parameter `flux_configuration,  # type: "_models.FluxConfiguration"`
Before:
```
return cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, name, cluster_rp, cluster_type, cluster_name)
```
Expected:
```
return cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, cluster_rp, cluster_type, cluster_name, name, flux_configuration) # The type of `flux_configuration` must be `_models.FluxConfiguration`
```


For more details about how to use `cached_put`, please refer to the doc [doc link](https://github.com/Azure/azure-cli/blob/master/doc/command_guidelines.md#overcoming-service-limitations)

**Comment by jonathan-innis** [comment]
@zhoxing-ms I have tried this and as mentioned above this can't work because the number of arguments is restricted to 2 arguments for the `resource_group` and the `resource_name`. It looks like this is being tracked for a milestone now though.

**Comment by jonathan-innis** [comment]
Also, the docs for `cached_put` are incorrect and should be updated to reflect the current state of the source

**Comment by zhoxing-ms** [comment]
@jonathan-innis Since there is no parameter `parameters` in the `begin_create_or_update` of SDK, so we need to specify the parameter name for the object to be updated through `setter_arg_name=flux_configuration`.

For example:
```
return cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, cluster_rp, cluster_type, cluster_name, name, setter_arg_name=flux_configuration) # The type of `flux_configuration` must be `_models.FluxConfiguration`
```
Could you please try this again?

**Comment by zhoxing-ms** [comment]
However, I haven't figured out why this problem happened. 
> expected 2 args, got 5: ('joinnis-test', 'my-config', 'Microsoft.Kubernetes', 'connectedClusters', 'my-cluster')

Could you add parameter `--debug` after the command you used, then send the printed information to me by email, my email address is Zhou.Xing@microsoft.com
In addition, the code you gave me is incomplete and there are some comments. Could you upload all your local code in dev environment? I'm going to debug it locally

**Comment by jonathan-innis** [comment]
Sent, also, updated the code to be a working test which you can find [here](https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/joinnis/k8s-config/src/k8s-config/azext_k8s_config/custom.py#L43)

**Comment by zhoxing-ms** [comment]
@jonathan-innis Hi, thanks for your debug log and code. I can reproduce your issue and understand what you mean~

> I have tried this and as mentioned above this can't work because the number of arguments is restricted to 2 arguments for the resource_group and the resource_name.

Yes, your feedback is correct. This is by design: 
In the current `CacheObject`, the following parameters are used to build the path and name of the cache file: [code link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/__init__.py#L148-L156)
`_model_name` and `resource_group` are the last path of the cache file path, and `resource_name` is the name of the cache file, where `_model_name` comes from parsing the return model of the corresponding operation (such as the return model of `FluxConfigurationsOperations` is `FluxConfiguration`, so the `_model_name` is `FluxConfiguration`)

So the existing architecture distinguishes different caches through `cloud_name + subscription_id + resource_group + model_name + resource_name`. Therefore, the granularity of cache is the same model and same resource name under the same resource group, it should be able to satisfy most scenarios.

Therefore, your usage scenario should also only need to pass in `resource_group` and `resource_name` to meet the requirements, right? Such as: `return cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, name)`

**Comment by jonathan-innis** [comment]
Hi @zhoxing-ms, this also does not work. When I make the `--defer` call this is fine; however, when I actually make the call to the operation, it fails with
```
The command failed with an unexpected error. Here is the traceback:
begin_create_or_update() missing 3 required positional arguments: 'cluster_name', 'flux_configuration_name', and 'flux_configuration'
Traceback (most recent call last):
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "c:\users\joinnis.redmond\github\azure-cli-extensions\src\k8s-config\azext_k8s_config\custom.py", line 104, in flux_create_source
    return cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name, name)
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 451, in cached_put
    result = _put_operation()
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\azure\cli\core\commands\__init__.py", line 438, in _put_operation
    result = operation(*extended_args)
TypeError: begin_create_or_update() missing 3 required positional arguments: 'cluster_name', 'flux_configuration_name', and 'flux_configuration'
```

**Comment by zhoxing-ms** [comment]
@jonathan-innis I submitted a PR draft #18683 to fix this issue. Could you try it to see if it can meet your needs?

The way of passing in parameters is as follows:
```Python
cached_put(cmd, client.begin_create_or_update, flux_configuration, resource_group_name=resource_group_name,
           flux_configuration_name=name, cluster_rp=cluster_rp, cluster_resource_name=cluster_type,
           cluster_name=cluster_name, setter_arg_name='flux_configuration')
```

Please note that the only object that can be cached is `flux_configuration`, does this meet your requirements?

**Comment by jonathan-innis** [comment]
Hi @zhoxing-ms, now `put` is working, but I am failing to `get` from the cache

```
flux_configuration = cached_get(self.cmd, self.client.get, resource_group_name, cluster_rp, cluster_type, cluster_name, name)
```

returns

```
(env) PS C:\Users\joinnis.REDMOND\github\azure-cli-extensions> az k8s-config flux kustomization create -g joinnis-test -c friday-demo -n myconfig -t connectedClusters  --defer --kustomization-name here
Command group 'k8s-config flux' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
<azure.cli.core.commands.CacheObject object at 0x0000022196625E50>
(ResourceNotFound) The fluxConfiguration was not found. Name: 'myconfig'.
```

**Comment by zhoxing-ms** [comment]
@jonathan-innis  Actually, my PR didn't change the cache distinguishing logic, so you still just need to pass in parameters `resource_group_name` and `resource_name` to get the cache.
Such as: 
```Python
cached_get(cmd, self.client.get, resource_group_name, flux_configuration_name)
```

**Comment by jonathan-innis** [comment]
@zhoxing-ms That also fails because we need more positional arguments for the get call

```
Traceback (most recent call last):
  File "C:\Users\joinnis.REDMOND\github\azure-cli-extensions\env\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in execute
    raise ex
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 724, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 695, in _run_job
    result = cmd_copy(params)
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "c:\users\joinnis.redmond\github\azure-cli-extensions\src\k8s-config\azext_k8s_config\custom.py", line 49, in flux_config_create_kustomization
    return provider.create_kustomization(resource_group_name, cluster_type, cluster_name, name, kustomization_name,
  File "c:\users\joinnis.redmond\github\azure-cli-extensions\src\k8s-config\azext_k8s_config\providers\FluxConfigurationProvider.py", line 153, in create_kustomization
    flux_configuration = cached_get(self.cmd, self.client.get, resource_group_name, name)
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 428, in cached_get
    return _get_operation()
  File "c:\users\joinnis.redmond\github\zhoxing-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 404, in _get_operation
    result = operation(*args)
TypeError: get() missing 3 required positional arguments: 'cluster_resource_name', 'cluster_name', and 'flux_configuration_name'
```

**Comment by zhoxing-ms** [comment]
Could you send me the debug log (add parameter `--debug` after executed command) by email for this error: https://github.com/Azure/azure-cli/issues/18337#issuecomment-873248210
```
(ResourceNotFound) The fluxConfiguration was not found. Name: 'myconfig'.
```

**Comment by jonathan-innis** [comment]
@zhoxing-ms Just emailed you the error logging with `--debug`

**Comment by zhoxing-ms** [comment]
@jonathan-innis Thank you for your email. I know the cause of this issue.
Please use the previous PR #18683 and try the following way
