### ISSUE TITLE
Az Container Create : 'ResourcesOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by kimmatthiesen** [Azure/azure-cli#18343]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ResourcesOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 113, in create_container
    return _create_update_from_file(cmd.cli_ctx, resource_group_name, name, location, file, no_wait)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 407, in _create_update_from_file
    resource_client.resources.create_or_update,
AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create --resource-group {} --file {}`

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by kimmatthiesen** [comment]
It appeares we are hit by the bug fixed in hotfix #18276,  Azure CLI Version 2.24.2 :  https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli,  and based on what i can see with (Az Version) we are running version 2.24.0 atm..

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by cbseirani** [comment]
I'm getting this same issue - I tried using az upgrade to update the CLI to 2.24.2 - but I'm getting:

2021-06-03T20:01:51.2518056Z ##[section]Starting: Bash Script
2021-06-03T20:01:51.2525416Z ==============================================================================
2021-06-03T20:01:51.2525792Z Task : Bash
2021-06-03T20:01:51.2526109Z Description : Run a Bash script on macOS, Linux, or Windows
2021-06-03T20:01:51.2526402Z Version : 3.182.0
2021-06-03T20:01:51.2526663Z Author : Microsoft Corporation
2021-06-03T20:01:51.2527026Z Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-06-03T20:01:51.2527456Z ==============================================================================
2021-06-03T20:01:51.6162523Z Generating script.
2021-06-03T20:01:51.6200941Z ========================== Starting Command Output ===========================
2021-06-03T20:01:51.6235989Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/e4f2e7dd-63f5-4019-bf08-9723c15a7c6d.sh
2021-06-03T20:01:51.6361454Z Hello world - IM TRYING TO UPDATE THIS THING!
2021-06-03T20:01:53.8066565Z WARNING: Command group ‘config’ is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
2021-06-03T20:01:54.3462976Z WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
**2021-06-03T20:01:54.3463977Z WARNING: Your current Azure CLI version is 2.24.0. It will be updated to 2.24.2.**
2021-06-03T20:01:54.5126665Z Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
2021-06-03T20:01:54.5131711Z Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
2021-06-03T20:01:54.5150125Z Get:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
2021-06-03T20:01:54.5422414Z Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
2021-06-03T20:01:54.7019519Z Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
2021-06-03T20:01:54.7781145Z Hit:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
2021-06-03T20:01:54.8496691Z Get:7 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1012 kB]
2021-06-03T20:01:54.9091972Z Get:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [227 kB]
2021-06-03T20:01:54.9135140Z Get:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.5 kB]
2021-06-03T20:01:54.9152230Z Get:10 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [241 kB]
2021-06-03T20:01:54.9196789Z Get:11 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [35.5 kB]
2021-06-03T20:01:54.9205266Z Get:12 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [456 B]
2021-06-03T20:01:54.9210763Z Get:13 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [779 kB]
2021-06-03T20:01:54.9330808Z Get:14 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [168 kB]
2021-06-03T20:01:54.9347999Z Get:15 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [17.6 kB]
2021-06-03T20:01:54.9364546Z Get:16 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [23.4 kB]
2021-06-03T20:01:54.9365913Z Get:17 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [5888 B]
2021-06-03T20:01:54.9367055Z Get:18 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [648 B]
2021-06-03T20:01:55.1228912Z Get:19 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [687 kB]
2021-06-03T20:01:55.2332707Z Get:20 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [138 kB]
2021-06-03T20:01:55.2362728Z Get:21 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [7780 B]
2021-06-03T20:01:55.2371206Z Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [222 kB]
2021-06-03T20:01:55.2420310Z Get:23 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [32.7 kB]
2021-06-03T20:01:55.2429860Z Get:24 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [456 B]
2021-06-03T20:01:55.2460323Z Get:25 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [588 kB]
2021-06-03T20:01:55.2670638Z Get:26 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [94.6 kB]
2021-06-03T20:01:55.2709283Z Get:27 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [11.5 kB]
2021-06-03T20:01:55.2710735Z Get:28 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [19.9 kB]
2021-06-03T20:01:55.2811321Z Get:29 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [74.7 kB]
2021-06-03T20:02:00.7800396Z Fetched 4740 kB in 1s (3681 kB/s)
2021-06-03T20:02:01.7087003Z Reading package lists…
2021-06-03T20:02:01.8001247Z Reading package lists…
2021-06-03T20:02:01.9831207Z Building dependency tree…
2021-06-03T20:02:01.9848691Z Reading state information…
**2021-06-03T20:02:02.7525064Z azure-cli is already the newest version (2.24.0-1~focal).**
2021-06-03T20:02:02.7525960Z 0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.
2021-06-03T20:02:03.0346861Z WARNING: CLI upgrade failed or aborted.
2021-06-03T20:02:03.3647163Z WARNING: Command group ‘config’ is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
2021-06-03T20:02:03.3937058Z ##[section]Finishing: Bash Script

**Comment by zhoxing-ms** [comment]
@cbseirani Could you please try this workaround https://github.com/actions/virtual-environments/issues/3508#issuecomment-853141701 to upgrade the CLI version?

**Comment by zhoxing-ms** [comment]
This issue is duplicate with #18276, let's discuss in that issue~
