### ISSUE TITLE
az storage fs file list --exclude-dir breaks with --show-next-marker

### ISSUE THREAD

**Issue by jkleint** [Azure/azure-cli#18352]
## Describe the bug

**Command Name**
`az storage fs file list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'dict' object has no attribute 'is_directory'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 352, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/fs_file.py", line 88, in list_fs_files
    return list(f for f in result if not f.is_directory)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/fs_file.py", line 88, in <genexpr>
    return list(f for f in result if not f.is_directory)
AttributeError: 'dict' object has no attribute 'is_directory'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage fs file list --file-system {} --account-name {} --subscription {} --exclude-dir --show-next-marker`

## Expected Behavior

Should return files list as normal without crashing.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.24.2

Extensions:
datafactory 0.3.0
databricks 0.7.2
storage-preview 0.7.3

```
## Additional Context

The design of including the marker where data goes seems broken.  It breaks all kinds of things downstream trying to process this data.  Is there any reason `fs file list` can't use `--continuation-token` like (most of...) the rest of the API, and return a top-level object with the data in one key and the token in another?

**Comment by yonzhan** [comment]
storage
