### ISSUE TITLE
az container create --resource-group myResourceGroup --file test.yaml after using this command in cloudshell I am facing this error, can you please tell the issue

### ISSUE THREAD

**Issue by devopssameer** [Azure/azure-cli#18366]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ResourcesOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 113, in create_container
    return _create_update_from_file(cmd.cli_ctx, resource_group_name, name, location, file, no_wait)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 407, in _create_update_from_file
    resource_client.resources.create_or_update,
AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create --resource-group {} --file {}`

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by connorLaderer** [comment]
Also experiencing this issue, it seems like it started during the 5/28->5/31 weekend as we have a daily work-day job that deploys this and it broke on 5/31 5PM EST with the same error: 'ResourcesOperations' object has no attribute 'create_or_update'.

**Comment by connorLaderer** [comment]
After a bit more searching, seems related to #18276 ?  I upgraded the az cli version on the Microsoft Hosted Agent in Azure Pipelines (it still has 2.24.0, https://github.com/actions/virtual-environments/issues/3508) and it was resolved for me as well.

**Comment by zhoxing-ms** [comment]
Yes, this issue is duplicate with #18276, let's discuss in that issue~
