### ISSUE TITLE
az storage blob list --num-results parameter

### ISSUE THREAD

**Issue by Atraback** [Azure/azure-cli#18379]
## Describe the bug
The --num-results parameter is ignored (after a value of 4615)

I encountered a problem on a machine with az version 2.23, locally I had 2.20 installed, where I did not get the MemoryError as seen below, but actually saw that the output returned all ~150 thousand results there are in the blob storage

I then updated my local version to version 2.24.2 and also got the MemoryError

I've used 'binary search' tactic to determine at what value the --num-results parameter was ignored, 4614 returned within a few seconds, but at 4615 it would take a few minutes before throwing the Error below, I don't know if the value 4615 is just relevant for my case

I first tried to put the value on 5000 (as that's the default said in the documentation) but that also returned all entries, that's why I decided to investigate further

**Command Name**
`az storage blob list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 202, in encode
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- The storage container probably needs a lot of entries
- `az storage blob list --account-name {} --connection-string {} --container-name {} --show-next-marker --num-results 4615 --include m`

## Expected Behavior
It should return 4615 results (or 4616 if the next marker is also returned, which it would in my case)

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

```

**Comment by Atraback** [comment]
As a workaround for my situation, I had locally set the --num-results to 4500, this works for the case above, but for the case where I want to use the --marker parameter i need to put an even lower value (4000 seems to work, I don't have time to find the exact value)

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @Atraback, for the first issue you mentioned when you do not specify --num-results and you have 150 thousands blobs, you see all blobs returned. Could you show me you debug information with `--debug` in your command? I cannot see the issue in my test.

For the second issue you mentioned, MemoryError should be caused by your machine. Here is some information from StackOverflow: https://stackoverflow.com/questions/40399933/memoryerror-when-loading-a-json-file and https://stackoverflow.com/questions/24239613/memoryerror-using-json-dumps.

As you mentioned, you could write scripts to get marker from last item in output and list again. We cannot help with machine limitation.

**Comment by Atraback** [comment]
Hello, I've just retested it locally using the following powershell:

`az storage blob list --account-name $accountName --connection-string $cs --container-name $containerName --show-next-marker --num-results 4500 --include m --query """length(@)"""`

This gives me 16242 items

If I remove the `--include m` option like so:

`az storage blob list --account-name $accountName --connection-string $cs --container-name $containerName --show-next-marker --num-results 4500 --query """length(@)"""`

I get the expected 4501 items, so maybe the `--include m` flag is the issue

I'm not sure whether I can put the output of the --debug in this issue since it appears to contain sensitive information, however comparing the debug information when including the `--include m` with the one without the option shows me that the one with the `--include m` parameter automatically retrieves all results in multiple calls using the marker that is returned

> urllib3.connectionpool: Starting new HTTPS connection (1): (mystorage).blob.core.windows.net:443
urllib3.connectionpool: https://(mystorage).blob.core.windows.net:443 "GET /(container)?restype=container&comp=list&maxresults=4500&include=metadata HTTP/1.1" 200 None
urllib3.connectionpool: https://(mystorage).blob.core.windows.net:443 "GET /(container)?restype=container&comp=list&marker=(marker)&maxresults=4500&include=metadata HTTP/1.1" 200 None
urllib3.connectionpool: https://(mystorage).blob.core.windows.net:443 "GET /(container)?restype=container&comp=list&marker=(marker)&maxresults=4500&include=metadata HTTP/1.1" 200 None
urllib3.connectionpool: https://(mystorage).blob.core.windows.net:443 "GET /(container)?restype=container&comp=list&marker=(marker)&maxresults=4500&include=metadata HTTP/1.1" 200 None
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03406D18>, <function _x509_from_base64_to_hex_transform at 0x03406D60>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult [<function CLIQuery.handle_query_parameter.<locals>.filter_output at 0x046B1268>]
16242



Whereas the one where I don't specify the option only retrieves the result once:

> urllib3.connectionpool: Starting new HTTPS connection (1): (mystorage).blob.core.windows.net:443
urllib3.connectionpool: https://(mystorage).blob.core.windows.net:443 "GET /(container)?restype=container&comp=list&maxresults=4500 HTTP/1.1" 200 None
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x036A6CD0>, <function _x509_from_base64_to_hex_transform at 0x036A6D18>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult [<function CLIQuery.handle_query_parameter.<locals>.filter_output at 0x04942190>]
4501


For good measure here's the first line of the debug with sensitive information redacted
> cli.knack.cli: Command arguments: ['storage', 'blob', 'list', '--account-name', '(...)', '--connection-string', '(...)', '--container-name', '(...)', '--show-next-marker', '--num-results', '4500', '--query', 'length(@)', '--debug']

With `--include m`
> cli.knack.cli: Command arguments: ['storage', 'blob', 'list', '--account-name', '(...)', '--connection-string', '(...)', '--container-name', '(...)', '--show-next-marker', '--num-results', '4500', '--include', 'm', '--query', 'length(@)', '--debug']


And a screenshot
![image](https://user-images.githubusercontent.com/8746841/125423996-f47de298-b901-439d-8134-6dfde705604f.png)
