### ISSUE TITLE
webapps list - Import error

### ISSUE THREAD

**Issue by n9839950** [Azure/azure-cli#18377]
## Describe the bug

**Command Name**
`az webapp list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'KeyInfo' from 'azure.mgmt.web.models' (c:\python39\lib\site-packages\azure\mgmt\web\models\__init__.py)
Traceback (most recent call last):
  File "C:\Users\MananPatelCodify\AppData\Roaming\Python\Python39\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\core\commands\__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\core\__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\core\commands\__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "C:\Users\MananPatelCodify\AppData\Roaming\Python\Python39\site-packages\knack\commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\core\commands\command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\core\commands\command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\mananpatelcodify\appdata\roaming\python\python39\site-packages\azure\cli\command_modules\appservice\custom.py", line 37, in <module>
    from azure.mgmt.web.models import KeyInfo
ImportError: cannot import name 'KeyInfo' from 'azure.mgmt.web.models' (c:\python39\lib\site-packages\azure\mgmt\web\models\__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list --subscription {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.0 *

Extensions:
logic 0.1.3

```

**Comment by yonzhan** [comment]
route to service team

**Comment by n9839950** [comment]
The issue is resolved by reinstalling azure cli. Thanks
