### ISSUE TITLE
Command 'az vm boot-diagnostics get-boot-log' is failing

### ISSUE THREAD

**Issue by pdostal** [Azure/azure-cli#18404]
**Command Name**
`az vm boot-diagnostics get-boot-log`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RetrieveBootDiagnosticsDataResult' object has no attribute 'done'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1555, in get_boot_log
    uris = LongRunningOperation(cmd.cli_ctx)(poller)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 959, in __call__
    while not poller.done():
AttributeError: 'RetrieveBootDiagnosticsDataResult' object has no attribute 'done'

```

## To Reproduce:
- `az vm boot-diagnostics get-boot-log -n {} -g {}`

## Environment Summary
```
Linux-5.3.18-24.43-default-x86_64-with-glibc2.3.4
Python 3.6.12
Installer: RPM

azure-cli 2.24.1 *

```

**Comment by yonzhan** [comment]
Compute
