### ISSUE TITLE
az storage share-rm create fails with (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by pdroz** [Azure/azure-cli#18405]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

We noticed some of our pipelines using the command `az storage share-rm create` started failing.  

I attempted to upgrade az to the newest version using: `az upgrade`
```
❯ az --version
azure-cli                         2.24.2

core                              2.24.2
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
spring-cloud                       2.4.0

Python location '/usr/local/Cellar/azure-cli/2.24.2/libexec/bin/python'
Extensions directory '/Users/pdrozdowski/.azure/cliextensions'

Python (Darwin) 3.8.10 (default, May  4 2021, 03:05:50)
[Clang 12.0.0 (clang-1200.0.32.29)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

```
❯ az storage share-rm create --resource-group rg-name --storage-account storageaccountname --name nfs-env --enabled-protocol NFS --root-squash RootSquash --quota 100 --debug
Argument '--enabled-protocols' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Argument '--root-squash' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:7ab18c4c-501a-00f2-19c2-5c829a000000
Time:2021-06-08T23:59:43.6161901Z
```

Full Debug output:
```
❯ az storage share-rm create --resource-group XXXXXXXX --storage-account XXXXXXXX --name XXXXXXXX --enabled-protocol NFS --root-squash RootSquash --quota 100 --debug
cli.knack.cli: Command arguments: ['storage', 'share-rm', 'create', '--resource-group', 'XXXXXXXX', '--storage-account', 'XXXXXXXX', '--name', 'XXXXXXXX', '--enabled-protocol', 'NFS', '--root-squash', 'RootSquash', '--quota', '100', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x1083ce9d0>, <function OutputProducer.on_global_arguments at 0x108433c10>, <function CLIQuery.on_global_arguments at 0x108456430>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.043        53       246
cli.azure.cli.core: Total (1)                 0.043        53       246
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 53 groups, 246 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage share-rm create
cli.azure.cli.core: Command table: storage share-rm create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x108bfbee0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/pdrozdowski/.azure/commands/2021-06-08.16-49-16.storage_share-rm_create.63419.log'.
az_command_data_logger: command args: storage share-rm create --resource-group {} --storage-account {} --name {} --enabled-protocol {} --root-squash {} --quota {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x108c1e3a0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x108c7ad30>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x108c7adc0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x108c7aee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x108433ca0>, <function CLIQuery.handle_query_parameter at 0x1084564c0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x108c7aca0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x108c7ae50>]
Argument '--enabled-protocols' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Argument '--root-squash' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /Users/pdrozdowski/.azure/accessTokens.json as utf-8-sig
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - Authority:Performing instance discovery: ...
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - Authority:Performing static instance discovery
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - Authority:Authority validated via static instance discovery
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - CacheDriver:Found 4 potential entries.
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - CacheDriver:Resource specific token found.
adal-python: db2ba85b-e76f-46d9-abc8-65d05e4d3f50 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'10E9Y8ttwfS02ue9rDAC8zkOySz3KritPHt172dTs9c=', RefreshTokenId: b'D9cOzXM3HSaxskR/RQr49QM/r1UMMrTTBuWUyM2RF3E='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/37eed708-4bbc-4418-aca7-8c98298dff7d/resourceGroups/XXXXXXXX/providers/Microsoft.Storage/storageAccounts/XXXXXXXX/fileServices/default/shares/XXXXXXXX?api-version=2021-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '90'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '226fd92a-c8b4-11eb-8963-367dda6b67f3'
cli.azure.cli.core.sdk.policies:     'CommandName': 'storage share-rm create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --storage-account --name --enabled-protocol --root-squash --quota --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.24.2 (HOMEBREW) azsdk-python-azure-mgmt-storage/18.0.0 Python/3.8.10 (macOS-10.15.6-x86_64-i386-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"shareQuota": 100, "enabledProtocols": "NFS", "rootSquash": "RootSquash"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/37eed708-4bbc-4418-aca7-8c98298dff7d/resourceGroups/XXXXXXXX/providers/Microsoft.Storage/storageAccounts/XXXXXXXX/fileServices/default/shares/XXXXXXXX?api-version=2021-04-01 HTTP/1.1" 400 202
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '202'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '4479b28d-0e12-43ad-acf8-ba6b08017c78'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7d7d5fbb-834b-469d-ba46-dba3eef4c197'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS:20210608T234917Z:7d7d5fbb-834b-469d-ba46-dba3eef4c197'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 08 Jun 2021 23:49:16 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidHeaderValue","message":"The value for one of the HTTP headers is not in the correct format.\nRequestId:10724943-501a-0006-1cc0-5c496c000000\nTime:2021-06-08T23:49:17.3609985Z"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/file.py", line 24, in create_share_rm
    return _create_share_rm(cmd, client, resource_group_name, account_name, share_name, metadata=metadata,
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/file.py", line 56, in _create_share_rm
    return client.create(resource_group_name=resource_group_name, account_name=account_name, share_name=share_name,
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/mgmt/storage/v2021_04_01/operations/_file_shares_operations.py", line 221, in create
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:10724943-501a-0006-1cc0-5c496c000000
Time:2021-06-08T23:49:17.3609985Z

cli.azure.cli.core.azclierror: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:10724943-501a-0006-1cc0-5c496c000000
Time:2021-06-08T23:49:17.3609985Z
az_command_data_logger: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:10724943-501a-0006-1cc0-5c496c000000
Time:2021-06-08T23:49:17.3609985Z
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x108bfc160>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.412 seconds (init: 0.128, invoke: 1.283)
telemetry.save: Save telemetry record of length 3343 in cache
telemetry.check: Negative: The /Users/pdrozdowski/.azure/telemetry.txt was modified at 2021-06-08 16:45:03.658038, which in less than 600.000000 s


**To Reproduce**
<!--- Steps to reproduce the behavior. --->
Try to run `az storage share-rm create`

**Expected behavior**
<!--- A clear and concise description of what you expected to happen. --->
Resource should be created and HTTP status code 200OK returned.

**Environment summary**
<!--- Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  --->

We reproduced this on my local machine running MacOS and az cli 2.24

We also reproduced this in Azure DevOps pipelines running az cli 2.17, 2.24.

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by yonzhan** [comment]
storage

**Comment by pdroz** [comment]
We were able to resolve this issue. Turns out we forgot to enable this feature in our subscription.
