### ISSUE TITLE
Error running 'az connectedk8s show'

### ISSUE THREAD

**Issue by cloudmadlab** [Azure/azure-cli#18424]
## Describe the bug

I am following this documentation to create a custom location in Azure using the custom location CLI extension:

https://docs.microsoft.com/en-us/azure/azure-arc/data/deploy-data-controller-direct-mode

**Command Name**

az connectedk8s show -g "$ENV:resourceGroup" -n "$ENV:resourceName" --query id -o tsv

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp38-win32.pyd': cannot load library 'C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\administrator\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp38-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\administrator\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 367, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 70, in load_getter_op_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\administrator\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 34, in <module>
    from Crypto.IO import PEM
  File "C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\IO\PEM.py", line 39, in <module>
    from Crypto.Hash import MD5
  File "C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Hash\MD5.py", line 29, in <module>
    _raw_md5_lib = load_pycryptodome_raw_lib("Crypto.Hash._MD5",
  File "C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp38-win32.pyd': cannot load library 'C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\administrator\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp38-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\administrator\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\administrator\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

$ENV:hostClusterId = az connectedk8s show -g "$ENV:resourceGroup" -n "$ENV:resourceName" --query id -o tsv

## Expected Behavior

I assume this should populate the environment variable with the ID of my connected Kubernetes cluster.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

Extensions:
connectedk8s 1.1.3
customlocation 0.1.2
k8s-configuration 1.0.0
k8s-extension 0.4.2

```

**Comment by cloudmadlab** [comment]
After creating this bug, I discovered that the connectedk8s extension had an updated version 1.1.5.  After I updated, the command succeeded.

**Comment by jiasli** [comment]
`Crypto` folder is installed by the **pycryptodome** library required by `connectedk8s`:

https://github.com/Azure/azure-cli-extensions/blob/4efe2eda6c0627e62f99b1de37bbb6b28a30e557/src/connectedk8s/setup.py#L39

```py
DEPENDENCIES = [
    'kubernetes==11.0.0',
    'pycryptodome==3.9.8',
]
```

I installed the latest `connectedk8s` 1.1.7 extension, but couldn't repro:

```
> az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "connectedk8s",
    "path": "C:\\Users\\user1\\.azure\\cliextensions\\connectedk8s",
    "preview": false,
    "version": "1.1.7"
  }
]

> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe"

>>> import sys
>>> sys.path.insert(0, r"C:\Users\user1\.azure\cliextensions\connectedk8s")
>>> from Crypto.Hash import MD5
>>> MD5.__file__
'C:\\Users\\user1\\.azure\\cliextensions\\connectedk8s\\Crypto\\Hash\\MD5.py'
>>>
```

- Does this issue still happen with the latest `connectedk8s`?
- Could you check the content of `C:\Users\<username>\.azure\cliextensions\connectedk8s\Crypto\Hash`?
  ```
  > Get-ChildItem C:\Users\<username>\.azure\cliextensions\connectedk8s\Crypto\Hash\*MD5*

      Directory: C:\Users\<username>\.azure\cliextensions\connectedk8s\Crypto\Hash

  Mode                 LastWriteTime         Length Name
  ----                 -------------         ------ ----
  -a---          2021-08-31    13:52          13312 _MD5.cp38-win32.pyd
  -a---          2021-08-31    13:52           6618 MD5.py
  -a---          2021-08-31    13:52            492 MD5.pyi
  ```

**Comment by jiasli** [comment]
One possible explanation is that `pycryptodome` is installed by one version of Python, but is later imported by another version of Python. For example:

- Install Azure CLI < 2.23.0, which uses Python 3.6.
- Install `pycryptodome` from `connectedk8s` extension. This will install `_MD5.cp36-win32.pyd`.
- Upgrade to Azure CLI >= 2.23.0, which uses Python 3.8 (https://github.com/Azure/azure-cli/pull/17816).
- Run `az connectedk8s` commands which requires `_MD5.cp38-win32.pyd` -> ERROR ❌

So the solution is to reinstall `connectedk8s`:

```
az extension remove --name connectedk8s
extension add --name connectedk8s
```

`pycryptodome` 3.9.8 has different `whl`s for different version of Python `cp35`, `cp36`, ..., `cp39`: https://pypi.org/project/pycryptodome/3.9.8/#files

But the latest `pycryptodome` 3.10.1 uses application binary interface (ABI): https://pypi.org/project/pycryptodome/#files. There is only one `cp35` for each platform and only one`_MD5.pyd` in the `whl` file. A better solution is for `connectedk8s` to use the latest `pycryptodome`, so that upgrading Python will not require re-installing `pycryptodome`.

This issue can also happen if the extension is installed by `azdev`-installed dev-mode Azure CLI, due to the version inconsistency between Python from the virtual environment (same as system Python) and Python from Azure CLI's MSI.
