### ISSUE TITLE
MySQL server restore failed

### ISSUE THREAD

**Issue by dg-tgsw** [Azure/azure-cli#18436]
## Describe the bug

**Command Name**
`az mysql server restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to get source server: (ResourceNotFound) The Resource 'Microsoft.DBForMySQL/servers/flexdisk' under resource group 'thindiskWebL' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/custom.py", line 233, in _server_restore
    source_server_object = client.get(id_parts['resource_group'], id_parts['name'])
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql/operations/_servers_operations.py", line 467, in get
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/opt/az/lib/python3.6/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (ResourceNotFound) The Resource 'Microsoft.DBForMySQL/servers/flexdisk' under resource group 'thindiskWebL' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/custom.py", line 236, in _server_restore
    raise ValueError('Unable to get source server: {}.'.format(str(e)))
ValueError: Unable to get source server: (ResourceNotFound) The Resource 'Microsoft.DBForMySQL/servers/flexdisk' under resource group 'thindiskWebL' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql server restore -g {} -n {} --source-server {} --restore-point-in-time {}`

## Expected Behavior

restoring server1 (--source-server) at specified time (--restore-point-in-time) to new server2 (-n) 
 
## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.2

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```
## Additional Context
The reason is maybe my former issue #18434

**Comment by dg-tgsw** [comment]
... wrong syntax use "az mysql flexible-server restore"
