### ISSUE TITLE
Connect an existing Kubernetes cluster-arc

### ISSUE THREAD

**Issue by samikdatta-gep** [Azure/azure-cli#18469]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp38-win32.pyd': cannot load library 'C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Samik.Datta\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp38-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Samik.Datta\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 27, in <module>
    from Crypto.IO import PEM
  File "C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\IO\PEM.py", line 39, in <module>
    from Crypto.Hash import MD5
  File "C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Hash\MD5.py", line 29, in <module>
    _raw_md5_lib = load_pycryptodome_raw_lib("Crypto.Hash._MD5",
  File "C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._MD5': Trying '_MD5.cp38-win32.pyd': cannot load library 'C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Samik.Datta\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.cp38-win32.pyd', Trying '_MD5.pyd': cannot load library 'C:\Users\Samik.Datta\.azure\cliextensions\connectedk8s\Crypto\Util\..\Hash\_MD5.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Samik.Datta\\.azure\\cliextensions\\connectedk8s\\Crypto\\Util\\..\\Hash\\_MD5.pyd'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

Extensions:
appservice-kube 0.1.8
connectedk8s 0.3.5
customlocation 0.1.0
k8s-extension 0.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
Same as #18424
