### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback: Cannot deserialize duration object., ISO8601Error: Unrecognised ISO 8601 date format: ''

### ISSUE THREAD

**Issue by stefanrothnet** [Azure/azure-cli#18486]
## Describe the bug

**Command Name**
`az monitor metrics alert list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize duration object., ISO8601Error: Unrecognised ISO 8601 date format: ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1872, in deserialize_duration
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isoduration.py", line 91, in parse_duration
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isodatetime.py", line 55, in parse_datetime
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isodates.py", line 203, in parse_date
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 704, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/monitor/v2018_03_01/operations/_metric_alerts_operations.py", line 92, in extract_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1613, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1875, in deserialize_duration
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1872, in deserialize_duration
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isoduration.py", line 91, in parse_duration
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isodatetime.py", line 55, in parse_datetime
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isodates.py", line 203, in parse_date
msrest.exceptions.DeserializationError: Cannot deserialize duration object., ISO8601Error: Unrecognised ISO 8601 date format: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor metrics alert list`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

Extensions:
aks-virtual-node 0.2.0

```

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
The value of evaluationFrequency or windowSize property must be wrong. Could you add `--debug` to show the service response body?
