### ISSUE TITLE
az aks create  with --enable-addons monitoring gives error

### ISSUE THREAD

**Issue by Lukas1v** [Azure/azure-cli#18489]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Creating an AKS cluster via the cli gives error AttributeError: 'DeploymentsOperations' object has no attribute 'create_or_update'

**To Reproduce**
```
    az aks create --name "test" \
                --resource-group sandbox-01 \
                --kubernetes-version 1.21.1 \
                --location westeurope \
                --node-count 1 \
                --enable-addons monitoring
```

**Expected behavior**
AKS cluster created without errors

**Environment summary**
```
az --version
azure-cli                         2.25.0

core                              2.25.0
telemetry                          1.0.6

Extensions:
aks-preview                        0.5.0
healthcareapis                     0.3.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jun 11 2021, 05:19:38) 
[GCC 9.3.0]
```

**Additional context**
Full error traceback:
```
The command failed with an unexpected error. Here is the traceback:
'DeploymentsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/user/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1117, in aks_create
    _ensure_container_insights_for_monitoring(cmd, addon_profiles[CONST_MONITORING_ADDON_NAME])
  File "/home/user/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2294, in _ensure_container_insights_for_monitoring
    validate=False, no_wait=False, subscription_id=subscription_id)
  File "/home/user/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 303, in _invoke_deployment
    return sdk_no_wait(no_wait, smc.create_or_update, resource_group_name, deployment_name, deployment)
AttributeError: 'DeploymentsOperations' object has no attribute 'create_or_update'
```

**Comment by yonzhan** [comment]
route to service team

**Comment by miwithro** [comment]
Hello,
   I was not able to reproduce the failure you have above.  I am running the same cli version and ran the same command you did with success.   Can you please execute again?

**Comment by Lukas1v** [comment]
Hi, I executed the command again but with the same error.

**Comment by miwithro** [comment]
what rights do you have within the subscription?

**Comment by Lukas1v** [comment]
I have owner rights on the subscription. I have a colleague with less rights on the subscription who can execute this command with a similar set-up, but without the aks-preview extension, could this be the culprit?

**Comment by miwithro** [comment]
Good catch.  My preview version is  "aks-preview": "0.5.19"   I see yours is 0.5.0.  Can you upgrade and try again?

**Comment by Lukas1v** [comment]
Upgraded and everything works fine now, thanks!
