### ISSUE TITLE
az group list crashes (also az resource list)

### ISSUE THREAD

**Issue by delian** [Azure/azure-cli#18542]
## Describe the bug

**Command Name**
`az group list`

**Errors:**
```
API version 2020-10-01 does not have operation group 'resource_groups'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/resource/custom.py, ln 1198, in list_resource_groups
    groups = rcf.resource_groups.list(filter=filter_text)
mgmt/resource/resources/_resource_management_client.py, ln 350, in resource_groups
    raise ValueError("API version {} does not have operation group 'resource_groups'".format(api_version))
ValueError: API version 2020-10-01 does not have operation group 'resource_groups'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list -o {}`

## Environment Summary
```
Linux-5.11.0-18-generic-x86_64-with-glibc2.33
Python 3.9.5
Installer: DEB

azure-cli 2.18.0 *

Extensions:
interactive Unknown
azure-devops Unknown

```

**Comment by yonzhan** [comment]
ARM

**Comment by lishaie** [comment]
Happens to me too.
Ubuntu 21.04, x86_64
default python installation (python 3.9.5)
deb installer. azure-cli 2.18.0-1




```

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
API version 2020-10-01 does not have operation group 'resource_groups'
Traceback (most recent call last):                                                                                                               
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke                                                                        
    cmd_result = self.invocation.execute(args)                                                                                                   
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute                                                
    raise ex                                                                                                                                     
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially                                     
    results.append(self._run_job(expanded_arg, cmd_copy))                                                                                        
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job                                               
    six.reraise(*sys.exc_info())                                                                                                                 
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise                                                                             
    raise value                                                                                                                                  
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job                                               
    result = cmd_copy(params)                                                                                                                    
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__                                               
    return self.handler(*args, **kwargs)                                                                                                         
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/resource/custom.py", line 1198, in list_resource_groups
    groups = rcf.resource_groups.list(filter=filter_text)
  File "/usr/lib/python3/dist-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 350, in resource_groups
    raise ValueError("API version {} does not have operation group 'resource_groups'".format(api_version))
ValueError: API version 2020-10-01 does not have operation group 'resource_groups'
```

**Comment by zhoxing-ms** [comment]
@delian @lishaie This issue looks like a historical issue with older version of CLI.
Could you please upgrade the CLI to the latest version and try again? You can execute command `az upgrade` to upgrade
