### ISSUE TITLE
Azure CLI stopped working

### ISSUE THREAD

**Issue by cindyzhu888** [Azure/azure-cli#18556]
## Describe the bug

Azure CLI stopped working with my "Azure Subscription 1" (Subscription ID = 4ab4a6f3-e219-4912-84cb-c7a6196ea04a) with the following error: 
cindy@Azure:~$ az group create --name learn-deploy-acr-rg --location eastus
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/cindy/.azure/commands/2021-06-20.06-23-39.group_create.646.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 514, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/cindy/.azure/commands/2021-06-20.06-23-39.group_create.646.log'

Tried just with "az" and again it's "Read-only file system" error:
cindy@Azure:~$ az
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/cindy/.azure/commandIndex.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 512, in execute
    self.commands_loader.load_command_table(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 479, in load_command_table
    command_index.update(self.command_table)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 595, in update
    self.INDEX[self._COMMAND_INDEX_VERSION] = __version__
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/cindy/.azure/commandIndex.json'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

## Expected Behavior
Azure CLI should just work. 

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```
## Additional Context
I initially deleted the storage account resource group used by the CLI, but have recreated it when I launched the Azure CLI next time. However Azure CLI just stopped working and always gave error of "read-only file system". Is it locked or messed up somewhere? Could you please help restore the functionality? Thanks.

**Comment by cindyzhu888** [comment]
This issue is resolved. I'm closing it.
