### ISSUE TITLE
Deploying Network Watcher Connection Monitor fails with request headers too large

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli#18551]
## Describe the bug

**Command Name**
`az deployment group create`

Deploying an ARM template for resource of type Microsoft.Network/networkWatchers/connectionMonitors fails repeatably.
See Pre-Requisites below for links to the script and template I am trying to get working.
(Note I was also encountering Azure Portal errors trying to deploy a Connection Monitor, which is why I switched to try CLI.)

**Errors:**
```
(DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.

Output from running with --debug follow. Note the response:
HTTP Error 400. The size of the request headers is too long.

===

cli.knack.cli: Command arguments: ['deployment', 'group', 'create', '--subscription', 'e61e4c75-268b-4c94-ad48-237aa3231481', '-n', 'network-watcher', '--verbose', '--debug', '-g', 'NetworkWatcherRG', '--template-file', '../infra-deploy/templates/net.connection-monitor.json', '--parameters', 'location=eastus2', 'networkWatcherName=NetworkWatcher_eastus2', 'connectionMonitorName=cm1']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f896842dbf8>, <function OutputProducer.on_global_arguments at 0x7f896835b730>, <function CLIQuery.on_global_arguments at 0x7f896837a840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.025        38       180
cli.azure.cli.core: Total (1)                 0.025        38       180
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 38 groups, 180 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : deployment group create
cli.azure.cli.core: Command table: deployment group create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f8967e011e0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/pelazem/.azure/commands/2021-06-18.16-47-16.deployment_group_create.182.log'.
az_command_data_logger: command args: deployment group create --subscription {} -n {} --verbose --debug -g {} --template-file {} --parameters {} {} {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f8967e29378>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f8967d7f400>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f8967d7f488>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f8967d7f598>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f896835b7b8>, <function CLIQuery.handle_query_parameter at 0x7f896837a8c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f8967d7f378>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f8967d7f510>]
cli.azure.cli.core.util: attempting to read file ../infra-deploy/templates/net.connection-monitor.json as utf-8-sig
cli.azure.cli.core.util: invalid syntax (<unknown>, line 1)
cli.azure.cli.core.util: invalid syntax (<unknown>, line 1)
cli.azure.cli.core.util: invalid syntax (<unknown>, line 1)
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /home/pelazem/.azure/accessTokens.json as utf-8-sig
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - Authority:Performing instance discovery: ...
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - Authority:Performing static instance discovery
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - Authority:Authority validated via static instance discovery
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - CacheDriver:Found 7 potential entries.
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - CacheDriver:Resource specific token found.
adal-python: e5b3fcac-7d33-45c7-a7d5-ee239f6bf1aa - CacheDriver:Returning token from cache lookup, AccessTokenId: b'Dr8oJOIQXL1eWl6t6gYTMuzjhdmthsYOiuls/V4MT2w=', RefreshTokenId: b'Y81sHZ0sb/UZ4FeMtM/jbiCwtNfY+yF//NP44uWU7m8='
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher/validate?api-version=2020-10-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5ddbf97a-d076-11eb-a753-00155db8d95f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription -n --verbose --debug -g --template-file --parameters'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (DEB) azsdk-python-azure-mgmt-resource/18.0.0 Python/3.6.10 (Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f896619c3c8>, 'parameters': {'location': {'value': 'eastus2'}, 'networkWatcherName': {'value': 'NetworkWatcher_eastus2'}, 'connectionMonitorName': {'value': 'cm1'}}, 'mode': 'Incremental'}}
cli.azure.cli.command_modules.resource.custom: {'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f896619c3c8>, 'parameters': {'location': {'value': 'eastus2'}, 'networkWatcherName': {'value': 'NetworkWatcher_eastus2'}, 'connectionMonitorName': {'value': 'cm1'}}, 'mode': 'Incremental'}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher/validate?api-version=2020-10-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '4ea08569-282e-4ad9-ab47-1f94122dd525'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4ea08569-282e-4ad9-ab47-1f94122dd525'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADAEAST:20210618T204719Z:4ea08569-282e-4ad9-ab47-1f94122dd525'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 18 Jun 2021 20:47:18 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher","name":"network-watcher","type":"Microsoft.Resources/deployments","properties":{"templateHash":"12426936561030444639","parameters":{"location":{"type":"String","value":"eastus2"},"networkWatcherName":{"type":"String","value":"NetworkWatcher_eastus2"},"connectionMonitorName":{"type":"String","value":"cm1"}},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"2021-06-18T20:47:18.9473182Z","duration":"PT0S","correlationId":"4ea08569-282e-4ad9-ab47-1f94122dd525","providers":[{"namespace":"Microsoft.Network","resourceTypes":[{"resourceType":"networkWatchers/connectionMonitors","locations":["eastus2"]}]}],"dependencies":[],"validatedResources":[{"id":"/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus2/connectionMonitors/cm1"}]}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher?api-version=2020-10-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5ddbf97a-d076-11eb-a753-00155db8d95f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription -n --verbose --debug -g --template-file --parameters'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (DEB) azsdk-python-azure-mgmt-resource/18.0.0 Python/3.6.10 (Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f8967a19ef0>, 'parameters': {'location': {'value': 'eastus2'}, 'networkWatcherName': {'value': 'NetworkWatcher_eastus2'}, 'connectionMonitorName': {'value': 'cm1'}}, 'mode': 'Incremental'}}
cli.azure.cli.command_modules.resource.custom: {'properties': {'template': <azure.cli.command_modules.resource.custom.JsonCTemplate object at 0x7f8967a19ef0>, 'parameters': {'location': {'value': 'eastus2'}, 'networkWatcherName': {'value': 'NetworkWatcher_eastus2'}, 'connectionMonitorName': {'value': 'cm1'}}, 'mode': 'Incremental'}}
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher?api-version=2020-10-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher/operationStatuses/08585775576460164782?api-version=2020-10-01'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '475b4549-c123-453f-8356-2f562ce94d3d'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '475b4549-c123-453f-8356-2f562ce94d3d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADAEAST:20210618T204720Z:475b4549-c123-453f-8356-2f562ce94d3d'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 18 Jun 2021 20:47:20 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher","name":"network-watcher","type":"Microsoft.Resources/deployments","properties":{"templateHash":"12426936561030444639","parameters":{"location":{"type":"String","value":"eastus2"},"networkWatcherName":{"type":"String","value":"NetworkWatcher_eastus2"},"connectionMonitorName":{"type":"String","value":"cm1"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2021-06-18T20:47:20.002086Z","duration":"PT0.540943S","correlationId":"475b4549-c123-453f-8356-2f562ce94d3d","providers":[{"namespace":"Microsoft.Network","resourceTypes":[{"resourceType":"networkWatchers/connectionMonitors","locations":["eastus2"]}]}],"dependencies":[]}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher/operationStatuses/08585775576460164782?api-version=2020-10-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5ddbf97a-d076-11eb-a753-00155db8d95f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription -n --verbose --debug -g --template-file --parameters'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.25.0 (DEB) azsdk-python-azure-mgmt-resource/18.0.0 Python/3.6.10 (Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
cli.azure.cli.command_modules.resource.custom: None
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourcegroups/NetworkWatcherRG/providers/Microsoft.Resources/deployments/network-watcher/operationStatuses/08585775576460164782?api-version=2020-10-01 HTTP/1.1" 200 595
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '18b6bed0-fcc0-46bc-ae1b-8727368645cb'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '18b6bed0-fcc0-46bc-ae1b-8727368645cb'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADAEAST:20210618T204750Z:18b6bed0-fcc0-46bc-ae1b-8727368645cb'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 18 Jun 2021 20:47:50 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '595'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.01//EN\\\"\\\"http://www.w3.org/TR/html4/strict.dtd\\\">\\r\\n<HTML><HEAD><TITLE>Bad Request</TITLE>\\r\\n<META HTTP-EQUIV=\\\"Content-Type\\\" Content=\\\"text/html; charset=us-ascii\\\"></HEAD>\\r\\n<BODY><h2>Bad Request - Request Too Long</h2>\\r\\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\\r\\n</BODY></HTML>\\r\\n\"\r\n  }\r\n}"}]}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 482, in run
    self._poll()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 521, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 702, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 999, in __call__
    raise exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 987, in __call__
    result = poller.result()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/opt/az/lib/python3.6/site-packages/azure/core/polling/base_polling.py", line 502, in run
    error=err
azure.core.exceptions.HttpResponseError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 100, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'OperationFailed' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 102, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.

cli.azure.cli.core.azclierror: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
az_command_data_logger: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f8967e01400>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 34.348 seconds (init: 0.173, invoke: 34.175)
telemetry.save: Save telemetry record of length 3352 in cache
telemetry.check: Negative: The /home/pelazem/.azure/telemetry.txt was modified at 2021-06-18 16:45:58.049661, which in less than 600.000000 s


```

## To Reproduce:
I put the exact template (various values hard-coded for testing) and the .sh script that calls it here:
https://github.com/plzm/always-on/blob/connmon/src/infra-deploy/templates/net.connection-monitor.json
https://github.com/plzm/always-on/blob/connmon/src/scripts/net.connection-monitor.sh

## Expected Behavior
The Connection Monitor gets created in NetworkWatcherRG as expected.

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
aks-preview 0.5.14
application-insights 0.1.13
front-door 1.0.14
azure-iot 0.10.10

```

**Comment by yonzhan** [comment]
ARM
