### ISSUE TITLE
what-if fails during change formatting with exception in Azure DevOps but not locally

### ISSUE THREAD

**Issue by mauve** [Azure/azure-cli#18562]
**Describe the bug**
When printing the change an unhandled exception occurs.

```
/usr/bin/az --version
WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.24.0 *

core                              2.24.0 *

telemetry                          1.0.6
Please let us know how we are doing: https://aka.ms/azureclihats

and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
Extensions:
azure-devops                      0.18.0
```

**To Reproduce**
`az deployment sub what-if --debug --name validate-1624284227 --location northeurope --subscription MYSUB --template-file /home/vsts/work/1/s/templates/service.bicep --parameters hideFromConfirmWithWhatIf=true @/tmp/tmp.GW9on7zbIN`
 
**Expected behavior**
No unhandled exception

**Environment summary**
Azure DevOps

**Additional context**
Unhandled exception:

```
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 768, in what_if_deploy_arm_template_at_subscription_scope
    return _what_if_deploy_arm_template_core(cmd.cli_ctx, what_if_poller, no_pretty_print, exclude_change_types)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 833, in _what_if_deploy_arm_template_core
    print(format_what_if_operation_result(what_if_result, cli_ctx.enable_color))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/_formatters.py", line 66, in format_what_if_operation_result
    _format_change_type_legend(builder, what_if_operation_result.changes)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/_formatters.py", line 111, in _format_change_type_legend
    builder.append_line(change_type.value.title())
AttributeError: 'str' object has no attribute 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 100, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'AttributeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)

```

**Comment by mauve** [comment]
Adding `--no-pretty-print --output json` works

**Comment by yonzhan** [comment]
ARM

**Comment by mauve** [comment]
LEG
