### ISSUE TITLE
How to resolve SSL Certificate Error while installing Azure Kubectl CLI in Ubuntu 18.04?

### ISSUE THREAD

**Issue by vinh75002** [Azure/azure-cli#18574]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/az/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/az/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/opt/az/lib/python3.6/http/client.py", line 1423, in connect
    server_hostname=server_hostname)
  File "/opt/az/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/opt/az/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/opt/az/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/az/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 366, in k8s_install_cli
    k8s_install_kubectl(cmd, client_version, install_location, base_src_url)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 384, in k8s_install_kubectl
    version = urlopen(source_url + '/stable.txt', context=context).read()
  File "/opt/az/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/az/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/az/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/az/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location {}`

## Environment Summary
```
Linux-5.4.0-74-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Volatus** [comment]
@vinh75002 Could you retry with a newer version of Python? Might help. Other than that I'd suggest [installing kubectl from official Kubernetes sources for the time being (For Ubuntu)](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management).

Lastly, I'd make sure you have `openssl` installed.

**Comment by jiasli** [comment]
`certificate verify failed` is caused by proxy issue, please see https://github.com/Azure/azure-cli/issues/1572#issuecomment-894029686.
