### ISSUE TITLE
az resource update --set tags throw an error "cli.azure.cli.core.azclierror: Error occurred in deserializing the response body."

### ISSUE THREAD

**Issue by ovidiu10** [Azure/azure-cli#18570]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
az version 2.25.0

**Describe the bug**

running 
az resource update --set tags.'Application'='App1' --ids /subscriptions/********/resourceGroups/rg/providers/Microsoft.Sql/servers/otsql1/databases/otdbsql1
Error occurred in deserializing the response body.

**To Reproduce**
just run the command 

**Expected behavior**
no error in return

**Environment summary**
$ az --version
azure-cli                         2.25.0
core                              2.25.0
telemetry                          1.0.6
Extensions:
aks-preview                       0.5.12
resource-graph                     2.0.0
Python location '\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory '\.azure\cliextensions'
Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

**Additional context**
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: <?xml version="1.0" encoding="utf-8"?><entry xml:base="https://management.eastus2.control.database.windows.
net/v2/ManagementService.Trusted.svc/modules/ServerManagement/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ad
o/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://management.eastus2.control.data
base.windows.net/v2/ManagementService.Trusted.svc/modules/ServerManagement/azureAsyncOperation/c930aeda-0305-41a7-89e8-697316c399a9</id><cat
egory term="Microsoft.SqlServer.Management.Service.Domain.ArmResourceProvider.AzureAsyncOperationResource" scheme="http://schemas.microsoft.
com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="AzureAsyncOperationResource" href="azureAsyncOperation/c930aeda-0305-41a7-89e
8-697316c399a9" /><title /><updated>2021-06-21T20:12:50Z</updated><author><name /></author><content type="application/xml"><m:properties><d:
operationId m:type="Edm.Guid">c930aeda-0305-41a7-89e8-697316c399a9</d:operationId><d:status>Succeeded</d:status><d:error m:type="Microsoft.S
qlServer.Management.Service.Domain.ArmResourceProvider.AzureAsyncOperationResource_ErrorInfo" m:null="true" /></m:properties></content></ent
ry>
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 95, in _as_json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 253, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 255, in result
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 275, in wait
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 192, in _start
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 482, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 518, in _poll
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 561, in update_status
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 261, in get_status
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 97, in _as_json
azure.core.exceptions.DecodeError: Error occurred in deserializing the response body.

cli.azure.cli.core.azclierror: Error occurred in deserializing the response body.
az_command_data_logger: Error occurred in deserializing the response body.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03C40100>]

**Comment by yonzhan** [comment]
ARM

**Comment by ovidiu10** [comment]
thanks @yonzhan

**Comment by zhoxing-ms** [comment]
@ovidiu10 Could you please add parameter `--debug` after the executed command before run it, then please send me the printed information by email. My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by ylashin** [comment]
More context on how to reproduce:
- Try to apply tags on an Azure SQL database
- `az resource tag --tags "CostCenter=Test" --ids $ResourceId  --debug`
- You will find one of the REST calls returning XML instead of JSON
- That REST call is `https://management.azure.com:443/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.Sql/servers/<SqlServerName>/databases/<DatabaseName>/azureAsyncOperation/<SOME-GUID>?api-version=2014-04-01-Preview`

**Comment by zhoxing-ms** [comment]
Yes, thanks for your information, I can reproduce this problem.

> You will find one of the REST calls returning XML instead of JSON

This problem is really caused by this, so it should be a service issue, it needs to be investigated by the service team~

**correlation-id: '9fbc8b74-99cf-41ec-955c-f5052360f792'**
