### ISSUE TITLE
az monitor scheduled-query list: ERROR: Cannot deserialize as [Action] an object of type <class 'dict'>

### ISSUE THREAD

**Issue by dacla42** [Azure/azure-cli#18598]
failing since latest extension update...

{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "alertsmanagement": "0.1.0",
    "application-insights": "0.1.13",
    "scheduled-query": "0.3.0"
  }
}

az monitor scheduled-query list -g rg

az : ERROR: The command failed with an unexpected error. Here is the traceback:
At C:\azureclitaskscript1624352342553_inlinescript.ps1:43 char:19
+ ... uledQuery = az monitor scheduled-query list -g rg ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The comm... the traceback::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: Cannot deserialize as [Action] an object of type <class 'dict'>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 704, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "C:\Users\username\.azure\cliextensions\scheduled-query\azext_scheduled_query\vendored_sdks\azure_mgmt_scheduled_query\operations\_scheduled_query_rules_operations.py", line 164, in extract_data
    deserialized = self._deserialize('ScheduledQueryRuleResourceCollection', pipeline_response)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1442, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.DeserializationError: Cannot deserialize as [Action] an object of type <class 'dict'>

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Fixed in 0.3.1
