### ISSUE TITLE
Local runner docker image set up

### ISSUE THREAD

**Issue by sycao5** [Azure/azure-cli#18661]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2020-11-01-preview is not available
Traceback (most recent call last):
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\command_modules\acr\custom.py", line 251, in acr_login
    login_server, username, password = get_login_credentials(
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 411, in get_login_credentials
    return _get_credentials(cmd,
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 310, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\command_modules\acr\_utils.py", line 108, in get_registry_by_name
    client = cf_acr_registries(cli_ctx)
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\cli\command_modules\acr\_client_factory.py", line 20, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "D:\aidev\AzureMlCli\msftkube\lib\site-packages\azure\mgmt\containerregistry\container_registry_management_client.py", line 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2020-11-01-preview is not available

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.6
Installer: PIP

azure-cli 2.24.2 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by hkuadithya** [comment]
@sycao5  Can you confirm/validate if this issue is occurring with the latest CLI version? You can run `az upgrade` to upgrade CLI to latest version.

**Comment by sycao5** [comment]
Yes, the problem get resolved by running "az upgrade". Thank you. Regards

**Comment by hkuadithya** [comment]
@yonzhan Please close this issue. This was an issue related to CLI, not ACR.

**Comment by yonzhan** [comment]
ACR related CLI commands are owned by service team
