### ISSUE TITLE
Not able to add path to the command

### ISSUE THREAD

**Issue by sushma0550** [Azure/azure-cli#18677]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: 'C:\\Windows\\SysWOW64\\config\\systemprofile\\AppData\\Local\\Jenkins\\.jenkins\\workspace\\e-VOTING\\e-voting.zip'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 400, in enable_zip_deploy_webapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 426, in enable_zip_deploy
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\SysWOW64\\config\\systemprofile\\AppData\\Local\\Jenkins\\.jenkins\\workspace\\e-VOTING\\e-voting.zip'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
use --src parameter to pass the path  see az webapp deployment source config-zip --src
                                       [--ids]
                                       [--name]
                                       [--resource-group]
                                       [--slot]
                                       [--subscription]
                                       [--timeout]
