### ISSUE TITLE
"az aks command invoke" command for kubectl and spinnaker failed with errors.

### ISSUE THREAD

**Issue by james88nguyen** [Azure/azure-cli#18710]
## Describe the bug

**Command Name**
`az aks command invoke`

Full command: `az aks command invoke -g rg-cicd-01 -n dev-spinnaker -c "kubectl -n spinnaker get spinsvc spinnaker -w" -f .`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'provisioning_state'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 2957, in aks_runcommand
    return _print_command_result(cmd.cli_ctx, commandResultFuture.result(300))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 2979, in _print_command_result
    if commandResult.provisioning_state == "Succeeded":
AttributeError: 'NoneType' object has no attribute 'provisioning_state'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks command invoke -g {} -n {} -c {} -f {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.25.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by mbifeld** [comment]
Hi @james88nguyen, I realize this 4-year-old issue never got a meaningful response. Is this still an active issue?

**Comment by mbifeld** [comment]
Closing as outdated based on comment above. Please comment/reopen if this should still be an active issue. Thanks!
