### ISSUE TITLE
How to create virtualDirectories with Azure CLI

### ISSUE THREAD

**Issue by nkzw1** [Azure/azure-cli#18715]
## Describe the bug

**Command Name**
`az webapp config set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1174, in update_site_configs
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config set --name {webapp-name} --resource-group {resource-group-name} --generic-configurations {"virtualApplications":[{"physicalPath":"site\wwwroot\api","preloadEnabled":false,"virtualDirectories":null,"virtualPath":"/api"}]}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0

```

**Comment by yonzhan** [comment]
route to service team
