### ISSUE TITLE
What-if for FrontDoor throws python exception

### ISSUE THREAD

**Issue by miqm** [Azure/azure-cli#18720]
## Describe the bug

**Command Name**
`az deployment group what-if`

**Errors:**
```
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 752, in what_if_deploy_arm_template_at_resource_group
    return _what_if_deploy_arm_template_core(cmd.cli_ctx, what_if_poller, no_pretty_print, exclude_change_types)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 833, in _what_if_deploy_arm_template_core
    print(format_what_if_operation_result(what_if_result, cli_ctx.enable_color))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 67, in format_what_if_operation_result
    _format_resource_changes(builder, what_if_operation_result.changes)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 160, in _format_resource_changes
    _format_resource_changes_in_scope(builder, scope, resource_changes_in_scope_list)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 176, in _format_resource_changes_in_scope
    _format_resource_change(builder, resource_change, is_last)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 196, in _format_resource_change
    _format_property_changes(
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 239, in _format_property_changes
    _format_property_change(builder, property_change, max_path_length, indent_level)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 258, in _format_property_change
    _format_property_array_change(builder, children, indent_level + 1)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 342, in _format_property_array_change
    _format_property_changes(
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 239, in _format_property_changes
    _format_property_change(builder, property_change, max_path_length, indent_level)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 255, in _format_property_change
    _format_property_modify(builder, before, after, children, indent_level + 1)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 307, in _format_property_modify
    _format_property_changes(
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 239, in _format_property_changes
    _format_property_change(builder, property_change, max_path_length, indent_level)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 255, in _format_property_change
    _format_property_modify(builder, before, after, children, indent_level + 1)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 318, in _format_property_modify
    _format_indent(indent_level)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/_formatters.py", line 491, in _format_indent
    builder.append(str(Symbol.WHITE_SPACE) * 2 * indent_level)
AttributeError: 'int' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 100, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'AttributeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 102, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: 'int' object has no attribute 'append'

cli.azure.cli.core.azclierror: 'int' object has no attribute 'append'
az_command_data_logger: 'int' object has no attribute 'append'
```

## To Reproduce:
This is most probably related to some specific that I applied for front door - for a simple example this works 

## Expected Behavior
What-if will succeed and show applied changes

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW
azure-cli 2.25.0
```

## Additional Context
I experience this on cli 2.23.0, 2.24.0 and 2.25.0, on MacOS and in Docker.

CorrelationId: ece931bc-0951-400b-92ca-34a3147e24bc

**Comment by miqm** [comment]
I just reviewed what-if output with the fixed cli bug and it turned out it came out because I used invalid variable (my bug), and the deployment would fail anyway.
Nevertheless, the bug in python is still there and it might arise at the point we do not expect.

**Comment by yonzhan** [comment]
route to service team
