### ISSUE TITLE
az acr build 'NoneType' object is not callable in v2.26.0

### ISSUE THREAD

**Issue by lbenton** [Azure/azure-cli#18755]
**Describe the bug**
When running az acr build from latest az cli docker image (2.26.0) inside a gitlab pipeline azcli throws the error "TypeError: 'NoneType' object is not callable"

Works fine when using 2.25.0 image 

**To Reproduce**
Here is the command we use within the docker image (the variables are provided by the CI file)

az acr build --build-arg APP_NAME="${APP_NAME}" --build-arg CI_COMMIT_SHA="${CI_COMMIT_SHA}" --build-arg SKIP_TESTS="${SKIP_TESTS}" --build-arg GITLAB_TOKEN="${GITLAB_TOKEN}" --build-arg BUNDLE_GIT__EON-CDS__DE="oauth2:$GITLAB_TOKEN" --build-arg MIRRORED_REGISTRY="${MIRRORED_REGISTRY}" --build-arg ARTIFACTORY_USER="${ARTIFACTORY_USER}" --build-arg ARTIFACTORY_PASSWORD="${ARTIFACTORY_PASSWORD}" --registry ${ACR_NAME} -t "${APP_NAME}":"${IMG_TAG}" -t "${APP_NAME}":latest . || true

**Expected behavior**
command succeeds and az acr build starts

**Environment summary**
Started from a gitlab CI pipeline (using a gitlab-runner) using azure-cli:latest docker image (as mentioned, works fine if we use 2.25.0 instead of latest)

**Additional context**
Traceback
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 106, in acr_build
    platform=PlatformProperties(
TypeError: 'NoneType' object is not callable

**Comment by yonzhan** [comment]
route to service team

**Comment by benhamiltonpro** [comment]
Experiencing the same issue here when running `az acr run`

```
ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/acr/run.py", line 90, in acr_run
    platform=PlatformProperties(
TypeError: 'NoneType' object is not callable
```

**Comment by Diastro** [comment]
Experiencing the same thing as well.

**Comment by juliusl** [comment]
Looking into this issue.

**Comment by jsntcy** [comment]
As a workaround, you can rollback to previous version:
- For windows installer, you can uninstall current version and install the previous version from https://azcliprod.blob.core.windows.net/msi/azure-cli-2.25.0.msi.
- If you install with `pip`, you can install with `pip install azure-cli=2.25.0`

**Comment by kumarg25** [comment]
I am also facing similar issue with 2.26.0

az acr token delete --name $TOKEN_NAME --registry $REGISTRY_NAME --resource-group $REGISTRY_RESOURCE_GROUP_NAME --yes is throwing below error

'TokensOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/token.py", line 103, in acr_token_delete
    return client.delete(resource_group_name, registry_name, token_name)
AttributeError: 'TokensOperations' object has no attribute 'delete'

This works fine with lower version.

**Comment by northtyphoon** [comment]
The issue has been fixed a while ago.
