### ISSUE TITLE
az acr build fail to work with Dockerfile in 2.26.0 version

### ISSUE THREAD

**Issue by sscchh2001** [Azure/azure-cli#18754]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
# az acr build --image sample/hello-world:v1 --registry acrname --file Dockerfile .
Packing source code into tar to upload...
Uploading archived source code from '/tmp/build_archive_f3056afbc2994c7e9f312feaf0203965.tar.gz'...
Sending context (221.246 MiB) to registry: acrname...
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Follow the document https://docs.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli?view=azs-2102, install CLI 2.26.0 and try to build image with acr build cmd.
CLI 2.24.2 works well.

- _Put any pre-requisite steps here..._
- `az acr build --image {} --registry {} --file {} {}`

## Environment Summary
```
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.8
Installer: RPM

azure-cli 2.26.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by charliefoxrf** [comment]
I'm also experiencing this issue using the latest CLI version on ubuntu 18.04

**Comment by ahmednuaman** [comment]
Only started experiencing this a few days ago on our CI platform. This is halting production deployments, so a very severe issue.

**Comment by northtyphoon** [comment]
The issue has been fixed a while ago.
