### ISSUE TITLE
az aks check-acr KeyError: 'serverVersion'

### ISSUE THREAD

**Issue by defenestration** [Azure/azure-cli#18762]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 1575, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --acr {} -g {} -n {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.25.0 *

Extensions:
aks-preview 0.5.10
azure-devops 0.18.0
storage-preview 0.7.2
subscription 0.1.4
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@defenestration Apologies for the late reply. I am not able to repro this issue. I was able to successfully validate my ACR access using the below command:

```
az aks check-acr -g MyaksRG -n MyAKSName --acr MyACRName.azurecr.io
Merged "MyAKSName" as current context in C:\Users\******\AppData\Local\Temp\tmp__aa0tlp
[2022-02-14T03:19:36Z] Validating image pull permission: SUCCEEDED
[2022-02-14T03:19:36Z]
Your cluster can pull images from MyACRName.azurecr.io!
```

Here is the AzCLI and Python version I am using in my box. Could you please try to [upgrade the python](https://www.python.org/downloads/) libraries and the [most recent version of](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) Azure CLI version and run the command again ? Awaiting your reply.

```
az --version
azure-cli                         2.33.0
core                                2.33.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.51
ssh                                1.0.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\****\.azure\cliextensions'
Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
Your CLI is up-to-date.

```

**Comment by defenestration** [comment]
This seems to be working now in azure-cli 2.33.1.
