### ISSUE TITLE
APIVersion 2021-04-01 not available in Python3.8 and az cli 2.24.2

### ISSUE THREAD

**Issue by meierale** [Azure/azure-cli#18769]
## Describe the bug
az storage account network-rule add fails with `NotImplementedError: APIVersion 2021-04-01 is not available`

**Command Name**
`az storage account network-rule add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2021-04-01 is not available
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 143, in cf_sa
    return storage_client_factory(cli_ctx).storage_accounts
  File "/usr/lib/python3.8/site-packages/azure/mgmt/storage/_storage_management_client.py", line 413, in storage_accounts
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2021-04-01 is not available

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- install az cli 2.24.x in a python 3.8 environment
- `az storage account network-rule add --resource-group {} --account-name {} --ip-address {}`

## Expected Behavior
Network rule add should work for given storage account.

## Environment Summary
```
Linux-5.10.25-linuxkit-x86_64-with
Python 3.8.10
Installer: PIP

azure-cli 2.24.2 *

Extensions:
ml 2.0.1a3

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
could you show me your `azure-mgmt-storage` version and which cloud you are accessing?

**Comment by meierale** [comment]
According to pip freeze it's 11.2.0
```pip freeze | grep azure-mgmt-storage
azure-mgmt-storage==11.2.0```

So this is too low according to your statement. However I don't remember having installed this manually myself. Should this not be automatically installed with the rest of az-cli?

Regarding the second part of your question: What do you mean with `which cloud are you accessing`?

**Comment by gro1m** [comment]
@meierale @Juliehzl Regarding the cloud it is : 'AzureCloud'.

**Comment by meierale** [comment]
I just noticed something:

- is it possible that az cli and azure python sdk are not compatible with each other?
- we are trying to build and use a docker image which we can use for various scenarios... thus we sometimes want to use az cli, sometimes the python sdk
- I think azure cli and python sdk are using different azure-mgmt-x versions, is that true/possible?

**Comment by Juliehzl** [comment]
> I just noticed something:
> 
> * is it possible that az cli and azure python sdk are not compatible with each other?
> * we are trying to build and use a docker image which we can use for various scenarios... thus we sometimes want to use az cli, sometimes the python sdk. But we want to have the same general docker image for the various scenarios.
> * I think azure cli and python sdk are using different azure-mgmt-x versions, is that true/possible?

Yes, especially when you customize python sdk. Azure CLI has hard python SDK version requirement to make sure all features supported. As I mentioned before, in current azure cli, you need to have `azure-mgmt-storage>=18.0.0`

**Comment by gro1m** [comment]
@Juliehzl It is not only about customization. Basically, it boils down to that
`pip install azureml-core==1.32.0`
and
`pip install azure-cli==2.24.2`
use different package versions and leads to package version requirements conflicts. One should be able to use Azure ML SDK and Azure CLI alongside each other. This does only work well if both support the same versions of azure packages.

**Comment by gro1m** [comment]
@Juliehzl What's more this workaround will (respectively should) not work from pip version 21.1.3 forward, as is detailed in this article https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020:

_The most significant changes to the resolver are:

It will reduce inconsistency: it will no longer install a combination of packages that is mutually inconsistent. In older versions of pip, it is possible for pip to install a package which does not satisfy the declared requirements of another installed package. For example, in pip 20.0, pip install "six<1.12" "virtualenv==20.0.2" does the wrong thing, “successfully” installing six==1.11, even though virtualenv==20.0.2 requires six>=1.12.0,<2 (defined here). The new resolver, instead, outright rejects installing anything if it gets that input.

It will be stricter - if you ask pip to install two packages with incompatible requirements, it will refuse (rather than installing a broken combination, like it did in previous versions).

So, if you have been using workarounds to force pip to deal with incompatible or inconsistent requirements combinations, now’s a good time to fix the underlying problem in the packages, because pip will be stricter from here on out._

**Comment by gro1m** [comment]
@Juliehzl @jsntcy As far as I see it is a bit difficult to tell if this is really a bug, because it occurs if both `azureml-core` and `azure-cli` are installed in the same Python virtual environment. I am not sure what the plans are here, but if they shall not be compatible, then this is probably a non-issue. Otherwise it is :)
