### ISSUE TITLE
Cloud Shell [Errno 5] Input/output error

### ISSUE THREAD

**Issue by yungchou** [Azure/azure-cli#18781]
## Describe the bug
cloudshell bash session no longer working, any az command will fail like the following:

$ az
The command failed with an unexpected error. Here is the traceback:
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 512, in execute
    self.commands_loader.load_command_table(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 475, in load_command_table
    _update_command_table_from_extensions(ext_suppressions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 346, in _update_command_table_from_extensions
    check_version_compatibility(ext.get_metadata())
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/__init__.py", line 154, in get_metadata
    azext_metadata = WheelExtension.get_azext_metadata(ext_dir)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/__init__.py", line 184, in get_azext_metadata
    azext_metadata = json.load(f)
  File "/opt/az/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
OSError: [Errno 5] Input/output error
To open an issue, please run: 'az feedback'

----

Earlier I deleted some containers thought useless in my storage account, zulustore, which I believe possibly causing the issue.
I would like to simply have the cloud shell reset to start from scratch. Thank you.

**Command Name**
``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0 *

Extensions:
vm-repair Unknown
interactive Unknown
azure-iot Unknown
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This issue could be similar to #16529, #14456, #13533, #12505.

Per https://docs.microsoft.com/en-us/azure/cloud-shell/persisting-shell-storage, the Cloud Shell disk image of your `$Home` directory is saved to a **file share**, instead of **blob container**. Deleting blob containers won't affect Cloud Shell.

You may check the file share's location with

```
$ df
Filesystem                                1K-blocks     Used Available Use% Mounted on
//xxstcs.file.core.windows.net/fs20210709   6291456  5242880   1048576  84% /usr/csuser/clouddrive
```

If you delete the file share and restart Cloud Shell, it will automatically create a new one from scratch.

To help us understand the root cause:

1. Could you share the result of `df`?
2. Is it possible to manually read the file with `cat ~/.azure/cliextensions/vm-repair/azext_vm_repair/azext_metadata.json`?

**Comment by jiasli** [comment]
We have opened issue https://github.com/Azure/CloudShell/issues/106 on Cloud Shell side.
