### ISSUE TITLE
"az acs kubernetes get-credentials" should allow for specifying ssh-key

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-cli#1878]
`az acs create` allows one to specify the path to an ssh key.  `az acs kubernetes get-credentials` assumes the key is `~/.ssh/id_rsa`.  This should be configurable.

**Comment by tirithen** [comment]
I'm also having trouble, in my case the original problem is that az refuses to take encrypted keys like most other services does. That suggests that this client is not making use of SSH keys in the way they where intended in the first place.

If az will support encrypted keys, we need a way of pointing to these unencrypted keys since there are no way I will unencrypt my main key.

Even with unencrypted key temporarily placed in /home/user/.ssh I get this (that is after successful login):

```
$ az acs kubernetes get-credentials --resource-group=$RESOURCE_GROUP --name=$SERVICE_NAME
Authentication failed.
Traceback (most recent call last):
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 535, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 552, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/acs_client.py", line 20, in SecureCopy
    ssh.connect(host, username=user, key_filename=key_filename)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/paramiko/client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/paramiko/client.py", line 621, in _auth
    raise saved_exception
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/paramiko/client.py", line 598, in _auth
    allowed_types = set(self._transport.auth_publickey(username, key))
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/paramiko/transport.py", line 1337, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/home/user/bin/azure-cli/lib/python3.6/site-packages/paramiko/auth_handler.py", line 208, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

```

**Comment by Rurouni** [comment]
It would be great if `az acs kubernetes get-credentials` command automatically download and configure ssh key as `gcloud container clusters get-credentials`  does

**Comment by tirithen** [comment]
:up:

Den 16 feb. 2017 17:41 skrev "Sergii Kryvonos" <notifications@github.com>:

**Comment by nerdondon** [comment]
if you do `az acs kubernetes get-credentials --help` you will see that there is a `--ssh-key-file` switch that will allow you to specify the ssh key. is this what you're looking for?

**Comment by jmspring** [comment]
Is there a disconnect here -- maybe in documentation -- as to how to find
said "ssh-key-file".  I've only specified my own keys, but I do know that
if you create a cluster and allow it to create a key, the documentation as
to where said key is isn't clear.

**Comment by brendandburns** [comment]
`az acs create -h`

shows:

```
    --ssh-key-value               : SSH key file value or key file path.  Default:
                                    ~\.ssh\id_rsa.pub.
```

Which I think is what you need. I'm closing this issue, please re-open if more is needed.

**Comment by yueguoguo** [comment]
Hi @brendandburns I am trying --ssh-key-value with ~/.ssh/id_rsa.pub, but get an error saying

```
Deployment failed. Provided ssh key () is invalid or non-existent.
```

Any idea about what might be the reason? Many thanks!

**Comment by torosgo** [comment]
@yueguoguo please check id_rsa.pub file format. For example create one with "ssh-keygen -t rsa" and compare with the one that already exist.

**Comment by yueguoguo** [comment]
@torosgo It's been a while but still thanks for getting back to the question. 😄
