### ISSUE TITLE
appservice-kube extension for azure-cli stopped working on v2.26.0 from today

### ISSUE THREAD

**Issue by monojit18** [Azure/azure-cli#18797]
## Describe the bug
_appservice-kube_ extension for azure-cli stopped working on v2.26.0 from today
This is actually a blocker for our Arc workshop preparing for our sessions - as I can not create appservice Kube environment, I can not proceed with the subsequent steps to deploy apps, functions etc.

**Command Name**
`az appservice kube create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/monojitdattams/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 90, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "/Users/monojitdattams/.azure/cliextensions/appservice-kube/azext_appservice_kube/vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az appservice kube create --resource-group {} --name {} --custom-location {} --static-ip {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.0

Extensions:
dev-spaces 1.0.6
connectedk8s 1.1.5
azure-iot 0.10.13
azure-firewall 0.11.0
dev-spaces-preview 0.1.6
k8s-extension 0.4.3
azure-devops 0.18.0
appservice-kube 0.1.20
virtual-wan 0.2.6
customlocation 0.1.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by apwestgarth** [comment]
This is something we are tracking and working on resolution.  However for now our guidance is to use an earlier version of Azure CLI i.e. 2.25, 2.24.  We are updating documentation to reflect this limitation at this time.

**Comment by monojit18** [comment]
> This is something we are tracking and working on resolution. However for now our guidance is to use an earlier version of Azure CLI i.e. 2.25, 2.24. We are updating documentation to reflect this limitation at this time.

@apwestgrath:
Thanks for the suggestion
I could finally downgrade the CLI version to 2.25.0 using _pip3 install azure-cli==2.25.0_ as Ia m on Mac and HomeBrew did not allow me to install the older versions!

The _az appservice kube_ commands started working but I noticed one peculiar thing - 
_az connectedk8s_ set of commands started failing!

So, that kind of puts me in a spot where a set of commands are working in 2.26.0 whereas appservice piece is fine with 2.25.0
Should I downgrade even further?

I was not sure whether to raise it as a bug...

Also, any tentative date for the fix for 2.26.0?

**Comment by apwestgarth** [comment]
Hi, this should now be resolved after we have released an updated extension this afternoon.  To upgrade:

az extension remove -n appservice-kube
az extension add --yes --source "https://aka.ms/appsvc/appservice_kube-latest-py2.py3-none-any.whl"

**Comment by monojit18** [comment]
This is working fine now.
Thanks @apwestgarth
The fix came on the day of our Spark session and worked seamlessly  :)
