### ISSUE TITLE
'postgres server ad-admin create' fails with display-name and object-id

### ISSUE THREAD

**Issue by alsastre** [Azure/azure-cli#18819]
## Describe the bug
`az postgres server ad-admin create` fails when specifying the display-name and also when specifying the object-id

**Command Name**
`az postgres server ad-admin create`

**Errors:**
```
(InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.
```
Logs in debug (with relevant ids `<OMMITED>`)
```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<OMMITED>/resourceGroups/<OMMITED>/providers/Microsoft.DBForPostgreSQL/servers/<OMMITED>/administrators/activeDirectory?api-version=2017-12-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '155'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '<OMMITED>'
cli.azure.cli.core.sdk.policies:     'CommandName': 'postgres server ad-admin create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --server-name --object-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (HOMEBREW) azsdk-python-mgmt-rdbms/8.1.0b4 Python/3.8.11 (macOS-11.4-x86_64-i386-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"administratorType": "ActiveDirectory", "sid": "<AD GROUP OBJECT ID>", "tenantId": "<TENANT_ID"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT https://management.azure.com/subscriptions/<OMMITED>/resourceGroups/<OMMITED>/providers/Microsoft.DBForPostgreSQL/servers/<OMMITED>/administrators/activeDirectory?api-version=2017-12-01 HTTP/1.1" 400 210
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '210'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '<OMMITED>'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '<OMMITED>'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': '<OMMITED>'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 12 Jul 2021 14:38:45 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"details":[{"code":"InvalidResourceIdSegment","message":"","target":"parameters.properties"}],"code":"InvalidResourceIdSegment","message":"The 'parameters.properties' segment in the url is invalid."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/rdbms/custom.py", line 715, in server_ad_admin_set
    return client.begin_create_or_update(
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/mgmt/rdbms/postgresql/operations/_server_administrators_operations.py", line 203, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/mgmt/rdbms/postgresql/operations/_server_administrators_operations.py", line 153, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.
```
## To Reproduce:
Steps to reproduce the behaviour. Note that argument values have been redacted, as they may contain sensitive information.

- `az postgres server ad-admin create --resource-group {} --server-name {} --display-name {}`
or
- `az postgres server ad-admin create --resource-group {} --server-name {} --object-id {}`

## Expected Behavior
ad-admin successfully defined for the postgresql server.

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.0

Extensions:
azure-firewall 0.11.0
log-analytics-solution 0.1.1
aks-preview 0.5.22
logic 0.1.3
azure-devops 0.18.0
storage-preview 0.7.3
sentinel 0.1.0
scheduled-query 0.3.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by nachoalonsoportillo** [comment]
@alsastre Thanks for having taken the time to create this issue. Apologize for not having responded much earlier. It happens that the REST API administrator/activeDirectory endpoint targeted by this CLI command required that both UPN and Object ID are provided, not only one of them.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please, proceed with closing this one as resolved. Thanks!
