### ISSUE TITLE
general syntax bug / broken function functionality

### ISSUE THREAD

**Issue by tyeth** [Azure/azure-cli#18818]
## Describe the bug
Following this guide, 
https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/user?view=azure-cli-latest#az_functionapp_deployment_user_show 
I was trying to explore why my deployments weren't behaving as expected. I get a spurious error.

**Command Name**
`az functionapp deployment user show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'function' object has no attribute 'metadata'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 363, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 361, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2020_09_01/operations/_web_site_management_client_operations.py", line 114, in get_publishing_user
AttributeError: 'function' object has no attribute 'metadata'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment user show`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Thanks for reporting @tyeth I'll look into this

**Comment by panchagnula** [comment]
@gzuber was this ever resolved?

**Comment by panchagnula** [comment]
Please retry with latest cli version & open new issue if this still repros.

**Comment by tyeth** [comment]
Not worried about it, but still exists
![image](https://user-images.githubusercontent.com/6692083/169672041-25d0b14f-0b85-462b-aa69-50ebb504ab99.png)
