### ISSUE TITLE
AKS planned maintenance preview feature error

### ISSUE THREAD

**Issue by budisrikanth** [Azure/azure-cli#18839]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
create_or_update() missing 1 required positional argument: 'parameters' , while trying to setup a maintenance window on AKS cluster

**az aks maintenanceconfiguration add -g <my-rg>--cluster-name <my-test-cluster> -n default --weekday Wednesday --start-hour 1**
The command failed with an unexpected error. Here is the traceback:
create_or_update() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/b005331/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 919, in aks_maintenanceconfiguration_add
    return aks_maintenanceconfiguration_update_internal(cmd, client, resource_group_name, cluster_name, config_name, config_file, weekday, start_hour)
  File "/Users/b005331/.azure/cliextensions/aks-preview/azext_aks_preview/maintenanceconfiguration.py", line 50, in aks_maintenanceconfiguration_update_internal
    return client.create_or_update(resource_group_name=resource_group_name, resource_name=cluster_name, config_name=config_name, time_in_week=config.time_in_week, not_allowed_time=config.not_allowed_time)
TypeError: create_or_update() missing 1 required positional argument: 'parameters'

**To Reproduce**
az aks maintenanceconfiguration add -g <my-rg> --cluster-name <my-aks-cluster> -n default --weekday Wednesday --start-hour 1

**Expected behavior**
Expected to see a JSON output with scheduled maintenance times

**Environment summary**
az version
{
  "azure-cli": "2.26.0",
  "azure-cli-core": "2.26.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.22"
  }
}

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by mbifeld** [comment]
Hi @budisrikanth, I realize this 4-year-old issue never got a meaningful response. Is this still an active issue?

**Comment by mbifeld** [comment]
Closing as outdated based on comment above. Please comment/reopen if this should still be an active issue. Thanks!
