### ISSUE TITLE
acr build failure

### ISSUE THREAD

**Issue by jafetrgl** [Azure/azure-cli#18834]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/jafet/venv/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/jafet/venv/az/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 106, in acr_build
    platform=PlatformProperties(
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --subscription {} -r {} -t {} -f {} --platform {} {}`

## Environment Summary
```
Linux-5.8.0-59-generic-x86_64-with-glibc2.29
Python 3.8.10
Installer: PIP

azure-cli 2.26.0

Extensions:
subscription 0.1.4
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by dosmanak** [comment]
The issue has been introduced in 2.26.0. Version 2.25.0 is working properly.

**Comment by augustjoergensen** [comment]
This problem is pretty critical since many CI solutions is setup to use the newest version, like on circleci we use circleci/azure-cli@1.2.0

This will automatically use the newest version and thereby all our build automation does not work. The only solution is that we create a private orb that uses a specific version.

**Comment by ncoder** [comment]
I'm stuck on this, unable to deploy.
using github actions.

```txt
2021-07-13T05:39:15.0519727Z Found online and idle hosted runner(s) in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2021-07-13T05:39:15.0519803Z Waiting for a hosted runner in 'organization' to pick this job...
2021-07-13T05:39:20.5539006Z Current runner version: '2.278.0'
2021-07-13T05:39:20.5563403Z ##[group]Operating System
2021-07-13T05:39:20.5564320Z Ubuntu
2021-07-13T05:39:20.5564827Z 20.04.2
2021-07-13T05:39:20.5565295Z LTS
2021-07-13T05:39:20.5565767Z ##[endgroup]
2021-07-13T05:39:20.5566353Z ##[group]Virtual Environment
2021-07-13T05:39:20.5567034Z Environment: ubuntu-20.04
2021-07-13T05:39:20.5567621Z Version: 20210628.1
2021-07-13T05:39:20.5568594Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
2021-07-13T05:39:20.5569947Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210628.1
2021-07-13T05:39:20.5570834Z ##[endgroup]
2021-07-13T05:39:20.5572712Z ##[group]GITHUB_TOKEN Permissions
2021-07-13T05:39:20.5573922Z Actions: write
2021-07-13T05:39:20.5574417Z Checks: write
2021-07-13T05:39:20.5574956Z Contents: write
2021-07-13T05:39:20.5575549Z Deployments: write
2021-07-13T05:39:20.5576216Z Discussions: write
2021-07-13T05:39:20.5576796Z Issues: write
2021-07-13T05:39:20.5577325Z Metadata: read
2021-07-13T05:39:20.5577888Z Packages: write
2021-07-13T05:39:20.5578483Z PullRequests: write
2021-07-13T05:39:20.5579095Z RepositoryProjects: write
2021-07-13T05:39:20.5579761Z SecurityEvents: write
2021-07-13T05:39:20.5580367Z Statuses: write
2021-07-13T05:39:20.5580956Z ##[endgroup]
2021-07-13T05:39:20.5584008Z Prepare workflow directory
2021-07-13T05:39:20.6157721Z Prepare all required actions
2021-07-13T05:39:20.6167922Z Getting action download info
2021-07-13T05:39:20.9749585Z Download action repository 'ncoder/acr-task-github-action@ncoder-debug'
2021-07-13T05:39:22.8826278Z ##[group]Build container for action use: '/home/runner/work/_actions/ncoder/acr-task-github-action/ncoder-debug/Dockerfile'.
2021-07-13T05:39:22.8898893Z ##[command]/usr/bin/docker build -t 8a33c1:3950bef8f0d64859990a752fa94d3b1a -f "/home/runner/work/_actions/ncoder/acr-task-github-action/ncoder-debug/Dockerfile" "/home/runner/work/_actions/ncoder/acr-task-github-action/ncoder-debug"
2021-07-13T05:39:23.7653202Z Sending build context to Docker daemon  13.82kB
2021-07-13T05:39:23.7787724Z 
2021-07-13T05:39:23.7798344Z Step 1/7 : FROM mcr.microsoft.com/azure-cli as runtime
2021-07-13T05:39:23.7799062Z latest: Pulling from azure-cli
2021-07-13T05:39:23.7799631Z 540db60ca938: Already exists
2021-07-13T05:39:23.7800159Z a7ad1a75a999: Pulling fs layer
2021-07-13T05:39:23.7802187Z 8d9a9d314bf5: Pulling fs layer
2021-07-13T05:39:23.7802732Z 8f925a9eaeee: Pulling fs layer
2021-07-13T05:39:23.7803323Z 4af2838ea733: Pulling fs layer
2021-07-13T05:39:23.7803952Z 67c66fcf2472: Pulling fs layer
2021-07-13T05:39:23.7804484Z 4d65be69f739: Pulling fs layer
2021-07-13T05:39:23.7804990Z 972154c2557e: Pulling fs layer
2021-07-13T05:39:23.7805495Z 1e886299a753: Pulling fs layer
2021-07-13T05:39:23.7806018Z 2fe29e15d0d1: Pulling fs layer
2021-07-13T05:39:23.7806523Z 17023a562c21: Pulling fs layer
2021-07-13T05:39:23.7807012Z 4af2838ea733: Waiting
2021-07-13T05:39:23.7807482Z 67c66fcf2472: Waiting
2021-07-13T05:39:23.7807965Z 4d65be69f739: Waiting
2021-07-13T05:39:23.7808409Z 972154c2557e: Waiting
2021-07-13T05:39:23.7808861Z 1e886299a753: Waiting
2021-07-13T05:39:23.7809330Z 2fe29e15d0d1: Waiting
2021-07-13T05:39:23.7809779Z 17023a562c21: Waiting
2021-07-13T05:39:23.7815087Z 8f925a9eaeee: Verifying Checksum
2021-07-13T05:39:23.7898983Z 8f925a9eaeee: Download complete
2021-07-13T05:39:23.7985233Z a7ad1a75a999: Verifying Checksum
2021-07-13T05:39:23.8000087Z a7ad1a75a999: Download complete
2021-07-13T05:39:23.8000696Z 8d9a9d314bf5: Verifying Checksum
2021-07-13T05:39:23.8001289Z 8d9a9d314bf5: Download complete
2021-07-13T05:39:23.8003046Z 4af2838ea733: Verifying Checksum
2021-07-13T05:39:23.8003605Z 4af2838ea733: Download complete
2021-07-13T05:39:23.8004147Z 972154c2557e: Verifying Checksum
2021-07-13T05:39:23.8004725Z 972154c2557e: Download complete
2021-07-13T05:39:23.8226722Z 4d65be69f739: Verifying Checksum
2021-07-13T05:39:23.8227335Z 4d65be69f739: Download complete
2021-07-13T05:39:23.9530700Z 1e886299a753: Verifying Checksum
2021-07-13T05:39:23.9531702Z 1e886299a753: Download complete
2021-07-13T05:39:24.1435916Z 17023a562c21: Verifying Checksum
2021-07-13T05:39:24.1438012Z 17023a562c21: Download complete
2021-07-13T05:39:24.1634130Z a7ad1a75a999: Pull complete
2021-07-13T05:39:24.2182852Z 67c66fcf2472: Verifying Checksum
2021-07-13T05:39:24.2185420Z 67c66fcf2472: Download complete
2021-07-13T05:39:24.9826021Z 2fe29e15d0d1: Verifying Checksum
2021-07-13T05:39:24.9827295Z 2fe29e15d0d1: Download complete
2021-07-13T05:39:26.0421456Z 8d9a9d314bf5: Pull complete
2021-07-13T05:39:26.1108866Z 8f925a9eaeee: Pull complete
2021-07-13T05:39:26.3440463Z 4af2838ea733: Pull complete
2021-07-13T05:39:29.4837289Z 67c66fcf2472: Pull complete
2021-07-13T05:39:30.2648303Z 4d65be69f739: Pull complete
2021-07-13T05:39:30.2649696Z 972154c2557e: Pull complete
2021-07-13T05:39:30.2884948Z 1e886299a753: Pull complete
2021-07-13T05:39:41.8834632Z 2fe29e15d0d1: Pull complete
2021-07-13T05:39:41.9848926Z 17023a562c21: Pull complete
2021-07-13T05:39:41.9906039Z Digest: sha256:dbc5a0322409bdf973b50e4f249eca2ef653b7c9558a903a8778ba3995cbb2b3
2021-07-13T05:39:41.9916470Z Status: Downloaded newer image for mcr.microsoft.com/azure-cli:latest
2021-07-13T05:39:41.9934812Z  ---> e3324745da3e
2021-07-13T05:39:41.9935655Z Step 2/7 : LABEL "repository"="https://github.com/ams0/acr-task-github-action"
2021-07-13T05:39:42.0159923Z  ---> Running in 0a17a99a32bd
2021-07-13T05:39:44.0303189Z Removing intermediate container 0a17a99a32bd
2021-07-13T05:39:44.0303848Z  ---> 4c2799906aee
2021-07-13T05:39:44.0336336Z Step 3/7 : LABEL "maintainer"="Alessandro Vozza"
2021-07-13T05:39:44.0457147Z  ---> Running in 2eddb1a2106a
2021-07-13T05:39:45.9476193Z Removing intermediate container 2eddb1a2106a
2021-07-13T05:39:45.9479550Z  ---> 4b941003cd14
2021-07-13T05:39:45.9520219Z Step 4/7 : ADD entrypoint.sh /entrypoint.sh
2021-07-13T05:39:47.8670464Z  ---> e589be54be12
2021-07-13T05:39:47.8741646Z Step 5/7 : RUN ["chmod", "+x", "/entrypoint.sh"]
2021-07-13T05:39:47.8815665Z  ---> Running in d03d37ca1639
2021-07-13T05:39:50.1848438Z Removing intermediate container d03d37ca1639
2021-07-13T05:39:50.1849457Z  ---> 20a2578672e5
2021-07-13T05:39:50.1850135Z Step 6/7 : ENTRYPOINT ["/entrypoint.sh"]
2021-07-13T05:39:50.2080345Z  ---> Running in dc514ae96f62
2021-07-13T05:39:52.0891946Z Removing intermediate container dc514ae96f62
2021-07-13T05:39:52.0892621Z  ---> 4559a26637c4
2021-07-13T05:39:52.0893023Z Step 7/7 : FROM runtime
2021-07-13T05:39:52.0893416Z  ---> 4559a26637c4
2021-07-13T05:39:52.0893827Z Successfully built 4559a26637c4
2021-07-13T05:39:52.0949518Z Successfully tagged 8a33c1:3950bef8f0d64859990a752fa94d3b1a
2021-07-13T05:39:52.0962624Z ##[endgroup]
2021-07-13T05:39:52.1260091Z ##[group]Run ncoder/acr-task-github-action@ncoder-debug
2021-07-13T05:39:52.1260834Z with:
(...)
2021-07-13T05:39:52.1266991Z   build_args: [{"COMMIT_HASH": "7d09b84a1004dc7176c47a88c7471604c39ae400"}]

2021-07-13T05:39:52.1267587Z ##[endgroup]
2021-07-13T05:39:52.1312692Z ##[command]/usr/bin/docker run --name a33c13950bef8f0d64859990a752fa94d3b1a_99c8bc --label 8a33c1 --workdir /github/workspace --rm -e INPUT_SERVICE_PRINCIPAL -e INPUT_SERVICE_PRINCIPAL_PASSWORD -e INPUT_TENANT -e INPUT_REGISTRY -e INPUT_BRANCH -e INPUT_REPOSITORY -e INPUT_TAG -e INPUT_GIT_ACCESS_TOKEN -e INPUT_BUILD_ARGS -e INPUT_IMAGE -e INPUT_FOLDER -e INPUT_DOCKERFILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wizard/wizard":"/github/workspace" 8a33c1:3950bef8f0d64859990a752fa94d3b1a
2021-07-13T05:39:52.5228485Z Building Docker image nlu:test from ncoder/wizard on 7d09b84a1004dc7176c47a88c7471604c39ae400 and using context  ; and pushing it to guiltlessgames Azure Container Registry
2021-07-13T05:39:52.5230471Z Logging into azure..
(...)
2021-07-13T05:39:53.8844662Z Sending build job to ACR..
2021-07-13T05:39:53.8847868Z az acr build -r guiltlessgames --build-arg COMMIT_HASH="7d09b84a1004dc7176c47a88c7471604c39ae400" -f Dockerfile -t nlu:test 
(...)

2021-07-13T05:39:54.8153151Z WARNING: Sending context to registry: guiltlessgames...
2021-07-13T05:39:54.8530708Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-07-13T05:39:54.8537003Z ERROR: 'NoneType' object is not callable
2021-07-13T05:39:54.8537613Z Traceback (most recent call last):
2021-07-13T05:39:54.8538499Z   File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
2021-07-13T05:39:54.8539302Z     cmd_result = self.invocation.execute(args)
2021-07-13T05:39:54.8540554Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
2021-07-13T05:39:54.8541232Z     raise ex
2021-07-13T05:39:54.8542345Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-07-13T05:39:54.8543229Z     results.append(self._run_job(expanded_arg, cmd_copy))
2021-07-13T05:39:54.8544254Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-07-13T05:39:54.8562941Z     result = cmd_copy(params)
2021-07-13T05:39:54.8564108Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
2021-07-13T05:39:54.8564861Z     return self.handler(*args, **kwargs)
2021-07-13T05:39:54.8565882Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2021-07-13T05:39:54.8566652Z     return op(**command_args)
2021-07-13T05:39:54.8567589Z   File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 106, in acr_build
2021-07-13T05:39:54.8568401Z     platform=PlatformProperties(
2021-07-13T05:39:54.8569147Z TypeError: 'NoneType' object is not callable
2021-07-13T05:39:55.0248344Z To open an issue, please run: 'az feedback'
2021-07-13T05:39:55.0296519Z Cleaning up orphan processes

```

**Comment by ncoder** [comment]
If anyone else finds this and is looking for a quick fix, and is using acr-task-github-action (or something similar), this fix will lock the azure-cli version:

https://github.com/ncoder/acr-task-github-action/commit/c4fb980cee217269d100bbf116244d0f943f080a

**Comment by zhoxing-ms** [comment]
@00Kai0 Could you please take a look at this issue?

**Comment by zhoxing-ms** [comment]
This issue is fixed by https://github.com/Azure/azure-cli/pull/18853 , @00Kai0 please help to confirm it~

**Comment by jafetrgl** [comment]
Yes, is fixed.

Thanks!

Jafet Rodríguez
CanaryTek Consultoria y Sistemas SL
tel: 828 08 35 20
e-mail: ***@***.***

________________________________
