### ISSUE TITLE
 'NoneType' object is not callable when `az acr build`

### ISSUE THREAD

**Issue by AliJP** [Azure/azure-cli#18841]
## Describe the bug
`az acr build` was working fine with our project, but since today morning, I am getting below error.

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 106, in acr_build
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I am building a console dot net project with alpine image
- `az acr build --image {imagename}:{version} --registry {acrName} --file Dockerfile .`

## Expected Behavior
Build and push the image to my ACR repository

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.0

Extensions:
aks-preview 0.4.52
interactive 0.4.4

```

**Comment by ndrmnl** [comment]
Same problem here. Python 3.9.1, Windows 10.0.19043, azure-cli 2.26.0. Exact same error message as shown above.

Seems related to https://github.com/Azure/azure-cli/commit/a8abfbbffe6b3f5d45f6821dabe060871bd1db25?branch=a8abfbbffe6b3f5d45f6821dabe060871bd1db25&diff=unified#diff-0f3568ab838e8abfa5fd9ff9c4e886aa58b3e0d969968a166268ef29e51c6733L100, is that already in `release`? It was updated 13h ago, so it might have been included. Gonna point that out on #18786 perhaps...

**Comment by yonzhan** [comment]
route to service team

**Comment by daniel347x** [comment]
Same problem for me... This has been working for years, and suddenly I can't build my container...

**Comment by johnynfulleffect** [comment]
Can recreate this issue.

**Comment by luisdlp** [comment]
A hotfix for the cli has been released. Please use Version 2.26.1 for the cli:
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-14-2021
