### ISSUE TITLE
az servicebus namespace list throws TypeError: 'NoneType' object is not iterable when there are no service bus namespaces in the given subscription

### ISSUE THREAD

**Issue by nwohlgemuth** [Azure/azure-cli#18866]
## Describe the bug
az servicebus namespace list does not correctly handle the case when there are no service bus namespaces in a given subscription

**Command Name**
`az servicebus namespace list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 704, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/servicebus/operations/_namespaces_operations.py", line 371, in extract_data
    return deserialized.next_link or None, iter(list_of_elem)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Have an azure subscription foo that has no service bus namespaces in it and then run:
- `az servicebus namespace list --subscription foo`

## Expected Behavior

Command should successfully list that there are no service bus namespaces

## Environment Summary
```
Linux-4.15.0-144-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.26.1

Extensions:
scheduled-query 0.3.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @nwohlgemuth, Thanks for bringing this to our attention.

We would triage this internally and keep you posted.

**Comment by danielwagn3r** [comment]
Having this error as well.

### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az servicebus namespace list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/servicebus/v2021_06_01_preview/operations/_namespaces_operations.py", line 98, in extract_data
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus namespace list`

## Expected Behavior

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
arcdata 1.4.0
azure-devops 0.25.0
azure-iot 0.14.1
webapp 0.4.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

**Comment by Saglodha** [comment]
Hi @nwohlgemuth , this has been fixed in our latest release. Please retry the operation with latest package and let us know in case of additional concerns.
