### ISSUE TITLE
Unable to create app svc kube environment with az cli 2.26.0

### ISSUE THREAD

**Issue by Bapic** [Azure/azure-cli#18879]
## Describe the bug

**Command Name**
`az appservice kube create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bapi/.azure/cliextensions/appservice-kube/azext_appservice_kube/custom.py", line 90, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "/home/bapi/.azure/cliextensions/appservice-kube/azext_appservice_kube/vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice kube create`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
customlocation 0.1.2
azure-iot 0.10.5
k8s-extension 0.4.3
appservice-kube 0.1.20
arcdata 0.0.2
connectedk8s 1.1.5
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by apwestgarth** [comment]
Hi, this should now be resolved after we have released an updated extension this afternoon.  To upgrade:

az extension remove -n appservice-kube
az extension add --yes --source "https://aka.ms/appsvc/appservice_kube-latest-py2.py3-none-any.whl"
