### ISSUE TITLE
aks creds failed

### ISSUE THREAD

**Issue by maxvandl** [Azure/azure-cli#18884]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2540, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 4337, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.9.6
Installer: PIP

azure-cli 2.26.0 *

```

**Comment by campbellj0** [comment]
Experiencing the exact same error. Pipeline worked yesterday (azcli v2.25.0) Today failing (azcli v2.26.0):

/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1626381719071.sh
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2541, in aks_get_credentials
    path, kubeconfig, overwrite_existing, context_name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 4337, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by yonzhan** [comment]
route to service team

**Comment by SailingYYC** [comment]
this is impacting to us as well, is there any update?

**Comment by yonzhan** [comment]
AKS service team should take a look

**Comment by campbellj0** [comment]
The 2.26.0 release notes mention that the "az aks get-credentials" added a check for KUBECONFIG environment variable.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-06-2021
Is there a work around for this env var check?
Is there anyway to set the AzureCLI@2 task to use a specific version of the az cli?
If this were possible, we could rollback to 2.25.0.

**Comment by SailingYYC** [comment]
> The 2.26.0 release notes mention that the "az aks get-credentials" added a check for KUBECONFIG environment variable.
> https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-06-2021

Based on this, I think the `azure-cli` is the source of the bug. `KUBECONFIG` is an override, it is not a required EnvVar, and will not exist on the vast majority of systems. This behaviour should be flagged as a bug and immediately remediated to follow the `kubectl` logic, as appropriate for the host OS.

**Comment by awz5015** [comment]
It seems that part of our problem may be coming from the "KubernetesManifest@0" azure devops task setting the following at the end of the task (shown when executing pipeline with System Diagnostics enabled). 

```
##[debug]KUBECONFIG=/home/vsts/work/_temp/kubectlTask/1626444824321/config
##[debug]set KUBECONFIG=
##[debug]Processed: ##vso[task.setvariable variable=KUBECONFIG;issecret=false;]
```

Any subsequent `AzureCLI@2` tasks running `az aks get-credentials` on `azure-cli >  2.25.0` then appear to fail because of this blank `KUBECONFIG` EnvVar.

I was able to reproduce this locally in an Ubuntu container:

```
az --version
azure-cli                         2.26.0 *
export KUBECONFIG=
az login
az aks get-credentials   --name {} --resource-group {}
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2541, in aks_get_credentials
    path, kubeconfig, overwrite_existing, context_name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 4337, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory:
```

A possible work around may be to switch the ordering of the Azure Devops tasks if allowable in your pipeline.

**Comment by 4c74356b41** [comment]
2 workarounds:
1. unset KUBECONFIG
2. export KUBECONFIG=$(Build.Repository.LocalPath)

**Comment by vladimirglazkov** [comment]
for task: PowerShell@2 workaround:
$Env:KUBECONFIG = $null

**Comment by Volatus** [comment]
I was the one that introduced the `KUBECONFIG` check and this is standard K8s behavior, the blame is on the pipeline task for setting `KUBECONFIG`. If it's set, then it will be used. Maybe could consider another check to make sure `KUBECONFIG` is actually valid before usage.

**Comment by SailingYYC** [comment]
> @SailingYYC I was the one that introduced the `KUBECONFIG` check and this is standard K8s behavior, the blame is on the pipeline task for setting `KUBECONFIG` to essentially null. If it's set, then it will be used. Maybe could consider another check to make sure `KUBECONFIG` is actually valid before usage.

On my machine, if I `export KUBECONFIG=`, that "essentially null" value you refer to, everything still functions with `kubectl` as expected. From your description, you're still using it as a value if the variable merely exists? In this case, should an empty variable and a non-existent variable not be the same use case/logic?

As a note, and yes it's a different team at Microsoft, it is the `KubernetesManifest@0` task that is implementing this behaviour, so it's not readily in the user's scope to correct it.

**Comment by maxvandl** [comment]
Hello! Any new about issue? On latest azure-cli same problem
