### ISSUE TITLE
az acr token delete failed since 2.26.0

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-cli#18881]
It's a regression from 2.26.0. Log the bug for tracking.

Workaround: Downgrade to version before 2.26.0.

az acr token delete --name $TOKEN_NAME --registry $REGISTRY_NAME --resource-group $REGISTRY_RESOURCE_GROUP_NAME --yes

-----------
'TokensOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/token.py", line 103, in acr_token_delete
    return client.delete(resource_group_name, registry_name, token_name)
AttributeError: 'TokensOperations' object has no attribute 'delete'

**Comment by yonzhan** [comment]
route to service team
