### ISSUE TITLE
WebApp:Failed upload "no file or directory" for file that exists

### ISSUE THREAD

**Issue by InfinityGhost** [Azure/azure-cli#18894]
## Describe the bug

Failed upload claiming a fail doesn't exist that does exist.

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/repos/OpenTabletDriver-Web/OpenTabletDriver.Web.Core.csproj'
Traceback (most recent call last):
  File "/nix/store/yiln326wmrhxchb1sjbq4v3ggm78slgy-python3.8-knack-0.8.2/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/nix/store/ryygn4wlxjinq9g2l8ig2kncjqwgm63g-python3.8-azure-cli-2.26.0/lib/python3.8/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/nix/store/2x7lxldf83wy8q2wgkwb2yw7csr8i80y-python3.8-azure-cli-core-2.26.0/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/nix/store/ryygn4wlxjinq9g2l8ig2kncjqwgm63g-python3.8-azure-cli-2.26.0/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 3705, in webapp_up
    _lang_details = get_lang_from_content(src_dir, html)
  File "/nix/store/ryygn4wlxjinq9g2l8ig2kncjqwgm63g-python3.8-azure-cli-2.26.0/lib/python3.8/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 179, in get_lang_from_content
    runtime_lang = detect_dotnet_lang(package_netcore_file)
  File "/nix/store/ryygn4wlxjinq9g2l8ig2kncjqwgm63g-python3.8-azure-cli-2.26.0/lib/python3.8/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 193, in detect_dotnet_lang
    parsed_file = ET.parse(csproj_path)
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/repos/OpenTabletDriver-Web/OpenTabletDriver.Web.Core.csproj'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create webapp on Linux
- `az webapp up --sku {} --name {} --os-type {} --location {}`

## Expected Behavior

Finds the directory, publishes as expected.

## Environment Summary
```
NixOS 21.05
Linux-5.4.130-x86_64-with-glibc2.2.5
Python 3.8.9
Installer: PIP

azure-cli 2.26.0 *

```
## Additional Context

Tree:
```
├── OpenTabletDriver.Web
│   ├── appsettings.Development.json
│   ├── appsettings.json
│   ├── bin
│   ├── Controllers
│   ├── Markdown.cs
│   ├── Models
│   ├── obj
│   ├── OpenTabletDriver.Web.csproj
│   ├── Program.cs
│   ├── Properties
│   ├── Startup.cs
│   ├── Utilities
│   ├── Views
│   └── wwwroot
├── OpenTabletDriver.Web.Core
│   ├── bin
│   ├── Contracts
│   ├── GitHub
│   ├── obj
│   ├── OpenTabletDriver.Web.Core.csproj
│   ├── Services
│   └── Utilities
├── OpenTabletDriver.Web.sln
└── shell.nix
```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
The command is required to run from the folder where the code is present. Please retry from code folder. it should work.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
