### ISSUE TITLE
az acr build fails with python error 'NoneType' object is not callable

### ISSUE THREAD

**Issue by gvt** [Azure/azure-cli#18908]
Full command-line command and resulting output:

```
az acr build --file Dockerfile.base --registry WhoIhrBenchmarksRegistry -t benchmarksbase:{{.Run.ID}} .                                                                                                 [19:56:54]
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Excluding '.git' based on default ignore rules
Uploading archived source code from '/var/folders/1v/13qvs0c54y5cfjp6_jtwjf8m0000gn/T/build_archive_3df63f0a1b094da9b466671a2a9bac12.tar.gz'...
Sending context (500.534 MiB) to registry: WhoIhrBenchmarksRegistry...
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 106, in acr_build
    platform=PlatformProperties(
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
```

Screenshot of my command line:
![Screen Shot 2021-07-16 at 8 41 42 PM](https://user-images.githubusercontent.com/15811/126020290-53b6a369-bbb0-461d-b469-b0cbe2ce3e94.png)

## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/build.py", line 106, in acr_build
    platform=PlatformProperties(
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr build --file Dockerfile.base --registry WhoIhrBenchmarksRegistry -t benchmarksbase:{{.Run.ID}} .`

## Expected Behavior
It would work to push, tag, and push the docker image to my Azure Container Registry.

## Actual Behavior
The command appears to have failed, but I am not clear whether the operation completed within the registry itself. I attempted to check via `az acr repository list --name WhoIhrBenchmarksRegistry --output table` but see no output from that command so I think it did not work, but am not yet certain.

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.0

Extensions:
db-up 0.2.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by vaisakh007** [comment]
I am also facing the same issue

**Comment by vijayshinva** [comment]
I run this command as part of a GitHub Action and it fails running on **ubuntu-latest** or **ubuntu-18.04**. Similar to what @vaisakh007 reported. I added **az acr check-health** and it reports everything is fine with the acr instance.

![image](https://user-images.githubusercontent.com/16094361/126042959-e64f534f-cc78-44b7-9724-ac04d68143b6.png)

**Comment by Andreas-Huber** [comment]
Can confirm the same issue in the Azure Cloud Shell, while building a from the [Azure Kubernetes Service Workshop Exercise - Create a private, highly available container registry](https://docs.microsoft.com/en-us/learn/modules/aks-workshop/03-deploy-container-registry).

**Comment by alizamani84** [comment]
The issue was fixed in azure cli [2.26.1](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-14-2021). Could not upgrade the cli from 2.26.0 to 2.26.1 via `az upgrade`, but `pip install azure-cli` worked without any issue.

**Comment by vaisakh007** [comment]
Would be nice to have task like https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops for mentioning az cli version other wise the command like az acr build is completely unreliable

**Comment by gvt** [comment]
I upgraded to version 2.26.1, re-ran the same command and it completed successfully this time. Thanks!
