### ISSUE TITLE
"az acr task timer remove" fails after upgrading to cli 2.26.1

### ISSUE THREAD

**Issue by Blackbaud-EricSlater** [Azure/azure-cli#18903]
## Describe the bug

**Command Name**
`az acr task timer remove`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'TasksOperations' object has no attribute 'create'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/task.py", line 804, in acr_task_timer_remove
    return client.create(resource_group_name=resource_group_name,
AttributeError: 'TasksOperations' object has no attribute 'create'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr task timer remove -n {} -r {} -g {} --timer-name {}`

This is failing on my local computer runnning mac os. It is also failing on the ubuntu-18.04 agent in VSTS.

## Expected Behavior

The command should remove the schedule

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.1

```
## Additional Context

This was working until upgrading to azure cli 2.26.1. Was previously running 2.25.x

**Comment by yonzhan** [comment]
route to service team
