### ISSUE TITLE
az cli command failing in ubuntu 20.4 microsoft hosted agent azure devops

### ISSUE THREAD

**Issue by vaisakh007** [Azure/azure-cli#18910]
## Describe the bug
I was building  docker image using az acr commands from azure devops pipeline(ubuntu 20.04 microsoft hosted) and am making use of azcli task for the az login purpose but it is failing.
Please note that the this task was working previously and i have not made any changes to the pipeline or  service connection
az cli task is failing for version 2.26.0
**Command Name**
 - task: AzureCLI@2
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        azureSubscription: 'name_service_connection'
        scriptType: 'bash'
        workingDirectory: $(VAR_WORKING_DIR)
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr build --image reponame:$(Build.BuildNumber)   --registry  $(VAR_ACR)  --only-show-errors  --file $(VAR_DOCKERFILE) .'
        addSpnToEnvironment: true
        failOnStandardError: true

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback:
2021-07-17T03:21:41.4817228Z ERROR: 'NoneType' object is not callable
2021-07-17T03:21:41.4818143Z Traceback (most recent call last):
2021-07-17T03:21:41.4819482Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
2021-07-17T03:21:41.4820315Z     cmd_result = self.invocation.execute(args)
2021-07-17T03:21:41.4821527Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
2021-07-17T03:21:41.4822277Z     raise ex
2021-07-17T03:21:41.4823939Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-07-17T03:21:41.4824842Z     results.append(self._run_job(expanded_arg, cmd_copy))
2021-07-17T03:21:41.4826022Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-07-17T03:21:41.4826838Z     result = cmd_copy(params)
2021-07-17T03:21:41.4827936Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
2021-07-17T03:21:41.4828780Z     return self.handler(*args, **kwargs)
2021-07-17T03:21:41.4830014Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2021-07-17T03:21:41.4830865Z     return op(**command_args)
2021-07-17T03:21:41.4832236Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
2021-07-17T03:21:41.4833031Z     variant=platform_variant
2021-07-17T03:21:41.4833954Z TypeError: 'NoneType' object is not callable
2021-07-17T03:21:41.5097461Z To open an issue, please run: 'az feedback'
2021-07-17T03:21:41.5717731Z ##[error]ERROR: The command failed with an unexpected error. Here is the traceback:
2021-07-17T03:21:41.5726878Z ##[error]ERROR: 'NoneType' object is not callable
2021-07-17T03:21:41.5727815Z ##[error]Traceback (most recent call last):
2021-07-17T03:21:41.5728836Z ##[error]  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
2021-07-17T03:21:41.5729707Z ##[error]    cmd_result = self.invocation.execute(args)
2021-07-17T03:21:41.5731119Z ##[error]  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
2021-07-17T03:21:41.5731925Z ##[error]    raise ex
2021-07-17T03:21:41.5732986Z ##[error]  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-07-17T03:21:41.5733950Z ##[error]    results.append(self._run_job(expanded_arg, cmd_copy))
2021-07-17T03:21:41.5735558Z ##[error]  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-07-17T03:21:41.5737085Z ##[error]Script has output to stderr. Failing as failOnStdErr is set to true.
```

## To Reproduce:
Try running a sample pipeline that make use of azcli task in ubuntu 20.04 microsoft hosted agent

## Expected Behavior
AZ cli should login and proceed with the command specified in inline script.
## Environment Summary
```
 [command]/usr/bin/az --version
 azure-cli                         2.26.0 *
 core                              2.26.0 *
 telemetry                          1.0.6
 Extensions:
 azure-devops                      0.18.0
all other env values at mentioned at https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
```
## Additional Context
The command was working fine for all builds previously and it is failing from today.

**Comment by vaisakh007** [comment]
same issue is already raised #18908 .Hence this is a duplicate and am closing this

**Comment by jiasli** [comment]
The topic of using `failOnStderr` is tracked by https://github.com/Azure/azure-cli/issues/18372.
