### ISSUE TITLE
Seems like there is an issue i'm getting this error while deploying [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by gopisettyr** [Azure/azure-cli#18915]
## Describe the bug

**Command Name**
`az bicep upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3418, in upgrade_bicep_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 93, in ensure_bicep_installation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 171, in _get_bicep_installed_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 205, in _run_command
  File "subprocess.py", line 493, in run
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep upgrade`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by snaheth** [comment]
Hi @gopisettyr, thanks for bringing this up.

When you check your `PATH` variable (`$Env:PATH` in PowerShell, for example) - do you see a path listed that contains a python executable (something like `D:\Python38\`)?

**Comment by sosoriov** [comment]
I'm having the same issue using the latest version

{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by AGregersen** [comment]
We get it when using az bicep publish --file <file> --target "br:<registry>.azurecr.io/bicep/modules/<filename>:0.1.3r"  through Octopus Deploy, but not if I run it directly.
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by chaoscreater** [comment]
> Hi @gopisettyr, thanks for bringing this up.
> 
> When you check your `PATH` variable (`$Env:PATH` in PowerShell, for example) - do you see a path listed that contains a python executable (something like `D:\Python38\`)?

Yes. I have Python 3.9.5 and 2.7.17 installed already and added to PATH, prior to installing BICEP.

**Comment by rahulwaghule** [comment]
This worked for me.

```
az bicep uninstall
az bicep install
```
