### ISSUE TITLE
az mysql db list error?

### ISSUE THREAD

**Issue by aPraelexisAdministrator** [Azure/azure-cli#18917]
## Describe the bug

**Command Name**
`az mysql db list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/private/etc/.azure'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 674, in execute
    self.cli_ctx.save_local_context(parsed_args, self.commands_loader.command_table[command].arguments,
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 164, in save_local_context
    self.local_context.set(lca.scopes, lca.name, value)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/local_context.py", line 116, in set
    self._local_context_file.set_value(scope.lower(), argument, value)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/config.py", line 238, in set_value
    self.set(config)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/config.py", line 222, in set
    ensure_dir(self.config_dir)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/util.py", line 115, in ensure_dir
    raise e
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/util.py", line 112, in ensure_dir
    os.makedirs(d)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/private/etc/.azure'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql db list --resource-group {} --server-name {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.1

```
## Additional Context

% cd /private/etc/.azure
cd: no such file or directory: /private/etc/.azure

**Comment by yonzhan** [comment]
route to service team

**Comment by honghr** [comment]
`az mysql server `is used for Azure MySQL Single server. we have deprecated this service. Please use `az mysql flexible-server.`
