### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CislakDamian** [Azure/azure-cli#18920]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\dcislak\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 663, in cli_execute
    result = invocation.execute(args)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 341, in k8s_install_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 369, in k8s_install_kubectl
  File "ntpath.py", line 223, in dirname
  File "ntpath.py", line 185, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
interactive 0.4.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by mbifeld** [comment]
Hi @CislakDamian, is this issue still happening for you in the latest az cli and az aks versions?

**Comment by mbifeld** [comment]
Closing as outdated with no recent response. Please reopen if this is an active issue.
