### ISSUE TITLE
az acr task credential add failing with v2.26.0 and v2.26.1

### ISSUE THREAD

**Issue by Sasi-JellyFish** [Azure/azure-cli#18949]
## Describe the bug

**Command Name**
`az acr task credential add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'TasksOperations' object has no attribute 'update'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/acr/task.py", line 635, in acr_task_credential_add
    client.update(resource_group_name, registry_name, task_name, taskUpdateParameters)
AttributeError: 'TasksOperations' object has no attribute 'update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr task credential add --name {} --registry {} --login-server {} --username {} --password {}`

## Environment Summary
```
Linux-5.10.25-linuxkit-x86_64-with
Python 3.8.9
Installer: DOCKER

azure-cli 2.26.1

```

**Comment by Sasi-JellyFish** [comment]
No problem till the tag 2.25.0. This image has Python 3.8.9. Problem started from tag 2.26.0.

**Comment by yonzhan** [comment]
route to service team
