### ISSUE TITLE
MSI not supported for storage directory commands.

### ISSUE THREAD

**Issue by EdgyEdgemond** [Azure/azure-cli#18940]
## Describe the bug

**Command Name**
`az storage fs directory upload`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
MSI auth not yet supported.
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 108, in login_auth_for_azcopy
    token_info = _unserialize_non_msi_token_payload(token_info)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 148, in _unserialize_non_msi_token_payload
    'refresh_token': token_info['refreshToken'],
KeyError: 'refreshToken'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/__init__.py", line 352, in new_handler
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 71, in storage_fs_directory_copy
    azcopy = _azcopy_login_client(cmd)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 122, in _azcopy_login_client
    return AzCopy(creds=login_auth_for_azcopy(cmd))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 110, in login_auth_for_azcopy
    raise Exception('MSI auth not yet supported.')
Exception: MSI auth not yet supported.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login` # with a service principal
- `az storage fs directory upload --account-name {} -s {} -f {} --auth-mode {}`

## Environment Summary
```
Linux-5.11.9-zen1-1-zen-x86_64-with-glibc2.33
Python 3.9.2
Installer: 

azure-cli 2.26.1

```

**Comment by yonzhan** [comment]
storage
