### ISSUE TITLE
Webapp:error out when adding a hybrid-connection to a webapp

### ISSUE THREAD

**Issue by anewio** [Azure/azure-cli#18968]
## Describe the bug

**Command Name**
`az webapp hybrid-connection add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
malformed node or string: None
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3362, in add_hc
  File "ast.py", line 99, in literal_eval
  File "ast.py", line 98, in _convert
  File "ast.py", line 75, in _convert_signed_num
  File "ast.py", line 66, in _convert_num
  File "ast.py", line 63, in _raise_malformed_node
ValueError: malformed node or string: None

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp hybrid-connection add --hybrid-connection {} --name {} --namespace {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
application-insights 0.1.13

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
I think this issue is because your `Hybrid Connection` doesn't have `User Metadata`. Please add and verify.
 example of user metadata : `'[{\"key\":\"endpoint\",\"value\":\"vmsq1:80\"}]'`

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
