### ISSUE TITLE
ERROR: Either 'my.zip' is not a valid local file path or you do not have permissions to access it

### ISSUE THREAD

**Issue by Niyojan** [Azure/azure-cli#19012]
**Describe the bug**
While running `az webapp deploy --resource-group myrg --name myname --src-path my.zip --type zip --async true --debug` getting following error:

`ERROR: Either 'my.zip' is not a valid local file path or you do not have permissions to access it`

**To Reproduce**
Run above mentioned command and observe the error

**Expected behavior**
Should upload the zip

**Environment summary**
Jenkins version - `2.289.2`
Java version - `1.8.0_281-b09`
os.arch - `amd64`
os.name - `Windows Server 2019`
os.version - `10.0`
`azure-cli 2.26.1 core 2.26.1 telemetry 1.0.6 Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' Extensions directory 'C:\windows\system32\config\systemprofile\.azure\cliextensions' Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr 6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] Legal docs and information: aka.ms/AzureCliLegal Your CLI is up-to-date.`

**Additional context**
Command that Jenkins is running - `C:\windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\myworkspace>az webapp deploy --resource-group myrg --name myname --src-path my.zip --type zip --async true `

Debug info
```
20:54:02 INFO: cli.azure.cli.command_modules.appservice.custom: Initiating deployment
20:54:02 INFO: cli.azure.cli.command_modules.appservice.custom: Deploying from local path: my.zip
20:54:02 DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
20:54:02 DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4114, in _get_onedeploy_request_body
20:54:02 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\SysWOW64\\config\\systemprofile\\AppData\\Local\\Jenkins\\.jenkins\\workspace\\myworkspace\\my.zip'
20:54:02 
20:54:02 The above exception was the direct cause of the following exception:
20:54:02 
20:54:02 Traceback (most recent call last):
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4037, in perform_onedeploy
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4202, in _perform_onedeploy_internal
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4157, in _make_onedeploy_request
20:54:02   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4117, in _get_onedeploy_request_body
20:54:02 knack.util.CLIError: Either 'my.zip' is not a valid local file path or you do not have permissions to access it
20:54:02 
20:54:02 ERROR: cli.azure.cli.core.azclierror: Either 'my.zip' is not a valid local file path or you do not have permissions to access it
20:54:02 ERROR: az_command_data_logger: Either 'my.zip' is not a valid local file path or you do not have permissions to access it
```

Observer that my zip file is in `C:\windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\myworkspace` but its searching it in `C:\\Windows\\SysWOW64\\config\\systemprofile\\AppData\\Local\\Jenkins\\.jenkins\\workspace\\myworkspace\\my.zip`

**Comment by yonzhan** [comment]
route to service team
