### ISSUE TITLE
error calling the az rest to add a user to a directory role

### ISSUE THREAD

**Issue by chuckthompsonprofisee** [Azure/azure-cli#19016]
## Describe the bug
error calling the az rest to add a user to a directory role from powershell
$miObjectId="id of managed identity"
$body="{""@odata.id"": ""https://graph.microsoft.com/v1.0/directoryObjects/$miObjectId""}"
$headers="{""Content-Type"": ""application//json""}"
az rest --method POST --uri "https://graph.microsoft.com/beta/directoryRoles/9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3/members/$ref" --headers $headers  --body $body

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 506, in shell_safe_json_parse
  File "json\__init__.py", line 370, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 815, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 531, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: {Content-Type: application//json}
Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 16, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 818, in send_raw_request
ValueError: not enough values to unpack (expected 2, got 1)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --uri {} --headers {} --body {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
azure-devops 0.17.0

```

**Comment by chuckthompsonprofisee** [comment]
I was able to get past that error by doing this and replace all occurrences of " with \".
$body="{""@odata.id"": ""https://graph.microsoft.com/v1.0/directoryObjects/$miObjectId""}"
$body = $body -replace "`"", "\`""
$headers="{""Content-Type"": ""application/json""}"
$headers = $headers -replace "`"", "\`""

az rest --method POST --uri "https://graph.microsoft.com/beta/directoryRoles/9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3/members/$ref" --headers $headers  --body $body

but now I get this error 
Bad Request({"error":{"code":"Request_BadRequest","message":"Unsupported resource type 'DirectoryObject' for operation 'Create'.","innerError":{"date":"2021-07-27T20:47:18","request-id":"20ff01b5-8eb6-49f2-8fb2-9d7a63d02297","client-request-id":"20ff01b5-8eb6-49f2-8fb2-9d7a63d02297"}}})

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
For including quotes in argument values, please see https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#pass-arguments

As for calling Microsoft Graph API, please see https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0&preserve-view=true to make sure the correct API is used.
