### ISSUE TITLE
Broken: Build a Docker image and upload it to Azure Container Registry

### ISSUE THREAD

**Issue by ulja-dd** [Azure/azure-cli#19031]
https://docs.microsoft.com/en-us/learn/modules/deploy-run-container-app-service/3-exercise-build-images?pivots=csharp

## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --registry {} --image {} {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by CCostaT** [comment]
Try updating azure-cli to version 2.26.1. It should solve that bug

**Comment by ulja-dd** [comment]
The shell is provided by an [azure learn path sandbox](https://docs.microsoft.com/en-us/learn/modules/deploy-run-container-app-service/3-exercise-build-images?pivots=csharp).

I'm not allowed to upgrade:
```
van@Azure:~$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.26.0. Latest version available is 2.27.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
az upgrade is not supported in Cloud Shell.
```

**Comment by CCostaT** [comment]
In that case I guess you'll have to wait for Microsoft to upgrade it. I don't think there's anything else you can do.

**Comment by shizhMSFT** [comment]
I've checked that `az` has been upgrade to `2.27.0` in Azure Cloud Shell.

Output of `az version`:
```json
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "azure-iot": "0.10.11",
    "ssh": "0.1.5"
  }
}
```
