### ISSUE TITLE
Failure with AZ SQL VM GROUP CREATE

### ISSUE THREAD

**Issue by nnellans-acts** [Azure/azure-cli#19032]
## Describe the bug
Not sure why this is happening.  I upgraded to the most recent version of the CLI and still get this issue.  This is the parameter that i'm using:
--storage-account 'https://myStorage.blob.core.windows.net/'

However, I'm getting this error:
"Message: Storage account url is invalid. Needs to be blob service endpoint."

**Command Name**
`az sql vm group create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'Response' object has no attribute 'internal_response'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/sqlvm/custom.py", line 89, in sqlvm_group_create
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 648, in sdk_no_wait
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sqlvirtualmachine/operations/_sql_virtual_machine_groups_operations.py", line 187, in create_or_update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sqlvirtualmachine/operations/_sql_virtual_machine_groups_operations.py", line 145, in _create_or_update_initial
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidStorageAccountUrl
Message: Storage account url is invalid. Needs to be blob service endpoint.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 112, in handle_template_based_exception
AttributeError: 'Response' object has no attribute 'internal_response'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql vm group create --name {} --resource-group {} --image-offer {} --image-sku {} --domain-fqdn {} --operator-acc {} --service-acc {} --sa-key {} --storage-account {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
aks-preview 0.5.5
azure-devops 0.18.0
monitor-control-service 0.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by NivedhaChellam** [comment]
Though the storage account URL seems to be the valid one, it had been sent along with leading whitespace(s), that was the reason for SQL VM group creation failure. Should work fine without the space.  

`az sql vm group create -n sqlvmgroup -l eastus -g myresourcegroup --image-offer SQL2016-WS2016 --image-sku Enterprise --domain-fqdn Domain.com --operator-acc testop --service-acc testservice --sa-key {PublicKey} --storage-account 'https://storacc.blob.core.windows.net/'`
