### ISSUE TITLE
az consumption usage list - MemoryError

### ISSUE THREAD

**Issue by Nickelodeon111** [Azure/azure-cli#19044]
## Describe the bug

**Command Name**
`az consumption usage list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 234, in dumps
  File "json\encoder.py", line 201, in encode
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az consumption usage list --start-date {} --end-date {} --subscription {} --include-meter-details -m`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
costmanagement 0.1.1

```

**Comment by Nickelodeon111** [comment]
Details of command used: 
az consumption usage list --start-date 2021-07-01  --end-date 2021-07-29  --subscription a464f508-ff11-423c-bab6-8eadb42ebcf2 --include-meter-details -m

**Comment by yonzhan** [comment]
route to service team
