### ISSUE TITLE
No module named 'vsts_cd_manager' - error when running "az logicapp create "

### ISSUE THREAD

**Issue by brendondb** [Azure/azure-cli#19053]
## Bug Description:
##When executing the command below (under **Command**), the error (under **Errors) is returned

**Command **
az logicapp create --name MyLogicAppName    --resource-group MyResourceGroupName --subscription MySubscription   --storage-account MyStorageAccount --custom-location MyCustomLocation

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'vsts_cd_manager'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\.azure\cliextensions\logicapp\azext_logicapp\custom.py", line 102, in <module>
    from .vsts_cd_provider import VstsContinuousDeliveryProvider
  File "C:\Users\usr\.azure\cliextensions\logicapp\azext_logicapp\vsts_cd_provider.py", line 8, in <module>
    from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
ModuleNotFoundError: No module named 'vsts_cd_manager'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logicapp create --name {} --resource-group {} --subscription {} --storage-account {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
appservice-kube 0.1.21
connectedk8s 1.1.5
customlocation 0.1.2
k8s-extension 0.6.1
logicapp 0.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by derek1ee** [comment]
@Bec ***@***.***> can you take a look at this?
________________________________

**Comment by archidda** [comment]
We are aware of the issue and working on a fix, new version of the extension will be released next week.

As a workaround, please downgrade the azure cli to 2.23.0.

**Comment by archidda** [comment]
We released a new version of logic app extension. To upgrade, please remove and install the extension again using these two commands-
-	az extension remove --name logicapp
-	az extension add --source https://aka.ms/logicapp-latest-py2.py3-none-any.whl
