### ISSUE TITLE
Creating a private endpoint approval on a postgresdb - endpoint created but this error was received.

### ISSUE THREAD

**Issue by mcarter106** [Azure/azure-cli#19066]
## Describe the bug

**Command Name**
`az network private-endpoint-connection approve`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py", line 103, in approve_private_endpoint_connection
    approval_description)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/__init__.py", line 102, in approve_private_endpoint_connection
    description=approval_description)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/__init__.py", line 58, in _update_private_endpoint_connection_status
    private_endpoint_connection_name)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/__init__.py", line 123, in show_private_endpoint_connection
    return r.json()
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint-connection approve -g {} -n {} --resource-name {} --type {} --description {}`

## Environment Summary
```
Linux-4.18.0-193.47.1.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa
Python 3.6.8
Installer: RPM

azure-cli 2.26.1

```

**Comment by yonzhan** [comment]
network

**Comment by 00Kai0** [comment]
Hi @mcarter106 , Can you show more detail about creating your resource step by step?
I can't reproduce this error on my resource.
