### ISSUE TITLE
Failed to create storage account in sandbox (MSLearn)

### ISSUE THREAD

**Issue by J0ck3l** [Azure/azure-cli#19060]
## Describe the bug
Failed to create storage account in MSLearn sandbox working on the following module:
https://docs.microsoft.com/de-de/learn/modules/store-app-data-with-azure-blob-storage/4-create-storage-resources

**Command Name**
`az storage account create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/julian/.azure/commands/2021-07-30.13-44-58.storage_account_create.292.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 514, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/julian/.azure/commands/2021-07-30.13-44-58.storage_account_create.292.log'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
az storage account create \
   --kind StorageV2 \
   --resource-group learn-526a56ab-210b-4a71-8539-9f9fe0959619 \
   --location centralus \
   --name mslearnsajmo0815

## Expected Behavior
Storage account to be created

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
storage
