### ISSUE TITLE
az acr token delete is broken

### ISSUE THREAD

**Issue by saswatac** [Azure/azure-cli#19095]
## Describe the bug

**Command Name**
`az acr token delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'TokensOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/token.py", line 103, in acr_token_delete
    return client.delete(resource_group_name, registry_name, token_name)
AttributeError: 'TokensOperations' object has no attribute 'delete'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr token delete -n {} -r {} --yes`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.1

Extensions:
costmanagement 0.1.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by shizhMSFT** [comment]
Thanks for reporting it and sorry for the inconvenience.
`2.27.0` has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

Please upgrade to the latest version of Azure CLI to resolve this issue.

**Comment by saswatac** [comment]
I confirm the issue is resolved in the latest version of the cli.
