### ISSUE TITLE
Unable to deploy a bot using zip deploy; [Errno 21] Is a directory

### ISSUE THREAD

**Issue by sujungchoi1** [Azure/azure-cli#19105]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
* Instructions from this page was used: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#deploy-via-arm-template-with-new-resource-group

* {current path} is where the project files are located with the deploy file, but it keeps showing the error. A new bot resource (Bot Channels Registration) appears on the Azure portal, but when 'Test in Web Chat' is used, the bot doesn't work at all.

```
Getting scm site credentials for zip deployment
The command failed with an unexpected error. Here is the traceback:
[Errno 21] Is a directory: '{current path}'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 402, in enable_zip_deploy_webapp
    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout=timeout, slot=slot)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 428, in enable_zip_deploy
    with open(os.path.realpath(os.path.expanduser(src)), 'rb') as fs:
IsADirectoryError: [Errno 21] Is a directory: '{current path}'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Expected Behavior
The web app is successfully deployed to Azure. 

## Environment Summary
```
macOS-11.5-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.27.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by sujungchoi1** [comment]
I created a new resource group and started over, and it worked!
