### ISSUE TITLE
az container exec fail after upgrade to 2.27.0 on the windows image

### ISSUE THREAD

**Issue by kopendrex** [Azure/azure-cli#19133]
**Describe the bug**
After upgrade az-cli 2.27.0 on the windows image in Azure DevOps az container exec with python code finishes with error.

`ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 618, in container_exec
OSError: [WinError 6] The handle is invalid`

**To Reproduce**
`az container exec --resource-group $SomeRG --name $SomeName --container-name $SomeContainerName --exec-command "some_command.sh"`

**Expected behavior**
Run python script without error in version <= 2.26.1 works correctly

**Environment summary**

pool:
  vmImage: 'windows-latest'
steps:
  - checkout: self
  - task: AzureCLI@2
    name: Run_migrations
     inputs:
       scriptType: 'pscore'

az-cli: 2.27.0
azure-devops: 0.18.0

**Comment by yonzhan** [comment]
route to service team

**Comment by TheIdentityHub** [comment]
We are also facing the same issue.
