### ISSUE TITLE
azure cli issue

### ISSUE THREAD

**Issue by surendra0801** [Azure/azure-cli#19152]
## Describe the bug

**Command Name**
`az container create`

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/surendra/.azure/commandIndex.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 512, in execute
    self.commands_loader.load_command_table(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 479, in load_command_table
    command_index.update(self.command_table)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 595, in update
    self.INDEX[self._COMMAND_INDEX_VERSION] = __version__
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 86, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 30] Read-only file system: '/home/surendra/.azure/commandIndex.json'

**Comment by yonzhan** [comment]
route to service team
