### ISSUE TITLE
Unable to delete the reference to gateway load balancer frontend ID

### ISSUE THREAD

**Issue by edwardshao** [Azure/azure-cli#19160]
## Describe the bug

**Command Name**
`az network lb frontend-ip update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'subscription'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 3486, in update_lb_frontend_ip_configuration_setter
    aux_subscriptions.append(parse_resource_id(gateway_lb)['subscription'])
KeyError: 'subscription'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-Follow the Azure CLI document and using "--gateway-lb" with "" to delete the reference to gateway load balancer frontend ID.
https://docs.microsoft.com/en-us/cli/azure/network/lb/frontend-ip?view=azure-cli-latest#az_network_lb_frontend_ip_update
- `az network lb frontend-ip update -g {} --lb-name {} -n {} --public-ip-address {} --gateway-lb "" --subscription {}`

## Expected Behavior
The reference to gateway load balancer frontend ID should be removed.

## Environment Summary
```
Linux-5.4.0-80-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.0

Extensions:
image-copy-extension 0.2.8

```

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Thanks for your feedback. We will fix it in next release. Please use `az network lb frontend-ip update -g {} --lb-name {} -n {} --public-ip-address {} --remove gatewayLoadBalancer` as a workaround.
