### ISSUE TITLE
Cannot access azureml workspace from gitlab CI pipeline. 

### ISSUE THREAD

**Issue by antaradas94** [Azure/azure-cli#19168]
###

## 
unable to connect with azureml workspace from gitlab CI pipeline. There is no authentification established. with az login there was an authentification window in my browser, i could login but end up with : TypeError: __init__() got an unexpected keyword argument 'user_agent'

**Command Name**
`az login`

**Errors:**
```
$ az login
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DAKZWRN4V to authenticate.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: __init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 208, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_through_interactive_flow(
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 930, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 962, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 880, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'
To open an issue, please run: 'az feedback'
```

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.25.0 *

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The path `/usr/local/lib/python3.8/site-packages/azure/cli` is a Linux path where `pip` installs to, but the issue description shows `Installer: MSI` which is only available on Windows. Have you manually changed the content in `Environment Summary`?

This issue could be related to https://github.com/Azure/azure-cli/issues/18626, where `azureml-core` and `azure-cli` have conflicting dependencies on `azure-mgmt-resource`. Could you try to install Azure CLI in a separate virtual environment (https://github.com/Azure/azure-cli/issues/18626#issuecomment-887411446)?

**Comment by antaradas94** [comment]
Thank you for the response. No, the Environment Summary is not changed. the issue was opened from az feedback on local windows pycharm where authentification is possible via az login and also via interactiveauthentication. 
However on gitlab ci docker it fails with az login

**Comment by jiasli** [comment]
Thanks for clarifying. Have you manually installed Azure CLI with `pip` on the GitLab CI docker?

**Comment by antaradas94** [comment]
yes on gitlab ci docker i tried to manually pip install azure-cli. 
In general case when i try to access workspace from my local IDE on Windows , an authentication browser is easily opened, which did not work in in the CI pipeline. 
The main aim is to access the authentication

**Comment by jiasli** [comment]
@antaradas94,

> yes on gitlab ci docker i tried to manually pip install azure-cli.

As `azure-cli` and `azureml-core` have conflicting dependencies, could you try to install Azure CLI in another virtual environment following https://github.com/Azure/azure-cli/issues/18626#issuecomment-887411446?
