### ISSUE TITLE
aks module not working

### ISSUE THREAD

**Issue by tocy1** [Azure/azure-cli#19170]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azure.cli.command_modules.acs.custom#aks_get_credentials' is invalid.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 46, in <module>
    from azure.cli.command_modules.acs import acs_client, proxy
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acs/acs_client.py", line 15, in <module>
    from sshtunnel import SSHTunnelForwarder
  File "/Users/tochukwunwoko/Documents/Ops/sshtunnel.py", line 4, in <module>
    with sshtunnel.open_tunnel(
AttributeError: partially initialized module 'sshtunnel' has no attribute 'open_tunnel' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/Cellar/azure-cli/2.27.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_get_credentials' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --admin`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.27.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@tocy1 Apologies for the late reply. Could you please let me know if you are still facing the same issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos) of the Azure CLI ? This issue is open for quite sometime. Please let me know if you need any further assistance on this. Awaiting your reply.
