### ISSUE TITLE
az connectedk8s connect failing with "No module named 'Crypto.IO'" in WSL window

### ISSUE THREAD

**Issue by PhaniChiruvolu** [Azure/azure-cli#19205]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'Crypto.IO'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/phanic/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 34, in <module>
    from Crypto.IO import PEM
ModuleNotFoundError: No module named 'Crypto.IO'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.1

Extensions:
connectedk8s 1.1.7
k8s-extension 0.6.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@PhaniChiruvolu Apologies for the late reply. Could you please try the below steps and let us know if you still face the issue ?

>az upgrade # Update the Azure CLI version
az extension update --name connectedk8s # This will update the existing connectedk8s extension

Then you can try to run the [az connectedk8s connect](https://docs.microsoft.com/en-us/cli/azure/connectedk8s?view=azure-cli-latest#az-connectedk8s-connect) command and let us know if you run into any issues.

Also this issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by PhaniChiruvolu** [comment]
I don't have the repro setup anymore.
