### ISSUE TITLE
WebApp:Unable to restore webapp

### ISSUE THREAD

**Issue by calebherbison** [Azure/azure-cli#19210]
## Describe the bug

**Command Name**
`az webapp deleted restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore_from_deleted_app'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 708, in restore_deleted_webapp
    return _generic_site_operation(cmd.cli_ctx, resource_group_name, name, 'restore_from_deleted_app', slot, request)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_appservice_utils.py", line 18, in _generic_site_operation
    operation_name if slot is None else operation_name + '_slot')
AttributeError: 'WebAppsOperations' object has no attribute 'restore_from_deleted_app'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deleted restore -g {} -n {} --deleted-id {}`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.1

Extensions:
azure-iot 0.10.15
resource-graph 2.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by ramya894** [comment]
Looking in to the issue

**Comment by ramya894** [comment]
I am able to repro the issue. Will work on the fix.
