### ISSUE TITLE
KeyError 'serverVersion'

### ISSUE THREAD

**Issue by trias702** [Azure/azure-cli#19232]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1563, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --name {} --resource-group {} --acr {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by yukirii** [comment]
I could reproduce the error with AKS cluster using authorized IP address ranges. When executing the command from an unauthorized client, client timeout exceeded and displayed `KeyError: 'serverVersion'`.

```shell
% az aks check-acr -g aadcluster -n aadcluster --acr <ACR name>.azurecr.io
Merged "aadcluster" as current context in /tmp/tmpbntu42xf
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HQ33YEC7C to authenticate.
Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1563, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'
To open an issue, please run: 'az feedback'
```

**Comment by navba-MSFT** [comment]
@trias702 Apologies for the late reply. I am not able to repro this issue. I was able to successfully validate my ACR access using the below command:

```
az aks check-acr -g MyaksRG -n MyAKSName --acr MyACRName.azurecr.io
Merged "MyAKSName" as current context in C:\Users\******\AppData\Local\Temp\tmp__aa0tlp
[2022-02-14T03:19:36Z] Validating image pull permission: SUCCEEDED
[2022-02-14T03:19:36Z]
Your cluster can pull images from MyACRName.azurecr.io!
```

Here is the AzCLI and Python version I am using in my box. Could you please try to [upgrade the python](https://www.python.org/downloads/) libraries and the [most recent version of](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) Azure CLI version and run the command again ? Awaiting your reply.

```
az --version
azure-cli                         2.33.0
core                                2.33.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.51
ssh                                1.0.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\****\.azure\cliextensions'
Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
Your CLI is up-to-date.

```

**Comment by mloskot** [comment]
I think I have hit the same error with much newer Azure CLI:

```
az aks check-acr -g rg-aks-my-dev -n aks-my-uks-dev-aks --acr myacruniquename.azurecr.io
Merged "aks-cadcorp-uks-dev-aks" as current context in C:\Users\mateuszl\AppData\Local\Temp\tmpqpywgvjp
W0208 09:01:31.290528   10700 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CMMLM6M5W to authenticate.
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1324, in aks_check_acr
KeyError: 'serverVersion'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

I authenticated using https://microsoft.com/devicelogin 

```
>  az --version
azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Extensions:
account                            0.2.5
azure-devops                      0.26.0
azure-firewall                    0.14.4
ssh                                1.1.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mateuszl\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

@navba-MSFT in your https://github.com/Azure/azure-cli/issues/19232#issuecomment-1038594567 What do you mean by 
> Could you please try to [upgrade the python](https://www.python.org/downloads/) libraries

Since the Azure CLI deploys and uses its own Python in `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\`, doesn't it automatically upgrade it? I have run `az upgrade` and everything seems up to date on my end.
