### ISSUE TITLE
ISO 8601 duration times generate error during "az servicebus topic create"

### ISSUE THREAD

**Issue by AnthonyRobinson** [Azure/azure-cli#19278]
## Describe the bug

**Command Name**
`az servicebus topic create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'>' not supported between instances of 'Duration' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicebus/custom.py", line 224, in cli_sbtopic_create
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicebus/custom.py", line 547, in return_valid_duration_create
TypeError: '>' not supported between instances of 'Duration' and 'datetime.timedelta'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus topic create --name {} --namespace-name {} --resource-group {} --default-message-time-to-live P1Y`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: 

azure-cli 2.27.0 *

Extensions:
azure-devops 0.20.0
interactive 0.4.5
logic 0.1.4
storage-preview 0.7.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @AnthonyRobinson, thanks for bringing this to our attention. I would triage internally and keep you posted with updates here.

**Comment by Saglodha** [comment]
Hi @AnthonyRobinson - this has been fixed in our latest release. Please review and let us know. Thanks!
