### ISSUE TITLE
Problem with az on macOS

### ISSUE THREAD

**Issue by ArturKa77** [Azure/azure-cli#19275]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'module' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 145, in login
    password = prompt_pass('Password: ')
  File "/usr/local/Cellar/azure-cli/2.27.1/libexec/lib/python3.9/site-packages/knack/prompting.py", line 58, in prompt_pass
    password = getpass.getpass(msg)
TypeError: 'module' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --tenant {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.9.6
Installer: HOMEBREW

azure-cli 2.27.1

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Looks like [`getpass.getpass`](https://docs.python.org/3/library/getpass.html) somehow becomes a module.

Could you check if `getpass` is imported from the correct path?

```
$ /usr/local/Cellar/azure-cli/2.27.1/libexec/bin/python  -c "import getpass; print(getpass, getpass.getpass)"
<module 'getpass' from '/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py'> <function unix_getpass at 0x1054d6700>
```

**Comment by ArturKa77** [comment]
➜  bin ./python -c "import getpass; print(getpass, getpass.getpass)"
<module 'getpass' from '/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py'> <function unix_getpass at 0x102d71d30>
➜  bin
