### ISSUE TITLE
az login fail with error (find_subscriptions_on_login() got an unexpected keyword argument 'scopes')

### ISSUE THREAD

**Issue by CharbelHanna** [Azure/azure-cli#19307]
## After upgrading the AZ cli do 2.27.1 az login fail with the below error, 
to note that the issue will be resolved if you downgrade to an earlier version ( 2.25.0) for example 

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
find_subscriptions_on_login() got an unexpected keyword argument 'scopes'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 152, in login
TypeError: find_subscriptions_on_login() got an unexpected keyword argument 'scopes'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

Extensions:
blueprint 0.3.1
resource-graph 2.1.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by CharbelHanna** [comment]
Hello, 

sorry for the delay in replying, no i have not installed manually any version of the azure-cli-core on my machine

Regards,
Charbel HANNA

**Comment by jiasli** [comment]
Are you still seeing this issue? Could you share the result of `az --version`?

**Comment by CharbelHanna** [comment]
Yes I am still having the same issue, 

here is the az --version output

[09:35:15] ~ on ❯  az --version
azure-cli                         2.27.1

core                              2.27.1
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.33
resource-graph                     2.1.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\channa\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by jiasli** [comment]
Looks like a problem with the Windows MSI installer. Could you check https://github.com/Azure/azure-cli/issues/18477#issuecomment-861108175 and see if it can be fixed?
