### ISSUE TITLE
Cannot run azure-cli in RHEL 8.4

### ISSUE THREAD

**Issue by LezzG** [Azure/azure-cli#19317]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I follow the instructions at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf to install azure-cli on RHEL 8.4, but it fails when I try to run any az command:

$ az login
Traceback (most recent call last):
  File "/tools/python3.6.9-ssl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tools/python3.6.9-ssl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 905, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 26, in <module>
    from azure.cli.core.util import (
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 13, in <module>
    import ssl
  File "/tools/python3.6.9-ssl/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

**To Reproduce**

Create a RHEL 8.4 system
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
sudo dnf install azure-cli
az login

**Expected behavior**

I expect it to pop up a browser window so I can authenticate to Azure

**Environment summary**

**Additional context**

Worth noting all packages that I see in https://packages.microsoft.com/yumrepos/azure-cli/ are all marked for 'el7'.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by LezzG** [comment]
Turns out I was using a bad version of python.  Totally my project's fault :-)
