### ISSUE TITLE
--library-requirements issue (az synapse spark pool create)

### ISSUE THREAD

**Issue by genegc** [Azure/azure-cli#19342]
The --library-requirements option does not appear to be working.

**Command Name**
`az synapse spark pool create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: 'name: prod-env\ndependencies:\n  - opencensus-ext-azure\n  - Faker'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/operations/sparkpool.py", line 40, in create_spark_pool
    library_requirements_content = read_file_content(library_requirements)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 484, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
  File "/usr/bin/../../opt/az/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'name: prod-env\ndependencies:\n  - opencensus-ext-azure\n  - Faker'

```

## To Reproduce:
I tried the following approaches (one using requirements.yaml file, and one using a requirements.txt file)
az synapse spark pool create --name sparkx1 --workspace-name syn-oea-cisdggv04n --resource-group rg-oea-cisdggv04n --spark-version 3.0 --node-count 3 --node-size Small --min-node-count 3 --max-node-count 10 --library-requirements @./requirements.yml --verbose

az synapse spark pool create --name sparkx1 --workspace-name syn-oea-cisdggv04n --resource-group rg-oea-cisdggv04n --spark-version 3.0 --node-count 3 --node-size Small --min-node-count 3 --max-node-count 10 --library-requirements @./requirements.txt --verbose

## Expected Behavior
I would expect for the spark pool to be provisioned and the requirments library to be included.

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *
azure-cli-ml 1.23.0

Extensions:
datafactory 0.5.0
azure-cli-ml 1.23.0
application-insights 0.1.13
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by idear1203** [comment]
Please try removing `@` because `--library-requirements` wants a file path rather than file content.
