### ISSUE TITLE
Az Login failed temporarily in the Pipeline

### ISSUE THREAD

**Issue by matthid** [Azure/azure-cli#19371]
## Describe the bug

We use `az login` in one of our Azure DevOps release pipelines to deploy stuff to azure (probably not relevant in this issue).
Today the pipeline failed temporarily (worked after retry) with an error I couldn't find any google results for.
Therefore I decided to report it here.

**Command Name**
`az login`

**Output & Errors:**
```


Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Setting AZURE_CONFIG_DIR env variable to: D:\Agent1\_work\_temp\.azclitask
Setting active cloud to: AzureCloud
C:\WINDOWS\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
C:\WINDOWS\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: cannot import name 'register_algorithm' from 'jwt.api_jwt' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\jwt\api_jwt.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 118, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/__init__.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/authentication_context.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/self_signed_jwt.py", line 35, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/__init__.py", line 19, in <module>
ImportError: cannot import name 'register_algorithm' from 'jwt.api_jwt' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\jwt\api_jwt.pyc)
To open an issue, please run: 'az feedback'
##[error]Error Code: [1]
##[error]Error: Azure login failed
##[error]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: cannot import name 'register_algorithm' from 'jwt.api_jwt' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\jwt\api_jwt.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 118, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/__init__.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/authentication_context.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/token_request.py", line 34, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\adal/self_signed_jwt.py", line 35, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/__init__.py", line 19, in <module>
ImportError: cannot import name 'register_algorithm' from 'jwt.api_jwt' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\jwt\api_jwt.pyc)
To open an issue, please run: 'az feedback'
```

## To Reproduce:
See output above

## Expected Behavior
Works

## Environment Summary

<html>
<body>

Name | Value 
-- | -- 
Agent.Name | TEAMBUILD17_B1
AzureCLI | 2.3.0
DotNetCore | 3.1.401
Agent.Version | 2.190.0
Agent.ComputerName | TEAMBUILD17
Agent.HomeDirectory | D:\Agent1
Agent.OS | Windows_NT
Agent.OSArchitecture | X64 
Agent.OSVersion | 10.0.19043
Path | C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WI...
AzurePS | 5.7.0
PowerShell | 5.1.19041.1151

</body>
</html>

## Additional Context

So it seems like we use python 2.7 there. That is still supported, correct?

**Comment by jiasli** [comment]
You are using Azure CLI 2.3.0 which is a very old version. Could you use the latest Azure CLI and see if the problem still exists?

**Comment by MaddyMicrosoft** [comment]
Closing as stale. The trace is from Azure CLI 2.3.0 (2020), which used the retired ADAL stack; `az login` uses MSAL now. Since the failure was transient (`worked after retry`), it's most likely a network blip in the pipeline. If similar failures show up on current CLI , please open a fresh issue.
