### ISSUE TITLE
az k8s-configuration module Crypto error

### ISSUE THREAD

**Issue by nithinmohantk** [Azure/azure-cli#19388]
## Describe the bug

**Command Name**
`az k8s-configuration`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.PublicKey._ec_ws': Trying '_ec_ws.cp38-win32.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.cp38-win32.pyd', Trying '_ec_ws.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.pyd'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 582, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 260, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2006, in _parse_known_args
  File "argparse.py", line 1946, in consume_optional
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1044, in __call__
  File "argparse.py", line 2494, in print_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 195, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 247, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 168, in show_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 306, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 240, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\custom.py", line 12, in <module>
    from azext_k8s_configuration._validators import _validate_known_hosts, _validate_url_with_params, \
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\_validators.py", line 18, in <module>
    from Crypto.PublicKey import RSA, ECC, DSA
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\PublicKey\ECC.py", line 58, in <module>
    _ec_lib = load_pycryptodome_raw_lib("Crypto.PublicKey._ec_ws", """
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.PublicKey._ec_ws': Trying '_ec_ws.cp38-win32.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.cp38-win32.pyd', Trying '_ec_ws.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.pyd'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az k8s-configuration -h`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.0 *

Extensions:
aks-preview 0.5.28
azure-devops 0.20.0
connectedk8s 1.1.7
k8s-configuration 1.1.0

```

**Comment by yonzhan** [comment]
route to service team
