### ISSUE TITLE
invalid syntax SCM_DO_BUILD_DURING_DEPLOYMENT=false when deploying ZIP file

### ISSUE THREAD

**Issue by coderbyheart** [Azure/azure-cli#19431]
## Describe the bug

When trying to deploy a function app from a ZIP file this error happens:

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/util.py", line 512, in shell_safe_json_parse
    return ast.literal_eval(json_or_dict_string)
  File "/usr/local/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    SCM_DO_BUILD_DURING_DEPLOYMENT=false
                                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 396, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 515, in remove_remote_build_app_settings
    update_app_settings(cmd, resource_group_name, name, [
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 260, in update_app_settings
    temp = shell_safe_json_parse(s)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/util.py", line 525, in shell_safe_json_parse
    parent_proc = get_parent_proc_name().lower()
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp deployment source config-zip -g {} -n {} --src {} --debug`

## Expected Behavior

The ZIP file is deployed.

## Environment Summary

```
Linux-5.13.13-arch1-1-x86_64-with
Python 3.8.9
Installer: DOCKER

azure-cli 2.27.2

Extensions:
azure-iot 0.10.15

```

**Comment by yonzhan** [comment]
route to service team

**Comment by coderbyheart** [comment]
Workaround is to set add this to the function app configuration:

```json
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "0"
            },
```

so it wont be set wrongly during the deployment.

**Comment by navba-MSFT** [comment]
@coderbyheart Apologies for the late reply. Could you please confirm if you had a chance to follow the above plan ? Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by coderbyheart** [comment]
There is no plan above.

**Comment by navba-MSFT** [comment]
@coderbyheart My bad. I was looking at another github thread and thought I was commenting on that. The Action Plan I wanted to share is to try using the [most recent version of AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and check if you are getting the same issue ? Awaiting your reply.

**Comment by coderbyheart** [comment]
The workaround is no longer needed with version 2.33.1
