### ISSUE TITLE
Can't upgrade to remote build, az crashed

### ISSUE THREAD

**Issue by JohanRyberg** [Azure/azure-cli#19434]
## Describe the bug

**Command Name**
`az functionapp update`

**Errors:**
```
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 419, in cached_put
    return _put_operation()
cli/core/commands/__init__.py, ln 414, in _put_operation
    result = operation(parameters=parameters, **kwargs)
cli/command_modules/appservice/custom.py, ln 574, in set_functionapp
    if 'function' not in instance.kind:
AttributeError: 'NoneType' object has no attribute 'kind'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp update -g {} -n {}`

## Environment Summary
```
Linux-5.4.0-74-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by JohanRyberg** [comment]
Upgraded az to the latest version. Same error
```
johan@cts:~$ az --version
azure-cli                         2.27.2

core                              2.27.2
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/johan/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Aug 23 2021, 03:36:00)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

```

```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 61, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 447, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 441, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 688, in set_functionapp
    if 'function' not in instance.kind:
AttributeError: 'NoneType' object has no attribute 'kind'

```

**Comment by JohanRyberg** [comment]
There are no functions yet. I'm trying to build my first function using remote build.

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@JohanRyberg does this still repro for you?

**Comment by JohanRyberg** [comment]
@panchagnula

Hi, thanks for reaching out.

Has this issue been fixed? It's not linked to this issue

Regards Johan Ryberg

**Comment by panchagnula** [comment]
@JohanRyberg we can't repro this issue , hence no fix was linked to this. 
Will try this locally on an empty functionapp (no functions) & update this.

@haroonf can you check if you can repro this by creating  an empty  function app using functionapp create & then try an update on the same?

**Comment by JohanRyberg** [comment]
It might have been fixed in later versions? Was the exact same versions used during the test?
