### ISSUE TITLE
 AKS Cluster deployment via CLI fails

### ISSUE THREAD

**Issue by Mparvez123** [Azure/azure-cli#19430]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 AKS Cluster deployment via CLI fails

**To Reproduce**
Deploy AKS clusters using CLI - Az deployment command 

**Expected behavior**
Successful cluster deployment

**Environment summary**
the “az commands” are throwing following errors some time from cloud shell(command line) as well as from the Jenkins jobs.

Traceback (most recent call last):
File "/opt/az/lib/python3.6/logging/__init__.py", line 998, in emit
self.flush()
File "/opt/az/lib/python3.6/logging/__init__.py", line 978, in flush
self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:

**Additional context**
Please find the error attached.
--- Logging error ---
Traceback (most recent call last):
File "/opt/az/lib/python3.6/logging/__init__.py", line 998, in emit
self.flush()
File "/opt/az/lib/python3.6/logging/__init__.py", line 978, in flush
self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 48, in <module>
exit_code = cli_main(az_cli, sys.argv[1:])
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 35, in cli_main
return cli.invoke(args)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
self.raise_event(EVENT_CLI_POST_EXECUTE)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
func(self, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 180, in deinit_cmd_metadata_logging
cli_ctx.logging.end_cmd_metadata_logging(cli_ctx.result.exit_code if cli_ctx.result else 128)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 184, in end_cmd_metadata_logging
self.command_metadata_logger.info("exit code: %s", exit_code)
Message: 'exit code: %s'
Arguments: (0,)
Traceback (most recent call last):
File "/opt/az/lib/python3.6/logging/__init__.py", line 1043, in close
self.flush()
File "/opt/az/lib/python3.6/logging/__init__.py", line 978, in flush
self.stream.flush()
OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 48, in <module>
exit_code = cli_main(az_cli, sys.argv[1:])
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 35, in cli_main
return cli.invoke(args)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
self.raise_event(EVENT_CLI_POST_EXECUTE)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
func(self, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 180, in deinit_cmd_metadata_logging
cli_ctx.logging.end_cmd_metadata_logging(cli_ctx.result.exit_code if cli_ctx.result else 128)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 189, in end_cmd_metadata_logging
self.command_logger_handler.close()
File "/opt/az/lib/python3.6/logging/__init__.py", line 1048, in close
stream.close()
OSError: [Errno 116] Stale file handle
+ echo 'AKS deployment Failed'
AKS deployment Failed

**Comment by yonzhan** [comment]
route to service team

**Comment by Mparvez123** [comment]
Hi,

Can we have an update on this please?

Thanks

**Comment by Mparvez123** [comment]
Hi,

Can we have an update on this please?

Thanks

**Comment by miwithro** [comment]
hello @Mparvez123  you are on a pretty old version of the azure cli.  The latest version is 2.27.1.  Can you run az upgrade --all and then try the deployment again?

**Comment by Mparvez123** [comment]
Sure, will try and let you know our feedback. Thanks

**Comment by Mparvez123** [comment]
Hi,

After upgraded to az cli version to 2.28.0
+++++++++++++++++++
az version
{
"azure-cli": "2.28.0",
"azure-cli-core": "2.28.0",
"azure-cli-telemetry": "1.0.6",
"extensions": {}
}
+++++++++++++++++++
Getting following error message while running az deployment command
_______________________
--- Logging error ---
Traceback (most recent call last):
File "/opt/az/lib/python3.6/logging/__init__.py", line 998, in emit
self.flush()
File "/opt/az/lib/python3.6/logging/__init__.py", line 978, in flush
self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 48, in <module>
exit_code = cli_main(az_cli, sys.argv[1:])
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 35, in cli_main
return cli.invoke(args)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 250, in invoke
self.raise_event(EVENT_CLI_POST_EXECUTE)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
func(self, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 188, in deinit_cmd_metadata_logging
cli_ctx.logging.end_cmd_metadata_logging(cli_ctx.result.exit_code if cli_ctx.result else 128)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 192, in end_cmd_metadata_logging
self.command_metadata_logger.info("exit code: %s", exit_code)
Message: 'exit code: %s'
Arguments: (0,)
WARNING: Auto upgrade failed. name 'exit_code' is not defined
Traceback (most recent call last):
File "/opt/az/lib/python3.6/logging/__init__.py", line 1043, in close
self.flush()
File "/opt/az/lib/python3.6/logging/__init__.py", line 978, in flush
self.stream.flush()
OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

OSError: [Errno 116] Stale file handle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 48, in <module>
exit_code = cli_main(az_cli, sys.argv[1:])
File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 35, in cli_main
return cli.invoke(args)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 250, in invoke
self.raise_event(EVENT_CLI_POST_EXECUTE)
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
func(self, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 188, in deinit_cmd_metadata_logging
cli_ctx.logging.end_cmd_metadata_logging(cli_ctx.result.exit_code if cli_ctx.result else 128)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 197, in end_cmd_metadata_logging
self.command_logger_handler.close()
File "/opt/az/lib/python3.6/logging/__init__.py", line 1048, in close
stream.close()
OSError: [Errno 116] Stale file handle

**Comment by Mparvez123** [comment]
Hi Team,

Any updates on the previous request?

**Comment by Mparvez123** [comment]
Hi Team,

Awaiting your response. Can you please look to this on priority?

**Comment by Mparvez123** [comment]
@miwithro Can you please investigate and provide an update?

**Comment by miwithro** [comment]
In looking into this error this seems to be due to some resource constraints on the system you are executing the cli from.  I found a bunch of random references to the errors you are getting while nothing directly.   All seem to point to the same thing.

https://support.delphix.com/Delphix_Virtualization_Engine/Delphix_Admin/Resolving_%22Stale_File_Handle%22_Error_on_Linux_Systems_(KBA1037)

**Comment by navba-MSFT** [comment]
@Mparvez123 Apologies for the late reply. Could you please let us know if you have tried with the recent version [2.33.0 of AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) ? Also please let us know the Azure CLI command that you are executing from the Azure Cloud shell? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Mparvez123 Could you please let us know if you had a chance to follow the action plan mentioned in my above comment? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Mparvez123 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
