### ISSUE TITLE
az network private-endpoint dns-zone-group add is inconsistent and subscription ID mapping does not work

### ISSUE THREAD

**Issue by spotakash** [Azure/azure-cli#19444]
## Describe the bug

**Command Name**
`az network private-endpoint dns-zone-group add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'private_dns_zone_configs'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 3106, in add_private_endpoint_private_dns_zone
    private_dns_zone_group.private_dns_zone_configs.append(private_dns_zone)
AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint dns-zone-group add --endpoint-name {} -g {} -n {} --zone-name {} --private-dns-zone {}`

## Environment Summary
```
Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.1

Extensions:
aks-preview 0.5.25
azure-firewall 0.12.0
k8sconfiguration 0.2.4
virtual-wan 0.2.7

```

**Comment by yonzhan** [comment]
network

**Comment by spotakash** [comment]
Found that "create" command worked not "add" as dnszonegroup record exist. Which is difficult to locate unless his error while error description does tell it clearly unless --debug

**Comment by 00Kai0** [comment]
Hi @spotakash , could you try with the latest version 2.28.1 ?

**Comment by yonzhan** [comment]
Hi @spotakash, any update?
