### ISSUE TITLE
az aks error

### ISSUE THREAD

**Issue by karthikgouni** [Azure/azure-cli#19479]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'C:\\Users\\saish\\.azure-kubelogin\\kubelogin.exe'
Traceback (most recent call last):
  File "shutil.py", line 791, in move
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\saish\\AppData\\Local\\Temp\\tmpk467hzch\\bin\\windows_amd64\\kubelogin.exe' -> 'C:\\Users\\saish\\.azure-kubelogin\\kubelogin.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 342, in k8s_install_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 466, in k8s_install_kubelogin
  File "shutil.py", line 811, in move
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\saish\\.azure-kubelogin\\kubelogin.exe'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@karthikgouni Apologies for the late reply. Could you please use the `--install-location` parameter and try giving a different path and check if the installation works fine ? Refer [this](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-cli) for more details.

>--install-location
Path at which to install kubectl.
default value: ~/.azure-kubectl/kubectl.exe

Awaiting your reply.
