### ISSUE TITLE
ValueError: time data '2021-09-08T10:52:52.213Z' does not match format '%Y-%m-%d %H:%M:%S.%f'

### ISSUE THREAD

**Issue by mhyllander** [Azure/azure-cli#19485]
## Describe the bug

I started getting this error today. I'm running Ubuntu 20.04 in WSL2, with latest apt updates. This happened first with 2.27.1, then I updated to 2.28.0, and the error persists.

**Command Name**
`az vm list`

The same error occurred with: `az network lb list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
time data '2021-09-08T10:52:52.213Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 1185, in list_vm
    return list(vm_list)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/compute/v2021_04_01/operations/_virtual_machines_operations.py", line 1158, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 69, in send
    _await_result(self._policy.on_request, request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
    result = func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 108, in get_token
    datetime.datetime.strptime(token_entry['expiresOn'], '%Y-%m-%d %H:%M:%S.%f')))
  File "/opt/az/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/opt/az/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2021-09-08T10:52:52.213Z' does not match format '%Y-%m-%d %H:%M:%S.%f'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
vm-repair 0.3.5
aks-preview 0.5.5
image-copy-extension 0.2.8

```

**Comment by mhyllander** [comment]
Maybe this was just a temporary issue? After `az logout`, `az login` as another user, it worked. Logging in as the first user again also worked.

**Comment by yonzhan** [comment]
@zhoxing-ms to take a look

**Comment by zhoxing-ms** [comment]
@mhyllander This issue seems to be the same as #18333. You can refer to the comment https://github.com/Azure/azure-cli/issues/18333#issuecomment-861207480 provided by @jiasli

**Comment by mhyllander** [comment]
@zhoxing-ms Yes, looks to be the same thing. Thanks!
