### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by mvalenzisi** [Azure/azure-cli#19504]
**Describe the bug**

During the installation phase the script throws this error:
```
    ERROR: Command errored out with exit status 1:
     command: /home/mau/azure-cli/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p24n1qif/jsmin_de400cde6f7c46eab51af55dff500699/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p24n1qif/jsmin_de400cde6f7c46eab51af55dff500699/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-50gwi6au
         cwd: /tmp/pip-install-p24n1qif/jsmin_de400cde6f7c46eab51af55dff500699/
    Complete output (1 lines):
    error in jsmin setup command: use_2to3 is invalid.
    ----------------------------------------
```

The installation completes, but the cli does not work, any command fails with the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mau/azure-cli/lib/python3.8/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/home/mau/azure-cli/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 546, in get_default_cli
    return AzCli(cli_name='az',
  File "/home/mau/azure-cli/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/home/mau/azure-cli/lib/python3.8/site-packages/azure/cli/core/_session.py", line 46, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'
```

**To Reproduce**

Run any command.

**Expected behavior**

The cli to work correctly, and no errors during the installation.

**Environment summary**

- install method: interactive script
- cli version: 2.28.0
- os version: Linux gentoo 5.10.27-gentoo-x86_64
- shell type: bash
- python version: 3.8.12

**Comment by jiasli** [comment]
Caused by https://github.com/Azure/azure-cli/issues/19468

**Comment by nullcharb** [comment]
Still seeing this on macos for some reason. 
![Screen Shot 2022-01-07 at 11 06 36 pm](https://user-images.githubusercontent.com/58240340/148548325-78dce42b-19f1-47d0-af98-b1c876d2a8ae.png)
<img width="459" alt="Screen Shot 2022-01-07 at 11 07 19 pm" src="https://user-images.githubusercontent.com/58240340/148548333-1c7c0317-3559-4387-9758-abd10a8d9cda.png">
