### ISSUE TITLE
not able to run cli command for delete in blob container using sas token

### ISSUE THREAD

**Issue by SoumyadipB** [Azure/azure-cli#19525]
## Describe the bug

**Command Name**
`az storage file delete-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
share_name should not be None.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/file.py", line 308, in storage_file_delete_batch
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/util.py", line 100, in glob_files_remotely
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/file/fileservice.py", line 1214, in list_directories_and_files
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/file/fileservice.py", line 1248, in _list_directories_and_files
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/_error.py", line 130, in _validate_not_none
ValueError: share_name should not be None.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage file delete-batch --source {} --account-name {} --sas-token {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
storage
