### ISSUE TITLE
Cannot run `az container attach`

### ISSUE THREAD

**Issue by qmacro** [Azure/azure-cli#19529]
## Describe the bug

**Command Name**
`az container attach`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 740, in attach_to_container
    container_client = cf_container(cmd.cli_ctx)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
    return _container_instance_client_factory(cli_ctx).container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container attach --name {} --resource-group {}`

## Expected Behavior
I should be attached to a container, or at least not get an error like this.

## Environment Summary
```
Linux-5.4.119-14945-gafc97d54f809-x86_64-with-debian-10.10, Debian GNU/Linux 10 (buster)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

```
## Additional Context

This is a crostini-based Linux environment (i.e. on Chrome OS)

**Comment by yonzhan** [comment]
route to service team

**Comment by jhwj9617** [comment]
Similar issue as this: https://github.com/Azure/azure-cli/issues/19489.

**Comment by PramodValavala-MSFT** [comment]
@qmacro Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.

**Comment by qmacro** [comment]
Thanks! 👍
