### ISSUE TITLE
Connect to container failed

### ISSUE THREAD

**Issue by prasanta4u** [Azure/azure-cli#19535]
## Describe the bug

**Command Name**
`az container exec`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 609, in container_exec
    container_client = cf_container(cmd.cli_ctx)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
    return _container_instance_client_factory(cli_ctx).container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec --exec-command {} --name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by EdiFirst** [comment]
Guys, I'm facing the same issue. Is there news?

**Comment by kf6kjg** [comment]
Probably the same underlying problem and workarounds as #19489

**Comment by PramodValavala-MSFT** [comment]
@prasanta4u Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.

**Comment by prasanta4u** [comment]
Thanks, I am unable to reproduce now. kindly take this for closure
