### ISSUE TITLE
"az container start" issue in 2.28 ERROR: Operation returned an invalid status 'No Content'

### ISSUE THREAD

**Issue by jayeshu** [Azure/azure-cli#19530]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
We suddenly getting error on YAML task "az container create ..."
The pipeline was working fine with 2.27.2 version.

##[debug]addSpnToEnvironment=false
##[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   . 'D:\a\_temp\azureclitaskscript1631282790185.ps1'
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1631282790185.ps1'"
ERROR: Operation returned an invalid status 'No Content'
##[debug]$LASTEXITCODE: 1
##[debug]Exit code 1 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]task result: Failed
##[error]Script failed with exit code: 1
##[debug]Processed: ##vso[task.issue type=error;]Script failed with exit code: 1
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with exit code: 1

**To Reproduce**
Our YAML definition looks like below :
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'az container create acixxxxxxxx'
            inputs:
              azureSubscription: '${{ parameters.AZURE_SUBSCRIPTION }}'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: 'az container create -g ${{ parameters.RESOURCE_GROUP }} -l eastus --name acixxxxxxxx --image ${{ parameters.REGISTRY_URL }}/smi:${{ parameters.TAG }}  --restart-policy Never --registry-username "${{ parameters.REGISTRY_USERNAME }}" --registry-password "${{ parameters.REGISTRY_PASSWORD }}" --assign-identity ${{ parameters.CONTAINER_IDENTITY }} --command-line "java -jar xxx.jar --azure.keyvault.client-id=${{ parameters.KEYVAULT_CLIENT_ID }} --azure.keyvault.client-key=${{ parameters.KEYVAULT_CLIENT_KEY }} --azure.keyvault.tenant-id=${{ parameters.KEYVAULT_TENANT_ID }} --azure.keyvault.uri=${{ parameters.KEYVAULT_ENDPOINT }} --azure.application-insights.instrumentation-key=${{ parameters.APP_INSIGHTS_KEY }}"'
            timeoutInMinutes: 5

**Expected behavior**
Pipeline should create ACI and run task

**Environment summary**

image : windows-latest
task : AzureCLI@2
command : az container create

Error: ERROR: Operation returned an invalid status 'No Content'

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by Stateofminf** [comment]
coCo

**Comment by Text-only** [comment]
Is container still on 

D:\

Has the ntfs letter changed?

**Comment by jayeshu** [comment]
The container is not ON ... we purposely STOP the container at the end as separate task.

**Comment by BartekR** [comment]
Have the same issue. `az container start ...` stopped working after the Azure DevOps Hosted Agent (windows-2019 image) was upgraded and contained AZ CLI 2.28.0 instead of 2.27.2. No changes in the pipeline.
Running `az container start ...` from my AZ CLI (2.27.1) still works as expected. With 2.28.0 in Azure DevOps Hosted Agent (windows 2019), I have the `ERROR: Operation returned an invalid status 'No Content'` entry.
The container I use is SQL Server 2019 CU8. Also - when I started having `az container start` issues, I started seeing many `invalid login` entries for the database user in the container logs.
Using the same user/password and logging into the database in the container using SSMS worked correctly.

**Comment by jayeshu** [comment]
here is more debug info on the same issue.

`
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /***/oauth2/token HTTP/1.1" 200 1466
DEBUG: adal-python: 4a60ac6d-eaed-49ed-bcc2-340aed97f695 - OAuth2Client:Get Token Server returned this correlation_id: 4a60ac6d-eaed-49ed-bcc2-340aed97f695
DEBUG: adal-python: 4a60ac6d-eaed-49ed-bcc2-340aed97f695 - CacheDriver:Adding entry AccessTokenId: xxxx'
DEBUG: adal-python: 4a60ac6d-eaed-49ed-bcc2-340aed97f695 - CacheDriver:Added entry is MRRT
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/xxxxxxxx-1xcxx-43b9-aecd-xxxxxxxxxxx/resourceGroups/rg-group-name/providers/Microsoft.ContainerInstance/containerGroups/container-name/start?api-version=2021-03-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'POST'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '47c84088-1bf7-11ec-9584-00155d00040f'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'container start'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --name --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.28.0 (MSI) azsdk-python-mgmt-containerinstance/8.0.0 Python/3.8.9 (Windows-10-10.0.17763-SP0) VSTS_50466eb3-8b38-4fee-ac26-00b60b7ea1fb_build_352_0'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/xxxxxxxx-1xcxx-43b9-aecd-xxxxxxxxxxx/resourceGroups/rg-group-name/providers/Microsoft.ContainerInstance/containerGroups/container-name/start?api-version=2021-03-01 HTTP/1.1" 204 0
DEBUG: cli.azure.cli.core.sdk.policies: **Response status: 204**
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'eastus:ecf55e95-691e-4639-8231-efd358a35a90'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '088ee356-85e6-45be-82a9-09d59bab702b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20210922T224902Z:088ee356-85e6-45be-82a9-09d59bab702b'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 22 Sep 2021 22:49:01 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: 
**DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:**
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerinstance/operations/_container_groups_operations.py", line 832, in begin_start
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerinstance/operations/_container_groups_operations.py", line 791, in _start_initial
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'No Content'

**ERROR: cli.azure.cli.core.azclierror: Operation returned an invalid status 'No Content'**
ERROR: az_command_data_logger: Operation returned an invalid status 'No Content'
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x034499B8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.531 seconds (init: 0.435, invoke: 1.096)
INFO: telemetry.save: Save telemetry record of length 2965 in cache
WARNING: telemetry.check: Negative: The D:\a\_temp\.azclitask\telemetry.txt was modified at 2021-09-22 22:48:15.663824, which in less than 600.000000 s
##[error]Script failed with exit code: 1
`

**According to documentation of that [API](https://docs.microsoft.com/en-us/rest/api/container-instances/container-groups/start) it returns 204 status only. 
So why AZ CLI acts 204 as an error ?**
