### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback

### ISSUE THREAD

**Issue by khanhtt0310** [Azure/azure-cli#19537]
## Describe the bug

**Command Name**
`az container delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerGroupsOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 66, in delete_container
    return client.delete(resource_group_name, name)
AttributeError: 'ContainerGroupsOperations' object has no attribute 'delete'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container delete --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by atmaxinger** [comment]
Hi, 
we are also running into this problem on Azure CLI in hosted Azure Pipelines agents.

```
2021-09-10T11:00:30.7062434Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-09-10T11:00:31.5215537Z azure-cli                         2.28.0
2021-09-10T11:00:31.5215963Z 
2021-09-10T11:00:31.5216387Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-09-10T11:00:31.5216988Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-09-10T11:00:31.5217291Z 
2021-09-10T11:00:31.5217904Z core                              2.28.0
2021-09-10T11:00:31.5218831Z telemetry                          1.0.6
2021-09-10T11:00:31.5219303Z 
2021-09-10T11:00:31.5219707Z Extensions:
2021-09-10T11:00:31.5220187Z azure-devops                      0.20.0
```

```
2021-09-10T11:00:33.9507878Z [command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1631271630643.ps1'"
2021-09-10T11:00:35.3289621Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-09-10T11:00:35.3292263Z ERROR: 'ContainerGroupsOperations' object has no attribute 'delete'
2021-09-10T11:00:35.3292904Z Traceback (most recent call last):
2021-09-10T11:00:35.3293747Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-09-10T11:00:35.3294575Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-09-10T11:00:35.3295412Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-09-10T11:00:35.3296297Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-09-10T11:00:35.3297128Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-09-10T11:00:35.3297963Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2021-09-10T11:00:35.3298834Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 66, in delete_container
2021-09-10T11:00:35.3299581Z AttributeError: 'ContainerGroupsOperations' object has no attribute 'delete'
2021-09-10T11:00:35.3887949Z To open an issue, please run: 'az feedback'
```

**Comment by ddelapasse2** [comment]
Here too!

Failed command: az container delete –resource-group rg-inform-predict-uat –name uat-ipmonitor --yes

![image](https://user-images.githubusercontent.com/18335575/133142162-cd829c76-5ac3-4a18-9f02-dfa349288e7e.png)

**Comment by atmaxinger** [comment]
Seems to be related to  #19489

**Comment by PramodValavala-MSFT** [comment]
@khanhtt0310 Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.
