### ISSUE TITLE
Error while trying to view logs on (likely) bad container deploy

### ISSUE THREAD

**Issue by tmswfrk** [Azure/azure-cli#19542]
## Describe the bug
Been trying to follow the docs I've found both officially and elsewhere online. I'm a bit limited on my knowledge of docker and Azure, and especially with the two together, but I understand what I'm at least trying to do here. I've created a container, i've tagged it, set up a service principal, and have pushed the container to my registry. However, it appears that after a `container create`, the container is restarting and not properly coming online - which could be likely due to a misconfigured or missing config file (which would be my issue). Unfortunately I cannot confirm this as trying to retrieve the specific logs for this container is failing for me. I've also attempted to attach to the container to stream stdout/stderr, but a similar message appears here as well.

**Command Name**
`az container logs`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
    return _container_instance_client_factory(cli_ctx).container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container logs --resource-group {} --name {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit, Darwin 20.5.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Stateofminf** [comment]
Q

**Comment by kf6kjg** [comment]
Probably the same underlying problem and workarounds as #19489

**Comment by PramodValavala-MSFT** [comment]
@tmswfrk Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.
