### ISSUE TITLE
Cannot update staticwebapp user roles from the CLI.

### ISSUE THREAD

**Issue by rwaldin** [Azure/azure-cli#19550]
## Describe the bug
Cannot update staticwebapp user roles from the CLI.

**Command Name**
`az staticwebapp users update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
update_static_site_user() missing 1 required positional argument: 'static_site_user_envelope'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/static_sites.py", line 190, in update_staticsite_users
    return client.update_static_site_user(resource_group_name, name, authentication_provider, user_id, roles=roles)
TypeError: update_static_site_user() missing 1 required positional argument: 'static_site_user_envelope'

```

## To Reproduce:
This command fails with any valid staticwebapp name (-n) and valid user-id or user-details argument.
- `az staticwebapp users update -n {} --roles {} --user-details {}`

## Expected Behavior
The command updates the specified users roles to those specified on the command line.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.28.0

Extensions:
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by StrawnSC** [comment]
Sorry about the issue here @rwaldin -- looks like it may have been broken by a recent SDK update. I'm working on a fix now. It should be ready for the next CLI release (Jan 4)

**Comment by StrawnSC** [comment]
Closing this because the fix has been released. @rwaldin please upgrade your CLI version and reopen the issue if you're still seeing the bug
