### ISSUE TITLE
az security location list fails with "type 'bool' is not an acceptable base type"

### ISSUE THREAD

**Issue by schrewe** [Azure/azure-cli#19559]
## Describe the bug

**Command Name**
`az security location list`

**Errors:**

$ az security location list
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
type 'bool' is not an acceptable base type
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 480, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 315, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 789, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 829, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/security/custom.py", line 6, in <module>
    from azure.mgmt.security.models import (SecurityContact,
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/__init__.py", line 9, in <module>
    from ._security_center import SecurityCenter
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/_security_center.py", line 21, in <module>
    from .operations import ComplianceResultsOperations
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/operations/__init__.py", line 9, in <module>
    from ._compliance_results_operations import ComplianceResultsOperations
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/operations/_compliance_results_operations.py", line 17, in <module>
    from .. import models
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/__init__.py", line 10, in <module>
    from ._models_py3 import AadConnectivityState
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/_models_py3.py", line 14, in <module>
    from ._security_center_enums import *
  File "/usr/lib/python3/dist-packages/azure/mgmt/security/models/_security_center_enums.py", line 258, in <module>
    class Enum37(with_metaclass(_CaseInsensitiveEnumMeta, bool, Enum)):
  File "/usr/lib/python3/dist-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "/usr/lib/python3.9/enum.py", line 214, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
TypeError: type 'bool' is not an acceptable base type
To open an issue, please run: 'az feedback'

```
type 'bool' is not an acceptable base type
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 480, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
lib/python3/dist-packages/six.py, ln 872, in __new__
    return meta(name, resolved_bases, d)
usr/lib/python3.9/enum.py, ln 214, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
TypeError: type 'bool' is not an acceptable base type
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az security location list`

## Environment Summary
```
Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
Python 3.9.7
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@schrewe Apologies for the late reply. I was able to run the command on my box. Could you please use the [most recent version of the AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and check if you still face the same issue ? Awaiting your reply.
