### ISSUE TITLE
az k8s-configuration show failure

### ISSUE THREAD

**Issue by nithinmohantk** [Azure/azure-cli#19562]
## Describe the bug

**Command Name**
`az k8s-configuration show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.PublicKey._ec_ws': Trying '_ec_ws.cp38-win32.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.cp38-win32.pyd', Trying '_ec_ws.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.pyd'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 367, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 70, in load_getter_op_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\custom.py", line 12, in <module>
    from azext_k8s_configuration._validators import _validate_known_hosts, _validate_url_with_params, \
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\azext_k8s_configuration\_validators.py", line 18, in <module>
    from Crypto.PublicKey import RSA, ECC, DSA
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\PublicKey\ECC.py", line 58, in <module>
    _ec_lib = load_pycryptodome_raw_lib("Crypto.PublicKey._ec_ws", """
  File "C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\_raw_api.py", line 308, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.PublicKey._ec_ws': Trying '_ec_ws.cp38-win32.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.cp38-win32.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.cp38-win32.pyd', Trying '_ec_ws.pyd': cannot load library 'C:\Users\nithinkadumberi\.azure\cliextensions\k8s-configuration\Crypto\Util\..\PublicKey\_ec_ws.pyd': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\nithinkadumberi\\.azure\\cliextensions\\k8s-configuration\\Crypto\\Util\\..\\PublicKey\\_ec_ws.pyd'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az k8s-configuration show --name {} --cluster-name {} --resource-group {} --cluster-type {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.0 *

Extensions:
aks-preview 0.5.29
azure-devops 0.20.0
blueprint 0.3.1
connectedk8s 1.1.7
k8s-configuration 1.1.0
resource-graph 2.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by nithinmohantk** [comment]
Nicely routed to a Service team, yet no response.  Great!, support.

**Comment by NarayanThiru** [comment]
Apologize for the delay in responding to this - somehow it got missed!
Regarding this issue, in our CLI extension we have specified 'pycryptodome' as a dependency, and it should be installed by Az CLI when the 'k8s-configuration' extension was installed.  Looks like this did not happen.
I have reached out to the Az CLI team about this.  In the meantime, if possible, can you remove this extension, reinstall and try again?
Thank you very much for trying out our CLI extension and once again, very sorry about this error and more importantly the delay in responding to the issue.  Going forward, we'll make sure to not miss issues reported by our customers.
I'll keep this issue open until I get a response from the Az CLI team.

**Comment by NarayanThiru** [comment]
We investigated and found that this is an issue in az extension add, and I've opened a bug for the Az CLI team to track this.
In the meantime, @nithinmohantk, you can try installing pycryptodome by directly installing it using "pip install".

**Comment by NarayanThiru** [comment]
This issue has been resolved and the fix will be rolled out on 12/07, as mentioned in the root cause issue (https://github.com/Azure/azure-cli/issues/20431).

**Comment by nithinmohantk** [comment]
Issue seems to have resolved in updated vesions. Hence closing the ticket.
