### ISSUE TITLE
az container logs / az container attach throw an error on Ubuntu 21.04

### ISSUE THREAD

**Issue by chrishardenkio** [Azure/azure-cli#19566]
## Describe the bug

**Command Name**
`az container logs`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
    return _container_instance_client_factory(cli_ctx).container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container logs --resource-group {} --name {}`

## Environment Summary
```
Linux-5.11.0-34-generic-x86_64-with-debian-bullseye-sid, Ubuntu 21.04
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by ghelyar** [comment]
https://github.com/Azure/azure-cli/issues/19558

**Comment by kf6kjg** [comment]
Probably the same underlying problem and workarounds as #19489

**Comment by PramodValavala-MSFT** [comment]
@chrishardenkio Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.
