### ISSUE TITLE
YQ DNS records 

### ISSUE THREAD

**Issue by arunadevendra** [Azure/azure-cli#19577]
## Describe the bug

**Command Name**
`az network dns zone export`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'$ttl'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 2151, in export_zone
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/make_zone_file.py", line 67, in make_zone_file
KeyError: '$ttl'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns zone export -g {} -n {} -f {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
network

**Comment by mbulik** [comment]
Hi,
I see the same issue but on a Linux (Centos 7.8.2003) system and when the command is run inside a Jenkins job. When run interactively it works normally. The Azure CLI version is 2.28.
[jenkins-job-error.txt](https://github.com/Azure/azure-cli/files/7251805/jenkins-job-error.txt)
I attach the error message.
Thank you,
Michal
