### ISSUE TITLE
Cannot create delivery-attribute-mapping for event grid topic subscription

### ISSUE THREAD

**Issue by sourabhnighot1991** [Azure/azure-cli#19602]
## Describe the bug

**Command Name**
`az eventgrid event-subscription update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 191, in handler
    instance = cached_get(self.cmd, getter, **getterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in cached_get
    return _get_operation()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 404, in _get_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/eventgrid/custom.py", line 1126, in event_subscription_getter
    return client.get(source_resource_id, event_subscription_name)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/eventgrid/operations/_event_subscriptions_operations.py", line 88, in get
    'scope': self._serialize.url("scope", scope, 'str', skip_quote=True),
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventgrid event-subscription update --name {} --delivery-attribute-mapping {} {} {}`

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team
