### ISSUE TITLE
When running az aks get-credentials --resource-group resourcegroupname --name name results in an error [WinError 123] The filename, directory name, or volume label syntax is incorrect: ';C:'

### ISSUE THREAD

**Issue by michaelfouad** [Azure/azure-cli#19612]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 123] The filename, directory name, or volume label syntax is incorrect: ';C:'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2681, in aks_get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 4515, in _print_or_merge_credentials
  File "os.py", line 213, in makedirs
  File "os.py", line 213, in makedirs
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ';C:'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
interactive 0.4.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@michaelfouad Apologies for the late reply. You can check under the user profile for file ~/.kube/config for the existing kubeconfig file. You can try to rename or delete the file and then run the command az aks get-credentials and check if that helps. 

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).
 This issue is open for quite sometime now. Please let us know if you still need assistance on this. Awaiting your reply.

**Comment by michaelfouad** [comment]
Thank you for your response. 
I am unblocked now, it was kubeconfig file that was recreated.
