### ISSUE TITLE
"az login" error: Permission denied: '/Users/xxx/.azure/azureProfile.json'

### ISSUE THREAD

**Issue by mawada14** [Azure/azure-cli#19657]
I am getting an error after having downloaded azure cli and have tried to write "az login" and got an error message and cannot troubleshoot it - im new to azure and scripting / coding in general 

Does anyone recommend training prior to using azure powershell / cmdlets / cli as I dont have terminal experience nor do I have any experience with how a computer work - [ basically dont know how to configure and customize things the way i do] give me suggestions please 

the error message im receiving -

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 912, in get_default_cli
    return AzCli(cli_name='az',
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 80, in __init__
    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/_session.py", line 61, in load
    self.save()
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/_session.py", line 65, in save
    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/Users/mawada14/.azure/azureProfile.json'

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error seems to be the same as https://github.com/Azure/azure-cli/issues/15638.

> Does anyone recommend training prior to using azure powershell / cmdlets / cli as I dont have terminal experience nor do I have any experience with how a computer work - [ basically dont know how to configure and customize things the way i do] give me suggestions please

You may check the official document https://docs.microsoft.com/en-us/cli/azure/ which shows you how to use Azure CLI step-by-step.

**Comment by mawada14** [comment]
I checked out #15638 -and ran the commands requested and the returned output was **[stat: No such file or directory]**

Any ideas?

**Comment by jiasli** [comment]
In your case, you need to check the permission of `azureProfile.json`, instead of `commandIndex.json` (from #15638):

```
stat ~/.azure/azureProfile.json
```

Then delete the `.azure` folder:

```
sudo rm -r ~/.azure
```

Then you do _not_ need to prefix `az` with `sudo` anymore.

**Comment by jiasli** [comment]
Have yo deleted `.azure`? If so, you may run `az login` now.

**Comment by mawada14** [comment]
Hi @jiasli  it worked!!! Thank you, just wondering how you were able to find the solution and what do you need to be trained on figure these type of terminal errors?

**Comment by jiasli** [comment]
I am glad to know it works. 

>Just wondering how you were able to find the solution and what do you need to be trained on figure these type of terminal errors?

This would require basic Linux knowledge, you may search the internet for "learn linux" or "linux tutorial" and there are many resources you may refer to.
