### ISSUE TITLE
az container logs -g <resource group name> -n <aci name> fail in az version 2.28

### ISSUE THREAD

**Issue by sriarush** [Azure/azure-cli#19650]
az container logs -g fct-ct-prod-mnz20-full-220 -n nsxt-tests-containers 
Traceback (most recent call last): 
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke 
    cmd_result = self.invocation.execute(args) 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute 
    raise ex 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially 
    results.append(self._run_job(expanded_arg, cmd_copy)) 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job 
    result = cmd_copy(params) 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__ 
    return self.handler(*args, **kwargs) 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler 
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None 
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container 
    return _container_instance_client_factory(cli_ctx).container 
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container' 
To open an issue, please run: 'az feedback' 
***** Test finished executing *****

**Comment by yonzhan** [comment]
route to service team
