### ISSUE TITLE
Can't use bicep; "permission denied"

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#19670]
### **This is autogenerated. Please review and update as needed.**

Getting an error executing az bicep commands and az deployment when using bicep files. Appears correct permissions have not been applied to the bicep executable(s).

**Command Name**
`az bicep version`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/root/.azure/bin/bicep'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 3566, in show_bicep_cli_version
    print(run_bicep_command(["--version"], auto_install=False))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/_bicep.py", line 69, in run_bicep_command
    installed_version = _get_bicep_installed_version(installation_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/_bicep.py", line 181, in _get_bicep_installed_version
    installed_version_output = _run_command(bicep_executable_path, ["--version"])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/_bicep.py", line 215, in _run_command
    process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/az/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/az/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/az/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/.azure/bin/bicep'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep version`

## Expected Behavior

These commands should execute without issues. Bicep should be installed/added to system **and have necessary permissions for execution applied** without user intervention.

## Environment Summary
```
Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-debian-10.10, Debian GNU/Linux 10 (buster)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

```

**Comment by brandonh-msft** [comment]
Additionally, the following happens if I attempt to fix the problem on my own:
```shell
root@5f528e7a8067:/workspaces/durable-functions-producer-consumer# sudo chmod +x /root/.azure/bin/bicep
root@5f528e7a8067:/workspaces/durable-functions-producer-consumer# az bicep version
The command failed with an unexpected error. Here is the traceback:
[Errno 8] Exec format error: '/root/.azure/bin/bicep'
```

**Comment by brandonh-msft** [comment]
must've  been something in the dev container environment. I blew the whole thing away, re-built, and things are working now 🤷🏻‍♂️
