### ISSUE TITLE
AttributeError: module 'json' has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by JoCo356** [Azure/azure-cli#19691]
**Describe the bug**
I can't run "az login" , "az versions" or "az upgrade", it shows up an AttributeError.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 14, in <module>
    import azure.cli.core.telemetry as telemetry
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 13, in <module>
    from knack.cli import CLI
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/knack/__init__.py", line 8, in <module>
    from knack.cli import CLI
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 12, in <module>
    from .output import OutputProducer
  File "/usr/local/Cellar/azure-cli/2.28.0/libexec/lib/python3.9/site-packages/knack/output.py", line 25, in <module>
    class _ComplexEncoder(json.JSONEncoder):
AttributeError: module 'json' has no attribute 'JSONEncoder'
```

**To Reproduce**
Run "az login" or "az versions" on the terminal.

**Expected behavior**
I expected that when I runned az login an isolated window could open on the internet logging in.

**Environment summary**
I am using a macOS Catalina version 10.15.7 and I use .zshrc. I am trying to run "az login" in a pyenv which uses python 3.7.5.

**Additional context**
When I run "ls -l /System/Library/Frameworks/Python.framework/Versions" it gives me:
```
total 0
lrwxr-xr-x   1 root  wheel    3 Jul 20  2020 2.3 -> 2.7
lrwxr-xr-x   1 root  wheel    3 Jul 20  2020 2.5 -> 2.7
lrwxr-xr-x   1 root  wheel    3 Jul 20  2020 2.6 -> 2.7
drwxr-xr-x  11 root  wheel  352 Sep 12 16:18 2.7
lrwxr-xr-x   1 root  wheel    3 Jul 20  2020 Current -> 2.7
```

I already run "brew update && brew install python3 && brew upgrade python3" and "brew link --overwrite python3" and relinked again. And I am aware of this webpage https://docs.microsoft.com/pt-pt/cli/azure/install-azure-cli-macos?view=azure-cli-latest. I also run "brew upgrade" because it asked to do that after running "brew update", I had nghttp2 and openjdk outdated. and "brew reinstall azure-cli". When I run "brew update && brew install python3 && brew upgrade python3" it says: 
```
Already up-to-date.
Warning: python@3.9 3.9.7 is already installed and up-to-date.
To reinstall 3.9.7, run:
  brew reinstall python@3.9
Warning: python3 3.9.7 already installed
```
And when "brew link --overwrite python3":
```
Warning: Already linked: /usr/local/Cellar/python@3.9/3.9.7
To relink, run:
  brew unlink python@3.9 && brew link python@3.9
```

Tried the relink but didn't worked.

Also uninstalled with command "brew uninstall azure-cli" and re-installed with "brew update && brew install azure-cli", at my pyenv. Didn't work.

Hope you can help me.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Azure CLI uses the python installed by `brew`, instead of the one installed by `pyenv`.

Could you check the version of `/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python` (https://github.com/Azure/azure-cli/issues/19027#issuecomment-900773977):

```sh
# You may need to replace version 2.28.0 with the one you are using in the future
ls -l /usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python
/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -V
```

Also, can `JSONEncoder` be imported?

```
/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -c "from json import JSONEncoder"
```

**Comment by JoCo356** [comment]
Thanks for helping, @jiasli and @yonzhan.

I believe the version is 3.9. however the version in my pyenv is 3.7.5 could this be a problem?
```
ls -l /usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python
lrwxr-xr-x  1 joco  staff  84 Sep  3 06:01 /usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -> ../../../../../opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```

```
/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -V
Python 3.9.7
```

```
 /usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -c "from json import JSONEncoder"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'JSONEncoder' from 'json' (unknown location)
```
I don't understand 

> You may need to replace version 2.28.0 with the one you are using in the future

Should I reinstall python 3.9.7. at  `/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python` directory ? But it was installed by azure-cli, right? When I did:
`brew update && brew install azure-cli`

**Comment by jiasli** [comment]
> You may need to replace version 2.28.0 with the one you are using in the future

The current Azure CLI is 2.28.0. I am only saying in the future you may need to replace the version number with 2.29.0, 2.30.0, etc. 😄


```
`/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python -c "from json import JSONEncoder"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'JSONEncoder' from 'json' (unknown location)
```

`/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python` points to `/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9`. As you cannot import JSON, that means the Python installation is broken. 

What is the result of 

```
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c "from json import JSONEncoder"
```

Could you reinstall Python and see if `JSONEncoder` can be imported?

```
brew reinstall python@3.9
```

**Comment by JoCo356** [comment]
Okay one information, the python3.9. comes from my operating system.

**Comment by JoCo356** [comment]
But python3.9. was not installed with homebrew. 

I just tried this `brew update && brew install python3 && brew upgrade python3` out because it was on the mac installation page of azure client (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos). Maybe I shouldn't, but I was trying out everything without reading that it was if `Unable to find Python`, even though that was not the problem. I have python, but it is broken.

**Comment by JoCo356** [comment]
Hello, first I had this:

```
joco@Jo-MBP ~ % python3
Python 3.9.7 (default, Sep  3 2021, 12:45:31)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from json import JSONEncoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JSONEncoder' from 'json' (unknown location)
>>> exit()
```
Than I did >> sudo rm -rf /usr/local/bin/python3
I run brew doctor to find sylinks than needed to delete. None was found.
I wanted to reinstall with homebrew:
```
joco@Jo-MBP ~ % brew install python3
Warning: python@3.9 3.9.7 is already installed and up-to-date.
To reinstall 3.9.7, run:
  brew reinstall python@3.9
```

Now I have:
```
joco@Jo-MBP ~ % python3
Python 3.8.2 (default, Dec 21 2020, 15:06:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from json import JSONEncoder
>>> exit()
```
And
```
joanacosta@Joanas-MBP ~ % azure login
zsh: command not found: azure
```

Hope you can help me, I am not an expert on this, but I want to be able to solve my problem. If you still think it is better to reach out homebrew, okay.
