### ISSUE TITLE
az upgrade failed with machinelearningservices extension

### ISSUE THREAD

**Issue by seanyao1** [Azure/azure-cli#19720]
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.28.1
Upgrading extensions
Checking update for machinelearningservices
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\Miniconda3\lib\site-packages\azure\cli\command_modules\extension\custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\extension\operations.py", line 391, in update_extension
    cur_version = ext.get_version()
  File "C:\Miniconda3\lib\site-packages\azure\cli\core\extension\__init__.py", line 139, in get_version
    return self.metadata.get('version')
AttributeError: 'NoneType' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Windows-10-10.0.19042-SP0, 
Python 3.9.5
Installer: PIP

azure-cli 2.28.1

Extensions:
machinelearningservices Unknown

```

**Comment by yonzhan** [comment]
@jiasli for awareness
