### ISSUE TITLE
AZ cli bug

### ISSUE THREAD

**Issue by Ak47u1999** [Azure/azure-cli#19747]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3867, in webapp_up
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3900, in _update_app_settings_for_windows_if_needed
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {} --os-type {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
Not sure what the error is here based on the generated bug. @Ak47u1999 can you please provide more details?

**Comment by StrawnSC** [comment]
I encountered this bug when running `az webapp up` on a windows node app that already exists

**Comment by navba-MSFT** [comment]
@StrawnSC Thanks for reaching out to us. This issue seems to be addressed Azure/azure-cli#14335. Could you please let us know if you are still facing this issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI ? If it does, Could you please share the `--debug` output along with the AzCLI version ? Awaiting your reply.

**Comment by StrawnSC** [comment]
Also planning on taking care of this issue myself @navba-MSFT btw. I reopened the issue for tracking / visibility

**Comment by StrawnSC** [comment]
This is downstream of this behavior: https://github.com/Azure/azure-cli/issues/21548 where the API erroneously returns `siteConfig.appSettings` as null for some webapps
