### ISSUE TITLE
chardet missing

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#19758]
**Describe the bug**
`chardet` is missing after freshly installing az-cli

**To Reproduce**
```bash
> python -m venv ./venv
> source venv/bin/activate
# ensure chardet is not installed
> pip freeze --all
> pip install azure-cli
...
> az appconfig kv import --help
The command failed with an unexpected error. Here is the traceback:
No module named 'chardet'
Traceback (most recent call last):
  ...
  File "/c/src/venv/lib/python3.8/site-packages/azure/cli/command_modules/appconfig/keyvalue.py", line 30, in <module>
    from ._kv_helpers import (__compare_kvs_for_restore, __read_kv_from_file, __read_features_from_file,
  File "/c/src/venv/lib/python3.8/site-packages/azure/cli/command_modules/appconfig/_kv_helpers.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
To open an issue, please run: 'az feedback'
```

**Expected behavior**
All az-cli dependencies are installed and `az appconfig kv import --help` can be executed successfully.

**Additional context**

This is related to #11467

**Comment by yonzhan** [comment]
route to service team

**Comment by shenmuxiaosen** [comment]
@stan-sz  chardet is a third party tool that CLI depends on. It should be installed during CLI installation. Can you help to verify the ```pip install azure-cli``` is a full success? Would you mind to re-run ```pip freeze``` after CLI installation to verify the cli and chardet version?

**Comment by stan-sz** [comment]
`chardet` is missing in the `pip freeze` after CLI installation.

**Comment by shenmuxiaosen** [comment]
@yonzhan Can you help to route this issue to CLI core folks? chardet is specified as requirement [here](https://github.com/Azure/azure-cli/blob/82b725b09d8448ca800217960ef00bf9e3ce0dc3/src/azure-cli/requirements.py3.Linux.txt#L99).

**Comment by stan-sz** [comment]
Should it be added to setup.py? https://github.com/Azure/azure-cli/blob/82b725b09d8448ca800217960ef00bf9e3ce0dc3/src/azure-cli/setup.py#L52

**Comment by yonzhan** [comment]
Add @jiasli @zhoxing-ms for awareness
