### ISSUE TITLE
az upgrade returns python errors

### ISSUE THREAD

**Issue by eja-git** [Azure/azure-cli#19753]
## Describe the bug
This is a new machine, so installing everything.  After some python installations, I now get "The system cannot find the path specified." whenever I run an az command.  (or start code)  I tried to check 'az upgrade --all' and got the following error.

**Command Name**
`az upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Command '['az', 'version', '-o', 'json']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 152, in upgrade_version
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['az', 'version', '-o', 'json']' returned non-zero exit status 1.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade --all`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by eja-git** [comment]
Some additional information.  I installed Python via the Windows Store, which I've never done before, but things seemed ok for a few days with Python and my command line.  I installed Anaconda, but decided I didn't want that, so un-installed Anaconda, then started to see issues with my command line.  I think I'll uninstall Python and install via exe.

**Comment by eja-git** [comment]
I uninstalled the Windows Store version 3.9.7.  Still had the issue with az upgrade.  It appears there is a python version 3.8.9 in C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2, but it appears to be a 32-bit version, while I've been installing the 64-bit.  Maybe this caused some conflict?
![az-version-python](https://user-images.githubusercontent.com/3740288/135555703-84c7baaf-f49c-42ae-9aee-96c42cc36277.png)

**Comment by eja-git** [comment]
This was the fix: https://github.com/Azure/azure-cli/issues/19202#issuecomment-898271305
