### ISSUE TITLE
az storage blob copy start-batch

### ISSUE THREAD

**Issue by RustamSultansoy** [Azure/azure-cli#19757]
## Describe the bug

**Command Name**
`az storage blob copy start-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Incorrect padding
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 352, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 262, in storage_blob_copy_batch
    source_sas = create_short_lived_container_sas(cmd, source_client.account_name, source_client.account_key,
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/storage/util.py", line 145, in create_short_lived_container_sas
    return sas.generate_container(container, permission=t_blob_permissions(read=True), expiry=expiry, protocol='https')
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/sharedaccesssignature.py", line 192, in generate_container
    sas.add_resource_signature(self.account_name, self.account_key, container_name,
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/blob/sharedaccesssignature.py", line 267, in add_resource_signature
    _sign_string(account_key if user_delegation_key is None else user_delegation_key.value,
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/common/_common_conversion.py", line 91, in _sign_string
    key = _decode_base64_to_bytes(key)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/multiapi/storage/v2018_11_09/common/_common_conversion.py", line 81, in _decode_base64_to_bytes
    return base64.b64decode(data)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob copy start-batch --destination-container {} --account-name {} --account-key {} --source-account-name {} --source-account-key {} --source-container {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.25.0 *

```

**Comment by yonzhan** [comment]
Storage
