### ISSUE TITLE
Got a really weird error while trying to update a container image

### ISSUE THREAD

**Issue by nemkicsiaron** [Azure/azure-cli#19768]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 114, in create_container
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 390, in _create_update_from_file
AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create -g {} -n {} --file {} --image {}`

## Environment Summary
```
Windows-10-10.0.22468-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by PramodValavala-MSFT** [comment]
@nemkicsiaron This has since been fixed. Closing.
