### ISSUE TITLE
az sql server list giving CLIInternalError on arm64

### ISSUE THREAD

**Issue by kierenj** [Azure/azure-cli#19772]
**Describe the bug**
`az sql server list` results in:

````
ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: cannot import name 'ImportExistingDatabaseDefinition' from 'azure.mgmt.sql.models' (/usr/lib/python3/dist-packages/azure/mgmt/sql/models/__init__.py)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke   
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 558, in execute 
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 481, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries 
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/sql/__init__.py", line 27, in load_arguments
    from azure.cli.command_modules.sql._params import load_arguments   
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/sql/_params.py", line 11, in <module>   
    from azure.mgmt.sql.models import (
ImportError: cannot import name 'ImportExistingDatabaseDefinition' from 'azure.mgmt.sql.models' (/usr/lib/python3/dist-packages/azure/mgmt/sql/models/__init__.py)
````

**To Reproduce**
ARM64 arch. Dockerfile:

````
FROM debian:bullseye

RUN apt-get update
RUN apt-get install --yes python3 python3-pip
RUN apt install --yes azure-cli
````

I then run a script which does:

1. `az login` with username, password, tenant for a service principal - works
2. `az account set --subscription "my sub here"` - works
3. `az sql server list` - fails as above

**Expected behavior**
List of servers returned, as works with `mcr.microsoft.com/azure-cli:latest` image (on amd64 it works... arm64 build is broken)

**Environment summary**
- arm64 arch
- kubernetes
- `debian:bullseye`
- latest `azure-cli` installed via `apt` as above

**Comment by yonzhan** [comment]
route to service team

**Comment by kierenj** [comment]
This is specific to 'bullseye' debian, despite that being the latest stable release.

This seems to work fine for 'buster':

````
FROM debian:buster

RUN apt-get update
RUN apt-get install --yes ca-certificates curl apt-transport-https lsb-release gnupg
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
RUN echo "deb [arch=$(dpkg --print-architecture)] https://packages.microsoft.com/repos/azure-cli/ buster main" | tee /etc/apt/sources.list.d/azure-cli.list
RUN apt-get update
RUN apt-get install --yes azure-cli
````

**Comment by kierenj** [comment]
I spoke too soon. On arm64:

````
/usr/bin/az: line 3: /usr/bin/../../opt/az/bin/python3: cannot execute binary file: Exec format error
````

**Comment by kierenj** [comment]
This worked:

https://github.com/Azure/azure-cli/issues/7368#issuecomment-921578936
