### ISSUE TITLE
failure in Synapse create linked service azure cli command 

### ISSUE THREAD

**Issue by sarajag** [Azure/azure-cli#19775]
## Describe the bug
When using the azure cli cmd  : az synapse linked-service create to create a new linked service in synapse workspace, it fails with a type error. I have validated and tested and deployed with the same JSON in Azure and works as expected.
But fails in azure cli. 

**Command Name**
`az synapse linked-service create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/operations/artifacts.py", line 32, in create_or_update_linked_service
TypeError: string indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse linked-service create --workspace-name {} --name {} --file {}`

## Expected Behavior
Must create a linked service in synapse successfully.
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by idear1203** [comment]
@zesluo @kevinzz6 to take a look.

cc: @wonner

**Comment by kevinzz6** [comment]
@sarajag Hi, could you please upload your definition file?
