### ISSUE TITLE
az functionapp function show call failure

### ISSUE THREAD

**Issue by Auburg** [Azure/azure-cli#19770]
## Describe the bug

**Command Name**
`az functionapp function show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize content-type: text/html
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 4423, in show_function
    result = client.web_apps.get_function(resource_group_name, name, function_name)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 5171, in get_function
    error = self._deserialize(_models.DefaultErrorResponse, response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1541, in _unpack_content
    raw_data.headers
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/html

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp function show -g {} -n {} --function-name {} --query {}`

## Environment Summary
```
Linux-5.4.0-1059-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
I am unable to repro the issue. Please retry and share your debug logs to analyze further if you still face the issue.
![image](https://user-images.githubusercontent.com/60102891/136024051-eb47f05c-9354-478a-8095-408cdf1a6510.png)
