### ISSUE TITLE
az container delete failing

### ISSUE THREAD

**Issue by neilcaldwell** [Azure/azure-cli#19785]
## Describe the bug
az container delete showing an error and not completing

**Command Name**
`az container delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerGroupsOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 66, in delete_container
    return client.delete(resource_group_name, name)
AttributeError: 'ContainerGroupsOperations' object has no attribute 'delete'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

create a container, as per microsoft learn steps at https://docs.microsoft.com/en-gb/learn/modules/secure-apps-azure-container-instances-sidecar/2-deploy-into-virtual-network 
- `az container delete -n {} -g {} -y`

## Expected Behavior
container instance deleted

## Environment Summary
```
Linux-5.4.0-1059-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by berndverst** [comment]
Downgrade to Azure CLI 2.27.2 for the latest CLI where this still works.

Here is how I did it:
https://github.com/Azure/azure-cli/issues/19789#issuecomment-936997354

**Comment by berndverst** [comment]
@macolso or just run the 2.27.2 CLI Docker container:

```bash
docker run --rm -it mcr.microsoft.com/azure-cli:2.27.2 /bin/bash
```
