### ISSUE TITLE
Enabling virtual node on an AKS cluster using System Managed Identity

### ISSUE THREAD

**Issue by istarbuxs** [Azure/azure-cli#19794]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2569, in aks_enable_addons
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1917, in _add_virtual_node_role_assignment
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --resource-group {} --name {} --addons {} --subnet-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@istarbuxs Apologies for the late reply. Could you please let me know if you are still facing this issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) of AzCLI ? Awaiting your reply.
