### ISSUE TITLE
No module named 'decorator'

### ISSUE THREAD

**Issue by Riyasharma-in** [Azure/azure-cli#19797]
The command failed with an unexpected error. Here is the traceback:

No module named 'decorator'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fabric/connection.py", line 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 528, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 496, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/appservice/custom.py", line 25, in <module>
    from fabric import Connection
  File "/usr/lib/python3/dist-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/lib/python3/dist-packages/fabric/connection.py", line 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment]
route to service team
