### ISSUE TITLE
access tokens not being properly retrieved by azure cli when spinning up ray cluster

### ISSUE THREAD

**Issue by wesmadrigal** [Azure/azure-cli#19832]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When calling ray up with Azure yaml config the azure python library has issues generating tokens.  This is, of course, after running az login on the same terminal (so credentials are available on the machine).

**To Reproduce**

1. fresh install azure cli
2. install ray https://docs.ray.io/en/latest/installation.html
3. configure a ray cluster config.yaml file with Azure specs (https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/azure)
4. run "ray up -y your_config_file.yaml"
5. exception thrown
`Checking Azure environment settings
2021-10-11 01:23:22,098	INFO config.py:43 -- Using subscription id: 6dbdfff5-53f0-4b20-aef0-96eb549200ac
2021-10-11 01:23:22,099	INFO config.py:57 -- Creating/Updating Resource Group: derwen
Traceback (most recent call last):
  File "/home/azureuser/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1970, in main
    return cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1260, in submit
    rsync(
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 1085, in rsync
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 322, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 309, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/config.py", line 22, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/home/azureuser/.local/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/config.py", line 58, in _configure_resource_group
    resource_client.resource_groups.create_or_update(
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 154, in create_or_update
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/common/credentials.py", line 74, in get_token
    _, token, fulltoken = credentials._token_retriever()  # pylint:disable=protected-access
TypeError: _retrieve_token() missing 1 required positional argument: 'token_resource'`

**Expected behavior**
Expected behavior is successful ray cluster launch on Azure

**Environment summary**
azure cli
ray
az login

**Comment by jiasli** [comment]
Please see the explanation and solution from https://github.com/Azure/azure-cli/issues/19528#issuecomment-918764998.

In summary, `_retrieve_token` is an internal function so we don't guarantee its back-ward compatibility. Also `azure-common` has been deprecated. Please work with Ray to use the latest Azure SDKs which uses Azure Identity in https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/azure/defaults.yaml.
