### ISSUE TITLE
problem with jmes query in az storage blob list - error when searching for names containing a string

### ISSUE THREAD

**Issue by mpowrie** [Azure/azure-cli#19871]
## Describe the bug

**Command Name**
```
az storage blob list --container-name $containername --account-name $accountname --query '[?contains(name, "5-9998602") == `true`]'
```

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 669, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_FILTER_RESULT, event_data=event_data)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/query.py", line 46, in filter_output
    kwargs['event_data']['result'], Options(collections.OrderedDict))
  File "/opt/az/lib/python3.6/site-packages/jmespath/parser.py", line 509, in search
    result = interpreter.visit(self.parsed, value)
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 94, in visit
    return method(node, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 180, in visit_filter_projection
    if self._is_true(self.visit(comparator_node, element)):
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 94, in visit
    return method(node, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 145, in visit_comparator
    self.visit(node['children'][0], value),
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 94, in visit
    return method(node, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/jmespath/visitor.py", line 171, in visit_function_expression
    return self._functions.call_function(node['value'], resolved_args)
  File "/opt/az/lib/python3.6/site-packages/jmespath/functions.py", line 81, in call_function
    return function(self, *resolved_args)
  File "/opt/az/lib/python3.6/site-packages/jmespath/functions.py", line 215, in _func_contains
    return search in subject
TypeError: 'in <string>' requires string as left operand, not NoneType

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob list --container-name {} --account-name {} --query {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0
azure-cli-ml 1.33.0

Extensions:
account 0.2.1
ad 0.1.0
azure-cli-ml 1.33.0
azure-devops 0.20.0
dataprotection 0.2.0

```

**Comment by mpowrie** [comment]
The corrected syntax was:

`az storage blob list --container-name $containername --account-name $accountname --query "[?contains(@.name, '5-10048891')==\`true\`].name"
`
