### ISSUE TITLE
WebApp:AttributeError while running `az staticwebapp disconnect`

### ISSUE THREAD

**Issue by marek-ciazynski** [Azure/azure-cli#19891]
## Describe the bug

**Command Name**
`az staticwebapp disconnect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'StaticSitesOperations' object has no attribute 'detach_static_site'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/static_sites.py", line 38, in disconnect_staticsite
    return sdk_no_wait(no_wait, client.detach_static_site,
AttributeError: 'StaticSitesOperations' object has no attribute 'detach_static_site'

```

## To Reproduce:
- Create a Static Web App in Free tier
- `az staticwebapp disconnect --subscription {} -n {}`

## Expected Behavior
App should be disconnected from source control

## Environment Summary
```
Linux-5.11.0-37-generic-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0

```

**Comment by RossMurr4y** [comment]
Receiving this error suddenly too - didn't receive it yesterday, today on 3x StaticWebApps in individual release pipelines.

I was performing a disconnect on the SWA's prior to deployment in AzDO Pipelines, which was previously required as without it the Pipelines would fail, reporting that I was attempting to update some Read Only attributes. If I remove the disconnect from the Pipeline they now succeed, but its not clear to me whether it can be safely removed from future releases or if this is a temporary change.

**Comment by kjfranklin** [comment]
Ah yes, thanks, but it appears azure devops machines don't have it, even when forcing an az upgrade it errors with azure-cli is already the newest version (2.29.0-1~focal).

**Comment by sisirap** [comment]
@Alec13355 2.29.1 CLI version got the fixes. We don't control devops pipeline, so please ensure that devops  is using latest CLI build.

**Comment by StrawnSC** [comment]
This issue should be resolved now. Please reopen if you're still running into this bug
