### ISSUE TITLE
Can't deploy function app: AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by yvaillancourt** [Azure/azure-cli#19903]
## Describe the bug
Since I upgrade to az cli 2.29, I can't deploy my function app package.
**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 405, in enable_zip_deploy_functionapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 417, in enable_zip_deploy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --resource-group MyRG --name func-MyFunc --src C:\Path\webDeploy.zip`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0

Extensions:
application-insights 0.1.14
azure-devops 0.20.0
logic 0.1.4

```

**Comment by jiasli** [comment]
This issue has been fixed by https://github.com/Azure/azure-cli/pull/19897 and released in Azure CLI 2.29.1. Please update to the latest version following the official document https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
