### ISSUE TITLE
Cannot login to azure CLI 

### ISSUE THREAD

**Issue by pratiksanglikar** [Azure/azure-cli#19938]
## Describe the bug
Unable to login to Azure CLI.
using `az login` command fails with the errors below and using `az login --use-device-code` results in the following error - 
`Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new`

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
request() got an unexpected keyword argument 'error_template'
Traceback (most recent call last):
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli\azure\cli\command_modules\profile\custom.py", line 145, in login
    subscriptions = profile.login(
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "c:\users\username\source\workspace\azure-cli\src\azure-cli-core\azure\cli\core\auth\identity.py", line 120, in login_with_auth_code
    result = self.msal_app.acquire_token_interactive(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\application.py", line 1090, in acquire_token_interactive
    return _clean_up(self.client.obtain_token_by_browser(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oidc.py", line 243, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oauth2.py", line 648, in obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oidc.py", line 189, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oauth2.py", line 548, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oauth2.py", line 702, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oidc.py", line 102, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oauth2.py", line 742, in _obtain_token
    resp = super(Client, self)._obtain_token(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\msal\oauth2cli\oauth2.py", line 235, in _obtain_token
    resp = (post or self._http_client.post)(
  File "C:\Users\username\source\Workspace\azure-cli\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
TypeError: request() got an unexpected keyword argument 'error_template'

```

## To Reproduce:
Login to Azure CLI using `az login` command.

- _Put any pre-requisite steps here..._
- `az login`

## Expected Behavior
`az login` should be successful.

## Environment Summary
```
Windows-10-10.0.22478-SP0
Python 3.9.7
Installer: PIP

azure-cli 2.29.0

Extensions:
dev-spaces 1.0.4

```

**Comment by jiasli** [comment]
This should only happen on the `dev` branch. 

It is triggered here:

https://github.com/Azure/azure-cli/blob/6442bedce93ea849dc02700fde4befef6313219a/src/azure-cli-core/azure/cli/core/auth/identity.py#L122

The corresponding change on MSAL is https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/349.

Please run `azdev setup` to re-setup the CLI dev environment which will bump MSAL and see if the issue gone.

**Comment by satyaswarup99** [comment]
i am getting no subscription error but i have azure subscription

**Comment by jiasli** [comment]
@satyaswarup99, it is because you do have no subscription. Please make sure you have a valid [RBAC role assignment](https://docs.microsoft.com/en-us/azure/role-based-access-control/) to any subscription. 

If you want to directly operate on the tenant, use 

```
az login --allow-no-subscriptions
```
