### ISSUE TITLE
Can't invoke `az interactive` without raising a Module Not Found Error

### ISSUE THREAD

**Issue by duysqubix** [Azure/azure-cli#19931]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/home/dhuys/py/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/dhuys/py/lib/python3.7/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/dhuys/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/dhuys/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-4.19.0-17-cloud-amd64-x86_64-with-debian-10.11, Debian GNU/Linux 10 (buster)
Python 3.7.3
Installer: PIP

azure-cli 2.29.0

Extensions:
azure-devops 0.20.0
interactive 0.4.5

```

**Comment by RakeshMohanMSFT** [comment]
This is resolved https://github.com/Azure/azure-cli/issues/24213
