### ISSUE TITLE
facing this error while installing aks cli

### ISSUE THREAD

**Issue by harshbhardwaj-123** [Azure/azure-cli#19965]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTP Error 403: rate limit exceeded
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 355, in k8s_install_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 442, in k8s_install_kubelogin
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by timbodeit** [comment]
@phealy 

> I'm assuming you're using az aks install-cli in a script or CI/CD pipeline of some sort that's running it repeatedly from the same system

In our case, we're running this on bitbucket cloud ci pipelines. We are only running this occasionally, though you're probably right, that other companies have probably also been running the same command repeatedly on the same shared runner.

We're using the [Azure CLI](https://mcr.microsoft.com/en-us/product/azure-cli/about) Docker container. 

> Preferred: get kubectl/kubelogin into your pipeline using an alternate method that doesn't download them every time, incurring bandwidth and processing on the hosting servers for every run.

We'd love that as well. The reason why we need to call `az aks install-cli` in the first place, is that the `azure-cli` container doesn't come with it pre-installed.
Our much preferred option would be Microsoft publishing a second variant of the `azure-cli` container that already includes all of the related addons (like in this case the aks cli). Then we would just use that docker container as the base for our pipeline (and have that cached in Bitbucket, without the outbound network traffic for each pipeline run).
