### ISSUE TITLE
az acr build from quickstart not working

### ISSUE THREAD

**Issue by Konnor5092** [Azure/azure-cli#19968]
**Describe the bug**

I am unable to use `az acr build` with the Azure CLI. 

The 5 different methods I have tried when running the following command result in the following errors

```
az acr build --image sample/hello-world:v1 --registry aksmattcloudgurutest --debug --verbose --file Dockerfile .
```

1. Via Cloud Shell

```
2021/10/21 14:37:45 Using acb_vol_613a3111-c1ca-47d5-9fb2-a8dacc116698 as the home volume
2021/10/21 14:37:45 Setting up Docker configuration...
2021/10/21 14:37:45 Successfully set up Docker configuration
2021/10/21 14:37:45 Logging in to registry: aksmattcloudgurutest.azurecr.io
2021/10/21 14:37:46 Successfully logged into aksmattcloudgurutest.azurecr.io
2021/10/21 14:37:46 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2021/10/21 14:37:46 Scanning for dependencies...
2021/10/21 14:37:47 Output from dependency scanning: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
unable to understand line FROM
failed to run step ID: build: failed to scan dependencies: exit status 1

Run ID: db3 failed after 4s. Error: failed during run, err: exit status 1
```

2. Via Powershell

```
cli.azure.cli.command_modules.acr._archive_utils: Packing source code into tar to upload...
cli.azure.cli.command_modules.acr.build: Deleting the archived source code from 'C:\Users\matty\AppData\Local\Temp\build_archive_c843a91f830e422cbd902644cd771393.tar.gz'...
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 72, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 29, in upload_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 104, in _pack_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 209, in _archive_file_recursively
PermissionError: [WinError 5] Access is denied: '.\\AppData\\Local\\Application Data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 80, in acr_build
knack.util.CLIError: [WinError 5] Access is denied: '.\\AppData\\Local\\Application Data'

cli.azure.cli.core.azclierror: [WinError 5] Access is denied: '.\\AppData\\Local\\Application Data'
az_command_data_logger: [WinError 5] Access is denied: '.\\AppData\\Local\\Application Data'
```

3. Via Git Bash

```
←[93mcli.azure.cli.command_modules.acr._archive_utils: Packing source code into tar to upload...←[0m
←[36mcli.azure.cli.command_modules.acr.build: Deleting the archived source code from 'C:\Users\matty\AppData\Local\Temp\build_archive_52fe8aedfaec484283d68703ffcdef11.tar.gz'...←[0m
←[36mcli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:←[0m
←[36mcli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 72, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 29, in upload_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 104, in _pack_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 209, in _archive_file_recursively
PermissionError: [WinError 5] Access is denied: '.\\Com\\dmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 80, in acr_build
knack.util.CLIError: [WinError 5] Access is denied: '.\\Com\\dmp'
←[0m
←[91mcli.azure.cli.core.azclierror: [WinError 5] Access is denied: '.\\Com\\dmp'←[0m
←[91maz_command_data_logger: [WinError 5] Access is denied: '.\\Com\\dmp'←[0m
←[36mcli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03B631D8>]←[0m
←[32maz_command_data_logger: exit code: 1←[0m
←[32mcli.__main__: Command ran in 11.177 seconds (init: 0.210, invoke: 10.967)←[0m
←[32mtelemetry.save: Save telemetry record of length 2990 in cache←[0m
←[93mtelemetry.check: Negative: The C:\Users\matty\.azure\telemetry.txt was modified at 2021-10-21 15:52:56.963771, which in less than 600.000000 s←[0m
```

4. Via Command Prompt

```
cli.azure.cli.command_modules.acr._archive_utils: Packing source code into tar to upload...
cli.azure.cli.command_modules.acr.build: Deleting the archived source code from 'C:\Users\matty\AppData\Local\Temp\build_archive_c7919ab62a8249fb907c08538aadfa11.tar.gz'...
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 72, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 29, in upload_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 104, in _pack_source_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
  [Previous line repeated 5 more times]
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_archive_utils.py", line 209, in _archive_file_recursively
PermissionError: [WinError 5] Access is denied: '.\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 80, in acr_build
knack.util.CLIError: [WinError 5] Access is denied: '.\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5'

cli.azure.cli.core.azclierror: [WinError 5] Access is denied: '.\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5'
az_command_data_logger: [WinError 5] Access is denied: '.\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x041031D8>]
```

![cmdadmin](https://user-images.githubusercontent.com/18048889/138430701-7f5c460d-3d1e-4bee-b063-a7fe07b354c8.png)

5. Via `mcr.microsoft.com/azure-cli:latest` docker image

```
cli.azure.cli.command_modules.acr._archive_utils: Packing source code into tar to upload...
cli.azure.cli.command_modules.acr.build: Deleting the archived source code from '/tmp/build_archive_b164219537bf41c0ba2abece5b76c32b.tar.gz'...
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/build.py", line 72, in acr_build
    source_location = upload_source_code(
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 29, in upload_source_code
    _pack_source_code(source_location,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 104, in _pack_source_code
    _archive_file_recursively(tar,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
    _archive_file_recursively(tar, os.path.join(name, f), os.path.join(arcname, f),
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
    _archive_file_recursively(tar, os.path.join(name, f), os.path.join(arcname, f),
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 210, in _archive_file_recursively
    _archive_file_recursively(tar, os.path.join(name, f), os.path.join(arcname, f),
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/_archive_utils.py", line 203, in _archive_file_recursively
    tar.addfile(tarinfo, f)
  File "/usr/local/lib/python3.9/tarfile.py", line 2007, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/local/lib/python3.9/tarfile.py", line 255, in copyfileobj
    raise exception("unexpected end of data")
OSError: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/acr/build.py", line 80, in acr_build
    raise CLIError(err)
knack.util.CLIError: unexpected end of data

cli.azure.cli.core.azclierror: unexpected end of data
az_command_data_logger: unexpected end of data
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcb96159160>]
```

**To Reproduce**

- Create fresh windows 10 virtual machine in Azure
- Install Azure CLI
- Open powershell as an administrator
- Make sure you have created an Azure Container Registry
- Run the following below...

```
az login
echo FROM mcr.microsoft.com/hello-world > Dockerfile
az acr build --image sample/hello-world:v1 --registry aksmattcloudgurutest --debug --verbose --file Dockerfile .
```

**Expected behavior**

Image is built

**Environment summary**

Installed via `az upgrade` 

- Windows 10
- Azure CLI 2.29.1
- Powershell 7.1.3
- Python 3.10.0
- Azure Cloud Shell
- Git Bash

**Comment by kingstonrk** [comment]
I had the same issue and found it was caused by the `echo FROM nginx > Dockerfile`  resulting in the two words being split across separate lines in the Dockerfile file. Removing the line break allowed the script to run as expected.

**Comment by Wwwsylvia** [comment]
@Konnor5092 Does [this](https://github.com/Azure/azure-cli/issues/19968#issuecomment-1015607984) help?

**Comment by ellinge** [comment]
I had issues as well even after removing the line break. Changed the file encoding to UTF-8 for the created Dockerfile.

I ran the echo command from a Windows Terminal instead of bash (creating a UTF-16 LE BOM encoded file).

**Comment by navba-MSFT** [comment]
@Konnor5092 Apologies for the late reply. Could you please let me know if you had to chance to look at the suggestions in the above comment? Awaiting your reply.

**Comment by seppo498573908457** [comment]
FWIW, I run into this same issue today. I created the Dockerfile with the console command, which resulted in a two-line file encoded with UTF-16 LE BOM. I changed it to one-liner, which did not work, then I changed it to UTF-8 BOM, which resolved the issue.
The last time I had issues with string encoding it was in 2006, those were the good old times (but not for software deving).
