### ISSUE TITLE
az login --interactive fails on Azure ML Compute node

### ISSUE THREAD

**Issue by swilkTUDA** [Azure/azure-cli#19999]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/algorithms.py", line 256, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1217, in load_pem_private_key
    return self._load_key(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1448, in _load_key
    self._handle_key_loading_error()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1490, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 138, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 360, in find_subscriptions_in_vm_with_msi
    decode = jwt.decode(token, verify=False, algorithms=['RS256'])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/api_jws.py", line 233, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jwt/algorithms.py", line 258, in prepare_key
    key = load_pem_public_key(key)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 25, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1247, in load_pem_public_key
    self._handle_key_loading_error()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1490, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-glibc2.10
Python 3.8.1
Installer: PIP

azure-cli 2.24.0 *
azure-cli-ml 1.33.0

Extensions:
azure-cli-ml 1.33.0

```

**Comment by jiasli** [comment]
There is no `--interactive` argument for `az login`. I think you are talking about `--identity`.

The call stack shows Azure CLI lets `jwt` decode the JWT without verifying it (`verify=False`):

```
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 360, in find_subscriptions_in_vm_with_msi
    decode = jwt.decode(token, verify=False, algorithms=['RS256'])
```

but `jwt` library is still trying to verify it. Because the key is absent, the error occurs.

It is highly possible that Azure CLI's installation dependencies have been corrupted, as the `jwt` version is higher than what CLI requires at that moment (`PyJWT==1.7.1`).

This issue should not happen in later versions, since Azure CLI changed to `options={"verify_signature": False}` to be compatible with the latest `jwt` library (`PyJWT>=2.1.0`):

https://github.com/Azure/azure-cli/blob/e8efb791ea2f0ba5e4f172b26f75725fd8aa8079/src/azure-cli-core/azure/cli/core/_profile.py#L239

See https://github.com/Azure/azure-cli/pull/18506 for more information.
