### ISSUE TITLE
az iot hub update --set identity.type="SystemAssigned" is not working

### ISSUE THREAD

**Issue by eserkaraca** [Azure/azure-cli#20004]
## Describe the bug

**Command Name**
`az iot hub update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'$default'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 200, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/iot/custom.py", line 586, in update_iot_hub_custom
    instance.properties.storage_endpoints['$default'],
KeyError: '$default'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub update --name iothub-name --set identity.type="SystemAssigned"`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

I tried it with Python 3.7, 3.8 and 3.9 and it fails.
I tried with latest azure-cli version (2.29.1) and it fails.

```
## Additional Context
```
I were trying to enable iothub system assigned identity as below (Also tried escaped version);
az iot hub update --name iothub-name --set identity.type="SystemAssigned"

I tried also following workaround but fails again. See https://github.com/Azure/azure-cli/issues/11437 

```

**Comment by yonzhan** [comment]
route to service team
