### ISSUE TITLE
Az Restore from snapshot failure

### ISSUE THREAD

**Issue by ngurram** [Azure/azure-cli#20006]
## Describe the bug

**Command Name**
`az webapp config snapshot restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore_snapshot'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1889, in restore_snapshot
    return client.web_apps.restore_snapshot(resource_group_name, name, request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore_snapshot'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config snapshot restore -g {} -n {} --source-name {} --source-resource-group {} --time {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
Please update to the latest CLI and let us know if this is still an issue.

**Comment by seligj95** [comment]
Closing for now due to no response. Please reopen if this is still an issue.
