### ISSUE TITLE
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sozercan** [Azure/azure-cli#20003]
## Describe the bug

**Command Name**
`az keyvault set-policy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
libffi.so.7: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/custom.py", line 21, in <module>
    from azure.cli.command_modules.keyvault.security_domain.jwe import JWE
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/security_domain/jwe.py", line 13, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault set-policy`

## Environment Summary
```
Linux-5.4.0-1059-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.0 *

Extensions:
aks-preview 0.5.10
k8s-extension 0.1PP.12
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
keyvault
