### ISSUE TITLE
Bind SSL Certificates : ERROR: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by atkachuk-corgi** [Azure/azure-cli#20011]
## Describe the bug

**Command Name**
`az webapp config ssl bind`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2597, in bind_ssl_cert
    return _update_ssl_binding(cmd, resource_group_name, name, certificate_thumbprint,
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2590, in _update_ssl_binding
    return show_webapp(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config ssl bind --certificate-thumbprint {} --name {} --resource-group {} --ssl-type {} --subscription {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.1

Extensions:
azure-devops 0.18.0

```

**Comment by Menci** [comment]
Reproduced in 2.30.0:

```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2595, in bind_ssl_cert
    return _update_ssl_binding(cmd, resource_group_name, name, certificate_thumbprint,
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2588, in _update_ssl_binding
    return show_webapp(cmd, resource_group_name, name, slot)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 605, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 734, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'
```

**Comment by jiasli** [comment]
@Menci, are you Microsoft employee? You may reach me on Teams and we can work on this issue internally.

**Comment by atkachuk-corgi** [comment]
@jiasli Looks like the issue has been fixed

```
az version
{
  "azure-cli": "2.31.0",
  "azure-cli-core": "2.31.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0"
  }
}
```

az webapp config ssl bind --certificate-thumbprint XXXX --name XXXX --resource-group XXXX --ssl-type SNI | ConvertFrom-Json
```
appServicePlanId            : XXXX
availabilityState           : Normal
clientAffinityEnabled       : True
clientCertEnabled           : False
clientCertExclusionPaths    : 
clientCertMode              : Required
cloningInfo                 : 
...
```

but when I try this 
az functionapp config ssl bind --certificate-thumbprint XXXX --name BBBB --resource-group BBBB --ssl-type SNI | ConvertFrom-Json
```
ERROR: Unable to find webapp 'BBBB', in resource group 'BBBB'
Use 'az functionapp show' to show functionapps
```
I can check this resource 

az functionapp config appsettings list --name BBBB --resource-group BBBB

```
[
  {
    "name": "Name",
    "slotSetting": false,
    "value": "1111"
  },
  {
    "name": "Name2",
    "slotSetting": false,
    "value": "2222"
  },
....
```

**Comment by Nibushi** [comment]
I am also having the exact same issue when trying to run the az functionapp config ssl bind command

I am running version 2.32.0 of the cli.
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "application-insights": "0.1.14"
  }
}

**Comment by louisbergmann** [comment]
Same here. The issues seems to be in function _update_ssl_binding. In the end of that function it calls show_webapp(). This will probably fail for the function app.

Reproduce with:
`az functionapp config ssl bind --certificate-thumbprint xxx--id /subscriptions/yyy/resourceGroups/ggg/providers/Microsoft.Web/sites/zzz --ssl-type SNI
`
Output:
`Unable to find webapp 'zzz ', in resource group 'ggg'
Use 'az functionapp show' to show functionapps`

When running az functionapp show, the webapp is found.

**Comment by panchagnula** [comment]
@louisbergmann sorry for the lack of response on this. Yes, the issues with changes to show webapp being used for show function app is known - the fix is in progress & targeting March CLI release. Thanks!

**Comment by atkachuk-corgi** [comment]
Doesn't work on the latest version 
```
az version

{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0"
  }
}
```
```
az functionapp config ssl bind --certificate-thumbprint XXXXX --name AAAAA --resource-group BBBBB --ssl-type SNI --subscription CCCCC | ConvertFrom-Json

ERROR: Unable to find webapp AAAAA, in resource group BBBBB
Use 'az functionapp show' to show functionapps
```

**Comment by panchagnula** [comment]
yes known issue on our end - we are working on getting the fix out with the upcoming deployment.

**Comment by navba-MSFT** [comment]
@atkachuk-corgi Apologies for the late reply. Could you please try running the same command using the[ most recent version of the AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and check if you still face this issue? Awaiting your reply.

**Comment by atkachuk-corgi** [comment]
Hi folks
With the latest version of **az webapp config ssl bind** everything is working fine
Please close the ticket
P.S. Please don't update az webapp next couple of years
