### ISSUE TITLE
WebApp:az cli  `az webapp show` command  no longer works

### ISSUE THREAD

**Issue by wetjenk** [Azure/azure-cli#20049]
Command is:

`az webapp show --debug --resource-group ukazs-rg-d-dev-02 --name plutuswriter-functions-dev --query possibleOutboundIpAddresses  --output tsv`

## Describe the bug

**Command Name**
`az webapp show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp show --debug --resource-group {} --name {} --query {} --output {}`

## Environment Summary
```
Linux-5.4.0-1057-aws-x86_64-with-debian-buster-sid, Ubuntu 18.04.6 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.1

```

**Comment by b10-dslappendel** [comment]
Is this being worked on? While the linked issue may be fixed, this issue is still a problem for me.
It blocks https://github.com/actions/virtual-environments/issues/4327 for me on 2.30.0, meaning that I have to manually install 2.28.0 in the agent, causing an additional 7-10 minutes on Windows agents during deployment.

**Comment by wetjenk** [comment]
i've kept mine downgraded too. surprising this issue was not caught by the automated tests. do they need expanding?

**Comment by Kotasudhakarreddy** [comment]
@wetjenk might be you are trying to use get `functionapp` details using `webapp` command. from release 2.29.0 we have made a clear separation and usage of `functionapp show` and `webapp show` commands. please use accordingly.

**Comment by Kotasudhakarreddy** [comment]
Issue has been fixed and released. Please upgrade to the latest CLI version (2.31.0) and reopen the issue if you're still seeing this bug
