### ISSUE TITLE
Error when running az find blob

### ISSUE THREAD

**Issue by WKahWai** [Azure/azure-cli#20072]
## Describe the bug
Macbook Pro M1
MacOS 12.0.1
Running on Terminal
Installed the latest Azure CLI via Homebrew

**Command Name**
`az find`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/find/custom.py", line 49, in process_query
    if answer_list[0]['source'] == 'pruned':
TypeError: string indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
macOS-12.0.1-arm64-i386-64bit, Darwin 21.1.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.1

```

**Comment by navba-MSFT** [comment]
@WKahWai Apologies for the late reply. I was able to run the below command:

>C:\Users\navba>az find blob
Finding examples...
Here are the most common ways to use [blob]:
Restore blobs in two specified blob ranges. For examples, (container1/blob1, container2/blob2) and (container2/blob3..container2/blob4).
az storage blob restore --account-name mystorageaccount --resource-group MyResourceGroup --time-to-restore 2020-02-27T03:59:59Z --blob-range container1/blob1 container2/blob2 --blob-range container2/blob3 container2/blob4
Restore blobs in the specified blob range.
time=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
az storage blob restore --account-name mystorageaccount -g MyResourceGroup -t $time -r container0/blob1 container0/blob2
Sync blobs recursively to a storage blob container. (autogenerated)
az storage blob sync --account-name mystorageccount --container mycontainer --source "path/to/directory"
Please let us know how we are doing: https://aka.ms/azureclihats

I am using the recent version of AzCLI. Could you please use the most [recent version of CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)and test again ? Awaiting your reply.
