### ISSUE TITLE
az login failed with error  __init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by hepower** [Azure/azure-cli#20101]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/command_modules/profile/custom.py", line 161, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/_profile.py", line 209, in find_subscriptions_on_login
    tenant, self._ad_resource_uri, auth_resource=auth_resource)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/_profile.py", line 941, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/_profile.py", line 973, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/_profile.py", line 892, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.0.0-1018-azure-x86_64-with-Ubuntu-18.04-bionic, Ubuntu 18.04.6 LTS
Python 3.6.9
Installer: PIP

azure-cli 2.29.1

```

**Comment by hepower** [comment]
Thanks JiaShuo, the issue is fixed by re-install azure-cli in formal suggest way.
