### ISSUE TITLE
Restoring App Service from snapshot via CLI is not working

### ISSUE THREAD

**Issue by bartosz-piotrowski** [Azure/azure-cli#20110]
I'm using this docu command:
az webapp config snapshot restore -g TargetResourceGroup -n TargetApp --source-name SourceApp --source-resource-group OriginalResourceGroup --time 2018-12-11T23:34:16.8388367 --restore-content-only

I tried restore to:
- new webapp in the same RG
- in the other RG
- to the slot

I'm doing this as an owner of the subscirption.

## Describe the bug

**Command Name**
`az webapp config snapshot restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore_snapshot'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.29.1/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 1889, in restore_snapshot
    return client.web_apps.restore_snapshot(resource_group_name, name, request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore_snapshot'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config snapshot restore -g {} -n {} --source-name {} --source-resource-group {} --time {} --restore-content-only`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.1 *

Extensions:
webapp 0.4.0

```

**Comment by bartosz-piotrowski** [comment]
any updates ?

**Comment by nik0811** [comment]
any updates, anyone at least listening here or not. @bartosz-piotrowski  have you got your issue fixed?

**Comment by bartosz-piotrowski** [comment]
@nik0811  no I have no answer but I have figure out by myself why my restoring was not working, developers turned on tracing logs it and webapp storage was over 10GB nobody configured _backup.filter file and excluded logs/catalogs, you cannot restore snapshot if storage was over 10GB ;-( (it is by App service design)

**Comment by navba-MSFT** [comment]
@bartosz-piotrowski Apologies for the late reply. Thanks for sharing an update. If you need any further assistance on this issue, feel free to reopen this thread. We would be happy to help.
