### ISSUE TITLE
Python exception while configuring maximum throughput

### ISSUE THREAD

**Issue by daiyinong** [Azure/azure-cli#20119]
## Describe the bug

**Command Name**
`az cosmosdb mongodb collection throughput update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
local variable 'throughput_resource' referenced before assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cosmosdb/custom.py", line 1266, in cli_cosmosdb_mongodb_collection_throughput_update
    throughput_update_resource = _get_throughput_settings_update_parameters(throughput, max_throughput)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cosmosdb/custom.py", line 1431, in _get_throughput_settings_update_parameters
    return ThroughputSettingsUpdateParameters(resource=throughput_resource)
UnboundLocalError: local variable 'throughput_resource' referenced before assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb mongodb collection throughput update --resource-group {} --account-name {} --name {} --database-name {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by markjbrown** [comment]
There's not enough information here. Is the collection this is being run on configured for autoscale? This would cause an exception if the user attempts to set max_throughput on a non-autoscale collection.
