### ISSUE TITLE
Azure cli sent me here

### ISSUE THREAD

**Issue by MCKevmeister** [Azure/azure-cli#20124]
## Describe the bug

**Command Name**
`az mysql flexible-server db create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py", line 622, in database_create_func
    parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 154, in begin_create_or_update
    **kwargs
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 72, in _create_or_update_initial
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1),
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql flexible-server db create -d {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by savjani** [comment]
Adding @DaeunYim to help with this

**Comment by DaeunYim** [comment]
@MCKevmeister Hi, you need to give resource group and server name (--resource-group/-g, --server-name/-s) as parameters as well as the database name. If you want to skip typing resource group name and server name every time, please use az config param-persist command to store those values. https://docs.microsoft.com/en-us/cli/azure/param-persist-tutorial?tabs=azure-cli
