### ISSUE TITLE
`az storage container create -h` returns error

### ISSUE THREAD

**Issue by Rashair** [Azure/azure-cli#20121]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 582, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 260, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/opt/az/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 250, in format_help
    is_group)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 173, in show_help
    AzCliHelp.update_examples(help_file)
  File "/opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples/azext_ai_examples/custom.py", line 29, in new_examples
    examples = replace_examples(help_file.command)
  File "/opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples/azext_ai_examples/custom.py", line 41, in replace_examples
    return get_generated_examples(lookup_term)
  File "/opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples/azext_ai_examples/custom.py", line 52, in get_generated_examples
    if answer['source'] != 'pruned':
TypeError: string indices must be integers

```

## To Reproduce:
- `az storage container create -h`

## Expected Behavior
Help manual displayed.

## Environment Summary
```
Azure Cloud Shell with Microsoft Sandbox
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```
## Additional Context
Microsoft Sandbox
https://docs.microsoft.com/en-us/learn/modules/store-app-data-with-azure-blob-storage/4-create-storage-resources

**Comment by yonzhan** [comment]
storage

**Comment by RakeshMohanMSFT** [comment]
@Rashair Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
