### ISSUE TITLE
az find "az ad app create" returns TypeError: string indices must be integers

### ISSUE THREAD

**Issue by philipsd6** [Azure/azure-cli#20123]
## Describe the bug
Running `az ad app create --help` shows:

    For more specific examples, use: az find "az ad app create"

But that fails:

**Command Name**
`az find "az ad app create"`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/find/custom.py", line 49, in process_query
    if answer_list[0]['source'] == 'pruned':
TypeError: string indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az find "az ad app create"`

## Expected Behavior

A list of example usages should be returned, or the usual "Sorry I am not able to help with" message. This appears to be intermittent, as the `az find "az ad app update"` works a few times, but then has the same error now and then.

## Environment Summary
```
Linux-5.13.0-20-generic-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.29.2

Extensions:
interactive 0.4.5
db-up 0.2.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@philipsd6 Apologies for the delay. Can you please try upgrading to latest Azure CLI [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)? it has been fixed.

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed
