### ISSUE TITLE
'az container create' Table output unavailable

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#20125]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
'az container create' Table output unavailable

**To Reproduce**
root@ubuntu20:~/docker# az container create --resource-group dockers --file /root/debiandocker.yaml -o table
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

**Expected behavior**
'az container create' Table output is available

**Environment summary**
root@ubuntu20:~/docker# az version
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.29.2       2.29.2            1.0.6
root@ubuntu20:~/docker# az --version
azure-cli                         2.29.2
core                              2.29.2
telemetry                          1.0.6

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by berndverst** [comment]
```
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x1031b1f30>, <function _x509_from_base64_to_hex_transform at 0x1031b1fc0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.output: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 79, in format_table
    raise CLIError("Table output unavailable. "
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

cli.azure.cli.core.azclierror: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x103166560>]
cli.__main__: Command ran in 0.798 seconds (init: 0.045, invoke: 0.753)
```

**Comment by jiasli** [comment]
I guess you are using Python 3.10. Let's work on https://github.com/Azure/azure-cli/issues/20125.
