### ISSUE TITLE
MS Learn -  Exercise - Create a new API in API Management from a function app is not working

### ISSUE THREAD

**Issue by lluthus** [Azure/azure-cli#20137]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 403, in enable_zip_deploy_functionapp
    remove_remote_build_app_settings(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 538, in remove_remote_build_app_settings
    should_contain=app_settings_should_contain)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1019, in validate_app_settings_in_scm
    scm_settings = _get_app_settings_from_scm(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 81, in call
    raise exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 77, in call
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1038, in _get_app_settings_from_scm
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
    webapp = show_webapp(cmd, resource_group_name, name, slot=slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive informatio

**Comment by lluthus** [comment]
`#!/bin/bash

# Set up randomized names for a storage account and two functions, which must be globally unique
export STORAGE_ACCOUNT_NAME=storestorage$(openssl rand -hex 5)
export PRODUCT_FUNCTION_NAME=ProductFunction$(openssl rand -hex 5)
export ORDER_FUNCTION_NAME=OrderFunction$(openssl rand -hex 5)
export CURRENT_DIR=$(pwd)

# Get the resource group and location
export RESOURCE_GROUP=$(az group list --query "[0].name" -o tsv)
export LOCATION=$(az group show --name $RESOURCE_GROUP -o json| jq -r ".location")
printf "\nThe resource group is called $RESOURCE_GROUP and is located in $LOCATION\n"

# Create a storage account
printf "\nCreating a storage account for the functions...\n"
az storage account create --name $STORAGE_ACCOUNT_NAME --location $LOCATION --resource-group $RESOURCE_GROUP  --sku Standard_LRS
printf "\nStorage account created.\n"

# Create two functions in Azure
printf "\nCreating function apps in Azure...\n"
az functionapp create --resource-group $RESOURCE_GROUP --consumption-plan-location $LOCATION --name $PRODUCT_FUNCTION_NAME --storage-account $STORAGE_ACCOUNT_NAME --functions-version 2
az functionapp create --resource-group $RESOURCE_GROUP --consumption-plan-location $LOCATION --name $ORDER_FUNCTION_NAME --storage-account $STORAGE_ACCOUNT_NAME --functions-version 2
printf "\nFunction apps created.\n"

# Building the zip files for the functions
printf "\nBuilding zip files for deployment...\n"
for zipFile in ProductDetailsFunc OrderShippingFunc
do
    mkdir $zipFile
    unzip -q $zipFile.zip -d $zipFile
    cd $zipFile/bin/Debug/netcoreapp2.1
    zip -q -r $CURRENT_DIR/$zipFile.PKG.zip ./*
    cd $CURRENT_DIR
done
printf "\nZip files built.\n"

# Use zip deploy to publish the code
printf "\nPublishing function source code...\n"
az functionapp deployment source config-zip -g $RESOURCE_GROUP -n $PRODUCT_FUNCTION_NAME --src ProductDetailsFunc.PKG.zip
az functionapp deployment source config-zip -g $RESOURCE_GROUP -n $ORDER_FUNCTION_NAME --src OrderShippingFunc.PKG.zip
printf "\nCode published. Functions are ready to use.\n"`

**Comment by yonzhan** [comment]
route to service team

**Comment by lluthus** [comment]
Dear, now is working !
