### ISSUE TITLE
Cannot configure auto-swap

### ISSUE THREAD

**Issue by avdv** [Azure/azure-cli#20149]
## Describe the bug

**Command Name**
`az webapp deployment slot auto-swap`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/pz6jk0lcplmzwfbcqxc3kav8b9smqf6s-python3.8-knack-0.8.1/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/nix/store/r3mxr5k657vhlwd437wgq9cwznnmj01l-python3.8-azure-cli-core-2.23.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/nix/store/r3mxr5k657vhlwd437wgq9cwznnmj01l-python3.8-azure-cli-core-2.23.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/nix/store/r3mxr5k657vhlwd437wgq9cwznnmj01l-python3.8-azure-cli-core-2.23.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/nix/store/r3mxr5k657vhlwd437wgq9cwznnmj01l-python3.8-azure-cli-core-2.23.0/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/nix/store/r3mxr5k657vhlwd437wgq9cwznnmj01l-python3.8-azure-cli-core-2.23.0/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/nix/store/saawm7gsm2wbarcywr6l8cpgyk3asa6k-python3.8-azure-cli-2.23.0/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 2181, in config_slot_auto_swap
    return client.web_apps.update_configuration_slot(resource_group_name, webapp, site_config, slot)
  File "/nix/store/kxls050mxybzg43sf8bwr4sz2m1jcf72-python3.8-azure-mgmt-web-2.0.0/lib/python3.8/site-packages/azure/mgmt/web/v2020_09_01/operations/_web_apps_operations.py", line 14737, in update_configuration_slot
    body_content = self._serialize.body(site_config, 'SiteConfigResource')
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 622, in body
    raise_with_traceback(
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1446, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/nix/store/y8y164vjxyjdama0vdb4yiahjjms5p2x-python3.8-msrest-0.6.21/lib/python3.8/site-packages/msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp deployment slot create --name {} --resource-group {} --slot {}`
- `az webapp deployment slot auto-swap --name {} --resource-group {} --slot {}`

## Environment Summary
```
Linux-5.13.13-zen1-x86_64-with-glibc2.2.5
Python 3.8.11
Installer: PIP

azure-cli 2.23.0 *

```

**Comment by avdv** [comment]
I should have looked through the closed issues too, probably already solved. Sorry for the noise.
