### ISSUE TITLE
Not able to run az upgrade for 2.30.0

### ISSUE THREAD

**Issue by StigNil** [Azure/azure-cli#20147]
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 411, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 532, in increment
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/packages/six.py", line 769, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 411, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 135, in upgrade_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 184, in _upgrade_on_windows
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 202, in _download_from_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 76, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.1 *

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by rumstead** [comment]
Also experience `az upgrade` hanging. I am behind a corporate proxy but all my brew installs and such work fine.

I keep getting spammed with 
```
New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.29.2. Latest version available is 2.30.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
```

```
~ ❯ sw_vers                                                                                                                                                                                                        
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

~ ❯ az upgrade -y --debug
cli.azure.cli.command_modules.util.custom: Update azure cli with 'brew upgrade azure-cli'
Warning: azure-cli 2.29.2 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.29.2. Latest version available is 2.30.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

Warning: azure-cli 2.29.2 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.29.2. Latest version available is 2.30.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

^Ccli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10eab6d30>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 178.976 seconds (init: 0.082, invoke: 178.894)
telemetry.save: Save telemetry record of length 3000 in cache
telemetry.check: Negative: The /Users/me/.azure/telemetry.txt was modified at 2021-11-02 14:21:44.074924, which in less than 600.000000 s
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 60, in <module>
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 53, in <module>
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 105, in <module>
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/__main__.py", line 105, in <module>
    upgrade_exit_code = subprocess.call(cmd, shell=platform.system() == 'Windows')
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 351, in call
    upgrade_exit_code = subprocess.call(cmd, shell=platform.system() == 'Windows')
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 351, in call
    return p.wait(timeout=timeout)
    return p.wait(timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1189, in wait
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1189, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1917, in _wait
    return self._wait(timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1917, in _wait
    (pid, sts) = self._try_wait(0)
    (pid, sts) = self._try_wait(0)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1875, in _try_wait
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1875, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
Brew is up to date
```
~ ❯ brew update && brew upgrade azure-cli                                                                                                                                                                          
Already up-to-date.
Warning: azure-cli 2.29.2 already installed
```

**Comment by jiasli** [comment]
@StigNil, the failed line is 

https://github.com/Azure/azure-cli/blob/a7afdf11ab917e257e99b03890804c8b50a4b8ee/src/azure-cli/azure/cli/command_modules/util/custom.py#L184

Please make sure you can connect to https://aka.ms/ and try again.

**Comment by jiasli** [comment]
@rumstead, this is because the homebrew PR https://github.com/Homebrew/homebrew-core/pull/88586 has been stalled, triggering known issue https://github.com/Azure/azure-cli/issues/19196 of `az upgrade`. Please refrain from using `az upgrade` on Mac for now.

**Comment by StigNil** [comment]
> @StigNil, the failed line is
> 
> https://github.com/Azure/azure-cli/blob/a7afdf11ab917e257e99b03890804c8b50a4b8ee/src/azure-cli/azure/cli/command_modules/util/custom.py#L184
> 
> Please make sure you can connect to https://aka.ms/ and try again.

No, I cannot

**Comment by jiasli** [comment]
@StigNil, aka.ms is a public website hosted by Microsoft, which doesn't require any specific permission. You may want to check your firewall settings to allow its access.

**Comment by jiasli** [comment]
@rumstead, https://github.com/Homebrew/homebrew-core/pull/88586 has been merged and 2.30.0 is now on brew: https://formulae.brew.sh/formula/azure-cli

Please retry the update.

**Comment by StigNil** [comment]
> @StigNil, aka.ms is a public website hosted by Microsoft, which doesn't require any specific permission. You may want to check your firewall settings to allow its access.

I have tried several company pc's on company network and local network, but get the same issue, allso tried with my home computer on local network with same issue. You allways get login, and even if using private gmail as login I cant seam to get in. 

Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50020: User account 'mr.stig.nilsen@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application '405e80fc-f8e6-40e6-b6b9-e5bcc7e6813e'(RedirectionUxProd) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
Troubleshooting details
If you contact your administrator, send this info to them.
Copy info to clipboard
Request Id: ed11db9f-a0b3-4dc1-a146-10d3c014d700
Correlation Id: 8af9b14c-bfb0-4d3b-b439-9a41d3591406
Timestamp: 2021-11-04T07:41:35Z
Message: AADSTS50020: User account 'mr.**********@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft' and cannot access the application '405e80fc-f8e6-40e6-b6b9-e5bcc7e6813e'(RedirectionUxProd) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
Flag sign-in errors for review: Enable flagging
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.

**Comment by rumstead** [comment]
> @rumstead, [Homebrew/homebrew-core#88586](https://github.com/Homebrew/homebrew-core/pull/88586) has been merged and 2.30.0 is now on brew: https://formulae.brew.sh/formula/azure-cli
> 
> Please retry the update.

Will do thanks!

**Comment by jiasli** [comment]
@StigNil, I am a little bit confused. Isn't the error you pasted from `az login`? I won't think `az upgrade` can fail with that message.
