### ISSUE TITLE
az login fails: The current time MUST be before the time represented by the exp Claim

### ISSUE THREAD

**Issue by asalamintel** [Azure/azure-cli#20158]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1635894218.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/46c98d88-e344-4ed4-8496-4ed7712e255d/v2.0",
  "iat": 1635889627,
  "nbf": 1635889627,
  "exp": 1635893527,
  "aio": "AVQAq/8TAAAAJ4+ZdIpRBBRLFWAAVZzMGpkwOaIHjSjO2Yf6OXm/9ztDpqQmOUxnHhdnM7mOGZoRJNfTOwHMwH/fEe5yTfMywfOPnVvNKL2SrcV/hmD6Zjk=",
  "name": "<username>",
  "nonce": "13564f6ea3ddf17d449915fba024e33bb19469dddc23accf136bb25913a0a2c0",
  "oid": "86a2b4a4-3179-4200-aeea-91a2467c3bd5",
  "preferred_username": "<email_addr>",
  "puid": "10032001699F3AAD",
  "rh": "0.AQ0AiI3JRkTj1E6Elk7XcS4lXZV3sATbjRpGu-4C-eG_e0YNAMQ.",
  "sub": "xNXFvWlEsPSBAe6RB_znLwevhi8xDRroc9gSzhTZhmo",
  "tid": "46c98d88-e344-4ed4-8496-4ed7712e255d",
  "uti": "ibLVdsXiZ02RD8gEPS84AA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 154, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 123, in login_with_auth_code
    success_template=success_template, error_template=error_template, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 1505, in acquire_token_interactive
    **kwargs))
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 282, in obtain_token_by_browser
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 661, in obtain_token_by_browser
    flow, auth_response, scope=scope, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 136, in obtain_token_by_auth_code_flow
    auth_code_flow, auth_response, headers=headers, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    auth_code_flow, auth_response, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 561, in obtain_token_by_auth_code_flow
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 714, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oauth2.py", line 777, in _obtain_token
    "response": _resp, "params": params, "data": _data,
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 524, in <lambda>
    event, environment=authority.instance)),
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.6/site-packages/msal/token_cache.py", line 153, in __add
    if id_token else {})
  File "/opt/az/lib/python3.6/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    err, _now, json.dumps(decoded, indent=2)))
RuntimeError: 9. The current time MUST be before the time represented by the exp Claim. Current epoch = 1635894218.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/46c98d88-e344-4ed4-8496-4ed7712e255d/v2.0",
  "iat": 1635889627,
  "nbf": 1635889627,
  "exp": 1635893527,
  "aio": "AVQAq/8TAAAAJ4+ZdIpRBBRLFWAAVZzMGpkwOaIHjSjO2Yf6OXm/9ztDpqQmOUxnHhdnM7mOGZoRJNfTOwHMwH/fEe5yTfMywfOPnVvNKL2SrcV/hmD6Zjk=",
  "name": "<userrname>",
  "nonce": "13564f6ea3ddf17d449915fba024e33bb19469dddc23accf136bb25913a0a2c0",
  "oid": "86a2b4a4-3179-4200-aeea-91a2467c3bd5",
  "preferred_username": <email_addr>.",
  "puid": "10032001699F3AAD",
  "rh": "0.AQ0AiI3JRkTj1E6Elk7XcS4lXZV3sATbjRpGu-4C-eG_e0YNAMQ.",
  "sub": "xNXFvWlEsPSBAe6RB_znLwevhi8xDRroc9gSzhTZhmo",
  "tid": "46c98d88-e344-4ed4-8496-4ed7712e255d",
  "uti": "ibLVdsXiZ02RD8gEPS84AA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.11.0-37-generic-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```

**Comment by jiasli** [comment]
As the error suggested: Current epoch = 1635894218. This is 2021-11-2 23:03:38 UTC (converted using https://www.epochconverter.com/).

This issue was raised at 2021-11-2 21:57 UTC. Make sure the local time of you machine is correctly set. +@rayluo for awareness.

**Comment by asalamintel** [comment]
> As the error suggested: Current epoch = 1635894218. This is 2021-11-2 23:03:38 UTC (converted using https://www.epochconverter.com/).
> 
> This issue was raised at 2021-11-2 21:57 UTC. Make sure the local time of you machine is correctly set. +@rayluo for awareness.

This did turn out to be an issue with date,time settings on a VM in xubuntu where settings won't stick unless ntp is enabled and configured. 
Thanks for looking into this.

**Comment by jiasli** [comment]
Detailed summary is provided in https://github.com/Azure/azure-cli/issues/20388#issuecomment-987770547.

**Comment by cforce** [comment]
This is the solving workaround https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154
