### ISSUE TITLE
Could not detach static site.

### ISSUE THREAD

**Issue by TopperKain** [Azure/azure-cli#20185]
## Describe the bug
I tried to detach a site which is defintely there, but got an error.
**Command Name**
`az staticwebapp disconnect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'StaticSitesOperations' object has no attribute 'detach_static_site'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/static_sites.py", line 38, in disconnect_staticsite
    return sdk_no_wait(no_wait, client.detach_static_site,
AttributeError: 'StaticSitesOperations' object has no attribute 'detach_static_site'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az staticwebapp disconnect -n {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by StrawnSC** [comment]
Sorry about the issue, @TopperKain. This was a regression introduced by our SDK upgrade in CLI version `2.29.0`. The bug was fixed in the subsequent release. Could you try updating your CLI version and re-running the command?

**Comment by StrawnSC** [comment]
@TopperKain please reopen this issue if the bug was not fixed by updating the CLI
