### ISSUE TITLE
Az login --identity doen't work from custom container i app services

### ISSUE THREAD

**Issue by KennethJakobsen** [Azure/azure-cli#20196]
## Describe the bug
We are running a custom linux container in app services.
We have opened up SSH to the container.
From SSH we have verified that the IDENTITY_ENDPOINT environment variable exists.
When we run az login -i the following occurs 

**Command Name**
`az login --identity`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
MSI: Failed to retrieve a token from 'http://172.16.5.3:8081/msi/token/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of '{"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"52079882-ca1e-4b91-8d14-e4f6c2f6cddc"}'.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 128, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 235, in login_with_managed_identity
    msi_creds = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 47, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 596, in set_token
    self.scheme, _, self.token = get_msi_token_webapp(self.resource, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 546, in get_msi_token_webapp
    raise RuntimeError(err_msg)
RuntimeError: MSI: Failed to retrieve a token from 'http://172.16.5.3:8081/msi/token/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of '{"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"52079882-ca1e-4b91-8d14-e4f6c2f6cddc"}'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

custom linus container in azure app services
- `az login -i`

## Environment Summary
```
Linux-5.4.0-1031-azure-x86_64-with-debian-10.11, Debian GNU/Linux 10 (buster)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by KennethJakobsen** [comment]
Additional info:
The above was done with only a userassigned Identity I get this error when enabling a system assigned ID 

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 128, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 244, in login_with_managed_identity
    subscriptions = subscription_finder.find_using_specific_tenant(tenant, msi_creds)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 822, in find_using_specific_tenant
    for s in subscriptions:
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_subscriptions_operations.py", line 224, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 41, in get_token
    return AccessToken(self.token['access_token'], int(self.token['expires_on']))
ValueError: invalid literal for int() with base 10: '11/05/2021 11:27:53 +00:00'

**Comment by jiasli** [comment]
For the original issue:

```
RuntimeError: MSI: Failed to retrieve a token from 'http://172.16.5.3:8081/msi/token/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of '{"statusCode":400,"message":"Unable to load requested managed identity.","correlationId":"52079882-ca1e-4b91-8d14-e4f6c2f6cddc"}'.
```

Please make sure the managed identity is configured correctly. This can be cross-checked with `curl`:

- https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=powershell#obtain-tokens-for-azure-resources
- https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-curl

As for error

```
ValueError: invalid literal for int() with base 10: '11/05/2021 11:27:53 +00:00'
```

Could you follow https://github.com/Azure/azure-cli/issues/19480#issuecomment-952671931 and provide the raw HTTP response? Thanks.

**Comment by KennethJakobsen** [comment]
requesting this:` curl "${IDENTITY_ENDPOINT}?resource=https://vault.azure.net/&api-version=2019-08-01" -H "X-IDENTITY-HEADER: ${IDENTITY_HEADER}"  -H "Host: localhost:4141" `

gives me this response:

{
    "access_token":"..",
    "expires_on" : "1636118517",
    "resource" : "https://vault.azure.net/",
    "token_type" : "Bearer",
    "client_id":"..."
}

**Comment by KennethJakobsen** [comment]
this: `curl "${IDENTITY_ENDPOINT}?resource=management.core.windows.net/&api-version=2019-08-01" -H "X-IDENTITY-HEADER: ${IDENTITY_HEADER}"  -H "Host: localhost:4141" `

gives me
`{"exceptionMessage":"AADSTS500011: The resource principal named management.core.windows.net/ was not found in the tenant named [...]. This can happen if the application has not
 been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 
1e2c1157-9b01-4dea-be1f-89f8e12e2d00
Correlation ID: 3db0b71d-4a0b-4f44-8aa8-da26057d2df5
Timestamp: 2021-11-04 13:29:41Z",
"errorCode":"invalid_resource",
"serviceErrorCodes":["500011"],
"statusCode":400,"message":null,
"correlationId":"e8539218-fdde-47b3-a331-f972c22da818"}`

**Comment by KennethJakobsen** [comment]
I noticed "expires_in" is missing from this response...

**Comment by jiasli** [comment]
I have reproduced the issue and found the root cause. Let's work on https://github.com/Azure/azure-cli/issues/19480.

**Comment by KennethJakobsen** [comment]
@jiasli That sounds good - can you help me out with a workaround?

**Comment by waylew-lexis** [comment]
Hello, 
 Getting a similar issue with using system assigned mi on a linux container: calling 'az login -i' works, but when getting access token using 'az account get-access-token', I get this error ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: invalid literal for int() with base 10: '11/19/2021 14:29:35 +00:00'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 84, in get_access_token
    token_entry['expiresOn'] = _fromtimestamp(int(token_entry['expires_on']))\
ValueError: invalid literal for int() with base 10: '11/19/2021 14:29:35 +00:00'
To open an issue, please run: 'az feedback'

**Comment by jiasli** [comment]
@waylew-lexis, app service container managed identity support has been added by https://github.com/Azure/azure-cli/pull/20215.
