### ISSUE TITLE
Cant update access of a blob

### ISSUE THREAD

**Issue by blcksrx** [Azure/azure-cli#20200]
## Describe the bug

**Command Name**
`az storage fs access set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
At least one parameter should be set for set_access_control API
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/storage/__init__.py", line 370, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_path_client.py", line 333, in set_access_control
    raise ValueError("At least one parameter should be set for set_access_control API")
ValueError: At least one parameter should be set for set_access_control API

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs access set --owner={} -f {} -p {} --account-name {} --auth-mode {} --account-key {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.0 *

Extensions:
storage-preview 0.7.4

```

**Comment by yonzhan** [comment]
storage

**Comment by RakeshMohanMSFT** [comment]
@blcksrx Please upgrade to latest version azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
