### ISSUE TITLE
az cli failed with ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by dunalduck0** [Azure/azure-cli#20206]
## Describe the bug

**Command Name**
Install Azure CLI with "curl -L https://aka.ms/InstallAzureCli | bash". Started a new shell but "az --help" crashed for missing "colorama". Manually installed "pip install colorama", but didn't fix the issue.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'colorama'
Traceback (most recent call last):
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 582, in execute
    parsed_args = self.parser.parse_args(args)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 1043, in __call__
    parser.print_help()
  File "/home/meiyang/miniconda3/envs/amlt_release/lib/python3.7/argparse.py", line 2481, in print_help
    self._print_message(self.format_help(), file)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/parser.py", line 251, in format_help
    is_group)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/_help.py", line 168, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/_help.py", line 306, in load
    loader.versioned_load(self, options)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/knack/parser.py", line 242, in __getattribute__
    if callable(self._description) else self._description
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/home/meiyang/lib/azure-cli/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/meiyang/lib/azure-cli/lib/python3.7/site-packages/azure/cli/command_modules/find/custom.py", line 13, in <module>
    import colorama  # pylint: disable=import-error
ModuleNotFoundError: No module named 'colorama'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `curl -L https://aka.ms/InstallAzureCli | bash`
- `pip install colorama`
- Start a new shell
- `az --help`

## Environment Summary
```
Linux-5.4.0-89-generic-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.7.11
Installer: 

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
We have removed knack 0.8.3 from PyPI as `azure-cli-core` is incompatible with knack 0.8.3.

To fix an existing broken installation, please run

```
~/lib/azure-cli/bin/python -m pip install knack==0.8.2
```

**Comment by dunalduck0** [comment]
@jiasli Thanks for your suggestion. I manually installed knack v0.8.2 as you suggested, but "az --help" crashed with the same error. I also didn't understand why installing knack would resolve error of missing colorama.

![image](https://user-images.githubusercontent.com/51274745/140445069-fa929347-7855-45de-a41a-30fd571ab291.png)

**Comment by jiasli** [comment]
Please make sure you use the python at `~/lib/azure-cli/bin/python`, instead of `pip` in your current virtual environment.
