### ISSUE TITLE
Failure on quick login from AZ CLI in wsl2 Ubuntu 20.04 LTS: ValueError: Unable to find wstrust endpoint from MEX.

### ISSUE THREAD

**Issue by mitussro** [Azure/azure-cli#20221]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to find wstrust endpoint from MEX. This typically happens when attempting MSA accounts. More details available here. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 154, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 158, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 136, in login_with_username_password
    result = self.msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 1346, in acquire_token_by_username_password
    headers=headers, **kwargs))
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 1365, in _acquire_token_by_username_password_federated
    raise ValueError("Unable to find wstrust endpoint from MEX. "
ValueError: Unable to find wstrust endpoint from MEX. This typically happens when attempting MSA accounts. More details available here. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p={}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```
## Additional Context
 Same operation done from Windows env.  AZ CLI works without any issues.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is more of an MSAL issue. + MSAL developer @rayluo

**Username + password flow** is not recommended:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

> **Microsoft recommends you do not use the ROPC flow.** In most scenarios, more secure alternatives are available and recommended. This flow requires a very high degree of trust in the application, and carries risks which are not present in other flows. You should only use this flow when other more secure flows can't be used.

Instead,please use

- `az login` for [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) which will launch the default web browser for login (yes, WSL supports that)
- `az login --use-device-code` for [device code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code)

If you need automated login, please use a service principal: https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

**Comment by rayluo** [comment]
Agree with @jiasli's triage and all the correct guidance. One more thing to @mitussro , were you trying to sign in with username and password with your personal account (i.e. a Microsoft Account)? That is not a supported feature.

> ValueError: Unable to find wstrust endpoint from MEX. **This typically happens when attempting MSA accounts. More details available here**. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication

**Comment by jiasli** [comment]
I am able to reproduce with my personal outlook account:

```
> az login --username myname@outlook.com --password mypassword
...
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1365, in _acquire_token_by_username_password_federated
ValueError: Unable to find wstrust endpoint from MEX. This typically happens when attempting MSA accounts. More details available here. https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication
```
