### ISSUE TITLE
WebApp:az webapp log tail from the azure course does not work

### ISSUE THREAD

**Issue by AndreasAtGH** [Azure/azure-cli#20229]
## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail -g {} -n {}`

## Environment Summary
```
Linux-5.4.0-89-generic-x86_64-with-debian-bullseye-sid, Linux Mint 20
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Seems like you are checking for the non-existing app. please check with the existing app. If you still face the issue share us the complete `--debug` log.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
