### ISSUE TITLE
[VM] List VMs with details flag throws an error on deallocated VMs

### ISSUE THREAD

**Issue by tylerd** [Azure/azure-cli#2023]
```
pi@mylinuxmachine:~ $ az vm list -d
sequence item 0: expected string, NoneType found
Traceback (most recent call last):
  File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 333, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 153, in list_vm
    return [get_vm_details(_parse_rg_name(v.id)[0], v.name) for v in vm_list]
  File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 192, in get_vm_details
    setattr(result, 'mac_addresses', ','.join(mac_addresses))
TypeError: sequence item 0: expected string, NoneType found
```

Based on the error I expect this is because deallocated machines have no MAC address

Running `az vm list` works just fine

**Comment by tylerd** [comment]
Reproduced the issue using the latest Docker container
Version Info:
```
bash-4.3# az --version
azure-cli (0.1.1b2+dev)

acr (0.1.1b1+dev)
acs (0.1.1b1+dev)
appservice (0.1.1b1+dev)
batch (0.1.1b1+dev)
cloud (0.1.1b1+dev)
component (0.1.0rc1+dev)
configure (0.1.1b2+dev)
container (0.1.1b1+dev)
context (0.1.1b1+dev)
core (0.1.1b2+dev)
feedback (0.1.1b1+dev)
iot (0.1.1b1+dev)
keyvault (0.1.1b2+dev)
network (0.1.1b1+dev)
nspkg (0.1.1+dev)
profile (0.1.1b1+dev)
redis (0.1.1b1+dev)
resource (0.1.1b1+dev)
role (0.1.1b1+dev)
sql (0.1.1b2+dev)
storage (0.1.1b1+dev)
taskhelp (0.1.1b1+dev)
vm (0.1.1b1+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]
```

**Comment by TermeHansen** [comment]
I just ran into the same issue, and for me a fix could also be to get the state/status of the vm prior, but I can not see how to get that either??
