### ISSUE TITLE
`az synapse sql audit-policy show` needs value for optional `--blob-auditing-policy-name`

### ISSUE THREAD

**Issue by HansZimmer5000** [Azure/azure-cli#20242]
## Describe the bug

**Command Name**
`az synapse sql audit-policy show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/synapse/manual/operations/sqlpoolblobauditingpolicy.py", line 911, in workspace_audit_policy_show
    return _audit_policy_show(
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/synapse/manual/operations/sqlpoolblobauditingpolicy.py", line 955, in _audit_policy_show
    audit_policy = client.get(
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/mgmt/synapse/operations/_workspace_managed_sql_server_blob_auditing_policies_operations.py", line 87, in get
    'blobAuditingPolicyName': self._serialize.url("blob_auditing_policy_name", blob_auditing_policy_name, 'str'),
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Open a BASH Terminal
- `az login`
- `az synapse sql audit-policy show --workspace-name {some existing workspace-name} --resource-group {the matching resource-group}`

## Expected Behavior

No error due to omitting of optional `--blob-auditing-policy-name`

## Environment Summary
```
macOS-11.6.1-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0
```
### Hotfix / Workaround

Set empty value: `az synapse sql audit-policy show --workspace-name {some existing workspace-name} --resource-group {the matching resource-group} --blob-auditing-policy-name ""` 

Without prior look at the code, I guess the problem is that the variable does not have a default value and so relies on some value coming from the cli. If I have the time, I will create a PR later.

**Comment by yonzhan** [comment]
route to service team

**Comment by zesluo** [comment]
Hello @HansZimmer5000 , I can repo it. Thanks for your feedback! I will make a PR for it then.

**Comment by zesluo** [comment]
PR merged, thanks

**Comment by HansZimmer5000** [comment]
fyi, mentioned PR is [here](https://github.com/Azure/azure-cli/pull/20494)
