### ISSUE TITLE
az aks get-credentials raise "ModuleNotFoundError: No module named 'colorama'"

### ISSUE THREAD

**Issue by paganellif** [Azure/azure-cli#20254]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'colorama'
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/azure-cli/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 6, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Expected Behavior

Cluster credential added to kube-config successfully.

## Environment Summary
```
Linux-5.13.19-2-MANJARO-x86_64-with-glibc2.33, Manjaro Linux
Python 3.9.7
Installer: 

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
`colorama` was removed from Knack for non-Windows systems (https://github.com/microsoft/knack/pull/249).

I saw `Installer: ` shows empty, which is weird. May I know how you installed Azure CLI? Have you manually updated Knack to the latest version [0.9.0](https://github.com/microsoft/knack/releases/tag/v0.9.0) which is incompatible with `azure-cli` 2.30.0?

**Comment by paganellif** [comment]
The problem occurs both installing via and via pip. I didn't manually upgrade knack but downgrading to version 0.8.2 via `pip install --user 'knack == 0.8.2'~ solved the problem.

Thanks @jiasli
