### ISSUE TITLE
Remote ssh connection command for app service fails from cloud shell

### ISSUE THREAD

**Issue by Abhishek-rastogi07** [Azure/azure-cli#20257]
## Remote ssh connection command for app service fails from cloud shell

I followed the below guide:-
https://docs.microsoft.com/en-us/azure/app-service/configure-linux-open-ssh-session#open-ssh-session-from-remote-shell

**Command Name**
`az webapp create-remote-connection`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 4009, in create_tunnel
    tunnel_server = get_tunnel(cmd, resource_group_name, name, port, slot, instance)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 3977, in get_tunnel
    webapp = show_webapp(cmd, resource_group_name, name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 605, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 734, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  Follow this guide:- https://docs.microsoft.com/en-us/azure/app-service/configure-linux-open-ssh-session
- `az webapp create-remote-connection --subscription {} --resource-group {} -n {}`

## Expected Behavior
SSH into the linux container

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Abhishek-rastogi07** [comment]
@yonzhan Hi. Are there any updates on this?

**Comment by yonzhan** [comment]
webapp service team should look into this

**Comment by jiasli** [comment]
Could be related to #19903.

**Comment by navba-MSFT** [comment]
@Abhishek-rastogi07 Apologies for the late reply. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI and let me know if you still face the same issue? Awaiting your reply.
