### ISSUE TITLE
Azure CLI multiple issues after update to 2.30.0

### ISSUE THREAD

**Issue by Remi-Faydide** [Azure/azure-cli#20278]
# Azure CLI multiple issues after update to 2.30.0

### Command tested without success

- `az apim api versionset list`
- `az ad signed-in-user show`
- `az ad sp list`
- `az group list`
- `az login`
- ...

### Errors

```
The command failed with an unexpected error. Here is the traceback:
[WinError 0] : ''
Traceback (most recent call last):
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\command_modules\apim\_client_factory.py", line 10, in cf_apim
    return get_mgmt_service_client(cli_ctx, ApiManagementClient)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\client_factory.py", line 70, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\client_factory.py", line 212, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id, resource=resource,
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\_profile.py", line 335, in get_login_credentials
    credential = self._create_credential(account, client_id=client_id)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\_profile.py", line 588, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\auth\identity.py", line 182, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\auth\msal_authentication.py", line 41, in __init__
    accounts = self.get_accounts(username)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\msal\application.py", line 930, in get_accounts
    accounts = self._find_msal_accounts(environment=self.authority.instance)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\msal\application.py", line 968, in _find_msal_accounts
    for a in self.token_cache.find(
  File "C:\Python39\lib\site-packages\msal_extensions\token_cache.py", line 54, in find
    self._reload_if_necessary()
  File "C:\Python39\lib\site-packages\msal_extensions\token_cache.py", line 35, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "C:\Python39\lib\site-packages\msal_extensions\persistence.py", line 172, in load
    return self._dp_agent.unprotect(data)
  File "C:\Python39\lib\site-packages\msal_extensions\windows.py", line 111, in unprotect
    raise OSError(256, '', '', err_code)
OSError: [WinError 0] : ''
```

## To Reproduce

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. Update to the latest azure cli: `pip install azure-cli --user --upgrade`
2. try one of the following commands
   - `az apim api versionset list --resource-group {} --service-name {} --subscription {}`
   - `az login` ==> nothing happens
   - all the commands listed previously fails with the same errors

## Expected Behavior

No errors when launching such commands

## Environment Summary

```
Windows-10-10.0.19043-SP0, 
Python 3.9.5
Installer: PIP

azure-cli 2.30.0

Extensions:
account 0.2.1
ad 0.1.0
aks-preview 0.5.26
azure-devops 0.20.0
portal 0.1.2
ssh 0.1.5
subscription 0.1.4

```

## Additional Context

I installed the previous version 2.29.2 with the command `pip install azure-cli==2.29.2 --user` but now when I try to launch my az commands, I have a footer on each commands

```raw
New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.29.2. Latest version available is 2.30.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n):
```

Despite this is quite annoying to say no each time, my Terraform commands don't work since it tries to parse the last sentence `Do you want to continue? (Y/n):`

```raw
Error parsing json result from the Azure CLI: Error unmarshaling the result of Azure CLI: invalid character 'D' looking for beginning of value.
```

**Comment by Remi-Faydide** [comment]
last version `2.30.0` uninstalled with the Application Settings panel

installed the previous version with the command

```text
  $ProgressPreference = 'SilentlyContinue';
  $version = "2.29.2";
  $Uri = "https://azcliprod.blob.core.windows.net/msi/azure-cli-$version.msi";
  Invoke-WebRequest -Uri $Uri -OutFile .\AzureCLI.msi;
  Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet';
  rm .\AzureCLI.msi
```

version `2.29.2` successfully installed...

- `az login` ==> works successfully
- edit of the `$HOME\.Azure\config` to set as below
```
[auto-upgrade]
enable = no
```
This has fixed my terraform command issue, but not the az version `2.30.0` installation issue...

Anybody else is experiencing the same kind of issue ?

**Comment by diondrapeck** [comment]
@Remi-Faydide - Please use 2.29.1 version. There were multiple breaking changes released in 2.30.0 that are being investigated.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
## WinError 0

For the `OSError: [WinError 0] : ''` error, as described in https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-, it should be a successful execution

> ERROR_SUCCESS
> 0 (0x0)
> The operation completed successfully.

`unprotect` method failed at `C:\Python39\lib\site-packages\msal_extensions\windows.py`, line 111:

```py
    def unprotect(self, cipher_text):
        ...
        err_code = _GET_LAST_ERROR()
        raise OSError(256, '', '', err_code)
```

\+ MSAL developer @rayluo

You may try `az config set core.token_encryption=false` to temporarily turn it off. (⚠ This is an internal experimental config option. We may change it or drop it anytime.)

## `az upgrade` message

As for the `az upgrade` message, you may follow https://docs.microsoft.com/en-us/cli/azure/update-azure-cli to turn it off (as you have already did).

**Comment by rayluo** [comment]
> Just fully uninstall my installation with
> 
> ...
> 
> Then, re-installed the latest version with the command from the official doc
> 
> ...
> 
> Here is the result of my `az login` command
> 
> ```
> The command failed with an unexpected error. Here is the traceback:
> [WinError 0] : ''
> Traceback (most recent call last):
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
>   ...
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 172, in load
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 111, in unprotect
> OSError: [WinError 0] : ''
> ```

Hi @Remi-Faydide , the uninstall-and-reinstall would not automatically reset the data file. Would you mind manually go find and delete this file `~/.azure/msal_token_cache.bin` (encrypted), and then re-run az cli 2.30?

**Comment by bergmeister** [comment]
@diondrapeck 
May I suggest to re-publish 2.29.1 as 2.30.1 in the meantime whilst you are investigating especially since you say it's not just one issue.

**Comment by Remi-Faydide** [comment]
ok here is the status with your suggestions

# suggestion 1: 
> delete this file ~/.azure/msal_token_cache.bin (encrypted), and then re-run az cli 2.30? 

check the file before deletion
```
gci ~/.azure/msal_token_cache.bin

    Directory: C:\Users\{username}\.azure

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          04/11/2021    17:17           9264 msal_token_cache.bin
```
delete the file
```
gci ~/.azure/msal_token_cache.bin | remove-item -Force
```
confirm the version of az cli
```
az --version
azure-cli                         2.29.2 *

core                              2.29.2 *
telemetry                          1.0.6

Extensions:
account                            0.2.1
ad                                 0.1.0
aks-preview                       0.5.26
azure-devops                      0.20.0
portal                             0.1.2
ssh                                0.1.5
subscription                       0.1.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\{username}\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

check if a command respond successfully

```
az group list -o table
Name                             Location    Status
-------------------------------  ----------  ---------
group-1                  location1  Succeeded
group-2                  location2  Succeeded
group-3                  location3  Succeeded
group-x                  locationx  Succeeded
```
perform the upgrade to `2.30.0`
```
az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.29.2. Latest version available is 2.30.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
[...]
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
```
confirm the version
```
az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
account                            0.2.1
ad                                 0.1.0
aks-preview                       0.5.41
azure-devops                      0.22.0
portal                             0.1.2
ssh                                0.1.8
subscription                       0.1.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\{username}\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
check if the command `az group list -o table` works successfully
```
az group list -o table
User {username} does not exist in MSAL token cache. Run `az login`.
```
perform `az login`
```
az login
The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
The command failed with an unexpected error. Here is the traceback:
[WinError 0] : ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 145, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 121, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1488, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 660, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 714, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 771, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 523, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 229, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 44, in modify
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 35, in _reload_if_necessary
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 172, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 111, in unprotect
OSError: [WinError 0] : ''
To open an issue, please run: 'az feedback'
```
remove once again the `~/.azure/msal_token_cache.bin` file and perform `az login` once again ==> same result

# suggestion 2
> You may try az config set core.token_encryption=false to temporarily turn it off. (⚠ This is an internal experimental config option. We may change it or drop it anytime.)

```
az config set core.token_encryption=false
Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
```
perform `az login` once again ===> it works !

check if a simple command works as expected

```
az group list -o table
Name                             Location    Status
-------------------------------  ----------  ---------
group-1                  location1  Succeeded
group-2                  location2  Succeeded
group-3                  location3  Succeeded
group-x                  locationx  Succeeded
```
```

**Comment by jiasli** [comment]
The document for `CryptProtectData` says:

https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata#return-value

> If the function succeeds, the function returns **TRUE**.
> If the function fails, it returns **FALSE**. For extended error information, call [GetLastError](https://docs.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).

In MSAL extension's code:

https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/msal_extensions/windows.py#L68-L82

```py
        if _CRYPT_PROTECT_DATA(
                ctypes.byref(message_blob),
                u"python_data",
                entropy,
                None,
                None,
                _CRYPTPROTECT_UI_FORBIDDEN,
                ctypes.byref(result)):
            try:
                return result.raw()
            finally:
                _LOCAL_FREE(result.pbData)


        err_code = _GET_LAST_ERROR()
        raise OSError(256, '', '', err_code)
```

`_CRYPT_PROTECT_DATA` returned `0` indicating `False` for failure, but `_GET_LAST_ERROR` returned `0` for success. 🤔

**Comment by moritzbiersack** [comment]
This is still happening in v2.38

```
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<...>\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]
```

Temporarily fixed it by running `az account clear` but it came back after adding the azure-devops extension. Removing the extension again doesn't help. Neither does setting the token encryption to false.

**Comment by zenntenn** [comment]
Brand new Azure CLI install, never used before with this account or computer:

C:\windows\system32>az --version
azure-cli                         2.41.0

core                              2.41.0
telemetry                          1.0.8

Dependencies:
msal                            1.20.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\joshua.hillerup\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

C:\windows\system32>az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError 0] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20278

**Comment by ash3rr** [comment]
az --version
azure-cli                         2.43.0

core                              2.43.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\rankaspl\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError 0] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20278

**Comment by PedroEss** [comment]
FYI. Statement `az config set core.encrypt_token_cache=false` resolved issue on my side.

**Comment by theguru0** [comment]
Getting this error.  This machine is a build agent in Azure, and was a GEN1 box and working fine.  Now it was converted to a GEN2 box and gets this error.

C:\>az login --service-principal -u <user> -p <password> --tenant <tenant>
Decryption failed: [WinError 0] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20278

C:\>az --version
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\matt.hrynkow.so\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.


_az config set core.encrypt_token_cache=false_  Fixed this for me.

**Comment by sivajjj** [comment]
Bug Report
Describe the bug
On running az login with Azure CLI version 2.66.0, I get the following error:

bash
Copy
Edit
Decryption failed: [WinError 0]
App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20278

**Comment by zekidkiller** [comment]
Hi,

I have same mistake. 
So I decided to look for this with installation of azure-cli through pip on my desktop.
I finally found that _CRYPT_UNPROTECT_DATA in windows.py when trying to unprotect saved file return False with an error code of 0.

Everyone knows that in general 0 means SUCCESS... But here... Mystery !!

Well I don't go further because when I look at result.raw() (what is done in case it was True), result seems to be good one (aka access_token is visible).

So I decided to add a control just after error_code and before raising error like this : 

`if err_code==0:
            try:
                return result.raw().decode('utf-8')
            finally:
                _LOCAL_FREE(result.pbData)`

And TADA !!! It is working for me ! 

So I don't know if it is a good solution to this bug (in my mind, it is !), but it is clearly a workaround at least for me !! But I suppose also for many !

I have no time to deep in more, but for information I am in environment hard secured for business reasons.

Hope it can help someone,

Regards,

**Comment by astafan8** [comment]
experiencing this issue with my colleagues today again:
```
> az login
Select the account you want to log in with. For more information on login with Azure CLI, see https://go.microsoft.com/f
wlink/?linkid=2271136
Decryption failed: [WinError -2146893813] Key not valid for use in specified state. App developer may consider this guid
ance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github. com/Azure/azure-cli/issues/20231
```

What solved the issue was to manually go to `.azure` folder in the users home folder and delete `msal_token_cache.bin` (or the whole folder) and then login again.

@jiasli @rayluo @yonzhan any news on this issue from the dev's side? Any extra info that you'd need to get this addressed?
