### ISSUE TITLE
Java SpringBoot jar file deployment fails

### ISSUE THREAD

**Issue by ericis** [Azure/azure-cli#20277]
## Describe the bug

**IMPORTANT:** I am aware of the Maven plug-in, but we use Gradle and would like to simply upload the ".jar" if possible.

**Command Name**
`az webapp deploy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/az/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/opt/az/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
  File "/opt/az/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/opt/az/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/opt/az/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/az/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/az/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.6/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/opt/az/lib/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
  File "/opt/az/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/opt/az/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/opt/az/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 4085, in perform_onedeploy
    return _perform_onedeploy_internal(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 4251, in _perform_onedeploy_internal
    response = _make_onedeploy_request(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 4211, in _make_onedeploy_request
    response = requests.post(deploy_url, data=body, headers=headers, verify=not should_disable_connection_verify())
  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

The below is a shell script executed by GNU `make`...

```
	@set -eu \
	&& echo 'Creating Resource Group...' \
	&& az group create \
		--name $(azure_rg) \
		--location $(azure_region) \
	&& echo 'Resource Group successfully created.' \
	&& az config set \
		defaults.group=$(azure_rg) \
		defaults.location=$(azure_region) \
	&& echo 'Creating AppService Plan...' \
	&& az appservice plan create \
		--name $(azure_app_plan_name) \
		--is-linux \
		--sku F1 \
	&& echo 'AppService Plan successfully created.' \
	&& echo 'Creating Java web AppService...' \
	&& az webapp create \
		--name $(azure_app_name) \
		--plan $(azure_app_plan_name) \
		--runtime "JAVA|11-java11" \
	&& echo 'AppService successfully created.' \
	&& az config set logging.enable_log_file=true
	&& echo 'Deploying build artifact jar file to Azure Java web AppService...' \
	&& az webapp deploy \
		--name $(azure_app_name) \
		--src-path ./build/libs/hello-cloud-0.0.1-SNAPSHOT.jar \
		--type jar \
		--async true \
		--restart true \
	&& echo 'Java jar file successfully deployed.'
```

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.1 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by ericis** [comment]
Here is the project in question:
https://ericis.github.io/hello-cloud/services/java-springboot/#microsoft-azure

I'd love to use only the `az` CLI and not to rely on Maven and maven-specific plug-ins to empower developer choice, especially since Gradle is a very popular choice (e.g. Google uses Gradle to build Android).

**Comment by navba-MSFT** [comment]
@ericis Apologies for the late reply. The error message is pointing to the connection reset, which would typically point to the network level socket termination. Could you please let us know if you are still facing the same issue ? If yes, Could you please try the same operation[ from cloud shell ](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#code-try-11)from a different network? This plan will help us rule out any unreliable network issues at your end. Awaiting your reply.
