### ISSUE TITLE
az storage blob --help causes ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by ccaspers** [Azure/azure-cli#20296]
## Describe the bug

When trying to display help for `az storage blob` an error is generated.

**Command Name**
`az storage blob`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'colorama'
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 582, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib64/python3.9/argparse.py", line 1820, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2044, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2021, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1209, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2044, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2021, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1209, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2062, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2002, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1094, in __call__
    parser.print_help()
  File "/usr/lib64/python3.9/argparse.py", line 2550, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/parser.py", line 248, in format_help
    self.cli_help.show_help(self.prog.split()[0],
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_help.py", line 174, in show_help
    self._print_detailed_help(cli_name, help_file)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_help.py", line 65, in _print_detailed_help
    self._print_az_find_message(help_file.command, self.cli_ctx.enable_color)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_help.py", line 92, in _print_az_find_message
    from colorama import Style
ModuleNotFoundError: No module named 'colorama'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob --help`

## Expected Behavior
Command doesn't display an error

## Environment Summary
```
Linux-5.10.70-1-MANJARO-x86_64-with-glibc2.33, Manjaro Linux
Python 3.9.7
Installer: 

azure-cli 2.30.0

Extensions:
azure-devops 0.18.0
storage-preview 0.7.4

```

**Comment by yonzhan** [comment]
storage

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20254
