### ISSUE TITLE
`az group list` doesn't work - KeyError: 'environmentName'

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#2031]
I also get this when trying to switch subscriptions. Multiple things seem to be broken with this.

Example when I install from nightly:

```
$ rm -rf $HOME/.local/lib/python3.6/site-packages/*az*
$ pip install --no-cache-dir --user --upgrade --pre azure-cli --extra-index-url https://azureclinightly.blob.core.windows.net/packages
$ pip install --user --upgrade --pre azure-cli-keyvault --extra-index-url https://azureclinightly.blob.core.windows.net/packages

 azdev  ~  az group list
'environmentName'
Traceback (most recent call last):
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 336, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 36, in list_resource_groups
    rcf = _resource_client_factory()
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/command_modules/resource/_client_factory.py", line 9, in _resource_client_factory
    return get_mgmt_service_client(ResourceManagementClient)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 21, in get_mgmt_service_client
    api_version=api_version)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 51, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 253, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 239, in get_subscription
    subscriptions = self.load_cached_subscriptions()
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 227, in load_cached_subscriptions
    return [sub for sub in subscriptions
  File "/home/cole/.local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 228, in <listcomp>
    if all_clouds or sub[_ENVIRONMENT_NAME] == active_cloud.name]
KeyError: 'environmentName'

```

And then from the latest docker container: (`sha256:ac27352ef97a6cf4a9e9482de412512985db469e7fd77167e2f63473c966b4ff`)
```
 azdev  ~  docker run -it azuresdk/azure-cli-python:latest
fd178ab7c992# az login
...
fd178ab7c992# az group list
'environmentName'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 336, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/resource/custom.py", line 36, in list_resource_groups
    rcf = _resource_client_factory()
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/resource/_client_factory.py", line 9, in _resource_client_factory
    return get_mgmt_service_client(ResourceManagementClient)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/client_factory.py", line 21, in get_mgmt_service_client
    api_version=api_version)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/client_factory.py", line 51, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 253, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 239, in get_subscription
    subscriptions = self.load_cached_subscriptions()
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 227, in load_cached_subscriptions
    return [sub for sub in subscriptions
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 228, in <listcomp>
    if all_clouds or sub[_ENVIRONMENT_NAME] == active_cloud.name]
KeyError: 'environmentName'
```

**Comment by yugangw-msft** [comment]
@derekbekoe, could you take a look?

**Comment by derekbekoe** [comment]
Yep taking a look

**Comment by TheBigHeat** [comment]
Confirming that I am getting similar error as OP trying to set or list account (using latest Docker container).

From both "az account list" and "az account set --subscription ...":

```
'environmentName'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 336, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/profile/custom.py", line 24, in list_subscriptions
    subscriptions = load_subscriptions(all_clouds)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/profile/custom.py", line 18, in load_subscriptions
    subscriptions = profile.load_cached_subscriptions(all_clouds)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 227, in load_cached_subscriptions
    return [sub for sub in subscriptions
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 228, in <listcomp>
    if all_clouds or sub[_ENVIRONMENT_NAME] == active_cloud.name]
KeyError: 'environmentName'

```
Let me know if this should be entered as separate issue or if they are truly related.

Thank you!

**Comment by derekbekoe** [comment]
Identified the cause (thanks @troydai). Working on a fix.

**Comment by derekbekoe** [comment]
PR merged.
The 'latest' Docker image has the fix (image id `4ff5e253c1c6`).
I new nightly will be built tonight that has that fix.

Thanks for the bug report.

**Comment by colemickens** [comment]
AFAICT this has been broken again since Thursday.

```
$ rm -rf /home/cole/.local/lib/python3.6/site-packages/*
$ pip install --no-cache-dir --user --upgrade --pre azure-cli --extra-index-url https://azureclinightly.blob.core.windows.net/package
$ az group create ...

[stack trace]
KeyError: 'environmentName'
```

**Comment by colemickens** [comment]
Well, I purged `~/.azure` and re-logged in and it seems to be fixed...

**Comment by rgardler** [comment]
I hit this problem, purged ~/.azure re-logged in and I'm working now.

**Comment by derekbekoe** [comment]
For anyone running into this issue, the latest version of the CLI fixes this but your `~/.azure/azureProfile.json` file is likely already invalid. This is why purging `~/.azure` resolves this.

---
Details:
The original bug was that 'cloudName' was saved to ~/.azure/azureProfile.json instead of 'environmentName'. So when loading the file, the CLI would fail with `KeyError: 'environmentName'`.

The PR linked in this issue now correctly saves 'environmentName' to the file instead of 'cloudName'. But if your azureProfile.json already contains the incorrect 'cloudName', you'll see the error.
