### ISSUE TITLE
abc

### ISSUE THREAD

**Issue by Kiratpal000** [Azure/azure-cli#20323]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/home/kiratapal/site.zip'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 407, in enable_zip_deploy_webapp
    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout=timeout, slot=slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 433, in enable_zip_deploy
    with open(os.path.realpath(os.path.expanduser(src)), 'rb') as fs:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kiratapal/site.zip'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --src {} --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
@Kiratpal000 - Can you please explain what the bug is or how we can reproduce so we can further assist?

**Comment by panchagnula** [comment]
@Kiratpal000 looks like the issue is that the zip file location is incorrect or doesn't exist

No such file or directory: '/home/kiratapal/site.zip'
