### ISSUE TITLE
"az aks pod-identity add" would generate cannot import name 'edge_zone_type'

### ISSUE THREAD

**Issue by msftjonw** [Azure/azure-cli#20329]
## Describe the bug
when running AZ CLI "az aks pod-identity add --resource-group xx --cluster-name yy --namespace aa --name bb --identity-resource-id cc", the console provides the below error message.

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 481, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/home/jonw/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "/home/jonw/.azure/cliextensions/aks-preview/azext_aks_preview/_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'

**Command Name**
`az aks pod-identity add --resource-group xx --cluster-name yy --namespace aa --name bb --identity-resource-id cc`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 481, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/home/jonw/.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "/home/jonw/.azure/cliextensions/aks-preview/azext_aks_preview/_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Follow every step from [the official website](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity) until "Create a Pod identity".

## Expected Behavior
Create a Pod identity

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.18.0 *

Extensions:
aks-preview 0.5.41
hpc-cache 0.1.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by phealy** [comment]
Per the documentation, pod identity requires Azure CLI version 2.20.0. Your bug report indicates you're using version 2.18. Please try again after upgrading your Azure CLI to at least version 2.20.0 and reopen the issue if you're still having problems. Thanks!

**Comment by msftjonw** [comment]
Yup, it worked. Thank you!


Jonathan Wang

Sr. Azure Customer Engineer

Advanced Cloud Engineering (ACE) 


Office:  425-703-6823<tel:425-703-6823>

***@***.******@***.***>


________________________________
