### ISSUE TITLE
az storage copy 

### ISSUE THREAD

**Issue by woowil** [Azure/azure-cli#20324]
## Describe the bug

**Command Name**
`az storage copy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/azcopy.py", line 32, in storage_copy
TypeError: can only concatenate str (not "NoneType") to str

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage copy --source-account-key {} --source-account-name {} --source {} --exclude-pattern {} --destination {} --account-name {} --account-key {} --blob-type AppendBlob --only-show-errors --recursive`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
aks-preview 0.5.41
azure-devops 0.22.0
costmanagement 0.1.1
resource-graph 2.1.0
ssh 0.1.8

```

**Comment by yonzhan** [comment]
storage
