### ISSUE TITLE
NoneType error when enabling/disabling ahub on cluster.

### ISSUE THREAD

**Issue by dvpierce** [Azure/azure-cli#20344]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'license_type'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 3049, in aks_update
    instance.windows_profile.license_type = 'Windows_Server'
AttributeError: 'NoneType' object has no attribute 'license_type'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --subscription {} --resource-group {} --name {} --enable-ahub`

## Environment Summary
```
Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo, Red Hat Enterprise Linux
Python 3.6.8
Installer: RPM

azure-cli 2.29.1 *

Extensions:
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@dvpierce Apologies for the late reply. This issue seems to be fixed here https://github.com/Azure/azure-cli/pull/14335 . Could you please use the most [recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the Azure CLI and let us know if you are still facing this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@dvpierce I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
