### ISSUE TITLE
'utf-8' codec can't encode characters in position 29-30

### ISSUE THREAD

**Issue by gft-nine** [Azure/azure-cli#20354]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'utf-8' codec can't encode characters in position 29-30: surrogates not allowed
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 454, in storage_blob_upload_batch
    if_none_match=if_none_match, timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/util.py", line 239, in wrapper
    return True, func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 430, in _upload_blob
    return upload_blob(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 610, in upload_blob
    return type_func[blob_type]()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 603, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 470, in create_blob_from_path
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 589, in create_blob_from_stream
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 1108, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 284, in _perform_request
    _update_request(request, self._X_MS_VERSION, self._USER_AGENT_STRING)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/common/_serialization.py", line 74, in _update_request
    request.path = url_quote(request.path, '/()$=\',~')
  File "/opt/az/lib/python3.6/urllib/parse.py", line 819, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 29-30: surrogates not allowed

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch --account-name {} --content-encoding {} -d {} -s {}`

## Environment Summary
```
Linux-5.4.0-1058-aws-x86_64-with-debian-buster-sid, Ubuntu 18.04.6 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
storage
