### ISSUE TITLE
No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by CaptinCaveman** [Azure/azure-cli#20363]
## Describe the bug

**Command Name**
`az postgres`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'psycopg2._psycopg'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 582, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 260, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1975, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 2001, in _parse_known_args
    ', '.join(required_actions))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 160, in error
    recommender.set_help_examples(self.get_examples(self.prog))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 203, in get_examples
    is_group)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 195, in get_examples
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 306, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 241, in __getattribute__
    if callable(self._description) else self._description
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/azure/.azure/cliextensions/db-up/azext_db_up/custom.py", line 15, in <module>
    import psycopg2
  File "/home/azure/.azure/cliextensions/db-up/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres`

## Environment Summary
```
Linux-5.4.0-89-generic-x86_64-with-debian-bullseye-sid, Linux Mint 20.2
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
db-up 0.2.6

```

**Comment by CaptinCaveman** [comment]
Solved  - Had to use the Debian distribution (stretch)
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#no-package-for-your-distribution
