### ISSUE TITLE
az vm run-command create with protected parameters: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by gxtaillon** [Azure/azure-cli#20372]
I was unable to find another issue like this. Apologies if it's a dup.

Attempting to create a new run command per documentation found here : https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#az_vm_run_command_create

Expected: Works and runs

Actual: No azure error is produced, the command fails inside the cli.

**Command Name**
`az vm run-command create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 2270, in vm_run_command_create
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm run-command create --name {} --resource-group {} --vm-name {} --protected-parameters arg1=param1 arg2=value1 --async-execution false --script 'Write-Output "Hi"`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
Compute

**Comment by SreejaBhattacharya-MSFT** [comment]
Hi @yonzhan , can we use the protected-parameters to pass credentials? Could you please help confirm if credentials passed in "--protected-parameters" are not logged anywhere? Thanks.
