### ISSUE TITLE
az subcommand doesn't work: json.decoder.JSONDecodeError: Extra data: line 181 column 2 (char 34171)

### ISSUE THREAD

**Issue by iamworldsky** [Azure/azure-cli#20375]
## Describe the bug
    I was using it in the morning and suddenly it didn't work when I was using terraform.
    I try to reinstall and reboot, but it doesn't work.

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Extra data: line 181 column 2 (char 34171)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 22, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 62, in get_container_service_client
    return get_mgmt_service_client(cli_ctx, ResourceType.MGMT_CONTAINERSERVICE)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 212, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id, resource=resource,
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 335, in get_login_credentials
    credential = self._create_credential(account, client_id=client_id)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 588, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 182, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 41, in __init__
    accounts = self.get_accounts(username)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 872, in get_accounts
    accounts = self._find_msal_accounts(environment=self.authority.instance)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 910, in _find_msal_accounts
    for a in self.token_cache.find(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 54, in find
    self._reload_if_necessary()
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 35, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 319, in deserialize
    self._cache = json.loads(state) if state else {}
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 181 column 2 (char 34171)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --admin --name {} --resource-group {}`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0

Extensions:
front-door 1.0.16
azure-devops 0.20.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by miwithro** [comment]
Most likely a problem cli installation via homebrew.  Can you try to install it again.

**Comment by iamworldsky** [comment]
I had already reinstall it. it doesn't work.  so I try to use azure cli in another user, and it works

I thought it has something wrong with Azure configuration. I delete the .azure related file/directory in home directory
and it works.

**Comment by jiasli** [comment]
Seems to be the same problem as https://github.com/Azure/azure-cli/issues/21848
