### ISSUE TITLE
failure when running `fs file list` 

### ISSUE THREAD

**Issue by romange** [Azure/azure-cli#20380]
## Describe the bug
When `--recursive false` is passed the command fails with stacktrace
**Command Name**
`az storage fs file list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
strptime() argument 1 must be str, not None
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 370, in new_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/fs_file.py", line 77, in list_fs_files
    result = list(next(pages))
  File "/opt/az/lib/python3.6/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_generated/operations/_file_system_operations.py", line 502, in extract_data
    list_of_elem = cls(list_of_elem)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_deserialize.py", line 48, in deserialize_path_properties
    return [PathProperties._from_generated(path) for path in path_list] # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_deserialize.py", line 48, in <listcomp>
    return [PathProperties._from_generated(path) for path in path_list] # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_models.py", line 223, in _from_generated
    path_prop.last_modified = datetime.strptime(generated.last_modified, "%a, %d %b %Y %H:%M:%S %Z")
TypeError: strptime() argument 1 must be str, not None

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs file list -f {} --recursive {}`

## Environment Summary
```
Linux-5.13.0-20-generic-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
storage-preview 0.7.4

```

**Comment by yonzhan** [comment]
storage
