### ISSUE TITLE
[BUG] AzureCliCredential fails intermittently on devops pipelines with CredentialUnavailableError because of timed out after 10 seconds

### ISSUE THREAD

**Issue by harneetvirk** [Azure/azure-cli#20404]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
AzureCliCredential fails intermittently on devops pipelines with CredentialUnavailableError because of timed out after 10 seconds, and resulting in the build failures.

'['cmd', '/c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 10 seconds

**To Reproduce**
Intermittent CredentialUnavailableError  in DevOps pipelines.

**Expected behavior**
Some random Az CLI tasks should not fail with an intermittent CredentialUnavailableError

**Environment summary**
[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"

azure-cli                         2.30.0
Please let us know how we are doing: https://aka.ms/azureclihats

and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
core                              2.30.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.22.0

**Additional context**
Logs from build agent:
2021-11-11T07:56:03.1173758Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2021-11-11T07:56:03.1174605Z self = <azure.identity._credentials.chained.ChainedTokenCredential object at 0x0000023C52710BA8>
2021-11-11T07:56:03.1175442Z scopes = ('https://management.azure.com/.default',), kwargs = {}
2021-11-11T07:56:03.1176625Z history = [(<azure.identity._credentials.azure_cli.AzureCliCredential object at 0x0000023C5275C550>, 'Failed to invoke the Azure...veBrowserCredential object at 0x0000023C52732828>, 'Timed out after waiting 300 seconds for the user to authenticate')]
2021-11-11T07:56:03.1177864Z credential = <azure.identity._credentials.browser.InteractiveBrowserCredential object at 0x0000023C52732828>
2021-11-11T07:56:03.1179086Z attempts = '\nAttempted credentials:\n\tAzureCliCredential: Failed to invoke the Azure CLI\n\tInteractiveBrowserCredential: Timed out after waiting 300 seconds for the user to authenticate'
2021-11-11T07:56:03.1180830Z message = 'ChainedTokenCredential failed to retrieve a token from the included credentials.\nAttempted credentials:\n\tAzureCliC...er to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.'

<Some logs removed>

2021-11-11T07:56:03.1426711Z ------------------------------ Captured log call ------------------------------
2021-11-11T07:56:03.1427773Z [33mWARNING [0m azure.identity._internal.decorators:decorators.py:41 AzureCliCredential.get_token failed: Failed to invoke the Azure CLI
2021-11-11T07:56:03.1428786Z Traceback (most recent call last):
2021-11-11T07:56:03.1429550Z   File "c:\miniconda\envs\51333213\lib\subprocess.py", line 425, in run
2021-11-11T07:56:03.1430721Z     stdout, stderr = process.communicate(input, timeout=timeout)
2021-11-11T07:56:03.1431643Z   File "c:\miniconda\envs\51333213\lib\subprocess.py", line 863, in communicate
2021-11-11T07:56:03.1432446Z     stdout, stderr = self._communicate(input, endtime, timeout)
2021-11-11T07:56:03.1433238Z   File "c:\miniconda\envs\51333213\lib\subprocess.py", line 1114, in _communicate
2021-11-11T07:56:03.1434006Z     raise TimeoutExpired(self.args, orig_timeout)
2021-11-11T07:56:03.1435013Z subprocess.TimeoutExpired: Command '['cmd', '/c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 10 seconds
2021-11-11T07:56:03.1436106Z During handling of the above exception, another exception occurred:
2021-11-11T07:56:03.1436870Z Traceback (most recent call last):
2021-11-11T07:56:03.1437705Z   File "c:\miniconda\envs\51333213\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 141, in _run_command
2021-11-11T07:56:03.1438575Z     return subprocess.check_output(args, **kwargs)
2021-11-11T07:56:03.1439366Z   File "c:\miniconda\envs\51333213\lib\subprocess.py", line 356, in check_output
2021-11-11T07:56:03.1440070Z     **kwargs).stdout
2021-11-11T07:56:03.1440895Z   File "c:\miniconda\envs\51333213\lib\subprocess.py", line 430, in run
2021-11-11T07:56:03.1441595Z     stderr=stderr)
2021-11-11T07:56:03.1442515Z subprocess.TimeoutExpired: Command '['cmd', '/c', 'az account get-access-token --output json --resource https://management.azure.com']' timed out after 10 seconds
2021-11-11T07:56:03.1443608Z The above exception was the direct cause of the following exception:
2021-11-11T07:56:03.1444363Z Traceback (most recent call last):
2021-11-11T07:56:03.1445190Z   File "c:\miniconda\envs\51333213\lib\site-packages\azure\identity\_internal\decorators.py", line 30, in wrapper
2021-11-11T07:56:03.1445991Z     token = fn(*args, **kwargs)
2021-11-11T07:56:03.1446820Z   File "c:\miniconda\envs\51333213\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 73, in get_token
2021-11-11T07:56:03.1447630Z     output = _run_command(command)
2021-11-11T07:56:03.1448621Z   File "c:\miniconda\envs\51333213\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 162, in _run_command
2021-11-11T07:56:03.1449429Z     six.raise_from(error, ex)
2021-11-11T07:56:03.1450057Z   File "<string>", line 3, in raise_from
2021-11-11T07:56:03.1450965Z azure.identity._exceptions.CredentialUnavailableError: Failed to invoke the Azure CLI
2021-11-11T07:56:03.1452689Z [32mINFO    [0m azure.core.pipeline.policies.http_logging_policy:_universal.py:475 Request URL: 'https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration'/nRequest method: 'GET'/nRequest headers:/n    'User-Agent': 'azsdk-python-identity/1.7.1 Python/3.6.8 (Windows-10-10.0.17763-SP0) VSTS_8b119ea1-2e2a-4839-8db7-8c9e8d50f6fa_build_13339_0'/nNo body was attached to the request
2021-11-11T07:56:03.1454520Z [35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): login.microsoftonline.com:443
2021-11-11T07:56:03.1456088Z [35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:461 https://login.microsoftonline.com:443 "GET /organizations/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1589
2021-11-11T07:56:03.1458835Z [32mINFO    [0m azure.core.pipeline.policies.http_logging_policy:_universal.py:503 Response status: 200/nResponse headers:/n    'Cache-Control': 'max-age=86400, private'/n    'Content-Type': 'application/json; charset=utf-8'/n    'Strict-Transport-Security': 'REDACTED'/n    'X-Content-Type-Options': 'REDACTED'/n    'Access-Control-Allow-Origin': 'REDACTED'/n    'Access-Control-Allow-Methods': 'REDACTED'/n    'P3P': 'REDACTED'/n    'x-ms-request-id': 'cef116c9-1073-4ad3-861c-b643b8245d00'/n    'x-ms-ests-server': 'REDACTED'/n    'Set-Cookie': 'REDACTED'/n    'Date': 'Thu, 11 Nov 2021 07:43:14 GMT'/n    'Content-Leng

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The log seems to be trimmed. Could you share the full log please?

How long does it usually take to call

```
az account get-access-token --output json --resource https://management.azure.com
```

**Comment by harneetvirk** [comment]
@jiasli : I have shared the link of the logs to you on Teams.

**Comment by yatamlite** [comment]
We are running into this everyday since we've upgraded to 2.30.0.
Like the submitter pointed out, this is wrecking our CI/CD pipeline jobs.

Environment : RHEL 7/8.

```
$ time az account get-access-token --output json --resource https://management.azure.com/
{
 ...
}

real    0m13.078s
```

For temporary relief, is there a way to increase the timeout for getting the token?

**Comment by katekimani** [comment]
@yatamlite I got around this by adding an override to the installed package code on the Docker image its used in. 

1. First confirmed that the file only has 1 instance of the timeout value in the code (annoying its not set as a variable in v2.29.2)
`cat /usr/local/lib/python3.7/dist-packages/azure/identity/_credentials/azure_cli.py | grep -c 10`

2. Used `sed` to replace it with my desired timeout of 30secs
`RUN sed -i 's/10/30' /usr/local/lib/python3.7/dist-packages/azure/identity/_credentials/azure_cli.py`

**Comment by YingChen1996** [comment]
We're running into the issue in our runner and file ticket. Is there ETA to fix this bug?
{'azure-ai-ml': '1.4.0', 'mldesigner': '0.1.0b11', 'az': '{\\n  \"azure-cli\": \"2.45.0\",\\n  \"azure-cli-core\": \"2.45.0\",\\n  \"azure-cli-telemetry\": \"1.0.8\",\\n  \"extensions\": {\\n    \"databricks\": \"0.9.0\",\\n    \"ml\": \"2.14.0\"\\n  }\\n}\\n', 'python': '3.8.13'}"

**Comment by alexpovel** [comment]
I am also affected by this. Consider this example snippet:

```python
import os

from azure.identity.aio import DefaultAzureCredential
from azure.storage.blob.aio import BlobServiceClient


class AzureBlobStorage:
    def __init__(
        self,
        credential: DefaultAzureCredential | None = None,
    ) -> None:
        if credential is None:
            credential = DefaultAzureCredential()
        self.credential = credential

    async def do_things(self) -> None:
        async with self.credential as credential:
            async with BlobServiceClient(
                account_url=os.environ["AZURE_STORAGE_ACCOUNT_URL"],
                credential=credential,
            ) as bsc:
                async for container in bsc.list_containers():
                    print(container)
```

It's a dummy example for the concept of some class with associated credentials (`DefaultAzureCredentials` is instantiated only once!), doing some operation. Doesn't really matter. I followed roughly [this guide](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#async-credentials).

But it turns out, instantiating `DefaultAzureCredentials` doesn't really... do anything, if I see right? It mainly sets up the whole credential chain with all required data, but doesn't call any operation just yet.

As soon as `BlobServiceClient` requires a token, `get_token` is called. The class remembers which credential is/was "successful":

https://github.com/Azure/azure-sdk-for-python/blob/cdb4cad5d561c61a569279d51f070c969f8fa23f/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L218-L223

Running this locally, however, `az` is used, as is intended, but getting a token from it seems to involve spawning a whole new Python interpreter per `get_token` invocation? (didn't dig into this too much) It absolutely eats away CPU for what is fundamentally a simple operation, you'd think (if anything, I/O-bound, not CPU heavy):

<img width="1914" alt="image" src="https://github.com/Azure/azure-cli/assets/48824213/91076f03-dbad-457d-adb5-4ff1f8b2ef7f">

And remembering the credential is helpful, but it doesn't cache the *token value*. Just the token provider (credential).

I am calling `do_things` highly concurrently. Nothing in the docs indicate that's a bad idea, but I am starting to think otherwise... I haven't researched this properly, but I can only suspect some of those Python interpreters are put on a diet by the overburdened CPU, timing them out, leading to the issue people already mentioned in this thread. The eventual stack trace is very similar, anyway, ending in:

```text
|   File "/home/alex/project/.venv/lib/python3.11/site-packages/azure/identity/aio/_credentials/azure_cli.py", line 148, in _run_command
|     raise error from ex
| azure.identity._exceptions.CredentialUnavailableError: Failed to execute '/bin/sh'
```
