### ISSUE TITLE
App Service: Managed Identity issues with container

### ISSUE THREAD

**Issue by waylew-lexis** [Azure/azure-cli#20415]
**Describe the bug**
when calling 'az login --identity' from a linux container using the latest version of azure cli (v.2.30) with app service using a system assigned manged identity, I get the following error:

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: invalid literal for int() with base 10: '11/19/2021 15:44:21 +00:00'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 128, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 244, in login_with_managed_identity
    subscriptions = subscription_finder.find_using_specific_tenant(tenant, msi_creds)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 822, in find_using_specific_tenant
    for s in subscriptions:
  File "/usr/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/lib/python3.8/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_subscriptions_operations.py", line 224, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/usr/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/usr/lib/python3.8/site-packages/azure/cli/core/auth/adal_authentication.py", line 41, in get_token
    return AccessToken(self.token['access_token'], int(self.token['expires_on']))
ValueError: invalid literal for int() with base 10: '11/19/2021 15:44:21 +00:00'

dockerfile:

FROM runatlantis/atlantis:latest

RUN apk update && apk upgrade
RUN apk add --no-cache python3 \
  py3-pip \
  curl \
  git \
  gcc \
  bash \
  musl-dev \
  libffi-dev \
  openssl-dev \
  cargo \
  make

RUN pip install --upgrade setuptools

RUN pip install azure-cli

**Additional context**
This issue does not occur when running same image on ACI or AKS

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@waylew-lexis Apologies for the late reply. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI and let us know if you see the same issue ? Awaiting your reply.
