### ISSUE TITLE
az backup recoverypoint list with --recommended-for-archive fails

### ISSUE THREAD

**Issue by jeremypope-valpak** [Azure/azure-cli#20423]
## Describe the bug

**Command Name**
`az backup recoverypoint list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_base.py", line 90, in list_recovery_points
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom.py", line 742, in list_recovery_points
TypeError: list() missing 1 required positional argument: 'parameters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup recoverypoint list -g {} -v {} -c {} -i {} --backup-management-type {} --workload-type {} --recommended-for-archive`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
application-insights 0.1.14
automation 0.1.1
datafactory 0.5.0
log-analytics-solution 0.1.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by adityabalaji-msft** [comment]
Thanks for reaching out. We will look into this issue and revert

**Comment by adityabalaji-msft** [comment]
We were able to reproduce the issue - it happens when selecting the recommended-for-archive flag
We've identified the cause of the bug. Fix planned to be released by Dec 2nd week in the next CLI release

**Comment by adityabalaji-msft** [comment]
Issue has been fixed. Feel free to reach out if any further questions
