### ISSUE TITLE
'NoneType' object has no attribute 'identity'

### ISSUE THREAD

**Issue by spottedmahn** [Azure/azure-cli#20472]
## Describe the bug
I guess I ran an invalid command or something... but it shouldn't "blow up" like this right?

**Command Name**
`az webapp identity assign`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 830, in assign_identity
    webapp = _assign_identity(cmd.cli_ctx, getter, setter, role, scope)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 718, in assign_identity
    resource = setter(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 802, in setter
    if webapp.identity and webapp.identity.type == ResourceIdentityType.system_assigned_user_assigned:
AttributeError: 'NoneType' object has no attribute 'identity'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I was following [this guide](https://docs.microsoft.com/en-us/azure/app-service/tutorial-custom-container?pivots=container-linux)
- `az webapp identity assign --name {} --query {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
containerapp 0.2.0
deploy-to-azure 0.2.0
log-analytics 0.2.2

```

**Comment by spottedmahn** [comment]
I should mention I am using `az configure --defaults group=rs-mygroup` so I don't have to specify the resource group

**Comment by yonzhan** [comment]
route to service team

**Comment by spottedmahn** [comment]
**update**
repro steps: `az webapp identity assign --name {something that doesn't exist} --resource-group blah`

so running the command on a webapp that doesn't exist will cause the problem

**Comment by panchagnula** [comment]
@spottedmahn this was a regression on the 2.29 & 2.30 version of CLI - & hence it blew up. Please re-try with the latest CLI version.

**Comment by PramodValavala-MSFT** [comment]
@spottedmahn Looks like this has since been fixed and I can confirm that there is no error now. You could upgrade to the latest version and try again.

**Comment by spottedmahn** [comment]
I'll take your word, thanks!
