### ISSUE TITLE
Az Cli Message Auto upgrade failed. 'pypi' display despite running latest version 

### ISSUE THREAD

**Issue by schwinbp** [Azure/azure-cli#20473]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Every Az CLI command I run generates this message at the end despite successfully running the command. "Auto upgrade failed. 'pypi'"

**To Reproduce**
run "az --version" or any az cli command at command line.

**Expected behavior**
Displays this WITHOUT "Auto upgrade failed. 'pypi'"

az --version

azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.22.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\schwinbp\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
**Auto upgrade failed. 'pypi'**

**Environment summary**
Windows 10
MSI and CMD.exe CLI for Azure DevOps extension.

**Comment by schwinbp** [comment]
Resolved! 
I still don't know why this message is displayed since I have the latest Python version installed. So I think it is still a bug. 
But I was able to fix it by turning off auto upgrade in my config file in c:\users\<username>\.azure\config file.

[auto-upgrade]
enable = **no**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
If you can repro this issue, please kindly provide the `--debug` log. Thanks.

**Comment by kbrimble** [comment]
I still have this issue:
```
➜ az --version --debug
cli.knack.cli: Command arguments: ['--version', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
urllib3.connectionpool: Starting new HTTPS connection (1): azure.microsoft.com:443
urllib3.connectionpool: https://azure.microsoft.com:443 "HEAD / HTTP/1.1" 301 0
cli.azure.cli.core.util: Connectivity check: 0.2612989000000141 sec
urllib3.connectionpool: Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool: https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/main/src/azure-cli-core/setup.py HTTP/1.1" 200 1265
urllib3.connectionpool: Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool: https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/main/src/azure-cli-telemetry/setup.py HTTP/1.1" 200 676
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/kristianb/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Oct 29 2021, 10:11:34)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f2b73c49378>]
cli.__main__: Command ran in 0.612 seconds (init: 0.084, invoke: 0.528)
cli.__main__: Auto upgrade failed. 'pypi'
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/decorators.py", line 76, in _wrapped_func
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 306, in set_custom_properties
    actual_value = value() if hasattr(value, '__call__') else value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/telemetry.py", line 171, in <lambda>
    'x-ms-client-request-id'])
KeyError: 'x-ms-client-request-id'
```

**Comment by jiasli** [comment]
`auto-upgrade` is currently not maintained very actively. Please refrain from using `auto-upgrade`.

**Comment by dozer75** [comment]
Interestingly enough, never got this message before I upgraded to 2.44.1 today, have never enabled the auto upgrade either, but I thought it was strange that I got an auto-upgrade warning to this version from the previous 2.43.<something> since I have never done that before.

**Comment by kejne** [comment]
This issue popped up for me just now, which breaks the use of AzureCliCredentials in the SDK:s since it expects a json, but gets the warning-message instead!
Seems to have been turned on by default again?

**Comment by bebound** [comment]
@kejne  No, it's disabled by default.
You can list all config by `az config get`.

**Comment by kkannan1982** [comment]
`az config set auto-upgrade.enable=no`

**Comment by OranguTech** [comment]
> `auto-upgrade` is currently not maintained very actively. Please refrain from using `auto-upgrade` which is by default turned off.

Then maybe the default output (a year and a half later) shouldn't say:
`Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update`

(Which makes no mention of the fact it's unsupported/not in development/known issues.)

**Comment by webstean** [comment]
Here we are, a year later and it still saying the same thing.
```
You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
```
when this feature, apparently is **not being maintained**.
