### ISSUE TITLE
Sudden inability to do anything in Azure CLI

### ISSUE THREAD

**Issue by MathieuBeaudoin** [Azure/azure-cli#20474]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'PersistenceNotFound' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 145, in login
    subscriptions = profile.login(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 144, in login
    identity = _create_identity_instance(self.cli_ctx, self._authority, tenant_id=tenant)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 865, in _create_identity_instance
    from .auth.identity import Identity
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 19, in <module>
    from .persistence import load_persisted_token_cache, file_extensions
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/auth/persistence.py", line 14, in <module>
    from msal_extensions.persistence import PersistenceNotFound
ImportError: cannot import name 'PersistenceNotFound' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.4.0-1043-azure-x86_64-with-glibc2.10, Ubuntu 18.04.5 LTS
Python 3.8.1
Installer: PIP

azure-cli 2.30.0
azure-cli-ml 1.25.0

Extensions:
azure-cli-ml 1.25.0

```
## Additional Context

This error started appearing after an attempt to build an ACR image using the exact same command that built an already-existing ACR image (albeit with a modified Dockerfile). Afterwards, any command I attempted with azure-cli resulted in the same error. Shutting down the terminal and reopening it did not fix the issue; neither did restarting the Compute instance on which Terminal was running.

**Comment by MathieuBeaudoin** [comment]
**Update**: I managed to run the "az login" command in Terminal after switching to another, untainted, Compute instance.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
If you check the source code of `msal_extensions`, you can see `PersistenceNotFound` sits right in `msal_extensions/persistence.py`: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/69eef72b0e7a540ae00abb6a65e749cfce4d532a/msal_extensions/persistence.py#L54-L67

Please make sure `msal_extensions` is installed correctly:

```
pip install --force-reinstall --upgrade msal_extensions
```

**Comment by rayluo** [comment]
> If you check the source code of `msal_extensions`, you can see `PersistenceNotFound` sits right in `msal_extensions/persistence.py`: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/69eef72b0e7a540ae00abb6a65e749cfce4d532a/msal_extensions/persistence.py#L54-L67
> 
> Please make sure `msal_extensions` is installed correctly:
> 
> ```
> pip install --force-reinstall --upgrade msal_extensions
> ```

Agree with @jiasli's triage. This looks like a dependency issue. @MathieuBeaudoin seems to be using `conda`. @jiasli , how do we check which version of `msal_extensions` is being used? Do we use `pip list`, or does Az CLI has a different way to show its vendored `msal_extensions`?

**Comment by jiasli** [comment]
Installing `azure-cli` is conda is usually done by using `pip` (https://github.com/Azure/azure-cli/issues/16526), so `pip list` should work here.

**Comment by MathieuBeaudoin** [comment]
Reinstalling `msal_extensions` seems to have fixed the issue. Thank you!
