### ISSUE TITLE
Az log tail throws 'NoneType' object has no attribute 'host_name_ssl_states' error

### ISSUE THREAD

**Issue by sorin-silaghi** [Azure/azure-cli#20489]
## Describe the bug
I was trying to see the log tail for an application service and just got this error.
 

**Command Name**

`az webapp log tail`

 

**Errors:**

```

The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'host_name_ssl_states'

Traceback (most recent call last):

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log

  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url

AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

 

```

 

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp log tail --name {} --resource-group {}`

 

## Environment Summary

```

Windows-10-10.0.19041-SP0

Python 3.8.9

Installer: MSI

 

azure-cli 2.30.0

 

```

**Comment by sorin-silaghi** [comment]
Duplicate of #20484

**Comment by yonzhan** [comment]
route to service team

**Comment by abelykh0** [comment]
Still happens, slightly different line numbers

### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2401, in get_streaming_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2068, in _get_scm_url
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail -g {} -n {}`

## Expected Behavior

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0
```
## Additional Context

**Comment by navba-MSFT** [comment]
@sorin-silaghi the PR https://github.com/Azure/azure-cli/pull/21398 has been merged. Use the most recent version of the AzCLI and test again. Please let me know if you have any further questions. Awaiting your reply.
