### ISSUE TITLE
WebApp:az webapp log tail errors out

### ISSUE THREAD

**Issue by retorquere** [Azure/azure-cli#20484]
## Describe the bug

**Command Name**
`az webapp log tail --name hec-anaylse-main`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp log tail --name hec-anaylse-main`

## Expected Behavior

see the logs of the named app

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Unable to repro this issue. please share `--debug` log to analyze further. refer to [this](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az_webapp_log_tail) document for better understanding.

**Comment by retorquere** [comment]
I've looked at that page but it's not clear to me what I should be doing differently based on information I can find there. A run with `--debug` produces

```
Script started on Thu Nov 25 12:03:59 2021
[GitPrompt version 1.2.1 by Christer Enfors enabled. Type 'GPHelp' for help.]
[?2004h[0;34m[[0m12:03[0;34m][0m [0;32memile[0m @ [0;32mlimonia[0m: [0;33m~/Documents/HIVL/webapp[0m [0;34m[[0mdev[0;34m][0m: [0;36mUntracked[0m

$ [7maz webapp log tail --name hec-anaylse-main --debug | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g"[27m
[C[Caz webapp log tail --name hec-anaylse-main --debug | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g"
[?2004l
DEBUG: cli.knack.cli: Command arguments: ['webapp', 'log', 'tail', '--name', 'hec-anaylse-main', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10b7ed6c0>, <function OutputProducer.on_global_arguments at 0x10b82f760>, <function CLIQuery.on_global_arguments at 0x10b890ca0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'webapp': ['azure.cli.command_modules.appservice', 'azure.cli.command_modules.serviceconnector']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: appservice                0.407        64       233
DEBUG: cli.azure.cli.core: serviceconnector          0.022         4        39
DEBUG: cli.azure.cli.core: Total (2)                 0.429        68       272
DEBUG: cli.azure.cli.core: Loaded 67 groups, 272 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : webapp log tail
DEBUG: cli.azure.cli.core: Command table: webapp log tail
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10bfab640>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/emile/.azure/commands/2021-11-25.12-04-02.webapp_log_tail.32006.log'.
INFO: az_command_data_logger: command args: webapp log tail --name {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10bfce950>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x10c000160>]
DEBUG: cli.azure.cli.core.util: attempting to read file /usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/resources/WindowsFunctionsStacks.json as utf-8-sig
DEBUG: cli.azure.cli.core.util: attempting to read file /usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json as utf-8-sig
INFO: cli.knack.commands: Configured default 'hannl-hnse-rg' for arg resource_group_name
INFO: cli.knack.commands: Configured default 'hec-analyse-main' for arg name
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10c0001f0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10c000310>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10b82f7f0>, <function CLIQuery.handle_query_parameter at 0x10b890d30>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x10c0000d0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10c000280>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /5d73e7b7-b3e1-4d00-b303-056140b2a3b4/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/5d73e7b7-b3e1-4d00-b303-056140b2a3b4/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 035ab373-6b98-47ea-9811-f83c49a76820
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/3833845b-6902-4f8a-9842-008a990e5398/resourceGroups/hannl-hnse-rg/providers/Microsoft.Web/sites/hec-anaylse-main?api-version=2020-09-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '65a96908-4ddf-11ec-b712-acde48001122'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'webapp log tail'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.30.0 (HOMEBREW) azsdk-python-azure-mgmt-web/4.0.0 Python/3.10.0 (macOS-12.0.1-x86_64-i386-64bit)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/3833845b-6902-4f8a-9842-008a990e5398/resourceGroups/hannl-hnse-rg/providers/Microsoft.Web/sites/hec-anaylse-main?api-version=2020-09-01 HTTP/1.1" 404 221
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ab6fba6d-2bc2-4354-89f3-a929bfa8e19b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'ab6fba6d-2bc2-4354-89f3-a929bfa8e19b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20211125T110404Z:ab6fba6d-2bc2-4354-89f3-a929bfa8e19b'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 25 Nov 2021 11:04:04 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '221'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/hec-anaylse-main' under resource group 'hannl-hnse-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'
ERROR: az_command_data_logger: 'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'
To open an issue, please run: 'az feedback'
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10bfab880>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 3.301 seconds (init: 0.252, invoke: 3.049)
INFO: telemetry.save: Save telemetry record of length 6416 in cache
WARNING: telemetry.check: Negative: The /Users/emile/.azure/telemetry.txt was modified at 2021-11-25 12:01:33.327388, which in less than 600.000000 s
[?2004h[0;34m[[0m12:04[0;34m][0m [0;32memile[0m @ [0;32mlimonia[0m: [0;33m~/Documents/HIVL/webapp[0m [0;34m[[0mdev[0;34m][0m: [0;36mUntracked[0m

$ [?2004l

exit

Script done on Thu Nov 25 12:04:06 2021
```

**Comment by Kotasudhakarreddy** [comment]
If you take a look at the `--debug` log your command is returning `Response status: 404` (Not found).
`Response content:
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/hec-anaylse-main' under resource group 'hannl-hnse-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}`

Either of your  `WebSite name` or `ResourceGroupName` doesnot exist under the subscreption `3833845b-6902-4f8a-9842-008a990e5398`.

**Comment by retorquere** [comment]
I have only one RG, and the app was created in it, but your comment set me on the right path; if I manually specify the RG using

```
az webapp log tail --name hec-analyse-main --resource-group hannl-hnse-rg
```

it does work, but in the `--debug` log I see that these values are taken as default. I can see the logs now, so I'm good, but I still don't understand why I had to specify the RG when it matches the reported default.

**Comment by Kotasudhakarreddy** [comment]
If you can compare `--debug` logs for success and failure HTTP calls it should give you an idea on what is causing the issue.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
