### ISSUE TITLE
az resource show Exception

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2049]
```
$ az resource show -g MYRG -n MYPUBLICIP --namespace Microsoft.Network
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 333, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 147, in show_resource
    resource_id, api_version)
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 541, in __init__
    resource_type)
  File "/Users/derekb/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 609, in _resolve_api_version
    if t.resource_type.lower() == resource_type_str.lower()]
AttributeError: 'NoneType' object has no attribute 'lower'
```

Specifying the `--resource-type` param yields the correct result.

**Comment by derekbekoe** [comment]
Should have searched first. Dupe of https://github.com/Azure/azure-cli/issues/1975.
