### ISSUE TITLE
az aks command not working 

### ISSUE THREAD

**Issue by pappasG** [Azure/azure-cli#20506]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.core.polling.base_polling'
Traceback (most recent call last):
  File "/home/jerin/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/jerin/.local/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 70, in <module>
    from azure.mgmt.containerservice.models import ContainerServiceOrchestratorTypes
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/models.py", line 7, in <module>
    from .v2017_07_01.models import *
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2017_07_01/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2017_07_01/_container_service_client.py", line 22, in <module>
    from .operations import ContainerServicesOperations
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2017_07_01/operations/__init__.py", line 9, in <module>
    from ._container_services_operations import ContainerServicesOperations
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/containerservice/v2017_07_01/operations/_container_services_operations.py", line 17, in <module>
    from azure.mgmt.core.polling.arm_polling import ARMPolling
  File "/home/jerin/.local/lib/python3.8/site-packages/azure/mgmt/core/polling/arm_polling.py", line 29, in <module>
    from azure.core.polling.base_polling import (
ModuleNotFoundError: No module named 'azure.core.polling.base_polling'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --api-server-authorized-ip-ranges {}`

## Environment Summary
```
Linux-5.11.0-40-generic-x86_64-with-glibc2.29
Python 3.8.10
Installer: PIP

azure-cli 2.26.1 *

Extensions:
interactive 0.4.4
storage-preview 0.7.3

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@pappasG Apologies for the late reply. Could you please upgrade to the [most recent version](https://www.python.org/downloads/) of python and [upgrade](https://packaging.python.org/en/latest/tutorials/installing-packages/#use-pip-for-installing) all its dependent libraries and test the behavior again with the [recent CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) ? Please let us know if you are still facing this issue. Awaiting your reply.
