### ISSUE TITLE
executing az login command \\\\\\   TypeError: __init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by hamzaraouzi** [Azure/azure-cli#20503]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 154, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\_profile.py", line 177, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\_profile.py", line 750, in find_using_common_tenant
    client = self._create_subscription_client(credential)
  File "C:\ProgramData\Anaconda3\envs\azure-ml-env\lib\site-packages\azure\cli\core\_profile.py", line 843, in _create_subscription_client
    **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0, 
Python 3.6.13
Installer: PIP

azure-cli 2.30.0
azure-cli-ml 1.5.0

Extensions:
azure-cli-ml 1.5.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by hamzaraouzi** [comment]
I have resolved the problem after reinstalling azure, because i had conflect dependencies , which can be verified using the command:
pipdeptree --revers --packages azure-mgmt-resource

**Comment by jiasli** [comment]
Duplicate of #18626
