### ISSUE TITLE
Azure Bastion login via cli with aad does throw error message

### ISSUE THREAD

**Issue by cpinotossi** [Azure/azure-cli#20519]
PS C:\Users\chpinoto> az network bastion ssh -n cptddns -g cptddns --target-resource-id /subscriptions/my-sub-id/resourceGroups/cptddns/providers/Microsoft.Compute/virtualMachines/cpddnsvmhub --auth-type AAD
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 7802, in ssh_bastion_host
  File "C:\Users\chpinoto\.azure\cliextensions\ssh\azext_ssh\custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

PS C:\Users\chpinoto> az version
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.1",
    "ad": "0.1.0",
    "alias": "0.5.2",
    "application-insights": "0.1.13",
    "azure-devops": "0.18.0",
    "cli-translator": "0.3.0",
    "costmanagement": "0.1.1",
    "interactive": "0.4.4",
    "internet-analyzer": "0.1.0rc6",
    "kusto": "0.3.0",
    "log-analytics": "0.2.2",
    "portal": "0.1.1",
    "resource-graph": "1.1.0",
    "sentinel": "0.1.0",
    "ssh": "0.1.5",
    "storage-blob-preview": "0.5.0",
    "storagesync": "0.1.0"
  }
}

Some guidance how to fix this to get the bastion native client working on my Windows OS.
Thanks

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/20648
