### ISSUE TITLE
az restore-disks to secondary region

### ISSUE THREAD

**Issue by jeremypope-valpak** [Azure/azure-cli#20523]
## Describe the bug

**Command Name**
`az backup restore restore-disks`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'properties'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_base.py", line 416, in restore_disks
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom.py", line 965, in restore_disks
AttributeError: 'NoneType' object has no attribute 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup restore restore-disks --container-name {} --item-name {} --rp-name {} --storage-account {} -v {} --use-secondary-region --target-resource-group {} -g {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
application-insights 0.1.14
automation 0.1.1
datafactory 0.5.0
log-analytics-solution 0.1.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by adityabalaji-msft** [comment]
Hi @jeremypope-valpak - thanks for reaching out. We are not able to reproduce the issue when we enter the correct parameter values. However, we were able to repro the error message when we provide an incorrect value for  rp-name parameter (eg. providing an rp name that doesn't exist).

Could you confirm that all the parameter values are correct? If possible, kindly share an example command.

In the future, we will make sure to add more descriptive error message for incorrect parameter scenarios

**Comment by jeremypope-valpak** [comment]
Hi,

I use “az backup recoverypoint list” with --use-secondary-region to list the available recovery points and then take one of the “name” values from the json output  – which is an 18 digit numeric value - as the –rp-name value.  Redacted command for the restore follows:

az backup restore restore-disks --container-name MYSERVER --item-name "VM;iaasvmcontainerv2;source-rg;MYSERVER " --rp-name  "8561670527120728668" -g source-recoveryvault -rg  -v source-recoveryvault  --use-secondary-region --target-resource-group target-rg  --storage-account crrstagingaccount

I can’t find a good definition in available documentation of what –rp-name should be, so I may have made the wrong choice.

I ran the same command using the id value from the JSON as –ids in the command and received a similar error:

option '--resource-group' will be ignored due to use of '--ids'.
option '--vault-name' will be ignored due to use of '--ids'.
option '--container-name' will be ignored due to use of '--ids'.
option '--item-name' will be ignored due to use of '--ids'.
Command group 'backup' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'properties'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_base.py", line 416, in restore_disks
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom.py", line 965, in restore_disks
AttributeError: 'NoneType' object has no attribute 'properties'

Jeremy.

***@***.***<http://>
Jeremy Pope | DevOps & Cloud Engineer
dd: <tel:>  ***@***.******@***.***>
<tel:>
________________________________

t: 03450 682 572<tel:03450%20682572> valpak.co.uk<http://www.valpak.co.uk>

Unit 4, Stratford Business Park, Banbury Road, Stratford-upon-Avon CV37 7GW


***@***.***<https://twitter.com/valpak_ltd> ***@***.*** <https://www.linkedin.com/company/valpak-limited>       ***@***.*** <https://www.facebook.com/ValpakLimitedUK/>     ***@***.*** <https://www.youtube.com/channel/UCsEDdqEZVWZBJc2YziCMxSg>

a Reconomy Group Company



***@***.***<https://www.communigator.co.uk/login/Instances/valpaklz/Documents/valpakwhitepaper-ukplasticpackagingtax.pdf>





Please consider the environment before printing


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by akshayneema** [comment]
Hi @jeremypope-valpak. Unfortunately, we are still not able to reproduce the issue. Could you please provide us with the debug logs of both the command(`az backup recoverypoint list` and `az backup restore restore-disks`) so that we can investigate if it is a client-side issue or a service-side issue?

For getting debug logs you just need to run the commands with `--debug` flag. Sorry for the inconvenience. Please reach out in case of any clarification. Thanks.

**Comment by adityabalaji-msft** [comment]
Hi @jeremypope-valpak - just wanted to check back on the below, whether you were still facing this issue. If so, could you help share the debug logs for the same?

**Comment by jeremypope-valpak** [comment]
Hi, the issue was resolved by Microsoft -  turned out to be an issue with with the underlying service, rather than the AZ CLI.
Thank you,
