### ISSUE TITLE
create task with a Gitlab repository fails with "Bad Request"

### ISSUE THREAD

**Issue by bensalemd** [Azure/azure-cli#20525]
**Describe the bug**
When trying to create a container registry task for my private gitlab project, the CLI returns the following error:
"Operation returned an invalid status 'Bad Request"

The command that I used is : 
```
az acr task create --registry bdescr --name mslearn-buildwebapp-gitlab --image mslearn-webimage-gitlab --context "https://gitlab.com/bdescr/mslearn.git" --file Dockerfile --git-access-token XXXXXXXXXXXXXXXX
```

Using the --debug flag, the cli shows this particular error:
```
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/azure-testlab/providers/Microsoft.ContainerRegistry/registries/bdescr/tasks/mslearn-buildwebapp-gitlab?api-version=2019-06-01-preview HTTP/1.1" 400 270
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '270'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '72e5fedb-6ad6-452b-a78c-6ebd0ae5e50c'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx/1.15.10'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c88cd2ee-405a-498f-85fa-a3be0dbbc0b2'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENCENTRAL:20211127T122345Z:c88cd2ee-405a-498f-85fa-a3be0dbbc0b2'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 27 Nov 2021 12:23:44 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: "{\"error\":{\"code\":\"InvalidRepositoryUrl\",\"message\":\"Invalid repository URL 'https://gitlab.com/bdescr/mslearn.git'. For more information see the tutorial https://aka.ms/acr/tasks/tutorial-git-trigger.\",\"target\":\"VisualStudioTeamService\",\"details\":null}}"
msrest.exceptions: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
msrest.serialization: Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1172, in rest_key_extractor
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1501, in failsafe_deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1368, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1172, in rest_key_extractor
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/task.py", line 239, in acr_task_create
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerregistry/v2019_06_01_preview/operations/_tasks_operations.py", line 239, in _create_initial
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'

cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'
az_command_data_logger: Operation returned an invalid status 'Bad Request'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x035A3148>]
az_command_data_logger: exit code: 1
```

When using the same command but targeting a private **github repository, the operation succeeds.**

**To Reproduce**
- Create a private repository in GitLab
- Create an access token for the azure cli
- Run the command: 
```
az acr task create --registry <registry_name> --name <task_name>--image <image_name> --context https://gitlab.com/<Group>/<Project>.git --file Dockerfile --git-access-token <access_token> --debug
```

**Expected behavior**
A task should be created for a gitlab repository. 

**Environment summary**

```
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
acr task doesn't support gitlab and has no plan to suppor it

**Comment by bensalemd** [comment]
I see, thanks for the prompt answer. Closing the issue.
