### ISSUE TITLE
KeyError: 'serverVersion' when running `az aks check-acr`

### ISSUE THREAD

**Issue by lindhe** [Azure/azure-cli#20545]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1587, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --resource-group {} --name {} --acr {}`

## Environment Summary
```
Linux-5.11.0-40-generic-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
azure-devops 0.18.0

```

**Comment by lindhe** [comment]
Closing as duplicate of #20132,  #19654,  #19232,  #18762, and  #17829.
