### ISSUE TITLE
App Service Snapshot Restore Issue, This should be fixed. I have seen the below bug already raised but no solution yet.

### ISSUE THREAD

**Issue by nik0811** [Azure/azure-cli#20544]
## Describe the bug

**Command Name**
`az webapp config snapshot restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore_snapshot'
Traceback (most recent call last):
  File "/home/nikhil/.local/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1894, in restore_snapshot
    return client.web_apps.restore_snapshot(resource_group_name, name, request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore_snapshot'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config snapshot restore -g {} -n {} --time {}`

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.7.3
Installer: PIP

azure-cli 2.30.0

```

**Comment by nik0811** [comment]
https://github.com/Azure/azure-cli/issues/19492

**Comment by yonzhan** [comment]
route to service team

**Comment by nik0811** [comment]
@yonzhan  any update on the above?

**Comment by yonzhan** [comment]
webapp service team should take a look

**Comment by navba-MSFT** [comment]
@nik0811 Apologies for the late reply. Could you please try running the same command using the[ most recent version of the AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and check if you still face this issue? Awaiting your reply.
