### ISSUE TITLE
'RoleDefinitionsOperations' object has no attribute 'config'

### ISSUE THREAD

**Issue by orgads** [Azure/azure-cli#20546]
## Describe the bug

**Command Name**
`az role assignment list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleDefinitionsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 219, in list_role_assignments
    definitions_client.config.subscription_id)
AttributeError: 'RoleDefinitionsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment list --scope {}`

## Environment Summary
```
Linux-5.10.0-8-amd64-x86_64-with-glibc2.32, Debian GNU/Linux bookworm/sid
Python 3.9.9
Installer: DEB

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The installation location `/usr/lib/python3/dist-packages` indicate this is not the official Azure CLI, please see https://github.com/Azure/azure-cli/issues/19640.
