### ISSUE TITLE
Fresh install, can't run basic commands

### ISSUE THREAD

**Issue by iTiamo** [Azure/azure-cli#20569]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError -2146893813] : ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 1307, in create_resource_group
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_client_factory.py", line 10, in _resource_client_factory
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 212, in _get_mgmt_service_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 335, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 588, in _create_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 182, in get_user_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 41, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 872, in get_accounts
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 910, in _find_msal_accounts
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 54, in find
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 35, in _reload_if_necessary
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 172, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 111, in unprotect
OSError: [WinError -2146893813] : ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Spun up a new Windows 10 VM in Azure, installed Azure CLI and ran:
- `az group create --name "test" --location "westeurope" --output "json"`

## Expected Behavior
The command to complete...

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 335, in get_login_credentials
  ...
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 41, in __init__
  ...
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 111, in unprotect

This issue seems to be related to MSAL. @jiasli please help take a look~

**Comment by zhoxing-ms** [comment]
It seems to duplicated with issue https://github.com/Azure/azure-cli/issues/20278#issuecomment-965938701 @jiasli Please help confirm it~

**Comment by jiasli** [comment]
@iTiamo, could you check the discussions at #20231 and let us know:

1. Have you copied `.azure` from/to another computer?
2. Could you share the detailed steps you followed to trigger this error?

Meanwhile, you may try to solve it by deleting `~/.azure` folder and rerun `az login`.

**Comment by iTiamo** [comment]
Hi @jiasli, 1. No I did not, I simply spun up a VM in Azure and installed Azure CLI from MSI installer. 2. Spun up a default Windows 10 Pro VM in Azure, installed CLI from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli, logged in using `az login`. Ran any command, resulting in error as posted in OP.

**Comment by rayluo** [comment]
> Hi @jiasli,
> 1. ...
> 2. Spun up a default Windows 10 Pro VM in Azure, installed CLI from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli, logged in using `az login`. Ran any command, resulting in error as posted in OP.

Hi @jiasli , in this case, since our customer @iTiamo provided clear steps, I think we could follow the steps to see if we can reproduce the issue. However, even if we could reproduce this, I don't know what else I can do in this line:

> File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 111, in unprotect
> OSError: [WinError -2146893813] : ''

Perhaps you can try to catch that exception in Azure CLI, and then suggest user to opt out of token encryption as a workaround?

**Comment by jiasli** [comment]
I am not to repro with `MicrosoftWindowsServer:WindowsServer:2022-datacenter-g2:latest` VM:

```
az vm create -n $vm -g $rg --image MicrosoftWindowsServer:WindowsServer:2022-datacenter-g2:latest --size Standard_D4a_v4 --nsg-rule NONE --admin-username $username --admin-password $password --query id --output tsv
```

<details>
<summary>VM details</summary>
  
```
> az vm show --resource-group jl1208rg --name jl1208vm --show-details
{
  "additionalCapabilities": null,
  "applicationProfile": null,
  "availabilitySet": null,
  "billingProfile": null,
  "capacityReservation": null,
  "diagnosticsProfile": null,
  "evictionPolicy": null,
  "extendedLocation": null,
  "extensionsTimeBudget": null,
  "fqdns": "",
  "hardwareProfile": {
    "vmSize": "Standard_D4a_v4",
    "vmSizeProperties": null
  },
  "host": null,
  "hostGroup": null,
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Compute/virtualMachines/jl1208vm",
  "identity": null,
  "licenseType": null,
  "location": "westus2",
  "macAddresses": "00-0D-3A-6E-4C-15",
  "name": "jl1208vm",
  "networkProfile": {
    "networkApiVersion": null,
    "networkInterfaceConfigurations": null,
    "networkInterfaces": [
      {
        "deleteOption": null,
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Network/networkInterfaces/jl1208vmVMNic",
        "primary": null,
        "resourceGroup": "jl1208rg"
      }
    ]
  },
  "osProfile": {
    "adminPassword": null,
    "adminUsername": "azureuser",
    "allowExtensionOperations": true,
    "computerName": "jl1208vm",
    "customData": null,
    "linuxConfiguration": null,
    "requireGuestProvisionSignal": true,
    "secrets": [],
    "windowsConfiguration": {
      "additionalUnattendContent": null,
      "enableAutomaticUpdates": true,
      "patchSettings": {
        "assessmentMode": "ImageDefault",
        "enableHotpatching": null,
        "patchMode": "AutomaticByOS"
      },
      "provisionVmAgent": true,
      "timeZone": null,
      "winRm": null
    }
  },
  "plan": null,
  "platformFaultDomain": null,
  "powerState": "VM running",
  "priority": null,
  "privateIps": "10.0.0.4",
  "provisioningState": "Succeeded",
  "proximityPlacementGroup": null,
  "publicIps": "20.94.209.246",
  "resourceGroup": "jl1208rg",
  "resources": null,
  "scheduledEventsProfile": null,
  "securityProfile": null,
  "storageProfile": {
    "dataDisks": [],
    "imageReference": {
      "exactVersion": "20348.350.2111030009",
      "id": null,
      "offer": "WindowsServer",
      "publisher": "MicrosoftWindowsServer",
      "sharedGalleryImageId": null,
      "sku": "2022-datacenter-g2",
      "version": "latest"
    },
    "osDisk": {
      "caching": "ReadWrite",
      "createOption": "FromImage",
      "deleteOption": "Detach",
      "diffDiskSettings": null,
      "diskSizeGb": 127,
      "encryptionSettings": null,
      "image": null,
      "managedDisk": {
        "diskEncryptionSet": null,
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Compute/disks/jl1208vm_OsDisk_1_36a992a476174040b6ab6eedb2027760",
        "resourceGroup": "jl1208rg",
        "storageAccountType": "Standard_LRS"
      },
      "name": "jl1208vm_OsDisk_1_36a992a476174040b6ab6eedb2027760",
      "osType": "Windows",
      "vhd": null,
      "writeAcceleratorEnabled": null
    }
  },
  "tags": {},
  "type": "Microsoft.Compute/virtualMachines",
  "userData": null,
  "virtualMachineScaleSet": null,
  "vmId": "d5bdd477-a906-4bb5-a192-b54cc5841006",
  "zones": null
}
```

</details>

![image](https://user-images.githubusercontent.com/4003950/145166559-02e50cc7-154b-4450-9ff9-21c3f0423d61.png)

Neither with `MicrosoftWindowsDesktop:Windows-10:20h2-pro-g2:latest`:

<details>
<summary>VM details</summary>

```
> az vm show --resource-group jl1208rg --name jl1208-win10 --show-details
{
  "additionalCapabilities": null,
  "applicationProfile": null,
  "availabilitySet": null,
  "billingProfile": null,
  "capacityReservation": null,
  "diagnosticsProfile": {
    "bootDiagnostics": {
      "enabled": true,
      "storageUri": null
    }
  },
  "evictionPolicy": null,
  "extendedLocation": null,
  "extensionsTimeBudget": null,
  "fqdns": "",
  "hardwareProfile": {
    "vmSize": "Standard_D2s_v3",
    "vmSizeProperties": null
  },
  "host": null,
  "hostGroup": null,
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Compute/virtualMachines/jl1208-win10",
  "identity": null,
  "licenseType": "Windows_Client",
  "location": "centralus",
  "macAddresses": "00-22-48-47-18-82",
  "name": "jl1208-win10",
  "networkProfile": {
    "networkApiVersion": null,
    "networkInterfaceConfigurations": null,
    "networkInterfaces": [
      {
        "deleteOption": "Detach",
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Network/networkInterfaces/jl1208-win10734",
        "primary": null,
        "resourceGroup": "jl1208rg"
      }
    ]
  },
  "osProfile": {
    "adminPassword": null,
    "adminUsername": "azureuser",
    "allowExtensionOperations": true,
    "computerName": "jl1208-win10",
    "customData": null,
    "linuxConfiguration": null,
    "requireGuestProvisionSignal": true,
    "secrets": [],
    "windowsConfiguration": {
      "additionalUnattendContent": null,
      "enableAutomaticUpdates": true,
      "patchSettings": {
        "assessmentMode": "ImageDefault",
        "enableHotpatching": false,
        "patchMode": "AutomaticByOS"
      },
      "provisionVmAgent": true,
      "timeZone": null,
      "winRm": null
    }
  },
  "plan": null,
  "platformFaultDomain": null,
  "powerState": "VM running",
  "priority": null,
  "privateIps": "10.1.0.4",
  "provisioningState": "Succeeded",
  "proximityPlacementGroup": null,
  "publicIps": "40.77.120.48",
  "resourceGroup": "jl1208rg",
  "resources": null,
  "scheduledEventsProfile": null,
  "securityProfile": null,
  "storageProfile": {
    "dataDisks": [],
    "imageReference": {
      "exactVersion": "19042.1348.2111032005",
      "id": null,
      "offer": "Windows-10",
      "publisher": "MicrosoftWindowsDesktop",
      "sharedGalleryImageId": null,
      "sku": "20h2-pro-g2",
      "version": "latest"
    },
    "osDisk": {
      "caching": "ReadWrite",
      "createOption": "FromImage",
      "deleteOption": "Delete",
      "diffDiskSettings": null,
      "diskSizeGb": 127,
      "encryptionSettings": null,
      "image": null,
      "managedDisk": {
        "diskEncryptionSet": null,
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jl1208rg/providers/Microsoft.Compute/disks/jl1208-win10_disk1_4b01e2b0ddd743dca7393da4f45c87c9",
        "resourceGroup": "jl1208rg",
        "storageAccountType": "Premium_LRS"
      },
      "name": "jl1208-win10_disk1_4b01e2b0ddd743dca7393da4f45c87c9",
      "osType": "Windows",
      "vhd": null,
      "writeAcceleratorEnabled": null
    }
  },
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines",
  "userData": null,
  "virtualMachineScaleSet": null,
  "vmId": "cd565eea-eafa-4ec4-a64a-9c644750a3e2",
  "zones": null
}
```
</details>

![image](https://user-images.githubusercontent.com/4003950/145169845-80d0d366-e938-41da-af62-61e3b9e7fe56.png)

@iTiamo, could you share more information about your VM?

```
az vm show --resource-group <resouce_group_name> --name <vm_name> --show-details
```

**Comment by iTiamo** [comment]
Hi @jiasli, unfortunately I do not have the VM anymore. I tried spinning up a new VM with your details and also could not reproduce this issue. Consider it closed. 👍

**Comment by jiasli** [comment]
@iTiamo, glad to know the issue is "solved". If you see this problem again, please kindly let us know.
