### ISSUE TITLE
Can't create identity for application

### ISSUE THREAD

**Issue by jmayorga94** [Azure/azure-cli#20564]
Hi everybody, I'm having trouble creating an identity for application

**Command Name**
`az webapp identity assign`

**Executed command**
az webapp identity assign --name "myapp" --resource-group "myResourceGroup"

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 832, in assign_identity
    webapp = _assign_identity(cmd.cli_ctx, getter, setter, role, scope)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 718, in assign_identity
    resource = setter(resource)
  File "/usr/local/Cellar/azure-cli/2.29.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 804, in setter
    if webapp.identity and webapp.identity.type == ResourceIdentityType.system_assigned_user_assigned:
AttributeError: 'NoneType' object has no attribute 'identity'

```

## To Reproduce:
Steps to reproduce the behavior. 

- `az webapp identity assign --name {} --resource-group {}`

## Expected Behavior
{
  "principalId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "type": "SystemAssigned"
}
## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.29.0 *

Extensions:
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
@jmayorga94 - please update to the latest version of the CLI. I am unable to reproduce the error, please provide more details if problem persists after updating.

**Comment by panchagnula** [comment]
Please try latest version & re-open if this still repros. Thanks!
