### ISSUE TITLE
"az storage account network-rule list" not available in version 2.24.0 on AML compute instance. 

### ISSUE THREAD

**Issue by jmagosta** [Azure/azure-cli#20571]
## Describe the bug

The documented command "az storage account network-rule list" returns an error: 
APIVersion 2021-04-01 is not available

when run on an AML compute instance running azure-cli   2.24.0.

The command is documented in https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest

for version 2.30.0.    

The release notes mention that az storage account network-rule: GA resource access rules were released 2 March 2021 for version 2.20.0, so the compute instance version should be adequate. 

The actual desired usage is to enable and disable a storage account network rule set programmatically. 

**Command Name**
`az storage account network-rule list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2021-04-01 is not available
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 143, in cf_sa
    return storage_client_factory(cli_ctx).storage_accounts
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/azure/mgmt/storage/_storage_management_client.py", line 413, in storage_accounts
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2021-04-01 is not available

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account network-rule list --account-name {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-buster-sid
Python 3.6.9
Installer: PIP

azure-cli 2.24.0 *
azure-cli-ml 1.33.0

Extensions:
azure-cli-ml 1.33.0

```

**Comment by yonzhan** [comment]
storage
