### ISSUE TITLE
FunctionApp:`az show webapp` unexpected error if the requested app is a functionapp

### ISSUE THREAD

**Issue by kimjamia** [Azure/azure-cli#20635]
`az show webapp` throws the following unexpected error if the requested app is a functionapp and not a webapp.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 605, in show_webapp
    return _show_app(cmd, resource_group_name, name, "webapp", slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 734, in _show_app
    "Unable to find {} '{}', in RG '{}'".format(cmd_app_type.value, name, resource_group_name),
AttributeError: 'str' object has no attribute 'value'

```

## To Reproduce:
- Make sure you're authenticated.
- `az webapp show -g somegroup -n somefunctionapp --query id`

## Expected Behavior
Output should be:
`Unable to find webapp 'somefunctionapp', in RG 'somegroup'.`
or even
`'somefunctionapp', in RG 'somegroup' is not a functionapp.`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid, Ubuntu 20.04 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0 *

Extensions:
aks-preview 0.5.45

```

**Comment by jiasli** [comment]
Could be related to #19903.

**Comment by Kotasudhakarreddy** [comment]
You might be trying to get functionapp information using the webapp command. Since release 2.29.0, we have separated and used webapp show and functionapp show commands.

**Comment by kimjamia** [comment]
> You might be trying to get functionapp information using the webapp command. Since release 2.29.0, we have separated and used webapp show and functionapp show commands.

Correct. I intended this issue to be about the error message which is not very helpful.

I'm guessing that the API returns something (not 404) and the CLI then assumes that it can continue but because the returned object is slightly different than the expected object, it fails.

**Comment by Kotasudhakarreddy** [comment]
Issue has been fixed and released. Please upgrade to the latest CLI version (2.31.0) and reopen the issue if you're still seeing this bug
