### ISSUE TITLE
Error while AZ CLI Login

### ISSUE THREAD

**Issue by samuraifox1** [Azure/azure-cli#20637]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1638851044.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1638870542,
  "nbf": 1638870542,
  "exp": 1638874442,
  "aio": "AYQAe/8TAAAAoiqIHdKfeIcH4prmkOl8OcUzFs1Ke+23ykX8YsoBAzsKXGQX5iXtZlK9IeQ8QuX8HOy6cK3rD+4+tXtzXc5JhN56HQXMWB2osdcp6hvJxICBf7/ELB3JWt/S+AP4fuHXr0IvFpZr5pPQt4Hhf/WKgaNv67pUq9EdYtdengAgJgo=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "cf5e588443a69c2b6aec326a1d8881f1b13dbc85588ed891e11fe54817f9648d",
  "preferred_username": "rjs.swarnkar@outlook.com",
  "rh": "0.AXAAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "8j-DO43k81cWGXaVn7o4O45k1Rc5y8pvMpUUGRaEtKY",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "eE23qeV55UKhj3GMAHYcAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 145, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 121, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1488, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 660, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 714, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 771, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 523, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1638851044.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1638870542,
  "nbf": 1638870542,
  "exp": 1638874442,
  "aio": "AYQAe/8TAAAAoiqIHdKfeIcH4prmkOl8OcUzFs1Ke+23ykX8YsoBAzsKXGQX5iXtZlK9IeQ8QuX8HOy6cK3rD+4+tXtzXc5JhN56HQXMWB2osdcp6hvJxICBf7/ELB3JWt/S+AP4fuHXr0IvFpZr5pPQt4Hhf/WKgaNv67pUq9EdYtdengAgJgo=",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "cf5e588443a69c2b6aec326a1d8881f1b13dbc85588ed891e11fe54817f9648d",
  "preferred_username": "rjs.swarnkar@outlook.com",
  "rh": "0.AXAAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAEI.",
  "sub": "8j-DO43k81cWGXaVn7o4O45k1Rc5y8pvMpUUGRaEtKY",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "eE23qeV55UKhj3GMAHYcAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

Extensions:
azure-devops 0.21.0

```

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20388#issuecomment-987770547.
