### ISSUE TITLE
Cannot login with AAD based authentication via Azure Bastion native Client support

### ISSUE THREAD

**Issue by Guido-Jacobs-MS** [Azure/azure-cli#20652]
## Describe the bug
AAD based login to Azure VM via Bastion native Client support doesn't work. I get the error see below.

**Command Name**
`az network bastion ssh`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
_check_or_create_public_private_files() missing 1 required positional argument: 'credentials_folder'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8003, in ssh_bastion_host
TypeError: _check_or_create_public_private_files() missing 1 required positional argument: 'credentials_folder'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
1.) Create a Standard Bastion Host & enable the "native Client" support feature
2.) Create a Linux VM with SSH Key authentication AND enable AAD based authentication as well
3.) Set one of the following RBACs: Virtual Machine Administrator Login / Virtual Machine User Login
4.) Install the lastest Azure CLI
5.) execute: az network bastion ssh --name {NAME_OF_BASTION} --resource-group {RG_OF-BASTION} --target-resource-id {RESOURCE-ID_OF_VM} --auth-type "AAD"

- _Put any pre-requisite steps here..._
- `az network bastion ssh --name {NAME_OF_BASTION} --resource-group {RG_OF-BASTION} --target-resource-id {RESOURCE-ID_OF_VM} --auth-type "AAD"`

## Expected Behavior
Get a successful login to the VM as I can do via: az ssh vm -n NAME_OF_VM -g RRG_OF_VM

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
ssh 1.0.0

```

**Comment by jsntcy** [comment]
Network

**Comment by kairu-ms** [comment]
fixed in https://github.com/Azure/azure-cli/pull/20648
