### ISSUE TITLE
az ask get credentials crashing

### ISSUE THREAD

**Issue by kajanth** [Azure/azure-cli#20653]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2163, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3572, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --admin`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.31.0

Extensions:
interactive 0.4.5
fzf 1.0.2

```

**Comment by jsntcy** [comment]
AKS

**Comment by jf781** [comment]
Same behavior for me but running in Azure DevOps Managed Agent (Ubuntu-latest)

**Comment by AdamSharif-MSFT** [comment]
This is also happening for me with CLI and aks-preview versions below:

❯ az version
{
  "azure-cli": "2.31.0",
  "azure-cli-core": "2.31.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.47",
    "azure-firewall": "0.13.0",
    "interactive": "0.4.5",
    "resource-graph": "2.1.0",
    "virtual-wan": "0.2.11"
  }
}

`❯ az aks get-credentials -n testcluster -g aks-testcluster
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:
'name'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/adamsharif/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1316, in aks_get_credentials
    path, kubeconfig, overwrite_existing, context_name)
  File "/home/adamsharif/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2672, in _print_or_merge_credentials
    path, temp_path, overwrite_existing, context_name)
  File "/home/adamsharif/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2747, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/home/adamsharif/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2690, in _handle_merge
    if i['name'] == j['name']:
KeyError: 'name'`

Same command without the aks-preview extension works OK.

**Comment by phealy** [comment]
What's the value of your `KUBECONFIG` variable? I see this behavior if `KUBECONFIG` is defined as an empty string.

Try `unset KUBECONFIG` or specifying a location for a file via `-f path/to/kubeconfig` for me please and let me know if that resolves it?

**Comment by mirzmaster** [comment]
I've been experiencing the same issue as the reporter, and I've traced the issue to the fact that my `KUBECONFIG` env var has a leading colon (`:`).  Once I remove that leading colon, `az aks get-credentials` works as expected.

I don't think my `KUBECONFIG` export statement has changed recently, and I recall doing a `get-credentials` within the last couple of months, so I'm wondering whether this is a regression in how `KUBECONFIG` is being parsed.

This line in my `.zshrc` is resulting in the leading colon due to `$KUBECONFIG` being undefined by default:
```
export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config1:$HOME/.kube/config2
```

This results in:
```
> echo $KUBECONFIG
:/Users/myuser/.kube/config1:/Users/myuser/.kube/config2
```

Azure CLI version:
```
> az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

Full stack trace:
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2164, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3575, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by janvanuytrecht** [comment]
When will this be fixed? Happens on an ootb Microsoft hosted agent - ubuntu 20.04

**Comment by navba-MSFT** [comment]
@kajanth Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. There seems to be an issue to read / find this config file. You can try to rename or delete the file and run the az aks get-credentials command and check if that works.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

Please let us know if you still run into this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kajanth I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by janvanuytrecht** [comment]
> @kajanth Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. There seems to be an issue to read / find this config file. You can try to rename or delete the file and run the az aks get-credentials command and check if that works.
> 
> Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).
> 
> Please let us know if you still run into this issue. Awaiting your reply.

How can this be done if the issue occurs on a Microsoft hosted agent in Azure DevOps?

**Comment by MarioArriaga92** [comment]
overwrite existing doesn't help

**Comment by MarioArriaga92** [comment]
using `unset KUBECONFIG` before `az aks get-credentials --resource-group $1 --name $2 --admin --overwrite-existing --only-show-errors` helped:
```
- task: AzureCLI@2
              inputs:
                azureSubscription: '{MY_AZ_SUB}'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                arguments: $(aksClusterResourceGroup) $(aksClusterName)
                inlineScript: |
                  unset KUBECONFIG
                  az aks get-credentials --resource-group $1 --name $2 --admin --overwrite-existing --only-show-errors
                  kubectl wait --for=condition=complete --timeout=5m job/heuristics-engine-test
                  kubectl logs -l type=heuristics-engine-test
                  SUCCESS=$(kubectl get job heuristics-engine-test -o jsonpath='{.status.succeeded}')
                  if [ $SUCCESS != '1' ]; then exit 1; fi
                  echo "Component test succesful"
                  failOnStandardError: true
              displayName: 'Output test results'
```
