### ISSUE TITLE
I am unable to logout: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by comboner** [Azure/azure-cli#20679]
## Describe the bug

**Command Name**
`az logout`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 175, in logout
    profile.logout(username)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 284, in logout
    result = [x for x in subscriptions
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 285, in <listcomp>
    if user_or_sp.lower() == x[_USER_ENTITY][_USER_NAME].lower()]
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logout --username {} --verbose`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0

Extensions:
azure-devops 0.22.0

```

**Comment by jiasli** [comment]
Please check https://github.com/Azure/azure-cli/issues/20244 and see if you can get unblocked.

**Comment by comboner** [comment]
thanks a lot. this was an easy fix ;)
