### ISSUE TITLE
"EOFError: Ran out of input" when trying to 'az login'

### ISSUE THREAD

**Issue by thomasoliveira** [Azure/azure-cli#20676]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Ran out of input
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 140, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 98, in _msal_app
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
EOFError: Ran out of input

```

## To Reproduce:
- the error started to appear after I canceled a `az ml job create` command using Ctrl-C.
- `az login`

## Expected Behavior

A browser would open so I could log in.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
ml 2.0.1a5

```

**Comment by MarcDufresne** [comment]
We are experiencing the same issue since 2021-12-07. My `az` is updated to the latest version.

It happens through Terraform in our case, when supposedly trying to get an access token, but it is not very clear. It is also intermittent, we run the command over and over until it goes through.

## Environment Summary
```
azure-cli                         2.31.0

core                              2.31.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.46
ml                                 2.0.3
```

## Error traceback
```
│ Error: unable to get authorization token for graph endpoints: obtaining Authorization Token from the Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:

│ ERROR: Ran out of input
│ Traceback (most recent call last):
│   File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
│     raise ex
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
│     result = cmd_copy(params)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 76, in get_access_token
│     creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     credential = self._create_credential(account, tenant)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 593, in _create_credential
│     return identity.get_user_credential(username_or_sp_id)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 209, in get_user_credential
│     return UserCredential(self.client_id, username, **self._msal_app_kwargs)
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
│     Identity._msal_http_cache = self._load_msal_http_cache()
│   File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
│     persisted_http_cache = pickle.load(f)
│ EOFError: Ran out of input
│ To open an issue, please run: 'az feedback'
```

**Comment by thomasoliveira** [comment]
After removing the most recent files from C:\Users\<user>\.azure, `az login` worked correctly again.

**Comment by MarcDufresne** [comment]
I traced back the change that causes this to here: https://github.com/Azure/azure-cli/pull/20234#discussion_r746196790

Somehow it was decided to not catch `EOFError` (among others) which causes the issue we have here

**Comment by jiasli** [comment]
This should be an edge case caused by Terraform calling Azure CLI concurrently. Let's work on https://github.com/Azure/azure-cli/issues/20707.
