### ISSUE TITLE
unable to create linked service through Azure CLI

### ISSUE THREAD

**Issue by dejan-shuki** [Azure/azure-cli#20681]
## Describe the bug

**Command Name**
`az synapse linked-service create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
string indices must be integers
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 36, in create_or_update_linked_service
TypeError: string indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse linked-service create --name LS_dakeyvault --file "'C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json'" --workspace-name edap-d-syn`

The file contained a simple key vault linked service:
{
	"name": "LS_dakeyvault",
	"properties": {
		"annotations": [],
		"type": "AzureKeyVault",
		"typeProperties": {
			"baseUrl": "https://edap-d-kv.vault.azure.net/"
		}
	}
}

**Note**: I placed both single and double quote around the file name.
I was trying to fix quoting issue:
> az synapse linked-service create --name LS_dakeyvault --file "C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json" --workspace-name %synName%
Failed to parse JSON: C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json
Error detail: Expecting value: line 1 column 1 (char 0)
The JSON may have been parsed by the shell. See https://docs.microsoft.com/cli/azure/use-cli-effectively#quoting-issues

## Environment Summary
Dev/Test subscription

Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

Extensions:
arcdata 1.1.2
databricks 0.7.3
interactive 0.4.5

```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by jiasli** [comment]
Adding service team to help.

**Comment by wonner** [comment]
Hi @dejan-shuki , could you please add "@" at the front of the path? 
for example: --file @"C:\Project\SynGitTest0\linkedService\LS_dakeyvault.json"
Here is the related doc: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#best-practice-use-file-input-for-json
cc: @kevinzz6

**Comment by dejan-shuki** [comment]
That worked. Thank you.
