### ISSUE TITLE
Failure on azure sunapse pipeline creation

### ISSUE THREAD

**Issue by Gianfe** [Azure/azure-cli#20690]
## Describe the bug

**Command Name**
`az synapse pipeline create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 82, in create_or_update_pipeline
KeyError: 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse pipeline create --workspace-name {} --name {} --file {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Routing to service team.

**Comment by kevinzz6** [comment]
hi @Gianfe , could you please add "@" at the front of the path?
for example: --file @"C:\Synapse\pipeline.json"
Here is the related doc: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#best-practice-use-file-input-for-json

**Comment by jiasli** [comment]
PowerShell quoting issue is tracked by #15529.
