### ISSUE TITLE
az webapp log tail with invalid resource-group(or subscription, or name) produces unfriendly errors

### ISSUE THREAD

**Issue by tanigon** [Azure/azure-cli#20709]
## Describe the bug
This may not be a bug, but possibly unintended behavior of CLI.
(in my opinion) Error message is just unfriendly.

**Command Name**
`az webapp log tail --resource-group {} --name {}`
and, only happened when described resource-group is invalid or unreachable without explicit `--subscription {}`.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2280, in get_streaming_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
- `az webapp log tail --resource-group {} --name {}`
may reproduce when described resource-group or name is invalid.

## Expected Behavior
more kindful error message.
such as "Resource group {} not found" or so..?

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: 

azure-cli 2.30.0 *

```

**Comment by tanigon** [comment]
easier way to reproduce:
- prepare working `az webapp log tail .....` command line
- modify any parameter (such as resource-group) to invalid one, and try it in command line
may reproduce this error

(Again) this may not be a bug, but possibly unintended weird error message so I drop this one as bugreport

**Comment by panchagnula** [comment]
@tanigon I am unable to reproduce this - do you still see this with the latest version of CLI?

**Comment by tanigon** [comment]
@panchagnula 

az upgrade and tried again, still reproduce.

```
D:\>az webapp log tail --resource-group invalid_something
(--name | --ids) are required

D:\>az webapp log tail --resource-group invalid_something --name invalid_name
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2468, in get_streaming_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2135, in _get_scm_url
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'
To open an issue, please run: 'az feedback'

D:\>az version
{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by panchagnula** [comment]
@tanigon what I see is the validation failure (which is what I expect) 
 (ResourceGroupNotFound) Resource group 'invalid_rg' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'invalid_rg' could not be found. Let me try this on cloud shell install of my local cli installed

**Comment by tanigon** [comment]
@panchagnula 
hmm, strange, and what I expected to see is such error message. it's informative.  but strange stack trace is not.
can I help in any way?
what I quote is everything and it looks some sort of stacktrace of problematic line of az cli tool?(I'm not sure)

**Comment by panchagnula** [comment]
Thanks @tanigon I am checking the core-cli team directly to check on the possible - since you are not the only customer reporting this :( I will keep this forum posted with updates & reach out directly if I need further help from you.

**Comment by seligj95** [comment]
closing, no longer relevant
