### ISSUE TITLE
Fail to execute command `az network application-gateway private-link add`

### ISSUE THREAD

**Issue by YuanyuanNi** [Azure/azure-cli#20708]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

when execute command 'az network application-gateway private-link add---’， the CLI shows error as below:

Command group 'network application-gateway private-link' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 527, in add_ag_private_link
TypeError: 'NoneType' object is not iterable
**To Reproduce**

commands as below:
az network application-gateway private-link add -g {} -n {} --frontend-ip {} --subnet {} --gateway-name {}
**Expected behavior**

the application-gateway private-link shoud be created successful
**Environment summary**

Powershell on Win 11
azure-cli                         2.30.0 *

core                              2.30.0 *
telemetry                          1.0.6

Extensions:
application-insights              0.1.14
virtual-wan                       0.2.11
**Additional context**

**Comment by jiasli** [comment]
Adding @kairu-ms to help.
