### ISSUE TITLE
az group list broken

### ISSUE THREAD

**Issue by nunofranciscomoreira** [Azure/azure-cli#20710]
## Describe the bug

**Command Name**
`az group list`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cannot import name 'raise_subdivision_deployment_error' from 'azure.cli.core.commands.arm' (/usr/lib/python3/dist-packages/azure/cli/core/commands/arm.py)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 480, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 315, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 789, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 829, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/resource/custom.py", line 31, in <module>
    from azure.cli.core.commands.arm import raise_subdivision_deployment_error
ImportError: cannot import name 'raise_subdivision_deployment_error' from 'azure.cli.core.commands.arm' (/usr/lib/python3/dist-packages/azure/cli/core/commands/arm.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list`

## Environment Summary
```
Linux-5.9.0-kali1-amd64-x86_64-with-glibc2.31, Kali GNU/Linux Rolling
Python 3.9.1
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by zhoxing-ms** [comment]
This is a legacy issue of CLI in the old version `2.18.0`. This issue in the latest version of CLI should have been resolved. You can use `az upgrade --y` to update CLI to the latest version, then please have a try again
