### ISSUE TITLE
CloudShell get-access-token error - Failed to connect to MSI

### ISSUE THREAD

**Issue by simonsben** [Azure/azure-cli#20715]
## Describe the bug
When requesting an access token from `admin.microsoft.com` az cli fails.

**Command Name**
`az account get-access-token`

**Errors:**
```
Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
```

## To Reproduce:
Steps to reproduce the behavior.

- `az account get-access-token --output json --resource https://admin.microsoft.com`

## Expected Behavior
``` json
{
  "accessToken": "...",
  "expiresOn": "2021-12-13 20:46:28.000000",
  "subscription": "...",
  "tenant": "...",
  "tokenType": "Bearer"
}
```

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.31.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0
```

## Additional Context
```
cli.knack.cli: Command arguments: ['account', 'get-access-token', '--output', 'json', '--resource', 'https://admin.microsoft.com', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f681d915b70>, <function OutputProducer.on_global_arguments at 0x7f681d849730>, <function CLIQuery.on_global_arguments at 0x7f681d862840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'account': ['azure.cli.command_modules.profile', 'azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.002         2         9
cli.azure.cli.core: resource                  0.015        40       187
cli.azure.cli.core: Total (2)                 0.018        42       196
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.134         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.134         1         1
cli.azure.cli.core: Loaded 42 groups, 197 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : account get-access-token
cli.azure.cli.core: Command table: account get-access-token
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f681d428400>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/ben/.azure/commands/2021-12-13.19-32-59.account_get-access-token.419.log'.
az_command_data_logger: command args: account get-access-token --output {} --resource {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f681d3de2f0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f681d34e510>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f681d34e598>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f681d34e6a8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f681d8497b8>, <function CLIQuery.handle_query_parameter at 0x7f681d8628c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f681d34e488>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f681d34e620>]
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 400 863
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://admin.microsoft.com'}
msrestazure.azure_active_directory: MSI: Failed to retrieve a token from 'http://localhost:50342/oauth2/token' with an error of '400 Client Error: Bad Requestfor url: http://localhost:50342/oauth2/token'. This could be caused by the MSI extension not yet fully provisioned.
cli.azure.cli.core.auth.adal_authentication: throw requests.exceptions.HTTPError when doing MSIAuthentication:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 58, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 58, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 70, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 77, in get_access_token
    tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 380, in get_raw_token
    scopes_to_resource(scopes))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 720, in msi_auth_factory
    return MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/adal_authentication.py", line 73, in set_token
    'Get Token request returned: {}'.format(err.response))
azure.cli.core.azclierror.AzureResponseError: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>

cli.azure.cli.core.azclierror: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
az_command_data_logger: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f681d428620>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.414 seconds (init: 0.119, invoke: 0.295)
telemetry.save: Save telemetry record of length 3198 in cache
telemetry.check: Negative: The /home/ben/.azure/telemetry.txt was modified at 2021-12-13 19:32:55.203057, which in less than 600.000000 s
```

**Comment by jiasli** [comment]
This is a known issue of Cloud Shell because https://admin.microsoft.com is not in their allow list (https://github.com/Azure/azure-cli/issues/11386).

**Comment by simonsben** [comment]
> This is a known issue of Cloud Shell because https://admin.microsoft.com is not in their allow list (#11386).

Sorry, I wasn't able to get any additional information from the ticket you linked - so they specifically block this within cloud shell, because it works fine for me locally?

**Comment by jiasli** [comment]
Cloud Shell _should_ support `https://admin.microsoft.com` as the resource but it doesn't, because Cloud Shell only allows resources in its allow list. 

This is the design of Cloud Shell and Cloud Shell is working on unblock all resources.

**Comment by jrett** [comment]
What's the workaround? I'm unable to activate my MSHM because of this.

**Comment by simonsben** [comment]
If you run `az login` explicitly in Cloud Shell it will generate whichever token you need for it to succeed

**Comment by navba-MSFT** [comment]
@simonsben Apologies for the late reply. Please let us know if you have any further questions or need any assistance on this. Awaiting your reply.
