### ISSUE TITLE
WebApp:Cannot create and deploy webapp during mslearn course

### ISSUE THREAD

**Issue by morriekken** [Azure/azure-cli#20729]
Beeing in right folder in az cli cloud shell (bash) using activated mslearn sandbox I ran following command:
```
WEBAPPNAME=educationapp-$RANDOM
az webapp up \
    --resource-group learn-4c7610d5-32f9-48f3-a4f7-7d4deab567d3 \
    --location centralus \
    --sku F1 \
    --name $WEBAPPNAME
```
This was supposed to create an webapp from artefacts in folder but instead it failed with following error:

**Command Name**
`az webapp up`

**Errors:**
```
The webapp 'educationapp-6476' doesn't exist
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 3959, in webapp_up
    plan=plan)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 385, in get_plan_to_use
    return _determine_if_default_plan_to_use(cmd, _default_asp, resource_group_name, loc, sku, create_rg)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 404, in _determine_if_default_plan_to_use
    _asp_generic = plan_name[:-len(plan_name.split("_")[4])]
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- PRE: Activated MSLearn Sandbox
```
WEBAPPNAME=educationapp-$RANDOM
az webapp up \
    --resource-group learn-4c7610d5-32f9-48f3-a4f7-7d4deab567d3 \
    --location centralus \
    --sku F1 \
    --name $WEBAPPNAME
```

## Expected Behavior
Successfull webapp creation

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.31.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

```

**Comment by jiasli** [comment]
Routing to service team.

**Comment by Kotasudhakarreddy** [comment]
@morriekken - The command is required to run from the folder where the code is present. please refer [here](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_up)  for more details.

**Comment by morriekken** [comment]
@Kotasudhakarreddy - The command was run from folder with code provided as part of this exercise:
https://docs.microsoft.com/en-us/learn/modules/develop-app-that-queries-azure-sql/5-exercise-connect-aspnet-to-azure-sql

I double checked current folder and it was the right one.

**Comment by StrawnSC** [comment]
@morriekken sorry you're running into this issue -- it should be fixed by this [PR](https://github.com/Azure/azure-cli/pull/20760), which is in the latest version of the CLI. Could you try upgrading and rerunning the command?

**Comment by panchagnula** [comment]
Please reopen if this still repros post the fix on the latest version of CLI. Thanks
