### ISSUE TITLE
msrestazure.azure_exceptions.CloudError: Tunneling is disabled

### ISSUE THREAD

**Issue by zomby1** [Azure/azure-cli#20735]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8074, in _start_tunnel
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 182, in start_server
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 117, in _listen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token

msrestazure.azure_exceptions.CloudError: Tunneling is disabled

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network bastion rdp --name "bxadVNET-bastion" --resource-group "binxAD" --target-resource-id "/subscriptions/80e3e9fe-f984-48fe-ad26-223b356d8632/resourceGroups/binxClients/providers/Microsoft.Compute/virtualMachines/AZWS90"`

## Expected Behavior
Connect via RDP

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Adding @kairu-ms to help.

**Comment by KentNordstrom** [comment]
Is this not the expected result if Bastion is not enabled for Native client support?
![image](https://user-images.githubusercontent.com/12670764/146524657-feb30c34-177c-44a1-af7c-db3629443c6e.png)

**Comment by bpasham** [comment]
I am still getting the same error after enabling Native client support on Bastion as well..

<img width="290" alt="image" src="https://user-images.githubusercontent.com/16566076/148389560-d1f2e7bd-0c62-43ac-ade2-2397bc1c3557.png">

**Comment by yonzhan** [comment]
route to service team

**Comment by seetharamanR** [comment]
Any Update on the above, I am getting the same problem
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8089, in _start_tunnel
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 182, in start_server
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 117, in _listen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
msrestazure.azure_exceptions.CloudError: Unexpected internal error

**Comment by AndrewRobie** [comment]
Hi @bpasham, @seetharamanR, & @dgaspar, I'm looking into this and haven't been able to recreate the scenario yet. Are you still seeing the same behavior or able to reproduce it? If so, could you provide what region you're in and what type of VM you're connecting to?

**Comment by brianlillyoir** [comment]
> I've noticed that I changed my Bastion resource from `Basic` to `Standard` and checked the [X] preview feature flag and saved both changes in a same operation. But that combined action might not be working well..
> 
> So what I did now was to turn off the Preview flag and then turn it on again (IT Crowd way) and the "Tunneling is disabled" issue went away!

I had this exact issue. I disabled and reenabled the native client support feature and this resolved my "Tunneling is disabled" error. Thank you!

**Comment by nSilberg** [comment]
> > I've noticed that I changed my Bastion resource from `Basic` to `Standard` and checked the [X] preview feature flag and saved both changes in a same operation. But that combined action might not be working well..
> > So what I did now was to turn off the Preview flag and then turn it on again (IT Crowd way) and the "Tunneling is disabled" issue went away!
> 
> I had this exact issue. I disabled and reenabled the native client support feature and this resolved my "Tunneling is disabled" error. Thank you!

Same. First it didnt work but found some patience and waited the 10 minutes it took to disable. Tip: keep an eye on the activity log and wait for the job to complete successful before trying to enable the feature again.

**Comment by mateialexandru** [comment]
Please add proper error messaging about the SKU requirement, instead of a generic message.

**Comment by jghal** [comment]
@AndrewRobie  I am still seeing this issue. I had an old (more than a year ago) Bastion instance deployed with Basic SKU via Terraform, and just updated it in-place to Standard with tunneling enabled. When I look in the Azure portal, _Native client support_ is enabled and it doesn't say it's in preview. But the CLI is still showing this error that tunneling is disabled. I confirmed I have the latest version of CLI installed. My assigned role doesn't allow me to make configuration changes, so I can't simply uncheck/check the option in the portal as others have done. In trying to do that via CLI with the role that Terraform uses, there's no [update subcommand](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest).

**Comment by AndrewRobie** [comment]
@jghal I can definitely discuss looking into this next week with the team. Are you able to provide some information on the VM/region in case we need to take a look at it? If it's something you're unable to share in a public forum, feel free to message me directly.

**Comment by jghal** [comment]
I'm happy to share what I can. Meantime I'll try running our Terraform pipeline to disable and then later re-enable tunneling and see if that works.

**Comment by jghal** [comment]
Disabling and re-enabling the tunneling option with the Terraform pipeline worked.

**Comment by AndrewRobie** [comment]
Another one of the devs is looking into it. Will update this once we have news.

**Comment by danielcgonzalez** [comment]
same problem here

    "enableFileCopy": true,
    "enableIpConnect": false,
    "enableShareableLink": false,
    "enableTunneling": true,

but 

msrestazure.azure_exceptions.CloudError: Tunneling is disabled

**Comment by AnvitaDineshRao** [comment]
Hi @danielcgonzalez , I'm looking into this and haven't been able to recreate the scenario yet.  I'd really appreciate if you could provide some information/steps on recreating it.
Did you enable Native client feature from Portal? Also , Were there multiple operations done simultaneously ? For instance updating Sku and enabling features?

**Comment by danielcgonzalez** [comment]
> Hi @danielcgonzalez , I'm looking into this and haven't been able to recreate the scenario yet. I'd really appreciate if you could provide some information/steps on recreating it. Did you enable Native client feature from Portal? Also , Were there multiple operations done simultaneously ? For instance updating Sku and enabling features?

I didn't enable it, don't know how to reproduce it.
Last time we enabled it, did it in two steps, changed license and then enabled, and worked without issues.
Later my partner enabled it through terraform in two steps too and both worked fine.

If i get more info i will update you

**Comment by kiashok** [comment]
Any update on this? I see this while trying to rdp to bastion client
