### ISSUE TITLE
Az login issue: json.decoder.JSONDecodeError: Extra data: line 14 column 2 (char 2325)

### ISSUE THREAD

**Issue by superff** [Azure/azure-cli#20749]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Extra data: line 14 column 2 (char 2325)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 147, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1546, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/application.py", line 135, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/application.py", line 581, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 184, in __add
    self.modify(self.CredentialType.ACCESS_TOKEN, at, at)
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 44, in modify
    self._reload_if_necessary()
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 35, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "/usr/local/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 319, in deserialize
    self._cache = json.loads(state) if state else {}
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 14 column 2 (char 2325)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-12.1-x86_64-i386-64bit, Darwin 21.2.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0

Extensions:
azure-devops 0.22.0
storage-preview 0.7.4
scheduled-query 0.4.0

```

**Comment by jiasli** [comment]
Have you manually edited `~/.azure/msal_token_cache.json`?

If not, I think a race condition somehow happened - multiple instances of Azure CLI / MSAL are writing to `~/.azure/msal_token_cache.json` at the same time.

@rayluo, shouldn't MSAL be guarded against concurrent writes?

## Solution

To recover from the broken `msal_token_cache.json`, please run 

```
az account clear
az login
```

**Comment by superff** [comment]
> Have you manually edited `~/.azure/msal_token_cache.json`?
> 
> If not, I think a race condition somehow happened - multiple instances of Azure CLI / MSAL are writing to `~/.azure/msal_token_cache.json` at the same time.
> 
> @rayluo, shouldn't MSAL be guarded against concurrent writes?
> 
> ## Solution
> To recover from the broken `msal_token_cache.json`, please run
> 
> ```
> az account clear
> az login
> ```
非常感谢，我没有手动改json file. it works now

**Comment by rayluo** [comment]
> Have you manually edited `~/.azure/msal_token_cache.json`?
> 
> If not, I think a race condition somehow happened - multiple instances of Azure CLI / MSAL are writing to `~/.azure/msal_token_cache.json` at the same time.
> 
> **@rayluo, shouldn't MSAL be guarded against concurrent writes?**
>
> ## Solution
> 
> To recover from the broken `msal_token_cache.json`, please run
> 
> ```
> az account clear
> az login
> ```

@jiasli, I understand your point. Based on that exception trace, this customer was [using MSAL EX 0.3.0](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/msal_extensions/token_cache.py#L35), which uses lock on both read & write operations already. And, as you can also review MSAL EX's implementation, it seems we already did all we could. In theory, there could be a chance that an uncompleted token cache write being interrupted by Azure CLI process was killed, or the entire VM/computer being shut down abruptly. Let's keep an eye on this kind of report. If it happens more frequently, we will revisit this.

**Comment by jiasli** [comment]
> In theory, there could be a chance that an uncompleted token cache write being interrupted by Azure CLI process was killed, or the entire VM/computer being shut down abruptly. Let's keep an eye on this kind of report. If it happens more frequently, we will revisit this.

I am thinking perhaps **Azure CLI should give a more user-friendly message when corrupted MSAL token cache is encountered**. 

However, there is a big BUT, `msal-extensions` loads token cache **lazily**. This means **any kind of exceptions can happen anywhere**. Here, it happens at `acquire_token_interactive`.

Previously, we had a discussion with Python's developer about [`LazyLoader`](https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader) to improve Azure CLI performance, but that proposal was rejected at the end due to the complexity of error handling.

A better solution I can think of is for `msal-extensions` to expose a public interface to load token cache (https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/86), so that we can catch all kinds of exception at a centralized place.

**Comment by rayluo** [comment]
> I am thinking perhaps **Azure CLI should give a more user-friendly message when corrupted MSAL token cache is encountered**.

What would that user-friendly message be? Asking them to "do `az account clear` and then `az login` again"? If we would be so certain about such a workaround, then we will better just have Azure CLI automatically reset the token cache.

But, again, I'd suggest we do not make any dramatic move, yet. If more similar reports suggest us to reopen this issue/topic, I'll also need to consider whether the "reset token cache" capability should be provided by MSAL and/or MSAL EX.

**Comment by jiasli** [comment]
> If we would be so certain about such a workaround, then we will better just have Azure CLI automatically reset the token cache.

This is certainly doable, but the difficulty here is to catch exceptions that can happen **anywhere**.

**Comment by rayluo** [comment]
> > If we would be so certain about such a workaround, then we will better just have Azure CLI automatically reset the token cache.
> 
> This is certainly doable, but the difficulty here is to catch exceptions that can happen **anywhere**.

That is why I also said "I'll also need to consider whether the "reset token cache" capability should be provided by MSAL and/or MSAL EX". But, "if exception caught, then nuke the cache" is a radical move. We would need enough case reports and evaluation to justify such a move.
