### ISSUE TITLE
`az login` fails: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jhern61** [Azure/azure-cli#20750]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 145, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 127, in login_with_device_code
    flow = self.msal_app.initiate_device_flow(scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 1521, in initiate_device_flow
    flow = self.client.initiate_device_flow(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 328, in initiate_device_flow
    flow = json.loads(resp.text)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0 *

```

**Comment by jiasli** [comment]
Looks like MSAL somehow got empty `str` from `resp.text` and `json.loads` failed:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/45499ff5a4ba1afbb71ed95aa5491f924f39dbba/msal/oauth2cli/oauth2.py#L324-L327

@rayluo, could you help take a look?

**Comment by rayluo** [comment]
> Looks like MSAL somehow got empty `str` from `resp.text` and `json.loads` failed:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/45499ff5a4ba1afbb71ed95aa5491f924f39dbba/msal/oauth2cli/oauth2.py#L324-L327
> 
> ```python
>         resp = self._http_client.post(self.configuration[DAE],
>             data={"client_id": self.client_id, "scope": self._stringify(scope or [])},
>             headers=dict(self.default_headers, **kwargs.pop("headers", {})),
>             **kwargs)
>         flow = json.loads(resp.text)
> ```
> 
> @rayluo, could you help take a look?

If `resp.text` was empty, it is likely the response was malformed, possibly fed by a proxy while the underlying connection times out... but, what I just mentioned is just a hypothesis.

When Azure CLI provides those auto-generated report, does it give user a chance to re-run the command and see if the error persists and do some basic troubleshooting? There would be no point to report a transient network error.
