### ISSUE TITLE
azure login issue: RuntimeError: 0. The ID token is not yet valid. Current epoch = 1639932228.

### ISSUE THREAD

**Issue by ahm798** [Azure/azure-cli#20778]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1639932228.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/7f3a6ceb-c511-477b-a21a-ea83ceae53d8/v2.0",
  "iat": 1639939130,
  "nbf": 1639939130,
  "exp": 1639943030,
  "aio": "AVQAq/8TAAAAYsnILJ3dlA0OeASi8Ho/o6KXiGr6ILKPMeHC5ito4c+1xDVXW2ACDq+M0glih2b12rv7s87mQ1aZ8EMe/6LSlQBZE/Nav9AndKAAkSptPD8=",
  "name": "\u0627\u062d\u0645\u062f \u0639\u0628\u062f \u0627\u0644\u0648\u0647\u0627\u0628 \u0627\u0644\u0645\u0644\u064a\u062c\u0649 \u0627\u0644\u0633\u064a\u062f \u062e\u0644\u064a\u0644",
  "nonce": "3c1378078f09b331d6f2303751c4c69cce309452cda35d220f1ba86fb6c605f0",
  "oid": "e700cf3f-f639-4ae5-b545-b344b47bb768",
  "preferred_username": "AHMED.ALMELEGY617@el-eng.menofia.edu.eg",
  "puid": "1003BFFD9F046A9C",
  "rh": "0.ATkA62w6fxHFe0eiGuqDzq5T2JV3sATbjRpGu-4C-eG_e0Y5AJI.",
  "sub": "lpL4lCbd45D_IEG8r_LFMNLzAu0cudfQ3Ew9Fwirt3I",
  "tid": "7f3a6ceb-c511-477b-a21a-ea83ceae53d8",
  "uti": "FArHWAuoHUWFtu_CVVonAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 147, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1639932228.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/7f3a6ceb-c511-477b-a21a-ea83ceae53d8/v2.0",
  "iat": 1639939130,
  "nbf": 1639939130,
  "exp": 1639943030,
  "aio": "AVQAq/8TAAAAYsnILJ3dlA0OeASi8Ho/o6KXiGr6ILKPMeHC5ito4c+1xDVXW2ACDq+M0glih2b12rv7s87mQ1aZ8EMe/6LSlQBZE/Nav9AndKAAkSptPD8=",
  "name": "\u0627\u062d\u0645\u062f \u0639\u0628\u062f \u0627\u0644\u0648\u0647\u0627\u0628 \u0627\u0644\u0645\u0644\u064a\u062c\u0649 \u0627\u0644\u0633\u064a\u062f \u062e\u0644\u064a\u0644",
  "nonce": "3c1378078f09b331d6f2303751c4c69cce309452cda35d220f1ba86fb6c605f0",
  "oid": "e700cf3f-f639-4ae5-b545-b344b47bb768",
  "preferred_username": "AHMED.ALMELEGY617@el-eng.menofia.edu.eg",
  "puid": "1003BFFD9F046A9C",
  "rh": "0.ATkA62w6fxHFe0eiGuqDzq5T2JV3sATbjRpGu-4C-eG_e0Y5AJI.",
  "sub": "lpL4lCbd45D_IEG8r_LFMNLzAu0cudfQ3Ew9Fwirt3I",
  "tid": "7f3a6ceb-c511-477b-a21a-ea83ceae53d8",
  "uti": "FArHWAuoHUWFtu_CVVonAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20388#issuecomment-987770547
