### ISSUE TITLE
`az account get-access-token` fails with `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` when using identity login

### ISSUE THREAD

**Issue by jgc128** [Azure/azure-cli#20773]
## Describe the bug

`az account get-access-token` fails with `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` if I use identity login (`az login --identity`). If I use `az login --use-device-code`, the same command works fine.

I am running these commands from a terminal on an azureml compute instance created from AzureML (AzureML Studio -> Compute -> Compute Instances).

**Command Name**
`az account get-access-token`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/anaconda/envs/quid/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 74, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 371, in get_raw_token
    msi_creds = MsiAccountTypes.msi_auth_factory(identity_type, identity_id, resource)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 722, in msi_auth_factory
    return MSIAuthenticationWrapper(resource=resource)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/anaconda/envs/quid/lib/python3.9/site-packages/azure/cli/core/auth/adal_authentication.py", line 47, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/anaconda/envs/quid/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 596, in set_token
    self.scheme, _, self.token = get_msi_token_webapp(self.resource, self.msi_conf)
  File "/anaconda/envs/quid/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 548, in get_msi_token_webapp
    token_entry = result.json()
  File "/anaconda/envs/quid/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/anaconda/envs/quid/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/anaconda/envs/quid/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/envs/quid/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --identity`
- `az account get-access-token --output {} --resource {} --debug`

## Expected Behavior
Access token is obtained

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-glibc2.27, Ubuntu 18.04.5 LTS
Python 3.9.7
Installer: PIP

azure-cli 2.30.0 *

Extensions:
ml 2.0.3

```
## Additional Context

Seems like `result.text` is an empty string (/anaconda/envs/quid/lib/python3.9/site-packages/msrestazure/azure_active_directory.py, around line 548), which makes `err` an empty string, which makes the `if err:` fail.

**Comment by jiasli** [comment]
@azureml-github, where is the document for AzureML's managed identity? Which protocol it follows? Like the [VM version](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token), or [App Service version](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity)? 

Then I would suggest to directly get an access token with `curl` and see what the response looks like.

**Comment by luigiw** [comment]
@jgc128 Is this still an active issue?
