### ISSUE TITLE
AZ Kubernetes Services Installation command failed with an unexpected error.

### ISSUE THREAD

**Issue by aqiftekhar** [Azure/azure-cli#20785]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
IncompleteRead(7948864 bytes read, 64108590 more expected)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 360, in k8s_install_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 481, in k8s_install_kubelogin
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 311, in _urlretrieve
  File "http\client.py", line 468, in read
  File "http\client.py", line 611, in _safe_read
http.client.IncompleteRead: IncompleteRead(7948864 bytes read, 64108590 more expected)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Could be related to https://github.com/Azure/azure-sdk-for-python/pull/20888.

**Comment by phealy** [comment]
This suggests that the download failed. When you run the command, it should output some log data, like so:

```shell
C:\Users\pahealy>az aks install-cli
Downloading client to "C:\Users\pahealy\.azure-kubectl\kubectl.exe" from "https://storage.googleapis.com/kubernetes-release/release/v1.23.1/bin/windows/amd64/kubectl.exe"
Please add "C:\Users\pahealy\.azure-kubectl" to your search PATH so the `kubectl.exe` can be found. 2 options:
    1. Run "set PATH=%PATH%;C:\Users\pahealy\.azure-kubectl" or "$env:path += 'C:\Users\pahealy\.azure-kubectl'" for PowerShell. This is good for the current command session.
    2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window. You only need to do it once
Downloading client to "C:\Users\pahealy\AppData\Local\Temp\tmpit1fyqgp\kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.10/kubelogin.zip"
Please add "C:\Users\pahealy\.azure-kubelogin" to your search PATH so the `kubelogin.exe` can be found. 2 options:
    1. Run "set PATH=%PATH%;C:\Users\pahealy\.azure-kubelogin" or "$env:path += 'C:\Users\pahealy\.azure-kubelogin'" for PowerShell. This is good for the current command session.
    2. Update system PATH environment variable by following "Control Panel->System->Advanced->Environment Variables", and re-open the command window. You only need to do it once
```

Note the two URLs in the output - in my case, they're:
- https://storage.googleapis.com/kubernetes-release/release/v1.23.1/bin/windows/amd64/kubectl.exe
- https://github.com/Azure/kubelogin/releases/download/v0.0.10/kubelogin.zip

Can you please try downloading from the two URLs it outputs **on your machine**, in your browser, and see if the download succeeds?

**Comment by navba-MSFT** [comment]
@aqiftekhar Apologies for the late reply. Could you please let us know if you had a chance to follow the action plan suggested by @phealy ? Please let me know if you are still facing this issue. Awaiting you reply.
