### ISSUE TITLE
Command failure for `az webapp log tail` on Apple MacBook Pro M1 Max

### ISSUE THREAD

**Issue by gvt** [Azure/azure-cli#20793]
## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2393, in get_streaming_log
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2060, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail --resource-group {} --name {} --slot {} --subscription {}`

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by panchagnula** [comment]
@gvt don't have M1 Max Pro - but don't repro this on my Intern Mac book pro. Could you please try this on cloud shell bash terminal of portal & let me know if you repro the same behavior? See aka.ms/cloudshell on how to use this. Thanks!

**Comment by zhoxing-ms** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/20489
