### ISSUE TITLE
az login failure: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by mnikser** [Azure/azure-cli#20797]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f05d9822630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f05d9822630>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib64/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f05d9822630>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 140, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 98, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 1467, in __init__
    client_id, client_credential=None, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 440, in __init__
    self.http_client, validate_authority=validate_authority)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/authority.py", line 85, in __init__
    self.http_client)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/authority.py", line 142, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f05d9822630>: Failed to establish a new connection: [Errno -2] Name or service not known',))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: RPM

azure-cli 2.31.0

Extensions:
azure-devops 0.18.0

```
## Additional Context
Please note at the same time general DNS lookup works on my Linux VM and I can resolve login.microsoft.com. Network connection is fine:
dig login.microsoftonline.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.4 <<>> login.microsoftonline.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20880
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;login.microsoftonline.com.	IN	A

;; ANSWER SECTION:
login.microsoftonline.com. 298	IN	CNAME	ak.privatelink.msidentity.com.
ak.privatelink.msidentity.com. 146 IN	CNAME	www.tm.ak.prd.aadg.akadns.net.
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.20
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.21
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.22
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.23
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.7.35
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.12
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.13
www.tm.ak.prd.aadg.akadns.net. 300 IN	A	40.126.28.14

;; Query time: 47 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Dec 21 15:12:53 EST 2021
;; MSG SIZE  rcvd: 543

**Comment by jiasli** [comment]
> Please note at the same time general DNS lookup works on my Linux VM and I can resolve login.microsoft.com. Network connection is fine:

This is weird. Could you test if you can directly reach `login.microsoftonline.com` with Python?

```
python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

**Comment by bathsundeep** [comment]
I am facing this issue trying to do a service principal login via az cli from a new kubernetes node. Pods on my other k8s nodes use the same login mechanism and work fine, so I think the error has to do with this new node's setup but am not sure.

> 
> This is weird. Could you test if you can directly reach `login.microsoftonline.com` with Python?
> 
> ```
> python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
> ```

This still doesnt work for me, gives me the same error as before
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb9aa35ad30>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by jiasli** [comment]
@bathsundeep, you may want to check your DNS settings and make `https://login.microsoftonline.com/` reachable.
