### ISSUE TITLE
az webapp deployment github-actions add fail with unexpected error

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/azure-cli#20808]
## Describe the bug
It seems to creating file start with slash `/.github/workflows/main_toshida-gha-webapp2.yml`

**Command Name**
`az webapp deployment github-actions add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
422 {"message": "path cannot start with a slash", "errors": [{"resource": "Commit", "field": "path", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4717, in add_github_actions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Repository.py", line 1789, in get_contents
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Requester.py", line 353, in requestJsonAndCheck
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Requester.py", line 378, in __check
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4744, in add_github_actions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Repository.py", line 2090, in create_file
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Requester.py", line 353, in requestJsonAndCheck
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\github/Requester.py", line 378, in __check
github.GithubException.GithubException: 422 {"message": "path cannot start with a slash", "errors": [{"resource": "Commit", "field": "path", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment github-actions add --repo {} -g {} -n {} --token {} -b {} --verbose`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by ramya894** [comment]
Great, please add comment if you still face the issue

**Comment by georgeOsdDev** [comment]
Yes it still happen.
I can use workaround what I commented on https://github.com/Azure/azure-cli/issues/20808#issuecomment-999480618
Please add permanent fix.

**Comment by panchagnula** [comment]
@calvinsID Can you take a look at this change.

**Comment by panchagnula** [comment]
@calvinsID / @StrawnSC is this fixed? who is working on this fix, if this is not?

**Comment by calvinsID** [comment]
This looks to be fixed in the `add` command, just made PR for the `remove` command
