### ISSUE TITLE
Error when trying to add an export policy to a NetappFiles Volume - AttributeError: 'NoneType' object has no attribute 'rules'

### ISSUE THREAD

**Issue by pjnroll** [Azure/azure-cli#20819]
When I first try the command, I was using this version of az-cli
```
{
  "azure-cli": "2.14.1",
  "azure-cli-core": "2.14.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

Then I have upgraded to the last version
```
{
  "azure-cli": "2.31.0",
  "azure-cli-core": "2.31.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
but nothing has changed

## Describe the bug

**Command Name**
`az netappfiles volume export-policy add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rules'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/netappfiles/_exception_handler.py", line 18, in netappfiles_exception_handler
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 200, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/netappfiles/custom.py", line 301, in add_export_policy_rule
    for rule in instance.export_policy.rules:
AttributeError: 'NoneType' object has no attribute 'rules'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I want to add an export policy to allow all clients to connect to this volume using the NFSv3 protocol (the same used when I created the volume)
- `az netappfiles volume export-policy add -g resourcegroup --account-name accountname --pool-name poolname --name volumename --allowed-clients 0.0.0.0 --rule-index 1 --unix-read-only false --unix-read-write true --cifs false --nfsv3 true --nfsv41 false`

I also tried with ``` --allowed-clients "0.0.0.0" ``` and ``` --allowed-clients "0.0.0.0/0" ``` but no lucky

## Environment Summary
```
Linux-4.18.0-305.17.1.el8_4.x86_64-x86_64-with-redhat-8.3-Ootpa, Red Hat Enterprise Linux 8.3 (Ootpa)
Python 3.6.8
Installer: RPM

azure-cli 2.31.0

```

**Comment by Arsamin-info** [comment]
#20818 #20809 #20796 #20815 #20796

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@pjnroll Apologies for the late reply. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of AzCLI and let us know if you are still running into the same issue ? Awaiting your reply.
