### ISSUE TITLE
`az acr login` failed with an unexpected error after `az upgrade`

### ISSUE THREAD

**Issue by msowji** [Azure/azure-cli#20840]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
username must be specified, got None
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/custom.py", line 244, in acr_login
    login_server, _, password = get_login_credentials(
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 411, in get_login_credentials
    return _get_credentials(cmd,
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 310, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 106, in get_registry_by_name
    resource_group_name = get_resource_group_name_by_registry_name(
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 85, in get_resource_group_name_by_registry_name
    arm_resource = _arm_get_resource_by_name(
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 40, in _arm_get_resource_by_name
    result = get_resources_in_subscription(cli_ctx, resource_type)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/parameters.py", line 136, in get_resources_in_subscription
    rcf = get_mgmt_service_client(cli_ctx, ResourceType.MGMT_RESOURCE_RESOURCES)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 212, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id, resource=resource,
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 335, in get_login_credentials
    credential = self._create_credential(account, client_id=client_id)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 593, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 209, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 42, in __init__
    assert username, "username must be specified, got {!r}".format(username)
AssertionError: username must be specified, got None

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {} --expose-token --output {} --query {}`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit, Darwin 21.1.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
@yonzhan the error is from msal auth library.

  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 42, in __init__
    assert username, "username must be specified, got {!r}".format(username)
AssertionError: username must be specified, got None

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/20244. 

Could you share the content of `~/.azure/azureProfile.json`? Do you have any other program that edits `~/.azure/azureProfile.json`? Please be aware that editing this file is not supported.
