### ISSUE TITLE
`az keyvault key create` fails: Session.request() got an unexpected keyword argument 'tenant_id'

### ISSUE THREAD

**Issue by alxndr13** [Azure/azure-cli#20856]
**Describe the bug**
When creating a new Azure Key Vault Key using `az` cli, i get the following error:

```bash
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 138, in keyvault_command_handler
    return keyvault_exception_handler(self.command_loader, ex)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 51, in keyvault_exception_handler
    raise CLIError(ex)
knack.util.CLIError: Can't find token from MSAL cache.
```

**To Reproduce**

- Create a key vault
- use the following command to create a key:

```bash
az keyvault key create --name "test" \
  --protection software \
  --ops encrypt decrypt \
  --expires "$date_in_two_years" \
  --vault-name "test-vault" > /dev/null
```

**Expected behavior**
A key gets created. 

**Environment summary**
Linux-5.10.84-1-MANJARO-x86_64-with-glibc2.33, Manjaro Linux
Python 3.9.9
azure-cli 2.31.0

Installation method: `interactive script`

**Additional context**
Works before version `2.30.0` (before the Azure CLI migration from ADAL to MSAL)

### Workaround
For anyone from the interwebz having the same problem, i use a workaround as of now.

Start a container and mount files inside:
`docker run -ti mcr.microsoft.com/azure-cli:2.29.2 bash`
(Any version before `2.30.0` works.)

- `az login`
- Set appropiate subscription
- run the command above
- works

**Comment by yonzhan** [comment]
KeyVault

**Comment by jiasli** [comment]
Running the command with `--debug` gives more info:

```
> az keyvault key create --name "key1" --protection software --ops encrypt decrypt --vault-name "jlkv1"

msal.application: Refresh token failed
Traceback (most recent call last):
  File "/root/azcli/lib/python3.10/site-packages/msal/application.py", line 1203, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    result = _clean_up(self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
  File "/root/azcli/lib/python3.10/site-packages/msal/application.py", line 1240, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
  File "/root/azcli/lib/python3.10/site-packages/msal/application.py", line 1287, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
  File "/root/azcli/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 831, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
  File "/root/azcli/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 263, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
  File "/root/azcli/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/root/azcli/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 772, in _obtain_token
    resp = super(Client, self)._obtain_token(
  File "/root/azcli/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 235, in _obtain_token
    resp = (post or self._http_client.post)(
  File "/root/azcli/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/root/azcli/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/root/azcli/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
TypeError: Session.request() got an unexpected keyword argument 'tenant_id'

...
  File "/root/azcli/lib/python3.10/site-packages/azure/cli/core/auth/util.py", line 125, in check_result
    raise AuthenticationError("Can't find token from MSAL cache.",
azure.cli.core.azclierror.AuthenticationError: Can't find token from MSAL cache.

During handling of the above exception, another exception occurred:
...
  File "/root/azcli/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 51, in keyvault_exception_handler
    raise CLIError(ex)
knack.util.CLIError: Can't find token from MSAL cache.
```

The inner exception is

```
TypeError: Session.request() got an unexpected keyword argument 'tenant_id'
```

but MSAL hides it with

```
msal.application: Refresh token failed
```

This is another instance showing MSAL should expose the inner exception:

- https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/431
- https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/434

Any idea when we will release a new MSAL with the above PR? @rayluo

**Comment by jiasli** [comment]
As for the original issue, `--debug` log also shows

```
urllib3.connectionpool: https://jlkv1.vault.azure.net:443 "POST /keys/key1/create?api-version=7.3-preview HTTP/1.1" 401 97
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://vault.azure.net/.default',), kwargs={'tenant_id': '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a'}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://vault.azure.net/.default',), kwargs={'tenant_id': '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a'}
```

Apparently, the extra `tenant_id` field is corrupting `UserCredential` and MSAL, because `azure-keyvault-keys==4.5.0b5` calls `get_token` with `tenant_id` which is not supported by `UserCredential` and MSAL.

https://github.com/Azure/azure-sdk-for-python/blob/azure-keyvault-keys_4.5.0b5/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py#L76

```py
                self._token = self._credential.get_token(scope, tenant_id=challenge.tenant_id)
```

`requirements.txt` contains:

https://github.com/Azure/azure-cli/blob/1c11174622b1cb2427b7e2417ab5e80b46b4f9ed/src/azure-cli/requirements.py3.windows.txt#L17

but Azure CLI doesn't pin the version of `azure-keyvault-keys` in `setup.py`:

https://github.com/Azure/azure-cli/blob/1c11174622b1cb2427b7e2417ab5e80b46b4f9ed/src/azure-cli/setup.py#L63

This causes `azure-keyvault-keys==4.5.0b5` being installed.

See https://www.python.org/dev/peps/pep-0440/#compatible-release

> If a pre-release, post-release or developmental release is named in a compatible release clause as V.N.suffix, then the suffix is ignored when determining the required prefix match.
