### ISSUE TITLE
AttributeError when attempting to create service principal

### ISSUE THREAD

**Issue by therealrooster** [Azure/azure-cli#20860]
**Environment:** 
WSL (kali_rolling 2021.4),  az-cli 2.31.0 (core 2.31.0, telemtry 1.0.6, azure-devops 0.22.0), python3 v3.9.9, installed az-cli using 'stretch' AZ_REPO value

- used: az login to successfully login
- set environment variables for $YOURSP, $TF_VAR_subscription_id, and $AZ_resource_group

`az ad sp create-for-rbac --name "$YOURSP" --role Contributor --scope /subscriptions/$TF_VAR_subscription_id/resourceGroups/$AZ_resource_group`

error received:

`ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'RoleAssignmentsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 1482, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 191, in _create_role_assignment
    assignments_client.config.subscription_id)
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'
To open an issue, please run: 'az feedback'`

I have tried simple test `az ad create-for-rbac` commands, all with the same AttributeError.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`dist-packages` shows this is not the official Azure CLI, please see 

- https://github.com/Azure/azure-cli/issues/19640
- https://github.com/Azure/azure-cli/issues/19369

**Comment by therealrooster** [comment]
I followed this: 
[https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions](url)

and set AZ_REPO to stretch for install.
