### ISSUE TITLE
[Help] Running -h on commands that don't exist can trigger an exception

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2086]
I accidentally typed 'az network dns record update-soa a -h' (with the extra 'a' parameter on the command line)

Exception!

Extra help param --email
Traceback (most recent call last):
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\application.py", line 129, in execute
    args = self.parser.parse_args(argv)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 1020, in __call__
    parser.print_help()
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\parser.py", line 167, in format_help
    is_group)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\_help.py", line 24, in show_help
    help_file.load(parser)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\_help.py", line 276, in load
    self._load_from_file()
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\_help.py", line 281, in _load_from_file
    self._load_from_data(file_data)
  File "C:\Users\jonatul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\azure\cli\core\_help.py", line 356, in _load_from_data
    raise HelpAuthoringException('Extra help param {0}'.format(extra_param['name']))
azure.cli.core._help.HelpAuthoringException: Extra help param --email

**Comment by tjprescott** [comment]
The key here is that you enter a genuine command followed by another positional arg (as if it were part of a command that doesn't exist) and then -h

**Comment by jtuliani** [comment]
Sure. It was definitely an invalid command line. But it was an honest slip (hence customers may do the same) and the error experience doesn't inspire confidence...need a nice clean error saying what I did wrong.

**Comment by tjprescott** [comment]
I agree. I was just summarizing how to recreate the issue since this is applies to the entire CLI not just DNS. :)

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
