### ISSUE TITLE
az webapp up gets index out of range exception

### ISSUE THREAD

**Issue by LuisTovar0** [Azure/azure-cli#20885]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 3959, in webapp_up
    plan=plan)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 385, in get_plan_to_use
    return _determine_if_default_plan_to_use(cmd, _default_asp, resource_group_name, loc, sku, create_rg)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 404, in _determine_if_default_plan_to_use
    _asp_generic = plan_name[:-len(plan_name.split("_")[4])]
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `cd` into a Node.js application directory
- `az webapp up --name <web-app-resource-name> --logs --launch-browser`

## Expected Behavior

A Web App resource is created in my Azure account. I have never run this before, so I don't know what the CLI output should look like.

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.31.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

```

## Additional context

I was following [this documentation](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/tutorial-vscode-azure-cli-node/tutorial-vscode-azure-cli-node-03) to deploy a Node.js app to Azure. If this bug can't be fixed, could I get an alternative for learning how to do it?

**Comment by yonzhan** [comment]
route to service team

**Comment by StrawnSC** [comment]
Hi @LuisTovar0, sorry you're running into this bug. This issue was fixed by https://github.com/Azure/azure-cli/pull/20760, which is in the latest version of the CLI. Could you try upgrading your CLI and re-running the command?

**Comment by StrawnSC** [comment]
Closing this because the fix has been released. Please reopen if you're still seeing the issue after upgrading your CLI version
