### ISSUE TITLE
unable to run cmds 

### ISSUE THREAD

**Issue by suresh8771** [Azure/azure-cli#20907]
## Describe the bug

**Command Name**
`az account list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'3'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 236, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 166, in get_formatter
KeyError: '3'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account list`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
account 0.2.1
alias 0.5.2
resource-graph 2.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by suresh8771** [comment]
1. did tried upgrade not helped 
 2.  uninstalled the whole CLI and re-installed using MSI
 3. getting similar error as reported

**Comment by yonzhan** [comment]
@jiasli for awareness
