### ISSUE TITLE
az aks get-credentials error

### ISSUE THREAD

**Issue by KISMIDEV** [Azure/azure-cli#20915]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
dlopen(/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/_bcrypt.abi3.so, 0x0002): tried: '/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/_bcrypt.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_bcrypt.abi3.so' (no such file), '/usr/lib/_bcrypt.abi3.so' (no such file)
Traceback (most recent call last):
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/command_modules/acs/custom.py", line 46, in <module>
    from azure.cli.command_modules.acs import acs_client, proxy
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/azure/cli/command_modules/acs/acs_client.py", line 13, in <module>
    import paramiko
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ImportError: dlopen(/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/_bcrypt.abi3.so, 0x0002): tried: '/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/_bcrypt.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_bcrypt.abi3.so' (no such file), '/usr/lib/_bcrypt.abi3.so' (no such file)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit, Darwin 21.1.0
Python 3.8.2
Installer: PIP

azure-cli 2.32.0

Extensions:
account 0.2.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by phealy** [comment]
You somehow have an x86_64 Python install on an ARM based machine. I'm guessing maybe you just got an M1 MacBook and copied your home directory over? Please fix your Python installation and this should start working again. If you still experience the issue after repairing Python, please let us know.

```
tried: '/Users/jpyoon/Library/Python/3.8/lib/python/site-packages/bcrypt/_bcrypt.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```
