### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback: '3'

### ISSUE THREAD

**Issue by suresh8771** [Azure/azure-cli#20911]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'3'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 236, in invoke
    formatter = self.output.get_formatter(output_type)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 166, in get_formatter
    return OutputProducer._FORMAT_DICT[format_type]
KeyError: '3'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.2 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
account 0.2.1
alias 0.5.2
resource-graph 2.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is because you have config `core.output` set as `3` which is invalid. Please unset this invalid config:

```
az config unset core.output
```

See https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration

**Comment by suresh8771** [comment]
thanks for the support the issue is resolved. 
    On Friday, 19 August, 2022 at 07:32:21 pm IST, msftbot[bot] ***@***.***> wrote:  
 
 


Hi, we're sending this friendly reminder because we haven't heard back from you in a while. We need more information about this issue to help address it. Please be sure to give us your input within the next 7 days. If we don't hear back from you within 14 days of this comment the issue will be automatically closed. Thank you!

**Comment by suresh8771** [comment]
@jiasli thanks  it solved my issue.
