### ISSUE TITLE
How to solve this problem when run az webapp config appsettings? Too much source code there.

### ISSUE THREAD

**Issue by lijianzhi01** [Azure/azure-cli#20926]
## Describe the bug

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 506, in shell_safe_json_parse
  File "json\__init__.py", line 370, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 260, in update_app_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 531, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: @local.settings.json
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 271, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- az webapp config container set -g EasyCosmic-RG -n easycosmic --docker-custom-image-name easycosmicbackend.azurecr.io/easycosmic:latest
- az webapp config appsettings set -g EasyCosmic-RG -n easycosmic --settings "@local.settings.json"

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@lijianzhi01 looking at the trace this is the issue "InvalidArgumentValueError: Failed to parse JSON: @local.settings.json"

**Comment by lijianzhi01** [comment]
Thanks @panchagnula  It's local.settings.json issue. That file should be created manually.

**Comment by panchagnula** [comment]
> Thanks @panchagnula It's local.settings.json issue. That file should be created manually.

Correct this file should exist & should have the JSON object (Key-value pair) of the appsettings you'd like to set with the command.
