### ISSUE TITLE
az cli commands are not working 

### ISSUE THREAD

**Issue by ssbandari1** [Azure/azure-cli#20930]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/home/sabanda/.local/lib/python3.8/site-packages/azure/mgmt/core/policies/__init__.py)
Traceback (most recent call last):
  File "/home/sabanda/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/sabanda/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/home/sabanda/.local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/sabanda/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/sabanda/.local/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/sabanda/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/sabanda/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sabanda/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 132, in <module>
    from .vendored_sdks.azure_mgmt_preview_aks.v2021_11_01_preview.models import (
  File "/home/sabanda/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2021_11_01_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/home/sabanda/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2021_11_01_preview/_container_service_client.py", line 16, in <module>
    from ._configuration import ContainerServiceClientConfiguration
  File "/home/sabanda/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2021_11_01_preview/_configuration.py", line 13, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/home/sabanda/.local/lib/python3.8/site-packages/azure/mgmt/core/policies/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.29, Ubuntu 20.04.1 LTS
Python 3.8.5
Installer: PIP

azure-cli 2.32.0

Extensions:
aks-preview 0.5.50
azure-firewall 0.13.0

Dependencies:
msal 1.10.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by phealy** [comment]
This looks like you have an outdated version of `azure-mgmt-core` in your Python install. Please try updating your Azure pip modules to resolve this issue.

If you switch to [installing Azure CLI via one of the better supported methods](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli), Azure CLI will bring along its own Python virtual environment that has all the correct module versions.

Please let me know if this resolves your issue.
