### ISSUE TITLE
Unable to install ml extension in MacOs 12.1

### ISSUE THREAD

**Issue by fer-git** [Azure/azure-cli#20947]
## Describe the bug

I tried to install azure cli v2 ml extension by following the guide [https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli).

**Command Name**
`brew update && brew install azure-cli`
`brew update && brew install python3 && brew upgrade python3`
`brew link --overwrite python3`
Success until here, then the next command throw errors
`az extension add -n ml -y --debug`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.

  creating build/temp.macosx-12-arm64-3.10
  creating build/temp.macosx-12-arm64-3.10/build
  creating build/temp.macosx-12-arm64-3.10/build/temp.macosx-12-arm64-3.10
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/include -I/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c build/temp.macosx-12-arm64-3.10/_openssl.c -o build/temp.macosx-12-arm64-3.10/build/temp.macosx-12-arm64-3.10/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.macosx-12-arm64-3.10/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
  #include <openssl/opensslv.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      =============================DEBUG ASSISTANCE=============================

  error: command '/usr/bin/clang' failed with exit code 1
  Building wheel for cryptography (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 374, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Removed build tracker: '/private/var/folders/t1/xd5ry9hd47b70znf1bq_zhyh0000gn/T/pip-req-tracker-0ul6f193'

cli.azure.cli.core.extension.operations: Command '['/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/username/.azure/cliextensions/ml', '/var/folders/t1/xd5ry9hd47b70znf1bq_zhyh0000gn/T/tmp37_bz345/ml-2.0.3-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /Users/username/.azure/cliextensions/ml
cli.azure.cli.core.util: Failed to delete '/Users/username/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/username/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/username/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/username/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/username/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/username/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/username/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/username/.azure/cliextensions/ml'. You may try to delete it manually.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 339, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az extension add -n ml -y --debug`

## Expected Behavior
Installation ml extension is successful

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.32.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by luigiw** [comment]
@fer-git Hello, thx for trying out the ml extension. The ml extension is not tested with Python 3.9+, can you try installing it in a Python 3.8 environment?

**Comment by fer-git** [comment]
Hi @luigiw, thanks for the responding.
I think that is also the culprit of this problem. The issue is how to use Python 3.8 for this specific installation?
I do not even install python 3.10 in my computer, but Azure install it on its own through brew when I try to add ml extension.
This is the guide I follow [Install and set up the CLI (v2)](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli)

**Comment by luigiw** [comment]
I don't think azure cli will install Python for users. It's prob this part of your command did it `brew install python3 && brew upgrade python3`

**Comment by fer-git** [comment]
I remove all python installations and azure-cli by homebrew.
Then I tried to install azure-cli again, by running `brew install azure-cli`.
Here is first few lines:
```
brew install azure-cli
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/manifests/3.10.1
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/ba44b4cfaec4b0996a8fc2b2def6f21371f8c859781b668a30ceb2e6f4bbf3be--python@3.10-3.10.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/blobs/sha256:610ffb
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/9f33296799fb0f3d8dc0e02e5a3f0248cc3f930fecbe9d5484feebad2976e337--python@3.10--3.10.1.arm64_monterey.bottle.tar.gz
```
It will simply target 3.10.

**Comment by luigiw** [comment]
According to this page, azure-cli on MacOS depends on some Homebrew python3.10.

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos

@fer-git will you be able to try manual installation listed here? https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

**Comment by fer-git** [comment]
@luigiw Alright I can install by using the script for linux. But I would say I still cannot install the ml extension through brew method. azure-cli installation requires 3.10 to be installation from brew. Then, ml extension installation requires 3.8 but it will automatically use that 3.10.

**Comment by Misterion777** [comment]
I can confirm, that its not possible to install ml extension through brew method, this issue should not be closed

**Comment by dhoeltgen** [comment]
I get the same result with either
`az extension add -n azure-cli-ml --debug` or
`az extension add -n ml -y --debug `
Please reopen this issue
