### ISSUE TITLE
Az acr commands fail with "API version 2020-11-01-preview does not have operation group 'registries'" - Debian Arm64 az cli version 2.18.0-2 

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-cli#20941]
## Describe the bug

**Command Name**
`az acr list`

**Errors:**
```
API version 2020-11-01-preview does not have operation group 'registries'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 20, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/_container_registry_management_client.py, ln 304, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
ValueError: API version 2020-11-01-preview does not have operation group 'registries'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr list -g {}`

## Environment Summary
```
Linux-5.10.76-linuxkit-aarch64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
@jjgriff93 please try install the latest https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to see if it resolves the issue.

**Comment by toddysm** [comment]
This seems to be very old issue with no activity for the past ~3 years. If no activity is detected, we will close in 30 days.

**Comment by tomasro27** [comment]
Hello @toddysm we are seeing this issue on an AZ CLI Dev Ops Task... although it is happening on windows. Would you recommend opening a new ticket? It is currently blocking our build.

azure-cli                         2.72.0

core                              2.72.0
telemetry                1.1.0.post20250227030620

Extensions:
azure-devops                       1.0.1
ml                                2.19.1

Dependencies:
msal                              1.32.3
azure-mgmt-resource               23.3.0


Python (Windows) 3.9.16 

We started seeing the issue with 2.72.0, so it looks like an incompatibility of packages installed.

```

WARNING: The output will be changed in next breaking change release(2.73.0) scheduled for May 2025. Exit code will be 1 if command fails for docker login.
C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\msal\application.py:204: UserWarning: Please upgrade msal-extensions. Only msal-extensions 1.2+ can work with msal 1.30+
  warnings.warn(
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: API version **2024-11-01-preview** does not have **operation group 'registries'**
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 666, in execute
    raise ex
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 703, in _run_job
    result = cmd_copy(params)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 120, in handler
    return op(**command_args)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\command_modules\acr\custom.py", line 319, in acr_login
    login_server, username, password = get_login_credentials(
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 463, in get_login_credentials
    return _get_credentials(cmd,
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 343, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name, resource_group_name)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\command_modules\acr\_utils.py", line 111, in get_registry_by_name
    client = cf_acr_registries(cli_ctx)
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\cli\command_modules\acr\_client_factory.py", line 25, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\azure\mgmt\containerregistry\_container_registry_management_client.py", line 781, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
**ValueError: API version 2024-11-01-preview does not have operation group 'registries'**
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

##[error]Script failed with exit code: 1
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Python\3.9.16\x64\Scripts\az.bat account clear"
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: You must install dependency by: pip install "msal[broker]>=1.20,<2"
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\msal\broker.py", line 14, in <module>
    import pymsalruntime  # Its API description is available in site-packages/pymsalruntime/PyMsalRuntime.pyi
ModuleNotFoundError: No module named 'pymsalruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.16\x64\lib\site-packages\knack\cli.py", line 231, in invoke
 
```

command is simply "az acr login --name acr_name"

**Comment by tomasro27** [comment]
issue only happens with 2.72.0

**Comment by johnsonshi** [comment]
Closing as this issue only happens with very specific older versions of az cli
