### ISSUE TITLE
Error while running "az aks addon list"

### ISSUE THREAD

**Issue by vgarmash** [Azure/azure-cli#20977]
## Describe the bug

**Command Name**
`az aks addon list`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 553, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 479, in load_arguments
  File "C:\Users\vgarmash\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\vgarmash\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks addon list`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to service team

**Comment by vgarmash** [comment]
After I got that error I found that I had Pyton installed on the system. I have uninstalled it and the AZ script started working properly. I hope this information help to understand the issue.

**Comment by navba-MSFT** [comment]
@vgarmash Apologies for the late reply. Thanks for sharing the steps you had followed to address this issue. I am glad that the issue stands resolved now. Please let me know if we can proceed with closure of this github thread. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vgarmash I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
