### ISSUE TITLE
Support for stdin for 'az storage blob upload' command

### ISSUE THREAD

**Issue by kenorb** [Azure/azure-cli#20980]
**Is your feature request related to a problem? Please describe.**

After running the following command:

```
$ echo foo bar buzz | az storage blob upload --container-name mycontainer -n test.txt -f /dev/stdin
{
  "etag": "\"0x8D...\"",
  "lastModified": "2022-01-13T21:50:19+00:00"
}
```

the blob content is empty.

**Describe the solution you'd like**

Correct content of the file should be uploaded.

**Describe alternatives you've considered**

Using a temporary file.

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can you install storage-blob-preview extension with `az extension add -n storage-blob-preview` and try `az storage blob upload --data`? `--data` can take input string as blob content directly.

**Comment by kenorb** [comment]
> Can you install storage-blob-preview extension with `az extension add -n storage-blob-preview` and try `az storage blob upload --data`? `--data` can take input string as blob content directly.

```
% az storage blob upload -c mycontainer --data "Foo Bar" -n test.txt
...
The command failed with an unexpected error. Here is the traceback:
'>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
...
  File "/usr/local/Cellar/azure-cli/2.25.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/user/.azure/cliextensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 666, in upload_blob
    _adjust_block_blob_size(client, blob_type, length)
  File "/Users/user/.azure/cliextensions/storage-blob-preview/azext_storage_blob_preview/operations/blob.py", line 613, in _adjust_block_blob_size
    if length > 50000 * 4 * 1024 * 1024:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
To open an issue, please run: 'az feedback'
```

**Comment by evelyn-ys** [comment]
Hi @kenorb, Can you explicitly specify `--length`:
```
az storage blob upload -c mycontainer --data "Foo Bar" --length 7 -n test.txt
```

We will fix the extension bug in next vesion, sorry for the inconvenience.

**Comment by evelyn-ys** [comment]
Hi @glanchow, we have supported `--data` in main CLI now, you don't have to install extension any more. Here's an example using stdin input with pipe:
```
echo $data | az storage blob upload --data @- -c mycontainer -n myblob --account-name $accountName
```

**Comment by chribsen** [comment]
Why is passing the length necessary? When working with streams, you might not know the size of the blob in advance.

**Comment by evelyn-ys** [comment]
@chribsen If you use the command directly from main CLI, `--length` is not needed any more. The bug has been fixed in main CLI.

**Comment by WattsInABox** [comment]
This feature technically uploads something but it doesn't seem to be uploading my files correctly. Not sure if we should close this one and then open a new issue but when I do something to the effect of:

```
cat my-textfile.txt | xz | az storage blob upload -c my-channel --data @- --content-type application/x-xz
```

and then re-download the file, the file has:

```
7zXZִF!t/G]&J
```

For the first line and the xz program does not recognize the file. I have tried this with zst and other binary files and I can't seem to get it to upload the file in the correct format. I suspect it has something to do with the handling of binary data since text files appear to work, but I have no way of confirming that.

What should I do?

**Comment by mochja** [comment]
@WattsInABox when pipe is not used, but you use `--data @/path/to/file` data end up in the storage as base64 encoded. I haven't figured out how to get un-mangled data using pipes, but there seems to be similar issue https://github.com/Azure/azure-cli/issues/22810 with az rest.

**Comment by a5ter0id** [comment]
I have the same issue like
https://github.com/Azure/azure-cli/issues/20980#issuecomment-1267449510

It seems that binary stdin does not correctly work with az storage account.

very need to xz and az as a pipe
