### ISSUE TITLE
bug .azure folder mounted from WSL2 creates lock errors with many requests

### ISSUE THREAD

**Issue by NissesSenap** [Azure/azure-cli#20993]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When running terraform inside WSL2 together with a .azure folder mounted inside windows seems like we get file lock issues.
```shell
│ Error: getting authenticated object ID: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: [Errno 2] No such file or directory
│ Traceback (most recent call last):
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 352, in handler
│ client = self.client_factory(self.cli_ctx) if self.client_factory else None
│ TypeError: get_graph_client_signed_in_users() missing 1 required positional argument: '_'
│
│ During handling of the above exception, another exception occurred:
│
│ Traceback (most recent call last):
│ File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
│ cmd_result = self.invocation.execute(args)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
│ raise ex
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
│ results.append(self._run_job(expanded_arg, cmd_copy))
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
│ return cmd_copy.exception_handler(ex)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
│ raise ex
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
│ result = cmd_copy(params)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
│ return self.handler(*args, **kwargs)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 354, in handler
│ client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 89, in get_graph_client_signed_in_users
│ return _graph_client_factory(cli_ctx).signed_in_user
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/_client_factory.py", line 25, in _graph_client_factory
│ resource=cli_ctx.cloud.endpoints.active_directory_graph_resource_id)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 335, in get_login_credentials
│ credential = self._create_credential(account, client_id=client_id)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 588, in _create_credential
│ return identity.get_user_credential(username_or_sp_id)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 182, in get_user_credential
│ return UserCredential(self.client_id, username, **self._msal_app_kwargs)
│ File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/msal_authentication.py", line 41, in __init__
│ accounts = self.get_accounts(username)
│ File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 872, in get_accounts
│ accounts = self._find_msal_accounts(environment=self.authority.instance)
│ File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 912, in _find_msal_accounts
│ query={​​"environment": environment}​​)
│ File "/opt/az/lib/python3.6/site-packages/msal_extensions/token_cache.py", line 53, in find
│ with CrossPlatLock(self._lock_location):
│ File "/opt/az/lib/python3.6/site-packages/msal_extensions/cache_lock.py", line 29, in __enter__
│ file_handle = self._lock.__enter__()
│ File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 199, in __enter__
│ return self.acquire()
│ File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 161, in acquire
│ fh = self._prepare_fh(fh)
│ File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 194, in _prepare_fh
│ fh.truncate(0)
│ FileNotFoundError: [Errno 2] No such file or directory
│ To open an issue, please run: 'az feedback'
│
│ with provider["registry.terraform.io/hashicorp/azuread"],
│ on main.tf line 19, in provider "azuread":
│ 19: provider "azuread" {​​}​​
```

The terraform module that we are using uses both azurerm and azuread. I think the switch between the modules is to quick and WSL2 don't have enough time to release the azure cli json file that it uses.

**To Reproduce**
Run lots of azure cli requests inside of WSL2 with a .azure folder mounted to windows. I don't have a reliable way of creating this issue.

**Expected behavior**
To not get the error.

Have some try logic that makes sure that this doesn't happen. Probably a simple retry to get the lock file will solve the problem to give WSL2/windows time to release the file lock. But I'm just guessing now.

**Environment summary**

**Additional context**

I have tried to explain this issue in our external docs: https://github.com/XenitAB/xenitab.github.io/pull/80

**Workaround*

Found a workaround which is to not to store .azure inside windows.
Assuming that pwd isn't a windows folder.

```
export AZURE_CONFIG_DIR=$(pwd)/.azure
# Store Azure CLI configuration here
[ -d $(pwd)/.azure ] || mkdir $(pwd)/.azure
# login to azure agaiin
az login
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This issue is similar to https://github.com/Azure/azure-cli/issues/20273.

However, this doesn't seem like the latest Azure CLI as the call stack doesn't match the file content of `msal-extensions`:

```py
│ File "/opt/az/lib/python3.6/site-packages/msal_extensions/token_cache.py", line 53, in find
│ with CrossPlatLock(self._lock_location):
```

`token_cache.py` L53 is

https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/a4d95b610a0bb45620c716001a20c85ec05f237e/msal_extensions/token_cache.py#L53

```py
    def _reload_if_necessary(self):
```

The race condition is solved by https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/100 in Azure CLI 2.32.0.

Please check if your have the latest Azure CLI installed.

**Comment by NissesSenap** [comment]
Thanks for quick reply.
@jiasli as written in the issue we are using the 2.32.0 so some issue might still be left.

**Comment by NissesSenap** [comment]
Thanks for your quick reply @jiasli but as written in the issue we are already running 2.32, also asked my colleague to write a few which and ls commands to show that we are using the full path and that is what should have been used when we got this error.

![image](https://user-images.githubusercontent.com/14774899/149729886-83ff9236-6799-4477-ab3c-ce7b9e19dcd2.png)

**Comment by jiasli** [comment]
This is weird, as the file content is indeed wrong. Here is my L53:

```
$ cat /opt/az/lib/python3.6/site-packages/msal_extensions/token_cache.py | sed -n 53p
    def _reload_if_necessary(self):
```

Could you follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt and reinstall?

**Comment by NissesSenap** [comment]
![image](https://user-images.githubusercontent.com/14774899/149912920-75253025-1c89-4d8d-8aac-2c2c4505499e.png)
My colleague have the same output as you.
Currently asking on how he have installed the cli.
But any way I will ask him to reinstall and see if it helps.

**Comment by linus-lysell** [comment]
Hi,

I have now reinstalled az cli. Unfortunately I get same error as before. 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/95033863/149971580-212f3c9e-9eb7-4724-ba8e-886e581fd82a.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/95033863/149971532-32434ebd-839c-41c2-a7a5-62df28651217.png">

**Comment by rayluo** [comment]
> We do see corrupted/outdated files after upgrading with MSI on Windows (#20990), but upgrading with `apt-get` resulting in outdated file is something we saw for the first time. 🤔

Theoretically speaking, I'm told that the packages distributed via each Linux's own channel (i.e. those .deb or .rpm or etc.) could be packed with any specific version that the package builder deem "appropriate".

@jiasli , is there a convenient way to check the packages' version that `az` uses? Could `/opt/az/bin/python3 -m pip list` work?

@NissesSenap, @linus-lysell , can you check the `__version__` in the file `/opt/az/lib/python3.6/site-packages/msal_extensions/__init__.py`?

**Comment by jiasli** [comment]
The `py` file looks correct but the error message shows unmatched content.

Perhaps you can try to remove the Python cache?

```
sudo rm -r /opt/az/lib/python3.6/site-packages/msal_extensions/__pycache__
```

I am not sure why the cache file is not updated as expected though.

> is there a convenient way to check the packages' version that `az` uses? Could `/opt/az/bin/python3 -m pip list` work?

Yes, `/opt/az/bin/python3 -m pip list` will work.

**Comment by jiasli** [comment]
I tried to decompile the `pyc` file on my WSL and the content is also correct:

```py
$ pip3 install uncompyle6

$ uncompyle6 /opt/az/lib/python3.6/site-packages/msal_extensions/__pycache__/token_cache.cpython-36.pyc
...
    def find(self, credential_type, **kwargs):
        retry = 3
        for attempt in range(1, retry + 1):
            try:
                self._reload_if_necessary()
            except Exception:
                if attempt < retry:
                    logger.debug('Unable to load token cache file in No. %d attempt', attempt)
                    time.sleep(0.5)
                else:
                    raise
            else:
                return (super(PersistedTokenCache, self).find)(credential_type, **kwargs)

        return []
```
