### ISSUE TITLE
After upgrading with MSI, Azure CLI's files become corrupted

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20990]
## Symptom

We have seen multiple occurrences that after upgrading with MSI, Azure CLI's file structure or file contents become corrupted, leading to all kinds of failures:

- https://github.com/Azure/azure-cli/issues/20978
- https://github.com/Azure/azure-cli/issues/20379
- https://github.com/Azure/azure-cli/issues/18477
- https://github.com/Azure/azure-cli/issues/17986
- https://github.com/Azure/azure-cli/issues/18172
- https://github.com/Azure/azure-cli/issues/17982
- https://github.com/Azure/azure-cli/issues/19307

## Solution

Please try to re-install Azure CLI:

1. Go to **Control Panel > Uninstall a program** , uninstall **Microsoft Azure CLI** 
2. Delete `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2`
3. [Install the latest Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) from scratch

## TODO

We should contact Windows MSI team to figure out why upgrading with MSI randomly fails.

**Comment by akeijzer11** [comment]
I am always on the latest version and have auto upgrade enabled (az config set auto-upgrade.enable=yes), this downloads the latest MSI file automatically when a newer version is available.

Today i came across this issue while automatically an update was triggered, it took me a while to figure out it was this bug.
The workaround worked.

error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 13, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 19, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/__init__.py", line 9, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/__init__.py", line 4, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/portalocker.py", line 11, in <module>
ImportError: DLL load failed while importing win32file: The specified module could not be found

**Comment by kimjamia** [comment]
This just happened to me now after I updated Az CLI with winget.

**Comment by 2PintChristianN** [comment]
Do we know exactly what is left behind so that we can automate detection, deletion and reinstall?

**Comment by TomasMalecek** [comment]
Is this a duplicate of #32045, which was resolved some 6 hours ago by downgrading pywin32 from 311 to 310? The fix should make it into 2.82.0. There is a nice analysis of the root cause under that issue: https://github.com/Azure/azure-cli/issues/32045#issuecomment-3669161120

**Comment by TomasMalecek** [comment]
It seems there may be other things at play in at least some of the issues. E.g., #17986 removed deprecated pypiwin32 and bumped pywin32. But the workaround that helped was the re-installation of pywin32, which hints that the root cause is the same.
