### ISSUE TITLE
AKS connect fails (Azure Portal generated command)

### ISSUE THREAD

**Issue by mdenhoedt** [Azure/azure-cli#20996]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 22] Invalid argument: '"C'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2163, in aks_get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 3572, in _print_or_merge_credentials
OSError: [Errno 22] Invalid argument: '"C'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az account set ....` (copied from the Azure Portal)
- `az aks get-credentials --resource-group {} --name {}` (copied from the Azure Portal)

## Expected Behavior
Be able to login to the cluster and use `kubectl` command from the Powershell window.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

Extensions:
azure-devops 0.22.0
deploy-to-azure 0.2.0
dev-spaces 1.0.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@mdenhoedt Apologies for the late reply. You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. There might be an issue in fetching details from this config file. To isolate the issue, You can try to rename or delete this config file and try to run the [az aks get-credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) and check if that helps.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

Please let me know if you have any further questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mdenhoedt I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
