### ISSUE TITLE
ImportError: No module named datetime on Ubuntu 16.10

### ISSUE THREAD

**Issue by uday31in** [Azure/azure-cli#2101]
root@udaylinux:~# az configure
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/az/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 9, in <module>
    from azure.cli.core.application import APPLICATION, Configuration
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 5, in <module>
    import pkg_resources
  File "/opt/az/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named datetime

**Comment by derekbekoe** [comment]
`datetime` is a standard Python module so this looks like a platform/Python set up issue.
There are a couple of forum posts on this I've found which may help.

http://askubuntu.com/questions/509283/python-no-module-named-datetime
http://stackoverflow.com/questions/26031160/importerror-no-module-named-datetime
