### ISSUE TITLE
Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'

### ISSUE THREAD

**Issue by GSYankov** [Azure/azure-cli#21037]
### Extension name (the extension in question)
logic

### Description of issue (in as much detail as possible)
If to Settings => Workflow settings => Access control configuration of an Azure Logic App had been added an IP, 
`az logic workflow show --resource-group "rgName" --name "laName"`, returns the following error:

```
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1430, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1588, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: 'FlowAccessControlConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 756, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 772, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 754, in handler
    return getter(**args)
  File "/home/georgi/.azure/cliextensions/logic/azext_logic/generated/custom.py", line 27, in logic_workflow_show
    workflow_name=name)
  File "/home/georgi/.azure/cliextensions/logic/azext_logic/vendored_sdks/logic/operations/_workflow_operations.py", line 248, in get
    deserialized = self._deserialize('Workflow', pipeline_response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1356, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1434, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1430, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1588, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: 'FlowAccessControlConfiguration'
```
The deletion of this IP doesn't solve the error, a possible way to recover is to promote a version before the IP restriction had been made.
-----/

**Comment by jsntcy** [comment]
The fix is available in logic 0.1.5 (latest version), and you can upgrade extension to latest version using command “az extension update –name logic” to try the fix.
