### ISSUE TITLE
SSH extension install failure

### ISSUE THREAD

**Issue by cbeshare** [Azure/azure-cli#21045]
## Describe the bug

**Command Name**
`az ssh`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh {} --ip {} --file {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

PS C:\Users\Chakra> az ssh config --ip \* --file ./azuressh
The command failed with an unexpected error. Here is the traceback:
[WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\*'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Chakra\.azure\cliextensions\ssh\azext_ssh\custom.py", line 53, in ssh_config
    _do_ssh_op(cmd, resource_group_name, vm_name, ssh_ip, public_key_file, private_key_file, use_private_ip,
  File "C:\Users\Chakra\.azure\cliextensions\ssh\azext_ssh\custom.py", line 90, in _do_ssh_op
    public_key_file, private_key_file, delete_keys = _check_or_create_public_private_files(public_key_file,
  File "C:\Users\Chakra\.azure\cliextensions\ssh\azext_ssh\custom.py", line 189, in _check_or_create_public_private_files
    os.makedirs(credentials_folder)
  File "os.py", line 223, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\*'

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@cbeshare Apologies for the late reply. Could you please follow the below action plan in the order and let me know if that works ?

>az extension add --name ssh # This command adds the ssh extension
az version  # Run this command to check the extensions installed. This should show the ssh extension

>az ssh config --ip 23.XXX.XX.86 --file ./sshconfig  # Add the right public IP address of the VM
ssh -F ./sshconfig 23.XXX.XX.86

Even if the error appears while running the command it should succeed in the background. The sshconfig file should be created. Please let me know if you face any issues. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@cbeshare This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by navba-MSFT** [comment]
@cbeshare We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
