### ISSUE TITLE
`az login` by attempting to specify `-u` and `-p` fails on MacOS 10.15.7

### ISSUE THREAD

**Issue by kristianjaeger** [Azure/azure-cli#21068]
## `az login` by attempting to specify `-u` and `-p` fails on MacOS 10.15.7.

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unsupported soap action: http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Cancel
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 158, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 186, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1401, in acquire_token_by_username_password
    response = _clean_up(self._acquire_token_by_username_password_federated(
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1428, in _acquire_token_by_username_password_federated
    wstrust_result = wst_send_request(
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/msal/wstrust_request.py", line 47, in send_request
    assert soap_action in (Mex.ACTION_13, Mex.ACTION_2005), (  # A loose check here
AssertionError: Unsupported soap action: http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Cancel

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`

## Expected Behavior
Able to specify user when calling `az login`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.32.0

Extensions:
dev-spaces 1.0.6
aks-preview 0.5.34

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by rayluo** [comment]
Inside the error trace, the "wstrust_request.py" suggested that this was an ADFS user. The last line of the error, "AssertionError: Unsupported soap action: `http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Cancel`", suggested that the ADFS somehow rejected/cancelled the auth request. Has this user, @kristianjaeger , ever been successfully used "az login -u ... -p ..." before?

Alternatively, please consider use "az login" instead. The [username password auth has its inherent restrictions](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication).

**Comment by kristianjaeger** [comment]
@rayluo Thanks. I actually encountered this error at work with an account that has been used previously to login at least with the portal. This is the first time that I recall trying to use the -u and - p flags.  Just `az login` works fine.

**Comment by rayluo** [comment]
There might be some settings needed from the ADFS to enable the username password sign-in. Unfortunately, I do not have much info on that part. If you are OK with sticking with "az login", please do. "az login" is the browser-based interactive login, which is our recommended login approach, anyway.

**Comment by kristianjaeger** [comment]
Thanks @rayluo .  Sounds good. I can stick with the browser approach and `az login`. Cheers.
