### ISSUE TITLE
Not able to run AKS create command 

### ISSUE THREAD

**Issue by Mcprasad** [Azure/azure-cli#21141]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/_sodium.abi3.so, 0x0002): Library not loaded: @rpath/libsodium.23.dylib
  Referenced from: /opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/_sodium.abi3.so
  Reason: tried: '/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/bin/../lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/bin/../lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 46, in <module>
    from azure.cli.command_modules.acs import acs_client, proxy
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/azure/cli/command_modules/acs/acs_client.py", line 13, in <module>
    import paramiko
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/paramiko/transport.py", line 92, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/signing.py", line 17, in <module>
    import nacl.bindings
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/_sodium.abi3.so, 0x0002): Library not loaded: @rpath/libsodium.23.dylib
  Referenced from: /opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/python3.8/site-packages/nacl/_sodium.abi3.so
  Reason: tried: '/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/bin/../lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/lib/libsodium.23.dylib' (no such file), '/opt/homebrew/Caskroom/miniforge/base/envs/tool/bin/../lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} -s {} -c {} -l {} --generate-ssh-keys`

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.8.12
Installer: PIP

azure-cli 2.31.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Mcprasad** [comment]
Any update ?

**Comment by mbifeld** [comment]
Hi @Mcprasad, I realize this issue was never updated. Is still an active issue? The error trace seems to indicate that libsodium isn't installed. Does installing it via `brew install libsodium` with the latest az cli version fix it?

**Comment by mbifeld** [comment]
Hi @Mcprasad, do you have any updates from my comment above? I'll close the issue soon if not.

**Comment by mbifeld** [comment]
Closing as no update from original author. Please reopen is this issue is still present.
