### ISSUE TITLE
az storage blob download-batch fails with 'ProtocolError' object has no attribute 'lower'

### ISSUE THREAD

**Issue by p-freire** [Azure/azure-cli#21148]
Getting time out errors when trying to download stuff from Azure Blob Storage. Similar to issue #[20073](https://github.com/Azure/azure-cli/issues/20073)

`az feedback` shown below

## Describe the bug

**Command Name**
`az storage blob download-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ProtocolError' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 438, in _error_catcher
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 764, in read_chunked
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 694, in _update_chunk_length
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 753, in generate
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 572, in stream
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 793, in read_chunked
  File "contextlib.py", line 131, in __exit__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 321, in _perform_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/_http/httpclient.py", line 86, in perform_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 697, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 831, in content
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 756, in generate
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/blob.py", line 358, in storage_blob_download_batch
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/util.py", line 16, in collect_blobs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/util.py", line 16, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/util.py", line 34, in collect_blob_objects
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 1303, in list_blobs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 1429, in _list_blobs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 430, in _perform_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/storageclient.py", line 361, in _perform_request
azure.common.AzureException: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 368, in new_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 273, in handler
AttributeError: 'ProtocolError' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download-batch -d {} -s {} --pattern {} --account-name {} --account-key {}`

## Expected Behavior
To download files without time outs.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.2 *

```
## Additional Context
I can download individual files using the GUI (i.e., Azure Portal), but that obviously does not scale.

**Comment by yonzhan** [comment]
storage

**Comment by navba-MSFT** [comment]
@p-freire Apologies for the late reply. The error message is pointing to the connection reset, which would typically point to the network level socket termination. Could you please let us know if you are still facing the same issue ? If yes, Could you please try the same operation[ from cloud shell ](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#code-try-11) from a different network? This plan will help us rule out any unreliable network issues at your end. Awaiting your reply.
