### ISSUE TITLE
Relative path for current directory when indicating filepath

### ISSUE THREAD

**Issue by Layer8Err** [Azure/azure-cli#21155]
**Is your feature request related to a problem? Please describe.**
Lack of dot notation "./" when referencing filepaths is kind of annoying. 

**Describe the solution you'd like**
I would prefer to be able to use relative filepaths (like "~/myproj/myfile.txt" or "./myproj/myfile.txt") to indicate the current directory, rather than indicating the full filepath each time.

**Describe alternatives you've considered**
You have to use the full filepath to a file or directory or the azure client will throw an error.

**Additional context**
Encountered this issue when running the following command:
```bash
az artifacts universal publish --organization $ORG --project="$PROJECT" --scope project --feed $FEED --name initial-package --version $VERSION --description "$DESCRIPTION" --path $SINGLEFILE
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@Layer8Err Thanks for reaching out to us. I am looking into this issue and doing some research. 
In the meantime, could you try the relative path _myproj/myfile.txt_ without specifying the '~' or '.' as the path and check if that helps? Awaiting your reply.
More Info [here](https://docs.microsoft.com/en-us/cli/azure/artifacts/universal?view=azure-cli-latest#az-artifacts-universal-publish)

**Comment by Layer8Err** [comment]
I am getting the same error when using the relative path _myproj/myfile.txt_ without specifying '~' or '.' as part of the path.

```bash
~# az artifacts universal publish --organization $ORG --project="$PROJECT" --scope project --feed $FEED --name initial-package --version $VERSION --description "$DESCRIPTION" --path myproj/myfile.txt

ERROR: Failed to hash a page of files. Exception listed below...
ERROR: An exception was thrown: Path '/home/user/tmp/myproj/myfile.txt' does not start with 'myproj'. (Parameter 'pageItem')
System.ArgumentException: Path '/home/user/tmp/myproj/myfile.txt' does not start with 'myproj'. (Parameter 'pageItem')
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass26_0.<<PaginateAndProcessFilesHelperAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.PaginateAndProcessFilesHelperAsync(String sourceDirectory, Boolean chunkDedup, IEnumerable`1 pathsInDir, Action`1 hashCompleteCallback, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass22_0.<<PaginateAndProcessFiles>b__0>d.MoveNext()
ERROR: Encountered an unexpected error.
System.ArgumentException: Path '/home/user/tmp/myproj/myfile.txt' does not start with 'myproj'. (Parameter 'pageItem')
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, PageItem pageItem, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass26_0.<<PaginateAndProcessFilesHelperAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.PaginateAndProcessFilesHelperAsync(String sourceDirectory, Boolean chunkDedup, IEnumerable`1 pathsInDir, Action`1 hashCompleteCallback, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass22_0.<<PaginateAndProcessFiles>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.<>c__DisplayClass22_0.<<PaginateAndProcessFiles>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.PaginateAndProcessFiles(String sourceDirectory, Boolean chunkDedup, IEnumerable`1 pages, CancellationToken cancellationToken, Action`1 hashCompleteCallback)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.PublishAsync(String fullPath, ArtifactPublishOptions artifactPublishOptions, String manifestFileOutputPath, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Packaging.UPackClientShared.UPackSharedClient.PushWithoutCheckingForDuplicatePackageAsync(String projectNameOrId, String feedNameOrId, String packageName, String packageVersion, String description, String sourceDirectory, Boolean honorIgnoreOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Packaging.UPackClientShared.UPackSharedClient.PushAsync(String projectNameOrId, String feedNameOrId, String packageName, String packageVersion, String description, String sourceDirectory, Boolean honorIgnoreOptions, CancellationToken cancellationToken)
   at ArtifactTool.Commands.UPackPublishCommand.<>c__DisplayClass25_0.<<ExecuteAsync>b__0>d.MoveNext() in D:\a\1\s\src\ArtifactTool\Commands\UPack\UPackPublishCommand.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at ArtifactTool.Commands.UPack.UPackExceptionMapper.WithExceptionHandlingAsync(Func`1 act) in D:\a\1\s\src\ArtifactTool\Commands\UPack\UPackExceptionMapper.cs:line 39
   at ArtifactTool.Commands.UPackPublishCommand.ExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\UPack\UPackPublishCommand.cs:line 63
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 105
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 57
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 112
ERROR: Process ['/home/user/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.204/artifacttool', 'universal', 'publish', '--service', 'https://dev.azure.com/DwightBrenner/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'TestFeed', '--package-name', 'initial-package', '--package-version', '0.0.2', '--path', 'myproj/myfile.txt', '--project', 'TestDocxConvert', '--description', 'My Test Description'] with PID 2191 exited with return code 1
```

**Comment by navba-MSFT** [comment]
@Layer8Err Thanks for getting back. I am doing some research on this. I will get back to you once I have an update on this.

**Comment by navba-MSFT** [comment]
@Layer8Err If you are running on agents, you could use predefined variables like "$(System.DefaultWorkingDirectory)/myproj". If you're running locally, you could workaround with something like "$(pwd)/myproj" if you absolutely want to avoid putting the absolute path directly. Please let me know if that helps.

**Comment by Layer8Err** [comment]
@navba-MSFT adding in the full path, either explicitly or with variables is fine and doesn't generate an error. It would just be nice if the `az` cli worked like other programs e.g. `cat myproj/myfile.txt` | `cat ./myproj/myfile.txt`.

**Comment by navba-MSFT** [comment]
@Layer8Err Azure CLI does support adding relative path or ~. However it depends on the CLI commands of certain Azure services. Example: For the Azure blob storage [upload](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload-examples) / [download](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-download-batch-examples) operations you can see the relative path or ~ being used in the CLI command. 

Looking into your error callstack during the AzCLI publish artifact operation, I see that there is a call to generate the Hash and it is doing an internal call to GetFileBlobDescriptorAsync() function which expects **_rootDirectory_** as one of the parameter. So using pre-defined variables itself is my recommendation. Hope this answers. 
Please let me know if you have any further queries.
