### ISSUE TITLE
Installing WSL2 following the Microsoft official instructions breaks az cli: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

### ISSUE THREAD

**Issue by agriggs** [Azure/azure-cli#21154]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'http_cache'
Traceback (most recent call last):
  File "/home/agriggs/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 177, in login_with_device_code
    flow = self._msal_app.initiate_device_flow(scopes, **kwargs)
  File "/home/agriggs/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 101, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/home/agriggs/.local/lib/python3.8/site-packages/msal/application.py", line 1023, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'http_cache'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.3 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.32.0
```
## Additional Context

az cli works if installing the outdated version. Ubuntu 20.04 (Focal Fossa) and 20.10 (Groovy Gorilla) include an azure-cli package with version 2.0.81 provided by the universe repository

**Comment by agriggs** [comment]
Only one machine if affected. Others work so closing.
