### ISSUE TITLE
a

### ISSUE THREAD

**Issue by Akshay-gade** [Azure/azure-cli#21176]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/home/gadeakshay2713/site.zip'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 500, in enable_zip_deploy_webapp
    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout=timeout, slot=slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 526, in enable_zip_deploy
    with open(os.path.realpath(os.path.expanduser(src)), 'rb') as fs:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gadeakshay2713/site.zip'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --src {} --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by SaurabhSharma-MSFT** [comment]
@Akshay-gade Are you passing your zip file location to `--src` parameter of the cmdlet? Please check if you are passing everything correctly in the cmdlet like below - 
`az webapp deployment source config-zip --resource-group "resource-group-name" --name "app-name" --src "your zip file path with file name.zip"`

**Comment by panchagnula** [comment]
The error here is: the path is incorrect or doesn't exit "No such file or directory: '/home/gadeakshay2713/site.zip"
