### ISSUE TITLE
az login not working: TypeError: SubscriptionClient.__init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by hcherukuri** [Azure/azure-cli#21189]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
SubscriptionClient.__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/home/hcheruku/.local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 177, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 746, in find_using_common_tenant
    client = self._create_subscription_client(credential)
  File "/home/hcheruku/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 837, in _create_subscription_client
    client = client_type(credential, api_version=api_version,
TypeError: SubscriptionClient.__init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.15.18-200.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Workstation Edition)
Python 3.10.2
Installer: PIP

azure-cli 2.32.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Looks like your `azure-mgmt-resource` SDK is track 1 which is downgraded by other installed `pip` packages. You may check with `pip list`. Azure CLI requires

https://github.com/Azure/azure-cli/blob/3ea435b045657d63745c8afedf14f06f16c67440/src/azure-cli/setup.py#L119

You may fix Azure CLI installation by running

```
pip install azure-cli --force-reinstall
```

If you use `pip` to install Azure CLI, we recommend installing Azure CLI in a virtual env: https://github.com/Azure/azure-cli/issues/20476
