### ISSUE TITLE
Operation returned an invalid status 'Bad Request' when trying to set a custom domain

### ISSUE THREAD

**Issue by simonaco** [Azure/azure-cli#21186]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

Run `az staticwebapp hostname set -n jamcloud --hostname blog.domain.com`
returns Operation returned an invalid status 'Bad Request' 

cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"The maximum number of custom domains allowed for this static site is 2.","Target":null,"Details":[{"Message":"The maximum number of custom domains allowed for this static site is 2."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"59334","MessageTemplate":"The maximum number of custom domains allowed for this static site is {0}.","Parameters":["2"],"Code":"BadRequest","Message":"The maximum number of custom domains allowed for this static site is 2."}}],"Innererror":null}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/static_sites.py", line 117, in set_staticsite_domain
    return sdk_no_wait(no_wait, client.begin_create_or_update_static_site_custom_domain,
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 678, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/mgmt/web/v2021_01_15/operations/_static_sites_operations.py", line 2464, in begin_create_or_update_static_site_custom_domain
    raw_result = self._create_or_update_static_site_custom_domain_initial(
  File "/opt/homebrew/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/mgmt/web/v2021_01_15/operations/_static_sites_operations.py", line 2409, in _create_or_update_static_site_custom_domain_initial
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'

cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'
az_command_data_logger: Operation returned an invalid status 'Bad Request'

**Expected behavior**

We should include the error message "The maximum number of custom domains allowed for this static site is 2."

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
The error here is that the quota has reached "The maximum number of custom domains allowed for this static site is 2."
@StrawnSC can we show the detailed error message by default on SWA command?

**Comment by StrawnSC** [comment]
I also need to fix this for `az staticwebapp identity assign`: 

<img width="1439" alt="Screen Shot 2022-02-28 at 11 46 43 AM" src="https://user-images.githubusercontent.com/10121214/156048621-fdc637b8-9f9d-46f9-b8c6-3027a4bd5fb3.png">

It seems this feature is only available for the standard SKU, but the error message here is simply the unhelpful `Bad Request`

**Comment by Kahera** [comment]
The same goes for `az staticwebapp create` where the error message is `
RepositoryToken is invalid. Please ensure the repository exists and the RepositoryToken is for an admin of the repository.` 

This also only outputs `Bad Request`.
