### ISSUE TITLE
"No module named 'Crypto.IO'" while running `az connectedk8s connect` command on Raspbian

### ISSUE THREAD

**Issue by ikivanc** [Azure/azure-cli#21197]
## Describe the bug

I try to add a K3S cluster on Raspberry Pi 2 with Raspbian to Azure Arc and I wanted to run the command through RP2
`az connectedk8s connect --name AzureArcTest1 --resource-group AzureArcTest`

I installed `azure cli` on my Raspberry Pi 2, I got below error, then I manually installed `pycryptodome` package and I get the same error.
`sudo pip install pycryptodome==3.14.0`

Is is possible to help me how to fix it?

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'Crypto.IO'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/__init__.py", line 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.7/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 33, in <module>
    from Crypto.IO import PEM
ModuleNotFoundError: No module named 'Crypto.IO'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect {} {} {} {} -l {}`

## Environment Summary
```
Linux-5.10.17-v7+-armv7l-with-debian-10.9, Raspbian GNU/Linux 10 (buster)
Python 3.7.3
Installer: PIP

azure-cli 2.32.0

Extensions:
connectedk8s 1.2.0
k8sconfiguration 0.2.4

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by ikivanc** [comment]
After re-installing `sudo pip install pycryptodome` solved the issue. It didn't worked previously. Closing this issue.
