### ISSUE TITLE
sftp storage account new user ssh

### ISSUE THREAD

**Issue by PeterVos81** [Azure/azure-cli#21198]
## Describe the bug

**Command Name**
`az storage account local-user create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 582, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 260, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2006, in _parse_known_args
  File "argparse.py", line 1946, in consume_optional
  File "argparse.py", line 1874, in take_action
  File "C:\Users\p.vos\.azure\cliextensions\storage-preview\azext_storage_preview\_validators.py", line 649, in __call__
    namespace.permission_scope.append(PermissionScope(
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account local-user create --account-name {} -g {} -n {} --home-directory {} --permission-scope {} {} {} --ssh-authorized-key {} --has-ssh-key {} --has-ssh-password {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0 *

Extensions:
storage-preview 0.8.0

```

**Comment by yonzhan** [comment]
storage
