### ISSUE TITLE
Azure Bash error: OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by codeNameM1** [Azure/azure-cli#21213]
## Describe the bug

**Command Name**
``

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/morgan/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/feedback/custom.py", line 589, in handle_feedback
    show_updates_available(new_line_before=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 466, in show_updates_available
    VERSIONS[_VERSION_CHECK_TIME] = str(datetime.datetime.now())
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 76, in __setitem__
    self.save_with_retry()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 66, in save_with_retry
    self.save()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_session.py", line 55, in save
    with open(self.filename, 'w', encoding=self._encoding) as f:
OSError: [Errno 30] Read-only file system: '/home/morgan/.azure/versionCheck.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``followed steps on https://microsoftlearning.github.io/AZ-900T0x-MicrosoftAzureFundamentals/Instructions/Walkthroughs/11-Create%20a%20VM%20with%20the%20CLI.html 
- 
- but came back with error

## Expected Behavior
show the resource group i created 

## Environment Summary
```
Linux-5.4.0-1068-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is the same issue as https://github.com/Azure/azure-cli/issues/13855.
