### ISSUE TITLE
az login:  Failed to establish a new connection: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by Svessir** [Azure/azure-cli#21247]
## Describe the bug
When logging in with azure cli inside of mcr.microsoft.com/azure-cli:2.32.0 container I get an error (See below), The same login command works if I login outside of the container on my host.

**Command Name**
`az login`

**Errors:**
```
<urllib3.connection.HTTPSConnection object at 0x7f3ed60e6490>: Failed to establish a new connection: [Errno -2] Name does not resolve

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Expected Behavior
Should have successfully signed in.

## Environment Summary
```
Linux-5.4.0-99-generic-x86_64-with, Alpine Linux v3.14
Python 3.9.6
Installer: DOCKER

azure-cli 2.32.0 *
```
## Additional Context
Running inside a mcr.microsoft.com/azure-cli:2.32.0 container

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I am not able to reproduce with docker on WSL:

```
> docker run -it --rm mcr.microsoft.com/azure-cli:2.32.0
Unable to find image 'mcr.microsoft.com/azure-cli:2.32.0' locally
2.32.0: Pulling from azure-cli
a0d0a0d46f8b: Pull complete
ba51967de001: Pull complete
61c7c23e14da: Pull complete
e344ba9f0095: Pull complete
ecfd11eb7166: Pull complete
a97b999d14a2: Pull complete
4fdd3e1ce8c7: Pull complete
040868a78130: Pull complete
708b80d1ae83: Pull complete
9f274ba9c25a: Pull complete
e47da6763739: Pull complete
Digest: sha256:d2a53ad219b28567e256693eba1b985bbebea4687fddf293b0ab6d75ab9f728b
Status: Downloaded newer image for mcr.microsoft.com/azure-cli:2.32.0
bash-5.1# az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HHG6H6X3L to authenticate.
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "id": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
...
```
Are you running the docker container on WSL? If so, this could be related to 

- https://github.com/microsoft/WSL/issues/5991
- https://github.com/microsoft/WSL/issues/5256

**Comment by Svessir** [comment]
No I am running the docker container in a hyper-v Ubuntu 18.04 virtual machine.

**Comment by jiasli** [comment]
I see. Then could you test if your container can resolve `login.microsoftonline.com`?

```
apt-get update
apt install dnsutils
nslookup login.microsoftonline.com
```

The result should look like 

```
# nslookup login.microsoftonline.com
Server:         192.168.65.5
Address:        192.168.65.5#53

Non-authoritative answer:
login.microsoftonline.com       canonical name = ak.privatelink.msidentity.com.
ak.privatelink.msidentity.com   canonical name = www.tm.ak.prd.aadg.trafficmanager.net.
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.86
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.151
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.129
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.87
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.144
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.80
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 20.190.163.18
Name:   www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.128
```

**Comment by Svessir** [comment]
Here is the result:
```
bash-5.1# nslookup login.microsoftonline.com
Server:		172.30.208.1
Address:	172.30.208.1:53

Non-authoritative answer:
login.microsoftonline.com	canonical name = ak.privatelink.msidentity.com
ak.privatelink.msidentity.com	canonical name = www.tm.ak.prd.aadg.akadns.net
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.74
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.5
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.3
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.9
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.70
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.1
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.131
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.160.130

Non-authoritative answer:
login.microsoftonline.com	canonical name = ak.privatelink.msidentity.com
ak.privatelink.msidentity.com	canonical name = www.tm.ak.prd.aadg.akadns.net
```

**Comment by Svessir** [comment]
Any update on this issue?

**Comment by jiasli** [comment]
DNS resolution looks good. Could you check if Python can access https://login.microsoftonline.com/ ?

Use the Azure CLI image:

```
docker run -it mcr.microsoft.com/azure-cli
python -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

Use official Python image based on Alpine:

```
docker run -it python:alpine
pip install requests
python -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

However, I don't think this problem is caused by Azure CLI image. I would recommend checking the docker or Hyper-V configuration instead.

**Comment by Svessir** [comment]
Yeah I can confirm I am having issues with `https://login.microsoftonline.com/` now. Getting a different error message from last time on az login. Do you have any info what configuration is possibly causing this?
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83f3789240>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f83f3789240>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83f3789240>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 177, in login_with_device_code
    flow = self._msal_app.initiate_device_flow(scopes, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 101, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/usr/local/lib/python3.10/site-packages/msal/application.py", line 1466, in __init__
    super(PublicClientApplication, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/msal/application.py", line 438, in __init__
    self.authority = Authority(
  File "/usr/local/lib/python3.10/site-packages/msal/authority.py", line 83, in __init__
    openid_config = tenant_discovery(
  File "/usr/local/lib/python3.10/site-packages/msal/authority.py", line 142, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83f3789240>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by jiasli** [comment]
@Svessir, I am afraid this is really out of my knowledge. 😥 Do other domains work, like https://github.com/, https://outlook.live.com/?

**Comment by superff** [comment]
I saw a similar issue `ERROR: <urllib3.connection.HTTPSConnection object at 0x7f8a18270610>: Failed to establish a new connection: [Errno -2] Name or service not known` with calling  `az storage blob upload `

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by mpouleijn** [comment]
Same issue here running the mcr.microsoft.com/azure-cli:latest container on rancher desktop

**Comment by sidoverflow** [comment]
I've come across this a couple times when I switch my connection to an enterprise network. Restarting the container seems to fix the issue for me.

**Comment by baromojm** [comment]
The issue seems to be with URL:
https://management.azure.com/tenants?api-version=2019-11-01

Steps to reproduce:
$ docker run -it --rm mcr.microsoft.com/azure-cli:latest
bash-5.1# curl https://management.azure.com/tenants?api-version=2019-11-01
curl: (6) Could not resolve host: management.azure.com

**Comment by Al77056** [comment]
I ran into the same issue, and found out a workaround by adding the "--add-host=management.azure.com:20.40.227.150" to the docker command line.

**Comment by karpikpl** [comment]
thanks @Al77056 for the solution.

I had DNS issues on WSL, changed resolvers which fixed all of them but still had this problem with azure-cli

**Comment by lcqueiroz** [comment]
I'm facing this error when testing my code in my company's Kubernetes cluster. Locally it works. The **upload_blob** method is crashing and giving me this error: 
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f5959eb3890>: Failed to establish a new connection: [Errno -2] Name or service not known

code:
`from azure.storage.blob import BlobServiceClient
import os
from typing import List, Tuple, ByteString

 class AzureBlob:
    def __init__(self):
        self.blob_container_name = "example"
         os.environ["HTTP_PROXY"] = "proxy.example"
        self.container_client = self.create_service_client()

    def create_service_client(self):
        az_connection_str = os.environ.get('azure_st_connection_string')

        blob_service_client = BlobServiceClient.from_connection_string(conn_str=az_connection_str )
        container_client = blob_service_client.get_container_client(container=self.blob_container_name)
        print("Client connected ...", flush=True)

        return container_client

    def save_file(self, path: str, content: ByteString):
        blob = self.container_client.get_blob_client(path)
        blob.upload_blob(content)`

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/16524
