### ISSUE TITLE
`API version 2021-10-01 does not have operation group 'managed_clusters'` when running `az aks get-credentials`

### ISSUE THREAD

**Issue by Stummi** [Azure/azure-cli#21254]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2021-10-01 does not have operation group 'managed_clusters'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/_client_factory.py", line 22, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerservice/_container_service_client.py", line 404, in managed_clusters
    raise ValueError("API version {} does not have operation group 'managed_clusters'".format(api_version))
ValueError: API version 2021-10-01 does not have operation group 'managed_clusters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az aks get-credentials --admin --subscription={} --name {} --resource-group {}`

## Environment Summary
```
Linux-5.15.0-3-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.10
Installer: DEB

azure-cli 2.33.0

Extensions:
azure-devops 0.23.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@Stummi Apologies for the late reply. I was not able to reproduce this issue in my machine. Could you please install the latest version of the Azure CLI from [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and then test this again ? Awaiting your reply.

Tagging a few _similar_ issues here #16498 #18889

**Comment by jiasli** [comment]
Judging by 

```
Linux-5.15.0-3-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.10
azure-cli 2.33.0
```

This is not the official Azure CLI published by Microsoft. Please see https://github.com/Azure/azure-cli/issues/19640.

**Comment by Stummi** [comment]
Thanks. I actually did download the official version but it seems I was unaware of a locally installed one that did override the official one. It now works.
