### ISSUE TITLE
Installer fails on Windows with FileNotFoundError

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-cli#2127]
Running Python 3.5, when I run `curl -L https://aka.ms/InstallAzureCli | bash`, it fails with:

```
...
Already using interpreter C:\Users\David\AppData\Local\Programs\Python\Python35-32\python.exe
Using base prefix 'C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python35-32'
New python executable in C:\Users\David\lib\azure-cli\Scripts\python.exe
Installing setuptools, pip, wheel...done.
-- Executing: ['C:\\Users\\David\\lib\\azure-cli\\bin\\pip', 'install', '--cache-dir', 'C:\\Users\\David\\AppData\\Local\\Temp\\tmptp70dicz', 'azure-cli', '--upgrade']
Traceback (most recent call last):
  File "C:/Users/David/AppData/Local/Temp/azure_cli_install_tmp_K1pi", line 344, in <module>
    main()
  File "C:/Users/David/AppData/Local/Temp/azure_cli_install_tmp_K1pi", line 330, in main
    install_cli(install_dir, tmp_dir)
  File "C:/Users/David/AppData/Local/Temp/azure_cli_install_tmp_K1pi", line 140, in install_cli
    exec_command(cmd)
  File "C:/Users/David/AppData/Local/Temp/azure_cli_install_tmp_K1pi", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\David\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by derekbekoe** [comment]
@davidebbo That install method is for Linux and macOS.
On Windows, install with pip.
See https://github.com/Azure/azure-cli#installation

**Comment by davidebbo** [comment]
@derekbekoe Duh, my bad, misread the doc page! :)
