### ISSUE TITLE
az image builder create

### ISSUE THREAD

**Issue by masonhuemmer** [Azure/azure-cli#21273]
## Describe the bug

**Command Name**
`az image builder create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Cannot deserialize as [str] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [str] an object of type <class 'str'>
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1645, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
msrest.exceptions.DeserializationError: Cannot deserialize as [str] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/vm/_image_builder.py", line 426, in create_image_template
    return client.virtual_machine_image_templates.begin_create_or_update(
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/mgmt/imagebuilder/operations/_virtual_machine_image_templates_operations.py", line 280, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/mgmt/imagebuilder/operations/_virtual_machine_image_templates_operations.py", line 224, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'ImageTemplate')
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 622, in body
    raise_with_traceback(
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 620, in body
    data = deserializer._deserialize(data_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1649, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1631, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1645, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [str] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [str] an object of type <class 'str'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image builder create --name {} --resource-group {} --image-template {}`

## Environment Summary
```
macOS-12.3-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by masonhuemmer** [comment]
FYI, I was using the image template available in Microsoft docs. 

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json

```
{ 
    "type": "Microsoft.VirtualMachineImages/imageTemplates", 
    "apiVersion": "2021-10-01", 
    "location": "<region>", 
    "tags": {
      "<name>": "<value>",
      "<name>": "<value>"
    },
    "identity": {},			 
    "properties": { 
      "buildTimeoutInMinutes": <minutes>, 
      "vmProfile": {
        "vmSize": "<vmSize>",
        "proxyVmSize": "<vmSize>",
        "osDiskSizeGB": <sizeInGB>,
        "vnetConfig": {
          "subnetId": "/subscriptions/<subscriptionID>/resourceGroups/<vnetRgName>/providers/Microsoft.Network/virtualNetworks/<vnetName>/subnets/<subnetName>"
        },
	"userAssignedIdentities": [
          "/subscriptions/<subscriptionID>/resourceGroups/<identityRgName>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identityName1>",
	  "/subscriptions/<subscriptionID>/resourceGroups/<identityRgName>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identityName2>",
	  "/subscriptions/<subscriptionID>/resourceGroups/<identityRgName>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identityName3>",
	  ...
      ]
      },
      "source": {}, 
      "customize": {}, 
      "distribute": {} 
    } 
  }
```

**Comment by zhoxing-ms** [comment]
@masonhuemmer Could you please send me your specific parameters, templates and the debug log to me by email? My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by masonhuemmer** [comment]
I sent you the image template.

**Comment by zhoxing-ms** [comment]
@masonhuemmer This issue is caused by the wrong type of `replicationRegions` value in the template file.

Please note that the definition of `replicationRegions` is an array, not a string. [doc link](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json#distribute-sharedimage)
```
"replicationRegions": [
    "<region where the gallery is deployed>",
    "<region>"
]
```
Therefore, `"replicationRegions": "centralus"` in your template file should be changed to `"replicationRegions": ["centralus"]`

**Comment by masonhuemmer** [comment]
Once I updated the replicationRegion to a list, I was able to resolve my issue.
