### ISSUE TITLE
az keyvault secret list fails to run with azure managed identity

### ISSUE THREAD

**Issue by TopperKain** [Azure/azure-cli#21331]
## Describe the bug

**Command Name**
`az keyvault secret list`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- created a new Azure Linux VM (Ubuntu 20)
- Added a system managed identity to the Azure VM
- (I've done a bunch of other work to setup the VM at this point, but I don't think its relavent here other than perhaps I have multiple Python versions installed)
- Added a certificate to may Azure Key Vault
- Gave access to the key vault as reader to the VM's identity
-  Created an access policy to get and list secrets and certificates to the VM's identity
- Logged into the vm via `az ssh vm`
- Installed azure cli with sudo apt install azure-cli
-  Ran `az login --identity`
-  Ran `az keyvault secret`
- `az keyvault secret list`

## Environment Summary
```
Linux-5.11.0-1028-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```
## Additional Context
Here is the full command line error:
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 528, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/keyvault/_command_type.py", line 71, in keyvault_arguments_loader
    op = get_op_handler()
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/keyvault/_command_type.py", line 68, in get_op_handler
    return self.command_loader.get_op_handler(operations_tmpl.format(method_name))
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'

**Comment by TopperKain** [comment]
Reviewing #21118, it looked like the issue was an out of date package from the Ubuntu Universe repo. I updated the package using the instructions here https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt and it appears to be working.

However, this is a pretty bad user experience. I'm utilizing Microsoft's Ubuntu image in Azure, getting recommended by the os to run "sudo apt install azure-cli" and then having the operation fail. Is there anyway to get that universe package continually updated or get the Microsoft repos added the VM images in Azure?

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
#19640 for details
