### ISSUE TITLE
Unable to list subscriptions for Event Grid Topic

### ISSUE THREAD

**Issue by CoffeeExpress** [Azure/azure-cli#21344]
## Describe the bug

**Command Name**
`az eventgrid event-subscription list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 903, in cli_event_subscription_list
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 1740, in _list_event_subscriptions_by_resource_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 1793, in _validate_subscription_id_matches_default_subscription_id
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventgrid event-subscription list --source-resource-id {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: 

azure-cli 2.28.0 *

Extensions:
aks-preview 0.5.44
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@CoffeeExpress Thanks for reporting the issue. I was able to run the below command to list the subscription for EG Topic and it worked fine. Could you please refer this thread #20244 for the similar issue? And then run the below command using most recent version of Azure CLI:

>az login
az account set --subscription "1234-123-****-1234"
az eventgrid event-subscription list --source-resource-id /subscriptions/MySubscriotionID/resourceGroups/MyRG/providers/Microsoft.EventGrid/topics/MyTopicName

Please let me know if you face any issues. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@CoffeeExpress I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@CoffeeExpress We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
