### ISSUE TITLE
login with --service-principal results in following error: 

### ISSUE THREAD

**Issue by majorsmann** [Azure/azure-cli#21376]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/algorithms.py", line 256, in prepare_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/primitives/serialization/base.py", line 18, in load_pem_private_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py", line 1244, in load_pem_private_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py", line 1475, in _load_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 145, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 160, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 147, in login_with_service_principal
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1589, in acquire_token_for_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 735, in obtain_token_for_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 754, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 200, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/assertion.py", line 63, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/assertion.py", line 42, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/assertion.py", line 115, in create_normal_assertion
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/api_jwt.py", line 63, in encode
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/api_jws.py", line 110, in encode
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\jwt/algorithms.py", line 258, in prepare_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/primitives/serialization/base.py", line 23, in load_pem_public_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py", line 1274, in load_pem_public_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

Extensions:
azure-devops 0.20.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by elqian** [comment]
I also have this issue. I downloaded the certificate using  azure cli
az keyvault certificate download --file cert.pem --vault-name {} --name {}
and then 
az login --service-principal --username $servicePrincipalId --tenant $tenantId --password cert.pem
And got the exact same error

**Comment by jiasli** [comment]
@majorsmann, please share what your certificate looks like without the credential value. According to https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#certificate-based-authentication, it should look like

```
-----BEGIN PRIVATE KEY-----
myPrivateKeyValue
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
myCertificateValue
-----END CERTIFICATE-----
```

**Comment by jiasli** [comment]
@elqian, certificate downloaded by `az keyvault certificate download` doesn't have the private key part:

```
> az keyvault certificate download -h

Command
    az keyvault certificate download : Download the public portion of a Key Vault certificate.
        The certificate formatted as either PEM or DER. PEM is the default.
```

Please see https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#retrieve-certificate-from-key-vault

**Comment by elqian** [comment]
I now use the following:
az keyvault secret download --file cert.pfx --encoding base64 -n name --vault-name vaultName  && \openssl pkcs12 -in cert.pfx -passin pass: -out cert.pem -nodes

 az login --service-principal --username $servicePrincipalId --tenant $tenantId --password cert.pem

now I get an error of "ERROR: AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found.,"

Do you know what's the root cause?

Thank you!
Elisa

**Comment by jiasli** [comment]
@elqian, this is because the certificate you used is not added to the **Certificates & secrets** setting of the service principal.

For example, when no certificate is added to a service principal:

![image](https://user-images.githubusercontent.com/4003950/161543876-04639012-2643-4d9d-8835-40844510f5bb.png)

Logging in with a certificate will result in error:

```
> az login --service-principal --username eb81c7c5-729c-4884-9fa0-343c4badd294 --password C:\Users\name\tmpk5xurg_u.pem --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: 'E1971492F364D2618F8485042B8E44B10A79929C', Please visit the Azure Portal, Graph Explorer or directly use MS Graph to see configured keys for app Id 'eb81c7c5-729c-4884-9fa0-343c4badd294'. Review the documentation at https://docs.microsoft.com/en-us/graph/deployments to determine the corresponding service endpoint and https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http to build a query request URL, such as 'https://graph.microsoft.com/beta/applications/eb81c7c5-729c-4884-9fa0-343c4badd294'].
Trace ID: cdc89483-3de1-47bf-a481-07b480f8f400
Correlation ID: a8eb8606-d61e-49e4-817b-0dfab6cc6e6c
Timestamp: 2022-04-04 12:28:46Z
```
