### ISSUE TITLE
Azure cli ml extension on M1 Mac cannot be installed

### ISSUE THREAD

**Issue by dhoeltgen** [Azure/azure-cli#21416]
**Describe the bug**
ml extension cannot be installed using Homebrew on an M1 Mac following the guide:
1) https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-macos
2) https://docs.microsoft.com/de-de/azure/machine-learning/reference-azure-machine-learning-cli

```
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      =============================DEBUG ASSISTANCE=============================

  error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/azure-cli/2.33.1/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/wg/1y6gg0js6rzfd8dtrjpxhyj00000gq/T/tmp7sgu1q1f
  cwd: /private/var/folders/wg/1y6gg0js6rzfd8dtrjpxhyj00000gq/T/pip-install-bo4v6upk/cryptography_6c903b69483f4cfcbef55e4d4ccf4261
  Building wheel for cryptography (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 375, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Removed build tracker: '/private/var/folders/wg/1y6gg0js6rzfd8dtrjpxhyj00000gq/T/pip-req-tracker-41anz500'

cli.azure.cli.core.extension.operations: Command '['/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/user/.azure/cliextensions/ml', '/var/folders/wg/1y6gg0js6rzfd8dtrjpxhyj00000gq/T/tmp12hwthfb/ml-2.1.2-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /Users/user/.azure/cliextensions/ml
cli.azure.cli.core.util: Failed to delete '/Users/user/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/user/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/user/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/user/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/user/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/user/.azure/cliextensions/ml'. Retrying ...
cli.azure.cli.core.util: Failed to delete '/Users/user/.azure/cliextensions/ml': [Errno 2] No such file or directory: '/Users/user/.azure/cliextensions/ml'. You may try to delete it manually.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 339, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/homebrew/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x105f57ac0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 14.053 seconds (init: 0.038, invoke: 14.015)
telemetry.save: Save telemetry record of length 3227 in cache
telemetry.check: Negative: The /Users/user/.azure/telemetry.txt was modified at 2022-02-23 17:47:12.087062, which in less than 600.000000 s
```

**To Reproduce**
`brew update && brew install azure-cli`
`az login`
`az extension add -n azure-cli-ml --debug`

**Expected behavior**
ml extension installs without problems

**Environment summary**
```
macOS-12.2.1-arm64-64bit, 
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.1
```
Same error on a colleague's M1 Mac with python 3.9.10 (does work fine on another colleagues Intel Mac though)

**Additional context**
`az extension add -n ml --debug` seems to return the exact same error.
Using the script for linux seems to work #20947 but that's not the recommended way of doing it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@dhoeltgen Since the error is when building cryptography, could you follow the steps in [their doc](https://cryptography.io/en/latest/installation/#building-cryptography-on-macos). There are commands which install dependencies like rust and openssl which are required.

I suppose the problem might be that there isn't a statically linked wheel for ARM64 perhaps.

**Comment by dhoeltgen** [comment]
@PramodValavala-MSFT yes, thank you! That was the right hint! It works with:
`xcode-select --install`
`brew install openssl@1.1 rust`
`env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" CFLAGS="-I$(brew --prefix openssl@1.1)/include" az extension add -n azure-cli-ml --debug`

**Comment by JuvenileLocksmith** [comment]
This did not work for me. Been at it for two hours, now resigned. This seemed to be the most promising solution. Odd that issue remains unresolved seven months on. 

[errors-arm64-wheel.txt](https://github.com/Azure/azure-cli/files/12545900/errors-arm64-wheel.txt)

**Comment by dani16antonio** [comment]
> z extension add -n azure-cli-ml --debug

Thanks, I had the same issue and this worked for me.

**Comment by dani16antonio** [comment]
> @PramodValavala-MSFT yes, thank you! That was the right hint! It works with: `xcode-select --install` `brew install openssl@1.1 rust` `env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" CFLAGS="-I$(brew --prefix openssl@1.1)/include" az extension add -n azure-cli-ml --debug`

z extension add -n azure-cli-ml --debug

Thanks, I had the same issue and this worked for me.
