### ISSUE TITLE
Unable to pass JSON file to Azure CLI

### ISSUE THREAD

**Issue by callumhester** [Azure/azure-cli#21418]
## Describe the bug
When the below command is run, a unknown error appears. I am trying to update my AKS resource with Diagnostic settings with the use of 2 JSON files for metics and logs.

**Command Name**
az monitor diagnostic-settings create --resource $aksid -n akslogging --event-hub-rule $ehid --workspace $logid --logs '@akslogs.json' --metrics  '@aksmetrics.json' 

**Errors:**
The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Cannot deserialize as [MetricSettings] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [MetricSettings] an object of type <class 'dict'>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.DeserializationError: Cannot deserialize as [MetricSettings] an object of type <class 'dict'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/monitor/operations/diagnostics_settings.py", line 28, in create_diagnostics_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/monitor/v2017_05_01_preview/operations/_diagnostic_settings_operations.py", line 154, in create_or_update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1645, in deserialize_iter
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [MetricSettings] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [MetricSettings] an object of type <class 'dict'>

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
Expected to create diagnostic setting of for AKS. 
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI
azure-cli 2.33.0 *
Extensions:
Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
akslogs.JSON
[{
    "category": "kube-apiserver",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "kube-audit",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "kube-audit-admin",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "kube-controller-manager",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "kube-scheduler",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "cluster-autoscaler",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "cloud-controller-manager",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "guard",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "csi-azuredisk-controller",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "csi-azurefile-controller",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
},
{
    "category": "csi-snapshot-controller",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
}]

AKSmetrics.Json

{
    "category": "AllMetrics",
    "enabled": true,
    "retentionPolicy": {
        "enabled": true,
        "days": 1
    }
}

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
Hi,
     For AKSmetrics.Json file, you should add a '[ ]' (as below), then try again, best wishes.

   [{
"category": "AllMetrics",
"enabled": true,
"retentionPolicy": {
"enabled": true,
"days": 1
}
}]

**Comment by callumhester** [comment]
> Hi, For AKSmetrics.Json file, you should add a '[ ]' (as below), then try again, best wishes.
> 
> [{ "category": "AllMetrics", "enabled": true, "retentionPolicy": { "enabled": true, "days": 1 } }]

I've added '[]' to the metrics file but it still fails. It looks to be failing on the AKSlogs.json file rather then the aksmetics.json file.

Thanks
