### ISSUE TITLE
failure on az ask install-cli MacOS

### ISSUE THREAD

**Issue by jreynolds0962** [Azure/azure-cli#21412]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 805, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/var/folders/2c/0dp_h1rj5w77lbpvn1jg95mr0000gn/T/tmpegdo9pk2/bin/darwin_arm64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 362, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version,
  File "/opt/homebrew/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 489, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 825, in move
    copy_function(src, real_dst)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SubhashVasarapu-MSFT** [comment]
@jreynolds0962, could you please try running this in command in "sudo" command or in any other directory that you have permissions in?
