### ISSUE TITLE
az aks get-credentials API issus

### ISSUE THREAD

**Issue by lastnod** [Azure/azure-cli#21411]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2021-10-01 does not have operation group 'managed_clusters'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/_client_factory.py", line 22, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerservice/_container_service_client.py", line 404, in managed_clusters
    raise ValueError("API version {} does not have operation group 'managed_clusters'".format(api_version))
ValueError: API version 2021-10-01 does not have operation group 'managed_clusters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {} --subscription {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.33, Kali GNU/Linux Rolling
Python 3.9.10
Installer: DEB

azure-cli 2.33.1

Extensions:
azure-devops 0.23.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
aks

**Comment by SaurabhSharma-MSFT** [comment]
@lastnod I do not think it is supported on the Debian version you are using.  Can you please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Azure CLI on stable/GA versions of Debian, like 11 Bullseye.
