### ISSUE TITLE
{monitor} when execute 'az monitor app-insights metrics get-metadata --app ', CLI shows error:"__init__() missing 1 required keyword-only argument: 'error'"

### ISSUE THREAD

**Issue by YuanyuanNi** [Azure/azure-cli#21438]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

when execute 'az monitor app-insights metrics get-metadata --app ', CLI shows error:__init__() missing 1 required keyword-only argument: 'error', see below for detail:
The command failed with an unexpected error. Here is the traceback:
__init__() missing 1 required keyword-only argument: 'error'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\v-tinani\.azure\cliextensions\application-insights\azext_applicationinsights\custom.py", line 49, in get_metrics_metadata
    return client.metrics.get_metadata(get_id_from_azure_resource(cmd.cli_ctx, application, resource_group=resource_group_name))
  File "C:\Users\v-tinani\.azure\cliextensions\application-insights\azext_applicationinsights\vendored_sdks\applicationinsights\operations\metrics_operations.py", line 268, in get_metadata
    raise models.ErrorResponseException(self._deserialize, response)
  File "C:\Users\v-tinani\.azure\cliextensions\application-insights\azext_applicationinsights\vendored_sdks\applicationinsights\models\error_response_py3.py", line 49, in __init__
    super(ErrorResponseException, self).__init__(deserialize, response, 'ErrorResponse', *args, **kwargs)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 173, in __init__
TypeError: __init__() missing 1 required keyword-only argument: 'error'
To open an issue, please run: 'az feedback'
**To Reproduce**

execute 'az monitor app-insights metrics get-metadata --app  appid 
**Expected behavior**

 'az monitor app-insights metrics get-metadata --app ' will execute correctly and data will be responded in json 
**Environment summary**

azure-cli                         2.33.1

core                              2.33.1
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.54
application-insights              0.1.14
front-door                        1.0.16
**Additional context**

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
SDK issue
