### ISSUE TITLE
Failed to create a ADLS directory using a SAS token

### ISSUE THREAD

**Issue by valrusu** [Azure/azure-cli#21452]
## Describe the bug

**Command Name**
`az storage fs directory create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
element indices must be integers
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_path_client.py", line 201, in _create
    return self._client.path.create(**options)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_generated/operations/_path_operations.py", line 248, in create
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'An HTTP header that's mandatory for this request is not specified.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 370, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_data_lake_directory_client.py", line 162, in create_directory
    return self._create('directory', metadata=metadata, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_path_client.py", line 203, in _create
    process_storage_error(error)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2020_02_10/_deserialize.py", line 98, in process_storage_error
    additional_data[info] = error_body[info]
TypeError: element indices must be integers

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs directory create --file-system {} --name {} --connection-string {} --sas-token {}`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.0 *
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Please provide either `--connection-string` or `--sas-token`(need to be used with `--account-name`), don't use them together.
