### ISSUE TITLE
az login fails

### ISSUE THREAD

**Issue by Qi77Qi** [Azure/azure-cli#21464]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ClientApplication.__init__() got an unexpected keyword argument 'http_cache'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 164, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 101, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/usr/local/lib/python3.9/site-packages/msal/application.py", line 1360, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: ClientApplication.__init__() got an unexpected keyword argument 'http_cache'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-11.6.2-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.1

Extensions:
account 0.2.1
image-copy-extension 0.2.8

Dependencies:
msal 1.14.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The call stack shows it is Azure CLI 2.33.0 running on Python 3.10:

```
/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py
```

It calls MSAL 1.14.0 from Python 3.9's system `site-packages`:

```
/usr/local/lib/python3.9/site-packages/msal/application.py
```

And Environment Summary shows it is 

```
azure-cli 2.33.1
```

I am not sure how the environment becomes so complex. 😅

Since we have set `system_site_packages: false` in the Homebrew formula (https://github.com/Azure/azure-cli/pull/19663), system `site-packages` (`/usr/local/lib/python3.9/site-packages`) shouldn't be access at all. It seems something went wrong. @carlocab, I was wondering if you have any clue on why this is happening.

@Qi77Qi, could you follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos to reinstall Azure CLI and try again? If it fails, could you share the new call stack?

**Comment by Qi77Qi** [comment]
Apologies that I forgot about this issue. Think I was able to resolve it by using a different python version back then
