### ISSUE TITLE
Failed connect from visual code to Azure Ubuntu VM, any method to run applications on the Azure Linux VMs?

### ISSUE THREAD

**Issue by billxu2007** [Azure/azure-cli#21466]
## Describe the bug

**Command Name**
`az network bastion ssh`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The extension ssh is not installed.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8097, in ssh_bastion_host
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8030, in _test_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 340, in get_extension
azure.cli.core.extension.ExtensionNotInstalledException: The extension ssh is not installed.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion ssh --name {} --resource-group {} --target-resource-id {} --auth-type {} --username {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@billxu2007 Thanks for reaching out to us. Could you please run the below command to install the _ssh_ extension ?

`az extension add --name ssh` 

Then you can run [this](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#az-network-bastion-ssh) command and check if that works. Please let me know if you face any issues. Awaiting you reply.

**Comment by billxu2007** [comment]
Hi,

Thank you very much for your help!
1. Can I put the password in the parameters too for this command?
az network bastion ssh --name MyBastionHost --resource-group
MyResourceGroup --target-resource-id vmResourceId --auth-type password
--username xyz

2. after the SSH authentication, in powershell terminal, I can manual enter
the mount share file command, but in script,
If I want to run the linux command to mount a shortage share file inside an
Azure cli command,
should I use the
az vm run-command invoke -g MyResourceGroup -n MyVm --command-id
RunShellScript --scripts "sudo apt-get update && sudo apt-get install -y
nginx"

or any video or example for this?

My main purpose is connecting to each Linux Servers, downloading the
installation file, then installing it as root in the Linux server.

Thanks,
Bill Xu

**Comment by billxu2007** [comment]
Hi

After the bastion SSH connection command, then it will open the terminal of
the VM.
But I need to run a script file to connect, mount share storage, download
the file, then install the app.

Any suggestions to run the whole process as a CLI script?

Thanks,
Bill Xu

PS D:\Work\TC3oE> az network bastion ssh  `
>>     --name $myBastionHost `
>>     --resource-group $resourceGroupName `
>>     --target-resource-id $targetId `
>>     --auth-type password `
>>     --username xubi

Command group 'network bastion' is in preview and under development.
Reference and support levels: https://aka.ms/CLI_refstatus
***@***.***'s password:
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-1014-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Mar  2 13:40:08 UTC 2022

  System load:  0.02               Processes:             241
  Usage of /:   12.9% of 28.90GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 172.23.0.5
  Swap usage:   0%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

16 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


*** System restart required ***
Last login: Mon Feb 28 19:03:47 2022 from 172.23.1.4
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

***@***.***:~$ ls
***@***.***:~$ whoami
xubi
***@***.***:~$ ls /home/xubi

**Comment by navba-MSFT** [comment]
@billxu2007 Thanks for getting back. I am providing a few suggestions here, inline with your questions:

_1. Can I put the password in the parameters too for this command?_
>Here is the sample command:
>
>az network bastion ssh --name MyBastionHost --resource-group MyResourceGroup --target-resource-id vmResourceId --auth-type password --username xyz



_2. After the SSH authentication, in powershell terminal, I can manual enter the mount share file command, but in script,
If I want to run the linux command to mount a shortage share file inside an Azure cli command, should I use the
az vm run-command invoke -g MyResourceGroup -n MyVm --command-id RunShellScript --scripts "sudo apt-get update && sudo apt-get install -y nginx" or any video or example for this?_
 >Run-Command has a few restrictions which are explained [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command#restrictions). The bash script to perform manual on-demand share mount is [here](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux?tabs=smb311#mount-the-azure-file-share-on-demand-with-mount). The bash script to automatically mount the file share is [here](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux?tabs=smb311#automatically-mount-file-shares). Also If you wish to download the file from Azure File Storage without mounting the share on linux, you can refer [this](https://docs.microsoft.com/en-us/cli/azure/storage/file?view=azure-cli-latest#az-storage-file-download) article.
 
 
 _3. Any suggestions to run the whole process as a CLI script?_
 > I couldn't find the custom script in github which serves all the above requirement. So you need to tweak the above commands accordingly to achieve this ask. 
 
 Hope this helps.

**Comment by navba-MSFT** [comment]
@billxu2007 I wanted to do quick follow-up to check if you have any follow-up questions on this. Awaiting your reply.

**Comment by billxu2007** [comment]
Thank you very much for your email, my client changed his plan, use another
way to do it since this way is a manual operation.

Thanks again
Bill Xu

**Comment by navba-MSFT** [comment]
@billxu2007 Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by billxu2007** [comment]
Great, thanks!

Thank you very much for your help again!

Cheers,
Bill Xu
