### ISSUE TITLE
NotImplementedError when running: az acr credential show

### ISSUE THREAD

**Issue by andrescodas** [Azure/azure-cli#21498]
## Describe the bug

**Command Name**
`az acr credential show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
APIVersion 2021-06-01-preview is not available
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 352, in handler
    client = self.client_factory(self.cli_ctx) if self.client_factory else None
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/acr/_client_factory.py", line 21, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/containerregistry/container_registry_management_client.py", line 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2021-06-01-preview is not available

```

## To Reproduce:

- `az acr credential show --name tappcontainerregistry.azurecr.io`

## Expected Behavior

- no error

## Environment Summary
```
Linux-5.4.0-99-generic-x86_64-with-glibc2.2.5, Debian GNU/Linux 11 (bullseye)
Python 3.8.12
Installer: PIP

azure-cli 2.32.0 *

Extensions:
ml 2.0.3

Dependencies:
msal 1.16.0
azure-mgmt-resource 16.0.0
```

**Comment by SubhashVasarapu-MSFT** [comment]
@andrescodas, please retry by updating the Azure-cli to the latest version. Do let us know if you are still not able to bypass this issue.

**Comment by andrescodas** [comment]
works after updating.  Thanks!
