### ISSUE TITLE
AZ LOGIN ISSUE: TypeError: __init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by dfuture** [Azure/azure-cli#21501]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/home/future/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 177, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 746, in find_using_common_tenant
    client = self._create_subscription_client(credential)
  File "/home/future/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 837, in _create_subscription_client
    client = client_type(credential, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.1 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.32.0 *

Extensions:
resource-graph 1.0.0
azure-devops 0.17.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 8.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/21189#issuecomment-1031018427
