### ISSUE TITLE
system topic subscription update causes error: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'`

### ISSUE THREAD

**Issue by kensykora** [Azure/azure-cli#21521]
**Describe the bug**

Trying to call `az eventgrid system-topic event-subscription update` causes error `AttributeError: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'`

**To Reproduce**

1. Create a system topic on a storage account.
2. Create a subscription to that topic. In my use case, I was delivering to a service bus topic with a managed identity access.
3. Run `az eventgrid system-topic event-subscription update --name mysubscription--resource-group myrg --system-topic-name mysystemtopic --delivery-attribute-mapping label dynamic subject`

**Expected behavior**

Delivery property is added with `label` using dynamic type and has the value of `subject`

**Actual behavior**

```
The command failed with an unexpected error. Here is the traceback:
'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/eventgrid/custom.py", line 1198, in cli_system_topic_event_subscription_update
    params = _update_event_subscription_internal(
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/eventgrid/custom.py", line 1378, in _update_event_subscription_internal
    current_destination_with_resource_identity.destination,
AttributeError: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'
```

**Environment summary**

```
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Extensions:
azure-iot                         0.13.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/ken/.azure/cliextensions'

Python (Linux) 3.8.12 (default, Mar  2 2022, 07:26:21) 
[GCC 9.3.0]
```

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kensykora Thanks for reaching out to us. I am doing some research on this issue. I was able to run this command successfully without enabling the managed identity. Could you please test the same at your end ? Awaiting your reply.

**Comment by kensykora** [comment]
Hi @navba-MSFT I can confirm it works correctly when I do not have managed identity enabled. However, for my use case I want to use managed identity for the connection. Thanks for looking into it!

**Comment by navba-MSFT** [comment]
@kensykora Thanks for getting back. I am looking into this issue. I will get back to you once I have an update.

**Comment by kensykora** [comment]
I was able to work around this with an `az rest` call. If you'll excuse the terraform -- I think you can get the gist of it though. Looks like it actually needs `deliveryWithResourceIdentity` property instead of `delivery` property.

```hcl
resource "null_resource" "subject_delivery_property" {
  triggers = {
    id = azurerm_eventgrid_system_topic_event_subscription.sub.id
    body = jsonencode({
      deliveryWithResourceIdentity = {
        identity = {
          type = "SystemAssigned"
        }
        destination = {
          endpointType = "ServiceBusTopic",
          properties = {
            resourceId = azurerm_servicebus_topic.integration.id,
            deliveryAttributeMappings = [
              {
                name = "label",
                type = "dynamic",
                properties = {
                  sourceField = "subject"
                }
              }
            ]
          }
        }
      }
    })
  }

  provisioner "local-exec" {
    command = <<BASH
      az rest \
        --method patch \
        --headers Content-Type=application/json \
        --url https://management.azure.com${self.triggers.id}?api-version=2021-06-01-preview \
        --body ${replace(self.triggers.body, "\"", "\\\"")}
    BASH
  }
}
```

**Comment by navba-MSFT** [comment]
@kensykora Thanks for getting back to us and reporting this bug. Our Product Owners have confirmed this issue as a bug and they are working on the fix. We will keep you updated about the release.

**Comment by navba-MSFT** [comment]
PR #21615 for the fix has been created
