### ISSUE TITLE
Enable autorotation for an existing cluster

### ISSUE THREAD

**Issue by DanJoh74** [Azure/azure-cli#21538]
## Describe the bug

Enable autorotation for an existing cluster as [described here](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation) results in `The command failed with an unexpected error`.

**Command Name**
`az aks update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2369, in aks_update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 6061, in update_default_mc_profile
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 6007, in update_addon_profiles
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 5941, in update_azure_keyvault_secrets_provider_addon_profile
TypeError: 'NoneType' object does not support item assignment

```

## To Reproduce:
Enable autorotation for an existing cluster as [described here](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation).

## Expected Behavior
Autorotation enabled.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@DanJoh74 Apologies for late reply. I was able to run the below command for my existing AKS cluster:

>az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup

>az aks update -g myResourceGroup -n myAKSCluster --enable-secret-rotation

I am sending you the az version that I used. Could you please try with the same and let me know if you face any issues? Awaiting your reply.

>az version
{
"azure-cli": "2.32.0",
"azure-cli-core": "2.32.0",
"azure-cli-telemetry": "1.0.6",
"extensions": {
"aks-preview": "0.5.51",
"application-insights": "0.1.14",
"blueprint": "0.3.1",
"storage-blob-preview": "0.6.1"
}
}

Similar issue #20438. Hope this helps. Please let me know if you face any issues with the above command.

**Comment by navba-MSFT** [comment]
@DanJoh74 I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@DanJoh74 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
