### ISSUE TITLE
az devops command throw an exception

### ISSUE THREAD

**Issue by anassk** [Azure/azure-cli#21560]
## Describe the bug

**Command Name**
`az devops`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azext_devops.dev.team.credentials#credential_set' is invalid.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\akeddo\.azure\cliextensions\azure-devops\azext_devops\dev\team\credentials.py", line 15, in <module>
    from azext_devops.dev.common._credentials import clear_credential, set_credential
  File "C:\Users\akeddo\.azure\cliextensions\azure-devops\azext_devops\dev\common\_credentials.py", line 10, in <module>
    from .credential_store import CredentialStore
  File "C:\Users\akeddo\.azure\cliextensions\azure-devops\azext_devops\dev\common\credential_store.py", line 11, in <module>
    from .config import AZ_DEVOPS_GLOBAL_CONFIG_DIR
  File "C:\Users\akeddo\.azure\cliextensions\azure-devops\azext_devops\dev\common\config.py", line 37, in <module>
    azdevops_config.config_parser.read(AZ_DEVOPS_GLOBAL_CONFIG_PATH)
  File "configparser.py", line 697, in read
  File "configparser.py", line 1017, in _read
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 116: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2009, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2009, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1858, in take_action
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 275, in _get_values
  File "argparse.py", line 2399, in _get_values
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 326, in _check_value
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 201, in get_examples
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 192, in get_examples
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 303, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 241, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
ValueError: The operation 'azext_devops.dev.team.credentials#credential_set' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
account 0.2.2
ad 0.1.0
azure-devops 0.23.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@anassk Are you using a PAT token to connect to azure devops  ? Which `az devops` subcommand it is failing?

**Comment by anassk** [comment]
@SaurabhSharma-MSFT  i used 

`az login`

and already set : 

`az devops configure --defaults organization=https://myorganisation.visualstudio.com/`

**Comment by SaurabhSharma-MSFT** [comment]
@anassk Redirecting this to respective to look into this.

**Comment by v-anvashist** [comment]
@anassk.We are not able to repro this issue. Please provide the detailed steps if possible to test the complete scenario in our system.

**Comment by anassk** [comment]
@v-anvashist  all what i do is launching a powershell console and trying a `az devops`
I even tried to remove and add again the devops extension but still have same exception
![az_devops_error2](https://user-images.githubusercontent.com/4243614/159686930-86811887-8deb-4142-8eec-da13efeb371f.png)

**Comment by v-anvashist** [comment]
@anassk  Could you please check the azure devops CLI extension version again in your machine and if possible share the screenshot.

We are using 0.24.0  and az devops command is working fine in our machine.

**Comment by anassk** [comment]
@v-anvashist  it was working fine and it just stopped in the same session where it was working...

![az_devops_error3](https://user-images.githubusercontent.com/4243614/159734230-d7aafc52-5869-41fa-8f8e-001b62409beb.png)

**Comment by v-anvashist** [comment]
@anassk Can you please uninstall the azure CLI and install it again  and check if it would work for you?

**Comment by anassk** [comment]
@v-anvashist  even after reinstalling azure CLI still have same problem, it seems to be a problem with devops extention since if i execute command under cli it works fine but when trying any devops command it fails, for example i just tried 
![az_devops_error4](https://user-images.githubusercontent.com/4243614/159900074-6577a80f-b242-4f1c-967e-873f5802b4fb.png)
