### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'server_farm_id'

### ISSUE THREAD

**Issue by MarcusAPT** [Azure/azure-cli#21574]
## Describe the bug
Deploying an App Service and adding the VNET it fails and my script continues 
**Command Name**
az webapp vnet-integration add

**Errors:**
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4006, in add_webapp_vnet_integration
    return _add_vnet_integration(cmd, name, resource_group_name, vnet, subnet, slot, skip_delegation_check)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/appservice/custom.py", line 4023, in _add_vnet_integration
    parsed_plan = parse_resource_id(app.server_farm_id)
AttributeError: 'NoneType' object has no attribute 'server_farm_id'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1070-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
interactive 0.4.5
front-door 1.0.16
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by StrawnSC** [comment]
@MarcusAPT thanks for reporting. I  get the same error if I run the command on a webapp that doesn't exist. Could you verify that a webapp with the correct name/resource group exists in your subscription by running `az webapp show --name {} --resource-group {}`? 

I opened https://github.com/Azure/azure-cli/pull/21636 to ensure that a more helpful error message is returned in this case
