### ISSUE TITLE
az commands are failing including attempt to upgrade with `No module named 'azure.cli.core.azclierror'`

### ISSUE THREAD

**Issue by rohinibhagdikar** [Azure/azure-cli#21589]
All az commands are failing including attempt to upgrade with `No module named 'azure.cli.core.azclierror'`

`az login`

bash-4.4$ az upgrade
Error loading command module 'appservice': No module named 'azure.cli.core.azclierror'
Error loading command module 'keyvault': No module named 'azure.cli.core.azclierror'
Error loading command module 'resource': MGMT_RESOURCE_TEMPLATESPECS
Error loading command module 'storage': local variable 'command_loader' referenced before assignment
Error loading command module 'vm': cannot import name 'DISALLOWED_USER_NAMES'
This command is experimental and not covered by customer support. Please use with discretion.
The command failed with an unexpected error. Here is the traceback:

cannot import name 'get_latest_from_github'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in execute
    raise ex
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 665, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 574, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3.6/site-packages/azure/cli/command_modules/util/custom.py", line 47, in upgrade_version
    from azure.cli.core.util import get_latest_from_github
ImportError: cannot import name 'get_latest_from_github'

## To Reproduce:
- `az login`

## Environment Summary
```
Linux-4.9.125-linuxkit-x86_64-with
Python 3.6.9
Installer: PIP

azure-cli 2.15.1

```

**Comment by rohinibhagdikar** [comment]
Azure packages in use:
azure-cli==2.15.1
azure-mgmt-network==12.0.0
azure-mgmt-resource==10.2.0
azure-cli-core==2.5.1 
azure-cli-nspkg==3.0.4 
azure-cli-telemetry==1.0.4 
azure-common==1.1.25 
azure-core==1.5.0 
azure-mgmt-compute==11.1.0 
azure-mgmt-core==1.0.0 
azure-mgmt-resource==9.0.0 
azure-mgmt-storage==10.0.0 
azure-nspkg==3.0.2 
azure-storage-blob==2.1.0 
azure-storage-common==2.1.0

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by rohinibhagdikar** [comment]
Issue got resolved. It was being caused by some packages getting pinned to much lower versions causing import issues. 
List of lower version packages:
azure-cli-core==2.5.1 azure-cli-nspkg==3.0.4 azure-cli-telemetry==1.0.4 azure-common==1.1.25 azure-core==1.5.0 azure-mgmt-compute==11.1.0 azure-mgmt-core==1.0.0 azure-mgmt-resource==9.0.0 azure-storage-common==2.1.0


I am closing this thread.

**Comment by jiasli** [comment]
`azure-cli 2.15.1` is a very old version. Please install the latest version of `azure-cli` and do not pin internal packages (such as `azure-cli-core`, `azure-mgmt-resource`) by your self.
