### ISSUE TITLE
azure cli error about azure bastion

### ISSUE THREAD

**Issue by seullee-me** [Azure/azure-cli#21619]
## Describe the bug

**Command Name**
`az network bastion tunnel`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 7836, in create_bastion_tunnel
    tunnel_server = get_tunnel(cmd, resource_group_name, bastion_host_name, target_resource_id, resource_port, port)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 7829, in get_tunnel
    tunnel_server = TunnelServer(cmd.cli_ctx, 'localhost', port, bastion, vm_id, resource_port)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/tunnel.py", line 59, in __init__
    self.sock.bind((self.local_addr, self.local_port))
PermissionError: [Errno 13] Permission denied

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion tunnel --name {} --resource-group {} --target-resource-id {} --resource-port {} --port {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
deploy-to-azure 0.2.0

```

**Comment by seullee-me** [comment]
Resolved the issue

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@seullee-me Thanks for reaching out to us. Could you please let me know if you have any proxy in your corporate network ? If Yes, could you try to bypass it and check if that helps? Also could you please test the same command using the Azure Cloud Shell[ TryIt option](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#code-try-14) and check if that works? Awaiting your reply.

**Comment by seullee-me** [comment]
Hello, there.

Issue is resolved.
Thanks for your supports


2022년 3월 14일 (월) 오후 3:32, navba-MSFT ***@***.***>님이 작성:

**Comment by navba-MSFT** [comment]
@seullee-me Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
