### ISSUE TITLE
az login not working properly: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ruthvik123** [Azure/azure-cli#21612]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit
Python 3.9.10
Installer: PIP

azure-cli 2.22.0 *

```

**Comment by ruthvik123** [comment]
because of the breaking changes caused due to az-cli 2.30 i installed the older version using pip3 install azure-cli==2.22.0

It was installed fine and when i do az --version it works fine. But when I do az login i get the following exceptions:
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/__init__.py", line 807, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 186, in find_subscriptions_on_login
    self._creds_cache.adal_token_cache)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 1139, in adal_token_cache
    return self.load_adal_token_cache()
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 1145, in load_adal_token_cache
    self._load_service_principal_creds(all_entries)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 1172, in _load_service_principal_creds
    if c.get(_SERVICE_PRINCIPAL_ID):
AttributeError: 'str' object has no attribute 'get'

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
2.22.0 is very old version. Please install the latest 2.34.1, delete `~/.azure` and re-run `az login.

**Comment by ruthvik123** [comment]
Np, I figured it out. It was just version mismatches in libs. Unfortunately az-cli with version > 2.30 has some breaking changes introduced and I needed the older versions. I had to uninstall python 3.9 and re install 3.7 and then install az-cli version 2.29.2. Then it worked. It was just  version mismatches amongst all the packages. 
Thanks for the help. 
-Ruth

**Comment by jrmanisme** [comment]
Getting same issue with 2.46 and 2.45 but not with 2.35, it seems a bug was introduced in the mean time version ... have to test each one @https://github.com/Azure/azure-cli-extensions/issues/5986
