### ISSUE TITLE
Not able to login using az login

### ISSUE THREAD

**Issue by logan-1999** [Azure/azure-cli#21616]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Current epoch = 1647052461.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1647071960,
  "nbf": 1647071960,
  "exp": 1647075860,
  "aio": "AWQAm/8TAAAAD5XQ4zFzM/6ir5nG4Mni3ioR3WFIYpmQHiYFhUxt9V5KZZqNGH5KJJ/o5PaDgZpcFzczf13nfVUuB0uSCMWv/wqq5cKuXL3r/N2tgI8yLCR9UrTxo7EiBFYZKamVIaMp",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "53b848a9ad98658239e61116c590e71aeb45987bc9a105c484cda3560300dd39",
  "preferred_username": "sajal.bera.58@outlook.com",
  "prov_data": [
    {
      "at": true,
      "prov": "linkedin.com",
      "altsecid": "DgGCV1yfhUZNNAj4SiYrm21pCfAdAr5wahPhEH42NGQ"
    },
    {
      "at": true,
      "prov": "samsung.com",
      "altsecid": "bwAuQ88oHAjujObSMs9_WIX7MmMUyxnHA2PGrbBbRUQ"
    }
  ],
  "rh": "0.AXIAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBADY.",
  "sub": "aqAIoJXAVdhp0YflEzqsaF6J3-tTyj5JTwWsSpvCFPE",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "VAwx3BbtBkSM-yAQpaXHAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1546, in acquire_token_interactive
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 135, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 152, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 76, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Current epoch = 1647052461.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1647071960,
  "nbf": 1647071960,
  "exp": 1647075860,
  "aio": "AWQAm/8TAAAAD5XQ4zFzM/6ir5nG4Mni3ioR3WFIYpmQHiYFhUxt9V5KZZqNGH5KJJ/o5PaDgZpcFzczf13nfVUuB0uSCMWv/wqq5cKuXL3r/N2tgI8yLCR9UrTxo7EiBFYZKamVIaMp",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "53b848a9ad98658239e61116c590e71aeb45987bc9a105c484cda3560300dd39",
  "preferred_username": "sajal.bera.58@outlook.com",
  "prov_data": [
    {
      "at": true,
      "prov": "linkedin.com",
      "altsecid": "DgGCV1yfhUZNNAj4SiYrm21pCfAdAr5wahPhEH42NGQ"
    },
    {
      "at": true,
      "prov": "samsung.com",
      "altsecid": "bwAuQ88oHAjujObSMs9_WIX7MmMUyxnHA2PGrbBbRUQ"
    }
  ],
  "rh": "0.AXIAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBADY.",
  "sub": "aqAIoJXAVdhp0YflEzqsaF6J3-tTyj5JTwWsSpvCFPE",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "VAwx3BbtBkSM-yAQpaXHAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by logan-1999** [comment]
I found my system's time was behind 5 hrs, I synchronized it with current time and it works just charm.

Don't know how to close this issue on Git, please close it :) 
Thanks.

**Comment by jiasli** [comment]
@logan-1999, glad to know the issue is solved. We'll refine the error message in next version.
