### ISSUE TITLE
'charmap' codec can't encode characters in position 258-264: character maps to <undefined>

### ISSUE THREAD

**Issue by SerhiiZavalko** [Azure/azure-cli#21703]
## Describe the bug

**Command Name**
`az container logs`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'charmap' codec can't encode characters in position 258-264: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 560, in container_logs
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 258-264: character maps to <undefined>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container logs --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@SerhiiZavalko Is your resource name containing any Unicode characters?

**Comment by SerhiiZavalko** [comment]
@SaurabhSharma-MSFT No, but I suppose stdout containing such characters. This error occurs only with `az logs` command.

**Comment by williamhbell** [comment]
> @SerhiiZavalko Is your resource name containing any Unicode characters?

No, the resource name only contains normal ASCII characters.  The issue is in the pip progress character.

**Comment by williamhbell** [comment]
> @SaurabhSharma-MSFT No, but I suppose stdout containing such characters. This error occurs only with `az logs` command.

Yes, it is the stdout that is associated with the pip install progress characters.

**Comment by esdccs1** [comment]
This happned to me as well, I was trying to build a docker container on a windows VM targeting a linux environment

```
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 3564: character maps to <undefined>
```

**Comment by idrisfl** [comment]
Got the same error. Any updates or fixes?

**Comment by klemmchr** [comment]
Having same issue on Windows

```
22:14:52 [DBG] ERROR: The command failed with an unexpected error. Here is the traceback:
22:14:52 [DBG] (Reading database ... 10312 files and directories currently installed.)
22:14:52 [DBG]
22:14:52 [DBG] Preparing to unpack .../00-python3_3.8.2-0ubuntu2_amd64.deb ...
22:14:52 [DBG]
22:14:52 [DBG] ERROR: 'charmap' codec can't encode character '\u2192' in position 516: character maps to <undefined>
22:14:52 [DBG] Unpacking python3 (3.8.2-0ubuntu2) ...
22:14:52 [DBG] Traceback (most recent call last):
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
22:14:52 [DBG] Selecting previously unselected package libapparmor1:amd64.
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
22:14:52 [DBG] Preparing to unpack .../01-libapparmor1_2.13.3-7ubuntu5.3_amd64.deb ...
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
22:14:52 [DBG] Unpacking libapparmor1:amd64 (2.13.3-7ubuntu5.3) ...
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
22:14:52 [DBG] Selecting previously unselected package libcap2:amd64.
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
22:14:52 [DBG] Preparing to unpack .../02-libcap2_1%3a2.32-1ubuntu0.1_amd64.deb ...
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 47, in write
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 177, in write
22:14:52 [DBG] Unpacking libcap2:amd64 (1:2.32-1ubuntu0.1) ...
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 205, in write_and_convert
22:14:52 [DBG]
22:14:52 [DBG]   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 210, in write_plain_text
22:14:52 [DBG] Selecting previously unselected package libargon2-1:amd64.
22:14:52 [DBG]   File "encodings\cp1252.py", line 19, in encode
```

**Comment by Alan170306** [comment]
I have the same Issue, is there any solution?
