### ISSUE TITLE
az login fails with FRAME length exceeds system's maximum of 2147483647 bytes

### ISSUE THREAD

**Issue by rohitrg** [Azure/azure-cli#21704]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
FRAME length exceeds system's maximum of 2147483647 bytes
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 149, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 155, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 164, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 101, in _msal_app
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 87, in _msal_app_kwargs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 134, in _load_msal_http_cache
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 102, in _wrapped_func
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 115, in __load_msal_http_cache
OverflowError: FRAME length exceeds system's maximum of 2147483647 bytes

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0 *

Extensions:
account 0.2.1
init 0.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
I have tried 2.34.1 and 2.32.0 versions on Windows 10. Still fails

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
```
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 115, in __load_msal_http_cache
```

corresponds to 

https://github.com/Azure/azure-cli/blob/azure-cli-2.32.0/src/azure-cli-core/azure/cli/core/auth/identity.py#L115

https://github.com/Azure/azure-cli/blob/d04b359a45c7c92485ac590fcdf48caaf44a88b8/src/azure-cli-core/azure/cli/core/auth/identity.py#L115

@rayluo, looks like MSAL HTTP cache somehow got too big.
