### ISSUE TITLE
Az Login throwing an error: Connection reset by peer

### ISSUE THREAD

**Issue by ttevatia** [Azure/azure-cli#21710]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    **response_kw
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/lib/azure-cli/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/command_modules/profile/custom.py", line 148, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 153, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/auth/identity.py", line 177, in login_with_device_code
    flow = self._msal_app.initiate_device_flow(scopes, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/azure/cli/core/auth/identity.py", line 101, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/msal/application.py", line 1486, in __init__
    client_id, client_credential=None, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/msal/application.py", line 457, in __init__
    self.http_client, validate_authority=validate_authority)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/msal/authority.py", line 102, in __init__
    self._http_client)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/msal/authority.py", line 160, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/root/lib/azure-cli/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.18.0-193.47.1.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa, Red Hat Enterprise Linux 8.2 (Ootpa)
Python 3.7.9
Installer: 

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by ttevatia** [comment]
Any updates on this issue. The RHEL VM that we are using has been created on Azure only and still we are getting login issues. Maybe some package issues in Azure VMs?

**Comment by jiasli** [comment]
Looks like you can't access https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration

You may verify with

```
python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```
