### ISSUE TITLE
Permission denied on msal_token_cache.bin.lockfile

### ISSUE THREAD

**Issue by sanistaal-bbc** [Azure/azure-cli#21744]
## Describe the bug

We use Octopus to deploy websites to our Azure app services. Sometimes we get the error "**PermissionError: [Errno 13] Permission denied: 'C:\\Octopus\\Work\\20220322100442-6880-1549\\azure-cli\\msal_token_cache.bin.lockfile'** " when running AZ commands. It's not the same AZ command failing every time we get the error and re-running the command will be succesful.

**Command Name**
az webapp stop --name $WebApp --resource-group $ResourceGroup
az webapp config
az webapp start
az webapp stop

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback: 
March 22nd 2022 11:05:19Error
ERROR: [Errno 13] Permission denied: 'C:\\Octopus\\Work\\20220322100442-6880-1549\\azure-cli\\msal_token_cache.bin.lockfile' 
March 22nd 2022 11:05:19Error
Traceback (most recent call last): 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__ 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 160, in login 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 197, in login_with_service_principal 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1647, in acquire_token_for_client 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 753, in obtain_token_for_client 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 115, in _obtain_token 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 581, in <lambda> 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 307, in add 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 237, in __add 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 66, in modify 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/cache_lock.py", line 57, in __enter__ 
March 22nd 2022 11:05:19Error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/cache_lock.py", line 43, in _try_to_create_lock_file 
March 22nd 2022 11:05:19Error
PermissionError: [Errno 13] Permission denied: 'C:\\Octopus\\Work\\20220322100442-6880-1549\\azure-cli\\msal_token_cache.bin.lockfile' 
```

## To Reproduce:

- _Put any pre-requisite steps here..._
- `Can't reproduce. I happens occasionally and on any az command`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Windows Server 2016
Python 3.8.9
Installer: MSI

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@sanistaal-bbc Based on the previous discussion in the issue that you linked, looks like the one case where it is expected to hit this error is around the time the token expires. I am routing this the appropriate team to take a further look.

**Comment by sanistaal-bbc** [comment]
Hello. Any news on this issue? We still experience it a few times every week

**Comment by jiasli** [comment]
@rayluo, even though we improved concurrent read-write in https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/100 and https://github.com/Azure/azure-cli/pull/20408, looks like people are still facing issue during concurrent writes. 

@sanistaal-bbc, meanwhile, could you execute CLI commands in parallel? Or utilizing [`AZURE_CONFIG_DIR`](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#concurrent-builds) in order to isolate concurrent executions?

**Comment by rayluo** [comment]
@sanistaal-bbc mentioned
> We use Octopus to deploy websites to our Azure app services.

Do we know how many concurrent az commands were being run?

Did the symptom tend to happen during the first time you ran `az` or Octopus in the last 1+ hours (so that `az` would need to fetch in a new token and then write it), or would it still happen even when the same command was run successfully within the last hour?

**Comment by rayluo** [comment]
> Two of them can run at the same time, but no concurrent az commands will run on the same worker.

@sanistaal-bbc , were the "two of them" develop and QA? By any chance you can try to have them run sequentially? If that would become a workaround to bypass this, it would also give us a strong hint that it was indeed caused by the concurrency.

**Comment by sanistaal-bbc** [comment]
@rayluo Develop and QA will run at the same time and Develop and Production will run at the same time. But all three environments runs az commands on their om worker. I just went off for vacation and will be back in 3 weeks. I will try what you suggest when I'm back.

**Comment by sanistaal-bbc** [comment]
A late update after some weeks of testing this. I changed the setup to run sequentially and then we don't experience any issues with the lockfile. I'm not in doubt that the concurrency is causing the problem

**Comment by rayluo** [comment]
Thanks, @sanistaal-bbc , for sharing your latest progress above. Glad that workaround works.

@jiasli , I re-read this issue, quoted below.

> ## Describe the bug
> 
> We use Octopus to deploy websites to our Azure app services. Sometimes we get the error "**PermissionError: [Errno 13] Permission denied: 'C:\Octopus\Work\20220322100442-6880-1549\azure-cli\msal_token_cache.bin.lockfile'** " when running AZ commands. It's not the same AZ command failing every time we get the error and re-running the command will be succesful.
> 
> Same behaviour as this closed issue: #20273
> 
> **Command Name**
> az webapp stop
> az webapp config
> az webapp start
> 
> **Errors:**
> 
> ```
> ERROR: The command failed with an unexpected error. Here is the traceback: 
> March 22nd 2022 11:05:19Error
> ERROR: [Errno 13] Permission denied: 'C:\\Octopus\\Work\\20220322100442-6880-1549\\azure-cli\\msal_token_cache.bin.lockfile' 
> ```

@jiasli , you/we once suggested:

> @rayluo, even though we improved concurrent read-write in [AzureAD/microsoft-authentication-extensions-for-python#100](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/100) and #20408, looks like people are still facing issue during concurrent writes.
> 
> @sanistaal-bbc, meanwhile, could you execute CLI commands in parallel? Or utilizing [`AZURE_CONFIG_DIR`](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#concurrent-builds) in order to isolate concurrent executions?

But, the lockfile was already in a folder containing a datetime stamp, so it seems like their Azure CLI was always using a different/new folder.


> In Octopus we have a set of Workers (Windows VM's) deploying to Azure. And each worker lives in their own Octopus environment. There is a develop, QA and production.

> Develop and QA will run at the same time and Develop and Production will run at the same time. But all three environments runs az commands on their own worker.

@sanistaal-bbc, I don't know much about your setup. For your each run, does your workers (Windows VMs) always start afresh in a new directory "C:\Octopus\Work\YYYYmmddHHMMSS-????-????\azure-cli", so that each of your run would begin with an "az login"? And that login attempt was successful? Since then, how many concurrent "az foo bar" commands would be run within the same worker? Those commands you mentioned, "az webapp stop, az webapp config, az webapp start" do not seem to be run concurrently.

I'm still trying to understand the concurrency level of this report. While some other reports out there would hint many concurrent "az" commands racing with each other on the same lockfile, that seems not the case here in @sanistaal-bbc 's usage.

**Comment by sanistaal-bbc** [comment]
> Thanks, @sanistaal-bbc , for sharing your latest progress above. Glad that workaround works.

I'm not really sure that it's a workaround but more a roll-back to where I came from. I would like to run them side by side
