### ISSUE TITLE
ImportError: cannot import name 'KeyVaultAuthentication' from 'azure.keyvault' (unknown location) - when running az keyvault certificate import

### ISSUE THREAD

**Issue by seannguyn** [Azure/azure-cli#21818]
## Describe the bug

**Command Name**
`az keyvault certificate import`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'KeyVaultAuthentication' from 'azure.keyvault' (unknown location)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/keyvault/_command_type.py", line 96, in keyvault_command_handler
    client = client_factory(self.command_loader.cli_ctx, command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/keyvault/_client_factory.py", line 18, in keyvault_data_plane_factory
    from azure.keyvault import KeyVaultAuthentication, KeyVaultClient
ImportError: cannot import name 'KeyVaultAuthentication' from 'azure.keyvault' (unknown location)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault certificate import --file {} --name {} --vault-name {} --password {} {} {} {} {} {}`

## Environment Summary
```
Linux-5.11.0-1023-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
keyvault

**Comment by seannguyn** [comment]
> keyvault

What does that mean? 
What is the resolution?

**Comment by evelyn-ys** [comment]
`azure-cli 2.0.81` is not our official Azure CLI. See #19640 for details

Please install our CLI following https://docs.microsoft.com/cli/azure/install-azure-cli

**Comment by seannguyn** [comment]
resovled
