### ISSUE TITLE
az spring-cloud app create -n hellospring -s spring-boot-azure-name -g MY-RS --runtime-version=Java_11 --assign-endpoint true

### ISSUE THREAD

**Issue by rafex** [Azure/azure-cli#21830]
## Describe the bug

**Command Name**
`az spring-cloud app create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.storage'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafex/.azure/cliextensions/spring-cloud/azext_spring_cloud/app.py", line 17, in <module>
    from ._deployment_deployable_factory import deployable_selector
  File "/home/rafex/.azure/cliextensions/spring-cloud/azext_spring_cloud/_deployment_deployable_factory.py", line 10, in <module>
    from ._deployment_uploadable_factory import FileUpload, FolderUpload
  File "/home/rafex/.azure/cliextensions/spring-cloud/azext_spring_cloud/_deployment_uploadable_factory.py", line 12, in <module>
    from .azure_storage_file import FileService
  File "/home/rafex/.azure/cliextensions/spring-cloud/azext_spring_cloud/azure_storage_file/__init__.py", line 9, in <module>
    from .fileservice import FileService
  File "/home/rafex/.azure/cliextensions/spring-cloud/azext_spring_cloud/azure_storage_file/fileservice.py", line 19, in <module>
    from azure.storage.common._auth import (
ModuleNotFoundError: No module named 'azure.storage'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring-cloud app create -n {} -s {} -g {} --runtime-version={} --assign-endpoint {}`

## Environment Summary
```
Linux-5.16.0-17.2-liquorix-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.12
Installer: DEB

azure-cli 2.34.1

Extensions:
spring-cloud 3.0.1
azure-devops 0.24.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.1.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@rafex I am seeing any issues when using this cmdlet.  Can you please update to the latest version of spring cloud by using `az extension update -n spring-cloud` and let us know.

**Comment by SaurabhSharma-MSFT** [comment]
@rafex Please let us know if you have any questions else we will proceed with the closure of this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@rafex We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
