### ISSUE TITLE
az login fails after: json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by CianT123** [Azure/azure-cli#21848]
## Describe the bug
Az login is failing after I sign in to my account https://login.microsoftonline.com.

I will run az login, and be presented with the following message as a window for login.microsoftonline.com opens in my browser.

A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

Running az login --use-device-code results in the same problem

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Extra data: line 36 column 6 (char 6185)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/application.py", line 1546, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/application.py", line 135, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/application.py", line 581, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 184, in __add
    self.modify(self.CredentialType.ACCESS_TOKEN, at, at)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 67, in modify
    self._reload_if_necessary()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 58, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/msal/token_cache.py", line 319, in deserialize
    self._cache = json.loads(state) if state else {}
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 36 column 6 (char 6185)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
-  Sign in to my account on the login.microsoftonline.com

## Expected Behavior
Logs me into my azure account for az cli

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
It seems the MSAL token cache is somehow corrupted. To get unblocked, you may run

```
az account clear
```

to delete the token cache.

@rayluo, shoudln't MSAL token cache be protected from concurrent writes?

**Comment by CianT123** [comment]
Deleting the token cache resolved this issue. Thank you!

**Comment by rayluo** [comment]
> shoudln't MSAL token cache be protected from concurrent writes?

@jiasli, indeed, MSAL tries very hard to prevent concurrent writes to corrupt token cache. But there can still be a chance. Hypothetically speaking, if the previous "az login" process was somehow terminated abruptly (such as a `kill -9 pid` on Linux) during an (even non-concurrent) cache write, it would probably end up with an incomplete token cache file. I'm not saying this was the case here, but we won't know for sure until we can have a repro.

**Comment by MortenLohne** [comment]
`az account clear` failed with the same error message for me, but removing the `~/.azure` directory resolved the issue, thanks!
