### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by bacteria673** [Azure/azure-cli#21858]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2240, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3749, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-12.1-x86_64-i386-64bit, Darwin 21.2.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
k8s-configuration 1.4.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@bacteria673 Thanks for reaching out to us and sharing this feedback. Could you please run the below commands in order ?

>az login
az account set --subscription "your current subscription name"
az aks get-credentials --resource-group=MyRGName --name=MyAKSCluster **--overwrite-existing --file $HOME/PathToYourConfigFile**

--file -f  
Kubernetes configuration file to update. default value: ~/.kube/config

--overwrite-existing
Overwrite any existing cluster entry with the same name.

Please let me know if you still face the same issue after running the above commands. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bacteria673 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bacteria673 Please let us know if you have any updates to share on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bacteria673 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
