### ISSUE TITLE
az appconfig kv list [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by AbhishekTripathi** [Azure/azure-cli#21869]
## Describe the bug
AZ Cli was working fine with the previous version. I updated it today and started getting the certificate error. I have tried uninstalling and reinstalling the latest version. The issue persists. I can perform other operations and only issue so far I have seen is with the `az appconfig kv` commands.

**Command Name**
`az appconfig kv list -n mycfgstoreurlxxxxxx`

**Errors:**
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appconfig kv list -n mycfgstoreurlxxxxxx`

## Expected Behavior
See the list of the keys
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1
```
### Relevant redacted log from `az appconfig kv list -n mycfgstoreurlxxxxxx --debug` 

```
urllib3.connectionpool: Starting new HTTPS connection (1): mycfgstoreurlxxxxxx.azconfig.io:443
urllib3.connectionpool: Starting new HTTPS connection (2): mycfgstoreurlxxxxxx.azconfig.io:443
urllib3.connectionpool: Starting new HTTPS connection (3): mycfgstoreurlxxxxxx.azconfig.io:443
urllib3.connectionpool: Starting new HTTPS connection (4): mycfgstoreurlxxxxxx.azconfig.io:443
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appconfig/keyvalue.py", line 666, in list_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appconfig/_kv_helpers.py", line 330, in __read_kv_from_config_store
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/appconfiguration/_generated/operations/_azure_app_configuration_operations.py", line 227, in get_next
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 211, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/appconfiguration/_azure_appconfiguration_requests.py", line 76, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 467, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 445, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  [Previous line repeated 1 more time]
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 103, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 361, in send
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)

cli.azure.cli.core.azclierror: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)
az_command_data_logger: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03538B20>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 7.829 seconds (init: 0.238, invoke: 7.592)
telemetry.save: Save telemetry record of length 3160 in cache
telemetry.check: Negative: The C:\Users\username\.azure\telemetry.txt was modified at 2022-03-30 16:25:51.565012, which in less than 600.000000 s
cli.azure.cli.core.auth.identity: _dump_msal_http_cache: C:\Users\username\.azure\msal_http_cache.bin
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@AbhishekTripathi Thank you for reaching out we are looking into the issue and will help you with an update as soon as possible.

**Comment by RakeshMohanMSFT** [comment]
@AbhishekTripathi I was able to successfully list the keys with this command "az appconfig kv list -n" using cli version 2.34.1. If you are still having issues, can you please share the --debug trace with me here? of course to sanitize the logs for sensitive inforrmation.

**Comment by AbhishekTripathi** [comment]
After some detailed analysis, I found that the root cause is the ZScaler proxy which is installed on the enterprise laptop. After the firewall was updated for unrestricted access to  *.azconfig.io, the problem was resolved. I can confirm that this issue is not with the AZ CLI albeit the error message can contain more detail and use more meaningful verbiage.

**Comment by RakeshMohanMSFT** [comment]
Thank you @AbhishekTripathi for the confirmation and glad to hear that it is working for you now. Thank you for feedback about the improving the error message, we will try to improve the same. I will go ahead and close the issue.
