### ISSUE TITLE
Azure CLI is unable on M1 mac due to AttributeError: module 'logging' has no attribute 'getLogger

### ISSUE THREAD

**Issue by j0rd1smit** [Azure/azure-cli#21885]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I just installed using it using `brew install azure-cli`. This installed the version `azure-cli--2.34.1.arm64_monterey.bottle.tar.gz`. However, as soon as use any `az` cli command I get the following error.

```bash
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/opt/homebrew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.specifiers')
  File "/opt/homebrew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 24, in <module>
    from .utils import canonicalize_version
  File "/opt/homebrew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/opt/homebrew/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/tags.py", line 25, in <module>
    logger = logging.getLogger(__name__)
AttributeError: module 'logging' has no attribute 'getLogger'
```

It doesn't matter if I remove or reinstall the cli.

**To Reproduce**
Run this:
```
brew install azure-cli
az
```

**Expected behavior**
No errors 😀

**Environment summary**
System Version:	macOS 12.3 (21E230)
Kernel Version:	Darwin 21.4.0
Chip:	Apple M1 Pro

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by j0rd1smit** [comment]
I fixed it. It was my bad. I had a folder named logging in my home dir, and python was importing this directory instead of the logging module.
