### ISSUE TITLE
ForEach-Object -Parallel  issue with  az appconfig kv list 

### ISSUE THREAD

**Issue by AbhishekTripathi** [Azure/azure-cli#21883]
## Describe the bug
I want to iterate over a list of keys to see if we have same key existing with different labels. To achieve this efficiently, I am trying to iterate over the list in parallel invocation. A sequential invocation works as expected but the parallel call fails.

```
$keys = (az appconfig kv list -n MYCFGSTORE--label MYLABEL--fields key | ConvertFrom-Json)
$keys | ForEach-Object -Parallel {
    az appconfig kv list --name MYCFGSTORE --all --key $_  --fields key last_modified label | ConvertFrom-Json
}
```

**Command Name**
`az appconfig kv list`

**Errors:**
```
--- Logging error ---
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 60, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 53, in <module>
SystemExit: 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "logging\handlers.py", line 70, in emit
  File "logging\handlers.py", line 171, in doRollover
  File "logging\handlers.py", line 111, in rotate
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\.azure\\telemetry\\cache' -> 'C:\\Users\\username\\.azure\\telemetry\\cache.1'
Call stack:
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 123, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 241, in _wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 79, in _wrapped_func
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 297, in conclude
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/__init__.py", line 51, in save
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/util.py", line 53, in save_payload
  File "logging\__init__.py", line 1446, in info
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 954, in handle
  File "logging\handlers.py", line 73, in emit
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"b1ac6b9f-9c09-4553-85b2-3d2d99655fb4","Reserved.SequenceNumber":1,"Reserved.SessionId":"ab8cb9be9a35021fb616272321df8a6f029ace1690038ceaac20246df3ee630a","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"appconfig-kv-list","Reserved.DataModel.CorrelationId":"9f8a44e4-865c-464e-8d04-5e0fa31c3125","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.34.0@none","Context.Default.VS.Core.MacAddressHash":"5896cb89da52ee9fae4b1f09bcd0f164aea9ed0f761d5da1b8601afb0e981228","Context.Default.VS.Core.Machine.Id":"5896cb89-da52-ee9f-ae4b-1f09bcd0f164","Context.Default.VS.Core.OS.Type":"windows","Context.Default.VS.Core.OS.Version":"10.0.19041","Context.Default.VS.Core.OS.Platform":"windows-10-10.0.19041-sp0","Context.Default.VS.Core.User.Id":"1cb358e8-7da8-11eb-8193-046c592de6ae","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.34.0","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"d8792be5-b0de-11ec-bf67-046c592de6ae","Context.Default.AzureCLI.CoreVersion":"2.34.0","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"1cb358e8-7da8-11eb-8193-046c592de6ae","Context.Default.AzureCLI.ShellType":"cmd","Context.Default.AzureCLI.UserAzureId":"47d57aef066ea0e92e3d019d287d9c0fc3de7138a26133d4e61c839015eccd02","Context.Default.AzureCLI.UserAzureSubscriptionId":"562e1333-535e-453c-8266-ae70b5c527d3","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[_AZURE_CLIENT_ID_, _AZURE_CLIENT_SECRET_]","Context.Default.AzureCLI.Locale":"en_US,cp1252","Context.Default.AzureCLI.StartTime":"2022-03-31 10:39:30.238117","Context.Default.AzureCLI.EndTime":"2022-03-31 10:39:32.903255","Context.Default.AzureCLI.InitTimeElapsed":"0.301855","Context.Default.AzureCLI.InvokeTimeElapsed":"2.660278","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"appconfig kv list","Context.Default.AzureCLI.Params":"--name,--all,--key,--fields","Context.Default.AzureCLI.PythonVersion":"3.8.9","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"MSI","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'Arguments: ()
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

execute the script snippet provided earlier.

## Expected Behavior
Iteration should happen successfully in both sequential or in parallel execution

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @AbhishekTripathi Thanks for the query!

Did you try the For loop to iterate through the list?

![image](https://user-images.githubusercontent.com/62923178/163938284-4f381fca-e265-49fa-b0e5-b4cb4034e4cc.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @AbhishekTripathi Just checking back, could you please let us know if you need further help in this matter.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
