### ISSUE TITLE
Not able to get aks credentials

### ISSUE THREAD

**Issue by Kailash-P** [Azure/azure-cli#21919]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 553, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 479, in load_arguments
  File "C:\Users\PKail\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\PKail\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by RakeshMohanMSFT** [comment]
@Kailash-P Thank you for reaching out to us, we are looking into it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Kailash-P Thanks for reaching out to us. You are using an older version of Azure CLI. Please upgrade to the most [recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) (2.34.1) of the Az CLI and run the command again. Please let me know if you face any issues. Awaiting your reply.
