### ISSUE TITLE
az vm create : Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

### ISSUE THREAD

**Issue by piyushsh** [Azure/azure-cli#21940]
As I am trying out to create new VM using azure CLI, it is throwing error in my bash and command window as shown below
```
az vm create --resource-group "learnVMResourceGroup" --name "learnVM" --image UbuntuLTS --admin-username "learnadmin" --generate-ssh-keys
ERROR: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4
```

Steps:
1. Logged in to my account using `az login`
2. Trying to create vm using `az vm create --resource-group "learnVMResourceGroup" --name "learnVM" --image UbuntuLTS --admin-username "learnadmin" --generate-ssh-keys`

Azure CLI Version : 2.34.1

**Comment by SaurabhSharma-MSFT** [comment]
@piyushsh We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
compute

**Comment by piyushsh** [comment]
hey guys
@yonzhan @zhoxing-ms @cxznmhdcxz any update on the issue?

**Comment by zhoxing-ms** [comment]
@piyushsh Could you add the `--debug` parameter to the original command and run it again, then please show us the printed debug log?

**Comment by piyushsh** [comment]
Here are the logs with `--debug`
```
DEBUG: cli.knack.cli: Command arguments: ['vm', 'create', '--resource-group', 'learnVMRG', '--name', 'myVM', '--image', 'UbuntuLTS', '--admin-username', 'learnadmin', '--generate-ssh-keys', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x016E5100>, <function OutputProducer.on_global_arguments at 0x0174FF58>, <function CLIQuery.on_global_arguments at 0x01877B20>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: vm                        0.434        54       278
DEBUG: cli.azure.cli.core: Total (1)                 0.434        54       278
DEBUG: cli.azure.cli.core: Loaded 54 groups, 278 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : vm create
DEBUG: cli.azure.cli.core: Command table: vm create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03309850>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Piyush Sharma\.azure\commands\2022-04-10.22-06-49.vm_create.11676.log'.
INFO: az_command_data_logger: command args: vm create --resource-group {} --name {} --image {} --admin-username {} --generate-ssh-keys --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03359418>]
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 605, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2021_04_01.models' has no attribute 'DiskStorageAccountTypes,'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 605, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2021_11_01.models' has no attribute 'HyperVGeneration'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 605, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2021_11_01.models' has no attribute 'EncryptionType'

DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 605, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2021_11_01.models' has no attribute 'EncryptionType'

DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x033594F0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x033B3610>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0174FFA0>, <function CLIQuery.handle_query_parameter at 0x01877B68>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x033B35C8>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Piyush Sharma\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.identity: _load_msal_http_cache: C:\Users\Piyush Sharma\.azure\msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.identity: __load_msal_http_cache: C:\Users\Piyush Sharma\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 8c943594-4c90-45c2-b5f7-0a2276dcd9cf
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/49bec027-ac47-495c-9df0-6b27be472ee8/resourcegroups/learnVMRG?api-version=2021-04-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '22d03b42-b912-11ec-8454-84ef18442b32'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --image --admin-username --generate-ssh-keys --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.34.1 (MSI) azsdk-python-azure-mgmt-resource/20.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/49bec027-ac47-495c-9df0-6b27be472ee8/resourcegroups/learnVMRG?api-version=2021-04-01 HTTP/1.1" 200 280
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'bb45daf1-a40a-415f-bf58-141ae46e6cf5'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'bb45daf1-a40a-415f-bf58-141ae46e6cf5'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20220410T210657Z:bb45daf1-a40a-415f-bf58-141ae46e6cf5'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Sun, 10 Apr 2022 21:06:56 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '280'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/49bec027-ac47-495c-9df0-6b27be472ee8/resourceGroups/learnVMRG","name":"learnVMRG","type":"Microsoft.Resources/resourceGroups","location":"centralus","properties":{"provisioningState":"Succeeded"}}
DEBUG: cli.azure.cli.core.commands.validators: using location 'centralus' from resource group 'learnVMRG'
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG: urllib3.connectionpool: https://raw.githubusercontent.com:443 "GET /Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json HTTP/1.1" 200 529
DEBUG: cli.azure.cli.command_modules.vm._validators: storage profile 'StorageProfile.ManagedPirImage'
DEBUG: cli.azure.cli.command_modules.vm._validators: no subnet specified. Attempting to find an existing Vnet and subnet...
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=NetworkManagementClient
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/440ad669-8261-4a96-bce6-2b4d8d6d0313/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 1de3f3fe-721f-4e06-9101-3f7d22458aa2
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/49bec027-ac47-495c-9df0-6b27be472ee8/resourceGroups/learnVMRG/providers/Microsoft.Network/virtualNetworks?api-version=2018-01-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json, text/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '22d03b42-b912-11ec-8454-84ef18442b32'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vm create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --image --admin-username --generate-ssh-keys --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.34.1 (MSI) azsdk-python-azure-mgmt-network/19.3.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/49bec027-ac47-495c-9df0-6b27be472ee8/resourceGroups/learnVMRG/providers/Microsoft.Network/virtualNetworks?api-version=2018-01-01 HTTP/1.1" 200 133
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b38ccae6-2b9e-4b9f-888d-41f2a8d78e0f'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b38ccae6-2b9e-4b9f-888d-41f2a8d78e0f'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20220410T210657Z:b38ccae6-2b9e-4b9f-888d-41f2a8d78e0f'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Sun, 10 Apr 2022 21:06:57 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '133'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"value":[]}
DEBUG: cli.azure.cli.command_modules.vm._validators: no suitable subnet found. One will be created.
DEBUG: cli.azure.cli.command_modules.vm._validators: new NSG will be created
DEBUG: cli.azure.cli.command_modules.vm._validators: new public IP address will be created
DEBUG: cli.azure.cli.command_modules.vm._validators: new NIC will be created
ERROR: cli.azure.cli.core.azclierror: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4
ERROR: az_command_data_logger: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03309970>]
INFO: az_command_data_logger: exit code: 2
INFO: cli.__main__: Command ran in 3.824 seconds (init: 0.388, invoke: 3.436)
INFO: telemetry.save: Save telemetry record of length 3067 in cache
WARNING: telemetry.check: Negative: The C:\Users\Piyush Sharma\.azure\telemetry.txt was modified at 2022-04-10 22:02:05.446815, which in less than 600.000000 s
DEBUG: cli.azure.cli.core.auth.identity: _dump_msal_http_cache: C:\Users\Piyush Sharma\.azure\msal_http_cache.bin
```

**Comment by zhoxing-ms** [comment]
@cxznmhdcxz Please help have a look~

**Comment by piyushsh** [comment]
@cxznmhdcxz I don't have any `.ssh` folder in `c:\Users\Piyush Sharma\` folder.

**Comment by zhoxing-ms** [comment]
@piyushsh Could you use the  [`ssh-keygen`](https://www.ssh.com/academy/ssh/keygen) generate the new SSH key in the user directory and make sure that directory `~/.ssh` exists, and then try this command again?

**Comment by piyushsh** [comment]
@zhoxing-ms It worked, so closing this issue.

**Comment by Ibrahimgasali** [comment]
az vm create --resource-group "AzureCLIDemoGroup" --name "AzureCLIDemoGroup" --image Ubuntu2204 --size Standard_B1s --admin-username "azureuser" --generate-ssh-keys
Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

Please look into this command as I am still getting invalid error
