### ISSUE TITLE
az postgres flexible-server error - "No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by seajhawk** [Azure/azure-cli#21998]
## Describe the bug
This issue occurred when running `az postgres flexible-server --help` so I could see what parameters were needed.

**Command Name**
`az postgres flexible-server`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'psycopg2._psycopg'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1825, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2049, in _parse_known_args
  File "argparse.py", line 2026, in consume_positionals
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1213, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2049, in _parse_known_args
  File "argparse.py", line 2026, in consume_positionals
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1213, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2067, in _parse_known_args
  File "argparse.py", line 2007, in consume_optional
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1098, in __call__
  File "argparse.py", line 2555, in print_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 195, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 248, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 165, in show_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 303, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 241, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\charris\.azure\cliextensions\rdbms-connect\azext_rdbms_connect\custom.py", line 10, in <module>
    import psycopg2
  File "C:\Users\charris\.azure\cliextensions\rdbms-connect\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server --help`

## Expected Behavior
Output showing the parameters needed by the command

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
azure-dev 0.0.1b456
containerapp 0.1.3
rdbms-connect 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@seajhawk Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. Could you please try to run the below command and check if you still see same issue ? Awaiting your reply.

>pip install psycopg2==2.8.5

**Comment by seajhawk** [comment]
Hello @navba-MSFT,

I got two errors when trying to pip install the package:

`Error: pg_config executable not found.`

and
`ERROR: Could not find a version that satisfies the requirement psycopg2==2.8.5`

Though version 2.8.5 is clearly in the list of versions (emphasis mine):
```
versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, **2.8.5**, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3
```

I tried a couple of other versions that are in the list and got the same error.


I do not have postgresql install on this machine, so I'm guessing the first error about not finding pg_config is the primary error.


Full output from pip:
```
(.venv) > pip install psycopg2==2.8.5
Collecting psycopg2==2.8.5
  Using cached psycopg2-2.8.5.tar.gz (380 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\git\superset-on-Azure\.venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\charris\\AppData\\Local\\Temp\\pip-install-_ui_ttte\\psycopg2_2b378be06828468194cd7b87b3201780\\setup.py'"'"'; __file__='"'"'C:\\Users\\charris\\AppData\\Local\\Temp\\pip-install-_ui_ttte\\psycopg2_2b378be06828468194cd7b87b3201780\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm'
         cwd: C:\Users\charris\AppData\Local\Temp\pip-install-_ui_ttte\psycopg2_2b378be06828468194cd7b87b3201780\
    Complete output (23 lines):
    running egg_info
    creating C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm\psycopg2.egg-info
    writing C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm\psycopg2.egg-info\PKG-INFO
    writing dependency_links to C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm\psycopg2.egg-info\dependency_links.txt
    writing top-level names to C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm\psycopg2.egg-info\top_level.txt
    writing manifest file 'C:\Users\charris\AppData\Local\Temp\pip-pip-egg-info-908mx2tm\psycopg2.egg-info\SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a8/8f/1c5690eebf148d1d1554fc00ccf9101e134636553dbb75bdfef4f85d7647/psycopg2-2.8.5.tar.gz#sha256=f7d46240f7a1ae1dd95aab38bd74f7428d46531f69219954266d669da60c0818 (from https://pypi.org/simple/psycopg2/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2==2.8.5 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3)
ERROR: No matching distribution found for psycopg2==2.8.5
```

**Comment by navba-MSFT** [comment]
@seajhawk Apologies for the late reply. We are discussing this internally with the Product Owners. We will update this thread once we have more details on this. Tagging another similar issue here Azure/azure-cli#21953

**Comment by charris-msft** [comment]
No problem @navba-MSFT.
Just to let you know, I don't see this issue on a different computer that I use for personal projects.

**Comment by navba-MSFT** [comment]
@seajhawk We are aware of this bug and will be looking into this. The fix will be released tentatively by end of next month. In the meantime, if you have any questions, please feel free to ask. I would be happy to answer it. Awaiting your reply.

**Comment by seajhawk** [comment]
@navba-MSFT - Thanks for letting me know. I'm glad it's getting fixed!

**Comment by navba-MSFT** [comment]
@seajhawk  We have got a confirmation from the Product owners that the fix will be released tentatively by end of this month. In the meantime, if you have any questions, please feel free to ask. I would be happy to answer it.

**Comment by navba-MSFT** [comment]
@seajhawk Could you please delete the `rdbms-connect` folder n the ~/.azure/cliextensions/ location and install the most recent version using the below command ?

>az extension add --name rdbms-connect

Post this, you can try to run the AzCli command `az postgres flexible-server `again and check if you see the issue. Awaiting your reply.

**Comment by charris-msft** [comment]
That fixed it! 
The command runs successfully now.

**Comment by navba-MSFT** [comment]
@seajhawk Please follow the above mentioned action plan once you get a chance. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
