### ISSUE TITLE
az network nsg rule create FAILS with weird 'str' object has no attribute 'is_default' error

### ISSUE THREAD

**Issue by kirvam** [Azure/azure-cli#22023]
## Describe the bug

**Command Name**
`az network nsg rule create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'is_default'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 5016, in create_nsg_rule_2017_06_01
    _handle_asg_property(kwargs, 'source_application_security_groups', source_asgs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 4985, in _handle_asg_property
    if kwargs[prefix + 'address_prefix'].is_default:
AttributeError: 'str' object has no attribute 'is_default'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nsg rule create --v --subscription {} --resource-group {} --nsg-name {} --name {} --priority {} --source-port-ranges {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} --source-address-prefixes {} --source-asgs {} --access {} --protocol {} --direction {} --destination-port-ranges {}`

## Environment Summary
```
Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: RPM

azure-cli 2.35.0
```

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
It's duplicated one as: https://github.com/Azure/azure-cli/issues/22023
