### ISSUE TITLE
Az storage account create

### ISSUE THREAD

**Issue by accern-pavan** [Azure/azure-cli#22029]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 828, in load_arguments
    help=sas_help.format(get_permission_help_string(t_blob_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 803, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --verbose`

## Environment Summary
```
Linux-4.14.273-207.502.amzn2.x86_64-x86_64-with-glibc2.2.5, Amazon Linux 2
Python 3.7.10
Installer: RPM

azure-cli 2.35.0
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can you check the dependency if `azure-mgmt-storage` and `azure-multiapi-storage` are installed well? Seems package loss from the debug log

**Comment by dlipovetsky** [comment]
I ran into this same issue in Fedora 35, having installed the `azure-cli` package, version 2.36.0.

@evelyn-ys Based on your suggestion, I installed the presumably equivalent Fedora packages `python3-azure-mgmt-storage` and `python-azure-multiapi-storage`, but the issue remained.

I resorted to using azure CLI in a docker container.

**Comment by evelyn-ys** [comment]
@dlipovetsky your case is similar with #22235
