### ISSUE TITLE
cdn name-exists command failure in pipeline

### ISSUE THREAD

**Issue by eglavin** [Azure/azure-cli#22066]
## Describe the bug

**Command Name**
`az cdn name-exists`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
CheckNameAvailabilityInput.__init__() missing 1 required keyword-only argument: 'type'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cdn/custom/custom.py", line 156, in check_name_availability
TypeError: CheckNameAvailabilityInput.__init__() missing 1 required keyword-only argument: 'type'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn name-exists -n {}`

Running `az cdn name-exists -n` with any name fails with the above traceback, First found in Azure pipeline, can also be reproduced on a local machine running the latest release.

## Expected Behavior

Command runs successfully.

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@eglavin We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@eglavin I am able to reproduce this issue with CLI version 2.35.  This command does however worked with CLI version 2.34.1
I am redirecting this to services team to look into this issue.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by v-anvashist** [comment]
@SaurabhSharma-MSFT We are not owing cdn so I am searching to reroute this issue to cdn team.

**Comment by t-bzhan** [comment]
Ack, we take a look at it.
