### ISSUE TITLE
Error while creating the subnet

### ISSUE THREAD

**Issue by jayant-asians-cloud** [Azure/azure-cli#22076]
## Describe the bug

**Command Name**
`az network vnet subnet create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 6889, in create_subnet
    return get_property(vnet.subnets, subnet_name)
  File "/home/ops/.local/share/virtualenvs/XXX-8k5p5ZtP/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 490, in get_property
    result = next((x for x in items if x.name.lower() == name.lower()), None)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet subnet create -g {} --vnet-name {} --address-prefixes {} --name {}`

## Environment Summary
```
Linux-5.13.0-1017-azure-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.9.5
Installer: PIP

azure-cli 2.35.0
```

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
@jayant-asians-cloud, it seems vnet creation missing, the usual steps should be like:
```text
$ az network vnet create -g {} -n vnet --address-prefix 10.0.0.0/16
$ az network vnet subnet create -g {} --vnet-name vnet -n {} --address-prefixes 10.0.0.0/24
```
