### ISSUE TITLE
AZ AKS is no longer working.  How can I downgrade to the previous version?

### ISSUE THREAD

**Issue by eugen-nw** [Azure/azure-cli#22083]
## Describe the bug

**Command Name**
`az aks upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
bad magic number in 'pkg_resources.extern.packaging.tags': b'3\r\r\n'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 515, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\edaroczy\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 133, in <module>
    from .vendored_sdks.azure_mgmt_preview_aks.v2022_01_02_preview.models import (
  File "C:\Users\edaroczy\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\__init__.py", line 6, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\pkg_resources/__init__.py", line 83, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\pkg_resources/_vendor/packaging/specifiers.py", line 24, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\pkg_resources/_vendor/packaging/utils.py", line 8, in <module>
ImportError: bad magic number in 'pkg_resources.extern.packaging.tags': b'3\r\r\n'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks upgrade`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
aks-preview 0.5.56
subscription 0.1.4

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@eugen-nw Thank you for reaching out to us. We are looking into it.

**Comment by eugen-nw** [comment]
While investigating/fixing, can you please provide a rollback way out of this situation?  We have paying customers that we have to cater to.

**Comment by RakeshMohanMSFT** [comment]
@eugen-nw Unfortunately there is no support for rollback to previous AKS versions. But you can create a second cluster on the side and then redeploy your manifests to have an similar copy.

Also i was able to upgrade my cluster with similar environment as yours
Command I used `az aks upgrade --kubernetes-version 1.22.6 --name Issue4655 --resource-group Issue4655`
azure-cli                         2.35.0

**Comment by eugen-nw** [comment]
I ended up uninstalling Azure CLI from the Add/Remove programs and installing it again from the web.
