### ISSUE TITLE
'str' object has no attribute 'is_default'

### ISSUE THREAD

**Issue by rckannan** [Azure/azure-cli#22085]
## Describe the bug

**Command Name**
`az network nsg rule create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'is_default'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/network/custom.py", line 5016, in create_nsg_rule_2017_06_01
    _handle_asg_property(kwargs, 'source_application_security_groups', source_asgs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/network/custom.py", line 4985, in _handle_asg_property
    if kwargs[prefix + 'address_prefix'].is_default:
AttributeError: 'str' object has no attribute 'is_default'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nsg rule create --resource-group {} --nsg-name {} --name {} --direction {} --priority {} --source-address-prefixes {} --source-port-ranges {} --source-asgs {} --destination-address-prefixes {} --destination-port-ranges {} --access {} --protocol {} --description {}`

## Environment Summary
```
Linux-5.4.0-1074-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12

**Comment by yonzhan** [comment]
network
