### ISSUE TITLE
'NoneType' object has no attribute 'private_dns_zone_configs'

### ISSUE THREAD

**Issue by surajkewat24** [Azure/azure-cli#22118]
## Describe the bug

**Command Name**
`az network private-endpoint dns-zone-group add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'private_dns_zone_configs'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 3415, in add_private_endpoint_private_dns_zone
AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint dns-zone-group add --endpoint-name {} --resource-group {} --name {} --zone-name {} --subscription {} --private-dns-zone {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1 *

Extensions:
costmanagement 0.2.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi,
     @surajkewat24 You should use 'az network private-endpoint dns-zone-group create' to create a dns-zone-group before you use 'az network private-endpoint dns-zone-group add' command.
Best wishes.

**Comment by mihaimircea** [comment]
Hello,
I created a Private Endpoint with private DNS integration from the Azure Portal and then ran 
`az network private-endpoint dns-zone-group list` against that PE, here;s the result:

```
[
  {
    "etag": "W/\"ef\"",
    "id": "/subscriptions/1234/resourceGroups/devtest-mihaimircea-rg/providers/Microsoft.Network/privateEndpoints/testmmm1-we-fe/privateDnsZoneGroups/default",
    "name": "default",
    "privateDnsZoneConfigs": [
      {
        "etag": "W/\"ef618c48-8a88-4926-b6b7-5d3b6c1f03fd\"",
        "id": "/subscriptions/1234/resourceGroups/devtest-mihaimircea-rg/providers/Microsoft.Network/privateEndpoints/testmmm1-we-fe/privateDnsZoneGroups/default/privateDnsZoneConfigs/privatelink-blob-core-windows-net",
        "name": "privatelink-blob-core-windows-net",
        "privateDnsZoneId": "/subscriptions/1234/resourceGroups/devtest-mihaimircea-rg/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net",
        "recordSets": [
          {
            "fqdn": "testmmm1.privatelink.blob.core.windows.net",
            "ipAddresses": [
              "10.100.10.4"
            ],
            "provisioningState": "Succeeded",
            "recordSetName": "testmmm1",
            "recordType": "A",
            "ttl": 10
          }
        ],
        "resourceGroup": "devtest-mihaimircea-rg",
        "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups/privateDnsZoneConfigs"
      }
    ],
    "provisioningState": "Succeeded",
    "resourceGroup": "devtest-mihaimircea-rg",
    "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups"
  }
]
```

so I guess the dns zone group default exists.

And then, when trying to add another PE to the same private DNS zone I get the same exception

```
az network private-endpoint dns-zone-group add `
  --endpoint-name     testmmm3-we-pe `
  --name              default `
  --private-dns-zone  '/subscriptions/1234/resourceGroups/devtest-mihaimircea-rg/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net' `
  --resource-group    'devtest-mihaimircea-rg' `
  --zone-name         'privatelink-blob-core-windows-net'
```
