### ISSUE TITLE
az apim command fails 

### ISSUE THREAD

**Issue by mukeshinit** [Azure/azure-cli#22114]
## Describe the bug

**Command Name**
`az apim`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'NamedValueCreateContract' from 'azure.mgmt.apimanagement.models' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\apimanagement\models\__init__.py)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1825, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2049, in _parse_known_args
  File "argparse.py", line 2026, in consume_positionals
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1213, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2067, in _parse_known_args
  File "argparse.py", line 2007, in consume_optional
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1098, in __call__
  File "argparse.py", line 2555, in print_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 195, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 248, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 165, in show_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 303, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 241, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/apim/custom.py", line 28, in <module>
ImportError: cannot import name 'NamedValueCreateContract' from 'azure.mgmt.apimanagement.models' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\apimanagement\models\__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim -h`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
application-insights 0.1.13
azure-devops 0.18.0
interactive 0.4.4

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@mukeshinit We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@mukeshinit Can you please share the subcommand which you are using with `az apim` which is failing ?

**Comment by SaurabhSharma-MSFT** [comment]
@mukeshinit Please can you please share the required details, so that we could look into it ? Thanks

**Comment by mukeshinit** [comment]
> @mukeshinit Please can you please share the required details, so that we could look into it ? Thanks

**Comment by mukeshinit** [comment]
Apologies for delayed response ..

I'm getting this error when execute any az apim commands. But fine with other modules.. problem occurs only to apim commands

**Comment by mukeshinit** [comment]
Any update on this issue ?
