### ISSUE TITLE
Error when az get-credentials - 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ilozano2** [Azure/azure-cli#22142]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2225, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3764, in _print_or_merge_credentials
    merge_kubernetes_configurations(
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1201, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1136, in _handle_merge
    if not existing.get(key):
AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.35.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ilozano2 To unblock can you please downgrade to previous version of CLI and check again. While we investigate this issue?

**Comment by FumingZhang** [comment]
Hi @ilozano2, the reason for the error is that the existing kubeconfig file (default path is `~/.kube/config`) is not a valid yaml file.

Workarounds:
- Option 1
  If necessary, back up the existing file, then delete the file and execute the command again.

- Option 2
  Specify some other path to store the kubeconfig file like `az aks get-credentials -g {resource_group_name} -n {cluster_name} -f {custom_local_path_to_store_the_config} `.
