### ISSUE TITLE
az vmss set diagnostics - Failing to set custom config from JSON

### ISSUE THREAD

**Issue by Bougheyy** [Azure/azure-cli#22151]
## Describe the bug

**Command Name**
`az vmss diagnostics set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'mode'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 3600, in set_vmss_diagnostics_extension
    if vmss.upgrade_policy.mode == UpgradeMode.manual:
AttributeError: 'NoneType' object has no attribute 'mode'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss diagnostics set --resource-group {} --vmss-name {} --settings {} --protected-settings {}`

## Environment Summary
```
Linux-5.4.0-1077-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
ai-examples 0.2.5
ssh 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by Bougheyy** [comment]
Changing the Virtual Machine Scale Set from Flexible Orchestration to Uniform Orchestration and running the same command appears to be a work around for the issue.  The 'az vmss diagnostics set' command appears to fail whenever it is run on a Flexible VMSS.

**Comment by cxznmhdcxz** [comment]
Hi @fitzgeraldsteele , does flexible VMSS support diagnostics?

**Comment by JoshLuedeman** [comment]
Getting the same error when trying to update a flexible VMSS using flags "--enable-auto-os-upgrade true --upgrade-policy-mode Rolling"
