### ISSUE TITLE
az arcdata dc update failing

### ISSUE THREAD

**Issue by likamrat** [Azure/azure-cli#22168]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running various ```az arcdata dc update``` commands, cli is erroring out

```
PS C:\Users\arcdemo> $Env:WORKSPACE_ID=$(az resource show --resource-group $Env:resourceGroup --name $Env:workspaceName --resource-type "Microsoft.OperationalInsights/workspaces" --query properties.customerId -o tsv)
PS C:\Users\arcdemo> $Env:WORKSPACE_SHARED_KEY=$(az monitor log-analytics workspace get-shared-keys --resource-group $Env:resourceGroup --workspace-name $Env:workspaceName  --query primarySharedKey -o tsv)
PS C:\Users\arcdemo> az arcdata dc update --name arcbox-dc --resource-group $Env:resourceGroup --auto-upload-logs true
The command failed with an unexpected error. Here is the traceback:
ArmClient.update_dc() takes 4 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\arcdemo\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 167, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\arcdemo\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 383, in update
    return self._arm_client.update_dc(
TypeError: ArmClient.update_dc() takes 4 positional arguments but 6 were given
To open an issue, please run: 'az feedback'
PS C:\Users\arcdemo> az arcdata dc update --name arcbox-dc --resource-group $Env:resourceGroup --auto-upload-metrics true
The command failed with an unexpected error. Here is the traceback:
ArmClient.update_dc() takes 4 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\arcdemo\.azure\cliextensions\arcdata\azext_arcdata\dc\custom.py", line 167, in dc_update
    return client.services.dc.update(cvo)
  File "C:\Users\arcdemo\.azure\cliextensions\arcdata\azext_arcdata\core\services.py", line 383, in update
    return self._arm_client.update_dc(
TypeError: ArmClient.update_dc() takes 4 positional arguments but 6 were given
To open an issue, please run: 'az feedback'
```

**To Reproduce**
1. Deploy Azure Arc Data Controller
2. Deploy Log Analytics workspace
3. Follow [Upload logs to Azure Log Analytics Workspace in direct mode](https://docs.microsoft.com/en-us/azure/azure-arc/data/upload-logs?tabs=windows#upload-logs-to-azure-log-analytics-workspace-in-direct-mode)
4. Follow [Upload metrics for Azure Arc data controller in direct mode](https://docs.microsoft.com/en-us/azure/azure-arc/data/upload-metrics?tabs=windows#upload-metrics-for-azure-arc-data-controller-in-direct-mode)

**Expected behavior**

**Environment summary**
```
PS C:\Users\arcdemo> az -v
azure-cli                         2.35.0

core                              2.35.0
telemetry                          1.0.6

Extensions:
arcdata                            1.3.1

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@likamrat Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@likamrat `az arcdata dc update --auto-upload-logs true `--k8s-namespace issue22168` --name issue22168 --resource-group Issue22168 **--use-k8s**` Can you please try adding --k8s-namespace param and also --use-k8s param please, these are mandatory param for the update command.

--k8s-namespace -k
[Required] The Kubernetes namespace in which the data controller exists.

**Comment by swells** [comment]
This is a regression in `arcdata` ext not core azure-cli.  The issues has been resolved and a new build will go out this week.

**Comment by likamrat** [comment]
Related to #22224

**Comment by RakeshMohanMSFT** [comment]
@likamrat Thank you. @swells can you please help us with an update on the fix?

**Comment by RakeshMohanMSFT** [comment]
@likamrat This should be fixed now, can you please try again? Also see if you can uninstall and install arcdata extension.

**Comment by RakeshMohanMSFT** [comment]
Glad that your issue is resolved @likamrat. I will close this issue now.
