### ISSUE TITLE
can't access Datalake account from azure-cli

### ISSUE THREAD

**Issue by Katana-Steel** [Azure/azure-cli#22181]
## Describe the bug

**Command Name**
`az dls account`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.datalake.store.operations.accounts_operations'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 583, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib/python3.9/argparse.py", line 1836, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/argparse.py", line 1869, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2037, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.9/argparse.py", line 1946, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1225, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/argparse.py", line 1869, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2037, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.9/argparse.py", line 1946, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1225, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/argparse.py", line 1869, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2078, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2018, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1946, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1110, in __call__
    parser.print_help()
  File "/usr/lib/python3.9/argparse.py", line 2566, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 195, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 248, in format_help
    self.cli_help.show_help(self.prog.split()[0],
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help.py", line 165, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/usr/lib/python3/dist-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help.py", line 303, in load
    loader.versioned_load(self, options)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/usr/lib/python3/dist-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/usr/lib/python3/dist-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.datalake.store.operations.accounts_operations'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls account --help`

## Environment Summary
```
Linux-5.16.0-5-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.12
Installer: DEB

azure-cli 2.35.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.1.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Katana-Steel Thanks for reaching out to us and sharing this feedback. Looking at the below:

```
Linux-5.16.0-5-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.12
Installer: DEB
```
This is not the official Azure CLI published by Microsoft. Please see https://github.com/Azure/azure-cli/issues/19640.

>Sid is forever doomed to being unstable. Sid will always be the unstable branch.

Refer this: https://wiki.debian.org/DebianUnstable

Could you please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Azure CLI on stable/GA versions of Debian, like 11 Bullseye, instead of Sid. Please let us know if you still see the same issue after following this plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Katana-Steel I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Katana-Steel We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
