### ISSUE TITLE
az dls fs test unexpected error 

### ISSUE THREAD

**Issue by jaknigh** [Azure/azure-cli#22246]
## Describe the bug

**Command Name**
`az dls fs test`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'headers'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/dls/custom.py", line 213, in test_adls_item
    return cf_dls_filesystem(cmd.cli_ctx, account_name).exists(path)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/dls/_client_factory.py", line 40, in cf_dls_filesystem
    return core.AzureDLFileSystem(
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/core.py", line 72, in __init__
    self.connect()
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/core.py", line 90, in connect
    self.azure = DatalakeRESTInterface(token=self.token, req_timeout_s=self.per_call_timeout_seconds, **self.kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/lib.py", line 273, in __init__
    self._check_token()  # Retryable method. Will ensure that signed_session token is current when we set it on next line
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/lib.py", line 307, in _check_token
    check_token_internal()
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/retry.py", line 93, in f_retry
    out = func(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/datalake/store/lib.py", line 305, in check_token_internal
    self.head = {'Authorization': cur_session.headers['Authorization']}
AttributeError: 'NoneType' object has no attribute 'headers'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs test --account {} --path {}`

## Environment Summary
```
Linux-5.4.0-1077-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
storage-preview 0.8.0
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @jaknigh we are routing this issue to the Service Team's Attention!

**Comment by RakeshMohanMSFT** [comment]
@jaknigh This is working. Please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and retry

`az dls fs test -n issue22246dls --path 'issue22246folder/piuzzle.png"`
Command group 'dls' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
false
