### ISSUE TITLE
Cache is empty but the Azure CLI is still picking up values

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#22247]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Operation returned an invalid status 'Forbidden'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {} --location {} --debug`

## Expected Behavior

The command I entered specifically sent in a location with the --location param but this output shows it picked up a different location from somewhere, not the cache, as the next command in the series shows. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.1 *

Extensions:
account 0.2.3
application-insights 0.1.16

```
## Additional Context

```
 az webapp up --name learn-js-rentals --location westus3 --debug
←[36mcli.knack.cli: Command arguments: ['webapp', 'up', '--name', 'learn-js-rentals', '--location', 'westus3', '--debug']←[0m
←[36mcli.knack.cli: __init__ debug log:
Enable color in terminal.←[0m
←[36mcli.knack.cli: Event: Cli.PreExecute []←[0m
←[36mcli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02E760B8>, <function OutputProducer.on_global_arguments at 0x03113F10>, <function CLIQuery.on_global_arguments at 0x0313AB20>]←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []←[0m
←[36mcli.azure.cli.core: Modules found from index for 'webapp': ['azure.cli.command_modules.appservice']←[0m
←[36mcli.azure.cli.core: Loading command modules:←[0m
←[36mcli.azure.cli.core: Name                  Load Time    Groups  Commands←[0m
←[36mcli.azure.cli.core: appservice                0.189        63       223←[0m
←[36mcli.azure.cli.core: Total (1)                 0.189        63       223←[0m
←[36mcli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']←[0m
←[36mcli.azure.cli.core: Loading extensions:←[0m
←[36mcli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory←[0m
←[36mcli.azure.cli.core: Total (0)                 0.000         0         0  ←[0m
←[36mcli.azure.cli.core: Loaded 63 groups, 223 commands.←[0m
←[36mcli.azure.cli.core: Found a match in the command table.←[0m
←[36mcli.azure.cli.core: Raw command  : webapp up←[0m
←[36mcli.azure.cli.core: Command table: webapp up←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x034D1F58>]←[0m
←[36mcli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\diberry\.azure\commands\2022-05-02.15-17-43.webapp_up.26748.log'.←[0m
←[32maz_command_data_logger: command args: webapp up --name {} --location {} --debug←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x035242B0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x0353A970>]←[0m
←[36mcli.azure.cli.core.util: attempting to read file C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\appservice\resources\WindowsFunctionsStacks.json as utf-8-sig←[0m
←[36mcli.azure.cli.core.util: attempting to read file C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\appservice\resources\LinuxFunctionsStacks.json as utf-8-sig←[0m
←[32mcli.knack.commands: Configured default 'js-rentals-284134351' for arg name←[0m
←[32mcli.knack.commands: Configured default 'js-rentals-284134351' for arg resource_group_name←[0m
←[32mcli.knack.commands: Configured default 'diberry_asp_Linux_westus3_0' for arg plan←[0m
←[32mcli.knack.commands: Configured default 'westus' for arg location←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0353A9B8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0353AA48>]←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPreParseArgs []←[0m
←[36mcli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03113F58>, <function CLIQuery.handle_query_parameter at 0x0313AB68>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03524340>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0353AA00>]←[0m
←[36mcli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient←[0m
←[36mcli.azure.cli.core: Current cloud config:
AzureCloud←[0m
←[36mcli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient←[0m
←[36mcli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)←[0m
←[36mcli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'←[0m
←[36mcli.azure.cli.core.util: attempting to read file C:\Users\diberry\.azure\accessTokens.json as utf-8-sig←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - Authority:Performing instance discovery: ...←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - Authority:Performing static instance discovery←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - Authority:Authority validated via static instance discovery←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - TokenRequest:Getting token from cache with refresh if necessary.←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - CacheDriver:Found 10 potential entries.←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - CacheDriver:Resource specific token found.←[0m
←[36madal-python: 06e58f06-847d-400a-a89b-2233b3c7f2dc - CacheDriver:Returning token from cache lookup, AccessTokenId: b'yUlArjn6zmQ7R6S+3qy1CQ/xG6ZVrHN57FFvn0VBO1k=', RefreshTokenId: b'wh39zLdJJhWGWMU5Si57PUn9SFtOWE+057l2VmgPT7g='←[0m
←[36mcli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/84590f3a-289c-4c37-ac6f-0ac95730cfe2/providers/Microsoft.Web/checknameavailability?api-version=2020-09-01'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request method: 'POST'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request headers:←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Accept': 'application/json'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Length': '44'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'b02a1c9e-ca65-11ec-b67a-8cdcd42e37d4'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'CommandName': 'webapp up'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --location --debug'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.27.1 (MSI) azsdk-python-azure-mgmt-web/2.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Authorization': '*****'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request body:←[0m
←[36mcli.azure.cli.core.sdk.policies: {"name": "learn-js-rentals", "type": "Site"}←[0m
←[36murllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443←[0m
←[36murllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/84590f3a-289c-4c37-ac6f-0ac95730cfe2/providers/Microsoft.Web/checknameavailability?api-version=2020-09-01 HTTP/1.1" 200 None←[0m
←[36mcli.azure.cli.core.sdk.policies: Response status: 200←[0m
←[36mcli.azure.cli.core.sdk.policies: Response headers:←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Expires': '-1'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-request-id': '95d38a1d-01ce-46bc-90b9-55f127bc4516'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4828ec63-27b7-4439-a95f-bda0cd721103'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20220502T221744Z:4828ec63-27b7-4439-a95f-bda0cd721103'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Date': 'Mon, 02 May 2022 22:17:44 GMT'←[0m
←[36mcli.azure.cli.core.sdk.policies: Response content:←[0m
←[36mcli.azure.cli.core.sdk.policies: {"nameAvailable":true,"reason":"","message":""}←[0m
←[93mcli.azure.cli.command_modules.appservice.custom: The webapp 'learn-js-rentals' doesn't exist←[0m
←[36mcli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient←[0m
←[36mcli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient←[0m
←[36mcli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)←[0m
←[36mcli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - Authority:Performing instance discovery: ...←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - Authority:Performing static instance discovery←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - Authority:Authority validated via static instance discovery←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - TokenRequest:Getting token from cache with refresh if necessary.←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - CacheDriver:Found 10 potential entries.←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - CacheDriver:Resource specific token found.←[0m
←[36madal-python: 2c4aaae2-c78f-4d88-a9d8-a6d09f7321bb - CacheDriver:Returning token from cache lookup, AccessTokenId: b'yUlArjn6zmQ7R6S+3qy1CQ/xG6ZVrHN57FFvn0VBO1k=', RefreshTokenId: b'wh39zLdJJhWGWMU5Si57PUn9SFtOWE+057l2VmgPT7g='←[0m
←[36mcli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/84590f3a-289c-4c37-ac6f-0ac95730cfe2/resourcegroups/js-rentals-284134351?api-version=2021-04-01'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request method: 'HEAD'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request headers:←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Accept': 'application/json'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'b02a1c9e-ca65-11ec-b67a-8cdcd42e37d4'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'CommandName': 'webapp up'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --location --debug'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.27.1 (MSI) azsdk-python-azure-mgmt-resource/18.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Authorization': '*****'←[0m
←[36mcli.azure.cli.core.sdk.policies: Request body:←[0m
←[36mcli.azure.cli.core.sdk.policies: This request has no body←[0m
←[36murllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443←[0m
←[36murllib3.connectionpool: https://management.azure.com:443 "HEAD /subscriptions/84590f3a-289c-4c37-ac6f-0ac95730cfe2/resourcegroups/js-rentals-284134351?api-version=2021-04-01 HTTP/1.1" 403 0←[0m
←[36mcli.azure.cli.core.sdk.policies: Response status: 403←[0m
←[36mcli.azure.cli.core.sdk.policies: Response headers:←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Length': '434'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Expires': '-1'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-request-id': '7bd39e1e-87b1-4dcd-98e7-976384504c3b'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7bd39e1e-87b1-4dcd-98e7-976384504c3b'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20220502T221745Z:7bd39e1e-87b1-4dcd-98e7-976384504c3b'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Date': 'Mon, 02 May 2022 22:17:45 GMT'←[0m
←[36mcli.azure.cli.core.sdk.policies:     'Connection': 'close'←[0m
←[36mcli.azure.cli.core.sdk.policies: Response content:←[0m
←[36mcli.azure.cli.core.sdk.policies: ←[0m
←[36mcli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:←[0m
←[36mcli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3783, in webapp_up
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_create_util.py", line 349, in get_rg_to_use
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_create_util.py", line 116, in _check_resource_group_exists
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 96, in check_existence
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Forbidden'
←[0m
←[91mcli.azure.cli.core.azclierror: Operation returned an invalid status 'Forbidden'←[0m
←[91maz_command_data_logger: Operation returned an invalid status 'Forbidden'←[0m
←[36mcli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x034D40B8>]←[0m
←[32maz_command_data_logger: exit code: 1←[0m
←[32mcli.__main__: Command ran in 2.120 seconds (init: 0.343, invoke: 1.776)←[0m
←[32mtelemetry.save: Save telemetry record of length 2964 in cache←[0m
←[93mtelemetry.check: Negative: The C:\Users\diberry\.azure\telemetry.txt was modified at 2022-05-02 15:16:07.849336, which in less than 600.000000 s←[0m

REDMOND+diberry@DINA-HP-WIN10-MS MSYS /c/repos/code/js-e2e/msdocs-javascript-nodejs-server/3-Add-cosmosdb-mongodb (main)
$ az cache list
[]

REDMOND+diberry@DINA-HP-WIN10-MS MSYS /c/repos/code/js-e2e/msdocs-javascript-nodejs-server/3-Add-cosmosdb-mongodb (main)
```

I also checked the environment variables but that didn't have any location either.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @diberry Did you try the new web app from the Web Portal?
Did you try with any other location?
I may also check the az configure for any default?

We are not able to repro the issue related to the --location param with this command.

![image](https://user-images.githubusercontent.com/62923178/167510992-58acf3c1-4893-4388-b120-e1bf2fb409eb.png)

![image](https://user-images.githubusercontent.com/62923178/167510937-923fc1e8-4d28-4375-9cba-9a95ee661a19.png)

The only failure scenario was due to unauthorized location(westus3) on my subscription (restriction).

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
