### ISSUE TITLE
az storage entity cant serialize UUID

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-cli#22250]
## Describe the bug
Throws an error trying to serialize a table entity with a guid field
**Command Name**
`az storage entity query`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Object of type UUID is not JSON serializable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 325, in _iterencode_list
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 438, in _iterencode
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 30, in default
  File "json\encoder.py", line 179, in default
TypeError: Object of type UUID is not JSON serializable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Create a table with rows which contain a guid
- `az storage entity query --table-name {} --account-name {} --account-key {} --output  'json'

## Expected Behavior
Outputs table entites as json
## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
storage

**Comment by jonie001** [comment]
Hi, @RDavis3000
When I assign UUID to key = value pairs, the JSON format can be output correctly. Can you provide more information about the command？
![image](https://user-images.githubusercontent.com/99947323/167656670-ab2f2aed-59e1-4b7c-a2b8-e6409c1cd529.png)
