### ISSUE TITLE
az acr build : UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-96

### ISSUE THREAD

**Issue by williamhbell** [Azure/azure-cli#22301]
## Describe the bug
When an  `az acr build` is run on Windows 10 using Git Bash and pip, it appears that the pip package install progress characters crash the log from the build.  The build succeeds and the image is created in the container registry, even though the build is reported to have failed.  The failure appears to be only associated with the log stream.

If the same command is run using a command prompt and `az acr build` it succeeds.  If the command is used with Git Bash and Docker desktop, it also succeeds.

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'charmap' codec can't encode characters in position 57-96: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 187, in write_and_convert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-96: character maps to <undefined>

```

## To Reproduce:
Steps to reproduce the behaviour. Note that argument values have been redacted, as they may contain sensitive information.

The present working directory should contain `Dockerfile`, `app.py`, `requirements.txt`. 

`app.py`
```python
from flask import Flask
from flask import request

app = Flask(__name__)


@app.route("/")
def hello_server():
    host_and_port = request.headers.get('Host')
    fragments = host_and_port.split(":")
    hostname = fragments[0]
    port = "80"
    if len(fragments) > 1:
        port = fragments[1]
    return f"<p>Hello from {hostname}, listening on port {port}.</p>"


if __name__ == '__main__':
    app.run(debug=True)
```

`requirements.txt`
```
Flask>=2.0
gunicorn>20.0
```

- `az acr build --resource-group {} --registry {} --image {} {}`

The  `az acr build` from Git Bash with and the Dockerfile:
```yaml
# syntax=docker/dockerfile:1
FROM python:slim-bullseye
WORKDIR /app
COPY . .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
ENV PORT=5000
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT app:app"]
```
crashes.

However, the `az acr build` from Git Bash and the Dockerfile:

```yaml
# syntax=docker/dockerfile:1
FROM python:slim-bullseye
WORKDIR /app
COPY . .
RUN pip3 install --upgrade --progress-bar off pip && pip3 install --progress-bar off -r requirements.txt
ENV PORT=5000
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT app:app"]
```
succeeds.

## Expected Behaviour
I expect that the build log should not crash when the build is run from Git Bash.

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0

Extensions:
account 0.2.2
azure-devops 0.23.0
db-up 0.2.6

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@williamhbell Thanks for reaching out to us and sharing this feedback. I am sharing a few action plan. Please implement it and share the outcome.

**Plan 1:**  Could you please try `--no-format` option in `az acr build `and check if you see the same issue ?
**Plan 2:** If the above command fails with same error, try running with ` --no-logs` options. If you need to fetch logs you can use the `run-id `and execute the command `az acr task logs --run-id <you-run-id>` to see if you can retrieve the logs ?
**Plan 3:** If both the above plans fail, Please try with the following commands inside the docker file:
```
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8
```
Firstly you need to ensure that the `locales` package is installed by the docker file before you run the above commands. 

reference: https://github.com/Azure/azure-cli/issues/19042

Hope this helps.

**Comment by williamhbell** [comment]
Using `--no-format`:
```
$ az acr build --no-format --resource-group **** --registry ******* --image **/***:latest .
WARNING: Packing source code into tar to upload...
WARNING: Uploading archived source code from 'C:\Users\******\AppData\Local\Temp\build_archive_bfa5f9c02cbf421d9ae0d1454a6554c1.tar.gz'...
WARNING: Sending context (1.870 KiB) to registry: *******...
WARNING: Queued a build with ID: db6
WARNING: Waiting for an agent...
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'charmap' codec can't encode characters in position 57-96: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-96: character maps to <undefined>
To open an issue, please run: 'az feedback'
2022/05/09 08:15:25 Downloading source code...
2022/05/09 08:15:26 Finished downloading source code
2022/05/09 08:15:26 Using acb_vol_******* as the home volume
2022/05/09 08:15:26 Setting up Docker configuration...
2022/05/09 08:15:27 Successfully set up Docker configuration
2022/05/09 08:15:27 Logging in to registry: ******..azurecr.io
2022/05/09 08:15:28 Successfully logged into ******.azurecr.io
2022/05/09 08:15:28 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2022/05/09 08:15:28 Scanning for dependencies...
2022/05/09 08:15:28 Successfully scanned dependencies
2022/05/09 08:15:28 Launching container with name: build
Sending build context to Docker daemon  9.728kB
Step 1/6 : FROM python:slim-bullseye
slim-bullseye: Pulling from library/python
1fe172e4850f: Pulling fs layer
caf521ccaac6: Pulling fs layer
b3278b635dc9: Pulling fs layer
4298f8ff43f9: Pulling fs layer
56eb47d0c00a: Pulling fs layer
4298f8ff43f9: Waiting
56eb47d0c00a: Waiting
caf521ccaac6: Verifying Checksum
caf521ccaac6: Download complete
b3278b635dc9: Verifying Checksum
b3278b635dc9: Download complete
1fe172e4850f: Verifying Checksum
1fe172e4850f: Download complete
4298f8ff43f9: Verifying Checksum
4298f8ff43f9: Download complete
56eb47d0c00a: Verifying Checksum
56eb47d0c00a: Download complete
1fe172e4850f: Pull complete
caf521ccaac6: Pull complete
b3278b635dc9: Pull complete
4298f8ff43f9: Pull complete
56eb47d0c00a: Pull complete
Digest: sha256:ad719a882ac0594bdc92abccff22e5b6713bbf9893320264fd9e8affd8a6f470
Status: Downloaded newer image for python:slim-bullseye
 ---> c3e38abaf684
Step 2/6 : WORKDIR /app
 ---> Running in 942e01731ed7
Removing intermediate container 942e01731ed7
 ---> cbcd85bdaa89
Step 3/6 : COPY . .
 ---> c1bea7998e39
Step 4/6 : RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
 ---> Running in 3fbf0bb72d4c
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting Flask>=2.0
```

With the `--no-logs` option:
```
az acr build --no-logs --resource-group ****** --registry ****** --image *****/*****:latest .
WARNING: Packing source code into tar to upload...
WARNING: Uploading archived source code from 'C:\Users\*****\AppData\Local\Temp\build_archive_924657647851432c9ce9e3d5e242a02e.tar.gz'...
WARNING: Sending context (1.868 KiB) to registry: *******...
WARNING: Queued a build with ID: db7
WARNING: Waiting for an agent...
{
****JSON output****
}
```
The output successfully completes.

Retrieving the log from the previous command fails as expected:
```
$ az acr task logs --registry *******
WARNING: Showing logs of the last created run.
WARNING: Run ID: db7
2022/05/09 08:20:03 Downloading source code...
2022/05/09 08:20:04 Finished downloading source code
2022/05/09 08:20:04 Using acb_vol_********* as the home volume
2022/05/09 08:20:04 Setting up Docker configuration...
2022/05/09 08:20:05 Successfully set up Docker configuration
2022/05/09 08:20:05 Logging in to registry: *******.azurecr.io
2022/05/09 08:20:06 Successfully logged into *******..azurecr.io
2022/05/09 08:20:06 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2022/05/09 08:20:06 Scanning for dependencies...
2022/05/09 08:20:06 Successfully scanned dependencies
2022/05/09 08:20:06 Launching container with name: build
Sending build context to Docker daemon  9.728kB
Step 1/6 : FROM python:slim-bullseye
slim-bullseye: Pulling from library/python
1fe172e4850f: Pulling fs layer
caf521ccaac6: Pulling fs layer
b3278b635dc9: Pulling fs layer
4298f8ff43f9: Pulling fs layer
56eb47d0c00a: Pulling fs layer
4298f8ff43f9: Waiting
56eb47d0c00a: Waiting
caf521ccaac6: Verifying Checksum
caf521ccaac6: Download complete
b3278b635dc9: Verifying Checksum
b3278b635dc9: Download complete
1fe172e4850f: Verifying Checksum
1fe172e4850f: Download complete
4298f8ff43f9: Verifying Checksum
4298f8ff43f9: Download complete
56eb47d0c00a: Download complete
1fe172e4850f: Pull complete
caf521ccaac6: Pull complete
b3278b635dc9: Pull complete
4298f8ff43f9: Pull complete
56eb47d0c00a: Pull complete
Digest: sha256:ad719a882ac0594bdc92abccff22e5b6713bbf9893320264fd9e8affd8a6f470
Status: Downloaded newer image for python:slim-bullseye
 ---> c3e38abaf684
Step 2/6 : WORKDIR /app
 ---> Running in 10b9d77c6d58
Removing intermediate container 10b9d77c6d58
 ---> e064126dbdde
Step 3/6 : COPY . .
 ---> 7f8eab0d8533
Step 4/6 : RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
 ---> Running in 2183ebc84107
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting Flask>=2.0
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'charmap' codec can't encode characters in position 57-96: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/task.py", line 1012, in acr_task_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 187, in write_and_convert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-96: character maps to <undefined>
To open an issue, please run: 'az feedback'
```

**Comment by navba-MSFT** [comment]
@williamhbell Thanks for sharing the outcome of Plan 1 and Plan 2. May I know if you have tried the plan 3 mentioned in my above command ? Could you please update me the status once you get a chance ? Awaiting you reply.

**Comment by williamhbell** [comment]
Using the Dockerfile
```
# syntax=docker/dockerfile:1
FROM python:slim-bullseye
RUN apt update && apt upgrade -y && apt install locales -y && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
WORKDIR /app
COPY . .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
ENV PORT=5000
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT app:app"]
```

The az acr build fails as before:
```
...
debconf: falling back to frontend: Teletype
Generating locales (this might take a while)...
Generation complete.
Generating locales (this might take a while)...
Generation complete.
Removing intermediate container 24444b9f8319
 ---> 8d95737e8095
Step 3/10 : ENV LANG en_US.UTF-8
 ---> Running in e1748450b882
Removing intermediate container e1748450b882
 ---> 142039d7c672
Step 4/10 : ENV LANGUAGE en_US:en
 ---> Running in 06e2f8568e41
Removing intermediate container 06e2f8568e41
 ---> 06f5f5671fcd
Step 5/10 : ENV LC_ALL en_US.UTF-8
 ---> Running in db8ebe7be7b2
Removing intermediate container db8ebe7be7b2
 ---> c6f6aed6be03
Step 6/10 : WORKDIR /app
 ---> Running in 9fb63989a7d9
Removing intermediate container 9fb63989a7d9
 ---> b4364fdd1985
Step 7/10 : COPY . .
 ---> a5fea8ed00e0
Step 8/10 : RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
 ---> Running in 4868daeb0a3e
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.0.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'charmap' codec can't encode characters in position 80-119: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 187, in write_and_convert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 80-119: character maps to <undefined>
To open an issue, please run: 'az feedback'
```

**Comment by navba-MSFT** [comment]
@williamhbell Apologies for the late reply. I think it's a platform issue related to the unique combination Windows + GitBash (MSYS2)  + Python. 

Could you please try to update the Windows system language setting ?

Control panel -> Clock and Region -> Region -> Administrative -> Change system locale -> Check Beta: Use Unicode UTF-8 for worldwide language support
![image](https://user-images.githubusercontent.com/57353862/168459057-bab27aa2-1030-43bb-a53a-fb49699caa0f.png)


The change will require reboot. 

 

Also I would suggest you to switch to Windows Terminal for better support.

**Comment by navba-MSFT** [comment]
@williamhbell I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@williamhbell The action is currently pending on you to test the above action plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by AndreyBespamyatnov** [comment]
Unfortunately, we can see the same issue with our Azure Pipeline

**Comment by navba-MSFT** [comment]
@AndreyBespamyatnov If you are seeing the same issue with Windows image in Azure Devops Pipeline then the same above plan can be done by implementing this via registry key using PS. You can run the below PS script for that:

```
New-ItemProperty -LiteralPath 'HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage' -Name 'ACP' -Value '65001' -PropertyType String -Force;
New-ItemProperty -LiteralPath 'HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage' -Name 'OEMCP' -Value '65001' -PropertyType String -Force;
New-ItemProperty -LiteralPath 'HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage' -Name 'MACCP' -Value '65001' -PropertyType String -Force;
```
More Info [here](https://github.com/Azure/azure-cli/issues/23776#issuecomment-1239730959). Hope this helps.
