### ISSUE TITLE
`az login`: ImportError: cannot import name 'PersistenceNotFound' from 'msal_extensions.persistence'

### ISSUE THREAD

**Issue by fontechaje-AA** [Azure/azure-cli#22325]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'PersistenceNotFound' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 144, in login
    identity = _create_identity_instance(self.cli_ctx, self._authority, tenant_id=tenant)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 861, in _create_identity_instance
    from .auth.identity import Identity
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 19, in <module>
    from .persistence import load_persisted_token_cache, file_extensions, load_secret_store
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/auth/persistence.py", line 14, in <module>
    from msal_extensions.persistence import PersistenceNotFound
ImportError: cannot import name 'PersistenceNotFound' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-glibc2.10, Ubuntu 18.04.6 LTS
Python 3.8.1
Installer: PIP

azure-cli 2.31.0 *
azure-cli-ml 1.33.0

Extensions:
azure-cli-ml 1.33.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by edgex004** [comment]
I have also encountered this same error with `az login`

Fedora 5.17.5-300.fc36.x86_64
Python 3.10.7
pip 21.3.1

azure-common==1.1.25
azure-core==1.8.2
azure-identity==1.4.1
azure-keyvault-secrets==4.2.0
azure-storage-blob==12.5.0

**Comment by SBAESH** [comment]
Getting the same error with az_cli. Any solution yet?

**Comment by syss-ta1** [comment]
had the same issue. running > pip install azure-cli fixed the issue- it seems like it was installation got corrupted somehow!

**Comment by jiasli** [comment]
@syss-ta1, this lets `pip` reinstall Azure CLI's dependencies:

https://github.com/Azure/azure-cli/blob/07e1b17d4c0f9e4a4cd76fa9ff3838644be5e419/src/azure-cli-core/setup.py#L54
