### ISSUE TITLE
az sf cluster durability update fails with: 'ClustersOperations' object has no attribute 'update' error 

### ISSUE THREAD

**Issue by tanviapte** [Azure/azure-cli#22344]
I am trying to update the DurabilityLevel for one of our prod serviceFabric clusters using the commandlet 
az sf cluster durability update

but it fails with the following error:

The command failed with an unexpected error. Here is the traceback:
'ClustersOperations' object has no attribute 'update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicefabric/custom.py", line 538, in update_cluster_durability
AttributeError: 'ClustersOperations' object has no attribute 'update'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f434075-665e-b1fa-91ae-d54cddf1e28d
* Version Independent ID: 57942680-f335-9c72-f64f-0b89efdb5768
* Content: [az sf cluster durability](https://docs.microsoft.com/en-us/cli/azure/sf/cluster/durability?view=azure-cli-latest#az-sf-cluster-durability-update)
* Content Source: [latest/docs-ref-autogen/sf/cluster/durability.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sf/cluster/durability.yml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@tanviapte Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@tanviapte I am able to reproduce this issue at my end. I have reached out to the Product Owners with my findings. I will get back to you as soon as I hear from them.

**Comment by navba-MSFT** [comment]
@tanviapte The above PR has been filed to fix this issue. Currently @a-santamaria is working to activate the tests that runs through this code paths but it should be ready to be included on the next release [May 2022 (2022-05-24)](https://github.com/Azure/azure-cli/milestone/118).

Thanks @a-santamaria for your help.

**Comment by navba-MSFT** [comment]
@tanviapte While the PR is under review, In the meantime if you have any questions, please feel free to ask here.

**Comment by navba-MSFT** [comment]
@tanviapte This PR https://github.com/Azure/azure-cli/pull/22283 includes the fix and it is merged now. The fix should be available in the next release. Refer the [May milestone ](https://github.com/Azure/azure-cli/milestone/118). With that we will proceed with closure of this thread. If you need any further assistance on this in future, feel free to reopen this. We would be happy to help.
