### ISSUE TITLE
Region mapping missing when using az backup restore restore-disks

### ISSUE THREAD

**Issue by makowskip** [Azure/azure-cli#22342]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az backup restore restore-disks

**Describe the bug**
When trying to initiate a disk restore in secondary region below error occurs:

The command failed with an unexpected error. Here is the traceback:
'germanywestcentral'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom_base.py", line 411, in restore_disks
    return custom.restore_disks(cmd, client, resource_group_name, vault_name, container_name, item_name, rp_name,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom.py", line 1068, in restore_disks
    azure_region = secondary_region_map[vault_location]
KeyError: 'germanywestcentral'

There are missing entries in secondary_region_map defined in /opt/az/lib/python3.8/site-packages/azure/cli/command_modules/backup/custom.py for germanywestcentral and germanynorth 
After adding them manually command works and disk was restored.

**To Reproduce**
az backup restore restore-disks --storage-account <storage_account_in_germanynorth \
--container-name <backup_container_name> \
--item-name <backup_item_name> \
--resource-group <source_resource_group> \
--restore-to-staging-storage-account true \
--rp-name <recovery_point_name> \
--target-resource-group <target_resource_group> \
--use-secondary-region \
--vault-name <backup_vault_name>	

<backup_vault_name> is the name of a Recovery Services vault located in germanywestcentral with RA-GRS enabled

**Expected behavior**
Disk is restored without throwing error

**Environment summary**
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0 *

Extensions:
azure-firewall 0.13.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@makowskip Thank you for reaching out, we are looking into it.
