### ISSUE TITLE
az aks command fails when creating kubeconfig of file name is same as an existing directory

### ISSUE THREAD

**Issue by trevor-primer** [Azure/azure-cli#22383]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az aks get-credentials --name "${AKS_CLUSTER}" \
        --resource-group "${RESOURCE_GROUP}" \
        --admin \
        --file "$GITHUB_WORKSPACE"/config`

**Describe the bug**
When a folder exists with same name as file being created with kubeconfig it errors with `IsADirectoryError: [Errno 21] Is a directory: `

**To Reproduce**
- Create folder called config
- run az aks login command with --file name same as folder created in first step

**Expected behavior**
Should check if file exists, and not care if directory with same name exists

**Environment summary**
pip / 2.36.0 / Ubuntu / Bash

**Additional context**
`ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [Errno 21] Is a directory: '/runner/_work/gui2/gui2/config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 2286, in aks_get_credentials
    _print_or_merge_credentials(
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 3526, in _print_or_merge_credentials
    merge_kubernetes_configurations(
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 1183, in merge_kubernetes_configurations
    existing = load_kubernetes_configuration(existing_file)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 1172, in load_kubernetes_configuration
    with open(filename) as stream:
IsADirectoryError: [Errno 21] Is a directory: '/runner/_work/gui2/gui2/config'`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@trevor-primer AFAIK you can't have a file and folder with the same name in the same directory. A folder is just a special kind of file.
