### ISSUE TITLE
Retrieving an Azure Data Table with GUID column will return "Object of type UUID is not JSON serializable" error

### ISSUE THREAD

**Issue by tsteenbakkers** [Azure/azure-cli#22436]
## Describe the bug

**Command Name**
`az storage entity query`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Object of type UUID is not JSON serializable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 146, in out
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 37, in format_json
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
  File "json\encoder.py", line 431, in _iterencode
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 325, in _iterencode_list
  File "json\encoder.py", line 405, in _iterencode_dict
  File "json\encoder.py", line 438, in _iterencode
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 30, in default
  File "json\encoder.py", line 179, in default
TypeError: Object of type UUID is not JSON serializable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage entity query --table-name {} --connection-string {} --output JSON`
note that the following command will return the same error:
- `az storage entity query --table-name {} --connection-string {}`

## Expected Behavior

This is related and most likely the same as bugs #22429 and #22250.

Expecting to have a returned result with all columns including the Guid type column

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/10227683/168537657-7296d5bb-e2f1-40f9-814c-823f61569d45.png)

**Comment by zale1983** [comment]
@evelyn-ys 
please check on portal if gid: e4f05187-... is type [GUID]
![wecom-temp-718c1274d3085a7210f078c2b8ae3028](https://user-images.githubusercontent.com/43394331/168723074-7d30d5c2-83ed-4bd9-a524-3d23dee87d51.png)
![wecom-temp-cd2e1f1df5bb6ef79cf3848838943a20](https://user-images.githubusercontent.com/43394331/168723096-22db4c1a-e5ce-4a7d-837d-40133bc9b7aa.png)
![wecom-temp-f940d022f125465f9002a936978ff448](https://user-images.githubusercontent.com/43394331/168723112-9c865038-d2df-49b4-85f0-61f08451ed52.png)

**Comment by evelyn-ys** [comment]
We can reproduce now. You can use `Key=value Key@odata.type="Edm.Guid"` to insert guid key with CLI. We do find that the query is broken and @jonie001 is working on the fix

**Comment by tsteenbakkers** [comment]
@evelyn-ys I am aware of how to define specific data types when inserting data. Thanks for the tip though :)

Hope this can be fixed soon :)
