### ISSUE TITLE
No module named 'decorator' on webapp up

### ISSUE THREAD

**Issue by adamringeisen** [Azure/azure-cli#22445]
## Describe the bug
Brand new install of Fedora 36. Installed azure-cli got this error. Upgraded using az upgrade, same error. 

I saw a closed issue with a similar problem for an older version, but it appears that this is not fixed or has reared its head again.
**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'decorator'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fabric/connection.py", line 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/adam/.local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 25, in <module>
    from fabric import Connection
  File "/usr/lib/python3.10/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/lib/python3.10/site-packages/fabric/connection.py", line 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --os-type {}`

## Environment Summary
```
Linux-5.17.6-300.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Workstation Edition)
Python 3.10.4
Installer: PIP

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@adamringeisen Can you please look this issue and try the action plan provided there? https://github.com/Azure/azure-cli/issues/13343#issuecomment-635811624

**Comment by adamringeisen** [comment]
Well the action described there is to upgrade to a newer version of the cli and I am using the newest version so no I can’t try the action described there.

**Comment by RakeshMohanMSFT** [comment]
@adamringeisen Apologies, i mean this comment https://github.com/Azure/azure-cli/issues/13343#issuecomment-624367680. I am still looking into it, in the meantime give it a try.

**Comment by adamringeisen** [comment]
The command didn't work unless I removed the --system argument. 

Then it did work but I got a warning about using sudo with pip potentially causing errors with system package manager.

file:///home/adam/Pictures/Screenshots/Screenshot%20from%202022-05-15%2005-56-42.png

**Comment by panchagnula** [comment]
this seems like a problem with CLI install package - please try with a brand new full  re-install of CLI.

**Comment by lucas-thimoteo-sy** [comment]
Hello, already followed all the steps and is still not working.

Any solution?
