### ISSUE TITLE
Error on creating an Advisor CPU Threshold

### ISSUE THREAD

**Issue by thomasnield** [Azure/azure-cli#22450]
## Describe the bug

I get an error running this command. 

```
az advisor configuration update --low-cpu-threshold 5
```

**Command Name**
`az advisor configuration update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 191, in handler
    instance = cached_get(self.cmd, getter, **getterargs)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 409, in cached_get
    return _get_operation()
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 404, in _get_operation
    result = operation(**kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/advisor/custom.py", line 85, in show_configuration
    return list(output)[0]
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az advisor configuration update --low-cpu-threshold {}`

## Environment Summary
```
macOS-12.2.1-arm64-arm-64bit, Darwin 21.3.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.36.0

Extensions:
azure-firewall 0.13.0
databricks 0.8.0
logic 0.1.5
azure-devops 0.23.0
interactive 0.4.5
account 0.2.2
blueprint 0.3.1
costmanagement 0.1.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
advisor

**Comment by mojayara** [comment]
Closing this issue as the command is working as expected. Please reopen the issue if the CX is facing the issue.
