### ISSUE TITLE
Trying to install aks cli on osx Monterey (12.3.1 (21E258)) M1

### ISSUE THREAD

**Issue by kventil** [Azure/azure-cli#22463]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 813, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/var/folders/2h/cfdyy6bs55qbqm6why4q7gm00000gn/T/tmpep97r28m/bin/darwin_arm64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 369, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version,
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 496, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 833, in move
    copy_function(src, real_dst)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
macOS-12.3.1-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kventil Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide more details once we have an update on this.

**Comment by navba-MSFT** [comment]
@kventil Apologies for the late reply. This is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions). This issue would occur, if you do not have full access to the /usr/local/bin path.

You can try with the `sudo az aks install-cli` and check if that helps. Alternatively, You can follow the below to install in a different location (download to a specified path) in the home folder, for example:

>az aks install-cli --install-location **mykubetools**/kubectl1.23.5  --client-version 1.23.5  --kubelogin-install-location **mykubetools**/kubelogin

Please ensure that **mykubetools** is in your search **PATH**, so the kubelogin command can be found.

Hope this helps.

**Comment by navba-MSFT** [comment]
@kventil I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kventil The action is pending on you to follow the above action plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
