### ISSUE TITLE
Getting some FileNotFoundError while retrieving credentials

### ISSUE THREAD

**Issue by Thlr** [Azure/azure-cli#22473]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2286, in aks_get_credentials
    _print_or_merge_credentials(
  File "/opt/azure-cli/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 3517, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks get-credentials --resource-group {} --name {}`

Note that both the resource group and the cluster name I am getting credentials from contain hyphens. Both were created with Terraform, and it did not cause any issue.

## Expected Behavior

It does not error out, or if it does, it does so with an intellegible message.

## Environment Summary
```
Linux-5.17.1-arch1-1-x86_64-with-glibc2.35, Arch Linux
Python 3.9.4
Installer: 

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Thlr Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Thlr hlr Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
