### ISSUE TITLE
Getting "FileNotFoundError: [WinError 2] The system cannot find the file specified" when trying to download a pipeline artifact

### ISSUE THREAD

**Issue by bbi-adamvengroff** [Azure/azure-cli#22480]
Getting `FileNotFoundError: [WinError 2] The system cannot find the file specified` when trying to download a pipeline artifact

**Command Name**
`az pipelines runs artifact download --artifact-name {artifactName} --path {path} --run-id {id }--org {org_url} --project {project}`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\pipelines\runs_artifacts.py", line 27, in run_artifact_download
    return artifact_tool.download_pipeline_artifact(
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 25, in download_pipeline_artifact
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 74, in run
    self.start(command_args, env)
  File "C:\Users\miles.miller\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 33, in start
    self._proc = subprocess.Popen(
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
To open an issue, please run: 'az feedback'
```

## To Reproduce:
Just run the command
Error only happening on 1 user's PC

## Expected Behavior
Artifact downloads

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

Extensions:
azure-devops 0.22.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into the DevOps Pipeline artifacts issues

@v-anvashist, @V-hmusukula Please look into this issue and provide an update once you get a chance

**Comment by bbi-adamvengroff** [comment]
Thanks for triaging @navba-MSFT! Do we have a sense on what the turn-around times for a response typically looks like?

**Comment by navba-MSFT** [comment]
@bbi-adamvengroff The SLA followed by Service Team items is to provide an update on all questions once every 30 days, and an update on all bugs once every 90 days. If this issue is very critical, I would recommend you to open a support ticket.

@v-anvashist, @V-hmusukula Could you please provide an update on this ? Awaiting your reply.

**Comment by v-anvashist** [comment]
@navba-MSFT  We received this incident last week and recently start working on this service.

We are trying to repro it and will share the updates to you.

Thanks,
Anjali

**Comment by v-soujanya** [comment]
Hi @bbi-adamvengroff,
We are not able to repro the use, we are able to download the artifacts successfully. Please try to pass the correct path to download artifacts. Please find the Image for reference.
<img width="621" alt="Cli" src="https://user-images.githubusercontent.com/101401302/170680127-77d3bf74-fae3-479b-af5b-a0aab0cf2e44.PNG">


Currently we are using azure-cli 2.34.1 version *
Please let me know if any other information required. Thanks!

**Comment by bbi-adamvengroff** [comment]
Hi @v-soujanya 

Thanks for the response
We tried reproing the issue and it's stopped happening
I will re-open the ticket if it happens again
