### ISSUE TITLE
Error trying to look up resource by ID

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-cli#2248]
Per the example in the help output for "az resource show -h", I should be able to look up a resource by it's id:
show a webapp using resource id
    az resource show --id /subscriptions/<my_sub_id>/resourceGroups/myGroup/providers/Microsoft.Web/sites/myWebapp

When I run the command:
_az resource show --id "/subscriptions/<my_sub_id>/resourcegroups/bocconitestlabrg138089/providers/microsoft.devtestlab/labs/bocconitestlab/virtualmachines/tasktest1"_

I get the following error:
'type'
Traceback (most recent call last):
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 341, in _execute_command

    result = exception_handler(ex)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\_util.py", line 48, in empty_on_404
    raise ex
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 338, in _execute_command

    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\resource\custom.py", line 147, in show_re
source
    resource_id, api_version)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\resource\custom.py", line 572, in __init_
_
    api_version = _ResourceUtils._resolve_api_version_by_id(self.rcf, resource_id)
  File "C:\Users\scotmoor\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\resource\custom.py", line 669, in _resolv
e_api_version_by_id
    resource_type = parts['type']
KeyError: 'type'

**Comment by tjprescott** [comment]
> az resource show --id "/subscriptions/00000/resourcegroups/bocconitestlabrg138089/providers/microsoft.devtestlab/labs/bocconitestlab/virtualmachines/tasktest1"

Where are you getting this ID from?  In trying to recreate this error, I created a DevTest Lab in the portal and then provisioned a VM. However, that VM gets created in a different resource group, not as a child of the DevTest Lab. All `resource show --id {id}` operations I tried on the lab or the VM that was created worked fine.

**Comment by scotmoor** [comment]
I got the ID from [Azure Resource Explorer](https://resources.azure.com)
