### ISSUE TITLE
Error when trying to connect to a new kubernetes cluster

### ISSUE THREAD

**Issue by tudor-pop** [Azure/azure-cli#22494]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2286, in aks_get_credentials
    _print_or_merge_credentials(
  File "/opt/homebrew/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3517, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-12.3.1-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by mdenhoedt** [comment]
This looks related to #20996 and #21135, which also don't have a solution yet.

**Comment by navba-MSFT** [comment]
@tudor-pop Apologies for the late reply. Thanks for reaching out to us and reporting this issue. You can check under the user profile for file **~/.kube/config.** There are 3 required sections which must be present: clusters, contexts and users. There might be an issue in fetching details from this config file. 

To isolate the issue, You can try to **rename** or **delete** this config file and try to run the [az aks get-credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) and check if that helps.

Alternatively you can pass the _--file_ or _--overwrite-existing_ parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

Please let me know if you have any further questions on this. Awaiting your reply.

**Comment by tudor-pop** [comment]
Hello @navba-MSFT Unfortunately I can't help you any further and I don't know how it happened. I think I followed the standard terraform [tutorial](https://learn.hashicorp.com/collections/terraform/azure-get-started). You can try to go through it and see if you encounter the issue...it should be the setup part where you connect to azure. 
I'm on a Mac Monterey 12.4 and now have the 2.37 az CLI ... if you're not able to reproduce, I'm afraid I can't help it further than this

**Comment by navba-MSFT** [comment]
@tudor-pop I am unable to repro this issue on my windows box. Unfortunately, I don't have the same machine as your environment. If you are still able to reproduce this issue, check if my above suggestion helps. If it doesn't help, please feel free to reopen this issue, we would be happy to help.
