### ISSUE TITLE
List index error when executing `az advisor configuration show`

### ISSUE THREAD

**Issue by sstoops** [Azure/azure-cli#22534]
## Describe the bug

**Command Name**
`az advisor configuration show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/advisor/custom.py", line 85, in show_configuration
    return list(output)[0]
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az advisor configuration show`

## Environment Summary
```
Linux-5.4.0-109-generic-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@sstoops Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@sstoops This advisor must have at least one default configuration when we get it by subscription API (the default), therefore I suggest you trying this API call once and let me know what output you get. https://docs.microsoft.com/en-us/rest/api/advisor/configurations/list-by-subscription. 

If that API call is also empty then you will have to file a support ticket.

**Comment by RakeshMohanMSFT** [comment]
@sstoops Yes, i was referring to API because internally CLIs call APIs and it is expected that the API return at least one object, which in your case is not happening that is is why it is failing. Can you please open a support ticket?

**Comment by RakeshMohanMSFT** [comment]
Thank you @sstoops. I will close this issue now.

**Comment by v-saadsaiyed** [comment]
Hi there @sstoops I looked at the backend logs from the ticket you create on the support portal and I just wanted to post my finding here for others if they have similar issue.

The backend shows "Received '1' resources. Returning '0' resources after filtering."
This means that the get request for the recommendation is actually returning 1 resource but after the ARM filter it seems final request return is 0. So I'm afraid this is because this user don't have permission to view advisory recommendation.
As the list returns empty, you cannot configure the empty list with anything and so you get index out of bound.

If the user doesn't have permissions on this resource, ARM will return the empty array as it is filtering out the response based on RBAC.
I believe CLI should handle this scenario gracefully by verifying the user permissions as the index out of bounds exception is not a friendly response to the user
