### ISSUE TITLE
az aks get-credentials failed with error : socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by asafsofer-sl** [Azure/azure-cli#22559]
## Describe the bug

**Command Name**
``

**Errors:**
```

```

## To Reproduce:
run 

az aks get-credentials --resource-group MyResourceGroup --name MyClsutername

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior

should get the credentials  , instead getting the below error 

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd9dc051a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/az/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.29, Ubuntu 20.04 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
aks-preview 0.5.39

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@asafsofer-sl Thanks for reaching out to us and sharing this feedback. Looking at the error message, it seems like the issue is at the Network socket layer causing the connection failure. Could you confirm if there are any proxy / firewall in your corporate network ? Could you please test it from a different network and check if you still face the same issue ? Awaiting your reply.

**Comment by asafsofer-sl** [comment]
Hi @navba-MSFT  , Yes you are totally right , look like there was security update on my laptop causing my FW to block the access.
anyway resolved now , after i regain the access by changing my FW configuration .
