### ISSUE TITLE
keyvault certificate download gives 'Bad Request'

### ISSUE THREAD

**Issue by dtzar** [Azure/azure-cli#22575]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az keyvault certificate download --file $CERT_PATH --vault-name $AKV_NAME --name $KEY_ID`

**Describe the bug**
I try to download a certificate which I have access to in AKV using this command and it gives the error:
`Operation returned an invalid status code 'Bad Request'`

**To Reproduce**
https://github.com/Azure/notation-azure-kv/blob/07758764ba0319d6cf1f17b189b1933e7639e0f3/docs/nv2-sign-verify-aks.md#store-the-signing-certificate-in-azure-key-vault

**Expected behavior**
Certificate file downloads successfully.

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
aks-preview 0.5.56
azure-cli-ml 1.37.0
azure-iot 0.10.15
k8s-config 0.1.0
k8s-extension 1.0.4

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Additional context**

```shell
az keyvault certificate download --file $CERT_PATH --vault-name $AKV_NAME --name $KEY_ID --encoding PEM --debug
cli.knack.cli: Command arguments: ['keyvault', 'certificate', 'download', '--file', './wabbitnetworks.pem', '--vault-name', 'redacted', '--name', 'https://<redacted>.vault.azure.net/keys/wabbitnetworks/2de43313f57f489581f6e0eec4e7ddc2', '--encoding', 'PEM', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa3d1015280>, <function OutputProducer.on_global_arguments at 0x7fa3d0fbc160>, <function CLIQuery.on_global_arguments at 0x7fa3d0f51670>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: keyvault                  0.016        20       122
cli.azure.cli.core: Total (1)                 0.016        20       122
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 20 groups, 122 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : keyvault certificate download
cli.azure.cli.core: Command table: keyvault certificate download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa3d07315e0>]
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa3d06af9d0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa3d0602d30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa3d0602e50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa3d0fbc1f0>, <function CLIQuery.handle_query_parameter at 0x7fa3d0f51700>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa3d0602dc0>]
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.service_client: Accept header absent and forced to application/json
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): redacted.vault.azure.net:443
urllib3.connectionpool: https://<redacted>.vault.azure.net:443 "GET /certificates/https%3A%2F%2F<redacted>.vault.azure.net%2Fkeys%2Fwabbitnetworks%2F2de43313f57f489581f6e0eec4e7ddc2/?api-version=7.0 HTTP/1.1" 400 3420
msrest.exceptions: Cannot deserialize content-type: text/html
msrest.exceptions: Operation returned an invalid status code 'Bad Request'
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 112, in keyvault_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/keyvault/custom.py", line 1692, in download_certificate
    cert = client.get_certificate(
  File "/opt/az/lib/python3.8/site-packages/azure/keyvault/v7_0/key_vault_client.py", line 3648, in get_certificate
    raise models.KeyVaultErrorException(self._deserialize, response)
azure.keyvault.v7_0.models.key_vault_error_py3.KeyVaultErrorException: Operation returned an invalid status code 'Bad Request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 38, in keyvault_exception_handler
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'HTTPError' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 138, in keyvault_command_handler
    return keyvault_exception_handler(self.command_loader, ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 40, in keyvault_exception_handler
    raise CLIError(ex)
knack.util.CLIError: Operation returned an invalid status code 'Bad Request'

cli.azure.cli.core.azclierror: Operation returned an invalid status code 'Bad Request'
az_command_data_logger: Operation returned an invalid status code 'Bad Request'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa3d0731820>]
cli.__main__: Command ran in 1.283 seconds (init: 0.213, invoke: 1.070)
```

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
Need keyvault server side investigation

**Comment by aramase** [comment]
@dtzar I did a quick test

1. `--name` can only be the name of the certificate. It can't be the id.
2. To get the certificate using the id, you can run `az keyvault certificate download --file $CERT_PATH --id $CERT_ID`. When id is provided, vault name is not required.

To get the certificate id, you can run
```
az keyvault certificate show -n $CERT_NAME --vault-name $VAULT_NAME --query 'id' -otsv
```

**Comment by aramase** [comment]
cc @jlichwa to correct me if I'm wrong

**Comment by dtzar** [comment]
`az keyvault certificate download --file $CERT_PATH --id https://redacted.vault.azure.net/certificates/wabbitnetworks/2de43313f57f489581f6e0eec4e7ddc2 --encoding PEM` 
worked!
Same issue if I use the `--vault-name` and `--name` versus `--id`

**Comment by aramase** [comment]
@dtzar what are you using in the `--name` as part of the command?

This worked fine for me:
```bash
➜ az keyvault certificate download --name notary --vault-name notarykv --file testfile
```

**Comment by dtzar** [comment]
Weird.  Now the same command which caused the problem works for me and I've changed nothing (not even logging out/in again).  Perhaps something was just fixed on the backend @evelyn-ys ?

**Comment by evelyn-ys** [comment]
CLI didn't make any change😂

**Comment by navba-MSFT** [comment]
@dtzar Since there were no changes on the AzCLI side, it could have been a transient issue. Since the issue is auto-resolved, feel free to reopen this thread if the issue resurfaces again. We would be happy to investigate and assist you further.
