### ISSUE TITLE
`az storage account create` fails on Fedora 35

### ISSUE THREAD

**Issue by worming004** [Azure/azure-cli#22578]
## Describe the bug

I was trying to create a volume following this doc https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

**Command Name**
`az storage account create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 683, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 837, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --resource-group <personnal-resource-group> --name <globally-unique-name> --location westeurope`

## Expected Behavior

create a new storage

## Environment Summary
```
Linux-5.17.5-200.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Workstation Edition)
Python 3.10.4
Installer: RPM

azure-cli 2.37.0
```
## Additional Context

I've got the same exception before doing an `az upgrade`, it was version 2.36.0

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Seems like the dependency package is broken. Can you make sure you have installed CLI correctly with https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?

**Comment by dhageman** [comment]
@evelyn-ys I am also seeing this issue.  This is on Fedora 36 using the RPMs installed from the link you referenced.  I tested the 2.37.0 and the 2.36.0 rpms.  They both demonstrated the behavior above.  

As a test, I installed the azure-cli (2.37.0) using pip into a python virtual environment and that installation is working fine.

I do see a difference in the installed supporting libraries between the two installation methods.  I didn't debug further.

**Comment by evelyn-ys** [comment]
@jiasli Can you help take a look on packaging issue?

**Comment by jiasli** [comment]
Fedora 35 is not official supported (https://github.com/Azure/azure-cli/issues/22278).

Fedora repo has its own unofficial Azure CLI published which overrides our official `el7` package:

```
# dnf info azure-cli
Last metadata expiration check: 0:00:49 ago on Tue Jun  7 05:32:44 2022.
Available Packages
Name         : azure-cli
Version      : 2.37.0
Release      : 1.el7
Architecture : x86_64
Size         : 52 M
Source       : azure-cli-2.37.0-1.el7.src.rpm
Repository   : azure-cli
Summary      : Azure CLI
URL          : https://docs.microsoft.com/cli/azure/install-azure-cli
License      : MIT
Description  : A great cloud needs great tools; we're excited to introduce Azure CLI,
             :  our next generation multi-platform command line experience for Azure.

Name         : azure-cli
Version      : 2.37.0
Release      : 4.fc35
Architecture : noarch
Size         : 3.7 M
Source       : azure-cli-2.37.0-4.fc35.src.rpm
Repository   : updates
Summary      : Microsoft Azure Command-Line Tools
URL          : https://github.com/Azure/azure-cli
License      : MIT
Description  : Microsoft Azure Command-Line Tools
```


https://packages.fedoraproject.org/pkgs/azure-cli/azure-cli/

![image](https://user-images.githubusercontent.com/4003950/172303862-340dfbbf-8c0c-4c70-a17e-2de6691ea706.png)

Even the official RPM doesn't work on RPM:

```
# dnf install azure-cli-2.37.0-1.el7
# az storage account create -h
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 837, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
```

This is explained by https://github.com/Azure/azure-cli/issues/22235#issuecomment-1118275063
