### ISSUE TITLE
failed to refresh advisor recommendation list

### ISSUE THREAD

**Issue by je-ru** [Azure/azure-cli#22577]
## I failed to refresh advisor recommendation list using az

**Command Name**
`az advisor recommendation list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
request() got an unexpected keyword argument 'raw'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/advisor/custom.py", line 13, in list_recommendations
    _generate_recommendations(client)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/advisor/custom.py", line 139, in _generate_recommendations
    response = client.generate(raw=True)
  File "/opt/az/lib/python3.8/site-packages/azure/mgmt/advisor/operations/_recommendations_operations.py", line 84, in generate
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 327, in send
    response = self.session.request(  # type: ignore
TypeError: request() got an unexpected keyword argument 'raw'

```

## To Reproduce:
- `az advisor recommendation list --resource-group {} --refresh`
or
- `az advisor recommendation list --refresh`

## Expected Behavior
 Refresh without failure :)

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0 *

Extensions:
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@je-ru Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will get back to you if I need more information.

**Comment by navba-MSFT** [comment]
@je-ru Could you please run the below command and check if that helps ? The below command initiates the recommendation generation or computation process for a subscription. This operation is asynchronous. 

>az login
>
>az rest --method POST --uri https://management.azure.com/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Advisor/generateRecommendations?api-version=2020-01-01

Awaiting your reply.

**Comment by je-ru** [comment]
I get "Successfully refreshed recommendations for Azure Advisor" in the notifications, but when I select the affected VM and go to "Advisor recommendations" I can see under "last updated" the date from yesterday. So that one is still old.

**Comment by navba-MSFT** [comment]
@je-ru Thanks for getting back. Did you follow my above suggested action plan ? May I know the outcome of that ?

**Comment by je-ru** [comment]
Yes, I did.
I see no output from the second command.
Beyond that the result was described in my previous comment.

**Comment by navba-MSFT** [comment]
@je-ru Thanks for your reply. I am checking with the Product Owners regarding this. I will get back to you once I hear from them

**Comment by navba-MSFT** [comment]
@je-ru Apologies for delay in getting back. I have heard back from the Product Owners. I am sharing the update in this thread.

>The generate recommendations API is on path to be deprecated and is no longer required to be run to refresh the recommendations. Advisor platform refreshes recommendations automatically in background every 24 hours. 

If you don't see the refresh happening in 24 hours, please feel free to open a support ticket. Our support professionals would be happy to assist you further.

**Comment by je-ru** [comment]
Thanks for your investigation.
24 hours refresh seems to work, but when I'm working on a list of advices I would like to refresh during the day to see the progress. Please forward this to the Product Owners

**Comment by navba-MSFT** [comment]
@je-ru I have shared the feedback with the Product Group. They have confirmed that the recommendations are refreshed in background automatically as we get new data from respective services (24 hours time frequency). Currently, there is no way to trigger on demand refresh. Hope this answers.

So with that we will proceed with closure of this issue. If you need any further assistance on this, feel free to reopen this issue. We would be happy to help.

**Comment by Miti-Shah** [comment]
Hi , we have updated our setting on the resource as per advisory recommendation but when it got refreshed next , the recommendation is still there. what to do?
