### ISSUE TITLE
az storage entity insert is failing with 'tuple' object has no attribute 'replace'

### ISSUE THREAD

**Issue by jgercken** [Azure/azure-cli#22589]
az storage entity insert recently began failing

**Command Name**
`az storage entity insert`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
PartitionKey or RowKey must be of type string.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/data/tables/_serialize.py", line 38, in _prepare_key
    return keyvalue.replace("'", "''")
AttributeError: 'tuple' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    first(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 408, in new_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/table.py", line 77, in insert_entity
    client.get_entity(partition_key, row_key)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/data/tables/_table_client.py", line 609, in get_entity
    partition_key=_prepare_key(partition_key),
  File "/opt/az/lib/python3.10/site-packages/azure/data/tables/_serialize.py", line 40, in _prepare_key
    raise TypeError('PartitionKey or RowKey must be of type string.')
TypeError: PartitionKey or RowKey must be of type string.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `rowkey=333; az storage entity insert --only-show-errors --account-name {} -t {} --if-exists fail -e \ 
-      RowKey="$rowkey" \
        RowKey@odata.type=Edm.String  \
        PartitionKey=P1 \
        PartitionKey@odata.type=Edm.String `

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
storage
