### ISSUE TITLE
Enabling addon failure

### ISSUE THREAD

**Issue by mlovse1** [Azure/azure-cli#22587]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2232, in aks_enable_addons
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/addonconfiguration.py", line 695, in add_virtual_node_role_assignment
AttributeError: 'NoneType' object has no attribute 'rpartition'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --resource-group {} --name {} --addons {} --subnet-name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mlovse1 Thanks for reaching out to us and sharing this feedback. Could you please let me know the complete Az CLI command that you had executed ? Also please run the CLI command with --debug switch and share the output here. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mlovse1 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please share the --debug output details so that we can assist you further on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mlovse1 Once you are ready to resume troubleshooting on this, please provide us the details of the issue with --debug switch and the complete command that was executed. So for now, we will now proceed with closure of this github issue. Please feel free to reopen this thread once you have the requested details. We would be happy to help.
