### ISSUE TITLE
az rest command opening json body as latin-1 instead of utf-8

### ISSUE THREAD

**Issue by TeamDman** [Azure/azure-cli#22616]
**Related command**

```
powershell>az rest --body `@myfile.json
```

**Describe the bug**
az cli opening the json file without using utf-8 encoding

```
ERROR: The command failed with an unexpected error. Here is the traceback:                                           ]
ERROR: 'latin-1' codec can't encode character '\u2584' in position 25229: Body ('▄') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 23, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 973, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 394, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 239, in request
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1327, in _send_request
  File "http\client.py", line 166, in _encode
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2584' in position 25229: Body ('▄') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**To Reproduce**

Have a json with `W▄RTTEMBERG` as a value somewhere

**Expected behavior**
No error

**Environment summary**

```
azure-cli                         2.36.0 *

core                              2.36.0 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.25.0
costmanagement                     0.2.1
databricks                         0.8.0
resource-graph                     2.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\me\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**

Trying to avoid https://github.com/Azure/azure-cli/issues/10339 by using a json file instead of inlining the json in the command

https://stackoverflow.com/questions/29354602/powershell-error-the-command-line-is-too-long

https://stackoverflow.com/questions/63413704/azure-cli-rest-issue-with-encoding-german-umlauts

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by TeamDman** [comment]
May also be an issue with fetching data and not just posting using the `az rest` command, when I manually fetch details on our configured trusted publishers for [adaptive application controls](https://docs.microsoft.com/en-us/azure/defender-for-cloud/adaptive-application-controls) the umlaut shows properly in the azure portal but the fetched data seems to have changed the character to a square

**Comment by navba-MSFT** [comment]
@TeamDman Apologies for the late reply. I think it's a platform issue related to the unique combination Windows + Python.

Could you please try to update the Windows system language setting ?

Control panel -> Clock and Region -> Region -> Administrative -> Change system locale -> Check Beta: Use Unicode UTF-8 for worldwide language support.

![image](https://user-images.githubusercontent.com/57353862/172097732-4d27f258-5f5b-47cb-b100-20af81bd11bb.png)

The change will require reboot. Please let me know if you still face the Hope this helps.

**Comment by ZeChArtiahSaher** [comment]
Doesn't work on posix az-cli. Just add body encoding arg cmon

**Comment by TeamDman** [comment]
I've just re-encountered this again on a new machine because Windows defaults to not utf-8.

😿
https://github.com/AAFC-Cloud/Cloud-Terrastodon/blob/64b6dd639d14411bcbfaaff29f5da515a732fe66/rust/crates/command/src/command.rs#L813-L847

Can we get a --encoding arg or a warning or something
