### ISSUE TITLE
Can't create storage account

### ISSUE THREAD

**Issue by bashilias** [Azure/azure-cli#22665]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 837, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --name {} --resource-group {} --location {} --sku {} --encryption-services {}`

## Environment Summary
```
Linux-5.17.11-200.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Workstation Edition)
Python 3.10.4
Installer: RPM

azure-cli 2.37.0
```

**Comment by evelyn-ys** [comment]
Seems like CLI's dependency isn't installed correctly. `azure-multiapi-storage` package went wrong. Can you please install Azure CLI following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by bashilias** [comment]
Thanks. I had an old repo in my repolist and there is an old 'az-cli' version in the Fedora repo. 
Reinstalled az-cli from the correct repo.
