### ISSUE TITLE
Can not update storage file share smb properties

### ISSUE THREAD

**Issue by goelankit** [Azure/azure-cli#22694]
## Describe the bug

**Command Name**
`az storage account file-service-properties update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'smb'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 200, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/account.py", line 693, in update_file_service_properties
AttributeError: 'NoneType' object has no attribute 'smb'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account file-service-properties update --resource-group {} --account-name {} --versions {} --channel-encryption {} --auth-methods {} --kerb-ticket-encryption {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0 *

Extensions:
azure-devops 0.18.0
connectedk8s 0.2.7
k8sconfiguration 0.2.0

```

**Comment by yonzhan** [comment]
storage

**Comment by zoeperryman** [comment]
Getting the same problem, slightly different timing though.

I did a deployment this morning at 2022-06-03T01:51Z and this worked fine, a few hours later at 2022-06-03T04:23:34Z and we are getting the above error. As far as I can see nothing in the environment changed, these are being run from an Azure DevOps Agent:

```
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

Running from my own laptop using the `storage-preview` extension of `0.7.4` (old version) worked fine, upgrading to `0.8.3` (the latest), or removing it completely and I get the above error message. 

The specific command we are using (unsure if it matters):
```
az storage account file-service-properties update --resource-group <rg> --account-name <account> --enable-delete-retention true --delete-retention-days 7
```

**Comment by evelyn-ys** [comment]
This is a regression because of service response breaking change. CLI will be more compatible after https://github.com/Azure/azure-cli/pull/22691

**Comment by RakeshMohanMSFT** [comment]
@goelankit Please upgrade to that latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.
