### ISSUE TITLE
Attempting to create volume group via CLI. 

### ISSUE THREAD

**Issue by ynot-commit** [Azure/azure-cli#22690]
## Describe the bug

**Command Name**
`az netappfiles volume-group create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'VolumeGroupsOperations' object has no attribute 'resource_groups'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/netappfiles/_exception_handler.py", line 18, in netappfiles_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/netappfiles/custom.py", line 571, in create_volume_group
    location = client.resource_groups.get(resource_group_name).location
AttributeError: 'VolumeGroupsOperations' object has no attribute 'resource_groups'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az netappfiles volume-group create -g {} --account-name {} --pool-name {} --volume-group-name {} --vnet {} --ppg {} --sap-sid {}`

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
aem 0.3.0
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@ynot-commit Thank you for reaching out, we are looking into it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by ynot-commit** [comment]
Hi, Any update around this bug?

**Comment by RakeshMohanMSFT** [comment]
@ynot-commit We are still working on it, will keep you posted. It looks like a regression but we are yet to confirm.

**Comment by RakeshMohanMSFT** [comment]
Thank you @hildurhodd. @ynot-commit Let me know if that helps please.

**Comment by ynot-commit** [comment]
Hi Rakesh, Yes, this (location) is an easy attribute to add. Thank you all for the quick resolution.
