### ISSUE TITLE
az storage file list --exclude-dir fails when specified --path is non-empty

### ISSUE THREAD

**Issue by marklemmon** [Azure/azure-cli#22702]
## Describe the bug

**Command Name**
`az storage file list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'DirectoryProperties' object has no attribute 'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/file.py", line 132, in list_share_files
    return list(f for f in results if isinstance(f.properties, t_file_properties))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/file.py", line 132, in <genexpr>
    return list(f for f in results if isinstance(f.properties, t_file_properties))
AttributeError: 'DirectoryProperties' object has no attribute 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- pass a value for --path that contains a sub-directory to:
- `az storage file list --exclude-dir --num-results {} --path {} --share-name {}`

## Expected Behavior

The contents of the `path` are returned

## Environment Summary
```
Linux-4.14.275-207.503.amzn2.x86_64-x86_64-with-glibc2.28, Debian GNU/Linux 10 (buster)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0
```
## Additional Context

I originally thought this only occurred when there was a directory present, but I've also seen this error:

```
The command failed with an unexpected error. Here is the traceback:
'FileProperties' object has no attribute 'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/file.py", line 132, in list_share_files
    return list(f for f in results if isinstance(f.properties, t_file_properties))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/file.py", line 132, in <genexpr>
    return list(f for f in results if isinstance(f.properties, t_file_properties))
AttributeError: 'FileProperties' object has no attribute 'properties'
```

This makes me think it's just failing on the first object it encounters, whether that's a file or a directory.

Running the same command without the `--exclude-dir` flag returns the expected result.

This was behaving as expected in 2.36.0

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Thanks for your report. Sorry for the inconvenience. We will fix this in our next release!

**Comment by RakeshMohanMSFT** [comment]
@marklemmon This is working now.
![image](https://user-images.githubusercontent.com/49954584/186936589-c326d654-d3d7-4381-8a1e-0ba3707f485b.png)
