### ISSUE TITLE
Issue when trying to create rule via AZ CLI

### ISSUE THREAD

**Issue by Brudem** [Azure/azure-cli#22715]
## Describe the bug

**Command Name**
`az cdn endpoint rule action add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'rules'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cdn/custom/custom.py", line 451, in add_action
    for i in range(0, len(policy.rules)):
AttributeError: 'NoneType' object has no attribute 'rules'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn endpoint rule action add --action-name {} --rule-name {} --cache-behavior {} --profile-name {} --name {} --resource-group {}`

Ex : az cdn endpoint rule action add --action-name "CacheExpiration" --rule-name "test" --cache-behavior "BypassCache" --profile-name {the profile name} --name {the endpoint name } --resource-group {the resource group}

## Expected Behavior

We should expect a rule creation

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.33.1 *
```

**Comment by navba-MSFT** [comment]
@Brudem Apologies for the late reply. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of AzCLI and let us know if you are still running into the same issue ? Awaiting your reply.

**Comment by Brudem** [comment]
@navba-MSFT My bad I should always update CLI version when I meet an unrocoverable exception (and more when I see that it is a preview version).

So as you expected exception disappears, many thanks.

I have another "issue" (perhaps you can help) when I try an AZ CLI to create a rule.

 **(BadRequest) Rules other than the base rule (order greater than 0) must have at least one condition.**
 
So I compared my command parameters with json configuration of a CDN endpoint after creating a rule via Azure portal.
 
 The JSON is showing this kind of rule entry :
 
       {
        "actions": [
          {
            "name": "CacheExpiration",
            "parameters": {
              "cacheBehavior": "Override",
              "cacheDuration": "01:00:00",
              "cacheType": "All"
            }
          }
        ],
        "conditions": [
          {
            "name": "UrlFileName",
            "parameters": {
              "matchValues": [
                "interactivesimulator.html"
              ],
              "negateCondition": false,
              "operator": "EndsWith",
              "transforms": [
                "Lowercase"
              ]
            }
          }
        ],
        "name": "SIM1HOUR",
        "order": 1
      },
 
 I tried to do the same with the following AZ CLI command
 
az cdn endpoint rule add --rule-name TEST --order 5 --action-name "CacheExpiration" --cache-behavior "Override" --cache-duration "1.01:01:01" --profile-name XXX --name XXX --resource-group XXX --match-values "toto.js" --negate-condition false --operator "EndsWith" --transform "Lowercase"
 
I can't figure what parameters is missing for the command be able to create the embeded condition ? 

If I try to create a rule without any "condition" parameters it complain too (saying that all rule need a condition except the "global" one).

Many thanks.

**Comment by Brudem** [comment]
@navba-MSFT sorry again, just after writing my preceding comment I found that the missing argument was the "--match-variable" which is not very clear since it become condition "name" in JSON config.

All seems OK now :)

**Comment by navba-MSFT** [comment]
@Brudem  Thanks for the update. I am glad that the issue is now resolved. Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
