### ISSUE TITLE
Cannot create GPU-enabled container instance

### ISSUE THREAD

**Issue by sidoverflow** [Azure/azure-cli#22730]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 116, in create_container
    return _create_update_from_file(cmd.cli_ctx, resource_group_name, name, location, file, no_wait)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 379, in _create_update_from_file
    name = name or cg_defintion.get('name', None)
AttributeError: 'NoneType' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az container create --resource-group {} --file {} --location {}`

## Expected Behavior

Container created

## Environment Summary
```
Linux-5.9.16-1-MANJARO-x86_64-with, Alpine Linux v3.15
Python 3.10.4
Installer: DOCKER

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by sidoverflow** [comment]
Closing the issue, I was able to create the instance.

Tried creating the instance by removing the `apiVersion` from the YAML and that seemed to work, weirdly.
