### ISSUE TITLE
Can't get reservation order list. 

### ISSUE THREAD

**Issue by grzeg1** [Azure/azure-cli#22740]
## Describe the bug

**Command Name**
`az reservations reservation-order list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/reservations/_exception_handler.py", line 14, in reservations_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/reservations/operations/_reservation_order_operations.py", line 338, in extract_data
    deserialized = self._deserialize("ReservationOrderList", pipeline_response)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1368, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1442, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1618, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1645, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
msrest.exceptions.DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az reservations reservation-order list`

## Environment Summary
```
Linux-5.15.0-27-generic-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
serial-console 0.1.1
interactive 0.4.5
vm-repair 0.4.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by grzeg1** [comment]
This one works OK though so it does not seem to be RBAC related:
`az reservations reservation-order show --reservation-order-id 24..02`

**Comment by grzeg1** [comment]
```
msal.telemetry: Generate or reuse correlation_id: ******************
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/Microsoft.Capacity/reservationOrders?api-version=2022-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '******************'
cli.azure.cli.core.sdk.policies:     'CommandName': 'reservations reservation-order list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.37.0 (DEB) azsdk-python-mgmt-reservations/2.0.0 Python/3.10.4 (Linux-5.15.0-27-generic-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /providers/Microsoft.Capacity/reservationOrders?api-version=2022-03-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding,Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'northeurope:******************'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '******************'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYNORTH:20220606T131116Z:******************'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 06 Jun 2022 13:11:15 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":""}
msrest.exceptions: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>

```

**Comment by navba-MSFT** [comment]
@grzeg1 Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide an update once we have more details on this.

**Comment by navba-MSFT** [comment]
@grzeg1 Could you please run the below command and let me know if that helps ?

>az rest --method GET --uri "https://management.azure.com/providers/Microsoft.Capacity/reservationOrders?api-version=2022-03-01"

Awaiting your reply.

**Comment by grzeg1** [comment]
```
az rest --method GET --uri "https://management.azure.com/providers/Microsoft.Capacity/reservationOrders?api-version=2022-03-01"
{
  "value": ""
}
```

**Comment by grzeg1** [comment]
although
```
az reservations reservation-order-id list --subscription-id xxxx
```
seems to work

**Comment by navba-MSFT** [comment]
@grzeg1 Thanks for getting back and clarifying this. Could you test with the below command:

>az rest --method GET --uri "https://management.azure.com/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Capacity/appliedReservations?api-version=2022-03-01"

Please replace XXXXX with your concerned subscription id and let me know if that works. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@grzeg1 I wanted to do quick follow-up to check if you had a chance to look at my above comment and try the action plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@grzeg1 Could you please me know if you have tried the above action plan ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@grzeg1 The action is currently pending on you to test the above suggested plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
