### ISSUE TITLE
az synapse pipeline KeyError 'properties'

### ISSUE THREAD

**Issue by keranem1** [Azure/azure-cli#22742]
## Describe the bug

**Command Name**
`az synapse pipeline update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 82, in create_or_update_pipeline
    properties = PipelineResource.from_dict(definition_file['properties'])
KeyError: 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse pipeline update --workspace-name {} --name {} --file {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
arcdata 1.4.1
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by keranem1** [comment]
Same error occurs when running on Windows 10 PowerShell 7 prompt.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@keranem1 can you please check this issue https://github.com/Azure/azure-cli/issues/22839
