### ISSUE TITLE
az network public-ip update fails 

### ISSUE THREAD

**Issue by naioja** [Azure/azure-cli#22765]
## Describe the bug

**Command Name**
`az network public-ip update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'int' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/network/v2021_08_01/operations/_operations.py", line 28637, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/network/v2021_08_01/operations/_operations.py", line 28556, in _create_or_update_initial
    _json = self._serialize.body(parameters, 'PublicIPAddress')
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 626, in body
    errors = _recursive_validate(data_type, data_type, data)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 160, in _recursive_validate
    return data.validate()
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 254, in validate
    validation_result += _recursive_validate(attr_name, attr_type, value)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 152, in _recursive_validate
    for content in data:
TypeError: 'int' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip update -g {} -n {} --set {}`

## Environment Summary
```
Linux-5.4.0-1080-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by naioja** [comment]
Zone object cannot be changed.
