### ISSUE TITLE
AZ cli error for az webapp auth 

### ISSUE THREAD

**Issue by vishwakant-singh** [Azure/azure-cli#22785]
C:\Users\VSI118>az webapp auth set -g rg-mepc-sit --name ztest-app --body @auth.json
The command requires the extension authV2. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): y
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\VSI118\.azure\cliextensions\authV2\azext_authV2\custom.py", line 113, in set_auth_settings_v2
    json_object = json.loads(body)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
To open an issue, please run: 'az feedback'

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vishwakant-singh Thanks for reaching out to us and sharing this feedback. Could you please run the below CLI command and check if that helps ?

```
authSettings=$(az webapp auth show -g myAuthResourceGroup -n <front-end-app-name>)
authSettings=$(echo "$authSettings" | jq '.properties' | jq '.identityProviders.azureActiveDirectory.login += {"loginParameters":["scope=openid profile email offline_access api://<back-end-client-id>/user_impersonation"]}')
az webapp auth set --resource-group myAuthResourceGroup --name <front-end-app-name> --body "$authSettings"
```

**_Note_**: You need to update your resource name details in the above command.

The commands effectively adds a loginParameters property with additional custom scopes. Here's an explanation of the requested scopes:

>- openid, profile, and email are requested by App Service by default already. For information, see [OpenID Connect Scopes](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/develop/v2-permissions-and-consent.md#openid-connect-scopes).
>
>- api://<back-end-client-id>/user_impersonation is an exposed API in your back-end app registration. It's the scope that gives you a JWT token that includes the back end app as a [token audience](https://wikipedia.org/wiki/JSON_Web_Token).
>
>- [offline_access](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/develop/v2-permissions-and-consent.md#offline_access) is included here for convenience (in case you want to [refresh tokens](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/tutorial-auth-aad.md#when-access-tokens-expire)).

More Info [here](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/tutorial-auth-aad.md). Hope this helps.

**Comment by navba-MSFT** [comment]
@vishwakant-singh Could you please let me know if you had a chance to follow the above action plan ? Awaiting your reply.
