### ISSUE TITLE
unable to run az commands from terraform script

### ISSUE THREAD

**Issue by manpreetsinghbhatia** [Azure/azure-cli#22786]
## Describe the bug

**Command Name**
`az network`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
EOF when reading a line
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1825, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2049, in _parse_known_args
  File "argparse.py", line 2026, in consume_positionals
  File "argparse.py", line 1935, in take_action
  File "argparse.py", line 1213, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1858, in parse_known_args
  File "argparse.py", line 2049, in _parse_known_args
  File "argparse.py", line 2026, in consume_positionals
  File "argparse.py", line 1919, in take_action
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 275, in _get_values
  File "argparse.py", line 2460, in _get_values
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 303, in _check_value
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/dynamic_install.py", line 119, in try_install_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/dynamic_install.py", line 204, in _check_value_in_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/prompting.py", line 71, in prompt_y_n
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/prompting.py", line 85, in _prompt_bool
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/prompting.py", line 22, in _input
EOFError: EOF when reading a line

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network {} {} {} --name {} --resource-group {} --query {} -o {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
network
