### ISSUE TITLE
az containerapp throws errors for module azure.cli.core.auth

### ISSUE THREAD

**Issue by gopal-amlekar** [Azure/azure-cli#22811]
## Describe the bug
Error while using az containerapp commands. _No module named 'azure.cli.core.auth'_

**Command Name**

This is not specific to a command, it is with all the az containerapp commands. For example `az containerapp list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.core.auth'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\gopal.amlekar\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 29, in <module>
    from ._github_oauth import get_github_access_token
  File "C:\Users\gopal.amlekar\.azure\cliextensions\containerapp\azext_containerapp\_github_oauth.py", line 13, in <module>
    from azure.cli.core.auth.persistence import SecretStore, build_persistence
ModuleNotFoundError: No module named 'azure.cli.core.auth'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add --name containerapp --upgrade`
- `The installed extension 'containerapp' is in preview.`
- `az provider register --namespace Microsoft.App`
- `az provider register --namespace Microsoft.OperationalInsights`
- `az containerapp list`

## Expected Behavior
It should run the containerapp commands as described in documentation. As in this example, it should show the container apps (or ask for additional arguments etc.)

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2 *

Extensions:
containerapp 0.3.4

```

**Comment by gopal-amlekar** [comment]
Fixed this. It was just that an upgrade of azure cli and then upgrade of the containerapp extension was required. I missed to do that before creating the issue.
For anyone coming here facing same error, run az upgrade to upgrade the core azure cli. Then run az containerapp commands. If any more uprade of the containerapp extension is required then the cli will indicate accordingly.

Closing the issue. Thanks!
