### ISSUE TITLE
Python v3.10.x - Table Output - ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#22821]
## Describe the bug

`-o table` output does not work as of Python v3.10.x.

**Errors:**
```
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```

## To Reproduce:
- Get an ARM template
- Run any command whatsoever with the `-o table` output  format(I've been testing with `az deployment group validate [...] -o table`
- Command runs fine, but returns a non-0 error, with the above-mentioned error message.

Afer running in `--debug` mode, I found that the issue pertains to using Python 3.10.x specifically. It returns the following error, which I've seen referenced here and there in the AzureCLI Github issues, namely: https://github.com/Azure/azure-cli/issues/20444, meaning this fix has already been done, yet keeps coming back. 

```
cli.knack.output: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/lib/python3.10/dist-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/lib/python3.10/dist-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/usr/local/lib/python3.10/dist-packages/knack/output.py", line 79, in format_table
    raise CLIError("Table output unavailable. "
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
```
## Expected Behavior
Should return a table output.

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: PIP

azure-cli 2.37.0

Extensions:
azure-devops 0.25.0
aks-preview 0.5.79

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
ARM

**Comment by alexpilon666** [comment]
Any news on this issue ?
We're in the process of migrating from Centos7 to Ubuntu 22.04LTS, and this issue is actively blocking our progress as we heavily rely on Azure CLI for our day-to-day work.

**Comment by zhoxing-ms** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/20348. Please see https://github.com/Azure/azure-cli/issues/20348#issuecomment-988427069 for the solution.

**Comment by alexpilon666** [comment]
@zhoxing-ms , @jiasli , in my case, even though yes I am running on Ubuntu (not Debian directly), AzureCLI was installed via Python, not via the package manager.

This is how we have installed it:
_Note: The lack of `sudo` works because this is running inside an Ubuntu 22.04LTS container. All commands are executed as root, and when running AzureCLI post-install we are also running as root._
```
apt update && apt upgrade -y && apt install -y python3-pip
python3 -m pip install azure-cli==2.37.0
```

**Comment by jiasli** [comment]
The `dist-packages` folder in your callstack indicates you are still calling the Azure CLI installed from `apt`. Please follow https://github.com/Azure/azure-cli/issues/19640#issuecomment-924578571 to uninstall the `apt`-installed Azure CLI and try again.

**Comment by jiasli** [comment]
The `tabulate` issue was reported long ago (#20348) and was fixed by #20195.

I can't reproduce this error with above steps:

```
# apt update && apt upgrade -y && apt install -y python3-pip
# python3 -m pip install azure-cli==2.37.0

# python3 -m pip list -v
...
azure-cli                               2.37.0      /usr/local/lib/python3.10/dist-packages pip
...
tabulate                                0.8.10      /usr/local/lib/python3.10/dist-packages pip
...

# az version -o table
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.37.0       2.37.0            1.0.6
```

Could you run `python3 -m pip list -v` and check the `tabulate` package version?

If you want to use pip, creating a virtual environment first is recommended. See https://github.com/Azure/azure-cli/issues/20476.

Please also note that we recommend **using the official Azure CLI DEB package to install**. Please see https://github.com/Azure/azure-cli/issues/19640.
