### ISSUE TITLE
Can't get user list through cli

### ISSUE THREAD

**Issue by shannonlowder** [Azure/azure-cli#22855]
## Describe the bug

I'm trying to get a list of AAD users/objects to match up against the list of IAMs for a given resource.  I can't get the python command or Azure CLI commands (az ad user list or az ad user show --id) to work. However, I can get the az rest command to query the graph end point and get results that way.  Have the other commands been removed from the API?

**Command Name**
`az ad user list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='graph.microsoft.com', port=443): Max retries exceeded with url: /v1.0/users (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1033f63d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1033f63d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graph.microsoft.com', port=443): Max retries exceeded with url: /v1.0/users (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1033f63d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/command_modules/role/commands.py", line 54, in graph_err_handler
    raise ex
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/command_modules/role/custom.py", line 1828, in list_users
    return client.user_list(filter=' and '.join(sub_filters) if sub_filters else None)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/command_modules/role/msgrpah/_graph_client.py", line 256, in user_list
    result = self._send("GET", "/users" + _filter_to_query(filter))
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/command_modules/role/msgrpah/_graph_client.py", line 40, in _send
    r = send_raw_request(self.cli_ctx, method, url, resource=self.resource, uri_parameters=param, body=body)
  File "/opt/homebrew/lib/python3.9/site-packages/azure/cli/core/util.py", line 974, in send_raw_request
    r = s.send(prepped, **settings)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='graph.microsoft.com', port=443): Max retries exceeded with url: /v1.0/users (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1033f63d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad user list`

## Environment Summary
```
macOS-12.4-arm64-arm-64bit
Python 3.9.12
Installer: PIP

azure-cli 2.37.0

Extensions:
databricks 0.8.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error message indicate your DNS server can't resolve Microsoft Graph API `graph.microsoft.com`:

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='graph.microsoft.com', port=443): Max retries exceeded with url: /v1.0/users (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1033f63d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Please check your network setting.
