### ISSUE TITLE
vwan module not working

### ISSUE THREAD

**Issue by jandrucu** [Azure/azure-cli#22907]
## Describe the bug

**Command Name**
`az network vwan`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\core\policies\__init__.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 582, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 260, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2006, in _parse_known_args
  File "argparse.py", line 1946, in consume_optional
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1044, in __call__
  File "argparse.py", line 2494, in print_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 195, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 247, in format_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 168, in show_help
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 306, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 240, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\qx2189\.azure\cliextensions\virtual-wan\azext_vwan\vendored_sdks\v2021_08_01\__init__.py", line 9, in <module>
    from ._network_management_client import NetworkManagementClient
  File "C:\Users\qx2189\.azure\cliextensions\virtual-wan\azext_vwan\vendored_sdks\v2021_08_01\_network_management_client.py", line 20, in <module>
    from ._configuration import NetworkManagementClientConfiguration
  File "C:\Users\qx2189\.azure\cliextensions\virtual-wan\azext_vwan\vendored_sdks\v2021_08_01\_configuration.py", line 15, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\core\policies\__init__.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vwan --help`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0 *

Extensions:
virtual-wan 0.2.12

```

**Comment by yonzhan** [comment]
network

**Comment by jandrucu** [comment]
Issue was solved by running "az upgrade" command
