### ISSUE TITLE
az snapshot delete --ids fails

### ISSUE THREAD

**Issue by calace1** [Azure/azure-cli#22917]
## Describe the bug

**Command Name**
`az snapshot delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
can't start new thread
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    results, exceptions = self._run_jobs_concurrently(jobs, ids)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 736, in _run_jobs_concurrently
    tasks.append(executor.submit(self._run_job, expanded_arg, cmd_copy))
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/usr/lib64/python3.6/threading.py", line 849, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot delete --ids {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}`

## Environment Summary
```
Linux-4.18.0-348.12.2.el8_5.x86_64-x86_64-with-redhat-8.5-Ootpa, Red Hat Enterprise Linux 8.5 (Ootpa)
Python 3.6.8
Installer: RPM

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
Compute
