### ISSUE TITLE
az acr build error, but build is successful

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-cli#22910]
## Describe the bug
az acr build queues a task to ACR but fails with this error below

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'charmap' codec can't encode character '\u0151' in position 1785: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 190, in write_and_convert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0151' in position 1785: character maps to <undefined>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr build -t <my-image> -r <myacr> --platform linux -f file-in-utf8 <context>`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
application-insights 0.1.16
interactive 0.4.5
resource-graph 2.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by cmenzi** [comment]
Workaround found: It works with `--no-logs --no-format`.

**Comment by RakeshMohanMSFT** [comment]
@cmenzi Thank you for reaching out, glad that you are unblocked now. It perhaps is specific the file you are using? can you share the file with us to check?

**Comment by cmenzi** [comment]
@RakeshMohanMSFT Sure...

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.420-focal
LABEL maintainer="Cédric Menzi <cedric.menzi@buhlergroup.com>" \
      description="Includes: \
      - .NET Core 6.0 (SDK) - LTS \
      - .NET Core 3.1 (SDK) - LTS \
      - Azure Functions Core Tools \
      - Az, Az.ManagedServiceIdentity \
      - Azure CLI \
      - Node.js (LTS) \
      - OpenJDK 11 \
      - PowerShell Core 7 \
      - K6 \
      - Docker Tooling"

ENV BUILD_DIR=/build \
    DEBIAN_FRONTEND=noninteractive

RUN wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 && \
    echo "deb https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list && \
    apt-get update -q 2>/dev/null && \
    apt-get install -yq apt-utils && \
    apt-get install -yq \
        default-jdk \
        xz-utils \
        ca-certificates \
        apt-transport-https \
        curl \
        unzip \
        gnupg \
        lsb-release \
        azure-functions-core-tools-4 \
        dotnet-sdk-6.0=6.0.301-1 \
        openssh-client \
        k6 \
    && \
    update-ca-certificates && \
    apt-get -y autoclean && rm -rf /var/lib/apt/lists/*

ENV NODE_VERSION=16.15.1 \
    LC_ALL=C.UTF-8

RUN wget -q https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz -O /tmp/nodejs.tar.xz && \
    cd /usr/local && \
    tar --strip-components=1 -xf /tmp/nodejs.tar.xz && \
    rm -rf ${BUILD_DIR}/* && \
    npm update npm --location=global && \
    npm update uuid --location=global && \
    npm install azurite --location=global

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN az config set extension.use_dynamic_install=yes_without_prompt && \
    az extension add -n alertsmanagement -y && \
    az extension add -n application-insights -y && \
    az extension add -n azure-devops -y && \
    az extension add -n azure-iot -y && \
    az extension add -n datafactory -y && \
    az extension add -n kusto -y && \
    az extension add -n log-analytics -y && \
    az extension add -n log-analytics-solution -y && \
    az extension add -n resource-graph -y && \
    az extension add -n ssh -y && \
    az extension add -n webapp -y && \
    az extension add -n containerapp -y

RUN pwsh -noni -ex bypass -nop -c "Set-Variable -Name ProgressPreference -Value 'SilentlyContinue'; Install-Module Az -Force | Out-Null; Install-Module Az.ManagedServiceIdentity -Force | Out-Null; Install-Module Pester -Force | Out-Null; Install-Module PSScriptAnalyzer -Force | Out-Null;"

WORKDIR $BUILD_DIR

CMD ["bash"]
```

**Comment by RakeshMohanMSFT** [comment]
@cmenzi I am unable to reproduce this issue at my end. Here is the screenshot of my successful completion. This is the command I used `az acr build -r issue22910 . --platform linux` Please let me know if I missed anything crucial, so it will help further.

![image](https://user-images.githubusercontent.com/49954584/174558991-6e8e7e1d-0d7d-43e4-ba62-66865d63766d.png)

**Comment by BSubashRaj** [comment]
> Workaround found: It works with `--no-logs --no-format`.

Worked for me as well Thanks. :)
