### ISSUE TITLE
Can't update WAF Policy on Azure Front Door

### ISSUE THREAD

**Issue by rkganji** [Azure/azure-cli#22989]
**Related command**
`az network front-door update --name <> --resource-group <> --set frontendEndpoints[0].webApplicationFirewallPolicyLink='{"id":"<>"}'`

**Describe the bug**
Command to associate WAF policy to Front door using above command results in below error

```
2022-06-23T17:19:42.4394214Z ERROR: The command failed with an unexpected error. Here is the traceback:
2022-06-23T17:19:42.4404267Z ERROR: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2022-06-23T17:19:42.4404971Z Traceback (most recent call last):
2022-06-23T17:19:42.4405396Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2022-06-23T17:19:42.4405961Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2022-06-23T17:19:42.4406542Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2022-06-23T17:19:42.4407279Z AttributeError: 'str' object has no attribute 'get'
2022-06-23T17:19:42.4408009Z 
2022-06-23T17:19:42.4408320Z During handling of the above exception, another exception occurred:
2022-06-23T17:19:42.4408513Z 
2022-06-23T17:19:42.4408757Z Traceback (most recent call last):
2022-06-23T17:19:42.4409163Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2022-06-23T17:19:42.4409669Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
2022-06-23T17:19:42.4410165Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
2022-06-23T17:19:42.4410691Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
2022-06-23T17:19:42.4411211Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
2022-06-23T17:19:42.4411753Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
2022-06-23T17:19:42.4412260Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
2022-06-23T17:19:42.4412766Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
2022-06-23T17:19:42.4413276Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2022-06-23T17:19:42.4413788Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2022-06-23T17:19:42.4414285Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2022-06-23T17:19:42.4414833Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2022-06-23T17:19:42.4415408Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2022-06-23T17:19:42.4415992Z msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
2022-06-23T17:19:42.4416275Z 
2022-06-23T17:19:42.4416577Z During handling of the above exception, another exception occurred:
2022-06-23T17:19:42.4416783Z 
2022-06-23T17:19:42.4417011Z Traceback (most recent call last):
2022-06-23T17:19:42.4417400Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2022-06-23T17:19:42.4417904Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2022-06-23T17:19:42.4418450Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2022-06-23T17:19:42.4418990Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2022-06-23T17:19:42.4419517Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2022-06-23T17:19:42.4420031Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 242, in handler
2022-06-23T17:19:42.4420573Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in cached_put
2022-06-23T17:19:42.4421102Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 441, in _put_operation
2022-06-23T17:19:42.4421849Z   File "C:\agent_install1\_work\_temp\.azclitask\cliextensions\front-door\azext_front_door\vendored_sdks\operations\_front_doors_operations.py", line 348, in begin_create_or_update
2022-06-23T17:19:42.4422386Z     raw_result = self._create_or_update_initial(
2022-06-23T17:19:42.4422881Z   File "C:\agent_install1\_work\_temp\.azclitask\cliextensions\front-door\azext_front_door\vendored_sdks\operations\_front_doors_operations.py", line 287, in _create_or_update_initial
2022-06-23T17:19:42.4423398Z     body_content = self._serialize.body(front_door_parameters, 'FrontDoor')
2022-06-23T17:19:42.4423840Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
2022-06-23T17:19:42.4424329Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2022-06-23T17:19:42.4424842Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 620, in body
2022-06-23T17:19:42.4425343Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
2022-06-23T17:19:42.4425859Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1407, in _deserialize
2022-06-23T17:19:42.4426382Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1618, in deserialize_data
2022-06-23T17:19:42.4426900Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in deserialize_iter
2022-06-23T17:19:42.4427416Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1649, in <listcomp>
2022-06-23T17:19:42.4427908Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1631, in deserialize_data
2022-06-23T17:19:42.4428426Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1398, in _deserialize
2022-06-23T17:19:42.4428933Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1446, in _deserialize
2022-06-23T17:19:42.4429444Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
2022-06-23T17:19:42.4429956Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1428, in _deserialize
2022-06-23T17:19:42.4430493Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1193, in rest_key_case_insensitive_extractor
2022-06-23T17:19:42.4431097Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1222, in attribute_key_case_insensitive_extractor
2022-06-23T17:19:42.4431927Z msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**To Reproduce**
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
`az network front-door update --name <> --resource-group <> --set frontendEndpoints[0].webApplicationFirewallPolicyLink='{"id":"<>"}'`

**Expected behavior**
Front door should be associated with the WAF policy

**Environment summary**
Running from Azure DevOps CLI task.
Windows SelfHosted Agent.
azure-cli                         2.27.0 *
core                              2.27.0 *
telemetry                          1.0.6
Extensions:
front-door                        1.0.16

**Additional context**

**Comment by yonzhan** [comment]
network
