### ISSUE TITLE
Error on running az keyvault set-policy command.

### ISSUE THREAD

**Issue by eltersouza** [Azure/azure-cli#22985]
## Describe the bug

**Command Name**
`az keyvault set-policy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Invalid filter clause
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/msgrpah/_graph_client.py", line 40, in _send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 982, in send_raw_request
azure.cli.core.azclierror.HTTPError: Bad Request({"error":{"code":"BadRequest","message":"Invalid filter clause","innerError":{"date":"2022-06-23T12:36:19","request-id":"f782e8c7-48d4-431c-9e62-512ef28c5279","client-request-id":"f782e8c7-48d4-431c-9e62-512ef28c5279"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 915, in set_policy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 894, in _object_id_args_helper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 357, in _get_object_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 326, in _get_object_id_by_upn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/msgrpah/_graph_client.py", line 256, in user_list
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/msgrpah/_graph_client.py", line 42, in _send
azure.cli.command_modules.role.msgrpah._graph_client.GraphError: Invalid filter clause

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault set-policy --name {} --upn {} --secret-permissions {} {} {} {} {}`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
wondering if you used the right user principal name... I can't reproduce this issue:
![image](https://user-images.githubusercontent.com/10227683/175448584-a929f077-ee8c-4d0d-a949-4ad83f5b9f2c.png)

**Comment by adomin1000** [comment]
I'm having a similar error when attempting to set-policy on a keyvault.   Errors out regardless of what type of permissions

<img width="951" alt="image" src="https://user-images.githubusercontent.com/40310420/177428017-b558eaee-020d-4e13-a506-9ac9ad08740c.png">

**Comment by evelyn-ys** [comment]
Hi @adomin1000, this is because the `--upn` contains special character, for example, `#`. We have fixed this issue in latest version. Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to install CLI 2.38.0
