### ISSUE TITLE
Issue when trying to download blobs from storage container [az-cli 2.37.0]

### ISSUE THREAD

**Issue by cleconte987** [Azure/azure-cli#23048]
## Describe the bug

**Command Name**
`az storage blob download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    first(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    first(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 639, in download_blob
    download_stream.readinto(stream)
  File "/opt/az/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_download.py", line 592, in readinto
    self._progress_hook(len(self._current_content), self.size)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/_validators.py", line 1021, in _update_progress
    hook.add(message=message, value=current, total_val=total)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 73, in add
    self.reporter.add(**kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 49, in add
    assert 0 <= value <= total_val
AssertionError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download --account-name {} --account-key {} --container-name {} --name {} -f {}`

## Environment Summary
```
Linux-5.15.0-40-generic-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
storage

**Comment by RakeshMohanMSFT** [comment]
@cleconte987 Can you please upgrade to the latest version of cli and try again? the latest version is [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). We are unable to reproduce it. If you still face the issue after upgrading, please share the --debug trace log with us for further troubleshooting.

**Comment by kento1218** [comment]
@RakeshMohanMSFT 
I faced the same issue on 2.40.0. Here are the stack trace with `--debug`
Some information are masked.

I don't read these source codes precisely but these kind of comparison between float values are often troublesome. (Don't you think?)

```
133/494: "file_a"[####################]  100.0000%urllib3.connectionpool: https://account_x.blob.core.windows.net:443 "GET /container/file_a HTTP/1.1" 206 1781
134/494: "file_b"[######################]  100.0000%urllib3.connectionpool: https://account_x.blob.core.windows.net:443 "GET /container/file_b HTTP/1.1" 206 505
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 458, in storage_blob_download_batch
    include, result = _download_blob(client=blob_client, file_path=destination_path,
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/util.py", line 309, in wrapper
    return True, func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 414, in _download_blob
    blob = download_blob(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 683, in download_blob
    download_stream.readinto(stream)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_download.py", line 592, in readinto
    self._progress_hook(len(self._current_content), self.size)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_validators.py", line 1148, in _update_progress
    hook.add(message=message, value=current, total_val=total)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 73, in add
    self.reporter.add(**kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 49, in add
    assert 0 <= value <= total_val
AssertionError

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 458, in storage_blob_download_batch
    include, result = _download_blob(client=blob_client, file_path=destination_path,
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/util.py", line 309, in wrapper
    return True, func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 414, in _download_blob
    blob = download_blob(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 683, in download_blob
    download_stream.readinto(stream)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_download.py", line 592, in readinto
    self._progress_hook(len(self._current_content), self.size)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_validators.py", line 1148, in _update_progress
    hook.add(message=message, value=current, total_val=total)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 73, in add
    self.reporter.add(**kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 49, in add
    assert 0 <= value <= total_val
AssertionError
az_command_data_logger: 
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 411, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 458, in storage_blob_download_batch
    include, result = _download_blob(client=blob_client, file_path=destination_path,
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/util.py", line 309, in wrapper
    return True, func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 414, in _download_blob
    blob = download_blob(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 683, in download_blob
    download_stream.readinto(stream)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_download.py", line 592, in readinto
    self._progress_hook(len(self._current_content), self.size)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_validators.py", line 1148, in _update_progress
    hook.add(message=message, value=current, total_val=total)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 73, in add
    self.reporter.add(**kwargs)
  File "/usr/local/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/progress.py", line 49, in add
    assert 0 <= value <= total_val
AssertionError
To open an issue, please run: 'az feedback'
```

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit, Darwin 19.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0
```

**Comment by kento1218** [comment]
It works fine with `--no-progress` option.
