### ISSUE TITLE
Erro na hora de criar pipeline via arquivo.json

### ISSUE THREAD

**Issue by MatheusBelo** [Azure/azure-cli#23071]
## Describe the bug

**Command Name**
`az synapse pipeline create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 82, in create_or_update_pipeline
KeyError: 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse pipeline create --workspace-name {} --name {} --file {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@MatheusBelo Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@MatheusBelo I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please provide us the answer to the above questions. This will help us to assist you better. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@MatheusBelo The action is currently pending on you to get back to us on the above queries. Please feel free to reopen this thread once you get a chance to look into this. We would be happy to help again.
