### ISSUE TITLE
API version 2021-08-01 does not have operation group 'network_interfaces'

### ISSUE THREAD

**Issue by nyetwurk** [Azure/azure-cli#23094]
## Describe the bug

**Command Name**
`az vm list-ip-addresses`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2021-08-01 does not have operation group 'network_interfaces'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/vm/custom.py", line 1281, in list_vm_ip_addresses
    nics = network_client.network_interfaces.list_all()
  File "/usr/lib/python3/dist-packages/azure/mgmt/network/_network_management_client.py", line 4475, in network_interfaces
    raise ValueError("API version {} does not have operation group 'network_interfaces'".format(api_version))
ValueError: API version 2021-08-01 does not have operation group 'network_interfaces'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list-ip-addresses`

## Environment Summary
```
Linux-5.18.0-2-cloud-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.10.5
Installer: DEB

azure-cli 2.37.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by nyetwurk** [comment]
`2.36.0-1~buster` works.

**Comment by nyetwurk** [comment]
`2.37.0-1~buster` works as well

**Comment by nyetwurk** [comment]
```
*** 2.37.0-2 500
        500 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```
is broken

**Comment by yonzhan** [comment]
Compute

**Comment by nyetwurk** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014203

**Comment by zhoxing-ms** [comment]
> /usr/lib/python3/dist-packages/azure/mgmt/network/_network_management_client.py

It should be related to issue https://github.com/Azure/azure-cli/issues/19640 @jiasli Could you please help have a look?

**Comment by jiasli** [comment]
@zhoxing-ms, you are right. `2.37.0-2` is release by @bluca, not Microsoft.

**Comment by ericjs** [comment]
I get the same error with azure-cli v 2.39.0 on openSUSE tumbleweed, running an "az ssh config ..." command.

**Comment by nyetwurk** [comment]
Even worse, unattended upgrades continues to upgrade over it

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.

**Comment by nyetwurk** [comment]
I would prefer the package is renamed entirely so it does not overlap. This one installs several dozen dependencies and is entirely different from the MS azure-cli package.

**Comment by nyetwurk** [comment]
> Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.

```
ERROR: API version 2021-08-01 does not have operation group 'network_interfaces'
```

**Comment by RakeshMohanMSFT** [comment]
@nyetwurk Please share az --version details with us please. For some reason we are unable to reproduce this issue at our end.

**Comment by nyetwurk** [comment]
https://github.com/Azure/azure-cli/issues/19640#issuecomment-1227878091

**Comment by vthiebaut10** [comment]
The SSH extension no longer uses the network client that was causing this issue. @yonzhan can the SSH and VM SSH tags be removed?
