### ISSUE TITLE
az functionapp update

### ISSUE THREAD

**Issue by gravitysuckstoday** [Azure/azure-cli#23091]
## Describe the bug

**Command Name**
`az functionapp update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 61, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 200, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 644, in update_functionapp
AttributeError: 'NoneType' object has no attribute 'resource_group'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp update --name {} --resource-group {} --plan {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2 *

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@gravitysuckstoday Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please follow the below action plan:

**Plan 1:**
Please update the AzCLI version to the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and test again.

**Plan 2:**
If the above plan doesn't help, you can try to run the same above command by providing the complete resource id using `--ids `parameter. It should be a complete resource ID containing all information of 'Resource Id' arguments. 

More Info [here](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-update).

Hope this helps.

**Comment by StrawnSC** [comment]
@navba-MSFT @gravitysuckstoday I'm unable to repro this. It seems like it would probably be fixed by upgrading to the latest CLI version (see `az upgrade`)

**Comment by navba-MSFT** [comment]
@gravitysuckstoday The action is currently pending on you to test the above command after updating the CLI. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
