### ISSUE TITLE
Cannot login to ACR

### ISSUE THREAD

**Issue by anhvu-accuracy** [Azure/azure-cli#23117]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DeploymentExtendedFilter' from 'azure.mgmt.resource.resources.v2021_04_01.models._models_py3' (/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/models/_models_py3.py)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/custom.py", line 284, in acr_login
    login_server, username, password = get_login_credentials(
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 413, in get_login_credentials
    return _get_credentials(cmd,
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 312, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 106, in get_registry_by_name
    resource_group_name = get_resource_group_name_by_registry_name(
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 85, in get_resource_group_name_by_registry_name
    arm_resource = _arm_get_resource_by_name(
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/acr/_utils.py", line 40, in _arm_get_resource_by_name
    result = get_resources_in_subscription(cli_ctx, resource_type)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/parameters.py", line 138, in get_resources_in_subscription
    return list(rcf.resources.list(filter=filter_str))
  File "/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 487, in resources
    from .v2021_04_01.operations import ResourcesOperations as OperationClass
  File "/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/__init__.py", line 9, in <module>
    from ._resource_management_client import ResourceManagementClient
  File "/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/_resource_management_client.py", line 17, in <module>
    from . import models
  File "/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/models/__init__.py", line 20, in <module>
    from ._models_py3 import DeploymentExtendedFilter
ImportError: cannot import name 'DeploymentExtendedFilter' from 'azure.mgmt.resource.resources.v2021_04_01.models._models_py3' (/usr/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2021_04_01/models/_models_py3.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Linux-5.17.11-300.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Thirty Six)
Python 3.10.5
Installer: PIP

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment]
route to CXP team
