### ISSUE TITLE
bastion rdp vmss support

### ISSUE THREAD

**Issue by lovigano** [Azure/azure-cli#23143]
## Unable to use az network bastion rdp to connect to vmss instance

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8457, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by lovigano** [comment]
Also getting issues with  az network bastion tunnel and az network bastion ssh.

Both resulting in the same error:

Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8535, in _start_tunnel
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 184, in start_server
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 117, in _listen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
msrestazure.azure_exceptions.CloudError: java.lang.IllegalArgumentException: Invalid vmss instance format /subscriptions/SUB/resourceGroups/lovigano-bastion1/providers/Microsoft.Compute/virtualMachineScaleSets/gmcl-nr3j

Should be noted that the bastion DOES work through the browser. just not powershell nor wsl2

**Comment by aavalang** [comment]
@lovigano i see a typo in "virtualMachines"

**Comment by navba-MSFT** [comment]
@lovigano Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please confirm if you are running this from a cloudshell ? If Yes, it wont be able to open the RDP on your local machine. For this reason, we recommend using powershell with az cli (on **_Windows_** machine). 

Also, note that RDP command works best on Windows, for other OS’ (**like Linux**) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.

>Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:

>-  Use native clients on non-Windows local computers (example: **a Linux PC**).
>-  Use the native client of your choice. (This includes the Windows native client.)
>-  Connect using SSH or RDP.
>-  Set up concurrent VM sessions with Bastion.
>- [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.

>Currently, this feature has the following limitation:
Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.

Hope this helps.

**Comment by liorbp** [comment]
@navba-MSFT i'm getting the same error running from az cli on Windows.

here's the details bug report:

### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8457, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`

## Expected Behavior

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

**Comment by navba-MSFT** [comment]
@lovigano I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@lovigano The action is currently pending on you to test on powershell with az cli (on Windows machine). We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by jiasli** [comment]
I have linked all related issues to this one as a main tracker.

`az network bastion rdp` is now from `bastion` extension. It unconditionally imports `ctypes.WinDLL` regardless of the operating system:

https://github.com/Azure/azure-cli-extensions/blob/b293d7e9d91b6a97d958a424d136befb7a7f6d28/src/bastion/azext_bastion/_process_helper.py#L9

```py
from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
```

According to https://docs.python.org/3/library/ctypes.html#ctypes.WinDLL, `ctypes.WinDLL` is Windows only.

**This command should give a better error message stating `az network bastion rdp` is only supported on Windows.** It can detect the operating system with `sys.platform`. For example:

https://github.com/Azure/azure-cli/blob/fb805f4bb3167623107c10ec5f34581a838c8a1c/src/azure-cli-core/azure/cli/core/auth/persistence.py#L41-L50

**Comment by saqib-s** [comment]
resolved this by installing the full AZ CLI  and NOT using the azure cloud shell connector in Windows 11 Terminal (which seems to be AZ ClI lite). 

Once downloaded and installed the full AZ CLI client on my windows 11 machine, I restarted Windows Terminal (PowerShell windows), and logged into AZ using the following and rdp opened up via the bastion. 


```
az login

az account set --subscription "<sub-id>"

az network bastion rdp ....... 
```

**Comment by carlosonunez** [comment]
Unsure why this was closed. I still get this error when attempting to use `az network bastion rdp` on macOS. I agree with @jiasli that an "unsupported OS" type error would be appropriate here.

**Comment by FlorentATo** [comment]
@navba-MSFT RDP isn't specific to Microsoft Windows and the official documentation doesn't make mention of this command being Windows specific. Please consider re-opening this issue and patch `az network bastion rdp` to make it compatible with MacOS. cc @jiasli @yonzhan
