### ISSUE TITLE
az storage container policy delete crashed, but worked perfectly fine the 2nd time with same arguments

### ISSUE THREAD

**Issue by zaminda** [Azure/azure-cli#23145]
## Describe the bug

**Command Name**
`az storage container policy delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'dbbackupaccess'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    first(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 408, in new_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/acl.py", line 54, in delete_acl_policy
    del acl[policy_name]
KeyError: 'dbbackupaccess'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container policy delete --container-name {} --name {} --account-name {} --account-key {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.81
application-insights 0.1.14
azure-devops 0.25.0
k8s-configuration 1.5.1
k8s-extension 1.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
storage
