### ISSUE TITLE
az aks check-acr ERROR localy and via Cloud Shell

### ISSUE THREAD

**Issue by dmitrymorozovnoveo** [Azure/azure-cli#23151]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2290, in aks_check_acr
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --resource-group {} --name {} --acr {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by FumingZhang** [comment]
Hi @dmitrymorozovnoveo, could you please help confirm when executing the above command there is an output similar to the following,
`Merged "<cluster-name>" as current context in C:\Users\<some-temp-path>`

In this command, `az aks get-credentials` will be called first to get the kubeconfig of the cluster. Judging from your error message, getting the kubeconfig failed. Make sure you have permission to write temporary files. You can also view the detailed process by adding the `--debug` option when executing the command
