### ISSUE TITLE
az ad sp create-for-rbac --name "GitHub-Actions" --role contributor --scopes /subscriptions/{iuh886c0aa-f9b1-0000-8od7-bf98681r8713} --sdk-auth

### ISSUE THREAD

**Issue by duvergonzalez** [Azure/azure-cli#23160]
## Describe the bug

**Command Name**
az ad sp create-for-rbac --name "GitHub-Actions" --role contributor --scopes /subscriptions/{iuh886c0aa-f9b1-0000-8od7-bf98681r8713} --sdk-auth

**Errors:**
```
Option '--sdk-auth' has been deprecated and will be removed in a future release.
Creating 'contributor' role assignment under scope '/subscriptions/{e906c0aa-f6b1-4341-8bd4-bf98681c8713}'
  Role assignment creation failed.

The command failed with an unexpected error. Here is the traceback:
'e906c0aa-f6b1-4341-8bd4-bf98681c8713'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/commands.py", line 54, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 1255, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 198, in _create_role_assignment
    role_id = _resolve_role_id(role, scope, definitions_client)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 591, in _resolve_role_id
    role_defs = list(definitions_client.list(scope, "roleName eq '{}'".format(role)))
  File "/opt/az/lib/python3.10/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/az/lib/python3.10/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 285, in internal_paging
    request = prepare_request(next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 281, in prepare_request
    request = self._client.get(url, query_parameters, header_parameters)
  File "/opt/az/lib/python3.10/site-packages/msrest/service_client.py", line 168, in get
    request = self._request('GET', url, params, headers, content, form_content)
  File "/opt/az/lib/python3.10/site-packages/msrest/service_client.py", line 108, in _request
    request = ClientRequest(method, self.format_url(url))
  File "/opt/az/lib/python3.10/site-packages/msrest/service_client.py", line 151, in format_url
    url = url.format(**kwargs)
KeyError: 'e906c0aa-f6b1-4341-8bd4-bf98681c8713'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1085-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
You don't need curly bracket around your subscription ID: `/subscriptions/{e906c0aa-f6b1-4341-8bd4-bf98681c8713}` since `{xxx}` is considered Python keys and it corrupts CLI's execution.

Please just use `/subscriptions/e906c0aa-f6b1-4341-8bd4-bf98681c8713`.
