### ISSUE TITLE
az resource update does not work with latest api-version (2022-08-01)

### ISSUE THREAD

**Issue by dhoorens** [Azure/azure-cli#23174]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```
az resource update -g $RESOURCE_GROUP -n $vm_name --resource-type "Microsoft.Compute/virtualMachines" --set tags.'last_build_status'="${status}"
```
**Describe the bug**

When running the above command without specifying the `--api-version` argument, we get an error
```
(InvalidParameter) The value of parameter api-version is invalid.
Code: InvalidParameter
Message: The value of parameter api-version is invalid.
Target: api-version
Inner error: {
    "internalErrorCode": "ParameterValueInvalid"
}
```
**To Reproduce**

Run 
```
az resource update -g $RESOURCE_GROUP -n $vm_name --resource-type "Microsoft.Compute/virtualMachines" --set tags.'last_build_status'="${status}"
```
(with the RESOURCE_GROUP, vm_name and status populated with adequate values)

If we run 
```
az resource update -g $RESOURCE_GROUP -n $vm_name --resource-type "Microsoft.Compute/virtualMachines" --set tags.'last_build_status'="${status}" --api-version "2022-08-01"
```
we obtain the same outcome

If we run 
```
az resource update -g $RESOURCE_GROUP -n $vm_name --resource-type "Microsoft.Compute/virtualMachines" --set tags.'last_build_status'="${status}" --api-version "2022-03-01"
```
i.e. with the previous api-version value (i.e. 2022-03-01à, it works as expected

**Expected behavior**

It should work without specifying the api-version, as per the documentation

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@dhoorens It seems that there is a problem with the support of Compute service for api-version `2022-08-01`. Could you send the debug log to us for investigation? My email address is Zhou.Xing@microsoft.com, thanks!

**Comment by dhoorens** [comment]
I've removed some personal info from the log. Apart from that that's the log obtained with the --api-version set to 2022-08-01 (which BTW is funny, since we're still mid of July here...)
```
[@singletier00 ~]$ az resource update -g $RESOURCE_GROUP -n $vm_name --resource-type "Microsoft.Compute/virtualMachines" --set tags.'last_build_status'="${status}" --api-version "2022-08-01" --debug
cli.knack.cli: Command arguments: ['resource', 'update', '-g', '', '-n', '', '--resource-type', 'Microsoft.Compute/virtualMachines', '--set', 'tags.last_build_status=', '--api-version', '2022-08-01', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [, , ]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'resource': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.009        40       187
cli.azure.cli.core: Total (1)                 0.009        40       187
cli.azure.cli.core: Loaded 40 groups, 187 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : resource update
cli.azure.cli.core: Command table: resource update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate []
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home//.azure/commands/2022-07-12.13-26-54.resource_update.17805.log'.
az_command_data_logger: command args: resource update -g {} -n {} --resource-type {} --set {} --api-version {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [.add_subscription_parameter at 0x7f50cbccce18>, .register_query_examples at 0x7f50cbc2f6a8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [.add_ids_arguments at 0x7f50cbc2f730>, .add_cache_arguments at 0x7f50cbc2f840>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [, , .handle_example_parameter at 0x7f50cbc2f620>, .parse_ids_arguments at 0x7f50cbc2f7b8>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/home//.azure/service_principal_entries.json', encrypt=False
cli.azure.cli.core.auth.persistence: build_persistence: location='/home//.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.identity: _load_msal_http_cache: /home//.azure/msal_http_cache.bin
cli.azure.cli.core.auth.identity: __load_msal_http_cache: /home//.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com//discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com//v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com//kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Region to be used: None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions//resourcegroups//providers/Microsoft.Compute//virtualMachines/?api-version=2022-08-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': ''
cli.azure.cli.core.sdk.policies:     'CommandName': 'resource update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --resource-type --set --api-version --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.32.0 (RPM) azsdk-python-azure-mgmt-resource/20.0.0 Python/3.6.8 (Linux-4.18.0-348.12.2.el8_5.x86_64-x86_64-with-redhat-8.5-Ootpa)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions//resourcegroups//providers/Microsoft.Compute//virtualMachines/?api-version=2022-08-01 HTTP/1.1" 400 232
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '232'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': ''
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': ''
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20220712T132654Z:'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 12 Jul 2022 13:26:53 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "innererror": {
      "internalErrorCode": "ParameterValueInvalid"
    },
    "code": "InvalidParameter",
    "message": "The value of parameter api-version is invalid.",
    "target": "api-version"
  }
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 191, in handler
    instance = cached_get(self.cmd, getter, **getterargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in cached_get
    return _get_operation()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 404, in _get_operation
    result = operation(**kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 1734, in show_resource
    include_response_body) for id_dict in parsed_ids])
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 1734, in 
    include_response_body) for id_dict in parsed_ids])
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 3382, in get_resource
    cls=cls)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resources_operations.py", line 1081, in get
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidParameter) The value of parameter api-version is invalid.
Code: InvalidParameter
Message: The value of parameter api-version is invalid.
Target: api-version
Inner error: {
    "internalErrorCode": "ParameterValueInvalid"
}

cli.azure.cli.core.azclierror: (InvalidParameter) The value of parameter api-version is invalid.
Code: InvalidParameter
Message: The value of parameter api-version is invalid.
Target: api-version
Inner error: {
    "internalErrorCode": "ParameterValueInvalid"
}
az_command_data_logger: (InvalidParameter) The value of parameter api-version is invalid.
Code: InvalidParameter
Message: The value of parameter api-version is invalid.
Target: api-version
Inner error: {
    "internalErrorCode": "ParameterValueInvalid"
}
cli.knack.cli: Event: Cli.PostExecute []
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.405 seconds (init: 0.116, invoke: 0.290)
telemetry.save: Save telemetry record of length 3313 in cache
telemetry.check: Negative: The /home//.azure/telemetry.txt was modified at 2022-07-12 13:24:12.632262, which in less than 600.000000 s
cli.azure.cli.core.auth.identity: _dump_msal_http_cache: /home//.azure/msal_http_cache.bin
```

**Comment by stccde** [comment]
Same here running Powershell cmd:

Get-AzResource -ResourceGroupName $AZvirtualMachineRG -ResourceType Microsoft.Compute/virtualMachines -Name $AZComputerName

results in error:

<#
Get-AzResource : The value of parameter api-version is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : c7c0b1c8-a3bb-49d6-8edb-429253efab0d
At line:1 char:1
+ Get-AzResource -ResourceGroupName $AZvirtualMachineRG -ResourceType M ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResource], ResourceManagerCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
#>

Debug shows HTTP Request as:
Absolute Uri:
https://management.azure.com//subscriptions/000/resourceGroups/rg-000/providers/Microsoft.Compute/virtualMachines/vm-000?api-version=2022-08-01

explicitly calling with api 2022-08-01 results in same error:
Get-AzResource -ResourceGroupName $AZvirtualMachineRG -ResourceType Microsoft.Compute/virtualMachines -Name $AZComputerName -ApiVersion "2022-08-01"


Getting supported Versions:
((get-azresourceprovider -providernamespace Microsoft.Compute).resourcetypes | ?{$_.ResourceTypeName -eq "virtualmachines"}).apiversions


I tried the second, "2022-03-01", command runs just fine.
Get-AzResource -ResourceGroupName $AZvirtualMachineRG -ResourceType Microsoft.Compute/virtualMachines -Name $AZComputerName -ApiVersion "2022-03-01"


BTW: Occurred in EastUS but not in WestEU.

**Comment by zhoxing-ms** [comment]
> /subscriptions//resourcegroups//providers/Microsoft.Compute//virtualMachines/?api-version=2022-08-01 HTTP/1.1

The correct format should be
> /subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Compute/virtualMachines/{vm_name}?api-version=2022-03-01


@stccde Why is the format of the requested URL incorrect? (such as: `//resourcegroups//`, `//virtualMachines/`) 
Could you confirm whether there is extra `/` character in the value of the parameters?

**Comment by blindvalentine** [comment]
same error with az resource show

**Comment by tang81** [comment]
Error is present in `az resource <whatever> --resource-type virtualMachines`.

`az resource <whatever> --resource-type [disks|]networkInterfaces|networkSecurityGroups]` seems working fine.

**Comment by zhoxing-ms** [comment]
Because CLI has no special processing logic, this should be the problem related to Compute RP or ARM service, so the service team needs to investigate it

**Comment by dhoorens** [comment]
> @dhoorens Why is the format of the requested URL incorrect? (such as: `//resourcegroups//`, `//virtualMachines/`)? You deleted some resource names to hide sensitive information, right? If so, could you replace them with placeholders and send me a complete URL?

@zhoxing-ms because I explicitly removed the info about the resourcegroup and vm (and other sensitive stuff) from the log.

**Comment by navba-MSFT** [comment]
@dhoorens Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@dhoorens The issue was tracked as a live site incident and was fixed last week. Could you please test again and let me know if you are facing the same issue ? Awaiting your reply.

**Comment by dhoorens** [comment]
@navba-MSFT , I've just tested the 3 following commands
```
az resource update <parameters>
```
```
az resource update <parameters> --api-version "2022-08-01"
```
and (to ensure there is no regression)
```
az resource update <parameters> --api-version "2022-03-01"
```
with this az version
```
$ az --version
azure-cli                         2.32.0 *

core                              2.32.0 *
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
```
and both are working. Thanks for fixing it.

PS: Could you please tell me where/how I can be notified of any future api-version change?

Thanks

**Comment by navba-MSFT** [comment]
@dhoorens Thanks for your reply. I am glad that the issue is now resolved. You will not be notified for the newer api-version releases. To check the newly released api-versions you can run the below command: 

>((get-azresourceprovider -providernamespace Microsoft.Compute).resourcetypes | ?{$_.ResourceTypeName -eq "virtualmachines"}).apiversions

 We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
