### ISSUE TITLE
Invalid return character or leading space in header: Authorization

### ISSUE THREAD

**Issue by dhangerkapil** [Azure/azure-cli#23173]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Invalid return character or leading space in header: Authorization
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 24, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 978, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 456, in prepare_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 317, in prepare
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 451, in prepare_headers
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/utils.py", line 978, in check_header_validity
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --headers {} {} --url {} --query {} -o {}`

## Environment Summary
```
Windows-10-10.0.22622-SP0
Python 3.10.5
Installer: 

azure-cli 2.38.0

Extensions:
application-insights 0.1.15
azure-devops 0.23.0
interactive 0.4.5
ml 2.3.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by dhangerkapil** [comment]
command is az rest --method put --headers "Authorization=Bearer ${token}" "Content-Type=application/json;charset=utf-8" --url "${synapseLibraryUri}"


This is how I am getting token

token=$(az account get-access-token --resource ${synapseResource} --query accessToken --output tsv)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
As you are calling MSI-installed Azure CLI from Bash script, I suspect you are hitting https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313

You may also run `az rest` with `--debug` to double confirm if `\r` is included in the argument value.
