### ISSUE TITLE
az storage file upload fails with content-md5 parameter

### ISSUE THREAD

**Issue by jjmms** [Azure/azure-cli#23179]
**Related command**
```
$md5Hash = Get-FileHash ... -Algorithm MD5 | Select -ExpandProperty hash
Write-Host "MD5 hash: $md5Hash"
az storage file upload ... --content-md5 $md5Hash
```

**Describe the bug**
The command fails due to a type error:
```
MD5 hash: 17FB28B2ED928A031CA20FCD3B8D9E73
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: string argument without an encoding
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/file.py", line 155, in storage_file_upload
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/fileshare/v2021_06_08/_file_client.py", line 533, in upload_file
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/fileshare/v2021_06_08/_file_client.py", line 73, in _upload_file_helper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/fileshare/v2021_06_08/_file_client.py", line 399, in create_file
TypeError: string argument without an encoding
```

**To Reproduce**
1. Generate a MD5 hash of a file using:
```
$md5Hash = Get-FileHash ... -Algorithm MD5 | Select -ExpandProperty hash
Write-Host "MD5 hash: $md5Hash"
```
2. Upload the file: `az storage file upload ... --content-md5 $md5Hash`

**Expected behavior**
Upload should succeed with the hash being added.

**Environment summary**
Using Azure pipeline with windows-latest:
```
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"

azure-cli                         2.38.0
Please let us know how we are doing: https://aka.ms/azureclihats

and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
core                              2.38.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]
```

**Additional context**
This worked fine on azure-cli + core 2.37.0. It has only now become a problem on 2.38.0.

**Comment by yonzhan** [comment]
storage

**Comment by bebound** [comment]
In track2 SDK, `content_md5` should be `bytearray`.
Similar issue: https://github.com/Azure/azure-cli/issues/21494

**Comment by jjmms** [comment]
Will there be a preview extension to use with the fix, much like the similar issue? The Azure CLI pipeline task forces the latest version where this is broke, therefore unable to pin a previous version, so a preview extension might be best to tide over until the next release.

**Comment by bebound** [comment]
You can install `storage-preview` extension to make this command working.

-----

However, the md5 property in the blob is inconsistent.

In main repo, `content-md5` is treated as base64 string and converted to bytearray by `bytearray(base64.b64decode(data))`.
In `storage-preview`, it is treated as normal string and convert to bytearray by ` bytearray(data.encode('utf-8'))`.
In `az storage file show` and portal page, the bytearray is encode to base64 string again.

Therefore, the md5 value might be confusing if you use this extension.
