### ISSUE TITLE
az managedApp show --name with a valid MRG name fails

### ISSUE THREAD

**Issue by aherbst-broad** [Azure/azure-cli#23208]
## Describe the bug
Attempting to `show` an azure managed app with a valid name results in the stack trace below.

**Command Name**
`az managedapp show --name <redacted>`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 1456, in show_application
    return racf.applications.get(resource_group_name, application_name)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/azure/mgmt/resource/managedapplications/operations/_applications_operations.py", line 79, in get
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\w\._\(\)]+$'),
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.35.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
- `az managedapp show -n {}`

## Expected Behavior
There should be no uncaught exception.

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.35.0 *

Extensions:
storage-blob-preview 0.6.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@aherbst-broad Thank you for reaching out, we are looking into it.
