### ISSUE TITLE
az storage file upload-batch --dryrun - FAILED

### ISSUE THREAD

**Issue by pp185214** [Azure/azure-cli#23216]
## Describe the bug

**Command Name**
`az storage file upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/file.py", line 181, in storage_file_upload_batch
    'dir_name': os.path.dirname(dst),
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage file upload-batch --dryrun --destination {} --source {} --pattern {}`

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.38.0

Extensions:
azure-iot 0.14.1
account 0.2.1
scheduled-query 0.2.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
storage

**Comment by RakeshMohanMSFT** [comment]
@pp185214 We are unable to reproduce the issue using this command 

`az storage file upload-batch --destination <baseurl>/issue23216file --source . --account-key <accountkey> --pattern "*"`

Can you share the pattern you used, the file type and the some sample names of those files? for us to reproduce the issue. 

If possible the debug trace of the same.

**Comment by mic-hnk** [comment]
> @pp185214 We are unable to reproduce the issue using this command
> 
> `az storage file upload-batch --destination <baseurl>/issue23216file --source . --account-key <accountkey> --pattern "*"`
> 
> Can you share the pattern you used, the file type and the some sample names of those files? for us to reproduce the issue.
> 
> If possible the debug trace of the same.

I faced same issue and in my case `--dryrun` seems to be a problem.
Author mentioned this parameter but I can't see it in your example.

**Comment by benbz** [comment]
I've just encountered this. It is only an issue with `--dry-run`. The problem seems to be https://github.com/Azure/azure-cli/blob/374336ca6945d70b8caff756eb3e157a16238965/src/azure-cli/azure/cli/command_modules/storage/operations/file.py#L174-L183 as in `--dry-run` `dst` is unconditionally `None`. A quick change of line 179 to be `dst = destination` fixes this error but the `az storage file batch-upload --dry-run` command fails later on, so there's more wrong here

**Comment by benbz** [comment]
FTR this is still an issue for me in 2.40.0. Unsure what further information is required beyond the `--dry-run` flag is required to reproduce this, e.g. `az storage file upload-batch --account-name <account name> --destination <a share name> --source <a local folder> --destination-path <a remote folder> --dryrun`

**Comment by calvinhzy** [comment]
Will take a look this release cycle.
