### ISSUE TITLE
error while running az aks get-credentials

### ISSUE THREAD

**Issue by omkarchavan-shell** [Azure/azure-cli#23217]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: 'AZ-AS-SPN-EX-N-SEQ01763.pem'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 22, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 14, in get_container_service_client
    return get_mgmt_service_client(cli_ctx, ResourceType.MGMT_CONTAINERSERVICE)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 74, in get_mgmt_service_client
    **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 214, in _get_mgmt_service_client
    aux_tenants=aux_tenants)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 334, in get_login_credentials
    credential = self._create_credential(account, client_id=client_id)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 596, in _create_credential
    return identity.get_service_principal_credential(username_or_sp_id)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 207, in get_service_principal_credential
    sp_auth = ServicePrincipalAuth(entry)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 223, in __init__
    with open(self.certificate, 'r') as file_reader:
FileNotFoundError: [Errno 2] No such file or directory: 'AZ-AS-SPN-EX-N-SEQ01763.pem'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: RPM

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@omkarchavan-shell The error is self-explanatory. This seems to be due to the missing certificate 'AZ-AS-SPN-EX-N-SEQ01763.pem'. Could you ensure that the certificate is present ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@omkarchavan-shell I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any follow-up questions on this. Awaiting your reply.

**Comment by omkarchavan-shell** [comment]
Hey, using the AZ-AS-SPN-EX-N-SEQ01763.pem it solved the issue.
Thanks @navba-MSFT
