### ISSUE TITLE
unable to add extension

### ISSUE THREAD

**Issue by mbreslav** [Azure/azure-cli#23221]
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
An error occurred. Pip failed with status code 2. Use --debug for more information.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add --name {}`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.38.0
```

**Comment by mbreslav** [comment]
:/$ az extension add --name webapp --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'webapp', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f8fc333bbe0>, <function OutputProducer.on_global_arguments at 0x7f8fc206c4c0>, <function CLIQuery.on_global_arguments at 0x7f8fc209d6c0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.002         1         7
cli.azure.cli.core: Total (1)                 0.002         1         7
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f8fbf5cf400>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/mikhail/.azure/commands/2022-07-16.00-39-13.extension_add.78080.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f8fbeb90e50>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f8fbec392d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f8fbec393f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f8fc206c550>, <function CLIQuery.handle_query_parameter at 0x7f8fc209d750>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f8fbec39360>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 1950622
cli.azure.cli.core.extension._resolve: Candidates ['webapp-0.2.24-py2.py3-none-any.whl', 'webapp-0.3.1-py2.py3-none-any.whl', 'webapp-0.4.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['webapp-0.2.24-py2.py3-none-any.whl', 'webapp-0.3.1-py2.py3-none-any.whl', 'webapp-0.4.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['webapp-0.2.24-py2.py3-none-any.whl', 'webapp-0.3.1-py2.py3-none-any.whl', 'webapp-0.4.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['webapp-0.4.0-py2.py3-none-any.whl', 'webapp-0.3.1-py2.py3-none-any.whl', 'webapp-0.2.24-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Choosing the latest of the remaining candidates.
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://azcliprod.blob.core.windows.net/cli-extensions/webapp-0.4.0-py2.py3-none-any.whl', 'filename': 'webapp-0.4.0-py2.py3-none-any.whl', 'metadata': {'azext.isPreview': True, 'azext.minCliCoreVersion': '2.23.0', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'sisirap@microsoft.com', 'name': 'Sisira Panchagnula', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/master/src/webapp'}}}, 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'webapp', 'summary': 'Additional commands for Azure AppService.', 'version': '0.4.0'}, 'sha256Digest': '908b0df07cef652176a0f2bf0fdcf58b5d16fb4903ee3c06f73f0bb3913a5c0f'}
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: Downloading https://azcliprod.blob.core.windows.net/cli-extensions/webapp-0.4.0-py2.py3-none-any.whl to /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl
urllib3.connectionpool: Starting new HTTPS connection (1): azcliprod.blob.core.windows.net:443
urllib3.connectionpool: https://azcliprod.blob.core.windows.net:443 "GET /cli-extensions/webapp-0.4.0-py2.py3-none-any.whl HTTP/1.1" 200 7606
cli.azure.cli.core.extension.operations: Downloaded to /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl
cli.azure.cli.core.extension.operations: Validating the extension /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl
cli.azure.cli.core.extension.operations: Checksum of /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl is OK
cli.azure.cli.core.extension.operations: Validation successful on /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: Found in list file: bionic
cli.azure.cli.core.extension.operations: Linux distro check: Reported by API: bionic
cli.azure.cli.core.extension.operations: Executing pip with args: ['install', '--target', '/opt/az/extensions/webapp', '/tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension.operations: Running: ['/usr/bin/../../opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/opt/az/extensions/webapp', '/tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
cli.azure.cli.core.extension.operations: Using pip 22.1.2 from /opt/az/lib/python3.10/site-packages/pip (python 3.10)
Non-user install due to --prefix or --target option
Created temporary directory: /tmp/pip-target-pu4ab4cf
Created temporary directory: /tmp/pip-ephem-wheel-cache-7qb66bju
Created temporary directory: /tmp/pip-build-tracker-rwrgmvyf
Initialized build tracking at /tmp/pip-build-tracker-rwrgmvyf
Created build tracker: /tmp/pip-build-tracker-rwrgmvyf
Entered build tracker: /tmp/pip-build-tracker-rwrgmvyf
Created temporary directory: /tmp/pip-install-rju6itr4
Processing /tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl
  Added webapp==0.4.0 from file:///tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl to build tracker '/tmp/pip-build-tracker-rwrgmvyf'
  Removed webapp==0.4.0 from file:///tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl from build tracker '/tmp/pip-build-tracker-rwrgmvyf'
Created temporary directory: /tmp/pip-unpack-au5ed5do
Installing collected packages: webapp

Successfully installed webapp-0.4.0
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/az/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/opt/az/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 466, in run
    self._handle_target_dir(
  File "/opt/az/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 476, in _handle_target_dir
    ensure_dir(target_dir)
  File "/opt/az/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 105, in ensure_dir
    os.makedirs(path)
  File "/usr/bin/../../opt/az/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/bin/../../opt/az/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
**PermissionError: [Errno 13] Permission denied: '/opt/az/extensions'**
Removed build tracker: '/tmp/pip-build-tracker-rwrgmvyf'

cli.azure.cli.core.extension.operations: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/opt/az/extensions/webapp', '/tmp/tmp1u3g0ggn/webapp-0.4.0-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 2.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /opt/az/extensions/webapp
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 341, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 2. Use --debug for more information.

**Comment by mbreslav** [comment]
I don't know why there would be a permission error since azure cli is creating the /opt/az directory in the first place. I've tried running with sudo which avoids those errors but it doesn't result in a proper install either.

**Comment by yonzhan** [comment]
Add @kairu-ms for awareness

**Comment by mbreslav** [comment]
I used the following work around to install the extension. 

1. sudo mkdir /opt/az/extension
2. sudo mkdir /opt/az/extension/<extension_name>
3. sudo chmod a+w /opt/az/extension/<extension_name>
4. az extension add --name <extension_name>

I guess the root cause may be that /opt/az is created with the wrong permissions in the first place by the cli?

**Comment by kairu-ms** [comment]
Thanks for the feedback. It seems a package installation problem. Involve @jiasli to check.

**Comment by jiasli** [comment]
Azure CLI is installed at `/opt/az`. This is by design.

By default, extensions are installed in `~/.azure/cliextensions`. However, your debug log shows extensions are installed in `/opt/az/extensions`. 

Could you run `az config get` to see if you have `extension.dir` configured?

https://github.com/Azure/azure-cli/blob/ed6e829554624894d5c94ad71bb85e788d726a43/src/azure-cli-core/azure/cli/core/extension/__init__.py#L19

**Comment by mbreslav** [comment]
When I run `az config get` I only see the key `"cloud"`. There is nothing for extension or extension directory.

Also when I run `az extension list` it shows azure-cli-devai-extension and webapp, both with path in `/opt/az/extensions/`. If I do `ls ~/.azure/cliextensions/` it only shows webapp.

**Comment by niander** [comment]
I know someone else who is also finding their Azure CLI installation using `/opt/az/extensions/` as Extensions directory. They may be using the same image you are using @mbreslav.

@jiasli Did older versions of Azure CLI used to using `/opt/` for extensions directory?

I would recommend you all to also check if `$AZURE_EXTENSION_DIR` is set to anything.
