### ISSUE TITLE
Unable to install kubectl using az aks install-cli

### ISSUE THREAD

**Issue by khaleelyousuff81** [Azure/azure-cli#23224]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/var/folders/1n/7b8bwws50nv3xn8z97zlb17h0000gq/T/tmptw3a0pyk/bin/darwin_arm64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2490, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version,
  File "/opt/homebrew/Cellar/azure-cli/2.38.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2619, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
macOS-12.4-arm64-arm-64bit, Darwin 21.5.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@khaleelyousuff81 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@khaleelyousuff81 This is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions) if you do not have full access to the /usr/local/bin path.

You can try with the` sudo az aks install-cli `and check if that helps. Alternatively, You can follow the below to install in a different location (download to a specified path) in the home folder, for example:

>**:~$ az aks install-cli --install-location mykubetools/kubectl1.22.2 --client-version 1.22.2 **--kubelogin-install-location** mykubetools/kubelogin

**Output**
>Downloading client to "mykubetools/kubectl1.22.2" from https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/linux/amd64/kubectl
Please ensure that mykubetools is in your search PATH, so the kubectl1.22.2 command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from https://github.com/Azure/kubelogin/releases/download/v0.0.XX/kubelogin.zip

Please ensure that mykubetools is in your search **PATH**, so the kubelogin command can be found.

>**Azure:~$ ./mykubetools/kubectl1.22.2 version
Client Version: version.Info{Major:"1", Minor:"XX", GitVersion:"v1.22.2", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Hope this helps.

**Comment by navba-MSFT** [comment]
@khaleelyousuff81 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any follow-up question on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@khaleelyousuff81 The action is currently pending on you to follow the above steps. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
