### ISSUE TITLE
AZURE CLI Login Error

### ISSUE THREAD

**Issue by dela-sam** [Azure/azure-cli#23244]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1658149474.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/93fd2ade-6406-4a25-bf7a-f688462cc683/v2.0",
  "iat": 1658152796,
  "nbf": 1658152796,
  "exp": 1658156696,
  "aio": "ATQAy/8TAAAAWcKVrRRrJpF7tK5m98pOk/tPG84XMcPZzgGyn7HPNX29BbHibdrH72XN5jfNHRt3",
  "name": "DELA TEKPO",
  "oid": "8134da54-a9de-48c0-9839-1bdfc59b58ac",
  "preferred_username": "dela.tekpo@blacksilver.me",
  "puid": "10032000F6CA4EDA",
  "rh": "0.AXkA3ir9kwZkJUq_evaIRizGg5V3sATbjRpGu-4C-eG_e0Z5ALc.",
  "sub": "O-sh3mQzFezoWnVo4g_PsLFEuxx7fYODSLpIBngg5AE",
  "tid": "93fd2ade-6406-4a25-bf7a-f688462cc683",
  "uti": "rLPLvsqt00GNJfUx_5gEAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 152, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 152, in login_with_device_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1670, in acquire_token_by_device_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 384, in obtain_token_by_device_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 346, in _obtain_token_by_device_flow
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 116, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 789, in _obtain_token
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 599, in <lambda>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 310, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 113, in add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 153, in __add
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 77, in decode_id_token
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1658149474.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/93fd2ade-6406-4a25-bf7a-f688462cc683/v2.0",
  "iat": 1658152796,
  "nbf": 1658152796,
  "exp": 1658156696,
  "aio": "ATQAy/8TAAAAWcKVrRRrJpF7tK5m98pOk/tPG84XMcPZzgGyn7HPNX29BbHibdrH72XN5jfNHRt3",
  "name": "DELA TEKPO",
  "oid": "8134da54-a9de-48c0-9839-1bdfc59b58ac",
  "preferred_username": "dela.tekpo@blacksilver.me",
  "puid": "10032000F6CA4EDA",
  "rh": "0.AXkA3ir9kwZkJUq_evaIRizGg5V3sATbjRpGu-4C-eG_e0Z5ALc.",
  "sub": "O-sh3mQzFezoWnVo4g_PsLFEuxx7fYODSLpIBngg5AE",
  "tid": "93fd2ade-6406-4a25-bf7a-f688462cc683",
  "uti": "rLPLvsqt00GNJfUx_5gEAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/20388
