### ISSUE TITLE
azure-cli on Mariner 1.0 misses python3-xml runtime dependencies to properly perform 'az login' command for instance.

### ISSUE THREAD

**Issue by Kowsika-Ponnusamy** [Azure/azure-cli#23266]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az login

**Describe the bug**
The azure-cli on Mariner 1.0 misses python3-xml runtime dependencies to properly perform 'az login' command for instance.

**To Reproduce**
Dockerfile

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0 AS runtime
RUN tdnf check-update
RUN tdnf install azure-cli -y
RUN az login
```

**Expected behavior**
```

[+] Building 2.0s (7/7) FINISHED
 => [internal] load build definition from Dockerfile.aspnet.wxpIngestion                                0.0s
 => => transferring dockerfile: 193B                                                                    0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0                     0.1s
 => [1/4] FROM mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0@sha256:50e66d1ce10310bb07cb0e49f083c  0.0s
 => CACHED [2/4] RUN tdnf check-update                                                                  0.0s
 => CACHED [3/4] RUN tdnf install azure-cli -y                                                          0.0s
 => ERROR [4/4] RUN az login                                                                            1.7s
------
 > [4/4] RUN az login:
#6 1.141 ERROR: Error loading command module 'acs': No module named 'xml'
#6 1.176 ERROR: Error loading command module 'appservice': No module named 'xml'
#6 1.200 ERROR: Error loading command module 'aro': No module named 'xml'
#6 1.211 ERROR: Error loading command module 'batch': No module named 'xml'
#6 1.313 ERROR: Error loading command module 'iot': No module named 'xml'
#6 1.364 ERROR: Error loading command module 'monitor': No module named 'xml'
#6 1.371 ERROR: Error loading command module 'netappfiles': No module named 'xml'
#6 1.378 ERROR: Error loading command module 'network': No module named 'xml'
#6 1.402 ERROR: Error loading command module 'rdbms': No module named 'xml'
#6 1.468 ERROR: Error loading command module 'serviceconnector': No module named 'xml'
#6 1.500 ERROR: Error loading command module 'sqlvm': No module named 'xml'
#6 1.583 ERROR: Error loading command module 'vm': No module named 'xml'
#6 1.601 WARNING: Auto upgrade failed. name 'exit_code' is not defined
#6 1.623 Traceback (most recent call last):
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msal/mex.py", line 33, in <module>
#6 1.623     from xml.etree import cElementTree as ET
#6 1.623 ModuleNotFoundError: No module named 'xml'
#6 1.623
#6 1.623 During handling of the above exception, another exception occurred:
#6 1.623
#6 1.623 Traceback (most recent call last):
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
#6 1.623     cmd_result = self.invocation.execute(args)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
#6 1.623     raise ex
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
#6 1.623     results.append(self._run_job(expanded_arg, cmd_copy))
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
#6 1.623     result = cmd_copy(params)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
#6 1.623     return self.handler(*args, **kwargs)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
#6 1.623     return op(**command_args)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/command_modules/profile/custom.py", line 148, in login
#6 1.623     use_cert_sn_issuer=use_cert_sn_issuer)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 143, in login
#6 1.623     identity = _create_identity_instance(self.cli_ctx, self._authority, tenant_id=tenant)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 841, in _create_identity_instance
#6 1.623     from .auth.identity import Identity
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/auth/identity.py", line 13, in <module>
#6 1.623     from msal import PublicClientApplication
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msal/__init__.py", line 28, in <module>
#6 1.623     from .application import (
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msal/application.py", line 17, in <module>
#6 1.623     from .mex import send_request as mex_send_request
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msal/mex.py", line 35, in <module>
#6 1.623     from xml.etree import ElementTree as ET
#6 1.623 ModuleNotFoundError: No module named 'xml'
#6 1.623
#6 1.623 During handling of the above exception, another exception occurred:
#6 1.623
#6 1.623 Traceback (most recent call last):
#6 1.623   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#6 1.623     "__main__", mod_spec)
#6 1.623   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
#6 1.623     exec(code, run_globals)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/__main__.py", line 48, in <module>
#6 1.623     exit_code = cli_main(az_cli, sys.argv[1:])
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/__main__.py", line 35, in cli_main
#6 1.623     return cli.invoke(args)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/knack/cli.py", line 243, in invoke
#6 1.623     exit_code = self.exception_handler(ex)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 135, in exception_handler
#6 1.623     return handle_exception(ex)
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/azure/cli/core/util.py", line 58, in handle_exception
#6 1.623     from msrestazure.azure_exceptions import CloudError
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msrestazure/__init__.py", line 28, in <module>
#6 1.623     from .azure_configuration import AzureConfiguration
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msrestazure/azure_configuration.py", line 34, in <module>
#6 1.623     from msrest import Configuration
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msrest/__init__.py", line 28, in <module>
#6 1.623     from .configuration import Configuration
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msrest/configuration.py", line 37, in <module>
#6 1.623     from .pipeline import Pipeline
#6 1.623   File "/usr/lib64/az/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 41, in <module>
#6 1.623     import xml.etree.ElementTree as ET
#6 1.623 ModuleNotFoundError: No module named 'xml'
------
executor failed running [/bin/sh -c az login]: exit code: 1
```

**Dockerfile with a workaround**
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0 AS runtime
RUN tdnf check-update
RUN tdnf install python3-xml -y
RUN tdnf install azure-cli -y
RUN az login
```

**Expected behavior**
```
[+] Building 68.9s (7/8)
 => [internal] load build definition from Dockerfile.aspnet.wxpIngestion                                0.0s
 => => transferring dockerfile: 226B                                                                    0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0                     0.1s
 => [1/5] FROM mcr.microsoft.com/dotnet/aspnet:6.0-cbl-mariner1.0@sha256:50e66d1ce10310bb07cb0e49f083c  0.0s
 => CACHED [2/5] RUN tdnf check-update                                                                  0.0s
 => [3/5] RUN tdnf install python3-xml -y                                                               7.3s
 => [4/5] RUN tdnf install azure-cli -y                                                                40.9s
 => [5/5] RUN az login                                                                                 20.4s
 => => # WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter
 => => #  the code FAMN3WSFA to authenticate.
```

Thanks to @Eric Desrochers for the workaround solution.

**Comment by yonzhan** [comment]
Mariner

**Comment by eric-desrochers** [comment]
We reduced our size footprint in Mariner 2.0 by reducing the numbers of packages in the base container image.
I would recommend you add a Requires: python3-xml in your SPEC file instead of relying on Mariner to provide pre-installed packages.

**Comment by jiasli** [comment]
> Package manager (dnf, tdnf,) is smart enough to detect if the dependencies is already installed or not.

This is not true. Other Linux distributions doesn't have doesn't have `python3-xml`.

Red Hat:

```
> docker run -it --rm registry.access.redhat.com/ubi8/ubi:8.4 bash
[root@ed929244d4a0 /]# dnf install python3-xml
...
Error: Unable to find a match: python3-xml
```

Debian:

```
> docker run -it --rm debian:11
root@4d2cc3521fe6:/# apt update
root@4d2cc3521fe6:/# apt install python3-xml
...
E: Unable to locate package python3-xml
```

I think Mariner 1.0 should be consistent with Mariner 2.0 as well as other Linux distributions.

**Comment by eric-desrochers** [comment]
Other distros, may or may not have give the binary package a different name. Every distribution can name their package differently. Does this situation also impact other distributions outside Mariner ?

All I am just saying is that azure-cli should have a runtime dependency for Mariner 1.0 & 2.0 to ensure everything your program needs to operate (python modudle, ...) is met at installation time, regardless if the package is installed or not in Mariner base image.

dnf, tdnf is smart enough to detect if the "Requires:" are already installed or not on the system.

Adding `python3-xm`l for Mariner at https://github.com/Azure/azure-cli/blob/dev/scripts/release/rpm/mariner.dockerfile#L8 will do the trick and act as a level of protection to ensure this runtime dependency is always met, and this will only be effective for Mariner RPM.

```
- RUN tdnf install -y binutils file rpm-build gcc libffi-devel python3-devel openssl-devel make diffutils patch dos2unix perl sed
+ RUN tdnf install -y binutils file rpm-build gcc libffi-devel python3-devel openssl-devel make diffutils patch dos2unix perl sed python3-xml
```

**Comment by jiasli** [comment]
Actually, Mariner 1.0 is almost deprecated. Please kindly update to Mariner 2.0 and install corresponding Azure CLI package.
