### ISSUE TITLE
az storage container list (macos to azure) errors

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#23285]
## Describe the bug

**Command Name**
`az storage container list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to determine account name for shared key credential.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 380, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 379, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 233, in cf_blob_service
    return t_blob_service(account_url=account_url, credential=credential, **client_kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2020_10_02/_blob_service_client.py", line 135, in __init__
    super(BlobServiceClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2020_10_02/_shared/base_client.py", line 89, in __init__
    self.credential = _format_shared_key_credential(self.account_name, credential)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2020_10_02/_shared/base_client.py", line 351, in _format_shared_key_credential
    raise ValueError("Unable to determine account name for shared key credential.")
ValueError: Unable to determine account name for shared key credential.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container list`

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1 *

Extensions:
ssh 1.1.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can you share which auth do you use? Have you specified the correct `--account-name` and `--account-key`?
