### ISSUE TITLE
cli.azure.cli.core.azclierror: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by satheshs** [Azure/azure-cli#23282]
I am getting below error when I login with azure-cli.Currently not using any proxies. 

cli.azure.cli.core.azclierror: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
az_command_data_logger: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10e8eee60>]

**az --version**
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/Cellar/azure-cli/2.38.0/libexec/bin/python'
Extensions directory '/Users/sathesh/.azure/cliextensions'

Python (Darwin) 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by satheshs** [comment]
@jiasli @yonzhan Can you help me on this

**Comment by jiasli** [comment]
As indicated by the error message, please follow the instruction at https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy

**Comment by satheshs** [comment]
```
sathesh@Sathesh-S-2 ~ % python3 -c "import requests;print(requests.get('https://login.microsoftonline.com/').status_code)"
200
```

I am getting 200 reponse

**Comment by satheshs** [comment]
Any help ?

**Comment by jiasli** [comment]
It seems you can reach `https://login.microsoftonline.com/` without any problem. Could you run `az login --debug`?

**Comment by p9139010** [comment]
Hi, have similar problem but not connecting into Azure but couldn't update the extension or upgrade. Can anyone suggest.

Unable to get extension index.
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /azure-cli-extension-index-v1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by rdek** [comment]
Hi, @jiasli 
``` 
> python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
200
```
and from `az login --debug` I can freely write that `az login` uses `urllib3` instead of requests, given this snippet:
```
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '<REDACTED>'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.39.0 (PIP) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.10.6 (macOS-12.5-x86_64-i386-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
```

What should be the next steps in rectifying this problem?

**Comment by jiasli** [comment]
@p9139010. It seems your proxy intercepting traffic to https://aka.ms. Please refer to the document https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.

**Comment by p9139010** [comment]
thanks @jiasli  but we have this working for a long time and there is no proxy to block connectivity.

**Comment by jiasli** [comment]
@rdek, `requests` internally uses `urllib3` to send HTTP requests.

It's very likely your proxy allows https://login.microsoftonline.com/ but intercepts https://management.azure.com/. Please make  sure your proxy's certificate is trusted.

**Comment by jiasli** [comment]
@p9139010, the proxy may not be on your computer but company network. 

Can you access https://aka.ms/ directly with python?

```
> python -c "import requests;print(requests.get('https://aka.ms/').status_code)"
200
```

**Comment by rdek** [comment]
@jiasli - I've checked, don't have ANY proxy between me and web.

**Comment by satheshs** [comment]
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.@-S-2 ~ % python3 -c "import requests;print(requests.get('https://aka.ms/').status_code)"
200
`

Sometimes in my system working without any issues. but few times it doesn't. I am not using any vpn or proxies.

**Comment by exerror8** [comment]
[[Solved] certificate verify failed: unable to get local issuer certificate](https://exerror.com/certificate-verify-failed-unable-to-get-local-issuer-certificate/)

**Comment by DanStaticWard** [comment]
I'm also having this problem. I'm using a company provided MacBook M1, but we don't use proxies at any level and nobody else is having this problem. I got 200 codes for the two requests above, but `az login` always gives me the [SSL: CERTIFICATE_VERIFY_FAILED].

I've tried updating my certs file, reinstalling Python3 (both Mac local and Homebrew installed versions), running Python's `install certificates.command`, and installing certifi on my main Python3 installation.

**Comment by DanStaticWard** [comment]
I was able to fix this eventually by running `export REQUESTS_CA_BUNDLE=/opt/homebrew/etc/ca-certificates/cert.pem`. I'd love to say I understand what was going wrong, but I don't.

**Comment by simonhard** [comment]
> I was able to fix this eventually by running `export REQUESTS_CA_BUNDLE=/opt/homebrew/etc/ca-certificates/cert.pem`. I'd love to say I understand what was going wrong, but I don't.

Thanks a million! Works on macOS. 
I tried to use the one that's mentioned in azure help. Also to append portal.azure.com ssl cert to it. It never worked. @DanWardData 's solution works.

**Comment by joaocc** [comment]
In v2.55.0 (macOS), setting the REQUESTS_CA_BUNDLE doesn't solve the issue:
```
REQUESTS_CA_BUNDLE=/usr/local/share/certs/Cloudflare_CA.pem az login
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
```

Unfortunately for macOS, the path depends on 2 elements (azure-cli version and pythonversion), which means that configs will have to be redone if client is upgraded.

**Comment by s-nakagaki** [comment]
I have set the following:
```
$Env:AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
$Env:ADAL_PYTHON_SSL_NO_VERIFY=1
```
And `az login` was succeeded.
But `az network application-gateway stop` said the following:
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```

It looks `az network` command ignores flags.

**Comment by bandwiches** [comment]
> I have set the following:
> 
> ```
> $Env:AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
> $Env:ADAL_PYTHON_SSL_NO_VERIFY=1
> ```
> 
> And `az login` was succeeded. But `az network application-gateway stop` said the following:
> 
> ```
> [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
> ```
> 
> It looks `az network` command ignores flags.

This is true for `az keyvault secret show` but interestingly enough it is not true for `az keyvault show`.

**Comment by henrypost** [comment]
We have this issue too. Running `pip install pip-system-certs` and using the windows ca store seems to do nothing. Can someone from the `azure-cli` team confirm what the correct env var is, or other step we can do to so we can trust a self-signed cert?

**Comment by henrypost** [comment]
https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-troubleshooting?view=azure-cli-latest#work-behind-a-proxy

This doc suggests setting `REQUESTS_CA_BUNDLE` is the right choice.
