### ISSUE TITLE
Trying to add 

### ISSUE THREAD

**Issue by 13uilding** [Azure/azure-cli#23308]
When I was following this doc: https://docs.microsoft.com/en-us/azure/key-vault/keys/quick-create-python?tabs=azure-cli#grant-access-to-your-key-vault

I ran into issues when I would run the command:
`az keyvault set-policy --name <<your-unique-keyvault-name> --upn user@domain.com --secret-permissions delete get list set`

I think my upn might be the issue. I have also read that having a certain version of Azure Account (v0.11.0) extension can cause an issue.

## Describe the bug

**Command Name**
`az keyvault set-policy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Invalid filter clause
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/msgrpah/_graph_client.py", line 40, in _send
    r = send_raw_request(self.cli_ctx, method, url, resource=self.resource, uri_parameters=param, body=body)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 982, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Bad Request({"error":{"code":"BadRequest","message":"Invalid filter clause","innerError":{"date":"2022-07-23T20:15:14","request-id":"e0e1c89d-be2d-43c5-8df9-da0b2d279d33","client-request-id":"e0e1c89d-be2d-43c5-8df9-da0b2d279d33"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 915, in set_policy
    object_id = _object_id_args_helper(cmd.cli_ctx, object_id, spn, upn)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 894, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 357, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 326, in _get_object_id_by_upn
    accounts = list(graph_client.user_list(filter="userPrincipalName eq '{}'".format(upn)))
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/msgrpah/_graph_client.py", line 256, in user_list
    result = self._send("GET", "/users" + _filter_to_query(filter))
  File "/opt/homebrew/Cellar/azure-cli/2.37.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/msgrpah/_graph_client.py", line 42, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role.msgrpah._graph_client.GraphError: Invalid filter clause

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault set-policy --name {} --upn {} --secret-permissions {} {} {} {}`

## Environment Summary
```
macOS-12.4-arm64-arm-64bit, Darwin 21.5.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.37.0 *

Extensions:
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
I think it's the wrong `upn` which causes this issue. You can check your upn name in Portal:
![image](https://user-images.githubusercontent.com/10227683/180936326-be07003a-8bf1-489b-be4a-1e24dc68eda7.png)

Or you can provide your object id directly with `az keyvault set-policy --name {} --object-id {} --secret-permissions {}`
