### ISSUE TITLE
Az login through "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"

### ISSUE THREAD

**Issue by abu3lia** [Azure/azure-cli#23362]
When we are trying to do the AZ login we get the error:
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

No proxy is being used.

Recent change: We upgrade Azure CLI to the latest version.

`# az --version
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/bin/python3.6'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Aug 13 2020, 07:46:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy`

With --debug :

`cli.knack.cli: Command arguments: ['login', '--service-principal', '-u', '....', '-p', 'gB4R~ZpZ0t9~Y8giPx06cY42I-h11pZk_l', '--tenant', '....1', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f0b39f05ae8>, <function OutputProducer.on_global_arguments at 0x7f0b39a4ac80>, <function CLIQuery.on_global_arguments at 0x7f0b397ed158>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.003         2         9
cli.azure.cli.core: Total (1)                 0.003         2         9
cli.azure.cli.core: Loaded 2 groups, 9 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f0b38780488>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2022-07-28.14-18-02.login.21675.log'.
az_command_data_logger: command args: login --service-principal -u {} -p {} --tenant {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f0b38301598>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f0b3825dd08>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f0b3825de18>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f0b39a4ad08>, <function CLIQuery.handle_query_parameter at 0x7f0b397ed1e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f0b3825dd90>]
cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /root/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Region to be used: None
msal.telemetry: Generate or reuse correlation_id: a537bbad-f97e-4c3e-9353-fa7df6cea1e3
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/token HTTP/1.1" 200 1379
msal.token_cache: event={
    "client_id": "5c4b39e1-dc50-444b-b9aa-e482a2b5c00e",
    "data": {
        "claims": null,
        "scope": [
            "https://management.core.windows.net//.default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/token"
}
cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/service_principal_entries.json', encrypt=False
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/ce6f9430-1d64-4a97-a32d-e92a05a11971/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Region to be used: None
cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 2430cecd-15b5-409b-897b-6400e81746af
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fd3fb802-0e51-11ed-a11b-000d3ac9b77a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--service-principal -u -p --tenant --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.6.8 (Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fd3fb802-0e51-11ed-a11b-000d3ac9b77a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--service-principal -u -p --tenant --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.6.8 (Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fd3fb802-0e51-11ed-a11b-000d3ac9b77a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--service-principal -u -p --tenant --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.6.8 (Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fd3fb802-0e51-11ed-a11b-000d3ac9b77a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--service-principal -u -p --tenant --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.6.8 (Linux-3.10.0-1160.59.1.el7.x86_64-x86_64-with-redhat-7.9-Maipo)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 148, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 174, in login
    subscriptions = subscription_finder.find_using_specific_tenant(tenant, credential)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 798, in find_using_specific_tenant
    for s in subscriptions:
  File "/lib64/az/lib/python3.6/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 541, in get_next
    **kwargs
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/lib64/az/lib/python3.6/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 468, in send
    raise err
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/lib64/az/lib/python3.6/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

cli.azure.cli.core.azclierror: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
az_command_data_logger: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f0b387806a8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 5.700 seconds (init: 0.209, invoke: 5.491)
telemetry.save: Save telemetry record of length 3136 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/bin/python3.6 /usr/lib64/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /root/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.`

**Comment by abu3lia** [comment]
It turned out the issue is caused by the Firewall in the path, post bypassing it the connection succeeded.

**Comment by chrisribe** [comment]
> It turned out the issue is caused by the Firewall in the path, post bypassing it the connection succeeded.

I know this is old but what did you do to bypass it ?
