### ISSUE TITLE
Can install Preview needed to run "az aks nodepool stop"

### ISSUE THREAD

**Issue by pimanuel97** [Azure/azure-cli#23408]
## Describe the bug

**Command Name**
`az aks nodepool stop`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'map_azure_error_to_cli_error'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/parlin/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 105, in <module>
    from ._helpers import (
  File "/home/parlin/.azure/cliextensions/aks-preview/azext_aks_preview/_helpers.py", line 7, in <module>
    from azure.cli.command_modules.acs._helpers import map_azure_error_to_cli_error
ImportError: cannot import name 'map_azure_error_to_cli_error'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool stop --name {} --cluster-name {} --resource-group {}`

## Environment Summary
```
Linux-5.15.0-43-generic-x86_64-with-debian-bookworm-sid, Ubuntu 22.04 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.33.1 *

Extensions:
aks-preview 0.5.70
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@pimanuel97 Thanks for reaching out to us and reporting this issue. I see that you are using an older version of the `aks-preview `extension. Could you please run the below command to update your extension and check if that helps ? Awaiting your reply. 

>az extension update -n aks-preview

**Comment by pimanuel97** [comment]
Thank you
Its working now after uninstall and reinstall newest version.
