### ISSUE TITLE
az aks pod-identity command failure

### ISSUE THREAD

**Issue by Sri-Talla** [Azure/azure-cli#23427]
## Describe the bug

**Command Name**
`az aks pod-identity list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\stalla\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 105, in <module>
    from ._helpers import (
  File "C:\Users\stalla\.azure\cliextensions\aks-preview\azext_aks_preview\_helpers.py", line 7, in <module>
    from azure.cli.command_modules.acs._helpers import map_azure_error_to_cli_error
ImportError: cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks pod-identity list --help`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0 *

Extensions:
aks-preview 0.5.70

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Sri-Talla Can you please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
