### ISSUE TITLE
Issues working with Azure CLI

### ISSUE THREAD

**Issue by LiftedWorx** [Azure/azure-cli#23425]
## Describe the bug

**Command Name**
`az find`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=blob&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.39.0%22%2C+%22correlationId%22%3A+%228130501e-3a84-4cdc-9996-096bf5e19d72%22%2C+%22eventId%22%3A+%2248eba920-8fa9-4cb3-842a-1e62fa2747c7%22%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x06EF45E0>, 'Connection to app.aladdin.microsoft.com timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 96, in create_connection
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x06EF45E0>, 'Connection to app.aladdin.microsoft.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=blob&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.39.0%22%2C+%22correlationId%22%3A+%228130501e-3a84-4cdc-9996-096bf5e19d72%22%2C+%22eventId%22%3A+%2248eba920-8fa9-4cb3-842a-1e62fa2747c7%22%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x06EF45E0>, 'Connection to app.aladdin.microsoft.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/find/custom.py", line 36, in process_query
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/find/custom.py", line 126, in call_aladdin_service
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 75, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 504, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=blob&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.39.0%22%2C+%22correlationId%22%3A+%228130501e-3a84-4cdc-9996-096bf5e19d72%22%2C+%22eventId%22%3A+%2248eba920-8fa9-4cb3-842a-1e62fa2747c7%22%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x06EF45E0>, 'Connection to app.aladdin.microsoft.com timed out. (connect timeout=None)'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to CXP team
