### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'headers' while upload file with azure client

### ISSUE THREAD

**Issue by gavrochexu** [Azure/azure-cli#23423]
## Describe the bug

**Command Name**
`az dls fs upload`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'headers'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/dls/custom.py", line 180, in upload_to_adls
    client = cf_dls_filesystem(cmd.cli_ctx, account_name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/dls/_client_factory.py", line 40, in cf_dls_filesystem
    return core.AzureDLFileSystem(
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/core.py", line 72, in __init__
    self.connect()
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/core.py", line 90, in connect
    self.azure = DatalakeRESTInterface(token=self.token, req_timeout_s=self.per_call_timeout_seconds, **self.kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 273, in __init__
    self._check_token()  # Retryable method. Will ensure that signed_session token is current when we set it on next line
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 307, in _check_token
    check_token_internal()
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/retry.py", line 93, in f_retry
    out = func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 305, in check_token_internal
    self.head = {'Authorization': cur_session.headers['Authorization']}
AttributeError: 'NoneType' object has no attribute 'headers'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs upload --account {} --source-path {} --destination-path {}`

## Environment Summary
```
Linux-5.15.0-1014-azure-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by gavrochexu** [comment]
Hi, @yonzhan. I found a similar case reported 3 months ago: https://github.com/Azure/azure-cli/issues/22246. Was it caused by user or code in auzre client ?
