### ISSUE TITLE
az monitor log-analytics cluster show

### ISSUE THREAD

**Issue by hkamel** [Azure/azure-cli#23493]
## Describe the bug

**Command Name**
`az monitor log-analytics cluster show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'MSIAuthenticationWrapper' object has no attribute 'get_auxiliary_tokens'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 126, in __call__
    return self._handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/log_analytics/cluster/_show.py", line 33, in _handler
    self._execute_operations()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/log_analytics/cluster/_show.py", line 59, in _execute_operations
    self.ClustersGet(ctx=self.ctx)()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/log_analytics/cluster/_show.py", line 70, in __call__
    session = self.client.send_request(request=request, stream=False, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_client.py", line 86, in send_request
    session = self._pipeline.run(request, stream=stream, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_http_policy.py", line 105, in send
    self.on_request(request)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_http_policy.py", line 81, in on_request
    self._aux_tokens = self._credential.get_auxiliary_tokens(*self._scopes)
AttributeError: 'MSIAuthenticationWrapper' object has no attribute 'get_auxiliary_tokens'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- In Azure Cloud Shell run
- `az monitor log-analytics cluster show --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.39.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
monitor

**Comment by hkamel** [comment]
I'd like to add that this issue happens on Cloud Shell
