### ISSUE TITLE
az communication identity issue-access-token failing: 'azext_communication.custom#issue_access_token' is invalid.

### ISSUE THREAD

**Issue by jastill** [Azure/azure-cli#23500]
## Describe the bug

Trying to run az communication identity issue-access-token --scope chat --connection-string "<connection string>" and get the following error. 

Uninstalled and re-installed az cli and extension and still getting the same error.

**Command Name**
`az communication identity issue-access-token`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azext_communication.custom#issue_access_token' is invalid.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 61, in get_op_handler
    handler = getattr(handler, part)
AttributeError: module 'azext_communication.custom' has no attribute 'issue_access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azext_communication.custom#issue_access_token' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az communication identity issue-access-token --scope {} --connection-string {}`

## Environment Summary
```
macOS-12.5-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0

Extensions:
communication 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jastill Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jastill I am unable to reproduce this issue at my end. See below:

>C:\>az communication identity issue-access-token --scope chat --connection-string "endpoint=https://XXXXXXXX.communication.azure.com/;accesskey=5KtD8j7OOC9k******nqtdS1cCkIDxRJ+Bg=="
{
  "expires_on": "2022-08-12 06:58:16.497289+00:00",
  "token": "eyJhbGciOiJSU*************************Aeb9jz2NE2ngq_CqQ",
  "user_id": "8:acs:acbc0205-8313-*************f40f-343a0d00162f"
}

Sharing my AzCLI and extension versions:

>C:\>az version
{
  **"azure-cli": "2.39.0",**
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    **"communication": "1.1.2",**
  }
}

>python --version
**Python 3.10.4**

Could you please test again by using the same version as my environment and test again ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jastill I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any update on this. Awaiting your reply.

**Comment by jastill** [comment]
Hi @navba-MSFT ,

On MacOS 12.5 I have the following versions:

❯ az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
communication                      1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/Cellar/azure-cli/2.39.0/libexec/bin/python'
Extensions directory '/Users/i804190/.azure/cliextensions'

Python (Darwin) 3.10.6 (main, Aug  8 2022, 04:33:43) [Clang 13.1.6 (clang-1316.0.21.2.5)]

Which gives me the error:
❯ az communication identity issue-access-token --scope chat --connection-string "xxxxxxxxxxxxxxx"

The command failed with an unexpected error. Here is the traceback:
The operation 'azext_communication.custom#issue_access_token' is invalid.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 61, in get_op_handler
    handler = getattr(handler, part)
AttributeError: module 'azext_communication.custom' has no attribute 'issue_access_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute


.....

The command is working for me in Azure Cloud Shell which has the following versions:

johnxxx@Azure:~$ az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
communication                      1.1.2
ai-examples                        0.2.5
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/john_astill/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.10/site-packages/azure-cli-extensions'

Python (Linux) 3.10.5 (main, Jul 29 2022, 03:26:48) [GCC 8.3.0]

So potentially MacOS or my environment specific where  only see I have a minor Python version difference.

John

**Comment by navba-MSFT** [comment]
@jastill Thanks for getting back. Yes, since the AzCLI and extension version are the same in our environment, it seems like the issue is specific to your MacOS environment. Could you please test with the Python 3.10.5 / Python 3.10.4 version and test again in your environment ?

**Comment by navba-MSFT** [comment]
@jastill Adding on to my above comment.

The `issue-access-token ` command has been deprecated and will be removed in a future release. Use '`token issue`' instead.

Please refer [this](https://docs.microsoft.com/en-us/cli/azure/communication/identity/token?view=azure-cli-latest#az-communication-identity-token-issue) for more info. Hope this helps.

**Comment by navba-MSFT** [comment]
@jastill I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jastill The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by jastill** [comment]
with and without the optional --connection-string:

❯ az communication identity token issue --scope chat
Command group 'communication identity token' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.communication'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/i804190/.azure/cliextensions/communication/azext_communication/manual/_client_factory.py", line 13, in cf_communication_identity
    from azure.communication.identity import CommunicationIdentityClient
ModuleNotFoundError: No module named 'azure.communication'
To open an issue, please run: 'az feedback'




 az communication identity token issue --scope chat --connection-string "myconnectionstring"
Command group 'communication identity token' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.communication'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/Users/i804190/.azure/cliextensions/communication/azext_communication/manual/_client_factory.py", line 13, in cf_communication_identity
    from azure.communication.identity import CommunicationIdentityClient
ModuleNotFoundError: No module named 'azure.communication'
To open an issue, please run: 'az feedback'


az version

❯ az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
communication                      1.2.1

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/Cellar/azure-cli/2.39.0/libexec/bin/python'
Extensions directory '/Users/i804190/.azure/cliextensions'

Python (Darwin) 3.10.6 (main, Aug  8 2022, 04:33:43) [Clang 13.1.6 (clang-1316.0.21.2.5)]

Legal docs and information: aka.ms/AzureCliLegal


You have 1 updates available.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

This is on MacOS 12.5.1.
