### ISSUE TITLE
az webapp log download ssl error

### ISSUE THREAD

**Issue by kkantedi** [Azure/azure-cli#23541]
## Describe the bug

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='pace-prd-eastasia-api-app.scm.ase1-int-hkhk-cbre-prod.cbrecloudapps.com', port=443): Max retries exceeded with url: /dump (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/contrib/pyopenssl.py", line 498, in wrap_socket
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\OpenSSL/SSL.py", line 1915, in do_handshake
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\OpenSSL/SSL.py", line 1647, in _raise_ssl_error
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\OpenSSL/_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 416, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/contrib/pyopenssl.py", line 504, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2574, in download_historical_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2594, in _get_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/request.py", line 74, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/request.py", line 96, in request_encode_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/poolmanager.py", line 375, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 783, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 783, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 783, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pace-prd-eastasia-api-app.scm.ase1-int-hkhk-cbre-prod.cbrecloudapps.com', port=443): Max retries exceeded with url: /dump (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by ramfattah** [comment]
Hi @kkantedi,

Looks like I was not able to reproduce from my end.

#### Environment

* azure-cli 2.39.0
* core 2.39.0
* OS: Windows 11
* Windows Terminal: Powershell

#

After running `az webapp log download --name MyWebApp --resource-group MyResourceGroup`, it created a zip file containing the web app logs.

https://user-images.githubusercontent.com/38049078/184916131-92904035-4466-4106-9270-bf1c26557b0c.mp4


Steps I took:
1) Created an azure [app service ](https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vs)
2) In my local environment, I ran `az webapp log download --name MyWebApp --resource-group MyResourceGroup`

**Comment by ramfattah** [comment]
This error looks interesting:
`Max retries exceeded with url: /dump (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines',`

Were you able to run the command before or are you facing this issue suddenly?

**Comment by kkantedi** [comment]
Here is the screenshot, 
![image](https://user-images.githubusercontent.com/54891505/184919357-c44652b3-2181-48ba-b15d-7f0f8e17ba37.png)

**Comment by navba-MSFT** [comment]
@kkantedi Thanks for reaching out to us and reporting this issue. Could you please confirm if you have any proxy / firewall within your network ? If Yes, could you please try the same command from a different network and test ?

Alternatively, Could you also test the same command by running it from the[ Cloud shell ](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#code-try-4)and isolate this issue to be with your network ?

**Comment by navba-MSFT** [comment]
@kkantedi I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kkantedi The action is currently pending on you to try the above action plan and get back to us with an update. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
