### ISSUE TITLE
Fails to az login 

### ISSUE THREAD

**Issue by shaniiiwild** [Azure/azure-cli#23557]
az feeback failed due to the same issue probably; was unable to open the browser,
**therefore this is the error log when I run az login:**

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/open
id-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49e6046400>: Failed to establish a
 new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e

**Comment by RakeshMohanMSFT** [comment]
@shaniiiwild Please go through this issue and see if it helps
https://github.com/Azure/azure-cli/issues/21514

**Comment by shaniiiwild** [comment]
thanks @RakeshMohanMSFT 
it was helpful. 
Eventually I restarted my computer and it worked like magic :)
