### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by ricardo2009** [Azure/azure-cli#23550]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 515, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ricardolima\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 105, in <module>
    from ._helpers import (
  File "C:\Users\ricardolima\.azure\cliextensions\aks-preview\azext_aks_preview\_helpers.py", line 7, in <module>
    from azure.cli.command_modules.acs._helpers import map_azure_error_to_cli_error
ImportError: cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.8.9
Installer: 

azure-cli 2.33.1 *

Extensions:
aks-preview 0.5.70
alertsmanagement 0.2.2
resource-graph 2.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ricardo2009 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ricardo2009 I see that you are using an older version of the `aks-preview` extension. Could you please run the below command to update to the most recent version of this extension and check if that helps ? Awaiting your reply.

>az extension update -n aks-preview

**Comment by navba-MSFT** [comment]
@ricardo2009 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are still facing this issue after updating your extension. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ricardo2009 The action is currently pending on you to update your `aks-preview `extension and check if that fixes this issue.. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by ricardo2009** [comment]
What would be the procedure to install aks-preview ?

**Comment by navba-MSFT** [comment]
@ricardo2009 I see that you already have it installed. You just need to update it by running the below command:

>az extension update -n aks-preview

If you still want to know the command to install / add this extension here it is:
>az extension add -n aks-preview
