### ISSUE TITLE
az webapp log download getting connection broken

### ISSUE THREAD

**Issue by kpconnell** [Azure/azure-cli#23563]
## Describe the bug

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection broken: IncompleteRead(646 bytes read)', IncompleteRead(646 bytes read))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 532, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 567, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 597, in _read_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(646 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2575, in download_historical_logs
    _get_log(url, user_name, password, log_file)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2607, in _get_log
    data = r.read(1024)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 512, in read
    with self._error_catcher():
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(646 bytes read)', IncompleteRead(646 bytes read))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --name {} --resource-group {}`

## Environment Summary
```
macOS-12.5-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kpconnell Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@kpconnell Sharing a few action plans here to isolate this issue:

- Do you have a proxy / firewall within your network ? If yes, could you bypass it and check if you see the same issue ?

- Could you please try running the same command from another network which is faster and more reliable ? 

- Did you try to run the same command from the [Azure Cloud Shell ](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#code-try-4)and check if you encounter the same issue ?

- If the above action plans doesn't help, Could you please run the same command with `--debug `output and share it here ?

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kpconnell I wanted to do quick follow-up to check if you had a chance to look at my above comment and try the action plan. Please let us know if you have any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kpconnell The action is currently pending on you to try the above suggestion and get back to us. If you still face the same issue, please feel free to reopen this thread. We would be happy to help.
