### ISSUE TITLE
Unable to create Azure Container App Environment

### ISSUE THREAD

**Issue by snapfisher** [Azure/azure-cli#23582]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az containerapp env create --name acae-dthanding-dgen --resource-group dthandling --location eastus

**Describe the bug**

Big Red CLI error

No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-dthandlingLgin"
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/4d34293e-e544-4865-887d-b49c169bf080/resourceGroups/dthandling/providers/Microsoft.App/managedEnvironments/acae-dthanding-dgen?api-version=2022-03-01 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x059C8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 73, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x059C8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/4d34293e-e544-4865-887d-b49c169bf080/resourceGroups/dthandling/providers/Microsoft.App/managedEnvironments/acae-dthanding-dgen?api-version=2022-03-01 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x059C8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 981, in create_managed_environment
    handle_raw_exception(e)
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 970, in create_managed_environment
    r = ManagedEnvironmentClient.create(
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\_clients.py", line 461, in create
    return poll(cmd, request_url, "waiting")
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\_clients.py", line 68, in poll
    raise e
  File "C:\Users\pfisher\.azure\cliextensions\containerapp\azext_containerapp\_clients.py", line 53, in poll
    r = send_raw_request(cmd.cli_ctx, "GET", request_url)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 985, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/4d34293e-e544-4865-887d-b49c169bf080/resourceGroups/dthandling/providers/Microsoft.App/managedEnvironments/acae-dthanding-dgen?api-version=2022-03-01 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x059C8100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
To open an issue, please run: 'az feedback'

**To Reproduce**
Run the above command

**Expected behavior**
A container app environment should be created

**Environment summary**
az --version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
containerapp                       0.3.9

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\pfisher\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**
Before I received this error, I tried a couple of other times.  Then I did not get this error, but the resulting provisioningState was "failed".   I received this error twice.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@snapfisher Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@snapfisher We managed to create without any issue, see below image. Can you retry or check your connectivity to management.azure.com please?
![image](https://user-images.githubusercontent.com/49954584/185601010-81492e87-a8e1-4005-a647-b7cb54839b65.png)
