### ISSUE TITLE
Cannot get aks credentials with azure-cli 2.39.0

### ISSUE THREAD

**Issue by digennarot** [Azure/azure-cli#23594]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-06-01 does not have operation group 'managed_clusters'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/acs/_client_factory.py", line 27, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerservice/_container_service_client.py", line 404, in managed_clusters
    raise ValueError("API version {} does not have operation group 'managed_clusters'".format(api_version))
ValueError: API version 2022-06-01 does not have operation group 'managed_clusters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Linux-5.18.10-76051810-generic-x86_64-with-glibc2.35, Pop!_OS 22.04 LTS
Python 3.10.4
Installer: PIP

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@digennarot Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please try to use the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) of Azure CLI and check if that helps ?

**Comment by jiasli** [comment]
`dist-packages` suggests this is not official Azure CLI package. See https://github.com/Azure/azure-cli/issues/19640.

**Comment by navba-MSFT** [comment]
@digennarot I hope you had a chance to look at the above comment. Could you please install the [Microsoft official CLI ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@digennarot I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@digennarot The action is currently pending on you to install the [Microsoft official CLI ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)and check if you run into the same issue. Please feel free to reopen this thread if you need any further assistance on this. We would be happy to help.
