### ISSUE TITLE
can't export dns zone

### ISSUE THREAD

**Issue by rivir** [Azure/azure-cli#23645]
## Describe the bug

**Command Name**
`az network dns zone export`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'txt'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 2481, in export_zone
    zone_file_content = make_zone_file(zone_obj)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/zone_file/make_zone_file.py", line 94, in make_zone_file
    getattr(record_processors, method)(zone_file, entry, record_set_name, first_line)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/zone_file/record_processors.py", line 126, in process_txt
    return process_rr(io, _quote_field(data, 'txt'), 'TXT', 'txt', name, print_name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/zone_file/record_processors.py", line 55, in _quote_field
    for c in data[field]:
KeyError: 'txt'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns zone export -g {} -n {} -f {}`

## Environment Summary
```
Linux-5.4.0-1089-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.39.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.41.0
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by ZengTaoxu** [comment]
Hi @rivir, this error is caused by the null value of type "txt" in your DNS zone. Do you want to export type "txt" with empty value? Still want to delete this "txt" record in the export file?
