### ISSUE TITLE
'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by SamaRamya** [Azure/azure-cli#23640]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az deployment group create \
              --name "TestDeployment" \
              --resource-group "rg-11912-d-001" \
              --template-uri "https://github.intra.fcagroup.com/raw/FCA-ICT/smdn-cdp-adl-etl-11912/t0007el-patch-1/arm_template.json?token=GHSAT0AAAAAAAAAC5MBJRLM35JB7T2ULIXGYYN2KWA"
              --parameters "factoryName=df-11912-d-001"

**Describe the bug**

The version of az cli which im using is  2.27.2.
I want to deploy the arm_template.json file which is present in my repository.
So for deploying that file i was trying to take its path.
when i gave that path(i.e path of -- template-uri as u can see the command)it showing the error : 'str' object has no attribute 'get'.
Please help me.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@SamaRamya Could you please send the debug log *(add `--debug` parameter)* and arm_template.json to me by email, my email address is Zhou.Xing@microsoft.com, thanks~

**Comment by SamaRamya** [comment]
@zhoxing-ms I have sent u.Please check the mail.

**Comment by SamaRamya** [comment]
C:\Users\T5204RS\Desktop\adf>az group deployment create --name Schema --template-file arm_template.json --resource-group rg-11912-d-001 --debug
cli.knack.cli: Command arguments: ['group', 'deployment', 'create', '--name', 'Schema', '--template-file', 'arm_template.json', '--resource-group', 'rg-11912-d-001', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x015BBC88>, <function OutputProducer.on_global_arguments at 0x0177E5C8>, <function CLIQuery.on_global_arguments at 0x0179A220>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'group': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.031        47       207
cli.azure.cli.core: Total (1)                 0.031        47       207
cli.azure.cli.core: Loaded 47 groups, 207 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : group deployment create
cli.azure.cli.core: Command table: group deployment create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03AF1E80>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\T5204RS\.azure\commands\2022-08-26.14-01-11.group_deployment_create.5612.log'.
az_command_data_logger: command args: group deployment create --name {} --template-file {} --resource-group {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03B29AD8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03B29B68>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03B3D100>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0177E610>, <function CLIQuery.handle_query_parameter at 0x0179A268>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03B3D0B8>]
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
cli.azure.cli.core.util: attempting to read file arm_template.json as utf-8-sig
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 1601, in deploy_arm_template
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 339, in _deploy_arm_template_core_unmodified
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 263, in _get_missing_parameters
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 189, in _prompt_for_parameters
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
AttributeError: 'AttributeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
knack.util.CLIError: 'str' object has no attribute 'get'

cli.azure.cli.core.azclierror: 'str' object has no attribute 'get'
az_command_data_logger: 'str' object has no attribute 'get'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03AF1FA0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.295 seconds (init: 1.060, invoke: 1.235)
telemetry.save: Save telemetry record of length 3073 in cache
telemetry.check: Negative: The C:\Users\T5204RS\.azure\telemetry.txt was modified at 2022-08-26 13:55:27.480316, which in less than 600.000000 s

**Comment by SamaRamya** [comment]
@zhoxing-ms please check the above debug log

**Comment by zhoxing-ms** [comment]
@SamaRamya  In order to reproduce your problem, could you send the ARM template `arm_template.json` you used to me by email? My email address is [Zhou.Xing@microsoft.com](mailto:Zhou.Xing@microsoft.com), thanks~

**Comment by SamaRamya** [comment]
@zhoxing-ms  have sent u the arm_template.json which i used only.If you want i will reshare

**Comment by zhoxing-ms** [comment]
@SamaRamya Sorry, I haven't received the relevant email yet. Could you please help reshare it?

**Comment by SamaRamya** [comment]
@zhoxing-ms Can u please check the mail now

**Comment by SamaRamya** [comment]
@zhoxing-ms did u check my mail?

**Comment by zhoxing-ms** [comment]
Sorry, since I'm super busy with the feature of sprint release. + @yanzhudd to help with this issue

**Comment by SamaRamya** [comment]
@yanzhudd i will try changing it.Thank You

**Comment by SamaRamya** [comment]
@yanzhudd is that the only problem in the template.Beacuse now after making changes it is showing invalid json format.
Error:Failed to parse 'modified_template.json', please check whether it is a valid JSON format

**Comment by yanzhudd** [comment]
> please check whether it is a valid JSON format

Hello @SamaRamya, I cannot reproduce this problem, could you please send us your modified_template.json file in email? My email address is 'zhuyan@microsoft.com'. Thanks

**Comment by SamaRamya** [comment]
@yanzhudd,i have sent u the mail. Please check.

**Comment by yanzhudd** [comment]
> @yanzhudd,i have sent u the mail. Please check.

Okay, received. We will check and get back to you.

**Comment by SamaRamya** [comment]
sure

**Comment by yanzhudd** [comment]
Hello @SamaRamya, I have sent you a mail attached a file. Please check.

**Comment by SamaRamya** [comment]
ok

**Comment by SamaRamya** [comment]
@yonzhan I exactly dint understand what changes u have made to that file.Can u please let me know in detail?

**Comment by SamaRamya** [comment]
@yonzhan Got it! U just added the spaces right?

**Comment by SamaRamya** [comment]
@yonzhan Thank u so much yon.That worked actually!Now im facing another error:ERROR: Missing input parameters: ls_az_adls_cdp_connectionString, ls_az_sql_db_cdp_connectionString Can u please suggest something on this?

**Comment by SamaRamya** [comment]
@yanzhudd please ignore the above error

**Comment by SamaRamya** [comment]
the value for my parameter is like abc=123; def=456;and so on....The problem here is it is taking abc as a parameter and throwing the error like it is unrecognized parameter. Can u suggest me on this?
**ERROR: unrecognized template parameter 'Integrated Security'. Allowed parameters: factoryName, ls_az_adls_cdp_connectionString, ls_az_kv_cdp_properties_typeProperties_baseUrl, ls_az_sql_db_cdp_connectionString, ls_sftp_cdp_properties_typeProperties_host, ls_sftp_cdp_properties_typeProperties_userName, trigger_daily_properties_typeProperties_scope**

**Comment by yanzhudd** [comment]
> 

Could you please help to provide your modified command and param in mail?

**Comment by SamaRamya** [comment]
sure i will

**Comment by yanzhudd** [comment]
Hello @SamaRamya, I have replied to your mail. Please check.

**Comment by SamaRamya** [comment]
Hi @yanzhudd please check my mail.

**Comment by yanzhudd** [comment]
Hello @SamaRamya, please check the mail.

**Comment by SamaRamya** [comment]
hi @yanzhudd please check the mail now

**Comment by SamaRamya** [comment]
Hi@yanzhudd Issue Resolved.You can lose the issue now.Thanks

**Comment by jsr28** [comment]
Hello @SamaRamya excuse me, How could you resolve this issue?
