### ISSUE TITLE
az webapp config appsettings set

### ISSUE THREAD

**Issue by MrDarkPat** [Azure/azure-cli#23650]
## Describe the bug

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 557, in shell_safe_json_parse
  File "json\__init__.py", line 359, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 390, in update_app_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 583, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
@slotsettings.json
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 401, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config appsettings set -g {} -n {} --settings {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
application-insights 0.1.16
interactive 0.4.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@MrDarkPat I don't see any issues running the cmdlet. 
![image](https://user-images.githubusercontent.com/38112130/186984642-1bc56e5f-06f5-49e1-8cb0-a09706943d8d.png)
If you are using a settings file can you please make sure you are in the same directory or passing the filename + path correctly like below -
![image](https://user-images.githubusercontent.com/38112130/186985069-18475187-85c5-497c-8855-24a1e50b03c6.png)
Also, please check if the json content is correct.
![image](https://user-images.githubusercontent.com/38112130/186985278-8074b53e-1acc-44ab-a4e8-83b059ef7825.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@MrDarkPat Please let me know if you have any questions.

**Comment by SaurabhSharma-MSFT** [comment]
@MrDarkPat We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
