### ISSUE TITLE
fail to login in

### ISSUE THREAD

**Issue by MayXuQQ** [Azure/azure-cli#23657]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /6047c7e9-b2ad-488d-a54e-dc3f6be6a7ee/v2.0/.well-known/openid-configuration (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcd871c60e0>, 'Connection to 20.245.149.137 timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fcd871c60e0>, 'Connection to 20.245.149.137 timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /6047c7e9-b2ad-488d-a54e-dc3f6be6a7ee/v2.0/.well-known/openid-configuration (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcd871c60e0>, 'Connection to 20.245.149.137 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 159, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 166, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 123, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/usr/lib/python3.10/site-packages/msal/application.py", line 456, in __init__
    self.authority = Authority(
  File "/usr/lib/python3.10/site-packages/msal/authority.py", line 100, in __init__
    openid_config = tenant_discovery(
  File "/usr/lib/python3.10/site-packages/msal/authority.py", line 160, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/usr/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /6047c7e9-b2ad-488d-a54e-dc3f6be6a7ee/v2.0/.well-known/openid-configuration (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fcd871c60e0>, 'Connection to 20.245.149.137 timed out. (connect timeout=None)'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --password {} --tenant {}`

## Environment Summary
```
Linux-5.15.16-200.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Cloud Edition)
Python 3.10.4
Installer: PIP

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
Please go through this issue and see if it helps
https://github.com/Azure/azure-cli/issues/21514

**Comment by MayXuQQ** [comment]
> Please go through this issue and see if it helps #21514

nslookup login.microsoftonline.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
login.microsoftonline.com	canonical name = ak.privatelink.msidentity.com.
ak.privatelink.msidentity.com	canonical name = www.tm.ak.prd.aadg.akadns.net.
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.82
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.83
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.148
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.146
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.147
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.152.19
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 40.126.24.149
Name:	www.tm.ak.prd.aadg.akadns.net
Address: 20.190.152.22
az login --service-principal ... 
long time not response. 

How to resolve it ?
