### ISSUE TITLE
command failed with an unexpected error, cannot import name '_psutil_linux' from partially initialized module 'psutil'

### ISSUE THREAD

**Issue by ericjs** [Azure/azure-cli#23674]
## Describe the bug

**Command Name**
`az ssh config`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ericjs/.azure/cliextensions/ssh/azext_ssh/custom.py", line 23, in <module>
    from . import rdp_utils
  File "/home/ericjs/.azure/cliextensions/ssh/azext_ssh/rdp_utils.py", line 10, in <module>
    import psutil
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh config --file {} -n {} -g {}`

## Environment Summary
```
Linux-5.19.1-1-default-x86_64-with-glibc2.35, openSUSE Tumbleweed
Python 3.10.6
Installer: RPM

azure-cli 2.38.0 *

Extensions:
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by ericjs** [comment]
This is under openSUSE Tumbleweed after installing the official version according to the instructions here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper
I'd previously been using an unofficial version from the opensuse repositories successfully, until I recently started getting the error "API version 2021-08-01 does not have operation group 'network_interfaces'". So I uninstalled that and installed this official version, which does not seem to work. FWIW the unofficial version also pulled in a ton of dependencies, none of which this official version seems to call for. That unofficial version used python 3.10, which this official version seems to be using 3.6

**Comment by ericjs** [comment]
Since tumbleweed doesn't have python 3.6 (it has 3.8, 3.9 and 3.10) I tried using the instructions on the page I referenced under the section "Install on SLES 12 or other systems without Python 3.6". I ran the curl command given and started a new bash shell, and tried the az ssh config command again. I get the result except for the line in the traceback which previously said python3.10 now says python3.8. Here it is

`The command failed with an unexpected error. Here is the traceback:
cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ericjs/.azure/cliextensions/ssh/azext_ssh/custom.py", line 23, in <module>
    from . import rdp_utils
  File "/home/ericjs/.azure/cliextensions/ssh/azext_ssh/rdp_utils.py", line 10, in <module>
    import psutil
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib64/az/lib/python3.6/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib64/az/lib/python3.6/site-packages/psutil/__init__.py)`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by ynden** [comment]
Hey @ericjs,

Can you try this workaround, and let us know what is the result please:
1. Make sure you have Python 3.10 installed (if not upgrade it first) or follow those sub-steps
    1. Run `zypper install python39` It'll install it as python3.9 (we don't want that since it's gonna be confusing)
    2. Run `ln -s /usr/bin/python3.9 /usr/bin/python` && `ln -s /usr/bin/python3.9 /usr/bin/python3`
    
4. Uninstall az cli using `zypper remove -y azure-cli`
5. Run `zypper install openssl`
6. Run `zypper install openssh-server`
7.  Run `zypper install curl`
8.  Run `curl -L https://aka.ms/InstallAzureCli | bash`
> Just enter 'y' every single time (even if it says that you are missing some libraries)
10.  Run `az extension add --name ssh`

Then try to run your command, it should work.

**Comment by ericjs** [comment]
Hi @ynden,
That worked! My "az ssh config" work successfully again, as before.
Thank you much,
Eric

**Comment by RakeshMohanMSFT** [comment]
@ericjs Glad to hear that its working. @ynden Thank you for providing the solution.
