### ISSUE TITLE
Failed to Download Logs for Azure App Service

### ISSUE THREAD

**Issue by resqrobert** [Azure/azure-cli#23738]
## Describe the bug
My attempts to download logs using `az web app log show` are consistently failing.  The is a new error.  I performed `az upgrade` and continue to have the issue.

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection broken: IncompleteRead(350 bytes read)', IncompleteRead(350 bytes read))
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 532, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 567, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 597, in _read_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(350 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2575, in download_historical_logs
    _get_log(url, user_name, password, log_file)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2607, in _get_log
    data = r.read(1024)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 512, in read
    with self._error_catcher():
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(350 bytes read)', IncompleteRead(350 bytes read))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --resource-group {} --name {} --log-file {}`

## Environment Summary
```
macOS-11.6.8-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@resqrobert I am unable to reproduce this error.  Can you please try using downloading any other web app ?

**Comment by resqrobert** [comment]
Okay.. that seemed to work.  So it's just something about the specific app service?  Note that the failing app service is a Linux environment whereas the test that passed was for a Windows environment.  Running another test now on another Linux-based app service.

**Comment by resqrobert** [comment]
Indeed it is something wrong specifically with our `rq-wtp` app.  I've tested a few others and don't have this problem.

**Comment by SaurabhSharma-MSFT** [comment]
@resqrobert As mentioned in the document this command will not work for a linux based web apps and that's why you may be getting the download error.
> ![image](https://user-images.githubusercontent.com/38112130/187983768-1a4b5c73-6894-4908-aab6-75b4a349fe1d.png)

**Comment by resqrobert** [comment]
Okay, thank you for the info @SaurabhSharma-MSFT. I was unaware of this and have not run into trouble until now.  How then does Microsoft recommend I access my server logs for Linux based web apps?

**Comment by SaurabhSharma-MSFT** [comment]
@resqrobert I am checking internally with the products team on this and get back to you as soon as possible.

**Comment by SaurabhSharma-MSFT** [comment]
@resqrobert Our Product Group team has identified the cause and shared the below RCA:

The Microsoft Azure Team has investigated the issue you reported regarding log download not working for your app.

Upon investigation, engineers determined that this was due to a code bug in the Kudu site, which creates the zip archive containing all logs. We identified a race condition which could cause the zip archive to be malformed. The CLI could not parse the malformed zip and threw the error you were seeing.

We have identified the fix for the issue and will be releasing it as part of our next platform upgrade.

As workaround, you may download logs directly using [Kudu REST API](https://github.com/projectkudu/kudu/wiki/REST-API#zip) /api/zip or using the File Manager on [Kudu NewUI](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/new-kudu-ui-for-app-service-on-linux-preview/ba-p/3212270) /newui.

We are continuously taking steps to improve the Azure Web App service and our processes to ensure such incidents do not occur in the future, and in this case it includes (but is not limited to):

Bug fix for Kudu
CLI changes to handle such errors more gracefully
We apologize for any inconvenience.
