### ISSUE TITLE
Resource Lock - impossible to work with

### ISSUE THREAD

**Issue by lkurzyniec-bcg** [Azure/azure-cli#23767]
**Command Name**
`az resource lock list`

**Errors:**
```
Missing required resource_name parameter.
```

## Expected Behavior
Be able to list resource locks

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
account 0.2.3
managementpartner 0.1.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

Some tries:
```
❯ az resource lock list --resource /subscriptions/da0efdd1-xxx/resourceGroups/UC-xxx -g UC-xxx      
--resource-type is required if the name, --resource, is present
```

```
az resource lock list --resource /subscriptions/da0efdd1xxx/resourceGroups/UC-xxx -g UC-xxx --resource-type Microsoft.Resources/subscriptions/resourceGroups
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/locks/v2016_09_01/operations/_operations.py", line 1731, in get_next
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/locks/v2016_09_01/operations/_operations.py", line 1693, in prepare_request    
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/locks/v2016_09_01/operations/_operations.py", line 564, in build_management_locks_list_at_resource_level_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 652, in url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 760, in serialize_data
ValueError: No value for given attribute
```

```
❯ az resource lock list --resource /subscriptions/da0efdd1-xxx/resourceGroups/UC-xxx -g UC-xxx      
--resource-type is required if the name, --resource, is present
```

```
❯ az resource lock list --resource "/subscriptions/da0efdd1-xxx/resourceGroups/UC-xxx"
'NoneType' object has no attribute 'strip'
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@lkurzyniec-bcg Please note that the `--resource` parameter is either passed in a complete resource id **(not the resource group id)**, such as
> az resource lock list --resource /subscriptions/{subscription}/resourceGroups/zhoxing-test/providers/Microsoft.Storage/storageAccounts/zhoxing

Or the resource name is passed in and used together with the `--resource-group` and `--resource-type` parameters, such as:
> az resource lock list -g MyResourceGroup --resource ResourceName --resource-type Microsoft.Storage/storageAccounts

**Comment by ynden** [comment]
@lkurzyniec-bcg,
Can you can try with `az group lock delete --name lockName -g MyResourceGroup` and confirm?
More information on resource group locks [here](https://docs.microsoft.com/en-us/cli/azure/group/lock?view=azure-cli-latest).

**Comment by ynden** [comment]
@lkurzyniec-bcg,
I see you tried with `az resource lock`, not `az group lock`. Make sure you try with the suggested command above, and confirm.

**Comment by zhoxing-ms** [comment]
@ynden Thanks for your kind reply!

@lkurzyniec-bcg Please note that there are two command groups with different scopes. 
If you want to operate the lock of resource group level, please use `az group lock `
```pwsh
> (env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az group lock -h

Group
    az group lock : Manage Azure resource group locks.
```

If you want to operate the lock of resource level, please use `az resource lock`
```pwsh
> (env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az resource lock -h

Group
    az resource lock : Manage Azure resource level locks.
```
