### ISSUE TITLE
az datafactory trigger stop/start CLI command not working throws ERROR: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies

### ISSUE THREAD

**Issue by ANithish** [Azure/azure-cli#23772]
When stopping/starting ADF triggers facing below error. Working fine earlier but facing issues from yesterday .
Command using:- az datafactory trigger stop --factory-name "adfname" --resource-group "resourcegroupname" --name "TriggerName"
Error:- 
WARNING: The command requires the extension datafactory. It will be installed first.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/mgmt/core/policies/__init__.py)
Traceback (most recent call last):
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/jenkins/azure/extensions/datafactory/azext_datafactory/generated/_client_factory.py", line 52, in cf_trigger
    return cf_datafactory_cl(cli_ctx).triggers
  File "/home/jenkins/azure/extensions/datafactory/azext_datafactory/generated/_client_factory.py", line 14, in cf_datafactory_cl
    from azext_datafactory.vendored_sdks.datafactory import DataFactoryManagementClient
  File "/home/jenkins/azure/extensions/datafactory/azext_datafactory/vendored_sdks/datafactory/__init__.py", line 9, in <module>
    from ._data_factory_management_client import DataFactoryManagementClient
  File "/home/jenkins/azure/extensions/datafactory/azext_datafactory/vendored_sdks/datafactory/_data_factory_management_client.py", line 18, in <module>
    from ._configuration import DataFactoryManagementClientConfiguration
  File "/home/jenkins/azure/extensions/datafactory/azext_datafactory/vendored_sdks/datafactory/_configuration.py", line 13, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/tools/azurecli/azurecli-2.29.2/lib/python3.7/site-packages/azure/mgmt/core/policies/__init__.py)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ANithish I do not see any issues executing the cmdlet and it works fine.
What is the "datafactory" version in your CLI environment ?
Also, can you please share the debug information by using the same command with `--debug`.
