### ISSUE TITLE
Curl install improvements (based on feedback)

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2377]
```
$ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0    678      0 --:--:-- --:--:-- --:--:--   818
100   989  100   989    0     0   1810      0 --:--:-- --:--:-- --:--:-- 34103
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs.
######################################################################## 100.0%
5.84
/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs: OK
Running install script.
-- Verifying Python version.
-- Python version 3.6.0 okay.

===> In what directory would you like to place the install? (leave blank to use '/Users/parallels/lib/azure-cli'): 
-- Creating directory '/Users/parallels/lib/azure-cli'.
-- We will install at '/Users/parallels/lib/azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use '/Users/parallels/bin'): 
-- Creating directory '/Users/parallels/bin'.
-- The executable will be in '/Users/parallels/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
-- Downloaded virtualenv package to /var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/tmp2d7efne9/virtualenv-15.0.0.tar.gz.
-- Checksum of /var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/tmp2d7efne9/virtualenv-15.0.0.tar.gz OK.
-- Extracting '/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/tmp2d7efne9/virtualenv-15.0.0.tar.gz' to '/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/tmp2d7efne9'.
-- Executing: ['/Users/parallels/anaconda/bin/python', 'virtualenv.py', '--python', '/Users/parallels/anaconda/bin/python', '/Users/parallels/lib/azure-cli']
Already using interpreter /Users/parallels/anaconda/bin/python
Using base prefix '/Users/parallels/anaconda'
New python executable in /Users/parallels/lib/azure-cli/bin/python
dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/parallels/lib/azure-cli/bin/python
  Reason: image not found
ERROR: The executable /Users/parallels/lib/azure-cli/bin/python is not functioning
ERROR: It thinks sys.prefix is '/private/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/tmp2d7efne9/virtualenv-15.0.0' (should be '/Users/parallels/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs", line 346, in <module>
    main()
  File "/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs", line 331, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs", line 135, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/var/folders/xg/6kvpfmgj1zd5rh2lrp658bj00000gn/T/azure_cli_install_tmp_XXXX.ZJMbA3Zs", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/Users/parallels/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/parallels/anaconda/bin/python', 'virtualenv.py', '--python', '/Users/parallels/anaconda/bin/python', '/Users/parallels/lib/azure-cli']' returned non-zero exit status 100.
```

Script should detect Anaconda and should an appropriate error message to install with pip.

**Comment by derekbekoe** [comment]
Solution is to create a virtual environment in `conda` and install with pip.
For example:
```
$ conda create -n myenv
$ source activate myenv
$ pip install azure-cli
```

**Comment by derekbekoe** [comment]
- [ ] Show appropriate error message on interactive script install if using Anaconda
- [ ] Reference this issue in https://github.com/Azure/azure-cli/blob/master/doc/install_troubleshooting.md.

**Comment by derekbekoe** [comment]
Also

- [ ] Show appropriate error message is user tries to run script from Windows.

```
$ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0    356      0 --:--:-- --:--:-- --:--:--   410
100   989  100   989    0     0   1171      0 --:--:-- --:--:-- --:--:--  1171
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_3Dnf.
######################################################################## 100.0%
5.95
/tmp/azure_cli_install_tmp_3Dnf: OK
Running install script.
-- Verifying Python version.
-- Python version 3.6.0 okay.
 
===> In what directory would you like to place the install? (leave blank to use 'C:\Users\myuser\lib\azure-cli'):
-- Creating directory 'C:\Users\myuser\lib\azure-cli'.
-- We will install at 'C:\Users\myuser\lib\azure-cli'.
 
===> In what directory would you like to place the 'az' executable? (leave blank to use 'C:\Users\myuser\bin'):
Already using interpreter C:\Python\python.exe
Using base prefix 'C:\\Python'
New python executable in C:\Users\myuser\lib\azure-cli\Scripts\python.exe
Installing setuptools, pip, wheel...done.
-- Creating directory 'C:\Users\myuser\bin'.
-- The executable will be in 'C:\Users\myuser\bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
-- Downloaded virtualenv package to C:\Users\myuser\AppData\Local\Temp\tmp87ynl_qp\virtualenv-15.0.0.tar.gz.
-- Checksum of C:\Users\myuser\AppData\Local\Temp\tmp87ynl_qp\virtualenv-15.0.0.tar.gz OK.
-- Extracting 'C:\Users\myuser\AppData\Local\Temp\tmp87ynl_qp\virtualenv-15.0.0.tar.gz' to 'C:\Users\myuser\AppData\Local\Temp\tmp87ynl_qp'.
-- Executing: ['C:\\Python\\python.exe', 'virtualenv.py', '--python', 'C:\\Python\\python.exe', 'C:\\Users\\myuser\\lib\\azure-cli']
-- Executing: ['C:\\Users\\myuser\\lib\\azure-cli\\bin\\pip', 'install', '--cache-dir', 'C:\\Users\\myuser\\AppData\\Local\\Temp\\tmp87ynl_qp', 'azure-cli', '--upgrade']
Traceback (most recent call last):
 File "C:/Users/myuser/AppData/Local/Temp/azure_cli_install_tmp_3Dnf", line 346, in <module>
    main()
  File "C:/Users/myuser/AppData/Local/Temp/azure_cli_install_tmp_3Dnf", line 332, in main
    install_cli(install_dir, tmp_dir)
  File "C:/Users/myuser/AppData/Local/Temp/azure_cli_install_tmp_3Dnf", line 140, in install_cli
    exec_command(cmd)
  File "C:/Users/myuser/AppData/Local/Temp/azure_cli_install_tmp_3Dnf", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "C:\Python\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by derekbekoe** [comment]
Install CLI with Python Anaconda and you get an unfriendly error
- [ ] Show appropriate error message on interactive script install if using Anaconda
- [ ] Reference this issue in https://github.com/Azure/azure-cli/blob/master/doc/install_troubleshooting.md.
- [ ] Show appropriate error message is user tries to run script from Windows.
- [ ] If no bashrc or bash_profile file found, print one line instructions stating what file is typically required (i.e. `~/.bashrc` on Linux, `~/.bash_profile` on macOS).
