### ISSUE TITLE
Crash when upgrading bicep

### ISSUE THREAD

**Issue by lhotrifork** [Azure/azure-cli#23799]
## Describe the bug
This morning I could no longer run `az deployment` which gave the following error:
```
 az deployment group what-if --resource-group rg-my-own --template-file Bicep/main.bicep --parameters Bicep/main.parameters-dev.json  
[Errno 8] Exec format error: '/Users/lassehojgaard/.azure/bin/bicep'
```
I tried fixing it with an upgrade, but then that failed.
Uninstalling and reinstalling seems to have fixed it.

**Command Name**
`az bicep upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 8] Exec format error: '/Users/lassehojgaard/.azure/bin/bicep'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3672, in upgrade_bicep_cli
    ensure_bicep_installation(release_tag=latest_release_tag, target_platform=target_platform)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 96, in ensure_bicep_installation
    installed_version = _get_bicep_installed_version(installation_path)
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 200, in _get_bicep_installed_version
    installed_version_output = _run_command(bicep_executable_path, ["--version"])
  File "/opt/homebrew/Cellar/azure-cli/2.39.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 238, in _run_command
    process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/lassehojgaard/.azure/bin/bicep'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep upgrade`

## Environment Summary
```
macOS-12.3-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@lhotrifork Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@lhotrifork I believe you are using macOS. Could you please install Azure Bicep manually and add it to your **PATH** to see if that helps ? 

When installing manually, select a location that is different than the one managed by Azure CLI. All of the following examples use a location named bicep or .bicep. This location won't conflict with the location managed by Azure CLI, which uses .azure.

You can follow **either** of the below approach:

> **macOS Via homebrew**
```
# Add the tap for bicep
brew tap azure/bicep

# Install the tool
brew install bicep
```

> **macOS Via Bash**
```
# Fetch the latest Bicep CLI binary
curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-osx-x64
# Mark it as executable
chmod +x ./bicep
# Add Gatekeeper exception (requires admin)
sudo spctl --add ./bicep
# Add bicep to your PATH (requires admin)
sudo mv ./bicep /usr/local/bin/bicep
# Verify you can now access the 'bicep' command
bicep --help
# Done!
```

Refer [this](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#macos) article for more details.

**Comment by navba-MSFT** [comment]
@lhotrifork I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@lhotrifork The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
