### ISSUE TITLE
az login throws an error

### ISSUE THREAD

**Issue by Yakuza-UA** [Azure/azure-cli#23805]
## Describe the bug

`az login --use-device-code` throws an error after timeout. Once executed it halts for a while with no visible progress, then exists with the error below.

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 148, in login_with_device_code
    flow = self._msal_app.initiate_device_flow(scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1641, in initiate_device_flow
    flow = self.client.initiate_device_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 328, in initiate_device_flow
    flow = json.loads(resp.text)
  File "/opt/az/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Linux-4.15.0-20-generic-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0

Extensions:
azure-firewall 0.14.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/38001a4d087e5d3ec9b77f4096d52d76ab359c46/msal/oauth2cli/oauth2.py#L323-L327

```py
        resp = self._http_client.post(self.configuration[DAE],
            data={"client_id": self.client_id, "scope": self._stringify(scope or [])},
            headers=dict(self.default_headers, **kwargs.pop("headers", {})),
            **kwargs)
        flow = json.loads(resp.text)
```

@rayluo, looks like `resp.text` is empty. How can it be?

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/issues/23805

**Comment by rayluo** [comment]
> https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/38001a4d087e5d3ec9b77f4096d52d76ab359c46/msal/oauth2cli/oauth2.py#L323-L327
> 
> ```python
>         resp = self._http_client.post(self.configuration[DAE],
>             data={"client_id": self.client_id, "scope": self._stringify(scope or [])},
>             headers=dict(self.default_headers, **kwargs.pop("headers", {})),
>             **kwargs)
>         flow = json.loads(resp.text)
> ```
> 
> @rayluo, looks like `resp.text` is empty. How can it be?

If this is reproducible, we will need to inform the service team.
