### ISSUE TITLE
"az cosmodb create" command failed with Periodic backup policy 

### ISSUE THREAD

**Issue by gmns-mgl** [Azure/azure-cli#23806]
> ### `az cosmodb create` failed with option --backup-policy-type Periodic as of CLI version 2.40.0

**Related command**
```powershell
$backupPolicy="Periodic"
az cosmosdb create --name $dbName --resource-group $resourceGroup `
        --backup-policy-type $backupPolicy `
        --default-consistency-level Session `
        --kind MongoDB --server-version 4.2
```

**Describe the bug**
I get the error:
```
The command failed with an unexpected error. Here is the traceback:
local variable 'periodic_mode_properties' referenced before assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cosmosdb/custom.py", line 146, in cli_cosmosdb_create 
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cosmosdb/custom.py", line 276, in _create_database_account
UnboundLocalError: local variable 'periodic_mode_properties' referenced before assignment
```
However, everything works fine with "Continuous" backup policy and if I specify `--backup-retention 24 --backup-interval 720`

**Expected behavior**
It should work even without retention and interval (with default values)? Or at least the documentation should tell they are mandatory in case of periodic backup as well as the command when only policy is specified.

**Environment summary**
Powershell script under Windows OS

**Comment by RakeshMohanMSFT** [comment]
@gmns-mgl Thank you for reaching out, we are looking into it.

**Comment by gmns-mgl** [comment]
> @gmns-mgl Thank you for reaching out, we are looking into it. Can you please share your environment details with us? using az --version
Of course!
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
