### ISSUE TITLE
si o no

### ISSUE THREAD

**Issue by luisadanmunoz** [Azure/azure-cli#23818]
## Describe the bug

**Command Name**
`az devops login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azext_devops.dev.team.credentials#credential_set' is invalid.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\605858105\.azure\cliextensions\azure-devops\azext_devops\dev\team\credentials.py", line 15, in <module>
    from azext_devops.dev.common._credentials import clear_credential, set_credential
  File "C:\Users\605858105\.azure\cliextensions\azure-devops\azext_devops\dev\common\_credentials.py", line 10, in <module>
    from .credential_store import CredentialStore
  File "C:\Users\605858105\.azure\cliextensions\azure-devops\azext_devops\dev\common\credential_store.py", line 11, in <module>
    from .config import AZ_DEVOPS_GLOBAL_CONFIG_DIR
  File "C:\Users\605858105\.azure\cliextensions\azure-devops\azext_devops\dev\common\config.py", line 37, in <module>
    azdevops_config.config_parser.read(AZ_DEVOPS_GLOBAL_CONFIG_PATH)
  File "configparser.py", line 698, in read
  File "configparser.py", line 1021, in _read
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 94: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 515, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
ValueError: The operation 'azext_devops.dev.team.credentials#credential_set' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0 *

Extensions:
account 0.2.3
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@luisadanmunoz Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@luisadanmunoz I think it's a platform issue related to the unique combination Windows + Python.

Could you please try to update the Windows system language setting as shown below ?

Control panel -> Clock and Region -> Region -> Administrative -> Change system locale -> Check Beta: Use Unicode UTF-8 for worldwide language support.

![image](https://user-images.githubusercontent.com/57353862/189279592-d3075070-4367-40a5-9d73-53b46a38aace.png)

The change will require reboot. Please let me know if you still face the same issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@luisadanmunoz I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@luisadanmunoz The action is pending on you to try the above action plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
