### ISSUE TITLE
Error while attempting to download Bicep CLI in Azure DevOps pipeline

### ISSUE THREAD

**Issue by alextouli** [Azure/azure-cli#23811]
One of the steps in my pipeline calls Azure CLI in order to deploy infrastructure defined in a bicep file. The following command is executed 
 `az deployment group create [parameters] --template-file foo.bicep`

After which, the following error is thrown
`ERROR: Error while attempting to download Bicep CLI: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>`

**Comment by bengavin** [comment]
We're seeing the same issue, DevOps hosted agents can't seem to get to the Azure CLI endpoints.  This was working earlier this AM.

**Comment by bengavin** [comment]
@alextouli if it helps, a workaround seems to be to add a new task to our build that executes 'az bicep upgrade --debug --verbose' (was hoping to get more detailed error info, but it just started working after this).

**Comment by alextouli** [comment]
@bengavin I tried out the workaround, but it doesn't seem to solve the issue. In fact, even before I tried the workaround, the pipeline was working haphazardly (like 1 out of 3 tries)

**Comment by bengavin** [comment]
`2022-09-07T19:03:14.1886736Z ##[section]Starting: Ensure BICEP tooling for build
2022-09-07T19:03:14.1893612Z ==============================================================================
2022-09-07T19:03:14.1893884Z Task         : Command line
2022-09-07T19:03:14.1894184Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-09-07T19:03:14.1894465Z Version      : 2.201.1
2022-09-07T19:03:14.1894658Z Author       : Microsoft Corporation
2022-09-07T19:03:14.1894966Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-09-07T19:03:14.1895321Z ==============================================================================
2022-09-07T19:03:14.3176681Z Generating script.
2022-09-07T19:03:14.3184929Z Script contents:
2022-09-07T19:03:14.3186586Z az bicep upgrade --debug --verbose
2022-09-07T19:03:14.3186984Z ========================== Starting Command Output ===========================
2022-09-07T19:03:14.3206420Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/73182c6f-5038-49ed-b0ea-987ee973c58e.sh
2022-09-07T19:03:16.4297708Z DEBUG: cli.knack.cli: Command arguments: ['bicep', 'upgrade', '--debug', '--verbose']
2022-09-07T19:03:16.4298916Z DEBUG: cli.knack.cli: __init__ debug log:
2022-09-07T19:03:16.4299424Z Cannot enable color.
2022-09-07T19:03:16.4300243Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2022-09-07T19:03:16.4307879Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fcb0c58bbe0>, <function OutputProducer.on_global_arguments at 0x7fcb0c2e44c0>, <function CLIQuery.on_global_arguments at 0x7fcb0c3196c0>]
2022-09-07T19:03:16.4541704Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2022-09-07T19:03:16.4553577Z DEBUG: cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
2022-09-07T19:03:16.4562081Z DEBUG: cli.azure.cli.core: Command index has been invalidated.
2022-09-07T19:03:16.4564271Z DEBUG: cli.azure.cli.core: No module found from index for '['bicep', 'upgrade', '--debug', '--verbose']'
2022-09-07T19:03:16.4565117Z DEBUG: cli.azure.cli.core: Loading all modules and extensions
2022-09-07T19:03:16.4727414Z DEBUG: cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
2022-09-07T19:03:16.4729784Z DEBUG: cli.azure.cli.core: Loading command modules:
2022-09-07T19:03:16.4730385Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2022-09-07T19:03:16.4832153Z DEBUG: cli.azure.cli.core: acr                       0.011        30       126
2022-09-07T19:03:16.6122571Z DEBUG: cli.azure.cli.core: acs                       0.129         8        58
2022-09-07T19:03:16.6142851Z DEBUG: cli.azure.cli.core: advisor                   0.002         3         6
2022-09-07T19:03:16.6206817Z DEBUG: cli.azure.cli.core: ams                       0.006        22       100
2022-09-07T19:03:16.6288146Z DEBUG: cli.azure.cli.core: apim                      0.008        11        60
2022-09-07T19:03:16.6325197Z DEBUG: cli.azure.cli.core: appconfig                 0.004         7        37
2022-09-07T19:03:16.6492924Z DEBUG: cli.azure.cli.core: appservice                0.017        68       245
2022-09-07T19:03:16.6562519Z DEBUG: cli.azure.cli.core: aro                       0.007         1         7
2022-09-07T19:03:16.6612210Z DEBUG: cli.azure.cli.core: backup                    0.005        16        58
2022-09-07T19:03:16.7057404Z DEBUG: cli.azure.cli.core: batch                     0.044        36       104
2022-09-07T19:03:16.7091626Z DEBUG: cli.azure.cli.core: batchai                   0.004        10        30
2022-09-07T19:03:16.7166326Z DEBUG: cli.azure.cli.core: billing                   0.007        19        52
2022-09-07T19:03:16.7202787Z DEBUG: cli.azure.cli.core: botservice                0.004        12        42
2022-09-07T19:03:16.7269469Z DEBUG: cli.azure.cli.core: cdn                       0.007        39       133
2022-09-07T19:03:16.7288923Z DEBUG: cli.azure.cli.core: cloud                     0.002         1         7
2022-09-07T19:03:16.7312968Z DEBUG: cli.azure.cli.core: cognitiveservices         0.002         8        31
2022-09-07T19:03:16.7331279Z DEBUG: cli.azure.cli.core: config                    0.002         2         7
2022-09-07T19:03:16.7343981Z DEBUG: cli.azure.cli.core: configure                 0.001         2         5
2022-09-07T19:03:16.7371027Z DEBUG: cli.azure.cli.core: consumption               0.003         8         9
2022-09-07T19:03:16.7392016Z DEBUG: cli.azure.cli.core: container                 0.002         1        11
2022-09-07T19:03:16.7494353Z DEBUG: cli.azure.cli.core: cosmosdb                  0.010        47       167
2022-09-07T19:03:16.7542672Z DEBUG: cli.azure.cli.core: databoxedge               0.005         5        27
2022-09-07T19:03:16.7566315Z DEBUG: cli.azure.cli.core: deploymentmanager         0.002         7        30
2022-09-07T19:03:16.7609668Z DEBUG: cli.azure.cli.core: dla                       0.004        23        62
2022-09-07T19:03:16.7641596Z DEBUG: cli.azure.cli.core: dls                       0.003         7        41
2022-09-07T19:03:16.7665635Z DEBUG: cli.azure.cli.core: dms                       0.002         3        22
2022-09-07T19:03:16.7717299Z DEBUG: cli.azure.cli.core: eventgrid                 0.005        25        96
2022-09-07T19:03:16.7763959Z DEBUG: cli.azure.cli.core: eventhubs                 0.005        21        73
2022-09-07T19:03:16.7775997Z DEBUG: cli.azure.cli.core: extension                 0.001         1         7
2022-09-07T19:03:16.7784987Z DEBUG: cli.azure.cli.core: feedback                  0.001         1         1
2022-09-07T19:03:16.7795877Z DEBUG: cli.azure.cli.core: find                      0.001         1         1
2022-09-07T19:03:16.7822026Z DEBUG: cli.azure.cli.core: hdinsight                 0.003         8        39
2022-09-07T19:03:16.7841602Z DEBUG: cli.azure.cli.core: identity                  0.002         1         6
2022-09-07T19:03:16.7846835Z DEBUG: cli.azure.cli.core: interactive               0.000         1         1
2022-09-07T19:03:16.8685539Z DEBUG: cli.azure.cli.core: iot                       0.083        19        81
2022-09-07T19:03:16.8773764Z DEBUG: cli.azure.cli.core: keyvault                  0.009        20       122
2022-09-07T19:03:16.8797474Z DEBUG: cli.azure.cli.core: kusto                     0.002         3        14
2022-09-07T19:03:16.8831238Z DEBUG: cli.azure.cli.core: lab                       0.003        11        34
2022-09-07T19:03:16.8849499Z DEBUG: cli.azure.cli.core: managedservices           0.002         3         8
2022-09-07T19:03:16.8868294Z DEBUG: cli.azure.cli.core: maps                      0.002         5        13
2022-09-07T19:03:16.8900349Z DEBUG: cli.azure.cli.core: marketplaceordering       0.003         1         2
2022-09-07T19:03:16.9139531Z DEBUG: cli.azure.cli.core: monitor                   0.024        32       123
2022-09-07T19:03:16.9156139Z DEBUG: cli.azure.cli.core: natgateway                0.002         3         6
2022-09-07T19:03:16.9208935Z DEBUG: cli.azure.cli.core: netappfiles               0.005        16        86
2022-09-07T19:03:16.9868461Z DEBUG: cli.azure.cli.core: network                   0.065       143       660
2022-09-07T19:03:16.9895796Z DEBUG: cli.azure.cli.core: policyinsights            0.003         6        12
2022-09-07T19:03:16.9951953Z DEBUG: cli.azure.cli.core: privatedns                0.005        14        66
2022-09-07T19:03:16.9972944Z DEBUG: cli.azure.cli.core: profile                   0.002         2         9
2022-09-07T19:03:17.1075054Z DEBUG: cli.azure.cli.core: rdbms                     0.110        47       201
2022-09-07T19:03:17.1101979Z DEBUG: cli.azure.cli.core: redis                     0.003         5        27
2022-09-07T19:03:17.1135451Z DEBUG: cli.azure.cli.core: relay                     0.003        10        37
2022-09-07T19:03:17.1159031Z DEBUG: cli.azure.cli.core: reservations              0.002         5        12
2022-09-07T19:03:17.1276405Z DEBUG: cli.azure.cli.core: resource                  0.012        47       207
2022-09-07T19:03:17.1311596Z DEBUG: cli.azure.cli.core: role                      0.003        17        61
2022-09-07T19:03:17.1334859Z DEBUG: cli.azure.cli.core: search                    0.002         7        22
2022-09-07T19:03:17.1405667Z DEBUG: cli.azure.cli.core: security                  0.007        46       102
2022-09-07T19:03:17.1466859Z DEBUG: cli.azure.cli.core: servicebus                0.006        21        74
2022-09-07T19:03:17.1643950Z DEBUG: cli.azure.cli.core: serviceconnector          0.018         4        53
2022-09-07T19:03:17.1694952Z DEBUG: cli.azure.cli.core: servicefabric             0.005        26        75
2022-09-07T19:03:17.1721443Z DEBUG: cli.azure.cli.core: signalr                   0.003         6        20
2022-09-07T19:03:17.1835242Z DEBUG: cli.azure.cli.core: sql                       0.011        45       179
2022-09-07T19:03:17.2595170Z DEBUG: cli.azure.cli.core: sqlvm                     0.076         4        18
2022-09-07T19:03:17.3049792Z DEBUG: cli.azure.cli.core: storage                   0.045        56       261
2022-09-07T19:03:17.3220233Z DEBUG: cli.azure.cli.core: synapse                   0.017        54       246
2022-09-07T19:03:17.3234751Z DEBUG: cli.azure.cli.core: util                      0.002         3         6
2022-09-07T19:03:17.3397197Z DEBUG: cli.azure.cli.core: vm                        0.016        56       292
2022-09-07T19:03:17.3398009Z DEBUG: cli.azure.cli.core: Total (66)                0.861      1192      4830
2022-09-07T19:03:17.3405315Z DEBUG: cli.azure.cli.core: Loading extensions:
2022-09-07T19:03:17.3407100Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
2022-09-07T19:03:17.4707196Z DEBUG: cli.azure.cli.core: azure-devops              0.129        60       191  /opt/az/azcliextensions/azure-devops
2022-09-07T19:03:17.4708211Z DEBUG: cli.azure.cli.core: Total (1)                 0.129        60       191  
2022-09-07T19:03:17.4709441Z DEBUG: cli.azure.cli.core: Loaded 1241 groups, 5021 commands.
2022-09-07T19:03:17.4766321Z DEBUG: cli.azure.cli.core: Updated command index in 0.005 seconds.
2022-09-07T19:03:17.4767139Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fcb0b9ef400>]
2022-09-07T19:03:17.4779676Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/vsts/.azure/commands/2022-09-07.19-03-17.bicep_upgrade.1608.log'.
2022-09-07T19:03:17.4786728Z INFO: az_command_data_logger: command args: bicep upgrade --debug --verbose
2022-09-07T19:03:17.4796759Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fcb0b8ef520>]
2022-09-07T19:03:17.6221123Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2022-09-07T19:03:17.6222669Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fcb0b8ef490>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fcb0b49c5e0>]
2022-09-07T19:03:17.6232149Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2022-09-07T19:03:17.6233393Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fcb0a774d30>]
2022-09-07T19:03:17.6238019Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fcb0c2e4550>, <function CLIQuery.handle_query_parameter at 0x7fcb0c319750>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fcb0b852c20>, <function handler at 0x7fcb0a524dc0>, <function DevCommandsLoader.post_parse_args at 0x7fcb0ae5e680>]
2022-09-07T19:03:17.6277492Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
2022-09-07T19:03:17.8985995Z DEBUG: urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
2022-09-07T19:03:17.9038627Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): api.github.com:443
2022-09-07T19:03:17.9365252Z DEBUG: urllib3.connectionpool: https://api.github.com:443 "GET /repos/Azure/bicep/releases/latest HTTP/1.1" 200 2680
2022-09-07T19:09:14.4061632Z DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
2022-09-07T19:09:14.5891113Z DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
2022-09-07T19:09:14.5891767Z   File "/opt/az/lib/python3.10/urllib/request.py", line 1348, in do_open
2022-09-07T19:09:14.5895932Z     h.request(req.get_method(), req.selector, req.data, headers,
2022-09-07T19:09:14.5897148Z   File "/opt/az/lib/python3.10/http/client.py", line 1282, in request
2022-09-07T19:09:14.5897694Z     self._send_request(method, url, body, headers, encode_chunked)
2022-09-07T19:09:14.5898235Z   File "/opt/az/lib/python3.10/http/client.py", line 1328, in _send_request
2022-09-07T19:09:14.5898786Z     self.endheaders(body, encode_chunked=encode_chunked)
2022-09-07T19:09:14.5899301Z   File "/opt/az/lib/python3.10/http/client.py", line 1277, in endheaders
2022-09-07T19:09:14.5900031Z     self._send_output(message_body, encode_chunked=encode_chunked)
2022-09-07T19:09:14.5900559Z   File "/opt/az/lib/python3.10/http/client.py", line 1037, in _send_output
2022-09-07T19:09:14.5901008Z     self.send(msg)
2022-09-07T19:09:14.5901432Z   File "/opt/az/lib/python3.10/http/client.py", line 975, in send
2022-09-07T19:09:14.5901846Z     self.connect()
2022-09-07T19:09:14.5902275Z   File "/opt/az/lib/python3.10/http/client.py", line 1454, in connect
2022-09-07T19:09:14.5902773Z     self.sock = self._context.wrap_socket(self.sock,
2022-09-07T19:09:14.5903261Z   File "/opt/az/lib/python3.10/ssl.py", line 513, in wrap_socket
2022-09-07T19:09:14.5903724Z     return self.sslsocket_class._create(
2022-09-07T19:09:14.5904188Z   File "/opt/az/lib/python3.10/ssl.py", line 1071, in _create
2022-09-07T19:09:14.5904597Z     self.do_handshake()
2022-09-07T19:09:14.5905035Z   File "/opt/az/lib/python3.10/ssl.py", line 1342, in do_handshake
2022-09-07T19:09:14.5905716Z     self._sslobj.do_handshake()
2022-09-07T19:09:14.5906161Z ConnectionResetError: [Errno 104] Connection reset by peer
2022-09-07T19:09:14.5906390Z 
2022-09-07T19:09:14.5907023Z During handling of the above exception, another exception occurred:
2022-09-07T19:09:14.5907291Z 
2022-09-07T19:09:14.5907605Z Traceback (most recent call last):
2022-09-07T19:09:14.5909030Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 113, in ensure_bicep_installation
2022-09-07T19:09:14.5909775Z     request = urlopen(_get_bicep_download_url(system, release_tag, target_platform=target_platform))
2022-09-07T19:09:14.5910388Z   File "/opt/az/lib/python3.10/urllib/request.py", line 216, in urlopen
2022-09-07T19:09:14.5910871Z     return opener.open(url, data, timeout)
2022-09-07T19:09:14.5911360Z   File "/opt/az/lib/python3.10/urllib/request.py", line 519, in open
2022-09-07T19:09:14.5911819Z     response = self._open(req, data)
2022-09-07T19:09:14.5912416Z   File "/opt/az/lib/python3.10/urllib/request.py", line 536, in _open
2022-09-07T19:09:14.5912952Z     result = self._call_chain(self.handle_open, protocol, protocol +
2022-09-07T19:09:14.5913734Z   File "/opt/az/lib/python3.10/urllib/request.py", line 496, in _call_chain
2022-09-07T19:09:14.5914180Z     result = func(*args)
2022-09-07T19:09:14.5914619Z   File "/opt/az/lib/python3.10/urllib/request.py", line 1391, in https_open
2022-09-07T19:09:14.5915144Z     return self.do_open(http.client.HTTPSConnection, req,
2022-09-07T19:09:14.5915665Z   File "/opt/az/lib/python3.10/urllib/request.py", line 1351, in do_open
2022-09-07T19:09:14.5916105Z     raise URLError(err)
2022-09-07T19:09:14.5916557Z urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
2022-09-07T19:09:14.5916811Z 
2022-09-07T19:09:14.5917324Z During handling of the above exception, another exception occurred:
2022-09-07T19:09:14.5917577Z 
2022-09-07T19:09:14.5917888Z Traceback (most recent call last):
2022-09-07T19:09:14.5918638Z   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
2022-09-07T19:09:14.5919152Z     cmd_result = self.invocation.execute(args)
2022-09-07T19:09:14.5919937Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
2022-09-07T19:09:14.5920424Z     raise ex
2022-09-07T19:09:14.5921324Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2022-09-07T19:09:14.5921937Z     results.append(self._run_job(expanded_arg, cmd_copy))
2022-09-07T19:09:14.5922735Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
2022-09-07T19:09:14.5923256Z     result = cmd_copy(params)
2022-09-07T19:09:14.5923985Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
2022-09-07T19:09:14.5924540Z     return self.handler(*args, **kwargs)
2022-09-07T19:09:14.5925325Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2022-09-07T19:09:14.5925866Z     return op(**command_args)
2022-09-07T19:09:14.5926663Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3672, in upgrade_bicep_cli
2022-09-07T19:09:14.5927376Z     ensure_bicep_installation(release_tag=latest_release_tag, target_platform=target_platform)
2022-09-07T19:09:14.5928334Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 127, in ensure_bicep_installation
2022-09-07T19:09:14.5929022Z     raise ClientRequestError(f"Error while attempting to download Bicep CLI: {err}")
2022-09-07T19:09:14.5929732Z azure.cli.core.azclierror.ClientRequestError: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
2022-09-07T19:09:14.5930136Z 
2022-09-07T19:09:14.5995473Z ERROR: cli.azure.cli.core.azclierror: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
2022-09-07T19:09:14.5996200Z ERROR: az_command_data_logger: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
2022-09-07T19:09:14.5996872Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcb0b9ef640>]
2022-09-07T19:09:14.5997391Z INFO: az_command_data_logger: exit code: 1
2022-09-07T19:09:14.5998056Z INFO: cli.__main__: Command ran in 358.710 seconds (init: 0.539, invoke: 358.171)
2022-09-07T19:09:14.6168135Z INFO: telemetry.save: Save telemetry record of length 2946 in cache
2022-09-07T19:09:14.6168987Z INFO: telemetry.check: Positive: The /home/vsts/.azure/telemetry.txt does not exist.
2022-09-07T19:09:14.6169617Z INFO: telemetry.main: Begin creating telemetry upload process.
2022-09-07T19:09:14.6171628Z INFO: telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/vsts/.azure"
2022-09-07T19:09:14.6178714Z INFO: telemetry.process: Return from creating process
2022-09-07T19:09:14.6181906Z INFO: telemetry.main: Finish creating telemetry upload process.
2022-09-07T19:09:14.6187193Z Installing Bicep CLI v0.9.1...
2022-09-07T19:09:14.7625049Z ##[error]Bash exited with code '1'.
2022-09-07T19:09:14.7676377Z ##[section]Finishing: Ensure BICEP tooling for build`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by JamiePan** [comment]
Hello, Dear Microsoft Team. 
Just wonder the bicep-cli is fixed? or how is the progress now?
I need to install the bicep-cli in Azure DevOps, but this bug still is in pending...
Need your support very urgently!

Appreciate your helps and efforts very much!

Jamie
