### ISSUE TITLE
Azure CLI: API version 2022-05-01 does not have operation group 'storage_accounts'

### ISSUE THREAD

**Issue by qTipTip** [Azure/azure-cli#23821]
Hello!

## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:f56786d2-c01e-004b-5a6d-c38f55000000
Time:2022-09-08T10:25:19.9002276Z
ErrorCode:NoAuthenticationInformation

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --service-principal --username {} --tenant {} --password {}`
- `az storage blob upload -f {} -c {} -n {} --account-name {} --subscription {} --auth-mode key`

## Expected Behavior

That the storage blob uploads successfully. 

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-debian-10.12, Debian GNU/Linux 10 (buster)
Python 3.7.14
Installer: PIP

azure-cli 2.40.0
```
## Additional Context

We had to upgrade from `azure-cli` version 2.36 to `azure-cli` version 2.40 due to a regression bug. We are now experiencing the aforementioned error and this is directly impacting our users. The CLI is authenticated using a service principal and has previously worked.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by andrescodas** [comment]
I'm facing the same issue.  Is there any fix?

**Comment by andrescodas** [comment]
The point is that I'm using az-cli to get the key.  Here is what I see:

```bash
$ az storage account keys list --account-name "${STORAGE_NAME}" --subscription "${SUBSCRIPTION_NAME}"
Auto upgrade failed. name 'exit_code' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.storage.v2022_05_01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/__main__.py", line 49, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/azure/cli/__main__.py", line 36, in cli_main
    return cli.invoke(args)
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 243, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 127, in exception_handler
    return handle_exception(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/util.py", line 64, in handle_exception
    from msal_extensions.persistence import PersistenceError
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/usr/local/lib/python3.8/site-packages/msal_extensions/persistence.py)
$ az --version
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
azure-cli-ml                      1.41.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/bin/python'
Extensions directory '/home/andrescodas/.azure/cliextensions'

Python (Linux) 3.8.13 (default, May 28 2022, 14:23:53) 
[GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date
```

**Comment by andrescodas** [comment]
Hi @evelyn-ys 

This is how I installed az-cli:
```bash
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
```
this is how I attempt to updated it:

```bash
$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.40.0
Upgrading extensions
Checking update for storage-preview
Latest version of 'storage-preview' is already installed.

Use --debug for more information
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
$ az storage account keys list --account-name "${STORAGE_NAME}" --subscription "${SUBSCRIPTION_NAME}"
Auto upgrade failed. name 'exit_code' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.8/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.storage.v2022_05_01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/__main__.py", line 49, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/azure/cli/__main__.py", line 36, in cli_main
    return cli.invoke(args)
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 243, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 127, in exception_handler
    return handle_exception(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/util.py", line 64, in handle_exception
    from msal_extensions.persistence import PersistenceError
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/usr/local/lib/python3.8/site-packages/msal_extensions/persistence.py)
```

Can you send the specific updates I need to use to update?  I use a linux-debian environment

**Comment by andrescodas** [comment]
I think I found the issue.  There is a conflict with other packages I install:

```bash
python -m pip install --no-cache-dir --upgrade pip \
 && python -m pip install --no-cache-dir --upgrade "azure-ml-component[notebooks]" \
 && python -m pip install --no-cache-dir --upgrade azureml-dataset-runtime[fuse] \
 && az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/componentsdk/azure_cli_ml-0.9.13-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/componentsdk/0.9.13 --yes --verbose
```

After installing these, I start seeing the error above

**Comment by evelyn-ys** [comment]
Sounds like known issue of `ml` extension conflict. @jiasli may have more knowledge

**Comment by jiasli** [comment]
`https://aka.ms/InstallAzureCLIDeb` installs Azure CLI DEB package at `/opt/az`, but your Azure CLI was installed with `pip` judging by the installation location:

```
/usr/local/lib/python3.8/site-packages/azure/cli
```

We recommend installing the Azure CLI DEB package, but if you have to use `pip`, we recommend installing to a virtual environment. See https://github.com/Azure/azure-cli/issues/20476#issuecomment-1007131837.

Please be aware that installing from `pip` is not officially supported.

**Comment by johnathon-b** [comment]
> `https://aka.ms/InstallAzureCLIDeb` installs Azure CLI DEB package at `/opt/az`, but your Azure CLI was installed with `pip` judging by the installation location:
> 
> ```
> /usr/local/lib/python3.8/site-packages/azure/cli
> ```
> 
> We recommend installing the Azure CLI DEB package, but if you have to use `pip`, we recommend installing to a virtual environment. See [#20476 (comment)](https://github.com/Azure/azure-cli/issues/20476#issuecomment-1007131837).
> 
> Please be aware that installing from `pip` is not officially supported.

This same error is happening for `az storage` on Microsoft hosted build agents.. We don't control how the az cli is installed. Updating the cli to latest doesn't fix the issue.

This broke a lot of our pipelines this week. 

```
WARNING: 
There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
```
WARNING: 
Skip querying account key due to failure: Storage account 'DataPlanesoguiadt' not found.
ERROR: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bddd40d6-901e-000d-3c0c-3cbab2000000
Time:2023-02-08T22:28:36.1235041Z
ErrorCode:NoAuthenticationInformation

```

**Comment by johnathon-b** [comment]
Azure DevOps Task:
```
Starting: Deploy Client Files
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.216.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
WARNING: You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.44.1 *

core                              2.44.1 *
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Jan 10 2023, 15:48:33) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Setting AZURE_CONFIG_DIR env variable to: /opt/azdo/_work/_temp/.azclitask

```
