### ISSUE TITLE
API version 2022-03-01 does not have operation group 'web_apps'

### ISSUE THREAD

**Issue by krisek** [Azure/azure-cli#23848]
## Describe the bug
No `az webapp` commands work with the current version of the `az` command.

**Command Name**
`az webapp list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-03-01 does not have operation group 'web_apps'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/appservice/custom.py", line 967, in list_webapp
    full_list = _list_app(cmd.cli_ctx, resource_group_name)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/appservice/custom.py", line 1006, in _list_app
    result = list(client.web_apps.list())
  File "/usr/lib/python3/dist-packages/azure/mgmt/web/_web_site_management_client.py", line 804, in web_apps
    raise ValueError("API version {} does not have operation group 'web_apps'".format(api_version))
ValueError: API version 2022-03-01 does not have operation group 'web_apps'

```

## To Reproduce:

- `az webapp list -o {}`

## Expected Behavior

The webapp list is returned. 

## Environment Summary
```
Linux-5.10.131-19114-g6651b07c6153-x86_64-with-glibc2.34, Debian GNU/Linux bookworm/sid
Python 3.10.6
Installer: DEB

azure-cli 2.40.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
@krisek thanks for reporting but I wasn't able to repro this with the latest version. I used https://shell.azure.com to verify.
If this is your local CLI - can you try to  run az upgrade & re-try the command.

**Comment by krisek** [comment]
Thanks for the feedback, I used the the debian installer script.

It worked now with the generic CLI installer.

**Comment by RakeshMohanMSFT** [comment]
@krisek Glad it worked. Closing the thread now.
