### ISSUE TITLE
Not able to create subnet using az cli

### ISSUE THREAD

**Issue by Ravi-9654** [Azure/azure-cli#23861]
## Describe the bug

**Command Name**
`az network vnet subnet create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/command_modules/network/custom.py", line 6743, in create_subnet
    return get_property(vnet.subnets, subnet_name)
  File "/home/azureuser/lib/azure-cli/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 490, in get_property
    result = next((x for x in items if x.name.lower() == name.lower()), None)
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet subnet create -g {} --vnet-name {} -n {} --address-prefixes {}`

## Environment Summary
```
Linux-4.4.140-96.80.TDC-default-x86_64-with-glibc2.17, SUSE Linux Enterprise Server 12 SP3
Python 3.8.12
Installer: 

azure-cli 2.32.0 *
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@Ravi-9654 Sorry, I cannot reproduce your case, my detailed procedures are as follows:
1. az network vnet create -n ethan-vn -g ethan-rg
2. az network vnet subnet create -n ethan-sn -g ethan-rg --vnet-name ethan-vn --address-prefixes 10.0.0.0/24

**Comment by navba-MSFT** [comment]
@Ravi-9654 The action is currently pending on you to try the [above suggestion](https://github.com/Azure/azure-cli/issues/23861#issuecomment-1246148703). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
