### ISSUE TITLE
azure-cli not working - opensuse or debian

### ISSUE THREAD

**Issue by tern015** [Azure/azure-cli#23882]
## Describe the bug

**Command Name**
`az network vnet create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/network/__init__.py", line 50, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/network/_params.py", line 135, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get

**Comment by tern015** [comment]
Removed all dependencies and let azure-cli install all python3 dependencies. Still not working.

**Comment by tern015** [comment]
Downgraded from 2.39 to 2.32. Still not working. Microsoft at its best xD

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@tern015 Could you please provide the input parameters as well?

As the following command (with 2 parameters) is working:
```
az network vnet create -n {} -g {}
```
