### ISSUE TITLE
az aro failed by 'Insufficient privileges to complete the operation'

### ISSUE THREAD

**Issue by MayXuQQ** [Azure/azure-cli#23892]
## Describe the bug

**Command Name**
`az aro create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/util.py", line 993, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2022-09-14T16:04:00","request-id":"daab7cfa-14e8-4d69-ae5c-a9eab9f571b9","client-request-id":"daab7cfa-14e8-4d69-ae5c-a9eab9f571b9"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/command_modules/aro/custom.py", line 78, in aro_create
    client_id, client_secret = aad.create_application(cluster_resource_group or 'aro-' + random_id)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/command_modules/aro/_aad.py", line 24, in create_application
    app = self.client.application_create(request_body)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 91, in application_create
    result = self._send("POST", "/applications", body=body)
  File "/home/fedora/.local/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aro create --resource-group {} --name {} --vnet {} --master-subnet {} --worker-subnet {} --pull-secret {}`

## Environment Summary
```
Linux-5.15.16-200.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Cloud Edition)
Python 3.10.4
Installer: PIP

azure-cli 2.40.0
```

**Comment by mgahagan73** [comment]
This attempt was with using a Service Principal with the "Cloud Application Administrator" AAD role assigned to it. This worked until az-cli 2.38.0 was released. Any idea if this role was depreciated or  similar when az-cli got moved to the Azure Graph API? User accounts with the "Application Developer" AAD role can still create aro clusters in our environment. We need to be able to build aro clusters using a service principal for automated testing purposes.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MayXuQQ** [comment]
how about the progress of this issue ? thanks

**Comment by MayXuQQ** [comment]
whether has progress of this issue ?

**Comment by navba-MSFT** [comment]
@MayXuQQ Apologies for the late reply. Thanks for reaching out to us and reporting this issue. As per [this ](https://learn.microsoft.com/en-us/azure/openshift/tutorial-create-cluster)article the below permissions are required:

>You must have either Contributor and User Access Administrator permissions, or Owner permissions, either directly on the virtual network, or on the resource group or subscription containing it.

>
>You will also need sufficient Azure Active Directory permissions (either a member user of the tenant, or a guest user assigned with role Application administrator) for the tooling to create an application and service principal on your behalf for the cluster. See [Member and guest users](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/users-default-permissions#member-and-guest-users) and [Assign administrator and non-administrator roles to users with Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal) for more details.

Hope this helps.

**Comment by navba-MSFT** [comment]
@MayXuQQ Thanks for the update.
