### ISSUE TITLE
az storage account keys renew appears to require --resource-group

### ISSUE THREAD

**Issue by aolszowka** [Azure/azure-cli#23893]
## Describe the bug
Attempting to run is command without specifying the optional `--resource-group` fails.

This command indicates that `--resource-group` is optional as per the documentation here: https://docs.microsoft.com/en-us/cli/azure/storage/account/keys?view=azure-cli-latest#az-storage-account-keys-renew

**Command Name**
`az storage account keys renew`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/account.py", line 27, in regenerate_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 1386, in regenerate_key
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 362, in build_regenerate_key_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 652, in url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 760, in serialize_data
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account keys renew --account-name {REDACTED} --key secondary`

Its unclear if this happens with the `--key primary` argument (as this was not tested) but is reproducible with `--key secondary` for sure.

## Expected Behavior
I would expect the secondary storage key to be rotated for the given account name.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
When the `--resource-group` parameter is provided this command works as expected and is a work around for now.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by RakeshMohanMSFT** [comment]
@aolszowka Thank you for reaching out, we are looking into it.

**Comment by navba-MSFT** [comment]
@aolszowka If you would like to run the command without specifying the resource group set the `config` as shown below:

> **az config set defaults.group=myRGName**

> az storage account keys renew --account-name MyStorageAccountName --key primary
   az storage account keys renew --account-name MyStorageAccountName --key secondary

**Output:**
[
  {
    "creationTime": null,
    "keyName": "key1",
    "permissions": "FULL",
    "value": "JF1bMEJ0IfVVp/BT48zUG******************************kC4vDugc0HXuzaw=="
  },
  {
    "creationTime": "2022-10-18T07:13:22.377876+00:00",
    "keyName": "key2",
    "permissions": "FULL",
    "value": "8qGE49QRU04N**********************4YB+AStwN/Ugg=="
  }
]

Please let us know if that helps.

**Comment by aolszowka** [comment]
Hey @navba-MSFT that's great but that means that the documentation is still incorrect.

`--resource-group` is not optional, unless you have defined a default. That's fine, but should probably be called out in the documentation.

For now I am specifying the `--resource-group` with every command going forward.
