### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by dotina** [Azure/azure-cli#23914]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-02-01-preview does not have operation group 'registries'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/custom.py", line 290, in acr_login
    login_server, username, password = get_login_credentials(
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/_docker_utils.py", line 450, in get_login_credentials
    return _get_credentials(cmd,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/_docker_utils.py", line 337, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/_utils.py", line 111, in get_registry_by_name
    client = cf_acr_registries(cli_ctx)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/_client_factory.py", line 22, in cf_acr_registries
    return get_acr_service_client(cli_ctx, VERSION_2022_02_01_PREVIEW).registries
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerregistry/_container_registry_management_client.py", line 420, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
ValueError: API version 2022-02-01-preview does not have operation group 'registries'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34, Kali GNU/Linux Rolling
Python 3.10.7
Installer: DEB

azure-cli 2.40.0

Extensions:
vm-repair 0.4.3
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by dotina** [comment]
any assistance here

**Comment by SaurabhSharma-MSFT** [comment]
@dotina What version of `azure-mgmt-containerregistry` you are using ? Also, did you install the azure-cli package using [documentaion](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest) ?

**Comment by SaurabhSharma-MSFT** [comment]
@dotina Please let me know if you still are having issues.

**Comment by SaurabhSharma-MSFT** [comment]
@dotina We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by MarcinWronecki** [comment]
I have the same problem. Yes, I installed the azure-cli using documentation.

```
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource               21.0.0

Python location '/usr/bin/python3'
Extensions directory '/home/wronecki/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
