### ISSUE TITLE
"az webapp log download" sometimes fails, often on the first try, but then works on second (or later)

### ISSUE THREAD

**Issue by andreas-nielsen-xlo** [Azure/azure-cli#23945]
## Describe the bug

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection broken: IncompleteRead(823 bytes read)', IncompleteRead(823 bytes read))
Traceback (most recent call last):
  File "http\client.py", line 565, in _get_chunk_left
  File "http\client.py", line 532, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "http\client.py", line 582, in _read_chunked
  File "http\client.py", line 567, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 438, in _error_catcher
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 519, in read
  File "http\client.py", line 459, in read
  File "http\client.py", line 597, in _read_chunked
http.client.IncompleteRead: IncompleteRead(823 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2684, in download_historical_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2716, in _get_log
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 512, in read
  File "contextlib.py", line 153, in __exit__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 455, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(823 bytes read)', IncompleteRead(823 bytes read))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp log download --resource-group {} --name {}`

## Expected Behavior

`Downloaded logs to webapp_logs.zip`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
account 0.2.3
application-insights 0.1.16
interactive 0.4.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1

Ran in Windows Terminal + PowerShell 7.2.6

```
## Additional Context

This fails often, but not always. Today I had to try 6-8 times before it suddenly succeeded with:

`Downloaded logs to webapp_logs.zip`

Has been erratic since I started using `az` for downloading logs months ago.

Often fails on first try, then succeeds on second.

As far as I know I do not have other problems with either internal or external network or the webapps themselves. We have 20+ webapps, they all show the same behaviour.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
@andreas-nielsen-xlo thanks for reporting. Are these Linux apps? If so there is a known issue that the PG team is already investigating. Thanks!

**Comment by andreas-nielsen-xlo** [comment]
> @andreas-nielsen-xlo thanks for reporting. Are these Linux apps? If so there is a known issue that the PG team is already investigating. Thanks!

They are indeed linux-apps, good to know you are working on it.

**Comment by PramodValavala-MSFT** [comment]
@andreas-nielsen-xlo As mentioned, this is being worked upon and the workaround for it is described [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1243185740). Closing this issue since there is no change required in Azure CLI.
