### ISSUE TITLE
AZ CLI for scheduled query returning python error

### ISSUE THREAD

**Issue by snamboothiry** [Azure/azure-cli#23950]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az monitor scheduled-query create -g {{steps.getKeyVault.outputs.azure-resource-group}} -n Excpetion-Log-Alert --scopes {appResourceId} --condition "count 'Placholder_1' > 0" --condition-query "AppServiceConsoleLogs \n| where tolower(ResultDescription) contains \"exception\" and TimeGenerated > ago(30m)" --action-groups {action} --severity 3 --description "Test rule"

**Describe the bug**
While running the above command using github actions , I am getting the below error. 
I had tried using single quotes to escape double quotes , but still getting the same issue:

WARNING: The installed extension 'scheduled-query' is in preview.
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 5[88](https://github.com/AAInternal/Swim-Tfms-Flow/actions/runs/3067764249/jobs/4954415265#step:5:89), in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/local/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/local/lib/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 2050, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/lib/python3.10/argparse.py", line 2027, in consume_positionals
    take_action(action, args)
  File "/usr/local/lib/python3.10/argparse.py", line 1[93](https://github.com/AAInternal/Swim-Tfms-Flow/actions/runs/3067764249/jobs/4954415265#step:5:94)6, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line [121](https://github.com/AAInternal/Swim-Tfms-Flow/actions/runs/3067764249/jobs/4954415265#step:5:122)4, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 2050, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/lib/python3.10/argparse.py", line 2027, in consume_positionals
    take_action(action, args)
  File "/usr/local/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 2050, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/lib/python3.10/argparse.py", line 2027, in consume_positionals
    take_action(action, args)
  File "/usr/local/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 2068, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/lib/python3.10/argparse.py", line 2008, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/azcliextensions/scheduled-query/azext_scheduled_query/_actions.py", line 54, in __call__
    k, v = x.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
To open an issue, please run: 'az feedback'
Error: Error: az cli script failed.
cleaning up container...

**To Reproduce**
Ran the below step using GHA: 
 az monitor scheduled-query create -g {{ steps.getKeyVault.outputs.azure-resource-group }} -n Excpetion-Log-Alert --scopes {appResourceId} --condition "count 'Placholder_1' > 0" --condition-query "AppServiceConsoleLogs \n| where tolower(ResultDescription) contains \"exception\" and TimeGenerated > ago(30m)" --action-groups {action} --severity 3 --description "Test rule"

or Run the below step in azure cli:
az monitor scheduled-query create -g myRG -n Excpetion-Log-Alert --scopes myApp --condition "count 'Placholder_1' > 0" --condition-query "AppServiceConsoleLogs \n| where tolower(ResultDescription) contains \"exception\" and TimeGenerated > ago(30m)" --action-groups myAction} --severity 3 --description "Test rule"

**Expected behavior**
The above commands should create log alert based on the above command

**Environment summary**
az version
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "scheduled-query": "0.5.1"
  }
}

For GHA :
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.39.0

**Additional context**

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by snamboothiry** [comment]
Placeholder was wrongly spelt above

az monitor scheduled-query create -g aa-aot-cae-nonprod-eastus-rg -n Excpetion-Log-Alert --scopes /subscriptions/***/resourceGroups/***/providers/Microsoft.Web/sites/*** --condition "count 'Placeholder_1' > 0" --condition-query "AppServiceConsoleLogs \n| where tolower(ResultDescription) contains '"exception"' and TimeGenerated > ago(30m)" --action-groups /subscriptions/***/resourceGroups/***/providers/microsoft.insights/actionGroups/*** --severity 3 --description "Test rule"

**Comment by snamboothiry** [comment]
Made some changes to the cli to make it work:

 az monitor scheduled-query create -g ${{ steps.getKeyVault.outputs.azure-resource-group }} -n Excpetion-Log-Alert --scopes ${appResourceId} --condition "count 'Placeholder_1' > 0" --condition-query Placeholder_1="AppServiceConsoleLogs | where tolower(ResultDescription) contains '"exception"' and TimeGenerated > ago(30m)" --action-groups ${action} --severity 3 --description "Test rule"
