### ISSUE TITLE
az login --identity throw error __init__() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by emmanuelsomeox** [Azure/azure-cli#23954]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 122, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 244, in login_with_managed_identity
    subscriptions = subscription_finder.find_using_specific_tenant(tenant, msi_creds)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 796, in find_using_specific_tenant
    client = self._create_subscription_client(credential)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 820, in _create_subscription_client
    **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -i`

## Environment Summary
```
Linux-4.18.0-193.65.2.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa, Red Hat Enterprise Linux 8.2 (Ootpa)
Python 3.6.8
Installer: RPM

azure-cli 2.37.0
```

**Comment by emmanuelsomeox** [comment]
Additional info : package azure-cli has been installed using [official methods for Red Hat ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf).

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
What's the output of `PYTHONPATH=/usr/lib64/az/lib/python3.6/site-packages/ /usr/bin/python3.6 -m pip list | grep azure-mgmt-resource`?

**Comment by emmanuelsomeox** [comment]
Output :
PYTHONPATH=/usr/lib64/az/lib/python3.6/site-packages/ /usr/bin/python3.6 -m pip list | grep azure-mgmt-resource
azure-mgmt-resource                              21.1.0b1
azure-mgmt-resourcegraph                         1.0.0

**Comment by bebound** [comment]
That's weird. The error message indicates that dependency might be broken(similar to #21189), but it looks okay.
Could you please attach the output of `az -v`?

A fresh installation should help.

**Comment by jiasli** [comment]
Here is a previous analysis on the error `TypeError: __init__() got an unexpected keyword argument 'user_agent'`: https://github.com/Azure/azure-cli/issues/18626#issuecomment-876982958

Some how your `SubscriptionClient` is from Track 1 SDK.

Perhaps you may also try this command to see where `SubscriptionClient` is imported from:

```
$ PYTHONPATH=/usr/lib64/az/lib/python3.6/site-packages/ /usr/bin/python3.6 -c "import azure.mgmt.resource.subscriptions; print(azure.mgmt.resource.subscriptions.__file__)"
/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/__init__.py
```

The latest Azure CLI is 2.40.0. For latest Azure CLI, the command should be

```
$ PYTHONPATH=/usr/lib64/az/lib/python3.9/site-packages/ /usr/bin/python3.9 -c "import azure.mgmt.resource.subscriptions; print(azure.mgmt.resource.subscriptions.__file__)"
/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/resource/subscriptions/__init__.py
```

**Comment by emmanuelsomeox** [comment]
Result of az -v
az -v
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource                2.1.0

Python location '/usr/bin/python3.6'
Extensions directory '/home/xxxxx/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Aug  3 2021, 06:54:29)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by jiasli** [comment]
`azure-mgmt-resource 2.1.0` is Track 1 SDK. I am not sure why it is against `azure-mgmt-resource 21.1.0b1` from https://github.com/Azure/azure-cli/issues/23954#issuecomment-1253123915

**Comment by emmanuelsomeox** [comment]
Result of command https://github.com/Azure/azure-cli/issues/23954#issuecomment-1253146609
 PYTHONPATH=/usr/lib64/az/lib/python3.6/site-packages/ /usr/bin/python3.6 -c "import azure.mgmt.resource.subscriptions; print(azure.mgmt.resource.subscriptions.__file__)"
/usr/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/__init__.py

I will test a new fresh install tomorrow on a new server

**Comment by jiasli** [comment]
Just as I inferred, `/usr/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/__init__.py` is installed by `pip`, interfering with Azure CLI's `/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/__init__.py`.

**Comment by emmanuelsomeox** [comment]
I followed the official method [official methods for Red Hat ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf). for the installation via dnf and not pip.

**Comment by emmanuelsomeox** [comment]
Hello, I redo the installation on another system following the [official methods for Red Hat ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf).  and I still have the same issue.
Do you have a solution / workaround to solve that issue ?

**Comment by jiasli** [comment]
Do you install other software that installs `/usr/lib/python3.6/site-packages/azure/mgmt/resource/subscriptions/__init__.py`?

**Comment by emmanuelsomeox** [comment]
Hello,
Sorry for the delay.
I checked on a fresh installed machine and there is no existing /usr/lib/python3.6/site-packages/azure/ dir before the installation of the package
