### ISSUE TITLE
Heeelp please

### ISSUE THREAD

**Issue by OZZYTA** [Azure/azure-cli#23970]
## Describe the bug

**Command Name**
`az spring app deploy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'termios'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 507, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ozzy\.azure\cliextensions\spring\azext_spring\app.py", line 10, in <module>
    from .custom import app_get
  File "C:\Users\Ozzy\.azure\cliextensions\spring\azext_spring\custom.py", line 12, in <module>
    import tty
  File "tty.py", line 5, in <module>
ModuleNotFoundError: No module named 'termios'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring app deploy --resource-group {} --service {} --name {} --artifact-path {}`

## Environment Summary
```
Windows-10-10.0.18363-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
spring 1.1.8

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@OZZYTA Thank you for reaching out to us, we are looking into it.

**Comment by navba-MSFT** [comment]
@OZZYTA This issue seems to be fixed by this PR https://github.com/Azure/azure-cli-extensions/pull/5378. Could you please run the below command to update your `spring` extension and check if you still see the same issue ?

> az extension update -n spring

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@OZZYTA I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@OZZYTA The action is currently pending on you to update the `spring` extension using the above command. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
