### ISSUE TITLE
Issue with az cli reservations module

### ISSUE THREAD

**Issue by hharsunen** [Azure/azure-cli#23976]
## Describe the bug

**Command Name**
`az reservations reservation-order list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
("Unable to deserialize response data. Data: , [ReservationOrderResponse], DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>"))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1653, in deserialize_iter
azure.core.exceptions.DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/reservations/_exception_handler.py", line 14, in reservations_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/reservations/operations/_reservation_order_operations.py", line 338, in extract_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1376, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1450, in _deserialize
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1637, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1653, in deserialize_iter
azure.core.exceptions.DeserializationError: ("Unable to deserialize response data. Data: , [ReservationOrderResponse], DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>"))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az reservations reservation-order list`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
account 0.2.4
resource-graph 2.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@hharsunen Apologies for the late reply. Thanks for reaching out to us and reporting this issue. I am unable to reproduce this issue. I ran the below command and it worked fine:

> **az reservations reservation-order-id list --subscription-id xxxx**

Could you please update to the most recent version of the `reservation `CLI extension and check if that helps ?

> **az extension update -n reservation**

Also as a workaround, if you still encounter this issue, please run the below command: 

```
az rest --method GET --uri "https://management.azure.com/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Capacity/appliedReservations?api-version=2022-03-01"
```
Please replace XXXXX with your concerned subscription id and let me know if that works. Awaiting your reply.

**Comment by hharsunen** [comment]
Tried today without having upgraded any modules on the machine where powershell and it's working now without.

**Comment by navba-MSFT** [comment]
@hharsunen Thanks for getting back. If the issue resurfaces or if you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
