### ISSUE TITLE
download of logfiles...

### ISSUE THREAD

**Issue by hhazewinkel** [Azure/azure-cli#23981]
## Describe the bug

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'host_name_ssl_states'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 2295, in download_historical_logs
    scm_url = _get_scm_url(cmd, resource_group_name, name, slot)
  File "/usr/local/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 1947, in _get_scm_url
    for host in app.host_name_ssl_states or []:
AttributeError: 'NoneType' object has no attribute 'host_name_ssl_states'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --name {} --resource-group {}`

## Environment Summary
```
macOS-12.5.1-x86_64-i386-64bit, Darwin 21.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0 *

Extensions:
application-insights 0.1.16

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@hhazewinkel Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@hhazewinkel I see that you are using an older version of Azure CLI. Could you please update the AzCLI to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) and test the same command again ?

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@hhazewinkel I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by hhazewinkel** [comment]
After an update it works again.
II guess, something changed over time and, therefore, it stopped working.

**Comment by navba-MSFT** [comment]
@hhazewinkel Thanks for the update. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
