### ISSUE TITLE
AKS cluster stuck on starting, cannot be stopped

### ISSUE THREAD

**Issue by rinna-mnizami** [Azure/azure-cli#23989]
## Describe the bug

**Command Name**
`az aks stop`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-49qlvzn7\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\commands\__init__.py", line 553, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-03qxfwck\azure\cli\core\__init__.py", line 479, in load_arguments
  File "C:\Users\nizam\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\nizam\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- The cluster is stuck on "This cluster is starting..." for more than an hour
- `az aks stop --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by rinna-mnizami** [comment]
suddenly it started but I don't know why. Did CXP team do something?

**Comment by navba-MSFT** [comment]
@rinna-mnizami CXP team didn't do any changes. Our recommendations would be to update an updated version of the `aks-preview` extension, since you are using an older version of this extension.

> az extension update -n aks-preview

If you encounter the same issue even after updating the extension, please feel free to reopen this issue. We would be happy to help.
