### ISSUE TITLE
Reservation Order List bug

### ISSUE THREAD

**Issue by strachan** [Azure/azure-cli#23992]
## Describe the bug

**Command Name**
`az reservations reservation-order list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
("Unable to deserialize response data. Data: , [ReservationOrderResponse], DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>"))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1653, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
azure.core.exceptions.DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/reservations/_exception_handler.py", line 14, in reservations_exception_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/azure/mgmt/reservations/operations/_reservation_order_operations.py", line 338, in extract_data
    deserialized = self._deserialize("ReservationOrderList", pipeline_response)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1376, in __call__
    return self._deserialize(target_obj, data)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1450, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/homebrew/Cellar/azure-cli/2.40.0/libexec/lib/python3.10/site-packages/msrest/serialization.py", line 1653, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
azure.core.exceptions.DeserializationError: ("Unable to deserialize response data. Data: , [ReservationOrderResponse], DeserializationError: Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [ReservationOrderResponse] an object of type <class 'str'>"))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az reservations reservation-order list`

## Environment Summary
```
macOS-12.6-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
route to CXP team
