### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c'.

### ISSUE THREAD

**Issue by Rizo-R** [Azure/azure-cli#24013]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'latin-1' codec can't encode character '\u201c' in position 29: Body ('“') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/util/custom.py", line 24, in rest_call
    r = send_raw_request(cmd.cli_ctx, method, url, headers, uri_parameters, body,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 985, in send_raw_request
    r = s.send(prepped, **settings)
  File "/usr/lib64/az/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/az/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1330, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.9/http/client.py", line 168, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 29: Body ('“') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Follow the steps for section "1. Create an Azure Active Directory (AAD) application to enable authentication on the Feathr UI" in the following article: https://feathr-ai.github.io/feathr/how-to-guides/azure-deployment-arm.html
- The error happens when running 'az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/$aad_objectId" --headers "Content-Type=application/json" --body "{spa:{redirectUris:['https://$sitename.azurewebsites.net']}}"'

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0

Extensions:
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

Seems like encoding needs to be changed from 'latin-1' to 'utf-8' but I can't find a way to do it for Azure CLI.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The latest Azure CLI does support Unicode in request body:

- https://github.com/Azure/azure-cli/pull/23005

`--body "{spa:{redirectUris:['https://$sitename.azurewebsites.net']}}"` is not a valid JSON string. It is highly possible the string you pasted/typed to the terminal contains `“` (https://unicode-table.com/en/201C/), instead of `"`, making the Unicode escaping logic skipped. Actually, the JSON shouldn't contain `“` at all!

Correct form should be:

`az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/$aad_objectId" --body "{\"spa\":{\"redirectUris\":[\"https://$sitename.azurewebsites.net\"]}}"`

**Comment by Rizo-R** [comment]
You're right, turns out my `resource_prefix` string was surrounded with `“ ` instead of `"` (I wrote it in the Notes app on Mac and copy-pasted into CloudShell). Changing the symbol fixed the error, without having to modify the original `az rest` command to what you suggested.
