### ISSUE TITLE
azure aks not working!

### ISSUE THREAD

**Issue by Akash3221** [Azure/azure-cli#24021]
## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named '_cffi_backend'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib64/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.7/argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.7/argparse.py", line 1158, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 2022, in _parse_known_args
    ', '.join(required_actions))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 160, in error
    recommender.set_help_examples(self.get_examples(self.prog))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 203, in get_examples
    is_group)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 192, in get_examples
    else self.group_help_cls(self, delimiters, parser)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 303, in load
    loader.versioned_load(self, options)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/parser.py", line 242, in __getattribute__
    if callable(self._description) else self._description
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 37, in <module>
    from azure.cli.command_modules.acs import acs_client, proxy
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/acs_client.py", line 13, in <module>
    import paramiko
  File "/usr/lib64/az/lib/python3.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib64/az/lib/python3.6/site-packages/paramiko/transport.py", line 91, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/lib64/az/lib/python3.6/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/usr/lib64/az/lib/python3.6/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/usr/lib64/az/lib/python3.6/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ModuleNotFoundError: No module named '_cffi_backend'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks`

## Environment Summary
```
Linux-5.10.135-122.509.amzn2.x86_64-x86_64-with-glibc2.2.5, Amazon Linux 2
Python 3.7.10
Installer: RPM

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Akash3221 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Akash3221 Could you please run the below command and check if that helps ?

```
sudo apt remove python3-cffi
sudo python3 -m pip install cffi
```

Also please update the [Azure CLI to the most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli). Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Akash3221 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by Akash3221** [comment]
@navba-MSFT thanks for the help its working!

**Comment by navba-MSFT** [comment]
@Akash3221 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
