### ISSUE TITLE
Upgrade `ml` extension in Cloud Shell fails: FileExistsError: [Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'

### ISSUE THREAD

**Issue by edygyan** [Azure/azure-cli#24023]
## Describe the bug

**Command Name**
`az extension update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 413, in update_extension
    _add_whl_ext(cli_ctx=cmd_cli_ctx, source=download_url, ext_sha256=ext_sha256,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 113, in _add_whl_ext
    raise CLIError('The extension {} already exists.'.format(extension_name))
knack.util.CLIError: The extension ml already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/extension/custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 421, in update_extension
    shutil.copytree(backup_dir, extension_path)
  File "/usr/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension update -n {}`

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0

Extensions:
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by edygyan** [comment]
az>> upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.40.0

Upgrading extensions
Checking update for interactive
Latest version of 'interactive' is already installed.

Use --debug for more information
Checking update for ai-examples
Latest version of 'ai-examples' is already installed.

Use --debug for more information
Checking update for ml
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. You may try to delete it manually.
An error occurred whilst updating.
The extension ml already exists.
The command failed with an unexpected error. Here is the traceback:
[Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 413, in update_extension
    _add_whl_ext(cli_ctx=cmd_cli_ctx, source=download_url, ext_sha256=ext_sha256,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 113, in _add_whl_ext
    raise CLIError('The extension {} already exists.'.format(extension_name))
knack.util.CLIError: The extension ml already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/extension/custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 421, in update_extension
    shutil.copytree(backup_dir, extension_path)
  File "/usr/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
To open an issue, please run: 'az feedback'
Checking update for ssh
Latest version of 'ssh' is already installed.

Use --debug for more information
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
az>> 
az>>

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jiasli** [comment]
I see you are running this command in Cloud Shell:

```
az extension update -n ml
```

If you run `az extension list`, you will see `ml` is installed as a system-level extension under `/usr/lib/python3.9/site-packages/azure-cli-extensions`:

```
$ az extension list 
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ai-examples",
    "path": "/usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples",
    "preview": true,
    "version": "0.2.5"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ml",
    "path": "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml",
    "preview": false,
    "version": "2.7.1"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ssh",
    "path": "/usr/lib/python3.9/site-packages/azure-cli-extensions/ssh",
    "preview": false,
    "version": "1.1.2"
  }
]
```

So you can't manually update `ml`. 

I think we do need a way to override system-level extension.

**Comment by bebound** [comment]
We can use **extension.sys_dir** to override system extension directory.
If we set it to an empty dir, the pre-installed extension disappears and you can install `ml` now.
`az config set extension.sys_dir=/dev/null`
