### ISSUE TITLE
az acs kubernetes get-credentials: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vdice** [Azure/azure-cli#2405]
I've followed the [docs](https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough) around launching my first ACS cluster and although creation of the resource group (`az group create --name "${AZURE_RG_NAME}" --location "${AZURE_DC_LOCATION}"`) and acs cluster (`az acs create ...`) is successful, I am greeted with the following when attempting to get credentials (`az acs kubernetes get-credentials...`):

```
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 338, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 590, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 613, in _k8s_get_credentials_internal
    merge_kubernetes_configurations(path, path_candidate)
  File "/Users/vaughndice/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 627, in merge_kubernetes_configurations
    existing['clusters'].extend(addition['clusters'])
TypeError: 'NoneType' object is not subscriptable
```

Here is a [gist](https://gist.github.com/vdice/01ea18451e15701e1dff2e5dade85a33) including the full output and flow, with `--debug` and `--verbose` set on the command in question.

**Comment by vdice** [comment]
Update: Although the error mentioned in the description is definitely still an issue, I realized later that the context was actually successfully written to `/Users/vaughndice/.kubes/acs/kubeconfig-vrd-svc-7` and I just verified I am able to interact with the cluster after `export KUBECONFIG=/Users/vaughndice/.kubes/acs/kubeconfig-vrd-svc-7`.  (There had been 6 previous iterations of bootstrapping/tearing down...)

It was a little confusing as I had intended the context to be written to `/Users/vaughndice/.kubes/acs/kubeconfig` -- this was the value that `$KUBECONFIG` resolved to when invoking `az acs kubernetes get-credentials ... -f "${KUBECONFIG}"` initially.

**Comment by brendandburns** [comment]
Yeah, that merge should have happened, but it crashed. I'll add a test and fix the bug.

Apologies!

**Comment by brendandburns** [comment]
I believe that this is now fixed, please re-open if it it occurs again.
