### ISSUE TITLE
`az aks install-cli` causes "Connection reset by peer" on 18.04 Ubuntu VM

### ISSUE THREAD

**Issue by tsela** [Azure/azure-cli#24083]
## Describe the bug

After installing the Azure CLI without a problem, I'm trying to install the AKS CLI as I need the `kubectl` command up and running. But running the installation command errors out.

**Command Name**
`az aks install-cli`

Run with `sudo` as needed in Linux.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
<urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/az/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/az/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/az/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/az/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/az/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/az/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2508, in k8s_install_cli
    k8s_install_kubectl(cmd, client_version, install_location, base_src_url)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2527, in k8s_install_kubectl
    version = urlopen(source_url + '/stable.txt', context=context).read()
  File "/opt/az/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/az/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/az/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/az/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _No prerequisite steps needed except installing the Azure CLI and running `az login` (which completed successfully)_
- `sudo az aks install-cli`

## Expected Behavior

I'd expect the Kubernetes commands to install properly.

## Environment Summary
```
Linux-5.4.0-126-generic-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0
```
## Additional Context

This is actually a VirtualBox VM running on my work computer, with proxy environment variables set up to allow the VM to talk to the network via the corporate proxy.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@tsela Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tsela Looking at the error message, it seems like a network layer connectivity failure. Do you have a proxy / firewall within your corporate network ? If Yes, could you please bypass that and run the AzCLI command again ?

Alternatively, The following methods exist for installing _`kubectl on Linux`_:

- [Install kubectl binary with curl on Linux](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux)

- [Install using native package management](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management)

- [Install using other package management](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-other-package-management)

Could you please follow either if the above and let me know if that helps ? Please let me know if you face any issues.

**Comment by tsela** [comment]
@navba-MSFT Yes, we have a firewall within the corporate network. My VM is set up to use the corporate proxy, and pretty much everything works fine that way. Unfortunately, I cannot bypass the proxy. If I do so, Zscaler takes over instead, and my VM can't connect to the Internet with Zscaler running.

I'll try the alternative installation methods you provide and will update afterwards.

**Comment by tsela** [comment]
OK, so I managed to install both `kubectl` and `kubelogin` via Homebrew. Does the `az aks install-cli` do anything else I need to do separately?

**Comment by navba-MSFT** [comment]
@tsela There is no issue with the above AzCLI command. It does work fine. I have tried that in my enviornment and it installed the kubectl successfully. However, in your scenario with the proxy in picture there was issue in establishing the connection. AzCLI (uses python) underneath and has restriction while working with proxy. So there are a few additional configuration needs to be done. That is explained [here](https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy) and [here](https://github.com/jiasli/azure-notes/tree/master/cli). Hope this helps. Please feel free to reopen this issue if you have any follow-up queries.

**Comment by roshithrajan** [comment]
I am also facing same issue , kubectl got installed not able to install kubelogin 
The detected architecture is 'x86_64', which will be regarded as 'amd64' and the corresponding binary will be downloaded. If there is any problem, please download the appropriate binary by y
ourself.
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.26.2/bin/linux/amd64/kubectl"
Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.
Downloading client to "/tmp/tmphcnd6z9i/kubelogin.zip" from "https://github.com/Azure/kubelogin/releases/download/v0.0.27/kubelogin.zip"
Connection error while attempting to download client (<urlopen error [Errno 104] Connection reset by peer>)
