### ISSUE TITLE
Creating Contributor role security policy fails (github action configuration)

### ISSUE THREAD

**Issue by Jamie-Clayton** [Azure/azure-cli#24089]
## Describe the bug

Attempting to create the security credentials required to publish a static website from GitHub via Microsoft learning resources.

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'id=/subscriptions/8a5a8fe8-3456-4d6e-a0ad-5e9938fd8a0e/resourceGroups/Jenasys-DevOps'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/commands.py", line 51, in graph_err_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1228, in create_service_principal_for_rbac
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 198, in _create_role_assignment
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 591, in _resolve_role_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/paging.py", line 143, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/paging.py", line 129, in advance_page
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 285, in internal_paging
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 281, in prepare_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/service_client.py", line 168, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/service_client.py", line 108, in _request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/service_client.py", line 151, in format_url
KeyError: 'id=/subscriptions/8a5a8fe8-3456-4d6e-a0ad-5e9938fd8a0e/resourceGroups/Jenasys-DevOps'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Following steps provided in the [online tutorial](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel)
- Had DNS Zone preconfigured and named 'mydomain.com'
- Applied the following powershell script

```powershell
az login --allow-no-subscriptions
$siteUri = "mydomain.com" 
$resourceGroupName = 'mybusiness-devops'
$resourceScope = az group show --name $resourceGroupName | ConvertFrom-Json | Select-Object id
az ad sp create-for-rbac --name $siteUri --role contributor --scopes $resourceScope
```

## Expected Behavior

The az cli should not crash and show exception stack traces.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
azure-iot 0.10.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

The az cli returns a warning, suggesting that the [online tutorial](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel) was written with an older edition of the az cli.

> Option '--sdk-auth' has been deprecated and will be removed in a future release.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is not the scope of Azure CLI, but PowerShell.

Your `$resourceScope` is a JSON object, not string.

```
> echo $resourceScope

id
--
/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/clitest.rg6i4hl6iakg

> python -c "import sys; print(sys.argv)" $resourceScope
['-c', '@{id=/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/clitest.rg6i4hl6iakg}']
```

Make sure `$resourceScope` is a string like `/subscriptions/8a5a8fe8-3456-4d6e-a0ad-5e9938fd8a0e/resourceGroups/Jenasys-DevOps` before passing to Azure CLI:

```
> $resourceScope = (az group show --name 'clitest.rg6i4hl6iakg' | ConvertFrom-Json).id
> python -c "import sys; print(sys.argv)" $resourceScope
['-c', '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/clitest.rg6i4hl6iakg']
```

**Comment by Jamie-Clayton** [comment]
@jiasli thanks for clarifying my mistake with the Powershell script. I've updated the logic on the last line to ensure I convert the $resourceScope object to a string variable required for the CLI --scopes parameter.  
Chaining together all the Az CLI examples for a full automation script is an entertaining Powershell skills uplift.

```powershell
az login --allow-no-subscriptions
$siteUri = "mydomain.com" 
$resourceGroupName = 'mybusiness-devops'
$resourceScope = az group show --name $resourceGroupName | ConvertFrom-Json | Select-Object id
az ad sp create-for-rbac --name $siteUri --role contributor --scopes $resourceScope.id  --sdk-auth
```
