### ISSUE TITLE
"az aks create" fails with error "400 Request Header Or Cookie Too Large"

### ISSUE THREAD

**Issue by adrianparks** [Azure/azure-cli#24107]
**Related command**

az aks create

**Describe the bug**
`az aks create` fails with error "400 Request Header Or Cookie Too Large". We tried clearing cache and account details:

```
az account clear
az login

az cache purge
az cache list
[]
az login

rm -rf ~/.azure
```
but the problem persists.

**To Reproduce**
az aks create -g my-rg -n my-cluster --debug

**Expected behavior**

See description.

**Environment summary**

We have observed this with azcli 2.40.0 on Linux (WSL), as well as earlier versions (2.3x) on both MacOS and Linux. We have tried deploying clusters in different regions (westeurope, northeurope, eastus) with same result.

```
Linux 5.10.16.3-microsoft-standard-WSL2
Python 3.10.5
azure-cli 2.40.0
```

**Additional context**

We were successfully deploying AKS clusters with azcli and using the Azure SDK for Go until last week (30 September). We started observing this issue yesterday (4 October). We have tried varying our location (on and off VPN, for example) with the same results. We have also observed this started happening with earlier versions of azcli (2.39.0 and an earlier 2.3x, which I upgraded to 2.40.0 to see if that would resolve the issue, and did not).

Will attach debug logs.

**Comment by adrianparks** [comment]
Debug logs (redacted):
```
cli.knack.cli: Command arguments: ['aks', 'create', '-g', 'my-rg-name', '-n', 'my_cluster_name', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7ff1520d6a70>, <function OutputProducer.on_global_arguments at 0x7ff151ffc430>, <function CLIQuery.on_global_arguments at 0x7ff152025630>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.118         8        58
cli.azure.cli.core: Total (1)                 0.118         8        58
cli.azure.cli.core: Loaded 8 groups, 58 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks create
cli.azure.cli.core: Command table: aks create
[..]
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/...?api-version=2021-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': ************************************
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.40.0 (DEB) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.10.5 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/...?api-version=2021-04-01 HTTP/1.1" 200 279
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '************************************'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '************************************'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20221005T144021Z:************************************'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 05 Oct 2022 14:40:21 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '279'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/.../resourceGroups/my-rg-name","name":"my-rg-name","type":"Microsoft.Resources/resourceGroups","location":"westeurope","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'subscription_id' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'monitoring_addon_enabled' does not exist. Return default value 'False'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'ingress_appgw_addon_enabled' does not exist. Return default value 'False'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'virtual_node_addon_enabled' does not exist. Return default value 'False'.
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: ************************************
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/.../providers/Microsoft.ContainerService/managedClusters/my_cluster_name?api-version=2022-06-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1768'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '************************************'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.40.0 (DEB) azsdk-python-azure-mgmt-containerservice/20.2.0 Python/3.10.5 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westeurope", "identity": {"type": "SystemAssigned"}, "properties": {"kubernetesVersion": "", "dnsPrefix": "************************************", "agentPoolProfiles": [{"count": 3, "vmSize": "Standard_DS2_v2", "osDiskSizeGB": 0, "osType": "Linux", "enableAutoScaling": false, "type": "VirtualMachineScaleSets", "mode": "System", "orchestratorVersion": "", "upgradeSettings": {}, "enableNodePublicIP": false, "scaleSetPriority": "Regular", "scaleSetEvictionPolicy": "Delete", "spotMaxPrice": -1.0, "nodeTaints": [], "enableEncryptionAtHost": false, "enableUltraSSD": false, "enableFIPS": false, "name": "nodepool1"}], "linuxProfile": {"adminUsername": "azureuser", "ssh": {"publicKeys": [{"keyData": "ssh-rsa ************************************ \n"}]}}, "addonProfiles": {}, "enableRBAC": true, "networkProfile": {"networkPlugin": "kubenet", "podCidr": "10.244.0.0/16", "serviceCidr": "10.0.0.0/16", "dnsServiceIP": "10.0.0.10", "dockerBridgeCidr": "172.17.0.1/16", "outboundType": "loadBalancer", "loadBalancerSku": "standard"}, "disableLocalAccounts": false, "storageProfile": {}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/.../providers/Microsoft.ContainerService/managedClusters/my_cluster_name?api-version=2022-06-01 HTTP/1.1" 400 226
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '226'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'text/html'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '************************************'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '************************************'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20221005T144023Z:************************************'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 05 Oct 2022 14:40:23 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx</center>
</body>
</html>

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5440, in create_mc
    cluster = self.put_mc(mc)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5418, in put_mc
    cluster = sdk_no_wait(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 699, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_06_01/operations/_managed_clusters_operations.py", line 1601, in begin_create_or_update
    raw_result = self._create_or_update_initial(  # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_06_01/operations/_managed_clusters_operations.py", line 1540, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx</center>
</body>
</html>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1606, in aks_create
    return aks_create_decorator.create_mc(mc)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 5449, in create_mc
    raise map_azure_error_to_cli_error(ex)
azure.cli.core.azclierror.BadRequestError: Operation returned an invalid status 'Bad Request'

cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'
az_command_data_logger: Operation returned an invalid status 'Bad Request'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7ff1515b1c60>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.704 seconds (init: 0.112, invoke: 2.592)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3246 in cache
telemetry.check: Negative: The /home/my-user-name/.azure/telemetry.txt was modified at 2022-10-05 14:39:10.769910, which in less than 600.000000 s
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@adrianparks Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@adrianparks We had a few customers reporting the same issue. So this issue was reported with the Product Group and they have fixed it in the background. Below is the RCA which they have shared:

> AKS recently changed our ARM manifest to ask ARM to send On-Behalf-Of tokens to AKS. For users who are members of a lot of security groups, their tokens can be quite large, upwards of 100K+. This causes the headers for those requests to be very large. Our http web server configuration currently has a maximum request header size set to 1K. So, for those users who had large tokens, our http web server configuration rejected the request for being too large. We have rolled back the manifest change as mitigation, and have a work item filed to change our http web server configuration to allow for the increased request header size.

Could you please try to recreate the AKS cluster and check if that works now? Awaiting your reply.

**Comment by adrianparks** [comment]
Thanks @navba-MSFT - all working fine now. Thanks for the resolution and for the analysis!
