### ISSUE TITLE
After updating az cli az login crashes

### ISSUE THREAD

**Issue by antgustech** [Azure/azure-cli#24103]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az login

**Describe the bug**
The browser opens automatically.  I click sign in on my account. The browser redirects saying login succesfully. CLI then throws error in python.
`➜ az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 171, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1546, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oidc.py", line 280, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 640, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 678, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 135, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oidc.py", line 204, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 548, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 732, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oidc.py", line 115, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 581, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 184, in __add
    self.modify(self.CredentialType.ACCESS_TOKEN, at, at)
  File "/opt/az/lib/python3.8/site-packages/msal_extensions/token_cache.py", line 67, in modify
    self._reload_if_necessary()
  File "/opt/az/lib/python3.8/site-packages/msal_extensions/token_cache.py", line 58, in _reload_if_necessary
    self.deserialize(self._persistence.load())
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 319, in deserialize
    self._cache = json.loads(state) if state else {}
  File "/opt/az/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**To Reproduce**
run az login and login via browser.

**Expected behavior**
To be logged in.

**Environment summary**
WSL

**Additional context**
This has worked fine before, then I updated to 2.40.0 and issues started happening. I then downgraded to older version but the issue persists.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
It is not related to Azure CLI 2.40.0. It seems your token cache `~/.azure/msal_token_cache.json` has been corrupted, possibly by manual alternation or forcefully closing Azure CLI. Please delete that file and run `az login` again.
