### ISSUE TITLE
Unable to az login

### ISSUE THREAD

**Issue by tsuiala** [Azure/azure-cli#24102]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
WsTrust server returned error in RSTR: {'reason': 'ID3242: The security token could not be authenticated or authorized.', 'code': 'a:FailedAuthentication'}
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 157, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 158, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/msal/application.py", line 1460, in acquire_token_by_username_password
    response = _clean_up(self._acquire_token_by_username_password_federated(
  File "/opt/homebrew/lib/python3.10/site-packages/msal/application.py", line 1487, in _acquire_token_by_username_password_federated
    wstrust_result = wst_send_request(
  File "/opt/homebrew/lib/python3.10/site-packages/msal/wstrust_request.py", line 60, in send_request
    return parse_response(resp.text)
  File "/opt/homebrew/lib/python3.10/site-packages/msal/wstrust_response.py", line 49, in parse_response
    raise RuntimeError("WsTrust server returned error in RSTR: %s" % (error or body))
RuntimeError: WsTrust server returned error in RSTR: {'reason': 'ID3242: The security token could not be authenticated or authorized.', 'code': 'a:FailedAuthentication'}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {}`

## Environment Summary
```
macOS-12.5.1-arm64-arm-64bit
Python 3.10.6
Installer: PIP

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
Similar to https://github.com/Azure/azure-cli/issues/21050. Please see https://github.com/Azure/azure-cli/issues/21050#issuecomment-1017922460 and try if interactive login works. If you can't use the browser-based interactive flow, such as in automation environment, the recommendation is to [sign in with a service principal](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-service-principal) or [sign in with a managed identity](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-managed-identity).
