### ISSUE TITLE
az servicebus namespace list fails in subscription with no namespaces

### ISSUE THREAD

**Issue by Strandfelt** [Azure/azure-cli#24101]
## Describe the bug

When calling `az servicebus namespace list` in a subscription that does not contain any service bus namespaces, an error is returned instead of an empty array.

**Command Name**
`az servicebus namespace list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 84, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/servicebus/v2022_01_01_preview/operations/_namespaces_operations.py", line 747, in extract_data
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Select subscription that does not contain any Service Bus namespaces
- `az servicebus namespace list`

## Expected Behavior
An empty json array should be returned

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
application-insights 0.1.16
azure-devops 0.25.0
logic 0.1.6
virtual-wan 0.2.13

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Strandfelt Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Strandfelt Until the fix is released, could you please run the below command? This should show an empty array if there are no namespaces in the subscription and doesn't fail with TypeError exception.

>**az resource list --resource-type  "Microsoft.ServiceBus/Namespaces"**

Hope this helps.

**Comment by navba-MSFT** [comment]
@Strandfelt I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by Strandfelt** [comment]
@navba-MSFT Yes, that command does indeed work without errors. Thanks.

**Comment by navba-MSFT** [comment]
@Strandfelt Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
