### ISSUE TITLE
az storage blob ls failed for a bucket with 1 million objects

### ISSUE THREAD

**Issue by xinglin** [Azure/azure-cli#2412]
This tool does not seem to scale well. It can consume more than 12GB of memory for a bucket with 1 million objects and failed with a memory error. 

azure storage blob ls -c container-with-1million-blobs

the traceback is attached below. 

Traceback (most recent call last):
  File "/home/xing/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 44, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result)
  File "/home/xing/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_output.py", line 111, in out
    output = self.formatter(obj)
  File "/home/xing/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_output.py", line 43, in format_json
    separators=(',', ': ')) + '\n'
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
MemoryError

-Xing

**Comment by williexu** [comment]
Closing in favor of: https://github.com/Azure/azure-cli/issues/3745
