### ISSUE TITLE
Unable to run "az connectedk8s"; versions mismatch?

### ISSUE THREAD

**Issue by MswPaulDSmith** [Azure/azure-cli#24144]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'Crypto.IO'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/developer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/home/developer/.local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/developer/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.8/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/developer/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/developer/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 37, in <module>
    from Crypto.IO import PEM
ModuleNotFoundError: No module named 'Crypto.IO'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --group {} --name --subscription {}`

## Environment Summary
```
Linux-5.15.57.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.5 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.40.0

Extensions:
storage-preview 0.8.3
connectedk8s 1.3.4
resource-graph 2.1.0
account 0.2.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@MswPaulDSmith I've just tried the same command using the latest versions (which you have as well) and the command did work without any issues. Could you try reinstalling Azure CLI and try the command again?

**Comment by MswPaulDSmith** [comment]
Apparently (found elsewhere by searching for the error message) the magic incantation is `python3 -m pip install pycryptodome`; I tried an `az update` but this didn't work so I'm guessing some combination of `az` libraries is missing a dependency and perhaps your system had `pycryptodome` for other reasons already.

**Comment by PramodValavala-MSFT** [comment]
@MswPaulDSmith The dependencies are shipped (including python) along with Azure CLI if installed by following the [official options](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli). Would it be right to assume that you installed Azure CLI using `pip`?

**Comment by papadeltasierra** [comment]
I installed the base `az` CLI a long time ago so honestly can't remember.  Is there any way I can check and confirm whether I did, or not?  I do have a `/usr/local/lib/python3.8/dist-packages/azure/cli` directory if that answers the question.

**Comment by PramodValavala-MSFT** [comment]
@MswPaulDSmith Based on where it is installed, you used `pip`. It would be best to use the official methods of installation which should ensure all required dependencies are available.

@jiasli Could you confirm if installing from `pip` is still an option?

**Comment by papadeltasierra** [comment]
Removed all azure packages via pip and have reinstalled as per https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt.  Will try commands again ASAP.

**Comment by papadeltasierra** [comment]
Confirming that uninstalling all Azure components and reinstalling again works.  Is there a way to remove the package from Pypi to avoid this in future? Happy for this issue to be closed though.  Thanks for you help.

**Comment by PramodValavala-MSFT** [comment]
@MswPaulDSmith @papadeltasierra Thanks for the confirmation! With the right dependencies, the pypi package should work as well but its part of the official documentation since the other methods are recommended. Nonetheless, I will share the feedback with the concerning team. Closing.
