### ISSUE TITLE
regression in az acr build

### ISSUE THREAD

**Issue by miobrado** [Azure/azure-cli#24157]
## Describe the bug

A Quick Task is successfully created and executed in Azure Container Registry. The complete logs can be found on the ACR / Tasks / Runs tab. Everything seems fine on ACR side. Image is successfully created and pushed.

The problem seems to exist only on the client side. It fails to print out the logs from the ACR Quick Task due to this encoding-related error.

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'charmap' codec can't encode characters in position 78-116: character maps to <undefined>
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 190, in write_and_convert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 78-116: character maps to <undefined>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --registry {} --image {} --platform {} --file {} {}`

- Dockerfile
```
FROM python:latest

WORKDIR /usr/src/myapp

COPY ./myapp ./

# Shell tools
RUN apt-get update
RUN apt-get install -y curl vim

# ODBC drivers and SQL tools (python:latest image is based on Debian 11)
# https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16#debian18
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
RUN apt-get install -y unixodbc-dev libgssapi-krb5-2

# Install requirements.
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./myapp.py" ]
```

## Expected Behavior

Expecting that the progress bar line "━" character emitted by `pip install` does not break `az acr build` command.

```
RUN pip install --no-cache-dir -r requirements.txt
```

Workaround is to turn the progress bar off:

```
RUN pip install --no-cache-dir --progress-bar off -r requirements.txt
```

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
aks-preview 0.5.100
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by miobrado** [comment]
A Quick Task is successfully created and executed in Azure Container Registry. The complete logs can be found on the ACR / Tasks / Runs tab. Everything seems fine on ACR side.

The problem seems to exist only on the client side. It fails to print out the logs from the ACR Quick Task due to this encoding-related error.

**Comment by miobrado** [comment]
Indeed, the `pip install` progress bar breaks the `az acr build` command.
A workaround is to turn the progress bar off:

```
RUN pip install --no-cache-dir --progress-bar off -r requirements.txt
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@miobrado Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@miobrado  I think it's a platform issue related to the unique combination Windows + Python.

Could you please try to update the Windows system language setting as shown below ?

Control panel -> Clock and Region -> Region -> Administrative -> Change system locale -> Check Beta: Use Unicode UTF-8 for worldwide language support.

![image](https://user-images.githubusercontent.com/57353862/195258511-eb876449-7fcd-426c-8eb6-7910ee3f4914.png)

The change will require reboot. Please let me know if you still face the same issue. Awaiting your reply.

**Comment by miobrado** [comment]
Thank you! Ticking the "Check Beta: Use Unicode UTF-8 for worldwide language support" option mitigated the problem.
