### ISSUE TITLE
Getting lock for specified resource with az lock show --resource xxx fails with exception

### ISSUE THREAD

**Issue by Fireblade954** [Azure/azure-cli#24152]
## Describe the bug

**Command Name**
`az lock show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 363, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 361, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3125, in get_lock
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/locks/v2016_09_01/operations/_operations.py", line 1355, in get_at_resource_level
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/locks/v2016_09_01/operations/_operations.py", line 381, in build_management_locks_get_at_resource_level_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 652, in url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 760, in serialize_data
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az lock show --resource {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
quota 0.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@Fireblade954 Could you please send the debug log to me by email. My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by navba-MSFT** [comment]
@Fireblade954 I am able to run the same command without any issues. Could you please use the [most recent version of the Azure CLI ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)and try running the same command ? Hope this helps.

**Comment by Fireblade954** [comment]
I tried azure-cli 2.40.0 first again, still the same issue. After i upgraded to azure-cli 2.42.0 but still give the exact same error.

**Comment by navba-MSFT** [comment]
@Fireblade954 Could you please run the same command again and share the complete `--debug` output over email navba [@]microsoft(.) dotcom ? Awaiting your reply.

**Comment by Fireblade954** [comment]
@navba-MSFT email send 👍

**Comment by navba-MSFT** [comment]
@Fireblade954 Thanks for getting back. Could you please try the below command and check if that helps ?

>**az rest --url https://management.azure.com/subscriptions/XXXXXXXXXXX/providers/Microsoft.Authorization/locks?api-version=2016-09-01**

**Comment by Fireblade954** [comment]
That call works, but as seen in the Debug log that call also returns a 200 and returns the same result when doing the az lock show.

**Comment by zhoxing-ms** [comment]
This problem is actually caused by a mistake in usage. Please distinguish the `--resource` parameter from `--name` parameter

```pwsh
(env) PS C:\Users\xxx\project> az lock show -h

Command
    az lock show : Show the properties of a lock.

Arguments
    ......
    --name -n                  : Name of the lock.
    ......
    --resource --resource-name : Name or ID of the resource being locked. If an ID is given, other
                                 resource arguments should not be given.
```
As we can see in the help message, the `--resource` parameter needs to pass in the **ID of the resource being locked**, while the `--name` parameter needs to pass in the **lock name**.
Therefore, the `--resource` parameter should **NOT** be passed in the **lock ID**. The correct usage should be: `az lock show --resource {locked_resouce_id} --name {lock_name}`

**Comment by navba-MSFT** [comment]
@Fireblade954 The action is currently pending on you to try the action plan mentioned above. Please feel free to reopen this thread if you need any further assistance on this in future. We would be happy to help.
