### ISSUE TITLE
Bastion ssh with AAD auth not working

### ISSUE THREAD

**Issue by larslind** [Azure/azure-cli#24173]
## Describe the bug

**Command Name**
`az network bastion ssh`

**Errors:**
```
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
C:\Users\<username>\AppData\Local\Temp\aadsshcertxnty0ib4 contains sensitive information (id_rsa, id_rsa.pub). Please delete once this certificate is no longer being used.
Generated SSH certificate C:\Users\<username>\AppData\Local\Temp\aadsshcertxnty0ib4\id_rsa.pub-aadcert.pub is valid until 2022-10-12 15:51:23 in local time.
Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8485, in _start_tunnel
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 184, in start_server
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 117, in _listen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
msrestazure.azure_exceptions.CloudError: Tunneling is disabled
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network bastion ssh --name {} --resource-group {} --target-resource-id {} --auth-type "AAD" --debug`

## Expected Behavior
Logged in with ssh to Ubuntu VM via Bastion using AAD credentials. I tried connecting to the same VM using AAD credentials with - `az ssh vm --name {} --resource-group {}` and that worked OK.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by larslind** [comment]
Hi @necusjz 
I also tested this from Azure Cloud Shell and got the same result.

**Error:**
```
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
/tmp/aadsshcert78z2hij8 contains sensitive information (id_rsa, id_rsa.pub). Please delete once this certificate is no longer being used.
Generated SSH certificate /tmp/aadsshcert78z2hij8/id_rsa.pub-aadcert.pub is valid until 2022-10-13 18:14:18 in local time.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 8475, in _start_tunnel
    tunnel_server.start_server()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/tunnel.py", line 184, in start_server
    self._listen()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/tunnel.py", line 117, in _listen
    auth_token = self._get_auth_token()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
    raise exp
msrestazure.azure_exceptions.CloudError: Tunneling is disabled
```

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0 *

Extensions:
resource-graph 0.1.8
azure-iot 0.9.2
kusto 0.3.0
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by larslind** [comment]
I've now also tried to connect to a Windows VM using
`az network bastion rdp`
and get the error
`Request to EncodingReservedUnitTypes v2 API endpoint failed.`
The final part of the `--debug` output is
```
urllib3.connectionpool: Starting new HTTPS connection (1): bst-fbfd7e59-2068-4a31-a948-70cf3193efa8.bastion.azure.com:443
urllib3.connectionpool: https://bst-fbfd7e59-2068-4a31-a948-70cf3193efa8.bastion.azure.com:443 "GET /api/rdpfile?resourceId=/subscriptions/7645db42-8220-45fc-a5bf-7c296c1a68bd/resourceGroups/AADVMTEST/providers/Microsoft.Compute/virtualMachines/aadwinvm&format=rdp HTTP/1.1" 403 431
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8436, in rdp_bastion_host
knack.util.CLIError: Request to EncodingReservedUnitTypes v2 API endpoint failed.
```
Do I need to open a separate issue for this?
@yonzhan, @necusjz

**Comment by larslind** [comment]
Turns out there was a problem with my Azure Bastion deployment, so I will close this issue now.

**Comment by larslind** [comment]
Some more useful error messages might have been helpful :-)
