### ISSUE TITLE
az bicep upgrade failed

### ISSUE THREAD

**Issue by spike28742** [Azure/azure-cli#24191]
## Describe the bug

**Command Name**
`az bicep upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3672, in upgrade_bicep_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 96, in ensure_bicep_installation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 200, in _get_bicep_installed_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 238, in _run_command
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep upgrade`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@spike28742 The issue looks more like python configuration issue, please try to uninstall python and reinstall again. Also verify its path and any orphan path of previous installations as well.

Additionally please upgrade to latest version of az cli [2.41.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by spike28742** [comment]
Hi,

I followed your recommendations and did not fix the issue.

Finally I managed to solve it by upgrading to the latest powershell version.

**Comment by RakeshMohanMSFT** [comment]
@spike28742 Glad you could solve the issue.
