### ISSUE TITLE
No module named 'azure.cli.command_modules.acs.decorator'

### ISSUE THREAD

**Issue by Maheshk-MSFT** [Azure/azure-cli#24208]
## Describe the bug

**Command Name**
`az feature list`

**Errors:**
```
maheshkumar@Azure:~$ az aks create     --resource-group ${GROUP}     --location eastus     --name ${MEMBER_CLUSTER_1}     --node-count 1     --network-plugin azure     --vnet-subnet-id "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${GROUP}/providers/Microsoft.Network/virtualNetworks/${FIRST_VNET}/subnets/${MEMBER_1_SUBNET}"
The behavior of this command has been altered by the following extension: aks-preview
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.command_modules.acs.decorator'
Traceback (most recent call last):
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/maheshkumar/.local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/maheshkumar/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 766, in aks_create
    from azure.cli.command_modules.acs.decorator import AKSParamDict
ModuleNotFoundError: No module named 'azure.cli.command_modules.acs.decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az feature list -o {} --query {}`

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: PIP

azure-cli 2.41.0

Extensions:
fleet 0.1.1
storage-preview 0.8.0
alias 0.5.2
interactive 0.4.5
costmanagement 0.1.1
connectedmachine 0.4.1
acrtransfer 1.1.0
azure-batch-cli-extensions 6.0.0
front-door 1.0.16
mesh 0.10.7
maintenance 1.3.0
deploy-to-azure 0.2.0
aem 0.3.0
managementpartner 0.1.3
mixed-reality 0.0.4
containerapp 0.2.0
connectedvmware 0.1.6
functionapp 0.1.0
eventgrid 0.4.9
azure-firewall 0.13.0
k8s-extension 1.3.5
notification-hub 0.2.0
sap-hana 0.6.5
customlocation 0.1.3
k8s-configuration 1.5.0
virtual-network-tap 0.1.0
subscription 0.1.4
internet-analyzer 0.1.0rc6
log-analytics 0.2.2
scheduled-query 0.5.0
support 1.0.3
resource-graph 2.1.0
db-up 0.2.6
peering 0.2.1
vmware 4.0.2
aks-preview 0.5.50
init 0.1.0
dms-preview 0.15.0
vm-repair 0.4.1
spring-cloud 3.0.0
image-copy-extension 0.2.9
netappfiles-preview 0.3.2
k8sconfiguration 0.2.4
csvmware 0.3.0
virtual-wan 0.2.11
healthcareapis 0.3.4
arcappliance 0.2.15
azure-cli-ml 1.37.0
azure-devops 0.23.0
connectedk8s 1.2.0
hack 0.4.3
ip-group 0.1.2
application-insights 0.1.14
dev-spaces 1.0.6
powerbidedicated 0.2.1
express-route-cross-connection 0.1.1
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@Maheshk-MSFT Looks like you are using a very old version of the `aks-preview` extension. Could you update to the latest and try again by running this command?

```sh
az extension update --name aks-preview
```
