### ISSUE TITLE
`az interactive` fails to start: ModuleNotFoundError: No module named 'prompt_toolkit.interface'

### ISSUE THREAD

**Issue by dagnello** [Azure/azure-cli#24213]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/davide.agnello/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/Users/davide.agnello/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
macOS-12.5.1-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0

Extensions:
interactive 0.4.5

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
interactive

**Comment by taoyama** [comment]
same here

**Comment by taoyama** [comment]
## Environment Summary
```
Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.41.0

Extensions:
interactive 0.4.5

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by taoyama** [comment]
@jiasli 

prompt_toolkit module is installed under  `/usr/lib64/az/lib/python3.9/site-packages/` by azure-cli 2.41.0 package.
```
$ PYTHONPAPYTHONPATH=/usr/lib64/az/lib/python3.9/site-packages/ /usr/bin/python3.9 \
-c "import sys; sys.path; import prompt_toolkit; import prompt_toolkit.interface"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

Remove it will fix the issue.
```
$ sudo rm -rf /usr/lib64/az/lib/python3.9/site-packages/prompt_toolkit

$ az interactive
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

az>>
```

**Comment by bebound** [comment]
In https://github.com/Azure/azure-cli/pull/22459, `mycli` is added in dependency, which requires `prompt-toolkit`.
`azure-cli` installs `3.0.31` and `interactive` wants `1.0.18`, so the conflict occurs.

**Comment by dagnello** [comment]
> @jiasli
> 
> prompt_toolkit module is installed under `/usr/lib64/az/lib/python3.9/site-packages/` by azure-cli 2.41.0 package.
> 
> ```
> $ PYTHONPAPYTHONPATH=/usr/lib64/az/lib/python3.9/site-packages/ /usr/bin/python3.9 \
> -c "import sys; sys.path; import prompt_toolkit; import prompt_toolkit.interface"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'prompt_toolkit.interface'
> ```
> 
> Remove it will fix the issue.
> 
> ```
> $ sudo rm -rf /usr/lib64/az/lib/python3.9/site-packages/prompt_toolkit
> 
> $ az interactive
> This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
> 
> az>>
> ```

@taoyama your suggestion worked, thanks!

**Comment by bebound** [comment]
`interactive` uses an ancient version of `prompt_toolkit` which is not compatible with latest cli.

As a workaround, you need to uninstall `prompt-toolkit` from azure-cli. **This may break other command, use it at your own risk**.
For yum user, following taoyama's solution above.
For apt user, ` /opt/az/bin/python3 -m pip uninstall prompt_toolkit`

**Comment by yonzhan** [comment]
This issue should be fixed by service connector team and will roll out on 11.1.2022. https://github.com/Azure/azure-cli/pull/24268
