### ISSUE TITLE
Error running "Fail to pull images from Azure Container Registry to Azure Kubernetes Service cluster"

### ISSUE THREAD

**Issue by wangchi16** [Azure/azure-cli#24231]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2400, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --resource-group {} --name {} --acr {}`

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0 *

Extensions:
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@wangchi16 Duplicate of #24190

As mentioned in the other issue, could you share the output of `kubectl version -o json` from the same terminal where you are running the `az` command from?

**Comment by wangchi16** [comment]
![Screenshot 2022-10-21 093900](https://user-images.githubusercontent.com/23097409/197091040-e58457d7-96ff-4c6c-a748-ef36f33c3ddb.png)

**Comment by Rabosa616** [comment]
Any news?

**Comment by mbifeld** [comment]
@wangchi16 @Rabosa616 Checking in on this issue. Is this issue still occurring for you?

**Comment by mbifeld** [comment]
Closing as outdated based on no response from the original author. Please reopen / tag me if this issue is still present. Thank you.
