### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by kaitaklam** [Azure/azure-cli#24275]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05FAB2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 96, in create_connection
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 86, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 696, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 964, in _prepare_proxy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x05FAB2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 783, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05FAB2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 112, in _msal_app
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1629, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 489, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 102, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 162, in tenant_discovery
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/individual_cache.py", line 269, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 555, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05FAB2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0
```

**Comment by yonzhan** [comment]
Please go through this issue and see if it helps
https://github.com/Azure/azure-cli/issues/21514

**Comment by kaitaklam** [comment]
nslookup login.microsoftonline.com
giving:
Addresses:  20.190.159.4
          20.190.159.71
          20.190.159.73
          40.126.31.73
          20.190.159.23
          20.190.159.0
          20.190.159.75
          20.190.159.2
Aliases:  login.microsoftonline.com
          ak.privatelink.msidentity.com

so nslookup works.

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/11829. Looks like some network issue.

Per the error message:

> requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05FAB2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

This seems to be connection issue. Could you run this command to see if you can connect to `https://login.microsoftonline.com`?

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

If not, you will need to check the proxy to make `https://login.microsoftonline.com/` accessible.

**Comment by kaitaklam** [comment]
See here the complete session:
- first I am able to run curl to https://login.microsoftonline.com
- then run az login and it failed.
- Can you tell how to configure the proxy for az on Windows 10?


Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
                                                                                                                        Try the new cross-platform PowerShell https://aka.ms/pscore6                                                                                                                                                                                    PS C:\Users\lamkt> curl                                       
cmdlet Invoke-WebRequest at command pipeline position 1
Supply values for the following parameters:
Uri: https://login.microsoftonline.com


StatusCode        : 200
StatusDescription : OK
Content           :

                    
                    <!DOCTYPE html>
                    <html dir="ltr" class="" lang="en">
                    <head>
                        <title>Sign in to your account</title>
                        <meta http-equiv="...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    X-Content-Type-Options: nosniff
                    X-Frame-Options: DENY
                    Link: <https://aadcdn.msftauth.net>; rel=prec...
Forms             : {}
Headers           : {[Pragma, no-cache], [Strict-Transport-Security, max-age=31536000; includeSubDomains],
                    [X-Content-Type-Options, nosniff], [X-Frame-Options, DENY]...}
Images            : {@{innerHTML=; innerText=; outerHTML=<img class="logo" role="img" alt="Microsoft" src="https://aadc
                    dn.msftauth.net/shared/1.0/content/images/microsoft_logo_ee5c8d9fb6248c938fd0dc19370e90bd.svg"
                    data-bind="imgSrc, attr: { alt: str['MOBILE_STR_Footer_Microsoft'] }" svgsrc="https://aadcdn.msftau
                    th.net/shared/1.0/content/images/microsoft_logo_ee5c8d9fb6248c938fd0dc19370e90bd.svg" pngsrc="https
                    ://aadcdn.msftauth.net/shared/1.0/content/images/microsoft_logo_ed9c9eb0dce17d752bedea6b5acda6d9.pn
                    g">; outerText=; tagName=IMG; class=logo; role=img; alt=Microsoft; src=https://aadcdn.msftauth.net/
                    shared/1.0/content/images/microsoft_logo_ee5c8d9fb6248c938fd0dc19370e90bd.svg; data-bind=imgSrc,
                    attr: { alt: str['MOBILE_STR_Footer_Microsoft'] }; svgsrc=https://aadcdn.msftauth.net/shared/1.0/co
                    ntent/images/microsoft_logo_ee5c8d9fb6248c938fd0dc19370e90bd.svg; pngsrc=https://aadcdn.msftauth.ne
                    t/shared/1.0/content/images/microsoft_logo_ed9c9eb0dce17d752bedea6b5acda6d9.png}}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="i19" type="hidden" value="" data-bind="value:
                    timeOnPage">; outerText=; tagName=INPUT; name=i19; type=hidden; value=; data-bind=value:
                    timeOnPage}}
Links             : {@{innerHTML=Terms of use; innerText=Terms of use; outerHTML=<a class="footer-content
                    ext-footer-content footer-item ext-footer-item" id="ftrTerms"
                    href="https://www.microsoft.com/en-US/servicesagreement/" data-bind="&#10;            text:
                    termsText,&#10;            href: termsLink,&#10;            click: termsLink_onClick,&#10;
                       externalCss: {&#10;                'footer-content': true,&#10;                'footer-item':
                    true,&#10;                'has-background': !useDefaultBackground,&#10;
                    'background-always-visible': hasDarkBackground }">Terms of use</a>; outerText=Terms of use;
                    tagName=A; class=footer-content ext-footer-content footer-item ext-footer-item; id=ftrTerms;
                    href=https://www.microsoft.com/en-US/servicesagreement/; data-bind=&#10;            text:
                    termsText,&#10;            href: termsLink,&#10;            click: termsLink_onClick,&#10;
                       externalCss: {&#10;                'footer-content': true,&#10;                'footer-item':
                    true,&#10;                'has-background': !useDefaultBackground,&#10;
                    'background-always-visible': hasDarkBackground }}, @{innerHTML=Privacy &amp; cookies;
                    innerText=Privacy & cookies; outerHTML=<a class="footer-content ext-footer-content footer-item
                    ext-footer-item" id="ftrPrivacy" href="https://privacy.microsoft.com/en-US/privacystatement"
                    data-bind="&#10;            text: privacyText,&#10;            href: privacyLink,&#10;
                    click: privacyLink_onClick,&#10;            externalCss: {&#10;                'footer-content':
                    true,&#10;                'footer-item': true,&#10;                'has-background':
                    !useDefaultBackground,&#10;                'background-always-visible': hasDarkBackground
                    }">Privacy &amp; cookies</a>; outerText=Privacy & cookies; tagName=A; class=footer-content
                    ext-footer-content footer-item ext-footer-item; id=ftrPrivacy;
                    href=https://privacy.microsoft.com/en-US/privacystatement; data-bind=&#10;            text:
                    privacyText,&#10;            href: privacyLink,&#10;            click: privacyLink_onClick,&#10;
                             externalCss: {&#10;                'footer-content': true,&#10;
                    'footer-item': true,&#10;                'has-background': !useDefaultBackground,&#10;
                       'background-always-visible': hasDarkBackground }}, @{innerHTML=...; innerText=...; outerHTML=<a
                    class="footer-content ext-footer-content footer-item ext-footer-item debug-item ext-debug-item"
                    id="moreOptions" role="button" aria-expanded="false" aria-label="Click here for troubleshooting
                    information" href="#" data-bind="&#10;        click: moreInfo_onClick,&#10;        ariaLabel:
                    str['CT_STR_More_Options_Ellipsis_AriaLabel'],&#10;        attr: { 'aria-expanded':
                    showDebugDetails().toString() },&#10;        hasFocusEx: focusMoreInfo(),&#10;        externalCss:
                    {&#10;            'footer-content': true,&#10;            'footer-item': true,&#10;
                    'debug-item': true,&#10;            'has-background': !useDefaultBackground,&#10;
                    'background-always-visible': hasDarkBackground }">...</a>; outerText=...; tagName=A;
                    class=footer-content ext-footer-content footer-item ext-footer-item debug-item ext-debug-item;
                    id=moreOptions; role=button; aria-expanded=false; aria-label=Click here for troubleshooting
                    information; href=#; data-bind=&#10;        click: moreInfo_onClick,&#10;        ariaLabel:
                    str['CT_STR_More_Options_Ellipsis_AriaLabel'],&#10;        attr: { 'aria-expanded':
                    showDebugDetails().toString() },&#10;        hasFocusEx: focusMoreInfo(),&#10;        externalCss:
                    {&#10;            'footer-content': true,&#10;            'footer-item': true,&#10;
                    'debug-item': true,&#10;            'has-background': !useDefaultBackground,&#10;
                    'background-always-visible': hasDarkBackground }}}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 200999



PS C:\Users\lamkt> az login
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x047F8490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 96, in create_connection
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 86, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 696, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 964, in _prepare_proxy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x047F8490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 783, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x047F8490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 112, in _msal_app
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1629, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 489, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 102, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 162, in tenant_discovery
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/individual_cache.py", line 269, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 555, in get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x047F8490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
To open an issue, please run: 'az feedback'
PS C:\Users\lamkt>

**Comment by kaitaklam** [comment]
fixed by setting HTTP_PROXY and HTTPS_PROXY in environment

**Comment by IgorTTenorio** [comment]
hello @kaitaklam i'm facing a similar issue, could you please be so kind and specify a bit what you mean with setting HTTP_PROXY and HTTPS_PROXY? Many thanks!
