### ISSUE TITLE
ComputeManagementClientConfiguration' object has no attribute 'api_version'

### ISSUE THREAD

**Issue by jfsimoneau** [Azure/azure-cli#24295]
## Describe the bug

**Command Name**
`az image list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ComputeManagementClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/compute/v2022_08_01/operations/_images_operations.py", line 951, in get_next
    request = prepare_request(next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/compute/v2022_08_01/operations/_images_operations.py", line 936, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image list`

## Expected Behavior
Returns the list of images.

## Environment Summary
```
Linux-5.14.0-1054-oem-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0
```

**Comment by RakeshMohanMSFT** [comment]
@jfsimoneau We are unable to reproduce this issue at our end, even in a similar environment. Can you please try to uninstall and reinstall Azure cli and retry please?

![image](https://user-images.githubusercontent.com/49954584/196843892-b4dea732-7fee-480d-8679-ca861b753a71.png)

**Comment by prbobba** [comment]
We are facing the same issue when running list command for Disk Encryption sets

```
prbobba-a04:~ prbobba$ az disk-encryption-set list
The command failed with an unexpected error. Here is the traceback:
'ComputeManagementClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/v2022_03_02/operations/_disk_encryption_sets_operations.py", line 1020, in get_next
    request = prepare_request(next_link)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/v2022_03_02/operations/_disk_encryption_sets_operations.py", line 1005, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'api_version'
```

Listing images is working correctly for me. 

I am using latest azure-cli

```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by jfsimoneau** [comment]
Seems related to https://github.com/Azure/azure-cli/issues/24187#issuecomment-1278384023. I'll close this.
