### ISSUE TITLE
az image copy - Not working between RGs in the same subscription

### ISSUE THREAD

**Issue by tang81** [Azure/azure-cli#24291]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```

Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
                    

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {} --account-name {} --output {}`

## Environment Summary
```
Linux-5.15.0-50-generic-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
image-copy-extension 0.2.9

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by evelyn-ys** [comment]
Have you run `az login` before `az storage container create`?

If you don't specify `--account-key` or `--sas-token` or `--connection-string`, you need to login first for authentication

**Comment by tang81** [comment]
Hi @evelyn-ys, Actually I was trying to copy a VM image to another resource group using the command `az image copy`. I'm logged into the azure account by `az login`

The run command was. `az image copy --source-resource-group ***** --source-object-name ****-Image-20221017 --target-location eastus --target-resource-group *****`

Te following error was reached:

```
Getting OS disk ID of the source VM/image
Creating source snapshot
Getting sas url for the source snapshot with timeout: 3600 seconds
Target location count: 1
eastus - Creating target storage account (can be slow sometimes)
eastus - Creating container in the target storage account
command failed: ['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'container', 'create', '--name', 'snapshots', '--account-name', 'eastuses6wjpfw26crv7qib6', '--output', 'json']
output: ERROR: 
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
                    

The command failed with an unexpected error. Here is the traceback:
Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'container', 'create', '--name', 'snapshots', '--account-name', 'eastuses6wjpfw26crv7qib6', '--output', 'json']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/dtovar/.azure/cliextensions/image-copy-extension/azext_imagecopy/custom.py", line 158, in imagecopy
    create_target_image(cmd, location, transient_resource_group_name, source_type,
  File "/home/dtovar/.azure/cliextensions/image-copy-extension/azext_imagecopy/create_target.py", line 81, in create_target_image
    run_cli_command(cli_cmd)
  File "/home/dtovar/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 45, in run_cli_command
    raise ex
  File "/home/dtovar/.azure/cliextensions/image-copy-extension/azext_imagecopy/cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "/opt/az/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/az/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'azure.cli', 'storage', 'container', 'create', '--name', 'snapshots', '--account-name', 'eastuses6wjpfw26crv7qib6', '--output', 'json']' returned non-zero exit status 1.
```
Seems an auth error but az cli is authenticated with an administratos user (used for IaC)

Regards!

**Comment by tang81** [comment]
UPDATE

I tried also using ubuntu 18.04 and got the same error as 22.04.

Then I tried using CentOS 7 and finally I was able to copy the image using the next environment:

## Environment Summary
```
Linux-5.15.0-50-generic-x86_64-with-centos-7.5.1804-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: RPM

azure-cli 2.38.0 *

Extensions:
image-copy-extension 0.2.9

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
From my perspective, seems an error with `python 3.10`, could you please take a look, @evelyn-ys?

Regards!

**Comment by tang81** [comment]
Hi, any update on this?

**Comment by evelyn-ys** [comment]
@zhoxing-ms Can you take a look? These are all commands from VM module

**Comment by zhoxing-ms** [comment]
> Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/core/_enum_meta.py", line 59, in __getattr__
    return cls._member_map_[name.upper()]
KeyError: 'IMPORT_ENUM'

This should be the same issue as https://github.com/Azure/azure-cli/issues/24263
