### ISSUE TITLE
Unable to stop node pool

### ISSUE THREAD

**Issue by kGetchAuthenticx** [Azure/azure-cli#24331]
## Describe the bug

**Command Name**
`az aks nodepool stop`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerServiceClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2111, in aks_agentpool_stop
    for agentpool_profile in instances:
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_agent_pools_operations.py", line 406, in get_next
    request = prepare_request(next_link)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_agent_pools_operations.py", line 391, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool stop --nodepool-name {} --resource-group {} --cluster-name {} --no-wait`

## Environment Summary
```
Linux-5.4.0-1094-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.41.0

Extensions:
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by PramodValavala-MSFT** [comment]
@kGetchAuthenticx This has been fixed as part of this PR - #24270 - and should be available in the next release. In the meantime, the workaround would be to downgrade to version `2.4.0`.
