### ISSUE TITLE
az login (got an unexpected keyword argument 'allow_broker')

### ISSUE THREAD

**Issue by tazz007** [Azure/azure-cli#24372]
## Describe the bug

**Command Name**
`az ad signed-in-user show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/commands.py", line 51, in graph_err_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 1803, in show_signed_in_user
    result = client.signed_in_user_get()
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 224, in signed_in_user_get
    result = self._send("GET", "/me")
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/usr/lib/python3/dist-packages/azure/cli/core/util.py", line 990, in send_raw_request
    token_info, _, _ = profile.get_raw_token(resource)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 382, in get_raw_token
    credential = self._create_credential(account, tenant)
  File "/usr/lib/python3/dist-packages/azure/cli/core/_profile.py", line 592, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/identity.py", line 224, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/auth/msal_authentication.py", line 39, in __init__
    super().__init__(client_id, **kwargs)
  File "/usr/lib/python3/dist-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad signed-in-user show -o={}`

## Environment Summary
```
Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.7
Installer: DEB

azure-cli 2.41.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by sean-keane25** [comment]
I am experiencing the same issue.

**Comment by dr-1** [comment]
For me the issue went away when upgrading the msal package from version 1.18.0b1 to version 1.20.0.
`pip install --upgrade msal`

**Comment by RakeshMohanMSFT** [comment]
@tazz007 and @sean-keane25 can you try this command as suggested by @dr-1 `pip install --upgrade msal` and see if that helps?
