### ISSUE TITLE
`az container export` to YAML fails if there is a user-assigned identity

### ISSUE THREAD

**Issue by lynshi** [Azure/azure-cli#24380]
## Describe the bug

EDIT: Strikethrough for references to ACI creation from YAML, which now works after I copied an example.

`az container` does not handle `UserAssignedIdentities` in YAML during export. ~~Errors occur both during container creation and container export. I will describe the container export issue as that is easier to reproduce.~~

**Command Name**
`az container export`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('cannot represent an object', <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.IdentityUserAssignedIdentitiesValue object at 0x7f1a6a27bb20>)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 633, in container_export
    yaml.safe_dump(resource, f, default_flow_style=False)
  File "/opt/az/lib/python3.10/site-packages/yaml/__init__.py", line 269, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/opt/az/lib/python3.10/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/opt/az/lib/python3.10/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <azure.mgmt.resource.resources.v2021_04_01.models._models_py3.IdentityUserAssignedIdentitiesValue object at 0x7f1a6a27bb20>)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Note that `userID` is set following the instructions in the [Deploy to Azure Container Instances from Azure Container Registry using a managed identity](https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#create-an-identity).

1. Create the container.
```bash
az container create \
	--name $aciName \
	--resource-group $resourceGroup \
	--image $privateACR/aci-helloworld:latest \
	--acr-identity $userID \
	--assign-identity $userID \
	--ports 80 \
	--dns-name-label $dnsLabelName
```

2. Export to YAML.
```bash
az container export --output yaml --name $aciName -g $resourceGroup --output.yaml
```

## Expected Behavior
A YAML file that can be used to recreate the container should be successfully exported.

## Environment Summary
```
Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
account 0.2.5
aks-preview 0.5.104
azure-devops 0.25.0
confcom 0.1.2
confidentialledger 1.0.0
subscription 0.1.5
confidentialledger 1.0.0 (dev) /home/lyshi/repos/azure-cli-extensions/src/confidentialledger

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
_Please disregard this section, preserving it so the error string is searchable._

~~As mentioned above, YAML does not work for `az container create` either. In a YAML file that contains a [ContainerGroupIdentity object](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml#containergroupidentity-object), I have the following:~~
```yaml
identity:
  type: UserAssigned
  userAssignedIdentities:
  - "/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>"
```

~~After running `az container create --resource-group $resourceGroup --file input.yaml`, I got the following error:~~
```
The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: ("Unable to deserialize response data. Data: [\'/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>\'], {IdentityUserAssignedIdentitiesValue}, TypeError: string indices must be integers", TypeError(\'string indices must be integers\')), DeserializationError: ("Unable to deserialize response data. Data: [\'/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>\'], {IdentityUserAssignedIdentitiesValue}, TypeError: string indices must be integers", TypeError(\'string indices must be integers\'))', DeserializationError("Unable to deserialize response data. Data: ['/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>'], {IdentityUserAssignedIdentitiesValue}, TypeError: string indices must be integers", TypeError('string indices must be integers')))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1668, in deserialize_dict
    return {x['key']: self.deserialize_data(x['value'], dict_type) for x in attr}
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 1668, in <dictcomp>
    return {x['key']: self.deserialize_data(x['value'], dict_type) for x in attr}
TypeError: string indices must be integers
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@macolso Could you please look into this once you get a chance ?

**Comment by lynshi** [comment]
@navba-MSFT looks like that person no longer works at Microsoft

**Comment by lynshi** [comment]
Okay, I stumbled across an example of how to use `userAssignedIdentities` in [Enable managed identity using YAML file](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-managed-identity#enable-managed-identity-using-yaml-file).

```yaml
identity:
  type: UserAssigned
  userAssignedIdentities:
    {
      '/subscriptions/<SUB ID>/resourcegroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>': {},
      "/subscriptions/<SUB ID>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY NAME>": {}
    }
```

So, I am at least able to create an ACI using user-assigned identity from a YAML file. However, this doesn't resolve the `export` command issue.

**Comment by lynshi** [comment]
@yonzhan @navba-MSFT were you able to repro or find someone to assign this to?

**Comment by zhoxing-ms** [comment]
@joseph-porter Could you please help take look at the container related issue?

**Comment by sam-cogan** [comment]
Any update on this? Seems we still cannot export YAML for a container with a user assigned MI

**Comment by navba-MSFT** [comment]
@sam-cogan @lynshi  A PR has been created https://github.com/Azure/azure-cli/pull/24833 to fix this. It is currently under review. I am following up with the product owners to review that PR and I will update this thread.

**Comment by pregress** [comment]
This can be closed, is fixed in the latest versions
