### ISSUE TITLE
az vm list error

### ISSUE THREAD

**Issue by agm83** [Azure/azure-cli#24441]
## Describe the bug

Unable to list vms using azure cli

**Command Name**
`az vm list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ComputeManagementClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 1381, in list_vm
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/compute/v2022_08_01/operations/_virtual_machines_operations.py", line 2254, in get_next
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/compute/v2022_08_01/operations/_virtual_machines_operations.py", line 2239, in prepare_request
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'api_version'

## To Reproduce:
run command : az vm list

{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-firewall": "0.14.4",
    "desktopvirtualization": "0.2.0",
    "ip-group": "0.1.2"
  }
}

## Expected Behavior

should list vms

## Environment Summary
```
Windows 11 21H2 (OS Build 22000.1098)
PowerShell 7.2.6

{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-firewall": "0.14.4",
    "desktopvirtualization": "0.2.0",
    "ip-group": "0.1.2"
  }
}

Extensions:
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-firewall",
    "path": "C:\\Users\\username\\.azure\\cliextensions\\azure-firewall",
    "preview": true,
    "version": "0.14.4"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "desktopvirtualization",
    "path": "C:\\Users\\username\\.azure\\cliextensions\\desktopvirtualization",
    "preview": false,
    "version": "0.2.0"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ip-group",
    "path": "C:\\Users\\username\\.azure\\cliextensions\\ip-group",
    "preview": true,
    "version": "0.1.2"
  }
]

**Comment by yonzhan** [comment]
Since it is repeated with issue https://github.com/Azure/azure-cli/issues/24187, so I will close the issue first. We will focus on issue https://github.com/Azure/azure-cli/issues/24187 for discussion
