### ISSUE TITLE
az storage account show-connection-string failing after upgrade to azure-cli 2.42.0

### ISSUE THREAD

**Issue by andysbolton** [Azure/azure-cli#24528]
**Related command**

`az storage account show-connection-string`

**Describe the bug**

`az storage account show-connection-string` seems to fail after an upgrade to azure-cli 2.42.0 (but works if downgraded to 2.41.0).

Output is: 
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/account.py", line 293, in show_storage_account_connection_string
    obj = scf.list_keys(resource_group_name, account_name, logging_enable=False)  # pylint: disable=no-member
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 1312, in list_keys
    request = build_list_keys_request(
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 319, in build_list_keys_request
    "resourceGroupName": _SERIALIZER.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\w\._\(\)]+$'),
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute
```

**To Reproduce**

Seems to happen when running any variation of `az storage account show-connection-string --name $ACCOUNT`.

**Expected behavior**

No failure/returns the connection string.

**Environment summary**

Happens on both Windows (installed via Chocolatey and upgraded through the CLI) and Debian (installed via apt-get).

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Please add `-g $resource_group_name` as a workaround. Will figure out the route cause and update later

**Comment by cizordj** [comment]
@evelyn-ys Sorry if it's a dumb question but where can I get the group name? I've with `az storage account list` but I have no clue.

**Comment by evelyn-ys** [comment]
By running `az storage account show -n $accountName`, you can get the resource id in the format of `/subscriptions/$subId/resourceGroups/$resourceGroupName/providers/Microsoft.Storage/storageAccounts/$accountName`.

You can find the resource group name there

**Comment by jmshal** [comment]
Is there any update on this issue? My team has just started seeing our deployments fail due to this, as Azure Pipelines has updated the CLI that comes pre-installed on the hosted agents. The workaround is non-trivial for us to implement reasonably quickly.

**Comment by evelyn-ys** [comment]
The fix PR https://github.com/Azure/azure-cli/pull/24531 has been merged. The next release would be 12/6. Sorry for the inconvenience.

**Comment by evelyn-ys** [comment]
It may take some time for Devops to adopt latest CLI. We CLI team can't control this schedule😂

**Comment by ishepherd** [comment]
Confirming Azure DevOps has now rolled out the fixed version. Happened sometime in the period 12-19 Dec. Thanks
