### ISSUE TITLE
Bastion native client - API Version conflict

### ISSUE THREAD

**Issue by jpfarhadian** [Azure/azure-cli#24540]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2017-10-01 does not have operation group 'bastion_hosts'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/azure_stack/custom.py", line 8426, in rdp_bastion_host
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/network/_network_management_client.py", line 1134, in bastion_hosts
ValueError: API version 2017-10-01 does not have operation group 'bastion_hosts'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0

Extensions:
account 0.2.3
interactive 0.4.5
managementpartner 0.1.3
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jpfarhadian Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@jpfarhadian We are unable to reproduce this issue at our end. Can you please try to reinstall Az cli once and retry?

**Comment by jpfarhadian** [comment]
That is strange : here is what I'm getting - (I have done complete Uninstall - reboot - Install Latest CLI Versiom)
 az network bastion rdp --name "HM-Bastion" --resource-group "Bastion-RG" --target-resource-id "/subscriptions/d3017c91-b341-493c-a153-e684856479e8/resourceGroups/HM-Client-Dev-RG2/providers/Microsoft.Compute/virtualMachines/VM-MP"
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
API version 2017-10-01 does not have operation group 'bastion_hosts'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/azure_stack/custom.py", line 8426, in rdp_bastion_host
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/network/_network_management_client.py", line 1134, in bastion_hosts
ValueError: API version 2017-10-01 does not have operation group 'bastion_hosts'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by jpfarhadian** [comment]
does it have dependency on specific Phyton version ? I have version 3.10.8
