### ISSUE TITLE
az cloud set -n AzureCloud" is fails intermittently. 

### ISSUE THREAD

**Issue by talktovishal** [Azure/azure-cli#24545]
## Describe the bug
az cloud set -n AzureCloud" is failing intermittently. 

**Command Name**
`az cloud set -n AzureCloud" is failing intermittently. `

**Errors:**
```

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument _subcommand: conflicting subparser: set
To open an issue, please run: 'az feedback'
##[error]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument _subcommand: conflicting subparser: set
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    self.parser.load_command_table(self.commands_loader)
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/azure/cli/core/parser.py", line 100, in load_command_table
    command_parser = subparser.add_parser(command_verb,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument _subcommand: conflicting subparser: set
To open an issue, please run: 'az feedback'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0 *

Extensions:
ml 2.1.2

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
az cloud set

**Comment by bebound** [comment]
I don't why it happens but you're using python 3.11 to executed command.
3.11 is not supported yet. See https://github.com/Azure/azure-cli/issues/24494

You need to check your cli installation.
