### ISSUE TITLE
az network bastion tunnel crashes

### ISSUE THREAD

**Issue by tobimax** [Azure/azure-cli#24564]
## Describe the bug

**Command Name**
`az network bastion tunnel`

**Errors:**
```Opening tunnel on port: 53608
Tunnel is ready, connect on port 53608
Ctrl + C to close
Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8430, in _start_tunnel
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 184, in start_server
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 117, in _listen
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
msrestazure.azure_exceptions.CloudError: Unexpected internal error
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion tunnel --name 'xxx' --resource-group 'xxx' --target-resource-id 'xxx' --resource-port 3389 --port 53608`
- Open RDP to localhost:53608

## Expected Behavior

Native RDP Connects

## Environment Summary
```
Windows-10-10.0.20348-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by tobimax** [comment]
I have updated my CLI and its working again.

**Comment by elfazzz** [comment]
I have the same issue with Linux azure-cli, 2.44.1

- Create tunnel:

```
╰> az network bastion tunnel --name ${BASTION} --resource-group ${BRG} --target-resource-id ${RID} --resource-port 80 --port 8080
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Opening tunnel on port: 8080
Tunnel is ready, connect on port 8080
Ctrl + C to close
```


- Launch a connection test from another terminal:

```
╰> nc -v localhost 8080
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
```


- Error + tunnel crash as soon as connection test is launched:

```
Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8404, in _start_tunnel
    tunnel_server.start_server()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 184, in start_server
    self._listen()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 117, in _listen
    auth_token = self._get_auth_token()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
    raise exp
msrestazure.azure_exceptions.CloudError: Unexpected internal error
```


Target resource ID that I used here is a container instance. I got an "nc -l 80" running in it, port redirection is enabled in CI.
