### ISSUE TITLE
the following arguments are required: --applied-scope-type/-t

### ISSUE THREAD

**Issue by ThierryVanacker-TomTom** [Azure/azure-cli#24575]
Dear,
According to the documentation the --applied-scope-type/-t param is optional when running "az reservations reservation update" however when I try to update a name for a reservation (using az reservations reservation update --reservation-id [guid] --reservation-order-id [guid] --name [newname]) I get an error "the following arguments are required: --applied-scope-type/-t"
Am I missing something?
Regards,
Thierry
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63965398-b60e-9846-10e6-501eb6a87e94
* Version Independent ID: b30fdc30-2faa-6a50-6da2-de42c06ccc83
* Content: [az reservations reservation](https://learn.microsoft.com/en-us/cli/azure/reservations/reservation?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/reservations/reservation.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/reservations/reservation.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ThierryVanacker-TomTom Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ThierryVanacker-TomTom  We are unable to reproduce this issue at our end. Can you please share the debug trace and the environment details? using `az reservations reservation update --applied-scope-type Shared --reservation-id 10000000-aaaa-bbbb-cccc-200000000001 --reservation-order-id 50000000-aaaa-bbbb-cccc-200000000005 --debug` and `az --version`

**Comment by ThierryVanacker-TomTom** [comment]
Dear,

Aplogies for the late reply, please find below the requested output

Regards,
Thierry Van Acker



PS C:\Users\ldap_un> az --version
azure-cli                         2.20.0 *

core                              2.20.0 *
telemetry                          1.0.6

Extensions:
costmanagement                     0.1.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\vanacket\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy



PS C:\Users\ldap_un> az reservations reservation update --reservation-id 090d0b4a-9ac4-4e4a-9d8e-8ab369c787cb --reservation-order-id 416ffd77-76b2-42bf-b840-4b7f4bbda403 --name Shared_VM_RI_04-14-2020_17-44 --debug
cli.knack.cli: Command arguments: ['reservations', 'reservation', 'update', '--reservation-id', '090d0b4a-9ac4-4e4a-9d8e-8ab369c787cb', '--reservation-order-id', '416ffd77-76b2-42bf-b840-4b7f4bbda403', '--name', 'Shared_VM_RI_04-14-2020_17-44', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x030AAAE0>, <function OutputProducer.on_global_arguments at 0x030FDF60>, <function CLIQuery.on_global_arguments at 0x0315FED0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'reservations': ['azure.cli.command_modules.reservations']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: reservations              0.016         5        12
cli.azure.cli.core: Total (1)                 0.016         5        12
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 5 groups, 12 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : reservations reservation update
cli.azure.cli.core: Command table: reservations reservation update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0346B1E0>]
az_command_data_logger: command args: reservations reservation update --reservation-id {} --reservation-order-id {} --name {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\vanacket\.azure\commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x034C7DB0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x034D1540>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x034D1588>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x034D1618>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 540, in _get_azure_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 535, in get_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 509, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 57, in _decorator
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 530, in _get_user_azure_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 511, in get_current_account_user
knack.util.CLIError: There are no active accounts.

cli.azure.cli.core.command_recommender: "--name" is an invalid parameter for command "reservations reservation update".
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22reservations+reservation+update%22%2C+%22parameters%22%3A+%22--reservation-id%2C--reservation-order-id%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.20.0%22%2C+%22errorType%22%3A+%22MissingRequiredParameters%22%2C+%22correlationId%22%3A+%22274f1b4a-645f-4f79-8a9c-a1e9cb34710c%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.command_recommender: "--name" is an invalid parameter for command "reservations reservation update".
cli.azure.cli.core.azclierror: the following arguments are required: --applied-scope-type/-t
cli.azure.cli.core.azclierror: the following arguments are required: --applied-scope-type/-t

TRY THIS:
https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0346B300>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 1.399 seconds (init: 0.238, invoke: 1.160)
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 60, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 48, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 35, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 250, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 585, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\parser.py", line 262, in parse_args
  File "argparse.py", line 1734, in parse_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 2001, in _parse_known_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 181, in error
  File "argparse.py", line 2380, in exit
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 509, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 57, in _decorator
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 530, in _get_user_azure_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 511, in get_current_account_user
knack.util.CLIError: There are no active accounts.

cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 60, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 48, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 35, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 250, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 585, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\parser.py", line 262, in parse_args
  File "argparse.py", line 1734, in parse_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 1954, in _parse_known_args
  File "argparse.py", line 1931, in consume_positionals
  File "argparse.py", line 1840, in take_action
  File "argparse.py", line 1137, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 287, in parse_known_args
  File "argparse.py", line 1766, in parse_known_args
  File "argparse.py", line 2001, in _parse_known_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 181, in error
  File "argparse.py", line 2380, in exit
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 540, in _get_azure_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 535, in get_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

telemetry.save: Save telemetry record of length 2965 in cache
telemetry.check: Negative: The C:\Users\vanacket\.azure\telemetry.txt was modified at 2022-11-17 22:54:55.877338, which in less than 600.000000 s



PS C:\Users\ldap_un> az reservations reservation update --applied-scope-type Shared --reservation-id 090d0b4a-9ac4-4e4a-9d8e-8ab369c787cb --reservation-order-id 416ffd77-76b2-42bf-b840-4b7f4bbda403 --name Shared_VM_RI_04-14-2020_17-44 --debug
cli.knack.cli: Command arguments: ['reservations', 'reservation', 'update', '--applied-scope-type', 'Shared', '--reservation-id', '090d0b4a-9ac4-4e4a-9d8e-8ab369c787cb', '--reservation-order-id', '416ffd77-76b2-42bf-b840-4b7f4bbda403', '--name', 'Shared_VM_RI_04-14-2020_17-44', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x030DAAE0>, <function OutputProducer.on_global_arguments at 0x0322DF60>, <function CLIQuery.on_global_arguments at 0x0328FED0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'reservations': ['azure.cli.command_modules.reservations']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: reservations              0.007         5        12
cli.azure.cli.core: Total (1)                 0.007         5        12
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 5 groups, 12 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : reservations reservation update
cli.azure.cli.core: Command table: reservations reservation update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x034BB1E0>]
az_command_data_logger: command args: reservations reservation update --applied-scope-type {} --reservation-id {} --reservation-order-id {} --name {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\vanacket\.azure\commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03517DB0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03521540>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03521588>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03521618>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 540, in _get_azure_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 535, in get_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 509, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 57, in _decorator
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 530, in _get_user_azure_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 511, in get_current_account_user
knack.util.CLIError: There are no active accounts.

cli.azure.cli.core.command_recommender: "--name" is an invalid parameter for command "reservations reservation update".
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22reservations+reservation+update%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.20.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%222cb1947e-9fd3-48e1-99d4-0da5dab8a098%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.command_recommender: "--name" is an invalid parameter for command "reservations reservation update".
cli.azure.cli.core.azclierror: unrecognized arguments: --name Shared_VM_RI_04-14-2020_17-44
cli.azure.cli.core.azclierror: unrecognized arguments: --name Shared_VM_RI_04-14-2020_17-44

TRY THIS:
https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x034BB300>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 1.095 seconds (init: 0.235, invoke: 0.860)
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 60, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 48, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 35, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 250, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 585, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\parser.py", line 262, in parse_args
  File "argparse.py", line 1737, in parse_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 181, in error
  File "argparse.py", line 2380, in exit
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 509, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 57, in _decorator
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 530, in _get_user_azure_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 511, in get_current_account_user
knack.util.CLIError: There are no active accounts.

cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 60, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 48, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ibh5mnup\azure\cli\__main__.py", line 35, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 250, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\commands\__init__.py", line 585, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-taryuzhh\knack\parser.py", line 262, in parse_args
  File "argparse.py", line 1737, in parse_args
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\parser.py", line 181, in error
  File "argparse.py", line 2380, in exit
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\telemetry.py", line 540, in _get_azure_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 535, in get_subscription_id
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-sc_lkrar\azure\cli\core\_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

telemetry.save: Save telemetry record of length 2961 in cache
telemetry.check: Negative: The C:\Users\vanacket\.azure\telemetry.txt was modified at 2022-11-17 22:54:55.877338, which in less than 600.000000 s

**Comment by RakeshMohanMSFT** [comment]
@ThierryVanacker-TomTom The CLI version you are using is really old, can you please update it to the latest [2.42.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and retry? also update your python version.

**Comment by ThierryVanacker-TomTom** [comment]
Rakesh,

Thanks for the tip, that did the trick

Thanks,
Thierry
