### ISSUE TITLE
unable to get MSAL authorization token for storage API

### ISSUE THREAD

**Issue by dtotopus** [Azure/azure-cli#24659]
**Related command**
Terraform commands for azurerm provider.
az login also does seem to have issues to login every time.

**Describe the bug**
When executing terraform commands using azurerm provider it takes forever to finish them up or to even start.
In most cases command fails with auth related error:
`│ Error: unable to get MSAL authorization token for storage API: obtaining Authorization Token from the Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
│     httplib_response = self._make_request(
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
│     six.raise_from(e, None)
│   File "<string>", line 3, in raise_from
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
│     httplib_response = conn.getresponse()
│   File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
│     response.begin()
│   File "/opt/az/lib/python3.10/http/client.py", line 318, in begin
│     version, status, reason = self._read_status()
│   File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
│     raise RemoteDisconnected("Remote end closed connection without"
│ http.client.RemoteDisconnected: Remote end closed connection without response
│ 
│ During handling of the above exception, another exception occurred:
│ 
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
│     resp = conn.urlopen(
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
│     retries = retries.increment(
│   File "/opt/az/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
│     raise six.reraise(type(error), error, _stacktrace)
│   File "/opt/az/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
│     raise value.with_traceback(tb)
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
│     httplib_response = self._make_request(
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
│     six.raise_from(e, None)
│   File "<string>", line 3, in raise_from
│   File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
│     httplib_response = conn.getresponse()
│   File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
│     response.begin()
│   File "/opt/az/lib/python3.10/http/client.py", line 318, in begin
│     version, status, reason = self._read_status()
│   File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
│     raise RemoteDisconnected("Remote end closed connection without"
│ urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
│ 
│ During handling of the above exception, another exception occurred:
│ 
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
│     raise ex
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
│     result = cmd_copy(params)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 66, in get_access_token
│     creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     sdk_token = credential.get_token(*scopes)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 63, in get_token
│     result = self.acquire_token_silent_with_error(list(scopes), self._account, claims_challenge=claims, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1287, in acquire_token_silent_with_error
│     result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
│   File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1392, in _acquire_token_silent_from_cache_and_possibly_refresh_it
│     result = _clean_up(self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
│   File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1444, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
│     last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
│   File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1491, in _acquire_token_silent_by_finding_specific_refresh_token
│     response = client.obtain_token_by_refresh_token(
│   File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 830, in obtain_token_by_refresh_token
│     resp = super(Client, self).obtain_token_by_refresh_token(
│   File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 262, in obtain_token_by_refresh_token
│     return self._obtain_token("refresh_token", data=data, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
│     ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 771, in _obtain_token
│     resp = super(Client, self)._obtain_token(
│   File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 234, in _obtain_token
│     resp = (post or self._http_client.post)(
│   File "/opt/az/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
│     value = function(*args, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
│     value = function(*args, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
│     return self.request('POST', url, data=data, json=json, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
│     resp = self.send(prep, **send_kwargs)
│   File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
│     r = adapter.send(request, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 498, in send
│     raise ConnectionError(err, request=request)
│ requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
│ To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
│ To open a new issue, please run `az feedback``

**Expected behavior**
Terraform commands are able to use logged in user info,

**Environment summary**
Linux

**Comment by dtotopus** [comment]
Apparently issue was caused by failed az logins. No idea why it didn't cause immediate auth errors but those cryptic ones , but after eventually logging out and in for a few times ( first attempts did hung up as well by not returning back to the terminal )  terraform started to work fine again.
