### ISSUE TITLE
Issue with az login and az connect to Kubernetes cluster

### ISSUE THREAD

**Issue by vkamani21** [Azure/azure-cli#24658]
## Describe the bug
I'm getting issue with commands like "az login" and az connecting with kubernetes cluster. The issue mentions about the computer timezone here which is synced automatically with the world clock. Can you please help me understand and resolve the issue?

**Command Name**
`az login`
`az aks get-credentials --resource-group Compute-rg-slbSimulation-wstdty --name aks-jhuug4jkx4sgu`

**Errors:**
```
vkamani@DESKTOP-58C3JIA:~$ az aks get-credentials --resource-group Compute-rg-slbSimulation-wstdty --name aks-jhuug4jkx4sgu
The command failed with an unexpected error. Here is the traceback:
0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1668493284.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1668509352,
  "nbf": 1668509352,
  "exp": 1668513252,
  "aio": "AXQAi/8TAAAASzVFUy1yHIU+8qW7aIR3uqxttgsS1xiGCUGPcQL9qPva8orLO3i8PRAukbjyl/gOYHtR9cTw1bzaJQ9DEeYMDhE0BLd13K5zaHX3/TsOa90YkKd033rwBnf0x/mbls3jq+GSIdJVa4w7AxaaKlidCQ==",
  "name": "Vaibhavi Kamani",
  "nonce": "d1a65b433a7e583f7dbf63cbfb13b549245bf3ba762c44b6cf1b5d8fc823114b",
  "oid": "2b92e528-18ff-4852-b3bf-7bd8104ec832",
  "preferred_username": "vkamani@microsoft.com",
  "puid": "10032001C5589438",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaACA.",
  "sub": "7LxyxYmfyAy1on28yjFg8mYYT7UTxRtmD_ARuKNXpCA",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "AKQJpkN7SEaelQ4VW04nAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 2207, in aks_get_credentials
    credentialResults = client.list_cluster_user_credentials(
  File "/opt/az/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/mgmt/containerservice/v2022_02_01/operations/_managed_clusters_operations.py", line 1221, in list_cluster_user_credentials
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/opt/az/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/auth/credential_adaptor.py", line 65, in get_token
    token, _ = self._get_token(scopes, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/auth/credential_adaptor.py", line 38, in _get_token
    token = self._credential.get_token(*scopes, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/auth/msal_authentication.py", line 60, in get_token
    result = self.acquire_token_silent_with_error(list(scopes), self._account, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1135, in acquire_token_silent_with_error
    result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1220, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    result = _clean_up(self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1259, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1306, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 831, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 263, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oauth2.py", line 789, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.8/site-packages/msal/application.py", line 1311, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 307, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 113, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.8/site-packages/msal/token_cache.py", line 152, in __add
    decode_id_token(id_token, client_id=event["client_id"])
  File "/opt/az/lib/python3.8/site-packages/msal/oauth2cli/oidc.py", line 77, in decode_id_token
    raise RuntimeError("%s Current epoch = %s.  The id_token was: %s" % (
RuntimeError: 0. The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1668493284.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0",
  "iat": 1668509352,
  "nbf": 1668509352,
  "exp": 1668513252,
  "aio": "AXQAi/8TAAAASzVFUy1yHIU+8qW7aIR3uqxttgsS1xiGCUGPcQL9qPva8orLO3i8PRAukbjyl/gOYHtR9cTw1bzaJQ9DEeYMDhE0BLd13K5zaHX3/TsOa90YkKd033rwBnf0x/mbls3jq+GSIdJVa4w7AxaaKlidCQ==",
  "name": "Vaibhavi Kamani",
  "nonce": "d1a65b433a7e583f7dbf63cbfb13b549245bf3ba762c44b6cf1b5d8fc823114b",
  "oid": "2b92e528-18ff-4852-b3bf-7bd8104ec832",
  "preferred_username": "vkamani@microsoft.com",
  "puid": "10032001C5589438",
  "rh": "0.ARoAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaACA.",
  "sub": "7LxyxYmfyAy1on28yjFg8mYYT7UTxRtmD_ARuKNXpCA",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "AKQJpkN7SEaelQ4VW04nAA",
  "ver": "2.0"
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account set --subscription c99e2bf3-1777-412b-baba-d823676589c2`
- `az aks get-credentials --resource-group Compute-rg-slbSimulation-wstdty --name aks-jhuug4jkx4sgu`

## Expected Behavior
* It should connect to the aks cluster

## Environment Summary
```
Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vkamani21 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@vkamani21 I looked at the error message:

```
The ID token is not yet valid. Make sure your computer's time and time zone are both correct. Current epoch = 1668493284. 
```
As the error suggested: `Current epoch = 1668493284`. This is **GMT: Tuesday, November 15, 2022 6:21:24 AM** (converted using https://www.epochconverter.com/).

**Cause:**
The cause is because the time on the computer is not correct. MSAL checks **nbf** and thinks the ID token is not yet valid.

> **nbf** is a value of a not before claim, which indicates the time before which the JSON Web Token (JWT) must not be accepted for processing.

**Action Plan:**
- If you are using WSL, try to run the command `sudo hwclock -s` and see if reboot helps.
- Also could you try to adjust your computer's time according to https://time.is/ ?

Tagging similar issues here: https://github.com/Azure/azure-cli/issues/20388 https://github.com/Azure/azure-cli/issues/20434 and https://github.com/Azure/azure-cli/issues/20158

**Comment by navba-MSFT** [comment]
@vkamani21 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vkamani21 The action is currently pending on you to try the[ above suggestion](https://github.com/Azure/azure-cli/issues/24658#issuecomment-1318123608). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
