### ISSUE TITLE
azure CLI  python error when trying list all the Global Admin role  assignee

### ISSUE THREAD

**Issue by kabene** [Azure/azure-cli#24656]
## Describe the bug

**Command Name**
`az role definition list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleDefinitionsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 49, in list_role_definitions
    definitions_client.config.subscription_id)
AttributeError: 'RoleDefinitionsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition list --subscription {}`

## Environment Summary
```
Linux-5.15.0-kali3-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.5
Installer: DEB

azure-cli 2.36.0 *

Extensions:
azure-firewall 0.13.0
managementpartner 0.1.3
azure-devops 0.24.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 21.0.0
```

**Comment by kabene** [comment]
solve https://github.com/Azure/azure-cli/issues/19640 sorry @jiasli
