### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.mgmt.security.models._security_center_enums'; 'azure.mgmt.security.models' is not a package on Kali linux

### ISSUE THREAD

**Issue by kabene** [Azure/azure-cli#24660]
## Describe the bug

**Command Name**
`az security pricing list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.security.models._security_center_enums'; 'azure.mgmt.security.models' is not a package
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/security/custom.py", line 35, in <module>
    from azure.mgmt.security.models._security_center_enums import Enum69
ModuleNotFoundError: No module named 'azure.mgmt.security.models._security_center_enums'; 'azure.mgmt.security.models' is not a package

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az security pricing list`

## Environment Summary
```
Linux-5.15.0-kali3-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.5
Installer: DEB

azure-cli 2.42.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.2.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@kabene I am not able to reproduce this and getting the results correctly.  
![image](https://user-images.githubusercontent.com/38112130/206173729-9095730e-5b1e-4b00-9ab6-ff37603980b7.png)

**Comment by kabene** [comment]
@SaurabhSharma-MSFT  what happen if you remove azure.mgmt.security.models._security_center_enums'; 'azure.mgmt.security.models' because my kali get that it is not a package and i cannot add it manually. 

I've tried multiple times to uninstall the cli and install it again but it seems to still be broken

**Comment by SaurabhSharma-MSFT** [comment]
@kabene I checked now with Kali and I am able to reproduce your error.  
![image](https://user-images.githubusercontent.com/38112130/206182415-d3514f37-67d1-4a14-a1a2-070f4c7f2e1c.png)
I am checking now internally on this issue and get back to you at the earliest.  Thanks.

**Comment by kabene** [comment]
@SaurabhSharma-MSFT  is there any news about this finding ?

**Comment by SaurabhSharma-MSFT** [comment]
@kabene sorry for the delay.  I am still waiting for product's team response.  I will update you as soon as I get any updates.

**Comment by SaurabhSharma-MSFT** [comment]
@kabene Can you please upgrade your Azure CLI version using `az upgrade` command and check the cli cmdlet again.  It looks like it is fixed in the new version of Azure CLI.
![image](https://user-images.githubusercontent.com/38112130/214220447-6151221a-83a6-43cd-8ab6-17cce04f6f0e.png)
