### ISSUE TITLE
az webapp log download fails sometimes

### ISSUE THREAD

**Issue by antgustech** [Azure/azure-cli#24678]
This looks to be the same issue as here: https://github.com/Azure/azure-cli/issues/23634

When running `az webapp log download --name name --resource-group rg --slot slot`

The command sometime fails with:

```
The command failed with an unexpected error. Here is the traceback:
('Connection broken: IncompleteRead(4 bytes read)', IncompleteRead(4 bytes read))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/az/lib/python3.10/http/client.py", line 532, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/az/lib/python3.10/http/client.py", line 567, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/opt/az/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/opt/az/lib/python3.10/http/client.py", line 597, in _read_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(4 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2580, in download_historical_logs
    _get_log(url, user_name, password, log_file)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2612, in _get_log
    data = r.read(1024)
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 512, in read
    with self._error_catcher():
  File "/opt/az/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(4 bytes read)', IncompleteRead(4 bytes read))
```
az cli 2.42

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@antgustech Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you check the suggestion mentioned [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1243185740) and [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1241499873) ? Awaiting your reply.

**Comment by antgustech** [comment]
> @antgustech Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you check the suggestion mentioned [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1243185740) and [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1241499873) ? Awaiting your reply.

/unresolve

Hi! I did see those threads. When can expect the App Service Platform upgrade to be done?

**Comment by navba-MSFT** [comment]
@antgustech Thanks for getting back. The fix will be rolled out completely in next 3 months. Until then you can follow the workaround mentioned in this [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1243185740)  and [here](https://github.com/Azure/azure-cli/issues/23634#issuecomment-1241499873). Hope this answers.

**Comment by navba-MSFT** [comment]
@antgustech I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any follow-up questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@antgustech I hope you had a chance to look at the[ above comment](https://github.com/Azure/azure-cli/issues/24678#issuecomment-1330268606). We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
