### ISSUE TITLE
Unable to upload logo image to app registration

### ISSUE THREAD

**Issue by alexdrenea** [Azure/azure-cli#24696]
## Describe the bug
Trying to upload the logo for an Azure app Registration, running into an encoding issue with az rest. (See below)

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'latin-1' codec can't encode character '\u2030' in position 0: Body ('â€°') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 24, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 974, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 394, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 239, in request
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1327, in _send_request
  File "http\client.py", line 166, in _encode
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2030' in position 0: Body ('â€°') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
-  `$logoBytes = Get-Content ..\logo.png -Raw`
- ` az rest --method PUT --uri "https://graph.microsoft.com/v1.0/applications/$MYAPPID/logo" --headers 'Content-Type=image/png' --body $logoBytes`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
account 0.2.1
application-insights 0.1.16
containerapp 0.3.7
storage-preview 0.8.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by alexdrenea** [comment]
The error above might be due to improper encoding of the stream being sent in.
After correcting the encoding (was not sending the body as stream), encountering a new error:

Script errors out with message "The command line is too long." 
```powershell
$logoBytesWeb = (Invoke-WebRequest "https://purepng.com/public/uploads/medium/purepng.com-microsoft-logo-iconlogobrand-logoiconslogos-251519939091wummo.png").Content
az rest --method PUT --uri "https://graph.microsoft.com/v1.0/applications/$appId/logo" --headers 'Content-Type=image/png' --body $logoBytesWeb --debug                                                                                                                                        
```

I am now confident I am now sending the proper bytes stream since I can make this work using the `Invoke-RestMehod` in PowerShell

Script that works:
```powershell
$token=(az account get-access-token --resource "https://graph.microsoft.com" --query accessToken --output tsv)

$logoBytesWeb = (Invoke-WebRequest "https://purepng.com/public/uploads/medium/purepng.com-microsoft-logo-iconlogobrand-logoiconslogos-251519939091wummo.png").Content

Invoke-RestMethod -Uri "https://graph.microsoft.com/v1.0/applications/$appId/logo" -Method "PUT" -Header @{"Authorization"="Bearer $token";"Content-Type"="image/png";} -Body $logoBytesWeb
```

**Comment by gabbsmo** [comment]
I also ran into this issue. I tried the following two approaches:

```
$bytes = $bytes = [System.IO.File]::ReadAllBytes($logo)
az rest `
  --method "put" `
  --uri "https://graph.microsoft.com/beta/applications/$($app.id)/logo" `
  --headers "{'Content-Type': 'image/png'}" `
  --body "$bytes"

# ERROR:  
# Program 'az.cmd' failed to run: An error occurred trying to start process 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd' with working directory 'C:\git\metashare\Azure'. The filename or extension is too long.
```

```
az rest `
  --method "put" `
  --uri "https://graph.microsoft.com/beta/applications/$($app.id)/logo" `
  --headers "{'Content-Type': 'image/png'}" `
  --body "@$logo"

# ERROR:
# Bad Request({"error":{"code":"Request_BadRequest","message":"Stream content does not represent a valid image.","innerError":{"date":"2026-03-09T07:12:52","request-id":"b946bd99-dec3-4204-9ac6-0adddb09f76b","client-request-id":"b946bd99-dec3-4204-9ac6-0adddb09f76b"}}})
```

As a workaround I can use `Invoke-RestMethod` but a native way to send files via `az rest` would be a useful escape hatch for this and possible other cases when native `az` commands are not available.
