### ISSUE TITLE
Az storage account show-connection-string gives exception on cli version 2.42.0

### ISSUE THREAD

**Issue by jscheeres** [Azure/azure-cli#24733]
## Describe the bug

az storage account show-connection-string --name ... ==> gives exception

az storage account show-connection-string --name ... --resource-group .... ==> gives no exception

**Command Name**
`az storage account show-connection-string`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/account.py", line 293, in show_storage_account_connection_string
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 1312, in list_keys
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_05_01/operations/_storage_accounts_operations.py", line 319, in build_list_keys_request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 652, in url
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 760, in serialize_data
ValueError: No value for given attribute

```

## To Reproduce:

az storage account show-connection-string --name .........

## Expected Behavior

Show connectionstring.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MO2k4** [comment]
thanks @jscheeres for your workaround 💯

**Comment by evelyn-ys** [comment]
duplicated with #24528
