### ISSUE TITLE
az connectedk8s commands result in error

### ISSUE THREAD

**Issue by katriendg** [Azure/azure-cli#24742]
## Describe the bug

**Command Name**
`az connectedk8s list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cp310-win32.pyd', Not found '_MD5.pyd'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 507, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\katriend\.azure\cliextensions\connectedk8s\azext_connectedk8s\custom.py", line 37, in <module>
    from Crypto.IO import PEM
  File "C:\Users\katriend\.azure\cliextensions\connectedk8s\Crypto\IO\PEM.py", line 39, in <module>
    from Crypto.Hash import MD5
  File "C:\Users\katriend\.azure\cliextensions\connectedk8s\Crypto\Hash\MD5.py", line 29, in <module>
    _raw_md5_lib = load_pycryptodome_raw_lib("Crypto.Hash._MD5",
  File "C:\Users\[...]\.azure\cliextensions\connectedk8s\Crypto\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._MD5': Not found '_MD5.cp310-win32.pyd', Not found '_MD5.pyd'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Running the command in Powershell on Windows 11, az cli and extension versions as below
- `az connectedk8s list --resource-group {} --output table`

## Expected Behavior

Expecting to see my connected cluster.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0 *

Extensions:
application-insights 0.1.16
connectedk8s 1.3.5
customlocation 0.1.3
k8s-configuration 1.7.0
k8s-extension 1.3.6

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@katriendg 
Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@katriendg Please follow the below action plan in order and check if that helps.

**Plan 1:** 
Could you please update the connectedk8s extension ?
> az extension update -n connectedk8s

**Plan 2:**
If the above plan doesn't help, Try running the commands:  ` pip install cryptography` and `pip install pycryptodome`

**Plan 3:**
If both the above action plan doesn't help, please upgrade your python package version _https://www.python.org/downloads/windows/_ and check if that helps.

Awaiting your reply.

**Comment by katriendg** [comment]
Thank you! Confirming Plan 1 works so closing this issue.

**Comment by syedhassaanahmed** [comment]
I ran into this as well on Windows 11 and Python 3.11 with Azure CLI 2.51.0 (64-bit). The 3 plans described by @navba-MSFT didn't help, but the following did,
```Powershell
az extension remove -n connectedk8s
az extension add -n connectedk8s
```

**Comment by katriendg** [comment]
Sharing here that I'm also unable to get this stabilized on a system running Windows 11 with WSL.
1. Using the approach above by to remove and re-add the extension works within the chosen environment, for example working in Windows, in Powershell I execute the remove/add and can execute the `az connectedk8s` commands.
2. Switching to WSL, whenever I try to work with the `az connectedk8s` extension I get the crypto error. In WSL I then execute remove/add extension and it works again.
3. Now if I switch back to my Windows based environment, again I will have to repeat remove/add to get it working. So, this has been my workaround for now.

**Comment by syedhassaanahmed** [comment]
I had exactly the same issue as @katriendg described above. Here is what I found which helped me resolve it.
Apparently there was an experimental Docker for Windows feature called [Cloud Experience](https://github.com/docker/for-win/issues/9503) that created symlinks for your WSL2 directories such as `/home/<linux_username>/.azure` and `/home/<linux_username>/.aws` pointing them to `/mnt/c/Users/<windows_username>/.azure` and `/mnt/c/Users/<windows_username>/.aws` respectively which are mounted to the following actual Windows path `%USERPROFILE%\.azure`. This can be easily verified by executing the following inside your WSL2 env
```bash
ls /home/<linux_username> -la
```
If the response is similar to `lrwxrwxrwx   .azure -> /mnt/c/Users/<windows_username>/.azure`, you'll likely run into this issue. The reason is that the `.azure/cliextensions/<az_extension_name>` directory stores Python scripts and native binaries required to run the Extension. In case of `connectedk8s` it seems to be dependent on the `cryptography` and `pycryptodome` libs wihch might have different binary flavors depending on the OS.

I resolved it by removing the `.azure` symlink in WSL2 and re-installed the `connectedk8s` extension. Now I'm able to use the extension from both Windows PowerShell and WSL2, without each breaking the other.
