### ISSUE TITLE
az network application-gateway ssl-cert list fails with exception

### ISSUE THREAD

**Issue by sundbry** [Azure/azure-cli#24745]
I had a workflow which was working before, that is no longer working after upgrading debian packages:

## Describe the bug

**Command Name**
`az network application-gateway ssl-cert list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 508, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/__init__.py", line 50, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/_params.py", line 133, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway ssl-cert list --resource-group {} --gateway-name {}`

## Environment Summary
```
Linux-6.0.0-4-amd64-x86_64-with-glibc2.36, Debian GNU/Linux bookworm/sid
Python 3.10.8
Installer: DEB

azure-cli 2.42.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.2.1
```

**Comment by yonzhan** [comment]
@necusjz for awareness
