### ISSUE TITLE
az update - An error occurred whilst updating. The extension ml already exists.

### ISSUE THREAD

**Issue by beamand** [Azure/azure-cli#24747]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az update

**Describe the bug**

Not really a bug but an observation of errors being generated!

**To Reproduce**

Not sure if everyone is getting there errors, but just type in "az update" in one of the CLI's. 

**Expected behavior**

I'm expecting there not to be any errors during this training exercise for a beginner.

**Environment summary**

https://learn.microsoft.com/en-us/training/modules/describe-core-architectural-components-of-azure/4-exercise-explore-learn-sandbox

PS /home/danny_beaman> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.42.0
Upgrading extensions
Checking update for interactive
Latest version of 'interactive' is already installed.

Use --debug for more information
Checking update for ai-examples
Latest version of 'ai-examples' is already installed.

Use --debug for more information
Checking update for ml
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. Retrying ...
Failed to delete '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml': [Errno 13] Permission denied: 'py.typed'. You may try to delete it manually.
An error occurred whilst updating.
The extension ml already exists.
The command failed with an unexpected error. Here is the traceback:'
[Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 413, in update_extension
    _add_whl_ext(cli_ctx=cmd_cli_ctx, source=download_url, ext_sha256=ext_sha256,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 113, in _add_whl_ext
    raise CLIError('The extension {} already exists.'.format(extension_name))
knack.util.CLIError: The extension ml already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/extension/custom.py", line 34, in update_extension_cmd
    return update_extension(cli_ctx=cmd.cli_ctx, extension_name=extension_name, index_url=index_url,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 421, in update_extension
    shutil.copytree(backup_dir, extension_path)
  File "/usr/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3.9/site-packages/azure-cli-extensions/ml'
To check existing

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/24023

This will be fixed in next release.
