### ISSUE TITLE
az login fails with unexpected keyword argument 'allow_broker'

### ISSUE THREAD

**Issue by grisu48** [Azure/azure-cli#24769]
## Describe the bug

`az login` fails with `TypeError: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'` using the latest (2.42.0) version on openSUSE Tumbleweed.

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 112, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/home/phoenix/.local/lib/python3.10/site-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'

```

## To Reproduce:

- `az login`

## Environment Summary
```
Linux-6.0.8-1-default-x86_64-with-glibc2.36, openSUSE Tumbleweed
Python 3.10.8
Installer: PIP

azure-cli 2.42.0
```

**Comment by grisu48** [comment]
The same error arises when performing an `az storage blob upload ...` operation:

```
Skip querying account key due to failure: ClientApplication.__init__() got an unexpected keyword argument 'allow_broker'
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:<redacted>
Time:2022-11-30T10:29:39.1210784Z
ErrorCode:NoAuthenticationInformation
```

**Comment by yonzhan** [comment]
Please refer to this issue https://github.com/Azure/azure-cli/issues/24372
