### ISSUE TITLE
az storage fails with TypeError: NoneType object is not iterable

### ISSUE THREAD

**Issue by grisu48** [Azure/azure-cli#24772]
## Describe the bug

Upload of a storage blob or listing of the storage account keys using the current version of the `azure-cli` from https://packages.microsoft.com/yumrepos/azure-cli (Version 2.38.0) fails with a TypeError:

```
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

**Command Name**

Issue arises in either of those commands:

* `az storage blob upload`
* `az storage account keys list`

**Errors:**

```
az storage blob upload

The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
```

```
$ az storage account keys list --resource-group {}--account-name {}
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:

- `az storage blob upload --max-connections 4 --container-name {} --account-name {} --type page --file {} --name {}`

or

- `az storage account keys list --resource-group {}--account-name {}`

## Expected Behavior

* The corresponding command runs instead of the TypeError

## Environment Summary
```
Linux-6.0.8-1-default-x86_64-with-glibc2.36, openSUSE Tumbleweed
Python 3.10.8
Installer: RPM

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by navba-MSFT** [comment]
@grisu48 Hope you had a chance to look at the above suggestion. Please let us know if that helps.

**Comment by bebound** [comment]
`Python 3.10.8` looks weird, it should be `3.6`.
Do you manually uninstall python3.6?

**Comment by grisu48** [comment]
> `Python 3.10.8` looks weird, it should be `3.6`. Maybe you need to manually uninstall python3.6.

On my laptop I have by default Python 3.10.8, but the `az` utility should run on 3.6, as the second traceback suggests:

```
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
```

No idea how the Python version in the `az feedback` subcommand is handled, it looks weird to me as well.

**Comment by grisu48** [comment]
> Please ensure the storage dependency is correctly installed. This error occurs when no enum definition read from dependency SDK.
> 
> Here's the official doc for installing cli together with all the dependencies: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli

In short: Nope, that doesn't work.

The only available package in the https://packages.microsoft.com/yumrepos/azure-cli repository is `azure-cli`, which I installed. There are no further packages or dependencies shipped within this repository.

However, when looking at the install documents I stumbled across this [deprecation notice](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper) for openSUSE/SLES:

![image](https://user-images.githubusercontent.com/1527829/205602191-e63596cf-21e8-40f8-b250-b9cc60aa8f75.png)

This was not clear to me, as I installed the CLI years back and didn't got a deprecation warning. Since what I'm running is obviously an unsupported version on a (now) unsupported platform I think I need to find a different approach.

**Comment by bebound** [comment]
Sorry, I made a mistake in the previous reply.
You need to install python3.6, in other word, make `python3.6` executable.

**Comment by grisu48** [comment]
> Sorry, I made a mistake in the previous reply. You need to install python3.6, in other word, make `python3.6` executable.
> 
> `cat /usr/bin/az` show that it itries to use python3.6 to run az, if not found, uses `python3` instead. Thus, the error raises.

Thank you! I leave this here for any other folk who find this issue. I switched in the meantime to my distribution-package, where this issue is not present.

Closing issue as it is not present anymore. Thanks everyone for the input and help! :slightly_smiling_face:
