### ISSUE TITLE
`az appservice kube list` from `appservice-kube` extension fails: ModuleNotFoundError: No module named 'azure.mgmt.web.v2021_01_01'

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24784]
**Related command**
`az appservice kube list`

**Describe the bug**
```
C:\Windows\System32>az appservice kube list
Command group 'appservice kube' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.web.v2021_01_01'
Traceback (most recent call last):
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
 File "C:\Users\navba\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 371, in list_kube_environments
   client = _get_kube_client(cmd)
 File "C:\Users\navba\.azure\cliextensions\appservice-kube\azext_appservice_kube\custom.py", line 301, in _get_kube_client
   return client.kube_environments
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/_web_site_management_client.py", line 627, in kube_environments
ModuleNotFoundError: No module named 'azure.mgmt.web.v2021_01_01'
```

**Comment by yonzhan** [comment]
caused by trimming SDK

**Comment by jiasli** [comment]
This error is because API version `v2021_01_01` is trimmed from `azure-mgmt-web` SDK by `scripts/trim_sdk.py` to reduce MSI package size (https://github.com/Azure/azure-cli/pull/23946):

https://github.com/Azure/azure-cli/blob/f952dc04ae2212d32bb8bb562fef40a7f749bacb/scripts/trim_sdk.py#L123

https://github.com/Azure/azure-cli/pull/24017 removed hard coded app service API versions from main Azure CLI `appservice` command module, but the `appservice-kube` extension is left unchanged.

### Possible solutions

- `appservice-kube` extension can use the latest API version defined at https://github.com/Azure/azure-cli/blob/8c45b0feeaaa9a8ca3ed53c5cead1a8435b04fa6/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L243
- If the above solution is not possible, `ResourceType.MGMT_APPSERVICE` can be defined as an `SDKProfile` so that different operations can use different API versions. This approach is adopted by `ResourceType.MGMT_COMPUTE`: https://github.com/Azure/azure-cli/blob/8c45b0feeaaa9a8ca3ed53c5cead1a8435b04fa6/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L157-L159
- A less recommended solution is to define ad-hoc API version in `AD_HOC_API_VERSIONS`, but this is hard to maintain: https://github.com/Azure/azure-cli/blob/8c45b0feeaaa9a8ca3ed53c5cead1a8435b04fa6/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L411-L415

**Comment by likamrat** [comment]
Looks like a dup #24744

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/24744
