### ISSUE TITLE
'NoneType' object is not iterable on az storage account commands

### ISSUE THREAD

**Issue by pkazi** [Azure/azure-cli#24786]
## Describe the bug

**Command Name**
`az storage account list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 1713, in load_arguments
    help_str = 'Allowed values: {}. Can be combined'.format(get_permission_help_string(t_share_permissions))
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account list`

## Environment Summary
```
Linux-4.14.276-211.499.amzn2.x86_64-x86_64-with-glibc2.2.5, Amazon Linux 2
Python 3.7.10
Installer: RPM

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
Please let us know whether above suggestion can resolve this issue.

**Comment by pkazi** [comment]
2.42.0 is not available as rpm for Amazon Linux 2 / CentOS 7, I know Azure has stopped support for these, 
what install option is left now ? Install via script ?

**Comment by bebound** [comment]
@pkazi  Can you try to install python3.6 and see it works.
`Python 3.7.10` is not expected, it should be 3.6.
