### ISSUE TITLE
issue with `az vmss perform-maintenance` targeting a single VM

### ISSUE THREAD

**Issue by eager-signal** [Azure/azure-cli#24791]
## Describe the bug

**Command Name**
`az vmss perform-maintenance`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
(', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 680, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1470, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py", line 78, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
azure.core.exceptions.DeserializationError: (", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/v2022_08_01/operations/_virtual_machine_scale_sets_operations.py", line 3447, in begin_perform_maintenance
    raw_result = self._perform_maintenance_initial(  # type: ignore
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/v2022_08_01/operations/_virtual_machine_scale_sets_operations.py", line 3290, in _perform_maintenance_initial
    _json = self._serialize.body(vm_instance_i_ds, "VirtualMachineScaleSetVMInstanceIDs")
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 682, in body
    raise_with_traceback(
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py", line 78, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 680, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1470, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py", line 78, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1452, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1217, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/compute/_serialization.py", line 1246, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
azure.core.exceptions.SerializationError: (', DeserializationError: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', 'Unable to build a model: (", AttributeError: \'str\' object has no attribute \'get\'", \'Unable to deserialize to object: type\', AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError(", AttributeError: 'str' object has no attribute 'get'", 'Unable to deserialize to object: type', AttributeError("'str' object has no attribute 'get'")))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss perform-maintenance -n {} -g {} --vm-instance-i-ds {}`

## Environment Summary
```
macOS-13.0.1-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.42.0

Extensions:
aks-preview 0.5.75

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
