### ISSUE TITLE
Can not generate new SAS

### ISSUE THREAD

**Issue by RyanFromAmperity** [Azure/azure-cli#24803]
## Describe the bug

**Command Name**
`az storage container generate-sas`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
self.account_key should not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/storage/__init__.py", line 371, in new_handler
    first(ex)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/storage/__init__.py", line 370, in new_handler
    raise ex
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 759, in generate_container_shared_access_signature
    return client.generate_container_shared_access_signature(
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 421, in generate_container_shared_access_signature
    _validate_not_none('self.account_key', self.account_key)
  File "/usr/local/Cellar/azure-cli@2.29.2/2.29.2/libexec/lib/python3.9/site-packages/azure/multiapi/storage/v2018_11_09/common/_error.py", line 130, in _validate_not_none
    raise ValueError(_ERROR_VALUE_NONE.format(param_name))
ValueError: self.account_key should not be None.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container generate-sas --https-only --account-name {} --name {} --permissions {} --start {} --expiry {}`

## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.9.13
Installer: HOMEBREW

azure-cli 2.29.2 *

```

**Comment by RakeshMohanMSFT** [comment]
@RyanFromAmperity Can you please try upgrading your azure cli to latest version [2.42.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos) and also upgrade your python and retry?

**Comment by TobiasBreuer** [comment]
Hey, don't know if it is the same original reason, but today I was facing a similar issue in Azure Release Pipeline:

```
2022-12-06T12:42:35.6448151Z ERROR: The command failed with an unexpected error. Here is the traceback:
2022-12-06T12:42:35.6449156Z ERROR: Incorrect padding
2022-12-06T12:42:35.6449795Z Traceback (most recent call last):
2022-12-06T12:42:35.6451452Z   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
2022-12-06T12:42:35.6452226Z     cmd_result = self.invocation.execute(args)
2022-12-06T12:42:35.6453296Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
2022-12-06T12:42:35.6454034Z     raise ex
2022-12-06T12:42:35.6455074Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2022-12-06T12:42:35.6455930Z     results.append(self._run_job(expanded_arg, cmd_copy))
2022-12-06T12:42:35.6458379Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
2022-12-06T12:42:35.6459070Z     result = cmd_copy(params)
2022-12-06T12:42:35.6459952Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
2022-12-06T12:42:35.6460624Z     return self.handler(*args, **kwargs)
2022-12-06T12:42:35.6461562Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2022-12-06T12:42:35.6462215Z     return op(**command_args)
2022-12-06T12:42:35.6463163Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/account.py", line 49, in generate_sas
2022-12-06T12:42:35.6464017Z     return t_account_sas(account_name=client.account_name, account_key=client.credential.account_key).\
2022-12-06T12:42:35.6465206Z   File "/opt/az/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_shared/shared_access_signature.py", line 158, in generate_account
2022-12-06T12:42:35.6466055Z     sas.add_account_signature(self.account_name, self.account_key)
2022-12-06T12:42:35.6467184Z   File "/opt/az/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_shared/shared_access_signature.py", line 227, in add_account_signature
2022-12-06T12:42:35.6467980Z     sign_string(account_key, string_to_sign))
2022-12-06T12:42:35.6468989Z   File "/opt/az/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_shared/__init__.py", line 47, in sign_string
2022-12-06T12:42:35.6469702Z     key = decode_base64_to_bytes(key)
2022-12-06T12:42:35.6470718Z   File "/opt/az/lib/python3.10/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_shared/__init__.py", line 37, in decode_base64_to_bytes
2022-12-06T12:42:35.6471443Z     return base64.b64decode(data)
2022-12-06T12:42:35.6472009Z   File "/opt/az/lib/python3.10/base64.py", line 87, in b64decode
2022-12-06T12:42:35.6472562Z     return binascii.a2b_base64(s)
2022-12-06T12:42:35.6473058Z binascii.Error: Incorrect padding
```
The reason for that issue actually was an incorrect value for `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` that did not match the environment I was releasing to...

So the error message is not really helpful in this case and seems totally unrelated but maybe it is worth to check.
