### ISSUE TITLE
OS architecture mismatch when installing Azure Bicep with the `az bicep install` command

### ISSUE THREAD

**Issue by pauldotyu** [Azure/azure-cli#24810]
## Describe the bug

**Command Name**
`az bicep version`

**Errors:**
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run the `az bicep install` command from any ARM64-based operating system (e.g., Dev Container running locally on M1 Mac)
- Run the `az bicep version` command to validate install

## Expected Behavior

- The installer should download the [appropriate executable](https://github.com/Azure/bicep/releases/latest/download/bicep-linux-arm64) if run from an `amd64` based system

## Environment Summary
```
Linux-5.15.49-linuxkit-aarch64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.6
Installer: PIP

azure-cli 2.42.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@pauldotyu Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@pauldotyu Could you please run the same command again with `--debug `parameter and share the detailed error output here ? Awaiting your reply.

**Comment by pauldotyu** [comment]
@navba-MSFT Here is the output

```
$ az bicep install --debug
cli.knack.cli: Command arguments: ['bicep', 'install', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0xffff9be86c20>, <function OutputProducer.on_global_arguments at 0xffff9bd88ca0>, <function CLIQuery.on_global_arguments at 0xffff9bdc1ea0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'bicep': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.004        47       207
cli.azure.cli.core: Total (1)                 0.004        47       207
cli.azure.cli.core: Loaded 47 groups, 207 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : bicep install
cli.azure.cli.core: Command table: bicep install
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0xffff9af8b7f0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/vscode/.azure/commands/2022-12-06.15-23-02.bicep_install.793.log'.
az_command_data_logger: command args: bicep install --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0xffff9afb85e0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0xffff9afe3130>, <function register_cache_arguments.<locals>.add_cache_arguments at 0xffff9afe3250>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0xffff9bd88d30>, <function CLIQuery.handle_query_parameter at 0xffff9bdc1f30>, <function register_ids_argument.<locals>.parse_ids_arguments at 0xffff9afe31c0>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): api.github.com:443
urllib3.connectionpool: https://api.github.com:443 "GET /repos/Azure/bicep/releases/latest HTTP/1.1" 200 None
Installing Bicep CLI v0.13.1...
Successfully installed Bicep CLI to "/home/vscode/.azure/bin/bicep".
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0xffff9afbbbe0>, <function _x509_from_base64_to_hex_transform at 0xffff9afbbc70>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0xffff9af8ba30>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 44.139 seconds (init: 0.064, invoke: 44.075)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3077 in cache
telemetry.check: Negative: The /home/vscode/.azure/telemetry.txt was modified at 2022-12-06 15:22:57.360527, which in less than 600.000000 s
```

Seems that the `target_platform` parameter is not being passed in when invoking the `_get_bicep_download_url()` function in [_bicep.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L116) causing it to install the `bicep-linux-x64` instead of `bicep-linux-arm64`

**Comment by navba-MSFT** [comment]
@pauldotyu Thanks for your reply. Could you please follow the below steps and check if that helps ?

```
# Fetch the latest Bicep CLI binary
curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-arm64
# Mark it as executable
chmod +x ./bicep
# Add bicep to your PATH (requires admin)
sudo mv ./bicep /usr/local/bin/bicep
# Verify you can now access the 'bicep' command
bicep --help
# Done!
```

More Info: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux

**Comment by pauldotyu** [comment]
> @pauldotyu Thanks for your reply. Could you please follow the below steps and check if that helps ?
> 
> ```
> # Fetch the latest Bicep CLI binary
> curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-arm64
> # Mark it as executable
> chmod +x ./bicep
> # Add bicep to your PATH (requires admin)
> sudo mv ./bicep /usr/local/bin/bicep
> # Verify you can now access the 'bicep' command
> bicep --help
> # Done!
> ```
> 
> More Info: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux

Yes, that absolutely works in arm64 machines. I've submitted  [PR#305](https://github.com/devcontainers/features/pull/305) in the devconatiners/features repo to resolve this issue when installing Azure Bicep in Dev Containers since the `az bicep install` command does not work for some users.

**Comment by navba-MSFT** [comment]
@pauldotyu Thanks for getting back. A few questions: 

1. Could you please let me know the environment you had used when installing bicep via Azure CLI? 
2  Are you running this command inside a virtual machine? 
    On M1 Mac, system is "Darwin", and the command should install the bicep-osx-x64 executable. I tried the command on my 
    M1 Mac, and it worked as expected. 
3. Could you please confirm if you have tried specifying the **--target-platform** parameter and check if that helps ?

> az bicep install [**--target-platform** {linux-musl-x64, linux-x64, osx-x64, win-x64}] [--version]

Awaiting your reply.

**Comment by pauldotyu** [comment]
@navba-MSFT here is the debug log when attempting to install inside my Dev Container on my darwin-arm64 system

```
$ az bicep install --target-platform osx-x64 --debug
cli.knack.cli: Command arguments: ['bicep', 'install', '--target-platform', 'osx-x64', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0xffffb86a6c20>, <function OutputProducer.on_global_arguments at 0xffffb85a8ca0>, <function CLIQuery.on_global_arguments at 0xffffb85e1ea0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'bicep': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.005        47       207
cli.azure.cli.core: Total (1)                 0.005        47       207
cli.azure.cli.core: Loaded 47 groups, 207 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : bicep install
cli.azure.cli.core: Command table: bicep install
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0xffffb77ab7f0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/vscode/.azure/commands/2022-12-09.03-03-06.bicep_install.952.log'.
az_command_data_logger: command args: bicep install --target-platform {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0xffffb77d85e0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0xffffb78031c0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0xffffb78032e0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0xffffb85a8d30>, <function CLIQuery.handle_query_parameter at 0xffffb85e1f30>, <function register_ids_argument.<locals>.parse_ids_arguments at 0xffffb7803250>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): api.github.com:443
urllib3.connectionpool: https://api.github.com:443 "GET /repos/Azure/bicep/releases/latest HTTP/1.1" 200 None
Installing Bicep CLI v0.13.1...
Successfully installed Bicep CLI to "/home/vscode/.azure/bin/bicep".
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0xffffb77dbc70>, <function _x509_from_base64_to_hex_transform at 0xffffb77dbd00>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0xffffb77aba30>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 8.523 seconds (init: 0.061, invoke: 8.463)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3094 in cache
telemetry.check: Negative: The /home/vscode/.azure/telemetry.txt was modified at 2022-12-09 03:01:17.828872, which in less than 600.000000 s
```

Here is the error I get when attempting to run `az bicep version` post install

```
$ az bicep version
The command failed with an unexpected error. Here is the traceback:
[Errno 8] Exec format error: '/home/vscode/.azure/bin/bicep'
Traceback (most recent call last):
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3708, in show_bicep_cli_version
    print(run_bicep_command(["--version"], auto_install=False))
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 75, in run_bicep_command
    installed_version = _get_bicep_installed_version(installation_path)
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 203, in _get_bicep_installed_version
    installed_version_output = _run_command(bicep_executable_path, ["--version"])
  File "/usr/local/pipx/venvs/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 241, in _run_command
    process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/vscode/.azure/bin/bicep'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

Note the error above states "OSError: [Errno 8] Exec format error:"

Also, since I am on a darwin arm64 system, I'd expect to be able to run the `az bicep install` command with a `--target-platform` value of `osx-arm64` but the [enum for the parameter](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_params.py#L108) does not support that value yet. 

Here is what I get when attempting to install for a target platform that is not supported.

```
$ az bicep install --target-platform osx-arm64
az bicep install: 'osx-arm64' is not a valid value for '--target-platform'. Allowed values: win-x64, linux-musl-x64, linux-x64, osx-x64.
```

**Comment by navba-MSFT** [comment]
@pauldotyu Thanks for your reply. The above PR has been created to address this. Currently it is pending under review.

**Comment by pamelafox** [comment]
I got this issue just today on a dev container on my M1 Mac, so I had to workaround by specifying "installBicep": true for the az CLI feature. It seems like it's supposed to be working now, right?
