### ISSUE TITLE
Not able to delete ARO resource group and cluster

### ISSUE THREAD

**Issue by vamshicholleti93** [Azure/azure-cli#24826]
## Describe the bug

**Command Name**
`az aro delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'GraphError' object has no attribute 'message'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 1014, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2022-12-07T05:52:55","request-id":"8182f078-0971-42d8-8486-407eee9037c8","client-request-id":"8182f078-0971-42d8-8486-407eee9037c8"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/aro/custom.py", line 168, in aro_delete
    rp_client_sp_id = aad.get_service_principal_id(resolve_rp_client_id())
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/aro/_aad.py", line 31, in get_service_principal_id
    sps = self.client.service_principal_list(f"appId eq '{app_id}'")
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
    result = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/aro/custom.py", line 172, in aro_delete
    logger.info(e.message)
AttributeError: 'GraphError' object has no attribute 'message'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aro delete --resource-group {} --name {} --yes`

## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0 *
```

**Comment by RakeshMohanMSFT** [comment]
@vamshicholleti93 Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@vamshicholleti93 Can you please upgrade to the latest version of azure CLI [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos) and retry? because with the latest version it works.

![image](https://user-images.githubusercontent.com/49954584/206358220-8150cc38-806f-4393-b40f-0981c5b54bdf.png)
