### ISSUE TITLE
AZ Aks get credentianls or az aks show is throwing exceptions in POwershell and WSL

### ISSUE THREAD

**Issue by rahul-chr** [Azure/azure-cli#24831]
## Describe the bug

**Command Name**
`az aks nodepool`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1858, in take_action
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 275, in _get_values
  File "argparse.py", line 2399, in _get_values
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 326, in _check_value
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 201, in get_examples
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 192, in get_examples
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help.py", line 303, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/help.py", line 198, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 241, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\SONIRAH\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 105, in <module>
    from ._helpers import (
  File "C:\Users\SONIRAH\.azure\cliextensions\aks-preview\azext_aks_preview\_helpers.py", line 7, in <module>
    from azure.cli.command_modules.acs._helpers import map_azure_error_to_cli_error
ImportError: cannot import name 'map_azure_error_to_cli_error' from 'azure.cli.command_modules.acs._helpers' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\_helpers.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool {} --resource-group {} --cluster-name {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1 *

Extensions:
aks-preview 0.5.70
k8s-extension 1.3.7

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rahul-chr Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rahul-chr Could you please update your` aks-preview` extension by running the below command and check if that helps ? 

> **az extension update -n aks-preview**

On a side note, I would also suggest you to use the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)of the Azure CLI. Hope this helps.

**Comment by rahul-chr** [comment]
@navba-MSFT 

```
PS C:\Windows\system32> az extension update -n aks-preview
No updates available for 'aks-preview'. Use --debug for more information.
PS C:\Windows\system32> az version
{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.70",
    "k8s-extension": "1.3.7"
  }
}
```

**Comment by navba-MSFT** [comment]
@rahul-chr Thanks for getting back. The most recent version is `"aks-preview": "0.5.118"` but you are using an older version  `"aks-preview": "0.5.70",`. Could you please uninstall the older version and reinstall the newer version again by running the below commands ?

**Uninstall**
>  **az extension remove -n aks-preview**

**Install**
> **az extension add -n aks-preview**

Then you also need to [update the AzCLI](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) version.

**Comment by rahul-chr** [comment]
works now! thanks
