### ISSUE TITLE
Trying to create service principal 

### ISSUE THREAD

**Issue by vangolla** [Azure/azure-cli#24856]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'9a1d6ccd-4345-405c-adea-f80973d517e5'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/commands.py", line 51, in graph_err_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 1246, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 200, in _create_role_assignment
    role_id = _resolve_role_id(role, scope, definitions_client)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 609, in _resolve_role_id
    role_defs = list(definitions_client.list(scope, "roleName eq '{}'".format(role)))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 285, in internal_paging
    request = prepare_request(next_link)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/mgmt/authorization/v2018_01_01_preview/operations/_role_definitions_operations.py", line 281, in prepare_request
    request = self._client.get(url, query_parameters, header_parameters)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/msrest/service_client.py", line 168, in get
    request = self._request('GET', url, params, headers, content, form_content)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/msrest/service_client.py", line 108, in _request
    request = ClientRequest(method, self.format_url(url))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/msrest/service_client.py", line 151, in format_url
    url = url.format(**kwargs)
KeyError: '9a1d6ccd-4345-405c-adea-f80973d517e5'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --role {} --scopes {}`

## Environment Summary
```
macOS-13.0-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.42.0 *
```

**Comment by jiasli** [comment]
I doubt the value you provided for `--role` contains curly brackets `{}`. This is similar to https://github.com/Azure/azure-cli/issues/15739.

We deliberately removed curly brackets from examples for `--scope` (#23206), but we still can't control if user insist to include them in argument values.

If that is not the case, please share the full command you use with argument values kept. Thanks.
