### ISSUE TITLE
NSG Rule Create fails when command contains ASG

### ISSUE THREAD

**Issue by hugoro** [Azure/azure-cli#24853]
## Describe the bug

**Command Name**
`az network nsg rule create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expect <class 'str'>, got {'additional_properties': {}, 'id': '/subscriptions/0ea89fa8-210b-4a83-a0ad-ecc31f973c/resourceGroups/network/providers/Microsoft.Network/applicationSecurityGroups/ASG-IM*', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'resource_guid': None, 'provisioning_state': None} (<class 'azure.mgmt.network.v2022_01_01.models._models_py3.ApplicationSecurityGroup'>
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 5358, in create_nsg_rule
    return Create(cli_ctx=cmd.cli_ctx)(command_args=kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 145, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/nsg/rule/_create.py", line 40, in _handler
    super()._handler(command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 149, in _handler
    self.ctx = AAZCommandCtx(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command_ctx.py", line 31, in __init__
    self.args[dest] = cmd_arg
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 80, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 382, in process_data
    value[idx] = sub_data
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 369, in __setitem__
    self._data[idx] = item_schema.process_data(data, key=idx)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 219, in process_data
    value[key] = sub_data
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 80, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 43, in process_data
    assert self.DataType is not None and isinstance(data, self.DataType), \
AssertionError: Expect <class 'str'>, got {'additional_properties': {}, 'id': '/subscriptions/0ea89fa8-210b-4a83-a0ad-ecc31f973c/resourceGroups/network/providers/Microsoft.Network/applicationSecurityGroups/ASG-IM*', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'resource_guid': None, 'provisioning_state': None} (<class 'azure.mgmt.network.v2022_01_01.models._models_py3.ApplicationSecurityGroup'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nsg rule create --name {} --resource-group {} --nsg-name {} --priority {} --direction {} --access {} --source-port-range {} --protocol {} --destination-port-ranges {} --description {} --source-address-prefixes {} --destination-asgs {}`

## Environment Summary
```
Linux-5.4.0-1095-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
interactive 0.4.5
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@hugoro Can I ask for some details? E.g., when this failure occurs, is `--destination-asgs` passing by Name or ID?

**Comment by hugoro** [comment]
tried both ways: asg name and asg id
error is the same as described

**Comment by VishalShindeTR** [comment]
There is something I observed today. 
If you install the azure cli **2.43.0 using the MSI, it works fine.** If you install the same using **python pip, it fails.** Hope this helps :)

**Comment by necusjz** [comment]
> There is something I observed today. If you install the azure cli **2.43.0 using the MSI, it works fine.** If you install the same using **python pip, it fails.** Hope this helps :)

Thanks for your info, and I do think it'll be fixed in the coming release (around 01/10/2023). The case has been covered by:
- https://github.com/Azure/azure-cli/blob/00caab1dd68346c837de819c7d485772a59146d5/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L4334-L4342
