### ISSUE TITLE
Azure AD Cli Fails in GHA 

### ISSUE THREAD

**Issue by sudharsanpunniyakotti** [Azure/azure-cli#24860]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az ad app list 

**Describe the bug**
az ad command fails in Github actions . 

**To Reproduce**
Run below yaml file in GHA . 

```on: [push]

name: AzureLoginWithNoSubscriptions

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - run: |
          az account show
          az group list
          az ad app list 

``` 

 Error : 

```RROR: The command failed with an unexpected error. Here is the traceback:
ERROR: HTTPSConnectionPool(host='graph.microsoft.com', port=443): Max retries exceeded with url: /v1.0/applications (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fabd051fc70>, 'Connection to graph.microsoft.com timed out. (connect timeout=None)'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

```

**Expected behavior**
az ad app registration list 

**Environment summary**
Run on self-hosted Github action with latest azure cli 

**Additional context**
Azure login works and az group list also works and give expected output .

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`TimeoutError: [Errno 110] Connection timed out` indicate your agent is not able to connect to Microsoft Graph endpoint `graph.microsoft.com`. Azure CLI `az ad` command group calls Microsoft Graph API. Please make sure your network setting allows access to `graph.microsoft.com`.
