### ISSUE TITLE
az appservice plan create results in an error

### ISSUE THREAD

**Issue by Strobodov** [Azure/azure-cli#24865]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'decorator'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fabric/connection.py", line 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hackzor/.local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/hackzor/.local/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/hackzor/.local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 27, in <module>
    from fabric import Connection
  File "/usr/lib/python3.10/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/lib/python3.10/site-packages/fabric/connection.py", line 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create -g {} -n {} --is-linux --sku {}`

## Environment Summary
```
Linux-6.0.10-100.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Workstation Edition)
Python 3.10.8
Installer: PIP

azure-cli 2.43.0

Extensions:
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Strobodov We are unable to reproduce this issue at our end, can you please uninstall and reinstall az cli and retry?

![image](https://user-images.githubusercontent.com/49954584/206915952-5b22c3ad-ea3a-43eb-8e78-f93bb80be414.png)

**Comment by Strobodov** [comment]
Can confirm that there seems to be something wrong with my installation. Issue can be closed for now.
