### ISSUE TITLE
az login with username and password is failing with {'reason': 'MSIS7068: Access denied.', 'code': 'a:FailedAuthentication'}

### ISSUE THREAD

**Issue by paychex-rkasired** [Azure/azure-cli#24889]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
WsTrust server returned error in RSTR: {'reason': 'MSIS7068: Access denied.', 'code': 'a:FailedAuthentication'}
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 158, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 156, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 1420, in acquire_token_by_username_password
    response = _clean_up(self._acquire_token_by_username_password_federated(
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/application.py", line 1447, in _acquire_token_by_username_password_federated
    wstrust_result = wst_send_request(
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/wstrust_request.py", line 60, in send_request
    return parse_response(resp.text)
  File "/usr/lib64/az/lib/python3.6/site-packages/msal/wstrust_response.py", line 49, in parse_response
    raise RuntimeError("WsTrust server returned error in RSTR: %s" % (error or body))
RuntimeError: WsTrust server returned error in RSTR: {'reason': 'MSIS7068: Access denied.', 'code': 'a:FailedAuthentication'}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`

## Environment Summary
```
Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.2.5, CentOS Linux 7 (Core)
Python 3.8.11
Installer: RPM

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20221#issuecomment-962380690

In short, username + password login is not recommended. For more information, please see https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication

Azure Portal is different, as you are using a web **browser** to login. The correct usage is to run `az login` and log in with your username + password in the **browser**, not **command line**.
