### ISSUE TITLE
Meet problems when changing the data disk size and sku when creating from an image

### ISSUE THREAD

**Issue by EdwinInnovation** [Azure/azure-cli#24908]
## Describe the bug

**Command Name**
`az disk create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'child_name_1'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.42.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/vm/custom.py", line 357, in create_managed_disk
    terms['child_name_1'], terms['child_name_3'], terms['child_name_4'], terms['child_name_5']
KeyError: 'child_name_1'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az disk create --name {} --resource-group {} --size-gb {} --image-reference {} --image-reference-lun {} --sku {} --zone {}`

## Environment Summary
```
macOS-13.1-arm64-arm-64bit, Darwin 22.2.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.42.0

Extensions:
aks-preview 0.5.116
communication 1.3.0
fleet 0.1.1
spring 1.4.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by qbradley** [comment]
I also hit this bug trying to create a disk from an image reference.

**Comment by yanzhudd** [comment]
Hi @EdwinInnovation, 

may I ask what format of your parameter `--image-reference` is? The format should be like this: 
`/Subscriptions/{subscriptionId}/Providers/Microsoft.Compute/Locations/westus/Publishers/{publisher}/ArtifactTypes/VMImage/Offers/{offer}/Skus/{sku}/Versions/1.0.0`

If you want to create a disk from an image, `--gallery-image-reference` and `--gallery-image-reference-lun` may could be tried to check if they meets your expectations.

Whether or not it could solve your problem, please let us know. Thanks.
