### ISSUE TITLE
az containerapp up error : 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kanuw** [Azure/azure-cli#24915]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az containerapp up --name nscontainerapp-pamjobsservice --resource-group nsrg_pam --image nsresgistry.azurecr.io/pam.jobsservice:0.4.0.29-01 --debug
**Describe the bug**

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2726, in containerapp_up
    up_output(app, no_dockerfile=(source and not _has_dockerfile(source, dockerfile)))
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_up_utils.py", line 864, in up_output
    url = safe_get(
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_utils.py", line 1063, in safe_get
    return model.get(keys[-1], default)
AttributeError: 'NoneType' object has no attribute 'get'
az_command_data_logger: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2726, in containerapp_up
    up_output(app, no_dockerfile=(source and not _has_dockerfile(source, dockerfile)))
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_up_utils.py", line 864, in up_output
    url = safe_get(
  File "/home/artur/.azure/cliextensions/containerapp/azext_containerapp/_utils.py", line 1063, in safe_get
    return model.get(keys[-1], default)
AttributeError: 'NoneType' object has no attribute 'get'
**To Reproduce**

**Expected behavior**

**Environment summary**

azure-cli                         2.43.0

core                              2.43.0
telemetry                          1.0.8

Extensions:
containerapp                      0.3.16
ai-examples                        0.2.5
ml                                2.11.0
ssh                                1.1.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1
**Additional context**

**Comment by SaurabhSharma-MSFT** [comment]
@kanuw We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@kanuw  I am not able to reproduce this issue.  
![image](https://user-images.githubusercontent.com/38112130/209113983-2fda1dfb-92b8-42cb-80f3-acc725b1e70c.png)

Can you please try updating your extension to version 0.3.17.

**Comment by kanuw** [comment]
Upgraded to version 0.3.18 and now it's working
