### ISSUE TITLE
az monitor diganostic setting command failing since today 

### ISSUE THREAD

**Issue by raunaknarooka** [Azure/azure-cli#24911]
## Describe the bug

**Command Name**
`az monitor diagnostic-settings create --resource  --name --event-hub  --event-hub-rule  --logs '[{"category": "FunctionAppLogs",  "enabled": true, "retentionPolicy": { "enabled": false, "days": 0 }}]' --debug`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'AAZCommandCtx' object has no attribute 'resource'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 145, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/diagnostic_settings/_create.py", line 33, in _handler
    self._execute_operations()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/diagnostic_settings/_create.py", line 176, in _execute_operations
    self.pre_operations()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/operations/diagnostics_settings.py", line 98, in pre_operations
    rg = parse_resource_id(ctx.resource)['resource_group']
AttributeError: 'AAZCommandCtx' object has no attribute 'resource'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az monitor diagnostic-settings create --resource {} --name {} --event-hub {} --event-hub-rule {} --logs {} --debug`

## Expected Behavior
I expect the diagnosti setting to be created. It has been working yesterday but suddenly it stopped working today.I am runnign this step throgh the Azure devops pipeline, but it seems it does not even work locally.

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@raunaknarooka Please look at this issue https://github.com/Azure/azure-cli/issues/24840 and see if that helps.

**Comment by raunaknarooka** [comment]
Yes it works, thanks. I am wondering, where can we get a notification of such breaking changes in the command?

**Comment by RakeshMohanMSFT** [comment]
@raunaknarooka You should be able to find here in this forum.

**Comment by ishepherd** [comment]
@RakeshMohanMSFT what can Azure CLI team do to improve their quality practices?

It's only 1 month since our builds were last broken by an Azure CLI bug. https://github.com/Azure/azure-cli/issues/24528
