### ISSUE TITLE
Ngs rule creating problem 

### ISSUE THREAD

**Issue by sudhas007** [Azure/azure-cli#24939]
The command failed with an unexpected error. Here is the traceback:
Expect <class 'str'>, got 80 (<class 'knack.validators.DefaultInt'>
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 5358, in create_nsg_rule
    return Create(cli_ctx=cmd.cli_ctx)(command_args=kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 145, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/nsg/rule/_create.py", line 40, in _handler
    super()._handler(command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 149, in _handler
    self.ctx = AAZCommandCtx(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command_ctx.py", line 31, in __init__
    self.args[dest] = cmd_arg
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 80, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 43, in process_data
    assert self.DataType is not None and isinstance(data, self.DataType), \
AssertionError: Expect <class 'str'>, got 80 (<class 'knack.validators.DefaultInt'>

**Comment by samueljmello** [comment]
Same problem for me, despite there being a fix in 2.43 from this [issue](https://github.com/Azure/azure-cli/issues/24853).

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by samueljmello** [comment]
Any idea on a work-around?

**Comment by necusjz** [comment]
@samueljmello Let me check, could you kindly provide the input parameters with `az network nsg rule create`?

**Comment by necusjz** [comment]
> @samueljmello Let me check, could you kindly provide the input parameters with `az network nsg rule create`?

@sudhas007 Could you help with that? :)

**Comment by sudhas007** [comment]
az network nsg rule create --name name --nsg-name Dev-Kubernetes --priority 105 --resource-group Group_DEV

**Comment by necusjz** [comment]
> az network nsg rule create --name name --nsg-name Dev-Kubernetes --priority 105 --resource-group Group_DEV

I see, you can temporarily append `--destination-port-ranges 80` as a workaround. We'll fix it in the next release.

**Comment by samueljmello** [comment]
My apologies @necusjz. Here is the command I am using:

`az network nsg rule create --nsg-name ${NSG_NAME} -g ${RESOURCE_GROUP} -n "AllowADOSSH" --priority 1000 --access "Allow" --description "Auto created rule by AZ CLI" --direction "Inbound" --protocol "Tcp" --destination-asgs "remote-access" --destination-port-ranges "22" --source-address-prefixes "${THIS_IP}"`

**Comment by necusjz** [comment]
> Same problem for me, despite there being a fix in 2.43 from this [issue](https://github.com/Azure/azure-cli/issues/24853).

It's a fix in 2.44 and will be released in 01/10/2023.

**Comment by andrewpleasants-bjss-nhs** [comment]
We get a similar issue on 2.43 when attempting to add a tag to a resource that is an "int", i.e.

`az network lb update --set 'tags.label=1' ...............`

This worked fine on 2.36

Is this related / fixed by the above PR or do we need to raise a separate issue?

**Comment by necusjz** [comment]
> We get a similar issue on 2.43 when attempting to add a tag to a resource that is an "int", i.e.
> 
> `az network lb update --set 'tags.label=1' ...............`
> 
> This worked fine on 2.36
> 
> Is this related / fixed by the above PR or do we need to raise a separate issue?

@andrewpleasants-bjss-nhs It's no related, please open a separate issue.

**Comment by kairu-ms** [comment]
> We get a similar issue on 2.43 when attempting to add a tag to a resource that is an "int", i.e.
> 
> `az network lb update --set 'tags.label=1' ...............`
> 
> This worked fine on 2.36
> 
> Is this related / fixed by the above PR or do we need to raise a separate issue?

It's fixed and will be released in 01/10/2023.
