### ISSUE TITLE
az network nsg rule create

### ISSUE THREAD

**Issue by martinevans-ptsl** [Azure/azure-cli#24955]
## Describe the bug

**Command Name**
`az network nsg rule create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expect <class 'str'>, got {'additional_properties': {}, 'id': '/subscriptions/25d76115-c785-433c-8cd5-99fceda2914d/resourceGroups/rg-mol-prd-vnet-001/providers/Microsoft.Network/applicationSecurityGroups/asg-mol-prd-rds-001', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'resource_guid': None, 'provisioning_state': None} (<class 'azure.mgmt.network.v2022_01_01.models._models_py3.ApplicationSecurityGroup'>
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 5358, in create_nsg_rule
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 145, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/aaz/latest/network/nsg/rule/_create.py", line 40, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 149, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 31, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_value.py", line 80, in __setitem__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_type.py", line 382, in process_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_value.py", line 369, in __setitem__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_type.py", line 219, in process_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_value.py", line 80, in __setitem__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_type.py", line 43, in process_data
AssertionError: Expect <class 'str'>, got {'additional_properties': {}, 'id': '/subscriptions/25d76115-c785-433c-8cd5-99fceda2914d/resourceGroups/rg-mol-prd-vnet-001/providers/Microsoft.Network/applicationSecurityGroups/asg-mol-prd-rds-001', 'name': None, 'type': None, 'location': None, 'tags': None, 'etag': None, 'resource_guid': None, 'provisioning_state': None} (<class 'azure.mgmt.network.v2022_01_01.models._models_py3.ApplicationSecurityGroup'>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nsg rule create -g {} --nsg-name {} --name {} --priority {} --direction {} --source-asgs {} {} {} --destination-asgs {} --destination-port-ranges {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} --access {} --protocol {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0
```

**Comment by necusjz** [comment]
It's duplicate with https://github.com/Azure/azure-cli/issues/24853 and will be fixed in Azure CLI 2.44.0.
