### ISSUE TITLE
az recommendation list --refresh command failed

### ISSUE THREAD

**Issue by ZoltanKoczan** [Azure/azure-cli#24964]
## It happens all the time I try to execute this command. 

**Command Name**
`az advisor recommendation list --refresh`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Session.request() got an unexpected keyword argument 'raw'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/advisor/custom.py", line 13, in list_recommendations
    _generate_recommendations(client)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/advisor/custom.py", line 152, in _generate_recommendations
    response = client.generate(raw=True)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/advisor/operations/_recommendations_operations.py", line 84, in generate
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/opt/az/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 327, in send
    response = self.session.request(  # type: ignore
TypeError: Session.request() got an unexpected keyword argument 'raw'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- simply executing the command again
- `az advisor recommendation list --refresh`

## Expected Behavior
To do not fail.

## Environment Summary
```
Linux-5.14.0-1051-oem-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0

It happens if I open Cloud Shell on azure portal, in bash and powershell as well.
```

**Comment by SaurabhSharma-MSFT** [comment]
@ZoltanKoczan Can you please refer to the recommendations provided over [here](https://github.com/Azure/azure-cli/issues/22577).

**Comment by ZoltanKoczan** [comment]
Hello,

I'm sorry for the late reply, but I've tried that already (even before opening this ticket), but it's not working:

`$ az rest --method POST --uri https://management.azure.com/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Advisor/generateRecommendations?api-version=2020-01-01
Bad Request({"error":{"code":"InvalidSubscriptionId","message":"The provided subscription identifier 'XXXXXXXXXXXXX' is malformed or invalid."}})`

The problem occurs on Azure portal Chell as well.

**Comment by SaurabhSharma-MSFT** [comment]
@ZoltanKoczan By looking at the error it looks like the subscriptionid which you are passing is not correct.  Can you please check and pass the correct subscription id.  I have tried the `az rest` command with above shared URI and it worked `https://management.azure.com/subscriptions/{subscriptionid}/providers/Microsoft.Advisor/generateRecommendations?api-version=2020-01-01`

**Comment by ZoltanKoczan** [comment]
It has worked! I really appreciate your help! 

Thank you!

**Comment by SaurabhSharma-MSFT** [comment]
@ZoltanKoczan No problem.  Glad it worked out for you.
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
