### ISSUE TITLE
Unable to enable blob CSI driver with error related to ingress-appgw addon

### ISSUE THREAD

**Issue by kaxing** [Azure/azure-cli#24971]
**Related command**

```bash
$ az aks update --enable-blob-driver --yes --debug
```

**Describe the bug**

- Throwing error message related to ingress-appgw addon.

```python
# sub ID redacted

DEBUG: urllib3.connectionpool: https://management.azure.com:443 "PUT 
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-resource-group/providers/Microsoft.ContainerService/managedClusters/cluster1?api-version=2022-08-02-preview 
HTTP/1.1" 400 303
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400

DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"LinkedInvalidPropertyId","message":"Property id '' at path 
'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or 
'/providers/{resourceProviderNamespace}/'."}}
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\user1\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 823, in aks_update
    return aks_update_decorator.update_mc(mc)
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6341, in update_mc
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6313, in put_mc
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "C:\Users\user1\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_08_02_preview\operations\_managed_clusters_operations.py", line 
1760, in begin_create_or_update
    raw_result = self._create_or_update_initial(  # type: ignore
  File "C:\Users\user1\.azure\cliextensions\aks-preview\azext_aks_preview\vendored_sdks\azure_mgmt_preview_aks\v2022_08_02_preview\operations\_managed_clusters_operations.py", line 
1624, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (LinkedInvalidPropertyId) Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. 
Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect fully qualified resource Id that start with 
'/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

ERROR: cli.azure.cli.core.azclierror: (LinkedInvalidPropertyId) Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect 
fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect fully qualified resource Id that start with 
'/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
ERROR: az_command_data_logger: (LinkedInvalidPropertyId) Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect fully 
qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id '' at path 'properties.addonProfiles.ingressApplicationGateway.config.applicationGatewayId' is invalid. Expect fully qualified resource Id that start with 
'/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03D16778>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 2.566 seconds (init: 0.571, invoke: 1.995)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3783 in cache
```

**To Reproduce**

- Unable to reproduce

**Expected behavior**

- Uncertain if it's a good idea to bypass invalid values in other addons.

**Environment summary**

- Windows 10 + Prompt
```python
INFO: az_command_data_logger: extension name: aks-preview
INFO: az_command_data_logger: extension version: 0.5.103

DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.40.0 (MSI) azsdk-python-azure-mgmt-containerservice/20.3.0b Python/3.10.5 (Windows-10-10.0.20348-SP0)'
```

**Additional context**

-  Workaround:
For future travelers, this is a possible step to resolve the problem, 
```bash
# Sync the resource state with Azure
$ az aks update

# disable the addon regardless if it's installed or not
az aks addon disable ingress-appgw

# Check if the add-ons are all in the desired state
$ az aks addon list

# Sync the resources state once more
$ az aks update
```

**Comment by navba-MSFT** [comment]
@kaxing Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kaxing Thanks for reaching out to us and reporting this issue. Could you please update your `aks-preview `extension by running the below command and check if you see the same issue ?

> **az extension update -n aks-preview**

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kaxing I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by kaxing** [comment]
@navba-MSFT I no longer have the environment.

But the extension was installed about the same time.

**Comment by navba-MSFT** [comment]
@kaxing Thanks for getting back. I tried the same command in my environment and it works fine. If you encounter the same issue in your environment in future, please feel free to reopen this issue. We would be happy to help.

**Comment by kaxing** [comment]
@navba-MSFT sure, thank you!
