### ISSUE TITLE
CognitiveServices Accounts are not able to use the list-skus feature in the az cli

### ISSUE THREAD

**Issue by chawlaj100** [Azure/azure-cli#24993]
## Describe the bug

**Command Name**
`az cognitiveservices account list-skus`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/cognitiveservices/custom.py", line 75, in list_skus
    return cf_accounts(cmd.cli_ctx).list_skus(resource_group_name, account_name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/cognitiveservices/operations/_accounts_operations.py", line 1354, in list_skus
    request = build_list_skus_request(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/cognitiveservices/operations/_accounts_operations.py", line 330, in build_list_skus_request
    "accountName": _SERIALIZER.url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/cognitiveservices/_serialization.py", line 703, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/cognitiveservices/_serialization.py", line 780, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cognitiveservices account list-skus --kind {}`

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
quota 0.1.0
connectedk8s 1.3.3
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@chawlaj100 We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@chawlaj100 I am not able to reproduce this issue and cmdlet works as expected.  (See screenshot below)
![image](https://user-images.githubusercontent.com/38112130/210040350-70b820fd-eecd-46cc-bc99-eee9c7ef38de.png)
