### ISSUE TITLE
az storage container immutability-policy create failure

### ISSUE THREAD

**Issue by Ranjith-George** [Azure/azure-cli#25013]
## Describe the bug

**Command Name**
`az storage container immutability-policy create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 48, in create_or_update_immutability_policy
    return client.create_or_update_immutability_policy(resource_group_name, account_name, container_name,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/storage/v2022_09_01/operations/_blob_containers_operations.py", line 1697, in create_or_update_immutability_policy
    request = build_create_or_update_immutability_policy_request(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/storage/v2022_09_01/operations/_blob_containers_operations.py", line 325, in build_create_or_update_immutability_policy_request
    "resourceGroupName": _SERIALIZER.url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/storage/_serialization.py", line 697, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/storage/_serialization.py", line 782, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container immutability-policy create --account-name {} --container-name {} --period {}`

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Please add `--resource-group` as a workaround. We will fix the resource group auto complete later
