### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable: '/Users/ZZZ/bin/azcopy'

### ISSUE THREAD

**Issue by hemant-belwalkar** [Azure/azure-cli#25021]
Getting error while running following 

az storage fs directory upload -f ZZZ --account-name 'ZZZ' -s “/Users/ZZZ/azdb/retail_db” --recursive 

Azcopy command: ['/Users/ZZZ/bin/azcopy', 'copy', '“/Users/ZZZ/azdb/retail_db”', 'https://dartdbstorage.dfs.core.windows.net/ZZZ?se=2023-01-03T18%3A33%3A31Z&sp=rwdlac&sv=2018-03-28&ss=b&srt=co&sig=', '--recursive']
The command failed with an unexpected error. Here is the traceback:
[Errno 86] Bad CPU type in executable: '/Users/ZZZ/bin/azcopy'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 86, in storage_fs_directory_copy
    azcopy.copy(source, destination, flags=flags)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 91, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 85, in run_command
    result = subprocess.call(args, env=dict(os.environ, **env_kwargs))
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/ZZZ/bin/azcopy'

**Comment by hemant-belwalkar** [comment]
CPU architecture type - ARM64
Installation Method for Azure CLI - Homebrew

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Seems like the pre-installed `azcopy` went wrong. Can you manually replace `/Users/ZZZ/bin/azcopy` with proper version: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

**Comment by hemant-belwalkar** [comment]
Tried replacing /Users/ZZZ/bin/azcopy with https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy. While the error is not shown, but 

az storage fs directory upload -f ZZZ --account-name 'ZZZ' -s “/Users/ZZZ/azdb/retail_db” --recursive

does not upload the folder to azure.

**Comment by evelyn-ys** [comment]
Can't reproduce. I can successfully upload folders recursively
![image](https://user-images.githubusercontent.com/10227683/210485756-923a3c6f-c8ef-437d-93a0-d57f21f06a62.png)

Please confirm the storage account `ZZZ` is ADLS Gen2 account and the file system `ZZZ` does exist.
Can you share the whole log so that we can know what's happening more than just "does not upload the folder to azure."

**Comment by hemant-belwalkar** [comment]
Please find below the log details. I had replaced the actual names with zzz. Please find below the command with actual names.

1. account name dartdbstorage is ADLS Gen2 Account
![image](https://user-images.githubusercontent.com/35556618/211019092-67bdbaa3-68bc-4215-bec9-70f80fe2ffe4.png)

3. File system “/Users/hemantbelwalkar/azdb/retail_db” exists on MacBook.

The command errors out with message 'Cannot scan path “/Users/hemantbelwalkar/azdb/retail_db”, please verify that it is a valid.'

hemantbelwalkar@HEMANTs-MacBook-Pro ~ % az storage fs directory upload -f dbdata --account-name 'dartdbstorage' -s “/Users/hemantbelwalkar/azdb/retail_db” --recursive
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
Azcopy command: ['/Users/hemantbelwalkar/bin/azcopy', 'copy', '“/Users/hemantbelwalkar/azdb/retail_db”', 'https://dartdbstorage.dfs.core.windows.net/dbdata?se=2023-01-07T13%3A03%3A23Z&sp=rwdlac&sv=2018-03-28&ss=b&srt=co&sig=', '--recursive']
INFO: Scanning...
INFO: Any empty folders will be processed, because source and destination both support folders

failed to perform copy command due to error: cannot start job due to error: cannot scan the path /Users/hemantbelwalkar/“/Users/hemantbelwalkar/azdb/retail_db”, please verify that it is a valid.

Failed to perform copy operation.

File System Screenshot:


<img width="800" alt="20230106184043" src="https://user-images.githubusercontent.com/35556618/211018902-ee4eb0f8-92e5-4eaf-b732-8d63cc7eb1ea.png">

**Comment by hemant-belwalkar** [comment]
Please note that I am able to upload the folder using Azure Storage Explorer
