### ISSUE TITLE
Not able to login to az using cli

### ISSUE THREAD

**Issue by RameshNaidu207** [Azure/azure-cli#25030]
Not able to goin to az login .. previously it is working 

C:\Users\to974153\.azure>az login
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_session.py", line 36, in load
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_session.py", line 54, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\to974153\\.azure\\az.sess'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 39, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 902, in get_default_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 81, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_session.py", line 50, in load
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_session.py", line 54, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\to974153\\.azure\\az.sess'

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@RameshNaidu207 Delete the C:/users/your-user-name/.azure directory and reinstall Azure cli from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli and retry the operation.

**Comment by jiasli** [comment]
This issue was previously reported by https://github.com/Azure/azure-cli/issues/14881

Looks like your local user account somehow lost permission to `C:\Users\to974153\.azure\az.sess`. Could you follow https://github.com/Azure/azure-cli/issues/25030#issuecomment-1370378163 and let us know if that works?

**Comment by RameshNaidu207** [comment]
H All,

The issue got resolved by deleting the .azure folder and then execute  az
login.   .azure folder is getting creating again wil all requested files.

thank you  for al your ..

Regards,
Ramesh
