### ISSUE TITLE
Zip Deployment

### ISSUE THREAD

**Issue by balajiramadass** [Azure/azure-cli#25047]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 40, in _ex_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4437, in webapp_up
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 561, in enable_zip_deploy
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --runtime {} --sku {} --logs`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@seligj95 I am not able to reproduce this issue. (see screenshot below) 
![image](https://user-images.githubusercontent.com/38112130/213169904-337f673b-329d-4375-842a-2ec8380cc1ef.png)
can you make sure that you are runnin az webapp up from the context of the dir where the content of the code to be deployed is. Please refer to [this]( https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python#create-a-web-app) tutorial.

**Comment by SaurabhSharma-MSFT** [comment]
@balajiramadass Please let us know if you still need any help.

**Comment by balajiramadass** [comment]
Hey,

I will try once again and let you know

Thanks
Balaji

**Comment by SaurabhSharma-MSFT** [comment]
@balajiramadass Please let me know if we can proceed with the issue closure if you are unblocked. Thanks.
