### ISSUE TITLE
Attaching File Storage to a Container App environment fails

### ISSUE THREAD

**Issue by rvanoord** [Azure/azure-cli#25073]
## Describe the bug
Attempt to attach file storage to a container app using the instructions here (https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts-azure-files?tabs=bash) fails.

Failure occurred both using the windows command line and linux (WSL).

**Command Name**
`az containerapp env storage set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.cli.core.auth.persistence'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 517, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 313, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\rvanoord\.azure\cliextensions\containerapp\azext_containerapp\custom.py", line 29, in <module>
    from ._github_oauth import get_github_access_token
  File "C:\Users\rvanoord\.azure\cliextensions\containerapp\azext_containerapp\_github_oauth.py", line 13, in <module>
    from azure.cli.core.auth.persistence import SecretStore, build_persistence
ModuleNotFoundError: No module named 'azure.cli.core.auth.persistence'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp env storage set --name {} --resource-group {} --storage-name {} --azure-file-account-name {} --azure-file-account-key {} --azure-file-share-name {} --access-mode {}`

## Expected Behavior
Should run without error. 

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.8.9
Installer: 

azure-cli 2.28.0 *

Extensions:
containerapp 0.3.4
front-door 1.0.16

```

**Comment by RakeshMohanMSFT** [comment]
@rvanoord Can you please update your az cli to latest version [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli) and retry?

**Comment by rvanoord** [comment]
Thanks @RakeshMohanMSFT - upgrading the AZ CLI and the container app extensions worked

**Comment by yonzhan** [comment]
issue resolved
