### ISSUE TITLE
imiw

### ISSUE THREAD

**Issue by natashakona** [Azure/azure-cli#25080]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1673331518.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1673288097,
  "nbf": 1673288097,
  "exp": 1673291997,
  "aio": "AXQAi/8TAAAAphDBTJ0ckVVQa/IL0T420NGX39gZ3DVUW+jtPWdYFvbz8ytMVCjUoMXCmxPsLzE/FZBu37f46O3l1ubnj9EXReM3Mqt2+Wrhivef18JwEiSDHeEjohOQ4bKKqppFmnN2HaLH8CcCM/gBu9Rsql54bA==",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "888ba71be52ce5d3cfa02429e1bfb94f0ef234145838fd5c0d004cee8e62840a",
  "preferred_username": "doug@imiw.net",
  "rh": "0.ASgAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAIo.",
  "sub": "B-j5O10jJrk0q5_CHITnmXWA6jrhxWtuSxsm66uIEC0",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "yWgDICwKhEi8pdylglPVAA",
  "ver": "2.0"
}
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1828, in acquire_token_interactive
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 639, in obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 677, in _obtain_token_by_browser
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 142, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 547, in obtain_token_by_auth_code_flow
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 731, in _obtain_token_by_authorization_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 116, in _obtain_token
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oauth2.py", line 788, in _obtain_token
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 700, in <lambda>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 314, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 117, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 158, in __add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/oauth2cli/oidc.py", line 77, in decode_id_token
RuntimeError: 9. The ID token already expires. Make sure your computer's time and time zone are both correct. Current epoch = 1673331518.  The id_token was: {
  "aud": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "iss": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "iat": 1673288097,
  "nbf": 1673288097,
  "exp": 1673291997,
  "aio": "AXQAi/8TAAAAphDBTJ0ckVVQa/IL0T420NGX39gZ3DVUW+jtPWdYFvbz8ytMVCjUoMXCmxPsLzE/FZBu37f46O3l1ubnj9EXReM3Mqt2+Wrhivef18JwEiSDHeEjohOQ4bKKqppFmnN2HaLH8CcCM/gBu9Rsql54bA==",
  "idp": "https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/",
  "nonce": "888ba71be52ce5d3cfa02429e1bfb94f0ef234145838fd5c0d004cee8e62840a",
  "preferred_username": "doug@imiw.net",
  "rh": "0.ASgAMe_N-B6jSkuT5F9XHpElWpV3sATbjRpGu-4C-eG_e0YBAIo.",
  "sub": "B-j5O10jJrk0q5_CHITnmXWA6jrhxWtuSxsm66uIEC0",
  "tid": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
  "uti": "yWgDICwKhEi8pdylglPVAA",
  "ver": "2.0"
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0
```

**Comment by natashakona** [comment]
the time on my laptop was off by 12 hours. I posted this issue minutes ago but was posted 12 hours ago. my laptop was off by 12 hours. easy fix sorry to bother you!

**Comment by jiasli** [comment]
Duplicate of #23223
