### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Jaylapirfta** [Azure/azure-cli#25127]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'in_tree'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
  File "C:\Users\Lapir\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 11, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
  File "C:\Users\Lapir\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 148, in __call__
    self.run()
  File "C:\Users\Lapir\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 721, in run
    b_flag, c_flag, outside, cmd = self._special_cases(cmd, outside)
  File "C:\Users\Lapir\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 521, in _special_cases
    continue_flag, cmd = self.handle_scoping_input(continue_flag, cmd, cmd_stripped)
  File "C:\Users\Lapir\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 600, in handle_scoping_input
    if self.completer.command_tree.in_tree(tree_path):
AttributeError: 'NoneType' object has no attribute 'in_tree'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.0 *

Extensions:
arcdata 1.4.10
interactive 0.4.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness
