### ISSUE TITLE
az interactive suddenly failed

### ISSUE THREAD

**Issue by Jas0n0ss** [Azure/azure-cli#25128]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'argcomplete.compat'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/jason/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/Users/jason/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 38, in <module>
    from .az_completer import AzCompleter
  File "/Users/jason/.azure/cliextensions/interactive/azext_interactive/azclishell/az_completer.py", line 19, in <module>
    from .argfinder import ArgsFinder
  File "/Users/jason/.azure/cliextensions/interactive/azext_interactive/azclishell/argfinder.py", line 9, in <module>
    from argcomplete.compat import USING_PYTHON2, ensure_bytes
ModuleNotFoundError: No module named 'argcomplete.compat'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
macOS-13.1-x86_64-i386-64bit, Darwin 22.2.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.44.1

Extensions:
interactive 0.4.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
Please update interactive to latest version and try again

**Comment by KhaaL** [comment]
> @Jas0n0ss try upgrading to latest interactive patch. 0.4.5 is broken.
> 
> I had success with 0.4.6
> 
> run `az upgrade`

Thanks, az upgrade fixed my problem 😃

**Comment by Jas0n0ss** [comment]
> @Jas0n0ss try upgrading to latest interactive patch. 0.4.5 is broken.
> 
> I had success with 0.4.6
> 
> run `az upgrade`

Thank you very much , upgrade fixed the issue
