### ISSUE TITLE
Unable to abort service bus migration

### ISSUE THREAD

**Issue by andreireinus** [Azure/azure-cli#25161]
## Describe the bug

Unable to abort ongoing migration. 

**Command Name**
`az servicebus migration abort`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 766, in revert
    request = build_revert_request(
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/servicebus/v2022_01_01_preview/operations/_migration_configs_operations.py", line 251, in build_revert_request
    "configName": _SERIALIZER.url("config_name", config_name, 'str'),
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a standard service bus 
- Create a premium service bus (add a private endpoint and remove public access)
- start the migration 
- `az servicebus migration abort --resource-group {} --name {} --subscription {}`

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0 *

Extensions:
azure-devops 0.25.0
application-insights 0.1.16

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@andreireinus Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
