### ISSUE TITLE
Unable to connect to AKS cluster with 'az aks get-credentials --resource-group mygroup --name mycluster

### ISSUE THREAD

**Issue by larrywa** [Azure/azure-cli#25199]
Azure CLI version: 2.44.1
Powershell command window in Terminal, attempted with both admin and non-admin mode.

Repo:
az login
az set account --subscription 'mysubscriptionid'
az aks get-credentials --resource-group mygroup --name mycluster

Error:
az aks get-credentials --resource-group MyResourceGroup --name akstestcluster
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'C:\\Users\\larrywa\\.kube\\config'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1118, in aks_get_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1250, in _print_or_merge_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1214, in merge_kubernetes_configurations
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\larrywa\\.kube\\config'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

I did not try older versions of az cli.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@larrywa Can you please check if you have admin privileges to access the config file over here `C:\Users\<username>\.kube\` ?

**Comment by SaurabhSharma-MSFT** [comment]
@larrywa Please let us know if you still having issues and needs help.

**Comment by larrywa** [comment]
Sorry, it took so long to get a response, I forgot I even had a problem.

**Comment by jerrychong25** [comment]
Hi @larrywa / @SaurabhSharma-MSFT ,

I've faced similar error like your case.

Could share what is steps required on resolving this issue?

Error Logs:
```
17:53:38  + az account set --subscription ****
17:53:39  + az aks get-credentials --resource-group RG-AKS-EXP-BI-DEV-WEU-001 --name AKS-EXP-BI-DEV-WEU-001
17:53:41  ERROR: The command failed with an unexpected error. Here is the traceback:
17:53:41  ERROR: [Errno 30] Read-only file system: '/.kube/config'
17:53:41  Traceback (most recent call last):
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
17:53:41      cmd_result = self.invocation.execute(args)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
17:53:41      raise ex
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
17:53:41      results.append(self._run_job(expanded_arg, cmd_copy))
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
17:53:41      result = cmd_copy(params)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
17:53:41      return self.handler(*args, **kwargs)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
17:53:41      return op(**command_args)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 1280, in aks_get_credentials
17:53:41      _print_or_merge_credentials(
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 1403, in _print_or_merge_credentials
17:53:41      with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
17:53:41  OSError: [Errno 30] Read-only file system: '/.kube/config'
17:53:41  To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
``` 

Thank you.

Best Regards,
Jerry Chong

**Comment by jerrychong25** [comment]
Hi @larrywa / @SaurabhSharma-MSFT ,

I've faced similar error like your case.

Could share what is steps required on resolving this issue?

Error Logs:
```
17:53:38  + az account set --subscription ****
17:53:39  + az aks get-credentials --resource-group RG_1 --name AKS-1
17:53:41  ERROR: The command failed with an unexpected error. Here is the traceback:
17:53:41  ERROR: [Errno 30] Read-only file system: '/.kube/config'
17:53:41  Traceback (most recent call last):
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
17:53:41      cmd_result = self.invocation.execute(args)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
17:53:41      raise ex
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
17:53:41      results.append(self._run_job(expanded_arg, cmd_copy))
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
17:53:41      result = cmd_copy(params)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
17:53:41      return self.handler(*args, **kwargs)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
17:53:41      return op(**command_args)
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 1280, in aks_get_credentials
17:53:41      _print_or_merge_credentials(
17:53:41    File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 1403, in _print_or_merge_credentials
17:53:41      with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
17:53:41  OSError: [Errno 30] Read-only file system: '/.kube/config'
17:53:41  To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
``` 

Thank you.

Best Regards,
Jerry Chong

**Comment by baarsik** [comment]
PowerShell runs in admin mode.
Azure CLI v 2.56.0
Executed commands:
`az login`
_works fine_
`az account set --subscription [my sub]`
_works fine_
`az aks get-credentials --resource-group [rg] --name [name] --overwrite-existing`
returns this
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'C:\\Users\\barsi\\.kube\\config'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1298, in aks_get_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1430, in _print_or_merge_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1353, in merge_kubernetes_configurations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1342, in load_kubernetes_configuration
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\barsi\\.kube\\config'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```
