### ISSUE TITLE
create a Service Principal with Contributor access to the Resource Group , gave error 

### ISSUE THREAD

**Issue by dacheampong1** [Azure/azure-cli#25207]
az ad sp create-for-rbac --name GH-Action-eshoponweb --role contributor --scopes /subscriptions/36305196-0bc1-4af5-8d33-79ca3ffc94c8/resourceGroups/rg-az400-eshopeonweb-DAV --sdk-auth
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/david/.azure/commands/2023-01-23.16-12-29.ad_sp_create-for-rbac.192.log'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 30] Read-only file system: '/home/david/.azure/commands/2023-01-23.16-12-29.ad_sp_create-for-rbac.192.log'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by yonzhan** [comment]
@jiasli for awareness
