### ISSUE TITLE
Crash in az aks update (preview command)

### ISSUE THREAD

**Issue by mladedav** [Azure/azure-cli#25287]
## Describe the bug

Updating ssh keys for an aks scale set fails.

**Command Name**
`az aks update`

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 558, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 479, in load_arguments
  File "C:\Users\david\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\david\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:

- `az aks update --name {} -g {} --ssh-key-value {}`

## Expected Behavior

The command works

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
aks-preview 0.5.41
azure-iot 0.12.1

```
## Additional Context

The environment summary has been auto-generated. If I run Python, I have 3.9.1 installed and used by default.
python --version
Python 3.9.1

**Comment by mladedav** [comment]
The issue seems to have been caused by older version of Azure CLI. Sorry for this issue, closing since it is invalid.

**Comment by navba-MSFT** [comment]
@mladedav Thanks for the update. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
