### ISSUE TITLE
az aks get-credentials: [Errno 22] Invalid argument: '"C'

### ISSUE THREAD

**Issue by tuxerrante** [Azure/azure-cli#25282]
## Describe the bug
After creating a new AKS cluster I'm trying to get access through AD with Powershell.
It works with Azure CLI.

az cli version 2.37 and 2.44.1
AKS 1.24.6
Authentication and Authorization: Azure AD authentication with Kubernetes RBAC.
I'm part of the authorized groups.

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 22] Invalid argument: '"C'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2085, in aks_get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2206, in _print_or_merge_credentials
OSError: [Errno 22] Invalid argument: '"C'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Creatre a new AKS cluster from the Azure portal
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
account 0.2.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@tuxerrante Thanks for reaching out to us and reporting this issue. I see that you are using an older version of AzCLI. Could you please [update your Azure cli ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)to the most recent version and test this command again ? Awaiting your reply.

**Comment by tuxerrante** [comment]
Hi,
I've already tried with the latest az cli, but the issue was I was trying with powershell and not az cli.

Here's how I've solved:
in Powershell
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
az login
Connect-AzAccount
Import-AzAksCredential -ResourceGroupName aff-experiments -Name aks-test
kubectl config list-context

choco install starship

kubectl completion powershell >> $PROFILE
Invoke-Expression (&starship init powershell) >> $PROFILE
```
- https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#winget
- https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-portal?tabs=azure-powershell#connect-to-the-cluster

WSL:
```
curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.25/kubelogin-linux-amd64.zip
unzip /mnt/c/Users/alessandro.affinito/Downloads/kubelogin-linux-amd64.zip -d /tmp
sudo mv /tmp/bin/linux_amd64/kubelogin /usr/bin/
sudo chmod +x /usr/bin/kubelogin
```
