### ISSUE TITLE
Error running  az synapse notebook import --workspace-name wsn --name nbName --file `@'"./nbName.ipynb"'

### ISSUE THREAD

**Issue by v-reduardo** [Azure/azure-cli#25295]
## Describe the bug

**Command Name**
`az synapse notebook import`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object does not support item assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 254, in create_or_update_notebook
TypeError: 'str' object does not support item assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook import --workspace-name {} --name {} --file {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0 *

Extensions:
powerbidedicated 0.2.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@v-reduardo Thanks for reaching out to us and reporting this issue. Could you please upgrade your Azure CLI to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) and let me know if you still see the same issue. Awaiting your reply.

**Comment by v-reduardo** [comment]
Hi

I'm trying to run this as task on a devops CI pipeline, seems to get latest version at runtime:

***@***.***

**Comment by v-reduardo** [comment]
Found the issue:

According to documentation command should be:
az synapse notebook import --workspace-name testsynapseworkspace  --name testnotebook --file @"path/notebook.ipynb"

it works if I do:
az synapse notebook import --workspace-name testsynapseworkspace --name testnotebook --file "@path/notebook.ipynb"

For some reason notebooks comming from synapse are stored as .json on git repo. CLI command won't work with these files so I would have to manually export nbs from synapse studio with .ipynb format and commit them from local branch so file format is preserved on repo.
