### ISSUE TITLE
Azure Cli and Adding DNS configuration to Private Endpoint

### ISSUE THREAD

**Issue by mnadeem** [Azure/azure-cli#25304]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

I have created private endpoint using the link https://github.com/ezYakaEagle442/aro-prv-acr/blob/master/setup-storage.md

```
echo Creating Private DNS zone %postgresPrivateLinkDnsZoneName%
call az network private-dns zone create --resource-group %resourceGroup% --name %postgresPrivateLinkDnsZoneName%

echo Linking privte DNS Zone %postgresPrivateLinkDnsZoneName% to Vnet  %vNetName%
call az network private-dns link vnet create --resource-group %resourceGroup%  --zone-name %postgresPrivateLinkDnsZoneName% --name %postgresVnetDnsLinkName% --virtual-network %vNetName%  --registration-enabled false

FOR /F "tokens=1" %%F IN ('call az postgres server show --name %postgresDbServerName% --resource-group %resourceGroup% --query "id" --output tsv')  DO SET postgresServerId=%%F

echo Feteched %postgresServerId%

echo Creating private enpoint   %postgresPrivateEnpointName% 
call az network private-endpoint create --name %postgresPrivateEnpointName% --resource-group %resourceGroup% --subnet %containerSubnetName% --vnet-name %vNetName% --private-connection-resource-id %postgresServerId%   --group-id postgresqlServer  --location %location%  --connection-name postgres-pe-svc-con --nic-name %postgresNetworkInterfaceName%


FOR /F "tokens=1" %%F IN ('call az network private-endpoint show --name %postgresPrivateEnpointName% --resource-group %resourceGroup% --query networkInterfaces[0].id -o tsv')  DO SET postgresInterfaceId=%%F

echo Feteched %postgresInterfaceId%

FOR /F "tokens=1" %%F IN ('call az resource show --ids %postgresInterfaceId% --api-version 2019-04-01 --query properties.ipConfigurations[0].properties.privateIPAddress --output tsv')  DO SET postgresInterfaceIp=%%F
echo Feteched %postgresInterfaceIp%

echo Creating private dns record set %postgresPrivateDnsRecordSetName% 
call az network private-dns record-set a create --resource-group %resourceGroup% --name %postgresPrivateDnsRecordSetName% --zone-name %postgresPrivateLinkDnsZoneName%

echo Adding record to private dns record set %postgresPrivateDnsRecordSetName% 
call az network private-dns record-set a add-record --resource-group %resourceGroup% --record-set-name %postgresPrivateDnsRecordSetName% --zone-name %postgresPrivateLinkDnsZoneName% --ipv4-address %postgresInterfaceIp%
```

<img width="692" alt="image" src="https://user-images.githubusercontent.com/476145/215757210-895f5e08-5983-435c-bbdf-bddd22d6997d.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/476145/215756998-5cf3c3f5-49e5-4db6-ad21-d4fe865019ee.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/476145/215756708-e19a5a40-b17e-4cb1-b808-2b8b05480971.png">

Note in the above it is recommending the following

`To be configured correctly, the following FQDNs are required in your private DNS setup`

If we hit **add configuration**

<img width="769" alt="image" src="https://user-images.githubusercontent.com/476145/215757763-721c9b1c-73c4-43e1-8dd8-bd23b2b452f7.png">

**What is the Azure Cli command to add configuration to private enpoint ?**

After adding, it works fine.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/476145/215758530-9f1eb716-c1b6-4e94-9309-4331c45b874c.png">

**To Reproduce**

```
echo Creating Private DNS zone %postgresPrivateLinkDnsZoneName%
call az network private-dns zone create --resource-group %resourceGroup% --name %postgresPrivateLinkDnsZoneName%

echo Linking privte DNS Zone %postgresPrivateLinkDnsZoneName% to Vnet  %vNetName%
call az network private-dns link vnet create --resource-group %resourceGroup%  --zone-name %postgresPrivateLinkDnsZoneName% --name %postgresVnetDnsLinkName% --virtual-network %vNetName%  --registration-enabled false

FOR /F "tokens=1" %%F IN ('call az postgres server show --name %postgresDbServerName% --resource-group %resourceGroup% --query "id" --output tsv')  DO SET postgresServerId=%%F

echo Feteched %postgresServerId%

echo Creating private enpoint   %postgresPrivateEnpointName% 
call az network private-endpoint create --name %postgresPrivateEnpointName% --resource-group %resourceGroup% --subnet %containerSubnetName% --vnet-name %vNetName% --private-connection-resource-id %postgresServerId%   --group-id postgresqlServer  --location %location%  --connection-name postgres-pe-svc-con --nic-name %postgresNetworkInterfaceName%


FOR /F "tokens=1" %%F IN ('call az network private-endpoint show --name %postgresPrivateEnpointName% --resource-group %resourceGroup% --query networkInterfaces[0].id -o tsv')  DO SET postgresInterfaceId=%%F

echo Feteched %postgresInterfaceId%

FOR /F "tokens=1" %%F IN ('call az resource show --ids %postgresInterfaceId% --api-version 2019-04-01 --query properties.ipConfigurations[0].properties.privateIPAddress --output tsv')  DO SET postgresInterfaceIp=%%F
echo Feteched %postgresInterfaceIp%

echo Creating private dns record set %postgresPrivateDnsRecordSetName% 
call az network private-dns record-set a create --resource-group %resourceGroup% --name %postgresPrivateDnsRecordSetName% --zone-name %postgresPrivateLinkDnsZoneName%

echo Adding record to private dns record set %postgresPrivateDnsRecordSetName% 
call az network private-dns record-set a add-record --resource-group %resourceGroup% --record-set-name %postgresPrivateDnsRecordSetName% --zone-name %postgresPrivateLinkDnsZoneName% --ipv4-address %postgresInterfaceIp%
```

**Expected behavior**

It should have DNS configuration Added, however DNS configuration should added manually using the portal, not sure if any other command needs to be executed.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@mnadeem Are your looking for `az network private-endpoint dns-zone-group add`? You can check the following link for details:

https://learn.microsoft.com/en-us/cli/azure/network/private-endpoint/dns-zone-group?view=azure-cli-latest#az-network-private-endpoint-dns-zone-group-add

**Comment by mnadeem** [comment]
Not sure if I am missing anything. Error is not clear to me, is there any example.

```
az network private-endpoint dns-zone-group add --resource-group m-dev-rg --endpoint-name blob-my-dev-vn-my-dev-con-sn-pe --private-dns-zone privatelink.blob.core.windows.net --zone-name privatelink.blob.core.windows.net --name default
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'private_dns_zone_configs'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 3644, in add_private_endpoint_private_dns_zone
AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

```

**Comment by necusjz** [comment]
@mnadeem Seems `az network private-endpoint dns-zone-group create` missed.

https://learn.microsoft.com/en-us/cli/azure/network/private-endpoint/dns-zone-group?view=azure-cli-latest#az-network-private-endpoint-dns-zone-group-create

**Comment by nachoalonsoportillo** [comment]
@mnadeem feel free to request to reopen in case you want to proceed with it. Thanks!

**Comment by nachoalonsoportillo** [comment]
@yonzhan This one is stale. Please, close. Thanks!
