### ISSUE TITLE
az bicep upgrade failure

### ISSUE THREAD

**Issue by kmkelly2015** [Azure/azure-cli#25329]
### **This is autogenerated. Please review and update as needed.**

I ran "az bicep upgrade" and now this is what happens.
I'm using the latest version of az cli (2.44.1), I have tried rolling back to a previous version of bicep (13.1) but i get the same issue
Looks similar to this
https://github.com/Azure/azure-cli/issues/24482

**Command Name**
`az bicep version`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3708, in show_bicep_cli_version
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 75, in run_bicep_command
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 203, in _get_bicep_installed_version
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 241, in _run_command
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep version`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.1

Extensions:
account 0.2.5
automation 0.2.1
front-door 1.0.17
virtual-wan 0.2.15

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kmkelly2015 Thanks for reaching out to us and reporting this issue. Could you please follow the below action plan in order and let me know if that helps ?

**Plan 1:**
Could you try running %USERPROFILE\.azure\bin\bicep.exe --version and see if it works?

**Plan 2:**
If the above plan doesn't help, Please clean up the %USERPROFILE\.azure\bin folder and run az bicep install to reinstall Bicep for Azure CLI.

Hope this helps.

**Comment by kmkelly2015** [comment]
@navba-MSFT This has fixed the issue.
Thank you
