### ISSUE TITLE
cant run " az aks get-credentials --resource-group"

### ISSUE THREAD

**Issue by eilanponycell** [Azure/azure-cli#25335]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/path'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1118, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1236, in _print_or_merge_credentials
    os.makedirs(directory)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/path'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --subscription {}`

## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.44.1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@eilanponycell Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@eilanponycell Could you please confirm if you are running this command from the `Azure Cloud Shell `? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@eilanponycell I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are running this command from the Azure Cloud Shell ? . Awaiting your reply.

**Comment by navba-MSFT** [comment]
@eilanponycell The action is currently pending on you to share the details with us regarding how / where the CLI command is being run. Please feel free to reopen this thread, once you are ready to resume troubleshooting on this. We would be happy to help.
