### ISSUE TITLE
After upgrading az cli, cannot run az connectedk8s

### ISSUE THREAD

**Issue by yehiyam** [Azure/azure-cli#25354]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'HMAC' from 'Crypto.Hash' (/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/Hash/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 507, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ylivneh/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 37, in <module>
  File "/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/IO/PEM.py", line 41, in <module>
  File "/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/Cipher/__init__.py", line 35, in <module>
  File "/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/Cipher/_mode_siv.py", line 44, in <module>
  File "/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/Protocol/KDF.py", line 32, in <module>
ImportError: cannot import name 'HMAC' from 'Crypto.Hash' (/home/ylivneh/.azure/cliextensions/connectedk8s/Crypto/Hash/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {} --location {} --correlation-id {}`

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1

Extensions:
connectedk8s 1.3.10

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@yehiyam Please follow the below action plan in order and check if that helps.

**Plan 1:**
Try running the commands:  `pip install cryptography` and `pip install pycryptodome`


**Plan 2:**
If the above plan doesn't help, Could you please remove and add the connectedk8s extension ?

>az extension remove -n connectedk8s
az extension add -n connectedk8s


**Plan 3:**
If both of the above action plans doesn't help, please upgrade your python package version https://www.python.org/downloads/windows/ and check if that helps.

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yehiyam I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yehiyam The action is currently pending on you to follow the above suggested plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
