### ISSUE TITLE
az backup restore restore error with SPN

### ISSUE THREAD

**Issue by rklugt** [Azure/azure-cli#25350]
Getting this error when I would like to restore a SQLDB from one server to another. The SPN has Backup Operator and Backup Contributor permissions on the RecoveryVault. With my personal account it works. Any ideas. Successfully verified the service connection with the SPN.

CLI powershell script: 
## Create RecoveryConfig.json for restore details
az backup recoveryconfig show --resource-group P-RG-RECOVERYSERVICE --vault-name P-RECOVERYSERVICE --container-name "VMAppContainer;Compute;P-RG-Aderant;P-VM-SQL-EXSQ-1" --item-name "SQLDataBase;MSSQLSERVER;ASPState" --restore-mode AlternateWorkloadRestore --rp-name "***********" --target-item-name "ASPState_Restored" --target-server-name "A-VM-SQL-EXSQ-1.corp.loyens.nl" --target-container-name "VMAppContainer;Compute;A-RG-Aderant;A-VM-SQL-EXSQ-1" --target-server-type SQLInstance --workload-type SQLDataBase --output json | Out-File ".\recoveryconfig.json"

#Restore DB from PROD to ACC
az backup restore restore-azurewl --resource-group P-RG-RECOVERYSERVICE --vault-name P-RECOVERYSERVICE --recovery-config "recoveryconfig.json" --output table

2023-02-03T14:29:51.7929136Z ##[section]Starting: Restore DB
2023-02-03T14:29:51.8322928Z ==============================================================================
2023-02-03T14:29:51.8323643Z Task         : Azure CLI
2023-02-03T14:29:51.8324115Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2023-02-03T14:29:51.8324560Z Version      : 2.216.0
2023-02-03T14:29:51.8324837Z Author       : Microsoft Corporation
2023-02-03T14:29:51.8325116Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2023-02-03T14:29:51.8325353Z ==============================================================================
2023-02-03T14:29:52.5677259Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2023-02-03T14:30:42.4217010Z azure-cli                         2.44.1
2023-02-03T14:30:42.4295430Z 
2023-02-03T14:30:42.4325883Z core                              2.44.1
2023-02-03T14:30:42.4386551Z telemetry                          1.0.8
2023-02-03T14:30:42.4435876Z 
2023-02-03T14:30:42.4454515Z Extensions:
2023-02-03T14:30:42.4485471Z azure-devops                      0.26.0
2023-02-03T14:30:42.4520561Z 
2023-02-03T14:30:42.4540152Z Dependencies:
2023-02-03T14:30:42.4543198Z msal                              1.20.0
2023-02-03T14:30:42.4545906Z azure-mgmt-resource             21.1.0b1
2023-02-03T14:30:42.4546766Z 
2023-02-03T14:30:42.4547787Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2023-02-03T14:30:42.4574145Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2023-02-03T14:30:42.4576189Z 
2023-02-03T14:30:42.4577329Z Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]
2023-02-03T14:30:42.4578032Z 
2023-02-03T14:30:42.4579323Z Legal docs and information: aka.ms/AzureCliLegal
2023-02-03T14:30:42.4579992Z 
2023-02-03T14:30:42.4585114Z 
2023-02-03T14:30:42.4589372Z Your CLI is up-to-date.
2023-02-03T14:30:42.4635841Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2023-02-03T14:30:42.4639703Z Setting active cloud to: AzureCloud
2023-02-03T14:30:42.4647754Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2023-02-03T14:31:29.8767929Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** "--password=***" --tenant 3829712d-6ccb-4e1b-8549-f3870946d02c --allow-no-subscriptions"
2023-02-03T14:31:33.2790299Z [
2023-02-03T14:31:33.2820100Z   {
2023-02-03T14:31:33.2820905Z     "cloudName": "AzureCloud",
2023-02-03T14:31:33.2821399Z     "homeTenantId": "3829712d-6ccb-4e1b-8549-f3870946d02c",
2023-02-03T14:31:33.2821862Z     "id": "c1d91d68-4914-470d-a216-cf5170510efc",
2023-02-03T14:31:33.2822308Z     "isDefault": true,
2023-02-03T14:31:33.2822642Z     "managedByTenants": [
2023-02-03T14:31:33.2822968Z       {
2023-02-03T14:31:33.2823334Z         "tenantId": "9ca44230-24ca-42bc-bdcc-3336dc6e0b07"
2023-02-03T14:31:33.2823736Z       }
2023-02-03T14:31:33.2824028Z     ],
2023-02-03T14:31:33.2824331Z     "name": "Production",
2023-02-03T14:31:33.2824683Z     "state": "Enabled",
2023-02-03T14:31:33.2825074Z     "tenantId": "3829712d-6ccb-4e1b-8549-f3870946d02c",
2023-02-03T14:31:33.2825469Z     "user": {
2023-02-03T14:31:33.2826384Z       "name": "***",
2023-02-03T14:31:33.2826737Z       "type": "servicePrincipal"
2023-02-03T14:31:33.2827075Z     }
2023-02-03T14:31:33.2827342Z   }
2023-02-03T14:31:33.2827625Z ]
2023-02-03T14:31:33.3009881Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account set --subscription c1d91d68-4914-470d-a216-cf5170510efc"
2023-02-03T14:31:33.9974638Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1675434592151.ps1'"
2023-02-03T14:31:46.9306920Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-02-03T14:31:46.9307923Z ERROR: Expecting value: line 1 column 1 (char 0)
2023-02-03T14:31:46.9308680Z Traceback (most recent call last):
2023-02-03T14:31:46.9309451Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2023-02-03T14:31:46.9310274Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
2023-02-03T14:31:46.9335465Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2023-02-03T14:31:46.9338322Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
2023-02-03T14:31:46.9339427Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
2023-02-03T14:31:46.9342857Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
2023-02-03T14:31:46.9343803Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
2023-02-03T14:31:46.9344693Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2023-02-03T14:31:46.9346992Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_base.py", line 508, in restore_azure_wl
2023-02-03T14:31:46.9348004Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_wl.py", line 618, in restore_azure_wl
2023-02-03T14:31:46.9348973Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_help.py", line 459, in get_or_read_json
2023-02-03T14:31:46.9354642Z   File "json\__init__.py", line 293, in load
2023-02-03T14:31:46.9355232Z   File "json\__init__.py", line 346, in loads
2023-02-03T14:31:46.9358015Z   File "json\decoder.py", line 337, in decode
2023-02-03T14:31:46.9361876Z   File "json\decoder.py", line 355, in raw_decode
2023-02-03T14:31:46.9362515Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-02-03T14:31:46.9363387Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-02-03T14:31:46.9363987Z To open a new issue, please run `az feedback`
2023-02-03T14:31:47.1921026Z ##[error]Script failed with exit code: 1
2023-02-03T14:31:47.2093667Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2023-02-03T14:31:48.4715652Z ##[section]Finishing: Restore DB

**Comment by yonzhan** [comment]
route to CXP team
