### ISSUE TITLE
Command fails on Mac

### ISSUE THREAD

**Issue by themeltman** [Azure/azure-cli#25379]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 2286, in aks_get_credentials
    _print_or_merge_credentials(
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 3517, in _print_or_merge_credentials
    with os.fdopen(os.open(path, os.O_CREAT | os.O_WRONLY, 0o600), 'wt'):
FileNotFoundError: [Errno 2] No such file or directory: ''

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {} --subscription {} --admin`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@themeltman Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@themeltman I see that you are using an older version of Azure CLI. Could you please update to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) of Azure CLI and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@themeltman I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@themeltman The action is currently pending on you to try with the updated version of AzCLI and check if the issue occurs. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
