### ISSUE TITLE
az aro wait returns "'AzureRedHatOpenShiftClient' object has no attribute 'get'" error after az cli update

### ISSUE THREAD

**Issue by Lunchee85** [Azure/azure-cli#25373]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az aro wait --name cluster -g rg --created

**Describe the bug**

After updating the az CLI to the latest version (as of February 7th), 2.45.0, the command returns this error message:

```
The command failed with an unexpected error. Here is the traceback:
'AzureRedHatOpenShiftClient' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 402, in handler
    return self.wait(command_args, cli_ctx=self.cli_ctx, getter=getter)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 431, in wait
    instance = getter(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/redhatopenshift/v2022_09_04/operations/_open_shift_clusters_operations.py", line 528, in get
    template_url=self.get.metadata["url"],
AttributeError: 'AzureRedHatOpenShiftClient' object has no attribute 'get'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

**To Reproduce**

- Running the aforementioned command passing a valid ARO cluster name and resource group as parameters

**Expected behavior**

**Environment summary**

Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
account 0.2.5
azure-devops 0.26.0
blueprint 0.3.1
log-analytics 0.2.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

**Additional context**

**Comment by Lunchee85** [comment]
I thought it was an error only my side for a moment, but it happens consistently, so I reopened the issue.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Lunchee85** [comment]
Hi, sorry for updating this, but also on new CLI versions I still can't use this command, I am still forced to rely on 2.44.0. 
Have there been any updates?

**Comment by nastacio** [comment]
I am getting the same thing with this version of the CLI.

```
az version
{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

I was not getting this with version 2.38, which is the last time I had used it before the upgrade.

**Comment by jsafarik** [comment]
Happening on Azure CLI 2.50.0 as well.

**Comment by RobertoLCP** [comment]
Hi, are there any news on this?
