### ISSUE TITLE
Loading command module errors

### ISSUE THREAD

**Issue by sasukeh** [Azure/azure-cli#2539]
I'm facing this issue now. Kindly refer to the following lines....

> ➜  ~ az login
> Error loading command module 'redis'
> Error loading command module 'resource'
> To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXXX to authenticate.

Thanks,

**Comment by sasukeh** [comment]
I've tried to reinstall Azure cli then. Azure cli works fine now.

**Comment by sasukeh** [comment]
but I still want to know what is the exact problem, should we reinstall when azure-cli 2.0 released?

**Comment by derekbekoe** [comment]
@sasukeh If it happens again, provide the output from `az --debug` and we can investigate.  Thanks.

**Comment by sasukeh** [comment]
@derekbekoe Sure. Thanks

**Comment by terrymccarthy3000** [comment]
Error loading command module 'ml'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/__init__.py", line 129, in _update_command_table_from_modules
    module_command_table = _load_module_command_loader(self, args, mod)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 549, in _load_module_command_loader
    return _load_command_loader(loader, args, mod, 'azure.cli.command_modules.')
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 523, in _load_command_loader
    module = import_module(prefix + name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/ml/__init__.py", line 8, in <module>
    import azure.cli.command_modules.ml._help #pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/ml/_help.py", line 6, in <module>
    from azure.cli.core.help_files import helps
ImportError: No module named help_files
