### ISSUE TITLE
No module named 'azure.mgmt.web.v2020_12_01' - az staticwebapp functions link

### ISSUE THREAD

**Issue by AndreasKratzig** [Azure/azure-cli#25403]
## Describe the bug

**Command Name**
`az staticwebapp functions link`

**Errors:**
```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/invocation.py", line 111, in _validation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 849, in _validate_cmd_level
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_validators.py", line 315, in validate_staticsite_link_function
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/_web_site_management_client.py", line 779, in static_sites
ModuleNotFoundError: No module named 'azure.mgmt.web.v2020_12_01'

cli.azure.cli.core.azclierror: No module named 'azure.mgmt.web.v2020_12_01'
az_command_data_logger: No module named 'azure.mgmt.web.v2020_12_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az staticwebapp functions link -n {} -g {} --function-resource-id {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
application-insights 0.1.18
containerapp 0.3.21
webapp 0.4.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by dkowalec** [comment]
Any update @yonzhan as I'm experiencing the same issue and can't deploy

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by dkowalec** [comment]
FYI, rolling back to the previous tag release resolved our issue as a workaround. There might be something wrong with the LATEST release.

**Comment by thrsn-ur** [comment]
We are also experiencing this for our Azure DevOps pipelines running version 2.48.1:
ERROR: No module named 'azure.mgmt.web.v2020_12_01'

**Comment by dkowalec** [comment]
> We are also experiencing this for our Azure DevOps pipelines running version 2.48.1:
> ERROR: No module named 'azure.mgmt.web.v2020_12_01'

I can confirm downgrading to '2.46.0' worked for us until it's fixed @navba-MSFT

**Comment by nezhar** [comment]
We had the same issue in an azure pipeline where we link a function to a staticwebapp. Fixed it by rolling back with `pip install azure-cli==2.47.0`

**Comment by AndreasKratzig** [comment]
Hi all,

I had again the opportunity to check this and did some steps ahead to verify that I've installed the latest versions via:
> winget upgrade --id Microsoft.AzureCLI
> pip install -U azure-cli
> az --version
azure-cli                         2.48.1
> python --version
Python 3.11.2
> pip freeze
azure-cli==2.48.1
azure-mgmt-web==7.0.0

With that the issue is gone for me and the command is working now without the error message _cli.azure.cli.core.azclierror: No module named 'azure.mgmt.web.v2020_12_01'_.

**Comment by dankarmyy** [comment]
This appears to still be in issue in v2.50.0

I'm seeing the same error in Azure Pipelines hosted agents Ubuntu 22.04.2 LTS.

I can confirm that the downgrade method to v2.47.0 works though.

**Comment by cgdietz** [comment]
still an error in v 2.52

**Comment by betabites** [comment]
I believe the cause of the issue has evolved over time. I've done some digging, and I believe it's caused by this line of code:
https://github.com/Azure/azure-cli/blob/7952300337b5b7f986131aee2efa39ea403a6902/src/azure-cli/azure/cli/command_modules/appservice/_validators.py#L394C4-L394C114
```python
client = get_mgmt_service_client(cmd.cli_ctx, WebSiteManagementClient, api_version="2020-12-01").static_sites
```
- This function is specific to `az staticwebapp functions link`. Meaning that theoretically other methods are unaffected.

- It's attempting to use API version `2020-12-01` from `azure-mgmt-web`, but that was removed in version 8. The change log is accessible here: https://pypi.org/project/azure-mgmt-web/
```
# 8.0.0 (2025-01-23)
## Breaking Changes

-  Removed subfolders of some unused Api-Versions for smaller package size. If your application requires a specific and non-latest Api-Version, it's recommended to pin this package to the previous released version; If your application always only use latest Api-Version, please ignore this change.
```
I don't believe that this was the original issue, however, given that v8 was released *after* the last comment on this thread. Might try to fork and resolve it, though.
