### ISSUE TITLE
az upgrade 2.37.0 to 2.45.0 is failing with [WinError 6] The handle is invalid exception

### ISSUE THREAD

**Issue by pschow-qtm** [Azure/azure-cli#25412]
## Describe the bug
"az feedback" CLI upgrade from 2.37.0 to 2.45.0 is failing with subprocess error
**az upgrade**

**Errors:**
```
 az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.37.0. Latest version available is 2.45.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Updating Azure CLI with MSI from https://aka.ms/installazurecliwindows
Downloading MSI to C:\Users\PETER~1.SCH\AppData\Local\Temp\tmp_gugznpn\azure-cli-2.45.0.msi
Installing MSI
The command failed with an unexpected error. Here is the traceback:
[WinError 6] The handle is invalid
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 140, in upgrade_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 193, in _upgrade_on_windows
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1458, in _execute_child
OSError: [WinError 6] The handle is invalid
To open an issue, please run: 'az feedback'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
quantum 0.17.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
I can't repro.
It fails at this line: `exit_code = subprocess.call(['msiexec.exe', '/i', msi_path])`.

Can you download the latest azure-cli msi and install?

**Comment by pschow-qtm** [comment]
Downloaded and installed the 2.45.0 MSI, this worked fine.  Thanks for the workaround.

I should have mentioned that my IT department has a security layer installed on my system that presents a popup that needs to be acknowledged, when something requests elevated privileges, like "az upgrade".  Likely this was causing the Python subprocess error.
