### ISSUE TITLE
Issue downloading invoices with az billing invoice

### ISSUE THREAD

**Issue by bastianjohn** [Azure/azure-cli#25423]
## Describe the bug
I try to download my invoices with the following method:
az billing invoice download --account-name "{accountName}" --invoice-name $invoiceName --download-token "token"

**Command Name**
`az billing invoice download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'InvoicesOperations' object has no attribute 'download_invoice'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/billing/manual/custom.py", line 24, in billing_invoice_download
    return client.download_invoice(account_name, invoice_name, download_token)
AttributeError: 'InvoicesOperations' object has no attribute 'download_invoice'
```
## What i wanted to do
Normally i just want to download all the invoices in all subscriptions. Therefore i tried to use AZ CLI. Unfortunaetly its not really working. I tried also:
```
$newInvoiceList = az billing invoice list

Invoke-WebRequest -Uri $_.newInvoiceListDocURL -headers $headers  -OutFile ($invoiceName + ".pdf")     
```
With this i get an authentication error       | {"error":{"code":"AuthorizationFailed","message":"The client '{UserId}' with object id
     | '297db162-cbe2-4cc4-8a24-99ea642014c0' does not have authorization to perform action
     | 'Microsoft.Billing/billingAccounts/billingSubscriptions/invoices/download/read' over scope
     | '/providers/Microsoft.Billing/billingAccounts/default/billingSubscriptions/subid/invoices/E0800XXXX' or the scope is invalid. If access was recently granted, please refresh your credentials."}}

## Environment Summary
```
macOS-13.0-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0
```

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@bastianjohn, could you please check if you really have permission for the operation?

**Comment by bastianjohn** [comment]
@jsntcy i have the required permission and can do it manually. Just with the CLI its not working. It was also working with the old powershell module instead.

**Comment by jsntcy** [comment]
@bastianjohn, 

- First I want to clarify with you, do you have issue only in `az billing invoice download`? or you have issues in both `az billing invoice download` and `az billing invoice list`?
- Secondly, please add `--debug` to the command that has the issue to help collect debug log for us to further troubleshooting.

**Comment by jsntcy** [comment]
Add @shagundaral and @bradenwatkins from service team for attention.

**Comment by bastianjohn** [comment]
> @bastianjohn,
> 
> * First I want to clarify with you, do you have issue only in `az billing invoice download`? or you have issues in both `az billing invoice download` and `az billing invoice list`?
> * Secondly, please add `--debug` to the command that has the issue to help collect debug log for us to further troubleshooting.

az billing invoice list was working fine, just tried it out today and its also not working anymore :-( 

`azure.core.exceptions.DeserializationError: ('Unable to deserialize response data. Data: [{\'id\': \'/providers/Microsoft.Billing/billingAccounts/default/billingSubscriptions/a7072860-ed29-4883-bc4c-a1ed77010cff/invoices/....\

DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))))
` 


Here the output of the download command:

`cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101b35f30>, <function OutputProducer.on_global_arguments at 0x101bc2cb0>, <function CLIQuery.on_global_arguments at 0x101c28160>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'billing': ['azure.cli.command_modules.billing']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: billing                   0.003        19        52
cli.azure.cli.core: Total (1)                 0.003        19        52
cli.azure.cli.core: Loaded 19 groups, 52 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : billing invoice download
cli.azure.cli.core: Command table: billing invoice download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x102639ea0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/bastianjohn/.azure/commands/2023-05-08.08-44-36.billing_invoice_download.29221.log'.
az_command_data_logger: command args: billing invoice download --account-name {} --invoice-name {} --download-token {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102676680>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1026985e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x102698700>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x101bc2d40>, <function CLIQuery.handle_query_parameter at 0x101c281f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x102698670>]
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=BillingManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/bastianjohn/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/bastianjohn/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/b7306395-5fd5-41dd-a805-6da2609d9bc9/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/billing/manual/custom.py", line 24, in billing_invoice_download
    return client.download_invoice(account_name, invoice_name, download_token)
AttributeError: 'InvoicesOperations' object has no attribute 'download_invoice'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'InvoicesOperations' object has no attribute 'download_invoice'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/billing/manual/custom.py", line 24, in billing_invoice_download
    return client.download_invoice(account_name, invoice_name, download_token)
AttributeError: 'InvoicesOperations' object has no attribute 'download_invoice'
az_command_data_logger: 'InvoicesOperations' object has no attribute 'download_invoice'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/billing/manual/custom.py", line 24, in billing_invoice_download
    return client.download_invoice(account_name, invoice_name, download_token)
AttributeError: 'InvoicesOperations' object has no attribute 'download_invoice'`

**Comment by bastianjohn** [comment]
Any news?

**Comment by Jing-song** [comment]
Hi @bastianjohn , I fixed this issue in the new [PR](https://github.com/Azure/azure-cli/pull/27804), could you please test it using this private package([package](https://dev.azure.com/azclitools/public/_build/results?buildId=105481&view=artifacts&pathAsName=false&type=publishedArtifacts)), I don't have a way to test it.
