### ISSUE TITLE
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError"

### ISSUE THREAD

**Issue by mh-Vthirumoorthy** [Azure/azure-cli#25421]
## Describe the bug
Error while running az keyvault set-policy command as service principal which have full Owner Permission on this Subscription & Resource.

**Command Name**
``
 az keyvault set-policy --name {Kevault_name}--secret-permissions get list --upn 'user@email.com'

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 1011, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2023-02-10T08:56:39","request-id":"a79d4083-9c1f-4d54-ae21-f4d6379e1955","client-request-id":"a79d4083-9c1f-4d54-ae21-f4d6379e1955"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 897, in set_policy
    object_id = _object_id_args_helper(cmd.cli_ctx, object_id, spn, upn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 876, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 356, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/custom.py", line 325, in _get_object_id_by_upn
    accounts = list(graph_client.user_list(filter="userPrincipalName eq '{}'".format(upn)))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 294, in user_list
    result = self._send("GET", "/users" + _filter_to_query(filter))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.
```

## To Reproduce:

az keyvault set-policy --name {Kevault_name}--secret-permissions get list --upn 'user@email.com'

## Expected Behavior

The command execute successfully to set policy for the give user

## Environment Summary

Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.3 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
interactive 0.4.6
resource-graph 2.1.0
account 0.2.5
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
@mh-Vthirumoorthy CLI failed to query the object id for the user principal you provided. Can you specify object id directly?
`az keyvault set-policy --name {Kevault_name}--secret-permissions get list --object-id {UserPrincipalOID}`
