### ISSUE TITLE
Error in response after VM Build

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#2543]
Hi,

I'm creating a VM and attaching an existing NIC.  In the portal, the VM is successfully created but the CLI gives the error / output below.  Something unique about this VM is that I'm adding IPv6 and IPv4 IPConfigs to the NIC.

 az vm create -g IPv6 --location eastus --name XREVM --nics XREVMNIC --os-disk-name XREOSDisk --authentication-type password --admin-username  --admin-password  --size "Standard_DS4" --image "OpenLogic:CentOS:6.8:latest" --debug

DEBUG: msrest.http_logger : Response content:
DEBUG: msrest.http_logger : Body contains chunked data.
ERROR: sequence item 1: expected str instance, NoneType found
Traceback (most recent call last):
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 358, in _execute_command
    raise ex
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 353, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\vm\custom.py", line 1623, in create_vm
    return get_vm_details(resource_group_name, vm_name)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\vm\custom.py", line 194, in get_vm_details
    setattr(result, 'private_ips', ','.join(private_ips))
TypeError: sequence item 1: expected str instance, NoneType found

**Comment by tjprescott** [comment]
If you do `vm show ... -d` does it show that your VM has a private IP address?

**Comment by Teodelas** [comment]
AZ vm show  … works but not when I add -d:
az vm show -n XREVM -g IPv6 -d
ERROR: sequence item 1: expected str instance, NoneType found
Traceback (most recent call last):
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 356, in _execute_command
    result = exception_handler(ex)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\_util.py", line 49, in empty_on_404
    raise ex
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 353, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\vm\custom.py", line 161, in show_vm
    return get_vm_details(resource_group_name, vm_name)
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\site-packages\azure\cli\command_modules\vm\custom.py", line 194, in get_vm_details
    setattr(result, 'private_ips', ','.join(private_ips))
TypeError: sequence item 1: expected str instance, NoneType found

**Comment by yugangw-msft** [comment]
@tjprescott , I can take a look at this.
