### ISSUE TITLE
[App Service] Configuring remote source control seems a little unpredictable

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2545]
If I run the following on a Linux web app: `az appservice web source-control config --repo-url https://github.com/scotch-io/node-todo.git`, I get the following error:

```
Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetWebHookInfo: Not Found
   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<ProcessResponse>d__a2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<GetWebHookInfo>d__6f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<AddWebHook>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass35a.<<UpdateSiteSourceControl>b__355>d__35f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Hosting.Administration.Csm.Common.Helpers.AsyncHelper.RunSync[TResult](Func`1 func)
   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl).
```

If I append the ` --manual-integration` flag, then I get the following error instead (I assume specifying the GitHub token would also work?):

```
Operation failed with status: 200. Details: Resource state Failed 
```

Finally, if I append `--branch master` to it, then it seems to succeed, since I can run `az appservice web source-control show` and see the correct settings.

However, if I now run `az appservice web source-control sync`, I get the following error:

```
Operation failed with status: 200. Details: none
```

Maybe this works correctly on Windows, but on Linux, it's a bit confusing. It would be great if we could ensure that we displayed actionable and clear error messages, as well as ensure that the help text for each of these params were as clear as possible. For example, the `--branch` flag isn't mentioned as being required in any situation, but the help text doesn't say what it's default value it. Should this be set to default to `master`?

> This is a different set of issues than #1806, which is focused on the local Git scenario, not a remote Git repo.

**Comment by JasonRShaver** [comment]
@yugangw-msft to comment

**Comment by suwatch** [comment]
@lostintangent many issues were mentioned.  Let do one at a time.

The user performs CLI must either have admin privilege to `https://github.com/scotch-io/node-todo.git` and setup the GitHub token, otherwise one would need to provide `--manual-integration` to indicate on-demand deployment.    Note that GitHub unauthenticated repo access returns a non-obvious 404 NotFound (what the first error indicated).

The failure after you provided  `--manual-integration` was not common.   Please provide site name here (or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)), and time/timezone.

**Comment by yugangw-msft** [comment]
The retry logic i am putting in the #3258 should mitigate this
