### ISSUE TITLE
Azure CLI V2 (azure-cli-2.45.0.msi) Error 1 module to load starting with 'azext_': got []

### ISSUE THREAD

**Issue by gailzmicrosoft** [Azure/azure-cli#25473]
Encountered the error and tried to reinstall (repair, remove, install) Azure CLI azure-cli-2.45.0.msi but kept getting same:

Terminal
(base) PS C:\Users\DirName> az version
The command failed with an unexpected error. Here is the traceback:
Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 426, in load_command_table
 File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 320, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 307, in _filter_modname
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 308, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

How did I get there? 
I was tring to install azure-cli-ml exension and it corrupted the Azure CLI. 

[Install and set up the CLI (v2) - Azure Machine Learning | Microsoft Learn](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public)

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
I guess the installation is interrupted.

Can you delete `C:\Users\{your_user_name}\.azure\cliextensions\azure-cli-ml` and install it again?

**Comment by gailzmicrosoft** [comment]
Thanks. My Machine has .Azure (not .azure). C:\Users\{your_user_name}\.**Azure**\cliextensions\azure-cli-ml 
I do not see .azure. Does it matter?

**Comment by gailzmicrosoft** [comment]
I see these in my machine: 
C:\Users\MyUserId\**.Azure**\cliextensions\account
C:\Users\MyUserId\**.Azure**\cliextensions\ml

**Comment by gailzmicrosoft** [comment]
I see these in my machine:
C:\Users\MyUserId\.Azure\cliextensions\account
C:\Users\MyUserId\.Azure\cliextensions\ml

**Comment by bebound** [comment]
I see, please delete `C:\Users{your_user_name}\.Azure\cliextensions\ml`

**Comment by gailzmicrosoft** [comment]
@bebound: Thank you! I deleted below two items and then tried "az version". The error went away: 
C:\Users{your_user_name}\.Azure\cliextensions\ml
C:\Users{your_user_name}\.azureml 
Hope this resolution help other users as well. Thank you again!
