### ISSUE TITLE
az aks install-cli fails with "CERTIFICATE_VERIFY_FAILED" error

### ISSUE THREAD

**Issue by mbeckergit** [Azure/azure-cli#25470]
## Describe the bug
az aks install-cli fails with "CERTIFICATE_VERIFY_FAILED" error

Ubuntu 18.04.2 (WSL)

I've tried without https_proxy set and while not connected to the corporate network.

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/az/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/az/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/az/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/az/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/az/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/az/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/az/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1433, in k8s_install_cli
    k8s_install_kubectl(cmd, client_version, install_location, base_src_url, arch=arch)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1548, in k8s_install_kubectl
    version = urlopen(source_url + '/stable.txt', context=context).read()
  File "/opt/az/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/az/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/az/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/az/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks install-cli`

## Expected Behavior
cli is installed.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27, Ubuntu 18.04.2 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
interactive 0.4.6
managementpartner 0.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mbeckergit  Thanks for reaching out to us and reporting this issue. From the error message it is pretty clear that there seems to be a proxy within your network. Please follow the below action plans to isolate if this is indeed related to the proxy.

**Plan 1:**
Could you please try to run the same command from a different machine which is on a completely different network? and check if that works.

**Plan 2:**
Try appending standard Python root CAs to your pem file and check if that helps to run the CLI command.

```
REQUESTS_CA_BUNDLE=$HOME/certs/internal.pem
```

**Plan 3:**
Try disabling SSL certificate verification temporarily by setting the `REQUESTS_CA_BUNDLE` environment variable to None and check if that helps to run the CLI command.

```
export REQUESTS_CA_BUNDLE=None
az aks install-cli
```

**Plan 4:**
Does other AzCLI commands like `az login --debug `commands like work fine ?

**Plan 5:**
Run this command and check the result:
`python.exe" -c "import urllib.request; print(urllib.request.getproxies())"`

**Plan 6:**
Please follow this article to make sure the issue is not caused by Azure CLI, but by Python and proxy.
https://github.com/jiasli/azure-notes/blob/master/cli/proxy-cert-linux.md

And to work behind a proxy follow this, please follow the instruction at https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy to trust the root certificate and add the root CA of the proxy to your CA bundle.

**Comment by navba-MSFT** [comment]
@mbeckergit I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mbeckergit** [comment]
@navba-MSFT Thanks for your suggestions, I ended up using brew on Linux to install kubectl and things seem to be working for me.

**Comment by orsharon7** [comment]
I'm having the same issue using `az aks install-cli`. Using Choco I have no issues.

**Comment by cawoodm** [comment]
```
export REQUESTS_CA_BUNDLE=None
$ az webapp log tail --resource-group abc --name def

REQUESTS_CA_BUNDLE environment variable is specified with an invalid file path
```

**Comment by besteban1989** [comment]
This worked for me: 

1. Visit https://cdn.dl.k8s.io
2. Click on the "Connection is secure" 
3. Click on the Certificate Icon 
4. In the pop-up click on "Details" tab. 
5. Click on "Export" and save it in a folder. 
6. Open the "ISRG Root X1" certificate by double-clicking on it. 
7. In the pop-up click on Install Certificate
8. Select "Local Machine" and click Next. 
9. Select "Yes" in the confirmation window. 
10. Click on "Place all certificates in the following store" and click on "Browse"
11. Select "Trusted Root Certification Authorities" and click on "OK" 
12. Click on Next and finish the process. 
 
Run the "az aks install-cli" the error should be gone.
