### ISSUE TITLE
Getting "The process cannot access the file because it is being used by another process" errors

### ISSUE THREAD

**Issue by Thwani47** [Azure/azure-cli#25483]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az login`
`az  --version`

It's every command to be honest.

**Describe the bug**

I keep on getting the error:
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpy64n3vr_'`

```bash
❯ az login
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpkfunmubo'
Auto upgrade failed. name 'exit_code' is not defined
Traceback (most recent call last):
  File "importlib\_common.py", line 92, in _tempfile
  File "importlib\abc.py", line 371, in read_bytes
  File "importlib\_adapters.py", line 54, in open
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 112, in _msal_app
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1685, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 507, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/__init__.py", line 133, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/utils.py", line 41, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\certifi/core.py", line 72, in where
  File "contextlib.py", line 135, in __enter__
  File "importlib\_common.py", line 98, in _tempfile
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpeqcxo5dq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "importlib\_common.py", line 92, in _tempfile
  File "importlib\abc.py", line 371, in read_bytes
  File "importlib\_adapters.py", line 54, in open
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 49, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 36, in cli_main
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 245, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 127, in exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 59, in handle_exception
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/__init__.py", line 28, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/azure_configuration.py", line 34, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/__init__.py", line 28, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/configuration.py", line 38, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/__init__.py", line 53, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 31, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/__init__.py", line 30, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/_pipeline_client.py", line 31, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/__init__.py", line 38, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 34, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/__init__.py", line 133, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/utils.py", line 41, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\certifi/core.py", line 72, in where
  File "contextlib.py", line 135, in __enter__
  File "importlib\_common.py", line 98, in _tempfile
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpojkk7wnb'
```

These "files" are all random and they change with each command run. Every command run fails on a different file. I've kills the processes using these files but there's a new one every time.

**To Reproduce**

Run `az --version`

**Expected behavior**

To display the installed version of the Azure CLI

**Environment summary**

- Azure CLI on Windows (Windows 10 Enterprise)
- Azure CLI version -2.45.0
- Python 3.11.1

**Additional context**

I've installed different versions of Azure CLI, ran the commands in Powershell Administrator mode, nothing helped

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Looks like some issue with

- https://github.com/pypa/pip/issues/11064
- https://stackoverflow.com/questions/72280762/pip-broke-after-downlading-python-certifi-win32
- https://stackoverflow.com/questions/72011315/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is

Is it possible that you have your own Python 3.11.1 installation that interferes with Azure CLI's `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe`?

**Comment by Thwani47** [comment]
Thank you for the links. They pointed me to the right direction

I managed to fix this be removing the files
```
python-certifi-win32-init.pth
distutils-precedence.pth
```
from  `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages`
