### ISSUE TITLE
[Errno 11] Resource temporarily unavailable error while az login

### ISSUE THREAD

**Issue by shraddhakannurkar** [Azure/azure-cli#25485]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 168, in login_with_device_code
    result = self._msal_app.acquire_token_by_device_flow(flow, **kwargs)  # By default it will block
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1978, in acquire_token_by_device_flow
    response = _clean_up(self.client.obtain_token_by_device_flow(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 383, in obtain_token_by_device_flow
    result = self._obtain_token_by_device_flow(flow, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 345, in _obtain_token_by_device_flow
    result = self._obtain_token(
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 788, in _obtain_token
    (on_obtaining_tokens or self.on_obtaining_tokens)({
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 700, in <lambda>
    on_obtaining_tokens=lambda event: self.token_cache.add(dict(
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 314, in add
    super(SerializableTokenCache, self).add(event, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 117, in add
    return self.__add(event, now=now)
  File "/opt/az/lib/python3.10/site-packages/msal/token_cache.py", line 189, in __add
    self.modify(self.CredentialType.ACCESS_TOKEN, at, at)
  File "/opt/az/lib/python3.10/site-packages/msal_extensions/token_cache.py", line 63, in modify
    with CrossPlatLock(self._lock_location):
  File "/opt/az/lib/python3.10/site-packages/msal_extensions/cache_lock.py", line 59, in __enter__
    file_handle = self._lock.__enter__()
  File "/opt/az/lib/python3.10/site-packages/portalocker/utils.py", line 153, in __enter__
    return self.acquire()
  File "/opt/az/lib/python3.10/site-packages/portalocker/utils.py", line 254, in acquire
    raise exceptions.LockException(exception)
portalocker.exceptions.LockException: [Errno 11] Resource temporarily unavailable
```

## To Reproduce:
To reproduce - run az login from terminal
- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.15.0-192-generic-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.45.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Are you running `az login` concurrently?

Azure CLI/MSAL's token cache is process-safe for read operations, but no write operations. Running `az login` or refreshing MSAL token cache concurrently may result in failure.

You may try `AZURE_CONFIG_DIR` to isolate Azure CLI environments: https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#concurrent-builds
