### ISSUE TITLE
Unable to connect my aks cluster..

### ISSUE THREAD

**Issue by Bowres1511** [Azure/azure-cli#25509]
**When I try to connect my cluster using Azure CLI the following error occurs.**

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>az aks get-credentials --resource-group bowres --name akscluster
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'C'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1119, in aks_get_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1242, in _print_or_merge_credentials
PermissionError: [Errno 13] Permission denied: 'C'

**Comment by navba-MSFT** [comment]
@Bowres1511 Thanks for reaching out to us and reporting this issue. 

- Open CMD in elevated admin mode, and run: 
> **az aks get-credentials -g [your aks resource group] -n [your aks name] -f  > .kube\config**

- Add to your environment variable the following parameter: KUBECONFIG and set the value to where previous step save the config file. for example: C:\Users[your user name folder].kube\config

- Try now to run the following command: "kubectl get nodes"
   kubectl get pods --all-namespaces

**Comment by Bowres1511** [comment]
By installing the preview by using the command **az extension add --name aks-preview
** the issue is cleared..
  Thank you.

**Comment by navba-MSFT** [comment]
@Bowres1511 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
