### ISSUE TITLE
Creating Resource Group using Bash 

### ISSUE THREAD

**Issue by Niluxsi** [Azure/azure-cli#25504]
When creating az group create cmd in Azure Bash CLI got this error

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/odl_user/.azure/commands/2023-02-18.03-59-04.group_create.547.log'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 30] Read-only file system: '/home/odl_user/.azure/commands/2023-02-18.03-59-04.group_create.547.log'

**Comment by yonzhan** [comment]
Please provide detailed CLI command with parameter names.

**Comment by bebound** [comment]
You don't have the permission to write to `/home/odl_user/.azure/commands/2023-02-18.03-59-04.group_create.547.log`. That's weird.
Make sure you have the write permission to this folder: `/home/odl_user/.azure/`.
