### ISSUE TITLE
ml extension not installing

### ISSUE THREAD

**Issue by JaakkoAhola** [Azure/azure-cli#25500]
Hi! I'm trying to install ml extension on a fresh ubuntu virtual machine.
I installed azure cli successfully with: `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`.

First when I tried to install the ml extension with:
`az extension add --name ml --yes` it failed with error:
`/usr/bin/az: line 3:  5036 Killed                  AZ_INSTALLER=DEB "$bin_dir"/../../opt/az/bin/python3 -Im azure.cli "$@"`.
When I tried again with `az extension add -n ml -y`
it gave the following error:

```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 177, in _add_whl_ext
    shutil.copyfile(ext_file, dst)
  File "/opt/az/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

Output of `az --version`:
```
az --version
azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/azureuser/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Feb  3 2023, 09:43:57) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
Googling did not come up with any results. Any advice on this?

BR,
Jaakko

**Comment by diondrapeck** [comment]
Can you try deleting C:\Users\{your_user_name}\.azure\cliextensions\azure-cli-ml or (C:\Users{your_user_name}\.Azure\cliextensions\ml depending on your machine) and try to run the install again? Perhaps the original installation step failing corrupted the installation.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by JaakkoAhola** [comment]
> Can you try deleting C:\Users{your_user_name}.azure\cliextensions\azure-cli-ml or (C:\Users{your_user_name}.Azure\cliextensions\ml depending on your machine) and try to run the install again? Perhaps the original installation step failing corrupted the installation.

**Comment by JaakkoAhola** [comment]
> Can you try deleting C:\Users{your_user_name}.azure\cliextensions\azure-cli-ml or (C:\Users{your_user_name}.Azure\cliextensions\ml depending on your machine) and try to run the install again? Perhaps the original installation step failing corrupted the installation.
The .azure directory does not contain cliextensions sub-directory.

**Comment by bebound** [comment]
Please delete this folder `/home/azureuser/.azure/cliextensions/ml`

**Comment by JaakkoAhola** [comment]
There's is no `/home/azureuser/.azure/cliextensions/ml` that I could delete. I have also tried to reinstall to azure-cli and then tried to install ml extension to no avail.

**Comment by bebound** [comment]
What's the output of `az extension add -n ml --debug`?

**Comment by JaakkoAhola** [comment]
The last lines of `az extension add -n ml --debug > ~/debug_output.log 2>1&`:

```
Installing collected packages: charset-normalizer, azure-common, websocket-client, urllib3, typing-extensions, tqdm, six, pyrsistent, pyjwt, pydash, pycparser, packaging, oauthlib, idna, colorama, certifi, attrs, requests, python-dateutil, marshmallow, jsonschema, isodate, cffi, strictyaml, requests-oauthlib, docker, cryptography, azure-core, msrest, azure-storage-file-share, azure-storage-blob, azure-storage-file-datalake, ml

  Creating /tmp/pip-target-63amd2t1/bin
  changing mode of /tmp/pip-target-63amd2t1/bin/normalizer to 775


  changing mode of /tmp/pip-target-63amd2t1/bin/wsdump to 775



  changing mode of /tmp/pip-target-63amd2t1/bin/tqdm to 775





DEBUG: cli.azure.cli.core.extension.operations: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/home/azureuser/.azure/cliextensions/ml', '/tmp/tmp2ifd3_j2/ml-2.14.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' died with <Signals.SIGKILL: 9>.
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 177, in _add_whl_ext
    shutil.copyfile(ext_file, dst)
  File "/opt/az/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 177, in _add_whl_ext
    shutil.copyfile(ext_file, dst)
  File "/opt/az/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
ERROR: az_command_data_logger: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 177, in _add_whl_ext
    shutil.copyfile(ext_file, dst)
  File "/opt/az/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/.azure/cliextensions/ml/ml-2.14.0-py3-none-any.whl'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fbeded4c8b0>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 13.152 seconds (init: 0.390, invoke: 12.762)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 7035 in cache
WARNING: telemetry.check: Negative: The /home/azureuser/.azure/telemetry.txt was modified at 2023-02-20 10:12:50.337388, which in less than 600.000000 s
```
The whole 2,1Mb debug log file available at [https://filesender.funet.fi/?s=download&token=3c6aba3f-42b9-4f88-a620-8f509fd69f33](https://filesender.funet.fi/?s=download&token=3c6aba3f-42b9-4f88-a620-8f509fd69f33)

**Comment by bebound** [comment]
Do you have any clue why pip is killed?
`DEBUG: cli.azure.cli.core.extension.operations: Command '['/usr/bin/../../opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/home/azureuser/.azure/cliextensions/ml', '/tmp/tmp2ifd3_j2/ml-2.14.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' died with <Signals.SIGKILL: 9>.`

**Comment by JaakkoAhola** [comment]
No idea.
I'm not even sure which pip it is using.
Probably it is this one:
```
/opt/az/bin/python3 -m pip --version
pip 23.0.1 from /home/azureuser/.local/lib/python3.10/site-packages/pip (python 3.10)
```
I updated that pip from 23.0 to 23.0.1 to no avail.

The machine is a newly deployed virtual machine hosted by Azure with Ubuntu server 20.04.5 LTS.

**Comment by JaakkoAhola** [comment]
I deployed a new virtual machine and installed azure-cli with ml extension without any problems.
So I cannot replicate the issue and now I have what I need so I'll close the issue. Thank you for your time!
