### ISSUE TITLE
az aks nodepool upgrade  - The cluster is already on version {} 

### ISSUE THREAD

**Issue by pipiobjo** [Azure/azure-cli#25521]
## Describe the bug

**Command Name**
`az aks nodepool upgrade`

**Errors:**
'AgentPool' object has no attribute 'kubernetes_version'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```bash
$  az aks nodepool list --cluster-name MY_CLUSTER_NAME --resource-group MY_RG --output table

Name         OsType    KubernetesVersion    VmSize           Count    MaxPods    ProvisioningState    Mode
-----------  --------  -------------------  ---------------  -------  ---------  -------------------  ------
myworkload  Linux     1.24.3               Standard_D2s_v5  2        110        Succeeded            User
system       Linux     1.24.3               Standard_D2s_v5  1        110        Succeeded            System


```
Then upgrade the nodepool to 1.24.6

```bash
$  az aks nodepool upgrade --kubernetes-version 1.24.6 --name system --cluster-name MY_CLUSTER_NAME --resource-group MY_RG --output table

The command failed with an unexpected error. Here is the traceback:
'AgentPool' object has no attribute 'kubernetes_version'
Traceback (most recent call last):
File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
cmd_result = self.invocation.execute(args)
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
raise ex
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
results.append(self._run_job(expanded_arg, cmd_copy))
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
result = cmd_copy(params)
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
return self.handler(*args, **kwargs)
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
return op(**command_args)
File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2124, in aks_agentpool_upgrade
msg = "The cluster is already on version {} and is not in a failed state. No operations will occur when upgrading to the same version if the cluster is not in a failed state.".format(instance.kubernetes_version)
AttributeError: 'AgentPool' object has no attribute 'kubernetes_version'
```

Connecting to the cluster and checking the version

```bash
kubectl get nodes -o wide
NAME                                  STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-myworkload-32043016-vmss00000f    Ready    agent   180d   v1.24.3   10.38.8.9     <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4
aks-myworkload-32043016-vmss00000t    Ready    agent   139d   v1.24.3   10.38.8.5     <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4
aks-system-17265536-vmss000000        Ready    agent   126d   v1.24.3   10.38.8.4     <none>        Ubuntu 18.04.6 LTS   5.4.0-1091-azure   containerd://1.6.4+azure-4

```

Upgrading it manually via the portal works as expected

## Expected Behavior

Upgrade is executed

## Environment Summary
```
Linux-5.4.0-1103-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.45.0

Extensions:
azure-devops 0.25.0
ai-examples 0.2.5
ml 2.13.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@pipiobjo Apologies for the late reply. Thanks for reaching out to us and reporting this issue. The above PR has been filed to fix this and it is currently under review.
