### ISSUE TITLE
azure tre -automated bug

### ISSUE THREAD

**Issue by pselmani** [Azure/azure-cli#25533]
## Describe the bug

**Command Name**
`az config set`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 1] Operation not permitted: '/home/vscode/.azure/config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/config/custom.py", line 41, in config_set
    cmd.cli_ctx.config.set_value(section, name, _normalize_config_value(value))
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 161, in set_value
    self._config_file_chain[-1].set_value(section, option, value)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 240, in set_value
    self.set(config)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 229, in set
    os.chmod(self.config_path, stat.S_IRUSR | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/home/vscode/.azure/config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az config set {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31, Debian GNU/Linux 11 (bullseye)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment]
@jiasli for awareness
