### ISSUE TITLE
Invocation of 'az aks nodepool upgrade --kubernetes-version X.XX.XX' results in "'AgentPool' object has no attribute 'kubernetes_version'"

### ISSUE THREAD

**Issue by reciproke79** [Azure/azure-cli#25545]
## Describe the bug

**Command Name**
`az aks nodepool upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'AgentPool' object has no attribute 'kubernetes_version'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2124, in aks_agentpool_upgrade
    msg = "The cluster is already on version {} and is not in a failed state. No operations will occur when upgrading to the same version if the cluster is not in a failed state.".format(instance.kubernetes_version)
AttributeError: 'AgentPool' object has no attribute 'kubernetes_version'```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool upgrade --kubernetes-version {} --cluster-name {} --resource-group {} --name {} --no-wait`

## Expected Behavior

## Environment Summary
```
Linux-5.4.0-1103-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.45.0

Extensions:
ai-examples 0.2.5
ml 2.13.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by reciproke79** [comment]
I took a look at the changes done in that regard, and yes, the 'AgentPool' seems to have the 'kubernetes_version' attribute missing. Going through that code and if I see correctly, an addition of that property in that method may fix that? https://github.com/Azure/azure-cli/blob/32ab2fae8a228249020db4d3306617e7f2439a8e/src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py#L1370

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@reciproke79 Thanks for reaching out to us and reporting this issue. This issue has been fixed as a part of this PR https://github.com/Azure/azure-cli/pull/25526 . The fix should be available as a part of this milestone: https://github.com/Azure/azure-cli/milestone/127

**Comment by reciproke79** [comment]
Great @yonzhan - thanks for confirming - looking forward to that fix!
