### ISSUE TITLE
`az afd endpoint create` error from API property AfdEndpoint.AutoGeneratedDomainNameLabelScope

### ISSUE THREAD

**Issue by datadot** [Azure/azure-cli#25553]
## Describe the bug

**Command Name**
`az afd endpoint create`

**Errors:**

(BadRequest) Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
Code: BadRequest
Message: Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE

Running with debug, seems the API is case sensitive and AZ CLI is submitted in camel case.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az afd profile create --profile-name {} --resource-group {} --sku Standard_AzureFrontDoor`
- `az afd endpoint create --resource-group {} --endpoint-name {} --profile-name {} --enabled-state {}`

## Expected Behavior

A Front Door profile should be created and then a endpoint should be added to the profile.

## Environment Summary
```
macOS-13.1-arm64-arm-64bit, Darwin 22.2.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
aks-preview 0.5.128
ssh 1.1.3
containerapp 0.3.22

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
This has been tested on Windows, macOS, and Linux.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@datadot Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@datadot Could you please share the `--debug` output ? Please remove the sensitive information from the output before sharing it here.

**Comment by datadot** [comment]
@navba-MSFT please find requested debug output below:

```
az afd endpoint create --resource-group {} --endpoint-name {} --profile-name {} --enabled-state Enabled --debug
cli.knack.cli: Command arguments: ['afd', 'endpoint', 'create', '--resource-group', '{}', '--endpoint-name', '{}', '--profile-name', '{}', '--enabled-state', 'Enabled', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101dd8280>, <function OutputProducer.on_global_arguments at 0x101e41000>, <function CLIQuery.on_global_arguments at 0x101e62440>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'afd': ['azure.cli.command_modules.cdn']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: cdn                       0.003        39       133
cli.azure.cli.core: Total (1)                 0.003        39       133
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 39 groups, 133 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : afd endpoint create
cli.azure.cli.core: Command table: afd endpoint create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1029eb490>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/xx/.azure/commands/2023-02-24.08-13-52.afd_endpoint_create.83355.log'.
az_command_data_logger: command args: afd endpoint create --resource-group {} --endpoint-name {} --profile-name {} --enabled-state {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102a0be20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x102a5e4d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x102a5e5f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x101e41090>, <function CLIQuery.handle_query_parameter at 0x101e624d0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x102a5e560>]
Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CdnManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/xx/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/xx/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/xx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xx/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: df091c7d-fb50-400e-a916-c3c76e0aecf7
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/xx/resourceGroups/{}/providers/Microsoft.Cdn/profiles/{}/afdEndpoints/{}?api-version=2021-06-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '117'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xx'
cli.azure.cli.core.sdk.policies:     'CommandName': 'afd endpoint create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --endpoint-name --profile-name --enabled-state --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.45.0 (HOMEBREW) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (macOS-13.2.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "global", "properties": {"enabledState": "Enabled", "autoGeneratedDomainNameLabelScope": "TenantReuse"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/xx/resourceGroups/{}/providers/Microsoft.Cdn/profiles/{}/afdEndpoints/{}?api-version=2021-06-01 HTTP/1.1" 400 245
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '245'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '99'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'xx'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xx'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '40761dac-5b48-4b83-b798-1fd7edcb472e'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230224T081353Z:xx'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 24 Feb 2023 08:13:52 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "BadRequest",
    "message": "Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE"
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/cdn/custom/custom_afdx.py", line 162, in create_afd_endpoint
    return sdk_no_wait(no_wait, client.begin_create, resource_group_name, profile_name, endpoint_name, endpoint)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 717, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/mgmt/cdn/operations/_afd_endpoints_operations.py", line 614, in begin_create
    raw_result = self._create_initial(
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/mgmt/cdn/operations/_afd_endpoints_operations.py", line 552, in _create_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
Code: BadRequest
Message: Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE

cli.azure.cli.core.azclierror: (BadRequest) Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
Code: BadRequest
Message: Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
az_command_data_logger: (BadRequest) Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
Code: BadRequest
Message: Property 'AfdEndpoint.AutoGeneratedDomainNameLabelScope' cannot be set to 'TenantReuse'. Acceptable values are: UNSECURE, TENANTREUSE, SUBSCRIPTIONREUSE, RESOURCEGROUPREUSE, NOREUSE
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1029eb6d0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.036 seconds (init: 0.054, invoke: 0.982)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3817 in cache
telemetry.check: Negative: The /Users/xx/.azure/telemetry.txt was modified at 2023-02-24 08:13:20.652192, which in less than 600.000000 s
```

**Comment by navba-MSFT** [comment]
@datadot Thanks for your reply. I have created the above PR to address this. It is currently under review.

**Comment by t-bzhan** [comment]
This is a service side regression to parse ENUM case-sensitively, the fix will be rolled out in several days.

**Comment by zhuofudeng** [comment]
Please contact the Azure support team to create a ticket to Azure CDN team if you need to mitigate the issue immediately.

**Comment by datadot** [comment]
Thanks @t-bzhan and @zhuofudeng your advised time frame is fine.

**Comment by t-bzhan** [comment]
Fix rolled out, closed the issue
