### ISSUE TITLE
az login command failure

### ISSUE THREAD

**Issue by sanman08** [Azure/azure-cli#25625]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
7e3eedd15a8f:/# az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /370ab0fd-38ab-4c72-b86f-153c941f439b/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', OSError(107, 'Socket not connected')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 458, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.10/ssl.py", line 1154, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.10/ssl.py", line 1119, in _check_connected
    self.getpeername()
OSError: [Errno 107] Socket not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /370ab0fd-38ab-4c72-b86f-153c941f439b/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', OSError(107, 'Socket not connected')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 176, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 756, in find_using_common_tenant
    specific_tenant_credential = identity.get_user_credential(username)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 225, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 45, in __init__
    super().__init__(client_id, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/msal/application.py", line 1685, in __init__
    super(PublicClientApplication, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/msal/application.py", line 533, in __init__
    self.authority = Authority(
  File "/usr/local/lib/python3.10/site-packages/msal/authority.py", line 120, in __init__
    openid_config = tenant_discovery(
  File "/usr/local/lib/python3.10/site-packages/msal/authority.py", line 175, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /370ab0fd-38ab-4c72-b86f-153c941f439b/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', OSError(107, 'Socket not connected')))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Expected Behavior
az login should authenticate successfully.
## Environment Summary
```
Linux-5.19.0-32-generic-x86_64-with, Alpine Linux v3.17
Python 3.10.9
Installer: DOCKER

azure-cli 2.45.0
```

**Comment by sanman08** [comment]
Nslookup is fine so not a dns issue

7e3eedd15a8f:/# nslookup login.microsoftonline.com
Server:		192.168.0.1
Address:	192.168.0.1:53

Non-authoritative answer:
login.microsoftonline.com	canonical name = login.mso.msidentity.com
login.mso.msidentity.com	canonical name = ak.privatelink.msidentity.com
ak.privatelink.msidentity.com	canonical name = www.tm.ak.prd.aadg.trafficmanager.net
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.87
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.64
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 20.190.163.21
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.144
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.151
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 20.190.163.19
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 40.126.35.80
Name:	www.tm.ak.prd.aadg.trafficmanager.net
Address: 20.190.163.18

Non-authoritative answer:
login.microsoftonline.com	canonical name = login.mso.msidentity.com
login.mso.msidentity.com	canonical name = ak.privatelink.msidentity.com
ak.privatelink.msidentity.com	canonical name = www.tm.ak.prd.aadg.trafficmanager.net

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by d-caviedes** [comment]
I have the same issue

**Comment by cpuntha** [comment]
I also having this issue

**Comment by bebound** [comment]
I can't repro, it looks like a network issue.
What's the output of this?
```
cd "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\"
.\python.exe -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
````

**Comment by hiephm** [comment]
same issue here.
testing with curl giving error:
```
curl https://login.microsoftonline.com
curl: (35) Network file descriptor is not connected
(venv) [root@fci-tools autoscaler]# curl -vvv  https://login.microsoftonline.com
* About to connect() to login.microsoftonline.com port 443 (#0)
*   Trying 40.126.35.129...
* Connected to login.microsoftonline.com (40.126.35.129) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5978 (PR_NOT_CONNECTED_ERROR)
* Network file descriptor is not connected
* Closing connection 0
curl: (35) Network file descriptor is not connected
```

however try to force curl use tls1.1 then it is fine:
```
curl --tlsv1.1  -vvv  https://login.microsoftonline.com
* About to connect() to login.microsoftonline.com port 443 (#0)
*   Trying 40.126.16.165...
* Connected to login.microsoftonline.com (40.126.16.165) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
*       subject: CN=stamp2.login.microsoftonline.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
*       start date: Nov 27 00:00:00 2022 GMT
*       expire date: Nov 27 23:59:59 2023 GMT
*       common name: stamp2.login.microsoftonline.com
*       issuer: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: login.microsoftonline.com
> Accept: */*
>
< HTTP/1.1 302 Found
```

**Comment by sanman08** [comment]
$ python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 453, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.10/ssl.py", line 1154, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.10/ssl.py", line 1119, in _check_connected
    self.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 453, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.10/ssl.py", line 1154, in getpeercert
    self._check_connected()
  File "/usr/lib/python3.10/ssl.py", line 1119, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))

**Comment by sanman08** [comment]
yes this is working now. Thanks.
