### ISSUE TITLE
 requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by alex8bitw** [Azure/azure-cli#25627]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
│ Error: obtaining Authorization Token from the Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
│ Traceback (most recent call last):
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
│     httplib_response = self._make_request(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
│     self._validate_conn(conn)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
│     conn.connect()
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connection.py", line 416, in connect
│     self.sock = ssl_wrap_socket(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
│     ssl_sock = _ssl_wrap_socket_impl(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
│     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
│     return self.sslsocket_class._create(
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 1071, in _create
│     self.do_handshake()
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
│     self._sslobj.do_handshake()
│ ConnectionResetError: [Errno 104] Connection reset by peer
│
│ During handling of the above exception, another exception occurred:
│
│ Traceback (most recent call last):
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
│     resp = conn.urlopen(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
│     retries = retries.increment(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
│     raise six.reraise(type(error), error, _stacktrace)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
│     raise value.with_traceback(tb)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
│     httplib_response = self._make_request(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
│     self._validate_conn(conn)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
│     conn.connect()
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/connection.py", line 416, in connect
│     self.sock = ssl_wrap_socket(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
│     ssl_sock = _ssl_wrap_socket_impl(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
│     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
│     return self.sslsocket_class._create(
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 1071, in _create
│     self.do_handshake()
│   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
│     self._sslobj.do_handshake()
│ urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
│
│ During handling of the above exception, another exception occurred:
│
│ Traceback (most recent call last):
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
│     raise ex
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
│     result = cmd_copy(params)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
│     return self.handler(*args, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 66, in get_access_token
│     creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     sdk_token = credential.get_token(*scopes)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 69, in get_token
│     result = self.acquire_token_silent_with_error(list(scopes), self._account, claims_challenge=claims, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1287, in acquire_token_silent_with_error
│     result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1392, in _acquire_token_silent_from_cache_and_possibly_refresh_it
│     result = _clean_up(self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1444, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
│     last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/application.py", line 1491, in _acquire_token_silent_by_finding_specific_refresh_token
│     response = client.obtain_token_by_refresh_token(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 830, in obtain_token_by_refresh_token
│     resp = super(Client, self).obtain_token_by_refresh_token(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 262, in obtain_token_by_refresh_token
│     return self._obtain_token("refresh_token", data=data, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
│     ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 771, in _obtain_token
│     resp = super(Client, self)._obtain_token(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/oauth2cli/oauth2.py", line 234, in _obtain_token
│     resp = (post or self._http_client.post)(
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
│     value = function(*args, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
│     value = function(*args, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
│     return self.request('POST', url, data=data, json=json, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
│     resp = self.send(prep, **send_kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
│     r = adapter.send(request, **kwargs)
│   File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/requests/adapters.py", line 498, in send
│     raise ConnectionError(err, request=request)
│ requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
│ To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
│ To open a new issue, please run `az feedback`
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {} --subscription {} -o={}`

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
account 0.2.3
containerapp 0.3.16
image-copy-extension 0.2.12
storage-preview 0.8.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
What's the output of `python -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"`?

Maybe this is related to https://github.com/Azure/azure-cli/issues/25625#issuecomment-1449566859

**Comment by alex8bitw** [comment]
Yeah, definitely related.  Eventually it just started to work, so guessing it was "just" an outage.
