### ISSUE TITLE
Cannot create media services account from command line

### ISSUE THREAD

**Issue by michalzubkowicz** [Azure/azure-cli#25646]
## Describe the bug

**Command Name**
`az ams account sp create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/ams/_exception_handler.py", line 16, in ams_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/ams/operations/sp.py", line 78, in create_or_update_assign_sp_to_mediaservice
    return _update_sp(cmd, graph_client, aad_sp, ams, account_name, resource_group_name,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/ams/operations/sp.py", line 111, in _update_sp
    app_object_id = _get_application_object_id(graph_client, app_id)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/ams/operations/sp.py", line 237, in _get_application_object_id
    return list(client.application_list(filter="appId eq '{}'".format(identifier)))[0]['id']
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ams account sp create -a {} -g {} -n {} --role {}`

## Environment Summary
```
Linux-5.19.0-32-generic-x86_64-with-glibc2.35, KDE neon 5.27
Python 3.10.8
Installer: DEB

azure-cli 2.45.0

Extensions:
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by akucer** [comment]
Closing as won't fix as Azure Media Services was retired on 6/30/2024 (https://aka-ms/ams-retirement).
