### ISSUE TITLE
Failed "az advisor recommendation list --category Cost --refresh"

### ISSUE THREAD

**Issue by rfraneksodexo** [Azure/azure-cli#25657]
## Describe the bug

**Command Name**
`az advisor recommendation list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
request() got an unexpected keyword argument 'raw'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/advisor/custom.py", line 13, in list_recommendations
    _generate_recommendations(client)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/advisor/custom.py", line 152, in _generate_recommendations
    response = client.generate(raw=True)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/advisor/operations/_recommendations_operations.py", line 84, in generate
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 119, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 327, in send
    response = self.session.request(  # type: ignore
TypeError: request() got an unexpected keyword argument 'raw'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az advisor recommendation list --category Cost --refresh`

## Environment Summary
```
Linux-5.4.0-1103-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.45.0

Extensions:
ai-examples 0.2.5
ml 2.13.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@rfraneksodexo We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team
