### ISSUE TITLE
Strange python error when running Azure Cli

### ISSUE THREAD

**Issue by mikaelsand** [Azure/azure-cli#25691]
## Describe the bug

**Command Name**
`az ad app update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/commands.py", line 51, in graph_err_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 200, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 703, in update_application
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1584, in _set_application_properties
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1612, in _build_app_roles
AttributeError: 'str' object has no attribute 'get'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I executed the command using this line
az ad app update --id <myGuid> --app-roles .\roleDefintionFile.json

The RoledDefinition file contains a JSON array with all the role definitions.
```JSON
[
    {
        "allowedMemberTypes": [
            "Application"
        ],
        "description": "My desc",
        "displayName": "My Displayname",
        "id": "<A GUID>",
        "isEnabled": true,
        "value": "A value with / in it."
    }
]
```

## Expected Behavior

Update the app reg to contain the role definition.

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0 *
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I am not able to repro with the provided JSON:

```
> az ad app update --id 1439c242-b7ed-48df-964e-4dcb672a0cc8 --app-roles D:\test\app-roles.json
One or more properties contains invalid values.
```

```json
[
    {
        "allowedMemberTypes": [
            "Application"
        ],
        "description": "My desc",
        "displayName": "My Displayname",
        "id": "32729182-ef55-4ca0-b1e6-ad4889c5055d",
        "isEnabled": true,
        "value": "A value with / in it."
    }
]
```

The error `One or more properties contains invalid values.` is expected, as space is not allowed in `value`: https://learn.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-1.0

The line that fails is https://github.com/Azure/azure-cli/blob/3e26929f7669c504a5720e7f63c4be729534d52e/src/azure-cli/azure/cli/command_modules/role/custom.py#L1612

I doubt the actual content of `.\roleDefintionFile.json` is a list of string. I got similar error if I edit `D:\test\app-roles.json` to 

```json
[
    "a", "b"
]
```

```
> az ad app update --id 1439c242-b7ed-48df-964e-4dcb672a0cc8 --app-roles D:\test\app-roles.json
The command failed with an unexpected error. Here is the traceback:
'str' object has no attribute 'get'
Traceback (most recent call last):
  File "D:\cli\py310\lib\site-packages\knack\cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 663, in execute
    raise ex
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\role\commands.py", line 51, in graph_err_handler
    raise ex
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "d:\cli\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 200, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\role\custom.py", line 728, in update_application
    _set_application_properties(
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\role\custom.py", line 1603, in _set_application_properties
    kwargs['app_roles'] = _build_app_roles(kwargs['app_roles'])
  File "d:\cli\azure-cli\src\azure-cli\azure\cli\command_modules\role\custom.py", line 1631, in _build_app_roles
    if not x.get(ID):
AttributeError: 'str' object has no attribute 'get'
```

**Comment by mikaelsand** [comment]
This case was as simple as: Update Azure Cli. It just worked.
