### ISSUE TITLE
az network vnet subnet show doen't work

### ISSUE THREAD

**Issue by azenakhi** [Azure/azure-cli#25696]
## Describe the bug

**Command Name**
`az network vnet subnet show`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet subnet show --resource-group {} --vnet-name {} --name {} --query {} -o {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
aks-preview 0.5.131
resource-graph 2.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@azenakhi `az network vnet subnet show --resource-group {} --vnet-name {} --name {} --query {} -o {}` is too crude, please provide the essential information. As well as **the error message**.

**Comment by azenakhi** [comment]
az network vnet subnet show --resource-group <rg> --vnet-name <sub> --name <subnet> --query id -o tsv
The command failed with an unexpected error. Here is the traceback:
option values must be strings
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 680, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 154, in save_local_context
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/local_context.py", line 116, in set
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 239, in set_value
  File "configparser.py", line 1204, in set
  File "configparser.py", line 1189, in _validate_value_types
TypeError: option values must be strings
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by necusjz** [comment]
Sorry, I still cannot reproduce your problem:
![image](https://user-images.githubusercontent.com/12371639/223618930-13f2a41a-1a9f-4a5d-a495-0673b8cd3679.png)
