### ISSUE TITLE
az aks install-cli is failing

### ISSUE THREAD

**Issue by pjillella** [Azure/azure-cli#25709]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
$ az aks install-cli
←[93mThe detected architecture is 'amd64', which will be regarded as 'amd64' and the corresponding binary will be downloaded. If there is any problem, please download the appropriate binary by yourself.←[0m
←[93mDownloading client to "C:\Users\c-pjillell\.azure-kubectl\kubectl.exe" from "https://storage.googleapis.com/kubernetes-release/release/v1.26.2/bin/windows/amd64/kubectl.exe"←[0m
←[91mThe command failed with an unexpected error. Here is the traceback:←[0m
←[91mHTTP Error 403: Forbidden
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially        
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1441, in k8s_install_cli      
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1616, in k8s_install_kubelogin
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden←[0m
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
aks-preview 0.5.38
interactive 0.4.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@pjillella We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@pjillella Can you please try to open PowerShell as an Administrator.  I was able to reproduce this issue and able to run the command once open PowerShell with Administrator permissions.
![image](https://user-images.githubusercontent.com/38112130/225108556-f89c68ce-dcc8-43d9-9f6d-9c9c53647145.png)
