### ISSUE TITLE
az bicep format --file a.bicep missing 1 required positional argument: 'cli_ctx'

### ISSUE THREAD

**Issue by JanuszNowak** [Azure/azure-cli#25706]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az bicep format --file a.bicep

**Describe the bug**

az bicep format --file a.bicep
The command failed with an unexpected error. Here is the traceback:
ensure_bicep_installation() missing 1 required positional argument: 'cli_ctx'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3678, in format_bicep_file
TypeError: ensure_bicep_installation() missing 1 required positional argument: 'cli_ctx'

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@JanuszNowak Thanks for catching that and apologies for the inconvenience! We are working up a fix to address this.

**Comment by JanuszNowak** [comment]
@PramodValavala-MSFT open PR for this fix https://github.com/Azure/azure-cli/pull/25707
