### ISSUE TITLE
Trying to upgrade to v0.15.31 with az bicep upgrade, the command fails with an unexpected error.

### ISSUE THREAD

**Issue by YuKogasaka** [Azure/azure-cli#25715]
## Describe the bug
**Command Name**
`az bicep upgrade`

**Errors:**
```
Installing Bicep CLI v0.15.31...
The command failed with an unexpected error. Here is the traceback:
No section: 'bicep'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3657, in upgrade_bicep_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 99, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 94, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 208, in get
  File "configparser.py", line 783, in get
  File "configparser.py", line 1154, in _unify_values
configparser.NoSectionError: No section: 'bicep'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep upgrade`

## Expected Behavior
Upgrade completed successfully to v0.15.31.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0

Extensions:
azure-firewall 0.14.5
bastion 0.2.3
containerapp 0.3.22
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by developing-azure-solutions-121212** [comment]
this is also happening with a fresh install, and older versions

![image](https://user-images.githubusercontent.com/127224341/223736779-415184e3-fb1b-444e-b190-d6a300368f85.png)

**Comment by developing-azure-solutions-121212** [comment]
also, it works sometimes... 
![image](https://user-images.githubusercontent.com/127224341/223737552-eb5fc672-5f29-4990-8687-177ee7379842.png)

**Comment by PramodValavala-MSFT** [comment]
@YuKogasaka Thanks for the feedback! We have worked up a PR to address this.

Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.

**Comment by robmaw** [comment]
> @YuKogasaka Thanks for the feedback! We have worked up a PR to address this.
> 
> Please do note that despite this error, the `bicep` CLI is installed and can be used as usual.

This is not correct - i.e. the bicep installed with an az cli installation is broken in the same way:

##[error]Error: Command failed: az bicep build --file /agent/_work/1/s/templates/DevTestLabs/dtl_main.bicep
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No section: 'bicep'

**Comment by PramodValavala-MSFT** [comment]
@robmaw Thanks for the feedback! This is a workaround in the meantime is to manually set the config value before the fix is out.

```
az config set bicep.use_binary_from_path=False
az bicep install
```
