### ISSUE TITLE
CLI checks for local dockerfile when remote url is provided

### ISSUE THREAD

**Issue by thegalah** [Azure/azure-cli#2571]
az container build create --target-resource-group mindaro-e2e-dev --target-name mindaro-e2e-dev --remote-access-token xxx --remote-url https://github.com/thegalah/sample-app.git

will fail:

Command '['git', 'rev-parse', '--is-inside-git-dir']' returned non-zero exit status 128
Traceback (most recent call last):
  File "/Users/matthewduong/Desktop/mindaro/azure-cli/src/azure-cli/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/matthewduong/Desktop/mindaro/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/matthewduong/Desktop/mindaro/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 363, in _execute_command
    raise ex
CalledProcessError: Command '['git', 'rev-parse', '--is-inside-git-dir']' returned non-zero exit status 128

**Comment by derekbekoe** [comment]
Closed with https://github.com/Azure/azure-cli/pull/2572
