### ISSUE TITLE
Error installing operation-abort using az cli aks-preview 

### ISSUE THREAD

**Issue by jmbarreiro1** [Azure/azure-cli#25718]
## Describe the bug

**Command Name**
``
az aks operation-abort

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.10/argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2070, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2026, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1213, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 284, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2070, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2026, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1919, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 275, in _get_values
    value = super(AzCliCommandParser, self)._get_values(action, arg_strings)
  File "/opt/az/lib/python3.10/argparse.py", line 2460, in _get_values
    self._check_value(action, value[0])
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 326, in _check_value
    recommender.set_help_examples(self.get_examples(command_name_inferred))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 201, in get_examples
    return self.cli_help.get_examples(command,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_help.py", line 192, in get_examples
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.10/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_help.py", line 303, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.10/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.10/site-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/opt/az/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josemanuel.barreiro@healthincode.global/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/__init__.py", line 9, in <module>
    from ._container_service_client import ContainerServiceClient
  File "/home/josemanuel.barreiro@healthincode.global/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/_container_service_client.py", line 19, in <module>
    from .operations import AgentPoolsOperations, FleetMembersOperations, FleetsOperations, MaintenanceConfigurationsOperations, ManagedClusterSnapshotsOperations, ManagedClustersOperations, Operations, PrivateEndpointConnectionsOperations, PrivateLinkResourcesOperations, ResolvePrivateLinkServiceIdOperations, SnapshotsOperations, TrustedAccessRoleBindingsOperations, TrustedAccessRolesOperations
  File "/home/josemanuel.barreiro@healthincode.global/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/__init__.py", line 9, in <module>
    from ._operations import Operations
  File "/home/josemanuel.barreiro@healthincode.global/.azure/cliextensions/aks-preview/azext_aks_preview/vendored_sdks/azure_mgmt_preview_aks/v2022_07_02_preview/operations/_operations.py", line 19, in <module>
    from azure.core.utils import case_insensitive_dict
ImportError: cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-139-generic-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.94
azure-firewall 0.13.0
automation 0.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jmbarreiro1** [comment]
Hi @saurabhsharma-msft

Sorry for the delay in my answer. I updated the az cli to a new version and
it is working fine now. Thank you for your help.

Regards

**Comment by SaurabhSharma-MSFT** [comment]
@jmbarreiro1 Thanks for the confirmation. We will now proceed to close this thread.
