### ISSUE TITLE
`az bicep version` results in a `rosetta error`

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [Azure/azure-cli#25726]
## Describe the bug

```bash
$ az bicep version
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

**Command Name**
`az bicep version`

**Errors:**
```bash
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

## To Reproduce:

Install the az cli tool in an `aarch64` container with the following command:

```bash
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

- _Put any pre-requisite steps here..._
- `az bicep version`

## Expected Behavior

Bicep successfully runs.

## Environment Summary
```
Linux-5.15.49-linuxkit-aarch64-with-glibc2.31, Debian GNU/Linux 11 (bullseye)
Python 3.9.2
Installer: PIP

azure-cli 2.46.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@kurt-mueller-osumc Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@kurt-mueller-osumc Could you please confirm if you had used Linux ARM64  or Linux x64 bicep during installation ?

Also please run the `az bicep version --debug` command and share the detailed debug output here. Awaiting your reply.

**Comment by kurt-mueller-osumc** [comment]
Well, I get a slightly different error now. Again, I'm attempting to use bicep inside a docker container that's being virtulaized by rosetta.

```bash
 $ az bicep version
Bicep CLI not found. Install it now by running "az bicep install".
$ az bicep install
Installing Bicep CLI v0.15.31...
The command failed with an unexpected error. Here is the traceback:
No section: 'bicep'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3648, in install_bicep_cli
    ensure_bicep_installation(cmd.cli_ctx, release_tag=version, target_platform=target_platform)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
    use_binary_from_path = cli_ctx.config.get("bicep", "use_binary_from_path").lower()
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 99, in get
    raise last_ex  # pylint:disable=raising-bad-type
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 94, in get
    return config.get(section, option)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 208, in get
    return self.config_parser.get(section, option)
  File "/opt/az/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/opt/az/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'bicep'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

**Comment by navba-MSFT** [comment]
@kurt-mueller-osumc Thanks for getting back. This is a known issue and it is fixed as a part of 
PR https://github.com/Azure/azure-cli/pull/25729 . The fix should be released in 4/4/2023 AzCLI release as a part of this milestone: https://github.com/Azure/azure-cli/milestone/128
