### ISSUE TITLE
az aro create command failed with error azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by lkalaivanan** [Azure/azure-cli#25774]
## Describe the bug

**Command Name**
`az aro create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/util.py", line 993, in send_raw_request
    raise HTTPError(reason, r)
azure.cli.core.azclierror.HTTPError: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2023-03-12T17:22:04","request-id":"305e665c-98c8-46fe-852d-f02073c75d7d","client-request-id":"305e665c-98c8-46fe-852d-f02073c75d7d"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/aro/custom.py", line 78, in aro_create
    client_id, client_secret = aad.create_application(cluster_resource_group or 'aro-' + random_id)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/aro/_aad.py", line 24, in create_application
    app = self.client.application_create(request_body)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 91, in application_create
    result = self._send("POST", "/applications", body=body)
  File "/opt/homebrew/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 55, in _send
    raise GraphError(ex.response.json()['error']['message'], ex.response) from ex
azure.cli.command_modules.role._msgrpah._graph_client.GraphError: Insufficient privileges to complete the operation.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az group create --name {}--location eastus
- az network vnet create --resource-group {} --name {} --address-prefixes 10.0.0.0/22
- az network vnet subnet create --resource-group {} --vnet-name {} --name {} --address-prefixes 10.0.0.0/23 --service-endpoints Microsoft.ContainerRegistry
- az network vnet subnet create --resource-group {} --vnet-name {} --name {} --address-prefixes 10.0.2.0/23 --service-endpoints Microsoft.ContainerRegistry
- az network vnet subnet update --name {} --resource-group {} --vnet-name {} --disable-private-link-service-network-policies true
- `az aro create --resource-group {} --name {} --vnet {} --master-subnet {} --worker-subnet {} --worker-count {}`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit
Python 3.10.8
Installer: PIP

azure-cli 2.39.0 *
```

also tried with flowing azure-cli versions  2.43.0 and 2.46.0

**Comment by lkalaivanan** [comment]
> Hi @lkalaivanan,
> 
> 2.39.0 is not the latest Azure CLI(2.46.0).
> 
> Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

tried with flowing azure-cli versions 2.43.0 and 2.46.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by lkalaivanan** [comment]
@yonzhan  Is some one looking into this issue.. We are bloacked due to this bug in CLI please let us know if there is any workaround.

**Comment by jsntcy** [comment]
The error message "Insufficient privileges to complete the operation" suggests that the user does not have the necessary permissions to perform the operation. The user needs to have either Contributor and User Access Administrator permissions, or Owner permissions, either directly on the virtual network, or on the resource group or subscription containing it. The user can assign [administrator roles to users with Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-users-assign-role-azure-portal).

**Comment by jsafarik** [comment]
@jsntcy I used azure-cli version 2.50.0, have my service principal added to the resource group where I want to create ARO instance in as an Owner (resource group -> access control), and I am still getting the same error as @lkalaivanan . 

The [official documentation](https://learn.microsoft.com/en-us/azure/openshift/tutorial-create-cluster) states also various resource providers that I've checked that they are registered. What could the problem be? At the moment it is impossible for us to install ARO cluster using CLI.

**Comment by jsntcy** [comment]
Add @darthhexx, @tsatam, @dem4gus, @SudoBrendan from service team to help take a look.

**Comment by SudoBrendan** [comment]
Greetings,

I'm +1 with other comments here, this doesn't appear to be a bug and instead seems like the person running this command does not have the permissions to create an Application ID (Service Principal) in the tenant. There's two ways to fix this:

1. Bring your own pre-created service principal by passing the `--client-id` and `--client-secret`
2. Run the `az aro create` command as a user that has the permissions to modify AAD resources, including creating the cluster Service Principal and assigning it the required permissions on the cluster infrastructure resource group

For a quicker resolution to any ARO issues you may experience in the future, you can go to either Red Hat or Microsoft Azure support, we monitor those much more than GH issues :)
