### ISSUE TITLE
The command failed with an unexpected error. [Errno 86]

### ISSUE THREAD

**Issue by rick-wubs** [Azure/azure-cli#25785]
## Describe the bug
`az bicep upgrade` command fails with 'Bad CPU type' error.

**Command Name**
`az bicep upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 86] Bad CPU type in executable: '/Users/rickwubs/.azure/bin/bicep'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3657, in upgrade_bicep_cli
    ensure_bicep_installation(cmd.cli_ctx, release_tag=latest_release_tag, target_platform=target_platform)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 118, in ensure_bicep_installation
    installed_version = _get_bicep_installed_version(installation_path)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 264, in _get_bicep_installed_version
    installed_version_output = _run_command(bicep_executable_path, ["--version"])
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 302, in _run_command
    process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/rickwubs/.azure/bin/bicep'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `brew install azure-cli`
- `az update`
- `az bicep install`
- `az bicep upgrade`

## Expected Behavior
Upgrade the installed bicep.

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.46.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by pejuborg** [comment]
I get a similar response running on WSL 2/ Ubuntu 20.04.5 LTS

Installing Bicep CLI v0.15.31...
The command failed with an unexpected error. Here is the traceback:
No section: 'bicep'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3657, in upgrade_bicep_cli
    ensure_bicep_installation(cmd.cli_ctx, release_tag=latest_release_tag, target_platform=target_platform)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
    use_binary_from_path = cli_ctx.config.get("bicep", "use_binary_from_path").lower()
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 99, in get
    raise last_ex  # pylint:disable=raising-bad-type
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 94, in get
    return config.get(section, option)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 208, in get
    return self.config_parser.get(section, option)
  File "/opt/az/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/opt/az/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'bicep'

**Comment by PramodValavala-MSFT** [comment]
@rick-wubs Thanks for the feedback! On first look, it looks like we aren't handling CPU Architecture when downloading the `bicep` CLI and hence the error. We will work up a fix for this.

In the meantime, you will have to install the `bicep` CLI directly using homebrew.

**Comment by PramodValavala-MSFT** [comment]
> I get a similar response running on WSL 2/ Ubuntu 20.04.5 LTS upgrading from Bicep CLI version 0.12.40 (41892bd0fb)
> 
> Installing Bicep CLI v0.15.31... The command failed with an unexpected error. Here is the traceback: No section: 'bicep' Traceback (most recent call last): File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke cmd_result = self.invocation.execute(args) File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/**init**.py", line 663, in execute raise ex File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/**init**.py", line 726, in _run_jobs_serially results.append(self._run_job(expanded_arg, cmd_copy)) File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/**init**.py", line 697, in _run_job result = cmd_copy(params) File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/**init**.py", line 333, in **call** return self.handler(*args, **kwargs) File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler return op(**command_args) File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3657, in upgrade_bicep_cli ensure_bicep_installation(cmd.cli_ctx, release_tag=latest_release_tag, target_platform=target_platform) File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation use_binary_from_path = cli_ctx.config.get("bicep", "use_binary_from_path").lower() File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 99, in get raise last_ex # pylint:disable=raising-bad-type File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 94, in get return config.get(section, option) File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 208, in get return self.config_parser.get(section, option) File "/opt/az/lib/python3.10/configparser.py", line 783, in get d = self._unify_values(section, vars) File "/opt/az/lib/python3.10/configparser.py", line 1154, in _unify_values raise NoSectionError(section) from None configparser.NoSectionError: No section: 'bicep'

@pejuborg This is being tracked here - #25710

**Comment by pejuborg** [comment]
@PramodValavala-MSFT 
In my case I can run the same command again without error and the bicep module is properly upgraded.

**Comment by PramodValavala-MSFT** [comment]
> @rick-wubs Thanks for the feedback! By default, Azure CLI defaults to fetching the `x86_64` bicep CLI. You can override it with the following in your case
> 
> ```shell
> # For Install
> az bicep install --target-platform osx-arm64
> 
> # For Upgrade
> az bicep upgrade --target-platform osx-arm64
> ```

@rick-wubs [This](https://github.com/Azure/azure-cli/issues/25785#issuecomment-1466966885) is the comment that is specific to the error that you are getting
