### ISSUE TITLE
Unable to update PLS - Inconsist nullable property between target and source args

### ISSUE THREAD

**Issue by npasken** [Azure/azure-cli#25784]
## Describe the bug

**Command Name**
`az network private-link-service update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Inconsist nullable property between target and source args
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_poller.py", line 105, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_poller.py", line 127, in wait
    raise self._exception  # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_poller.py", line 80, in _start
    for polling_method in self._polling_generator:
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/private_link_service/_update.py", line 1132, in _execute_operations
    self.pre_operations()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 3810, in pre_operations
    args.load_balancer_frontend_ip_configurations = assign_aaz_list_arg(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/utils.py", line 27, in assign_aaz_list_arg
    assert target_schema._nullable == source_schema._nullable, "Inconsist nullable property between target and " \
AssertionError: Inconsist nullable property between target and source args
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network private-link-service update --resource-group {} --name {} --subscription {} --lb-frontend-ip-configs {}`

## Expected Behavior
Modify PLS resource to use updated lb-frontend-ip-config

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Command worked with prior version of azure-cli 2.38.0. Had to downgrade to resolve production issue.
Behavior was the same for Windows and Linux builds of azure-cli.

**Comment by yonzhan** [comment]
@necusjz for awareness
