### ISSUE TITLE
New ssh version causes error

### ISSUE THREAD

**Issue by salob** [Azure/azure-cli#25804]
**Related command**
`az ssh vm`

**Describe the bug**
When adding latest ssh version (1.1.4) extension we see the below issue
Rolling back to ssh version 1.1.3 works as expected

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/jenkins/.azure/cliextensions/ssh/azext_ssh/custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "/home/jenkins/.azure/cliextensions/ssh/azext_ssh/custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
  File "/home/jenkins/.azure/cliextensions/ssh/azext_ssh/ip_utils.py", line 36, in get_ssh_ip
    if public_ip_ref and public_ip_ref.get("id", None):
AttributeError: 'str' object has no attribute 'get'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**To Reproduce**
run
`az ssh vm -n [vm-name] -g [resource-group]`

install the ssh extension when prompted

**Expected behavior**
`az ssh vm` ssh's to the machine as expected

**Environment summary**
az-cli extension install

**Additional context**
N/A

## Workaround

Install ssh v 1.1.3

`az extension add --name ssh --version 1.1.3`

**Comment by salob** [comment]
closing as duplicate of  #5984

**Comment by navba-MSFT** [comment]
@salob Adding the right issue https://github.com/Azure/azure-cli-extensions/issues/5984
