### ISSUE TITLE
az containerapp update | Remote end closed connection without response

### ISSUE THREAD

**Issue by bboycenteno** [Azure/azure-cli#25816]
> ### `az containerapp update` closes connection while running in GitHub Actions runners.

**Describe the bug**
This issue is intermittent while running the command `az containerapp update` from GitHub Actions runners (not self-hosted).

See the below stack trace seen:
```
/ Running ..
| Running ..
\ Running ..
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/az/lib/python3.10/http/client.py", line 3[18](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:19), in begin
    version, status, reason = self._read_status()
  File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/az/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/az/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/az/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/az/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 1[21](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:22), in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 9[25](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:26), in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 896, in update_containerapp_logic
    handle_raw_exception(e)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 888, in update_containerapp_logic
    r = ContainerAppClient.update(
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 1[31](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:32), in update
    return poll(cmd, request_url, "inprogress")
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 71, in poll
    raise e
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_clients.py", line 56, in poll
    r = send_raw_request(cmd.cli_ctx, "GET", request_url)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 1003, in send_raw_request
    r = s.send(prepped, **settings)
  File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line [49](https://github.com/crfusa/c2c-exchange/actions/runs/4376282564/jobs/7658198474#step:5:50)8, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

There are a few other references:
https://github.com/Azure/azure-cli/issues/21375
https://github.com/microsoft/azure-container-apps/issues/661

Looking to the stack trace from previous reports, it looks like the issue is caused by a connectivity problem, see:

`File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699,`

This issue was reported through a support request to Azure Container Apps team, after a retry the command works, from support we were not able to reproduce the same issue.

Here is snippet of the command (with PowerShell as main shell):

```
az containerapp update `
        --image "$AcrPath/$Image" `
        -n $appName `
        -g $Environment `
        --set-env-vars "EnvironmentDeployed=$nowDate" "EnvironmentVersion=$ImageTag" `
        --subscription $Subscription `
        --revision-suffix $RevisionSuffix
```

**To Reproduce**
Issue is very intermittent, so is not easy to reproduce. 
Run `az containerapp update` to update settings in Azure Container Apps resources.

**Environment summary**
`az version`
```
{
  "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.22",
    "ssh": "1.1.1"
  }
}
```

Task utilized:
```
- uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az extension add --name containerapp
      - name: Deploy to environment
        shell: pwsh
        run: |
          $env = "c2c-exchange-${{ inputs.env || 'qa' }}"
 
          ./tools/deploy-app-revision.ps1 `
            -Environment $env `
            -ImageName c2c-exchange/${{ matrix.app }} `
            -App app-${{ matrix.app }}
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by bboycenteno** [comment]
Hi @yonzhan CXP team has any update on this issue?

**Comment by kaparski** [comment]
same problem, waiting for update @yonzhan @bboycenteno

**Comment by bboycenteno** [comment]
@yonzhan today I another customer reported incident when using another command for container apps `az containerapp revision copy` but this time running in Azure DevOps:

```
2023-03-23T17:46:12.2049595Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-03-23T17:46:12.2050622Z ERROR: unhashable type: 'list'
2023-03-23T17:46:12.2051098Z Traceback (most recent call last):
2023-03-23T17:46:12.2051748Z   File '/opt/az/lib/python3.10/site-packages/knack/cli.py', line 233, in invoke
2023-03-23T17:46:12.2052691Z     cmd_result = self.invocation.execute(args)
2023-03-23T17:46:12.2053381Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py', line 663, in execute
2023-03-23T17:46:12.2054402Z     raise ex
2023-03-23T17:46:12.2054885Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py', line 726, in _run_jobs_serially
2023-03-23T17:46:12.2055311Z     results.append(self._run_job(expanded_arg, cmd_copy))
2023-03-23T17:46:12.2055824Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py', line 718, in _run_job
2023-03-23T17:46:12.2056216Z     return cmd_copy.exception_handler(ex)
2023-03-23T17:46:12.2056620Z   File '/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py', line 28, in _polish_bad_errors
2023-03-23T17:46:12.2056979Z     raise ex
2023-03-23T17:46:12.2057404Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py', line 697, in _run_job
2023-03-23T17:46:12.2057785Z     result = cmd_copy(params)
2023-03-23T17:46:12.2058247Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py', line 333, in __call__
2023-03-23T17:46:12.2058627Z     return self.handler(*args, **kwargs)
2023-03-23T17:46:12.2059122Z   File '/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py', line 121, in handler
2023-03-23T17:46:12.2059500Z     return op(**command_args)
2023-03-23T17:46:12.2059862Z   File '/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py', line 1590, in copy_revision
2023-03-23T17:46:12.2060256Z     return update_containerapp_logic(cmd=cmd,
2023-03-23T17:46:12.2060660Z   File '/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py', line 789, in update_containerapp_logic
2023-03-23T17:46:12.2061100Z     new_containerapp['properties']['template']['scale'].pop(['rules'])
2023-03-23T17:46:12.2061461Z TypeError: unhashable type: 'list'
2023-03-23T17:46:12.2061880Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-03-23T17:46:12.2062246Z To open a new issue, please run `az feedback`
```

I tried the same command in my WSL. The only difference I noticed was the Python version - I have `python3.8`, DevOps and GitHub Actions utilize `python3.10`.

Could it be possible this issue is related to `python3.10`?

**Comment by bebound** [comment]
This is a HTTP error. It may result from backend server error or network connection.
Since the extension is not developed by cli team, you can create issue in https://github.com/Azure/azure-cli-extensions/issues,
or contact Azure Container Apps team.

@bboycenteno Apparently, this is a logic error, you can open issue in https://github.com/Azure/azure-cli-extensions/issues.

**Comment by bboycenteno** [comment]
Thanks @bebound we filed a bug on Azure Container Apps to resolve this issue.
