### ISSUE TITLE
az connectedk8s connect Failed

### ISSUE THREAD

**Issue by southmw** [Azure/azure-cli#25822]
## Describe the bug

**Command Name**
`az connectedk8s connect`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azext_connectedk8s.custom#create_connectedk8s' is invalid.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/custom.py", line 48, in <module>
    import azext_connectedk8s._utils as utils
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/_utils.py", line 28, in <module>
    import azext_connectedk8s._precheckutils as precheckutils
  File "/root/.azure/cliextensions/connectedk8s/azext_connectedk8s/_precheckutils.py", line 27, in <module>
    import azext_connectedk8s._utils as azext_utils
AttributeError: module 'azext_connectedk8s' has no attribute '_utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azext_connectedk8s.custom#create_connectedk8s' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {} --debug`

## Environment Summary
```
Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.9
Installer: RPM

azure-cli 2.38.0 *

Extensions:
connectedk8s 1.3.14

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@southmw I am not able to reproduce this.  Are you still having issues?  Can you please try upgrading your Azure CLI version?

**Comment by southmw** [comment]
Resolved after updating Azure CLI.
However, the maximum Azure Cli version supported by Cent OS 7 as a package was 2.38, so I installed it with a script.
