### ISSUE TITLE
issue updating tags with the az devops rest api

### ISSUE THREAD

**Issue by vllama** [Azure/azure-cli#25845]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 506, in shell_safe_json_parse
  File "json\__init__.py", line 370, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 812, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 531, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: System.Collections.Hashtable
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 19, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 815, in send_raw_request
ValueError: not enough values to unpack (expected 2, got 1)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
$json = '[{"op": "replace","path": "/fields/System.Tags","value": ""}]'
- az rest --method patch --url "https://dev.azure.com/{client}/{project}/_apis/wit/workitems/$($issue.id)?api-version=7.0" --headers $AuthHeader --body $json 
    

## Expected Behavior
 Expect tags to be cleared out.
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

Extensions:
application-insights 0.1.14
azure-devops 0.25.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vllama** [comment]
just updated and get the same error
I get the error when running other commands as well such as:
az webapp config set -g group-n APP--generic-configurations '{"vnetRouteAllEnabled": true}'


```
az --version
azure-cli                         2.46.0

core                              2.46.0
telemetry                          1.0.8

Extensions:
application-insights              0.1.14
azure-devops                      0.25.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1
```

**Comment by jiasli** [comment]
For `ValueError: not enough values to unpack (expected 2, got 1)`, it is due to incorrect `--header` format. Please follow the document to provide `--header`:

```
    --headers                         : Space-separated headers in KEY=VALUE format or JSON string.
                                        Use @{file} to load from a file.
```

Also, when passing JSON string to `az`, make sure to take quoting rules into consideration: https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-quotation-marks-in-parameters

**Comment by vllama** [comment]
I am not using any headers in this case 
the command I am running is
az webapp config set --subscription MySubscription -g MyResourceGroupName -n MyAppName --generic-configurations '{"vnetRouteAllEnabled": true}'

I think this is valid json : '{"vnetRouteAllEnabled": true}'
Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@vllama You need to pass json with escaped double quotes to make it work, like below -
` --generic-configurations '{\"vnetRouteAllEnabled\": true}'`

**Comment by vllama** [comment]
That seems to have fixed it.  Interesting that old scripts that worked without escaping " inside ' have stopped working.
