### ISSUE TITLE
aaz moudle fails to load because of empty directory

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#25878]
**Describe the bug**

aaz module starts failing because of empty dir. I don't know how that folder is created.
There is an empty dir in `src/azure-cli/azure/cli/command_modules/network/aaz/latest/network/cross_region_lb/address_pool/address`

I add `print(pkg)` in https://github.com/Azure/azure-cli/blob/fdffe2e71a7002d8bb8613e4e1ee0a3cd2ed5291/src/azure-cli-core/azure/cli/core/aaz/_command.py#L440
The `az network vnet -h --debug` raises this error:
```
<module 'azure.cli.command_modules.network.aaz.latest.network.asg' from 'c:\\users\\hanglei\\developer\\azure-cli\\src\\azure-cli\\azure\\cli\\command_modules\\network\\aaz\\latest\\network\\asg\\__init__.py'>
<module 'azure.cli.command_modules.network.aaz.latest.network.cross_region_lb' (<_frozen_importlib_external._NamespaceLoader object at 0x000002E2E08D6920>)>
cli.azure.cli.core: Error loading command module 'network': expected str, bytes or os.PathLike object, not NoneType
cli.azure.cli.core: Traceback (most recent call last):
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 256, in _update_command_table_from_modules
    module_command_table, module_group_table = _load_module_command_loader(self, args, mod)
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 1085, in _load_module_command_loader
    return _load_command_loader(loader, args, mod, 'azure.cli.command_modules.')
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 1067, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "c:\users\kk\developer\azure-cli\src\azure-cli\azure\cli\command_modules\network\__init__.py", line 39, in load_command_table
    load_aaz_command_table(
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\aaz\_command.py", line 376, in load_aaz_command_table
    _load_aaz_pkg(loader, profile_pkg, command_table, command_group_table, arg_str, fully_load)
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\aaz\_command.py", line 453, in _load_aaz_pkg
    _load_aaz_pkg(loader, sub_pkg, command_table, command_group_table, arg_str, fully_load)
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\aaz\_command.py", line 453, in _load_aaz_pkg
    _load_aaz_pkg(loader, sub_pkg, command_table, command_group_table, arg_str, fully_load)
  File "c:\users\kk\developer\azure-cli\src\azure-cli-core\azure\cli\core\aaz\_command.py", line 441, in _load_aaz_pkg
    pkg_path = os.path.dirname(pkg.__file__)
  File "C:\Users\kk\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 249, in dirname
    return split(p)[0]
  File "C:\Users\kk\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

After I delete this dir, az works again.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@kairu-ms for awareness
