### ISSUE TITLE
az webapp config ssl import fails with local variable 'cert_name' referenced before assignment

### ISSUE THREAD

**Issue by gaeguu** [Azure/azure-cli#25876]
## Describe the bug

**Command Name**
`az webapp config ssl import`

**Errors:**
```
Unable to verify Key Vault permissions.
You may need to grant Microsoft.Azure.WebSites service principal the Secret:Get permission
Find more details here: https://azure.github.io/AppService/2016/05/24/Deploying-Azure-Web-App-Certificate-through-Key-Vault.html
The command failed with an unexpected error. Here is the traceback:
local variable 'cert_name' referenced before assignment
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/commands.py", line 40, in _ex_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.46.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2828, in import_ssl_cert
    return client.certificates.create_or_update(name=cert_name, resource_group_name=resource_group_name,
UnboundLocalError: local variable 'cert_name' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
It fails locally on my machine and on github runner as well.

- _Put any pre-requisite steps here..._
- `az webapp config ssl import --resource-group {} --name {} --key-vault {} --key-vault-certificate-name {}`

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.46.0

Extensions:
azure-iot 0.21.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team
