### ISSUE TITLE
az keyvault key create -> No module named 'azure.keyvault.keys'

### ISSUE THREAD

**Issue by toraritte** [Azure/azure-cli#25949]
## Describe the bug

**Command Name**
`az keyvault key create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.keyvault.keys'
Traceback (most recent call last):
  File "/nix/store/1kmix8ml5555cjs9h2hklfz2racjhkld-python3.10-knack-0.10.1/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/nix/store/5rddklvb8fnrr2jx9xmnq2vb5k4dm19z-python3.10-azure-cli-core-2.44.1/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/nix/store/5rddklvb8fnrr2jx9xmnq2vb5k4dm19z-python3.10-azure-cli-core-2.44.1/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/nix/store/5rddklvb8fnrr2jx9xmnq2vb5k4dm19z-python3.10-azure-cli-core-2.44.1/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/nix/store/5rddklvb8fnrr2jx9xmnq2vb5k4dm19z-python3.10-azure-cli-core-2.44.1/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/nix/store/gm67m9sc6vf7nkkwlja4gm1a776h7rwv-python3.10-azure-cli-2.44.1/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 100, in keyvault_command_handler
    client = client_factory(command_args['cmd'].cli_ctx, command_args)
  File "/nix/store/gm67m9sc6vf7nkkwlja4gm1a776h7rwv-python3.10-azure-cli-2.44.1/lib/python3.10/site-packages/azure/cli/command_modules/keyvault/_client_factory.py", line 218, in data_plane_azure_keyvault_key_client
    from azure.keyvault.keys import KeyClient
ModuleNotFoundError: No module named 'azure.keyvault.keys'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault key create --name {} --vault-name {} --protection {} --ops {} {} --size {} --verbose`

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: PIP

azure-cli 2.44.1 *
```

**Comment by toraritte** [comment]
This seems to be Nix-related (see https://github.com/NixOS/nixpkgs/issues/167177), so closing it.
