### ISSUE TITLE
Unable to login using azure cli in Windows 10 machine.

### ISSUE THREAD

**Issue by gpat** [Azure/azure-cli#26023]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by gpat** [comment]
Detailed error message 
PS C:\> az login
The command failed with an unexpected error. Here is the traceback:
Not a boolean: trueaz
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 143, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 860, in _create_identity_instance
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 147, in getboolean
ValueError: Not a boolean: trueaz
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Comment by gpat** [comment]
will you please share the update

**Comment by jiasli** [comment]
The configuration `C:\Users\<username>\.azure\config` has been corrupted - `core.allow_broker` is set to `trueaz`. Please reset this value to its correct format:

```
az config set core.allow_broker=true
```
