### ISSUE TITLE
Problem az login with service principal

### ISSUE THREAD

**Issue by susta123** [Azure/azure-cli#26024]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Environment Summary
```
Linux-5.19.0-38-generic-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
ssh 1.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.

**Comment by slaffka-vlasov** [comment]
I run:
az login --service-principal -u <Id> -p<password> --tenant <id>
here the error output:
The command failed with an unexpected error. Here is the traceback:
allow_broker=True is only supported in PublicClientApplication
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 159, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 182, in login_with_service_principal
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line 132, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 555, in __init__
ValueError: allow_broker=True is only supported in PublicClientApplication
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by jiasli** [comment]
Closing this issue as no error message is provided.

**Comment by jiasli** [comment]
@slaffka-vlasov, we will address the `allow_broker=True is only supported in PublicClientApplication` error in https://github.com/Azure/azure-cli/issues/26052.
