### ISSUE TITLE
cli command :  "az bot show" on Faillure

### ISSUE THREAD

**Issue by Kabylone** [Azure/azure-cli#26037]
When I execute the CLI command az bot show -n botnaem -g rsourcegroupname --msbot, i get the error below : 

The command failed with an unexpected error. Here is the traceback:
'AzureBotService' object has no attribute 'config'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 363, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 361, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/botservice/custom.py", line 179, in get_bot
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/botservice/bot_json_formatter.py", line 94, in create_bot_json
AttributeError: 'AzureBotService' object has no attribute 'config'
**To Reproduce**

- Open cli command 
- az login
- set the subscription
- az bot show -n botnaem -g rsourcegroupname --msbot

**Expected behavior**

The expected is to have the detail of the bot service

**Environment summary**

- I'm using powershell
- CLI command : 
az bot show -n botnaem -g rsourcegroupname --msbot

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@Kabylone Thanks for reaching out to us and reporting this issue. I tried to run the below command at my end and it worked fine.

> **az bot show -g MyBotRG -n MyBotName --msbot false**

I am using 2.46.0 version of AzCLI. May I know the Azure CLI version you are using ? Awaiting your reply.

**Comment by Kabylone** [comment]
Hello,  thanks for the reply.
Here is my version of CLI : 
 "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}

**Comment by navba-MSFT** [comment]
@Kabylone I am using the same version at my end too and it worked.

```
az version
{
  "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  ```

Could you please let me know the value you had used for `--msbot` parameter ?

**Comment by Kabylone** [comment]
I use it without parameter. As it says in the documentation here :  https://learn.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-show

**Comment by Kabylone** [comment]
I tried it with parameters : 
**--msbot** true  : the same error
**--msbot** false : It works

Is it a new version or chages made ?
Thanks for the help !

**Comment by navba-MSFT** [comment]
@Kabylone Thanks for sharing the details. I was able to reproduce this issue at my end. I have filed the above PR which has the fix for this issue. It is currently under review.
