### ISSUE TITLE
Error executing az aks get-credentials command

### ISSUE THREAD

**Issue by amillion8** [Azure/azure-cli#26048]
Getting below error:

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /3e20ecb2-9cb0-4df1-ad7b-914e31dcdda4/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa029757340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa029757340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /3e20ecb2-9cb0-4df1-ad7b-914e31dcdda4/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa029757340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 27, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/_client_factory.py", line 19, in get_container_service_client
    return get_mgmt_service_client(cli_ctx, ResourceType.MGMT_CONTAINERSERVICE, subscription_id=subscription_id)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/client_factory.py", line 212, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id, resource=resource,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 334, in get_login_credentials
    credential = self._create_credential(account, client_id=client_id)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 592, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 203, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 39, in __init__
    super().__init__(client_id, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1525, in __init__
    super(PublicClientApplication, self).__init__(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 456, in __init__
    self.authority = Authority(
  File "/opt/az/lib/python3.10/site-packages/msal/authority.py", line 100, in __init__
    openid_config = tenant_discovery(
  File "/opt/az/lib/python3.10/site-packages/msal/authority.py", line 160, in tenant_discovery
    resp = http_client.get(tenant_discovery_endpoint, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /3e20ecb2-9cb0-4df1-ad7b-914e31dcdda4/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa029757340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@amillion8 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by amillion8** [comment]
There is a firewall at the company's network. I' ran nslookup login.microsoftonline.com from my personal laptop and got the address back with no error, but running it from the company's network I got an error:

My personal laptop:
===========================================================
>nslookup login.microsoftonline.com
Server:  UnKnown
Address:  198.51.100.1

Non-authoritative answer:
Name:    login.microsoftonline.com
Address:  20.190.155.66

My work laptop inside the network:
===========================================================
$ nslookup login.microsoftonline.com
net.c:536: probing sendmsg() with IP_TOS=b8 failed: Network is unreachable
;; connection timed out; no servers could be reached






Alex

**Comment by navba-MSFT** [comment]
@amillion8 Thanks for your reply. From your findings, its clear that the connection is being blocked at the firewall layer. This issue is outside of Azure CLI. Could you please check with your internal network administrators to whitelist the access to `login.microsoftonline.com` and port 443 ?

**Comment by navba-MSFT** [comment]
@amillion8 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by amillion8** [comment]
Hello,

Yes, I sent a request to network team about this issue. Can we have this ticket open for a little longer, or do you need to close it?

Alex
(847) 845-6940

**Comment by navba-MSFT** [comment]
@amillion8 I will keep this open for now and follow-up with you next week.

**Comment by navba-MSFT** [comment]
@amillion8 I wanted to do quick follow-up to check if you have received any updates from your internal networking team. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by amillion8** [comment]
Hello,

The issue has been resolved on our end, please close this item.

Thank you for your help!



Alex

**Comment by navba-MSFT** [comment]
@amillion8 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
