### ISSUE TITLE
az login: ValueError: allow_broker=True is only supported in PublicClientApplication

### ISSUE THREAD

**Issue by ghostx3** [Azure/azure-cli#26052]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
% az login --service-principal -u $spnid -p $spnsecret --tenant $tenantid
The command failed with an unexpected error. Here is the traceback:
allow_broker=True is only supported in PublicClientApplication
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 159, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 182, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 132, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/msal/application.py", line 555, in __init__
    raise ValueError("allow_broker=True is only supported in PublicClientApplication")
ValueError: allow_broker=True is only supported in PublicClientApplication
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback````

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az login --service-principal -u $spnid -p $spnsecret --tenant $tenantid

## Expected Behavior

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.47.0

Extensions:
azure-devops 0.26.0
log-analytics-solution 0.1.1
ssh 1.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vsuzdaltsev** [comment]
the same issue

**Comment by anelliaf** [comment]
Having the same issue:

(.venv) PS C:\python> az feedback
The command failed with an unexpected error. Here is the traceback:
Expected 1 module to load starting with 'azext_': got []
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 426, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 320, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 307, in _filter_modname
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 308, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**Comment by pacorreia** [comment]
Same stuff here with version 2.47 👎 

My stack trace is the same as OP.

Hope this get fixed ASAP, I guess I'll rollaback to previous version until a fix is  released

**Comment by jiasli** [comment]
If you turn on WAM with

```
az config set core.allow_broker=true
```

and then use service principal to login, you will see this `ValueError: allow_broker=True is only supported in PublicClientApplication` error.

This is because WAM doesn't support service principal. This issue has also been reported to the MSAL library: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/544

In a future version, we will make it more intelligent and avoid using WAM when service principal is used.

## Solution

If you are using service principal to login, please do not turn on WAM:

```
az config unset core.allow_broker
```

**Comment by jiasli** [comment]
@anelliaf, your error `AssertionError: Expected 1 module to load starting with 'azext': got []` is different from the `ValueError: allow_broker=True is only supported in PublicClientApplication` error. Your error is tracked by https://github.com/Azure/azure-cli/issues/25473.

**Comment by adeturner** [comment]
It fails when you have the requested settings. 

```bash
[Windows only] Starting in May 2023, Azure CLI will authenticate using the [Web Account Manager](https://learn.microsoft.com/windows/uwp/security/web-account-manager) (WAM) broker by default.

az config set core.allow_broker=true # fails
# az config set core.allow_broker=false # works
az account clear
az login
```

**Comment by baartch** [comment]
> > If you turn on WAM with
> > ```
> > az config set core.allow_broker=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then use service principal to login, you will see this `ValueError: allow_broker=True is only supported in PublicClientApplication` error.
> > This is because WAM doesn't support service principal. This issue has also been reported to the MSAL library: [AzureAD/microsoft-authentication-library-for-python#544](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/544)
> > In a future version, we will make it more intelligent and avoid using WAM when service principal is used.
> > ## Solution
> > If you are using service principal to login, please do not turn on WAM:
> > ```
> > az config unset core.allow_broker
> > ```
> 
> Its so funny ..this one way approach. if you are in ..you can't get out again #26788

For me it worked, switching it manually. If you type
```bash
az config get
```
you see where your config is located. On linux, I manually edited it with _nano_.
```bash
nano /home/<username>/.azure/config
```

simply comment the line _allow_broker_
```ini
[cloud]
name = AzureCloud

[core]
first_run = yes
#allow_broker = true
```
