### ISSUE TITLE
Serial-console fails for systems in eastus

### ISSUE THREAD

**Issue by msftvito** [Azure/azure-cli#26050]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az serial-console connect -n vmname -g vmresourcegroup

**Describe the bug**

az serial-console connect fails because the dictionary used for looking up region pairs doesn't have eastus. Seems like a big bug to slip through testing, but I do see the problem in the HEAD revision and has been there since the initial commit in 2022(https://github.com/Azure/azure-cli-extensions/blob/main/src/serial-console/azext_serialconsole/_arm_endpoints.py). Official Azure documentation lists the pair for eastus is westus: https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure

**To Reproduce**

az serial-console connect -n vmname -g vmresourcegroup for a VM in eastus

The command failed with an unexpected error. Here is the traceback:
'eastus'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/vito/.azure/cliextensions/serial-console/azext_serialconsole/custom.py", line 633, in connect_serialconsole
    vm_vmss_name, vmss_instanceid)
  File "/home/vito/.azure/cliextensions/serial-console/azext_serialconsole/custom.py", line 597, in check_resource
    vmss_instanceid)
  File "/home/vito/.azure/cliextensions/serial-console/azext_serialconsole/custom.py", line 735, in get_region_from_storage_account
    storage_account_region = get_storage_account_info(storage_account_url, scf)
  File "/home/vito/.azure/cliextensions/serial-console/azext_serialconsole/custom.py", line 750, in get_storage_account_info
    return ArmEndpoints.region_prefix_pairings[sa_result.location]
KeyError: 'eastus'
To open an issue, please run: 'az feedback'

**Expected behavior**

Expect to be connected to the serial console of the VM.

**Environment summary**

yum repo for RHEL8 based distros

**Additional context**

Fixed for you, literally one line:
 diff _arm_endpoints.py_orig _arm_endpoints.py_fixed 
17a18
>                               'eastus': 'westus',

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by msftvito** [comment]
Just checking to see if there have been any updates

**Comment by msftvito** [comment]
I tried to ask in the Github link but didn't get an acknowledgement, do I need to ask in a different venue?

**Comment by SaurabhSharma-MSFT** [comment]
@msftvito I am not able to reproduce this issue and able to connect to a linux vm on eastus using the cmdlet.
![image](https://user-images.githubusercontent.com/38112130/231658382-e330cd52-76ce-400b-8f39-6a3a22851c03.png)
Can you please provide the extension version you are using with your environment details? I have extension version "0.1.4" installed.

**Comment by msftvito** [comment]
After more testing, I have more info to add for repro - the VM needs to have a custom storage account for boot diagnostics, not the default managed storage account, otherwise get_storage_account_info will return None and skip the dictionary lookup:

def get_storage_account_info(storage_account_url, scf):
    from azext_serialconsole._arm_endpoints import ArmEndpoints

    if storage_account_url is not None:
        storage_account, storage_account_resource_group = parse_storage_account_url(storage_account_url, scf)
        if storage_account is not None:
            sa_result = scf.storage_accounts.get_properties(storage_account_resource_group, storage_account)
            if (sa_result is not None and
                    sa_result.network_rule_set is not None and
                    len(sa_result.network_rule_set.ip_rules) > 0):
                **return ArmEndpoints.region_prefix_pairings[sa_result.location]**
    return None

From my Windows Sandbox using the latest azure-cli+serial-console
PS C:\Users\WDAGUtilityAccount> az serial-console connect -n serialconsoletest -g serialconsole
>>
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\serial-console\azext_serialconsole\custom.py", line 631, in connect_serialconsole
    check_resource(cmd.cli_ctx, resource_group_name,
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\serial-console\azext_serialconsole\custom.py", line 595, in check_resource
    result, storage_account_region = get_region_from_storage_account(cli_ctx, resource_group_name, vm_vmss_name,
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\serial-console\azext_serialconsole\custom.py", line 734, in get_region_from_storage_account
    storage_account_region = get_storage_account_info(storage_account_url, scf)
  File "C:\Users\WDAGUtilityAccount\.azure\cliextensions\serial-console\azext_serialconsole\custom.py", line 745, in get_storage_account_info
    sa_result = scf.storage_accounts.get_properties(storage_account_resource_group, storage_account)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_09_01/operations/_storage_accounts_operations.py", line 1051, in get_properties
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_09_01/operations/_storage_accounts_operations.py", line 158, in build_get_properties_request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/_serialization.py", line 697, in url
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/_serialization.py", line 782, in serialize_data

**Comment by CraigWiand** [comment]
@Azure Serial Console ***@***.***> - looks like there is some feedback on a connection issue.  The arm_endpoints file referenced below does not directly relate to Azure paired regions, but rather used to avoid the storage account firewall in-region behavior:

        if storage_account is not None:
            sa_result = scf.storage_accounts.get_properties(storage_account_resource_group, storage_account)
            if (sa_result is not None and
                    sa_result.network_rule_set is not None and
                    len(sa_result.network_rule_set.ip_rules) > 0):
                return ArmEndpoints.region_prefix_pairings[sa_result.location]

That said, some of the pairing should be compared to those in the portal because they don't look quite right.  Additionally, if the region is not found in the pairings (e.g. eastus) then it should use the default ARM url, not fail.

The command failed with an unexpected error. Here is the traceback:
'eastus'

Thanks,
Craig

**Comment by CraigWiand** [comment]
Hi Craig,

Thanks for bringing this to our attention. We’ll look to resolve this issue soon.

Regards,

Harish



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Craig Wiand ***@***.***>
Sent: Thursday, April 20, 2023 8:31:34 AM
To: Azure Serial Console Team ***@***.***>
Cc: Azure/azure-cli ***@***.***>
Subject: RE: [Azure/azure-cli] Serial-console fails for systems in eastus (Issue #26050)


@Azure Serial Console ***@***.***> – looks like there is some feedback on a connection issue.  The arm_endpoints file referenced below does not directly relate to Azure paired regions, but rather used to avoid the storage account firewall in-region behavior:



        if storage_account is not None:

            sa_result = scf.storage_accounts.get_properties(storage_account_resource_group, storage_account)

            if (sa_result is not None and

                    sa_result.network_rule_set is not None and

                    len(sa_result.network_rule_set.ip_rules) > 0):

                return ArmEndpoints.region_prefix_pairings[sa_result.location]



That said, some of the pairing should be compared to those in the portal because they don’t look quite right.  Additionally, if the region is not found in the pairings (e.g. eastus) then it should use the default ARM url, not fail.



The command failed with an unexpected error. Here is the traceback:
'eastus'



Thanks,

Craig

**Comment by rguptar** [comment]
hi @msftvito, the serial console team does not actively track the azure-cli repo, can you cross post in github.com/microsoft/azserialconsole?

**Comment by msftvito** [comment]
I'll do that.
