### ISSUE TITLE
recovery from cli failed

### ISSUE THREAD

**Issue by sakibmas** [Azure/azure-cli#26083]
## Describe the bug

**Command Name**
`az backup restore restore-azurewl`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/_exception_handler.py", line 11, in backup_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_base.py", line 508, in restore_azure_wl
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_wl.py", line 618, in restore_azure_wl
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/backup/custom_help.py", line 459, in get_or_read_json
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup restore restore-azurewl -g {} -v {} --recovery-config {} --verbose`

## Environment Summary
```
Windows-10-10.0.20348-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0 *

Extensions:
alertsmanagement 0.2.2
billing-benefits 0.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by sakibmas** [comment]
The issue still same after upgrading the azure cli

**Comment by SaurabhSharma-MSFT** [comment]
@sakibmas How are you passing the recovery config value to and if you are passing recovery config value from an exported json file, then try adding using the command with @ along with the json file name.  For example - 
`az backup restore restore-azurewl --resource-group $resourceGroupName --vault-name $rvname --recovery-config @c:\workspace\recovery.json`
![image](https://user-images.githubusercontent.com/38112130/233488869-acda989c-2a22-41f2-8296-151c8c264c84.png)
Please let me know if you still see any problems.
