### ISSUE TITLE
Issue with list-ip-addresses

### ISSUE THREAD

**Issue by spheex** [Azure/azure-cli#26118]
## Describe the bug

**Command Name**
`az vm list-ip-addresses`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ipAddress'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/vm/custom.py", line 1436, in list_vm_ip_addresses
    'ipAddress': public_ip_address['ipAddress'],
KeyError: 'ipAddress'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm list-ip-addresses`

## Expected Behavior

Should show the IP addresses of the VMs but return an error.

## Environment Summary
```
Linux-5.14.0-1059-oem-x86_64-with-glibc2.31, Ubuntu 20.04.1 LTS (fossa-cory-tgl X59)
Python 3.10.10
Installer: DEB

azure-cli 2.47.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@spheex Could you please send the debug log to my email? My email address is Zhou.Xing@microsoft.com

**Comment by spheex** [comment]
I noticed that v2.47.0 was installed yesterday and that the problem arose after that.
I downgraded to v2.46.0 and the issue disappeared.

**Comment by zhoxing-ms** [comment]
> I noticed that v2.47.0 was installed yesterday and that the problem arose after that.
I downgraded to v2.46.0 and the issue disappeared.

This issue should be related to PR #25805. When dropping the network SDK, some related code logic was modified here.  @kairu-ms  Could you please help take a look at this issue when you are free?
