### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback:

### ISSUE THREAD

**Issue by sanjaykulkarni04** [Azure/azure-cli#26110]
Hi,

$env:AZURE_DEVOPS_EXT_PAT = '<Cannot share>'
az artifacts universal download --organization "<URL>" --feed "upkgs" --name "<pkg name>" --version "1.0.0-pre00025" --path "C:\temp"

When I run the above download PowerShell command (windows 10 OS) I receive the below error. Can someone please help me?

**The command failed with an unexpected error. Here is the traceback:
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):**
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
718, in _run_job
  File "C:\Users\sa_ampbuild\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, i
n azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.p
y", line 121, in handler
  File "C:\Users\sa_ampbuild\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in dow
nload_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\build\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in dow
nload_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\build\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run
_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\build\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 74, in ru
n
    self.start(command_args, env)
  File "C:\Users\build\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 33, in st
art
    self._proc = subprocess.Popen(
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

Command **az --version** outcome -->

PS C:\Users\sa_ampbuild> az --version
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\build\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by razavistag** [comment]
Please run the following command in Powershell on your workstation:
`az extension update --name ssh`

**this solves your issue**
