### ISSUE TITLE
Error az network dns record-set txt update

### ISSUE THREAD

**Issue by danieldemoraisgurgel** [Azure/azure-cli#26158]
**Related command**
az network dns record-set txt update -g <resource-group> -z <dns-zone> -n <name> --set txtRecords[0].value=value>

I would like to update the existing DNS TXT entry to a new value:

**Current entry:**
`_acme-challenge.wpgurgel.     TXT     3600     FraO_zWySUBG3rUxiXsEn47qTkqQDpwoQKrOxV9PArE`

**Updated entry:** 
`_acme-challenge.wpgurgel.     TXT     3600     ABC123`

**Command used:**
`az network dns record-set txt update -g <resource-group> -z <zone-dns> -n _acme-challenge.wpgurgel --set txtRecords[0].value=ABC123`

After running the command replacing the resource group and dns zone values, we received the following error:
```
The command failed with an unexpected error. Here is the traceback:
Refuse str type as a valid iter type.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/dns/v2018_05_01/operations/_record_sets_operations.py", line 201, in create_or_update
    body_content = self._serialize.body(parameters, 'RecordSet')
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 631, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 483, in _serialize
    return self.serialize_data(
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 787, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 574, in _serialize
    raise err
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 782, in serialize_data
    raise err   # don't rewrap as SerializationError
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 777, in serialize_data
    return self.serialize_type[iter_type](
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 867, in serialize_iter
    raise err
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 864, in serialize_iter
    serialized.append(self.serialize_data(d, iter_type, **kwargs))
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 787, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 574, in _serialize
    raise err
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 782, in serialize_data
    raise err   # don't rewrap as SerializationError
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 777, in serialize_data
    return self.serialize_type[iter_type](
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 856, in serialize_iter
    raise SerializationError("Refuse str type as a valid iter type.")
azure.core.exceptions.SerializationError: Refuse str type as a valid iter type.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thorker** [comment]
Try to set .value[0]

`# az network dns record-set txt update -g <resource-group> -z <zone-dns> -n _acme-challenge.wpgurgel --set txtRecords[0].value[0]=ABC123`

**Comment by gmuth** [comment]
when trying to update an existing txt record using az cli 2.56 it looks good for me:
`az network dns record-set txt update -g <group> -z <zone> -n <name> --set txt_records[0].value[0]=foo`

However I am unable to set a value containing quotes, because az-cli is internally manipulates the value.
e.g. "a=1 b=2" is transformed into "a=1b=1" which can not be processed by dns-sd clients.

```
(make sure your shell does not mangle quotes either!)
az network dns record-set txt update -g ipp -z sendletters.online -n send1._ipp._tcp --set txt_records[0].value[0]='"a=1" "b=1"'

"TXTRecords": [
    {
      "value": [
        "a=1b=1"
      ]
    }
  ]
```
