### ISSUE TITLE
unable to execute az commands

### ISSUE THREAD

**Issue by iammahi12** [Azure/azure-cli#26165]
## Describe the bug

**Command Name**
`az vm list-ip-addresses`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 518, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/command_modules/vm/__init__.py", line 47, in load_arguments
    load_arguments(self, command)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/command_modules/vm/_params.py", line 36, in load_arguments
    StorageAccountTypes = self.get_models('StorageAccountTypes')
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/__init__.py", line 765, in get_models
    return get_sdk(self.cli_ctx, resource_type, *attr_args, mod='models', operation_group=operation_group)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/profiles/__init__.py", line 91, in get_sdk
    return _sdk_get_versioned_sdk(cli_ctx.cloud.profile, resource_type, *attr_args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/profiles/_shared.py", line 630, in get_versioned_sdk
    sdk_path = get_versioned_sdk_path(api_profile, resource_type, operation_group)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/profiles/_shared.py", line 622, in get_versioned_sdk_path
    api_version = getattr(api_version, operation_group)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/profiles/_shared.py", line 417, in __getattr__
    self._resolve()
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/profiles/_shared.py", line 404, in _resolve
    for operation_group_name, operation_type in self._client_type.__dict__.items():
AttributeError: 'NoneType' object has no attribute '__dict__'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list-ip-addresses --query {} --subscription {} -o {}`

## Environment Summary
```
Linux-3.10.0-1160.83.1.el7.x86_64-x86_64-with-glibc2.29, Ubuntu 20.04.1 LTS
Python 3.8.5
Installer: PIP

azure-cli 2.29.1 *

Extensions:
account 0.2.5

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
