### ISSUE TITLE
Unexpected client side error while running the update instance protection command on VMSS flex instances

### ISSUE THREAD

**Issue by mannanbansal** [Azure/azure-cli#26164]
## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'image_reference'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 191, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 414, in cached_get
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 409, in _get_operation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 3472, in get_vmss_modified
AttributeError: 'NoneType' object has no attribute 'image_reference'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update -n {} -g {} --instance-id {} --protect-from-scale-in {}`

## Expected Behavior
We expect the API to hit the controller on server side but the command is failing with client side error. This is the error expected from CLI:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/110012826/232452861-bf972d86-c2d5-4e55-9828-89d88b3e2470.png">

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
azure-devops 0.25.0
cloud-service 0.2.0
playfab 0.1.0
quota 0.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
PS: This issue is for VMSS flex VMs only not for VMSS uniform

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
