### ISSUE TITLE
`az vm extension set` crashes

### ISSUE THREAD

**Issue by kim0** [Azure/azure-cli#2616]
```
az vm extension set -n IaaSAntimalware --publisher Microsoft.Azure.Security -g TestDesktop_RG --vm-name vmAWB10Test09

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 358, in _execute_command
    raise ex
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 353, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 861, in set_extension
    instance_name = _get_extension_instance_name(vm.instance_view, publisher, vm_extension_name)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 712, in _get_extension_instance_name
    ext = next((x for x in instance_view.extensions
StopIteration
```

**Comment by yugangw-msft** [comment]
I will fix it today.

**Comment by EricJizbaMSFT** [comment]
@yugangw-msft I also ran into this issue, but I'm not familiar with how the cli is released. Do I have to use a nightly build? Will this be included in a more official 'release' sometime soon?

**Comment by yugangw-msft** [comment]
We plan to have a release early next week including this fix.

**Comment by EricJizbaMSFT** [comment]
Awesome, thanks!
