### ISSUE TITLE
az rest times out with microsoft graph

### ISSUE THREAD

**Issue by dayadam** [Azure/azure-cli#26183]
## Describe the bug

It first says 

"Can't derive appropriate Azure AD resource from --url to acquire an access token. If access token is required, use --resource to specify the resource" and then timesout. graph.windows.com is listed in `az cloud show --query endpoints` for me. 

# How do I find the microsoft's graph's resource to pass through to the rest command? 

**Command Name**
`az rest`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='graph.windows.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/servicePrincipals?api-version=1.6&$filter=appId%20eq%20'04b07795-8ddb-461a-bbee-02f9e1bf7b46' (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0422D9A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 174, in _new_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 96, in create_connection
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 358, in connect
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0422D9A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graph.windows.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/servicePrincipals?api-version=1.6&$filter=appId%20eq%20'04b07795-8ddb-461a-bbee-02f9e1bf7b46' (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0422D9A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 23, in rest_call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 959, in send_raw_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='graph.windows.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/servicePrincipals?api-version=1.6&$filter=appId%20eq%20'04b07795-8ddb-461a-bbee-02f9e1bf7b46' (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0422D9A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --url {} --headers {}`
-  `az rest --method get --url "https://graph.windows.com/72f988bf-86f1-41af-91ab-2d7cd011db47/servicePrincipals?api-version=1.6&$filter=appId eq '04b07795-8ddb-461a-bbee-02f9e1bf7b46'" --headers x-ms-effective-locale=en.en-us`

## Expected Behavior
Recieve info 
## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@dayadam 
You can use `https://graph.microsoft.com` instead of using `https://graph.windows.com` in az rest get method.  Please try to use the below cmdlet on command prompt. I have checked this and it works fine for me-
`az rest --method get --url "https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appId eq '7620cb76-ed03-445a-a993-f8e5866f472e'"`
Also, make sure that you are logged in to your subscription using `az login` on command prompt.  
Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment]
@dayadam Please let us know if you have any questions. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@dayadam We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
