### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/home/tej/.azure/versionCheck.json'

### ISSUE THREAD

**Issue by tejkonday** [Azure/azure-cli#26205]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/tej/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/feedback/custom.py", line 589, in handle_feedback
    show_updates_available(new_line_before=True)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 490, in show_updates_available
    VERSIONS[_VERSION_CHECK_TIME] = str(datetime.datetime.now())
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_session.py", line 75, in __setitem__
    self.save_with_retry()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_session.py", line 65, in save_with_retry
    self.save()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_session.py", line 54, in save
    with open(self.filename, 'w', encoding=self._encoding) as f:
OSError: [Errno 30] Read-only file system: '/home/tej/.azure/versionCheck.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --role {} --scopes {} --sdk-auth`

## Environment Summary
```
Linux-5.4.0-1106-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.47.0

Extensions:
ai-examples 0.2.5
ml 2.15.0
ssh 1.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
This is a known issue of Cloud Shell. Please see https://github.com/Azure/azure-cli/issues/13855#issuecomment-652793995.
