### ISSUE TITLE
az upgrade fails on init extension

### ISSUE THREAD

**Issue by BulldogCTISolutions** [Azure/azure-cli#26202]
## Describe the bug

Same as Issues #21871 and #23195   .  Running az upgrade fails on doing 'init' extension.

**Command Name**
`az upgrade`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Command '['az', 'version', '-o', 'json']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/util/custom.py", line 157, in upgrade_version
  File "subprocess.py", line 421, in check_output
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['az', 'version', '-o', 'json']' returned non-zero exit status 1.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.47.0

Extensions:
init 0.1.0
interactive 0.4.5
spring-cloud 3.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by bebound** [comment]
Seems the upgrade is success. It fails to run `az version -o json`.
What's the output of this command?

https://github.com/Azure/azure-cli/blob/21266e02457263420b62fba1c529f69e28852414/src/azure-cli/azure/cli/command_modules/util/custom.py#L157

**Comment by BulldogCTISolutions** [comment]
C:\Users\Jay>az version -o json
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "init": "0.1.0",
    "interactive": "0.4.5",
    "spring-cloud": "3.1.5"
  }
}

The process should be updating 'interactive' and 'spring-cloud', but it fails with the message in the log attached.
[2023-04-19.11-57-28.upgrade.5080.log](https://github.com/Azure/azure-cli/files/11287777/2023-04-19.11-57-28.upgrade.5080.log)

**Comment by bebound** [comment]
The error log file contains same info as the issue.
Since you can run `az version -o json`. I don't see why it fails.

If you can repro it, kindly attach the full log of `az upgrade --all --debug`

**Comment by BulldogCTISolutions** [comment]
I had this in my terminal buffer
[2023-04-21.08-09-30.upgrade.17556.txt](https://github.com/Azure/azure-cli/files/11297295/2023-04-21.08-09-30.upgrade.17556.txt)

**Comment by BulldogCTISolutions** [comment]
So, I executed these commands:

C:\Users\Jay>az extension update --name interactive
 - Installing ..
C:\Users\Jay>az extension update --name spring-cloud
 - Installing ..
C:\Users\Jay>az extension update --name init
Latest version of 'init' is already installed.

C:\Users\Jay>az version -o json
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "init": "0.1.0",
    "interactive": "0.4.6",
    "spring-cloud": "3.1.8"
  }
}

I think in the future, I'll just do these manually.  If you are able to find out why `az upgrade` doesn't work on this machine, kindly let me know.

**Comment by BulldogCTISolutions** [comment]
issue resolved with using a different command.
