### ISSUE TITLE
AZ ACR login error

### ISSUE THREAD

**Issue by thebinarycode** [Azure/azure-cli#26212]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
The login server endpoint suffix '.azurecr.io' is automatically omitted.
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/custom.py", line 290, in acr_login
    login_server, username, password = get_login_credentials(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 463, in get_login_credentials
    return _get_credentials(cmd,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 344, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/_utils.py", line 109, in get_registry_by_name
    resource_group_name = get_resource_group_name_by_registry_name(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/_utils.py", line 88, in get_resource_group_name_by_registry_name
    arm_resource = _arm_get_resource_by_name(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/acr/_utils.py", line 43, in _arm_get_resource_by_name
    result = get_resources_in_subscription(cli_ctx, resource_type)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/parameters.py", line 138, in get_resources_in_subscription
    return list(rcf.resources.list(filter=filter_str))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 492, in resources
    raise ValueError("API version {} does not have operation group 'resources'".format(api_version))
ValueError: API version 2022-09-01 does not have operation group 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 50, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 36, in cli_main
    return cli.invoke(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 245, in invoke
    exit_code = self.exception_handler(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 127, in exception_handler
    return handle_exception(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/util.py", line 65, in handle_exception
    from msal_extensions.persistence import PersistenceError
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az acr login -n {}`

## Environment Summary
```
Linux-5.15.0-1035-azure-x86_64-with-glibc2.10, Ubuntu 20.04.6 LTS
Python 3.8.5
Installer: PIP

azure-cli 2.47.0

Extensions:
ml 2.15.1

Dependencies:
msal 1.21.0
azure-mgmt-resource 21.2.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thebinarycode** [comment]
Hi Team, any update/fix for this issue would be highly appreciated

**Comment by sebastko** [comment]
Also running into this issue on a newly created AzureML Compute Instance (and it worked in the past). Is there a workaround available - perhaps downgrading some package?

**Comment by SaurabhSharma-MSFT** [comment]
@thebinarycode This looks like known issue of ml extension conflict as mentioned over [here](https://github.com/Azure/azure-cli/issues/20476#issuecomment-1007131837) and it recommend installing the Azure CLI DEB package, but if you have to use pip, we recommend installing to a virtual environment.
![image](https://user-images.githubusercontent.com/38112130/235535521-913382f5-4166-4252-a4a1-981c90768dd7.png)
Please let us know if this resolves your issue.
