### ISSUE TITLE
Any command in `az container` fails

### ISSUE THREAD

**Issue by jonboh** [Azure/azure-cli#26211]
## Describe the bug
Any interaction with `az container` fails

**Command Name**
`az container`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'ContainerGroupPriority' from 'azure.mgmt.containerinstance.models' (/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/mgmt/containerinstance/models/__init__.py)
Traceback (most recent call last):
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib64/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.10/argparse.py", line 2075, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.10/argparse.py", line 2100, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/parser.py", line 157, in error
    recommender.set_help_examples(self.get_examples(self.prog))
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/parser.py", line 198, in get_examples
    return self.cli_help.get_examples(command,
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/_help.py", line 185, in get_examples
    else self.group_help_cls(self, delimiters, parser)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/knack/help.py", line 253, in __init__
    child.load(options)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/_help.py", line 296, in load
    loader.versioned_load(self, options)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/_help_loaders.py", line 154, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/knack/help.py", line 198, in load
    description = getattr(options, 'description', None)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/knack/parser.py", line 241, in __getattribute__
    self.description = self._description() \
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 133, in description_loader
    op = self.get_op_handler(self.op_path)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 34, in <module>
    from azure.mgmt.containerinstance.models import (AzureFileVolume, Container, ContainerGroup, ContainerGroupNetworkProtocol,
ImportError: cannot import name 'ContainerGroupPriority' from 'azure.mgmt.containerinstance.models' (/home/jonvolt/lib/azure-cli/lib/python3.10/site-packages/azure/mgmt/containerinstance/models/__init__.py)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback````
```

## To Reproduce:
Just using `az container` will generate the error. 

- _Put any pre-requisite steps here..._
- `az container`

## Environment Summary
```
Linux-6.2.11-arch1-1-x86_64-with-glibc2.37, Arch Linux
Python 3.10.10
Installer: 

azure-cli 2.47.0
```
## Additional Context
Installed with this command:
`curl -L https://aka.ms/InstallAzureCli | bash` from [the docs](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@jonboh Can you please try upgrading you Azure CLI module if that helps fixing this issue.

**Comment by jonboh** [comment]
@SaurabhSharma-MSFT , sure, I've uninstalled the cli and run the script installation again:
```bash 
$ az --version
azure-cli 2.48.1
```
I've just tried running `azure container list` and it works. I cannot test right now any further but the issue seems to be solved (before, any interaction with `azure container` failed).
Thanks!!
