### ISSUE TITLE
az network dns record-set a add-record 'NoneType' object has no attribute 'standard_medium'

### ISSUE THREAD

**Issue by myautomaton** [Azure/azure-cli#26215]
## Describe the bug

**Command Name**
`az network dns record-set a add-record`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 508, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/network/__init__.py", line 50, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3.10/site-packages/azure/cli/command_modules/network/_params.py", line 91, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns record-set a add-record -g {} -z domain.name -n demo1 -a 10.1.2.20`

## Environment Summary
```
Linux-6.2.8-1-default-x86_64-with-glibc2.37, openSUSE Tumbleweed
Python 3.10.10
Installer: PIP

azure-cli 2.46.0 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
