### ISSUE TITLE
Az bicep publish throws NotFound Exception Error on Microsoft hosted build-agent (Azure Pipelines)

### ISSUE THREAD

**Issue by m-soltani** [Azure/azure-cli#26256]
**Related command**
`az bicep publish`

**Describe the bug**
2023-04-25T19:13:35.9218378Z Bicep CLI version 0.16.2 (de7fdd2b33)
2023-04-25T19:13:35.9218763Z 
2023-04-25T19:13:37.2827047Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-04-25T19:13:37.2827792Z ERROR: [Errno 2] No such file or directory: '/home/vsts/work/_temp/.azclitask/bin/bicep'
2023-04-25T19:13:37.2828066Z Traceback (most recent call last):
2023-04-25T19:13:37.2828413Z   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
2023-04-25T19:13:37.2828986Z     cmd_result = self.invocation.execute(args)
2023-04-25T19:13:37.2829366Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
2023-04-25T19:13:37.2829630Z     raise ex
2023-04-25T19:13:37.2829995Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2023-04-25T19:13:37.2830296Z     results.append(self._run_job(expanded_arg, cmd_copy))
2023-04-25T19:13:37.2830679Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
2023-04-25T19:13:37.2830943Z     result = cmd_copy(params)
2023-04-25T19:13:37.2831313Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
2023-04-25T19:13:37.2831594Z     return self.handler(*args, **kwargs)
2023-04-25T19:13:37.2831965Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2023-04-25T19:13:37.2832251Z     return op(**command_args)
2023-04-25T19:13:37.2832642Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 3779, in publish_bicep_file
2023-04-25T19:13:37.2832961Z     if bicep_version_greater_than_or_equal_to(minimum_supported_version):
2023-04-25T19:13:37.2833392Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 202, in bicep_version_greater_than_or_equal_to
2023-04-25T19:13:37.2833720Z     installed_version = _get_bicep_installed_version(installation_path)
2023-04-25T19:13:37.2834149Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 273, in _get_bicep_installed_version
2023-04-25T19:13:37.2834867Z     installed_version_output = _run_command(bicep_executable_path, ["--version"])
2023-04-25T19:13:37.2835272Z   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 311, in _run_command
2023-04-25T19:13:37.2835616Z     process = subprocess.run([rf"{bicep_installation_path}"] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
2023-04-25T19:13:37.2835916Z   File "/opt/az/lib/python3.10/subprocess.py", line 503, in run
2023-04-25T19:13:37.2836176Z     with Popen(*popenargs, **kwargs) as process:
2023-04-25T19:13:37.2836550Z   File "/opt/az/lib/python3.10/subprocess.py", line 971, in __init__
2023-04-25T19:13:37.2836825Z     self._execute_child(args, executable, preexec_fn, close_fds,
2023-04-25T19:13:37.2837101Z   File "/opt/az/lib/python3.10/subprocess.py", line 1847, in _execute_child
2023-04-25T19:13:37.2837377Z     raise child_exception_type(errno_num, err_msg, err_filename)
2023-04-25T19:13:37.2837766Z FileNotFoundError: [Errno 2] No such file or directory: '/home/vsts/work/_temp/.azclitask/bin/bicep'
2023-04-25T19:13:37.2838143Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-04-25T19:13:37.2838409Z To open a new issue, please run `az feedback`
2023-04-25T19:13:46.3159228Z ##[error]Script failed with exit code: 1

**Environment summary**
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az457-441'
Current agent version: '3.220.0'
azure-cli                         2.47.0 *

core                              2.47.0 *
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Mar 31 2023, 09:26:59) [GCC 11.3.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by GeraldGoldstein** [comment]
already on latest makes no difference

PS /workspaces/CARML> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.48.1
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
PS /workspaces/CARML>

**Comment by GeraldGoldstein** [comment]
in ado hosted agent, uppgrading az cli fixed it.

Starting: Publish user assigned identity module.
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.217.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
azure-cli                         2.47.0 *

core                              2.47.0 *
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0
WARNING: You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Mar 31 2023, 09:26:59) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
Setting active cloud to: AzureCloud
/usr/bin/az cloud set -n AzureCloud
/usr/bin/az login --service-principal -u *** --password=*** --tenant xxxxx --allow-no-subscriptions
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "xxxxx",
    "id": "xxxx",
    "isDefault": true,
    "managedByTenants": [],
    "name": "xxxx",
    "state": "Enabled",
    "tenantId": "xxxx",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
/usr/bin/az account set --subscription xxxx
/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1682470212146.sh
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.47.0. Latest version available is 2.48.1.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
ERROR: No tty available.
Please run command with --yes.
WARNING: The configuration value of bicep.use_binary_from_path has been set to 'false'.
Installing Bicep CLI v0.16.2...
Successfully installed Bicep CLI to "/home/vsts/work/_temp/.azclitask/bin/bicep".

next pipeline task ....

]
/usr/bin/az account set --subscription xxxxx
/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1682470222372.sh
/usr/bin/az account clear
Finishing: Publish user assigned identity module.

**Comment by abunnyuk** [comment]
Please see https://github.com/microsoft/azure-pipelines-tasks/issues/17956 for more details of the root cause and a workaround.

**Comment by PramodValavala-MSFT** [comment]
@m-soltani @GeraldGoldstein @abunnyuk Based on the logs, looks like the `bicep` CLI is not present but is being expected to be. This is a bug when running the `publish` command first. We will work up a PR to address this.

In the meantime, the fix would be to install the `bicep` CLI using the `az bicep install` command first.

**Comment by PramodValavala-MSFT** [comment]
@m-soltani Apologies for the delay here! There were a few other commands that had the same issue and created a PR to fix them all.

**Comment by m-soltani** [comment]
@PramodValavala-MSFT : It seems that your fix is not working fully. I got the chance to run the publish command again without using the workaround, now I have no problem with bicep itself but I receive an error like
```c#
/home/vsts/work/_temp/azureclitaskscript1684279681575_inlinescript.ps1 : ERROR: The command failed with an unexpected error. Here is the traceback:
At /home/vsts/work/_temp/azureclitaskscript1684279681577.ps1:3 char:1
+ . '/home/vsts/work/_temp/azureclitaskscript1684279681575_inlinescript …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,azureclitaskscript1684279681575_inlinescript.ps1

```
And the traceback is not being logged. 

Other information related to the issue:

azure-cli                         2.48.1

core                              2.48.1
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Apr 25 2023, 04:23:10) [GCC 11.3.0]

**Comment by PramodValavala-MSFT** [comment]
@m-soltani Sorry to hear that! Without any logs, it would be impossible to know what is going wrong. Since the original issue here has been fixed, could you create a new issue for this and share more details like the exact commands in the inline script, etc.
