### ISSUE TITLE
Az 2.48.1 stopped creating Service Bus with location parameter.

### ISSUE THREAD

**Issue by EdneiMonteiro** [Azure/azure-cli#26272]
## Describe the bug

**Command Name**
`az servicebus namespace create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'Request' from partially initialized module 'requests.models' (most likely due to a circular import) (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\models.pyc)
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 707, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1156, in _is_poller
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 686, in poller_classes
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/__init__.py", line 28, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/azure_configuration.py", line 34, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/__init__.py", line 28, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/configuration.py", line 37, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 52, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/__init__.py", line 135, in <module>
ImportError: cannot import name 'Request' from partially initialized module 'requests.models' (most likely due to a circular import) (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\models.pyc)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus namespace create --name ANY-VALID-NAME --sku Premium --resource-group MY-RG --location brazilsouth`

## Expected Behavior
Service successfully created. Just like with Az Cli 2.47.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1

Extensions:
resource-graph 2.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context

I found that by **removing** the **location** parameter the command works again.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kairu-ms** [comment]
It's the cpython issue. This PR fixes it: [gh-91351: Fix some bugs in importlib handling of re-entrant imports by exarkun · Pull Request #94504 · python/cpython (github.com)](https://github.com/python/cpython/pull/94504)

**Comment by kairu-ms** [comment]
We will update the packaged python version in the next release.

**Comment by kairu-ms** [comment]
It will be May 23

> Thanks for the workaround @kairu-ms. Is there an expected time for the next release?

**Comment by EdneiMonteiro** [comment]
> The current workaround is adding `--no-wait` which will bypass the polling functions. And call `xxxx wait` command

The workaround didn't work with the service bus. The error doesn't occur, but the command doesn't create the service bus. Removing the **--location** parameter allows creation without the --no-wait.

**Comment by mbashtovaya** [comment]
> It will be May 23
> 
> > Thanks for the workaround @kairu-ms. Is there an expected time for the next release?

that is a very long time to get a fix. considering many if not all commands are broken by this, can you at least remove the broken release?

**Comment by 5FEKO** [comment]
Leaving out the location parameter worked for namespace create , however it did not work for 
az servicebus namespace delete
, which throws the same exception.

**Comment by dazinator** [comment]
Great.. broken deployments. Service Bus is being moved to the top of my "move away from this technology" list! Any news on a fix?

**Comment by kairu-ms** [comment]
Sorry for the trouble. The fix will be included in the May 23th release. 
There is another workaround, which is to disable the command index using the "AZURE_CORE_USE_COMMAND_INDEX=False" environment variable. It can import requests module in main thread but it will slow down command execution time.

**Comment by fvalencia12** [comment]
Having the same issue with Log analytics, having to wait for a patch for this long is really not acceptable. Why can't this be released as a patch ASAP?

**Comment by fvalencia12** [comment]
> The current workaround is adding `--no-wait` which will bypass the polling functions. And call `xxxx wait` command

How does this help? In our devops process we depend on the previous resource to be created so things work. If we skip the wait, the next task just errors out as it doesn't have the dependencies met. This is not a workaround that is valid by any means.

**Comment by dazinator** [comment]
@fvalencia12 [this other](https://github.com/Azure/azure-cli/issues/26272#issuecomment-1534158361) workaround worked for me

**Comment by fvalencia12** [comment]
> Sorry for the trouble. The fix will be included in the May 23th release. There is another workaround, which is to disable the command index using the "AZURE_CORE_USE_COMMAND_INDEX=False" environment variable. It can import `requests` module in main thread but it will slow down command loading time.

I'm still having this issue? Did the release go out?

**Comment by TimJongerius** [comment]
Same for me. When is this going to be fixed? It's breaking our release pipeline. When will the fix be available on Azure DevOps hosted agents?

**Comment by PiotrDabrowskey** [comment]
> Did the release go out?

Yes it did. It was released yesterday and can confirm it fixed the problem for me.

> When is this going to be fixed?

It's already fixed.

**Comment by fvalencia12** [comment]
> > Did the release go out?
> 
> Yes it did. It was released yesterday as [2.49.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.49.0) and can confirm it fixed the problem for me.
> 
> > When is this going to be fixed?
> 
> It's already fixed.

Are you using a hosted agent? I still see 20230507.1 as the image version.

![image](https://github.com/Azure/azure-cli/assets/70413619/accbf93a-ca13-418a-85ce-63aabf2c21ce)

**Comment by CarlosSardo** [comment]
FYI, as of today, ubuntu-latest (non pre-release) is still https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.220.2. Meaning that it still uses AzureCLI (2.220.0), with this issue.

**Comment by CarlosSardo** [comment]
Issue seems to be solved for ubuntu-latest. Thanks!

**Comment by CarlosSardo** [comment]
Issue seems to solved for ubuntu-latest. Thanks!

**Comment by fvalencia12** [comment]
It is solved for me as well! We use the Azure CLI for a lot of our pipelines, it is crazy to think that this can be broken in the hosted agent for weeks, this has been broken for over a month. There has to be better unit test and system tests to prevent this from happening.
