### ISSUE TITLE
Serviceconnector-passwordless fails to install.

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#26284]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```
az webapp connection create sql
-g <your-resource-group>
-n <your-app-service-name>
--tg <your-database-server-resource-group>
--server <your-database-server-name>
--database <your-database-name>
--system-identity
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

```
$ bash create-service-connector-connection-diberry.sh
cli.knack.cli: Command arguments: ['webapp', 'connection', 'create', 'sql', '-g', 'azure-sql-passwordless-diberry', '-n', 'azure-sql-passwordless-diberry', '--tg', 'diberry-keep', '--server', 'mysqlserver-diberry', '--database', 'mySampleDatabase', '--system-identity', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01C28100>, <function OutputProducer.on_global_arguments at 0x01D93F58>, <function CLIQuery.on_global_arguments at 0x01DBBB20>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'webapp': ['azure.cli.command_modules.appservice', 'azure.cli.command_modules.serviceconnector']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: appservice                0.341        66       239
cli.azure.cli.core: serviceconnector          0.103         4        39
cli.azure.cli.core: Total (2)                 0.444        70       278
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 69 groups, 278 commands.
cli.azure.cli.core: Could not find a match in the command or command group table for 'webapp connection create sql'. The index may be outdated.
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.013        28       116
cli.azure.cli.core: acs                       0.072         8        53
cli.azure.cli.core: advisor                   0.008         3         6
cli.azure.cli.core: ams                       0.018        20        90
cli.azure.cli.core: apim                      0.023         9        50
cli.azure.cli.core: appconfig                 0.010         7        33
cli.azure.cli.core: appservice                0.012        66       239
cli.azure.cli.core: aro                       0.201         1         7
cli.azure.cli.core: backup                    0.019        15        55
cli.azure.cli.core: batch                     0.099        31        92
cli.azure.cli.core: batchai                   0.015        10        30
cli.azure.cli.core: billing                   0.036        19        52
cli.azure.cli.core: botservice                0.024        12        42
cli.azure.cli.core: cdn                       0.014        39       132
cli.azure.cli.core: cloud                     0.008         1         7
cli.azure.cli.core: cognitiveservices         0.006         8        30
cli.azure.cli.core: config                    0.005         2         7
cli.azure.cli.core: configure                 0.007         3         9
cli.azure.cli.core: consumption               0.007         8         9
cli.azure.cli.core: container                 0.009         1        11
cli.azure.cli.core: cosmosdb                  0.021        47       167
cli.azure.cli.core: databoxedge               0.013         5        27
cli.azure.cli.core: deploymentmanager         0.006         7        30
cli.azure.cli.core: dla                       0.010        23        62
cli.azure.cli.core: dls                       0.008         7        41
cli.azure.cli.core: dms                       0.007         3        22
cli.azure.cli.core: eventgrid                 0.009        18        61
cli.azure.cli.core: eventhubs                 0.014        16        57
cli.azure.cli.core: extension                 0.004         1         7
cli.azure.cli.core: feedback                  0.003         1         1
cli.azure.cli.core: find                      0.007         1         1
cli.azure.cli.core: hdinsight                 0.011         8        39
cli.azure.cli.core: interactive               0.002         1         1
cli.azure.cli.core: iot                       0.045        16        71
cli.azure.cli.core: keyvault                  0.020        20       122
cli.azure.cli.core: kusto                     0.010         3        14
cli.azure.cli.core: lab                       0.013        11        34
cli.azure.cli.core: managedservices           0.008         3         8
cli.azure.cli.core: maps                      0.010         5        13
cli.azure.cli.core: marketplaceordering       0.031         1         2
cli.azure.cli.core: monitor                   0.033        32       133
cli.azure.cli.core: natgateway                0.009         3         6
cli.azure.cli.core: netappfiles               0.016        13        56
cli.azure.cli.core: serviceconnector          0.044         4        39
cli.azure.cli.core: servicefabric             0.015        26        75
cli.azure.cli.core: signalr                   0.011         6        20
cli.azure.cli.core: sql                       0.027        45       179
cli.azure.cli.core: sqlvm                     0.007         4        17
cli.azure.cli.core: storage                   0.068        55       256
cli.azure.cli.core: synapse                   0.022        51       224
cli.azure.cli.core: util                      0.004         2         4
cli.azure.cli.core: vm                        0.046        52       267
cli.azure.cli.core: Total (65)                1.641      1124      4546
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: account                   0.015         4        12  C:\Users\diberry\.azure\cliextensions\account
cli.azure.cli.core: application-insights      0.064         9        24  C:\Users\diberry\.azure\cliextensions\application-insights
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: db-up                     0.022         3         8  C:\Users\diberry\.azure\cliextensions\db-up
cli.azure.cli.core: Total (3)                 0.100        16        44
cli.azure.cli.core: Loaded 1124 groups, 4590 commands.
cli.azure.cli.core: Updated command index in 0.007 seconds.
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0380DA00>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\diberry\.azure\commands\2023-04-27.13-57-50.webapp_connection_create.27224.log'.
az_command_data_logger: command args: webapp connection create {} -g {} -n {} --tg {} --server {} --database {} --system-identity --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0386E4A8>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03890B68>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03890BB0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03890C40>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x044266E8>]
The command requires the extension serviceconnector-passwordless. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): y
cli.azure.cli.core.extension.dynamic_install: Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 2737382
cli.azure.cli.core.extension._resolve: Candidates ['serviceconnector_passwordless-0.3.0-py3-none-any.whl', 'serviceconnector_passwordless-0.3.1-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['serviceconnector_passwordless-0.3.0-py3-none-any.whl', 'serviceconnector_passwordless-0.3.1-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Skipping 'serviceconnector_passwordless-0.3.0-py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.31.0 ext_version=0.3.0 min_core_required=2.46.0 max_core_required=None min_ext_required=None
cli.azure.cli.core.extension._resolve: Skipping 'serviceconnector_passwordless-0.3.1-py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.31.0 ext_version=0.3.1 min_core_required=2.46.0 max_core_required=None min_ext_required=None
cli.azure.cli.core.extension._resolve: Candidates []
cli.azure.cli.core.extension.operations: No suitable extensions found.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 328, in add_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/_resolve.py", line 77, in resolve_from_index
azure.cli.core.extension._resolve.NoExtensionCandidatesError: No suitable extensions found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 583, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1768, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1159, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 284, in parse_known_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 1988, in _parse_known_args
  File "argparse.py", line 1965, in consume_positionals
  File "argparse.py", line 1858, in take_action
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 275, in _get_values
  File "argparse.py", line 2399, in _get_values
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 303, in _check_value
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/dynamic_install.py", line 119, in try_install_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/dynamic_install.py", line 220, in _check_value_in_extensions
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 336, in add_extension
knack.util.CLIError: No matching extensions for 'serviceconnector-passwordless'. Use --debug for more information.

cli.azure.cli.core.azclierror: No matching extensions for 'serviceconnector-passwordless'. Use --debug for more information.
az_command_data_logger: No matching extensions for 'serviceconnector-passwordless'. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0380DB20>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 23.698 seconds (init: 0.405, invoke: 23.293)
telemetry.save: Save telemetry record of length 3205 in cache
telemetry.check: Negative: The C:\Users\diberry\.azure\telemetry.txt was modified at 2023-04-27 13:53:31.044721, which in less than 600.000000 s
```

![image](https://user-images.githubusercontent.com/41597107/234989463-1cb98256-5335-4e07-ad21-fd1830e6af86.png)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by diberry** [comment]
I updated my Azure CLI and it worked.
