### ISSUE TITLE
az network bastion rdp

### ISSUE THREAD

**Issue by mudarola** [Azure/azure-cli#26298]
I have been trying to run az network bastion rdp with the correct parameters and I keep getting these errors below using portal az cli:

The command failed with an unexpected error. Here is the traceback:
cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/mojeed/.azure/cliextensions/bastion/azext_bastion/custom.py", line 232, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/home/mojeed/.azure/cliextensions/bastion/azext_bastion/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mudarola** [comment]
I just found a thread https://github.com/Azure/azure-cli/issues/23228#issuecomment-1191032569 with the same error, so I tried to explore the mitigation plan and this is what I am getting "Request to EncodingReservedUnitTypes v2 API endpoint failed."

**Comment by PramodValavala-MSFT** [comment]
@mudarola Looks like you are trying this on Cloud Shell. If so, that isn't supported, and you would have to run the same on a Windows machine which opens the Remote Desktop Connection application to connect via RDP.

You could however navigate to the bastion blade for the VM and RDP into the portal from there
![image](https://user-images.githubusercontent.com/43602528/235488428-92de6e1d-5286-4788-90ac-d67e900791cd.png)

**Comment by mudarola** [comment]
> @mudarola Looks like you are trying this on Cloud Shell. If so, that isn't supported, and you would have to run the same on a Windows machine which opens the Remote Desktop Connection application to connect via RDP.
> 
> 
> 
> You could however navigate to the bastion blade for the VM and RDP into the portal from there
> 
> ![image](https://user-images.githubusercontent.com/43602528/235488428-92de6e1d-5286-4788-90ac-d67e900791cd.png)
> 
> 

I read that from the thread I linked into my issue, I was using the portal and eventually found out it wasn't supported, so I'm using the Local Computer PS AZ CLI and it's showing the error above.

**Comment by mudarola** [comment]
@PramodValavala-MSFT I found out it wasn't supported so I followed with the recommendation to use the local computer PS AS CLI and I'm getting the other error.

**Comment by jiasli** [comment]
Duplicate of #23143
