### ISSUE TITLE
Error when performing az webapp deploy

### ISSUE THREAD

**Issue by mosesantony** [Azure/azure-cli#26300]
## Describe the bug

**Command Name**
`az webapp deploy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azure.cli.command_modules.appservice.custom#perform_onedeploy' is invalid.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 24, in <module>
    import OpenSSL.crypto
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azure.cli.command_modules.appservice.custom#perform_onedeploy' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deploy --name {} --resource-group {} --src-path {}`

## Environment Summary
```
Linux-5.15.49-linuxkit-x86_64-with, Alpine Linux v3.15
Python 3.10.4
Installer: DOCKER

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mosesantony** [comment]
> Hi @mosesantony,
> 
> 2.36.0 is not the latest Azure CLI(2.48.1).
> 
> Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Latest CLI doesn't support python deployment. So i am forced to do it via this specific cli version. I got the reference from https://petri.com/install-azure-cli/ to use this version.

**Comment by dannysongg** [comment]
@mosesantony can you provide some more details about this issue? I am unable to reproduce this on my end.

**Comment by mosesantony** [comment]
Unfortunately, i am not into that environment. It is difficult to reproduce and i am not using this any more. Closing this one as of now.
