### ISSUE TITLE
ASH: "az network vnet subnet create" cannot pass name for nsg or route table

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#26318]
## Describe the bug
Error when trying to create subnet using az network command in Azure Stack Hub. The `--nsg` and `--route-table` can be either the resource id or name, but the format seems to be enforcing the resource id only. Historically, you could use either name or resource id since we had a test that passed the name:
https://github.com/Azure/azure-cli/blob/04caa20eb6578425f6ffd09d13108fdb1abccd10/src/azure-cli/azure/cli/command_modules/network/aaz/2020_09_01_hybrid/network/vnet/subnet/_create.py#L80

Same issue for route table:
https://github.com/Azure/azure-cli/blob/04caa20eb6578425f6ffd09d13108fdb1abccd10/src/azure-cli/azure/cli/command_modules/network/aaz/2020_09_01_hybrid/network/vnet/subnet/_create.py#L87

Was there a breaking change to move away from names and force users to pass the resource id? If so, then the help message should be updated.

**Command Name**
`az network vnet subnet create`

**Errors:**
```
cli.knack.cli: Command arguments: ['network', 'vnet', 'subnet', 'create', '-g', 'clicanvrg', '--vnet-name', 'testVnet', '-n', 'testSubnet', '--address-prefix', '10.0.0.0/24', '--network-security-group', 'testNsg', '--route-table', 'testRt', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x024EA4A8>, <function OutputProducer.on_global_arguments at 0x026B7C40>, <function CLIQuery.on_global_arguments at 0x026D6898>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.174        32       185
cli.azure.cli.core: Total (1)                 0.174        32       185
cli.azure.cli.core: Loaded 32 groups, 185 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network vnet subnet create
cli.azure.cli.core: Command table: network vnet subnet create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x048BB4A8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Administrator.RP0103-DVM\.azure\commands\2023-05-03.06-29-29.network_vnet_subnet_create.15732.log'.
az_command_data_logger: command args: network vnet subnet create -g {} --vnet-name {} -n {} --address-prefix {} --network-security-group {} --route-table {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x048E1850>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x048F1778>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x048F19B8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x026B7C88>, <function CLIQuery.handle_query_parameter at 0x026D68E0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x048F1970>]
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 53, in format_args
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 400, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 397, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 679, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 649, in __call__
azure.cli.core.aaz.exceptions.AAZInvalidArgValueError: InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/networkSecurityGroups/{}' format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 149, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\network\aaz_compact\2020_09_01_hybrid\network\vnet\subnet\__cmds.py", line 47, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 159, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 55, in format_args
azure.cli.core.azclierror.InvalidArgumentValueError: InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/networkSecurityGroups/{}' format.

cli.azure.cli.core.azclierror: InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/networkSecurityGroups/{}' format.
az_command_data_logger: InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/networkSecurityGroups/{}' format.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x048BB5C8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.804 seconds (init: 0.399, invoke: 0.405)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3660 in cache
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Az cloud register for Azure Stack Hub using API profile 2020-09-01-hybrid.
- `az network vnet subnet create -g {} --vnet-name {} -n {} --address-prefix {} --network-security-group {} --route-table {} --debug`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
Thanks for your detailed info, but I cannot reproduce:

![image](https://user-images.githubusercontent.com/12371639/236772192-9b19f29f-dbcc-4d3d-ab9c-2cd28f5687f7.png)

**Comment by jtvcodes** [comment]
I am having the same issue, with `az network vnet subnet update`. In my case, I'm using the resource id, which I am getting from `az network nsg list -g "${resource_group}" --query "[0].id" -otsv`.

**Command name:**
```
az network vnet subnet update -g ${resource_group} -n ${subnet}--vnet-name ${vnet}  --network-security-group \
/subscriptions/MYSUB/resourceGroups/MYRG/providers/Microsoft.Network/networkSecurityGroups/MYNSG
```

**Error:**
```
InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/networkSecurityGroups/{}' format.
```

**Comment by necusjz** [comment]
> I am having the same issue, with `az network vnet subnet update`. In my case, I'm using the resource id, which I am getting from `az network nsg list -g "${resource_group}" --query "[0].id" -otsv`.
> 
> **Command name:**
> 
> ```
> az network vnet subnet update -g ${resource_group} -n ${subnet}--vnet-name ${vnet}  --network-security-group \
> /subscriptions/MYSUB/resourceGroups/MYRG/providers/Microsoft.Network/networkSecurityGroups/MYNSG
> ```
> 
> **Error:**
> 
> ```
> InvalidArgumentValue: --nsg: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/networkSecurityGroups/{}' format.
> ```

Which version are you using?
