### ISSUE TITLE
Error 'AAZStrArg' object is not subscriptable when creating a resource with a tag containing a dot in its key

### ISSUE THREAD

**Issue by amine-bouassida** [Azure/azure-cli#26313]
## Describe the bug

**Command Name**
`az network private-endpoint create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'AAZStrArg' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/lib64/python3.9/argparse.py", line 1820, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2044, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2021, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1209, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2044, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2021, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1209, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2044, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2021, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1209, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2062, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2002, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 89, in __call__
    self.setup_operations(dest_ops, values)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 184, in setup_operations
    for _, key_parts, value in cls.decode_values(values):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 196, in decode_values
    key_parts, schema = cls.get_schema_by_key_items(key_parts, cls._schema)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_arg_action.py", line 215, in get_schema_by_key_items
    schema = schema[item]
TypeError: 'AAZStrArg' object is not subscriptable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network private-endpoint create --tags "some.key=some-value"`

## Environment Summary
```
Linux-4.18.0-348.20.1.el8_5.x86_64-x86_64-with-glibc2.28, Red Hat Enterprise Linux 8.5 (Ootpa)
Python 3.9.7
Installer: RPM

azure-cli 2.48.1

Extensions:
ssh 1.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context

The error only occurs when at least one of the tags we pass to `--tags` has a `.` (dot) in its key
This issue did not occur in older azure-cli versions. I think that it used to work until 2.44.x, and the error appeared since 2.45.x

A quick (non-expert) look into the python code of the core lead us to conclude that the command parsing code is in fault here. I'll let you explore more the root cause, and hopefully propose a bugfix.

Note that changing our tags, to no longer use dots in their keys, is not an option for us, as we have too many existing Azure infrastructure resources tagged that way, and changing course now would mean a big migration for us, that we cannot afford, let alone justify

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@amine-bouassida

You can take `--tags "'foo.bar'=baz"` as workaround, it's by design of our next generation CLI (based on codegen). `.` is used to access attributes, so we need to use `''` to escape.

Sorry for any inconveniences.
