### ISSUE TITLE
az network dns record-set cname create failed with an unexpected error in latest CLI

### ISSUE THREAD

**Issue by RuoyuWang-MS** [Azure/azure-cli#26379]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az network dns record-set cname create -n cli-et-standard-20230504-5ag -g azdmss-dogfood --ttl 3600 -z azdmss-test.net --subscription d51e3ffe-6b84-49cd-b426-0dc4ec660356

**Describe the bug**

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expect <class 'int'>, got 3600 (<class 'str'>)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 2522, in create_dns_record_set
    return _DNSRecordSetCreate(cli_ctx=cmd.cli_ctx)(command_args={
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 26, in _handler
    super()._handler(command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 153, in _handler
    self.ctx = AAZCommandCtx(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command_ctx.py", line 32, in __init__
    self.args[dest] = cmd_arg
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_type.py", line 48, in process_data
    raise AAZInvalidValueError('Expect {}, got {} ({})'.format(self.DataType, data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'int'>, got 3600 (<class 'str'>)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

**To Reproduce**

This command often fails in our ado pipelines.

**Expected behavior**

Succeed and return json values.
+ az network dns record-set cname create -n cli-et-standard-20230426-18o -g azdmss-dogfood --ttl 3600 -z azdmss-test.net --subscription d51e3ffe-6b84-49cd-b426-0dc4ec660356
{
  "etag": "0cec0854-9043-4c69-94bc-755abe6032cb",
  "fqdn": "cli-et-standard-20230426-18o.azdmss-test.net.",
  "id": "/subscriptions/d51e3ffe-6b84-49cd-b426-0dc4ec660356/resourceGroups/azdmss-dogfood/providers/Microsoft.Network/dnszones/azdmss-test.net/CNAME/cli-et-standard-20230426-18o",
  "metadata": null,
  "name": "cli-et-standard-20230426-18o",
  "provisioningState": "Succeeded",
  "resourceGroup": "azdmss-dogfood",
  "targetResource": {
    "id": null
  },
  "ttl": 3600,
  "type": "Microsoft.Network/dnszones/CNAME"
}

**Environment summary**

Lastest azure CLI because I use the ado pipeline. 

**Additional context**

FYI I tried in local The command works in azure-cli 2.45.0.
![image](https://user-images.githubusercontent.com/86712051/237003352-56f64765-979a-4cf0-94e8-c8556f0b5891.png)

But failed after I upgrade CLI to 2.48.1
![image](https://user-images.githubusercontent.com/86712051/237005687-9d5591f7-1c25-406c-9b8d-aa329d83a5fd.png)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
I remember the default value of `--ttl` is 3600, so you don't need to input it.

Nevertheless, such issue will be fixed by https://github.com/Azure/azure-cli/pull/26260.
