### ISSUE TITLE
az webapp up AttributeError: 'ZipFile' object has no attribute 'mkdir'

### ISSUE THREAD

**Issue by goofballLogic** [Azure/azure-cli#26413]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
e command failed with an unexpected error. Here is the traceback:
'ZipFile' object has no attribute 'mkdir'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/commands.py", line 45, in _ex_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 4748, in webapp_up
    zip_file_path = zip_contents_from_dir(src_dir, language)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 71, in zip_contents_from_dir
    zip_dotnet_project_references(abs_src, "{}".format(zip_file_path))
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 574, in zip_dotnet_project_references
    tmp_zf.mkdir(DOTNET_REFERENCES_DIR_IN_ZIP)
AttributeError: 'ZipFile' object has no attribute 'mkdir'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp up --sku {} --name {} --os-type {}`

## Expected Behavior

Package and deploy the web app

## Environment Summary
```
macOS-13.3.1-x86_64-i386-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1
```
## Additional Context

Note that I have python 3.11.3 installed, but the version 3.10 which comes with azure-cli lacks the mkdir method used (was introduced in 3.11)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@goofballLogic Thanks for reaching out to us and reporting this issue. Could you please confirm if it works with AzCLI on machine which has Python 3.11 installed ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@goofballLogic Apologies for the late reply. I tried to run the CLI command `az webapp up --sku B2 --name MyWebDelApp --os-type Linux --debug ` on my machine and it worked fine. I am using version on my Windows 11 machine. Did you try running the same command from [Azure Cloud Shell](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#code-try-35) and check if that works ?

Awaiting your reply.

**Comment by goofballLogic** [comment]
@navba-MSFT I can try but I need to use the CLI from my Mac.

**Comment by navba-MSFT** [comment]
@goofballLogic I wanted to do quick follow-up to check if you had any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Fed03 I am unable to reproduce this issue on my Windows 11 machine while running `az webapp up ` cli command. Could you please share us the below details ?

- The exact CLI command with sample arguments that you tried to execute ? 
- Azure CLI version by running `az --version`.
- Python version by running `python --version`.
- Try the same command from [Azure Cloud Shell](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#code-try-35) and check if that works.

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Fed03  I am unable to reproduce this issue at my end with the above command. Could you please [update to Az CLI 2.49.0 ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)version and test again ?

**Comment by Fed03** [comment]
@navba-MSFT after the upgrade, it seems working

**Comment by navba-MSFT** [comment]
Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
