### ISSUE TITLE
Errors after upgrading az stack-hci 

### ISSUE THREAD

**Issue by priyjain358** [Azure/azure-cli#26411]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az stack-hci cluster show 

**Describe the bug**

After upgrading the cli module, started getting the following error: 
"Conflict key when apply client flatten: type in ~scrubbed resource details~
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 149, in __call__
  File "C:\Users\priyjain\.azure\cliextensions\stack-hci\azext_stack_hci\aaz\latest\stack_hci\cluster\_show.py", line 34, in _handler
    return self._output()
  File "C:\Users\priyjain\.azure\cliextensions\stack-hci\azext_stack_hci\aaz\latest\stack_hci\cluster\_show.py", line 72, in _output
    result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 227, in deserialize_output
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_field_value.py", line 144, in to_serialized_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 221, in processor

**To Reproduce**

**Expected behavior**

**Environment summary**

az cli stack-hci version: 0.1.7
cli version: 2.45.0
**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by priyjain358** [comment]
[like]  Priyanshi Jain reacted to your message:
________________________________

**Comment by priyjain358** [comment]
Shared over email

**Comment by zhoxing-ms** [comment]
This is a conflict issue caused by Swagger. As we can see in the screenshot below that the `type` and `identity.type` have the same property name `type` in the data returned by the REST service, so flattening `identity` property will cause conflicts error `Conflict key when apply client flatten`.
![image](https://github.com/Azure/azure-cli/assets/16612065/6a2c3a25-7c8a-41cd-aa14-1d80771270e3)

Therefore, we also need to remove the [`"x-ms-client-flatten": true`](https://github.com/Azure/azure-rest-api-specs/blob/18b397a02e5c7b856f61b6d7fb66a69c9c56c8ce/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2023-03-01/clusters.json#L493) for `identity` property, then use Code Gen to generate new commands.  @Jing-song

**Comment by priyjain358** [comment]
Hi @zhoxing-ms and @Jing-song, we will take this up in the next api-version but it will take some time. Till then, is there a way to solve this issue from the cli itself, perhaps using directives over the current swagger? 
Since this is a blocker for using az stack-hci cli. 

Another thing, are there any tests done before releasing the module so as to uncover these issues in advance?

**Comment by zhoxing-ms** [comment]
@priyjain358 We plan to resolve it by the end of the month
