### ISSUE TITLE
az group list give error: API version 2022-09-01 does not have operation group 'resource_groups'

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-cli#26417]
## Describe the bug
The `az group list` command fails with the error: API version 2022-09-01 does not have operation group 'resource_groups'

**Command Name**
`az group list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-09-01 does not have operation group 'resource_groups'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 1306, in list_resource_groups
  File "c:\users\bmoore\source\azdeploymentstacksprivatepreview\azure-mgmt-resource-21.2.0\azure\mgmt\resource\resources\_resource_management_client.py", line 436, in resource_groups
    raise ValueError("API version {} does not have operation group 'resource_groups'".format(api_version))
ValueError: API version 2022-09-01 does not have operation group 'resource_groups'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Just run the command - have tried removing and reinstalling the CLI but no change in behavior.

## Expected Behavior
Command should return the list of resource groups in the sub

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1
```
## Additional Context
I think the issue is here, though I'm unable to get rid of it:

`  File "c:\users\bmoore\source\azdeploymentstacksprivatepreview\azure-mgmt-resource-21.2.0\azure\mgmt\resource\resources\_resource_management_client.py", line 436, in resource_groups
    raise ValueError("API version {} does not have operation group 'resource_groups'".format(api_version))
`

**Comment by bebound** [comment]
`c:\users\bmoore\source\azdeploymentstacksprivatepreview\azure-mgmt-resource-21.2.0\azure\mgmt\resource\resources\_resource_management_client.py` look weird, CLI should not use that file.

**Comment by bmoore-msft** [comment]
agreed - do you know how I get the CLI to stop looking for it?  That file does not exist.

**Comment by bebound** [comment]
`azdeploymentstacksprivatepreview` looks like an extension, kindle uninstall it or delete that folder and try again.

**Comment by bmoore-msft** [comment]
It's not installed on the machine (the folder does not exist).

**Comment by metazool** [comment]
I see the same error running `az acr login` for the first time on a freshly created Azure Machine Learning VM

**Comment by Vshringari** [comment]
I am getting same error if I am creating the resources from the desktop VSCode. any suggestions on it:

Group: ERROR: Loading resource groups: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: API version 2022-09-01 does not have operation group 'resource_groups'
Traceback (most recent call last):                                
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)

**Comment by arne21a** [comment]
Similar issue with az resource show
```
az resource show --ids /subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.Storage/storageAccounts/<account>/managementPolicies/default
The command failed with an unexpected error. Here is the traceback:
API version 2022-09-01 does not have operation group 'providers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 1742, in show_resource
    [_get_rsrc_util_from_parsed_id(cmd.cli_ctx, id_dict, api_version, latest_include_preview).get_resource(
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 1742, in <listcomp>
    [_get_rsrc_util_from_parsed_id(cmd.cli_ctx, id_dict, api_version, latest_include_preview).get_resource(
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 1697, in _get_rsrc_util_from_parsed_id
    return _ResourceUtils(cli_ctx,
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 3424, in __init__
    api_version = _ResourceUtils._resolve_api_version_by_id(self.rcf, resource_id,
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 3713, in _resolve_api_version_by_id
    return _ResourceUtils.resolve_api_version(rcf, namespace, parent, resource_type,
  File "/usr/local/lib/python3.10/dist-packages/azure/cli/command_modules/resource/custom.py", line 3664, in resolve_api_version
    provider = rcf.providers.get(resource_provider_namespace)
  File "/home/vscode/.local/lib/python3.10/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 380, in providers
    raise ValueError("API version {} does not have operation group 'providers'".format(api_version))
ValueError: API version 2022-09-01 does not have operation group 'providers'
```

```
az --version
azure-cli                         2.48.1 *

core                              2.48.1 *
telemetry                          1.0.8 *

Extensions:
containerapp                      0.3.29
resource-graph                     2.1.0
virtual-wan                       0.2.17

Dependencies:
msal                              1.27.0
azure-mgmt-resource               21.2.1

Python location '/usr/bin/python3'
Extensions directory '/home/vscode/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by helenzusa1** [comment]
I'm getting the error when creating k8s-extention:

>!echo yes | az k8s-extension create --name azureml --extension-type Microsoft.AzureML.Kubernetes --scope cluster --cluster-name aks-11cb8246871adb --resource-group Helen-ML --cluster-type managedClusters --configuration-settings enableInference=True allowInsecureConnections=True inferenceRouterServiceType=LoadBalancer  

The command requires the extension k8s-extension. It will be installed first.
Troubleshooting: https://aka.ms/arcmltsg
SSL is not enabled. Allowing insecure connections to the deployed services.
The command failed with an unexpected error. Here is the traceback:
API version 2022-09-01 does not have operation group 'resources'
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/azureuser/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 171, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
  File "/home/azureuser/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py", line 140, in Create
    resources = cf_resources(cmd.cli_ctx, subscription_id)
  File "/home/azureuser/.azure/cliextensions/k8s-extension/azext_k8s_extension/_client_factory.py", line 42, in cf_resources
    return get_mgmt_service_client(cli_ctx, ResourceType.MGMT_RESOURCE_RESOURCES,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 489, in resources
    raise ValueError("API version {} does not have operation group 'resources'".format(api_version))
ValueError: API version 2022-09-01 does not have operation group 'resources'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Comment by toddysm** [comment]
@johnsonshi Can we see whether this is still an issue and if we can repro? If not, we should close this for the ACR by providing update and removing the Container Registry tag.

**Comment by harshavmb** [comment]
@toddysm , This is still an issue. This is not just confined to ACR or so but wide spread. One way to replicate is to create a resource without `-l` argument.

`az disk create --resource-group abcd --name imgrepldb0b5316disk --gallery-image-reference /subscriptions/abcd-xyz/resourceGroups/abcdproviders/Microsoft.Compute/galleries/xyz/images/linux/versions/1.0.1 --security-type TrustedLaunch --hyper-v-generation V2`

From our stacktrace::
```
ERROR: API version 2024-11-01 does not have operation group 'resource_groups'
Traceback (most recent call last):
  ...blah-blah....
  File "/usr/local/lib/python3.12/site-packages/azure/cli/command_modules/vm/custom.py", line 190, in _get_resource_group_location
    return client.resource_groups.get(resource_group_name).location
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/mgmt/resource/resources/_resource_management_client.py", line 481, in resource_groups
    raise ValueError("API version {} does not have operation group 'resource_groups'".format(api_version))
ValueError: API version 2024-11-01 does not have operation group 'resource_groups'
```

To mitigate this, we pass `-l` argument with above command to avoid `location` lookup via `resource_groups` & it works. 

This is clearly a bug on Azure CLI end. The above disk creation is supposed to work without `-l` argument.
