### ISSUE TITLE
az storage account check-name - Can not find subscription

### ISSUE THREAD

**Issue by martinfletchersustainware** [Azure/azure-cli#26426]
## Describe the bug

**Command Name**
`az storage account check-name`

**Errors:**
(SubscriptionNotFound) Subscription <SUBSCRIPTION_ID> was not found.
Code: SubscriptionNotFound
Message: Subscription <SUBSCRIPTION_ID> was not found.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Assign Contributor role to your user in the Azure subscription
- `az login`
- `az account set --subscription <SUBSCRIPTION_NAME>`
- `az account show`
- `az storage account check-name --name <STORAGE_ACCOUNT_NAME>`

## Expected Behavior
Receive the response indicating if the storage account name is available:

```json
// Available
{
  "message": null,
  "nameAvailable": true,
  "reason": null
}

// Not Available
{
  "message": "The storage account named <STORAGE_ACCOUNT_NAME> is already taken.",
  "nameAvailable": false,
  "reason": "AlreadyExists"
}
```

## Environment Summary
```
Windows-10-10.0.19044-SP0, 
Python 3.10.10
Installer: MSI

azure-cli 2.48.1

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context
Also receiving this issue through Azure Pipelines AzureCli@2 task, which successfully creates a resource group prior to checking the storage account name exists.

- `az group create --location <AZURE_REGION> --name <RESOURCE_GROUP_NAME>`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
I can't reproduce in my local env. Can you please share debug log by adding `--debug`?

**Comment by martinfletchersustainware** [comment]
Sure - I can also confirm that the subscription exists, and both the user (and SP used by Azure DevOps Pipelines) has Contributor role for the subscription.

Output below:

```powershell
az role assignment list --all --assignee <PRINCIPAL_CLIENT_ID>
```
```json
[
  {
    "condition": null,
    "conditionVersion": null,
    "createdBy": "<CREATED_BY_ID>",
    "createdOn": "2023-05-05T11:09:30.824310+00:00",
    "delegatedManagedIdentityResourceId": null,
    "description": null,
    "id": "/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Authorization/roleAssignments/d374bbc4-81e4-4fa8-8211-c45774cf9f4a",
    "name": "d374bbc4-81e4-4fa8-8211-c45774cf9f4a",
    "principalId": "<PRINCIPAL_ID>",
    "principalName": "<PRINCIPAL_CLIENT_ID>",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c",
    "roleDefinitionName": "Contributor",
    "scope": "/subscriptions/<SUBSCRIPTION_ID>",
    "type": "Microsoft.Authorization/roleAssignments",
    "updatedBy": "<UPDATED_BY_ID>",
    "updatedOn": "2023-05-12T08:16:20.154253+00:00"
  }
]
```

```powershell
az account set --subscription <SUBSCRIPTION_NAME>
az account show
```
```json
{
  "environmentName": "AzureCloud",
  "homeTenantId": "<TENANT_ID>",
  "id": "<SUBSCRIPTION_ID>",
  "isDefault": true,
  "managedByTenants": [],
  "name": "<SUBSCRIPTION_NAME>",
  "state": "Enabled",
  "tenantId": "<TENANT_ID>",
  "user": {
    "name": "<USER_EMAIL>",
    "type": "user"
  }
}
```
```powershell
az storage account check-name --name <STORAGE_ACCOUNT_NAME> --verbose --debug

cli.knack.cli: Command arguments: ['storage', 'account', 'check-name', '--name', '<SOTRAGE_ACCOUNT_NAME>', '--verbose', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0177A388>, <function OutputProducer.on_global_arguments at 0x023B8B20>, <function CLIQuery.on_global_arguments at 0x023D6778>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.046        57       269
cli.azure.cli.core: Total (1)                 0.046        57       269
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 57 groups, 269 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account check-name
cli.azure.cli.core: Command table: storage account check-name
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x046EA2B0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\<USER>\.azure\commands\2023-05-15.08-27-15.storage_account_check-name.14340.log'.
az_command_data_logger: command args: storage account check-name --name {} --verbose --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04712388>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 641, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0471F2B0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0471F4A8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x023B8B68>, <function CLIQuery.handle_query_parameter at 0x023D67C0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0471F460>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\<USER>\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\<USER>\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<TENANT_ID>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<TENANT_ID>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<TENANT_ID>/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: c8bc2dfd-3160-433a-9308-ed6acf598e7c
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Storage/checkNameAvailability?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '68'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'ea8741f1-f2f1-11ed-82da-60a5e27d8286'
cli.azure.cli.core.sdk.policies:     'CommandName': 'storage account check-name'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --verbose --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (MSI) azsdk-python-azure-mgmt-storage/21.0.0 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"name": "<STORAGE_ACCOUNT_NAME>", "type": "Microsoft.Storage/storageAccounts"}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Storage/checkNameAvailability?api-version=2022-09-01 HTTP/1.1" 404 118
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '118'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ce71927b-f573-4bcc-8a09-a7de764097d8'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a8458368-1d32-4e05-a6b0-aba47fc65b9e'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230515T072734Z:a8458368-1d32-4e05-a6b0-aba47fc65b9e'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 15 May 2023 07:27:33 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SubscriptionNotFound","message":"Subscription <SUBSCRIPTION_ID> was not found."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/account.py", line 22, in check_name_availability
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/storage/v2022_09_01/operations/_storage_accounts_operations.py", line 704, in check_name_availability
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 107, in map_error
azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound) Subscription <SUBSCRIPTION_ID> was not found.
Code: SubscriptionNotFound
Message: Subscription <SUBSCRIPTION_ID> was not found.

cli.azure.cli.core.azclierror: (SubscriptionNotFound) Subscription <SUBSCRIPTION_ID> was not found.
Code: SubscriptionNotFound
Message: Subscription <SUBSCRIPTION_ID> was not found.
az_command_data_logger: (SubscriptionNotFound) Subscription <SUBSCRIPTION_ID> was not found.
Code: SubscriptionNotFound
Message: Subscription <SUBSCRIPTION_ID> was not found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x046EA3D0>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 1.040 seconds (init: 0.290, invoke: 0.750)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3604 in cache
telemetry.check: Negative: The C:\Users\<USER>\.azure\telemetry.txt was modified at 2023-05-15 08:22:19.505456, which in less than 600.000000 s
```

**Comment by evelyn-ys** [comment]
Oh it's reported by ARM service or Storage service that `Subscription <SUBSCRIPTION_ID> was not found`. Maybe it's a new subscription and it takes time for service to be aware. But anyway this issue should be redirect to service team.

**Comment by martinfletchersustainware** [comment]
> According to the debug log, it's reported by ARM service or Storage service that `Subscription <SUBSCRIPTION_ID> was not found`.
> 
> ```
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Storage/checkNameAvailability?api-version=2022-09-01'
> cli.azure.cli.core.sdk.policies: Request method: 'POST'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '68'
> cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'ea8741f1-f2f1-11ed-82da-60a5e27d8286'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'storage account check-name'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --verbose --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (MSI) azsdk-python-azure-mgmt-storage/21.0.0 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: {"name": "<STORAGE_ACCOUNT_NAME>", "type": "Microsoft.Storage/storageAccounts"}
> 
> cli.azure.cli.core.sdk.policies: Response status: 404
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '118'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ce71927b-f573-4bcc-8a09-a7de764097d8'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a8458368-1d32-4e05-a6b0-aba47fc65b9e'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230515T072734Z:a8458368-1d32-4e05-a6b0-aba47fc65b9e'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 15 May 2023 07:27:33 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"error":{"code":"SubscriptionNotFound","message":"Subscription <SUBSCRIPTION_ID> was not found."}}
> ```
> 
> Maybe it's a new subscription and it takes time for service to be aware. But anyway this issue should be redirect to service team.

This subscription was created a few months ago - As stated, in DevOps pipeline, the AzureCLI@2 task that produces this error creates a resource group successfully prior to the failing storage account check-name call.

**Comment by martinfletchersustainware** [comment]
Discovered the root cause of the issue - The Microsoft.Storage provider was not enabled for the subscription.

Closing as now working as expected.

**Comment by TiloGit** [comment]
I suggest to reopen and the azure-cli should produce a better error. Also on other products/components the azure cli  automatically register missing providers. 

here manual cmd to run: 
`az provider register --namespace Microsoft.Storage`
