### ISSUE TITLE
Disabling instance discovery or validate authority

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#26433]
**Related command**
`az login`

**Is your feature request related to a problem? Please describe.**
`az login` currently doesn't allow disabling instance discovery or validate authority required for some on-premise environments.

**Some investigation info:**
The msal used by latest Azure CLI is 1.20.0, which allows disabling of instance_discovery:
https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/14cbf591948ffb23eb64a675d81e4fa35112d1d9/msal/application.py#L180

I searched the azure cli repo and the only references to instance discovery and validate authority are in the msal package above that was imported.

Also found this issue on this topic:
https://github.com/Azure/azure-cli/issues/12938#issuecomment-611996399
From what jiasli said, it seems that disabling instance discovery or validate authority isn't supported yet for Azure CLI, but that was 3 years ago.

azure-identity Python package introduced validate_authority for version 1.9.0b1 (2022-03-08), which was changed to instance_discovery in 1.13.0b1 (2023-01-10):
https://pypi.org/project/azure-identity/#description
But from the code trace of an error caused by instance_discovery or validate_authority being true:
```
vmadmin@vmadmin-Virtual-Machine:~/Downloads$ az login
The command failed with an unexpected error. Here is the traceback:
invalid_instance: The authority you provided, https://login.devfabric.azs.microsoft.com/organizations, is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 152, in login
    user_identity = identity.login_with_device_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 162, in login_with_device_code
    flow = self._msal_app.initiate_device_flow(scopes, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 112, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 1685, in __init__
    super(PublicClientApplication, self).__init__(
  File "/opt/az/lib/python3.10/site-packages/msal/application.py", line 533, in __init__
    self.authority = Authority(
  File "/opt/az/lib/python3.10/site-packages/msal/authority.py", line 103, in __init__
    raise ValueError(
ValueError: invalid_instance: The authority you provided, https://login.devfabric.azs.microsoft.com/organizations, is not whitelisted. If it is indeed your legit customized domain name, you can turn off this check by passing in validate_authority=False
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```
Azure CLI seems to be calling msal package directly from their own identity package in azure/cli/core/auth/identity.py as opposed to using the Python SDK package azure-identity:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/auth/identity.py

For the az login command, I don't see a way to pass in instance discovery or validate authority configurations:
https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login

**Describe the solution you'd like**
A way to configure the disabling of instance discovery or validate authority.

**Describe alternatives you've considered**
The alternative is a workaround to append "/adfs" to the end of the login endpoint from ARM metadata or active directory endpoint in Azure CLI cloud configurations.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bganapa** [comment]
Please consider this request for the upcoming sprint.  it would help for all the disconnected clouds (e.g AzureStack)
