### ISSUE TITLE
DeserializationError in CLI after adding datafactory extension

### ISSUE THREAD

**Issue by naridnevahgar** [Azure/azure-cli#26435]
**Command Name**
`az datafactory pipeline show
Extension Name: datafactory. Version: 0.7.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'DeserializationError' from 'azure.core.exceptions' (/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 352, in handler
    client = self.client_factory(self.cli_ctx) if self.client_factory else None
...
...
    from azure.core.exceptions import DeserializationError, SerializationError, raise_with_traceback
ImportError: cannot import name 'DeserializationError' from 'azure.core.exceptions' (/usr/local/Cellar/azure-cli/2.36.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az datafactory pipeline show -g {} --factory-name {} --name {}`

## Environment Summary
```
macOS-13.3.1-x86_64-i386-64bit, Darwin 22.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.36.0 *

Extensions:
dev-spaces 1.0.5
datafactory 0.7.0
aks-preview 0.5.4
logic 0.1.4
eventgrid 0.4.9

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@naridnevahgar  Thanks for reaching out to us and reporting this issue. I see that you are using an older version of Azure CLI. Could you please update to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) of Azure CLI and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@naridnevahgar I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
