### ISSUE TITLE
az network dns record-set cname set-record fails

### ISSUE THREAD

**Issue by gerhardcit** [Azure/azure-cli#26437]
## Describe the bug

Someone else can run this on their machine but not me.

**Command Name**
```az network dns record-set cname set-record
--record-set-name test \
    --cname somehwere.qa.mydomain.com \
    --resource-group myresourceGroup \
    --zone-name qa.mydomain.com  \
    --subscription "Mysubscription" \
    --ttl 600
```

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expect <class 'int'>, got 600 (<class 'str'>)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 2833, in add_dns_cname_record
    return _add_save_record(cmd, record, record_type, record_set_name, resource_group_name, zone_name,
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 3093, in _add_save_record
    return _DNSRecordSetCreate(cli_ctx=cmd.cli_ctx)(command_args={
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 26, in _handler
    super()._handler(command_args)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 153, in _handler
    self.ctx = AAZCommandCtx(
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_command_ctx.py", line 32, in __init__
    self.args[dest] = cmd_arg
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/local/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_field_type.py", line 48, in process_data
    raise AAZInvalidValueError('Expect {}, got {} ({})'.format(self.DataType, data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'int'>, got 600 (<class 'str'>)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns record-set cname set-record --record-set-name {} --cname {} --resource-group {} --zone-name {} --subscription {} --ttl {}`

## Environment Summary
```
macOS-13.0.1-x86_64-i386-64bit, Darwin 22.1.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1

Extensions:
front-door 1.0.17
ssh 1.1.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
