### ISSUE TITLE
`AZ monitor log-analytics workspace table delete` fails with useless error

### ISSUE THREAD

**Issue by lightning-cowboy** [Azure/azure-cli#26441]
## Describe the bug
Try to delete a table in LAW from az-CLI
It gives a useless error - no actionable leads

**Command Name**
az monitor log-analytics workspace table delete \
--resource-group $RG \
--workspace-name $WORKSPACE \
-n $TABLENAME

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'Request' from partially initialized module 'requests.models' (most likely due to a circular import) (/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/requests/models.py)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 707, in _run_job
    if _is_poller(result):
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 1156, in _is_poller
    return isinstance(obj, poller_classes())
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 686, in poller_classes
    from msrestazure.azure_operation import AzureOperationPoller
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msrestazure/__init__.py", line 28, in <module>
    from .azure_configuration import AzureConfiguration
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msrestazure/azure_configuration.py", line 34, in <module>
    from msrest import Configuration
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msrest/configuration.py", line 37, in <module>
    from .pipeline import Pipeline
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/msrest/pipeline/__init__.py", line 52, in <module>
    from requests.structures import CaseInsensitiveDict
  File "/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/requests/__init__.py", line 135, in <module>
    from .models import Request, Response, PreparedRequest
ImportError: cannot import name 'Request' from partially initialized module 'requests.models' (most likely due to a circular import) (/opt/homebrew/Cellar/azure-cli/2.48.1/libexec/lib/python3.10/site-packages/requests/models.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
The table deletes. The other commands "workspace table create" "workspace table show" etc all work without complaint.

## Environment Summary
```
macOS-13.3.1-arm64-arm-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by lightning-cowboy** [comment]
> 

no unneeded params were provided as per https://learn.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/table?view=azure-cli-latest#az-monitor-log-analytics-workspace-table-delete-examples

**Comment by AllyW** [comment]
hi @lightning-cowboy , thanks for querying. The `import Request` failure is an existing issue and we have fixed it and will release it on May 23. 

Temporary solution is disabling the import caches like below, both could work:
a. run `rm commandIndex.json` under azure cached files' folder, (which is usually `~/.azure` or the `AZURE_CONFIG_DIR` user set), before every `az monitor log-analytics workspace create\delete` cmd runs
b. set this environment var `AZURE_CORE_USE_COMMAND_INDEX=False` in local script 

For more info, please refer to this issue: https://github.com/Azure/azure-cli/issues/26297
