### ISSUE TITLE
test: test_create_account_sas sporadically fail  

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2646]
@troydai, it starts to fail everyday now, so we should take a look.

```python
Traceback (most recent call last):
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py", line 55, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py", line 55, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "/home/travis/build/Azure/azure-cli/src/command_modules/azure-cli-storage/tests/test_storage_account_scenarios.py", line 136, in test_create_account_sas
    assert u'sig' in sas_keys
AssertionError: 
```

**Comment by troydai** [comment]
Thanks for opening this.

**Comment by JasonRShaver** [comment]
@troydai  is this still an issue or can we close it?

**Comment by troydai** [comment]
It is fixed.
