### ISSUE TITLE
Unable to create a DNS CNAME entry with az network dns record-set cname set-record

### ISSUE THREAD

**Issue by dpaynter** [Azure/azure-cli#26487]
## Describe the bug
Unable to create a DNS CNAME record for usage in a front door (classic). Error starts out by complaining about integer expected, but received a string.

**Command Name**
`az network dns record-set cname set-record`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Expect <class 'int'>, got 300 (<class 'str'>)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 2833, in add_dns_cname_record
    return _add_save_record(cmd, record, record_type, record_set_name, resource_group_name, zone_name,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 3093, in _add_save_record
    return _DNSRecordSetCreate(cli_ctx=cmd.cli_ctx)(command_args={
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 26, in _handler
    super()._handler(command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 153, in _handler
    self.ctx = AAZCommandCtx(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command_ctx.py", line 32, in __init__
    self.args[dest] = cmd_arg
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 48, in process_data
    raise AAZInvalidValueError('Expect {}, got {} ({})'.format(self.DataType, data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'int'>, got 300 (<class 'str'>)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
Just run the command listed below, fails consistently with the same error.
- `az network dns record-set cname set-record -g {} --cname {} -n {} -z {} --ttl {} --if-none-match`

## Expected Behavior
A DNS CNAME entry would be created pointing the domain name to the proper front door.

## Environment Summary
```
Linux-5.4.0-1107-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.48.1

Extensions:
account 0.2.5
ai-examples 0.2.5
alertsmanagement 0.2.3
application-insights 0.1.19
front-door 1.0.17
healthbot 0.1.0
ml 2.15.1
ssh 1.1.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
Azure CLI 2.49.0 has fixed it.
