### ISSUE TITLE
Create Resource failed by azure cli

### ISSUE THREAD

**Issue by myob-hankun** [Azure/azure-cli#26503]
**Related command**
az storage blob generate-sas #{storage_credentials} --name #{function_zip_name} --expiry \"#{sas_expiry}\" --permissions r --full-uri
`resources": [
        {
          "name": "MSDeploy",
          "type": "Extensions",
          "location": "[resourceGroup().location]",
          "apiVersion": "2015-02-01",
          "dependsOn": [
            "[resourceId('Microsoft.Web/Sites', parameters('siteName'))]"
          ],
          "properties": {
            "packageUri": "[parameters('packageURI')]"
          }
        },
`

**Describe the bug**
I upgraded Azure CLI from 0.10 to 2.1. 
And I used the above command to generate a package uri. And run `az deployment group create` to create resource. but this recourse is failed. 

The error is: `ARM-MSDeploy Deploy Failed: 'System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;amp;amp;amp;lt;DownloadPackageAndSettings&amp;amp;amp;amp;amp;gt;d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at `

My URI format is https://XXX.blob.core.windows.net/XXX/XXX?se=XX&sp=x&sv=2021-06-08&sr=b&sig=xxx

**Environment summary**
Azure cli 2.1.0, buildkite

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @myob-hankun , sorry for the late reply, wondering if you have tried the latest CLI version and see if the problem still occurs. https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.
