### ISSUE TITLE
Error az cli using aws cloud shell

### ISSUE THREAD

**Issue by iesodias** [Azure/azure-cli#26536]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 1713, in load_arguments
    help_str = 'Allowed values: {}. Can be combined'.format(get_permission_help_string(t_share_permissions))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --name {} --resource-group {} --location {} --sku {} --https-only --kind {}`

## Environment Summary
```
Linux-5.10.179-166.674.amzn2.x86_64-x86_64-with-glibc2.2.5, Amazon Linux 2
Python 3.7.16
Installer: RPM

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Please try to update CLI to the latest version or take a look at the above issue. Please let us know if those solutions don't solve the issue.
