### ISSUE TITLE
"az databricks workspace list" stopped working 

### ISSUE THREAD

**Issue by wibbico** [Azure/azure-cli#26562]
### Describe the bug

Command suddenly fails with an error: "The command failed with an unexpected error. "

It worked for weeks and month before

### Related command

az databricks workspace list --subscription $subscription_id

### Errors

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 49, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 26, in __next__
    self._executor(self._next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 244, in executor_wrapper
    executor()
  File "/home/user/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 60, in _execute_operations
    self.WorkspacesListBySubscription(ctx=self.ctx)()
  File "/home/user/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 489, in __call__
    return self.on_200(session)
  File "/home/user/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 539, in on_200
    self.ctx.set_var(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command_ctx.py", line 84, in set_var
    self.vars[name] = data
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_type.py", line 220, in process_data
    raise AAZInvalidValueError("Expect <class 'dict'>, got {} ({})".format(data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'dict'>, got [{'properties': {'publicNetworkAccess': 'Enabled', 'managedResourceGroupId': ......] (<class 'list'>)

### Issue script & Debug output

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: Expect <class 'dict'>, got [{'properties': {'publicNetworkAccess': 'Enabled', 'managedResourceGroupId': ......... ] (<class 'list'>)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 49, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 26, in __next__
    self._executor(self._next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 244, in executor_wrapper
    executor()
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 60, in _execute_operations
    self.WorkspacesListBySubscription(ctx=self.ctx)()
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 489, in __call__
    return self.on_200(session)
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 539, in on_200
    self.ctx.set_var(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command_ctx.py", line 84, in set_var
    self.vars[name] = data
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_type.py", line 220, in process_data
    raise AAZInvalidValueError("Expect <class 'dict'>, got {} ({})".format(data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'dict'>, got [{'properties': {'publicNetworkAccess': 'Enabled', 'managedResourceGroupId':...... ] (<class 'list'>)
az_command_data_logger: Expect <class 'dict'>, got [{'properties': {'publicNetworkAccess': 'Enabled', 'managedResourceGroupId':........] (<class 'list'>)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 49, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_paging.py", line 26, in __next__
    self._executor(self._next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 244, in executor_wrapper
    executor()
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 60, in _execute_operations
    self.WorkspacesListBySubscription(ctx=self.ctx)()
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 489, in __call__
    return self.on_200(session)
  File "/home/USERNAME/.azure/cliextensions/databricks/azext_databricks/aaz/latest/databricks/workspace/_list.py", line 539, in on_200
    self.ctx.set_var(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_command_ctx.py", line 84, in set_var
    self.vars[name] = data
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/aaz/_field_type.py", line 220, in process_data
    raise AAZInvalidValueError("Expect <class 'dict'>, got {} ({})".format(data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'dict'>, got [{'properties': {'publicNetworkAccess': 'Enabled', 'managedResourceGroupId':.............] (<class 'list'>)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f27b22e2ef0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.699 seconds (init: 0.198, invoke: 0.501)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 25290 in cache
telemetry.check: Negative: The /home/USERNAME/.azure/telemetry.txt was modified at 2023-05-30 12:01:25.548629, which in less than 600.000000 s

### Expected behavior

Execute command without error

### Environment Summary

core                              2.49.0
telemetry                          1.0.8

Extensions:
databricks                        0.10.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/xxx/.azure/cliextensions'

Python (Linux) 3.10.10 (main, May 19 2023, 08:20:28) [GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by jsntcy** [comment]
@ZengTaoxu, @kairu-ms, @necusjz, please help take a look at the aaz error.

**Comment by Teun-Roefs** [comment]
I'd like to add that using an older version of both the Azure-CLI package (2.48.1) and the Azure CLI Databricks Extension (0.10.0, 0.9.0, 0.8.0) do not resolve this issue.

**Comment by peter-resnick** [comment]
Any update on this? We are experiencing it as well, causing many automated processes that we use to fail repeatedly.

**Comment by MartinBoge** [comment]
I would also like an update. This issue causes problems with deployment pipelines. 

As a hot fix i have used 'az resource list' and then filtered the JSON output to achieve somewhat the same as ´az databricks workspace list´.

**Comment by zyeiy2** [comment]
For me it was the same. Then i added the parameter  --resource-group parameter 

with `az databricks workspace list --resource-group MyResourceGroup`

After the change it works again.

**Comment by brishi19791** [comment]
Facing the same issue. Waiting for an update

**Comment by necusjz** [comment]
Who can kindly provide the debug log by running `az databricks workspace list --debug`? I need `Response content` within it for further analysis.

**Comment by kairu-ms** [comment]
It seems the list by subscription response has some issue. We are reaching out service team to fix the response. Please use `az databricks workspace list --resource-group YourResourceGroup` as a workaround.

**Comment by jsntcy** [comment]
Add more troubleshooting details:

"list workspace by subscription" should return a dictionary as [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2023-02-01/databricks.json#L1389) defined.

while service returns a list instead
![image](https://github.com/Azure/azure-cli/assets/16348853/2dcd5cb5-2725-46f9-b696-deef2a3f0018)

That means the service response is inconsistent with swagger definition
![image](https://github.com/Azure/azure-cli/assets/16348853/6e1d82c8-3332-4c41-a067-be2762817358)

BTW, "list workspace by resource group" returns a dictionary as expected.

So the service team need fix the service to make the service response consists with swagger definition.

@msaranga, could you please help figure out a fix from service side.
`Get-AzDatabricksWorkspace` from Azure PowerShell also has the same issue which was reported in an IcM ticket.

**Comment by msaranga** [comment]
@jsntcy : This should have fixed long back. Can you please validate once

**Comment by evelyn-ys** [comment]
Close as @windoze asked. It should be fixed already
