### ISSUE TITLE
error (Inappropriate ioctl for device) on "az container exec" from GitHub action

### ISSUE THREAD

**Issue by C302** [Azure/azure-cli#26564]
### Describe the bug

On executing az container exec from a GitHub runner, we encounter this error: 
![image](https://github.com/Azure/azure-cli/assets/78357766/efd3c193-a3a2-405d-bcc4-b5130deb54aa)

### Related command

az container exec

### Errors

ERROR: (25, 'Inappropriate ioctl for device')

### Issue script & Debug output

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line [121](https://github.com/chili-publish/delivery-infrastructure/actions/runs/5119557895/jobs/9206147929#step:3:129), in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 695, in container_exec
    _start_exec_pipe_linux(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/container/custom.py", line 731, in _start_exec_pipe_linux
    old_tty = termios.tcgetattr(stdin_fd)
termios.error: (25, 'Inappropriate ioctl for device')
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`

### Expected behavior

return value 0

### Environment Summary

![image](https://github.com/Azure/azure-cli/assets/78357766/26fec69a-26e6-4a37-a8d8-23e2980ca297)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by C302** [comment]
> Hi @C302 Find similar issue #13352.
> 
> Issue title	az container exec in azure devops throws (25, 'Inappropriate ioctl for device')
> Create time	2020-05-06
> Comment number	21
> Please confirm if this resolves your issue. Kindly react a 👍 or 👎 to this comment so that we can improve this robot.

as far as i see this issue has not been resolved as well

**Comment by imroj801** [comment]
I am also getting this same error only when running from a linux agent. Windows agent may have some firewall issues but I am not getting any error, although the command is not running at all. Any advice?

**Comment by ekini** [comment]
Same issue locally
```bash
$echo ls | az containerapp exec -n backend -g group --command sh
...
  File "/usr/lib/python3.11/tty.py", line 32, in setcbreak
    mode = tcgetattr(fd)
           ^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by vandanchev** [comment]
Faced the same issue in Container Instance in Azure Chine and managed to work around it by switching to `Invoke-AzContainerInstanceCommand`

**Comment by thorfi** [comment]
Bump - this issue is back

**Comment by MasonLai-tactable** [comment]
Any update?

**Comment by ngocthoaia1** [comment]
It still happen when I using github action, 

I call `az containerapp update ...`


```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: (25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke

**Comment by arnoldknott** [comment]
This bug is still very much "alive".

Wrapping the `az containerapp exec command` with `script -q -e -c "..."` helps.

**Comment by thorfi** [comment]
Bump, this is back
