### ISSUE TITLE
Error in "az network firewall policy create " when configuring TLS Inspection via azure cli

### ISSUE THREAD

**Issue by agm83** [Azure/azure-cli#26592]
### Describe the bug

Unable to create an azure firewall policy with TLS Inspection
If I remove this parameters, it does generate a policy :
--key-vault-secret-id $KeyVaulSecId `
--cert-name $cernName `
--identity $managedId

### Related command

 az network firewall policy create `
-g $globalRg `
-n $azfwPolicyName `
--sku "Premium" `
--tags "costcenter=xx" `
--dns-servers $azfwDnsServers `
--enable-dns-proxy "true" `
--idps-mode "Alert" `
--threat-intel-mode "Alert" `
--location $azfwPolLocation `
--key-vault-secret-id $KeyVaulSecId `
--cert-name $cernName `
--identity $managedId

### Errors

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'resource'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
AttributeError: 'NoneType' object has no attribute 'resource'
az_command_data_logger: 'NoneType' object has no attribute 'resource'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
AttributeError: 'NoneType' object has no attribute 'resource'

### Issue script & Debug output

`az network firewall policy create `
>>     -g $globalRg `
>>     -n $azfwPolicyName `
>>     --sku "Premium" `
>>     --tags "costcenter=xx" `
>>     --dns-servers $azfwDnsServers `
>>     --enable-dns-proxy "true" `
>>     --idps-mode "Alert" `
>>     --threat-intel-mode "Alert" `
>>     --location $azfwPolLocation `
>>     --key-vault-secret-id $KeyVaulSecId `
>>     --cert-name $cernName `
>>     --identity $managedId `
>> --debug
cli.knack.cli: Command arguments: ['network', 'firewall', 'policy', 'create', '-g', 'oe_wvd', '-n', 'azfwTestPol', '--sku', 'Premium', '--tags', 'costcenter=oe', '--dns-servers', '10.100.16.164', '10.100.16.165', '--enable-dns-proxy', 'true', '--idps-mode', 'Alert', '--threat-intel-mode', 'Alert', '--location', 'francecentral', '--key-vault-secret-id', 'https://kv-oe-wvd-westus2.vault.azure.net/secrets/cert-oe-wvd-azfw/078d076fceb642999cb6e37100f1d23f', '--cert-name', 'cert-oe-wvd-azfw', '--identity', '/subscriptions/cd2991a1-eeb1-4648-bf82-76b2b270be37/resourceGroups/oe_wvd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-oe-wvd-fwpol-westus2', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02B8C4A8>, <function OutputProducer.on_global_arguments at 0x02C58C40>, <function CLIQuery.on_global_arguments at 0x02C79898>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_firewall']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.570       112       438
cli.azure.cli.core: privatedns                0.005        14        66
cli.azure.cli.core: Total (2)                 0.575       126       504
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-firewall            0.041        16        60  C:\Users\agmartinez\.azure\cliextensions\azure-firewall
cli.azure.cli.core: Total (1)                 0.041        16        60
cli.azure.cli.core: Loaded 140 groups, 564 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network firewall policy create
cli.azure.cli.core: Command table: network firewall policy create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04E5B4A8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\agmartinez\.azure\commands\2023-06-02.09-37-34.network_firewall_policy_create.96784.log'.
az_command_data_logger: command args: network firewall policy create -g {} -n {} --sku {} --tags {} --dns-servers {} {} --enable-dns-proxy {} --idps-mode {} --threat-intel-mode {} --location {} --key-vault-secret-id {} --cert-name {} --identity {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04E83610>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04E91580>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04E91778>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02C58C88>, <function CLIQuery.handle_query_parameter at 0x02C798E0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04E91730>]
az_command_data_logger: extension name: azure-firewall
az_command_data_logger: extension version: 0.14.7
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
AttributeError: 'NoneType' object has no attribute 'resource'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'resource'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
AttributeError: 'NoneType' object has no attribute 'resource'
az_command_data_logger: 'NoneType' object has no attribute 'resource'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
AttributeError: 'NoneType' object has no attribute 'resource'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04E5B5C8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.300 seconds (init: 0.391, invoke: 0.909)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7484 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\agmartinez\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload `process``

### Expected behavior

A policy should be created. This was working last month. 

### Environment Summary

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> az -v
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
azure-firewall                    0.14.7
desktopvirtualization               0.2.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\username\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

### Additional context

When using the same parameters via ARM, using json or the portal, I am able to create the policy. So the certificate, managedd Identity, and keyvault secret ID are all correct.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
