### ISSUE TITLE
az functionapp with Consumption plan + Subnet arguments throw "No value for given attribute" error

### ISSUE THREAD

**Issue by CarlOchs** [Azure/azure-cli#26601]
### Describe the bug

When passing arguments to `az functionapp create` to create a consumption plan along with a subnet ID the command will fail with just the error message: `No value for given attribute`

### Related command

az functionapp create

### Errors

`No value for given attribute`

### Issue script & Debug output

```
#!/bin/bash
location="eastus"
stgacct_name="fntststg"
resource_group="funappargissue"
app_insights_name="fntstai"
function_app_name="fntstargissue"
subscription_id=""
subnet_name="fntstsn"
vnet_name="fntstvnet"
rg_exists=$(az group exists --subscription $subscription_id --name $resource_group)
stg_sku="Standard_LRS"

if [ -z "$subscription_id" ]; then
    echo "Please update the subscription_id variable with a valid Subscription ID" >&2
    exit 1
fi

azcli_common_args="--subscription $subscription_id"

if [ "${rg_exists,,}" != "true" ]; then
    az group create --subscription $subscription_id --name $resource_group --location $location --tags $common_tags
fi
az storage account create $azcli_common_args --name $stgacct_name --location $location --resource-group $resource_group --sku $stg_sku

ai_create_result=$(az monitor app-insights component create -a $app_insights_name -l $location -g $resource_group --subscription $subscription_id --tags $common_tags)
echo $ai_create_result


ai_instrumentation_key=$(echo $ai_create_result | jq -r '.instrumentationKey')
ai_id=$(echo $ai_create_result | jq -r '.id')
# Get the connection string, which works across clouds
ai_connection_string=$(az monitor app-insights component show --ids "$ai_id" --query "connectionString" | tr -d \")

# Create subnet
net_info=$(az network vnet create --subscription $subscription_id --resource-group $resource_group --address-prefixes 10.0.0.0/16 --name $vnet_name --resource-group $resource_group --subnet-name $subnet_name --subnet-prefixes 10.0.0.0/24)
echo $net_info
vnet_id=$(echo $net_info | jq -r '.newVNet|.id')
subnet_id=$(echo $net_info | jq -r '.newVNet|.subnets|.[0]|.id')

fa_create_result=$(az functionapp create $azcli_common_args --debug -n $function_app_name --https-only true --disable-app-insights --storage-account $stgacct_name --consumption-plan-location $location  --runtime dotnet --runtime-version 6 -g $resource_group --functions-version 4 --subnet $subnet_id)
echo $fa_create_result
```

Debug output (from a run using a test subscription):

```
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5fc06b52d0>, <function OutputProducer.on_global_arguments at 0x7f5fc05b7eb0>, <function CLIQuery.on_global_arguments at 0x7f5fc0605120>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'functionapp': ['azure.cli.command_modules.appservice']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: appservice                0.139        73       260
DEBUG: cli.azure.cli.core: Total (1)                 0.139        73       260
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
DEBUG: cli.azure.cli.core: Loaded 73 groups, 260 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : functionapp create
DEBUG: cli.azure.cli.core: Command table: functionapp create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f5fbf60ab90>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/cjochsjr/.azure/commands/2023-06-04.14-10-14.functionapp_create.16129.log'.
INFO: az_command_data_logger: command args: functionapp create --debug --subscription {} --tags {} -n {} --https-only {} --disable-app-insights --storage-account {} --consumption-plan-location {} --runtime {} --runtime-version {} -g {} --functions-version {} --subnet {}
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f5fbf6276d0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f5fbf4ad630>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f5fbf4ad750>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f5fc05b7f40>, <function CLIQuery.handle_query_parameter at 0x7f5fc06051b0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f5fbf4ad6c0>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/home/cjochsjr/.azure/msal_token_cache.json', encrypt=False
DEBUG: cli.azure.cli.core.auth.binary_cache: load: /home/cjochsjr/.azure/msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/invocation.py", line 111, in _validation
    self._validate_cmd_level(parsed_ns, cmd_validator)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 849, in _validate_cmd_level
    cmd_validator(**self._build_kwargs(cmd_validator, ns))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_validators.py", line 376, in validate_functionapp
    validate_vnet_integration(cmd, namespace)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_validators.py", line 407, in validate_vnet_integration
    plan_info = client.app_service_plans.get(name=namespace.plan,
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/web/v2022_03_01/operations/_app_service_plans_operations.py", line 1362, in get
    request = build_get_request(
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/web/v2022_03_01/operations/_app_service_plans_operations.py", line 120, in build_get_request
    "name": _SERIALIZER.url("name", name, 'str'),
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 652, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/msrest/serialization.py", line 760, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

ERROR: cli.azure.cli.core.azclierror: No value for given attribute
ERROR: az_command_data_logger: No value for given attribute
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f5fbf60add0>]
INFO: az_command_data_logger: exit code: 2
INFO: cli.__main__: Command ran in 0.627 seconds (init: 0.195, invoke: 0.432)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3669 in cache
WARNING: telemetry.check: Negative: The /home/cjochsjr/.azure/telemetry.txt was modified at 2023-06-04 14:09:21.379528, which in less than 600.000000 s
```

### Expected behavior

An error message that states that the subnet (and vnet) arguments are only valid when used with a non-consumption App Service plan.

### Environment Summary

```
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "application-insights": "0.1.14",
    "azure-devops": "0.25.0",
    "ml": "2.15.1"
  }
```
OS info (`uname -a`):
`Linux WIN-8KKSJ87DR2I 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

```
> python -VV
Python 3.8.10 (default, Mar 13 2023, 10:26:41)
[GCC 9.4.0]
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
