### ISSUE TITLE
BlobAlreadyExists error when trying to Undelete a non-existing item

### ISSUE THREAD

**Issue by nfunwigabga** [Azure/azure-cli#26610]
### Describe the bug

I tried to undelete a file in my container. There is not existing file in the container with that name, but when I try the Undelete (whether through CLI or interface), I get an error saying "BlobAlreadyExists". 

### Related command

1. Check if the file exists in the container: Returns False.
```
az storage blob exists --account-key MyKey --account-name AccountName --container-name ContainerName --name fileName.zip
```

RESPONSE
```
{
  "exists": false
}
```

2. Try to undelete the file from SoftDelete
```
az storage blob undelete --account-key mykey --account-name AccountName --container-name ContainerName --name filename.zip
```
RESPONSE
```
{
  "undeleted": null
}
```

3. Use Filesystem to try to undelete the file
```
az storage fs undelete-path --account-key MyKey --account-name AccountName -f FileSystem --deleted-path-name filename.zip --deletion-id xxxxxx
```
RESPONSE
```
The specified blob already exists.
RequestId:04b2249e-e01e-003b-0807-981725000000
Time:2023-06-05T23:41:05.3648315Z
ErrorCode:BlobAlreadyExists
```

### Errors

RESPONSE
```
The specified blob already exists.
RequestId:04b2249e-e01e-003b-0807-981725000000
Time:2023-06-05T23:41:05.3648315Z
ErrorCode:BlobAlreadyExists
```

### Issue script & Debug output

```
az storage fs undelete-path --account-key MyKey --account-name AccountName -f FileSystem --deleted-path-name filename.zip --deletion-id xxxxxx --debug

cli.knack.cli: Command arguments: ['storage', 'fs', 'undelete-path', '--account-key', 'MyKey', '--account-name', 'AccountName', '-f', 'FileSystem', '--deleted-path-name', 'filename.zip', '--deletion-id', 'xxxxx', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105475fc0>, <function OutputProducer.on_global_arguments at 0x105502d40>, <function CLIQuery.on_global_arguments at 0x1055781f0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.019        58       272
cli.azure.cli.core: Total (1)                 0.019        58       272
cli.azure.cli.core: Loaded 58 groups, 272 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage fs undelete-path
cli.azure.cli.core: Command table: storage fs undelete-path
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x105f8dfc0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/neba/.azure/commands/2023-06-05.19-47-15.storage_fs_undelete-path.51638.log'.
az_command_data_logger: command args: storage fs undelete-path --account-key {} --account-name {} -f {} --deleted-path-name {} --deletion-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x105f9e950>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x105fe4670>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x105fe4790>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x105502dd0>, <function CLIQuery.handle_query_parameter at 0x105578280>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x105fe4700>]
cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
urllib3.connectionpool: Starting new HTTPS connection (1): cwix23data.blob.core.windows.net:443
urllib3.connectionpool: https://cwix23data.blob.core.windows.net:443 "PUT /cwix23backup/cwix23pink.mwbf?comp=undelete HTTP/1.1" 409 220
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 419, in new_handler
    first(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 418, in new_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2021_08_06/_file_system_client.py", line 868, in _undelete_path
    process_storage_error(error)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2021_08_06/_deserialize.py", line 215, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2021_08_06/_file_system_client.py", line 863, in _undelete_path
    is_file = path_client.path.undelete(undelete_source=undelete_source, cls=is_file_path, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/multiapi/storagev2/filedatalake/v2021_08_06/_generated/operations/_path_operations.py", line 2678, in undelete
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:61d1d5ce-801e-0094-0808-98e5e8000000
Time:2023-06-05T23:47:15.9043112Z
ErrorCode:BlobAlreadyExists
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:61d1d5ce-801e-0094-0808-98e5e8000000
Time:2023-06-05T23:47:15.9043112Z</Message></Error>

cli.azure.cli.core.azclierror: The specified blob already exists.
RequestId:61d1d5ce-801e-0094-0808-98e5e8000000
Time:2023-06-05T23:47:15.9043112Z
ErrorCode:BlobAlreadyExists
az_command_data_logger: The specified blob already exists.
RequestId:61d1d5ce-801e-0094-0808-98e5e8000000
Time:2023-06-05T23:47:15.9043112Z
ErrorCode:BlobAlreadyExists
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x105f8e200>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.488 seconds (init: 0.056, invoke: 0.432)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3730 in cache
telemetry.check: Negative: The /Users/xxx/.azure/telemetry.txt was modified at 2023-06-05 19:40:28.154906, which in less than 600.000000 s
```

### Expected behavior

The file should have been undeleted because it does not exist in the container and still within retention policy.

### Environment Summary

```
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/homebrew/Cellar/azure-cli/2.49.0/libexec/bin/python'
Extensions directory '/Users/neba/.azure/cliextensions'

Python (Darwin) 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Are you trying to restore the file in the blob storage or ADLS Gen2 file system. 
If the latter, try `az storage fs file exists --account-key MyKey --account-name AccountName -f FileSystem -p filename.zip` to see if the file already exists.

**Comment by benlw22** [comment]
I am having the same issue. How did you resolve this?
