### ISSUE TITLE
No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'

### ISSUE THREAD

**Issue by ata18** [Azure/azure-cli#26639]
### Describe the bug

 `az cosmosdb` commands in location usgovvirginia fails to execute.

### Related command

az cosmosdb show \
        --resource-group $resourceGroupName \
        --name $accountName \
        --query id \
        --output tsv

### Errors

ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'

### Issue script & Debug output

```
scope=$(
    az cosmosdb show \
        --resource-group $resourceGroupName \
        --name $accountName \
        --query id \
        --output tsv \
--debug )
DEBUG: cli.knack.cli: Command arguments: ['cosmosdb', 'show', '--resource-group', 'md-devbox-dev', '--name', 'md-devbox-dev', '--query', 'id', '--output', 'tsv', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x102492320>, <function OutputProducer.on_global_arguments at 0x102547400>, <function CLIQuery.on_global_arguments at 0x10257c8b0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'cosmosdb': ['azure.cli.command_modules.cosmosdb']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: cosmosdb                  0.021        57       191
DEBUG: cli.azure.cli.core: Total (1)                 0.021        57       191
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: Loaded 57 groups, 191 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : cosmosdb show
DEBUG: cli.azure.cli.core: Command table: cosmosdb show
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10301ff40>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/aishwaryathangappa/.azure/commands/2023-06-08.15-19-08.cosmosdb_show.69101.log'.
INFO: az_command_data_logger: command args: cosmosdb show --resource-group {} --name {} --query {} --output {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x103040a60>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10305e7a0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10305e8c0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x1030a41f0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x102547490>, <function CLIQuery.handle_query_parameter at 0x10257c940>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10305e830>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CosmosDBManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/aishwaryathangappa/.azure/msal_token_cache.json', encrypt=False
DEBUG: cli.azure.cli.core.auth.binary_cache: load: /Users/aishwaryathangappa/.azure/msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.us/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.us/4ba0f847-06cb-4f89-bec4-8bee621c2645/kerberos', 'tenant_region_scope': 'USGov', 'cloud_instance_name': 'microsoftonline.us', 'cloud_graph_host_name': 'graph.microsoftazure.us', 'msgraph_host': 'graph.microsoft.us', 'rbac_url': 'https://pasff.usgovcloudapi.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.usgovcloudapi.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.usgovcloudapi.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 3fb8677c-8bb6-4332-bb76-3d6d67750212
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.usgovcloudapi.net/subscriptions/8a4252fe-cbda-4d11-8349-92842b43911c/resourceGroups/md-devbox-dev/providers/Microsoft.DocumentDB/databaseAccounts/md-devbox-dev?api-version=2023-04-15'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7c6ffede-064a-11ee-87c9-acde48001122'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'cosmosdb show'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --query --output --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (HOMEBREW) azsdk-python-mgmt-cosmosdb/9.2.0 Python/3.10.12 (macOS-13.4-x86_64-i386-64bit)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.usgovcloudapi.net:443
DEBUG: urllib3.connectionpool: https://management.usgovcloudapi.net:443 "GET /subscriptions/8a4252fe-cbda-4d11-8349-92842b43911c/resourceGroups/md-devbox-dev/providers/Microsoft.DocumentDB/databaseAccounts/md-devbox-dev?api-version=2023-04-15 HTTP/1.1" 400 780
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'aae55ca7-c7ec-4a0c-b55a-8a1283f4b0d5'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'aae55ca7-c7ec-4a0c-b55a-8a1283f4b0d5'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'USGOVARIZONA:20230608T221908Z:aae55ca7-c7ec-4a0c-b55a-8a1283f4b0d5'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 08 Jun 2023 22:19:08 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '780'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'."}}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 429, in show_exception_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/mgmt/cosmosdb/operations/_database_accounts_operations.py", line 715, in get
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.

ERROR: cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.
ERROR: az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2023-04-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15-preview, 2022-11-15'. The supported locations are 'usdodcentral, usgovvirginia, usgovarizona, usgovtexas, usdodeast'.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1030201f0>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.072 seconds (init: 0.200, invoke: 0.872)
```

### Expected behavior

Command should succeed.

### Environment Summary

```
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
account                            0.2.5
amg                                1.2.5
application-insights              0.1.19
azure-devops                      0.26.0
interactive                        0.5.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/local/Cellar/azure-cli/2.49.0/libexec/bin/python'
Extensions directory '/Users/aishwaryathangappa/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun  7 2023, 00:45:35) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
