### ISSUE TITLE
az resource move generate invalid json when passing multiple resources resources

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-cli#26645]
### Describe the bug

When using `az resource move` I'm getting an error

The json generated is invalid, the string is not splited on spaces

![image](https://github.com/Azure/azure-cli/assets/539620/075da2f1-535e-4a39-ae80-02800d4ac786)

### Related command

```

az resource move --destination-group staging-mc-hub-storage-rg \
    --destination-subscription-id 04bf988d-ee80-4bb3-be58-4b24a576aa51 \
    --ids '/subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource1 /subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource2 /subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource3 /subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource4 /subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource5 /subscriptions/5955fbbf-b804-4315-a74e-4b9eff6fc762/resourceGroups/some-rg/providers/Microsoft.Storage/storageAccounts/resource6' \
    --debug
``` 

### Errors

{"error":{"code":"TooManyExtensionProviders","message":"The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers."}}

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['resource', 'move', '--destination-group', 'staging-mc-hub-storage-rg', '--destination-subscription-id', '04bf988d-ee80-4bb3-be58-4b24a576aa51', '--ids', '/subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource1 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource2 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource3 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource4 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource5 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/
[]...]
msal.telemetry: Generate or reuse correlation_id: 61e4db65-ab94-45d4-ad58-eb299b5497a3
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/moveResources?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1058'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '51cd6c49-06d1-11ee-a1db-a598e71c1dd2'
cli.azure.cli.core.sdk.policies:     'CommandName': 'resource move'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--destination-group --destination-subscription-id --ids --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (DEB) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Linux-5.19.0-40-generic-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"resources": ["/subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource1 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource2 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource3 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource4 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource5 /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/providers/Microsoft.Storage/storageAccounts/resource6"], "targetResourceGroup": "/subscriptions/04bf988d-ee80-4bb3-be58-4b24a576aa51/resourceGroups/staging-mc-hub-storage-rg"}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/0c6f1acd-31ba-4e86-beca-e264f808ec30/resourceGroups/staging-mc-hub-db-rg/moveResources?api-version=2022-09-01 HTTP/1.1" 400 168
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e8780fb8-f319-410c-811e-735350b1c66a'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e8780fb8-f319-410c-811e-735350b1c66a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADAEAST:20230609T142419Z:e8780fb8-f319-410c-811e-735350b1c66a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 09 Jun 2023 14:24:18 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '168'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"TooManyExtensionProviders","message":"The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 2233, in move_resource
    return rcf.resources.begin_move_resources(resources[0]['resource_group'], parameters=resources_move_info)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 9391, in begin_move_resources
    raw_result = self._move_resources_initial(  # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 9271, in _move_resources_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (TooManyExtensionProviders) The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers.
Code: TooManyExtensionProviders
Message: The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers.

cli.azure.cli.core.azclierror: (TooManyExtensionProviders) The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers.
Code: TooManyExtensionProviders
Message: The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers.
az_command_data_logger: (TooManyExtensionProviders) The number of extension providers in the request URI exceeds limit. ARM supports up to 3 extension providers.
```

### Expected behavior

It should work according to the documentation

https://learn.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-move

![image](https://github.com/Azure/azure-cli/assets/539620/715d5d51-28c0-48d9-ae46-6b563b590470)

### Environment Summary

{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.137",
    "azure-devops": "0.26.0",
    "ssh": "1.1.6"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@Socolin Please use `--ids 'id1' 'id2' 'id3'` instead of `--ids 'id1 id2 id3'`, because the whole of ` 'id1 id2 id3'` will be considered as an id

**Comment by Socolin** [comment]
/unresolve
Ok thanks, then the documentation need to be updated because this is misleading.

**Comment by Socolin** [comment]
@zhoxing-ms why did you close this, I thjink the documentation is misleading and should be fixed before.

**Comment by Socolin** [comment]
/unresolve
@zhoxing-ms 
I just tested it, and it only moved the last resources specified in `--ids` so it does not seems to work, it only take 1, so there is a problem in the code

**Comment by zhoxing-ms** [comment]
@Socolin Sorry, I thought this issue had been resolved, so I closed the issue first, we will add the additional examples later.
If this issue has not been resolved yet, could you please send me the debug log *(add `--debug` parameter)*  using the method I recommend by email? My email is Zhou.Xing@microsoft.com, thank you

**Comment by Socolin** [comment]
> @Socolin Sorry, I thought this issue had been resolved, so I closed the issue first, we will add the additional examples later. If this issue has not been resolved yet, could you please send me the debug log _(add `--debug` parameter)_ using the method I recommend by email? My email is [Zhou.Xing@microsoft.com](mailto:Zhou.Xing@microsoft.com), thank you

I sent you the logs with --debug

**Comment by zhoxing-ms** [comment]
@Socolin I replied to your email, please take a look

**Comment by Socolin** [comment]
So for anyone having this issue, the cli is expecting the following args[]

`'--ids', 'id1' 'id2'`

**Comment by zhoxing-ms** [comment]
@Socolin I have submitted a PR #26756 to add a sample for this case, which will be automatically updated into our document after the next new version of CLI is released.

**Comment by Socolin** [comment]
Thanks !
