### ISSUE TITLE
az servicebus namespace network-rule-set virtual-network-rule add bug

### ISSUE THREAD

**Issue by gsuttie** [Azure/azure-cli#26651]
### Describe the bug

Running the following code

$subid = az network vnet subnet show --resource-group $resourceGroupNameAKS --vnet-name $vnetName --name clusternodes --query id

    az servicebus namespace network-rule-set virtual-network-rule add `
    --resource-group $resourceGroupNameAKS `
    --namespace-name "sb-$environmentName" `
    --subnet $subid `

### Related command

az servicebus namespace network-rule-set virtual-network-rule add

### Errors

The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 588, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1826, in parse_args
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2054, in _parse_known_args
  File "argparse.py", line 2031, in consume_positionals
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1214, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2054, in _parse_known_args
  File "argparse.py", line 2031, in consume_positionals
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1214, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2054, in _parse_known_args
  File "argparse.py", line 2031, in consume_positionals
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1214, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2054, in _parse_known_args
  File "argparse.py", line 2031, in consume_positionals
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1214, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2054, in _parse_known_args
  File "argparse.py", line 2031, in consume_positionals
  File "argparse.py", line 1936, in take_action
  File "argparse.py", line 1214, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1859, in parse_known_args
  File "argparse.py", line 2072, in _parse_known_args
  File "argparse.py", line 2012, in consume_optional
  File "argparse.py", line 1936, in take_action
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicebus/action.py", line 54, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicebus/action.py", line 61, in get_action
ValueError: not enough values to unpack (expected 2, got 1)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

$subid = az network vnet subnet show --resource-group $resourceGroupNameAKS --vnet-name $vnetName --name clusternodes --query id

    az servicebus namespace network-rule-set virtual-network-rule add `
    --resource-group $resourceGroupNameAKS `
    --namespace-name "sb-$environmentName" `
    --subnet $subid `

### Expected behavior

A network rule is added to the ServiceBus Namespace

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

 

Extensions:
account                            0.2.5
aks-preview                      0.5.116
application-insights              0.1.16
authV2                             0.1.1
front-door                        1.0.17

 

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

Extensions directory 'C:\Users\alvar\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by AlvaroBiedma** [comment]
Hello! If there is any doubt, the command looks like this:
`az servicebus namespace network-rule-set virtual-network-rule add --resource-group <correct rg> --namespace-name <sb-...> --subnet "/subscriptions/<subscriptionID>/resourceGroups/<correct rg>/providers/Microsoft.Network/virtualNetworks/<vnet...>/subnets/cluster..."
`

I've tried upgrading azure CLI but it didn't work either. 
All the values are replaced correctly within the cmd. I need to know what's the issue is here as soon as possible please.

Thanks!

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by Saglodha** [comment]
Hi @gsuttie / @AlvaroBiedma ,

Thanks for reaching out to us. Subnet ID should be passed with id argument inside --subnet block with new cmdlet. Please refer here : https://learn.microsoft.com/en-us/cli/azure/servicebus/namespace/network-rule-set/virtual-network-rule?view=azure-cli-latest#az-servicebus-namespace-network-rule-set-virtual-network-rule-add 

We are working on marking --subnet as required parameter in the doc. Please feel free to write back in case of additional concerns.

**Comment by AlvaroBiedma** [comment]
Hello.

I've solved the issue some time ago (sorry for didn't notify it) using the Az Powershell modules:
```
$subid = az network vnet subnet show --resource-group $resourceGroupNameAKS --vnet-name $vnetName --name clusternodes --query id --output tsv
    $VirtualNetworkRule = New-AzServiceBusVirtualNetworkRuleConfig -SubnetId $subid
    Set-AzServiceBusNetworkRuleSet -ResourceGroupName $resourceGroupNameAKS -NamespaceName "sb-$environmentName" -VirtualNetworkRule $VirtualNetworkRule -DefaultAction Deny
```

And thank you so much for inform us that the ID argument inside --subnet block is needed.
Thanks for your response!

**Comment by AlvaroBiedma** [comment]
This issue can be closed. Thank you!
