### ISSUE TITLE
az storage blob service-properties update fails with AzureDnsZone

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cli#26679]
### Describe the bug

When executing `az storage blob service-properties update` on an account using AzureDnsZone, the CLI fails with:

```
<urllib3.connection.HTTPSConnection object at 0x064DBB98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

### Related command

az storage blob service-properties update `
        --auth-mode login `
        --account-name someaccount `
        --static-website `
        --404-document index.html `
        --index-document index.html

### Errors

<urllib3.connection.HTTPSConnection object at 0x064DBB98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Issue script & Debug output

cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x019DB4F0>, <function OutputProducer.on_global_arguments at 0x01AA8C88>, <function CLIQuery.on_global_arguments at 0x01AC98E0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage', 'azext_storage_preview']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.039        58       272
cli.azure.cli.core: Total (1)                 0.039        58       272
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: storage-preview           0.007         9        24  C:\Users\me\.azure\cliextensions\storage-preview
cli.azure.cli.core: Total (1)                 0.007         9        24
cli.azure.cli.core: Loaded 64 groups, 294 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage blob service-properties update
cli.azure.cli.core: Command table: storage blob service-properties update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03D7B418>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\me\.azure\commands\2023-06-14.16-45-53.storage_blob_service-properties_update.6964.log'.
az_command_data_logger: command args: storage blob service-properties update --subscription {} --auth-mode {} --account-name {} --static-website --404-document {} --index-document {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03DA1460>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03DB1538>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03DB15C8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01AA8CD0>, <function CLIQuery.handle_query_parameter at 0x01AC9928>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03DB1580>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\me\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\me\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/54b44b72-739c-4ac5-a64d-68941d13f4c7/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://storage.azure.com/.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://storage.azure.com/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 20bbe895-4d31-4943-8af1-1fa0cd57adae
urllib3.connectionpool: Starting new HTTPS connection (1): {snipaccountname}.blob.core.windows.net:443
urllib3.connectionpool: Starting new HTTPS connection (2): {snipaccountname}.blob.core.windows.net:443
urllib3.connectionpool: Starting new HTTPS connection (3): {snipaccountname}.blob.core.windows.net:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 419, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 418, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 191, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 414, in cached_get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 409, in _get_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/blob/v2021_06_08/_blob_service_client.py", line 303, in get_service_properties
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/blob/v2021_06_08/_generated/operations/_service_operations.py", line 552, in get_properties
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 211, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_redirect.py", line 158, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/blob/v2021_06_08/_shared/policies.py", line 543, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/blob/v2021_06_08/_shared/policies.py", line 517, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_authentication.py", line 118, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/blob/v2021_06_08/_shared/policies.py", line 313, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 103, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 361, in send
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x059F8B98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

cli.azure.cli.core.azclierror: <urllib3.connection.HTTPSConnection object at 0x059F8B98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
az_command_data_logger: <urllib3.connection.HTTPSConnection object at 0x059F8B98>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03D7B538>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 87.277 seconds (init: 0.199, invoke: 87.078)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3641 in cache
telemetry.check: Negative: The C:\Users\erikm\.azure\telemetry.txt was modified at 2023-06-14 16:41:34.880224, which in less than 600.000000 s

### Expected behavior

Should enable the static website.

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
containerapp                      0.3.33
storage-preview                    0.8.4

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Can you try `az login` again, seems like an auth issue. Currently cannot reproduce the issue.
![image](https://github.com/Azure/azure-cli/assets/17182306/b41ace22-0777-42b3-b7cb-1ee64bcb4e8e)

**Comment by onionhammer** [comment]
@calvinhzy Just retried, here's a repro:

```bicep
// Create azure storage account
resource storage 'Microsoft.Storage/storageAccounts@2022-09-01' = {
  name: 'xsi${uniqueString(subscription().id, resourceGroup().name)}'
  location: 'centralus'
  kind: 'StorageV2'
  sku: {
    name: 'Standard_LRS'
  }
  properties: {
    supportsHttpsTrafficOnly: true
    allowSharedKeyAccess: true
    publicNetworkAccess: 'Enabled'
    dnsEndpointType: 'AzureDnsZone'
  }
}

output storageAccountName string = storage.name
```
```ps1
az login

az storage blob service-properties update `
        --subscription $Subscription `
        --auth-mode login `
        --account-name $storageAccountName `
        --static-website `
        --404-document index.html `
        --index-document index.html
```

```
<urllib3.connection.HTTPSConnection object at 0x05997B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

**Comment by calvinhzy** [comment]
Wondering if you have created the storage account with `az storage account create`. Please run `az storage account show` to check. The above error might be caused by the storage account getting deleted.

**Comment by onionhammer** [comment]
> Wondering if you have created the storage account with `az storage account create`. Please run `az storage account show` to check. The above error might be caused by the storage account getting deleted. 

I created it with the bicep I quoted above.

**Comment by calvinhzy** [comment]
I got the same error when the storage account was deleted. Can you see the account with `az storage account show`?

**Comment by onionhammer** [comment]
@calvinhzy I've reproduced it on 2 computers in 2 minutes. The account is not deleted, the CLI is timing out likely because it does not implement AzureDnsZone support.

1. Follow the instructions in this comment: https://github.com/Azure/azure-cli/issues/26679#issuecomment-1598778834
2. Observe error.

**Comment by calvinhzy** [comment]
@onionhammer I was just able to reproduce the error. Likely a service issue, bring in storage team.
