### ISSUE TITLE
`az acr webhook create` fails if `--location` is not set to the registry location

### ISSUE THREAD

**Issue by shizhMSFT** [Azure/azure-cli#26676]
### Describe the bug

When `--location` is not set to the registry location or its default value is not the registry location for `az acr webhook create`, the server side reports `404 not found`, which is not desired.

### Related command

`az acr webhook create`

### Errors

```console
$ az acr webhook create -n scanner -r $acr_name -g $group_name --uri "https://${webapp_name}.azurewebsites.net/hook" --actions push
(RegistryResourceNotFound) The registry resource <acr_name> could not be found.
Code: RegistryResourceNotFound
Message: The registry resource shizhdemom5i could not be found.
```

### Issue script & Debug output

```console
$ az acr webhook create -n scanner -r $acr_name -g $group_name --uri "https://${webapp_name}.azurewebsites.net/hook" --actions push --debug
cli.knack.cli: Command arguments: ['acr', 'webhook', 'create', '-n', 'scanner', '-r', '<acr_name>', '-g', '<group_name>', '--uri', 'https://<webapp_name>.azurewebsites.net/hook', '--actions', 'push', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x018EA4F0>, <function OutputProducer.on_global_arguments at 0x019B8C88>, <function CLIQuery.on_global_arguments at 0x019D78E0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.238        34       144
cli.azure.cli.core: Total (1)                 0.238        34       144
cli.azure.cli.core: Loaded 34 groups, 144 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : acr webhook create
cli.azure.cli.core: Command table: acr webhook create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03C8B418>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\shizh\.azure\commands\2023-06-15.00-21-34.acr_webhook_create.25724.log'.
az_command_data_logger: command args: acr webhook create -n {} -r {} -g {} --uri {} --actions {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03CB56A0>]
cli.knack.commands: Configured default 'eastus' for arg location
cli.knack.commands: Configured default '<group_name>' for arg resource_group_name
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03CD9778>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03CD9808>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x019B8CD0>, <function CLIQuery.handle_query_parameter at 0x019D7928>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03CD97C0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerRegistryManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\shizh\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\shizh\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerRegistryManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 5279cdeb-4802-49a7-9b43-2b18960ca47d
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/ddee19de-7fd8-49f9-9193-4a6322c8fedf/resourceGroups/<group_name>/providers/Microsoft.ContainerRegistry/registries/<acr_name>?api-version=2022-02-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8798ae3e-0acf-11ee-9866-68545ae7fa19'
cli.azure.cli.core.sdk.policies:     'CommandName': 'acr webhook create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -r -g --uri --actions --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 azsdk-python-azure-mgmt-containerregistry/10.1.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/ddee19de-7fd8-49f9-9193-4a6322c8fedf/resourceGroups/<group_name>/providers/Microsoft.ContainerRegistry/registries/<acr_name>?api-version=2022-02-01-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2022-02-01-preview'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'cf0af91f-6714-4e4b-9f78-c0b5bee0d927'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'cf0af91f-6714-4e4b-9f78-c0b5bee0d927'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230614T162135Z:cf0af91f-6714-4e4b-9f78-c0b5bee0d927'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 14 Jun 2023 16:21:35 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"sku":{"name":"Premium","tier":"Premium"},"type":"Microsoft.ContainerRegistry/registries","id":"/subscriptions/ddee19de-7fd8-49f9-9193-4a6322c8fedf/resourceGroups/<group_name>/providers/Microsoft.ContainerRegistry/registries/<acr_name>","name":"<acr_name>","location":"southeastasia","tags":{},"systemData":{"createdBy":"shizh@microsoft.com","createdByType":"User","createdAt":"2023-06-14T14:25:22.7283576+00:00","lastModifiedBy":"shizh@microsoft.com","lastModifiedByType":"User","lastModifiedAt":"2023-06-14T14:40:52.2597147+00:00"},"properties":{"loginServer":"<acr_name>.azurecr.io","creationDate":"2023-06-14T14:25:22.7283576Z","provisioningState":"Succeeded","adminUserEnabled":false,"networkRuleSet":{"defaultAction":"Allow","ipRules":[]},"policies":{"quarantinePolicy":{"status":"enabled"},"trustPolicy":{"type":"Notary","status":"disabled"},"retentionPolicy":{"days":7,"lastUpdatedTime":"2023-06-14T14:25:31.9850924+00:00","status":"disabled"},"exportPolicy":{"status":"enabled"},"azureADAuthenticationAsArmPolicy":{"status":"enabled"},"softDeletePolicy":{"retentionDays":7,"lastUpdatedTime":"2023-06-14T14:34:59.9566026+00:00","status":"disabled"}},"encryption":{"status":"disabled"},"dataEndpointEnabled":false,"dataEndpointHostNames":[],"privateEndpointConnections":[],"publicNetworkAccess":"Enabled","networkRuleBypassOptions":"AzureServices","zoneRedundancy":"Disabled","anonymousPullEnabled":false}}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 819c5c41-7413-440c-af90-a4716df59c8e
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/ddee19de-7fd8-49f9-9193-4a6322c8fedf/resourceGroups/<group_name>/providers/Microsoft.ContainerRegistry/registries/<acr_name>/webhooks/scanner?api-version=2022-02-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '140'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8798ae3e-0acf-11ee-9866-68545ae7fa19'
cli.azure.cli.core.sdk.policies:     'CommandName': 'acr webhook create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -r -g --uri --actions --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 azsdk-python-azure-mgmt-containerregistry/10.1.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "eastus", "properties": {"serviceUri": "https://<webapp_name>.azurewebsites.net/hook", "status": "enabled", "actions": ["push"]}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/ddee19de-7fd8-49f9-9193-4a6322c8fedf/resourceGroups/<group_name>/providers/Microsoft.ContainerRegistry/registries/<acr_name>/webhooks/scanner?api-version=2022-02-01-preview HTTP/1.1" 404 130
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '130'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c133b16d-ef73-48c8-aaeb-57ec0f590d1f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c133b16d-ef73-48c8-aaeb-57ec0f590d1f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230614T162137Z:c133b16d-ef73-48c8-aaeb-57ec0f590d1f'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 14 Jun 2023 16:21:37 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"RegistryResourceNotFound","message":"The registry resource <acr_name> could not be found."},"status":"Failed"}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/webhook.py", line 41, in acr_webhook_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerregistry/v2022_02_01_preview/operations/_webhooks_operations.py", line 726, in begin_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerregistry/v2022_02_01_preview/operations/_webhooks_operations.py", line 579, in _create_initial
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 107, in map_error
azure.core.exceptions.ResourceNotFoundError: (RegistryResourceNotFound) The registry resource <acr_name> could not be found.
Code: RegistryResourceNotFound
Message: The registry resource <acr_name> could not be found.

cli.azure.cli.core.azclierror: (RegistryResourceNotFound) The registry resource <acr_name> could not be found.
Code: RegistryResourceNotFound
Message: The registry resource <acr_name> could not be found.
az_command_data_logger: (RegistryResourceNotFound) The registry resource <acr_name> could not be found.
Code: RegistryResourceNotFound
Message: The registry resource <acr_name> could not be found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03C8B538>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 3.784 seconds (init: 0.685, invoke: 3.099)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3540 in cache
telemetry.check: Negative: The C:\Users\shizh\.azure\telemetry.txt was modified at 2023-06-15 00:17:53.404698, which in less than 600.000000 s
```

### Expected behavior

The command should not fail (especially when `--location` is not set) or given the correct error message.

### Environment Summary

```console
$ az --version
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\shizh\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by shizhMSFT** [comment]
@yonzhan It's a server-side bug.

**Comment by toddysm** [comment]
@shizhMSFT I assume this is still not fixed. Do we need to provide validation here?

**Comment by shizhMSFT** [comment]
@toddysm I did a validation, and the issue has already been resolved as the error message presents.
```console
$ az acr webhook create -n scanner -r $acr_name -g $group_name --uri "https://${webapp_name}.azurewebsites.net/hook" --actions push --location eastus
(RegistryResourceNotFoundInSpecifiedRegion) The registry resource shizhissue26676 could not be found in the location eastus. Please ensure that you create a webhook in the registry home region or one of the geo-replication regions. For more information, please visit https://aka.ms/acr/webhooks.
Code: RegistryResourceNotFoundInSpecifiedRegion
Message: The registry resource shizhissue26676 could not be found in the location eastus. Please ensure that you create a webhook in the registry home region or one of the geo-replication regions. For more information, please visit https://aka.ms/acr/webhooks.
```
