### ISSUE TITLE
"az webapp config connection-string set" broken; returning 400 Bad Request

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#26687]
### Describe the bug

az webapp config connection-string set --connection-string-type SqlAzure --name <web app or function app name> --resource-group myRG --settings Foo='<any connection string>' fails with a 400 Bad Request.

Is true for the latest Azure CLI (2.49.0) and older versions at least as far back as 2.46.0.

### Related command

az webapp config connection-string set

### Errors

{
  "Code": "BadRequest",
  "Message": "The parameter properties has an invalid value.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter properties has an invalid value."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "51008",
        "MessageTemplate": "The parameter {0} has an invalid value.",
        "Parameters": [
          "properties"
        ],
        "Code": "BadRequest",
        "Message": "The parameter properties has an invalid value."
      }
    }
  ],
  "Innererror": null
}

Here is the debug log with some details obfuscated:

### Issue script & Debug output

DEBUG: msal.telemetry: Generate or reuse correlation_id: c354cf72-21a8-453d-9635-951f6b625265
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<mySubscription>/resourceGroups/<myRG>/providers/Microsoft.Web/sites/<myApp>/config/connectionstrings?api-version=2022-03-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'PUT'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '640'
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e5ecf459-0b91-11ee-9e60-3814280333d7'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'webapp config connection-string set'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--connection-string-type --name --resource-group --settings --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.46.0 (MSI) azsdk-python-azure-mgmt-web/7.0.0 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: {"properties": {"SomeConnectionName": {"value": "Data Source=<myAzureSQLServer>.database.windows.net,1433;Initial Catalog=SomeDatabase1;Authentication=Active Directory Managed Identity", "type": "SQLAzure"}, "SomeConnectionName2": {"value": "Data Source=<myAzureSQLServer>.database.windows.net,1433;Initial Catalog=SomeDatabase2;Authentication=Active Directory Managed Identity", "type": "SQLAzure"}, "SomeConnectionName3": {"value": "=<myAzureSQLServer>.database.windows.net,1433;Initial Catalog=SomeDatabase3;Authentication=Active Directory Managed Identity", "type": "SQLAzure"}}}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<mySubscription>/resourceGroups/<myRG>/providers/Microsoft.Web/sites/<myApp>/config/connectionstrings?api-version=2022-03-01 HTTP/1.1" 400 415
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '415'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '888ae195-bd80-4e6d-9147-f6ac5d055abf'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '888ae195-bd80-4e6d-9147-f6ac5d055abf'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20230615T153257Z:888ae195-bd80-4e6d-9147-f6ac5d055abf'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 15 Jun 2023 15:32:57 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"The parameter properties has an invalid value.","Target":null,"Details":[{"Message":"The parameter properties has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51008","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["properties"],"Code":"BadRequest","Message":"The parameter properties has an invalid value."}}],"Innererror":null}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1520, in update_connection_strings
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_appservice_utils.py", line 33, in _generic_settings_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2022_03_01/operations/_web_apps_operations.py", line 19492, in update_connection_strings
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"The parameter properties has an invalid value.","Target":null,"Details":[{"Message":"The parameter properties has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51008","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["properties"],"Code":"BadRequest","Message":"The parameter properties has an invalid value."}}],"Innererror":null}

ERROR: cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'
ERROR: az_command_data_logger: Operation returned an invalid status 'Bad Request'

### Expected behavior

It should add a new connection string. (or update an existing one)

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.17.2
ssh                                1.1.6

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3.9'
Extensions directory '/home/vaughn/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by seligj95** [comment]
assign: seligj95

**Comment by seligj95** [comment]
Unable to repro with version 2.50.0. 

@vhhughes Is this still an issue?

**Comment by seligj95** [comment]
Closing for now due to no activity. Please comment/re-open if this is still an issue.

**Comment by vhhughes** [comment]
I'm still able to reproduce it using 2.51.0. It is the exact same error as before.

**Comment by TossAyeCoin** [comment]
I am also having this issue @seligj95 can you post the azure cli command you used which did work? I am on az cli version 2.53.0

**Comment by warpdriv** [comment]
How was this resolved? I'm having the same issue. Thank you

**Comment by TossAyeCoin** [comment]
@warpdriv yes, check your az policy. You need to make sure that non-tls connections are allowed.

**Comment by nalmar** [comment]
Same issue too, cli v2.61.0

@TossAyeCoin can you give us the az-newbie version of "check your az policy. You need to make sure that non-tls connections are allowed."

**Comment by hampterfidev** [comment]
> Same issue too, cli v2.61.0
> 
> @TossAyeCoin can you give us the az-newbie version of "check your az policy. You need to make sure that non-tls connections are allowed."

Check to see if you have any azure policies enforcing a minimum TLS level for Azure app services. You will need to waive/remove them for the app you are trying to update.

**Comment by TossAyeCoin** [comment]
> Same issue too, cli v2.61.0
> 
> @TossAyeCoin can you give us the az-newbie version of "check your az policy. You need to make sure that non-tls connections are allowed."

Check your Azure Policy for any TLS specific policies around app service.
Waive the policies until you find the culprit. The error that this produces is basically useless.
I'm guessing the connection-string transmission method is different from the app settings. 
If this becomes a bigger issue I can dig into the WHY more.

**Comment by nalmar** [comment]
@TossAyeCoin Thanks, I'll see if I can pinpoint the "bad" policy.

**Comment by web3thijs** [comment]
This issue occurs when the policy "[AppService append sites with minimum TLS version to enforce.](https://www.azadvertizer.net/azpolicyadvertizer/Append-AppService-latestTLS.html)" is enabled on version 1.0.0.

Disabling this policy will work but this is not the recommended fix.

A new version of the policy has been released (v1.1.0) which resolves the issue we were experiencing. So you or whoever manages the policies in your tenant should update this policy  to the latest version.

![image](https://github.com/user-attachments/assets/d0acab8b-a59b-4ae1-ad50-f57b91fe7ffa)
