### ISSUE TITLE
az containerapp up fails to create GitHub Action (KeyError 'workflowName')

### ISSUE THREAD

**Issue by tmacam** [Azure/azure-cli#26735]
### Describe the bug

I am getting the following error following Container Apps docs https://learn.microsoft.com/en-us/azure/container-apps/quickstart-code-to-cloud?tabs=bash%2Ccsharp&pivots=github-build and forking the `containerapps-albumapi-csharp`  repo, 

```
az containerapp up \
  --name $API_NAME \
  --resource-group $RESOURCE_GROUP \
  --location $LOCATION \
  --environment $ENVIRONMENT \
  --context-path ./src \
  --repo https://github.com/tmacam/containerapps-albumapi-csharp
Please navigate to https://github.com/login/device and enter the user code REDACTED to activate and retrieve your github personal access token
Waiting up to '14' minutes for activation
Adding external ingress port 3500 based on dockerfile expose.
Creating resource group 'album-containerapps'
Creating ContainerAppEnvironment 'env-album-containerapps' in resource group album-containerapps
No Log Analytics workspace provided.
Generating a Log Analytics workspace with name "workspace-albumcontainerappsREDACTED"
Creating Azure Container Registry REDACTED in resource group album-containerapps
Creating Containerapp album-api in resource group album-containerapps

Container app created. Access your app at https://album-api.REDACTED.canadacentral.azurecontainerapps.io/

No valid service principal provided. Creating a new service principal...
Created service principal with ID REDACTED
Verified GitHub repo and branch
Creating Github action...
The command failed with an unexpected error. Here is the traceback:
'workflowName'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 4306, in containerapp_up
    _create_github_action(app, env, service_principal_client_id, service_principal_client_secret,
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_up_utils.py", line 1064, in _create_github_action
    create_or_update_github_action(
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2816, in create_or_update_github_action
    handle_raw_exception(e)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 63, in handle_raw_exception
    raise e
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2813, in create_or_update_github_action
    await_github_action(token, repo, r["properties"]["githubActionConfiguration"]["workflowName"])
KeyError: 'workflowName'
```
Checking the contents of `r` there is indeed no `workflowName` key:

```json
{
	"id": "/subscriptions/REDACTED/resourceGroups/album-containerapps/providers/Microsoft.App/containerApps/album-api/sourcecontrols/current",
	"name": "current",
	"type": "Microsoft.App/containerapps/sourcecontrols",
	"properties": {
		"operationState": "InProgress",
		"repoUrl": "https://github.com/tmacam/containerapps-albumapi-csharp",
		"branch": "main",
		"githubActionConfiguration": {
			"registryInfo": {
				"registryUrl": "REDACTED.azurecr.io",
				"registryUserName": "REDACTED"
			},
			"contextPath": "./src/",
			"image": "album-api:${{ github.sha }}"
		}
	}
}
```

### Related command

`az containerapp up`

### Errors

```
Creating Github action...
The command failed with an unexpected error. Here is the traceback:
'workflowName'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 4306, in containerapp_up
    _create_github_action(app, env, service_principal_client_id, service_principal_client_secret,
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_up_utils.py", line 1064, in _create_github_action
    create_or_update_github_action(
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2816, in create_or_update_github_action
    handle_raw_exception(e)
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 63, in handle_raw_exception
    raise e
  File "/home/tmacam/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 2813, in create_or_update_github_action
    await_github_action(token, repo, r["properties"]["githubActionConfiguration"]["workflowName"])
KeyError: 'workflowName'
```

### Issue script & Debug output

Is there a way to automatically remove PII from this command? I think the bug description already has enough to go through but let me know.

### Expected behavior

I guess the expected behaviour is for the command not to fail -- I have no idea what is the result of the GitHub action step.

### Environment Summary

az --version
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
containerapp                      0.3.33

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/tmacam/.azure/cliextensions'

Python (Linux) 3.10.10 (main, May 19 2023, 08:20:32) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

To reproduce this, just follow https://learn.microsoft.com/en-us/azure/container-apps/quickstart-code-to-cloud?tabs=bash%2Ccsharp&pivots=github-build

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by StrawnSC** [comment]
Should be fixed by https://github.com/Azure/azure-cli-extensions/pull/6428/files

**Comment by navba-MSFT** [comment]
@tmacam Thanks for reaching out to us and reporting this issue. As mentioned above the PR https://github.com/Azure/azure-cli-extensions/pull/6428 has been filed to fix this. It is currently under review. 

Thanks @StrawnSC for the update.

**Comment by navba-MSFT** [comment]
@tmacam The above PR is now merged. The fix would be released as a part of this milestone: https://github.com/Azure/azure-cli-extensions/milestone/80
