### ISSUE TITLE
Error when installing virtual-wan extension on Ubuntu 22.04

### ISSUE THREAD

**Issue by Strobodov** [Azure/azure-cli#26748]
### Describe the bug

When trying to install the virtual-wan extension on a freshly deployed Ubuntu 22.04 VM running within Azure, an error is thrown.

### Related command

az extension add --name virtual-wan

### Errors

The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory: '/home/strobodov/.azure/cliextensions/virtual-wan/virtual_wan-0.2.17-py2.py3-none-any.whl'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 177, in _add_whl_ext
    shutil.copyfile(ext_file, dst)
  File "/opt/az/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/strobodov/.azure/cliextensions/virtual-wan/virtual_wan-0.2.17-py2.py3-none-any.whl'

### Issue script & Debug output

seems to be a file missing

### Expected behavior

I would expect the extension to be installed. It works fine on my Fedora 37 machine.

### Environment Summary

 Static hostname: hopper
       Icon name: computer-vm
         Chassis: vm
      Machine ID: 278db56daca94b71a30af6ce8346536b
         Boot ID: ccc238b973674b988d0c5cc0e7d74f8c
  Virtualization: microsoft
Operating System: Ubuntu 22.04.2 LTS              
          Kernel: Linux 5.15.0-1040-azure
    Architecture: x86-64
 Hardware Vendor: Microsoft Corporation
  Hardware Model: Virtual Machine

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/strobodov/.azure/cliextensions'

Python (Linux) 3.10.10 (main, May 19 2023, 08:20:31) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
Cannot reproduce on Ubuntu:

![image](https://github.com/Azure/azure-cli/assets/12371639/4d2bf39c-4a25-4baa-9902-b15c2d6c04c3)

**Comment by Strobodov** [comment]
Be careful: you're using azure-cli 2.48.1. I've used latest which is 2.49.0

**Comment by bebound** [comment]
Please delete `/home/strobodov/.azure/cliextensions/virtual-wan/` and try again.
If still not working, please attack the output with `--debug` param.
