### ISSUE TITLE
generate-sas CLI command fails using custom role with generateUserDelegationKey permission

### ISSUE THREAD

**Issue by praneetsharma** [Azure/azure-cli#26745]
### Describe the bug

I have a VM with user-assigned MSI attached to it. This MSI has a custom role assigned with the following permissions (with Subscription as scope where both the VM and ADLS Gen2 account reside):
```
"Microsoft.ManagedIdentity/userAssignedIdentities/read",
"Microsoft.Storage/storageAccounts/read",
"Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action"
```
As per [the documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas), the above permissions should be enough to generate SAS for this container/blob, but I get the following error:

```
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```

### Related command

```
end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
az storage blob generate-sas --container-name sl-dev-app-logs-west-us --account-name srvlessagentadlsgen2 --name d3dYoBMeYuPbzgSIKTK72W --https-only --permissions acdrw --expiry $end -o tsv --auth-mode login --as-user
```

### Errors

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['storage', 'blob', 'generate-sas', '--container-name', 'sl-dev-app-logs-west-us', '--account-name', 'srvlessagentadlsgen2', '--name', 'd3dYoBMeYuPbzgSIKTK72W', '--https-only', '--permissions', 'acdrw', '--expiry', '2023-06-23T20:42Z', '-o', 'tsv', '--auth-mode', 'login', '--as-user', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f11a53e4ae8>, <function OutputProducer.on_global_arguments at 0x7f11a4f29c80>, <function CLIQuery.on_global_arguments at 0x7f11a4ccb158>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.067        56       261
cli.azure.cli.core: Total (1)                 0.067        56       261
cli.azure.cli.core: Loaded 56 groups, 261 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage blob generate-sas
cli.azure.cli.core: Command table: storage blob generate-sas
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f11a3c5c1e0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/data/home/cldagnt/.azure/commands/2023-06-23.20-13-33.storage_blob_generate-sas.24468.log'.
az_command_data_logger: command args: storage blob generate-sas --container-name {} --account-name {} --name {} --https-only --permissions {} --expiry {} -o {} --auth-mode {} --as-user --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f11a37e6048>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 618, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_09_01.models' has no attribute 'AccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 618, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_09_01.models' has no attribute 'ListKeyExpand'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f11a372f7b8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f11a372f8c8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f11a4f29d08>, <function CLIQuery.handle_query_parameter at 0x7f11a4ccb1e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f11a372f840>]
urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254:80
urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 200 2082
msrestazure.azure_active_directory: MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory: MSI: Token retrieved
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://storage.azure.com/.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254:80
urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fstorage.azure.com&api-version=2018-02-01 HTTP/1.1" 200 2008
msrestazure.azure_active_directory: MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://storage.azure.com', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory: MSI: Token retrieved
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1687635387' -> 1687635387
urllib3.connectionpool: Starting new HTTPS connection (1): srvlessagentadlsgen2.blob.core.windows.net:443
urllib3.connectionpool: https://srvlessagentadlsgen2.blob.core.windows.net:443 "POST /?restype=service&comp=userdelegationkey HTTP/1.1" 403 279
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 410, in new_handler
    first(ex)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    raise ex
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 819, in generate_sas_blob_uri
    get_datetime_from_string(start) if start else datetime.utcnow(), get_datetime_from_string(expiry))
  File "/lib64/az/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_blob_service_client.py", line 208, in get_user_delegation_key
    process_storage_error(error)
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/blob/v2021_06_08/_shared/response_handlers.py", line 181, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError:
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:57dca449-601e-001c-5f0f-a6fb8b000000
Time:2023-06-23T20:13:33.7830611Z</Message></Error>

cli.azure.cli.core.azclierror:
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

az_command_data_logger:
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f11a3c5c400>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.059 seconds (init: 0.213, invoke: 0.846)
telemetry.save: Save telemetry record of length 3699 in cache
telemetry.check: Negative: The /data/home/cldagnt/.azure/telemetry.txt was modified at 2023-06-23 20:12:05.133585, which in less than 600.000000 s

### Expected behavior

Expected behavior is that SAS token should get generated as per the documentation

### Environment Summary

[cldagnt@vm85069107f cloud-user]$ az --version
azure-cli                         2.38.0 *

core                              2.38.0 *
telemetry                          1.0.6 *

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/bin/python3.6'
Extensions directory '/data/home/cldagnt/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Can you try adding the role or make sure the action is set at storage account level or higher?
![image](https://github.com/Azure/azure-cli/assets/17182306/46191d67-b680-45b1-bfac-20fc857d6a41)

**Comment by praneetsharma** [comment]
Hi @calvinhzy 
I have a custom role with resource-group scope and the below permission:
"Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action". I am not using built-in roles.

**Comment by calvinhzy** [comment]
Hi @praneetsharma wondering if you made the role assignment on the resource group or the user assigned managed identity. Assigning the role assignment in the resource group should work. 
![image](https://github.com/Azure/azure-cli/assets/17182306/dc416645-f501-4b38-9d4b-4cd88b0a8594)
![image](https://github.com/Azure/azure-cli/assets/17182306/a8986ab3-5e48-485d-aa2f-871e39dea9b9)
![image](https://github.com/Azure/azure-cli/assets/17182306/150336ee-2bb2-4527-86c9-34c2e79ecaba)
![image](https://github.com/Azure/azure-cli/assets/17182306/14613516-e902-4128-a51b-d151cae714c5)
![image](https://github.com/Azure/azure-cli/assets/17182306/57fb4c8c-e41f-4d25-8563-d4fff866fbd2)
