### ISSUE TITLE
`az artifacts universal download` doesn't work with user assigned managed identities

### ISSUE THREAD

**Issue by JayDoubleu** [Azure/azure-cli#26775]
### Describe the bug

`az artifacts universal download` doesn't seem to work with user assigned managed identities

### Related command

```shell
az login --identity 
az artifacts universal download  --organization https://dev.azure.com/$org  --project="$project"  --scope project  --feed $feed  --name my-first-package  --version 0.0.1  --path $path
```

### Errors

> Failed to update Universal Packages tooling.
 Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.

### Issue script & Debug output

> cli.knack.cli: Command arguments: Ä'artifacts', 'universal', 'download', '--organization', 'https://dev.azure.com/_redacted_/', '--project=_redacted_', '--scope', 'project', '--feed', '_redacted_', '--name', 'my-first-package', '--version', '0.0.1', '--path', '.', '--debug'
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute ÄÅ
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate Ä<function CLILogging.on_global_arguments at 0x7fd0164072e0>, <function OutputProducer.on_global_arguments at 0x7fd01634ae60>, <function CLIQuery.on_global_arguments at 0x7fd0161801f0>Å
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate ÄÅ
cli.azure.cli.core: Modules found from index for 'artifacts': Ä'azext_devops'Å
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: Ä'azext_ai_examples', 'azext_next'Å
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-devops              0.098        60       192  /home/azuser/.azure/cliextensions/azure-devops
cli.azure.cli.core: Total (1)                 0.098        60       192
cli.azure.cli.core: Loaded 60 groups, 192 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : artifacts universal download
cli.azure.cli.core: Command table: artifacts universal download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate Ä<function AzCliLogging.init_command_file_logging at 0x7fd01562e7a0>Å
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/azuser/.azure/commands/2023-06-28.21-08-33.artifacts_universal_download.18932.log'.
az_command_data_logger: command args: artifacts universal download --organization äå --project=äå --scope äå --feed äå --name äå --version äå --path äå --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad Ä<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fd0156472e0>Å
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad ÄÅ
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate Ä<function register_ids_argument.<locals>.add_ids_arguments at 0x7fd0156991b0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fd0156992d0>Å
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded ÄÅ
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs ÄÅ
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs Ä<function OutputProducer.handle_output_argument at 0x7fd01634aef0>, <function CLIQuery.handle_query_parameter at 0x7fd016180280>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fd015699240>, <function DevCommandsLoader.post_parse_args at 0x7fd0156d2f80>Å
az_command_data_logger: extension name: azure-devops
az_command_data_logger: extension version: 0.26.0
cli.azext_devops.dev.common.artifacttool_updater: Checking for a new ArtifactTool
cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://dev.azure.com/_redacted_
keyring.backend: Loading KWallet
keyring.backend: Loading SecretService
keyring.backend: Loading Windows
keyring.backend: Loading chainer
keyring.backend: Loading libsecret
keyring.backend: Loading macOS
cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.fail.Keyring (priority: 0)
cli.azext_devops.dev.common.credential_store: Keyring not configured properly or package not found.Looking for credentials with key:azdevops-cli:https://dev.azure.com/_redacted_ in the file: /home/azuser/.azure/azuredevops/personalAccessTokens
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli: default
cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.fail.Keyring (priority: 0)
cli.azext_devops.dev.common.credential_store: Keyring not configured properly or package not found.Looking for credentials with key:azdevops-cli: default in the file: /home/azuser/.azure/azuredevops/personalAccessTokens
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: trying to get token (temp) for tenant _redacted_ and user systemAssignedIdentity
cli.azext_devops.dev.common.services: not able to get token from az login
cli.azext_devops.dev.common.services: Tenant shouldn't be specified for managed identity account
Traceback (most recent call last):
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 157, in get_token_from_az_login
    raw = profile.get_raw_token(
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 368, in get_raw_token
    raise CLIError("Tenant shouldn't be specified for managed identity account")
knack.util.CLIError: Tenant shouldn't be specified for managed identity account
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://dev.azure.com/_redacted_
cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.fail.Keyring (priority: 0)
cli.azext_devops.dev.common.credential_store: Keyring not configured properly or package not found.Looking for credentials with key:azdevops-cli:https://dev.azure.com/_redacted_ in the file: /home/azuser/.azure/azuredevops/personalAccessTokens
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli: default
cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.fail.Keyring (priority: 0)
cli.azext_devops.dev.common.credential_store: Keyring not configured properly or package not found.Looking for credentials with key:azdevops-cli: default in the file: /home/azuser/.azure/azuredevops/personalAccessTokens
cli.azext_devops.dev.common.artifacttool_updater: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
Traceback (most recent call last):
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 59, in _get_artifacttool
    release = _get_current_release(organization, override_version)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 155, in _get_current_release
    connection = get_connection(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 43, in get_connection
    credentials = _get_credentials(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 81, in _get_credentials
    raise get_authentication_error('Before you can run Azure DevOps commands, you need to run the login command'
knack.util.CLIError: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
cli.azext_devops.dev.common.exception_handler: handling generic error
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 59, in _get_artifacttool
    release = _get_current_release(organization, override_version)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 155, in _get_current_release
    connection = get_connection(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 43, in get_connection
    credentials = _get_credentials(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 81, in _get_credentials
    raise get_authentication_error('Before you can run Azure DevOps commands, you need to run the login command'
knack.util.CLIError: Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azuser/.local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/azuser/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/artifacts/universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 57, in run_artifacttool
    artifacttool_dir = self._artifacttool_updater.get_latest_artifacttool(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 43, in get_latest_artifacttool
    artifacttool_binary_path = self._get_artifacttool(organization)
  File "/home/azuser/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool_updater.py", line 62, in _get_artifacttool
    raise CLIError('Failed to update Universal Packages tooling.Ön äå'.format(ex))
knack.util.CLIError: Failed to update Universal Packages tooling.
 Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.

cli.azure.cli.core.azclierror: Failed to update Universal Packages tooling.
 Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
az_command_data_logger: Failed to update Universal Packages tooling.
 Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.
cli.knack.cli: Event: Cli.PostExecute Ä<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fd01562e9e0>Å
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.451 seconds (init: 0.116, invoke: 0.335)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3905 in cache
telemetry.check: Negative: The /home/azuser/.azure/telemetry.txt was modified at 2023-06-28 21:06:27.976168, which in less than 600.000000 s

### Expected behavior

Azure cli should log in to azure-devops and download the artefact

### Environment Summary

```
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3'
Extensions directory '/home/azuser/.azure/cliextensions'

Python (Linux) 3.10.6 (main, May 29 2023, 11:10:38) ÄGCC 11.3.0Å

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Additional context

To Reproduce:

1. Create a user-assigned managed identity on an Azure subscription.
2. Add the user-assigned managed identity to the users of your Azure DevOps organization.
3. Add the managed identity user to an Azure DevOps group.
4. Create an Azure DevOps artifact feed and package.
5. Add the Azure DevOps group, with the managed identity user as a member, to the feed's reader permissions.
6. Create a virtual machine on the same subscription as the managed identity.
7. Assign the user-assigned managed identity to the virtual machine.
8. Install Azure CLI and run the failing command.
9. The command will return the error described in this issue.

To Fix:

1. Navigate to the following location: https://github.com/Azure/azure-cli/blob/6928cee824b2dcbc95b66976cf992a6c9d76ffe5/src/azure-cli-core/azure/cli/core/_profile.py#L368 
2. Replace the line 
`raise CLIError("Please specify only one of subscription and tenant, not both")`
 with
` tenant = False`
3. Re-run the `az artifacts universal download` command.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Adding service team to look into the devops issue.

**Comment by chaosssliu** [comment]
Hi Team, may I ask if there're any further actions regarding the fix promoted by @JayDoubleu ? I'm also encountering the same issue of using the plugin with a managed identity. Want to see when the fix will be included in future release.

**Comment by srinisudharsan** [comment]
I am facing the same issue as well. Can we please have a fix for this?

**Comment by threedot14** [comment]
Any update? Would like to use universal package with MSI as well.
