### ISSUE TITLE
unable to deactivate  allow_broker again

### ISSUE THREAD

**Issue by cforce** [Azure/azure-cli#26788]
### Describe the bug

unable to deactivate  allow_broker again

### Related command

az config unset core.allow_broker

### Errors

It fails

### Issue script & Debug output

Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
[Errno 1] Operation not permitted: '/home/wallwif/.azure/config'
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/init.py", line 663, in execute
    raise ex
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/init.py", line 726, in run_jobs_serially
    results.append(self.run_job(expanded_arg, cmd_copy))
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init.py", line 697, in run_job
    result = cmd_copy(params)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/_init.py", line 333, in call
    return self.handler(args, *kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/config/custom.py", line 93, in config_unset
    cmd.cli_ctx.config.remove_option(section, name)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/knack/config.py", line 168, in remove_option
    if config.remove_option(section, option):
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages/knack/config.py", line 247, in remove_option
    self.set(self.config_parser)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.47.0/libexec/lib/python3.10/site-packages

### Expected behavior

no fail

### Environment Summary

azure cli 2.47.0
windows 10

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by cforce** [comment]
related https://github.com/Azure/azure-cli/issues/26052

**Comment by jiasli** [comment]
The error message `[Errno 1] Operation not permitted: '/home/wallwif/.azure/config'` indicates a permission issue on `/home/wallwif/.azure/config`. Please make sure you have write permission on it.

A `~/.azure/config` file with correct permission looks like:

```
$ stat /home/user2/.azure/config
  File: /home/user2/.azure/config
  Size: 27              Blocks: 8          IO Block: 4096   regular file
Device: 820h/2080d      Inode: 66837       Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/   user2)   Gid: ( 1000/   user2)
```
