### ISSUE TITLE
Network Manager - Unable to add a network group to a connectivity configuration

### ISSUE THREAD

**Issue by ph-hector** [Azure/azure-cli#26789]
### Describe the bug

I'm trying to add a network group to an existing connectivity configuration
command: 

### Related command

az network manager connect-config update

### Errors

The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: (\'Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \\\'{\\\\\\\\\\\', \\\'groupConnectivity\\\\\\\\: \\\\\\\\DirectlyConnected\\\\\\\\,\\\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \\\'str\\\' object has no attribute \\\'get\\\'", AttributeError("\\\'str\\\' object has no attribute \\\'get\\\'"))\', DeserializationError("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))), DeserializationError: (\'Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \\\'{\\\\\\\\\\\', \\\'groupConnectivity\\\\\\\\: \\\\\\\\DirectlyConnected\\\\\\\\,\\\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \\\'str\\\' object has no attribute \\\'get\\\'", AttributeError("\\\'str\\\' object has no attribute \\\'get\\\'"))\', DeserializationError("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'")))', DeserializationError('Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \'{\\\\\', \'groupConnectivity\\\\: \\\\DirectlyConnected\\\\,\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))))
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in deserialize_iter
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in <listcomp>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1639, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1454, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1406, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1415, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1637, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in deserialize_iter
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in <listcomp>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1639, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1454, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
azure.core.exceptions.DeserializationError: ('Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \'{\\\\\', \'groupConnectivity\\\\: \\\\DirectlyConnected\\\\,\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 242, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 452, in cached_put
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 446, in _put_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "C:\Users\.azure\cliextensions\virtual-network-manager\azext_network_manager\vendored_sdks\operations\_operations.py", line 46757, in create_or_update
    _json = self._serialize.body(connectivity_configuration, 'ConnectivityConfiguration')
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 624, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1406, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1415, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1637, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in deserialize_iter
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1657, in <listcomp>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1639, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1454, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1436, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1201, in rest_key_case_insensitive_extractor
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1230, in attribute_key_case_insensitive_extractor
azure.core.exceptions.SerializationError: ('Unable to build a model: (\'Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \\\'{\\\\\\\\\\\', \\\'groupConnectivity\\\\\\\\: \\\\\\\\DirectlyConnected\\\\\\\\,\\\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \\\'str\\\' object has no attribute \\\'get\\\'", AttributeError("\\\'str\\\' object has no attribute \\\'get\\\'"))\', DeserializationError("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))), DeserializationError: (\'Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \\\'{\\\\\\\\\\\', \\\'groupConnectivity\\\\\\\\: \\\\\\\\DirectlyConnected\\\\\\\\,\\\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \\\'str\\\' object has no attribute \\\'get\\\'", AttributeError("\\\'str\\\' object has no attribute \\\'get\\\'"))\', DeserializationError("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'")))', DeserializationError('Unable to deserialize response data. Data: [<azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08520>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E08388>, <azext_network_manager.vendored_sdks.models._models_py3.ConnectivityGroupItem object at 0x05E087F0>, \'{\\\\\', \'groupConnectivity\\\\: \\\\DirectlyConnected\\\\,\'], [ConnectivityGroupItem], DeserializationError: ("Unable to deserialize to object: type, AttributeError: \'str\' object has no attribute \'get\'", AttributeError("\'str\' object has no attribute \'get\'"))', DeserializationError("Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'", AttributeError("'str' object has no attribute 'get'"))))

### Issue script & Debug output

az network manager connect-config update -g xxxxx --configuration-name yyyyy --name zzzzz --add appliesToGroups "{\"groupConnectivity\": \"DirectlyConnected\", \"isGlobal\": \"False\", \"networkGroupId\": \"/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Network/networkManagers/zzzzzzz/networkGroups/somenetworkgroup\", \"useHubGateway\": \"True\"}" --debug

[debug.txt](https://github.com/Azure/azure-cli/files/11907079/debug.txt)

### Expected behavior

the network group should be added to the connectivity configuration

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
virtual-network-manager               0.6.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\username\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ZengTaoxu** [comment]
Please replace parameter --add with parameter --applies-to-groups and try again. For example: az network manager connect-config update --applies-to-groups  network-group-id="/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Network/networkManagers/zzzzzzz/networkGroups/somenetworkgroup" use-hub-gateway="True" is-global=False group-connectivity=DirectlyConnected

**Comment by ph-hector** [comment]
Hello Zeng,
The update command just replace an existing configuration, I need to add a new definition block under the applies-to-groups object.
To make it more clear, to add a new network group in an existing configuration, without losing it.

cf. attached file for result
[debug.txt](https://github.com/Azure/azure-cli/files/11914431/debug.txt)

**Comment by ZengTaoxu** [comment]
Hi ph-hector, update cannot add a new applies-to-group, only modify it.
