### ISSUE TITLE
Getting No registered resource provider error when adding cname through azure cli

### ISSUE THREAD

**Issue by contactkanika12** [Azure/azure-cli#26863]
### Describe the bug

i am trying to add cname through azure cli in my dns zone
i am getting this error 
(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/AAAA'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/AAAA'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

### Related command

az network dns record-set cname set-record --resource-group kaguptarg --zone-name kaguptaTestZone.com --record-set-name test-cname --cname www.contoso.com

### Errors

(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/AAAA'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/AAAA'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

### Issue script & Debug output

kanika@Azure:~$ az network dns record-set cname set-record --resource-group kaguptarg --zone-name kaguptaTestZone.com --record-set-name test-cname --cname www.contoso.com --debug
cli.knack.cli: Command arguments: ['network', 'dns', 'record-set', 'cname', 'set-record', '--resource-group', 'kaguptarg', '--zone-name', 'kaguptaTestZone.com', '--record-set-name', 'test-cname', '--cname', 'www.contoso.com', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f13cbb591f0>, <function OutputProducer.on_global_arguments at 0x7f13cba73d30>, <function CLIQuery.on_global_arguments at 0x7f13cba0b310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.516       115       355
cli.azure.cli.core: privatedns                0.004        14        66
cli.azure.cli.core: Total (2)                 0.520       129       421
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.065         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.065         1         1  
cli.azure.cli.core: Loaded 129 groups, 422 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network dns record-set cname set-record
cli.azure.cli.core: Command table: network dns record-set cname set-record
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f13cac9c4c0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/kanika/.azure/commands/2023-07-11.07-30-59.network_dns_record-set_cname_set-record.206.log'.
az_command_data_logger: command args: network dns record-set cname set-record --resource-group {} --zone-name {} --record-set-name {} --cname {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f13cac450d0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f13cac21280>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f13cabc20d0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f13cba73dc0>, <function CLIQuery.handle_query_parameter at 0x7f13cba0b3a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f13cabc2040>]
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2413
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2413
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1689064581' -> 1689064581
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/bd0c277b-79f3-4800-b0d2-a71a10b8e611/resourceGroups/kaguptarg/providers/Microsoft.Network/dnsZones/kaguptaTestZone.com/CNAME/test-cname?api-version=2023-07-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e1217a84-1fbc-11ee-ae91-ca854bd4c959'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network dns record-set cname set-record'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --zone-name --record-set-name --cname --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (RPM) (AAZ) azsdk-python-core/1.26.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/bd0c277b-79f3-4800-b0d2-a71a10b8e611/resourceGroups/kaguptarg/providers/Microsoft.Network/dnsZones/kaguptaTestZone.com/CNAME/test-cname?api-version=2023-07-01-preview HTTP/1.1" 400 363
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '5fbb05bb-e732-471e-8bcd-9a0c943b8636'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '5fbb05bb-e732-471e-8bcd-9a0c943b8636'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTINDIA:20230711T073059Z:5fbb05bb-e732-471e-8bcd-9a0c943b8636'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 11 Jul 2023 07:30:59 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '363'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'."}}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2413
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2413
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1689064581' -> 1689064581
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/bd0c277b-79f3-4800-b0d2-a71a10b8e611/resourceGroups/kaguptarg/providers/Microsoft.Network/dnsZones/kaguptaTestZone.com/CNAME/test-cname?api-version=2023-07-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '74'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e1217a84-1fbc-11ee-ae91-ca854bd4c959'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network dns record-set cname set-record'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --zone-name --record-set-name --cname --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (RPM) (AAZ) azsdk-python-core/1.26.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"CNAMERecord": {"cname": "www.contoso.com"}, "TTL": 3600}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/bd0c277b-79f3-4800-b0d2-a71a10b8e611/resourceGroups/kaguptarg/providers/Microsoft.Network/dnsZones/kaguptaTestZone.com/CNAME/test-cname?api-version=2023-07-01-preview HTTP/1.1" 400 363
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '363'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9f17f538-0ee4-41b2-8c40-5580cbb6a755'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '9f17f538-0ee4-41b2-8c40-5580cbb6a755'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIAWEST:20230711T073103Z:9f17f538-0ee4-41b2-8c40-5580cbb6a755'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 11 Jul 2023 07:31:02 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 2846, in add_dns_cname_record
    return _add_save_record(cmd, record, record_type, record_set_name, resource_group_name, zone_name,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 3140, in _add_save_record
    return _record_create(cli_ctx=cmd.cli_ctx)(command_args={
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 27, in _handler
    self._execute_operations()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 376, in _execute_operations
    self.RecordSetsCreateOrUpdate(ctx=self.ctx)()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_create.py", line 400, in __call__
    return self.on_error(session.http_response)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f13cac9c700>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 4.554 seconds (init: 0.123, invoke: 4.431)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4242 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/kanika/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

it should add cname in my dns zone

### Environment Summary

kanika@Azure:~$ az --version
azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.18.0
ssh                                1.1.6

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/kanika/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by David-Noble-at-work** [comment]
Please do look into this soon. It is a blocking automation issue for me and--I expect--others. Here's my version info:

```bash
+ az --version
azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0
bastion                            0.2.4
ssh                                1.1.6

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/bin/python'
Extensions directory '.../.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
```

What do you suggest as a workaround?

**Comment by contactkanika12** [comment]
The issue is still not solved, as I am facing issues running the azure cli commands through pipeline, also in yaml file, its not allowing to downgrade azure cli. Is there any fix for use in yaml file

**Comment by nithinmohantk** [comment]
> Hi @contactkanika12,
> 
> This is not the official Azure CLI published by Microsoft.
> 
> How to tell if the installed Azure CLI is unofficial:
> 
> * [Unofficial Azure CLI deb packages are distributed by Linux repositories #19640 (comment)](https://github.com/Azure/azure-cli/issues/19640#issuecomment-1133875268)
> * [Unofficial Azure CLI deb packages are distributed by Linux repositories #19640 (comment)](https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854)
> 
> Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux to install Microsoft official Azure CLI.
> 
> If you feel that further discussion is needed, please add a comment with the text `/clibot unresolve` to reopen the issue.

Where did this bot commented that non-official CLI is used. I am using the official version, still annoyed by the error 
`ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.`
