### ISSUE TITLE
az keyvault key create --curve Ed25519 "Unsupported curve"

### ISSUE THREAD

**Issue by watermelonjam** [Azure/azure-cli#26898]
### Describe the bug

CLI help text indicates Ed25519 curve is supported:

```
az keyvault key create --help

...
Arguments
    --curve              : Elliptic curve name. For valid values, see:
                           https://docs.microsoft.com/rest/api/keyvault/keys/create-key/create-
                           key#jsonwebkeycurvename.  Allowed values: Ed25519, P-256, P-256K, P-384,
                           P-521.
...

```
Online [documentation](https://learn.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-create)  repeats this claim.  Azure itself has never heard of such a curve whether using a premium keyvault or a managed HSM.

```
az keyvault key create --curve Ed25519 --kty EC --name TestKey --vault-name TestVault
(BadParameter) Unsupported curve: "Ed25519". Supported curves are "P-256", "P-384", "P-521", "P-256K", "SECP256K1".
Code: BadParameter
Message: Unsupported curve: "Ed25519". Supported curves are "P-256", "P-384", "P-521", "P-256K", "SECP256K1".

```
```
az keyvault key create --curve Ed25519 --kty EC --name TestKey --hsm-name TestHSM
(KeyCurveNotSupported) The specified key curve is not supported (Activity ID: ec361504-2252-11ee-a5f2-000d3a84ce15)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: ec361504-2252-11ee-a5f2-000d3a84ce15)


```

### Related command

az keyvault key create

### Errors

```
(BadParameter) Unsupported curve: "Ed25519". Supported curves are "P-256", "P-384", "P-521", "P-256K", "SECP256K1".
Code: BadParameter
Message: Unsupported curve: "Ed25519". Supported curves are "P-256", "P-384", "P-521", "P-256K", "SECP256K1".
```

```
(KeyCurveNotSupported) The specified key curve is not supported (Activity ID: ec361504-2252-11ee-a5f2-000d3a84ce15)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: ec361504-2252-11ee-a5f2-000d3a84ce15)
```

### Issue script & Debug output

cli.knack.cli: Command arguments: ['keyvault', 'key', 'create', '--debug', '--curve', 'Ed25519', '--kty', 'EC', '--name', 'TestKey', '--hsm-name', 'TestHSM']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01F1A460>, <function OutputProducer.on_global_arguments at 0x0211D6A0>, <function CLIQuery.on_global_arguments at 0x021382F8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: keyvault                  0.009        22       131
cli.azure.cli.core: Total (1)                 0.009        22       131
cli.azure.cli.core: Loaded 22 groups, 131 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : keyvault key create
cli.azure.cli.core: Command table: keyvault key create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0432B418>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\someuser\.azure\commands\2023-07-14.10-44-36.keyvault_key_create.27276.log'.
az_command_data_logger: command args: keyvault key create --debug --curve {} --kty {} --name {} --hsm-name {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x043524F0>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.keyvault.v2023_02_01.azure'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.keyvault.v2023_02_01.azure'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04363418>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04363610>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0211D6E8>, <function CLIQuery.handle_query_parameter at 0x02138340>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x043635C8>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\someuser\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\someuser\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<redacted>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<redacted>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<redacted>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<redacted>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<redacted>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<redacted>/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
urllib3.connectionpool: Starting new HTTPS connection (1): testvchsm.managedhsm.azure.net:443
urllib3.connectionpool: https://<redacted>.managedhsm.azure.net:443 "POST /keys/TestKey2/create?api-version=7.4-preview.1 HTTP/1.1" 401 0
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://managedhsm.azure.net/.default',), kwargs={'tenant_id': '<redacted>'}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://managedhsm.azure.net/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: b0757a2a-350b-4eca-aba3-ebbe1662a0df
urllib3.connectionpool: https://<redacted>.managedhsm.azure.net:443 "POST /keys/TestKey/create?api-version=7.4-preview.1 HTTP/1.1" 400 146
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 112, in keyvault_command_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 1111, in create_key
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/_client.py", line 150, in create_key
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/_generated/_operations_mixin.py", line 275, in create_key
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/_generated/v7_4_preview_1/operations/_key_vault_client_operations.py", line 848, in create_key
azure.core.exceptions.HttpResponseError: (KeyCurveNotSupported) The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 138, in keyvault_command_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 51, in keyvault_exception_handler
knack.util.CLIError: (KeyCurveNotSupported) The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)

cli.azure.cli.core.azclierror: (KeyCurveNotSupported) The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
az_command_data_logger: (KeyCurveNotSupported) The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
Code: KeyCurveNotSupported
Message: The specified key curve is not supported (Activity ID: f46ee4ec-2254-11ee-bc26-000d3ae98123)
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0432B538>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.929 seconds (init: 0.308, invoke: 0.621)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3662 in cache
telemetry.check: Negative: The C:\Users\arnoldd\.azure\telemetry.txt was modified at 2023-07-14 10:44:30.911692, which in less than 600.000000 s

### Expected behavior

Creation of an Ed25519 key pair that az CLI says is possible.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\someuser\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Hi @watermelonjam, the `Ed25519` curve is still under development from service side. CLI has withdrawn exposing this option in latest version
