### ISSUE TITLE
KeyError: 'streams' when running the  az aks enable-addons command

### ISSUE THREAD

**Issue by Freddyfredy** [Azure/azure-cli#26913]
### Describe the bug

All of a sudden today the command for enabling the addons gives us an error. First we disable the addons and then we create a file called data-collection-settings.json. 

And then we call the command and it gives an error.

### Related command

az aks enable-addons -a monitoring -g ${{ parameters.azureResourceGroup }} -n ${{ parameters.azureAksCluster }} --workspace-resource-id $WORKSPACE_RESOURCE_ID --data-collection-settings data-collection-settings.json

### Errors

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'streams'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 916, in aks_enable_addons
    ensure_container_insights_for_monitoring(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/addonconfiguration.py", line 425, in ensure_container_insights_for_monitoring
    cistreams = dataCollectionSettings["streams"]
KeyError: 'streams'

### Issue script & Debug output

  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/addonconfiguration.py", line 425, in ensure_container_insights_for_monitoring
    cistreams = dataCollectionSettings["streams"]
KeyError: 'streams'

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: 'streams'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 916, in aks_enable_addons
    ensure_container_insights_for_monitoring(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/addonconfiguration.py", line 425, in ensure_container_insights_for_monitoring
    cistreams = dataCollectionSettings["streams"]
KeyError: 'streams'
ERROR: az_command_data_logger: 'streams'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 916, in aks_enable_addons
    ensure_container_insights_for_monitoring(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/addonconfiguration.py", line 425, in ensure_container_insights_for_monitoring
    cistreams = dataCollectionSettings["streams"]
KeyError: 'streams'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Expected behavior

to add the settings file

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Jun 29 2023, 11:09:14) [GCC 11.3.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@Freddyfredy Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by FumingZhang** [comment]
Hey @Freddyfredy, the specification of the config file changed a little bit (by PR [#26555](https://github.com/Azure/azure-cli/pull/26555)) in latest release (2.50.0).

Some workarounds,
1. downgrade azure-cli to 2.49.0
2. Please refer to this [sample config](https://github.com/ganga1980/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/tests/latest/data/datacollectionsettings.json#L7-L10) and update your `data-collection-settings.json` accordingly.

+ @ganga1980 please add some key checks when reading from the json file/dictionary.

**Comment by Freddyfredy** [comment]
Hi @FumingZhang thanks i have added the config and it works.
