### ISSUE TITLE
Failure at upgrade or add extensions for arcdata

### ISSUE THREAD

**Issue by v-vegujjula** [Azure/azure-cli#26915]
### Describe the bug

while upgrading or adding extensions getting errors.

My environment 
mcr.microsoft.com/azure-cli:latest 
az cli version 2.49.0 and 2.50.0 

I am trying to upgrade arcdata extension and connectedk8s extension its failing.

### Related command

I tried both ways 
az extension add arcdata 
az extension add --upgrade --name arcdata --yes

az extension add connectedk8s 
az extension add --upgrade --name connectedk8s --yes

### Errors

kubectl exec -it dummy-pod -- bash
dummy-pod:/# az -v
azure-cli                         2.49.0 *

core                              2.49.0 *
telemetry                          1.0.8

Extensions:
arcdata                            1.5.0
connectedk8s                      1.3.19
customlocation                     0.1.3
k8s-configuration                  1.7.0
k8s-extension                      1.4.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.11 (main, May 11 2023, 23:39:48) [GCC 12.2.1 20220924]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'
dummy-pod:/# az extension add --upgrade --name arcdata --yes
Extension 'arcdata' 1.5.0 is already installed.
It will be overridden with version 1.5.3.
An error occurred whilst updating.
An error occurred. Pip failed with status code 1. Use --debug for more information.
Failed to update. Rolled arcdata back to 1.5.0.

###############
dummy-pod:/# az extension remove -n arcdata

dummy-pod:/# az extension add -n arcdata
An error occurred. Pip failed with status code 1. Use --debug for more information.

### Issue script & Debug output

 https://files.pythonhosted.org/packages/63/6b/f5dc7942bac17192f4ef00b2d0cdd1ae45eea453d05c1944c0573debe945/PyYAML-6.0-cp38-cp38-manylinux_2_17_s390x.manylinux2014_s390x.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp38-cp38-manylinux1_x86_64, cp38-cp38-manylinux2010_x86_64, cp38-cp38-manylinux_2_12_x86_64, cp38-cp38-manylinux_2_5_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/d7/42/7ad4b6d67a16229496d4f6e74201bdbebcf4bc1e87d5a70c9297d4961bd2/PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp38-cp38-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/a4/ba/e508fc780e3c94c12753a54fe8f74de535741a10d33b29a576a9bec03500/PyYAML-6.0-cp38-cp38-win32.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp38-cp38-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/a8/5b/c4d674846ea4b07ee239fbf6010bcc427c4e4552ba5655b446e36b9a40a7/PyYAML-6.0-cp38-cp38-win_amd64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-macosx_10_9_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/f5/6f/b8b4515346af7c33d3b07cd8ca8ea0700ca72e8d7a750b2b87ac0268ca4e/PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-macosx_11_0_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/67/d4/b95266228a25ef5bd70984c08b4efce2c035a4baa5ccafa827b266e3dc36/PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux2014_aarch64, cp39-cp39-manylinux_2_17_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/21/67/b42191239c5650c9e419c4a08a7a022bbf1abf55b0391c380a72c3af5462/PyYAML-6.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux2014_s390x, cp39-cp39-manylinux_2_17_s390x) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/77/da/e845437ffe0dffae4e7562faf23a4f264d886431c5d2a2816c853288dc8e/PyYAML-6.0-cp39-cp39-manylinux_2_17_s390x.manylinux2014_s390x.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-manylinux1_x86_64, cp39-cp39-manylinux2010_x86_64, cp39-cp39-manylinux_2_12_x86_64, cp39-cp39-manylinux_2_5_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/12/fc/a4d5a7554e0067677823f7265cb3ae22aed8a238560b5133b58cda252dad/PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/2e/b3/13dfd4eeb5e4b2d686b6d1822b40702e991bf3a4194ca5cbcce8d43749db/PyYAML-6.0-cp39-cp39-win32.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Skipping link: none of the wheel's tags (cp39-cp39-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/08/f4/ffa743f860f34a5e8c60abaaa686f82c9ac7a2b50e5a1c3b1eb564d59159/PyYAML-6.0-cp39-cp39-win_amd64.whl (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6)
  Found link https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz (from https://pypi.org/simple/pyyaml/) (requires-python:>=3.6), version: 6.0
Skipping link: not a file: https://pypi.org/simple/pyyaml/
Given no hashes to check 2 links for project 'pyyaml': discarding no candidates
Collecting pyyaml>=5.4.1
  Created temporary directory: /tmp/pip-unpack-iyw0n53s
  https://files.pythonhosted.org:443 "GET /packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz HTTP/1.1" 200 124996
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 162.6 MB/s eta 0:00:00
  Added pyyaml>=5.4.1 from https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz (from kubernetes==23.3.0->arcdata==1.5.3) to build tracker '/tmp/pip-build-tracker-1fxo1ch0'
  Created temporary directory: /tmp/pip-build-env-iguyqdmd
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Using pip 23.0.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
  Collecting setuptools
    Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Collecting Cython
    Using cached Cython-3.0.0-cp310-cp310-musllinux_1_1_x86_64.whl (3.6 MB)
  Installing collected packages: wheel, setuptools, Cython
    Creating /tmp/pip-build-env-iguyqdmd/overlay/bin
    changing mode of /tmp/pip-build-env-iguyqdmd/overlay/bin/wheel to 755
    changing mode of /tmp/pip-build-env-iguyqdmd/overlay/bin/cygdb to 755
    changing mode of /tmp/pip-build-env-iguyqdmd/overlay/bin/cython to 755
    changing mode of /tmp/pip-build-env-iguyqdmd/overlay/bin/cythonize to 755
  Successfully installed Cython-3.0.0 setuptools-68.0.0 wheel-0.40.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

  [notice] A new release of pip is available: 23.0.1 -> 23.2
  [notice] To update, run: pip install --upgrade pip
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  running egg_info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
      self.find_sources()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
      mm.run()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 204, in get_source_files
    File "/tmp/pip-build-env-iguyqdmd/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/bin/python /usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp5y6lt1f3
  cwd: /tmp/pip-install-usf6at8o/pyyaml_817dc06e49a149be91b29267d3346033
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
Removed pyyaml>=5.4.1 from https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz (from kubernetes==23.3.0->arcdata==1.5.3) from build tracker '/tmp/pip-build-tracker-1fxo1ch0'
Removed build tracker: '/tmp/pip-build-tracker-1fxo1ch0'

cli.azure.cli.core.extension.operations: Command '['/usr/local/bin/python', '-m', 'pip', 'install', '--target', '/root/.azure/cliextensions/arcdata', '/tmp/tmpkdd89pss/arcdata-1.5.3-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /root/.azure/cliextensions/arcdata
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f19aeee2dd0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 9.831 seconds (init: 0.339, invoke: 9.492)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3402 in cache
telemetry.check: Negative: The /root/.azure/telemetry.txt was modified at 2023-07-17 20:44:44.024874, which in less than 600.000000 s

### Expected behavior

It should install respective latest extension versions for arcdata and connectedk8s 

### Environment Summary

dummy-pod:/# az -v
azure-cli                         2.49.0 *

core                              2.49.0 *
telemetry                          1.0.8

Extensions:
connectedk8s                      1.3.19
customlocation                     0.1.3
k8s-configuration                  1.7.0
k8s-extension                      1.4.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.11 (main, May 11 2023, 23:39:48) [GCC 12.2.1 20220924]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

##############

dummy-pod:/# az -v
azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.12 (main, Jun 15 2023, 03:17:49) [GCC 12.2.1 20220924]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I tried to verify in both azure cli version 2.49.0 and 2.50.0 issue is there in both versions.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@v-vegujjula Thanks for reaching out to us and reporting this issue. Could you please confirm if you have updated your CLI to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli) (2.50.0) ? You can run the `az --version `command to confirm.

If Yes, Could you please remove the extension and install it again ?

> az extension remove --name MyExtension

After it is removed, you can try installing it again and check if that helps.

> az extension add --name Myextension


Awaiting your reply.

**Comment by v-vegujjula** [comment]
Hi Team
I saw this issue on that day only. Later its working fine. 
For me I am unblocked now. we can close this issue.
Thanks for quick support.

**Comment by navba-MSFT** [comment]
@v-vegujjula Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
