### ISSUE TITLE
ERROR: API version 2022-05-01 does not have operation group │ 'storage_accounts'

### ISSUE THREAD

**Issue by bpriyas92** [Azure/azure-cli#26945]
### Describe the bug

Unable to execute terraform null_resource with az command to set network rule for storage account

### Related command

az storage account network-rule add --resource-id ${azurerm_machine_learning_workspace.ws.id} --tenant-id ${data.azurerm_client_config.current.tenant_id} -g ${local.datastores[count.index].storage_resource_group_name} --account-name ${local.datastores[count.index].storage_name}

### Errors

│ Error: local-exec provisioner error
│ 
│   with null_resource.storage_resource_instance[0],
│   on main.tf line 169, in resource "null_resource" "storage_resource_instance":
│  169:   provisioner "local-exec" {
│ 
│ Error running command 'az storage account network-rule add --resource-id': exit status
│ 1. Output: ERROR: The command failed with an unexpected error. Here is the
│ traceback:
│ ERROR: API version 2022-05-01 does not have operation group
│ 'storage_accounts'
│ Traceback (most recent call last):
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
│     raise ex
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
│     result = cmd_copy(params)
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
│     return self.handler(*args, **kwargs)
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
│     client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 138, in cf_sa
│     return storage_client_factory(cli_ctx).storage_accounts
│   File "/home/nub2kor/.local/lib/python3.8/site-packages/azure/mgmt/storage/_storage_management_client.py", line 832, in storage_accounts
│     raise ValueError("API version {} does not have operation group 'storage_accounts'".format(api_version))
│ ValueError: API version 2022-05-01 does not have operation group
│ 'storage_accounts'
│ To open an issue, please run: 'az feedback'

### Issue script & Debug output

NA

### Expected behavior

NA

### Environment Summary

azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
ml                                 2.8.0
account                            0.2.5

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
