### ISSUE TITLE
az storage blob download taking too long to start downloading

### ISSUE THREAD

**Issue by prashantguleria** [Azure/azure-cli#27028]
### Describe the bug

When downloading a blob file using the az cli, It takes too long to just start the download/ receive first byte of the response.

It was working fine till last week, I have tried downgrading to multiple az cli versions ranging from 2.38 to 2.5 but same behavour is observed in all versions.

If i generate a sas full uri , the download starts immediately.

### Related command

az storage blob download --account-name {} --account-key {} --container-name {} --name {} --file {} --max-connections 4 --debug

### Errors

There are no errors, but it takes around 7-8 minutes just to start receving the content from the blob storage endpoint.

I have tried multiple ISP's as well as an azure linux VM with Ubuntu where the behaviour is similar.

### Issue script & Debug output

```
 az storage blob download --account-name storageaccountname --account-key storageaccountkey --container-name build-artifacts --name "20230627.5/file.zip.zip" --file "/Users/pg/Artifacts/environments/dev/20230627.5/file.zip.zip" --max-connections 4 --debug
cli.knack.cli: Command arguments: ['storage', 'blob', 'download', '--account-name', 'storageaccountname', '--account-key', 'storageaccountkey', '--container-name', 'build-artifacts', '--name', '20230627.5/file.zip.zip', '--file', '/Users/pg/Artifacts/environments/dev/20230627.5/file.zip.zip', '--max-connections', '4', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x100dea0e0>, <function OutputProducer.on_global_arguments at 0x100e770a0>, <function CLIQuery.on_global_arguments at 0x100ee0550>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.023        58       272
cli.azure.cli.core: Total (1)                 0.023        58       272
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 58 groups, 272 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage blob download
cli.azure.cli.core: Command table: storage blob download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10198eb90>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/pg/.azure/commands/2023-07-28.14-33-42.storage_blob_download.55953.log'.
az_command_data_logger: command args: storage blob download --account-name {} --account-key {} --container-name {} --name {} --file {} --max-connections {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10199f520>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 659, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 659, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 659, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x101a79240>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x101a79360>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x100e77130>, <function CLIQuery.handle_query_parameter at 0x100ee05e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x101a792d0>]
cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
urllib3.connectionpool: Starting new HTTPS connection (1): storageaccountname.blob.core.windows.net:443
urllib3.connectionpool: https://storageaccountname.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip.zip HTTP/1.1" 206 33554432

```

It got stuck here for around 7-8 minutes and logged the statements below:

```
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 33554432
Alive[###################                                             ]  31.2115%urllib3.connectionpool: Starting new HTTPS connection (2): storageaccount.blob.core.windows.net:443
urllib3.connectionpool: Starting new HTTPS connection (3): storageaccount.blob.core.windows.net:443
urllib3.connectionpool: Starting new HTTPS connection (4): storageaccount.blob.core.windows.net:443
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[########################                                        ]  39.0143%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[###########################                                     ]  42.9158%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[#############################                                   ]  46.8172%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[################################                                ]  50.7186%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[#####################################                           ]  58.5215%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[#######################################                         ]  62.4229%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[##########################################                      ]  66.3244%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[############################################                    ]  70.2258%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[#################################################               ]  78.0287%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[####################################################            ]  81.9301%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 4194304
Alive[#########################################################       ]  89.7330%urllib3.connectionpool: https://storageaccount.blob.core.windows.net:443 "GET /build-artifacts/20230627.5/file.zip HTTP/1.1" 206 2649147
Finished[#############################################################]  100.0000%
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x101a56830>, <function _x509_from_base64_to_hex_transform at 0x101a568c0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []

cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10198edd0>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 801.081 seconds (init: 0.076, invoke: 801.005)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3534 in cache
```

### Expected behavior

The download should start immediately or if any error/warnings are present should be logged.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
account                            0.2.5

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/bin/python'
Extensions directory '/Users/pg/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Wondering if the same behavior still occurs with the latest version? Do you perhaps have a lot of blobs in the container? Does `az storage blob show` also take a long time? What is the blob file size? Thanks.

**Comment by prashantguleria** [comment]
It started to work fine with latest version, Thhere were only 5-6 blobs in my container.
