### ISSUE TITLE
az dla job submit throws api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'

### ISSUE THREAD

**Issue by novablinkicelance** [Azure/azure-cli#27026]
### Describe the bug

`az dla job submit --account $Account --job-name "Test Job" --script scope_test.script`
Throws: api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'

Account, and Script are valid.

az --version
azure-cli                         2.50.0
core                              2.50.0
telemetry                          1.0.8
Extensions:
azure-devops                      0.26.0
Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\[user]\.azure\cliextensions'
Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
Your CLI is up-to-date.

### Related command

`az dla job submit`

### Errors

api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['dla', 'job', 'submit', '--account', '', '--job-name', 'Test Job', '--script', 'scope_test.script', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0253B580>, <function OutputProducer.on_global_arguments at 0x0273E7C0>, <function CLIQuery.on_global_arguments at 0x02758418>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'dla': ['azure.cli.command_modules.dla']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: dla                       0.005        23        62
cli.azure.cli.core: Total (1)                 0.005        23        62
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 23 groups, 62 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : dla job submit
cli.azure.cli.core: Command table: dla job submit
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x048FD4F0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\\.azure\commands\2023-07-27.22-51-00.dla_job_submit.26804.log'.
az_command_data_logger: command args: dla job submit --account {} --job-name {} --script {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04925A48>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0494C9B8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0494CBB0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0273E808>, <function CLIQuery.handle_query_parameter at 0x02758460>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0494CB68>]
Command group 'dla' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=DataLakeAnalyticsJobManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com//discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com//v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com//oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com//kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': 'bac04edb-2d0a-11ee-ba8a-000d3ac67f33'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'dla job submit'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--account --job-name --script --debug'
msrest.service_client: Accept header absent and forced to application/json
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.signed_session
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://datalake.azure.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 
msrest.http_logger: Request URL: 'https://.azuredatalakeanalytics.net/Jobs/?api-version=2016-11-01'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '143'
msrest.http_logger:     'User-Agent': 'python/3.10.10 (Windows-10-10.0.22621-SP0) msrest/0.7.1 msrest_azure/0.6.4 datalakeanalyticsjobmanagementclient/0.1.6 Azure-SDK-For-Python AZURECLI/2.50.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: {"type": "USql", "properties": {"script": "scope_test.script", "type": "USql"}, "name": "Test Job", "degreeOfParallelism": 1, "priority": 1000}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): .azuredatalakeanalytics.net:443
urllib3.connectionpool: https://.azuredatalakeanalytics.net:443 "PUT /Jobs/?api-version=2016-11-01 HTTP/1.1" 400 None
msrest.http_logger: Response status: 400
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'private, no-cache, no-store, max-age=0'
msrest.http_logger:     'Transfer-Encoding': 'chunked'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'x-ms-request-id': ''
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'
msrest.http_logger:     'Date': 'Fri, 28 Jul 2023 05:51:00 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"error":{"code":"InvalidArgument","message":"api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'"}}
msrest.exceptions: api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/dla/custom.py", line 291, in submit_adla_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/datalake/analytics/job/operations/job_operations.py", line 358, in create
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidArgument
Message: api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'

cli.azure.cli.core.azclierror: api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'
az_command_data_logger: api-version '2016-11-01' is invalid. Valid api-version: '2017-09-01-preview'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x048FD610>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.069 seconds (init: 0.496, invoke: 0.573)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3476 in cache
telemetry.check: Negative: The C:\Users\\.azure\telemetry.txt was modified at 2023-07-27 22:44:00.681437, which in less than 600.000000 s

### Expected behavior

Job submits successfully.

### Environment Summary

az --version
azure-cli                         2.50.0
core                              2.50.0
telemetry                          1.0.8
Extensions:
azure-devops                      0.26.0
Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\[user]\.azure\cliextensions'
Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ligz08** [comment]
Still running into the same problem as of Aug 2024, with Azure CLI version 2.63.0

```
> az --version
azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\***\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
