### ISSUE TITLE
Documentation for aks update/create wrong wording

### ISSUE THREAD

**Issue by alfeg** [Azure/azure-cli#27022]
### Describe the bug

Documentation says that
```
--ca-profile --cluster-autoscaler-profile
Space-separated list of key=value pairs for configuring cluster autoscaler. Pass an empty string to clear the profile.
```
When I try to pass `--ca-profile 'scale-down-delay-after-add=3m,scale-down-unneeded-time=3m'` command fails with error
```
The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.
```

### Related command

`az aks update`
and
`az aks create`

### Errors

The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.

### Issue script & Debug output

```
az aks update -n aks-xRedactedx-dev-eu -g rg-app-dev-eu --ca-profile 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' --debug
```
```
cli.knack.cli: Command arguments: ['aks', 'update', '-n', 'aks-xRedactedx-dev-eu', '-g', 'rg-app-dev-eu', '--ca-profile', 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x017BA3D0>, <function OutputProducer.on_global_arguments at 0x01988B68>, <function CLIQuery.on_global_arguments at 0x019A97C0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azext_aks_preview', 'azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.078         6        48
cli.azure.cli.core: Total (1)                 0.078         6        48
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: aks-preview               0.010        14        75  C:\Users\xxx\.azure\cliextensions\aks-preview
cli.azure.cli.core: Total (1)                 0.010        14        75  
cli.azure.cli.core: Loaded 16 groups, 86 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks update
cli.azure.cli.core: Command table: aks update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03C7A388>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\xxx\.azure\commands\2023-07-27.19-03-57.aks_update.19088.log'.
az_command_data_logger: command args: aks update -n {} -g {} --ca-profile {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03CA5460>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03CB3538>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03CB35C8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01988BB0>, <function CLIQuery.handle_query_parameter at 0x019A9808>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03CB3580>]
az_command_data_logger: extension name: aks-preview
az_command_data_logger: extension version: 0.5.149
cli.azure.cli.core.commands: The behavior of this command has been altered by the following extension: aks-preview
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\xxx\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\xxx\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xRedactedx-41ca-4d5a-8e28-0e81ae3c3f96/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\xxxx\.azure\cliextensions\aks-preview\azext_aks_preview\custom.py", line 769, in aks_update
    mc = aks_update_decorator.update_mc_profile_preview()
  File "C:\Users\xxxx\.azure\cliextensions\aks-preview\azext_aks_preview\managed_cluster_decorator.py", line 3632, in update_mc_profile_preview
    mc = self.update_mc_profile_default()
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 7004, in update_mc_profile_default
  File "C:\Users\xxxx\.azure\cliextensions\aks-preview\azext_aks_preview\managed_cluster_decorator.py", line 2998, in check_raw_parameters
    for pair in self.get_special_parameter_default_value_pairs_list():
  File "C:\Users\xxxx\.azure\cliextensions\aks-preview\azext_aks_preview\managed_cluster_decorator.py", line 2969, in get_special_parameter_default_value_pairs_list
    (self.context.get_cluster_autoscaler_profile(), None),
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 4040, in get_cluster_autoscaler_profile
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 4001, in _get_cluster_autoscaler_profile
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/managed_cluster_decorator.py", line 344, in __validate_cluster_autoscaler_profile
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/_validators.py", line 536, in extract_comma_separated_string
azure.cli.core.azclierror.InvalidArgumentValueError: The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.

cli.azure.cli.core.azclierror: The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.
az_command_data_logger: The format of 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' in 'scale-down-delay-after-add=3m scale-down-unneeded-time=3m' is incorrect, correct format should be 'Key1=Value1,Key2=Value2'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03C7A4A8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.992 seconds (init: 0.358, invoke: 0.634)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3659 in cache
telemetry.check: Negative: The C:\Users\xxxx\.azure\telemetry.txt was modified at 2023-07-27 18:56:11.241179, which in less than 600.000000 s
```

### Expected behavior

Command executed without error 

### Environment Summary

azure-cli                         2.49.0 *

core                              2.49.0 *
telemetry                          1.0.8

Extensions:
aks-preview                      0.5.149
containerapp                      0.3.36
front-door                        1.0.17
k8s-extension                      1.4.2
maintenance                        1.3.0
storage-blob-preview               0.7.2
storage-preview                    0.8.4

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by alfeg** [comment]
Sorry @azure-client-tools-bot-prd but I cannot do this. Because Azure DNS Zones are broken in 2.50.0

**Comment by navba-MSFT** [comment]
@alfeg Thanks for reaching out to us and reporting this issue. I understand that the **space** separated key value pair is failing.

Could you please confirm with the `--ca-profile `parameter value set to` scale-down-delay-after-add=3m,scale-down-unneeded-time=3m` which is **comma** separated and test ? Awaiting your reply.

**Comment by alfeg** [comment]
Yes comma separated values works fine.

пт, 28 июл. 2023 г., 07:26 navba-MSFT ***@***.***>:

**Comment by navba-MSFT** [comment]
@alfeg Thanks for getting back. I have created the PR to address the documentation issue.
