### ISSUE TITLE
Cannot Export Azure DNS Zone (multiple Azure CLI versions)

### ISSUE THREAD

**Issue by GreatState** [Azure/azure-cli#27021]
### Describe the bug

We are trying to run the following command

az network dns zone export -g XXXXX -n XXXXX.XXX -f XXXXXX.txt 

As instructed here - https://learn.microsoft.com/en-us/azure/dns/dns-import-export#export-a-dns-zone-file-from-azure-dns

Using these version 

https://github.com/Azure/azure-cli/releases/download/azure-cli-2.49.0/azure-cli-2.49.0.msi

https://github.com/Azure/azure-cli/releases/download/azure-cli-2.48.1/azure-cli-2.48.1.msi

v2.50.0 has it's own issues.  Which is why we were directed to use a previous.  Might i add.  That NO support info is provided to install previous versions of Azure CLI.  Not that we could find anyway.

- https://github.com/Azure/azure-cli/issues/26813
- https://github.com/Azure/azure-cli/issues/23985#issue-1383263012

But we keep getting the following error

`The command failed with an unexpected error. Here is the traceback:
'txt'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 2649, in export_zone
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/make_zone_file.py", line 94, in make_zone_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 126, in process_txt
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 55, in _quote_field
KeyError: 'txt'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback``

We've lost a lot of time messing around with this.

Why this export function is not included in the portal is beyond me.  Import/export is a standard operation.  This needs to be added.

### Related command

az network dns zone export -g XXXXX -n XXXXX.XXX -f XXXXXX.txt 

### Errors

`The command failed with an unexpected error. Here is the traceback:
'txt'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 2649, in export_zone
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/make_zone_file.py", line 94, in make_zone_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 126, in process_txt
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 55, in _quote_field
KeyError: 'txt'`

### Issue script & Debug output

az network dns zone export -g XXXXX -n XXXXX.XXX -f XXXXXX.txt 

### Expected behavior

We are trying to download the zone file

### Environment Summary

{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by GreatState** [comment]
> Hi @GreatState Find similar issue #23645.
> 
> Issue title	can't export dns zone
> Create time	2022-08-23
> Comment number	4
> Possible solution: . The error message you are seeing is caused by the null value of type "txt" in your DNS zone. One possible solution is to delete this "txt" record in the export file. Another solution is to export type "txt" with an empty value. You can try these solutions and see if they work for you.
> 
> Please confirm if this resolves your issue.

Hi All 

Yes.  There was a empty TXT record in the zone file.  I removed this and reran the export command.  This worked

az network dns zone export -g XXXX -n XXXX -f XXXX.txt

Thanks for the help
