### ISSUE TITLE
az ml model download doesn't work for hugging face registry

### ISSUE THREAD

**Issue by istairbn** [Azure/azure-cli#27068]
### Describe the bug

I'm trying to download a model from Hugging Face registry to my machine (to move into a private registry)
https://learn.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest#az-ml-model-download

I can pull from the azureml registry and my private one, but the Huggingface one does not work. I assume this is because the v2 CLI no longer accepts ID and instead insists on parsing it itself. 

### Related command

The following command DOES work - demonstrating the principle that I can pull from a registry
```
az ml model download --name microsoft-deberta-base --version 9 --registry-name azureml
```
The following command does NOT work and produces the error
```
az ml model download --name microsoft-deberta-base --version 14 --registry-name HuggingFace

Met error <class 'Exception'>:Registry asset URI could not be parsed.
Please check log by running the command with '--debug' for more details.
```

### Errors

Met error <class 'Exception'>:Registry asset URI could not be parsed.
Please check log by running the command with '--debug' for more details.

### Issue script & Debug output

Request body:
This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): cert-eastus.experiments.azureml.net:443
urllib3.connectionpool: https://cert-eastus.experiments.azureml.net:443 "GET /mferp/managementfrontend/subscriptions/d5210851-d1ca-44ac-8071-a0c7191e9631/resourceGroups/prod-azure-ml-registry/providers/Microsoft.MachineLearningServices/registries/HuggingFace/models/microsoft-deberta-base/versions/14?api-version=2021-10-01-dataplanepreview HTTP/1.1" 200 None
azure.core.pipeline.policies._universal: Response status: '200'
Response headers:
    'Date': 'Wed, 02 Aug 2023 13:59:28 GMT'
    'Content-Type': 'application/json; charset=utf-8'
    'Transfer-Encoding': 'chunked'
    'Connection': 'keep-alive'
    'Vary': 'Accept-Encoding'
    'Request-Context': 'appId=cid-v1:2d2e8e63-272e-4b3c-8598-4ee570a0e70d'
    'x-ms-response-type': 'standard'
    'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'
    'X-Content-Type-Options': 'nosniff, nosniff'
    'x-aml-cluster': 'vienna-eastus-01'
    'x-request-time': '0.364'
    'Content-Encoding': 'gzip'
Response content:
{
  "id": "azureml://registries/HuggingFace/models/microsoft-deberta-base/versions/14",
  "name": "microsoft-deberta-base",
  "type": "models",
  "properties": {
    "description": "`microsoft/deberta-base` is a pre-trained language model available on the Hugging Face Hub. It's specifically designed for the `fill-mask` task in the `transformers` library. If you want to learn more about the model's architecture, hyperparameters, limitations, and biases, you can find this information on the model's dedicated [Model Card on the Hugging Face Hub](https://huggingface.co/microsoft/deberta-base).\n\nHere's an example API request payload that you can use to obtain predictions from the model:\n```\n{\n  \"inputs\": \"Paris is the [MASK] of France.\"\n}\n```\n",
    "tags": {
      "modelId": "microsoft/deberta-base",
      "task": "fill-mask",
      "library": "transformers",
      "license": "mit",
      "author": "microsoft"
    },
    "properties": {
      "skuBasedEngineIds": "azureml://registries/HuggingFace/models/transformers-cpu-small/labels/latest,azureml://registries/HuggingFace/models/transformers-gpu-medium/labels/latest",
      "engineEnvironmentVariableOverrides": "{\"AZUREML_HF_MODEL_ID\": \"microsoft/deberta-base\", \"AZUREML_HF_TASK\": \"fill-mask\"}"
    },
    "isArchived": false,
    "isAnonymous": false,
    "flavors": {},
    "modelType": "preset_model",
    "modelUri": null,
    "originAssetId": "azureml://locations/eastus/workspaces/4dc95ec5-8c35-4023-840a-a15dfa91ac1f/models/microsoft-deberta-base/versions/14",
    "jobName": null,
    "intellectualProperty": null
  },
  "systemData": {
    "createdAt": "2023-05-17T12:29:13.1296138+00:00",
    "createdBy": "HuggingFace",
    "createdByType": "User",
    "lastModifiedAt": "2023-05-17T12:29:10.6227599+00:00",
    "lastModifiedBy": "Philipp Schmid",
    "lastModifiedByType": "User"
  }
}
Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 187, in get_ds_name_and_path_prefix
    split_paths = re.findall(STORAGE_URI_REGEX, asset_uri)
  File "re.py", line 240, in findall
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\custom\model.py", line 116, in ml_model_download
    ml_client.models.download(name=name, version=version, download_path=download_path)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_telemetry\activity.py", line 263, in wrapper
    return f(*args, **kwargs)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\operations\_model_operations.py", line 317, in download
    ds_name, path_prefix = get_ds_name_and_path_prefix(model_uri, self._registry_name)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 190, in get_ds_name_and_path_prefix
    raise Exception("Registry asset URI could not be parsed.") from e
Exception: Registry asset URI could not be parsed.
cli: None
cli: Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 187, in get_ds_name_and_path_prefix
    split_paths = re.findall(STORAGE_URI_REGEX, asset_uri)
  File "re.py", line 240, in findall
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\custom\model.py", line 116, in ml_model_download
    ml_client.models.download(name=name, version=version, download_path=download_path)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_telemetry\activity.py", line 263, in wrapper
    return f(*args, **kwargs)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\operations\_model_operations.py", line 317, in download
    ds_name, path_prefix = get_ds_name_and_path_prefix(model_uri, self._registry_name)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 190, in get_ds_name_and_path_prefix
    raise Exception("Registry asset URI could not be parsed.") from e
Exception: Registry asset URI could not be parsed.

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 187, in get_ds_name_and_path_prefix
    split_paths = re.findall(STORAGE_URI_REGEX, asset_uri)
  File "re.py", line 240, in findall
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\custom\model.py", line 116, in ml_model_download
    ml_client.models.download(name=name, version=version, download_path=download_path)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_telemetry\activity.py", line 263, in wrapper
    return f(*args, **kwargs)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\operations\_model_operations.py", line 317, in download
    ds_name, path_prefix = get_ds_name_and_path_prefix(model_uri, self._registry_name)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\_storage_utils.py", line 190, in get_ds_name_and_path_prefix
    raise Exception("Registry asset URI could not be parsed.") from e
Exception: Registry asset URI could not be parsed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\custom\model.py", line 118, in ml_model_download
    log_and_raise_error(err, debug)
  File "REDACTED\.azure\cliextensions\ml\azext_mlv2\manual\custom\raise_error.py", line 181, in log_and_raise_error
    raise cli_error
knack.util.CLIError: Met error <class 'Exception'>:Registry asset URI could not be parsed.
Please check log by running the command with '--debug' for more details.

cli.azure.cli.core.azclierror: Met error <class 'Exception'>:Registry asset URI could not be parsed.
Please check log by running the command with '--debug' for more details.
az_command_data_logger: Met error <class 'Exception'>:Registry asset URI could not be parsed.
Please check log by running the command with '--debug' for more details.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04A6B658>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 5.193 seconds (init: 0.496, invoke: 4.697)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3911 in cache
telemetry.check: Negative: The REDACTED\.azure\telemetry.txt was modified at 2023-08-02 14:57:21.109486, which in less than 600.000000 s

### Expected behavior

I should be able to download the model from this registry in the same way as any other

### Environment Summary

azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.21.0
ml                                2.19.1
ssh                                1.1.2

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@istairbn Thanks for reaching out to us and reporting this issue. Please follow the steps provided [here](https://stackoverflow.com/a/76603578/17951893) and check if that helps.

**Comment by navba-MSFT** [comment]
@istairbn I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@istairbn The action is pending on you to try the suggestion provided [here](https://stackoverflow.com/a/76603578/17951893). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
