### ISSUE TITLE
az artifacts universal download ERROR: TF400813: The user '{GUID}' is not authorized to access this resource.

### ISSUE THREAD

**Issue by jcoliz** [Azure/azure-cli#27089]
### Describe the bug

I have been using `az artifacts universal download` to download artifacts from universal packages successfully now for about a month.

Yesterday, `az upgrade` failed, leaving my az cli in an inoperable state. So I uninstalled it, and re-installed again.

Since that change, this command produces this error.

Things I've tried
1. az logout/az login
2. getting a *new* PAT with Packaging (Read) permissions, and then `az devops login --organization https://dev.azure.com/jcoliz/`
3. `rmdir ~\.azure\azuredevops\`, and repeating above steps
4. `rm ~\.azure\msal*.*`, and repeating above

Yes, I verified that my user account is still listed as the Owner of the package feed.

### Related command

```
az artifacts universal download --organization "https://dev.azure.com/jcoliz/" --project "8257bdfd-5bba-4d04-a064-9d1c720d3b35" --scope project --feed "brewhub-debs" --name "still6unitcontroller" --version "0.2.0" --path bin
```

### Errors

```
An error occurred on the service. TF400813: The user '[redacted]' is not authorized to access this resource.
Process ['C:\\Users\\[me]\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.289\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/jcoliz/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'brewhub-debs', '--package-name', 'still6unitcontroller', '--package-version', '0.2.0', '--path', 'bin', '--project', '8257bdfd-5bba-4d04-a064-9d1c720d3b35'] with PID 6880 exited with return code 1
```

### Issue script & Debug output

```
DEBUG: cli.knack.cli: Command arguments: ['artifacts', 'universal', 'download', '--organization', 'https://dev.azure.com/jcoliz/', '--project', '8257bdfd-5bba-4d04-a064-9d1c720d3b35', '--scope', 'project', '--feed', 'brewhub-debs', '--name', 'still6unitcontroller', '--version', '0.1.14', '--path', 'bin', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01B1B5C8>, <function OutputProducer.on_global_arguments at 0x01D1E808>, <function CLIQuery.on_global_arguments at 0x01D39460>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'artifacts': ['azext_devops']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: azure-devops              0.083        60       192  C:\Users\JamesColiz\.azure\cliextensions\azure-devops
DEBUG: cli.azure.cli.core: Total (1)                 0.083        60       192  
DEBUG: cli.azure.cli.core: Loaded 60 groups, 192 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : artifacts universal download
DEBUG: cli.azure.cli.core: Command table: artifacts universal download
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03F1C730>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\JamesColiz\.azure\commands\2023-08-03.19-35-48.artifacts_universal_download.13172.log'.
INFO: az_command_data_logger: command args: artifacts universal download --organization {} --project {} --scope {} --feed {} --name {} --version {} --path {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F43898>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F4F808>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F4FA00>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01D1E850>, <function CLIQuery.handle_query_parameter at 0x01D394A8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03F4F9B8>, <function DevCommandsLoader.post_parse_args at 0x03F85928>]
INFO: az_command_data_logger: extension name: azure-devops
INFO: az_command_data_logger: extension version: 0.26.0
DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Checking for a new ArtifactTool
DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
DEBUG: cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://dev.azure.com/jcoliz
INFO: keyring.backend: Loading KWallet
INFO: keyring.backend: Loading SecretService
INFO: keyring.backend: Loading Windows
DEBUG: win32ctypes.core.cffi: Loaded cffi backend
INFO: keyring.backend: Loading chainer
INFO: keyring.backend: Loading macOS
DEBUG: cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
DEBUG: cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
DEBUG: cli.azure.cli.core: Current cloud config:
AzureCloud
DEBUG: cli.azext_devops.dev.common.services: trying to get token (temp) for tenant e89963f8-f5c7-4033-8000-40321901d2c1 and user jcoliz@outlook.com 
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\JamesColiz\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\JamesColiz\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 3f26457a-84b0-457c-a969-d1d04857482e
DEBUG: cli.azext_devops.dev.common.services: instance recieved in validate_token_for_instance https://dev.azure.com/jcoliz/
DEBUG: cli.azext_devops.dev.common.services: instance processed in validate_token_for_instance https://dev.azure.com/jcoliz/
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\JamesColiz\.azure-devops\python-sdk\cache\resources.json
DEBUG: azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\JamesColiz\.azure-devops\python-sdk\cache\resources.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/jcoliz
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\JamesColiz\.azure-devops\python-sdk\cache\options.json
DEBUG: azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\JamesColiz\.azure-devops\python-sdk\cache\options.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.client: File cache hit for options on: https://dev.azure.com/jcoliz
DEBUG: azext_devops.devops_sdk.client: Route template: _apis/{resource}/{*projectId}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0'
DEBUG: azext_devops.devops_sdk.client: GET https://dev.azure.com/jcoliz/_apis/projects?stateFilter=all&$top=1&$skip=0
DEBUG: azext_devops.devops_sdk.client: Request content: None
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
DEBUG: urllib3.connectionpool: https://dev.azure.com:443 "GET /jcoliz/_apis/projects?stateFilter=all&$top=1&$skip=0 HTTP/1.1" 200 360
DEBUG: azext_devops.devops_sdk.client: Response content: b'{"count":1,"value":[{"id":"c5d950e7-314c-48b9-ad44-d4e0899f9600","name":"RVPaint","description":"RV Paint Studio","url":"https://dev.azure.com/jcoliz/_apis/projects/c5d950e7-314c-48b9-ad44-d4e0899f9600","state":"wellFormed","revision":358042794,"visibility":"private","lastUpdateTime":"2015-11-19T03:10:16.203Z"}]}'
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: cli.azext_devops.dev.common.telemetry: Azure devops telemetry enabled.
DEBUG: cli.azext_devops.dev.common.telemetry: Logging telemetry to azure devops server.
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.client: Route template: _apis/{area}/{resource}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0-preview.1'
DEBUG: azext_devops.devops_sdk.client: POST https://dev.azure.com/jcoliz/_apis/CustomerIntelligence/Events
DEBUG: azext_devops.devops_sdk.client: Request content: [{'area': 'AzureDevopsCli', 'feature': 'artifacts', 'properties': {'Command': 'universal download', 'Args': 'feed name version path scope organization project', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False}}]
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/jcoliz
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Looking up current version of ArtifactTool...
DEBUG: azext_devops.devops_sdk.client: File cache hit for options on: https://vsblob.dev.azure.com/jcoliz
DEBUG: azext_devops.devops_sdk.client: Route template: _apis/{area}/{toolName}/{resource}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0-preview'
DEBUG: azext_devops.devops_sdk.client: GET https://vsblob.dev.azure.com/jcoliz/_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64
DEBUG: azext_devops.devops_sdk.client: Request content: None
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): vsblob.dev.azure.com:443
DEBUG: urllib3.connectionpool: https://dev.azure.com:443 "POST /jcoliz/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
DEBUG: urllib3.connectionpool: https://vsblob.dev.azure.com:443 "GET /jcoliz/_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64 HTTP/1.1" 200 444
DEBUG: azext_devops.devops_sdk.client: Response content: b'{"name":"ArtifactTool","rid":"win10-x64","version":"0.2.289","uri":"https://004vsblobprodeus2116.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.289.zip?sv=2019-07-07&sr=b&sig=j%2FlvHwIsE%2FRcRkA17Z9hvWsvr6aYRjaxr3tXpTwoEcg%3D&spr=https&se=2023-08-04T03%3A35%3A54Z&sp=r&P1=1691119854&P2=11&P3=2&P4=yUZHuUyVVSuztxbITY5Eogo7qp7zhllLOKrFkUzweKE%3d"}'
DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Checking if we already have ArtifactTool release 'ArtifactTool_win10-x64_0.2.289'
DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Not updating ArtifactTool because the current release already exists at 'C:\Users\JamesColiz\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.289'
DEBUG: cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://dev.azure.com/jcoliz
DEBUG: cli.azext_devops.dev.common.credential_store: Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
DEBUG: cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
DEBUG: cli.azure.cli.core: Current cloud config:
AzureCloud
DEBUG: cli.azext_devops.dev.common.services: trying to get token (temp) for tenant e89963f8-f5c7-4033-8000-40321901d2c1 and user jcoliz@outlook.com 
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/e89963f8-f5c7-4033-8000-40321901d2c1/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 6e14ea1f-027f-45a3-adcb-1d26dd002d6b
DEBUG: cli.azext_devops.dev.common.services: instance recieved in validate_token_for_instance https://dev.azure.com/jcoliz/
DEBUG: cli.azext_devops.dev.common.services: instance processed in validate_token_for_instance https://dev.azure.com/jcoliz/
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/jcoliz
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.client: Route template: _apis/{resource}/{*projectId}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0'
DEBUG: azext_devops.devops_sdk.client: GET https://dev.azure.com/jcoliz/_apis/projects?stateFilter=all&$top=1&$skip=0
DEBUG: azext_devops.devops_sdk.client: Request content: None
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
DEBUG: urllib3.connectionpool: https://dev.azure.com:443 "GET /jcoliz/_apis/projects?stateFilter=all&$top=1&$skip=0 HTTP/1.1" 200 360
DEBUG: azext_devops.devops_sdk.client: Response content: b'{"count":1,"value":[{"id":"c5d950e7-314c-48b9-ad44-d4e0899f9600","name":"RVPaint","description":"RV Paint Studio","url":"https://dev.azure.com/jcoliz/_apis/projects/c5d950e7-314c-48b9-ad44-d4e0899f9600","state":"wellFormed","revision":358042794,"visibility":"private","lastUpdateTime":"2015-11-19T03:10:16.203Z"}]}'
DEBUG: cli.azext_devops.dev.common.external_tool: Running external command: C:\Users\JamesColiz\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.289\artifacttool universal download --service https://dev.azure.com/jcoliz/ --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed brewhub-debs --package-name still6unitcontroller --package-version 0.1.14 --path bin --project 8257bdfd-5bba-4d04-a064-9d1c720d3b35
ERROR: cli.azext_devops.dev.common.artifacttool: An error occurred on the service. TF400813: The user '3d70c7ae-c29d-6531-b977-d1f19efb7154' is not authorized to access this resource.
DEBUG: cli.azext_devops.dev.common.artifacttool: An error occurred on the service. TF400813: The user '3d70c7ae-c29d-6531-b977-d1f19efb7154' is not authorized to access this resource.
DEBUG: cli.azext_devops.dev.common.exception_handler: handling generic error
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 79, in run
    return self.wait()
  File "C:\Users\JamesColiz\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 51, in wait
    raise CLIError(
knack.util.CLIError: Process ['C:\\Users\\JamesColiz\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.289\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/jcoliz/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'brewhub-debs', '--package-name', 'still6unitcontroller', '--package-version', '0.1.14', '--path', 'bin', '--project', '8257bdfd-5bba-4d04-a064-9d1c720d3b35'] with PID 23816 exited with return code 1

ERROR: cli.azure.cli.core.azclierror: Process ['C:\\Users\\JamesColiz\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.289\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/jcoliz/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'brewhub-debs', '--package-name', 'still6unitcontroller', '--package-version', '0.1.14', '--path', 'bin', '--project', '8257bdfd-5bba-4d04-a064-9d1c720d3b35'] with PID 23816 exited with return code 1
ERROR: az_command_data_logger: Process ['C:\\Users\\JamesColiz\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.289\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/jcoliz/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'brewhub-debs', '--package-name', 'still6unitcontroller', '--package-version', '0.1.14', '--path', 'bin', '--project', '8257bdfd-5bba-4d04-a064-9d1c720d3b35'] with PID 23816 exited with return code 1
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03F1C850>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 2.461 seconds (init: 0.274, invoke: 2.187)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 4010 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\JamesColiz\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Package would be downloaded

### Environment Summary

```
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0
azure-iot                         0.21.5

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\JamesColiz\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Your CLI is up-to-date.
```

### Additional context

Here's what DID work! Calling artifact tool MYSELF and giving it a proper patvar

```
$env:PATVAR="{my shiny new PAT}"
C:\Users\JamesColiz\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.289\artifacttool.exe universal download --service https://dev.azure.com/jcoliz/ --patvar PATVAR --feed brewhub-debs --package-name still6unitcontroller --package-version 0.2.0 --path bin --project BrewHub
```

So somehow the wrong patvar is getting set??

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
