### ISSUE TITLE
Can't connect data connector to Sentinel via az sentinel data-connector command

### ISSUE THREAD

**Issue by celsocoutinho-tangany** [Azure/azure-cli#27094]
### Describe the bug

With a previously installed data connector, as shown in the screenshot, the `az sentinel data-connector connect` fails. The error is rather obscure, not revealing any information about the issue

![image](https://github.com/Azure/azure-cli/assets/128474517/1516827e-3c93-4ce2-9dfb-a3b1484fdff2)

### Related command

```
  az sentinel data-connector connect \
    --subscription "$SUBSCRIPTION" \
    --resource-group "$RESOURCE_GROUP" \
    --workspace-name "$WORKSPACE_NAME" \
    --data-connector-id "$DATA_CONNECTOR_ID"
```

### Errors

```
ERROR: (InternalServerError) Internal server error
Code: InternalServerError
Message: Internal server error
```

### Issue script & Debug output

```
az sentinel data-connector connect \
    --subscription my-subscription \
    --resource-group my-rg \
    --workspace-name my-workspace \
    --data-connector-id AzureActiveDirectory \
    --debug
cli.knack.cli: Command arguments: ['sentinel', 'data-connector', 'connect', '--subscription', 'my-subscription', '--resource-group', 'my-rg', '--workspace-name', 'my-workspace', '--data-connector-id', 'AzureActiveDirectory', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101659b40>, <function OutputProducer.on_global_arguments at 0x1016e6710>, <function CLIQuery.on_global_arguments at 0x101713b50>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'sentinel': ['azext_sentinel']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: sentinel                  0.073        17        21  /Users/me/.azure/cliextensions/sentinel
cli.azure.cli.core: Total (1)                 0.073        17        21  
cli.azure.cli.core: Loaded 17 groups, 21 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : sentinel data-connector connect
cli.azure.cli.core: Command table: sentinel data-connector connect
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1022e1870>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/me/.azure/commands/2023-08-04.13-06-36.sentinel_data-connector_connect.78077.log'.
az_command_data_logger: command args: sentinel data-connector connect --subscription {} --resource-group {} --workspace-name {} --data-connector-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1022fa200>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10234bd00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10234be20>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1016e67a0>, <function CLIQuery.handle_query_parameter at 0x101713be0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10234bd90>]
az_command_data_logger: extension name: sentinel
az_command_data_logger: extension version: 0.2.0
This command is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/me/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/me/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/50811143-5dac-46d6-92e0-3f954e222f9f/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 7f4bfa52-4866-4347-a9d4-76157b3bb99a
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fa889ffe-32b6-11ee-b86d-7640d5f61569'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sentinel data-connector connect'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription --resource-group --workspace-name --data-connector-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (HOMEBREW) (AAZ) azsdk-python-core/1.26.0 Python/3.10.12 (macOS-13.4.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview HTTP/1.1" 500 74
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '74'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '13421040-c8a3-4d79-8e2e-db148fe405ea'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '13421040-c8a3-4d79-8e2e-db148fe405ea'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYNORTH:20230804T110637Z:13421040-c8a3-4d79-8e2e-db148fe405ea'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 04 Aug 2023 11:06:36 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Internal server error"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fa889ffe-32b6-11ee-b86d-7640d5f61569'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sentinel data-connector connect'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription --resource-group --workspace-name --data-connector-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (HOMEBREW) (AAZ) azsdk-python-core/1.26.0 Python/3.10.12 (macOS-13.4.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview HTTP/1.1" 500 74
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '74'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'dd88b72e-0e36-4a72-8269-4a65dc83c1bd'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'dd88b72e-0e36-4a72-8269-4a65dc83c1bd'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYNORTH:20230804T110638Z:dd88b72e-0e36-4a72-8269-4a65dc83c1bd'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 04 Aug 2023 11:06:38 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Internal server error"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fa889ffe-32b6-11ee-b86d-7640d5f61569'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sentinel data-connector connect'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription --resource-group --workspace-name --data-connector-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (HOMEBREW) (AAZ) azsdk-python-core/1.26.0 Python/3.10.12 (macOS-13.4.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview HTTP/1.1" 500 74
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '74'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '13b23ea0-228c-4a4a-b02f-11a31ba56cb4'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '13b23ea0-228c-4a4a-b02f-11a31ba56cb4'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYNORTH:20230804T110640Z:13b23ea0-228c-4a4a-b02f-11a31ba56cb4'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 04 Aug 2023 11:06:39 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Internal server error"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fa889ffe-32b6-11ee-b86d-7640d5f61569'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sentinel data-connector connect'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription --resource-group --workspace-name --data-connector-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (HOMEBREW) (AAZ) azsdk-python-core/1.26.0 Python/3.10.12 (macOS-13.4.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {}
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/e3977875-a8a1-4d47-a69a-ed625758acb2/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace/providers/Microsoft.SecurityInsights/dataConnectors/AzureActiveDirectory/connect?api-version=2022-06-01-preview HTTP/1.1" 500 74
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '74'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '6db2b0db-25c7-4099-97e6-17815d434492'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '6db2b0db-25c7-4099-97e6-17815d434492'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYNORTH:20230804T110644Z:6db2b0db-25c7-4099-97e6-17815d434492'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 04 Aug 2023 11:06:44 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Internal server error"}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/Users/me/.azure/cliextensions/sentinel/azext_sentinel/aaz/latest/sentinel/data_connector/_connect.py", line 31, in _handler
    self._execute_operations()
  File "/Users/me/.azure/cliextensions/sentinel/azext_sentinel/aaz/latest/sentinel/data_connector/_connect.py", line 117, in _execute_operations
    self.DataConnectorsConnect(ctx=self.ctx)()
  File "/Users/me/.azure/cliextensions/sentinel/azext_sentinel/aaz/latest/sentinel/data_connector/_connect.py", line 128, in __call__
    return self.on_error(session.http_response)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (InternalServerError) Internal server error
Code: InternalServerError
Message: Internal server error

cli.azure.cli.core.azclierror: (InternalServerError) Internal server error
Code: InternalServerError
Message: Internal server error
az_command_data_logger: (InternalServerError) Internal server error
Code: InternalServerError
Message: Internal server error
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1022e1ab0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 8.629 seconds (init: 0.073, invoke: 8.557)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3760 in cache
telemetry.check: Negative: The /Users/me/.azure/telemetry.txt was modified at 2023-08-04 13:01:30.304073, which in less than 600.000000 s
```

### Expected behavior

The command should succeed, and the data connector should be activated

### Environment Summary

```
{
  "azure-cli": "2.50.0",
  "azure-cli-core": "2.50.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "azure-devops": "0.26.0",
    "resource-graph": "2.1.0",
    "sentinel": "0.2.0"
  }
}
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.
