### ISSUE TITLE
az webapp log tail stops after a few minutes

### ISSUE THREAD

**Issue by hugovoerman** [Azure/azure-cli#27189]
### Describe the bug

I use Azure Linux App Services on a linux app service plan. 

In a WSL Ubuntu Bash shell in Windows Terminal I do:

az webapp log tail --name <name-of-app-service> --resource-group <name-of-resource-group> --debug 

It tails the live log stream for a couple of minutes and then just stops.

When I logstream via: https:<name-of-app-service>.scm.azurewebsites.net/logstream
it stays running (up to the default 200 minutes timeout) as expected.

To make things even more curious. As long as I keep the scm logstream browser active, the az webapp log tail keeps runing. When I stop the browser then quite soon the az webapp log tail stops.

To me this sounds like the scm logstream keeps a process alive that the az webapp log tail also uses??? Really strange this "entanglement".

### Related command

az webapp log tail --name <name-of-app-service> --resource-group <name-of-resource-group> --debug 

### Errors

The tail just stops. No info, not even with --debug

### Issue script & Debug output

This I will show online. The az webapp log tail ... --debug output (blue in the windows terminal) contains a lot of info that I can't share.

### Expected behavior

That it continues to tail the logstream until the configured (or default) timeout.

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\hvoerman\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by hugovoerman** [comment]
You're welcome.

**Comment by hugovoerman** [comment]
Just a hunch.

It seems that when scm logstream reports:

2023-08-17T14:29:51  No new trace in the past 1 min(s).
2023-08-17T14:30:47    Error occurred, type: error, text: LogStreamManager: ProcessRequest end

2023-08-17T14:30:47  Error occurred, type: error, text: LogStreamManager: Inside Reset

2023-08-17T14:31:51  No new trace in the past 1 min(s).
2023-08-17T14:32:51  No new trace in the past 2 min(s).

The az webapp log tail stops. In my case with just three times:

cli.azure.cli.command_modules.appservice.custom:
cli.azure.cli.command_modules.appservice.custom:
cli.azure.cli.command_modules.appservice.custom:

without any datetime or whatsoever.

**Comment by hugovoerman** [comment]
Perhaps of help:

cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:39:34  No new trace in the past 1 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:40:34  No new trace in the past 2 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:41:34  No new trace in the past 3 min(s).
cli.azure.cli.command_modules.appservice.custom: 2023-08-23T15:42:34  No new trace in the past 4 min(s).
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 761, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 444, in _error_catcher
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 828, in read_chunked
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 765, in _update_chunk_length
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2817, in _get_log
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 624, in stream
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 816, in read_chunked
  File "contextlib.py", line 153, in __exit__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/response.py", line 461, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by btardif** [comment]
we need to make sure this fails gracefully if the connection tot the scm site is lost

**Comment by sarsharma** [comment]
I am unable to repro the issue where log stream stops after a few minutes. With the latest CLI, the stream continues till the timeout of 120 mins
![image](https://github.com/Azure/azure-cli/assets/48413781/45fd0b2b-a651-40d2-8eeb-a47cebc1e428)

As per the logs you shared, the error thrown is due to loss of connection to the scm logstream endpoint.

**Comment by hugovoerman** [comment]
Hi ,

I ran a test today with: az webapp log tail –name <name> --resource-group <rg>

and I can confirm that this completed its mission of 120 minutes continuous logstream.

I use:
{
  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

So, this issue may be closed in my opinion. If this issue arises again, I will make a new issue.

**Comment by sarsharma** [comment]
Glad to hear that, thanks for confirming! @hugovoerman

**Comment by vindicatorr** [comment]
I am getting back to testing azure (because of the dotnet upgrade notification).
I didn't update my app yet and went ahead and switched to 8.0 and as expected my app would fail, but I can't `create-remote-connection` unless it works.
I know I could flip back to the previous version so it'd run, but wouldn't think I'd have to for `ssh`.

And with the fail, I get the message to look at the log and I am getting this error, but it happens immediately:
```
$ az webapp log tail --ids <id>
2023-11-10T01:26:20  Welcome, you are now connected to log-streaming service.
Exception in thread Thread-1 (_get_log):
Traceback (most recent call last):
  File "/home/nater/azure/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/nater/azure/urllib3/response.py", line 1073, in read_chunked
    self._update_chunk_length()
  File "/home/nater/azure/urllib3/response.py", line 1008, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nater/azure/azure/cli/command_modules/appservice/custom.py", line 2864, in _get_log
    for chunk in r.stream():
  File "/home/nater/azure/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/nater/azure/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/nater/azure/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
And my search brought me here.

**Comment by sarsharma** [comment]
Hi @vindicatorr
The error that you are getting should be fixed in an upcoming CLI release, thanks!
