### ISSUE TITLE
bash vars corrupt in WSL2

### ISSUE THREAD

**Issue by FairW** [Azure/azure-cli#27211]
### Describe the bug

Disclaimer: This might be a problem with WSL2 and not az cli... 
I have a bash script that runs perfectly fine in Cloud Shell / bash. On my local win 11 with WSL2 (Ubuntu 22.04.2 LTS) it fails.
Code extract:

```
keyVaultId=$(az keyvault list --resource-group ${commonRg}  --query '[].[id]'  --output tsv)
echo "KV: ${keyVaultId}"
snetRef=$(az network vnet subnet show -g ${networkRg} -n ${protectedSnet} --vnet-name "${vnet}"  --query '[id]' --output tsv)
echo "SNET: ${snetRef}"
az network private-endpoint create --connection-name "$keyvaultPepName" --name "${keyvaultPepName}" --subnet ${snetRef} --private-connection-resource-id ${keyVaultId}  --resource-group "${operationRg}" --group-id vault
```

If I replace the two vars **`snetRef`** and **`keyVaultId`** with the hardcoded, fully qualified paths echo'ed in the script above; the script works in WSL2.... 

Note on error message: The message seems to be chopped - what I've enclosed here is the actual output, except for subscription Id is removed.

### Related command

n/a

### Errors

  is not a valid resource ID.subscriptions/<subscr-uuid-removed>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv
Code: InvalidResourceId
 is not a valid resource ID.ns/<subscr-uuid-removed>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv

### Issue script & Debug output

emsal.telemetry: Generate or reuse correlation_id: ddacd7e8-a1f3-4c30-8599-a803fa50655c
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subscrId>/resourceGroups/npp-operation-uat-dr-rg/providers/Microsoft.Network/privateEndpoints/nppu-common-uat-norw-keyvault-pep?api-version=2022-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '552'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7c4dcaa6-4017-11ee-a208-70a8d35938dd'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network private-endpoint create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--connection-name --name --subnet --private-connection-resource-id --resource-group --group-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "norwaywest", "properties": {"privateLinkServiceConnections": [{"name": "nppu-common-uat-norw-keyvault-pep", "properties": {"groupIds": ["vault"], "privateLinkServiceId": "/subscriptions/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv\r"}}], "subnet": {"id": "/subscriptions/<subscrId>/resourceGroups/networking-uat-rg/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/the-snet\r"}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscrId>/resourceGroups/npp-operation-uat-dr-rg/providers/Microsoft.Network/privateEndpoints/nppu-common-uat-norw-keyvault-pep?api-version=2022-01-01 HTTP/1.1" 400 271
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '271'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '0b15f03d-3861-43a6-9229-a9870251c670'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7e5bdd7e-297b-4897-a144-1bfe762e3f78'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '1e693484-c2ea-47f7-b5cc-d41d7d9ec3ed'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20230821T114013Z:7e5bdd7e-297b-4897-a144-1bfe762e3f78'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 1226A8EF0E974FCAA446DC37AD9CFF4A Ref B: FRA231050411047 Ref C: 2023-08-21T11:40:11Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 21 Aug 2023 11:40:12 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "InvalidResourceId",
    "message": "String /subscriptions/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv\r is not a valid resource ID.",
    "details": []
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1013, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\private_endpoint\__cmds.py", line 294, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\private_endpoint\__cmds.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (InvalidResourceId) String /subscriptions/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.Ke is not a valid resource ID.-kv
Code: InvalidResourceId
 is not a valid resource ID.ns/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv

cli.azure.cli.core.azclierror: (InvalidResourceId) String /subscriptions/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vau is not a valid resource ID.
Code: InvalidResourceId
 is not a valid resource ID.ns/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv
az_command_data_logger: (InvalidResourceId) String /subscriptions/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp is not a valid resource ID.
Code: InvalidResourceId
 is not a valid resource ID.ns/<subscrId>/resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04A9B6E8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.972 seconds (init: 0.539, invoke: 3.432)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3901 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\myUserId\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

running the script in WSL2 should give the same result as in Cloud Shell / bash

### Environment Summary

az --version
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<removed>\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
The keyvault resource id you pass in for `az network private-endpoint create` is `/subscriptions//resourceGroups/npp-common-uat-rg/providers/Microsoft.KeyVault/vaults/npp-common-uat-kv\r`

There're two problems:
- additional `-r` in the end. It's because `az keyvault list` is returning an array, `--output csv` would show `ResourceA\rResourceB\r...` what you really want is just one vault, right?
- the resourceId for single vault missing subscriptionId info. This is quite weird
