### ISSUE TITLE
install fails under Gentoo Lnux early

### ISSUE THREAD

**Issue by toralf** [Azure/azure-cli#27218]
### Describe the bug

The installer fails both in a clean environment and within a venv, create with:
```
python -m venv ~/hlag
```

### Related command

 curl -L https://aka.ms/InstallAzureCli | bash

### Errors

This is the error message:
```
Infra $ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1405  100  1405    0     0   1605      0 --:--:-- --:--:-- --:--:--  1605
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_q6bJtQ.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_q6bJtQ: OK
Running install script.
-- Verifying Python version.
-- Python version 3.11.4 okay.
-- Verifying native dependencies.
-- Unable to verify native dependencies. dist=gentoo, version=2.14. Continuing...

===> In what directory would you like to place the install? (leave blank to use '/home/tfoerste/lib/azure-cli'): 
-- Creating directory '/home/tfoerste/lib/azure-cli'.
-- We will install at '/home/tfoerste/lib/azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use '/home/tfoerste/bin'): 
-- The executable will be in '/home/tfoerste/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-16.7.11.tar.gz.
-- Downloaded virtualenv package to /tmp/tmpxrs0y1ri/virtualenv-16.7.11.tar.gz.
-- Checksum of /tmp/tmpxrs0y1ri/virtualenv-16.7.11.tar.gz OK.
-- Extracting '/tmp/tmpxrs0y1ri/virtualenv-16.7.11.tar.gz' to '/tmp/tmpxrs0y1ri'.
-- Executing: ['/home/tfoerste/hlag/bin/python3', 'virtualenv.py', '--python', '/home/tfoerste/hlag/bin/python3', '/home/tfoerste/lib/azure-cli']
Already using interpreter /home/tfoerste/hlag/bin/python3
Using base prefix '/usr'
New python executable in /home/tfoerste/lib/azure-cli/bin/python3
Also creating executable in /home/tfoerste/lib/azure-cli/bin/python
ERROR: The executable /home/tfoerste/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/tfoerste/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_q6bJtQ", line 415, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_q6bJtQ", line 399, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/azure_cli_install_tmp_q6bJtQ", line 144, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/azure_cli_install_tmp_q6bJtQ", line 105, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/tfoerste/hlag/bin/python3', 'virtualenv.py', '--python', '/home/tfoerste/hlag/bin/python3', '/home/tfoerste/lib/azure-cli']' returned non-zero exit status 100.

```

### Issue script & Debug output

n/a

### Expected behavior

https://aka.ms/InstallAzureCli 

### Environment Summary

it should work (it worked in the past with 2.49)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Hello, this script is deprecated.
Please follow steps in this issue to install azure-cli via pip: https://github.com/Azure/azure-cli/issues/20476

@jiasli, I prefer to remove it from doc and replace it with #20476.

**Comment by toralf** [comment]
indeed, pip seems to work.
