### ISSUE TITLE
az network watcher connection-monitor test-group add command forcing frequency which is not required parameter

### ISSUE THREAD

**Issue by abhiramani-git** [Azure/azure-cli#27233]
### Describe the bug

This command is forcing parameter frequency "Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800." and even after specifying frequency parameter it runs into to some runtime error

this command is taken straight from documentation third example

https://learn.microsoft.com/en-us/cli/azure/network/watcher/connection-monitor/test-group?view=azure-cli-latest#az-network-watcher-connection-monitor-test-group-add

### Related command

az network watcher connection-monitor test-group add --connection-monitor MyConnectionMonitor --location westus --name MyAccessibilityTestGroup --endpoint-source-name MySourceEndpoint --endpoint-source-resource-id MyVMResourceID --endpoint-dest-name bing --endpoint-dest-address bing.com --test-config-name MyNewTestConfiguration --protocol Tcp --tcp-port 4096

### Errors

Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.

### Issue script & Debug output

cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "InvalidTestFrequency",
    "message": "Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.",
    "details": []
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1013, in __call__
    raise exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/watcher/connection_monitor/test_group/_add.py", line 123, in _execute_operations
    yield self.ConnectionMonitorsCreateOrUpdate(ctx=self.ctx)()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/aaz/latest/network/watcher/connection_monitor/test_group/_add.py", line 283, in __call__
    return self.on_error(session.http_response)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (InvalidTestFrequency) Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.
Code: InvalidTestFrequency
Message: Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.

cli.azure.cli.core.azclierror: (InvalidTestFrequency) Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.
Code: InvalidTestFrequency
Message: Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.
az_command_data_logger: (InvalidTestFrequency) Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.
Code: InvalidTestFrequency
Message: Test frequency in seconds 0 should be greater or equal to 30 and lesser or equal to 1800.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcf26243670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.767 seconds (init: 0.121, invoke: 1.646)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3989 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/abhijit/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

should add test group to network watcher

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
application-insights              0.1.16
communication                    1.7.2b1
ml                                2.19.1
scheduled-query                    0.5.1
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/abhijit/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by abhiramani-git** [comment]
Any update?
