### ISSUE TITLE
Azure CLI on SAW feature requests

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#27278]
This issue tracks the feature requests for Azure CLI on SAW.

Due to the limitation of SAW, some commands are broken.
If you encounter an error while using azure-cli on SAW, please report it here with the command and error log.
We'll evaluate it with service team.

Installation guide and known issue can be found from [Azure CLI on SAW document](https://ppe.eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/azure_cli_on_saw).

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ulua1** [comment]
![image](https://github.com/Azure/azure-cli/assets/107612499/864a8fd1-c3c6-4c84-91fe-2f3fa2785e13)
Hello everyone, I would like to ask how should I solve this situation

**Comment by bebound** [comment]
Hi @ulua1, this issue is for **SAW only**, please open a new issue.

**Comment by ulua1** [comment]
Hello@bebound, do you know where I should consult with this question? Because I am the first to encounter this problem

**Comment by bebound** [comment]
Click "New issue" button on the top left corner and fill the form.
PS: I'll remove your reply once you create the new one.

**Comment by mbashtovaya** [comment]
I was able to install Azure CLI on SAW, however, i am getting the following error in the terminal:
C:\Users\XX>az
FATAL ERROR: UMCI enforcement is required by policy, but is turned off. Contact your system administrator or support person.

**Comment by bebound** [comment]
It seems that WDAC is not enabled on your server. Have you joined the `AzureCLI-SAW` silo?

**Comment by chunhuihu** [comment]
C:\Users\chunhuihu>az aks get-credentials --name sc-ncus-42ae4 --resource-group ms-production-sc-ncus-42ae4 --subscription 76e3fa68-c7e1-4e75-a706-1d7219996b61 --overwrite-existing
The command failed with an unexpected error. Here is the traceback:
**No module named 'requests'**
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/__init__.py", line 509, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 35, in <module>
ModuleNotFoundError: No module named 'requests'
To open an issue, please run: 'az feedback'

**Comment by mbashtovaya** [comment]
> It seems that WDAC is not enabled on your server. Have you joined the `AzureCLI-SAW` silo?

yes i have.

**Comment by bebound** [comment]
@mbashtovaya The log indicates that it is turned off. You can contact the SAW team for help.

**Comment by bhawna2303** [comment]
Hi I am having an issue, just install Azure CLI and I see this issue.

The command failed with an unexpected error. Here is the traceback:
The command failed with an unexpected error. Here is the traceback:
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/cli.py", line 212, in invoke
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/_win_vt.py", line 11, in <module>
ModuleNotFoundError: No module named 'ctypes'
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/cli.py", line 212, in invoke
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/_win_vt.py", line 11, in <module>
ModuleNotFoundError: No module named 'ctypes'
To open an issue, please run: 'az feedback'

**Comment by bebound** [comment]
@bhawna2303 Same as the previous issue.

**Comment by bhawna2303** [comment]
Running in Terminal gives this error:
PS C:\Users\bhkumari> az login
FATAL ERROR: UMCI enforcement is required by policy, but is turned off. Contact your system administrator or support person.
PS C:\Users\bhkumari>
