### ISSUE TITLE
az extension list-available not listing publicly available extensions. Cannot add extension 

### ISSUE THREAD

**Issue by auyidi1** [Azure/azure-cli#27293]
### Describe the bug

Unable to add any extension. Only one extension is showing after running "`az extension list-available --output table`"
Name        Version    Summary                                  Preview    Experimental    Installed
----------  ---------  ---------------------------------------  ---------  --------------  -----------
azure-edge  0.0.3a2    The Azure Edge extension for Azure CLI.  True       False           True

As a result, I am unable to add any new extensions as the extension cannot be found. For example:
`az extension add --name connectedk8s`
No extension found with name 'connectedk8s'

I tried uninstalling and reinstalling Azure CLI with no success. 

### Related command

az extension list-available --output table
az extension add --name connectedk8s

### Errors

az extension list-available --output table
Name        Version    Summary                                  Preview    Experimental    Installed
----------  ---------  ---------------------------------------  ---------  --------------  -----------
azure-edge  0.0.3a2    The Azure Edge extension for Azure CLI.  True       False           True

### Issue script & Debug output

`az extension list-available --output table --debug`
cli.knack.cli: Command arguments: ['extension', 'list-available', '--output', 'table', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001F22B4F5240>, <function OutputProducer.on_global_arguments at 0x000001F22B643EB0>, <function CLIQuery.on_global_arguments at 0x000001F22B88D240>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.005         1         7
cli.azure.cli.core: Total (1)                 0.005         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension list-available
cli.azure.cli.core: Command table: extension list
cli.azure.cli.core: remaining    :                available
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001F22DF44310>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\alainuyidi\.azure\commands\2023-08-30.07-47-04.extension_list-available.26484.log'.
az_command_data_logger: command args: extension list-available --output {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001F22DF46F80>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001F22DFA4F70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001F22DFA5090>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001F22B643F40>, <function CLIQuery.handle_query_parameter at 0x000001F22B88D2D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001F22DFA5000>]
urllib3.connectionpool: Starting new HTTPS connection (1): ***:443
urllib3.connectionpool: https://***:443 "GET /***/index.json HTTP/1.1" 200 13042
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x000001F22DF723B0>, <function _x509_from_base64_to_hex_transform at 0x000001F22DF72440>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
Name        Version    Summary                                  Preview    Experimental    Installed
----------  ---------  ---------------------------------------  ---------  --------------  -----------
azure-edge  0.0.3a2    The Azure Edge extension for Azure CLI.  True       False           True
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001F22DF44550>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 1.734 seconds (init: 0.964, invoke: 0.770)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3338 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\alainuyidi\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

--------------

`az extension add --name connectedk8s --debug`
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'connectedk8s', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000021F0CF15240>, <function OutputProducer.on_global_arguments at 0x0000021F0D063EB0>, <function CLIQuery.on_global_arguments at 0x0000021F0D2AD240>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.004         1         7
cli.azure.cli.core: Total (1)                 0.004         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000021F0F9E4310>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\alainuyidi\.azure\commands\2023-08-30.07-53-58.extension_add.12152.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000021F0F9E6F80>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000021F0FA44F70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000021F0FA45090>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000021F0D063F40>, <function CLIQuery.handle_query_parameter at 0x0000021F0D2AD2D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000021F0FA45000>]
urllib3.connectionpool: Starting new HTTPS connection (1): azedgecli.blob.core.windows.net:443

### Expected behavior

The **`az extension list-available`** command provides a list of all publicly available extensions.

### Environment Summary

az --version
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
account                            0.2.1
azure-edge                       0.0.3a2
azure-iot                         0.21.1
ssh                                1.1.2
webpubsub                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<user_name>\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

Original had the 32-bit version of azure-cli 2.51.0 installed. Installed the 64-bit version but have the same issue.

**Comment by hansgschossmann** [comment]
@yonzhan  I see the same issue on my box. Before my vacation early august everything worked fine.

Interesting is that i have uninstalled az and reinstalled to see if this fixes the issue. After this the azure-edge extension was there without installing it. But other extensions neither showed up with list-extensions nor i was able to install for example connectedk8s. Here is the output when it try to add it:
 C:\Users\johanng > az extension add --name connectedk8s
No extension found with name 'connectedk8s'

Use --debug for more information
 C:\Users\johanng > az extension add --name connectedk8s --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'connectedk8s', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000021D11F45240>, <function OutputProducer.on_global_arguments at 0x0000021D12093EB0>, <function CLIQuery.on_global_arguments at 0x0000021D122DD240>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.004         1         7
cli.azure.cli.core: Total (1)                 0.004         1         7
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000021D14994430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\johanng\.azure\commands\2023-09-05.22-20-51.extension_add.13928.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000021D149970A0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000021D14A21090>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000021D14A211B0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000021D12093F40>, <function CLIQuery.handle_query_parameter at 0x0000021D122DD2D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000021D14A21120>]
urllib3.connectionpool: Starting new HTTPS connection (1): azedgecli.blob.core.windows.net:443
urllib3.connectionpool: https://azedgecli.blob.core.windows.net:443 "GET /drop/index.json HTTP/1.1" 200 13042
cli.azure.cli.core.extension.operations: No extension found with name 'connectedk8s'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 318, in add_extension
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/_resolve.py", line 103, in resolve_from_index
azure.cli.core.extension._resolve.NoExtensionCandidatesError: No extension found with name 'connectedk8s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 322, in add_extension
knack.util.CLIError: No extension found with name 'connectedk8s'

Use --debug for more information

cli.azure.cli.core.azclierror: No extension found with name 'connectedk8s'

Use --debug for more information
az_command_data_logger: No extension found with name 'connectedk8s'

Use --debug for more information
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000021D14994670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.585 seconds (init: 0.538, invoke: 1.047)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3457 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\johanng\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by auyidi1** [comment]
On my end, the problem occurred after following steps in a private preview which set the default config to a private index url. You can see if this is your issue by using `az config get` and what's set in the `extension` section. I was able to get around this problem by resetting the extension using the `az config set extension.index_url=""`. The nuclear option would be to delete the ~/.azure or ~/.azure/config and reinstall Azure cli.

**Comment by hansgschossmann** [comment]
@auyidi1 thanks for your info. this fixed my problem, since the index_url has been set by a specific extension and suppressed showing all others.
