### ISSUE TITLE
Running az containerapp update with yaml fails when running in Azure Devops CI/CD

### ISSUE THREAD

**Issue by gameiro** [Azure/azure-cli#27295]
### Describe the bug

When running the command in the Azure Devops CI/CD pipelines: 

`az containerapp update -n <example> -g <rg> --yaml <file>`  I am getting constant error that something is malformed but running locally with the same file it works fine.

This was working few days ago but now its seems to fail every time.

### Related command

`az containerapp update -n <example> -g <rg> --yaml <file>`

### Errors

```bash
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'value'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 582, in update_containerapp
    return update_containerapp_logic(cmd=cmd,
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/custom.py", line 545, in update_containerapp_logic
    containerapp_update_decorator.construct_payload()
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/containerapp_decorator.py", line 1291, in construct_payload
    super().construct_payload()
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/containerapp_decorator.py", line 765, in construct_payload
    return self.set_up_update_containerapp_yaml(name=self.get_argument_name(), file_name=self.get_argument_yaml())
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/containerapp_decorator.py", line 1169, in set_up_update_containerapp_yaml
    _populate_secret_values(self.new_containerapp, secret_values)
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_utils.py", line 1085, in _populate_secret_values
    value["value"] = next(s["value"] for s in secret_values if s["name"] == value["name"])
  File "/opt/az/azcliextensions/containerapp/azext_containerapp/_utils.py", line 1085, in <genexpr>
    value["value"] = next(s["value"] for s in secret_values if s["name"] == value["name"])
KeyError: 'value'
```

### Issue script & Debug output

N/A

### Expected behavior

The command should work as expected and update the container app using the yaml

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Jul 27 2023, 07:10:25) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
