### ISSUE TITLE
Unable to install Azure Machine Learning (v2) extension. 

### ISSUE THREAD

**Issue by Mpmendoza10** [Azure/azure-cli#27330]
### Describe the bug

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'

### Related command

 az extension add -n ml -y

### Errors

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'

### Issue script & Debug output

The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 518, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE,
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 170, in raise_event
    func(self, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 95, in init_command_file_logging
    self._init_command_logfile_handlers(metadata_logger, args)  # pylint: disable=protected-access
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/azlogging.py", line 115, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path, encoding=LOG_FILE_ENCODING)
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 30] Read-only file system: '/home/maria/.azure/commands/2023-09-06.16-27-25.extension_add.270.log'

### Expected behavior

'Success'

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.19.1
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/maria/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
