### ISSUE TITLE
[extension] blueprint version 0.3.2 - Expect <class 'str'>, got ['Owner', 'Contributor', 'Reader'] (<class 'list'>)

### ISSUE THREAD

**Issue by ozbillwang** [Azure/azure-cli#27353]
### Describe the bug

the problem is only in the latest extention version of blueprint v0.3.2

no issue in v0.3.1

### Related command

```
az blueprint version list -m <mgmt_group> --blueprint-name <name>
```

### Errors

When the blueprint version stays as old version, such as `0.3.1`, the command is fine

```
$  az version
{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.149",
    "automation": "0.2.1",
    "azure-devops": "0.26.0",
    "bastion": "0.2.5",
    "blueprint": "0.3.1",
    "communication": "1.7.2b1",
    "express-route-cross-connection": "0.1.1",
    "interactive": "0.5.1",
    "logic": "0.1.7",
    "ssh": "2.0.0",
    "virtual-wan": "0.2.17"
  }
}
```

But after I upgrade to latest, 
```
az extension add -y --upgrade --name blueprint
Extension 'blueprint' 0.3.1 is already installed.
It will be overridden with version 0.3.2.
```
The command failed with an unexpected error. Here is the traceback:

```
Expect <class 'str'>, got ['Owner', 'Contributor', 'Reader'] (<class 'list'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_paging.py", line 87, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_paging.py", line 43, in __next__
    self._executor(self._next_link)
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_command.py", line 249, in executor_wrapper
    executor()
  File "/Users/bill/.azure/cliextensions/blueprint/azext_blueprint/aaz/latest/blueprint/version/_list.py", line 66, in _execute_operations
    self.PublishedBlueprintsList(ctx=self.ctx)()
  File "/Users/bill/.azure/cliextensions/blueprint/azext_blueprint/aaz/latest/blueprint/version/_list.py", line 89, in __call__
    return self.on_200(session)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bill/.azure/cliextensions/blueprint/azext_blueprint/aaz/latest/blueprint/version/_list.py", line 144, in on_200
    self.ctx.set_var(
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_command_ctx.py", line 84, in set_var
    self.vars[name] = data
    ~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 234, in process_data
    value[key] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 409, in process_data
    value[idx] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 363, in __setitem__
    self._data[idx] = item_schema.process_data(data, key=idx)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 234, in process_data
    value[key] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 234, in process_data
    value[key] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 311, in process_data
    value[key] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 241, in __setitem__
    self._data[key] = item_schema.process_data(data, key=key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 234, in process_data
    value[key] = sub_data
    ~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_value.py", line 76, in __setitem__
    self._data[name] = attr_schema.process_data(data, key=name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/aaz/_field_type.py", line 48, in process_data
    raise AAZInvalidValueError('Expect {}, got {} ({})'.format(self.DataType, data, type(data)))
azure.cli.core.aaz.exceptions.AAZInvalidValueError: Expect <class 'str'>, got ['Owner', 'Contributor', 'Reader'] (<class 'list'>)
```

### Issue script & Debug output

```
Expect <class 'str'>, got ['Owner', 'Contributor', 'Reader'] (<class 'list'>)
```

### Expected behavior

should work

### Environment Summary

```
$ az version
{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.149",
    "automation": "0.2.1",
    "azure-devops": "0.26.0",
    "bastion": "0.2.5",
    "blueprint": "0.3.1",
    "communication": "1.7.2b1",
    "express-route-cross-connection": "0.1.1",
    "interactive": "0.5.1",
    "logic": "0.1.7",
    "ssh": "2.0.0",
    "virtual-wan": "0.2.17"
  }
}
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ozbillwang** [comment]
> Hi @ozbillwang,
> 
> 2.51.0 is not the latest Azure CLI(2.52.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

I have upgraded with `az upgrad` to latest Azure CLI(2.52.0). But get same error.

**Comment by jsntcy** [comment]
@ZengTaoxu, please help take a look and it's probably caused by https://github.com/Azure/azure-cli-extensions/pull/6602.

**Comment by ZengTaoxu** [comment]
Hello @ozbillwang, do you know the specific return value of the error? For example: blueprintName, changeNotes or something like that.

**Comment by ozbillwang** [comment]
No idea. I copy most error messages here.

**Comment by ZengTaoxu** [comment]
Okay, can you provide the parameters that you used to create the blueprint resource? For example: az blueprint create -n ...

**Comment by ozbillwang** [comment]
> @ZengTaoxu, please help take a look and it's probably caused by [Azure/azure-cli-extensions#6602](https://github.com/Azure/azure-cli-extensions/pull/6602).

with so big change, I didn't see any unit tests, integration tests and regression tests for the PR. 

https://github.com/Azure/azure-cli-extensions/pull/6602/files

**Comment by ozbillwang** [comment]
it is deployed via Azure DevOps Pipeline 's task `CreateBlueprint@1`

Ref: https://marketplace.visualstudio.com/items?itemName=nepeters.azure-blueprints&targetId=59a456cc-1d4e-4bd9-ad4e-4d89ae19ce9c

**Comment by ZengTaoxu** [comment]
Hello @ozbillwang, can you provide the relevant json file? I need to repeat your issue.

**Comment by ozbillwang** [comment]
```
{
  "properties": {
    "description": "This is testing blueprint",
    "targetScope": "subscription",
    "parameters": {
      "auditLinuxmachinesthathavethespecifiedapplicationsinstalled_IncludeArcMachines": {
        "type": "string",
        "metadata": {
          "displayName": "Include Arc connected servers (Policy: Audit Linux machines that have the specified applications installed)"
        },
        "defaultValue": "false",
        "allowedValues": ["true", "false"]
      },
      "auditLinuxmachinesthathavethespecifiedapplicationsinstalled_ApplicationName": {
        "type": "string",
        "metadata": {
          "displayName": "Application names (Policy: Audit Linux machines that have the specified applications installed)"
        },
        "allowedValues": []
      }
    },
    "resourceGroups": {
      "ResourceGroup": {
        "name": "ResourceGroupX",
        "location": "australiaeast",
        "dependsOn": [],
        "tags": {
        },
        "metadata": {
          "displayName": "ResourceGroupX"
        }
      }
    }
  }
}
```

**Comment by ZengTaoxu** [comment]
Hi ozbillwang, the second json file you provided does not seem to be for assign blueprint. Can you provide specific parameters for the second step in the link?
https://marketplace.visualstudio.com/items?itemName=nepeters.azure-blueprints&targetId=59a456cc-1d4e-4bd9-ad4e-4d89ae19ce9c

**Comment by ozbillwang** [comment]
@ZengTaoxu 

That's all details I can provide. 

By the way, from my view, you are on the wrong direction. The problem I reported is az blueprint version`list`, not `create` or `update`

There is a simple way to duplicate the issue, and you don't need depend on any json files.

```
$ docker run -ti --rm mcr.microsoft.com/azure-cli bash
d2e6fedc9d66:/# az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxxx to authenticate.
...
d2e6fedc9d66:/# az extension list
[]

# Install the latest version of extension `blueprint`
d2e6fedc9d66:/# az extension add --yes --name blueprint
The installed extension 'blueprint' is experimental and not covered by customer support. Please use with discretion.
d2e6fedc9d66:/# az blueprint version list --management-group <group_name> --blueprint-name <blueprint_name>
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
Expect <class 'str'>, got ['Owner', 'Contributor', 'Reader'] (<class 'list'>)
Traceback (most recent call last):
...
```

**Comment by ZengTaoxu** [comment]
Hi ozbillwang, I see that this command works in version 0.3.1, so can you send the normal output?

**Comment by ozbillwang** [comment]
I didn't get you. If you knew blueprint, you should know the output. 

There is not special from my side.

**Comment by ZengTaoxu** [comment]
I can't find which field this error is, and there is no way to reproduce your resource situation, the return value of different blueprint resources may be different.
