### ISSUE TITLE
SAW: No module named requests

### ISSUE THREAD

**Issue by Danieladu** [Azure/azure-cli#27355]
### Describe the bug

occurs "No module named requests"whie running `az role assignment create`  command in a SAW maching.

### Related command

`az role assignment create`

### Errors

No module named requests

### Issue script & Debug output

az role assignment create --assignee $principalId --role "DocumentDB Account Contributor" --scope /subscriptions/$($cosmosDB.Subscription)/resourceGroups/$($cosmosDB.ResourceGroup)/providers/Microsoft.DocumentDB/databaseAccounts/$($cosmosDB.CosmosDBName)

### Expected behavior

works

### Environment Summary

az cli:  2.40.0 in SAW

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
@Danieladu, could you please share the full call stack?

**Comment by Danieladu** [comment]
@jiasli the full stack:
The command failed with an unexpected error. Here is the traceback:
No module named 'requests'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-gsv4lzxz\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 166, in create_role_assignment
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 1521, in _resolve_object_id_and_type
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/util.py", line 886, in send_raw_request
ModuleNotFoundError: No module named 'requests'

**Comment by Danieladu** [comment]
Is there any workaround for this? blocked by this

**Comment by bebound** [comment]
Currently, this is by design.
Requests package is forbidden on SAW. This command relies on requests and fails.
The module needs to eliminate the requests from the source code.
 
We may have a global replacement for requests in the future. The replacement is not perfect, and I’m not sure if it can fix this issue.

**Comment by Danieladu** [comment]
Thanks @bebound  for the reply

**Comment by wanzhuM** [comment]
Hello, trying to run az aks get-credentials on SAW, what's the workaround? 
Need to access clusters in tenants which are SAW only.
