### ISSUE TITLE
The command 'az vm extension set' does not work as intended.

### ISSUE THREAD

**Issue by mayankdaruka-msft** [Azure/azure-cli#27362]
### Describe the bug

This is an example of the 'az vm extension set' command:

```
az vm extension set -n VMAccessForLinux --publisher Microsoft.OSTCExtensions --version 1.4 \
    --vm-name MyVm --resource-group MyResourceGroup \
    --protected-settings '{"username":"user1", "ssh_key":"ssh_rsa ..."}'
```

As shown above, a string is passed to the **--protected-settings** attribute. The same goes for the **--settings** attribute, which isn't shown above.

The issue with this is that VM extensions only accept **settings** and **protected_settings** as objects (dictionaries), not strings. But, as you can see in this function within the Azure CLI repository:
https://github.com/Azure/azure-cli/blob/a9a87c7dbc7a50ce93c7f753b814e3991a49328e/src/azure-cli/azure/cli/command_modules/vm/custom.py#L2146
The function will take in both **settings** and **protected_settings** as a string and directly pass them to the extension.

Doing this results in the following error. This is an example where I am using the CLI command to invoke the VMAccess extension, and the extension expects a dictionary, but instead receives a string, causing the error:
![MicrosoftTeams-image (1)](https://github.com/Azure/azure-cli/assets/133302048/0378822a-cb02-47bf-852b-570e5b99ff5e)

### Related command

`az vm extension set`

### Errors

![MicrosoftTeams-image (1)](https://github.com/Azure/azure-cli/assets/133302048/04d8091b-2e1f-4dd6-bf98-1336556ccaa2)

This is an error specific to a failure that occurs when provisioning an extension. This is occurring because Azure CLI is not passing in the right attribute values to the extension **settings** and **protected_settings** properties. Look at Expected Behavior section to see how to fix this.

### Issue script & Debug output

```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/resourceGroups/mayankdaruka-rg3/providers/Microsoft.Compute/virtualMachines/mayankdar-ubuntuvm1/extensions/VMAccessForLinux?api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '250'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'afa3b812-50de-11ee-89ee-701ab8ff972b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm extension set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --publisher --resource-group --vm-name --protected-settings --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.46.0 (MSI) azsdk-python-azure-mgmt-compute/29.1.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "centraluseuap", "properties": {"publisher": "Microsoft.OSTCExtensions.Edp", "type": "VMAccessForLinux", "typeHandlerVersion": "1.5", "autoUpgradeMinorVersion": true, "protectedSettings": "{username:mayankd1,password:testpassword123#}"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/resourceGroups/mayankdaruka-rg3/providers/Microsoft.Compute/virtualMachines/mayankdar-ubuntuvm1/extensions/VMAccessForLinux?api-version=2022-11-01 HTTP/1.1" 200 568
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '568'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'azure-asyncoperation': 'https://management.azure.com/subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/providers/Microsoft.Compute/locations/CentralUSEUAP/operations/bd03c3fd-e6c7-4b87-b96e-c13416b763ac?p=8236366c-f5d5-4e5f-853d-0f478dc08837&api-version=2022-11-01'
cli.azure.cli.core.sdk.policies:     'azure-asyncnotification': 'Enabled'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/UpdateVM3Min;238,Microsoft.Compute/UpdateVM30Min;1198'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'bd03c3fd-e6c7-4b87-b96e-c13416b763ac'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e5d2590c-e921-4a91-a06e-9ce3df6edb2d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20230911T200629Z:e5d2590c-e921-4a91-a06e-9ce3df6edb2d'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 9D4C10DF145342A5BD8FBF9C835631B5 Ref B: MNZ221060608035 Ref C: 2023-09-11T20:06:29Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 11 Sep 2023 20:06:29 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "VMAccessForLinux",
  "id": "/subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/resourceGroups/mayankdaruka-rg3/providers/Microsoft.Compute/virtualMachines/mayankdar-ubuntuvm1/extensions/VMAccessForLinux",
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "location": "centraluseuap",
  "properties": {
    "autoUpgradeMinorVersion": true,
    "provisioningState": "Updating",
    "publisher": "Microsoft.OSTCExtensions.Edp",
    "type": "VMAccessForLinux",
    "typeHandlerVersion": "1.5",
    "settings": "{check_disk:true}"
  }
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/providers/Microsoft.Compute/locations/CentralUSEUAP/operations/bd03c3fd-e6c7-4b87-b96e-c13416b763ac?p=8236366c-f5d5-4e5f-853d-0f478dc08837&api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'afa3b812-50de-11ee-89ee-701ab8ff972b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm extension set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --publisher --resource-group --vm-name --protected-settings --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.46.0 (MSI) azsdk-python-azure-mgmt-compute/29.1.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/providers/Microsoft.Compute/locations/CentralUSEUAP/operations/bd03c3fd-e6c7-4b87-b96e-c13416b763ac?p=8236366c-f5d5-4e5f-853d-0f478dc08837&api-version=2022-11-01 HTTP/1.1" 200 134
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '134'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperationResource;59,Microsoft.Compute/GetOperationSubscriptionMaximum;14999'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2fd0df7e-f8d9-4c2b-9aab-1329afdda7f7'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e3329500-7cb1-4c73-b9be-c817ffab638f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20230911T200700Z:e3329500-7cb1-4c73-b9be-c817ffab638f'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 328BCB3B80CF4955890DBFDB0B1ACA11 Ref B: MNZ221060608035 Ref C: 2023-09-11T20:07:00Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 11 Sep 2023 20:07:00 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "startTime": "2023-09-11T20:06:29.8260796+00:00",
  "status": "InProgress",
  "name": "bd03c3fd-e6c7-4b87-b96e-c13416b763ac"
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/providers/Microsoft.Compute/locations/CentralUSEUAP/operations/bd03c3fd-e6c7-4b87-b96e-c13416b763ac?p=8236366c-f5d5-4e5f-853d-0f478dc08837&api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'afa3b812-50de-11ee-89ee-701ab8ff972b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm extension set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --publisher --resource-group --vm-name --protected-settings --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.46.0 (MSI) azsdk-python-azure-mgmt-compute/29.1.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/a53f7094-a16c-47af-abe4-b05c05d0d79a/providers/Microsoft.Compute/locations/CentralUSEUAP/operations/bd03c3fd-e6c7-4b87-b96e-c13416b763ac?p=8236366c-f5d5-4e5f-853d-0f478dc08837&api-version=2022-11-01 HTTP/1.1" 200 576
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '576'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperationResource;57,Microsoft.Compute/GetOperationSubscriptionMaximum;14999'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'efdd1469-75af-4728-af74-a3d5bb19f943'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c8560a95-0642-4618-8850-ae5275e4c29a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20230911T200730Z:c8560a95-0642-4618-8850-ae5275e4c29a'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: B9BA72513E7742979E53AEDCC22CA8CF Ref B: MNZ221060608035 Ref C: 2023-09-11T20:07:30Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 11 Sep 2023 20:07:30 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "startTime": "2023-09-11T20:06:29.8260796+00:00",
  "endTime": "2023-09-11T20:07:10.5612976+00:00",
  "status": "Failed",
  "error": {
    "code": "VMExtensionProvisioningError",
    "message": "VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: \"Enable failed: 'str' object has no attribute 'get'\". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot. "
  },
  "name": "bd03c3fd-e6c7-4b87-b96e-c13416b763ac"
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 517, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 556, in _poll
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1013, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 255, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 275, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 192, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 535, in run
azure.core.exceptions.HttpResponseError: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.

cli.azure.cli.core.azclierror: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.
az_command_data_logger: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'VMAccessForLinux' (publisher 'Microsoft.OSTCExtensions.Edp' and type 'VMAccessForLinux'). Error message: "Enable failed: 'str' object has no attribute 'get'". More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot. 
```

### Expected behavior

The expected behavior is that when a JSON string is passed to **--settings** and **--protected-settings**, the corresponding parameters, **settings** and **protected_settings** in the _set_extension_ function are passed into VirtualMachineExtension() as dictionaries.

This would involve calling `json.loads()` on both the parameters, so they are converted from JSON strings to Python dictionaries, and then passing the dictionaries in as parameters to create the VM extension.

### Environment Summary

azure-cli                         2.46.0 *

core                              2.46.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mayankdaruka\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @mayankdaruka-msft, in fact, we would convert the `--protected-settings` and `--settings` to json format before input to  set_extension function:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_params.py#L1137-L1138
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/validators.py#L106

You could try to add escape character to the string, e.g., 

```
az vm extension set -n VMAccessForLinux --publisher Microsoft.OSTCExtensions --version 1.4 --vm-name MyVm --resource-group MyResourceGroup --protected-settings '{\"username\":\"user1\", \"ssh_key\":\"ssh_rsa ...\"}'
```

**Comment by yanzhudd** [comment]
Hi @mayankdaruka-msft, 
I can't repro it as the debug log looks being well converted to JSON format:

![image](https://github.com/Azure/azure-cli/assets/105691024/2153fe44-6c28-48e8-8a1d-3584a0cc20b5)

![image](https://github.com/Azure/azure-cli/assets/105691024/7358d9db-0961-4b19-a142-e1fa362097e6)

I think the failure may be related to different ways of inputting JSON string in different operation systems and terminals.

**Comment by yanzhudd** [comment]
Hi @mayankdaruka-msft, sorry for the late reply. I am tied up recently. I will get back to you as soon as possible.

**Comment by yanzhudd** [comment]
@mayankdaruka-msft, oh, I can repro it in Command Prompt... Please use double quote instead of single quote to wrap the json string, i.e., 
--protected-settings **"**{\"username\": \"test\", \"password\": \"123\"}**"** 
instead of
--protected-settings **'**{\"username\": \"test\", \"password\": \"123\"}**'**

**Comment by yanzhudd** [comment]
Great! 
We will update it later.
