### ISSUE TITLE
az network private-dns record-set a add-record --resource-group --record-set-name --ipv4-address, fails with azure.core.exceptions.ResourceNotFoundError: (NotFound) The resource record '' does not exist in resource group. 2.52.0

### ISSUE THREAD

**Issue by mattiasclaesson** [Azure/azure-cli#27374]
### Describe the bug

Command worked in last version 2.51.0
Command is accordning to specification.
For some unknown reason the command now attempts to find the resource, since this is a add-record command it will not and fail.

### Related command

az network private-dns record-set a add-record --resource-group --record-set-name --ipv4-address

### Errors

ERROR: cli.azure.cli.core.azclierror: (NotFound) The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'xxxxxxxxxxxxxxxxxxxxxxx'.

### Issue script & Debug output

$ az network private-dns record-set a add-record --resource-group mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope --zone-name a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io --record-set-name webapi.mattias.claesson --ipv4-address 10.206.75.9 --debug

DEBUG: cli.knack.cli: Command arguments: ['network', 'private-dns', 'record-set', 'a', 'add-record', '--resource-group', 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope', '--zone-name', 'a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io', '--record-set-name', 'webapi.mattias.claesson', '--ipv4-address', '10.206.75.9', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01CFB4F0>, <function OutputProducer.on_global_arguments at 0x01EFE730>, <function CLIQuery.on_global_arguments at 0x01F18388>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: network                   0.620       115       453
DEBUG: cli.azure.cli.core: privatedns                0.032        14        60
DEBUG: cli.azure.cli.core: Total (2)                 0.652       129       513
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: Loaded 128 groups, 513 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : network private-dns record-set a add-record
DEBUG: cli.azure.cli.core: Command table: network private-dns record-set a add-record
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0410A580>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\40114616\.azure\commands\2023-09-12.11-20-53.network_private-dns_record-set_a_add-record.2860.log'.
INFO: az_command_data_logger: command args: network private-dns record-set a add-record --resource-group {} --zone-name {} --record-set-name {} --ipv4-address {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04135730>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x041466A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04146898>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01EFE778>, <function CLIQuery.handle_query_parameter at 0x01F183D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04146850>]
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\40114616\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: save: C:\Users\40114616\.azure\msal_http_cache.bin
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Found 1 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': '********.6af81d03-dafe-4d76-a257-3cc43cb0454f', 'family_id': '1'}
DEBUG: msal.telemetry: Generate or reuse correlation_id: e9dae67a-5062-45d8-90bc-091dbc1b372d
DEBUG: msal.application: Cache attempts an RT
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/token HTTP/1.1" 200 6747
DEBUG: msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "refresh_token": "********",
        "scope": [
            "openid",
            "profile",
            "https://management.core.windows.net//.default",
            "offline_access"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiIzY2Q4Yjc2OS00MDc1LTQwYTMtYTA2Mi0xZjhlMGJkZTJkMDgiLCJ1dGlkIjoiNmFmODFkMDMtZGFmZS00ZDc2LWEyNTctM2NjNDNjYjA0NTRmIn0",
        "expires_in": 5180,
        "ext_expires_in": 5180,
        "foci": "1",
        "id_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "skip_account_creation": true,
    "token_endpoint": "https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/token"
}
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/d358aa05-cbc2-477b-8012-ffee08ff8973/resourceGroups/mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope/providers/Microsoft.Network/privateDnsZones/a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io/A/webapi.mattias.claesson?api-version=2018-09-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'ab9f980d-514d-11ee-b172-3cf01158336e'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network private-dns record-set a add-record'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --zone-name --record-set-name --ipv4-address --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.18362-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/d358aa05-cbc2-477b-8012-ffee08ff8973/resourceGroups/mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope/providers/Microsoft.Network/privateDnsZones/a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io/A/webapi.mattias.claesson?api-version=2018-09-01 HTTP/1.1" 404 226
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'private'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '226'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ab9f980d-514d-11ee-b172-3cf01158336e'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '499'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f1f91b1e-7d9b-42ba-8e3d-35a494e35593'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20230912T092057Z:f1f91b1e-7d9b-42ba-8e3d-35a494e35593'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 12 Sep 2023 09:20:56 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"code":"NotFound","message":"The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'."}
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/2e98a3d4-e818-4d87-be41-bd0cfc6a6ab8/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 93153995-045a-4a5e-a880-e7366f9492eb
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/d358aa05-cbc2-477b-8012-ffee08ff8973/resourceGroups/mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope/providers/Microsoft.Network/privateDnsZones/a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io/A/webapi.mattias.claesson?api-version=2018-09-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'ab9f980d-514d-11ee-b172-3cf01158336e'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network private-dns record-set a add-record'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --zone-name --record-set-name --ipv4-address --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.18362-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/d358aa05-cbc2-477b-8012-ffee08ff8973/resourceGroups/mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope/providers/Microsoft.Network/privateDnsZones/a9ffb349-9068-4e9c-a5da-8c64d7b35aad.privatelink.westeurope.azmk8s.io/A/webapi.mattias.claesson?api-version=2018-09-01 HTTP/1.1" 404 226
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'private'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '226'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ab9f980d-514d-11ee-b172-3cf01158336e'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '499'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd0819043-a61f-44e4-bf8c-8f85d0b325f4'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20230912T092058Z:d0819043-a61f-44e4-bf8c-8f85d0b325f4'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 12 Sep 2023 09:20:57 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"code":"NotFound","message":"The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'."}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/privatedns/custom.py", line 965, in add_privatedns_a_record
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/privatedns/custom.py", line 947, in _privatedns_add_save_record
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 155, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/privatedns/aaz/latest/network/private_dns/record_set/_update.py", line 29, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/privatedns/aaz/latest/network/private_dns/record_set/_update.py", line 278, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/privatedns/aaz/latest/network/private_dns/record_set/_update.py", line 315, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 329, in on_error
azure.core.exceptions.ResourceNotFoundError: (NotFound) The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.
Code: NotFound
Message: The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.

ERROR: cli.azure.cli.core.azclierror: (NotFound) The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.
Code: NotFound
Message: The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.
ERROR: az_command_data_logger: (NotFound) The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.
Code: NotFound
Message: The resource record 'webapi.mattias.claesson' does not exist in resource group 'mc_rg-oden-demo-resources_aks-oden-shd-weu-002_westeurope' of subscription 'd358aa05-cbc2-477b-8012-ffee08ff8973'.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0410A6A0>]
INFO: az_command_data_logger: exit code: 3
INFO: cli.__main__: Command ran in 6.047 seconds (init: 0.381, invoke: 5.666)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3853 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\40114616\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The add-record should work as before. 

### Environment Summary

$ az --version
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\40114616\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

--if-none-match that is in the documentation does not work

**Comment by MattJeanes** [comment]
We're also seeing this in Azure Pipelines on `windows-latest` image version 20230910.1.0

Thank you for the workaround, we'll add that into our scripts until it's fixed 🙂
