### ISSUE TITLE
Azure cli storage upload command issues in linux redhat

### ISSUE THREAD

**Issue by B121215** [Azure/azure-cli#27394]
### Describe the bug

I was working with file upload from linux redhat server to azure storage account, While trying I am facing issues like below. Kindly help me.

### Related command

az storage blob upload --account-name storage_account_name --account-key storage_account_key -c container_name -n /path/to/blob -f /path/to/local_file

### Errors

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
az_command_data_logger: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f4329ab2400>]

### Issue script & Debug output

cli.knack.cli: Command arguments: ['storage', 'blob', 'upload', '--account-name', 'muleseastus2nprdstadls', '--account-key', 'd1Xy90gqu8JOEuicLD8EWHqvA5O63qvScX3+Dy5PSY//vApPkbsAUD62DAiRTtqw3FN17WNfNSbq+AStKOdBcg==', '-c', 'testfiletransfer', '-n', 'testfiletransfer/FileUpload', '-f', '/opt/app/mim/srini/rx_files/backup/Orphan_Fan_Query_202309121218.gz', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f432b23bae8>, <function OutputProducer.on_global_arguments at 0x7f432ad7fc80>, <function CLIQuery.on_global_arguments at 0x7f432ab22158>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.128        56       261
cli.azure.cli.core: Total (1)                 0.128        56       261
cli.azure.cli.core: Loaded 56 groups, 261 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage blob upload
cli.azure.cli.core: Command table: storage blob upload
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f4329ab21e0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/mim/.azure/commands/2023-09-14.05-20-37.storage_blob_upload.57967.log'.
az_command_data_logger: command args: storage blob upload --account-name {} --account-key {} -c {} -n {} -f {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f432963d048>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/fileshare/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/queue/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/cosmosdb/v2017_04_17/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/blob/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/blob/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 618, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_09_01.models' has no attribute 'AccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 618, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 614, in _get_attr
    op = import_module(full_mod_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lib64/az/lib/python3.6/site-packages/azure/multiapi/storagev2/blob/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

### Expected behavior

Have to transfer the file from redhat linux to my storage account.

### Environment Summary

azure-cli                         2.38.1

### Additional context

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by B121215** [comment]
Hi,

Thanks for the reply!

When I was trying to upgrade the azure cli verion in my Red hat linux machine I am facing below issue. 

[mim@zlt19357 /opt/app/mim]$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.1. Latest version available is None.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Loaded plugins: enabled_repos_upload, langpacks, package_upload, product-id, search-disabled-repos, subscription-manager
rhel-7-server-extras-rpms                                                                                                             | 1.9 kB  00:00:00
rhel-7-server-optional-rpms                                                                                                           | 1.9 kB  00:00:00
rhel-7-server-rh-common-rpms                                                                                                          | 2.0 kB  00:00:00
rhel-7-server-rpms                                                                                                                    | 2.2 kB  00:00:00
rhel-7-server-satellite-client-6-rpms                                                                                                 | 3.8 kB  00:00:00
rhel-7-server-supplementary-rpms                                                                                                      | 2.2 kB  00:00:00
rhel-server-rhscl-7-rpms                                                                                                              | 2.0 kB  00:00:00
No packages marked for update
Uploading Enabled Repositories Report
Loaded plugins: langpacks, product-id, subscription-manager
CLI upgrade failed or aborted.

Kindly help me here.

Thanks,
Gowthami

**Comment by B121215** [comment]
Please review below issue while I am running the command with latest version.

**Comment by bebound** [comment]
Please ignore the upgrade info, 2.38.1 is the latest version in rhel7.

Looks like an installation problem. Can you reproduce it in a clean centos7 docker environment?

**Comment by B121215** [comment]
Could you please help me with the steps to do?

**Comment by bebound** [comment]
Start a new centos:7 docker, then following the step in https://review.learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?branch=live&pivots=dnf#install-azure-cli to install CLI.
Run your command and see if the error persists.

`ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt` indicates that it's a Python interpreter error. What's the output of `az -v`?

**Comment by B121215** [comment]
let me check

**Comment by B121215** [comment]
[mim@zlt19357 /opt/app/mim]$ az -v
azure-cli                         2.38.1

 

core                              2.38.1
telemetry                          1.0.6

 

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

 

Python location '/bin/python3.6'
Extensions directory '/home/mim/.azure/cliextensions'

 

Python (Linux) 3.6.8 (default, Aug 13 2020, 07:46:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

 

Legal docs and information: aka.ms/AzureCliLegal

**Comment by B121215** [comment]
I have tried installing the Azure cli with below step intially.

**Comment by B121215** [comment]
> Start a new centos:7 docker, then following the step in https://review.learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?branch=live&pivots=dnf#install-azure-cli to install CLI. Run your command and see if the error persists.
> 
> `ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt` indicates that it's a Python interpreter error. What's the output of `az -v`?

I am unable to access the link to follow the steps to try.

**Comment by bebound** [comment]
The Python path should be `/usr/bin/python3.6`
It appears that you have a custom python3 in `/bin/python3.6` and it's broken.

`python3 -c 'from pyexpat import *'` should not raise any error.

**Comment by B121215** [comment]
while running this command - python3 -c 'from pyexpat import *'
 I am facing below issue.

[mim@zlt19357 /opt/app/mim]$ python3 -c 'from pyexpat import *'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt
[mim@zlt19357 /opt/app/mim]$

**Comment by bebound** [comment]
So this Python interpreter is the cause.
This issue is not related to CLI.

**Comment by B121215** [comment]
Can you suggest steps to solve this python interpreter issue?

**Comment by bebound** [comment]
**Do this at your own risk.**
If there is no other program uses `/bin/python3.6`, I suggest you removing it from PATH or relocating it.
