### ISSUE TITLE
az network command is unable understand syntax to use resourceID 

### ISSUE THREAD

**Issue by nishantrajmitra** [Azure/azure-cli#27395]
### Describe the bug

These below commands returning error though they were working a month ago properly:

az network vnet peering create -g $(resourceGroupName) -n $(aks_VnetName) --vnet-name $(functionapp_VnetName) --remote-vnet "/subscriptions/$(subscriptionId)/resourceGroups/$(regionResourceGroupName)/providers/Microsoft.Network/virtualNetworks/$(aks_VnetName)" --allow-vnet-access

ERROR: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' 

I tried with the suggested format from ERROR as well but it returning errors. please check

### Related command

az network vnet peering create -g $(resourceGroupName) -n $(aks_VnetName) --vnet-name $(functionapp_VnetName) --remote-vnet "/subscriptions/$(subscriptionId)/resourceGroups/$(regionResourceGroupName)/providers/Microsoft.Network/virtualNetworks/$(aks_VnetName)" --allow-vnet-access

### Errors

ERROR: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' 

### Issue script & Debug output

Peer Aks and Azure function VNETs
ERROR: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
ERROR: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
##[debug]Exit code 1 received from tool 'C:\Program Files\Git\bin\bash.exe'
##[debug]STDIO streams have closed for tool 'C:\Program Files\Git\bin\bash.exe'
##[debug]task result: Failed
##[error]Script failed with exit code: 1
##[debug]Processed: ##vso[task.issue type=error;]Script failed with exit code: 1
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with exit code: 1
##[debug]which 'az'

### Expected behavior

peering of vnet should have been done by this command

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nishantrajmitra** [comment]
The same command works on cloudshell but not on the devop agents
windows-latest or windows-2022 in ado pipelines.
Please check.

Thanks,
Nishant

**Comment by necusjz** [comment]
@nishantrajmitra Could you please provide the debug log with appending `--debug`?

**Comment by nishantrajmitra** [comment]
Please **reopen** the case as it's still _happening_. Below is **debug information**:

2023-11-15T09:33:11.8834426Z ##[debug]exec tool: C:\Program Files\Git\bin\bash.exe
2023-11-15T09:33:11.8835294Z ##[debug]arguments:
2023-11-15T09:33:11.8898845Z ##[debug]   D:\a\_temp\azureclitaskscript1700040721189.sh
2023-11-15T09:33:11.8900868Z [command]"C:\Program Files\Git\bin\bash.exe" D:\a\_temp\azureclitaskscript1700040721189.sh
2023-11-15T09:33:12.1032211Z Peer Aks and Azure function VNETs
2023-11-15T09:33:12.6954235Z DEBUG: cli.knack.cli: Command arguments: ['network', 'vnet', 'peering', 'create', '--resource-group', 'exxxxxxxxRSG000', '--name', 'exxxxxxvnet00', '--vnet-name', 'exxxxxxvnet02', '--remote-vnet', 'C:/Program Files/Git/subscriptions/xxxxxxxx-xxxf-xxxx-xxxx-03xxxxxxxxxx/resourceGroups/exxxxxxxxRSG000/providers/Microsoft.Network/virtualNetworks/exxxxxxvnet00', '--allow-vnet-access', '--debug']
2023-11-15T09:33:12.6960338Z DEBUG: cli.knack.cli: __init__ debug log:
2023-11-15T09:33:12.6961403Z Cannot enable color.
2023-11-15T09:33:12.6962224Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2023-11-15T09:33:12.6967715Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000002C0706956C0>, <function OutputProducer.on_global_arguments at 0x000002C070A043A0>, <function CLIQuery.on_global_arguments at 0x000002C070A2D6C0>]
2023-11-15T09:33:12.6970114Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2023-11-15T09:33:12.6977779Z DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
2023-11-15T09:33:12.6979201Z DEBUG: cli.azure.cli.core: Loading command modules:
2023-11-15T09:33:12.6980074Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2023-11-15T09:33:13.4948425Z DEBUG: cli.azure.cli.core: network                   0.796       115       463
2023-11-15T09:33:13.5214190Z DEBUG: cli.azure.cli.core: privatedns                0.026        14        60
2023-11-15T09:33:13.5215882Z DEBUG: cli.azure.cli.core: Total (2)                 0.823       129       523
2023-11-15T09:33:13.5232398Z DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
2023-11-15T09:33:13.5235958Z DEBUG: cli.azure.cli.core: Loading extensions:
2023-11-15T09:33:13.5238632Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
2023-11-15T09:33:13.5240044Z DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
2023-11-15T09:33:13.5241263Z DEBUG: cli.azure.cli.core: Loaded 128 groups, 523 commands.
2023-11-15T09:33:13.5242342Z DEBUG: cli.azure.cli.core: Found a match in the command table.
2023-11-15T09:33:13.5243508Z DEBUG: cli.azure.cli.core: Raw command  : network vnet peering create
2023-11-15T09:33:13.5244744Z DEBUG: cli.azure.cli.core: Command table: network vnet peering create
2023-11-15T09:33:13.5246724Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000002C073138820>]
2023-11-15T09:33:13.5250140Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'D:\a\_temp\.azclitask\commands\2023-11-15.09-33-13.network_vnet_peering_create.3816.log'.
2023-11-15T09:33:13.5253493Z INFO: az_command_data_logger: command args: network vnet peering create --resource-group {} --name {} --vnet-name {} --remote-vnet {} --allow-vnet-access --debug
2023-11-15T09:33:13.5256376Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000002C07313B490>]
2023-11-15T09:33:13.9703872Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2023-11-15T09:33:13.9706298Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000002C073191480>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000002C0731915A0>]
2023-11-15T09:33:13.9727983Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2023-11-15T09:33:13.9728956Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
2023-11-15T09:33:13.9764298Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000002C070A04430>, <function CLIQuery.handle_query_parameter at 0x000002C070A2D750>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000002C073191510>]
2023-11-15T09:33:14.1595401Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
2023-11-15T09:33:14.1597452Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 53, in format_args
2023-11-15T09:33:14.1599437Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 402, in __call__
2023-11-15T09:33:14.1601612Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 399, in __call__
2023-11-15T09:33:14.1606221Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 681, in __call__
2023-11-15T09:33:14.1608218Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 651, in __call__
2023-11-15T09:33:14.1611210Z azure.cli.core.aaz.exceptions.AAZInvalidArgValueError: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
2023-11-15T09:33:14.1613142Z 
2023-11-15T09:33:14.1613543Z During handling of the above exception, another exception occurred:
2023-11-15T09:33:14.1614030Z 
2023-11-15T09:33:14.1614238Z Traceback (most recent call last):
2023-11-15T09:33:14.1615480Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2023-11-15T09:33:14.1617273Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
2023-11-15T09:33:14.1619364Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2023-11-15T09:33:14.1621456Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
2023-11-15T09:33:14.1623391Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 155, in __call__
2023-11-15T09:33:14.1625718Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\vnet\peering\__cmds.py", line 46, in _handler
2023-11-15T09:33:14.1628000Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 165, in _handler
2023-11-15T09:33:14.1629945Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 55, in format_args
2023-11-15T09:33:14.1632999Z azure.cli.core.azclierror.InvalidArgumentValueError: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
2023-11-15T09:33:14.1634897Z 
2023-11-15T09:33:14.1636811Z ERROR: cli.azure.cli.core.azclierror: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
2023-11-15T09:33:14.1640888Z ERROR: az_command_data_logger: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format.
2023-11-15T09:33:14.1643479Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002C073138A60>]
2023-11-15T09:33:14.1644540Z INFO: az_command_data_logger: exit code: 1
2023-11-15T09:33:14.1645224Z INFO: cli.__main__: Command ran in 1.861 seconds (init: 0.394, invoke: 1.468)
2023-11-15T09:33:14.2176473Z INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
2023-11-15T09:33:14.2177762Z INFO: telemetry.client: Accumulated 0 events. Flush the clients.
2023-11-15T09:33:14.2178881Z INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
2023-11-15T09:33:14.2184086Z INFO: telemetry.save: Save telemetry record of length 3607 in cache

**Comment by nishantrajmitra** [comment]
> Please **reopen** the case as it's still _happening_. Below is **debug information**:
> 
> 2023-11-15T09:33:11.8834426Z ##[debug]exec tool: C:\Program Files\Git\bin\bash.exe 2023-11-15T09:33:11.8835294Z ##[debug]arguments: 2023-11-15T09:33:11.8898845Z ##[debug] D:\a_temp\azureclitaskscript1700040721189.sh 2023-11-15T09:33:11.8900868Z [command]"C:\Program Files\Git\bin\bash.exe" D:\a_temp\azureclitaskscript1700040721189.sh 2023-11-15T09:33:12.1032211Z Peer Aks and Azure function VNETs 2023-11-15T09:33:12.6954235Z DEBUG: cli.knack.cli: Command arguments: ['network', 'vnet', 'peering', 'create', '--resource-group', 'exxxxxxxxRSG000', '--name', 'exxxxxxvnet00', '--vnet-name', 'exxxxxxvnet02', '--remote-vnet', 'C:/Program Files/Git/subscriptions/xxxxxxxx-xxxf-xxxx-xxxx-03xxxxxxxxxx/resourceGroups/exxxxxxxxRSG000/providers/Microsoft.Network/virtualNetworks/exxxxxxvnet00', '--allow-vnet-access', '--debug'] 2023-11-15T09:33:12.6960338Z DEBUG: cli.knack.cli: **init** debug log: 2023-11-15T09:33:12.6961403Z Cannot enable color. 2023-11-15T09:33:12.6962224Z DEBUG: cli.knack.cli: Event: Cli.PreExecute [] 2023-11-15T09:33:12.6967715Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000002C0706956C0>, <function OutputProducer.on_global_arguments at 0x000002C070A043A0>, <function CLIQuery.on_global_arguments at 0x000002C070A2D6C0>] 2023-11-15T09:33:12.6970114Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate [] 2023-11-15T09:33:12.6977779Z DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns'] 2023-11-15T09:33:12.6979201Z DEBUG: cli.azure.cli.core: Loading command modules: 2023-11-15T09:33:12.6980074Z DEBUG: cli.azure.cli.core: Name Load Time Groups Commands 2023-11-15T09:33:13.4948425Z DEBUG: cli.azure.cli.core: network 0.796 115 463 2023-11-15T09:33:13.5214190Z DEBUG: cli.azure.cli.core: privatedns 0.026 14 60 2023-11-15T09:33:13.5215882Z DEBUG: cli.azure.cli.core: Total (2) 0.823 129 523 2023-11-15T09:33:13.5232398Z DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next'] 2023-11-15T09:33:13.5235958Z DEBUG: cli.azure.cli.core: Loading extensions: 2023-11-15T09:33:13.5238632Z DEBUG: cli.azure.cli.core: Name Load Time Groups Commands Directory 2023-11-15T09:33:13.5240044Z DEBUG: cli.azure.cli.core: Total (0) 0.000 0 0 2023-11-15T09:33:13.5241263Z DEBUG: cli.azure.cli.core: Loaded 128 groups, 523 commands. 2023-11-15T09:33:13.5242342Z DEBUG: cli.azure.cli.core: Found a match in the command table. 2023-11-15T09:33:13.5243508Z DEBUG: cli.azure.cli.core: Raw command : network vnet peering create 2023-11-15T09:33:13.5244744Z DEBUG: cli.azure.cli.core: Command table: network vnet peering create 2023-11-15T09:33:13.5246724Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000002C073138820>] 2023-11-15T09:33:13.5250140Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'D:\a_temp.azclitask\commands\2023-11-15.09-33-13.network_vnet_peering_create.3816.log'. 2023-11-15T09:33:13.5253493Z INFO: az_command_data_logger: command args: network vnet peering create --resource-group {} --name {} --vnet-name {} --remote-vnet {} --allow-vnet-access --debug 2023-11-15T09:33:13.5256376Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument..add_subscription_parameter at 0x000002C07313B490>] 2023-11-15T09:33:13.9703872Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad [] 2023-11-15T09:33:13.9706298Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument..add_ids_arguments at 0x000002C073191480>, <function register_cache_arguments..add_cache_arguments at 0x000002C0731915A0>] 2023-11-15T09:33:13.9727983Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded [] 2023-11-15T09:33:13.9728956Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [] 2023-11-15T09:33:13.9764298Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000002C070A04430>, <function CLIQuery.handle_query_parameter at 0x000002C070A2D750>, <function register_ids_argument..parse_ids_arguments at 0x000002C073191510>] 2023-11-15T09:33:14.1595401Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last): 2023-11-15T09:33:14.1597452Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 53, in format_args 2023-11-15T09:33:14.1599437Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 402, in **call** 2023-11-15T09:33:14.1601612Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 399, in **call** 2023-11-15T09:33:14.1606221Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 681, in **call** 2023-11-15T09:33:14.1608218Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_fmt.py", line 651, in **call** 2023-11-15T09:33:14.1611210Z azure.cli.core.aaz.exceptions.AAZInvalidArgValueError: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format. 2023-11-15T09:33:14.1613142Z 2023-11-15T09:33:14.1613543Z During handling of the above exception, another exception occurred: 2023-11-15T09:33:14.1614030Z 2023-11-15T09:33:14.1614238Z Traceback (most recent call last): 2023-11-15T09:33:14.1615480Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke 2023-11-15T09:33:14.1617273Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 663, in execute 2023-11-15T09:33:14.1619364Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 726, in _run_jobs_serially 2023-11-15T09:33:14.1621456Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 697, in _run_job 2023-11-15T09:33:14.1623391Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 155, in **call** 2023-11-15T09:33:14.1625718Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\vnet\peering__cmds.py", line 46, in _handler 2023-11-15T09:33:14.1628000Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 165, in _handler 2023-11-15T09:33:14.1629945Z File "D:\a_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command_ctx.py", line 55, in format_args 2023-11-15T09:33:14.1632999Z azure.cli.core.azclierror.InvalidArgumentValueError: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format. 2023-11-15T09:33:14.1634897Z 2023-11-15T09:33:14.1636811Z ERROR: cli.azure.cli.core.azclierror: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format. 2023-11-15T09:33:14.1640888Z ERROR: az_command_data_logger: InvalidArgumentValue: --remote-vnet: Invalid format: resource id should be in '/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Network/virtualNetworks/{}' format. 2023-11-15T09:33:14.1643479Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002C073138A60>] 2023-11-15T09:33:14.1644540Z INFO: az_command_data_logger: exit code: 1 2023-11-15T09:33:14.1645224Z INFO: cli.**main**: Command ran in 1.861 seconds (init: 0.394, invoke: 1.468) 2023-11-15T09:33:14.2176473Z INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1 2023-11-15T09:33:14.2177762Z INFO: telemetry.client: Accumulated 0 events. Flush the clients. 2023-11-15T09:33:14.2178881Z INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1 2023-11-15T09:33:14.2184086Z INFO: telemetry.save: Save telemetry record of length 3607 in cache

**Comment by nishantrajmitra** [comment]
@yonzhan please look into this.

**Comment by nishantrajmitra** [comment]
the double quotation was missing which contained 'newtorkResourceId'. this fixed error
