### ISSUE TITLE
"az network dns zone export" fails with empty TXT records

### ISSUE THREAD

**Issue by mikeclayton** [Azure/azure-cli#27396]
### Describe the bug

Attempting to export a DNS zone with a TXT record that has an empty value results in the following error:

```
The command failed with an unexpected error. Here is the traceback:
'txt'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 2633, in export_zone
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/make_zone_file.py", line 96, in make_zone_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 134, in process_txt
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 55, in _quote_field
KeyError: 'txt'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Related command

```az network dns zone export --subscription "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --resource-group "my-dns" --name "my.dns.zone"```

### Errors

```
The command failed with an unexpected error. Here is the traceback:
'txt'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 2633, in export_zone
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/make_zone_file.py", line 96, in make_zone_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 134, in process_txt
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/zone_file/record_processors.py", line 55, in _quote_field
KeyError: 'txt'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Set up a test environment

This script sets up ta new dns zone with an empty TXT record, but you can do it through manually via https://portal.azure.com as well...

```powershell
# set up some variables for the script
$subscriptionId        = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
$resourceGroupName     = "my-dns";
$zoneName              = "my.dns.zone";
$recordType            = "TXT";
$relativeRecordSetName = "@";
$apiVersion            = "2023-07-01-preview"; # "2018-05-01" also fails

# create a new dns zone so we've got a clean environment to test
$azZone = New-AzDnsZone `
    -ResourceGroupName $resourceGroupName `
    -Name              $zoneName;

# add a TXT recordset with an empty value
#
# note that neither "az cli" nor the Az PowerShell cmdlets will let us create
# a TXT record with an empty value - they both throw parameter validation
# errors, so we have to either create it via https://portal.azure.com or invoke
# the raw rest api using "az rest" which *do* allow empty values.
#
# see:
#   https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest
#   https://learn.microsoft.com/en-us/rest/api/dns/record-sets/create-or-update?tabs=HTTP#create-txt-recordset

$resourceId = `
    "/subscriptions/$subscriptionId" +
    "/resourceGroups/$resourceGroupName" +
    "/providers/Microsoft.Network" +
    "/dnsZones/$zoneName" +
    "/$recordType/$relativeRecordSetName";

# using Chrome's F12 dev tools shows this body is what https://portal.azure.com sends
# when creating an empty TXT record manually in a browser
$restBody = @{
  "id"         = $resourceId
  "name"       = "@"
  "type"       = "Microsoft.Network/dnszones/TXT"
  "properties" = @{
    "TTL"            = 3600
    "targetResource" = $null
    "ARecords"       = $null
    "AAAARecords"    = $null
    "caaRecords"     = $null
    "CNAMERecord"    = $null
    "MXRecords"      = $null
    "NSRecords"      = $null
    "SOARecord"      = $null
    "SRVRecords"     = $null
    "TXTRecords"     = $null
    "PTRRecords"     = $null
  }
} | ConvertTo-Json -Depth 99 -Compress;
$restBody = $restBody.Replace('"', '\"');

az rest `
  --uri     "https://management.azure.com$($resourceId)?api-version=$apiVersion" `
  --method  "PUT" `
  --headers "Content-Type=application/json" `
  --body    $restBody `
  --debug
```

## Reproduce the issue

With the environment set up with an empty TXT record using the above script, this command reproduces the error:

```powershell
az network dns zone export `
  --subscription   $subscriptionId `
  --resource-group $resourceGroupName  `
  --name           $zoneName
```

### Expected behavior

The DNS zone serialized properly to text, *including* an empty TXT record.

### Environment Summary

```
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory '********'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Additional context

There are other duplicate issues reported but have been closed with workarounds that I can't use:

* https://github.com/Azure/azure-cli/issues/23645
* https://github.com/Azure/azure-cli/issues/27021

The suggested resolution for these was to delete the empty TXT record, but I don't have this option as I don't have jurisdiction over the DNS configuration

---
And a similar issue
s
* https://github.com/Azure/azure-cli/issues/27391 - coincidentally raised a very short time ago. Affects AAAA and CNAME records, but It's probably got the same root cause based around handling empty values for fields

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mikeclayton** [comment]
Note: The workaround in the issue linked by the bot isn't viable for me. - I don't have jurisdiction over the DNS config so I can't delete TXT records with empty values. (I can raise tickets with the appropriate teams to *request* they delete them on a case-by-case basis, but I don't have control over whether any action is taken).

For context, I'm writing a simple "backup" script which will use the "az network dns export" command to export all of our dns zones to text files and then store them somewhere safe.

I have "read" access to the dns zones, but not "write" access so I can't make any changes, and since the zones are administered by other parties I can't control whether they might create more empty TXT zones in future, either by design or by mistake.

Ideally I need to be able to export the zones into files that can be used to import back into Azure DNS in the case that a zone gets mistakenly modified or deleted and needs to be restored back to a previous state with high fidelity, including empty TXT records and any other unusual-but-allowed settings.

**Comment by mikeclayton** [comment]
The attached zip is a isolated repro of the az cli python code which is easier to play with than the whole az cli codebase:

[repro.zip](https://github.com/Azure/azure-cli/files/12608902/repro.zip)

The cause seems to be that [```export_zone```](https://github.com/Azure/azure-cli/blob/cd6a794555b1541a6b6e254c909213de253369c0/src/azure-cli/azure/cli/command_modules/network/custom.py#L2546) uses ```_DNSRecordSetListByZone``` to retrieve the zone details, but that normally includes some json like this if there's a TXT record in the zone:

**TXT "example-value"**
```
      "TXTRecords": [
        {
          "value": [
            "example-value"
          ]
        }
      ],
```

but if there's an **empty** TXT record it contains this line:

**TXT ""**
```
      "TXTRecords": [],
```

In the happy path, ```export_zone``` uses the above to generate a modified object model like this, which it passes to [```make_zone_file```](https://github.com/Azure/azure-cli/blob/cd6a794555b1541a6b6e254c909213de253369c0/src/azure-cli/azure/cli/command_modules/network/zone_file/make_zone_file.py#L27):

**TXT "example-value"**
```
('example', OrderedDict([('txt', [{'ttl': 3600, 'txt': 'example-value'}])]))]
```

However, in the case of the empty TXT record it generates this:

**TXT ""**
```
 ('txt', [{'ttl': 3600}])]))
```

The call chain ultimately leads down to [```_quote_field(data, field)```](https://github.com/Azure/azure-cli/blob/cd6a794555b1541a6b6e254c909213de253369c0/src/azure-cli/azure/cli/command_modules/network/zone_file/record_processors.py#L42) where it tries to evaluate ```data[field]``` which is  equivalent to ```{'ttl': 3600, 'txt': 'example-value'}['txt']``` and ```{'ttl': 3600}['txt']``` respectively in the two previous examples - the latter fails with the error ```KeyError: 'txt'``` because it doesn't have a ```txt``` key in the ```data``` parameter.

A band-aid fix is to add this to ```export_zone```:

[custom.py#L2630]( https://github.com/Azure/azure-cli/blob/cd6a794555b1541a6b6e254c909213de253369c0/src/azure-cli/azure/cli/command_modules/network/custom.py#L2630
)
```
            elif record_type == 'txt':
                record_obj.update({'txt': ''})
```
which fudges the empty TXT record to look like this


**TXT ""**
```
 ('txt', [{'ttl': 3600, 'txt': ''}])]))
```

which then *does* have a ```txt``` key when it gets passed to ```field```.

I'm not convinced that's the best solution though as I think there's a wider issue with az cli not liking or handling empty values in dns records (see #27391 for a different but similar issue with empty values in fields)...

**Comment by mikeclayton** [comment]
Note - the equivalent ```private-dns``` command appears to have a cut&paste version of the code for ```dns``` with some modifications. There's an additional guard in ```export_zone``` here:

https://github.com/Azure/azure-cli/blob/cd6a794555b1541a6b6e254c909213de253369c0/src/azure-cli/azure/cli/command_modules/privatedns/custom.py#L178-L180

which omits records with an empty value - that means private dns zones with an empty TXT record work with

```
az network private-dns zone export --subscription "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --resource-group "my-dns" --name "test.test"
```

It's *better*, but it's not really *ideal* because re-importing the resulting zone file wouldn't recreate the empty TXT record so it doesn't round-trip with 100% fidelity...
