### ISSUE TITLE
Azure CLI "list index out of range" error when creating Static Web App with Azure Repos

### ISSUE THREAD

**Issue by asadsaeed** [Azure/azure-cli#27423]
### Describe the bug

When attempting to create a new static web app with Azure CLI using an Azure Repository as the source, the command fails and yields a "list index out of range" error message. Notably, the script does not prompt for a personal access token (PAT), although it is expected to.:

**To Reproduce**

1. Tried to use Azure CLI to execute the above az staticwebapp create command.
2. Encountered the error mentioned above.

### Related command

Here's the command I used:
```bash
az staticwebapp create \
  --name my-app-name \
  --resource-group my-resource-groupname \
  --location centralus \
  --source "{AzureDevOpsRepoURL}" \
  --branch master \
  --login-with-ado
```

### Errors

```bash
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: list index out of range
```

Complete traceback log:

```bash
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: list index out of range
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 444, in create_staticsites
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 392, in _get_ado_token
IndexError: list index out of range
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

```

### Issue script & Debug output

DEBUG: cli.knack.cli: Command arguments: ['staticwebapp', 'create', '--debug', '--name', 'patriotfire-dev-ui', '--resource-group', '{rresource-group-name}', '--location', 'centralus', '--source', '{url}', '--branch', 'master', '--login-with-ado']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000021196EB53F0>, <function OutputProducer.on_global_arguments at 0x00000211970300D0>, <function CLIQuery.on_global_arguments at 0x000002119724D3F0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'staticwebapp': ['azure.cli.command_modules.appservice']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: appservice                0.208        73       260
DEBUG: cli.azure.cli.core: Total (1)                 0.208        73       260
DEBUG: cli.azure.cli.core: Loaded 73 groups, 260 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : staticwebapp create
DEBUG: cli.azure.cli.core: Command table: staticwebapp create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000211999885E0>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\masad\.azure\commands\2023-09-19.14-43-23.staticwebapp_create.36288.log'.
INFO: az_command_data_logger: command args: staticwebapp create --debug --name {} --resource-group {} --location {} --source {} --branch {} --login-with-ado
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000002119998B250>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000211999E1240>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000211999E1360>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000021197030160>, <function CLIQuery.handle_query_parameter at 0x000002119724D480>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000211999E12D0>]
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=WebSiteManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\masad\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\masad\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{id}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{id}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{id}/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 2f2835dd-a986-4662-8f7f-50dcbbf77e6c
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/7742ab87-cdc1-4540-bb7f-f70eb06d0138/resourceGroups/ReporteqBackup/providers/Microsoft.Web/staticSites/patriotfire-dev-ui?api-version=2022-03-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '{id}'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'staticwebapp create'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --name --resource-group --location --source --branch --login-with-ado'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (MSI) azsdk-python-azure-mgmt-web/7.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/{}/resourceGroups/{resourcegroupname}/providers/Microsoft.Web/staticSites/{app-name}?api-version=2022-03-01 HTTP/1.1" 404 230
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '230'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '7cd425da-d133-4f90-aa5f-d6f94dbfb273'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7cd425da-d133-4f90-aa5f-d6f94dbfb273'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20230919T094326Z:7cd425da-d133-4f90-aa5f-d6f94dbfb273'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: AAD92190057E48A8B107009C9E96BF9B Ref B: AMS231022012009 Ref C: 2023-09-19T09:43:26Z'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 19 Sep 2023 09:43:25 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/staticSites/patriotfire-dev-ui' under resource group 'ReporteqBackup' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
DEBUG: cli.azure.cli.core.util: Retrieving token for resource https://management.core.windows.net/
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{ID}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{id}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{ID}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{ID}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{id}/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: {id}
INFO: cli.azure.cli.core.util: Request URL: 'https://app.vssps.visualstudio.com/_apis/profile/profiles/me?api-version=5.1'
INFO: cli.azure.cli.core.util: Request method: 'GET'
INFO: cli.azure.cli.core.util: Request headers:
INFO: cli.azure.cli.core.util:     'User-Agent': 'python/3.10.10 (Windows-10-10.0.22621-SP0) AZURECLI/2.52.0 (MSI)'
INFO: cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
INFO: cli.azure.cli.core.util:     'Accept': '*/*'
INFO: cli.azure.cli.core.util:     'Connection': 'keep-alive'
INFO: cli.azure.cli.core.util:     'x-ms-client-request-id': 'bf180fa4-8819-40c9-9cd2-c8a3c862a11a'
INFO: cli.azure.cli.core.util:     'CommandName': 'staticwebapp create'
INFO: cli.azure.cli.core.util:     'ParameterSetName': '--debug --name --resource-group --location --source --branch --login-with-ado'
INFO: cli.azure.cli.core.util:     'Authorization': 'Bearer ..................'
INFO: cli.azure.cli.core.util: Request body:
INFO: cli.azure.cli.core.util: None
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): app.vssps.visualstudio.com:443
DEBUG: urllib3.connectionpool: https://app.vssps.visualstudio.com:443 "GET /_apis/profile/profiles/me?api-version=5.1 HTTP/1.1" 200 291
INFO: cli.azure.cli.core.util: Response status: 200
INFO: cli.azure.cli.core.util: Response headers:
INFO: cli.azure.cli.core.util:     'Cache-Control': 'no-cache, no-store, must-revalidate'
INFO: cli.azure.cli.core.util:     'Pragma': 'no-cache'
INFO: cli.azure.cli.core.util:     'Content-Length': '291'
INFO: cli.azure.cli.core.util:     'Content-Type': 'application/json; charset=utf-8; api-version=5.1'
INFO: cli.azure.cli.core.util:     'Content-Encoding': 'gzip'
INFO: cli.azure.cli.core.util:     'Expires': '-1'
INFO: cli.azure.cli.core.util:     'Last-Modified': 'Mon, 15 Feb 2021 09:18:37 GMT'
INFO: cli.azure.cli.core.util:     'ETag': '"0"'
INFO: cli.azure.cli.core.util:     'Vary': 'Accept-Encoding'
INFO: cli.azure.cli.core.util:     'P3P': 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"'
INFO: cli.azure.cli.core.util:     'Set-Cookie': 'VstsSession=%7B%22PersistentSessionId%22%3A%22580bc257-8552-44df-9773-420d8ed32425%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId{id}SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.visualstudio.com; expires=Wed, 18-Sep-2024 09:43:27 GMT; path=/; secure; HttpOnly'
INFO: cli.azure.cli.core.util:     'X-TFS-ProcessId': 'fcce96e7-32f6-4f21-bff9-adc35976cb46'
INFO: cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
INFO: cli.azure.cli.core.util:     'ActivityId': 'e6499e6a-ea0d-4ab7-a23b-5e976c45c42e'
INFO: cli.azure.cli.core.util:     'X-TFS-Session': 'e6499e6a-ea0d-4ab7-a23b-5e976c45c42e'
INFO: cli.azure.cli.core.util:     'X-VSS-E2EID': 'e6499e6a-ea0d-4ab7-a23b-5e976c45c42e'
INFO: cli.azure.cli.core.util:     'X-VSS-SenderDeploymentId': 'a5ca35eb-148e-4ccd-bbb3-d31576d75958'
INFO: cli.azure.cli.core.util:     'X-VSS-UserData': '{UserData}'
INFO: cli.azure.cli.core.util:     'X-FRAME-OPTIONS': 'SAMEORIGIN'
INFO: cli.azure.cli.core.util:     'Request-Context': 'appId=cid-v1:20b3930f-73dc-453a-b660-e3891d782eef'
INFO: cli.azure.cli.core.util:     'Access-Control-Expose-Headers': 'Request-Context'
INFO: cli.azure.cli.core.util:     'X-Content-Type-Options': 'nosniff'
INFO: cli.azure.cli.core.util:     'X-Cache': 'CONFIG_NOCACHE'
INFO: cli.azure.cli.core.util:     'X-MSEdge-Ref': 'Ref A: 3F185B233C2E40A6AB5BD8A536640499 Ref B: DXB30EDGE0114 Ref C: 2023-09-19T09:43:27Z'
INFO: cli.azure.cli.core.util:     'Date': 'Tue, 19 Sep 2023 09:43:27 GMT'
INFO: cli.azure.cli.core.util: Response content:
INFO: cli.azure.cli.core.util: {"displayName":"Asad","publicAlias":"{ID}{","emailAddress":"{email}","coreRevision":351076717,"timeStamp":"2021-02-15T09:18:37.35+00:00","id":"{email}","revision":351076717}
DEBUG: cli.azure.cli.core.util: Retrieving token for resource https://management.core.windows.net/
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{id}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{id}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{id}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{id}/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 0c87386f-04a0-4325-afb7-a75189a06e20
INFO: cli.azure.cli.core.util: Request URL: 'https://app.vssps.visualstudio.com/_apis/accounts?api-version=5.1&memberId=e20ef766-3187-6e8b-8a11-9aaa5345b1cc'
INFO: cli.azure.cli.core.util: Request method: 'GET'
INFO: cli.azure.cli.core.util: Request headers:
INFO: cli.azure.cli.core.util:     'User-Agent': 'python/3.10.10 (Windows-10-10.0.22621-SP0) AZURECLI/2.52.0 (MSI)'
INFO: cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
INFO: cli.azure.cli.core.util:     'Accept': '*/*'
INFO: cli.azure.cli.core.util:     'Connection': 'keep-alive'
INFO: cli.azure.cli.core.util:     'x-ms-client-request-id': '19ddf0c2-d2da-457c-ab0a-696f3cf03d41'
INFO: cli.azure.cli.core.util:     'CommandName': 'staticwebapp create'
INFO: cli.azure.cli.core.util:     'ParameterSetName': '--debug --name --resource-group --location --source --branch --login-with-ado'
INFO: cli.azure.cli.core.util:     'Authorization': 'Bearer eyJ0eXAiOiJKV...'
INFO: cli.azure.cli.core.util: Request body:
INFO: cli.azure.cli.core.util: None
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): app.vssps.visualstudio.com:443
DEBUG: urllib3.connectionpool: https://app.vssps.visualstudio.com:443 "GET /_apis/accounts?api-version=5.1&memberId=e20ef766-3187-6e8b-8a11-9aaa5345b1cc HTTP/1.1" 200 261
INFO: cli.azure.cli.core.util: Response status: 200
INFO: cli.azure.cli.core.util: Response headers:
INFO: cli.azure.cli.core.util:     'Cache-Control': 'no-cache, no-store, must-revalidate'
INFO: cli.azure.cli.core.util:     'Pragma': 'no-cache'
INFO: cli.azure.cli.core.util:     'Content-Length': '261'
INFO: cli.azure.cli.core.util:     'Content-Type': 'application/json; charset=utf-8; api-version=5.1'
INFO: cli.azure.cli.core.util:     'Content-Encoding': 'gzip'
INFO: cli.azure.cli.core.util:     'Expires': '-1'
INFO: cli.azure.cli.core.util:     'Vary': 'Accept-Encoding'
INFO: cli.azure.cli.core.util:     'P3P': 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"'
INFO: cli.azure.cli.core.util:     'Set-Cookie': 'VstsSession=%7B%22PersistentSessionId%22%3A%2247962515-46a1-4abd-8edf-8dd7c46ace0a%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.visualstudio.com; expires=Wed, 18-Sep-2024 09:43:27 GMT; path=/; secure; HttpOnly'
INFO: cli.azure.cli.core.util:     'X-TFS-ProcessId': '3d2e4f93-fce0-4b3d-9e45-5c490fa5c4e7'
INFO: cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
INFO: cli.azure.cli.core.util:     'ActivityId': 'bbb7c22e-40de-4d20-bd7a-d5cfddf73a74'
INFO: cli.azure.cli.core.util:     'X-TFS-Session': 'bbb7c22e-40de-4d20-bd7a-d5cfddf73a74'
INFO: cli.azure.cli.core.util:     'X-VSS-E2EID': 'bbb7c22e-40de-4d20-bd7a-d5cfddf73a74'
INFO: cli.azure.cli.core.util:     'X-VSS-SenderDeploymentId': 'a5ca35eb-148e-4ccd-bbb3-d31576d75958'
INFO: cli.azure.cli.core.util:     'X-VSS-UserData': '{id}:{email}'
INFO: cli.azure.cli.core.util:     'X-FRAME-OPTIONS': 'SAMEORIGIN'
INFO: cli.azure.cli.core.util:     'Request-Context': 'appId=cid-v1:20b3930f-73dc-453a-b660-e3891d782eef'
INFO: cli.azure.cli.core.util:     'Access-Control-Expose-Headers': 'Request-Context'
INFO: cli.azure.cli.core.util:     'X-Content-Type-Options': 'nosniff'
INFO: cli.azure.cli.core.util:     'X-Cache': 'CONFIG_NOCACHE'
INFO: cli.azure.cli.core.util:     'X-MSEdge-Ref': 'Ref A: 7EE7A777656249D8A4B5FDD1836F4752 Ref B: DXB30EDGE0107 Ref C: 2023-09-19T09:43:27Z'
INFO: cli.azure.cli.core.util:     'Date': 'Tue, 19 Sep 2023 09:43:27 GMT'
INFO: cli.azure.cli.core.util: Response content:
INFO: cli.azure.cli.core.util: {"count":1,"value":[{"accountId":"{accountid}","accountUri":"https://vssps.dev.azure.com:443/{id}/","accountName":"{name}","properties":{}}]}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 444, in create_staticsites
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 392, in _get_ado_token
IndexError: list index out of range

### Expected behavior

The expectation was for the Azure CLI to prompt for a PAT that I had already generated, then create the static web app successfully when the command was run with that PAT.

### Environment Summary

```bash
{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by asadsaeed** [comment]
From the DEBUG logs, it appears that Azure CLI may only fetch the Personal Access Token (PAT) for the Azure DevOps organizations that are connected to my personal user account. If the repository exists under an organization where a user is only a member (and not an owner), Azure CLI fails to fetch the token for this organization, resulting in the 'list index out of range' error."

**Comment by asadsaeed** [comment]
> Hi @asadsaeed Find similar issue #10117.
> 
> Issue title	webapp: az webapp up failed
> Create time	2019-08-01
> Comment number	3
> Possible solution: According to the existing issue, there was an API regression that returned an empty array of values required for webapp creation. The issue was resolved on August 1st at around 3 am PST. Therefore, it is recommended to retry the command and check if the issue still persists.
> 
> Please confirm if this resolves your issue.

I tried the command on 9th September 2023. As I have shared in the issue details, I am running the latest version of Azure CLI.
