### ISSUE TITLE
Error while creating Postgres Flexible read replica through az cli

### ISSUE THREAD

**Issue by tomasz-sroka** [Azure/azure-cli#27422]
### Describe the bug

The command failed with an unexpected error. Here is the traceback:
'addressPrefix'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 498, in flexible_replica_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 877, in flexible_server_provision_network_resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 122, in prepare_private_network
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 155, in process_private_network_with_id_input
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 213, in _create_vnet_subnet_delegation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 250, in _create_subnet_delegation
KeyError: 'addressPrefix'

### Related command

az postgres flexible-server replica create --subscription f3eb8206-61e4-4819-97cd-1c8104e396ff --replica-name psp0000872-ne-replica --resource-group postgres-prod-rg-ne-001 --source-server /subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/postgres-prod-rg-we-001/providers/Microsoft.DBforPostgreSQL/flexibleServers/psp0000872 --location northeurope --no-wait --private-dns-zone /subscriptions/9bf73fab-d17b-42e1-a997-36770f36980a/resourceGroups/network_prod_dns_we/providers/Microsoft.Network/privateDnsZones/prod.dbaas.private.postgres.database.azure.com --yes --subnet /subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/azure-platform-networking-ne/providers/Microsoft.Network/virtualNetworks/postgres-prod-vnet-ne-001/subnets/postgres-prod-vnet-ne-001-psql

### Errors

The command failed with an unexpected error. Here is the traceback:
'addressPrefix'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 498, in flexible_replica_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 877, in flexible_server_provision_network_resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 122, in prepare_private_network
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 155, in process_private_network_with_id_input
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 213, in _create_vnet_subnet_delegation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 250, in _create_subnet_delegation
KeyError: 'addressPrefix'

### Issue script & Debug output

cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': 'W/"92aa0570-504d-4b0f-8f7c-22f7ca45b4c1"'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '98880507-d161-4f58-b2f6-db298cc92b1e'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'cfdf1be2-d54c-401f-bb88-459512263968'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': 'e14b9a9f-3d7c-4a86-b795-b36ac0ec659b'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11967'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWITZERLANDNORTH:20230919T092801Z:cfdf1be2-d54c-401f-bb88-459512263968'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 19 Sep 2023 09:28:00 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "postgres-prod-vnet-ne-001-psql",
  "id": "/subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/azure-platform-networking-ne/providers/Microsoft.Network/virtualNetworks/postgres-prod-vnet-ne-001/subnets/postgres-prod-vnet-ne-001-psql",
  "etag": "W/\"92aa0570-504d-4b0f-8f7c-22f7ca45b4c1\"",
  "properties": {
    "provisioningState": "Succeeded",
    "addressPrefixes": [
      "172.27.240.0/23"
    ],
    "routeTable": {
      "id": "/subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/azure-platform-networking-ne/providers/Microsoft.Network/routeTables/postgres-prod-vnet-ne-001-rt"
    },
    "serviceAssociationLinks": [
      {
        "name": "a4c7c170-9086-650a-b1b4-698bef0d69ec-service-association-link",
        "id": "/subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/azure-platform-networking-ne/providers/Microsoft.Network/virtualNetworks/postgres-prod-vnet-ne-001/subnets/postgres-prod-vnet-ne-001-psql/serviceAssociationLinks/a4c7c170-9086-650a-b1b4-698bef0d69ec-service-association-link",
        "etag": "W/\"92aa0570-504d-4b0f-8f7c-22f7ca45b4c1\"",
        "type": "Microsoft.Network/virtualNetworks/subnets/serviceAssociationLinks",
        "properties": {
          "provisioningState": "Succeeded",
          "linkedResourceType": "Microsoft.DBforPostgreSQL/flexibleServers",
          "enabledForArmDeployments": false,
          "allowDelete": false,
          "locations": []
        }
      }
    ],
    "serviceEndpoints": [
      {
        "provisioningState": "Succeeded",
        "service": "Microsoft.Storage",
        "locations": [
          "northeurope",
          "westeurope"
        ]
      }
    ],
    "delegations": [
      {
        "name": "dlg-Microsoft.DBforPostgreSQL-flexibleServers",
        "id": "/subscriptions/f3eb8206-61e4-4819-97cd-1c8104e396ff/resourceGroups/azure-platform-networking-ne/providers/Microsoft.Network/virtualNetworks/postgres-prod-vnet-ne-001/subnets/postgres-prod-vnet-ne-001-psql/delegations/dlg-Microsoft.DBforPostgreSQL-flexibleServers",
        "etag": "W/\"92aa0570-504d-4b0f-8f7c-22f7ca45b4c1\"",
        "properties": {
          "provisioningState": "Succeeded",
          "serviceName": "Microsoft.DBforPostgreSQL/flexibleServers",
          "actions": [
            "Microsoft.Network/virtualNetworks/subnets/join/action"
          ]
        },
        "type": "Microsoft.Network/virtualNetworks/subnets/delegations"
      }
    ],
    "privateEndpointNetworkPolicies": "Disabled",
    "privateLinkServiceNetworkPolicies": "Enabled"
  },
  "type": "Microsoft.Network/virtualNetworks/subnets"
}
cli.azure.cli.command_modules.rdbms.flexible_server_virtual_network: Using existing Subnet "postgres-prod-vnet-ne-001-psql" in resource group "azure-platform-networking-ne"
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 498, in flexible_replica_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 877, in flexible_server_provision_network_resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 122, in prepare_private_network
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 155, in process_private_network_with_id_input
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 213, in _create_vnet_subnet_delegation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 250, in _create_subnet_delegation
KeyError: 'addressPrefix'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'addressPrefix'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 498, in flexible_replica_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 877, in flexible_server_provision_network_resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 122, in prepare_private_network
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 155, in process_private_network_with_id_input
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 213, in _create_vnet_subnet_delegation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 250, in _create_subnet_delegation
KeyError: 'addressPrefix'
az_command_data_logger: 'addressPrefix'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 498, in flexible_replica_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 877, in flexible_server_provision_network_resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 122, in prepare_private_network
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 155, in process_private_network_with_id_input
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 213, in _create_vnet_subnet_delegation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/rdbms/flexible_server_virtual_network.py", line 250, in _create_subnet_delegation
KeyError: 'addressPrefix'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x041FE4F0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 8.704 seconds (init: 0.652, invoke: 8.052)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7250 in cache
telemetry.check: Negative: The C:\Users\s6xa8a\.azure\telemetry.txt was modified at 2023-09-19 11:23:10.767463, which in less than 600.000000 s

### Expected behavior

New read replica should be created through az cli

### Environment Summary

azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.26.0
interactive                        0.4.5

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\s6xa8a\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
@tomasz-sroka Thanks for reporting this issue. This problem shows up when the subnet was created using the properties.addressPrefixes[] instead of the properties.addressPrefix attribute to define the address space of the subnet in which you want to inject your instance https://learn.microsoft.com/en-us/rest/api/virtualnetwork/subnets/create-or-update?view=rest-virtualnetwork-2023-09-01&tabs=HTTP#request-body.

We'll be fixing this as soon as possible.
