### ISSUE TITLE
az cosmosdb create with public-network-access SECUREDBYPERIMETER

### ISSUE THREAD

**Issue by themidnightcom** [Azure/azure-cli#27431]
### Describe the bug

The documentation 
https://learn.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest

states that 
{DISABLED, ENABLED, SECUREDBYPERIMETER}

Are valid values for the parameter
--public-network-access

For the command
az cosmosdb create 

However, when passing SECUREDBYPERIMETER to az cosmosdb create/update, the response is: 
(BadRequest) PublicNetworkAccess property cannot be updated to SecuredByPerimeter.

### Related command

 az cosmosdb create --name $CosmosAccountName --resource-group $ResourceGroupName --public-network-access SECUREDBYPERIMETER

### Errors

(BadRequest) PublicNetworkAccess property cannot be updated to SecuredByPerimeter.
ActivityId: a333ca09-5737-11ee-bdf5-ecb1d74e5ec1, Microsoft.Azure.Documents.Common/2.14.0
Code: BadRequest
Message: PublicNetworkAccess property cannot be updated to SecuredByPerimeter.
ActivityId: a333ca09-5737-11ee-bdf5-ecb1d74e5ec1, Microsoft.Azure.Documents.Common/2.14.0

### Issue script & Debug output

az cosmosdb create --name testingcreatewfirewall3 --resource-group MyResourceGroup --public-network-access SECUREDBYPERIMETER --debug

cli.knack.cli: Command arguments: ['cosmosdb', 'create', '--name', 'testingcreatewfirewall3', '--resource-group', '*****', '--public-network-access', 'SECUREDBYPERIMETER', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01DFB580>, <function OutputProducer.on_global_arguments at 0x01FFB7C0>, <function CLIQuery.on_global_arguments at 0x02018418>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'cosmosdb': ['azure.cli.command_modules.cosmosdb']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: cosmosdb                  0.229        58       192
cli.azure.cli.core: Total (1)                 0.229        58       192
cli.azure.cli.core: Loaded 58 groups, 192 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : cosmosdb create
cli.azure.cli.core: Command table: cosmosdb create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0419B658>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\*****\.azure\commands\2023-09-20.10-08-35.cosmosdb_create.33796.log'.
az_command_data_logger: command args: cosmosdb create --name {} --resource-group {} --public-network-access {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x041C27C0>]
cli.knack.commands: Configured default 'learn-81a7a8c3-0b85-4891-a5e6-d7992f9ad0a4' for arg resource_group_name
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x041D3730>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x041D3928>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x0420EF58>]
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01FFB808>, <function CLIQuery.handle_query_parameter at 0x02018460>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x041D38E0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CosmosDBManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\*****\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\*****\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/*****/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/*****/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/*****/kerberos', 'tenant_region_scope': 'OC', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/*****/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/*****/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/*****/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/*****/kerberos', 'tenant_region_scope': 'OC', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 499b8d62-2633-4836-9b5a-3e462dfd4920
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/*****/resourcegroups/*****?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '13d40cbd-5739-11ee-bbef-ecb1d74e5ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'cosmosdb create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --public-network-access --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/*****/resourcegroups/*****?api-version=2022-09-01 HTTP/1.1" 200 299
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f93f364f-044a-4211-9871-3e6fb5c09aea'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f93f364f-044a-4211-9871-3e6fb5c09aea'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230919T220836Z:f93f364f-044a-4211-9871-3e6fb5c09aea'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 19 Sep 2023 22:08:36 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '299'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/*****/resourceGroups/*****","name":"*****","type":"Microsoft.Resources/resourceGroups","location":"australiaeast","tags":{},"properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 78fea88b-5cc0-444f-8da7-e9427015d951
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/*****/resourceGroups/*****/providers/Microsoft.DocumentDB/databaseAccounts/testingcreatewfirewall3?api-version=2023-04-15'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '303'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '13d40cbd-5739-11ee-bbef-ecb1d74e5ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'cosmosdb create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --public-network-access --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (MSI) azsdk-python-mgmt-cosmosdb/9.2.0 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "australiaeast", "kind": "GlobalDocumentDB", "properties": {"locations": [{"locationName": "australiaeast", "failoverPriority": 0, "isZoneRedundant": false}], "databaseAccountOfferType": "Standard", "publicNetworkAccess": "SECUREDBYPERIMETER", "apiProperties": {}, "createMode": "Default"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/*****/resourceGroups/*****/providers/Microsoft.DocumentDB/databaseAccounts/testingcreatewfirewall3?api-version=2023-04-15 HTTP/1.1" 400 196
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-store, no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '196'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-gatewayversion': 'version=2.14.0'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '0a0deef1-9789-4c11-af4a-d39310ff9acd'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0a0deef1-9789-4c11-af4a-d39310ff9acd'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230919T220837Z:0a0deef1-9789-4c11-af4a-d39310ff9acd'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 19 Sep 2023 22:08:36 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"code":"BadRequest","message":"PublicNetworkAccess property cannot be updated to SecuredByPerimeter.\r\nActivityId: 13d40cbd-5739-11ee-bbef-ecb1d74e5ec1, Microsoft.Azure.Documents.Common/2.14.0"}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cosmosdb/custom.py", line 153, in cli_cosmosdb_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cosmosdb/custom.py", line 369, in _create_database_account
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/cosmosdb/operations/_database_accounts_operations.py", line 1139, in begin_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/cosmosdb/operations/_database_accounts_operations.py", line 1003, in _create_or_update_initial
azure.core.exceptions.HttpResponseError: (BadRequest) PublicNetworkAccess property cannot be updated to SecuredByPerimeter.
ActivityId: 13d40cbd-5739-11ee-bbef-ecb1d74e5ec1, Microsoft.Azure.Documents.Common/2.14.0
Code: BadRequest
Message: PublicNetworkAccess property cannot be updated to SecuredByPerimeter.
ActivityId: 13d40cbd-5739-11ee-bbef-ecb1d74e5ec1, Microsoft.Azure.Documents.Common/2.14.0

### Expected behavior

The CosmosDB account should be provisioned the same as if "Selected networks" is selected as the "Public network access" option in the Azure portal.

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\****\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
