### ISSUE TITLE
Unable to use "az login" through private endpoint of resource manager (managed identity can be available) 

### ISSUE THREAD

**Issue by yuriwoof** [Azure/azure-cli#27453]
### Issue Description

I'm testing Azure CLI in closed environment which is described in below document.
I'm not surely understanding why "az login" failed and managed identitty (`az login --identity`) works in this scenario.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/create-private-link-access-commands?tabs=azure-cli

---

I confirmed that "management.azure.com" is resolved as private IP (10.0.0.4).

```
$ nslookup management.azure.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
management.azure.com    canonical name = management.privatelink.azure.com.
Name:   management.privatelink.azure.com
Address: 10.0.0.4
```

After installing Azure CLI, and I hit "az login" command and had following error (PrivateLinkAccessRestricted).
It failed to get subscriptions against https://management.azure.com/subscriptions?api-version=2019-11-01.

```
$ az login --debug

...

cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: eb6d40b4-6c15-4f58-8dd0-5705fa4c5600
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '6b0aa821-5829-11ee-a1ab-5d603f9e4def'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (DEB) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Linux-6.2.0-1012-azure-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: [https://management.azure.com:443](https://management.azure.com/) "GET /subscriptions?api-version=2019-11-01 HTTP/1.1" 200 161
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '62028fc9-cc9a-4ead-b83c-c2029bb9f35f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '62028fc9-cc9a-4ead-b83c-c2029bb9f35f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JAPANEAST:20230921T024923Z:62028fc9-cc9a-4ead-b83c-c2029bb9f35f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 02:49:22 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '161'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[],"count":{"type":"Total","value":0}}
cli.azure.cli.core._profile: Finding subscriptions under tenant 61c68011-22ce-4e06-a57a-ccedad28d3c9 'Contoso Marketing Company'
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/61c68011-22ce-4e06-a57a-ccedad28d3c9/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net/'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 3433a038-fcde-4456-8803-6c020169ff9f
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '6b0aa821-5829-11ee-a1ab-5d603f9e4def'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (DEB) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Linux-6.2.0-1012-azure-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: [https://management.azure.com:443](https://management.azure.com/) "GET /subscriptions?api-version=2019-11-01 HTTP/1.1" 200 161
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'df6d1482-9841-4131-a933-c2f9623aca0b'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'df6d1482-9841-4131-a933-c2f9623aca0b'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JAPANEAST:20230921T024923Z:df6d1482-9841-4131-a933-c2f9623aca0b'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 02:49:22 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '161'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[],"count":{"type":"Total","value":0}}
cli.azure.cli.core._profile: Finding subscriptions under tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 'Microsoft'
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net/'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 8eae2e66-d271-4450-b900-d34251889daf
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '6b0aa821-5829-11ee-a1ab-5d603f9e4def'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (DEB) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Linux-6.2.0-1012-azure-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: [https://management.azure.com:443](https://management.azure.com/) "GET /subscriptions?api-version=2019-11-01 HTTP/1.1" 403 289
cli.azure.cli.core.sdk.policies: Response status: 403
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '6744682a-b97e-472a-9940-4ef79eaccd4e'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '6744682a-b97e-472a-9940-4ef79eaccd4e'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JAPANEAST:20230921T024923Z:6744682a-b97e-472a-9940-4ef79eaccd4e'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 02:49:23 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies:     'Content-Length': '289'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"PrivateLinkAccessRestricted","message":"Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 176, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 759, in find_using_common_tenant
    subscriptions = self.find_using_specific_tenant(tenant_id, specific_tenant_credential)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 809, in find_using_specific_tenant
    for s in subscriptions:
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 526, in get_next
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (PrivateLinkAccessRestricted) Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
Code: PrivateLinkAccessRestricted
Message: Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.

cli.azure.cli.core.azclierror: (PrivateLinkAccessRestricted) Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
Code: PrivateLinkAccessRestricted
Message: Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
az_command_data_logger: (PrivateLinkAccessRestricted) Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
Code: PrivateLinkAccessRestricted
Message: Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f621aa030a0>]
az_command_data_logger: exit code: 1
```

It hit same URL but it works in case of managed ID.

```
$ az login --identity --debug

...

msrestazure.azure_active_directory: MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
msrestazure.azure_active_directory: MSI: Token retrieved
cli.azure.cli.core._profile: MSI: token was retrieved. Now trying to initialize local accounts...
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msrestazure.azure_active_directory: MSI: token is found in cache.
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1695351291' -> 1695351291
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'ea4e999d-582a-11ee-a1ab-5d603f9e4def'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--identity --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (DEB) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Linux-6.2.0-1012-azure-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: [https://management.azure.com:443](https://management.azure.com/) "GET /subscriptions?api-version=2019-11-01 HTTP/1.1" 200 429
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c97cd9c6-b03a-49a9-9051-9dabc7a8082c'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c97cd9c6-b03a-49a9-9051-9dabc7a8082c'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JAPANEAST:20230921T025944Z:c97cd9c6-b03a-49a9-9051-9dabc7a8082c'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 02:59:44 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '429'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"id":"/subscriptions/<mysub>","authorizationSource":"RoleBased","managedByTenants":[],"subscriptionId":"<mysub>","tenantId":"<mytenant>","displayName":"Visual Studio Enterprise Subscription","state":"Enabled","subscriptionPolicies":{"locationPlacementId":"Public_2014-09-01","quotaId":"MSDN_2014-09-01","spendingLimit":"On"}}],"count":{"type":"Total","value":1}}
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f812079ad40>, <function _x509_from_base64_to_hex_transform at 0x7f812079add0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
[
  {
    "environmentName": "AzureCloud",
    "homeTenantId": "<mytenant>",
    "id": "<mysub>",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Visual Studio Enterprise Subscription",
    "state": "Enabled",
    "tenantId": "<mytenant>",
    "user": {
      "assignedIdentityInfo": "MSI",
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f81207530a0>]
az_command_data_logger: exit code: 0
```

### Related command

az login

### Errors

(PrivateLinkAccessRestricted) Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.
Code: PrivateLinkAccessRestricted
Message: Request originated from private virtual network for resource '/subscriptions', but this resource can not be accessed from a private endpoint. To connect to this resource, please use the public network without a private endpoint.

### Issue script & Debug output

Please check description in "Describe the bug"

### Expected behavior

Able to sing in with azure cli as well.

### Environment Summary

{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
From the debug log, you can see not all `https://management.azure.com/subscriptions?api-version=2019-11-01` requests return `403`. Only `72f988bf-86f1-41af-91ab-2d7cd011db47 'Microsoft'` tenant returns `403`:

```
cli.azure.cli.core._profile: Finding subscriptions under tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 'Microsoft'
...
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
...
cli.azure.cli.core.sdk.policies: Response status: 403
```

As the error is returned by ARM service, I would recommend contacting [Azure Support](https://azure.microsoft.com/en-us/support) or Microsoft tenant support for this issue. Thanks for your understanding.
