### ISSUE TITLE
API profile broken for az vmss

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#27451]
### Describe the bug

API profile broken for "az vmss list-instances".

It is trying to use API version 2023-03-01 for API profile 2020-09-01, which is obviously wrong. Noticed there were commits named something like "Migrate commands to Code Gen V2", which might be causing the issue (@yanzhudd FYI).

### Related command

az vmss list-instances -n $vmssName -g $vmssRgName

### Errors

```
az : ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 
'virtualMachineScaleSets/virtualMachines'. The supported api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 
2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
At line:1 char:1
+ az vmss list-instances -n testvmss -g clivmssrg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: (NoRegis... are 'redmond'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 'virtualMachineScaleSets/virtualMachines'. The supported 
api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 
2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
```

### Issue script & Debug output

```
PS C:\Users\Administrator.RQ0301-DVM> az vmss list-instances -n testvmss -g clivmssrg --debug
az : DEBUG: cli.knack.cli: Command arguments: ['vmss', 'list-instances', '-n', 'testvmss', '-g', 'clivmssrg', '--debug']
At line:1 char:1
+ az vmss list-instances -n testvmss -g clivmssrg --debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG: cli.knac...rg', '--debug']:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01A7A538>, <function OutputProducer.on_global_arguments 
at 0x01FFB778>, <function CLIQuery.on_global_arguments at 0x021183D0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'vmss': ['azure.cli.command_modules.vm']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: vm                        0.292        57       222
DEBUG: cli.azure.cli.core: Total (1)                 0.292        57       222
DEBUG: cli.azure.cli.core: Loaded 57 groups, 222 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : vmss list-instances
DEBUG: cli.azure.cli.core: Command table: vmss list
DEBUG: cli.azure.cli.core: remaining    :           instances
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0427B610>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 
'C:\Users\Administrator.RQ0301-DVM\.azure\commands\2023-09-22.05-14-45.vmss_list-instances.15728.log'.
INFO: az_command_data_logger: command args: vmss list-instances -n {} -g {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x042A5970>]
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'VMGuestPatchRebootSetting'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'VMGuestPatchClassificationWindows'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'VMGuestPatchClassificationLinux'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'GallerySharingPermissionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_12_01.models' has no attribute 'ReplicationMode'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'DiskControllerTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'SharedToValues'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'SecurityTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_07_01.models' has no attribute 'NetworkAccessPolicy'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_07_01.models' has no attribute 'NetworkAccessPolicy'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_07_01.models' has no attribute 'DiskSecurityTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_07_01.models' has no attribute 'Architecture'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_07_01.models' has no attribute 'Architecture'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'DiskDeleteOptionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'DiskDeleteOptionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'DiskDeleteOptionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'SecurityEncryptionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'SecurityEncryptionTypes'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2019_12_01.models' has no attribute 'Architecture'
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2020_06_01.models' has no attribute 'ConsistencyModeTypes'
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x042B2A90>, <function 
register_cache_arguments.<locals>.add_cache_arguments at 0x042B2B20>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01FFB7C0>, <function CLIQuery.handle_query_parameter at 
0x02118418>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x042B2AD8>]
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Administrator.RQ0301-DVM\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\Administrator.RQ0301-DVM\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'issuer': 'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/dae9aea9-a980-4a75-a127-9948eeb63224/', 
'authorization_endpoint': 'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/oauth2/authorize/', 'token_endpoint': 
'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/oauth2/token/', 'jwks_uri': 
'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/discovery/keys', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'client_secret_basic', 
'private_key_jwt', 'windows_client_authentication'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token', 'code token', 'code id_token 
token'], 'response_modes_supported': ['query', 'fragment', 'form_post'], 'grant_types_supported': ['authorization_code', 'refresh_token', 'client_credentials', 
'urn:ietf:params:oauth:grant-type:jwt-bearer', 'implicit', 'password', 'srv_challenge', 'urn:ietf:params:oauth:grant-type:device_code', 'device_code'], 
'subject_types_supported': ['pairwise'], 'scopes_supported': ['winhello_cert', 'profile', '.default', 'aza', 'logon_cert', 'vpn_cert', 'email', 'openid', 
'user_impersonation', 'allatclaims'], 'id_token_signing_alg_values_supported': ['RS256'], 'token_endpoint_auth_signing_alg_values_supported': ['RS256'], 
'access_token_issuer': 'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/dae9aea9-a980-4a75-a127-9948eeb63224/', 'claims_supported': ['aud', 'iss', 'iat', 
'exp', 'auth_time', 'nonce', 'at_hash', 'c_hash', 'sub', 'upn', 'unique_name', 'pwd_url', 'pwd_exp', 'mfa_auth_time', 'sid', 'nbf'], 'microsoft_multi_refresh_token': 
True, 'userinfo_endpoint': 'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/userinfo', 'capabilities': ['kdf_ver2'], 'end_session_endpoint': 
'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/oauth2/logout', 'as_access_token_token_binding_supported': False, 
'as_refresh_token_token_binding_supported': False, 'resource_access_token_token_binding_supported': False, 'op_id_token_token_binding_supported': False, 
'rp_id_token_token_binding_supported': False, 'frontchannel_logout_supported': True, 'frontchannel_logout_session_supported': True, 'device_authorization_endpoint': 
'https://adfs.redmond.ext-rq0301.masd.stbtest.microsoft.com/adfs/oauth2/devicecode'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: 
scopes=('https://management.adfs.rq0301.masd.stbtest.microsoft.com/dae9aea9-a980-4a75-a127-9948eeb63224/.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: 
scopes=('https://management.adfs.rq0301.masd.stbtest.microsoft.com/dae9aea9-a980-4a75-a127-9948eeb63224/.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: c6d915bc-876d-46fc-9b13-d9a6be941695
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.redmond.ext-rq0301.masd.stbtest.microsoft.com/subscriptions/ff804056-adef-4d43-85aa-6d2033f3b9ca/
resourceGroups/clivmssrg/providers/Microsoft.Compute/virtualMachineScaleSets/testvmss/virtualMachines?api-version=2023-03-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f1b0601b-5906-11ee-8472-00155d1cfe2e'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'vmss list-instances'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -g --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.17763-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.redmond.ext-rq0301.masd.stbtest.microsoft.com:443
DEBUG: urllib3.connectionpool: https://management.redmond.ext-rq0301.masd.stbtest.microsoft.com:443 "GET /subscriptions/ff804056-adef-4d43-85aa-6d2033f3b9ca/resourceGroup
s/clivmssrg/providers/Microsoft.Compute/virtualMachineScaleSets/testvmss/virtualMachines?api-version=2023-03-01 HTTP/1.1" 400 440
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e494ce11-2be7-4cb4-85ca-f9ed094181ed'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e494ce11-2be7-4cb4-85ca-f9ed094181ed'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'REDMOND:20230922T051446Z:e494ce11-2be7-4cb4-85ca-f9ed094181ed'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 22 Sep 2023 05:14:46 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '440'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'redmond' and API 
version '2023-03-01' for type 'virtualMachineScaleSets/virtualMachines'. The supported api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 
2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2021-11-01'. The supported locations are 'redmond'."}}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_paging.py", line 87, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_paging.py", line 43, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 250, in executor_wrapper
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\vm\aaz_compact\latest\vmss\__cmds.py", line 2597, in 
_execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\azure\cli\command_modules\vm\aaz_compact\latest\vmss\__cmds.py", line 2622, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 
'virtualMachineScaleSets/virtualMachines'. The supported api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 
2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 'virtualMachineScaleSets/virtualMachines'. The supported 
api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 
2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
ERROR: cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 
'virtualMachineScaleSets/virtualMachines'. The supported api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 
2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 'virtualMachineScaleSets/virtualMachines'. The supported 
api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 
2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
ERROR: az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 
'virtualMachineScaleSets/virtualMachines'. The supported api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 
2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'redmond' and API version '2023-03-01' for type 'virtualMachineScaleSets/virtualMachines'. The supported 
api-versions are '2015-06-15, 2015-11-01, 2016-03-30, 2016-08-30, 2017-03-30, 2017-12-01, 2018-04-01, 2018-06-01, 2018-10-01, 2019-03-01, 2019-07-01, 2019-12-01, 
2020-06-01, 2021-11-01'. The supported locations are 'redmond'.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0427B730>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.330 seconds (init: 0.406, invoke: 0.924)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 4232 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft 
SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\Administrator.RQ0301-DVM\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Should not try to use API version 2023-03-01 for API profile 2020-09-01 for `virtualMachineScaleSets/virtualMachines`.

### Environment Summary

```
azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Administrator.RQ0301-DVM\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @TheOnlyWei, this issue has been fixed and will be released in the coming new version of CLI around 11-15.
