### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: '..databricks-0.10.2.dist-info'

### ISSUE THREAD

**Issue by syedhamjath** [Azure/azure-cli#27470]
### Describe the bug

I get this error message when I try to get AD token for https://database.windows.net/

### Related command

$token = $(az account get-access-token --resource=https://database.windows.net/ --query accessToken)
Write-host "Variable name DacPacToken is set with token value"
Write-host "##vso[task.setvariable variable=DacPacToken;issecret=true]$token"

### Errors

PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'

### Issue script & Debug output

2023-09-25T18:43:21.1243908Z ##[debug]Evaluating condition for step: 'Request token for deployment'
2023-09-25T18:43:21.1245029Z ##[debug]Evaluating: SucceededNode()
2023-09-25T18:43:21.1245364Z ##[debug]Evaluating SucceededNode:
2023-09-25T18:43:21.1246104Z ##[debug]=> True
2023-09-25T18:43:21.1246577Z ##[debug]Result: True
2023-09-25T18:43:21.1246986Z ##[section]Starting: Request token for deployment
2023-09-25T18:43:21.1405411Z ==============================================================================
2023-09-25T18:43:21.1405588Z Task         : Azure CLI
2023-09-25T18:43:21.1405671Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
2023-09-25T18:43:21.1405935Z Version      : 2.225.0
2023-09-25T18:43:21.1406023Z Author       : Microsoft Corporation
2023-09-25T18:43:21.1406135Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2023-09-25T18:43:21.1406317Z ==============================================================================
2023-09-25T18:43:21.1633754Z ##[debug]Using node path: C:\Data\Agent\externals\node16\bin\node.exe
2023-09-25T18:43:21.7391591Z ##[debug]agent.TempDirectory=C:\Data\Agent\_work\_temp
2023-09-25T18:43:21.7406613Z ##[debug]loading inputs and endpoints
2023-09-25T18:43:21.7427068Z ##[debug]loading ENDPOINT_AUTH_e636603a-3e3b-4322-a62c-e6c580aec420
2023-09-25T18:43:21.7476552Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_e636603a-3e3b-4322-a62c-e6c580aec420_AUTHENTICATIONTYPE
2023-09-25T18:43:21.7479342Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_e636603a-3e3b-4322-a62c-e6c580aec420_SCOPE
2023-09-25T18:43:21.7481794Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_e636603a-3e3b-4322-a62c-e6c580aec420_SERVICEPRINCIPALID
2023-09-25T18:43:21.7484310Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_e636603a-3e3b-4322-a62c-e6c580aec420_SERVICEPRINCIPALKEY
2023-09-25T18:43:21.7487016Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_e636603a-3e3b-4322-a62c-e6c580aec420_TENANTID
2023-09-25T18:43:21.7490572Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2023-09-25T18:43:21.7493511Z ##[debug]loading ENDPOINT_AUTH_SCHEME_e636603a-3e3b-4322-a62c-e6c580aec420
2023-09-25T18:43:21.7496811Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2023-09-25T18:43:21.7500389Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2023-09-25T18:43:21.7505305Z ##[debug]loading INPUT_ADDSPNTOENVIRONMENT
2023-09-25T18:43:21.7508998Z ##[debug]loading INPUT_CONNECTEDSERVICENAMEARM
2023-09-25T18:43:21.7512427Z ##[debug]loading INPUT_CWD
2023-09-25T18:43:21.7515849Z ##[debug]loading INPUT_FAILONSTANDARDERROR
2023-09-25T18:43:21.7518224Z ##[debug]loading INPUT_INLINESCRIPT
2023-09-25T18:43:21.7520487Z ##[debug]loading INPUT_POWERSHELLERRORACTIONPREFERENCE
2023-09-25T18:43:21.7522725Z ##[debug]loading INPUT_POWERSHELLIGNORELASTEXITCODE
2023-09-25T18:43:21.7524692Z ##[debug]loading INPUT_SCRIPTLOCATION
2023-09-25T18:43:21.7526752Z ##[debug]loading INPUT_SCRIPTPATH
2023-09-25T18:43:21.7528728Z ##[debug]loading INPUT_SCRIPTTYPE
2023-09-25T18:43:21.7531894Z ##[debug]loading INPUT_USEGLOBALCONFIG
2023-09-25T18:43:21.7535679Z ##[debug]loading SECRET_ANSIBLETOWER_KEY
2023-09-25T18:43:21.7537984Z ##[debug]loading SECRET_ANSIBLETOWER_USER_PART
2023-09-25T18:43:21.7540170Z ##[debug]loading SECRET_BUILDER_PASSWORD
2023-09-25T18:43:21.7543375Z ##[debug]loading SECRET_GLOBALREPORTPASSWORD
2023-09-25T18:43:21.7545609Z ##[debug]loading SECRET_IB_APPLICATION_GATEWAY_SECRET
2023-09-25T18:43:21.7547722Z ##[debug]loading SECRET_SERVICENOW_OA_DEV_CLIENT_ID
2023-09-25T18:43:21.7549808Z ##[debug]loading SECRET_SERVICENOW_OA_DEV_CLIENT_SECRET
2023-09-25T18:43:21.7551956Z ##[debug]loading SECRET_SERVICENOW_OA_DEV_REFRESH_TOKEN
2023-09-25T18:43:21.7554025Z ##[debug]loading SECRET_SERVICENOW_OA_ET_CLIENT_ID
2023-09-25T18:43:21.7556057Z ##[debug]loading SECRET_SERVICENOW_OA_ET_CLIENT_SECRET
2023-09-25T18:43:21.7558117Z ##[debug]loading SECRET_SERVICENOW_OA_ET_REFRESH_TOKEN
2023-09-25T18:43:21.7560194Z ##[debug]loading SECRET_SERVICENOW_OA_PR_CLIENT_ID
2023-09-25T18:43:21.7563580Z ##[debug]loading SECRET_SERVICENOW_OA_PR_CLIENT_SECRET
2023-09-25T18:43:21.7565842Z ##[debug]loading SECRET_SERVICENOW_OA_PR_REFRESH_TOKEN
2023-09-25T18:43:21.7567967Z ##[debug]loading SECRET_SERVICENOW_OA_ST_CLIENT_ID
2023-09-25T18:43:21.7569865Z ##[debug]loading SECRET_SERVICENOW_OA_ST_CLIENT_SECRET
2023-09-25T18:43:21.7571846Z ##[debug]loading SECRET_SERVICENOW_OA_ST_REFRESH_TOKEN
2023-09-25T18:43:21.7573867Z ##[debug]loading SECRET_SOLO_FORTIFYSSC_ANALYSISUPLOADTOKEN
2023-09-25T18:43:21.7576183Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2023-09-25T18:43:21.7578297Z ##[debug]loading SECRET_TARGETHOSTPASSWORD
2023-09-25T18:43:21.7580235Z ##[debug]loading SECRET_TARGETHOSTUSERNAME
2023-09-25T18:43:21.7582175Z ##[debug]loading SECRET_XLD-SECURITY-USER-PWD
2023-09-25T18:43:21.7584226Z ##[debug]loading SECRET_XLDPRIVATEKEYFILE
2023-09-25T18:43:21.7586144Z ##[debug]loading SECRET_XLRELEASE_TOKEN
2023-09-25T18:43:21.7594322Z ##[debug]loaded 45
2023-09-25T18:43:21.7599528Z ##[debug]Agent.ProxyUrl=undefined
2023-09-25T18:43:21.7600736Z ##[debug]Agent.CAInfo=undefined
2023-09-25T18:43:21.7601270Z ##[debug]Agent.ClientCert=undefined
2023-09-25T18:43:21.7601668Z ##[debug]Agent.SkipCertValidation=undefined
2023-09-25T18:43:23.4962361Z ##[debug]check path : C:\Data\Agent\_work\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.225.0\task.json
2023-09-25T18:43:23.4965567Z ##[debug]adding resource file: C:\Data\Agent\_work\_tasks\AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815\2.225.0\task.json
2023-09-25T18:43:23.4966039Z ##[debug]system.culture=en-US
2023-09-25T18:43:23.5186612Z ##[debug]which 'az'
2023-09-25T18:43:23.5333588Z ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
2023-09-25T18:43:23.5342022Z ##[debug]scriptType=pscore
2023-09-25T18:43:23.5344280Z ##[debug]scriptLocation=inlineScript
2023-09-25T18:43:23.5344811Z ##[debug]scriptArguments=undefined
2023-09-25T18:43:23.5350050Z ##[debug]powerShellErrorActionPreference=stop
2023-09-25T18:43:23.5351615Z ##[debug]Agent.Version=3.225.0
2023-09-25T18:43:23.5352258Z ##[debug]Agent.TempDirectory=C:\Data\Agent\_work\_temp
2023-09-25T18:43:23.5354450Z ##[debug]scriptPath=C:\Data\Agent\_work\563\s
2023-09-25T18:43:23.5356285Z ##[debug]inlineScript=$token = $(az account get-access-token --resource=https://database.windows.net/ --query accessToken)
Write-host "Variable name DacPacToken is set with token value"
Write-host "##vso[task.setvariable variable=DacPacToken;issecret=true]$token"
2023-09-25T18:43:23.5376642Z ##[debug]powerShellIgnoreLASTEXITCODE=false
2023-09-25T18:43:23.5384575Z ##[debug]which 'pwsh'
2023-09-25T18:43:23.5692050Z ##[debug]found: 'C:\Program Files\PowerShell\7\pwsh.exe'
2023-09-25T18:43:23.5693037Z ##[debug]which 'C:\Program Files\PowerShell\7\pwsh.exe'
2023-09-25T18:43:23.5696069Z ##[debug]found: 'C:\Program Files\PowerShell\7\pwsh.exe'
2023-09-25T18:43:23.5696867Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: -NoLogo
2023-09-25T18:43:23.5697515Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: -NoProfile
2023-09-25T18:43:23.5698125Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: -NonInteractive
2023-09-25T18:43:23.5698697Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: -ExecutionPolicy
2023-09-25T18:43:23.5699320Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: Unrestricted
2023-09-25T18:43:23.5699899Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: -Command
2023-09-25T18:43:23.5700517Z ##[debug]C:\Program Files\PowerShell\7\pwsh.exe arg: . 'C:\Data\Agent\_work\_temp\azureclitaskscript1695667403533.ps1'
2023-09-25T18:43:23.5702104Z ##[debug]cwd=C:\Data\Agent\_work\563\s
2023-09-25T18:43:23.5704838Z ##[debug]scriptLocation=inlineScript
2023-09-25T18:43:23.5707887Z ##[debug]failOnStandardError=false
2023-09-25T18:43:23.5710313Z ##[debug]testing directory 'C:\Data\Agent\_work\563\s'
2023-09-25T18:43:23.5739296Z ##[debug]which 'az'
2023-09-25T18:43:23.5921793Z ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
2023-09-25T18:43:23.5923269Z ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg: --version
2023-09-25T18:43:23.5923880Z ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg: --version
2023-09-25T18:43:23.5925875Z ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
2023-09-25T18:43:23.5926486Z ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
2023-09-25T18:43:23.5926811Z ##[debug]arguments:
2023-09-25T18:43:23.5927105Z ##[debug]arguments:
2023-09-25T18:43:23.5927400Z ##[debug]   --version
2023-09-25T18:43:23.5927683Z ##[debug]   --version
2023-09-25T18:43:23.5932077Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2023-09-25T18:43:24.9046814Z azure-cli                         2.52.0
2023-09-25T18:43:24.9047005Z 
2023-09-25T18:43:24.9047271Z core                              2.52.0
2023-09-25T18:43:24.9047593Z telemetry                          1.1.0
2023-09-25T18:43:24.9047676Z 
2023-09-25T18:43:24.9047870Z Extensions:
2023-09-25T18:43:24.9048114Z azure-devops                      0.26.0
2023-09-25T18:43:24.9048353Z databricks                       Unknown
2023-09-25T18:43:24.9048450Z 
2023-09-25T18:43:24.9048672Z Dependencies:
2023-09-25T18:43:24.9048896Z msal                            1.24.0b1
2023-09-25T18:43:24.9049135Z azure-mgmt-resource             23.1.0b2
2023-09-25T18:43:24.9049240Z 
2023-09-25T18:43:24.9049524Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2023-09-25T18:43:24.9049862Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2023-09-25T18:43:24.9050017Z 
2023-09-25T18:43:24.9050335Z Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
2023-09-25T18:43:24.9050512Z 
2023-09-25T18:43:24.9050763Z Legal docs and information: aka.ms/AzureCliLegal
2023-09-25T18:43:24.9050877Z 
2023-09-25T18:43:24.9050948Z 
2023-09-25T18:43:24.9051158Z Your CLI is up-to-date.
2023-09-25T18:43:24.9052701Z ##[debug]useGlobalConfig=false
2023-09-25T18:43:24.9053381Z ##[debug]Agent.TempDirectory=C:\Data\Agent\_work\_temp
2023-09-25T18:43:24.9053954Z ##[debug]Agent.TempDirectory=C:\Data\Agent\_work\_temp
2023-09-25T18:43:24.9090784Z Setting AZURE_CONFIG_DIR env variable to: C:\Data\Agent\_work\_temp\.azclitask
2023-09-25T18:43:24.9095720Z ##[debug]connectedServiceNameARM=e636603a-3e3b-4322-a62c-e6c580aec420
2023-09-25T18:43:24.9096491Z ##[debug]e636603a-3e3b-4322-a62c-e6c580aec420 data environment = AzureCloud
2023-09-25T18:43:24.9096953Z Setting active cloud to: AzureCloud
2023-09-25T18:43:24.9097715Z ##[debug]which 'az'
2023-09-25T18:43:24.9276162Z ##[debug]found: 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
2023-09-25T18:43:24.9276982Z ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg: cloud set -n AzureCloud
2023-09-25T18:43:24.9277754Z ##[debug]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg: cloud set -n AzureCloud
2023-09-25T18:43:24.9278502Z ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
2023-09-25T18:43:24.9279202Z ##[debug]exec tool: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
2023-09-25T18:43:24.9279851Z ##[debug]arguments:
2023-09-25T18:43:24.9280412Z ##[debug]arguments:
2023-09-25T18:43:24.9280941Z ##[debug]   cloud
2023-09-25T18:43:24.9281485Z ##[debug]   cloud
2023-09-25T18:43:24.9282036Z ##[debug]   set
2023-09-25T18:43:24.9282582Z ##[debug]   set
2023-09-25T18:43:24.9283121Z ##[debug]   -n
2023-09-25T18:43:24.9283668Z ##[debug]   -n
2023-09-25T18:43:24.9288043Z ##[debug]   AzureCloud
2023-09-25T18:43:24.9288643Z ##[debug]   AzureCloud
2023-09-25T18:43:24.9289110Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2023-09-25T18:43:28.1134730Z ERROR: The command failed with an unexpected error. Here is the traceback:
2023-09-25T18:43:28.1135295Z ERROR: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
2023-09-25T18:43:28.1135665Z Traceback (most recent call last):
2023-09-25T18:43:28.1136024Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2023-09-25T18:43:28.1136461Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
2023-09-25T18:43:28.1137372Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 479, in load_command_table
2023-09-25T18:43:28.1137964Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 336, in _update_command_table_from_extensions
2023-09-25T18:43:28.1138486Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 163, in get_metadata
2023-09-25T18:43:28.1138935Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 16, in __init__
2023-09-25T18:43:28.1139355Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/distribution.py", line 115, in extractMetadata
2023-09-25T18:43:28.1139747Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 33, in read
2023-09-25T18:43:28.1140199Z PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
2023-09-25T18:43:28.1140654Z To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
2023-09-25T18:43:28.1141825Z ##[error]Error Code: [1]
2023-09-25T18:43:28.1142742Z ##[debug]Processed: ##vso[task.issue type=error;]Error Code: [1]
2023-09-25T18:43:28.1148682Z ##[debug]task result: Failed
2023-09-25T18:43:28.1152516Z ##[error]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 479, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 336, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 163, in get_metadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 16, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/distribution.py", line 115, in extractMetadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 33, in read
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

2023-09-25T18:43:28.1156106Z ##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 479, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 336, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 163, in get_metadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 16, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/distribution.py", line 115, in extractMetadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 33, in read
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

2023-09-25T18:43:28.1161468Z ##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 517, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 479, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 336, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 163, in get_metadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 16, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/distribution.py", line 115, in extractMetadata
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\pkginfo/wheel.py", line 33, in read
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\databricks\\databricks-0.10.2.dist-info'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

2023-09-25T18:43:28.1263350Z ##[section]Finishing: Request token for deployment

### Expected behavior

Generate a token for given URI

### Environment Summary

2023-09-25T18:43:24.9046814Z azure-cli                         2.52.0
2023-09-25T18:43:24.9047005Z 
2023-09-25T18:43:24.9047271Z core                              2.52.0
2023-09-25T18:43:24.9047593Z telemetry                          1.1.0
2023-09-25T18:43:24.9047676Z 
2023-09-25T18:43:24.9047870Z Extensions:
2023-09-25T18:43:24.9048114Z azure-devops                      0.26.0
2023-09-25T18:43:24.9048353Z databricks                       Unknown
2023-09-25T18:43:24.9048450Z 
2023-09-25T18:43:24.9048672Z Dependencies:
2023-09-25T18:43:24.9048896Z msal                            1.24.0b1
2023-09-25T18:43:24.9049135Z azure-mgmt-resource             23.1.0b2
2023-09-25T18:43:24.9049240Z 
2023-09-25T18:43:24.9049524Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2023-09-25T18:43:24.9049862Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2023-09-25T18:43:24.9050017Z 
2023-09-25T18:43:24.9050335Z Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
2023-09-25T18:43:24.9050512Z 
2023-09-25T18:43:24.9050763Z Legal docs and information: aka.ms/AzureCliLegal
2023-09-25T18:43:24.9050877Z 
2023-09-25T18:43:24.9050948Z 
2023-09-25T18:43:24.9051158Z Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
