### ISSUE TITLE
az webapp deployment slot create is failing when setting --configuration-source to the production slot

### ISSUE THREAD

**Issue by jsclifford** [Azure/azure-cli#27474]
### Describe the bug

I cannot create an azure web app slot while using the `--configure-source` paramater.  When running `az webapp deployment slot create --name mywindows-app-service --slot my-slot --resource-group my-resource-group --subscription 1234 --configuration-source mywindows-app-service`  It give an error about a conflict and won't create the slot.

### Related command

`az webapp deployment slot create --name mywindows-app-service --slot my-slot --resource-group my-resource-group --subscription 1234 --configuration-source mywindows-app-service`

### Errors

The command failed due to SiteConfig.PublicNetworkAccess conflicts with Site.PublicNetworkAccess
The azure cli error
```
cli.azure.cli.core.azclierror: There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.
az_command_data_logger: There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000028D61B448B0>]
```

### Issue script & Debug output

```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/###SubcriptionID###/resourceGroups/###ResourceGroup###/providers/Microsoft.Web/sites/###AppServiceName###/slots/###SlotName###/config/web?api-version=2022-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '3290'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '4ad39161-5cae-11ee-90a5-a059501a93ec'
cli.azure.cli.core.sdk.policies:     'CommandName': 'webapp deployment slot create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --slot --resource-group --subscription --configuration-source --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) azsdk-python-azure-mgmt-web/7.0.0 Python/3.10.10 (Windows-10-10.0.19044-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"numberOfWorkers": 1, "defaultDocuments": ["Default.htm", "Default.html", "Default.asp", "index.htm", "index.html", "iisstart.htm", "default.aspx", "index.php", "hostingstart.html"], "netFrameworkVersion": "v6.0", "phpVersion": "5.6", "pythonVersion": "", "nodeVersion": "", "powerShellVersion": "", "linuxFxVersion": "", "requestTracingEnabled": true, "requestTracingExpirationTime": "9999-12-31T23:59:00.000Z", "remoteDebuggingEnabled": false, "remoteDebuggingVersion": "VS2019", "httpLoggingEnabled": false, "acrUseManagedIdentityCreds": false, "logsDirectorySizeLimit": 35, "detailedErrorLoggingEnabled": true, "publishingUsername": "$###AppServiceName###", "scmType": "None", "use32BitWorkerProcess": false, "webSocketsEnabled": false, "alwaysOn": true, "appCommandLine": "", "managedPipelineMode": "Integrated", "virtualApplications": [{"virtualPath": "/", "physicalPath": "site\\wwwroot", "preloadEnabled": true}], "loadBalancing": "LeastRequests", "experiments": {"rampUpRules": []}, "autoHealEnabled": false, "vnetName": "##vnet##", "vnetRouteAllEnabled": true, "vnetPrivatePortsCount": 0, "localMySqlEnabled": false, "xManagedServiceIdentityId": ##identityid##, "ipSecurityRestrictions": [{"vnetSubnetResourceId": "##vnet_id##", "action": "Allow", "tag": "Default", "priority": 100, "name": "##name##"}, {"vnetSubnetResourceId": "##vnet_id##", "action": "Allow", "tag": "Default", "priority": 101, "name": "Subnet"}, {"ipAddress": "ApplicationInsightsAvailability", "action": "Allow", "tag": "ServiceTag", "priority": 102, "name": "ping availability test"}, {"ipAddress": "Any", "action": "Deny", "priority": 2147483647, "name": "Deny all", "description": "Deny all access"}], "scmIpSecurityRestrictions": [{"vnetSubnetResourceId": "##vnet_id##", "action": "Allow", "tag": "Default", "priority": 100, "name": "##name##"}, {"vnetSubnetResourceId": "##vnet_id##", "action": "Allow", "tag": "Default", "priority": 101, "name": "##name##"}, {"ipAddress": "Any", "action": "Deny", "priority": 2147483647, "name": "Deny all", "description": "Deny all access"}], "scmIpSecurityRestrictionsUseMain": false, "http20Enabled": 
true, "minTlsVersion": "1.2", "scmMinTlsVersion": "1.2", "ftpsState": "Disabled", "preWarmedInstanceCount": 0, "healthCheckPath": "/health", "functionsRuntimeScaleMonitoringEnabled": false, "websiteTimeZone": "##TIMEZONE##", "minimumElasticInstanceCount": 0, "azureStorageAccounts": {}, "publicNetworkAccess": "Disabled"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/###SubcriptionID###/resourceGroups/###ResourceGroup###/providers/Microsoft.Web/sites/###AppServiceName###/slots/###SlotName###/config/web?api-version=2022-03-01 HTTP/1.1" 409 725
cli.azure.cli.core.sdk.policies: Response status: 409
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '725'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"###"'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '###'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '###'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': '###'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: ### Ref B: ### Ref C: 2023-09-26T20:50:38Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 26 Sep 2023 20:50:40 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"Conflict","Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.","Target":null,"Details":[{"Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"01020","MessageTemplate":"There was a conflict. {0}","Parameters":["SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."],"Code":"Conflict","Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."}}],"Innererror":null}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1915, in create_webapp_slot
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1987, in update_slot_configuration_from_source
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_appservice_utils.py", line 24, in _generic_site_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2022_03_01/operations/_web_apps_operations.py", line 34330, in update_configuration_slot
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 107, in map_error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'Conflict'
Content: {"Code":"Conflict","Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.","Target":null,"Details":[{"Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"01020","MessageTemplate":"There was a conflict. {0}","Parameters":["SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."],"Code":"Conflict","Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property."}}],"Innererror":null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
knack.util.CLIError: There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.

cli.azure.cli.core.azclierror: There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.
az_command_data_logger: There was a conflict. SiteConfig.PublicNetworkAccess cannot be modified. Please modify the Site.PublicNetworkAccess property.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000028D61B448B0>]
```

### Expected behavior

I expected the web app slot to be created with the same configuration of the production/default slot.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\##username##\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I just created the windows web app today.  
This isn't a problem on windows web apps that were created months ago.  Just newly created web app.

**Comment by btardif** [comment]
@seligj95 this is slot creation and not code deployment

**Comment by JoyDistelbrink** [comment]
Hi we are having the same issue. We can't create App Service Slots anymore from Azure DevOps Pipelines using az cli.

**Comment by kennethjeppesen** [comment]
Similar issue here. Can't update Function App Slots using Terraform resource azurerm_windows_function_app_slot. Same error message.

**Comment by LukeDearden** [comment]
We're having similar problems with SCM/Kudu failing to start/deploy when creating staging slots. We first noticed it when pushing a zip to kudu on the staging slot from PowerShell which manifested itself as an unknown host. We then added a check to make sure SCM was ready before pushing thinking it was just taking time to warm up. 

We're still seeing occasions where SCM is not ready in the staging slot even after 5 minutes of polling.

**Comment by seligj95** [comment]
No longer seeing this issue, unable to repro. Please upgrade to the latest CLI version and try again. Closing this out as this issue is a couple years old and we've made other backend changes to the publicNetworkAccess property that probably addressed the underlying issue here. Please let us know if you are still facing this issue and we can re-open and further investigate.
