### ISSUE TITLE
Manjaro: Encountering an issue during the installation process

### ISSUE THREAD

**Issue by Qodestackr** [Azure/azure-cli#27529]
### Describe the bug

CLI installation issue.

### Related command

```bash
curl -L https://aka.ms/InstallAzureCli | bash
```

### Errors

```bash
[qodestackr@qodestackr-pc ~]$ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100  1405  100  1405    0     0     76      0  0:00:18  0:00:18 --:--:--   345
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_1Jsqdz.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_1Jsqdz: OK
Running install script.
-- Verifying Python version.
-- Python version 3.11.5 okay.
-- Verifying native dependencies.
-- Unable to verify native dependencies. dist=manjaro linux, version=None. Continuing...

===> In what directory would you like to place the install? (leave blank to use '/home/qodestackr/lib/azure-cli'): 
-- '/home/qodestackr/lib/azure-cli' is not empty and may contain a previous installation.

===> Remove this directory? (y/N): y
-- Deleted '/home/qodestackr/lib/azure-cli'.
-- Creating directory '/home/qodestackr/lib/azure-cli'.
-- We will install at '/home/qodestackr/lib/azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use '/home/qodestackr/bin'): 
-- The executable will be in '/home/qodestackr/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-16.7.11.tar.gz.
-- Downloaded virtualenv package to /tmp/tmppj32e945/virtualenv-16.7.11.tar.gz.
-- Checksum of /tmp/tmppj32e945/virtualenv-16.7.11.tar.gz OK.
-- Extracting '/tmp/tmppj32e945/virtualenv-16.7.11.tar.gz' to '/tmp/tmppj32e945'.
-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/qodestackr/lib/azure-cli']
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/qodestackr/lib/azure-cli/bin/python3
Also creating executable in /home/qodestackr/lib/azure-cli/bin/python
ERROR: The executable /home/qodestackr/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/qodestackr/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 415, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 399, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 144, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 105, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/qodestackr/lib/azure-cli']' returned non-zero exit status 100.

```

### Issue script & Debug output

```bash
[qodestackr@qodestackr-pc ~]$ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100  1405  100  1405    0     0     76      0  0:00:18  0:00:18 --:--:--   345
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_1Jsqdz.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_1Jsqdz: OK
Running install script.
-- Verifying Python version.
-- Python version 3.11.5 okay.
-- Verifying native dependencies.
-- Unable to verify native dependencies. dist=manjaro linux, version=None. Continuing...

===> In what directory would you like to place the install? (leave blank to use '/home/qodestackr/lib/azure-cli'): 
-- '/home/qodestackr/lib/azure-cli' is not empty and may contain a previous installation.

===> Remove this directory? (y/N): y
-- Deleted '/home/qodestackr/lib/azure-cli'.
-- Creating directory '/home/qodestackr/lib/azure-cli'.
-- We will install at '/home/qodestackr/lib/azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use '/home/qodestackr/bin'): 
-- The executable will be in '/home/qodestackr/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-16.7.11.tar.gz.
-- Downloaded virtualenv package to /tmp/tmppj32e945/virtualenv-16.7.11.tar.gz.
-- Checksum of /tmp/tmppj32e945/virtualenv-16.7.11.tar.gz OK.
-- Extracting '/tmp/tmppj32e945/virtualenv-16.7.11.tar.gz' to '/tmp/tmppj32e945'.
-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/qodestackr/lib/azure-cli']
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/qodestackr/lib/azure-cli/bin/python3
Also creating executable in /home/qodestackr/lib/azure-cli/bin/python
ERROR: The executable /home/qodestackr/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/qodestackr/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 415, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 399, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 144, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/azure_cli_install_tmp_1Jsqdz", line 105, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/qodestackr/lib/azure-cli']' returned non-zero exit status 100.

```

### Expected behavior

It should complete installation

### Environment Summary

python version: ```Python 3.11.5```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Qodestackr** [comment]
```pip install azure-cli``` works

Kindly update Azure docs accordingly.

**Comment by makeitcloudy** [comment]
the way described in  #20476 works in manjaro 6.1.60-1
