### ISSUE TITLE
az storage azcopy blob download ends with [Errno 8] Exec format error

### ISSUE THREAD

**Issue by sethtregenna** [Azure/azure-cli#27624]
### Describe the bug

The following command errors out on Raspberry Pi OS but works fine on Ubuntu x64;

`az storage azcopy blob download --container <CONTAINER_NAME> --destination "FILENAME.EXT" --account-name <ACCOUNT_NAME> --source "SOURCE>EXT" --account-key "ACOUNT_KEY"
`

### Related command

az storage azcopy blob download --container <CONTAINER_NAME> --destination "FILENAME.EXT" --account-name <ACCOUNT_NAME> --source "SOURCE>EXT" --account-key "ACOUNT_KEY"

### Errors

The command failed with an unexpected error. Here is the traceback:
[Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'
Traceback (most recent call last):
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 288, in new_handler
    handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 223, in handler
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 25, in storage_blob_download
    storage_blob_copy(azcopy, _add_url_sas(source, azcopy.creds.sas_token), destination, recursive=recursive)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
    azcopy.copy(source, destination, flags=flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
    subprocess.call(command, env=dict(os.environ, **env_kwargs))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['storage', 'azcopy', 'blob', 'download', '--container', 'container_name', '--destination', 'image.img.xz', '--account-name', 'myaccount', '--source', 'image.img.xz', '--account-key', 'OBFUSCATED', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa0ee7790>, <function OutputProducer.on_global_arguments at 0x7fa0df6280>, <function CLIQuery.on_global_arguments at 0x7fa0d79820>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage', 'azext_storage_preview']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.175        58       272
cli.azure.cli.core: Total (1)                 0.175        58       272
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: storage-preview           0.404        16        52  /home/admin/.azure/cliextensions/storage-preview
cli.azure.cli.core: Total (1)                 0.404        16        52  
cli.azure.cli.core: Loaded 65 groups, 295 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage azcopy blob download
cli.azure.cli.core: Command table: storage azcopy blob download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa0067a60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/admin/.azure/commands/2023-10-18.09-50-41.storage_azcopy_blob_download.998.log'.
az_command_data_logger: command args: storage azcopy blob download --container {} --destination {} --account-name {} --source {} --account-key {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa00955e0>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azext_storage_preview.vendored_sdks.azure_mgmt_storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa003a820>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa0055670>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa0df6310>, <function CLIQuery.handle_query_parameter at 0x7fa0d798b0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa00555e0>]
az_command_data_logger: extension name: storage-preview
az_command_data_logger: extension version: 1.0.0b1
Command group 'az storage' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azext_storage_preview._client_factory: Getting data service client service_type=BlockBlobService
Namespace(_log_verbosity_verbose=False, _log_verbosity_debug=True, _log_verbosity_only_show_errors=False, _output_format='json', _command_package='storage', _subcommand='download', account_name='myaccount', account_key='OBFUSCATED', connection_string=None, sas_token=None, _subscription=None, cmd=<azure.cli.core.commands.AzCliCommand object at 0x7f9ebdfd30>, source='https://myaccount.blob.core.windows.net/images/image.img.xz', destination='image.img.xz', recursive=None, func=<azure.cli.core.commands.AzCliCommand object at 0x7f9f619130>, command='storage azcopy blob download', _cmd=<azure.cli.core.commands.AzCliCommand object at 0x7f9ebdfd30>, _command_validator=None, _argument_validators=[<function validate_client_parameters at 0x7f9f615550>, <function validate_azcopy_download_source_url at 0x7f9f6158b0>], _parser=AzCliCommandParser(prog='az storage azcopy blob download', usage=None, description='', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))
cli.azext_storage_preview._client_factory: Getting data service client service_type=BlockBlobService
cli.azext_storage_preview.azcopy.util: Azcopy command: ['/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy', 'copy', 'https://my_account.blob.core.windows.net/mycontainer/image.img.xz?se=2023-10-19T08%3A50%3A42Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=gSRjtCoAqssfWcL3Zb/YRqG6B5JrrmRprS%2Brq3qdqcQ%3D', 'image.img.xz']
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 288, in new_handler
    handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 223, in handler
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 25, in storage_blob_download
    storage_blob_copy(azcopy, _add_url_sas(source, azcopy.creds.sas_token), destination, recursive=recursive)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
    azcopy.copy(source, destination, flags=flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
    subprocess.call(command, env=dict(os.environ, **env_kwargs))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'
Traceback (most recent call last):
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 288, in new_handler
    handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 223, in handler
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 25, in storage_blob_download
    storage_blob_copy(azcopy, _add_url_sas(source, azcopy.creds.sas_token), destination, recursive=recursive)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
    azcopy.copy(source, destination, flags=flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
    subprocess.call(command, env=dict(os.environ, **env_kwargs))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'
az_command_data_logger: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'
Traceback (most recent call last):
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 288, in new_handler
    handler(ex)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 223, in handler
    raise ex
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 25, in storage_blob_download
    storage_blob_copy(azcopy, _add_url_sas(source, azcopy.creds.sas_token), destination, recursive=recursive)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/operations/azcopy.py", line 15, in storage_blob_copy
    azcopy.copy(source, destination, flags=flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 47, in copy
    self.run_command(['copy', source, destination] + flags)
  File "/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/util.py", line 43, in run_command
    subprocess.call(command, env=dict(os.environ, **env_kwargs))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/admin/.azure/cliextensions/storage-preview/azext_storage_preview/azcopy/azcopy_linux_amd64_10.5.0/azcopy'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa0067ca0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.793 seconds (init: 0.550, invoke: 1.243)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7135 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/home/admin/lib/azure-cli/bin/python /home/admin/lib/azure-cli/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/admin/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The file is downloaded. The same command works fine on an Ubuntu 22.04.3 x64 server.

### Environment Summary

az version
{
  "azure-cli": "2.53.0",
  "azure-cli-core": "2.53.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "storage-preview": "1.0.0b1"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @sethtregenna ,
Can you try `az storage blob download`, the 
`az storage azcopy blob download` command has not been updated in a while which might prevent it from working properly in some environments. 
`az storage blob download -c <container_name> -n <blob_name> --account-name <account_name> -f <destination_filename>`
