### ISSUE TITLE
 az sf cluster node-type add does not add new node type because of invalid subnet

### ISSUE THREAD

**Issue by schamal2205** [Azure/azure-cli#27646]
### Describe the bug

azure cli node type add throws this error when trying to add a new node type to an existing cluster: 
```
(NetcfgInvalidSubnet) Subnet 'subnet_1' is not valid in virtual network 'res-{networkname}-vnet'.
Code: NetcfgInvalidSubnet
Message: Subnet 'subnet_1' is not valid in virtual network 'res-{networkname}-vnet'.
```

### Related command

```
az sf cluster node-type add --resource-group {resgroup} --cluster-name {sfclustername} --node-type {nodetypename} --capacity 2 --vm-sku "B2s" --vm-user-name {vmuser} --vm-password {vmpassword}
```

### Errors

(NetcfgInvalidSubnet) Subnet 'subnet_1' is not valid in virtual network 'res-{networkname}-vnet'.
Code: NetcfgInvalidSubnet
Message: Subnet 'subnet_1' is not valid in virtual network 'res-{networkname}-vnet'.

### Issue script & Debug output

```
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '68'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2f23eb8a-6f10-11ee-980c-e0d464814399'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sf cluster node-type add'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --cluster-name --node-type --capacity --vm-sku --vm-user-name --vm-password --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"name": "subnet_1", "properties": {"addressPrefix": "10.0.1.0/24"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/.../providers/Microsoft.Network/virtualNetworks/.../subnets/subnet_1?api-version=2022-01-01 HTTP/1.1" 400 178
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '178'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 20 Oct 2023 06:29:25 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "NetcfgInvalidSubnet",
    "message": "Subnet 'subnet_1' is not valid in virtual network '...'.",
    "details": []
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicefabric/custom.py", line 706, in add_cluster_node_type
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicefabric/custom.py", line 767, in _create_vmss
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1013, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicefabric/aaz/latest/network/vnet/subnet/_create.py", line 287, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/servicefabric/aaz/latest/network/vnet/subnet/_create.py", line 327, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (NetcfgInvalidSubnet) Subnet 'subnet_1' is not valid in virtual network '...'.
Code: NetcfgInvalidSubnet
Message: Subnet 'subnet_1' is not valid in virtual network '...'.

cli.azure.cli.core.azclierror: (NetcfgInvalidSubnet) Subnet 'subnet_1' is not valid in virtual network '...'.
Code: NetcfgInvalidSubnet
Message: Subnet 'subnet_1' is not valid in virtual network '...'.
az_command_data_logger: (NetcfgInvalidSubnet) Subnet 'subnet_1' is not valid in virtual network '...'.
Code: NetcfgInvalidSubnet
Message: Subnet 'subnet_1' is not valid in virtual network '...'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002271F2605E0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 789.019 seconds (init: 0.366, invoke: 788.653)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3746 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\...\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

a new scale set is created and added to the cluster as new node type 

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by mwesigwaguma** [comment]
Failing deployment seems to be realted to VirtualNetworks. Can't find logs in Arm for this resource.
![image](https://github.com/user-attachments/assets/da319680-a3b2-4af0-ba00-21d71382651e)
Closing for now, if still a problem create issue on virtualNetwork team
