### ISSUE TITLE
_prepare_deployment_properties_unmodified fails "Unable to get API version for type 'None' in profile 'latest'"

### ISSUE THREAD

**Issue by RBDDcet** [Azure/azure-cli#27677]
### Describe the bug

This is part of a custom extension that was working as of Aug 2023

template_file = None
template_uri = 'https://github.com/rbddcet/az-bake/releases/download/v0.3.17/sandbox.json'
parameters =  [['location=eastus', 'keyVaultName=AzzBakeTestSandbox-kv', 'storageName=azzbaketestsandboxstore', 'vnetName=AzzBakeTestSandbox-vnet', 'identityName=AzzBakeTestSandbox-id', 'vnetAddressPrefixes=["10.0.0.0/24"]', 'defaultSubnetName=default', 'defaultSubnetAddressPrefix=10.0.0.0/25', 'builderSubnetName=builders', 'builderSubnetAddressPrefix=10.0.0.128/25', 'tags={"hidden-bake:sandbox-version": "v0.3.17", "hidden-bake:cli-version": "v0.3.17"}', 'ciPrincipalId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx']]

from azure.cli.command_modules.resource.custom import JsonCTemplatePolicy, _prepare_deployment_properties_unmodified

 properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
                                                           template_uri=template_uri, parameters=parameters,
                                                           mode='Incremental') 

### Related command

az deployment group

### Errors

DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 501, in get_api_version
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\DDCETRepo\az-bake\bake\azext_bake\custom.py", line 109, in bake_sandbox_create
    _, _ = deploy_arm_template_at_resource_group(cmd, sandbox_resource_group_name,
  File "C:\DDCETRepo\az-bake\bake\azext_bake\_arm.py", line 46, in deploy_arm_template_at_resource_group
    properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 986, in _prepare_deployment_properties_unmodified
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 356, in get_models
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 770, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/__init__.py", line 91, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 690, in get_versioned_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 676, in get_versioned_sdk_path
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 508, in get_api_version
azure.cli.core.profiles._shared.APIVersionException: Unable to get API version for type 'None' in profile 'latest'

### Issue script & Debug output

DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 501, in get_api_version
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\DDCETRepo\az-bake\bake\azext_bake\custom.py", line 109, in bake_sandbox_create
    _, _ = deploy_arm_template_at_resource_group(cmd, sandbox_resource_group_name,
  File "C:\DDCETRepo\az-bake\bake\azext_bake\_arm.py", line 46, in deploy_arm_template_at_resource_group
    properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 986, in _prepare_deployment_properties_unmodified
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 356, in get_models
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 770, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/__init__.py", line 91, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 690, in get_versioned_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 676, in get_versioned_sdk_path
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 508, in get_api_version
azure.cli.core.profiles._shared.APIVersionException: Unable to get API version for type 'None' in profile 'latest'

ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: Unable to get API version for type 'None' in profile 'latest'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 501, in get_api_version
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\DDCETRepo\az-bake\bake\azext_bake\custom.py", line 109, in bake_sandbox_create
    _, _ = deploy_arm_template_at_resource_group(cmd, sandbox_resource_group_name,
  File "C:\DDCETRepo\az-bake\bake\azext_bake\_arm.py", line 46, in deploy_arm_template_at_resource_group
    properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 986, in _prepare_deployment_properties_unmodified
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 356, in get_models
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 770, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/__init__.py", line 91, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 690, in get_versioned_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 676, in get_versioned_sdk_path
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 508, in get_api_version
azure.cli.core.profiles._shared.APIVersionException: Unable to get API version for type 'None' in profile 'latest'
ERROR: az_command_data_logger: Unable to get API version for type 'None' in profile 'latest'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 501, in get_api_version
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\DDCETRepo\az-bake\bake\azext_bake\custom.py", line 109, in bake_sandbox_create
    _, _ = deploy_arm_template_at_resource_group(cmd, sandbox_resource_group_name,
  File "C:\DDCETRepo\az-bake\bake\azext_bake\_arm.py", line 46, in deploy_arm_template_at_resource_group
    properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 986, in _prepare_deployment_properties_unmodified
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 356, in get_models
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 770, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/__init__.py", line 91, in get_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 690, in get_versioned_sdk
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 676, in get_versioned_sdk_path
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 508, in get_api_version
azure.cli.core.profiles._shared.APIVersionException: Unable to get API version for type 'None' in profile 'latest'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040ED5C8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 7.134 seconds (init: 0.639, invoke: 6.495)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 7183 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\rbest\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Return the necessary properties to deploy the template.

### Environment Summary

azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
devcenter                          0.1.2
init                               0.1.0
bake                              0.3.17 (dev) C:\DDCETRepo\az-bake\bake

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\DDCETRepo\az-bake\.venv\Scripts\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'
Development extension sources:
    C:\DDCETRepo\az-bake

Python (Windows) 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
