### ISSUE TITLE
az partnercenter marketplace offer list gives a 404 error

### ISSUE THREAD

**Issue by eitan-lb** [Azure/azure-cli#27679]
### Describe the bug

I run the following commands:
`> az login`
`> az partnercenter marketplace offer list`

Expecting a list of my offers in the partnercenter but I get a 404 error

### Related command

az partnercenter marketplace offer list

### Errors

Command group 'partnercenter marketplace offer' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054039Z-6qq4ykrcyt2h91uxt3u53w781000000000tg00000000urzx', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': 'a6c2bf86-076e-4f9d-9c81-25eb17f581e6', 'Date': 'Wed, 25 Oct 2023 05:40:39 GMT'})
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/operations/marketplace_offer/custom.py", line 26, in list_offer
    return client.list()
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in list
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/_util.py", line 46, in get_combined_paged_results
    response = method_with_paged_response(token)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in <lambda>
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api/product_client.py", line 495, in products_get
    return self.products_get_endpoint.call_with_http_info(**kwargs)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 205, in __call_api
    raise e
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 198, in __call_api
    response_data = self.request(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 447, in request
    return self.rest_client.GET(url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 235, in GET
    return self.request("GET", url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 224, in request
    raise NotFoundException(http_resp=r)
azext_partnercenter.vendored_sdks.v1.partnercenter.exceptions.NotFoundException: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054039Z-6qq4ykrcyt2h91uxt3u53w781000000000tg00000000urzx', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': 'a6c2bf86-076e-4f9d-9c81-25eb17f581e6', 'Date': 'Wed, 25 Oct 2023 05:40:39 GMT'})

### Issue script & Debug output

cli.knack.cli: Command arguments: ['partnercenter', 'marketplace', 'offer', 'list', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5e62809360>, <function OutputProducer.on_global_arguments at 0x7f5e62770280>, <function CLIQuery.on_global_arguments at 0x7f5e6258d480>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'partnercenter': ['azext_partnercenter']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: partnercenter             0.105        14        32  /home/****/.azure/cliextensions/partnercenter
cli.azure.cli.core: Total (1)                 0.105        14        32  
cli.azure.cli.core: Loaded 14 groups, 32 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : partnercenter marketplace offer list
cli.azure.cli.core: Command table: partnercenter marketplace offer list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f5e61962f80>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/****/.azure/commands/2023-10-25.08-46-37.partnercenter_marketplace_offer_list.51864.log'.
az_command_data_logger: command args: partnercenter marketplace offer list --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f5e6197fc70>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f5e619c9990>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f5e619c9ab0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f5e62770310>, <function CLIQuery.handle_query_parameter at 0x7f5e6258d510>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f5e619c9a20>]
az_command_data_logger: extension name: partnercenter
az_command_data_logger: extension version: 0.2.4
Command group 'partnercenter marketplace offer' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/****/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/****/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://api.partner.microsoft.com/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 32d6cdfc-5aff-4e15-bb4a-4fbb33fb94ef
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/1643a740-3389-4dba-9197-a4e27b0c9d2f/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://graph.microsoft.com/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: affef13b-bfbf-44dd-ab3d-912007c32686
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFDOUNENjczMzkwXCIsXCJtYXhcIjpcIkZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"AzureApplication","name":"****","externalIDs":[{"type":"AzureOfferId","value":"****"}],"isModularPublishing":true,"id":"2926ae66-ad3c-45ad-a49e-8f61629edf9f"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFEMzk5Q0Q2NzJDXCIsXCJtYXhcIjpcIjA1QzFEOUNENjczMzkwXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"AzureThirdPartyVirtualMachine","name":"****-VM","externalIDs":[{"type":"AzureOfferId","value":"****-vm"}],"isModularPublishing":true,"id":"a7474327-5593-411d-9f9e-45e97c129090"},{"resourceType":"AzureApplication","name":"****","externalIDs":[{"type":"AzureOfferId","value":"****"}],"isModularPublishing":true,"id":"7d566786-8bd2-41cf-9122-04b21b2f3f6d"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFERkZGRkZGRkY0XCIsXCJtYXhcIjpcIjA1QzFFMzk5Q0Q2NzJDXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"AzureApplication","name":"training-offer","externalIDs":[{"type":"AzureOfferId","value":"temp-offer"}],"isModularPublishing":true,"id":"63bbbe9f-1e09-431d-a6db-8a464770be67"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFFMzk5Q0Q2NzJDXCIsXCJtYXhcIjpcIkZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"SoftwareAsAService","name":"SaaS ****","externalIDs":[{"type":"AzureOfferId","value":"saas-****"}],"isModularPublishing":true,"id":"ed3966f1-fdb2-4e97-ad61-549c252fd64f"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFFNzMzOTlDRDVFXCIsXCJtYXhcIjpcIjA1QzFFOUNENjczMzkwXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"AzureThirdPartyVirtualMachine","name":"****","externalIDs":[{"type":"AzureOfferId","value":"vm123"}],"isModularPublishing":true,"id":"f6dc783a-6597-4147-893b-3f53d327adb9"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b'{"nextLink":"v1.0/ingestion/products?$skipToken=eyJMYXN0SWQiOiJbe1widG9rZW5cIjpudWxsLFwicmFuZ2VcIjp7XCJtaW5cIjpcIjA1QzFFRDY3MzM5OUMyXCIsXCJtYXhcIjpcIkZGXCJ9fV0iLCJTb3VyY2UiOiJEb2NEQiJ9","value":[{"resourceType":"SoftwareAsAService","name":"****-test-hk","externalIDs":[{"type":"AzureOfferId","value":"****-test-hk"}],"isModularPublishing":true,"id":"c5076f1a-98d6-4815-9168-efd628d6e0ce"}]}'
azext_partnercenter.vendored_sdks.v1.partnercenter.rest: response body: b''
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/operations/marketplace_offer/custom.py", line 26, in list_offer
    return client.list()
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in list
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/_util.py", line 46, in get_combined_paged_results
    response = method_with_paged_response(token)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in <lambda>
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api/product_client.py", line 495, in products_get
    return self.products_get_endpoint.call_with_http_info(**kwargs)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 205, in __call_api
    raise e
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 198, in __call_api
    response_data = self.request(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 447, in request
    return self.rest_client.GET(url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 235, in GET
    return self.request("GET", url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 224, in request
    raise NotFoundException(http_resp=r)
azext_partnercenter.vendored_sdks.v1.partnercenter.exceptions.NotFoundException: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054641Z-4x3w4k14kh2rt1d7rnn0xk271g00000002tg0000000263zw', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': '5b9defa2-9e21-4007-b04c-f6a6c95883d4', 'Date': 'Wed, 25 Oct 2023 05:46:40 GMT'})

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054641Z-4x3w4k14kh2rt1d7rnn0xk271g00000002tg0000000263zw', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': '5b9defa2-9e21-4007-b04c-f6a6c95883d4', 'Date': 'Wed, 25 Oct 2023 05:46:40 GMT'})
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/operations/marketplace_offer/custom.py", line 26, in list_offer
    return client.list()
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in list
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/_util.py", line 46, in get_combined_paged_results
    response = method_with_paged_response(token)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in <lambda>
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api/product_client.py", line 495, in products_get
    return self.products_get_endpoint.call_with_http_info(**kwargs)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 205, in __call_api
    raise e
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 198, in __call_api
    response_data = self.request(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 447, in request
    return self.rest_client.GET(url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 235, in GET
    return self.request("GET", url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 224, in request
    raise NotFoundException(http_resp=r)
azext_partnercenter.vendored_sdks.v1.partnercenter.exceptions.NotFoundException: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054641Z-4x3w4k14kh2rt1d7rnn0xk271g00000002tg0000000263zw', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': '5b9defa2-9e21-4007-b04c-f6a6c95883d4', 'Date': 'Wed, 25 Oct 2023 05:46:40 GMT'})

az_command_data_logger: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054641Z-4x3w4k14kh2rt1d7rnn0xk271g00000002tg0000000263zw', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': '5b9defa2-9e21-4007-b04c-f6a6c95883d4', 'Date': 'Wed, 25 Oct 2023 05:46:40 GMT'})
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/operations/marketplace_offer/custom.py", line 26, in list_offer
    return client.list()
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in list
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/_util.py", line 46, in get_combined_paged_results
    response = method_with_paged_response(token)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/clients/offer_client.py", line 33, in <lambda>
    results = get_combined_paged_results(lambda skip_token: self._sdk.product_client.products_get(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api/product_client.py", line 495, in products_get
    return self.products_get_endpoint.call_with_http_info(**kwargs)
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 879, in call_with_http_info
    return self.api_client.call_api(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 205, in __call_api
    raise e
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 198, in __call_api
    response_data = self.request(
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/api_client.py", line 447, in request
    return self.rest_client.GET(url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 235, in GET
    return self.request("GET", url,
  File "/home/****/.azure/cliextensions/partnercenter/azext_partnercenter/vendored_sdks/v1/partnercenter/rest.py", line 224, in request
    raise NotFoundException(http_resp=r)
azext_partnercenter.vendored_sdks.v1.partnercenter.exceptions.NotFoundException: Status Code: 404
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-azure-ref': '20231025T054641Z-4x3w4k14kh2rt1d7rnn0xk271g00000002tg0000000263zw', 'X-Cache': 'CONFIG_NOCACHE', 'Request-ID': '5b9defa2-9e21-4007-b04c-f6a6c95883d4', 'Date': 'Wed, 25 Oct 2023 05:46:40 GMT'})

### Expected behavior

Get a list of the offers I have in partner center

### Environment Summary

{
  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "alertsmanagement": "0.2.3",
    "partnercenter": "0.2.4"
  }
}

### Additional context

az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "alertsmanagement",
    "path": "/home/****/.azure/cliextensions/alertsmanagement",
    "preview": true,
    "version": "0.2.3"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "partnercenter",
    "path": "/home/****/.azure/cliextensions/partnercenter",
    "preview": true,
    "version": "0.2.4"
  }
]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@bobjac, please help take a look.
