### ISSUE TITLE
The command failed with an unexpected error. Here is the traceback: 'metadata'

### ISSUE THREAD

**Issue by avneeshkumar** [Azure/azure-cli#27696]
### Describe the bug

I am getting following error when updating the container app with new Image in ACR. 

### Related command

`az containerapp update -n ca-extrnlfrm-evnt-wrkr-debug -g $RESOURCE_GROUP --image $ACR_SERVER/externalform-events-worker-debug:bf41ee93067eb9b8b8ed2876f4fc21eb565fc3f5`

### Errors

```
The command failed with an unexpected error. Here is the traceback:
'metadata'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/avneeshkumar/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 705, in _run_job
    result = transform_op(result)
  File "/Users/avneeshkumar/.azure/cliextensions/containerapp/azext_containerapp/_transformers.py", line 32, in transform_sensitive_values
    val["metadata"] = dict((k, "") for k, v in val["metadata"].items())
KeyError: 'metadata'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

```
avneeshkumar@Avneeshs-MacBook-Pro mm-integrations-sync % az --version
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
containerapp                      0.3.42

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/bin/python'
Extensions directory '/Users/avneeshkumar/.azure/cliextensions'

Python (Darwin) 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Expected behavior

It give result like 

```

  "id": "/subscriptions/***/resourceGroups/rg-mm-apps-uat/providers/Microsoft.App/containerapps/ca-sync-shopify-uat",
  "identity": ***
    "type": "UserAssigned",
    "userAssignedIdentities": ***
      "/subscriptions/***/resourcegroups/portal-prod-apps/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AzureAppConfigAccessProd": ***
        "clientId": "8ade79f4-a7c6-4821-bfbe-7d288ffa666f",
        "principalId": "4213a4c0-5d54-428f-909f-277e9be35850"
      ***
    ***
  ***,
  "location": "West US",
  "name": "ca-sync-shopify-uat",
  "properties": ***
    "configuration": ***
      "activeRevisionsMode": "Single",
      "dapr": null,
      "ingress": null,
      "maxInactiveRevisions": null,
      "registries": [
        ***
          "identity": "",
          "passwordSecretRef": "reg-pwd",
          "server": "***",
          "username": "***"
        ***
      ],
      "secrets": [
        ***
          "name": "reg-pwd"
        ***
      ],
      "service": null
    ***,
    "customDomainVerificationId": "34BF7B5E6632FA59AEBD81F721D43C35233454DFAEDA6B9ECF34F935284DE78F",
    "environmentId": "/subscriptions/***/resourceGroups/rg-mm-apps-uat/providers/Microsoft.App/managedEnvironments/cae-mm-container-apps-uat",
    "eventStreamEndpoint": "https://westus.azurecontainerapps.dev/subscriptions/***/resourceGroups/rg-mm-apps-uat/containerApps/name-of-container-appt/eventstream",
    "latestReadyRevisionName": "ca-sync-shopify-uat--tftph12",
    "latestRevisionFqdn": "",
    "latestRevisionName": "latest-revision-name",
    "managedEnvironmentId": "/subscriptions/***/resourceGroups/rg-mm-apps-uat/providers/Microsoft.App/managedEnvironments/cae-mm-container-apps-uat",
    "outboundIpAddresses": [
      "20.245.102.6"
    ],
    "provisioningState": "Succeeded",
    "runningStatus": "Running",
    "template": ***
      "containers": [
        ***
          "env": [
            
          ],
          "image": "***/<imagename>t:3aa30908f2fd655b2a71cc03889ab9470aa86f0a",
          "name": "container-app-name",
          "resources": ***
            "cpu": 0.5,
            "ephemeralStorage": "2Gi",
            "memory": "1Gi"
          ***
        ***
      ],
      "initContainers": null,
      "revisionSuffix": "",
      "scale": ***
        "maxReplicas": 1,
        "minReplicas": 0,
        "rules": [
          ***
            "custom": ***
              "metadata": ***
                "activationValue": "",
                "credentialsFromEnv": "",
                "mode": "",
                "subscriptionName": "",
                "value": ""
              ***,
              "type": "gcp-pubsub"
            ***,
            "name": "gcp-pubsub-based-scaler"
          ***
        ]
      ***,
      "serviceBinds": null,
      "terminationGracePeriodSeconds": null,
      "volumes": null
    ***,
    "workloadProfileName": null
  ***,
  "resourceGroup": "rg-mm-apps-uat",
  "systemData": ***
    "createdAt": "2023-07-24T06:20:11.5369824",
    "createdBy": "",
    "createdByType": "User",
    "lastModifiedAt": "2023-10-26T06:35:27.6662754",
    "lastModifiedBy": "***",
    "lastModifiedByType": "Application"
  ***,
  "tags": ***
    "createdBy": "pulumi-infra",
    "environment": "uat"
  ***,
  "type": "Microsoft.App/containerApps"
***

az script ran successfully.

```

### Environment Summary

```
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
containerapp                      0.3.42

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by avneeshkumar** [comment]
> Hi @avneeshkumar Find similar issue #20037.
> 	
> Issue title 	az synapse notebook create results in error: The command failed with an unexpected error. 'metadata'
> Create time 	2021-10-26
> Comment number 	7
> 
> Possible solution: The error message you are seeing is similar to the one reported in issue #20037. The issue was caused by a KeyError in the `az synapse notebook create` command. The error occurred because the `metadata` key was not found in the `definition_file` dictionary.
> 
> The solution to this issue was to modify the `artifacts.py` file to look for the `metadata` key under the `properties` key. You can try the same solution by modifying the `transform_sensitive_values` function in the `azext_containerapp/_transformers.py` file to look for the `metadata` key under the `properties` key.
> 
> Alternatively, you can try exporting the notebook file from Synapse Studio or using the `az synapse notebook export` command, and then upload the file to the workspace. This is a recommended process to get the notebook file you want to import.
> 
> Please confirm if this resolves your issue.

This doesn't resolve my issue.

**Comment by Juliehzl** [comment]
Hi @avneeshkumar, for the issue you reported, we will fix in next version, which may be released this week.

Currently, to unblock you use cli commands, please remove container app extension and re-install with `az extension add -n containerapp  --version 0.3.41`

**Comment by Greedygre** [comment]
Hi @avneeshkumar 
This issue has been fixed and released. You can try it with `az extension add -n containerapp --upgrade`.
Thanks!

**Comment by pavel-krasnousov-LX** [comment]
Catch similar issue with version 0.3.46
