### ISSUE TITLE
az postgres flexible-server geo-restore

### ISSUE THREAD

**Issue by alsastre** [Azure/azure-cli#27819]
### Describe the bug

Geo-restore does not work for existing subnet in a different resource group (and possibly also not in the same)

### Related command

`az postgres flexible-server geo-restore -g {} -n {} --subnet {} --source-server {} --location {}`
Where:
- source-server: is the server id
- subnet: subnet id that already exists
- n: name of the new server
- g: resource-group of the new server
- location: westeurope

### Errors

```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'public_network_access'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 552, in flexible_server_georestore
    validate_georestore_network(source_server_object, None, vnet, subnet, 'postgres')
  File "/opt/homebrew/Cellar/azure-cli/2.52.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/rdbms/validators.py", line 614, in validate_georestore_network
    if source_server_object.network.public_network_access == 'Disabled' and not any((public_access, vnet, subnet)):
AttributeError: 'NoneType' object has no attribute 'public_network_access'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

Traceback starts right after a successfull call to: 
```
/providers/Microsoft.DBforPostgreSQL/locations/westeurope/checkNameAvailability?
```
with response:
```
.....,"nameAvailable":true,"message":""}
```

### Expected behavior

Postgres database gets georestored to a different resource group and subnet

### Environment Summary

```
macOS-13.6.1-arm64-arm-64bit, Darwin 22.6.0
Python 3.10.13
Installer: HOMEBREW

azure-cli 2.52.0 *

Extensions:
azure-devops 0.26.0
front-door 1.0.17
ssh 2.0.0

Dependencies:
msal 1.24.0b1
azure-mgmt-resource 23.1.0b2
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by alsastre** [comment]
Same exception with 2.53:
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'public_network_access'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py", line 559, in flexible_server_georestore
    validate_georestore_network(source_server_object, None, vnet, subnet, 'postgres')
  File "/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/rdbms/validators.py", line 619, in validate_georestore_network
    if source_server_object.network.public_network_access == 'Disabled' and not any((public_access, vnet, subnet)):
AttributeError: 'NoneType' object has no attribute 'public_network_access'
```

**Comment by alsastre** [comment]
The subnet was not delegated to `Microsoft.DBforPostgreSQL/flexibleServers`
after doing so, the cli moves forward but now fails to find the source database.

The GET request for the source database succeeds.

But the PUT request that is performed afterwards to create the new one fails with
```
{"error":{"code":"ResourceNotFound","message":"The requested resource of type 'Microsoft.DBforPostgreSQL/flexibleServers' with name 'mysourceServer' was not found."}}

```
the request had as body:
```
cli.azure.cli.core.sdk.policies: {"location": "westeurope", "properties": {"backup": {"backupRetentionDays": 7, "geoRedundantBackup": "Disabled"}, "network": {"delegatedSubnetResourceId": "mysubnetid", "privateDnsZoneArmResourceId": "myprivatednszoneid"}, "sourceServerResourceId": "mysourceserverid", "pointInTimeUTC": "2023-11-27T13:43:04.000Z", "createMode": "GeoRestore"}}
```

**Comment by alsastre** [comment]
Just had a call with Microsoft support after opening a support request. 
They were able to replicate the issue. Therefore is confirmed is a bug on the azcli and powershell that the product team must address. The problem does not occur if the same migrations is requested from the portal.


It happens only when the source and destination databases belong to different resource groups.

**Comment by kabharati** [comment]
@alsastre  - Could you please share the support ticket number so that I can look into it.

**Comment by alsastre** [comment]
Support ticket: 2311270050001293

**Comment by kabharati** [comment]
Thank you i will work with Azure CLI team to add support for this in the coming release. Until then as requested in the support case please follow the portal and Rest APT

**Comment by kabharati** [comment]
Closing this issue for now.  Please feel free to reach out if you have any questions

**Comment by alsastre** [comment]
Shouldn't it remain open till the issue is fixed?

**Comment by nachoalonsoportillo** [comment]
@alsastre please, reach out to me. I'm trying to reproduce the issue so that can work on a fix, but I'm unable to get to the error condition you're seeing.

**Comment by alsastre** [comment]
Hello @nachoalonsoportillo 
I am not sure of the differences but I just tested and obtained the same result 🥲
```sh
dstResourceGroup=DST_RESOURCE_GROUP
dstDatabase=DST_DB
subnet="/subscriptions/SUBSCRIPTION/resourceGroups/DST_RESOURCE_GROUP/providers/Microsoft.Network/virtualNetworks/DST_VNET/subnets/DST_SNET"
src_scope="/subscriptions/SUBSCRIPTION/resourceGroups/SOURCE_RESOURCE_GROUP/providers/Microsoft.DBforPostgreSQL/flexibleServers/SOURCE_DB"
MAIN_RESOURCES_LOCATION="westeurope"
privateDNS="/subscriptions/SUBSCRIPTION/resourceGroups/OTHER_RESOURCE_GROUP/providers/Microsoft.Network/privateDnsZones/MYDNSZONE.internal.postgres.database.azure.com"
az postgres flexible-server geo-restore -g "$dstResourceGroup" -n "$dstDatabase" --subnet "$subnet" --source-server "$src_scope" --location $MAIN_RESOURCES_LOCATION --private-dns-zone "$privateDNS"
```

Where the SOURCE DB is in SNET: 
`subnet="/subscriptions/SUBSCRIPTION/resourceGroups/SRC_RESOURCE_GROUP/providers/Microsoft.Network/virtualNetworks/SRC_VNET/subnets/SRC_SNET"`

I also tested by defining the dst_vnet with vnet and subnet parameters with the same result.
`az postgres flexible-server geo-restore -g "$dstResourceGroup" -n "$dstDatabase" --vnet $DST_VNET --subnet "$DST_SNET" --source-server "$src_scope" --location $MAIN_RESOURCES_LOCATION --private-dns-zone "$privateDNS" --debug`

**Comment by alsastre** [comment]
I just tested it also without the private-dns-zone parameter and the same issue appears.

**Comment by nachoalonsoportillo** [comment]
@alsastre BTW, for GeoRestore to succed, NSGs/FWs controlling network traffic on the restore server VNET must allowlist Azure Storage tag.

A note on that can be in the important note in the [Virtual network concepts](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking-private#virtual-network-concepts) section of the **Networking overview for Azure Database for PostgreSQL - Flexible Server with private access (VNET Integration)** article.

Make sure you read in that note what other traffic must be allowed so that other service features work properly.

**Comment by nachoalonsoportillo** [comment]
#please-close

**Comment by nachoalonsoportillo** [comment]
#please-close
