### ISSUE TITLE
Error uploading file using `az storage file upload` on az cli 2.54.0

### ISSUE THREAD

**Issue by AlexAugot** [Azure/azure-cli#27845]
### Describe the bug

Unable to upload a file to a azure file storage account using `az storage file upload` on the 2.54.0 release.  When running the command, we see errors in python related to `disallow_trailing_dot` cli argument.

### Related command

az storage file upload --account-name [storage account name] --share-name [file share name] --connection-string "[Storage Account Connection String]" --subscription [Azure Subscription] --source path/to/file/to/upload

### Errors

The command failed with an unexpected error. Here is the traceback:
storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
TypeError: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['storage', 'file', 'upload', '--account-name', 'XXXXXXXXXX', '--share-name', 'XXXXXX', '--connection-string', 'XXXXXXXXXXXX', '--subscription', 'XXXXXXXXXXXXX', '--source', 'XXXXXXXXXXXX', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01D6F7F8>, <function OutputProducer.on_global_arguments at 0x01E968E8>, <function CLIQuery.on_global_arguments at 0x01EB86B8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.177        59       273
cli.azure.cli.core: Total (1)                 0.177        59       273
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 59 groups, 273 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage file upload
cli.azure.cli.core: Command table: storage file upload
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0419BAC8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\aaugot\.azure\commands\2023-11-14.17-24-02.storage_file_upload.42068.log'.
az_command_data_logger: command args: storage file upload --account-name {} --share-name {} --connection-string {} --subscription {} --source {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x041AB708>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x041D8E38>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x041D8E88>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01E96938>, <function CLIQuery.handle_query_parameter at 0x01EB8708>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x041D8DE8>]
cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 651, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.multiapi.storagev2.fileshare.v2022_11_02.blob'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 651, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.multiapi.storagev2.fileshare.v2022_11_02.file'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 651, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.multiapi.storagev2.fileshare.v2022_11_02.blob'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 651, in _get_attr
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.multiapi.storagev2.fileshare.v2022_11_02.file'

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
TypeError: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
TypeError: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'
az_command_data_logger: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/__init__.py", line 430, in new_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
TypeError: storage_file_upload() got an unexpected keyword argument 'disallow_trailing_dot'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0419BC08>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.103 seconds (init: 0.368, invoke: 0.734)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7172 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\aaugot\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Expected file to be uploaded to azure file storage.

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
azure-iot                         0.21.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\aaugot\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Started to see this issue 11/14 when our CI pipelines installed the 2.54.0 release of az cli.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mdekok** [comment]
I've got the same problem in my GitHub actions. Setting the az cli back to the previous version 2.53.1 is a work around for me for now:  

```
- name: Deploy to storage using CLI
  uses: azure/CLI@v1
  with:
    azcliversion: 2.53.1
    inlineScript: |
      az storage file upload-batch ...
```

**Comment by calvinhzy** [comment]
Hi @AlexAugot @mdekok 
Can you run this, seems like when the new CLI version is installed, it somehow did not install the new SDK version. 
`pip show azure-multiapi-storage`
![image](https://github.com/Azure/azure-cli/assets/17182306/0f6ac308-d1f0-4298-ad8e-7d7a7ebbdd4b)
If the current version 1.2.0 is not there, please update all packages with `pip install -U azure-cli` and see if it fixes the issue.
![image](https://github.com/Azure/azure-cli/assets/17182306/3f3e0605-cb87-48c5-b3af-2204cc2227dc)

**Comment by chavetski** [comment]
Also seeing this when the task is run on Microsoft-Hosted Azure DevOps agents.

**Comment by gangjig** [comment]
same error here in ADO.

**Comment by andrew-bobyr** [comment]
Same error with:
az storage directory create

ENV:
az -v
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/dba/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov  8 2023, 05:21:25) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by sb-sh** [comment]
I encountered this issue in Cloud Shell on 2.54.0.

No success with pip install -U azure-cli (updated multiapi storage to 1.2) or /usr/bin/python3.9 -m pip install --upgrade pip

I was able to workaround by downgrading the Cloud Shell to 2.53.1 via pip install azure-cli==2.53.1

**Comment by calvinhzy** [comment]
There was a bug which made the `--connection-string` not work with the new `--disallow-trailing-dot` parameter. Will have it fixed by next release on 12/5. Sorry for the inconvenience. Please either use it without `--connection-string` or use the previous 2.53.1 version. Thanks.

**Comment by lennart-damen-eneco** [comment]
We have the same issue on azure pipelines, this blocks our deployments: "TypeError: storage_file_upload_batch() got an unexpected keyword argument 'disallow_trailing_dot'". Our az storage command is (in one of the steps of a job on azure pipelines):

`az storage file upload-batch --destination "$something" --destination-path "$something_else" --source ./some_folder`

- When do you expect to have a fix ready?
- What is the recommended workaround? I read "Please either use it without --connection-string or use the previous 2.53.1 version." We are not using  --connection-string (at least not explicitly), and I don't know how to specify versions of the azure cli on azure pipelines.

**Comment by doiwant** [comment]
> We have the same issue on azure pipelines, this blocks our deployments: "TypeError: storage_file_upload_batch() got an unexpected keyword argument 'disallow_trailing_dot'". Our az storage command is (in one of the steps of a job on azure pipelines):
> 
> `az storage file upload-batch --destination "$something" --destination-path "$something_else" --source ./some_folder`
> 
> * When do you expect to have a fix ready?
> * What is the recommended workaround? I read "Please either use it without --connection-string or use the previous 2.53.1 version." We are not using  --connection-string (at least not explicitly), and I don't know how to specify versions of the azure cli on azure pipelines.

Yes please help to clarify the work around.

**Comment by nicrobert** [comment]
How do I install the previous version when using the ```curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash``` method?

**Comment by calvinhzy** [comment]
> We have the same issue on azure pipelines, this blocks our deployments: "TypeError: storage_file_upload_batch() got an unexpected keyword argument 'disallow_trailing_dot'". Our az storage command is (in one of the steps of a job on azure pipelines):
> 
> `az storage file upload-batch --destination "$something" --destination-path "$something_else" --source ./some_folder`
> 
> * When do you expect to have a fix ready?
> * What is the recommended workaround? I read "Please either use it without --connection-string or use the previous 2.53.1 version." We are not using  --connection-string (at least not explicitly), and I don't know how to specify versions of the azure cli on azure pipelines.

@doiwant 
* The fix will be ready on 12/5, during our next release. 
* To use the previous version, you can try to run `pip install azure-cli==2.53.1` before running the az commands. Do you have a more detailed log/screenshot of the exact upload-batch command so I can see why it is failing? Usually if you just specify the storage account, CLI will query for the account key and use that, which would not break in 2.54.0.

**Comment by calvinhzy** [comment]
> How do I install the previous version when using the `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` method?
Hi @nicrobert 
Can you try with either `pip install azure-cli==2.53.1` or https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#install-specific-version, what linux version are you using?

**Comment by lennart-damen-eneco** [comment]
> upload-batch

We use this command in an azure pipeline. This is what the yaml roughly looks like

```
name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - main
      - release/* 
      - develop 
      - feature/*
  paths:
    exclude:
      - '*'
    include:
      - src/*
      - tests/*
      - azure-pipeline.yml

variables:
  - group: 'some_group'
   - name: SOME_VAR
      value: "something"

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: deploy
    displayName: Send file somewhere
    jobs:
      - deployment: ...
        displayName: ...
        environment: ...
        variables:
        - group: ...
        - name: DESTINATION_PATH
          value: "$(Build.Repository.Name)"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - bash: az storage file upload-batch --destination "$..." --destination-path "$..." --source ./.../...
```

**Comment by calvinhzy** [comment]
Hi @lennart-damen-eneco 
Can you send the full command here, it got cut off: 
![image](https://github.com/Azure/azure-cli/assets/17182306/a61b4721-c525-4dc8-96b6-378e098c6d87)

**Comment by calvinhzy** [comment]
Feel free to try this private package to see if it fixes the issue. 
to download: https://zhiyihuangsa.blob.core.windows.net/sharing/storage-file-upload-fix.zip
unzip and run `pip install azure_cli-2.54.0.post20231122073323-py3-none-any.whl azure_cli_core-2.54.0.post20231122073323-py3-none-any.whl azure_cli_telemetry-1.1.0.post20231122073323-py3-none-any.whl`

**Comment by lennart-damen-eneco** [comment]
@calvinhzy My command did not get cut-off, this is it. After `--source` I removed the real code, whatever is there just points to a folder in my repo.

Thanks for pointing to a package with a workaround, but to be honest I prefer not to install any private, untested package in my company's pipelines.

**Comment by calvinhzy** [comment]
Hi @lennart-damen-eneco  That is actually a good point regarding private packages, the exact same files can be found here for https://github.com/Azure/azure-cli/pull/27901/checks?check_run_id=18920622947 under the build python wheels - artifacts
![image](https://github.com/Azure/azure-cli/assets/17182306/c8c703f8-a229-414b-b232-563b8e2c303d)
![image](https://github.com/Azure/azure-cli/assets/17182306/a8431766-8d9c-4f73-9b8b-419c0a60deeb)

I have tried running without --account-name or --connection-string and it returns an error locally. I think the pipeline must be using an environment variable for either params. 
![image](https://github.com/Azure/azure-cli/assets/17182306/edcea9e3-8d09-4867-a6b0-239dada62685)
![image](https://github.com/Azure/azure-cli/assets/17182306/1a2bfe3b-baf1-4930-92e6-ec879c9854a6)

Using --account-name should work with the current 2.54.0 release. The fix for --connection-string will be out on 12/5.  Thanks.

**Comment by lennart-damen-eneco** [comment]
Okay thank you! Might indeed be an environment variable. We will try explicitly setting the `--account-name`, I'll post here again if we see that that works.
