### ISSUE TITLE
az tag create fails on a Azure SQL server with message of api version 2022-09-01

### ISSUE THREAD

**Issue by Br0k3nByD3s1gn** [Azure/azure-cli#27850]
### Describe the bug

Using az tag create fails when using on Azure Sql Server with an errormessage about API version 2022-09-01.

### Related command

az tag create -resource-id "<ID>" --tags ("<tag1>=<value1>", "...")

### Errors

(InvalidResourceType) The resource type **'locations/serverOperationResults'** could not be found in the namespace **'Microsoft.Sql'** for **api version '2022-09-01'**. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.

### Issue script & Debug output

PS> az tag create --resource-id "<snipY" --tags <snip>) --debug

cli.knack.cli: Command arguments: ['tag', 'create', '--resource-id', '<snip>', '--tags', '<snip>', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f91b7f881f0>, <function OutputProducer.on_global_arguments at 0x7f91b7ea4d30>, <function CLIQuery.on_global_arguments at 0x7f91b7e3b310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'tag': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.197        51       228
cli.azure.cli.core: Total (1)                 0.197        51       228
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.127         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.127         1         1  
cli.azure.cli.core: Loaded 52 groups, 229 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : tag create
cli.azure.cli.core: Command table: tag create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f91b72e03a0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/<snip>/.azure/commands/2023-11-15.14-45-35.tag_create.5566.log'.
az_command_data_logger: command args: tag create --resource-id {} --tags {} {} {} {} {} {} {} {} {} {} {} {} {} {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f91b7285f70>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f91b72bd040>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f91b7244e50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f91b7ea4dc0>, <function CLIQuery.handle_query_parameter at 0x7f91b7e3b3a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f91b7244dc0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 7009
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 7009
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1700060824' -> 1700060824
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<snip>/resourcegroups/<snip>/providers/Microsoft.Sql/servers/<snip>/providers/Microsoft.Resources/tags/default?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '436'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a2a062b2-83c5-11ee-a8c7-00155d65341c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'tag create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-id --tags --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (RPM) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"tags": <snip>}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<snip>/resourcegroups/<snip>/providers/Microsoft.Sql/servers/<snip>/providers/Microsoft.Resources/tags/default?api-version=2022-09-01 HTTP/1.1" 202 0
cli.azure.cli.core.sdk.policies: Response status: 202
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Location': 'https://management.azure.com//subscriptions/<snip>/tagsoperationresults?api-version=2022-09-01&$originalLocation=<snip>'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1195'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f0292199-b1e6-422a-8ff5-7db45e8529f1'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f0292199-b1e6-422a-8ff5-7db45e8529f1'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20231115T144536Z:f0292199-b1e6-422a-8ff5-7db45e8529f1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 15 Nov 2023 14:45:36 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '0'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: 
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com//subscriptions/<snip>/tagsoperationresults?api-version=2022-09-01&$originalLocation=<snip>'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a2a062b2-83c5-11ee-a8c7-00155d65341c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'tag create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-id --tags --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (RPM) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET //subscriptions/<snip>/tagsoperationresults?api-version=2022-09-01&$originalLocation=<snip> HTTP/1.1" 404 574
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11993'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '75bbd6e9-2074-420b-ab10-923c976073a1'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '75bbd6e9-2074-420b-ab10-923c976073a1'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20231115T144536Z:75bbd6e9-2074-420b-ab10-923c976073a1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 15 Nov 2023 14:45:36 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '574'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidResourceType","message":"The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 517, in run
    self._poll()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 551, in _poll
    self.update_status()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 596, in update_status
    _raise_if_bad_http_status_and_method(self._pipeline_response.http_response)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 114, in _raise_if_bad_http_status_and_method
    raise BadStatus(
azure.core.polling.base_polling.BadStatus: Invalid return status 404 for 'GET' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1013, in __call__
    raise exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 521, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (InvalidResourceType) The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.

cli.azure.cli.core.azclierror: (InvalidResourceType) The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
az_command_data_logger: (InvalidResourceType) The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type 'locations/serverOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f91b72e05e0>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 1.915 seconds (init: 0.322, invoke: 1.593)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4619 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/<snip>/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

No errormessage. 
The tags to appear on the Azure SQL server.

### Environment Summary

azure-cli                         2.54.0                                                                                       
core                              2.54.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
datafactory                        0.7.0
ml                                2.21.1
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/<snip>/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Using Azure Cloudshell.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by lukerogers** [comment]
I also get this when updating tags via the Azure.ResourceManager C# SDK, so it's broader than just the CLI.
