### ISSUE TITLE
[X509] unknown error (_ssl.c:4035) after upgrading to 2.54.0

### ISSUE THREAD

**Issue by daniel1941** [Azure/azure-cli#27912]
### Describe the bug

After upgrading to 2.54.0 the connection through proxy doesn't work anymore

### Related command

az login

### Errors

cli.azure.cli.core.azclierror: [X509] unknown error (_ssl.c:4035)
az_command_data_logger: [X509] unknown error (_ssl.c:4035)

### Issue script & Debug output

cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001E74074B560>, <function OutputProducer.on_global_arguments at 0x000001E7408D5C60>, <function CLIQuery.on_global_arguments at 0x000001E7409037E0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.006         2         8
cli.azure.cli.core: Total (1)                 0.006         2         8
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 2 groups, 8 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001E7437794E0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\danielste\.azure\commands\2023-11-24.09-34-31.login.21236.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001E7437B79C0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001E7437B7A60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001E7437B7BA0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001E7408D5D00>, <function CLIQuery.handle_query_parameter at 0x000001E740903880>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001E7437B7B00>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\danielste\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\danielste\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
msal.application: Falls back to broker._signin_interactively()
cli.azure.cli.core.auth.identity: Please select the account you want to log in with.
msal.broker: [MSAL:0001]        INFO    SetCorrelationId:220    Set correlation ID: a94ee503-bcb3-46ff-a80c-fb14256d95c2msal.broker: [MSAL:0001]        INFO    ExecuteInteractiveRequest:804   The original authority is 'https://login.microsoftonline.com/organizations'
msal.broker: [MSAL:0001]        WARNING TryNormalizeRealm:2224  No HomeAccountId provided to normalize the realm
msal.broker: [MSAL:0001]        INFO    ExecuteInteractiveRequest:815   The normalized realm is ''
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:208     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:208     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:225     Authority Realm: organizations
msal.broker: [MSAL:0002]        WARNING TryReadUniversalStorage:639     Attempted to read cache with a non-normalized realm, access token and ID token reads will fail
msal.broker: [MSAL:0002]        WARNING ReadAccountById:225     Account id is empty - account not found
msal.broker: [MSAL:0002]        INFO    SetCanonicalRealm:1048  Normalize realm to: '1ac04339-8417-4387-b32c-9a9526779033'
msal.broker: [MSAL:0002]        ERROR   ErrorInternalImpl:134   Created an error: 9zj2r, StatusInternal::Unexpected, InternalEvent::None, Error Code 2148073483, Context 'Error decrypting data of size 506'
msal.broker: [MSAL:0002]        WARNING DecryptParse:964        Failed to decrypt '(pii)', overwriting
msal.broker: [MSAL:0002]        ERROR   ErrorInternalImpl:134   Created an error: 9zj2r, StatusInternal::Unexpected, InternalEvent::None, Error Code 2148073483, Context 'Error decrypting data of size 538'
msal.broker: [MSAL:0002]        WARNING DecryptParse:964        Failed to decrypt '(pii)', overwriting
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:332    Printing Telemetry for Correlation ID: a94ee503-bcb3-46ff-a80c-fb14256d95c2
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: start_time, Value: 2023-11-24T07:34:31.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: api_name, Value: SignInInteractively
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: was_request_throttled, Value: false
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: authority_type, Value: AAD
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: access_token_expiry_time, Value: 2023-11-24T08:05:10.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: msal_version, Value: 1.1.0+local
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: client_id, Value: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: correlation_id, Value: a94ee503-bcb3-46ff-a80c-fb14256d95c2
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: stop_time, Value: 2023-11-24T07:34:37.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: msalruntime_version, Value: 0.13.12
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: original_authority, Value: https://login.microsoftonline.com/organizations
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: request_eligible_for_broker, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: broker_app_used, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: additional_query_parameters_count, Value: 2
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: read_token_last_error, Value: missing required parameter
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: auth_flow, Value: Broker
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: ui_event_count, Value: 1
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: wam_telemetry, Value: {"x_ms_clitelem":"1,0,0,50640297.4093,","ui_visible":false,"tenant_id":"1ac04339-8417-4387-b32c-9a9526779033","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","http_status":200,"http_event_count":2,"device_join":"haadj","correlation_id":"{1a27815c-6f7a-47a3-9eb7-d6fc6045d4c2}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.18362.1766","authority":"https://login.microsoftonline.com/organizations","api_error_code":0,"account_join_on_start":"primary","account_join_on_end":"primary","account_id":"81c1e8af-bbc1-47e9-b599-3136dc13a470","silent_code":0,"silent_bi_sub_code":0,"silent_message":"","silent_mats":{"x_ms_clitelem":"1,0,0,50640297.4093,","ui_visible":false,"tenant_id":"1ac04339-8417-4387-b32c-9a9526779033","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","http_status":200,"http_event_count":2,"device_join":"haadj","correlation_id":"{1a27815c-6f7a-47a3-9eb7-d6fc6045d4c2}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.18362.1766","authority":"https://login.microsoftonline.com/organizations","api_error_code":0,"account_join_on_start":"primary","account_join_on_end":"primary","account_id":"81c1e8af-bbc1-47e9-b599-3136dc13a470","silent_code":0,"silent_bi_sub_code":0,"silent_message":"","silent_mats":{"x_ms_clitelem":"1,0,0,50640297.4093,","ui_visible":false,"tenant_id":"1ac04339-8417-4387-b32c-9a9526779033","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","http_status":200,"http_event_count":2,"device_join":"haadj","correlation_id":"{1a27815c-6f7a-47a3-9eb7-d6fc6045d4c2}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.18362.1766","authority":"https://login.microsoftonline.com/organizations","api_error_code":0,"account_join_on_start":"primary","account_join_on_end":"primary","account_id":"81c1e8af-bbc1-47e9-b599-3136dc13a470"},"silent_status":0,"is_cached":0},"silent_status":0,"is_cached":1}
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: tenant_id, Value: 1ac04339-8417-4387-b32c-9a9526779033
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: normalized_realm, Value: 1ac04339-8417-4387-b32c-9a9526779033
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: write_token, Value: AT|ID
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: is_successful, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: authorization_type, Value: CompleteBrokerResult
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: request_duration, Value: 5649
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:345    Printing Execution Flow:
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:353    {"t":"646u1","tid":1,"ts":0,"l":2},{"t":"8dqim","tid":2,"ts":4,"l":2},{"t":"8dqkl","tid":1,"ts":6,"l":2,"a":9,"ie":0},{"t":"54uxe","tid":1,"ts":10,"l":2},{"t":"4wqm9","tid":3,"ts":2165,"l":2},{"t":"8dql1","tid":3,"ts":2204,"l":2},{"t":"8dqkn","tid":3,"ts":2204,"l":2,"a":5,"ie":1},{"t":"8dqko","tid":3,"ts":2204,"l":2,"a":9,"ie":1},{"t":"8dqkr","tid":3,"ts":2204,"l":2},{"t":"8b2yn","tid":2,"ts":2204,"l":2},{"t":"8dqlh","tid":2,"ts":2204,"l":2},{"t":"8dqli","tid":2,"ts":2204,"l":2},{"t":"8dqln","tid":2,"ts":2204,"l":2},{"t":"8dqih","tid":2,"ts":2204,"l":2},{"t":"7e60p","tid":2,"ts":2205,"l":2,"a":3,"ie":0},{"t":"7e60q","tid":2,"ts":2226,"l":2,"a":3,"ie":1},{"t":"7e60v","tid":2,"ts":2226,"l":2,"a":2,"ie":0},{"t":"7e60w","tid":2,"ts":2227,"l":2,"a":2,"ie":1},{"t":"7e60r","tid":2,"ts":2227,"l":2,"a":3,"ie":0},{"t":"6ou2y","tid":2,"ts":2238,"l":2,"a":3,"ie":1},{"t":"6xuag","tid":2,"ts":2238,"l":2},{"t":"4waym","tid":2,"ts":2238,"l":2}
msal.token_cache: event={
    "_account_id": "81c1e8af-bbc1-47e9-b599-3136dc13a470",
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {},
    "response": {
        "_account_id": "81c1e8af-bbc1-47e9-b599-3136dc13a470",
        "_msalruntime_telemetry": {
            "access_token_expiry_time": "2023-11-24T08:05:10.000Z",
            "additional_query_parameters_count": "2",
            "api_name": "SignInInteractively",
            "auth_flow": "Broker",
            "authority_type": "AAD",
            "authorization_type": "CompleteBrokerResult",
            "broker_app_used": "true",
            "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
            "correlation_id": "a94ee503-bcb3-46ff-a80c-fb14256d95c2",
            "is_successful": "true",
            "msal_version": "1.1.0+local",
            "msalruntime_version": "0.13.12",
            "normalized_realm": "1ac04339-8417-4387-b32c-9a9526779033",
            "original_authority": "https://login.microsoftonline.com/organizations",
            "read_token_last_error": "missing required parameter",
            "request_duration": "5649",
            "request_eligible_for_broker": "true",
            "start_time": "2023-11-24T07:34:31.000Z",
            "stop_time": "2023-11-24T07:34:37.000Z",
            "tenant_id": "1ac04339-8417-4387-b32c-9a9526779033",
            "ui_event_count": "1",
            "was_request_throttled": "false",
            "write_token": "AT|ID"
        },
        "access_token": "********",
        "client_info": "foobar",
        "expires_in": 1833,
        "id_token": "********",
        "id_token_claims": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
}
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
cli.azure.cli.core._debug: Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 8d9b946f-d408-4234-8792-ec74f28e43ec
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e809a827-8a9b-11ee-a582-d89ef3375ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.18363-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e809a827-8a9b-11ee-a582-d89ef3375ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.18363-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e809a827-8a9b-11ee-a582-d89ef3375ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.18363-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e809a827-8a9b-11ee-a582-d89ef3375ec1'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.18363-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 176, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 740, in find_using_common_tenant
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 128, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 739, in get_next
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 211, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/core/policies/_base.py", line 47, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_redirect.py", line 158, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 468, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 446, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_authentication.py", line 118, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 71, in send
  [Previous line repeated 1 more time]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 103, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 361, in send
azure.core.exceptions.ServiceRequestError: [X509] unknown error (_ssl.c:4035)

cli.azure.cli.core.azclierror: [X509] unknown error (_ssl.c:4035)
az_command_data_logger: [X509] unknown error (_ssl.c:4035)
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001E743779760>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 11.973 seconds (init: 0.655, invoke: 11.318)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4526 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\danielste\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxy'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
Connection verification disabled by environment variable AZURE_CLI_DISABLE_CONNECTION_VERIFICATION
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxy'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "1111",
    "id": "1111",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Visual Studio Professional Subscription",
    "state": "Enabled",
    "tenantId": "1111",
    "user": {
      "name": "foo@bar.com",
      "type": "user"
    }
  }
]

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0
devcenter                          3.0.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\danielste\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

### Additional context

Reverting back to 2.53.0 it fixed the issue

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
This could be related to https://github.com/python/cpython/issues/108721.
