### ISSUE TITLE
Unable to approve Private Link Hub private endpoint

### ISSUE THREAD

**Issue by randomnote1** [Azure/azure-cli#27926]
### Describe the bug

Attempting to approve a private endpoint connection ID results in an error.

### Related command

`az network private-endpoint-connection approve --id /subscriptions/<subscription ID>/resourceGroups/ResourceGroup1/providers/Microsoft.Synapse/privateLinkHubs/privatelinkhub/privateEndpointConnections/privateEndpointConnection1id`

### Errors

Resource type must be one of Microsoft.AgFoodPlatform/farmBeats, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.ApiManagement/service, Microsoft.AppConfiguration/configurationStores, Microsoft.Batch/batchAccounts, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.Dashboard/grafana, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.DesktopVirtualization/hostpools, Microsoft.DesktopVirtualization/workspaces, Microsoft.Devices/IotHubs, Microsoft.DeviceUpdate/accounts, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventHub/namespaces, Microsoft.HardwareSecurityModules/cloudHsmClusters, Microsoft.HDInsight/clusters, Microsoft.HybridCompute/privateLinkScopes, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Monitor/accounts, Microsoft.Network/applicationGateways, Microsoft.Network/privateLinkServices, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub, Microsoft.DataFactory/factories, Microsoft.Databricks/workspaces, Microsoft.RecoveryServices/vaults, Microsoft.Kusto/clusters, Microsoft.KubernetesConfiguration/privateLinkScopes, Microsoft.OpenEnergyPlatform/energyServices, Microsoft.MachineLearningServices/registries, Microsoft.DBforMySQL/flexibleServers

### Issue script & Debug output

`az network private-endpoint-connection approve --id $privateEndpointId --debug`
cli.knack.cli: Command arguments: ['network', 'private-endpoint-connection', 'approve', '--id', '/subscriptions/<subscription id>/resourceGroups/<resource group name>/providers/Microsoft.Synapse/privateLinkHubs/<private link hub name>/privateEndpointConnections/<private endpoint connection id>', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000171A961F6A0>, <function OutputProducer.on_global_arguments at 0x00000171A97A5DA0>, <function CLIQuery.on_global_arguments at 0x00000171A97D3920>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.525       115       453
cli.azure.cli.core: privatedns                0.029        14        60
cli.azure.cli.core: Total (2)                 0.554       129       513
cli.azure.cli.core: Loaded 128 groups, 513 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network private-endpoint-connection approve
cli.azure.cli.core: Command table: network private-endpoint-connection approve
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000171AC6F9620>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\dareist\.azure\commands\2023-11-27.13-06-05.network_private-endpoint-connection_approve.36344.log'.
az_command_data_logger: command args: network private-endpoint-connection approve --id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000171AC735940>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000171AC737A60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000171AC737BA0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000171A97A5E40>, <function CLIQuery.handle_query_parameter at 0x00000171A97D39C0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000171AC737B00>]
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py", line 130, in approve_private_endpoint_connection
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py", line 119, in _get_client
knack.util.CLIError: Resource type must be one of Microsoft.AgFoodPlatform/farmBeats, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.ApiManagement/service, Microsoft.AppConfiguration/configurationStores, Microsoft.Batch/batchAccounts, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.Dashboard/grafana, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.DBforPostgreSQL/serverGroupsv2, Microsoft.DesktopVirtualization/hostpools, Microsoft.DesktopVirtualization/workspaces, Microsoft.Devices/IotHubs, Microsoft.DeviceUpdate/accounts, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.ElasticSan/elasticSans, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventGrid/partnerNamespaces, Microsoft.EventGrid/namespaces, Microsoft.EventHub/namespaces, Microsoft.HardwareSecurityModules/cloudHsmClusters, Microsoft.HDInsight/clusters, Microsoft.HybridCompute/privateLinkScopes, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Monitor/accounts, Microsoft.Network/applicationGateways, Microsoft.Network/privateLinkServices, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub, Microsoft.DataFactory/factories, Microsoft.Databricks/workspaces, Microsoft.RecoveryServices/vaults, Microsoft.Kusto/clusters, Microsoft.KubernetesConfiguration/privateLinkScopes, Microsoft.OpenEnergyPlatform/energyServices, Microsoft.MachineLearningServices/registries, Microsoft.DBforMySQL/flexibleServers, Microsoft.DocumentDB/mongoClusters

cli.azure.cli.core.azclierror: Resource type must be one of Microsoft.AgFoodPlatform/farmBeats, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.ApiManagement/service, Microsoft.AppConfiguration/configurationStores, Microsoft.Batch/batchAccounts, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.Dashboard/grafana, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.DBforPostgreSQL/serverGroupsv2, Microsoft.DesktopVirtualization/hostpools, Microsoft.DesktopVirtualization/workspaces, Microsoft.Devices/IotHubs, Microsoft.DeviceUpdate/accounts, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.ElasticSan/elasticSans, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventGrid/partnerNamespaces, Microsoft.EventGrid/namespaces, Microsoft.EventHub/namespaces, Microsoft.HardwareSecurityModules/cloudHsmClusters, Microsoft.HDInsight/clusters, Microsoft.HybridCompute/privateLinkScopes, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Monitor/accounts, Microsoft.Network/applicationGateways, Microsoft.Network/privateLinkServices, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub, Microsoft.DataFactory/factories, Microsoft.Databricks/workspaces, Microsoft.RecoveryServices/vaults, Microsoft.Kusto/clusters, Microsoft.KubernetesConfiguration/privateLinkScopes, Microsoft.OpenEnergyPlatform/energyServices, Microsoft.MachineLearningServices/registries, Microsoft.DBforMySQL/flexibleServers, Microsoft.DocumentDB/mongoClusters
az_command_data_logger: Resource type must be one of Microsoft.AgFoodPlatform/farmBeats, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.ApiManagement/service, Microsoft.AppConfiguration/configurationStores, Microsoft.Batch/batchAccounts, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.Dashboard/grafana, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.DBforPostgreSQL/serverGroupsv2, Microsoft.DesktopVirtualization/hostpools, Microsoft.DesktopVirtualization/workspaces, Microsoft.Devices/IotHubs, Microsoft.DeviceUpdate/accounts, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.ElasticSan/elasticSans, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventGrid/partnerNamespaces, Microsoft.EventGrid/namespaces, Microsoft.EventHub/namespaces, Microsoft.HardwareSecurityModules/cloudHsmClusters, Microsoft.HDInsight/clusters, Microsoft.HybridCompute/privateLinkScopes, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Monitor/accounts, Microsoft.Network/applicationGateways, Microsoft.Network/privateLinkServices, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub, Microsoft.DataFactory/factories, Microsoft.Databricks/workspaces, Microsoft.RecoveryServices/vaults, Microsoft.Kusto/clusters, Microsoft.KubernetesConfiguration/privateLinkScopes, Microsoft.OpenEnergyPlatform/energyServices, Microsoft.MachineLearningServices/registries, Microsoft.DBforMySQL/flexibleServers, Microsoft.DocumentDB/mongoClusters
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x00000171AC6F98A0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.113 seconds (init: 0.450, invoke: 0.663)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 5673 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\dareist\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

It should approve the private endpoint connection on the private link hub.

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dareist\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

**Comment by necusjz** [comment]
Means your provider `Microsoft.Synapse/privateLinkHubs` hasn't been supported yet.
