### ISSUE TITLE
Command az login failing with Failed to establish a new connection: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by AFK-Python** [Azure/azure-cli#27941]
### Describe the bug

`az login` and `az login --use-device-code` both fail. The failures seem to be inconsistent, but definitely a no-go on company wifi/VPN. The inconsistency is off of those. Some of my users can't run the command and some can.

### Related command

`az login` and `az login --use-device-code` both fail.

### Errors

```
<urllib3.connection.HTTPSConnection object at 0x7f28ff70b4c0>: Failed to establish a new connection: [Errno -2] Name does not resolve
```

### Issue script & Debug output

Issue script:
```
az login --use-device-code --debug
```

Debug log:
```
66feca6ca5a5:~$ az login --debug
cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f2b049d45e0>, <function OutputProducer.on_global_arguments at 0x7f2b0488c160>, <function CLIQuery.on_global_arguments at 0x7f2b04655480>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.002         2         9
cli.azure.cli.core: Total (1)                 0.002         2         9
cli.azure.cli.core: Loaded 2 groups, 9 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f2b031580d0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/user/.azure/commands/2023-11-28.23-15-09.login.3780.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f2b03180c10>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f2b02e5e8c0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f2b02e5e9e0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f2b0488c1f0>, <function CLIQuery.handle_query_parameter at 0x7f2b04655510>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f2b02e5e950>]
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/user/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/user/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.identity: A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
msal.telemetry: Generate or reuse correlation_id: 0b3ea953-8aa9-4a7b-a818-c82a2f1e5c27
msal.oauth2cli.oauth2: Using http://localhost:44773 as redirect_uri
msal.oauth2cli.authcode: Abort by visit http://localhost:44773?error=abort
msal.oauth2cli.authcode: Open a browser on this device to visit: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A44773&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+offline_access+openid+profile&state=zgnyDcxKrBCWFEIQ&code_challenge=gmocfk-Ic5OLut3h2g7TDPTS6K7O86SOBBclkq3CZSI&code_challenge_method=S256&nonce=f8816cd662da81f7dc1bfbdae91a8d55887ebec83f892a92280a392eca66f881&client_info=1&claims=%7B%22access_token%22%3A+%7B%22xms_cc%22%3A+%7B%22values%22%3A+%5B%22CP1%22%5D%7D%7D%7D&prompt=select_account
msal.oauth2cli.authcode: Got auth response: {'code': '0.AVAAUn4QFG4RNU67JsGPCZd5FpV3sATbjRpGu-4C-eG_e0YJAG4.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P-GbByEd0cz4Xx_LH6MF0uCTrw0pY1uGXxoq0CGBkY6gNxj0mhmNdleEz5mnMeI3fvVei1bRh155D5CtktTzaLilVvW5Z1cnqOjo5cyLwgRG-LVfSJWi_WvDpKSeXLikru56fBqKc3xtLIFkmvJE7zcfvwwf0CdtzXVCOTZAD6M8XiMdDY1oEhMnX5T5wwGOwRGIgqaR80wKb1Xt0s9TJ0HNkN616gRgiRNpKVgJLoDoj1eiaXKL-ZYTP8lRfA-GTUCB6PDXod96vkNsBdJ-fMZMITpLXHx2dDWF5jgUGcCuuYo9qLjpY5-x5hRMyBmFAY0o7GJ5XBLAELrTEgwfGg_8dlXj--IvwS7fzzkS5dZpyuHvVS0SKyp2RWSVoYw7cDX-79uqpIRAXiZy5HFJjo1TRKiqrA9ETgWIYVp2DxUWxjHNP8GgL8mkf_RtXb6v-NaT7XHiFhVwIrZLzh9qWunecfZEEtOPr4k3sr5yDNSS94Ojrf8pRvEz9YuSaT2wFJGBFsKQaF0lcli1uMNT_I3HtqVpIKiVlRfnSArhQhJiUlwPw90qW0On5yP7RfEx5g3WgKjAfYxpxvxZyW-GIn-xR0TnqT4UxJ3on-Dkoy83w7oDDS2SWr7XIR9m0MsWRRiMYW4zzgGD4p3cPJtuJRWWieRjw_0aZWDt22hhGdGFnSuUH5xfHWjdu7ut2qlVY-0Tkvj_PCsyT2f2TwU7clS3N9nTILiT_NoqEkx8FaqG5lJb2kXO_OkoiKfcAUqf5o0yXS7x5ejePXti6oawzf7rsSJq724f_Bb3yM3HanOjc59ElISNl4gA1P6pV2D3Rp2AzMxdwfoCQuK5e8hwkTwDwYF0LGQdBDCx20ehbqN_q5Ngr9rHt-8fef7KzTPPrXruAajmg', 'client_info': <client_info>, 'state': 'zgnyDcxKrBCWFEIQ', 'session_state': '1c698e70-9b67-417b-97c5-f198d66cfb34'}
msal.oauth2cli.authcode: "GET /?code=0.AVAAUn4QFG4RNU67JsGPCZd5FpV3sATbjRpGu-4C-eG_e0YJAG4.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P-GbByEd0cz4Xx_LH6MF0uCTrw0pY1uGXxoq0CGBkY6gNxj0mhmNdleEz5mnMeI3fvVei1bRh155D5CtktTzaLilVvW5Z1cnqOjo5cyLwgRG-LVfSJWi_WvDpKSeXLikru56fBqKc3xtLIFkmvJE7zcfvwwf0CdtzXVCOTZAD6M8XiMdDY1oEhMnX5T5wwGOwRGIgqaR80wKb1Xt0s9TJ0HNkN616gRgiRNpKVgJLoDoj1eiaXKL-ZYTP8lRfA-GTUCB6PDXod96vkNsBdJ-fMZMITpLXHx2dDWF5jgUGcCuuYo9qLjpY5-x5hRMyBmFAY0o7GJ5XBLAELrTEgwfGg_8dlXj--IvwS7fzzkS5dZpyuHvVS0SKyp2RWSVoYw7cDX-79uqpIRAXiZy5HFJjo1TRKiqrA9ETgWIYVp2DxUWxjHNP8GgL8mkf_RtXb6v-NaT7XHiFhVwIrZLzh9qWunecfZEEtOPr4k3sr5yDNSS94Ojrf8pRvEz9YuSaT2wFJGBFsKQaF0lcli1uMNT_I3HtqVpIKiVlRfnSArhQhJiUlwPw90qW0On5yP7RfEx5g3WgKjAfYxpxvxZyW-GIn-xR0TnqT4UxJ3on-Dkoy83w7oDDS2SWr7XIR9m0MsWRRiMYW4zzgGD4p3cPJtuJRWWieRjw_0aZWDt22hhGdGFnSuUH5xfHWjdu7ut2qlVY-0Tkvj_PCsyT2f2TwU7clS3N9nTILiT_NoqEkx8FaqG5lJb2kXO_OkoiKfcAUqf5o0yXS7x5ejePXti6oawzf7rsSJq724f_Bb3yM3HanOjc59ElISNl4gA1P6pV2D3Rp2AzMxdwfoCQuK5e8hwkTwDwYF0LGQdBDCx20ehbqN_q5Ngr9rHt-8fef7KzTPPrXruAajmg&client_info=eyJ1aWQiOiI5MmFmNjlhYS1iMmQxLTQ4ZDgtOTNlNS1lMjY2NTE1ZTUxNjgiLCJ1dGlkIjoiMTQxMDdlNTItMTE2ZS00ZTM1LWJiMjYtYzE4ZjA5OTc3OTE2In0&state=zgnyDcxKrBCWFEIQ&session_state=1c698e70-9b67-417b-97c5-f198d66cfb34 HTTP/1.1" 200 -
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /organizations/oauth2/v2.0/token HTTP/1.1" 200 4812
msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "client_id": <client_id>,
        "code": "0.AVAAUn4QFG4RNU67JsGPCZd5FpV3sATbjRpGu-4C-eG_e0YJAG4.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P-GbByEd0cz4Xx_LH6MF0uCTrw0pY1uGXxoq0CGBkY6gNxj0mhmNdleEz5mnMeI3fvVei1bRh155D5CtktTzaLilVvW5Z1cnqOjo5cyLwgRG-LVfSJWi_WvDpKSeXLikru56fBqKc3xtLIFkmvJE7zcfvwwf0CdtzXVCOTZAD6M8XiMdDY1oEhMnX5T5wwGOwRGIgqaR80wKb1Xt0s9TJ0HNkN616gRgiRNpKVgJLoDoj1eiaXKL-ZYTP8lRfA-GTUCB6PDXod96vkNsBdJ-fMZMITpLXHx2dDWF5jgUGcCuuYo9qLjpY5-x5hRMyBmFAY0o7GJ5XBLAELrTEgwfGg_8dlXj--IvwS7fzzkS5dZpyuHvVS0SKyp2RWSVoYw7cDX-79uqpIRAXiZy5HFJjo1TRKiqrA9ETgWIYVp2DxUWxjHNP8GgL8mkf_RtXb6v-NaT7XHiFhVwIrZLzh9qWunecfZEEtOPr4k3sr5yDNSS94Ojrf8pRvEz9YuSaT2wFJGBFsKQaF0lcli1uMNT_I3HtqVpIKiVlRfnSArhQhJiUlwPw90qW0On5yP7RfEx5g3WgKjAfYxpxvxZyW-GIn-xR0TnqT4UxJ3on-Dkoy83w7oDDS2SWr7XIR9m0MsWRRiMYW4zzgGD4p3cPJtuJRWWieRjw_0aZWDt22hhGdGFnSuUH5xfHWjdu7ut2qlVY-0Tkvj_PCsyT2f2TwU7clS3N9nTILiT_NoqEkx8FaqG5lJb2kXO_OkoiKfcAUqf5o0yXS7x5ejePXti6oawzf7rsSJq724f_Bb3yM3HanOjc59ElISNl4gA1P6pV2D3Rp2AzMxdwfoCQuK5e8hwkTwDwYF0LGQdBDCx20ehbqN_q5Ngr9rHt-8fef7KzTPPrXruAajmg",
        "code_verifier": "hq7E6SOBPac3UJuXeRkm2vjTidLb~Gs-n4YoDAlWzy.",
        "redirect_uri": "http://localhost:44773",
        "scope": [
            "offline_access",
            "openid",
            "https://management.core.windows.net//.default",
            "profile"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": <client_info>,
        "expires_in": 5011,
        "ext_expires_in": 5011,
        "foci": "1",
        "id_token": "********",
        "refresh_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
}
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 77384816-31e5-432e-b538-a1cfe75bd190
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '97edc80c-8e3b-11ee-b919-0242ac110002'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (PIP) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.11 (Linux-6.4.16-linuxkit-x86_64-with)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '97edc80c-8e3b-11ee-b919-0242ac110002'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (PIP) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.11 (Linux-6.4.16-linuxkit-x86_64-with)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '97edc80c-8e3b-11ee-b919-0242ac110002'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (PIP) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.11 (Linux-6.4.16-linuxkit-x86_64-with)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '97edc80c-8e3b-11ee-b919-0242ac110002'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.48.1 (PIP) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.11 (Linux-6.4.16-linuxkit-x86_64-with)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 176, in login
    subscriptions = subscription_finder.find_using_common_tenant(username, credential)
  File "/home/user/.local/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 740, in find_using_common_tenant
    for t in tenants:
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/home/user/.local/lib/python3.10/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 737, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/user/.local/lib/python3.10/site-packages/azure/mgmt/core/policies/_base.py", line 46, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 470, in send
    raise err
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication.py", line 110, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/home/user/.local/lib/python3.10/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 364, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f2b021785e0>: Failed to establish a new connection: [Errno -2] Name does not resolve

cli.azure.cli.core.azclierror: <urllib3.connection.HTTPSConnection object at 0x7f2b021785e0>: Failed to establish a new connection: [Errno -2] Name does not resolve
az_command_data_logger: <urllib3.connection.HTTPSConnection object at 0x7f2b021785e0>: Failed to establish a new connection: [Errno -2] Name does not resolve
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f2b03158310>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 9.171 seconds (init: 0.264, invoke: 8.907)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3413 in cache
telemetry.check: Negative: The /home/user/.azure/telemetry.txt was modified at 2023-11-28 23:14:54.401288, which in less than 600.000000 s
```

### Expected behavior

I should be able to login and then use the Azure CLI.

### Environment Summary

Fails on both of these:
```
{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

```
{
  "azure-cli": "2.54.0",
  "azure-cli-core": "2.54.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
```

### Additional context

I am running this from a docker container that uses alpine linux. Inconsistent behavior is occurring: company VPN seems to cause issues, but others using the container are running into the issue, even with the VPN disabled.

The people who have encountered this error are able to hit the login endpoint as `print(requests.get('https://login.microsoftonline.com/').status_code)` returns a `200` status code.

Unable to get much more info from my side, and not really sure how to further debug this.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AFK-Python** [comment]
Access to the container in question can be found [here](https://github.com/SAP-samples/btp-bridge-framework/releases/tag/v1.0.0-tf-free-tier).

**Comment by jiasli** [comment]
Judging by the debug log, `login.microsoftonline.com` can be resolved. The error `[Errno -2] Name does not resolve` occurs on `management.azure.com`. 

```
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
...
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x7f2b021785e0>: Failed to establish a new connection: [Errno -2] Name does not resolve
```
As we didn't receive any reported DNS resolution issue for `management.azure.com` in the public internet, it is recommended to report this issue to your company's IT or network department for further investigation. Thanks for understanding.
