### ISSUE TITLE
az aro create error AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mmgbrouwers** [Azure/azure-cli#27944]
### Describe the bug

During the az aro create command the following error occu's

The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/custom.py", line 82, in aro_create
    validate(cmd,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/custom.py", line 252, in validate
    error_obj = error_func(cmd, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_dynamic_validators.py", line 115, in inner
    errors = func(cmd, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_dynamic_validators.py", line 295, in _validate_resource_permissions
    resource_contributor_exists = has_role_assignment_on_resource(cmd.cli_ctx,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_rbac.py", line 73, in has_role_assignment_on_resource
    assignment.principal_id.lower() == object_id.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

### Related command

az aro create

### Errors

The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/custom.py", line 82, in aro_create
    validate(cmd,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/custom.py", line 252, in validate
    error_obj = error_func(cmd, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_dynamic_validators.py", line 115, in inner
    errors = func(cmd, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_dynamic_validators.py", line 295, in _validate_resource_permissions
    resource_contributor_exists = has_role_assignment_on_resource(cmd.cli_ctx,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/aro/_rbac.py", line 73, in has_role_assignment_on_resource
    assignment.principal_id.lower() == object_id.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

### Issue script & Debug output

az aro create \
  --resource-group $AZR_RESOURCE_GROUP \
  --name $AZR_CLUSTER \
  --vnet "$AZR_CLUSTER-aro-vnet-$AZR_RESOURCE_LOCATION" \
  --master-subnet "$AZR_CLUSTER-aro-control-subnet-$AZR_RESOURCE_LOCATION" \
  --worker-subnet "$AZR_CLUSTER-aro-machine-subnet-$AZR_RESOURCE_LOCATION" \
  --pull-secret @$AZR_PULL_SECRET \
  --cluster-resource-group $AZR_RESOURCE_GROUP_INFRA \
  --client-id $AZR_CLIENT_ID \
  --client-secret $AZR_SECRET_VALUE \
  --worker-vm-size $AZR_WORKER_SIZE \
  --worker-count $AZR_WORKER_COUNT 

### Expected behavior

cluster created

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.21.1
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/maarten_brouwers1/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kpirkoBLM** [comment]
Any updates to this issue. I am getting same issue on 1 of my 2 subscription I am installing aro into?

**Comment by knorr3** [comment]
For everyone that is struggeling with this.
In my case, I accidentally messed up the ` --client-id $AZR_CLIENT_ID`.
I specified the "SECRET ID" of the AppRegs Secret Key, instead of the actual AppReg ID.
