### ISSUE TITLE
Issue with Deleting App Service SSL Certificate - Thumbprint Not Found

### ISSUE THREAD

**Issue by verttimakikyro** [Azure/azure-cli#27950]
### Describe the bug

When attempting to delete an App Service SSL certificate, the operation fails with an error stating "Certificate for thumbprint not found." Despite confirming the correctness of the thumbprint with the az cli command az webapp config ssl show --resource-group {resource-group} --certificate-name {name}  

If I use command az webapp config ssl list --resource-group, it appears that this command returns only four certificates. Consequently, attempting to delete a certificate not listed in these four results in an error.

### Related command

az webapp config ssl delete --resource-group <your-resource-group>  --certificate-thumbprint <thumbprint>.

### Errors

Certificate for thumbprint 'xxxx' not found

### Issue script & Debug output

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/appservice/custom.py", line 2980, in delete_ssl_cert
    raise ResourceNotFoundError("Certificate for thumbprint '{}' not found".format(certificate_thumbprint))
azure.cli.core.azclierror.ResourceNotFoundError: Certificate for thumbprint 'my-thumbprint' not found

### Expected behavior

The az webapp config ssl delete command should successfully delete the specified SSL certificate.

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.54.0/libexec/bin/python'

Python (Darwin) 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]

**Comment by jayintheoffice** [comment]
How does this issue gain more traction/visibility?

The 'az webapp config ssl show' command is capable of retrieving a certificate by name and presenting the thumbprint of the certificate.

The 'az webapp config ssl delete' command neither takes a certificate name as a parameter (as a possible workaround/alternative) and so demands the thumbprint is provided. But it's incapable of finding the very same certificate the 'show' command can find.

**Comment by CodingBricked** [comment]
This is a very old issue but the same error is being surfaced last week when trying to bind a certificate so I thought it warranted a bump.

`az webapp config ssl show --resource-group rg --certificate-name cert name`

Retrieves the certificate.... e.g. 

` "thumbprint": "C52633116206855B5E91C15544067D3488E721A0",
  "type": "Microsoft.Web/certificates",`

And then when we try to bind it with:

`az webapp config ssl bind --certificate-thumbprint C52633116206855B5E91C15544067D3488E721A0 --name name --resource-group rg --ssl-type SNI`

Results in:

`Certificate for thumbprint 'C52633116206855B5E91C15544067D3488E721A0' not found.`

btw - we can see this certificate in the portal, we can manually bind it through the portal ui. However the issue is broken using az cli.

This was working fine for us for many months until last week. No changes on our side.

**Comment by Abrissirba** [comment]
We are having similar issues. We can find the certificate with az webapp config ssl show. But it is not returned if we do a list of all certificates and if we try to delete it providing the thumbprint, it is not found.

**Comment by Nollins** [comment]
We are seeing the same here when adding a certificate hosting in Key Vault - this is with hte latest cli version 2.77.0. Do we know what the issue is as this was working fine.

**Comment by seligj95** [comment]
> [!NOTE]
> **[AI-Assisted Triage]** This comment was generated with AI assistance as part of an App Service CLI issue review. Reply to this comment and tag @seligj95 to follow up.

**Summary**: SSL certificate operations fail due to pagination — only the first page of certificates is returned, so certs beyond the first page can't be found.

**Status**: Duplicate of #28722

**Priority**: P1

**Next Steps**: This will be resolved when the pagination fix for #28722 lands. That fix addresses this issue, #29403, and #28722 together.
