### ISSUE TITLE
unable to enable the azure-keyvault-secrets-provider addon vi azure-cli

### ISSUE THREAD

**Issue by robbrooks-msft** [Azure/azure-cli#27965]
### Describe the bug

Attempting to enable...

```
$ az aks addon enable --addon azure-keyvault-secrets-provider --name example-eastus-test-aks --resource-group example-
test-eastus-rg
The azure-keyvault-secrets-provider addon is already enabled for this managed cluster.
To change azure-keyvault-secrets-provider configuration, run "az aks disable-addons -a azure-keyvault-secrets-provider -n example-eastus-test-aks -g example-test-eastus-rg" before enabling it again.
```

Using command provided in error gives:

```
$ az aks disable-addons -a azure-keyvault-secrets-provider -n example-eastus-test-aks -g example-test-eastus-rg
The behavior of this command has been altered by the following extension: aks-preview
(BadRequest) AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
Code: BadRequest
Message: AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
```

```
$ az aks addon list --name example-eastus-test-aks --resource-group example-test-eastus-rg --output table
Name                             Enabled
-------------------------------  ---------
http_application_routing         False
monitoring                       True
virtual-node                     False
kube-dashboard                   False
azure-policy                     False
ingress-appgw                    True
confcom                          False
open-service-mesh                False
azure-keyvault-secrets-provider  False
gitops                           False
web_application_routing          False
```

Note, the following is visible in the json for the Kubernetes service...

```
        "addonProfiles": {
            "azureKeyVaultSecretsProvider": {
                "enabled": true,
                "config": {
                    "enableSecretRotation": "true"
                },
                "identity": {
                    "resourceId": "/subscriptions/redacted",
                    "clientId": "redacted",
                    "objectId": "redacted"
                }
            },
```

### Related command

az aks addon

### Errors

```
The azure-keyvault-secrets-provider addon is already enabled for this managed cluster.
To change azure-keyvault-secrets-provider configuration, run "az aks disable-addons -a azure-keyvault-secrets-provider -n example-eastus-test-aks -g example-test-eastus-rg" before enabling it again.
```

### Issue script & Debug output

```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/robb/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1556, in aks_addon_enable
    return enable_addons(cmd, client, resource_group_name, name, addon, workspace_resource_id=workspace_resource_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robb/.azure/cliextensions/aks-preview/azext_aks_preview/addonconfiguration.py", line 77, in enable_addons
    instance = update_addons(cmd, instance, subscription_id, resource_group_name, name, addons, enable=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robb/.azure/cliextensions/aks-preview/azext_aks_preview/addonconfiguration.py", line 335, in update_addons
    raise CLIError(
knack.util.CLIError: The azure-keyvault-secrets-provider addon is already enabled for this managed cluster.
```

### Expected behavior

Expect the azure-keyvault-secrets-provider to be enabled following the initial command.

### Environment Summary

```
$ az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.172

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.54.0/libexec/bin/python'
Extensions directory '/Users/robb/.azure/cliextensions'

Python (Darwin) 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by robbrooks-msft** [comment]
> Hi @robbrooks-msft Find similar issue #20742.
> 
> Issue title	Unable to enable addon for azure-keyvault-secrets-provider
> Create time	2021-12-15
> Comment number	2
> Please confirm if this resolves your issue.

It does not.

**Comment by FumingZhang** [comment]
@robbrooks-msft, the error you met when you tried to disable the akv secret provider addon is returned by server, which is out of the scope of this client tool. Please create a support ticket next time.

> (BadRequest) AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
> Code: BadRequest
> Message: AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
