### ISSUE TITLE
`az iot central api-token create` not working

### ISSUE THREAD

**Issue by ppapla** [Azure/azure-cli#27964]
### Describe the bug

Creating token don't work, seems that URL is not created properly. Creating token via gui works.

### Related command

az iot central api-token create

### Errors

```
he command failed with an unexpected error. Here is the traceback:
Invalid URL 'https:///subscriptions/********-****-****-****-***********/resourceGroups/*************/providers/Microsoft.IoTCentral/iotApps/*********.azureiotcentral.com/api/apiTokens/********-****-****-****-***********': No host supplied
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/******/.azure/cliextensions/azure-iot/azext_iot/central/commands_api_token.py", line 34, in add_api_token
    return provider.add_api_token(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/******/.azure/cliextensions/azure-iot/azext_iot/central/providers/api_token_provider.py", line 43, in add_api_token
    return central_services.api_token.add_api_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/******/.azure/cliextensions/azure-iot/azext_iot/central/services/api_token.py", line 51, in add_api_token
    return _utility.make_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/******/.azure/cliextensions/azure-iot/azext_iot/central/services/_utility.py", line 45, in make_api_call
    response = requests.request(
               ^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/opt/az/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/opt/az/lib/python3.11/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")

```

### Issue script & Debug output

```
export USER=$(echo $USER | sed 's/[^[:alnum:]]//g' | tr '[:upper:]' '[:lower:]')
export GROUP=my-group
export RANDOM=$(echo "$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)")

az iot central app create -n $USER-central -g $GROUP -s $USER-central-$RANDOM
export ID=$(az iot central app show --name $USER-central --resource-group $GROUP --query 'id' --output tsv)
az iot central api-token create --app-id=$ID --role=admin --token-id=a12b345c-****-****-****-56789abc0123
```

### Expected behavior

Working command

### Environment Summary

{
  "azure-cli": "2.54.0",
  "azure-cli-core": "2.54.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-iot": "0.23.0"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yang-hai-feng** [comment]
@ppapla , would you please provide your app id?  I'd like to take a look on more details, from the errors shows up, seems "DNS for your new app is not ready when you run api-token creation command"

Central Application provision takes around 5 minutes to get everything ready,  fully automated scripts probably need to retry on new created apps, if it's old app, please provide the app id, I would take a look, just tried from my own apps, seems all working well.

**Comment by ppapla** [comment]
I reproduces it again (I waited at least 15 min):

```
{
  "applicationId": "5906f5cf-d73f-45d1-998f-6a7228be499f",
  "displayName": "ppapla-central",
  "id": "/subscriptions/****/resourceGroups/****/providers/Microsoft.IoTCentral/iotApps/****",
  "identity": {
    "principalId": null,
    "tenantId": null,
    "type": "None"
  },
  "location": "northeurope",
  "name": "****",
  "networkRuleSets": {
    "applyToDevices": false,
    "applyToIoTCentral": false,
    "defaultAction": "Allow",
    "ipRules": []
  },
  "privateEndpointConnections": [],
  "provisioningState": "Succeeded",
  "publicNetworkAccess": "Enabled",
  "resourceGroup": "****",
  "sku": {
    "name": "ST2"
  },
  "state": "created",
  "subdomain": "****",
  "systemData": null,
  "tags": {},
  "template": "iotc-pnp-preview@1.0.0",
  "type": "Microsoft.IoTCentral/IoTApps"
}

```

**Comment by ppapla** [comment]
It seems like host URL is not building properly (program error). I'm using Ubuntu 22.

**Comment by yang-hai-feng** [comment]
@ppapla is this happening every time?  I actually tried multiple times from my own apps, doesn't reproduce this:  
![image](https://github.com/Azure/azure-cli/assets/14871527/fd760d81-51f6-4ee5-92b3-60415d9cc9a7)

**Comment by ppapla** [comment]
Ahhh... there was issue with my command, you can see in my first message that I used:
```
export ID=$(az iot central app show --name $USER-central --resource-group $GROUP --query 'id' --output tsv)
```
not
```
export ID=$(az iot central app show --name $USER-central --resource-group $GROUP --query 'applicationId' --output tsv)
```

thanks
