### ISSUE TITLE
az artifact universal download doesn't work on Organization scoped AzDO feeds.

### ISSUE THREAD

**Issue by seanadams9** [Azure/azure-cli#28030]
### Describe the bug

I'm unable to download nuget packages from Organization scoped AzDo feeds, only packages in a Feed that is scoped to a Project works. I've tried on multiple organizations and all come back with the same "Cannot find the package '<packagename>' in feed '<feedname>'.

I've also verified I can use the pkgs AzDo API and my token is able to download these packages just fine.

### Related command

az artifacts universal download

### Errors

"Cannot find the package '<packagename>' in feed '<feedname>'.

### Issue script & Debug output

cli.azext_devops.dev.common.artifacttool: Cannot find the package '<pacakgename>' in feed '<feedname>'
cli.azext_devops.dev.common.exception_handler: handling generic error
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 79, in run
    return self.wait()
           ^^^^^^^^^^^
  File "C:\Users\johndoe\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 51, in wait
    raise CLIError(knack.util.CLIError: Process ['C:\\Users\\johndoe\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.300\\artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/<org>/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', '<feedname>', '--package-name', '<packagename>', '--package-version', '*', '--path', 'D:\\Test'] with PID 66444 exited with return code 18

### Expected behavior

Download succeeds. If I switch to a Project scoped feed in the same org, downloads are successful. 

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0
devcenter                          4.0.1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\seadams\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by seanadams9** [comment]
@yonzhan closing this, looking at Fiddler and looks like artifactstool only works with upack packages.
