### ISSUE TITLE
Getting error `UnknownDownstreamFailure` for command `az quota usage show`

### ISSUE THREAD

**Issue by mattwelke** [Azure/azure-cli#28073]
### Describe the bug

I'm trying to explore and understand the API for working with quotas and usages (https://learn.microsoft.com/en-us/rest/api/quota/). I have taken note that it is in preview right now, not general availability. I'm using the CLI as a quick easy way to explore the API. I have ensured I'm logged into the CLI as my user account, which I am assuming has all permissions possible. I've also already manually enabled the quotas provider via the Azure Portal GUI.

When I run `az quota usage show`, it provides me with an example that I could presumably run and see useful results if I sub in my subscription:

```
~ > az quota usage show
the following arguments are required: --resource-name, --scope

Examples from AI knowledge base:
az quota usage show --scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Network/locations/eastus --resource-name MinPublicIpInterNetworkPrefixLength
Show quota usage for network
```

But if I run that, I don't get useful information. I get an opaque error. It just says that some error occurred downstream:

```
~ > az quota usage show --scope /subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus --resource-name MinPublicIpInterNetworkPrefixLength
(UnknownDownstreamFailure) The service has encountered an unexpected failure while calling QuotaResourceProvider
Code: UnknownDownstreamFailure
Message: The service has encountered an unexpected failure while calling QuotaResourceProvider
```

I tried running this command a few times, a few minutes apart. I got the same result each time.

Is this issue related to the fact that the API that backs these commands is in preview? If so, should I wait until the API is in GA before beginning to learn how it works by testing out CLI commands or API calls?

### Related command

az quota usage show

### Errors

(UnknownDownstreamFailure) The service has encountered an unexpected failure while calling QuotaResourceProvider
Code: UnknownDownstreamFailure
Message: The service has encountered an unexpected failure while calling QuotaResourceProvider

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['quota', 'usage', 'show', '--scope', '/subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus', '--resource-name', 'MinPublicIpInterNetworkPrefixLength', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f9e7ffc54e0>, <function OutputProducer.on_global_arguments at 0x7f9e7ff69ee0>, <function CLIQuery.on_global_arguments at 0x7f9e7ffa39c0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'quota': ['azext_quota']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: quota                     0.050         5        10  /home/matt/.azure/cliextensions/quota
cli.azure.cli.core: Total (1)                 0.050         5        10  
cli.azure.cli.core: Loaded 5 groups, 10 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : quota usage show
cli.azure.cli.core: Command table: quota usage show
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f9e7f0acd60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/matt/.azure/commands/2023-12-20.12-47-50.quota_usage_show.26322.log'.
az_command_data_logger: command args: quota usage show --scope {} --resource-name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f9e7f0c3240>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f9e7eec4fe0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f9e7eec5120>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f9e7ff69f80>, <function CLIQuery.handle_query_parameter at 0x7f9e7ffa3a60>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f9e7eec5080>]
az_command_data_logger: extension name: quota
az_command_data_logger: extension version: 1.0.0
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/matt/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/matt/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/4b341b5e-d5bd-48ef-bb73-4c785efa512a/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 30a151c2-6d65-43be-8919-af6b586b9bf2
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e48fc249-9f5f-11ee-adba-50284a2b9d96'
cli.azure.cli.core.sdk.policies:     'CommandName': 'quota usage show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--scope --resource-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (DEB) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Linux-6.2.0-39-generic-x86_64-with-glibc2.37)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01 HTTP/1.1" 500 143
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '143'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b954cb4d-5552-4760-9062-ac3e4e2146f9'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b954cb4d-5552-4760-9062-ac3e4e2146f9'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20231220T174755Z:b954cb4d-5552-4760-9062-ac3e4e2146f9'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Dec 2023 17:47:55 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"UnknownDownstreamFailure","message":"The service has encountered an unexpected failure while calling QuotaResourceProvider"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e48fc249-9f5f-11ee-adba-50284a2b9d96'
cli.azure.cli.core.sdk.policies:     'CommandName': 'quota usage show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--scope --resource-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (DEB) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Linux-6.2.0-39-generic-x86_64-with-glibc2.37)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01 HTTP/1.1" 500 143
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '143'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f087bc6b-5966-4ac0-9649-362b0aa3dd50'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f087bc6b-5966-4ac0-9649-362b0aa3dd50'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20231220T174755Z:f087bc6b-5966-4ac0-9649-362b0aa3dd50'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Dec 2023 17:47:54 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"UnknownDownstreamFailure","message":"The service has encountered an unexpected failure while calling QuotaResourceProvider"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e48fc249-9f5f-11ee-adba-50284a2b9d96'
cli.azure.cli.core.sdk.policies:     'CommandName': 'quota usage show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--scope --resource-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (DEB) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Linux-6.2.0-39-generic-x86_64-with-glibc2.37)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01 HTTP/1.1" 500 143
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '143'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c3fa988c-2a54-42b0-b5ae-bc1d82e38a82'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c3fa988c-2a54-42b0-b5ae-bc1d82e38a82'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20231220T174758Z:c3fa988c-2a54-42b0-b5ae-bc1d82e38a82'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Dec 2023 17:47:57 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"UnknownDownstreamFailure","message":"The service has encountered an unexpected failure while calling QuotaResourceProvider"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e48fc249-9f5f-11ee-adba-50284a2b9d96'
cli.azure.cli.core.sdk.policies:     'CommandName': 'quota usage show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--scope --resource-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (DEB) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Linux-6.2.0-39-generic-x86_64-with-glibc2.37)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<my-subscription-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength?api-version=2023-02-01 HTTP/1.1" 500 143
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '143'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '07677b3e-bb5f-4265-b7f6-62f68bc558c3'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '07677b3e-bb5f-4265-b7f6-62f68bc558c3'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CANADACENTRAL:20231220T174802Z:07677b3e-bb5f-4265-b7f6-62f68bc558c3'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Dec 2023 17:48:01 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"UnknownDownstreamFailure","message":"The service has encountered an unexpected failure while calling QuotaResourceProvider"}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_command.py", line 155, in __call__
    return self._handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/.azure/cliextensions/quota/azext_quota/aaz/latest/quota/usage/_show.py", line 33, in _handler
    self._execute_operations()
  File "/home/matt/.azure/cliextensions/quota/azext_quota/aaz/latest/quota/usage/_show.py", line 61, in _execute_operations
    self.UsagesGet(ctx=self.ctx)()
  File "/home/matt/.azure/cliextensions/quota/azext_quota/aaz/latest/quota/usage/_show.py", line 85, in __call__
    return self.on_error(session.http_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (UnknownDownstreamFailure) The service has encountered an unexpected failure while calling QuotaResourceProvider
Code: UnknownDownstreamFailure
Message: The service has encountered an unexpected failure while calling QuotaResourceProvider

cli.azure.cli.core.azclierror: (UnknownDownstreamFailure) The service has encountered an unexpected failure while calling QuotaResourceProvider
Code: UnknownDownstreamFailure
Message: The service has encountered an unexpected failure while calling QuotaResourceProvider
az_command_data_logger: (UnknownDownstreamFailure) The service has encountered an unexpected failure while calling QuotaResourceProvider
Code: UnknownDownstreamFailure
Message: The service has encountered an unexpected failure while calling QuotaResourceProvider
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f9e7f0acfe0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 12.247 seconds (init: 0.100, invoke: 12.146)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3788 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /home/matt/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Expected command to not encounter error and to show some useful output.

### Environment Summary

```
~ > az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
quota                              1.0.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/matt/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov 29 2023, 03:40:58) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@Jing-song, please help take a look.

**Comment by Jing-song** [comment]
Hi @mattwelke , Please check whether `MinPublicIpInterNetworkPrefixLength` is available in your subscription. It may be caused by the subscription you are using missing it. Please use `az quota list --scope /subscriptions/your-sub-id/providers/Microsoft.Network/locations/eastus`to see which resources your subscription can show.

**Comment by mattwelke** [comment]
Hi @Jing-song,

This seems to be working for me now.

```
az quota usage show --scope /subscriptions/<sub-id>/providers/Microsoft.Network/locations/eastus --resource-name MinPublicIpInterNetworkPrefixLength
```

```json
{
  "id": "/subscriptions/<sub-id>/providers/Microsoft.Network/locations/eastus/providers/Microsoft.Quota/usages/MinPublicIpInterNetworkPrefixLength",
  "name": "MinPublicIpInterNetworkPrefixLength",
  "properties": {
    "isQuotaApplicable": true,
    "name": {
      "localizedValue": "Public IPv4 Prefix Length",
      "value": "MinPublicIpInterNetworkPrefixLength"
    },
    "properties": {},
    "unit": "Count",
    "usages": {
      "usagesType": "Individual",
      "value": 0
    }
  },
  "type": "Microsoft.Quota/Usages"
}
```

I think what may have made a difference is that while troubleshooting while using the Go SDK, I found out that some resource providers are not automatically registered when you create your subscription, and that you have to manually register them. I manually registered a few resource providers (including for quotas), and this fixed all errors I was getting using the Go SDK for the various APIs.

The following also returns a successful response with lots of data:

````
az quota list --scope /subscriptions/<sub-id>/providers/Microsoft.Network/locations/eastus
```

So I'm all set here. Thanks!
