### ISSUE TITLE
ACR task using an user-assigned identity

### ISSUE THREAD

**Issue by b-git-hub** [Azure/azure-cli#28151]
### Describe the bug

Following from the documentation listed here
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-cross-registry-authentication

User assigned ID do not work for acr build tasks, system assigned tasks work with no issues. The example provided walks you through building a pull request. However, there are examples available through   Azure doing this with a push. This works as expected through systemID, however, user ID fail with a 403 refresh token error.

YML file is basic and as mentioned this has no issues building when using system assigned IDs
version: v1.1.0
steps:
  - build: -t $Registry/platform/$name:1.0.0 -f Dockerfile .
  - push: 
    - $Registry/platform/$name:1.0.0

### Related command

az role assignment create \
  --assignee $principalID \
  --scope $baseregID \
  --role acrpush
  
az acr task create \
  --registry $reg \
  --name $name  \
   --context $url  \
  --file acr-task.yml \
  --assign-identity $resourceID \
--git-access-token $gittoken \
 --auth-mode None 
 
 az acr task credential add \
  --name $name \
  --registry $reg \
 --login-server $reg.azurecr.io \
  --use-identity $clientID 
  
  az acr task run   --name $name   --registry $reg

### Errors

Downloading source code...
Finished downloading source code
Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.
failed to unmarshal task before running: failed to resolve secrets: failed to get ACR refresh token, exchange API response code: 403 Forbidden

### Issue script & Debug output

cli.azure.cli.command_modules.acr._stream_utils: Failed to find new content 2 times in a row
cli.azure.cli.command_modules.acr._stream_utils: Base sleep time: 1, random delay: 1, total: 2, consecutive: 4
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=dwwefdsd Outgoing request: Method=HEAD, Path=/container-72aba744645a47f0a6547bf005b09c7c/logs/db25/rawtext.log, Query={'snapshot': None, 'timeout': None, 'sv': '2021-12-02', 'se': '2024-01-08T17:53:50Z', 'sr': 'b', 'sp': 'r', 'sig': 'REDACTED'}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.9.14; Linux 5.10.102.2-microsoft-standard)', 'x-ms-client-request-id': 'dwwefdsd', 'x-ms-date': 'Mon, 08 Jan 2024 16:43:57 GMT'}.
urllib3.connectionpool: https://acrtaskproduks066.blob.core.windows.net:443 "HEAD /container-72aba744645a47f0a6547bf005b09c7c/logs/db25/rawtext.log?sv=2021-12-02&se=2024-01-08T17%3A53%3A50Z&sr=b&sp=r&sig=TTJMaJORTruFCxziR9S8L9%2BCpJenKaVWBBd4vFGLtoo%3D HTTP/1.1" 200 0
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=dwwefdsd Receiving Response: Server-Timestamp=Mon, 08 Jan 2024 16:43:56 GMT, Server-Request-ID=7a7a0b0d-201e-0037-1a51-425219000000, HTTP Status Code=200, Message=OK, Headers={'content-length': '457', 'content-type': 'text/plain; charset=utf-8', 'content-encoding': 'utf-8', 'last-modified': 'Mon, 08 Jan 2024 16:43:57 GMT', 'accept-ranges': 'bytes', 'etag': '"0x8DC1069022FC24C"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '7a7a0b0d-201e-0037-1a51-425219000000', 'x-ms-version': '2018-11-09', 'x-ms-meta-Complete': 'failed', 'x-ms-creation-time': 'Mon, 08 Jan 2024 16:43:53 GMT', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-blob-type': 'AppendBlob', 'x-ms-blob-committed-block-count': '4', 'content-disposition': '', 'x-ms-server-encrypted': 'true', 'date': 'Mon, 08 Jan 2024 16:43:56 GMT'}.
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=dwwefdsd Outgoing request: Method=GET, Path=/container-72aba744645a47f0a6547bf005b09c7c/logs/db25/rawtext.log, Query={'snapshot': None, 'timeout': None, 'sv': '2021-12-02', 'se': '2024-01-08T17:53:50Z', 'sr': 'b', 'sp': 'r', 'sig': 'REDACTED'}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-4095', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.9.14; Linux 5.10.102.2-microsoft-standard)', 'x-ms-client-request-id': 'dwwefdsd', 'x-ms-date': 'Mon, 08 Jan 2024 16:43:57 GMT'}.
urllib3.connectionpool: https://acrtaskproduks066.blob.core.windows.net:443 "GET /container-72aba744645a47f0a6547bf005b09c7c/logs/db25/rawtext.log?sv=2021-12-02&se=2024-01-08T17%3A53%3A50Z&sr=b&sp=r&sig=TTJMaJORTruFCxziR9S8L9%2BCpJenKaVWBBd4vFGLtoo%3D HTTP/1.1" 206 457
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=dwwefdsd Receiving Response: Server-Timestamp=Mon, 08 Jan 2024 16:43:56 GMT, Server-Request-ID=7a7a0b17-201e-0037-2451-425219000000, HTTP Status Code=206, Message=Partial Content, Headers={'content-length': '457', 'content-type': 'text/plain; charset=utf-8', 'content-encoding': 'utf-8', 'content-range': 'bytes 0-456/457', 'last-modified': 'Mon, 08 Jan 2024 16:43:57 GMT', 'accept-ranges': 'bytes', 'etag': '"0x8DC1069022FC24C"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '7a7a0b17-201e-0037-2451-425219000000', 'x-ms-version': '2018-11-09', 'x-ms-meta-Complete': 'failed', 'x-ms-creation-time': 'Mon, 08 Jan 2024 16:43:53 GMT', 'x-ms-lease-status': 'unlocked', 'x-ms-lease-state': 'available', 'x-ms-blob-type': 'AppendBlob', 'x-ms-blob-committed-block-count': '4', 'content-disposition': '', 'x-ms-server-encrypted': 'true', 'date': 'Mon, 08 Jan 2024 16:43:56 GMT'}.
2024/01/08 16:43:53 Downloading source code...
2024/01/08 16:43:54 Finished downloading source code
2024/01/08 16:43:55 Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.

### Expected behavior

Job should run build and push the container docker file. As mentioned, this successfully builds with system assigned IDs, this only occurs on user assigned.

### Environment Summary

az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.22.0
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/brian/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by northtyphoon** [comment]
It looks you disables public access on the registry and enables trusted service. You need to use system assigned identity in Tasks to access the registry. User assigned identity is not allowed in trusted service access.

**Comment by Roshick** [comment]
@johnsonshi any news on this issue? we currently try to use acr tasks with rbac + abac enabled in a "private" registry, this forces us to [use --source-acr-auth-id](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-rbac-abac-repository-permissions?tabs=azure-portal#attaching-an-identity-to-a-new-acr-task-for-source-registry-access) which is only compatible with user assigned identities, making it seemingly impossible to authenticate to the acr with tasks in this setup.

**Comment by johnsonshi** [comment]
@Roshick what kind of task are you using? A normal task or a quick task like `az acr build|run`?

**Comment by Roshick** [comment]
The run is instantiated from an existing task via az acr task run --name, not sure which category this falls in, I'd say a "normal task"?! The identity connected to the task has the following roles assigned: Container Registry Repository Contributor, Container Registry Repository Catalog Lister, Container Registry Contributor and Data Access Configuration Administrator and Container Registry Tasks Contributor

**Comment by johnsonshi** [comment]
This issue requires further investigation by the ACR engineering team. @lizMSFT, are you able to investigate -- are user-assigned managed identities still blocked from public network access disabled registries as per @northtyphoon?

**Comment by Roshick** [comment]
here are some debug logs from our failed runs, maybe it helps:

```log
failed to unmarshal task before running: failed to resolve secrets: failed to get ACR refresh token, exchange API response code: 403 Forbidden
Run ID: cbx failed after 3s. Error: failed during run, err: exit status 1
urllib3.connectionpool: https://acrtaskprodweu064.blob.core.windows.net:443 "HEAD /container-c3f1b7fd0f5249a8967d93c92639f9f8/logs/cbx/rawtext.log?skoid=54ea2226-b787-4507-912e-75de6df49d1d&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2025-11-07T09%3A14%3A25Z&ske=2025-11-14T09%3A19%3A25Z&sks=b&skv=2024-11-04&sv=2024-11-04&se=2025-11-07T10%3A29%3A25Z&sr=b&sp=r&sig=V2UWotcW9Vy9hCqoTKZwdzlpiIFcY83kRlDRSHr6Tr8%3D HTTP/1.1" 200 0
cli.azure.cli.command_modules.acr._stream_utils: status was: 'failed'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.13/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.13/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.13/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.13/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.13/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.13/site-packages/azure/cli/core/commands/command_operation.py", line 120, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.13/site-packages/azure/cli/command_modules/acr/task.py", line 1033, in acr_task_run
    return stream_logs(cmd, client, run_id, registry_name, resource_group_name, timeout, no_format, True)
  File "/opt/az/lib/python3.13/site-packages/azure/cli/command_modules/acr/_stream_utils.py", line 56, in stream_logs
    _stream_logs(no_format,
    ~~~~~~~~~~~~^^^^^^^^^^^
                 DEFAULT_CHUNK_SIZE,
                 ^^^^^^^^^^^^^^^^^^^
                 timeout,
                 ^^^^^^^^
                 blob_client,
                 ^^^^^^^^^^^^
                 raise_error_on_failure)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.13/site-packages/azure/cli/command_modules/acr/_stream_utils.py", line 195, in _stream_logs
    raise CLIError("Run failed")
knack.util.CLIError: Run failed
```

**Comment by lizMSFT** [comment]
Hello @Roshick, the 403 error indicates that the user-assigned managed identity doesn't have the necessary permissions to access the registry. Could you confirm whether the user-assigned and system-assigned identities have been granted the same permissions? It would also be helpful if you could provide the registry name so we can further investigate on our side. Using a user-assigned identity for ACR Tasks should be supported.

**Comment by johnsonshi** [comment]
@Roshick, as this requires more complex in-depth investigation using our backend telemetry (which requires you and Azure support to divulge confidential information), I am moving to close this issue. Please raise this issue as soon as possible with Azure support so that we can take a look. You can do so via the Support Request button on the lower left portion of the screen when you are looking at your ACR Registry in the Azure Portal.
