### ISSUE TITLE
'--no-wait' option gives error in 'az vm user update' for Windows VM.

### ISSUE THREAD

**Issue by eyoh5** [Azure/azure-cli#28180]
### Describe the bug

'az vm user update' works fine for Linux VM, but it fails for Windows VM if we run the command with --no-wait option.
without --no-wait option, it works fine even with Windows VM.

### Related command

az vm user update -g MyRG -n MyVM --username username --password xxxxx --no-wait

### Errors

PS /home/eunyoung> az vm user update -g Test -n Win2022 --username eyoh --password 'xxxxxxx' --no-wait
The command failed with an unexpected error. Here is the traceback:
'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3037, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3023, in _reset_windows_admin
    return sdk_no_wait(no_wait, client.virtual_machine_extensions.create_or_update,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'

### Issue script & Debug output

PS /home/eunyoung> az vm user update -g Test -n Win2022 --username eyoh --password 'xxxxxx' --no-wait --debug
cli.knack.cli: Command arguments: ['vm', 'user', 'update', '-g', 'Test', '-n', 'Win2022', '--username', 'eyoh', '--password', 'dhsud^*^1225', '--no-wait', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f80b42b81f0>, <function OutputProducer.on_global_arguments at 0x7f80b41d2d30>, <function CLIQuery.on_global_arguments at 0x7f80b416a310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm', 'azext_vm_repair']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.596        57       244
cli.azure.cli.core: Total (1)                 0.596        57       244
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.273         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: vm-repair                 0.016         2         6  /home/eunyoung/.azure/cliextensions/vm-repair
cli.azure.cli.core: Total (2)                 0.289         3         7  
cli.azure.cli.core: Loaded 59 groups, 251 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vm user update
cli.azure.cli.core: Command table: vm user update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f80b360f3a0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/eunyoung/.azure/commands/2024-01-12.04-14-19.vm_user_update.4841.log'.
az_command_data_logger: command args: vm user update -g {} -n {} --username {} --password {} --no-wait --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f80b35d6dc0>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.compute.v2022_11_01.models' has no attribute 'RestorePointEncryptionType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.compute.v2022_11_01.models' has no attribute 'RestorePointEncryptionType'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f80b358c0d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f80b3593ee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f80b41d2dc0>, <function CLIQuery.handle_query_parameter at 0x7f80b416a3a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f80b3593e50>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2425
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2425
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1705035950' -> 1705035950
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Compute/virtualMachines/Win2022?$expand=instanceView&api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0e25b808-b101-11ee-ba60-00155d8d5266'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm user update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --username --password --no-wait --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (RPM) azsdk-python-azure-mgmt-compute/30.3.0 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Compute/virtualMachines/Win2022?$expand=instanceView&api-version=2022-11-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/LowCostGetSubscriptionMaximum;23999,Microsoft.Compute/LowCostGetResource;35'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '79350809-94b0-46b0-8a0d-18ec808be9b4'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '658db198-ce21-4bf6-93ea-7c00deba8b28'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20240112T041420Z:658db198-ce21-4bf6-93ea-7c00deba8b28'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 12 Jan 2024 04:14:20 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "win2022",
  "id": "/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Compute/virtualMachines/win2022",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "koreacentral",
  "identity": {
    "type": "SystemAssigned",
    "principalId": "0b075388-73f5-4dfc-a013-acbebba723e5",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47"
  },
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_D2s_v4"
    },
    "provisioningState": "Succeeded",
    "vmId": "d241d583-458c-4081-850a-1290674bc6e1",
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2022-datacenter-azure-edition",
        "version": "latest",
        "exactVersion": "20348.1970.230905"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "win2022_OsDisk_1_90a9f1b1f24e422c86aae20c97e3a6ec",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Standard_LRS",
          "id": "/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/TEST/providers/Microsoft.Compute/disks/win2022_OsDisk_1_90a9f1b1f24e422c86aae20c97e3a6ec"
        },
        "deleteOption": "Delete",
        "diskSizeGB": 127
      },
      "dataDisks": [],
      "diskControllerType": "SCSI"
    },
    "osProfile": {
      "computerName": "win2022",
      "adminUsername": "eyoh",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true,
        "patchSettings": {
          "patchMode": "AutomaticByOS",
          "assessmentMode": "ImageDefault",
          "enableHotpatching": false
        },
        "enableVMAgentPlatformUpdates": false
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "securityProfile": {
      "uefiSettings": {
        "secureBootEnabled": true,
        "vTpmEnabled": true
      },
      "securityType": "TrustedLaunch"
    },
    "networkProfile": {"networkInterfaces":[{"id":"/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Network/networkInterfaces/win2022156","properties":{"deleteOption":"Detach"}}]},
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "instanceView": {
      "computerName": "win2022",
      "osName": "Windows Server 2022 Datacenter Azure Edition",
      "osVersion": "10.0.20348.2113",
      "vmAgent": {
        "vmAgentVersion": "2.7.41491.1102",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "GuestAgent is running and processing the extensions.",
            "time": "2024-01-12T04:13:54.37+00:00"
          }
        ],
        "extensionHandlers": [
          {
            "type": "Microsoft.Compute.VMAccessAgent",
            "typeHandlerVersion": "2.4.11",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          },
          {
            "type": "Microsoft.GuestConfiguration.ConfigurationforWindows",
            "typeHandlerVersion": "1.29.65.0",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          }
        ]
      },
      "disks": [
        {
          "name": "win2022_OsDisk_1_90a9f1b1f24e422c86aae20c97e3a6ec",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2024-01-12T02:17:37.2509105+00:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "extensions": [
        {
          "name": "AzurePolicyforWindows",
          "type": "Microsoft.GuestConfiguration.ConfigurationforWindows",
          "typeHandlerVersion": "1.29.65.0",
          "substatuses": [
            {
              "code": "ComponentStatus/DscConfigurationLog/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": ""
            },
            {
              "code": "ComponentStatus/DscExtensionLog/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "[2023-12-20 08:44:47Z] C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\1.29.65.0\\bin\\..\\dsc\\GC folder doesnt exist. ... \r\n[2023-12-20 08:45:02Z] GC.zip unzip completed. Zip file count 799, Unzipped file count 799 ...\r\n[2023-12-20 08:45:02Z] Extension request for sequence number 0 attempting to acquire lock.0 file\r\n[2023-12-20 08:45:02Z] Extension request for sequence number 0 attempting to acquire lock file\r\n[2023-12-20 08:45:02Z] File lock does not exist: begin processing\r\n[2023-12-20 08:45:02Z] Starting DSC Extension ...\r\n[2023-12-20 08:45:02Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\1.29.65.0\\Status ...\r\n[2023-12-20 08:45:02Z] Updating execution status (HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\1.29.65.0\\Status)\r\n[2023-12-20 08:45:02Z] Transitioning to DataValidation state ...\r\n[2023-12-20 08:45:02Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\1.29.65.0\\Status\\0.status)\r\n[2023-12-20 08:45:02Z] Reading handler settings from C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\1.29.65.0\\RuntimeSettings\\0.settings\r\n[2023-12-20 08:45:02Z] Found protected settings on Azure VM. Decrypting.\r\n[2023-12-20 08:45:06Z] Get DSC Extension Handler install status  ...\r\n[2023-12-20 08:45:06Z]  Status: NotInstalled\r\n[2023-12-20 08:45:06Z] Updating execution status (HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\1.29.65.0\\Status)\r\n[2023-12-20 08:45:06Z] Transitioning to InstallExtension state ...\r\n[2023-12-20 08:45:06Z] Getting handler execution status HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\1.29.65.0\\Status ...\r\n[2023-12-20 08:45:06Z] DSC Extension Install Status: NotInstalled\r\n[2023-12-20 08:45:06Z] Installing the DSC Extension...\r\n[2023-12-20 08:45:06Z] Settings handler status to 'transitioning' (C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\1.29.65.0\\Status\\0.status)\r\n[2023-12-20 08:45:06Z] Installing GCService ...\r\n[2023-12-20 08:45:08Z] The DSC Extension was installed successfully\r\n[2023-12-20 08:45:08Z] Setting install status to 'Installed' (HKLM:\\SOFTWARE\\Microsoft\\Azure\\DSC\\1.29.65.0\\InstallStatus)\r\n[2023-12-20 08:45:09Z] VMUUId is D241D583-458C-4081-850A-1290674BC6E1 ...\r\n[2023-12-20 08:45:09Z] Invoking GCService Enable ...\r\n[2023-12-20 08:45:11Z] Settings handler status to 'success' (C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\1.29.65.0\\Status\\0.status)"
            }
          ],
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Extension has been enabled.",
              "time": "2023-12-20T08:45:11+00:00"
            }
          ]
        },
        {
          "name": "enablevmaccess",
          "type": "Microsoft.Compute.VMAccessAgent",
          "typeHandlerVersion": "2.4.11",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Succesfully updated Admin account and enabled Remote Desktop connection to the machine"
            }
          ]
        }
      ],
      "hyperVGeneration": "V2",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2024-01-12T04:09:58.516485+00:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    },
    "timeCreated": "2023-09-13T07:54:17.651548+00:00"
  },
  "resources": [
    {
      "name": "AzurePolicyforWindows",
      "id": "/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Compute/virtualMachines/win2022/extensions/AzurePolicyforWindows",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "koreacentral",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "enableAutomaticUpgrade": true,
        "publisher": "Microsoft.GuestConfiguration",
        "type": "ConfigurationforWindows",
        "typeHandlerVersion": "1.1",
        "settings": {}
      }
    },
    {
      "name": "enablevmaccess",
      "id": "/subscriptions/1fac221b-4436-452a-8453-6a99ce600916/resourceGroups/Test/providers/Microsoft.Compute/virtualMachines/win2022/extensions/enablevmaccess",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "koreacentral",
      "properties": {
        "autoUpgradeMinorVersion": false,
        "provisioningState": "Succeeded",
        "publisher": "Microsoft.Compute",
        "type": "VMAccessAgent",
        "typeHandlerVersion": "2.4",
        "settings": {"UserName":"eyoh"}
      }
    }
  ]
}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2425
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3037, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3023, in _reset_windows_admin
    return sdk_no_wait(no_wait, client.virtual_machine_extensions.create_or_update,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3037, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3023, in _reset_windows_admin
    return sdk_no_wait(no_wait, client.virtual_machine_extensions.create_or_update,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
az_command_data_logger: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3037, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 3023, in _reset_windows_admin
    return sdk_no_wait(no_wait, client.virtual_machine_extensions.create_or_update,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f80b360f5e0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.580 seconds (init: 0.375, invoke: 2.205)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7298 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/eunyoung/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

az vm user update success without failure even with --no-wait option

### Environment Summary

azure-cli                         2.55.0 *

core                              2.55.0 *
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.22.0
ssh                                2.0.2
vm-repair                          0.5.9

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/eunyoung/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. They will be updated with the next build of Cloud Shell.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by eyoh5** [comment]
Hi @yonzhan Do you have any updates on this issue? Is it bug on az cli?
