### ISSUE TITLE
"az afd route create --enable-compression true" is failed when "--content-types-to-compress" is not provided

### ISSUE THREAD

**Issue by vlardn** [Azure/azure-cli#28223]
### Describe the bug

Exactly the same 'az' command was succeeded on Dec 5, 2023 with azure-cli 2.54.0 but now is failing (with azure-cli 2.56.0):

### Related command

 `az afd route create --resource-group myapp-prod-network --profile-name myapp-prod-afd --route-name main --custom-domains www2-myapp-com --link-to-default-domain Disabled --endpoint-name myapp-prod --origin-group Main --supported-protocols Http Https --https-redirect Enabled --forwarding-protocol HttpsOnly --enable-caching true --query-string-caching-behavior UseQueryString --enable-compression true`

### Errors

`ERROR: (BadRequest) Compression cannot be enabled when content type to compress is empty`

### Issue script & Debug output

```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 1013, in __call__
    raise exception
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/cdn/aaz/latest/afd/route/_create.py", line 214, in _execute_operations
    yield self.RoutesCreate(ctx=self.ctx)()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/cdn/aaz/latest/afd/route/_create.py", line 254, in __call__
    return self.on_error(session.http_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (BadRequest) Compression cannot be enabled when content type to compress is empty.
Code: BadRequest
Message: Compression cannot be enabled when content type to compress is empty.
```

### Expected behavior

The command should succeed and compression should be enabled for default content types the same way as it happens in portal.azure.com:
<img src="https://github.com/Azure/azure-cli/assets/3735725/ac5f472c-2faa-4a3c-9d27-763460c2d9e3" width="300">

### Environment Summary

azure-cli 2.56.0

### Additional context

The `default_content_types` variable with all necessary values is already present in azure-cli source code but not used in this case:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vlardn** [comment]
Btw, adding `--content-types-to-compress text/plain text/html` to the command `az afd route create` above does not help and gives the same error: `Compression cannot be enabled when content type to compress is empty` :-( 

So this bug is even more serios

**Comment by t-bzhan** [comment]
Hi @vlardn , sorry for the for the inconvenience. Our engineering team is actively working on a fix and aims to address this in the upcoming release.
