### ISSUE TITLE
az login --identity issue on Machine Learning Compute

### ISSUE THREAD

**Issue by almmechanics** [Azure/azure-cli#28220]
### Describe the bug

Azure Machine Learning Compute with a `System assigned identity` cannot execute the `az login --identity` command

This occurs with both conda and core ubuntu instances of `az cli`

Note: 

- Managed Identity exists and is registered in EntraID
- Instance was created on 19/1/2024 
- Image Size `Standard_DS11_v2 (2 cores, 14 GB RAM, 28 GB disk)`
- OS All packages have been updated and the machine restarted

## with the default conda environment `azureml_py38`

Running `az login --identity` 

Returns 
> MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.

## If conda is deactivated 

running `az version` shows

> {
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ml": "2.5.0"
  }
}

Running `az login --identity` 

Returns 
> MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.

### Errors

# From conda environment

MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.
The command failed with an unexpected error. Here is the traceback:
MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 122, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 234, in login_with_managed_identity
    msi_creds = MSIAuthenticationWrapper(resource=resource)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/auth/adal_authentication.py", line 75, in set_token
    super().set_token()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 596, in set_token
    self.scheme, _, self.token = get_msi_token_webapp(self.resource, self.msi_conf)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msrestazure/azure_active_directory.py", line 546, in get_msi_token_webapp
    raise RuntimeError(err_msg)
RuntimeError: MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.

# From default environment

The command failed with an unexpected error. Here is the traceback:
MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/profile/custom.py", line 122, in login
    return profile.login_with_managed_identity(username, allow_no_subscriptions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 234, in login_with_managed_identity
    msi_creds = MSIAuthenticationWrapper(resource=resource)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/auth/adal_authentication.py", line 75, in set_token
    super().set_token()
  File "/opt/az/lib/python3.11/site-packages/msrestazure/azure_active_directory.py", line 596, in set_token
    self.scheme, _, self.token = get_msi_token_webapp(self.resource, self.msi_conf)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/msrestazure/azure_active_directory.py", line 546, in get_msi_token_webapp
    raise RuntimeError(err_msg)
RuntimeError: MSI: Failed to retrieve a token from 'http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01' with an error of 'SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found'.

### Issue script & Debug output

azure cli commands listed above

### Expected behavior

managed identity can be used from the machine learning compute.

### Environment Summary

With the default conda environment `azureml_py38`

running `az version` shows

> {
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ml": "2.5.0"
  }
}

If conda is deactivated 

running `az version` shows

> {
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ml": "2.5.0"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
The error `SSO failure: unable to retrieve a token. Error Token service my-compute01. Token not found` is from the IMDS endpoint `http://127.0.0.1:46808/MSI/auth/?resource=https://management.core.windows.net/&api-version=2017-09-01`. Routing to Machine Learning service team. 

If this issue is urgent, you may create a support ticket for Machine Learning service: https://azure.microsoft.com/en-us/support/create-ticket

**Comment by mispa-ms** [comment]
Any update on this issue? I also got the same issue.

**Comment by jnpr-stevenzhao** [comment]
The error is encountered and thrown out from HostTool runtime. I will continue the investigations two weeks later (after Chinese New Year holidays).

**Comment by jnpr-stevenzhao** [comment]
Investigation is ongoing ...

**Comment by jnpr-stevenzhao** [comment]
With one more option "--debug " for command "az login --identity", more logs are got, but the logs are not enough for debugging the issue.
Will try to change the log output level for more clues.

**Comment by jnpr-stevenzhao** [comment]
After I clicked the "JupyterLab" and tried again, the issue disappeared.
![Screenshot 2024-03-25 145150](https://github.com/Azure/azure-cli/assets/8045233/c9d8b889-7e0b-4be4-b6c5-e31fe0e478a1)

**Comment by jnpr-stevenzhao** [comment]
Some users may get a pop-up window prompted to login, and thereby will not encounter this issue after login.
But others who do not see this login window are required to login by some means, such as clicking "JupyterLab" shown in above comment.

![image](https://github.com/Azure/azure-cli/assets/8045233/348938ce-2f36-4614-ab4f-09c9fe8a9ede)

**Comment by jeburge-msft** [comment]
We are encountering the same issue as well, waiting for resolution.

**Comment by jeburge-msft** [comment]
Followed this solution to resolve: 
![image](https://github.com/Azure/azure-cli/assets/153769121/ca9e6515-2aca-4bf8-bac9-647fd8659143)
https://github.com/Azure/azure-cli/issues/24675

**Comment by ykerus** [comment]
Had the same issue today. Had already completely given up. But another error with `az ml` led me to this issue: https://github.com/Azure/azure-cli/issues/21390

And trying this:
```bash
az extension remove -n ml
az extension add -n ml
```

fixed everything for me! Was suddenly also able to call `az login --identity`, and access my data from storage afterwards.

Hope this works for you too

**Comment by gitgud5000** [comment]
> And trying this:
> 
> az extension remove -n ml
> az extension add -n ml
> fixed everything for me! Was suddenly also able to call `az login --identity`, and access my data from storage afterwards. Hope this works for you too

Same Issue, the nor this or the Jupyter workaround worked for me. 
Latest versions to date: `ml=2.44.0` and `cli= 2.87.0`
