### ISSUE TITLE
"az afd rule create" failing with unexpected internal error

### ISSUE THREAD

**Issue by vlardn** [Azure/azure-cli#28240]
### Describe the bug

The same 'az' command was succeeded on Dec 5, 2023, with azure-cli 2.54.0 but now is failing (with azure-cli 2.56.0):

### Related command

`az afd rule create --resource-group myapp-prod-network --profile-name myapp-prod-afd --rule-set-name RedirectRoot --rule-name RedirectForHsts --action-name UrlRedirect --order 0 --redirect-type TemporaryRedirect --redirect-protocol Https --custom-hostname www.myapp.com`

### Errors

```
The command failed with an unexpected error. Here is the traceback:
cannot access local variable 'condition' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/cdn/aaz/latest/afd/rule/_create.py", line 1308, in _execute_operations
    self.pre_operations()
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/cdn/custom/custom_afdx.py", line 694, in pre_operations
    condition = create_condition(args.match_variable, args.operator,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/cdn/custom/custom_rule_util.py", line 242, in create_condition
    return condition
           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'condition' where it is not associated with a value
```

### Issue script & Debug output

-

### Expected behavior

The command should succeed.

### Environment Summary

azure-cli 2.56.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by datadot** [comment]
Experiencing the same issue here, seems to be bug..

**Comment by Reeya17** [comment]
I am also facing same issue

**Comment by gctrevino** [comment]
I am having the same issue...

**Comment by datadot** [comment]
@yonzhan are you able to escalate or get an update on this please?

**Comment by t-bzhan** [comment]
Hi @vlardn / @datadot, we are actively working on a fix and aims to address this in the upcoming release.
