### ISSUE TITLE
Connection aborted.

### ISSUE THREAD

**Issue by aloizeau** [Azure/azure-cli#28305]
### Describe the bug

When I want to use `az login`  I've received this error: `('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))`

### Related command

`az login`

### Errors

('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))

### Issue script & Debug output

az login --debug
cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000002332A59B560>, <function OutputProducer.on_global_arguments at 0x000002332A725C60>, <function CLIQuery.on_global_arguments at 0x000002332A7537E0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.008         2         8
cli.azure.cli.core: Total (1)                 0.008         2         8
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 2 groups, 8 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000002332D63A160>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\antoi\.azure\commands\2024-02-05.22-31-37.login.7628.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000002332D66E480>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000002332D694540>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000002332D694680>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000002332A725D00>, <function CLIQuery.handle_query_parameter at 0x000002332A753880>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000002332D6945E0>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\antoi\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\antoi\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.identity: A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
msal.telemetry: Generate or reuse correlation_id: fdda97e9-a542-43c7-9413-a0c99e1fdd9f
msal.oauth2cli.oauth2: Using http://localhost:59905 as redirect_uri
msal.oauth2cli.authcode: Abort by visit http://localhost:59905?error=abort
msal.oauth2cli.authcode: Open a browser on this device to visit: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A59905&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+offline_access+openid+profile&state=zLTcpsOfFdZCwoul&code_challenge=07gaBeMo1KlB8A7SkuRoVbdmTlqjZC_Ka_8Vz__zjqw&code_challenge_method=S256&nonce=ba56ae5e98a97c36bb739a95998aca36637644cf5017642d252c0c44cfb2330d&client_info=1&claims=%7B%22access_token%22%3A+%7B%22xms_cc%22%3A+%7B%22values%22%3A+%5B%22CP1%22%5D%7D%7D%7D&prompt=select_account
msal.oauth2cli.authcode: Got auth response: {'code': '0.AU4AW4fu6KXpFkeUV7Efs17IT5V3sATbjRpGu-4C-eG_e0aDAKo.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P8DPrBiUBxbCvM4y0Ta-MMy95Os95S7n7VSgt50fHFlXPAeGgGqF82IZWvD9C7eliRYG-ZdJfD9K_qss72FtdV8GaJt3wbv1W9kSi_k2EOz_dER8l0uVvVnvxBaAW9UBJCZej6k40Q-8jyhPwllE6xyrQ3ckulCp0hvhRWLd8F83OP-XDBI4BsBu8P0aNybeOkZIuhAMZOxE379wjhJQPj_TmFi9ySTqhmpB29Cy-vLkeXW11XhTd1T0UIUXHiiD3tNED46YSNaVA7mEvh_gBleh8ZfC0rNq4M1d_n8mg4InJErgEHsg4r0uqlBJFb33agkOsF0rgg-RgNbv0kxhWjzwm27F1Thsiop4Cxa1kPf_Y6St0UlHSUmJDj-Q5DxO9VkiPJgPVm1YLyC-9ZKvbHC5HTts6oVJjKKldF6yq_U67IPPKgpixh4oDLwzuBk2YRZzlBR40xvNQtBwjn7RWH0zvCd5LA1MgAin-f1aCHJfJi52-A8pKEbomxXkRz73URYvUgqfUSeLl6zVCwIhFis4fTcxjjyxDv5YZOlv7gLYeZxCagfHJbuX1nKVLQQrr39XyhHsVGHbrb0GyzwTDzjS_hsL5BBDkr8c8hFnSe6sjXkqx0Jfxi1foAxqR1DqAxQ6BDQTYZ9jeIUfNUIP9tq4Elhf6LVgbNrzkFNEdLRpE5wW4sj0695UzDedxvi1hXGk9Ji568MR2of7e-ogeP61jUohuj3sdykOk4NAKZE6wKGTCVV7QzFgqbZ8ksE6IjPBno9ciIBUcD4uSPIvT_x1kvvy_oALAzdHCpYf6G-LYfkvZlr0xJLxRdbfe-7cpkypYYwbIHkAtFnpkc0JZAR5FriQx4bH0L2OxNW55k2GufupFRP4ELvPLSBnrmBbX9C0PLyofuinJgpqfLrIqJK7d6sjw2FJ-sX2mf7La8x3aewd1dJuK3orSybI0GmcCB28DdbEqFW94DivTCl5UIK1YM1NYuyaLd4QuGWSx4MkE-eKAzLzOn06izTH5K4vdESigDQusGYgJQnKzBzvucNwgfub5L86LEhZo_It44XIK2pdEG3xZwYKFPX-ESmuj4TrU1scns4mAqmKDGDhMFYsXlSlX5NZwpkKzBmuvV4aLBXEY2rPbyeWm1Iq_N1U1jhfskga87hxpkHm2v_ynAST8GTiq-emBgNtlc7Wot5q0pKQiREvwKtUgSQOQjtGRnMy2BqRwgkRqZwrORybvRe2uqTU0QKX39Um2CuE9STJMmNi-0AWN0zqokLJTPRgjI_AC50GsJD6ftiJDHRrO8sG3YqddINI3_5XGSA1OIFN7m3rkE0Gm1XjiPaqouzhzDW80_CktnlygrxJMpjJpAFdLZpJcaDpTBcKZqdQyL2tA7wfer8rsD_v0UY48lOyIO9SAx0HKIuMLAc7FAUv6lz0FhkhkR4ohJQe4hpkgfBbHEvt9Vv35oK9sC_r3-kyOlRMIehbEzp6DHR2oGX42zwsAmXYaX3DUDIW3hyGpPZjfSM0Vea9RaNX8Ab3-16UN8wXfcmr9Yngj4GQl3PPy6N9Hj4G-iciXWK0cDeNf_gRGPZto6ARh6Ep8leyb4UJS4hvgNqI8VJOUugZfS9gfGIEys4BnE', 'client_info': 'eyJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtYmRmNy02ZjVjZmNiNzRkNDkiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0', 'state': 'zLTcpsOfFdZCwoul', 'session_state': 'b7c91de7-f014-4d98-8a0f-26689488c360'}
msal.oauth2cli.authcode: "GET /?code=0.AU4AW4fu6KXpFkeUV7Efs17IT5V3sATbjRpGu-4C-eG_e0aDAKo.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P8DPrBiUBxbCvM4y0Ta-MMy95Os95S7n7VSgt50fHFlXPAeGgGqF82IZWvD9C7eliRYG-ZdJfD9K_qss72FtdV8GaJt3wbv1W9kSi_k2EOz_dER8l0uVvVnvxBaAW9UBJCZej6k40Q-8jyhPwllE6xyrQ3ckulCp0hvhRWLd8F83OP-XDBI4BsBu8P0aNybeOkZIuhAMZOxE379wjhJQPj_TmFi9ySTqhmpB29Cy-vLkeXW11XhTd1T0UIUXHiiD3tNED46YSNaVA7mEvh_gBleh8ZfC0rNq4M1d_n8mg4InJErgEHsg4r0uqlBJFb33agkOsF0rgg-RgNbv0kxhWjzwm27F1Thsiop4Cxa1kPf_Y6St0UlHSUmJDj-Q5DxO9VkiPJgPVm1YLyC-9ZKvbHC5HTts6oVJjKKldF6yq_U67IPPKgpixh4oDLwzuBk2YRZzlBR40xvNQtBwjn7RWH0zvCd5LA1MgAin-f1aCHJfJi52-A8pKEbomxXkRz73URYvUgqfUSeLl6zVCwIhFis4fTcxjjyxDv5YZOlv7gLYeZxCagfHJbuX1nKVLQQrr39XyhHsVGHbrb0GyzwTDzjS_hsL5BBDkr8c8hFnSe6sjXkqx0Jfxi1foAxqR1DqAxQ6BDQTYZ9jeIUfNUIP9tq4Elhf6LVgbNrzkFNEdLRpE5wW4sj0695UzDedxvi1hXGk9Ji568MR2of7e-ogeP61jUohuj3sdykOk4NAKZE6wKGTCVV7QzFgqbZ8ksE6IjPBno9ciIBUcD4uSPIvT_x1kvvy_oALAzdHCpYf6G-LYfkvZlr0xJLxRdbfe-7cpkypYYwbIHkAtFnpkc0JZAR5FriQx4bH0L2OxNW55k2GufupFRP4ELvPLSBnrmBbX9C0PLyofuinJgpqfLrIqJK7d6sjw2FJ-sX2mf7La8x3aewd1dJuK3orSybI0GmcCB28DdbEqFW94DivTCl5UIK1YM1NYuyaLd4QuGWSx4MkE-eKAzLzOn06izTH5K4vdESigDQusGYgJQnKzBzvucNwgfub5L86LEhZo_It44XIK2pdEG3xZwYKFPX-ESmuj4TrU1scns4mAqmKDGDhMFYsXlSlX5NZwpkKzBmuvV4aLBXEY2rPbyeWm1Iq_N1U1jhfskga87hxpkHm2v_ynAST8GTiq-emBgNtlc7Wot5q0pKQiREvwKtUgSQOQjtGRnMy2BqRwgkRqZwrORybvRe2uqTU0QKX39Um2CuE9STJMmNi-0AWN0zqokLJTPRgjI_AC50GsJD6ftiJDHRrO8sG3YqddINI3_5XGSA1OIFN7m3rkE0Gm1XjiPaqouzhzDW80_CktnlygrxJMpjJpAFdLZpJcaDpTBcKZqdQyL2tA7wfer8rsD_v0UY48lOyIO9SAx0HKIuMLAc7FAUv6lz0FhkhkR4ohJQe4hpkgfBbHEvt9Vv35oK9sC_r3-kyOlRMIehbEzp6DHR2oGX42zwsAmXYaX3DUDIW3hyGpPZjfSM0Vea9RaNX8Ab3-16UN8wXfcmr9Yngj4GQl3PPy6N9Hj4G-iciXWK0cDeNf_gRGPZto6ARh6Ep8leyb4UJS4hvgNqI8VJOUugZfS9gfGIEys4BnE&client_info=eyJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtYmRmNy02ZjVjZmNiNzRkNDkiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0&state=zLTcpsOfFdZCwoul&session_state=b7c91de7-f014-4d98-8a0f-26689488c360 HTTP/1.1" 200 -
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /organizations/oauth2/v2.0/token HTTP/1.1" 200 5807
msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
        "code": "0.AU4AW4fu6KXpFkeUV7Efs17IT5V3sATbjRpGu-4C-eG_e0aDAKo.AgABAAIAAAAmoFfGtYxvRrNriQdPKIZ-AgDs_wUA9P8DPrBiUBxbCvM4y0Ta-MMy95Os95S7n7VSgt50fHFlXPAeGgGqF82IZWvD9C7eliRYG-ZdJfD9K_qss72FtdV8GaJt3wbv1W9kSi_k2EOz_dER8l0uVvVnvxBaAW9UBJCZej6k40Q-8jyhPwllE6xyrQ3ckulCp0hvhRWLd8F83OP-XDBI4BsBu8P0aNybeOkZIuhAMZOxE379wjhJQPj_TmFi9ySTqhmpB29Cy-vLkeXW11XhTd1T0UIUXHiiD3tNED46YSNaVA7mEvh_gBleh8ZfC0rNq4M1d_n8mg4InJErgEHsg4r0uqlBJFb33agkOsF0rgg-RgNbv0kxhWjzwm27F1Thsiop4Cxa1kPf_Y6St0UlHSUmJDj-Q5DxO9VkiPJgPVm1YLyC-9ZKvbHC5HTts6oVJjKKldF6yq_U67IPPKgpixh4oDLwzuBk2YRZzlBR40xvNQtBwjn7RWH0zvCd5LA1MgAin-f1aCHJfJi52-A8pKEbomxXkRz73URYvUgqfUSeLl6zVCwIhFis4fTcxjjyxDv5YZOlv7gLYeZxCagfHJbuX1nKVLQQrr39XyhHsVGHbrb0GyzwTDzjS_hsL5BBDkr8c8hFnSe6sjXkqx0Jfxi1foAxqR1DqAxQ6BDQTYZ9jeIUfNUIP9tq4Elhf6LVgbNrzkFNEdLRpE5wW4sj0695UzDedxvi1hXGk9Ji568MR2of7e-ogeP61jUohuj3sdykOk4NAKZE6wKGTCVV7QzFgqbZ8ksE6IjPBno9ciIBUcD4uSPIvT_x1kvvy_oALAzdHCpYf6G-LYfkvZlr0xJLxRdbfe-7cpkypYYwbIHkAtFnpkc0JZAR5FriQx4bH0L2OxNW55k2GufupFRP4ELvPLSBnrmBbX9C0PLyofuinJgpqfLrIqJK7d6sjw2FJ-sX2mf7La8x3aewd1dJuK3orSybI0GmcCB28DdbEqFW94DivTCl5UIK1YM1NYuyaLd4QuGWSx4MkE-eKAzLzOn06izTH5K4vdESigDQusGYgJQnKzBzvucNwgfub5L86LEhZo_It44XIK2pdEG3xZwYKFPX-ESmuj4TrU1scns4mAqmKDGDhMFYsXlSlX5NZwpkKzBmuvV4aLBXEY2rPbyeWm1Iq_N1U1jhfskga87hxpkHm2v_ynAST8GTiq-emBgNtlc7Wot5q0pKQiREvwKtUgSQOQjtGRnMy2BqRwgkRqZwrORybvRe2uqTU0QKX39Um2CuE9STJMmNi-0AWN0zqokLJTPRgjI_AC50GsJD6ftiJDHRrO8sG3YqddINI3_5XGSA1OIFN7m3rkE0Gm1XjiPaqouzhzDW80_CktnlygrxJMpjJpAFdLZpJcaDpTBcKZqdQyL2tA7wfer8rsD_v0UY48lOyIO9SAx0HKIuMLAc7FAUv6lz0FhkhkR4ohJQe4hpkgfBbHEvt9Vv35oK9sC_r3-kyOlRMIehbEzp6DHR2oGX42zwsAmXYaX3DUDIW3hyGpPZjfSM0Vea9RaNX8Ab3-16UN8wXfcmr9Yngj4GQl3PPy6N9Hj4G-iciXWK0cDeNf_gRGPZto6ARh6Ep8leyb4UJS4hvgNqI8VJOUugZfS9gfGIEys4BnE",
        "code_verifier": "pDMKGC5Is9n8rxdXg~clfvEejJPhQUL_T.ZYWSu3zok",
        "redirect_uri": "http://localhost:59905",
        "scope": [
            "https://management.core.windows.net//.default",
            "profile",
            "openid",
            "offline_access"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtYmRmNy02ZjVjZmNiNzRkNDkiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0",
        "expires_in": 4749,
        "ext_expires_in": 4749,
        "foci": "1",
        "id_token": "********",
        "refresh_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
}
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 4223d473-77e9-4bd2-a883-9bad40074184
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f1936b42-c46d-11ee-813e-4c445bef0587'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.56.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f1936b42-c46d-11ee-813e-4c445bef0587'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.56.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f1936b42-c46d-11ee-813e-4c445bef0587'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.56.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f1936b42-c46d-11ee-813e-4c445bef0587'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.56.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 176, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 740, in find_using_common_tenant
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 123, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 75, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 739, in get_next
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 213, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/core/policies/_base.py", line 47, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_redirect.py", line 181, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 489, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 467, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_authentication.py", line 115, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 108, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 376, in send
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))

cli.azure.cli.core.azclierror: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
az_command_data_logger: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002332D63A3E0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 13.228 seconds (init: 0.494, invoke: 12.734)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3358 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\antoi\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

az login must show me my Azure context.

### Environment Summary

azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Extensions:
aks-preview                      1.0.0b5
application-insights               1.2.0
containerapp                      0.3.46
storage-preview                  1.0.0b1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\antoi\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I'm use Terminal console on Windows 11 home edition

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Duplicate of #20649
What's the output of `& "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://management.azure.com').status_code)"`

**Comment by aloizeau** [comment]
<img width="1934" height="100" alt="Image" src="https://github.com/user-attachments/assets/5b8e48c7-28a5-40fe-837c-4618ec611ffc" />

400

**Comment by aloizeau** [comment]
Any update on it, I've always the same issue with a new laptop ?

**Comment by kilchitsky13** [comment]
@aloizeau, please check this [answer](https://github.com/Azure/azure-cli/issues/20649#issuecomment-4163701133)
