### ISSUE TITLE
az network bastion rdp  fails if member of too many Entra groups

### ISSUE THREAD

**Issue by shil-patel** [Azure/azure-cli#28307]
### Describe the bug

"az network bastion rdp"  fails for users who are a member of a large number of groups.

Looking at the debug logs, the token response is cut off and then fails to download the RDP file.

### Related command

		az network bastion rdp `
		--name "<BastionName>" `
		--resource-group "<BastianResourceGroupName>" `
		--target-resource-id "<VMResourceId>" `
		--enable-mfa

### Errors

File "C: \Users\<User>\.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 112, in _get_auth_token
self. last_token = response_json["authToken"]
KeyError: "authToken'

### Issue script & Debug output

cli.azext_bastion.custom: Response eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSIsImtpZCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xODlhZTcwOC0xNWQ3LTQ0N2UtOTI3OC0zOGIxOWQzNzM5MGIvIiwiaWF0IjoxNzAyOTk5ODE4LCJuYmYiOjE3MDI5OTk4MTgsImV4cCI6MTcwMzAwNDIyOSwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhWQUFBQWxEcW5ZeXRoaDdyaStPR3FRbDFyREp1WkRuSkZWU2p0L3MwYlRxSDVxeGVDZXB2NTFodDNXWFFuU251c2FTeWIiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiY2Fwb2xpZHNfbGF0ZWJpbmQiOlsiYzBiZDA0ZGYtYWM4My00MGExLTg5YjEtMmQ3Yjk1YmE0YjdmIiwiMGEzYjg4YTEtMTczZC00NzNhLTk0MzQtNzUyZWZjZThmODI4Il0sImZhbWlseV9uYW1lIjoic3VwcG9ydDEiLCJnaXZlbl9uYW1lIjoiU1VQIC0gVE5QIiwiZ3JvdXBzIjpbImI4NTEwMjA0LTBmZTUtNGUwZC04NmIyLWJjMjQxMGNjMDMyYSIsImNhMWEzMTA2LTNjZWEtNDNlNy1iMGFjLTMxYWQ4NWM1YmUxMyIsIjQxNDYxNzA3LWQ2NWUtNDY4NS05Y2QzLTRlODA1NTIyYTc2MiIsIjI1Y2E3YzA3LTQxOTMtNDM3Mi1iMzA2LTg2Y2NlYTVhM2VhMCIsIjA5M2IyMjA5LTI0N2QtNDQ1MS05NGI0LTgwYmI1ZjA2ZTFmMSIsIjNlZmE0MjA5LTBiNGEtNDcxNy1iMWIxLTVkY2ZhZGI0ZDVmZiIsImQ2NTBjZjA5LTNlMGUtNGQ0ZC04ZWMyLWExMzI0ZDViMTUxMCIsIjE1ZmExMzBhLTFjODYtNGQ0OS04MWZiLWQ3NmFkZGZhNzVjOSIsIjliMzdjZTBmLWY5Y2ItNDgxNy05NzU3LTg5ZjJhZDc0NGJjZiIsImI2YWJjMzEyLWJmODAtNGZkYy1hMmNmLWY1MjQzMzA3NzRmMyIsIjg0NTdmNjE2LTRkNjYtNDBiNi1iOGI0LWFmODU3MGRhYzVkNSIsIjQ0MjIwMzE4LTBhZmMtNDkyNS1iMzdmLTQ0ZTUzMzBkZWUxZiIsImFkODYxMzE4LWZkNzYtNGRmOS1iNjg4LTI5NjczYWNmZTIyNCIsIjliYzEyMTE5LWZhMGQtNDY2Zi05YTlkLTE1M2IwZDk2OTNjMCIsImMzOTQ2NjE5LTk3NjYtNDE4MC04ZGQ5LWJiYzE1YTVhNGIzNiIsImM1M2IwNzFiLTE5MGYtNDE3OS04MTYwLTA2OTc5OWY0ZWFkNSIsImUzOWFjZDFlLTkzYjQtNGU4Zi05ODdiLTZjYzRkMjIwZjE4OSIsIjBlNzI0MDIwLWNmMWUtNDU5Zi05ZWQwLWEwNmUzZDRlMjBkMiIsIjY1N2RkNzIwLTUwOWEtNGVjOC1iNzg4LTAzZDk1ZDFlZWNlNyIsIjcyMmZmZDIyLTI1NzItNGEyMS04OTg1LTI2OWJmMDI3YzgxZSIsImZlNzA3OTI1LTVlMjgtNGRmYi1hMzY1LTJkOGY5MzQwNGEyZCIsIjEzZjE3ZjI1LTMzZGEtNDRjZS1hOTEwLTE0Y2VmOGJkNjBiNSIsImRhZjg1ZjI3LTA3YzAtNDIzMi1hM2RlLTdhZGYzN2FkYTkxMiIsIjAwYWE2NzI3LWE2NjctNDI5Yi1hOGYzLWFmMjk1ZDU2ODhiMyIsImIzODBmZTI4LTIxODMtNGNlYy1hMGEzLWNiNWRjYjE3MWVhMSIsIjI3MDQ0NzJiLTlmMWEtNDEzMS05OWJlLTY5NmQwMGNlMmI2OSIsIjgwZjZiODJkLTdmNjYtNGQ5Zi1iNGEwLThlM2NhOTJmNzA4YSIsIjdmNzg3OTJmLTU2OWItNDg1NC1iNTVjLWI5NTQyMzFhYTAxMyIsImUwMTBhNDM2LWU4NTktNDY5OC04YjZlLWE1Nzg3OTBhNDRhNCIsImM1YzliZTM5LWZmY2UtNDc2My05MzM3LTgyZjEwZWU2YTkwZCIsIjYwZjEyYzNhLWQ1NGItNDE1YS05MDhkLTc2ZDFiYzA4YThiNCIsIjg3MmY5ODNhLTVjY2ItNGE3NC05NzYyLTQ2M2ZjMzQ0ODAxMiIsImNiYmEyMjNlLTM3ZTEtNGRhOC04NDFmLTMxOTBiMWE0YThhZSIsIjQ0OGNkNzQxLTQzODgtNDIyYS04Mzc1LWY3ZTJkZjZkYTEyYSIsIjAyMzk0MTQzLTNlYjEtNDQ5My05ZDY3LWE2Zjc2ZTAxNWQ3NiIsIjMwNDQxNjRhLWY2MmEtNDZmYS1hMGE0LTg2NzRmYTQxNDc2NiIsImM2OWVhZTUwLTEwZjUtNDg4Mi1iMDVkLTg2MTE5MmE3MWMxMiIsIjVlOGRkMjU0LTYzMTEtNDA0Ni1iZGVmLWM5MDg3ZmUyYmY2OSIsIjNkZTE5NDU4LWVlNjktNDQ5Yy1iZjQwLTNjOWUxNzU5NjJiNyIsIjkyNWZhOTU4LTUzYWUtNDM0Yy05ZWQ2LTk3YjFmOGQ3ZGNkMyIsImMzNmVkNDVhLWJjYzctNDdkMi1hMmZkLTI0ZWY5NTY4NzBlZCIsIjM5OWI1ZTViLWE0YmItNDIwNy1iZjA2LTkxZTllMGNiMTAzYyIsImNiNTZiMTViLWU2NDktNDljYS05YjU4LTZhMmJmZjUyYzJlNiIsIjAzOGVhYzVkLTU0NzctNDY0Zi04YTliLWRjYjMyNTVjNDVhNyIsIjRkNTE4NDYwLWM4ZTYtNDJhZS05ZTFhLTFkZDBlZjhhMmE4ZiIsIjZmMTAzMzYxLWVkM2QtNDU1NS1hNjYzLWU4N2FiZDgzYjhhZSIsImNhOWRmYzYxLWI4MzQtNDIzOC1iYzU5LWU3MWU2YmYzZGEyZSIsIjlkODE3ODYyLWFhZTUtNGJkMS1iMmFlLTA0ZmUxODIyNmIwZSIsImI5NDA4YzYyLTA5YzAtNGVkOS1iN2FmLWM2YjhmMWUwYjA1YyIsImY4MGI3YzYzLTIxZjQtNDc1ZS04ZWU2LTEyZWI1MTZmYmEzNCIsImQ4NzhhZTY1LThhMWMtNDg5MC04YmYyLTNmZjAwOWU4ODAwNSIsIjY4NmEzMzY2LTgwNDMtNDI3MS1hNzNhLTBjYjBiODk3ODI1ZiIsIjA3ZTU5ZTZhLTY4NTUtNDc1ZC1hNzc4LTVhODY3MWE4MjY1NiIsIjEzMWIwMzZkLTIzYWItNGVjZC1hYTdhLWFkZGM2NDkyN2Q1OSIsIjI2M2UyYjczLWQyZTMtNGQ5OS04ZjBjLWY2MjhlNzAzNWQwZiIsIjA4MDMzNTczLThlMTMtNGU5Ni04ZmNkLTBiNTBkY2Q4OGM1YyIsImE5ZGRhYzczLWRiZmEtNGJiMi1iNjgxLTI3M2I1NWY0YmYyNCIsIjU2OTNjYjc0LTZlZDktNDk2ZC05NGEyLTA2MTAxMTdhMjA5OCIsImQyY2YxZjc1LWNjNjMtNDI1OC04YTY2LTEyNWQyOWJhNDE3OSIsIjQ2NjkwZDc5LWM4YWQtNGI1Zi05NDc2LTkzMTk4N2FlYjRhNSIsImUxYjZkYzc5LWM4YjAtNDA2NS1iZThhLWVhZWI1OGQyYWYyMyIsIjgxOGQ0ODdhLTYwZGQtNDlkMy04OWY4LTEwNGQ3Y2Q0ODQyNSIsImIzMDAxNzdkLWU2ZTAtNDkwZS04NjRmLWIwZmRiYzQ0NDUzMCIsImI1ODUyMDdlLTczZTQtNDZlZC04YmFjLTU0MTE5Yjk1YTY3NSIsIjhjYzU2NTgxLTgyNTItNGZjNC1hM2JjLWNlNzJmN2I4ZGNmZCIsImRhYzI5ZDg0LTEyNWUtNGQwNi05NjIyLWU3OTgxOTFhOWY0MiIsIjNmY2Q1MDg3LTBiZjEtNDUwNy1iNTdkLTJiZDZkOGIxMTg3ZSIsImYyZDBkODg4LTkwNzMtNDc5Mi1iMmYxLTQzNDEzNWE5NDZjYiIsIjBlMGM5MzhiLTFmMDctNDNhOS05YjVkLWZiNTVjMDhmODAxMyIsIjE4YTRmYzkwLWI4OGMtNDc3OS1hNjQwLWE5ZDcyYjkxOTU3YSIsImJhZTUwYjkyLTM0OTgtNDk1My1hNTRkLTVjNjliMzU4MDNhOSIsIjViZWMzOTk3LTllYWEtNDg0Mi04MjVkLTVkZTdmODRmYWFmZCIsImFkNjIxYjk5LWFlZDAtNGQxNC05N2U4LWRjNGE3OGJkMWUzMCIsIjcxYzY4NDk5LWMyZmItNDJjZS05YWYxLWFiYTFiODk1MzNjMiIsImZiMzIzMzliLWEyNTMtNDBlMy1hN2EzLWY2ZjUzY2VlOTNlYyIsImVhZDVhOTllLTZmMTUtNGZlNS1iNWFhLWRmOGRkNjUzNDVmMyIsImVhZjhlMDllLTlkMTYtNGZkNi1hNjEyLThlZDRlNDYwNmVmMCIsIjlkODM2NWExLTU1NzMtNDQzZi04MzM0LWJkMjY3MmMwZWQ3NiIsIjRjNjZjOGExLWFmNjAtNDQyMy1iYTQ3LWMyYmJlMjExNmU2MSIsImVlNGY5OGEyLTMyNjgtNDNlZC1iNDNhLWIwNzU0MzA1NjhlOSIsIjBmYjg4OGE3LWExNDMtNGZmYS1hMTFlLTU3YzQyMDBlMjVmNyIsIjI2N2QzZmE4LWIxMmUtNGQ1Mi04OTU4LTIyNzVkNDBkYmU4ZSIsIjBiOGI4MGE4LWU2OGUtNDdlZi1iNWY2LTI3NTZiNGYzMzVkNSIsImUxYjczMmFjLWQwZDItNGJiZS1hYTdiLTJmYzQxNjIxNmQ1OSIsIjg2M2UyY2FkLWZhNTEtNDNkYS1hYmY0LWRjMGM0NjI2ZjQyNiIsIjQwYjgzYmFkLWVjNjgtNGMzYy05NTE1LWNkNGVhYzQ4OWQ4NCIsIjA1YTUwZmFlLWE4NjktNGU1OS1iMTY1LWMwOGNiYTY5ODYzMiIsIjcwNDQyYWIwLWUxZjItNDEzZS1iM2EzLTQzNGYxYmFmYjY4ZCIsImRmYzAwYWIyLTZhYzQtNGRiOC1iYzkyLWI3OTkyZDk2NGVmZCIsImNiZTYxNWIzLTU3NjYtNDZhNy1hNjUxLTliNWZkZWYwMmQ4YSIsImE1MDUwNGI0LWY0NWMtNDM4NC05MTVjLTQwY2IxMTYxOTBmNSIsImM0MjY2MGI0LWZiMDgtNGQ3MC1iNmUwLTYxYTIwMWU2N2M3NyIsImEwZmVhNmI0LWFiM2QtNGIzMS05MDRmLTc2N2YyMTA3MDkwNCIsIjA5YTE0YWI1LTVjM2ItNDhjZC05NWQ2LTg1MDRlMTA1ODRkYSIsIjFlOGIyNGJiLTYxNDAtNGQ0Zi1iMmRmLTg0Y2EyMDdhNmE4OCIsIjQ4MzNmNGJiLTZiNjQtNDJmOC1hM2NjLWQ1OWZmYWJmYzQ3ZiIsIjlhZWE3NmJjLWE4ZGEtNDVmOC05NWVkLTNmYWU5OGY2NjBiZSIsImVjNmVmYmJmLTg2NDgtNDA1Yi1hOWY3LWIwNDg5NjRiMTM5MCIsImZhNDNlM2MyLWZkNWItNDgzNi05ODdlLTFjMjRhYzI1ZjMzNCIsImEyZjU4NWNhLTBhMTItNDQ5Yi04Njk0LTNiNjlhOTJmNzRiNSIsImY3N2Y3MGNlLTlmZGItNGQyNy05MWI2LWVmOWI0YzVkOWEyYiIsIjU4ODI3NWQxLTc2NGEtNDg2OC1hNjYxLTc4ZDlhMDM2ZDlkNyIsImYzOThmMmQ0LTZkNWItNGQwZS1iZThhLTQyZTU1ODcxY2UzNyIsIjU2NzBlN2Q2LWI1MmMtNGJlNy1hYThiLWVkMjMxMjQyZDg5ZCIsIjc1YTNmYmRjLWM3MWUtNGY0NC04YzdiLTQzZDljYTVjNGQ3MCIsIjQyZjI5ZmUxLThmN2MtNGU1Ni04MGMzLTgwMDFjY2QzMTQwMiIsIjdmMWRjZmU4LTMzZDYtNGZjNC05Y2YwLWFhNWJkZDE3OTU3MiIsImZiMDIzMWVlLTU1NGQtNDAxNy1hZjFiLTFlNWM4MGI3NmVmNSIsIjYzYzU0Y2VmLTBmNTctNDdkZi04ODIwLWE2OTNiMjRlYTE5NCIsIjYxNjZmYmYwLWFhYzQtNDlmYy05ZDRjLTM2YzQ0ODZjN2ZkOCIsIjg4MzFkYWYxLTJiMWYtNGYxZS1iMjExLWI1OGJhOTlhMDQ1MCIsImEzYzliNmYyLTFmNTYtNDAwMC1hYWU0LWEyNzNkMGRiZThjZCIsIjViNGU2N2Y1LWVkYWUtNDU4Ny05MGU0LTYwNjE1YWEzYmQ4NiIsIjFiYTVmOWY5LTMwYTItNGI2Yy1iMDRjLTg1MWQwMjQ5OTEzZSIsIjk3ZjE0Y2ZiLWJhYTAtNDVjMy1hZWMyLTFjMWE5NzUxMzc0YyIsIjA2N2Q0YmZlLWZhODItNDY3NC1iNDYyLWNiMWFmYTEzMGM5YSJdLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMTIuMTg4LjE2MC4xODAiLCJuYW1lIjoiU1VQIC0gVE5QIHN1cHBvcnQxIiwib2lkIjoiOWM2MGUyZmQtOTI0OS00ODYxLWFiODctMmFiMTM0OTYxMjQ3Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTE4NzUzNjg5ODYtNDAzOTM4MjE3OS0xOTA3MDQwMzMyLTU4NzI1IiwicHVpZCI6IjEwMDMyMDAwQUQwQTYyNDciLCJyaCI6IjAuQVRBQUNPZWFHTmNWZmtTU2VEaXhuVGM1QzBaSWYza0F1dGRQdWtQYXdmajJNQk13QUNJLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IkR2VW1FQ2RhODl3VVFHUmdLVzY2bDdFVVh5VzRCOUlCYTdhQXJlRkFXZzAiLCJ0aWQiOiIxODlhZTcwOC0xNWQ3LTQ0N2UtOTI3OC0zOGIxOWQzNzM5MGIiLCJ1bmlxdWVfbmFtZSI6InN1cC50bnBzdXBwb3J0MUBub3JkYW5nbGlhLmNvbSIsInVwbiI6InN1cC50bnBzdXBwb3J0MUBub3JkYW5nbGlhLmNvbSIsInV0aSI6ImtEbFRzOWxkMGtPUEVQNTNyLWQzQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc19jYyI6WyJDUDEiXSwieG1zX2ZpbHRlcl9pbmRleCI6WyI0OCJdLCJ4bXNfcmQiOiIwLjQyTGxZQlJpTkFBQSIsInhtc19zc20iOiIxIiwieG1zX3RjZHQiOjE1Mzc0NDgyNjl9.hv1QXEW1Vm2_C2p3X9Y4wxpyyCGUTDyHMPKgdUxAMPx4kgJL3ZrOtn47SqYPG1ywvwc4StRXdWxzrVRP_IUMcnBcc51wTYexCbGZk_FNBAjRS9ox_qXA-RorNQ_cZcURpJ_YU5u5SCVyEG2LVJrYDSpWFQPImLd0zfZ_iv4jw4UvcKnyJcJLPtsaA1_pKYtev1LrAuFLjr-A-xUZLrLWOqh8kTa01_az095e6sYAyG6yRHJ834KeyAoYLJ5Tl4Gs_6xGnjZ9L_Q3U0_XoW7KxhefgBrfQf1SVb60AUPUIbELF9iX58X3ctGnMYeN6w-TxPSrVmUJ8JRjfKixmwO9UQ
urllib3.connectionpool: Starting new HTTPS connection (1): <bastionHost>.bastion.azure.com:443
urllib3.connectionpool: https://<bastionHost>.bastion.azure.com:443 "GET /api/rdpfile?resourceId=/subscriptions/<subscriptionid>/resourceGroups/<resourceGroup>/providers/Microsoft.Compute/virtualMachines/<vmName>&format=rdp&rdpport=3389&enablerdsaad=True HTTP/1.1" 400 435
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\<User>\.azure\cliextensions\bastion\azext_bastion\custom.py", line 304, in rdp_bastion_host
    errorMessage = json.loads(response.content).get('message', None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Expected behavior

Response token should be well formed

### Environment Summary

azure-cli 2.57.0
bastion extension 0.3.0

Windows 11

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
