### ISSUE TITLE
Exception raised when executing any Azure CLI command after upgrading to version 2.57.

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#28312]
### Describe the bug

After upgrading to Azure CLI, version 2.57, when executing any command, I receive the following error message:

Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 62, in <module>
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 55, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
    show_secrets_warning = _get_config().getboolean('clients', 'show_secrets_warning', fallback=None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/config.py", line 147, in getboolean
    raise ValueError('Not a boolean: {}'.format(val))
ValueError: Not a boolean: None

Commands seem to execute successfully (I could list/deallocate/start virtual machines, manage virtual networks, etc.). The issue occurs on different platforms: I tested on Ubuntu Linux server ver.22.04, Mac OS Sonoma (on Apple Silicon), WSL on Windows Server 2022 Enterprise Azure Edition, command window on Windows Server 2022 Enterprise Azure Edition).

### Related command

Examples:

az vm list --subscription SUB-DEVANDTEST --verbose -o table
az network vnet subnet list --subscription SUB-DEVANDTEST --verbose -o table -g RG_BAGVIRTUALNETWORKS --vnet-name BAGVIRTUALNETWORK

The issue appears with almost every Azure CLI command.

### Errors

Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 62, in <module>
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 55, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
    show_secrets_warning = _get_config().getboolean('clients', 'show_secrets_warning', fallback=None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/config.py", line 147, in getboolean
    raise ValueError('Not a boolean: {}'.format(val))
ValueError: Not a boolean: None

### Issue script & Debug output

Output with --debug option is much too long to enter in here - can be shared in a separate e-mail message if required.

### Expected behavior

Expecting Azure CLI statements to execute successfully without raising an exception.

### Environment Summary

{
  "azure-cli": "2.57.0",
  "azure-cli-core": "2.57.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Please run `az config set clients.show_secrets_warning=False` as a workaround.

I'll look into this issue ASAP! Thanks for reporting!

**Comment by evelyn-ys** [comment]
Hi @ptsapralis, This is a exception traceback of suppressed exception. Your CLI command won't be affected and will successfully return as expected.

This is a small issue on collecting telemetry and we will fix in next version
