### ISSUE TITLE
"az aks get-credentials" intermittent timeout failures

### ISSUE THREAD

**Issue by mdhomer** [Azure/azure-cli#28334]
### Describe the bug

We run `az aks get-credentials -n developmentuk-a-aks -g developmentuk --overwrite-existing` within CI pipelines to connect via AD to our kubernetes clusters.

We see intermittent errors with this command, when the underlying library makes calls to:
```
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: '[https://management.azure.com/subscriptions/<SUBID>/resourceGroups/developmentuk/providers/Microsoft.ContainerService/managedClusters/developmentuk-a-aks/listClusterUserCredential?api-version=2023-11-01'](https://management.azure.com/subscriptions/<SUBID>/resourceGroups/developmentuk/providers/Microsoft.ContainerService/managedClusters/developmentuk-a-aks/listClusterUserCredential?api-version=2023-11-01%27)
...
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
...
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

It looks like this fails after 2 min 23 seconds based on the CI log timestamps:
```
2024-02-08T09:19:57.8875061Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
2024-02-08T09:22:20.0132733Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
```

We see these failures across vnets and different clusters, on an intermittent basis. Without much consistency in time or occurence.

### Related command

az aks get-credentials

### Errors

```
ERROR: cli.azure.cli.core.azclierror: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
ERROR: az_command_data_logger: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### Issue script & Debug output

```
2024-02-08T09:19:57.8796799Z DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBID>/resourceGroups/developmentuk/providers/Microsoft.ContainerService/managedClusters/developmentuk-a-aks/listClusterUserCredential?api-version=2023-11-01'
2024-02-08T09:19:57.8802881Z DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'POST'
2024-02-08T09:19:57.8808361Z DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
2024-02-08T09:19:57.8814491Z DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
2024-02-08T09:19:57.8820237Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '<REQ_ID'
2024-02-08T09:19:57.8825897Z DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'aks get-credentials'
2024-02-08T09:19:57.8828678Z DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -g --overwrite-existing --debug'
2024-02-08T09:19:57.8833237Z DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.57.0 (DEB) azsdk-python-azure-mgmt-containerservice/29.0.0 Python/3.11.7 (Linux-5.15.0-1054-azure-x86_64-with-glibc2.31) VSTS_5f18aba7-159b-4c4d-8f85-2bed8b2c087f_build_440_0'
2024-02-08T09:19:57.8837627Z DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
2024-02-08T09:19:57.8841410Z DEBUG: cli.azure.cli.core.sdk.policies: Request body:
2024-02-08T09:19:57.8845036Z DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
2024-02-08T09:19:57.8875061Z DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
2024-02-08T09:22:20.0132733Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
2024-02-08T09:22:20.0134406Z   File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
2024-02-08T09:22:20.0179042Z     cmd_result = self.invocation.execute(args)
2024-02-08T09:22:20.0179857Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0180480Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
2024-02-08T09:22:20.0180821Z     raise ex
2024-02-08T09:22:20.0181311Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 729, in _run_jobs_serially
2024-02-08T09:22:20.0181698Z     results.append(self._run_job(expanded_arg, cmd_copy))
2024-02-08T09:22:20.0181991Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0182462Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 698, in _run_job
2024-02-08T09:22:20.0182806Z     result = cmd_copy(params)
2024-02-08T09:22:20.0183063Z              ^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0183508Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
2024-02-08T09:22:20.0183856Z     return self.handler(*args, **kwargs)
2024-02-08T09:22:20.0184123Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0184582Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2024-02-08T09:22:20.0184930Z     return op(**command_args)
2024-02-08T09:22:20.0185189Z            ^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0185661Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/acs/custom.py", line 1343, in aks_get_credentials
2024-02-08T09:22:20.0189444Z     credentialResults = client.list_cluster_user_credentials(
2024-02-08T09:22:20.0190007Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0190499Z   File "/opt/az/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
2024-02-08T09:22:20.0190852Z     return func(*args, **kwargs)
2024-02-08T09:22:20.0191112Z            ^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0191685Z   File "/opt/az/lib/python3.11/site-packages/azure/mgmt/containerservice/v2023_11_01/operations/_managed_clusters_operations.py", line 1696, in list_cluster_user_credentials
2024-02-08T09:22:20.0192405Z     pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
2024-02-08T09:22:20.0192763Z                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0193209Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 213, in run
2024-02-08T09:22:20.0193557Z     return first_node.send(pipeline_request)
2024-02-08T09:22:20.0193837Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0194266Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0194735Z     response = self.next.send(request)
2024-02-08T09:22:20.0195005Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0195436Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0195774Z     response = self.next.send(request)
2024-02-08T09:22:20.0196036Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0196460Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0209804Z     response = self.next.send(request)
2024-02-08T09:22:20.0210364Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0210645Z   [Previous line repeated 2 more times]
2024-02-08T09:22:20.0211185Z   File "/opt/az/lib/python3.11/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
2024-02-08T09:22:20.0211544Z     response = self.next.send(request)
2024-02-08T09:22:20.0211872Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0212450Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_redirect.py", line 181, in send
2024-02-08T09:22:20.0212836Z     response = self.next.send(request)
2024-02-08T09:22:20.0213104Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0213810Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 489, in send
2024-02-08T09:22:20.0214154Z     raise err
2024-02-08T09:22:20.0214605Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
2024-02-08T09:22:20.0214965Z     response = self.next.send(request)
2024-02-08T09:22:20.0215234Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0215697Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_authentication.py", line 115, in send
2024-02-08T09:22:20.0216058Z     response = self.next.send(request)
2024-02-08T09:22:20.0216322Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0216751Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0217092Z     response = self.next.send(request)
2024-02-08T09:22:20.0217358Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0217771Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0218107Z     response = self.next.send(request)
2024-02-08T09:22:20.0218369Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0218798Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
2024-02-08T09:22:20.0219343Z     response = self.next.send(request)
2024-02-08T09:22:20.0219839Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0220284Z   [Previous line repeated 2 more times]
2024-02-08T09:22:20.0221332Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 108, in send
2024-02-08T09:22:20.0221839Z     self._sender.send(request.http_request, **request.context.options),
2024-02-08T09:22:20.0222152Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.0222632Z   File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 376, in send
2024-02-08T09:22:20.0222972Z     raise error
2024-02-08T09:22:20.0223489Z azure.core.exceptions.ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-08T09:22:20.0223759Z 
2024-02-08T09:22:20.0293798Z ERROR: cli.azure.cli.core.azclierror: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-08T09:22:20.0302292Z ERROR: az_command_data_logger: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-02-08T09:22:20.0308728Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fed9ac15b20>]
2024-02-08T09:22:20.0315465Z INFO: az_command_data_logger: exit code: 1
2024-02-08T09:22:20.0321382Z INFO: cli.__main__: Command ran in 142.661 seconds (init: 0.199, invoke: 142.461)
2024-02-08T09:22:20.0954222Z INFO: cli.azure.cli.core.decorators: Suppress exception:
2024-02-08T09:22:20.0955482Z Traceback (most recent call last):
2024-02-08T09:22:20.0956535Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 62, in <module>
2024-02-08T09:22:20.1034714Z     raise ex
2024-02-08T09:22:20.1035624Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 55, in <module>
2024-02-08T09:22:20.1036258Z     sys.exit(exit_code)
2024-02-08T09:22:20.1036511Z SystemExit: 1
2024-02-08T09:22:20.1036686Z 
2024-02-08T09:22:20.1036974Z During handling of the above exception, another exception occurred:
2024-02-08T09:22:20.1037283Z 
2024-02-08T09:22:20.1037544Z Traceback (most recent call last):
2024-02-08T09:22:20.1038030Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
2024-02-08T09:22:20.1038380Z     return func(*args, **kwargs)
2024-02-08T09:22:20.1038641Z            ^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.1039110Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
2024-02-08T09:22:20.1039652Z     show_secrets_warning = _get_config().getboolean('clients', 'show_secrets_warning', fallback=None)
2024-02-08T09:22:20.1040060Z                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-08T09:22:20.1040520Z   File "/opt/az/lib/python3.11/site-packages/knack/config.py", line 147, in getboolean
2024-02-08T09:22:20.1040954Z     raise ValueError('Not a boolean: {}'.format(val))
2024-02-08T09:22:20.1041256Z ValueError: Not a boolean: None
```

### Expected behavior

The urllib3 library allows for retry logic to be handled for the HTTPS api call, i'm not sure the 2min+ timeout is also considering retries? 

Or what circumstances could cause the command to fail consistently for this long

Could we make a change to leverage this?

### Environment Summary

```
/usr/bin/az --version
azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/AzDevOps/.azure/cliextensions'

Python (Linux) 3.11.7 (main, Jan 31 2024, 05:30:12) [GCC 9.4.0]
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FumingZhang** [comment]
Hey @mdhomer, from my understanding, the default timeout is [300s](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/configuration.py#L137-L138). In your case, the error the request eventually encountered was not the timeout, but `azure.core.exceptions.ServiceResponseError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`, which seems to be a server-side error.

In addition, judging from the log you provided, the client also retried at least once. [Here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/azure/core/pipeline/policies/_retry.py#L77-L84)'s the default configuration of retry used by the SDK.
