### ISSUE TITLE
az containerapp up fails with: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by yves-chan** [Azure/azure-cli#28346]
### Describe the bug

Az containerapp up command is failing with  TypeError: argument of type 'NoneType' is not iterable

### Related command

/usr/local/bin/az containerapp up -n genevabuddytest-fpa -g grafanaEmbedding -i <registry>.azurecr.io/genevabuddytest:1.2.0-buddy.108 --registry-server <registry>.azurecr.io --registry-username <registry> --registry-password *** --env-vars GFAZPL_USER_IDENTITY_ENABLED=true GFAZPL_USER_IDENTITY_CLIENT_ID=*** GFAZPL_USER_IDENTITY_CLIENT_SECRET=*** GFAZPL_USER_IDENTITY_TOKEN_URL=https://authproxytest.blackisland-51b08931.westus3.azurecontainerapps.io/oauth2/v2.0/token GFAZPL_USER_IDENTITY_ASSERTION=username --ingress external --target-port 3000

### Errors

WARNING: Using resource group 'grafanaEmbedding'
WARNING: Using ContainerAppEnvironment 'authproxytest-env' in resource group grafanaEmbedding
WARNING: Updating Containerapp genevabuddytest-fpa in resource group grafanaEmbedding
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/containerapp/custom.py", line 3612, in containerapp_up
##[error]Error Code: [1]
##[error]Error: Unable to update Azure Container App via 'az containerapp update' command.
    app.create(no_registry=bool(repo))
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/containerapp/_up_utils.py", line 392, in create
    return containerapp_up_logic(
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/containerapp/custom.py", line 3632, in containerapp_up_logic
    return update_containerapp_logic(cmd=cmd, name=name, resource_group_name=resource_group_name, image=image, replace_env_vars=env_vars, ingress=ingress, target_port=target_port,
  File "/usr/local/lib/python3.8/site-packages/azure/cli/command_modules/containerapp/custom.py", line 387, in update_containerapp_logic
    if "properties" in containerapp_def and "template" in containerapp_def["properties"] and "containers" in containerapp_def["properties"]["template"]:
TypeError: argument of type 'NoneType' is not iterable

### Issue script & Debug output

I can attach if needed

### Expected behavior

Able to deploy containerapp

### Environment Summary

{
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "amg": "1.2.9"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.58.0
The fix has been released from azure-cli version `2.58.0`.
