### ISSUE TITLE
URI '<MS_URI>' does not support the API version '2023-12-01' in `az resource delete` command

### ISSUE THREAD

**Issue by kislow** [Azure/azure-cli#28392]
### Describe the bug

When attempting to delete resource-type `microsoft.insights/scheduledqueryrules`  resource fails to be deleted.
 
`Code: UnsupportedApiVersion`

`The HTTP resource that matches the request URI 'https://lsa-westeurope-prod.alertsrp.trafficmanager.net/subscriptions/<SUB_ID>/resourcegroups/<RG_NAME>/providers/microsoft.insights/scheduledqueryrules/<NAME>' does not support the API version '2023-12-01'.` 

### Related command

`az resource delete`

### Errors

```
 ❯ az resource delete --resource-group <RG_NAME> --name <NAME> --resource-type microsoft.insights/scheduledqueryrules
Some resources failed to be deleted (run with `--verbose` for more information):
/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>
```

### Issue script & Debug output
```sh
 ❯ az resource delete --resource-group <RG_NAME> --name <QUERY_NAME> --resource-type microsoft.insights/scheduledqueryrules --verbose

(UnsupportedApiVersion) The HTTP resource that matches the request URI 'https://lsa-westeurope-prod.alertsrp.trafficmanager.net/subscriptions/<SUB_ID>/resourcegroups/<RG_NAME>/providers/microsoft.insights/scheduledqueryrules/<QUERY_NAME>' does not support the API version '2023-12-01'.

Code: UnsupportedApiVersion

Message: The HTTP resource that matches the request URI 'https://lsa-westeurope-prod.alertsrp.trafficmanager.net/subscriptions/<SUB_ID>/resourcegroups/<RG_NAME>/providers/microsoft.insights/scheduledqueryrules/<QUERY_NAME>'' does not support the API version '2023-12-01'.

Some resources failed to be deleted (run with `--verbose` for more information):
/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>
Command ran in 1.889 seconds (init: 0.101, invoke: 1.788)
Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 62, in <module>
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 55, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
    show_secrets_warning = _get_config().getboolean('clients', 'show_secrets_warning', fallback=None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/config.py", line 147, in getboolean
    raise ValueError('Not a boolean: {}'.format(val))
ValueError: Not a boolean: None
```
### Expected behavior

The resource should be deleted

### Environment Summary

```sh
az --version
azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0
bastion                            0.3.0
blueprint                          0.3.2

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/islowk/.azure/cliextensions'

Python (Linux) 3.11.7 (main, Jan 31 2024, 05:29:49) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Additional context

Successfully authorised to execute the commands in subscription.

```sh
az login --tenant <TENANT_ID>
az account set --subscription SUB_ID
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nirenbhardwaj** [comment]
I am facing the similar issue. While querying the role assignments for scheduledQueryRules.

Is there any update on this?

**Comment by kislow** [comment]
### Additional info:

The API version doesn't exist according to the documentation:
<img width="447" alt="Screenshot 2024-02-20 at 10 05 08" src="https://github.com/Azure/azure-cli/assets/33865204/0d906460-f997-4615-9cb7-aeff338cee10">

In Azure resource version 2023-12-01 for the specified resource type seems to be available?

![Screenshot 2024-02-20 at 10 07 46](https://github.com/Azure/azure-cli/assets/33865204/81348216-2921-4dea-903d-4bcc4fd0f159)

**Comment by bowlerma** [comment]
We're seeing the same problem trying to use `az resource update` to disable some alerts and receiving the following errors:

`az resource update --ids $alertObj.id --set properties.enabled=$false`

```
2024-02-20T18:05:14.6325805Z ERROR: (UnsupportedApiVersion) The HTTP resource that matches the request URI 'https://lsa-uksouth-prod.alertsrp.trafficmanager.net/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Insights/scheduledqueryrules/<redacted>' does not support the API version '2023-12-01'.
2024-02-20T18:05:14.6326912Z Code: UnsupportedApiVersion
2024-02-20T18:05:14.6327616Z Message: The HTTP resource that matches the request URI 'https://lsa-uksouth-prod.alertsrp.trafficmanager.net/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Insights/scheduledqueryrules/<redacted>' does not support the API version '2023-12-01'.
2024-02-20T18:05:14.7778340Z Disabling alert: <redacted>
2024-02-20T18:05:15.8419382Z ERROR: argument --ids: expected at least one argument
2024-02-20T18:05:15.8419796Z 
2024-02-20T18:05:15.8420157Z Examples from AI knowledge base:
2024-02-20T18:05:15.8420665Z az resource update --ids /subscriptions/{SubID}/resourceGroups/{ResourceGroup}/providers/Microsoft.Web/sites/{WebApp} --set tags.key=value
2024-02-20T18:05:15.8421133Z Update a webapp. (autogenerated)
2024-02-20T18:05:15.8421304Z 
2024-02-20T18:05:15.8421771Z az resource update --ids /subscriptions/{SubID}/resourceGroups/{ResourceGroup}/providers/Microsoft.Web/sites/{WebApp} --set tags.key=value --latest-include-preview
2024-02-20T18:05:15.8422313Z Update a webapp by using the latest api-version whether this version is a preview version.
2024-02-20T18:05:15.8422549Z 
2024-02-20T18:05:15.8422921Z https://docs.microsoft.com/en-US/cli/azure/resource#az_resource_update
2024-02-20T18:05:15.8423335Z Read more about the command in reference docs
```

**Comment by bowlerma** [comment]
Looks like Microsoft may have acknowledged and mitigated the issue now.  Unfortunately, not had a chance to retest yet.

https://app.azure.com/h/JLNQ-39Z/e9b996

> Status
Resolved
Health Event Type
Service Issue
Start time
20/02/2024 14:50:15 (1 day ago)
End Time
20/02/2024 23:57:41 (16 hours ago)
Last update
Summary of Impact: Between 19:35 UTC on 12 Feb 2024 and 23:15 UTC on 21 Feb 2024, you were identified as a customer using Log Search Alerts who may have experienced issues with management operations: listing, viewing and updating alert rules. Some requests to the Log Search Alerts service may have been rejected with a 400-error code with the message "Unsupported API version". This was limited to specific API version "2023-12-01", it occurred when the API version was not specified in the request as some tools default to it. 
> 
> Preliminary Root Cause: We identified that this was caused by a recent update, which introduced a configuration change to the control plane. This change caused problems in our underlying infrastructure, manifesting in the issues with management operations and 400-error codes experienced by customers.
> 
> Mitigation: This issue was detected when a customer initiated request failed. We mitigated by rolling back to a previous, known good build, which brought our resources to a healthy state. Further monitoring of our telemetry confirms that the errors are no longer occurring, and this issue is mitigated.
> 
> Next Steps: We will continue to investigate to establish the full root cause and prevent future occurrence. Stay informed about Azure service issues by creating custom service health alerts: https://aka.ms/ash-videos for video tutorials and https://aka.ms/ash-alerts for how-to documentation.
