### ISSUE TITLE
ValueError on Pip Installation with Old Version of Pip

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#2842]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

---

### Description

sudo apt-get upgrade python
sudo apt-get upgrade gcc
sudo apt-get install -y libssl-dev libffi-dev python-dev
curl -L https://aka.ms/InstallAzureCli | bash
pip install –user –upgrade –pre azure-cli-shell
 
Which then returns an error:
 
Cleaning up...
  Removing temporary dir /tmp/pip_build_johnmont...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'azure-common ~=1.1.4', 'at', ' ~=1.1.4')

**Comment by derekbekoe** [comment]
`sudo apt-get install pip` gives you an old version of pip (1.x).
The current latest is 9.x.
Solution is to upgrade pip.
```
sudo apt-get purge python-pip
curl  https://bootstrap.pypa.io/get-pip.py | sudo python
```
