### ISSUE TITLE
Not able to download latest 1.0.0 

### ISSUE THREAD

**Issue by jontreynes** [Azure/azure-cli#28442]
### Describe the bug

I am not able to download the Azure DevOps CLI 1.0.0 extension

### Related command

az extension update --name azure-devops

### Errors

~> az extension add --name azure-devops
Extension 'azure-devops' 0.26.0 is already installed.
~> az extension update --name azure-devops
Latest version of 'azure-devops' is already installed.

Use --debug for more information
~> az extension add --name azure-devops --version 1.0.0
Version '1.0.0' not found for extension 'azure-devops'

Use --debug for more information

### Issue script & Debug output

```
~> az extension add --name azure-devops --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'azure-devops', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01E4B460>, <function OutputProducer.on_global_arguments at 0x02018BF8>, <function CLIQuery.on_global_arguments at 0x0203A850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.006         1         7
cli.azure.cli.core: Total (1)                 0.006         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0423B388>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\joreynes\.azure\commands\2024-02-22.15-13-55.extension_add.28988.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04287850>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04287A00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04287A90>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02018C40>, <function CLIQuery.handle_query_parameter at 0x0203A898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04287A48>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 3700941
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://github.com/Azure/azure-devops-cli-extension/releases/download/20230127.2/azure_devops-0.26.0-py2.py3-none-any.whl', 'filename': 'azure_devops-0.26.0-py2.py3-none-any.whl', 'metadata': {'azext.minCliCoreVersion': '2.30.0', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'VSTS_Social@microsoft.com', 'name': 'Microsoft', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Microsoft/azure-devops-cli-extension'}}}, 'extras': [], 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'azure-devops', 'run_requires': [{'requires': ['distro (==1.3.0)']}], 'summary': 'Tools for managing Azure DevOps.', 'version': '0.26.0'}, 'sha256Digest': '565fc207f1740c26957f382fe2eefabec254011fb2d1b50c0e540f894f47dcbe'}
cli.azure.cli.core.extension.operations: Extension 'azure-devops' 0.26.0 is already installed.
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x04260BB0>, <function _x509_from_base64_to_hex_transform at 0x04260BF8>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0423B4A8>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 2.688 seconds (init: 0.602, invoke: 2.087)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3391 in cache
telemetry.check: Negative: The C:\Users\joreynes\.azure\telemetry.txt was modified at 2024-02-22 15:10:25.883799, which in less than 600.000000 s
~> az extension update --name azure-devops --debug
cli.knack.cli: Command arguments: ['extension', 'update', '--name', 'azure-devops', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01ABB460>, <function OutputProducer.on_global_arguments at 0x01B88BF8>, <function CLIQuery.on_global_arguments at 0x01BAA850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.005         1         7
cli.azure.cli.core: Total (1)                 0.005         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension update
cli.azure.cli.core: Command table: extension update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03EAB388>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\joreynes\.azure\commands\2024-02-22.15-14-12.extension_update.37068.log'.
az_command_data_logger: command args: extension update --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03EF7850>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03EF7A00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03EF7A90>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01B88C40>, <function CLIQuery.handle_query_parameter at 0x01BAA898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03EF7A48>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 3700941
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Skipping 'azure_devops-0.12.0-py2.py3-none-any.whl' as 0.12.0 not greater than current version 0.26.0
cli.azure.cli.core.extension._resolve: Skipping 'azure_devops-0.17.0-py2.py3-none-any.whl' as 0.17.0 not greater than current version 0.26.0
cli.azure.cli.core.extension._resolve: Skipping 'azure_devops-0.21.0-py2.py3-none-any.whl' as 0.21.0 not greater than current version 0.26.0
cli.azure.cli.core.extension._resolve: Skipping 'azure_devops-0.26.0-py2.py3-none-any.whl' as 0.26.0 not greater than current version 0.26.0
cli.azure.cli.core.extension.operations: Latest version of 'azure-devops' is already installed.
cli.azure.cli.core.extension.operations: Latest version of 'azure-devops' is already installed.

Use --debug for more information
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03ED0BB0>, <function _x509_from_base64_to_hex_transform at 0x03ED0BF8>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03EAB4A8>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 2.892 seconds (init: 0.587, invoke: 2.305)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3320 in cache
telemetry.check: Negative: The C:\Users\joreynes\.azure\telemetry.txt was modified at 2024-02-22 15:10:25.883799, which in less than 600.000000 s
~> az extension add --name azure-devops --version 1.0.0 --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'azure-devops', '--version', '1.0.0', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x021CB460>, <function OutputProducer.on_global_arguments at 0x02298BF8>, <function CLIQuery.on_global_arguments at 0x022B9850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.006         1         7
cli.azure.cli.core: Total (1)                 0.006         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x045BB388>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\joreynes\.azure\commands\2024-02-22.15-14-25.extension_add.24372.log'.
az_command_data_logger: command args: extension add --name {} --version {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04608850>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04608A00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04608A90>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02298C40>, <function CLIQuery.handle_query_parameter at 0x022B9898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04608A48>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 3700941
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_devops-0.12.0-py2.py3-none-any.whl', 'azure_devops-0.17.0-py2.py3-none-any.whl', 'azure_devops-0.21.0-py2.py3-none-any.whl', 'azure_devops-0.26.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension.operations: Version '1.0.0' not found for extension 'azure-devops'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 318, in add_extension
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/_resolve.py", line 149, in resolve_from_index
azure.cli.core.extension._resolve.NoExtensionCandidatesError: Version '1.0.0' not found for extension 'azure-devops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 322, in add_extension
knack.util.CLIError: Version '1.0.0' not found for extension 'azure-devops'

Use --debug for more information

cli.azure.cli.core.azclierror: Version '1.0.0' not found for extension 'azure-devops'

Use --debug for more information
az_command_data_logger: Version '1.0.0' not found for extension 'azure-devops'

Use --debug for more information
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x045BB4A8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.666 seconds (init: 0.601, invoke: 2.065)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3478 in cache
telemetry.check: Negative: The C:\Users\joreynes\.azure\telemetry.txt was modified at 2024-02-22 15:10:25.883799, which in less than 600.000000 s
```

### Expected behavior

az extension update --name azure-devops and az extension add --name azure-devops --version 1.0.0 should be able to install the new version found here https://github.com/Azure/azure-devops-cli-extension/releases/tag/20240206.1

### Environment Summary

 az --version
azure-cli                         2.49.0 *

core                              2.49.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.26.0
datafactory                        0.5.0
db-up                              0.2.3
spring                            1.13.2

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

### Additional context

I also do not see the new extension here https://[raw.githubusercontent.com/Azure/azure-cli-extensions/main/src/index.json](https://raw.githubusercontent.com/Azure/azure-cli-extensions/main/src/index.json)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jontreynes** [comment]
> Hi @jontreynes,
> 
> 2.49.0 is not the latest Azure CLI(2.57.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

same result when upgrading to 2.57
