### ISSUE TITLE
Error thrown on func start after upgrading nuget packages

### ISSUE THREAD

**Issue by wgrs** [Azure/azure-cli#28472]
### Describe the bug

After upgrading these nugets to the latest versions, the error is thrown

```
 <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
  </ItemGroup>
```

### Related command

func start

### Errors

Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2

### Issue script & Debug output

ERROR xxx@xxx-ThinkPad-E520  ~  Dev  Projects  FSBO  FunctionApi  master  func start --debug
Azure.Functions.Cli.Common.CliException: Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2
   at Azure.Functions.Cli.Helpers.DotnetHelpers.CanDotnetBuild() in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\DotnetHelpers.cs:line 166
   at Azure.Functions.Cli.Helpers.DotnetHelpers.BuildAndChangeDirectory(String outputPath, String cliParams) in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\DotnetHelpers.cs:line 173
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.PreRunConditions() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 431
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 356
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64

### Expected behavior

I expect it to discover the functions

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/greg/.azure/cliextensions'

### Additional context

This only happens when I upgrade the nugets

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I'm totally confused. It seems you're compiling a C# code, but azure-cli is a Python project.

**Comment by kamperiadis** [comment]
This is not Az CLI related but rather Core Tools related. Closing as I see that it has already been reported there: https://github.com/Azure/azure-functions-core-tools/issues/3611
