### ISSUE TITLE
az ml online-deployment create  seems broken

### ISSUE THREAD

**Issue by guillermo-rayo-aya** [Azure/azure-cli#28552]
### Describe the bug

az ml online-deployment create --name time-to-fill-online-dp --endpoint time-to-fill-online-dev -f online-deployment.yml
The command failed with an unexpected error. Here is the traceback:
local variable 'debug' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 78, in ml_online_deployment_create
    ml_client, debug = get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 207, in get_ml_client
    ml_client = _get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 154, in _get_ml_client
    ml_client = get_mgmt_service_client(cli_ctx, MLClient._ml_client_cli, subscription_id=subscription_id, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 254, in _get_mgmt_service_client
    client = client_type(credential, subscription_id, **client_kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 770, in _ml_client_cli
    ml_client = cls(credential=credentials, subscription_id=subscription_id, **kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 220, in __init__
    ws_ops = WorkspaceOperations(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_workspace_operations.py", line 60, in __init__
    self.dataplane_workspace_operations = kwargs.pop("dataplane_client").workspaces
KeyError: 'dataplane_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 132, in ml_online_deployment_create
    log_and_raise_error(err, debug, yaml_operation=yaml_operation)
UnboundLocalError: local variable 'debug' referenced before assignment

### Related command

az ml online-deployment create 

### Errors

The command failed with an unexpected error. Here is the traceback:
local variable 'debug' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 78, in ml_online_deployment_create
    ml_client, debug = get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 207, in get_ml_client
    ml_client = _get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 154, in _get_ml_client
    ml_client = get_mgmt_service_client(cli_ctx, MLClient._ml_client_cli, subscription_id=subscription_id, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 254, in _get_mgmt_service_client
    client = client_type(credential, subscription_id, **client_kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 770, in _ml_client_cli
    ml_client = cls(credential=credentials, subscription_id=subscription_id, **kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 220, in __init__
    ws_ops = WorkspaceOperations(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_workspace_operations.py", line 60, in __init__
    self.dataplane_workspace_operations = kwargs.pop("dataplane_client").workspaces
KeyError: 'dataplane_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 132, in ml_online_deployment_create
    log_and_raise_error(err, debug, yaml_operation=yaml_operation)
UnboundLocalError: local variable 'debug' referenced before assignment

### Issue script & Debug output

az ml online-deployment create --name time-to-fill-online-dp --endpoint time-to-fill-online-dev -f online-deployment.yml
The command failed with an unexpected error. Here is the traceback:
local variable 'debug' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 78, in ml_online_deployment_create
    ml_client, debug = get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 207, in get_ml_client
    ml_client = _get_ml_client(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/utils.py", line 154, in _get_ml_client
    ml_client = get_mgmt_service_client(cli_ctx, MLClient._ml_client_cli, subscription_id=subscription_id, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
    client, _ = _get_mgmt_service_client(cli_ctx, client_type, subscription_id=subscription_id,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/client_factory.py", line 254, in _get_mgmt_service_client
    client = client_type(credential, subscription_id, **client_kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 770, in _ml_client_cli
    ml_client = cls(credential=credentials, subscription_id=subscription_id, **kwargs)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 220, in __init__
    ws_ops = WorkspaceOperations(
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_workspace_operations.py", line 60, in __init__
    self.dataplane_workspace_operations = kwargs.pop("dataplane_client").workspaces
KeyError: 'dataplane_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3.9/site-packages/azure-cli-extensions/ml/azext_mlv2/manual/custom/online_deployment.py", line 132, in ml_online_deployment_create
    log_and_raise_error(err, debug, yaml_operation=yaml_operation)
UnboundLocalError: local variable 'debug' referenced before assignment

### Expected behavior

The command should run. 

### Environment Summary

guillermo [ ~ ]$ az --version
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.23.0
ssh                                2.0.2

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/guillermo/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
