### ISSUE TITLE
Unable to login using az login

### ISSUE THREAD

**Issue by ejsealms** [Azure/azure-cli#28578]
### Describe the bug

I ran az login, it opened the browser and I logged in. The browser said that everything worked fine. After a few seconds, the command line said: 

<urllib3.connection.HTTPSConnection object at 0x050429F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

I tried uninstalling and reinstalling the CLI, but got the same result. I also tried to allow-list the az CLI in my firewall settings, but the executable does not have a file extension, so it is not findable by the firewall app. 

### Related command

az login

### Errors

<urllib3.connection.HTTPSConnection object at 0x050429F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Issue script & Debug output

PS C:\Users\ethanseal> az login --debug
cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01AEF938>, <function OutputProducer.on_global_arguments at 0x01E16A28>, <function CLIQuery.on_global_arguments at 0x01E377F8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.033         2         8
cli.azure.cli.core: Total (1)                 0.033         2         8
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 2 groups, 8 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03F026B8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\ethanseal\.azure\commands\2024-03-18.12-02-39.login.40804.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F28ED8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F629D8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F62AC8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01E16A78>, <function CLIQuery.handle_query_parameter at 0x01E37848>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03F62A78>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\ethanseal\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\ethanseal\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.identity: A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
msal.telemetry: Generate or reuse correlation_id: f15bf2c8-ff54-4536-ac76-3c4110b5c5e4
msal.oauth2cli.oauth2: Using http://localhost:65184 as redirect_uri
msal.oauth2cli.authcode: Abort by visit http://localhost:65184?error=abort
msal.oauth2cli.authcode: Open a browser on this device to visit: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A65184&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+offline_access+openid+profile&state=xnclsHTFKEtMYjJa&code_challenge=CgZUvlp7Od5q_Y9wEflXE-WVqzcyOUF4un6n19RJDtg&code_challenge_method=S256&nonce=51bbc0d3bbbc506ef80a18adc1ff281f1b7e4c63b66280108d708707862346dc&client_info=1&claims=%7B%22access_token%22%3A+%7B%22xms_cc%22%3A+%7B%22values%22%3A+%5B%22CP1%22%5D%7D%7D%7D&prompt=select_account
msal.oauth2cli.authcode: Got auth response: {'code': '0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaACU.AgABAAIAAADnfolhJpSnRYB1SVj-Hgd8AgDs_wUA9P91_xPCHMB8Ljq_QTuYQUdVtn85Od11XpNSLWFXUlGqa0SlAYrOf0mm5Sbhxz7H8OZpd8kUnoRgm_MK5ol2eLM90aZssEUasYR3oHH6x56OQR_9oMDHp2Eu-CVvNwJ9vpEJ0O58dnjAL9JwGj2wPXxxlTPd2A-RDb4NonKtyZdWTzCatyJXfDDgeJsjkCod6hMyU6x1ikWDCvT1USq5WflBGsTg-s8iLu7UczDA_ndd08Sr8VKnmO1bCGWa_fRQg_I8v72W_pwcKnbvIGhyeBEJXzKE8ezGxdbWEYpigFyKgrcYSsQzy9n6LfSe3V6nSWaSrqS-hxki-Lcxigk-L49dobQXjtbk63Wk1Vm1aAVlEqtljM2TNLQrxWpBRmfsb-xwD0FLNxP3YL59eoM-G-zW3NXHO2L8VrBlWPNJ0pw8T4hq8zQtiAeTUt2VK_t0772JeyppqJBISSXEhGccjfEV4_bCOf9Z8ejlTwUeIUVHhCHt_SE1hudJgkENOjA-ndZf6HqyrZZtp4fpB0W8PCpcxSjMSMKP-sj4XxEXw4clBuiqPlgyLpIsaHpJIzNYXoNeTDmQFEo1ZLjmHTeUTJxX0kF7prE4cU56Dssmd7B2B1PJjFVdE3NWWg0A0pqx0P9JZQ9iTBvCs-8tB6p0HmBcPAgJDVjhb_bcn6nIOPdqmIhVBi2U-Ypd7R62EEJVH0JG_-UzytNmmycDiqeaTiywpayiNEoM6ilsrorvo7V8TJPWHebO0PX5RiJ0KfklcSOjBqQmOQpA_8RqlMjH3DsLKBF-iYxiZYZ4yolbZbSBtd10vYyPX43Q6UvTLcVe9SOXhg4u4SBG1_k0AvQHCHtEg7jvW4McfvhHdrygWYW3F2Mrms8brWR4vQqWHjRMOrzMaYrC1gt7_-W-XeJ91FVS5tp8JpZvLTcu2NIb3uxnnbZqqJu50grpkgfJYYy175wfT6FTG0sZ-ifcq8xlXE3aodY-zPbU5Z1KsRdABE8XAp1sjHc7UkB0a3bekNeXJwLsRTILLkwYuCsr1Vw_kLCGYlKEZG_uFXWZisG_U2ic_SjpY7WSGexNp99D-814yVUUkaX6YxvrR-3A0YPX4eQQ7M9JMIqPp7EHMqqSxgmjQ0uE-iXi9GJlAWOfK1-DHsyGvR_vvixtfVAd8-qqUndG', 'client_info': 'eyJ1aWQiOiI5NWU4NzU0ZC01ZjdkLTQwY2EtODhjMS03MWQwMThhYTUyNjUiLCJ1dGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3In0', 'state': 'xnclsHTFKEtMYjJa', 'session_state': '405ee491-4d5a-49d7-9bb6-a6aef1983426'}
msal.oauth2cli.authcode: "GET /?code=0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaACU.AgABAAIAAADnfolhJpSnRYB1SVj-Hgd8AgDs_wUA9P91_xPCHMB8Ljq_QTuYQUdVtn85Od11XpNSLWFXUlGqa0SlAYrOf0mm5Sbhxz7H8OZpd8kUnoRgm_MK5ol2eLM90aZssEUasYR3oHH6x56OQR_9oMDHp2Eu-CVvNwJ9vpEJ0O58dnjAL9JwGj2wPXxxlTPd2A-RDb4NonKtyZdWTzCatyJXfDDgeJsjkCod6hMyU6x1ikWDCvT1USq5WflBGsTg-s8iLu7UczDA_ndd08Sr8VKnmO1bCGWa_fRQg_I8v72W_pwcKnbvIGhyeBEJXzKE8ezGxdbWEYpigFyKgrcYSsQzy9n6LfSe3V6nSWaSrqS-hxki-Lcxigk-L49dobQXjtbk63Wk1Vm1aAVlEqtljM2TNLQrxWpBRmfsb-xwD0FLNxP3YL59eoM-G-zW3NXHO2L8VrBlWPNJ0pw8T4hq8zQtiAeTUt2VK_t0772JeyppqJBISSXEhGccjfEV4_bCOf9Z8ejlTwUeIUVHhCHt_SE1hudJgkENOjA-ndZf6HqyrZZtp4fpB0W8PCpcxSjMSMKP-sj4XxEXw4clBuiqPlgyLpIsaHpJIzNYXoNeTDmQFEo1ZLjmHTeUTJxX0kF7prE4cU56Dssmd7B2B1PJjFVdE3NWWg0A0pqx0P9JZQ9iTBvCs-8tB6p0HmBcPAgJDVjhb_bcn6nIOPdqmIhVBi2U-Ypd7R62EEJVH0JG_-UzytNmmycDiqeaTiywpayiNEoM6ilsrorvo7V8TJPWHebO0PX5RiJ0KfklcSOjBqQmOQpA_8RqlMjH3DsLKBF-iYxiZYZ4yolbZbSBtd10vYyPX43Q6UvTLcVe9SOXhg4u4SBG1_k0AvQHCHtEg7jvW4McfvhHdrygWYW3F2Mrms8brWR4vQqWHjRMOrzMaYrC1gt7_-W-XeJ91FVS5tp8JpZvLTcu2NIb3uxnnbZqqJu50grpkgfJYYy175wfT6FTG0sZ-ifcq8xlXE3aodY-zPbU5Z1KsRdABE8XAp1sjHc7UkB0a3bekNeXJwLsRTILLkwYuCsr1Vw_kLCGYlKEZG_uFXWZisG_U2ic_SjpY7WSGexNp99D-814yVUUkaX6YxvrR-3A0YPX4eQQ7M9JMIqPp7EHMqqSxgmjQ0uE-iXi9GJlAWOfK1-DHsyGvR_vvixtfVAd8-qqUndG&client_info=eyJ1aWQiOiI5NWU4NzU0ZC01ZjdkLTQwY2EtODhjMS03MWQwMThhYTUyNjUiLCJ1dGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3In0&state=xnclsHTFKEtMYjJa&session_state=405ee491-4d5a-49d7-9bb6-a6aef1983426 HTTP/1.1" 200 -
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /organizations/oauth2/v2.0/token HTTP/1.1" 200 5976
msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
        "code": "0.AQEAv4j5cvGGr0GRqy180BHbR5V3sATbjRpGu-4C-eG_e0YaACU.AgABAAIAAADnfolhJpSnRYB1SVj-Hgd8AgDs_wUA9P91_xPCHMB8Ljq_QTuYQUdVtn85Od11XpNSLWFXUlGqa0SlAYrOf0mm5Sbhxz7H8OZpd8kUnoRgm_MK5ol2eLM90aZssEUasYR3oHH6x56OQR_9oMDHp2Eu-CVvNwJ9vpEJ0O58dnjAL9JwGj2wPXxxlTPd2A-RDb4NonKtyZdWTzCatyJXfDDgeJsjkCod6hMyU6x1ikWDCvT1USq5WflBGsTg-s8iLu7UczDA_ndd08Sr8VKnmO1bCGWa_fRQg_I8v72W_pwcKnbvIGhyeBEJXzKE8ezGxdbWEYpigFyKgrcYSsQzy9n6LfSe3V6nSWaSrqS-hxki-Lcxigk-L49dobQXjtbk63Wk1Vm1aAVlEqtljM2TNLQrxWpBRmfsb-xwD0FLNxP3YL59eoM-G-zW3NXHO2L8VrBlWPNJ0pw8T4hq8zQtiAeTUt2VK_t0772JeyppqJBISSXEhGccjfEV4_bCOf9Z8ejlTwUeIUVHhCHt_SE1hudJgkENOjA-ndZf6HqyrZZtp4fpB0W8PCpcxSjMSMKP-sj4XxEXw4clBuiqPlgyLpIsaHpJIzNYXoNeTDmQFEo1ZLjmHTeUTJxX0kF7prE4cU56Dssmd7B2B1PJjFVdE3NWWg0A0pqx0P9JZQ9iTBvCs-8tB6p0HmBcPAgJDVjhb_bcn6nIOPdqmIhVBi2U-Ypd7R62EEJVH0JG_-UzytNmmycDiqeaTiywpayiNEoM6ilsrorvo7V8TJPWHebO0PX5RiJ0KfklcSOjBqQmOQpA_8RqlMjH3DsLKBF-iYxiZYZ4yolbZbSBtd10vYyPX43Q6UvTLcVe9SOXhg4u4SBG1_k0AvQHCHtEg7jvW4McfvhHdrygWYW3F2Mrms8brWR4vQqWHjRMOrzMaYrC1gt7_-W-XeJ91FVS5tp8JpZvLTcu2NIb3uxnnbZqqJu50grpkgfJYYy175wfT6FTG0sZ-ifcq8xlXE3aodY-zPbU5Z1KsRdABE8XAp1sjHc7UkB0a3bekNeXJwLsRTILLkwYuCsr1Vw_kLCGYlKEZG_uFXWZisG_U2ic_SjpY7WSGexNp99D-814yVUUkaX6YxvrR-3A0YPX4eQQ7M9JMIqPp7EHMqqSxgmjQ0uE-iXi9GJlAWOfK1-DHsyGvR_vvixtfVAd8-qqUndG",
        "code_verifier": "QgsBwhaNZXjy94TGOE3YRLxrFf5tHDCK8Iz_-ioq21A",
        "redirect_uri": "http://localhost:65184",
        "scope": [
            "https://management.core.windows.net//.default",
            "profile",
            "openid",
            "offline_access"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiI5NWU4NzU0ZC01ZjdkLTQwY2EtODhjMS03MWQwMThhYTUyNjUiLCJ1dGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3In0",
        "expires_in": 4567,
        "ext_expires_in": 4567,
        "foci": "1",
        "id_token": "********",
        "refresh_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
}
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f2245095-80f1-479f-9264-e7c8f2ca46fb
cli.azure.cli.core.sdk.policies: Request URL: 'https://wus2.management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '1740e071-e55a-11ee-8062-7c70db1c627d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): wus2.management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://wus2.management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '1740e071-e55a-11ee-8062-7c70db1c627d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (2): wus2.management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://wus2.management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '1740e071-e55a-11ee-8062-7c70db1c627d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (3): wus2.management.azure.com:443
cli.azure.cli.core.sdk.policies: Request URL: 'https://wus2.management.azure.com/tenants?api-version=2019-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '1740e071-e55a-11ee-8062-7c70db1c627d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.7 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (4): wus2.management.azure.com:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 176, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 740, in find_using_common_tenant
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 123, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 75, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 739, in get_next
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 213, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/core/policies/_base.py", line 47, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_redirect.py", line 181, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 489, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_retry.py", line 467, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/policies/_authentication.py", line 115, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 70, in send
  [Previous line repeated 2 more times]
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/_base.py", line 108, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/pipeline/transport/_requests_basic.py", line 376, in send
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x04D42C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

cli.azure.cli.core.azclierror: <urllib3.connection.HTTPSConnection object at 0x04D42C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
az_command_data_logger: <urllib3.connection.HTTPSConnection object at 0x04D42C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03F027F8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 16.154 seconds (init: 1.518, invoke: 14.636)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3573 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\ethanseal\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

I should be able to login

### Environment Summary

PS C:\Users\ethanseal> az --version
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.173
ssh                                2.0.2

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ethanseal\.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:13:08) [MSC v.1937 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I have had this issue for a long time.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ejsealms** [comment]
I ran the nslookup commands suggested in the similar incident, but everything appears to be fine. 

PS C:\Users\ethanseal> nslookup login.microsoftonline.com
Server:  wus2inetdns.microsoft.com
Address:  157.58.30.23

Non-authoritative answer:
Name:    www.tm.ak.prd.aadg.trafficmanager.net
Addresses:  2603:1037:1:128::8
          2603:1037:1:128::6
          2603:1036:3000:138::3
          2603:1037:1:130::6
          2603:1036:3000:138::6
          2603:1037:1:130::3
          2603:1037:1:130::4
          2603:1036:3000:138::5
          20.190.151.67
          20.190.151.134
          20.190.151.69
          20.190.151.9
          20.190.151.131
          20.190.151.133
          20.190.151.68
          20.190.151.70
Aliases:  login.microsoftonline.com
          login.mso.msidentity.com
          ak.privatelink.msidentity.com
          



PS C:\Users\ethanseal> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
200

**Comment by bebound** [comment]
The CLI raised a DNS error when connected to `wus2.management.azure.com`.
Is this a valid endpoint? @jiasli
