### ISSUE TITLE
Installation of azure-cli-find with pip fails on  Ubuntu 14.04.4 LTS

### ISSUE THREAD

**Issue by yokawasa** [Azure/azure-cli#2857]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  

```
pip install azure-cli-find --user
```

**OS Version:** What OS and version are you using?  
```
 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash on Windows

---

### Description
Installation of azure-cli-find with pip fails on  Ubuntu 14.04.4 LTS. Error message is this:
```
 $ pip install azure-cli-find --user
Downloading/unpacking azure-cli-find
  Could not find a version that satisfies the requirement azure-cli-find (from versions: 0.0.1b1, 0.0.1b1)
Cleaning up...
No distributions matching the version for azure-cli-find
Storing debug log for failure in /tmp/tmpJAUOdK
```

cat  /tmp/tmpJAUOdK
```
------------------------------------------------------------
/usr/bin/pip run on Fri Apr 14 21:06:12 2017
Downloading/unpacking azure-cli-find
  Getting page https://pypi.python.org/simple/azure-cli-find/
  URLs to search for versions for azure-cli-find:
  * https://pypi.python.org/simple/azure-cli-find/
  Analyzing links from page https://pypi.python.org/simple/azure-cli-find/
    Found link https://pypi.python.org/packages/7a/16/4d210f6b1690aea9e390e30fbacb7042920b34fb22a2e5dc09df83582357/azure_cli_find-0.0.1b1-py2.py3-none-any.whl#md5=d15b733391cd13f8149532e2a07d5ee0 (from https://pypi.python.org/simple/azure-cli-find/), version: 0.0.1b1
    Found link https://pypi.python.org/packages/f0/7a/7017494632e641c4239034ee209073e4e79fdcf738c7be900cc1888e99a5/azure-cli-find-0.0.1b1.tar.gz#md5=825c34507615738f44af59d99fcca12d (from https://pypi.python.org/simple/azure-cli-find/), version: 0.0.1b1
  Ignoring link https://pypi.python.org/packages/7a/16/4d210f6b1690aea9e390e30fbacb7042920b34fb22a2e5dc09df83582357/azure_cli_find-0.0.1b1-py2.py3-none-any.whl#md5=d15b733391cd13f8149532e2a07d5ee0 (from https://pypi.python.org/simple/azure-cli-find/), version 0.0.1b1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/f0/7a/7017494632e641c4239034ee209073e4e79fdcf738c7be900cc1888e99a5/azure-cli-find-0.0.1b1.tar.gz#md5=825c34507615738f44af59d99fcca12d (from https://pypi.python.org/simple/azure-cli-find/), version 0.0.1b1 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement azure-cli-find (from versions: 0.0.1b1, 0.0.1b1)
Cleaning up...
  Removing temporary dir /tmp/pip_build_yoichika...
No distributions matching the version for azure-cli-find
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for azure-cli-find
```

**Comment by derekbekoe** [comment]
Use --pre to allow the install of this module as it's currently marked as prerelease (b1). That should work.
In the next release of this module (next week) I'll change the version to 0.0.2 so the --pre flag is no longer needed.

**Comment by tjprescott** [comment]
Would updating pip also solve this?

**Comment by derekbekoe** [comment]
Yes.

**Comment by yokawasa** [comment]
@derekbekoe 
I tried with --pre but I saw it fail. 

my pip version is:
```
$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

error message is:
```
 $ pip install --user --pre azure-cli-find
Downloading/unpacking azure-cli-find
  Downloading azure_cli_find-0.0.1b1-py2.py3-none-any.whl
Downloading/unpacking whoosh (from azure-cli-find)
  Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468kB): 468kB downloaded
Downloading/unpacking azure-cli-core (from azure-cli-find)
  Downloading azure_cli_core-2.0.2-py2.py3-none-any.whl (74kB): 74kB downloaded
Downloading/unpacking msrestazure>=0.4.7 (from azure-cli-core->azure-cli-find)
  Downloading msrestazure-0.4.7-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4')

Storing debug log for failure in /tmp/tmpnBJs79
```

Anyway I'll wait until new version of this module will be released

**Comment by yokawasa** [comment]
@derekbekoe @tjprescott 
I was able to install the module by upgrading pip. Thanks!

```
pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by troydai** [comment]
Problem solved.
