### ISSUE TITLE
az login fails because of proxy

### ISSUE THREAD

**Issue by SUL-sj** [Azure/azure-cli#28592]
### Describe the bug

 
After trying to login via az login the following error occurs:
ERROR: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable'))
 
It used to work in the past with an unchanged setup. Somewhere in the last months it began to produce this error - worked again and now seemed to fail indefinitely.
 
Environment Variables HTTPS_PROXY, HTTP_PROXY, https_proxy and http_proxy are set (as mentioned: unchanged environment). We also tried without the proxy variables set - this results in the expected error of not being able to route target host - so proxy is definitely respected by az.
Login from other machine behind an identical proxy works. Other applications on the same machine are able to work with the proxy - only az cli having issues.
 
 

### Related command

az login --service-principal -u xxxx -p ../tf-common/service-principal.pem --tenant xxxx

### Errors

cli.azure.cli.core.azclierror: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable'))

### Issue script & Debug output

```
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f52f351d620>, <function OutputProducer.on_global_arguments at 0x7f52f34ba160>, <function CLIQuery.on_global_arguments at 0x7f52f34efc40>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
DEBUG: cli.azure.cli.core: Command index has been invalidated.
DEBUG: cli.azure.cli.core: No module found from index for '['login', '--debug', '--service-principal', '-u', 'xxxx', '-p', '../tf-common/service-principal.pem', '--tenant', 'xxxx']'
DEBUG: cli.azure.cli.core: Loading all modules and extensions
DEBUG: cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'containerapp', 'cosmosdb', 'databoxedge', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'mysql', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: acr                       0.084        36       149
DEBUG: cli.azure.cli.core: acs                       0.025        12        69
DEBUG: cli.azure.cli.core: advisor                   0.001         3         6
DEBUG: cli.azure.cli.core: ams                       0.005        22       100
DEBUG: cli.azure.cli.core: apim                      0.005        14        69
DEBUG: cli.azure.cli.core: appconfig                 0.003         9        47
DEBUG: cli.azure.cli.core: appservice                0.083        73       260
DEBUG: cli.azure.cli.core: aro                       0.011         1        10
DEBUG: cli.azure.cli.core: backup                    0.004        16        60
DEBUG: cli.azure.cli.core: batch                     0.042        34       102
DEBUG: cli.azure.cli.core: batchai                   0.005        10        30
DEBUG: cli.azure.cli.core: billing                   0.013        20        53
DEBUG: cli.azure.cli.core: botservice                0.003        12        42
DEBUG: cli.azure.cli.core: cdn                       0.118        23        93
DEBUG: cli.azure.cli.core: cloud                     0.001         1         7
DEBUG: cli.azure.cli.core: cognitiveservices         0.002        10        33
DEBUG: cli.azure.cli.core: config                    0.001         2         7
DEBUG: cli.azure.cli.core: configure                 0.001         2         5
DEBUG: cli.azure.cli.core: consumption               0.014         8         9
DEBUG: cli.azure.cli.core: container                 0.008         1        11
DEBUG: cli.azure.cli.core: containerapp              0.100        36       115
DEBUG: cli.azure.cli.core: cosmosdb                  0.015        58       199
DEBUG: cli.azure.cli.core: databoxedge               0.004         5        27
DEBUG: cli.azure.cli.core: dla                       0.005        23        62
DEBUG: cli.azure.cli.core: dls                       0.004         7        41
DEBUG: cli.azure.cli.core: dms                       0.002         3        22
DEBUG: cli.azure.cli.core: eventgrid                 0.007        25        96
DEBUG: cli.azure.cli.core: eventhubs                 0.007        12        18
DEBUG: cli.azure.cli.core: extension                 0.001         1         7
DEBUG: cli.azure.cli.core: feedback                  0.001         1         2
DEBUG: cli.azure.cli.core: find                      0.001         1         1
DEBUG: cli.azure.cli.core: hdinsight                 0.007         8        39
DEBUG: cli.azure.cli.core: identity                  0.002         2        11
DEBUG: cli.azure.cli.core: interactive               0.000         1         1
DEBUG: cli.azure.cli.core: iot                       0.144        19        82
DEBUG: cli.azure.cli.core: keyvault                  0.008        20       113
DEBUG: cli.azure.cli.core: kusto                     0.002         3        14
DEBUG: cli.azure.cli.core: lab                       0.003        11        34
DEBUG: cli.azure.cli.core: managedservices           0.001         3         8
DEBUG: cli.azure.cli.core: maps                      0.001         5        13
DEBUG: cli.azure.cli.core: marketplaceordering       0.002         1         2
DEBUG: cli.azure.cli.core: monitor                   0.478        18        60
DEBUG: cli.azure.cli.core: mysql                     0.095        14        49
DEBUG: cli.azure.cli.core: netappfiles               0.005        17        96
DEBUG: cli.azure.cli.core: network                   0.126       103       338
DEBUG: cli.azure.cli.core: policyinsights            0.011         9        17
DEBUG: cli.azure.cli.core: privatedns                0.016        14        60
DEBUG: cli.azure.cli.core: profile                   0.001         2         8
DEBUG: cli.azure.cli.core: rdbms                     0.021        49       202
DEBUG: cli.azure.cli.core: redis                     0.002         7        38
DEBUG: cli.azure.cli.core: relay                     0.019         7         8
DEBUG: cli.azure.cli.core: resource                  0.015        51       228
DEBUG: cli.azure.cli.core: role                      0.109        17        61
DEBUG: cli.azure.cli.core: search                    0.007         7        19
DEBUG: cli.azure.cli.core: security                  0.010        49       105
DEBUG: cli.azure.cli.core: servicebus                0.006        12        15
DEBUG: cli.azure.cli.core: serviceconnector          0.019        16       244
DEBUG: cli.azure.cli.core: servicefabric             0.013        27        76
DEBUG: cli.azure.cli.core: signalr                   0.002         9        34
DEBUG: cli.azure.cli.core: sql                       0.015        56       215
DEBUG: cli.azure.cli.core: sqlvm                     0.020         4        20
DEBUG: cli.azure.cli.core: storage                   0.051        59       273
DEBUG: cli.azure.cli.core: synapse                   0.013        54       246
DEBUG: cli.azure.cli.core: util                      0.001         3         7
DEBUG: cli.azure.cli.core: vm                        0.054        58       233
DEBUG: cli.azure.cli.core: Total (65)                1.860      1216      4721
DEBUG: cli.azure.cli.core: Loaded 1203 groups, 4721 commands.
DEBUG: cli.azure.cli.core: Updated command index in 0.005 seconds.
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f52f27adbc0>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2024-03-19.22-31-48.login.5493.log'.
INFO: az_command_data_logger: command args: login --debug --service-principal -u {} -p {} --tenant {}
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f52f209e700>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f52f209e7a0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f52f209e8e0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f52f0bca020>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f52f34ba200>, <function CLIQuery.handle_query_parameter at 0x7f52f34efce0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f52f209e840>]
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/msal_token_cache.json', encrypt=False
DEBUG: cli.azure.cli.core.auth.binary_cache: load: /root/.azure/msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: /root/.azure/msal_http_cache.bin not found. Using a fresh one.
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "GET /xxxx/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1753
DEBUG: cli.azure.cli.core.auth.binary_cache: save: /root/.azure/msal_http_cache.bin
DEBUG: cli.azure.cli.core.auth.binary_cache: save: /root/.azure/msal_http_cache.bin
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xxxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xxxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xxxxoauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xxxxoauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xxxxoauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xxxxkerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? None
DEBUG: msal.telemetry: Generate or reuse correlation_id: xxxx
DEBUG: msal.oauth2cli.assertion: Regenerating new assertion
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /xxxx/oauth2/v2.0/token HTTP/1.1" 200 1540
DEBUG: msal.token_cache: event={
    "client_id": "1xxxx",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "scope": [
            "https://management.core.windows.net//.default"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "client_credentials",
    "params": null,
    "response": {
        "access_token": "********",
        "expires_in": 3599,
        "ext_expires_in": 3599,
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/xxxx/oauth2/v2.0/token"
}
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/service_principal_entries.json', encrypt=False
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xxxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xxxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xxxx/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? None
DEBUG: cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: xxxx
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxx
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --service-principal -u -p --tenant'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (DEB) azsdk-python-core/1.28.0 Python/3.11.7 (Linux-4.18.0-394.el8.x86_64-x86_64-with-glibc2.28)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxx'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --service-principal -u -p --tenant'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (DEB) azsdk-python-core/1.28.0 Python/3.11.7 (Linux-4.18.0-394.el8.x86_64-x86_64-with-glibc2.28)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (2): management.azure.com:443
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxx'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --service-principal -u -p --tenant'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (DEB) azsdk-python-core/1.28.0 Python/3.11.7 (Linux-4.18.0-394.el8.x86_64-x86_64-with-glibc2.28)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (3): management.azure.com:443
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions?api-version=2019-11-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxx'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'login'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--debug --service-principal -u -p --tenant'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (DEB) azsdk-python-core/1.28.0 Python/3.11.7 (Linux-4.18.0-394.el8.x86_64-x86_64-with-glibc2.28)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (4): management.azure.com:443
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
                    ^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 174, in login
    subscriptions = subscription_finder.find_using_specific_tenant(tenant, credential)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 809, in find_using_specific_tenant
    for s in subscriptions:
  File "/opt/az/lib/python3.11/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_operations.py", line 519, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 213, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.11/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_redirect.py", line 181, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 489, in send
    raise err
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_retry.py", line 467, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/policies/_authentication.py", line 115, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/_base.py", line 108, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 376, in send
    raise error
azure.core.exceptions.ServiceRequestError: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable'))

ERROR: cli.azure.cli.core.azclierror: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable'))
ERROR: az_command_data_logger: ('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable'))
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f52f27ade40>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 26.107 seconds (init: 0.625, invoke: 25.482)
DEBUG: cli.azure.cli.core._profile: Failed to load installationId from AzureRmSurvey.json. [Errno 2] No such file or directory: '/root/.azure/AzureRmContextSettings.json'

```

### Expected behavior

az login successful via using the provided proxy

### Environment Summary

We are using debian buster with azure-cli version 2.58.0-1~buster

### Additional context

We also tried to connect to the proxy from python to make sure it is not a python related issue - this worked!
`import requests; print(requests.get('https://login.microsoftonline.com/').status_code)`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
`'Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')` indicates that it's a proxy/network issue.
_Login from other machine behind an identical proxy works._ So something goes wrong on this machine?

It seems that you can access to `login.microsoftonline.com`, but not `management.azure.com`. That's weird, I have no clue.

**Comment by SUL-sj** [comment]
> It seems that you can access to login.microsoftonline.com, but not management.azure.com. That's weird, I have no clue.
Thank you very much @bebound for pointing this out. It was in fact an issue with our DNS provider who appearantly decided to filter azure domains for reasons not yet known to us. We changed the DNS to google and now the login works.

Thank you for the support!
