### ISSUE TITLE
az iot hub message-enrichment create - the least permissions needed

### ISSUE THREAD

**Issue by chokosticks** [Azure/azure-cli#28645]
### Describe the bug

Hi,

What permission do I need to be able to run command:

az iot hub message-enrichment create

As of now I do get Forbidden when with the role Contributor on the IotHub.
I'm trying to create a pipeline which need to configure message routing on an iothub.

Both commands:

1. az iot hub message-route create,
2. az iot hub message-endpoint create servicebus-topic

works with the role Contributor on the IotHub.

Do I need more permissions to be able to run this command?

Thanks in advance

### Related command

az iot hub message-enrichment create

### Errors

Operation returned an invalid status 'Forbidden'

### Issue script & Debug output

DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: [https://management.azure.com:443](https://management.azure.com/) "HEAD /subscriptions/--/resourcegroups/--?api-version=2022-09-01 HTTP/1.1" 403 0
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 403
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '0'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '--'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '--'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20240326T151102Z:31cae7e5-8fcc-46cd-8d2c-7f376ae0cab6'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 26 Mar 2024 15:11:01 GMT'
DEBUG: cli.azure.cli.core.sdk.policies:     'Connection': 'close'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: 
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/iot/custom.py", line 1163, in iot_message_enrichment_create
    hub = iot_hub_get(cmd, client, hub_name, resource_group_name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/iot/custom.py", line 598, in iot_hub_get
    if not _ensure_resource_group_existence(cli_ctx, resource_group_name):

### Expected behavior

To be able, via a pipline, to configure message enrichment with the least permissions possible needed.

### Environment Summary

AZURECLI/2.48.1 (DEB) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Linux-5.15.0-1049-azure-x86_64-with-glibc2.31) VSTS_a3739de9-257e-4aa8-88a1-968a69f49455_build_2743_0

**Comment by chokosticks** [comment]
Hi,

When our Publish-app got the Reader-role on the resource group everything worked out fine.

So we needed Contributor on the IotHub as well as the ability to list/read the resource group.

Thanks.
