### ISSUE TITLE
Bicep in Docker is not working as expected

### ISSUE THREAD

**Issue by KrisSimon** [Azure/azure-cli#28758]
### Describe the bug

Lining a file on macOS works like expected: 
```
az bicep lint -f bicep/main.bicep; echo $?

0
```

The same file in a docker image from `mcr.microsoft.com/azure-cli` exit with `1`
```
az bicep lint -f bicep/main.bicep; echo $?

1
```

### Related command

`az bicep lint`

### Errors

```
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 312, in _run_command
    process.check_returncode()
  File "/usr/local/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/root/.azure/bin/bicep', 'lint', '/tmp/bicep/main.bicep']' died with <Signals.SIGSEGV: 11>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 4608, in lint_bicep_file
    output = run_bicep_command(cmd.cli_ctx, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 107, in run_bicep_command
    return _run_command(installation_path, args, custom_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 328, in _run_command
    raise UnclassifiedUserFault(error_msg)
azure.cli.core.azclierror.UnclassifiedUserFault
```

### Issue script & Debug output

```
# az bicep lint -f bicep/main.bicep --debug
cli.knack.cli: Command arguments: ['bicep', 'lint', '-f', 'bicep/main.bicep', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x40035880e0>, <function OutputProducer.on_global_arguments at 0x40038de480>, <function CLIQuery.on_global_arguments at 0x4003913f60>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'bicep': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.401        51       228
cli.azure.cli.core: Total (1)                 0.401        51       228
cli.azure.cli.core: Loaded 51 groups, 228 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : bicep lint
cli.azure.cli.core: Command table: bicep lint
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x4006a149a0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2024-04-16.09-44-12.bicep_lint.480.log'.
az_command_data_logger: command args: bicep lint -f {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x4006a51b20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x4006a70d60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x4006a70ea0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x40038de520>, <function CLIQuery.handle_query_parameter at 0x4003a88040>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x4006a70e00>]
cli.azure.cli.command_modules.resource._bicep: Current value of "use_binary_from_path": false.
cli.azure.cli.command_modules.resource._bicep: Bicep CLI installation path: /root/.azure/bin/bicep
cli.azure.cli.command_modules.resource._bicep: Bicep CLI installed: True.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 312, in _run_command
    process.check_returncode()
  File "/usr/local/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/root/.azure/bin/bicep', 'lint', 'bicep/main.bicep']' died with <Signals.SIGSEGV: 11>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 4608, in lint_bicep_file
    output = run_bicep_command(cmd.cli_ctx, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 107, in run_bicep_command
    return _run_command(installation_path, args, custom_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 328, in _run_command
    raise UnclassifiedUserFault(error_msg)
azure.cli.core.azclierror.UnclassifiedUserFault

cli.azure.cli.core.azclierror: 
az_command_data_logger: 
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x4006a14c20>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 24.077 seconds (init: 1.052, invoke: 23.025)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3578 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/local/bin/python /usr/local/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /root/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Expect the same behaviour in linux then on mac.

### Environment Summary

```
azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.11.8 (main, Mar 16 2024, 04:56:37) [GCC 13.2.1 20231014]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

```
# az bicep version
Bicep CLI version 0.26.170 (e9abaf16a5)
```

**Comment by carlcody21** [comment]
Any update? I am experiencing a similar issue deploying bicep via _az deployment_

**Comment by torreymicrosoft** [comment]
Thanks for your patience, @KrisSimon (and @carlcody21 for the +1) — this was recently picked up as an outstanding open issue for the ARM Deployments team to review.

This is almost certainly the same root cause as your #28756: the Bicep binary is **crashing** (SIGSEGV/SIGABRT) inside the Alpine-based `mcr.microsoft.com/azure-cli` image. There's no `linux-musl-arm64` Bicep build (confirmed from the CLI's supported target-platform list), so on that image Bicep doesn't have a matching native binary to run.

Two separate things are happening, and it's worth tracking them in the right places:
- **The crash itself** is a Bicep runtime/packaging issue → best owned in https://github.com/Azure/bicep (we'll link it to #28756).
- **The unhelpful `UnclassifiedUserFault` with no detail** is the azure-cli wrapper discarding the failed process's output — that's the same swallow we're tracking in #28259.

Workaround: run on a **glibc base** (e.g. an Ubuntu image with the CLI installed) instead of the Alpine azure-cli image — that path doesn't hit the crash. We'll consolidate the binary crash with #28756. Does switching base images get you unblocked?
