### ISSUE TITLE
az k8s-extension create lacks --yes parameter

### ISSUE THREAD

**Issue by stgleb** [Azure/azure-cli#28766]
### Describe the bug

Command ```az k8s-extension create --cluster-type managedClusters --cluster-name $CLUSTER_NAME --resource-group $CLUSTER_NAME --name dapr --extension-type Microsoft.Dapr --auto-upgrade-minor-version false --release-train stable```

does not have parameter yes to ignore command prompt

also running like:

```yes |az k8s-extension create --cluster-type managedClusters --cluster-name $CLUSTER_NAME --resource-group $CLUSTER_NAME --name dapr --extension-type Microsoft.Dapr --auto-upgrade-minor-version false --release-train stable ``` outputs with:

```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 173, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 122, in Create
    self._get_release_info(name, release_namespace, configuration_settings)
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 93, in _get_release_info
    if prompt_y_n(self.MSG_IS_DAPR_INSTALLED, default='n'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

az cli version:

```
az --version
azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
aks-preview                      3.0.0b3
k8s-extension                      1.6.1

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/bin/python'
Extensions directory '/Users/glebstepanov/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date
```

### Related command

az k8s-extension create --cluster-type managedClusters --cluster-name gleb-04-17 --resource-group gleb-04-17 --name dapr --extension-type Microsoft.Dapr --auto-upgrade-minor-version false --release-train stable

### Errors

```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 173, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 122, in Create
    self._get_release_info(name, release_namespace, configuration_settings)
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 93, in _get_release_info
    if prompt_y_n(self.MSG_IS_DAPR_INSTALLED, default='n'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

cli.knack.cli: Command arguments: ['k8s-extension', 'create', '--cluster-type', 'managedClusters', '--cluster-name', 'gleb-04-17', '--resource-group', 'gleb-04-17', '--name', 'dapr', '--extension-type', 'Microsoft.Dapr', '--auto-upgrade-minor-version', 'false', '--release-train', 'stable', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101159620>, <function OutputProducer.on_global_arguments at 0x1012047c0>, <function CLIQuery.on_global_arguments at 0x1012322a0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'k8s-extension': ['azext_k8s_extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: k8s-extension             0.077         2        16  /Users/glebstepanov/.azure/cliextensions/k8s-extension
cli.azure.cli.core: Total (1)                 0.077         2        16
cli.azure.cli.core: Loaded 2 groups, 16 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : k8s-extension create
cli.azure.cli.core: Command table: k8s-extension create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10287b060>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/glebstepanov/.azure/commands/2024-04-17.13-05-09.k8s-extension_create.83748.log'.
az_command_data_logger: command args: k8s-extension create --cluster-type {} --cluster-name {} --resource-group {} --name {} --extension-type {} --auto-upgrade-minor-version {} --release-train {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1028a5b20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1028cfd80>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1028cfec0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x101204860>, <function CLIQuery.handle_query_parameter at 0x101232340>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1028cfe20>]
az_command_data_logger: extension name: k8s-extension
az_command_data_logger: extension version: 1.6.1
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SourceControlConfigurationClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/glebstepanov/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/glebstepanov/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/355069b9-fbb7-41b7-a57b-83d5a8709362/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.knack.prompting: No tty available.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 173, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 122, in Create
    self._get_release_info(name, release_namespace, configuration_settings)
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 93, in _get_release_info
    if prompt_y_n(self.MSG_IS_DAPR_INSTALLED, default='n'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 173, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 122, in Create
    self._get_release_info(name, release_namespace, configuration_settings)
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 93, in _get_release_info
    if prompt_y_n(self.MSG_IS_DAPR_INSTALLED, default='n'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException
az_command_data_logger:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 173, in create_k8s_extension
    extension_instance, name, create_identity = extension_class.Create(
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 122, in Create
    self._get_release_info(name, release_namespace, configuration_settings)
  File "/Users/glebstepanov/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py", line 93, in _get_release_info
    if prompt_y_n(self.MSG_IS_DAPR_INSTALLED, default='n'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10287b2e0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.384 seconds (init: 0.095, invoke: 0.288)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7979 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.59.0/libexec/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /Users/glebstepanov/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

expect to have ability to bypass this prompt

### Environment Summary

azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
aks-preview                      3.0.0b3
k8s-extension                      1.6.1

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/bin/python'
Extensions directory '/Users/glebstepanov/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FumingZhang** [comment]
issue with k8s-extension, not related to AKS
