### ISSUE TITLE
Error when creating virtual machine by ansible script

### ISSUE THREAD

**Issue by giansototech** [Azure/azure-cli#28770]
### Describe the bug

Error when creating virtual machine by ansible script

The script has a series of steps, among them, validating that in the Resource Group there is a storage account whose name contains the word "diag", if one with that acronym already exists, it does not create it, but if it does not exist, it creates it so that This can be used for the virtual machine in the boot diagnostic.

The script was working normally but now I get the following error:

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'
StorageAccount no encontrado para Boot Diagnostic. Creando storage account...
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'

### Related command

This is the part of the script that is responsible for the aforementioned activities:

#####Storage Account para boot diagnostic####
echo $'\nValidando Storage Account para configuración de Boot Diagnostic...\n'
diagnosticsStorageAccountName=$(echo $resourceGroupName"diag1" | tr '[:upper:]' '[:lower:]')
storageAccountName=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].name" -o tsv)
if [[ -z "$storageAccountName" ]]; then
        echo "StorageAccount no encontrado para Boot Diagnostic. Creando storage account..."
        az storage account create --name $diagnosticsStorageAccountName --resource-group $resourceGroupName --location $location --sku Standard_LRS --kind StorageV2
        az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')]" -o table
        echo '"diagnosticsStorageAccountName": { "value": "'$diagnosticsStorageAccountName'" },' >> $jsonFile
        diagnosticsStorageAccountId=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].[id]" -o tsv)
        echo '"diagnosticsStorageAccountId": { "value": "'$diagnosticsStorageAccountId'" }' >> $jsonFile
        echo '}}' >> $jsonFile
else
        echo "Boot diagnostic encontrado!!!"
        echo '"diagnosticsStorageAccountName": { "value": "'$storageAccountName'" },' >> $jsonFile
        diagnosticsStorageAccountId=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].[id]" -o tsv)
        echo '"diagnosticsStorageAccountId": { "value": "'$diagnosticsStorageAccountId'" }' >> $jsonFile
        echo '}}' >> $jsonFile
fi

### Errors

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 516, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 684, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 862, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable
To open an issue, please run: 'az feedback'

### Issue script & Debug output

This is the part of the script that is responsible for the aforementioned activities:

#####Storage Account para boot diagnostic####
echo $'\nValidando Storage Account para configuración de Boot Diagnostic...\n'
diagnosticsStorageAccountName=$(echo $resourceGroupName"diag1" | tr '[:upper:]' '[:lower:]')
storageAccountName=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].name" -o tsv)
if [[ -z "$storageAccountName" ]]; then
        echo "StorageAccount no encontrado para Boot Diagnostic. Creando storage account..."
        az storage account create --name $diagnosticsStorageAccountName --resource-group $resourceGroupName --location $location --sku Standard_LRS --kind StorageV2
        az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')]" -o table
        echo '"diagnosticsStorageAccountName": { "value": "'$diagnosticsStorageAccountName'" },' >> $jsonFile
        diagnosticsStorageAccountId=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].[id]" -o tsv)
        echo '"diagnosticsStorageAccountId": { "value": "'$diagnosticsStorageAccountId'" }' >> $jsonFile
        echo '}}' >> $jsonFile
else
        echo "Boot diagnostic encontrado!!!"
        echo '"diagnosticsStorageAccountName": { "value": "'$storageAccountName'" },' >> $jsonFile
        diagnosticsStorageAccountId=$(az storage account list -g $resourceGroupName --query "[?contains(name,'$diagnosticsStorageAccountName')].[id]" -o tsv)
        echo '"diagnosticsStorageAccountId": { "value": "'$diagnosticsStorageAccountId'" }' >> $jsonFile
        echo '}}' >> $jsonFile
fi

### Expected behavior

- Validate that a storage account exists or not.
- If it does not exist, proceed to create a storage account.

### Environment Summary

azure-cli                         2.38.0 *

core                              2.38.0 *
telemetry                          1.0.6 *

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3.6'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Oct 25 2023, 10:26:27)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

### Additional context

Please support us to solve the problem

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @giansototech please give the latest version of the CLI a try and see if the issue is resolved.
