### ISSUE TITLE
Unable to install for Ubuntu 24.04

### ISSUE THREAD

**Issue by dixonwille** [Azure/azure-cli#28872]
### Describe the bug

With Ubuntu 24.04 being released, I first checked to see if `noble` was available in https://packages.microsoft.com/repos/azure-cli/dists/. 

Since it is not available yet, I tried to use the install script instead `curl -L https://aka.ms/InstallAzureCli | bash`.

Using the defaults for everything in the script (not specifying any strange paths for install directory or bin directory), I receive an error.

### Related command

```
curl -L https://aka.ms/InstallAzureCli | bash
```

### Errors

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1405  100  1405    0     0   1981      0 --:--:-- --:--:-- --:--:--  228k
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_DELCpg.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_DELCpg: OK
Running install script.
-- Verifying Python version.
-- Python version 3.12.3 okay.
-- Verifying native dependencies.
-- Unable to verify native dependencies. dist=ubuntu, version=24.04. Continuing...

===> In what directory would you like to place the install? (leave blank to use '/home/wdixon/lib/azure-cli'):
-- Creating directory '/home/wdixon/lib/azure-cli'.
-- We will install at '/home/wdixon/lib/azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use '/home/wdixon/bin'):
-- Creating directory '/home/wdixon/bin'.
-- The executable will be in '/home/wdixon/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-16.7.11.tar.gz.
-- Downloaded virtualenv package to /tmp/tmp1d0rj52p/virtualenv-16.7.11.tar.gz.
-- Checksum of /tmp/tmp1d0rj52p/virtualenv-16.7.11.tar.gz OK.
-- Extracting '/tmp/tmp1d0rj52p/virtualenv-16.7.11.tar.gz' to '/tmp/tmp1d0rj52p'.
-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/wdixon/lib/azure-cli']
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/wdixon/lib/azure-cli/bin/python3
Also creating executable in /home/wdixon/lib/azure-cli/bin/python
ERROR: The executable /home/wdixon/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/wdixon/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_DELCpg", line 415, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_DELCpg", line 399, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/azure_cli_install_tmp_DELCpg", line 144, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/azure_cli_install_tmp_DELCpg", line 105, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/wdixon/lib/azure-cli']' returned non-zero exit status 100.
```

### Issue script & Debug output

N/A

### Expected behavior

I would expect to either setup the PPA or use the Install script to successfully get a working version of the Azure CLI.

### Environment Summary

```
$ python3 --version
Python 3.12.3

$ which python3
/usr/bin/python3

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by dixonwille** [comment]
While the bot did find a solution to my problem for now. With Ubuntu 24.04 being LTS and publicly released (no longer in preview), would love to see an official .deb package in the PPA (https://packages.microsoft.com/repos/azure-cli/dists/) with `noble` being supported.

**Comment by dixonwille** [comment]
@rakibmirza I wrote the following work around to get it installed. It assumes it is ran as root.

```shell
azureEnv="/usr/local/share/azure-cli-env"
python3 -m venv "$azureEnv"
"$azureEnv/bin/python" -m pip install --upgrade pip
"$azureEnv/bin/python" -m pip install --upgrade setuptools
"$azureEnv/bin/python" -m pip install azure-cli
ln -s "$azureEnv/bin/az" /usr/local/bin/az

```

**Comment by bebound** [comment]
The install script is deprecated.

We'll release a package for 24.04

**Comment by PriyankaRudramaina** [comment]
@bebound Do we have an ETA on this? If not do we have any workaround?

**Comment by bebound** [comment]
It will be released on May 21.

**Comment by dixonwille** [comment]
@PriyankaRudramaina 
> @bebound Do we have an ETA on this? If not do we have any workaround?

See this comment for a workaround I am currently using.

https://github.com/Azure/azure-cli/issues/28872#issuecomment-2093817749
