### ISSUE TITLE
Service Connector to SQL Database From Azure Function Failing

### ISSUE THREAD

**Issue by kayfilipp** [Azure/azure-cli#28870]
### Describe the bug

In a timer-triggered Azure Function with outbound traffic attached to a subnet in a virtual network, attempts to add a SQL database through the Service Connector tool result in an attributeError.

### Related command

`az functionapp connection create sql `

### Errors

`'Namespace' object has no attribute 'opt_out_list'`

### Issue script & Debug output
```
cli.knack.cli: Command arguments: ['functionapp', 'connection', 'create', 'sql', '--connection', 'sql_7a5b5', '--source-id', '/subscriptions/bf40b8f0-7520-4c77-8881-c9260465784c/resourceGroups/test-az-rg/providers/Microsoft.Web/sites/p10-test-az-func', '--target-id', '/subscriptions/bf40b8f0-7520-4c77-8881-c9260465784c/resourceGroups/p10-dev-rg/providers/Microsoft.Sql/servers/p10-dev-sqlserver/databases/FirmInsights', '--client-type', 'python', '--system-identity', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f1dfe115160>, <function OutputProducer.on_global_arguments at 0x7f1dfe02fca0>, <function CLIQuery.on_global_arguments at 0x7f1dfdfc6280>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'functionapp': ['azure.cli.command_modules.appservice', 'azure.cli.command_modules.serviceconnector', 'azext_serviceconnector_passwordless']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: appservice                0.142        79       270
cli.azure.cli.core: serviceconnector          0.066        20       299
cli.azure.cli.core: Total (2)                 0.207        99       569
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.076         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: serviceconnector-passwordless      0.043        14        20  /home/filipp/.azure/cliextensions/serviceconnector-passwordless
cli.azure.cli.core: Total (2)                 0.119        15        21  
cli.azure.cli.core: Loaded 98 groups, 570 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : functionapp connection create sql
cli.azure.cli.core: Command table: functionapp connection create sql
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f1dfd474700>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/filipp/.azure/commands/2024-05-01.20-04-35.functionapp_connection_create_sql.4009.log'.
az_command_data_logger: command args: functionapp connection create sql --connection {} --source-id {} --target-id {} --client-type {} --system-identity --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f1dfd41d310>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f1dfd446310>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f1dfd3e81f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f1dfe02fd30>, <function CLIQuery.handle_query_parameter at 0x7f1dfdfc6310>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f1dfd3e8160>]
az_command_data_logger: extension name: serviceconnector-passwordless
az_command_data_logger: extension version: 1.0.3
cli.azure.cli.core.commands: The behavior of this command has been altered by the following extension: serviceconnector-passwordless
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/invocation.py", line 113, in _validation
    self._validate_arg_level(parsed_ns)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 898, in _validate_arg_level
    validator(**self._build_kwargs(validator, ns))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/serviceconnector/_validators.py", line 886, in validate_params
    _validate_and_apply(validate_create_params, apply_create_params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/serviceconnector/_validators.py", line 868, in _validate_and_apply
    missing_args = validate(cmd, namespace)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/serviceconnector/_validators.py", line 633, in validate_create_params
    if not validate_opt_out_auth_and_config(namespace):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/serviceconnector/_validators.py", line 449, in validate_opt_out_auth_and_config
    opt_out_list = namespace.opt_out_list
AttributeError: 'Namespace' object has no attribute 'opt_out_list'

cli.azure.cli.core.azclierror: 'Namespace' object has no attribute 'opt_out_list'
az_command_data_logger: 'Namespace' object has no attribute 'opt_out_list'
```
### Expected behavior

The SQL Database Service Connection was created successfully.

### Environment Summary
```
azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.25.1
serviceconnector-passwordless               1.0.3
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/filipp/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal
```
### Additional context

# Service Connector Configuration
**Basics**
Service Type: `SQL Database`
Client Type: `Python`

**Authentication:**
`System Assigned Managed Identity`

**Network:**
`Configure Firewall Rules to enable access to target service`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
