### ISSUE TITLE
Zip deployment with parameter --clean set to false fails 

### ISSUE THREAD

**Issue by patrik-logistikbude** [Azure/azure-cli#28882]
### Describe the bug

When using az webapp deploy with the parameter `--clean` set to `false`, the deployment fails. 
Error message is `Zip deployment failed.` with status `3`. No status text is being provided.

### Related command

`az webapp deploy [...] --type zip --clean false`

### Errors

Zip deployment failed. {'id': 'xxx', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'OneDeploy', 'message': 'OneDeploy', 'progress': '', 'received_time': '2024-05-03T12:13:15.3324331Z', 'start_time': '2024-05-03T12:13:16.0838198Z', 'end_time': '2024-05-03T12:13:17.4588336Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'xxx', 'log_url': 'xxx', 'site_name': 'xxx', 'provisioningState': 'Failed'}. Please run the command az webapp log deployment show -n xxx -g zzz

### Issue script & Debug output

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 6783, in perform_onedeploy_webapp
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 7010, in _perform_onedeploy_internal
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 6968, in _make_onedeploy_request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 5628, in _check_zip_deployment_status

### Expected behavior

Successful deployment while maintaining old files

### Environment Summary

azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by seligj95** [comment]
> 🤖 **AI Triage Note** — This comment was generated by an AI agent and posted on behalf of @seligj95. If you have questions, please tag the App Service team directly.

We've confirmed this is a valid bug — `az webapp deploy --clean false` fails while `--clean true` works. We're investigating how the `clean` parameter is serialized in the OneDeploy API request.

We've prioritized this as **P1 High** and it's in our fix queue.

**Comment by seligj95** [comment]
> 🤖 **AI Triage Note** — This comment was generated by an AI agent and posted on behalf of @seligj95. If you have questions, please tag the App Service team directly.

**Update — Live reproduction on CLI v2.76.0:** We tested `az webapp deploy --type zip --clean false` and it completed successfully. This bug appears to be **fixed** in the current release.

Closing this issue. Please reopen if you're still experiencing this on the latest CLI version.
