### ISSUE TITLE
Error: No ML Server install Path found in SOFTWARE\Microsoft\R Server when using azure-ml-admin-cli

### ISSUE THREAD

**Issue by Muhammadyousafrana** [Azure/azure-cli#29051]
### Describe the bug

Encountering an error when attempting to use az login with the azure-ml-admin-cli extension. The error message indicates that no ML Server install path is found. Additionally, there are syntax warnings in mls_client.py.

### Related command

az login

### Errors

C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\mls_client.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if res.status is not 200 and res.status is not 201:
C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\mls_client.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if res.status is not 200 and res.status is not 201:
The command failed with an unexpected error. Here is the traceback:
No ML Server install Path found in SOFTWARE\Microsoft\R Server.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\_client_factory.py", line 83, in admin_extensions_client
    client = AdminExtensionsClient(endpoint, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\_client_factory.py", line 97, in __init__
    self._admin_client = AdminUtilClient(access_token)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\admin_util_client.py", line 35, in __init__
    o16n_path = PathContext().o16n_path
                ^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\path_context.py", line 30, in __init__
    raise EnvironmentError('No ML Server install Path found in '
OSError: No ML Server install Path found in SOFTWARE\Microsoft\R Server.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\mls_client.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if res.status is not 200 and res.status is not 201:
C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\mls_client.py:127: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if res.status is not 200 and res.status is not 201:
The command failed with an unexpected error. Here is the traceback:
No ML Server install Path found in SOFTWARE\Microsoft\R Server.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\_client_factory.py", line 83, in admin_extensions_client
    client = AdminExtensionsClient(endpoint, access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\_client_factory.py", line 97, in __init__
    self._admin_client = AdminUtilClient(access_token)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\clients\admin_util_client.py", line 35, in __init__
    o16n_path = PathContext().o16n_path
                ^^^^^^^^^^^^^
  File "C:\Users\muham\.azure\cliextensions\azure-ml-admin-cli\azext_admin\path_context.py", line 30, in __init__
    raise EnvironmentError('No ML Server install Path found in '
OSError: No ML Server install Path found in SOFTWARE\Microsoft\R Server.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Expected behavior

The az login command should successfully authenticate without errors related to ML Server.

### Environment Summary

OS: Windows
Azure CLI Version: (Provide the version from az --version)
azure-ml-admin-cli Version: (Provide the version from az extension show --name azure-ml-admin-cli)

### Additional context

Confirmed that ML Server is installed and path is correctly set in the registry.
Followed troubleshooting steps: syntax fix, reinstalling extension, updating CLI and extensions.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
