### ISSUE TITLE
Unable to unset Broker driven authentication when setting Allow_Broker=false or unsetting

### ISSUE THREAD

**Issue by romanrozinov** [Azure/azure-cli#29076]
### Describe the bug

I am currently unable to revert azure-cli to use traditional "az login" experience from using the Allow_Broker=true experimental feature.
I have attempted a few options to do this
Option 1
```
az config set core.allow_broker false
az account clear
az login
```
Option 2
```
az config unset core.allow_broker
az account clear
az login
```

Either option subsequent attempt to login ivokes modal UI
![image](https://github.com/Azure/azure-cli/assets/67590407/ca4707a2-8879-434d-a31f-bd70f79b8f09)
along with error in the command prompt,
![image](https://github.com/Azure/azure-cli/assets/67590407/03f70a9d-3079-4201-b77e-eb547752d6a2)

### Related command

```
az config unset core.allow_broker
az login
```

### Errors

![image](https://github.com/Azure/azure-cli/assets/67590407/bc7d767b-ea27-4093-8d45-ecf576d05905)

### Issue script & Debug output

output of `az config get core` with _allow_broker_ unset
```
Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Name                  Source                        Value
--------------------  ----------------------------  -------
first_run             C:\Users\rrozi\.azure\config  yes
output                C:\Users\rrozi\.azure\config  table
only_show_errors      C:\Users\rrozi\.azure\config  false
error_recommendation  C:\Users\rrozi\.azure\config  on
no_color              C:\Users\rrozi\.azure\config  false
disable_progress_bar  C:\Users\rrozi\.azure\config  false
```

output of the `az login --debug` command:
```
DEBUG: cli.knack.cli: Command arguments: ['login', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000016DF1543920>, <function OutputProducer.on_global_arguments at 0x0000016DF16C6160>, <function CLIQuery.on_global_arguments at 0x0000016DF16F3CE0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: profile                   0.006         2         8
DEBUG: cli.azure.cli.core: Total (1)                 0.006         2         8
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: Loaded 2 groups, 8 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : login
DEBUG: cli.azure.cli.core: Command table: login
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000016DF46123E0>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\rrozi\.azure\commands\2024-06-02.16-03-23.login.13560.log'.
INFO: az_command_data_logger: command args: login --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000016DF4646840>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000016DF4674860>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000016DF46749A0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000016DF16C6200>, <function CLIQuery.handle_query_parameter at 0x0000016DF16F3D80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000016DF4674900>]
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\rrozi\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\rrozi\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
INFO: msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/organizations
DEBUG: msal.authority: openid_config("https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? True
DEBUG: msal.application: Falls back to broker._signin_interactively()
WARNING: cli.azure.cli.core.auth.identity: Please select the account you want to log in with.
DEBUG: msal.broker: [MSAL:0001] WARNING SetAuthorityString:98   Initializing authority from string 'https://login.microsoftonline.com/organizations' without authority type, defaulting to MsSts
DEBUG: msal.broker: [MSAL:0002] INFO    SetCorrelationId:273    Set correlation ID: 6664fc8d-18cf-4940-941b-aeebb2b5e801
DEBUG: msal.broker: [MSAL:0002] INFO    ExecuteInteractiveRequest:1103  The original authority is 'https://login.microsoftonline.com/organizations'
DEBUG: msal.broker: [MSAL:0002] WARNING TryNormalizeRealm:2295  No HomeAccountId provided to normalize the realm
DEBUG: msal.broker: [MSAL:0002] INFO    ExecuteInteractiveRequest:1114  The normalized realm is ''
DEBUG: msal.broker: [MSAL:0002] INFO    ModifyAndValidateAuthParameters:191     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
DEBUG: msal.broker: [MSAL:0002] INFO    ModifyAndValidateAuthParameters:191     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
DEBUG: msal.broker: [MSAL:0002] INFO    ModifyAndValidateAuthParameters:215     Authority Realm: organizations
DEBUG: msal.broker: [MSAL:0003] WARNING ReturnResponseDueToMissingParameter:643 Attempted to read cache with a non-normalized realm, access token and ID token reads will fail
DEBUG: msal.broker: [MSAL:0003] WARNING ReadAccountById:227     Account id is empty - account not found
DEBUG: msal.broker: [MSAL:0004] INFO    ErrorInternalImpl:116   Created an error: 55xnk, StatusInternal::UserCanceled, InternalEvent::None, Context 'User cancelled the Accounts Control Operation.'
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:383    Printing Telemetry for Correlation ID: 6664fc8d-18cf-4940-941b-aeebb2b5e801
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: start_time, Value: 2024-06-02T23:03:23.000Z
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: api_name, Value: SignInInteractively
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: was_request_throttled, Value: false
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: authority_type, Value: Unknown
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: msal_version, Value: 1.1.0+local
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: api_status_code, Value: StatusInternal::UserCanceled
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: client_id, Value: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: correlation_id, Value: 6664fc8d-18cf-4940-941b-aeebb2b5e801
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: broker_app_used, Value: true
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: stop_time, Value: 2024-06-02T23:03:23.000Z
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: all_error_tags, Value: 55xnk
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: msalruntime_version, Value: 0.14.2-alpha1
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: original_authority, Value: https://login.microsoftonline.com/organizations
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: additional_query_parameters_count, Value: 2
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: read_token_last_error, Value: missing required parameter
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: request_eligible_for_broker, Value: true
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: auth_flow, Value: Broker
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: ui_event_count, Value: 1
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: authorization_type, Value: Interactive
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: api_error_code, Value: 0
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: api_error_tag, Value: 55xnk
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: api_error_context, Value: User cancelled the Accounts Control Operation.
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: is_successful, Value: false
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:391    Key: request_duration, Value: 88
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:396    Printing Execution Flow:
DEBUG: msal.broker: [MSAL:0004] INFO    LogTelemetryData:404    {"t":"646u1","tid":2,"ts":0,"l":2},{"t":"4s7ub","tid":2,"ts":1,"l":2},{"t":"4sufd","tid":2,"ts":2,"s":2,"l":2},{"t":"4swgg","tid":2,"ts":2,"s":1,"l":2},{"t":"4swgf","tid":2,"ts":2,"s":1,"l":2},{"t":"4swgi","tid":3,"ts":2,"s":1,"l":2},{"t":"8dqim","tid":3,"ts":2,"l":2},{"t":"8dqkl","tid":3,"ts":3,"l":2,"a":9,"ie":0},{"t":"54uxd","tid":2,"ts":5,"l":2},{"t":"8dqkn","tid":4,"ts":80,"l":2,"a":5,"ie":1},{"t":"8dqko","tid":4,"ts":80,"l":2,"a":9,"ie":1},{"t":"646u1","tid":4,"ts":80,"l":2}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 158, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 172, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 166, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/util.py", line 139, in check_result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/util.py", line 43, in aad_error_handler
azure.cli.core.azclierror.AuthenticationError: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210

ERROR: cli.azure.cli.core.azclierror: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210
ERROR: az_command_data_logger: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210
Please explicitly log in with:
az login
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000016DF4612660>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 0.930 seconds (init: 0.521, invoke: 0.409)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 4680 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\rrozi\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

I'd expect the azure cli to revert its behavior to default experience.

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
authV2                             0.1.2
azure-devops                      0.25.0
init                               0.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\rrozi\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Please use `az config set core.enable_broker_on_windows=false`
Ref: https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively#sign-in-with-web-account-manager-wam-on-windows

**Comment by romanrozinov** [comment]
That did the trick.  Thank you. 

I also had issues with our corporate VPN routing which may have been the root cause of wam broker auth not working in the first place.
