### ISSUE TITLE
Cannot create compute image from VM with PremiumV2_LRS disks

### ISSUE THREAD

**Issue by jmurphy-asurity** [Azure/azure-cli#29091]
### Describe the bug

Cannot create compute image from VM with PremiumV2_LRS disks. There does not appear to be any other way to create a scale set with a pre-populated PremiumV2_LRS data disk.

### Related command

```
az sig image-version create --resource-group MyRg \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.2.0 \
--virtual-machine /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/virtualMachines/my-vm-with-v2ssd-data
```

### Errors

```
(InternalOperationError) Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
Code: InternalOperationError
Message: Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
```

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['sig', 'image-version', 'create', '--resource-group', 'MyRg', '--gallery-name', 'MyGallery', '--gallery-image-definition', 'MyImage', '--gallery-image-version', '1.2.0', '--virtual-machine', '/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/virtualMachines/my-vm-with-v2ssd-data', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fd862e653f0>, <function OutputProducer.on_global_arguments at 0x7fd862dc8310>, <function CLIQuery.on_global_arguments at 0x7fd862be5510>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'sig': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.184        57       239
cli.azure.cli.core: Total (1)                 0.184        57       239
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 57 groups, 239 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : sig image-version create
cli.azure.cli.core: Command table: sig image-version create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fd861fa3010>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/.azure/commands/2024-06-04.16-37-06.sig_image-version_create.3264306.log'.
az_command_data_logger: command args: sig image-version create --resource-group {} --gallery-name {} --gallery-image-definition {} --gallery-image-version {} --virtual-machine {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fd861fc3d00>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fd862009a20>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fd862009b40>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fd862dc83a0>, <function CLIQuery.handle_query_parameter at 0x7fd862be55a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fd862009ab0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: .azure/msal_http_cache.bin
msal.application: Broker enabled? False
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: c15397ab-5bd8-41a7-a164-5fdcbc950cc6
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/MyRg?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'add2771f-2290-11ef-a3ee-9b5be111769b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sig image-version create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --gallery-name --gallery-image-definition --gallery-image-version --virtual-machine --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (DEB) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Linux-5.15.0-1051-azure-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/MyRg?api-version=2022-09-01 HTTP/1.1" 200 248
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '248'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3cfeae85-f79c-4da4-8541-5676116f554f'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '3cfeae85-f79c-4da4-8541-5676116f554f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20240604T163706Z:3cfeae85-f79c-4da4-8541-5676116f554f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 215F6F093EBD4ECF9DB4133B606F138C Ref B: BN1AA2051012039 Ref C: 2024-06-04T16:37:06Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 04 Jun 2024 16:37:05 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg","name":"MyRg","type":"Microsoft.Resources/resourceGroups","location":"eastus2","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: d1804df8-d976-45af-aa97-e30f4e04b625
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/galleries/MyGallery/images/MyImage/versions/1.2.0?api-version=2022-03-03'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '308'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'add2771f-2290-11ef-a3ee-9b5be111769b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sig image-version create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --gallery-name --gallery-image-definition --gallery-image-version --virtual-machine --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (DEB) azsdk-python-azure-mgmt-compute/30.0.0 Python/3.10.10 (Linux-5.15.0-1051-azure-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "eastus2", "tags": {}, "properties": {"publishingProfile": {"targetRegions": [{"name": "eastus2"}]}, "storageProfile": {"source": {"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/virtualMachines/my-vm-with-v2ssd-data"}}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/galleries/MyGallery/images/MyImage/versions/1.2.0?api-version=2022-03-03 HTTP/1.1" 200 1324
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1324'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Retry-After': '60'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus2/capsOperations/ac5016eb'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/CreateUpdateGalleryImageVersion3Min;374,Microsoft.Compute/CreateUpdateGalleryImageVersion30Min;1198'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362,867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ac5016eb-4c3c-43e5-a527-59740453feb4'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c6af3645-cc44-4469-802d-18f4c690c2e0'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20240604T163707Z:c6af3645-cc44-4469-802d-18f4c690c2e0'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: EE1F1019643A4C1EAD95FF976C622224 Ref B: BN1AA2051015037 Ref C: 2024-06-04T16:37:07Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 04 Jun 2024 16:37:07 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "1.2.0",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/galleries/MyGallery/images/MyImage/versions/1.2.0",
  "type": "Microsoft.Compute/galleries/images/versions",
  "location": "eastus2",
  "tags": {},
  "properties": {
    "publishingProfile": {
      "targetRegions": [
        {
          "name": "East US 2",
          "regionalReplicaCount": 1,
          "storageAccountType": "Standard_LRS"
        }
      ],
      "replicaCount": 1,
      "excludeFromLatest": false,
      "publishedDate": "2024-06-04T16:19:48.5492871+00:00",
      "storageAccountType": "Standard_LRS"
    },
    "storageProfile": {
      "source": {
        "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Compute/virtualMachines/my-vm-with-v2ssd-data"
      },
      "osDiskImage": {
        "hostCaching": "ReadWrite",
        "source": {}
      },
      "dataDiskImages": [
        {
          "lun": 0,
          "hostCaching": "None"
        }
      ]
    },
    "safetyProfile": {
      "reportedForPolicyViolation": false,
      "allowDeletionOfReplicatedLocations": false
    },
    "provisioningState": "Updating"
  }
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus2/capsOperations/ac5016eb'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'add2771f-2290-11ef-a3ee-9b5be111769b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sig image-version create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --gallery-name --gallery-image-definition --gallery-image-version --virtual-machine --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (DEB) azsdk-python-azure-mgmt-compute/30.0.0 Python/3.10.10 (Linux-5.15.0-1051-azure-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus2/capsOperations/ac5016eb HTTP/1.1" 200 133
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '133'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Retry-After': '60'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperationStatus3Min;4999,Microsoft.Compute/GetOperationStatus30Min;14996'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362,867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '86130881-7269-46ea-9023-3fcd4ca6cb28'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8db0a0bf-8625-452d-bb2a-567458cc6f73'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20240604T163707Z:8db0a0bf-8625-452d-bb2a-567458cc6f73'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 9EA0EF33FFEC46ECA65C0717D296D9D9 Ref B: BN1AA2051015037 Ref C: 2024-06-04T16:37:07Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 04 Jun 2024 16:37:07 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "startTime": "2024-06-04T16:37:07.795126+00:00",
  "status": "InProgress",
  "name": "ac5016eb-4c3c-43e5-a527-59740453feb4"
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus2/capsOperations/ac5016eb'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'add2771f-2290-11ef-a3ee-9b5be111769b'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sig image-version create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --gallery-name --gallery-image-definition --gallery-image-version --virtual-machine --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (DEB) azsdk-python-azure-mgmt-compute/30.0.0 Python/3.10.10 (Linux-5.15.0-1051-azure-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus2/capsOperations/ac5016eb HTTP/1.1" 200 353
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '353'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Retry-After': '480'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperationStatus3Min;4997,Microsoft.Compute/GetOperationStatus30Min;14994'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-served-by': '867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362,867fc4d0-09e1-4e91-b5b8-a7800b6bf3c5_133609702250876362'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e64f906a-0125-43fa-bfab-5bf27ff2557f'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '544aea21-8dbc-4857-90d2-e41f210b9e8e'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20240604T163808Z:544aea21-8dbc-4857-90d2-e41f210b9e8e'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 728B7315ACBF44E4886AC93F3B2FB463 Ref B: BN1AA2051015037 Ref C: 2024-06-04T16:38:08Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 04 Jun 2024 16:38:07 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "startTime": "2024-06-04T16:37:07.795126+00:00",
  "endTime": "2024-06-04T16:37:22.9358874+00:00",
  "status": "Failed",
  "error": {
    "code": "InternalOperationError",
    "message": "Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'."
  },
  "name": "ac5016eb-4c3c-43e5-a527-59740453feb4"
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 517, in run
    self._poll()
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 557, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 1013, in __call__
    raise exception
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/opt/az/lib/python3.10/site-packages/azure/core/polling/base_polling.py", line 535, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (InternalOperationError) Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
Code: InternalOperationError
Message: Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.

cli.azure.cli.core.azclierror: (InternalOperationError) Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
Code: InternalOperationError
Message: Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
az_command_data_logger: (InternalOperationError) Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
Code: InternalOperationError
Message: Replication failed in this region due to 'Snapshots of PremiumV2_LRS disks are not supported.'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fd861fa3250>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 62.725 seconds (init: 0.179, invoke: 62.546)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3877 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py .azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Expected an image version I can use with a scale set.

### Environment Summary

```
az --version
azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jmurphy\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by danielmarker** [comment]
Issue is present via the portal also and is blocking consumption of V2 SSDs for Customers.

**Comment by remyBerrebi-fi** [comment]
I can confirm the issue is still here. Any news ?
