### ISSUE TITLE
az ml update error: "NameError: name 'select_load_function' is not defined"

### ISSUE THREAD

**Issue by alexmpm** [Azure/azure-cli#29168]
### Describe the bug

Tryng up update my AML WS following the [AML documentation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-training-vnet?view=azureml-api-2&tabs=cli%2Crequired#compute-instancecluster-with-public-ip), getting an error "name 'select_load_function' is not defined". 
![image](https://github.com/Azure/azure-cli/assets/71778727/a5b477d5-7c0f-477c-87fd-949002da4310)

Tried from my computer terminal and also from the Azure Cloud Shell - same behaviour. Just installed the ml extension on my computer, so using the last version "2.26.1"

### Related command

az ml workspace update -n <wsname> -g <rgname> --file <filename>.yml 

### Errors

The command failed with an unexpected error. Here is the traceback:
name 'select_load_function' is not defined
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 453, in cached_put
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in _put_operation
  File "C:\Users\almeneze\.azure\cliextensions\ml\azext_mlv2\manual\custom\workspace.py", line 212, in ml_workspace_update
    workspace = select_load_function()(file, params_override=params_override)
                ^^^^^^^^^^^^^^^^^^^^
NameError: name 'select_load_function' is not defined

### Issue script & Debug output

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: name 'select_load_function' is not defined
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 453, in cached_put
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in _put_operation
  File "C:\Users\almeneze\.azure\cliextensions\ml\azext_mlv2\manual\custom\workspace.py", line 212, in ml_workspace_update
    workspace = select_load_function()(file, params_override=params_override)
                ^^^^^^^^^^^^^^^^^^^^
NameError: name 'select_load_function' is not defined
az_command_data_logger: name 'select_load_function' is not defined
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 453, in cached_put
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 447, in _put_operation
  File "C:\Users\almeneze\.azure\cliextensions\ml\azext_mlv2\manual\custom\workspace.py", line 212, in ml_workspace_update
    workspace = select_load_function()(file, params_override=params_override)
                ^^^^^^^^^^^^^^^^^^^^
NameError: name 'select_load_function' is not defined

### Expected behavior

My AML workspace would be updated and I would get a confirmation message

### Environment Summary

Python 3.9.19
azure-cli                         2.61.0
core                              2.61.0
telemetry                          1.1.0
Extensions:
ai-examples                        0.2.5
ml                                2.26.1
ssh                                2.0.3
Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by alexmpm** [comment]
https://github.com/Azure/azure-cli/issues/29168#issuecomment-2167915525
It is not possible to downgrade packages while using Azure cloud shell. So the solution proposed does not work for me

**Comment by alexmpm** [comment]
> Hi @alexmpm Find similar issue #29148.
> 
> Issue title	Update Build machine in AzureML Workspace
> Create time	2024-06-11
> Comment number	0
> Possible solution: As mentioned in that issue, downgrading the `ml` extension version from 2.26.1 to 2.25.0 might resolve the error. You can try downgrading the extension version and see if it resolves the issue.
> 
> Please confirm if this resolves your issue.
It is not possible to downgrade packages while using Azure cloud shell. So the proposed solution does not work for me

**Comment by diondrapeck** [comment]
@alexmpm - This will be fixed in the 2.27.0 release for ml cli.
