### ISSUE TITLE
Cannot Attach Multiple Load balancer Front End IP Configurations to an Existing Private Link Service (PLS)

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [Azure/azure-cli#29305]
### Describe the bug

Tried the following command to attach an additional load balancer front end IP configuration.

```
az network private-link-service update --lb-frontend-ip-configs <lb frontend cofig1> <lb frontend config2>  -g <resource group> -n <name of the private link service>
```

This resulted the following error.

```
(InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified) Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
Code: InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified
Message: Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
```

However, the [docs](--lb-frontend-ip-configs) state that we can provide space separated list of IP configurations with `--lb-frontend-ip-configs` option 

### Related command

az network private-link-service update

### Errors

(InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified) Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
Code: InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified
Message: Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['network', 'private-link-service', 'update', '--lb-frontend-ip-configs', <lb frontend cofig1> <lb frontend config2>, '-g', '<resource group>, '-n', '<PLS name>', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101e8d6c0>, <function OutputProducer.on_global_arguments at 0x101f38900>, <function CLIQuery.on_global_arguments at 0x101f663e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_bastion']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.365       115       360
cli.azure.cli.core: privatedns                0.009        14        60
cli.azure.cli.core: Total (2)                 0.374       129       420
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: bastion                   0.005         2         4  /Users/sachithka/.azure/cliextensions/bastion
cli.azure.cli.core: Total (1)                 0.005         2         4  
cli.azure.cli.core: Loaded 129 groups, 424 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network private-link-service update
cli.azure.cli.core: Command table: network private-link-service update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x102ca7420>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/sachithka/.azure/commands/2024-07-03.10-20-54.network_private-link-service_update.6535.log'.
az_command_data_logger: command args: network private-link-service update --lb-frontend-ip-configs {} {} -g {} -n {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102cd9ee0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x102d30180>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x102d302c0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x101f389a0>, <function CLIQuery.handle_query_parameter at 0x101f66480>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x102d30220>]
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/sachithka/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/sachithka/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/<tenanat ID>
msal.authority: openid_config("https://login.microsoftonline.com/<tenanat ID>/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/<tenanat ID>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<tenanat ID>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<tenanat ID>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<tenanat ID>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<tenanat ID>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<tenanat ID>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<tenanat ID>/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: ffc9d37c-a287-40ae-80dc-24cb46c2f62a
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.Network/privateLinkServices/<PLS name>?api-version=2022-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'd4643426-38f7-11ef-97b4-ee4c9e21041d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network private-link-service update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--lb-frontend-ip-configs -g -n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.61.0 (HOMEBREW) azsdk-python-core/1.28.0 Python/3.11.9 (macOS-14.5-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<subscription ID>/resourceGroups/<resource group>/providers/Microsoft.Network/privateLinkServices/<PLS name>?api-version=2022-01-01 HTTP/1.1" 200 4893
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '4893'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': 'W/"b8e32dfa-5673-4936-8fda-d6c483f10e41"'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'cfc26d1d-81e1-4d97-b2c3-89fb740dbb7b'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '2d8fe038-a921-4845-bb9f-a981a82199bd'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '58367995-2805-4004-981a-6ef1ccdcc686'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '249'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '3749'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20240703T045055Z:2d8fe038-a921-4845-bb9f-a981a82199bd'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 1999FDB997F4442E9A8339D861297279 Ref B: MAA201060514039 Ref C: 2024-07-03T04:50:55Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 03 Jul 2024 04:50:55 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "<PLS name>",
  "id": "/subscriptions/<subscription ID>/resourceGroups/<resource group>/providers/Microsoft.Network/privateLinkServices/<PLS name>",
  "etag": "W/\"b8e32dfa-5673-4936-8fda-d6c483f10e41\"",
  "type": "Microsoft.Network/privateLinkServices",
  "location": "eastus2",
  "tags": {
    "environment": "dev",
    "project": "***",
    "purpose": "privatelinkservice",
    "terraform": "true"
  },
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "8dd67e81-37d3-4db6-837e-97d31fe1cdb6",
    "fqdns": [],
    "alias": "<pls name>.7d3998f1-7abd-4466-a723-3c6ec79c9a3c.eastus2.azure.privatelinkservice",
    "visibility": {
      "subscriptions": [
        "<visible subscription ID>"
      ]
    },
    "autoApproval": {
      "subscriptions": [
        "<visible subscription ID>"
      ]
    },
    "enableProxyProtocol": false,
    "loadBalancerFrontendIpConfigurations": [
      {
        "id": "/subscriptions/<subscription id>/resourceGroups/<kubernetes MC resource group>/providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/a594a43c3f83348998714866bd330823-<loadbalancer subnet>"
      }
    ],
    "ipConfigurations": [
      {
        "name": "Primary",
        "id": "/subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>/ipConfigurations/Primary",
        "etag": "W/\"b8e32dfa-5673-4936-8fda-d6c483f10e41\"",
        "type": "Microsoft.Network/privateLinkServices/ipConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "172.18.222.5",
          "privateIPAllocationMethod": "Static",
          "subnet": {
            "id": "/subscriptions/<subscription ID>/resourceGroups/<VNET rg>/providers/Microsoft.Network/virtualNetworks/<VNET name>/subnets/<PLS NAT IP subnet>"
          },
          "primary": true,
          "privateIPAddressVersion": "IPv4"
        }
      }
    ],
    "privateEndpointConnections": [
      {
        "name": "<private endpoint name>.6bfda7be-983e-4d11-b948-82b216f4d1e0",
        "id": "/subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>/privateEndpointConnections/c<private endpoint name>.6bfda7be-983e-4d11-b948-82b216f4d1e0",
        "etag": "W/\"b8e32dfa-5673-4936-8fda-d6c483f10e41\"",
        "properties": {
          "provisioningState": "Succeeded",
          "privateEndpoint": {
            "id": "/subscriptions/<visible subscription id>resourceGroups/c<visible subscription name>/providers/Microsoft.Network/privateEndpoints/<private endpoint name>"
          },
          "privateLinkServiceConnectionState": {
            "status": "Approved",
            "description": "Approved",
            "actionsRequired": "None"
          },
          "linkIdentifier": "553665006"
        },
        "type": "Microsoft.Network/privateLinkServices/privateEndpointConnections"
      },
      {
        "name": "<other private endpoint name>.4af65e8b-1e2c-47bf-b528-c983292539da",
        "id": "/subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/c<PLS name>/privateEndpointConnections/<other private endpoint name>.4af65e8b-1e2c-47bf-b528-c983292539da",
        "etag": "W/\"b8e32dfa-5673-4936-8fda-d6c483f10e41\"",
        "properties": {
          "provisioningState": "Succeeded",
          "privateEndpoint": {
            "id": "/subscriptions/<visible subscription ID>/resourceGroups/<visible subscription name>/providers/Microsoft.Network/privateEndpoints/<other private endpoint name>"
          },
          "privateLinkServiceConnectionState": {
            "status": "Approved",
            "description": "Auto Approved",
            "actionsRequired": "None"
          },
          "linkIdentifier": "553679386"
        },
        "type": "Microsoft.Network/privateLinkServices/privateEndpointConnections"
      }
    ],
    "networkInterfaces": [
      {
        "id": "/subscriptions/<subscription ID>/resourceGroups/<PLS rg>/providers/Microsoft.Network/networkInterfaces/<PLS name>.nic.be2744cd-3a28-4e4e-a837-d04818d13ebe"
      }
    ]
  }
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subscription ID>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>?api-version=2022-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1771'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'd4643426-38f7-11ef-97b4-ee4c9e21041d'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network private-link-service update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--lb-frontend-ip-configs -g -n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.61.0 (HOMEBREW) azsdk-python-core/1.28.0 Python/3.11.9 (macOS-14.5-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"id": "/subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>", "location": "eastus2", "properties": {"autoApproval": {"subscriptions": ["<visible subscription id>"]}, "enableProxyProtocol": false, "fqdns": [], "ipConfigurations": [{"id": "/subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>/ipConfigurations/Primary", "name": "Primary", "properties": {"primary": true, "privateIPAddress": "172.18.222.5", "privateIPAddressVersion": "IPv4", "privateIPAllocationMethod": "Static", "subnet": {"id": "/subscriptions/<subscription id>/resourceGroups/<VNET rg>/providers/Microsoft.Network/virtualNetworks/<VNET name>/subnets/<NAT IP subnet>"}}}], "loadBalancerFrontendIpConfigurations": [{"id": "/subscriptions/<subscription id>/resourceGroups/<MC AKS rg (first)>/providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/a594a43c3f83348998714866bd330823-<loadbalancer subnet>"}, {"id": "/subscriptions/<subscription id>/resourceGroups/<MC AKS rg (second)>/providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/a23dfbc79f7834c7fb4e5e2ab3f2a53f-<loadbalancer subnet(second)>"}], "visibility": {"subscriptions": ["<visible subscription id>"]}}, "tags": {"environment": "dev", "project": "***", "purpose": "privatelinkservice", "terraform": "true"}}
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<subscription id>/resourceGroups/<PLS rg>/providers/Microsoft.Network/privateLinkServices/<PLS name>?api-version=2022-01-01 HTTP/1.1" 400 362
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '362'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '1a9f172f-4ba9-420f-a73e-02f03fcb2663'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '38c460b9-5e18-4e83-8936-a2e56066fff5'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': 'a1e9ca9a-ddb8-4762-9888-527228f977d0'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20240703T045056Z:38c460b9-5e18-4e83-8936-a2e56066fff5'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 1CB3ED33AB61459D9D1D5B4873B9D9F7 Ref B: MAA201060514039 Ref C: 2024-07-03T04:50:55Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 03 Jul 2024 04:50:56 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified",
    "message": "Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.",
    "details": []
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 1052, in __call__
    raise exception
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 1039, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/network/aaz/latest/network/private_link_service/_update.py", line 1138, in _execute_operations
    yield self.PrivateLinkServicesCreateOrUpdate(ctx=self.ctx)()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/network/aaz/latest/network/private_link_service/_update.py", line 1269, in __call__
    return self.on_error(session.http_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified) Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
Code: InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified
Message: Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.

cli.azure.cli.core.azclierror: (InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified) Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
Code: InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified
Message: Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
az_command_data_logger: (InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified) Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
Code: InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified
Message: Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service <PLS name> has 2 load balancer frontend IP configurations specified.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x102ca76a0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.532 seconds (init: 0.095, invoke: 2.437)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4530 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.61.0/libexec/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /Users/sachithka/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

According to the docs it should allow us to provide multiple IP configurations with `--lb-frontend-ip-configs` option

### Environment Summary

```
azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
aks-preview                      5.0.0b3
bastion                            1.0.1
ssh                                2.0.4

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.61.0/libexec/bin/python'
Extensions directory '/Users/sachithka/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
