### ISSUE TITLE
pythom

### ISSUE THREAD

**Issue by shaddad2189** [Azure/azure-cli#29315]
### Describe the bug

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    subscriptions = profile.login(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 177, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 189, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/auth/msal_authentication.py", line 132, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/application.py", line 516, in __init__
    self.authority = Authority(
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/authority.py", line 95, in __init__
    raise ValueError(error_message)

### Related command

az login 

### Errors

az login --service-principal --username *** --password *** --tenant ***

### Issue script & Debug output

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    subscriptions = profile.login(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/_profile.py", line 177, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/auth/identity.py", line 189, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/auth/msal_authentication.py", line 132, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/application.py", line 516, in __init__
    self.authority = Authority(
  File "/usr/lib64/az/lib/python3.9/site-packages/msal/authority.py", line 95, in __init__
    raise ValueError(error_message)

### Expected behavior

I Was trying to connect direct to an authorized graph api app that I configured and it was throwing errors and weird syntax issues

### Environment Summary

azure cli + graph api ext

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Could you share the full error message?
