### ISSUE TITLE
Arm64 Windows support

### ISSUE THREAD

**Issue by dmal-msft** [Azure/azure-cli#29317]
Is there a plan for support of az cli on windows arm64?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
This is not feasible unless we have a build and test env and all dependencies support Windows on ARM.

**Comment by soerennielsen** [comment]
Also wanting this one. 

@bebound: Sure. So which are missing now?

**Comment by bebound** [comment]
> Also wanting this one.
> 
> @bebound: Sure. So which are missing now?

All.

**Comment by causer** [comment]
Hello, can you please give an update on the issue? Any plans, estimates? Thank you.

**Comment by soerennielsen** [comment]
It seems that at least the build part should be fully supported now: https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

**Comment by bebound** [comment]
@soerennielsen Thanks for the info.
I doubt there is windows ARM runner image with pre-installed build tools: https://github.com/actions/runner-images/issues/10820#issuecomment-2615760866, https://github.com/actions/partner-runner-images/issues/19

**Comment by argium** [comment]
Hitting this on my arm64 Surface laptop.
```
> az login
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 13, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 19, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/telemetry/__init__.py", line 9, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/__init__.py", line 4, in <module>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\portalocker/portalocker.py", line 11, in <module>
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```

**Comment by bramsdell-ms** [comment]
@bebound The issue for the arm64 runner looks like it's been resolved, does that help?

**Comment by bebound** [comment]
Not sure if we can create ARM VM in 1ES.

The other two prerequisites remain:
- We don't have arm64 device for testing/development
- Not all dependencies provide win_arm64 wheel. For example: https://pypi.org/project/pymsalruntime/#files

**Comment by vcfvct** [comment]
@bebound any way we can contact msal team for this? 
I recently got a snapdragon Surface laptop 7, I can do the testing if need.(alias hanli3 ).

**Comment by mjsabby** [comment]
@bebound you can create ARM64 images in 1ES. ARM64 wheel for pymsal is also available. Can we get on this? @yanrez ARM64 blocker you may be interested in.

**Comment by bebound** [comment]
There are dependencies that does not support win arm64: https://pypi.org/project/cryptography/#files

**Comment by yanrez** [comment]
Relevant: https://github.com/pyca/cryptography/issues/14293

**Comment by mjsabby** [comment]
Looks like maybe 46.0 has it? https://github.com/platformio/platform-espressif32/issues/1742 Will need to check.

**Comment by yanrez** [comment]
@bebound  do you know full list of dependencies you are missing, besides cryptography ?

**Comment by dennisameling** [comment]
The cryptography maintainers have re-added Windows arm64 as a supported platform and will start releasing prebuilt wheels again in version 51 (which hasn't been released yet): https://github.com/pyca/cryptography/pull/15350

In that same PR, someone [said](https://github.com/pyca/cryptography/pull/15350#issuecomment-5425140394) that 46.0.3 was the last version to have Windows arm64 wheels before they had to take it out due to GH Actions CI issues. So for cryptography that means either <=46.0.3 or >=51.0.0 for Windows arm64 support.
