### ISSUE TITLE
Error with az webapp config appsettings set

### ISSUE THREAD

**Issue by ts0491** [Azure/azure-cli#29343]
### Describe the bug

When executing the below Azure CLI from the CloudShell to enable App Insights for an App Service (Shared tier) in East US2:

instrumentationKey=$(az monitor app-insights component show --app appi..... --resource-group .... --query  "instrumentationKey"  | cut -f2 -d"\"")

az webapp config appsettings set --name app-.... --resource-group .... \
     --settings APPINSIGHTS_INSTRUMENTATIONKEY=$instrumentationKey APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=$instrumentationKey \ 
     ApplicationInsightsAgent_EXTENSION_VERSION=~2 

I get the following:
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 574, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 503, in update_app_settings
    temp = shell_safe_json_parse(s)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 600, in shell_safe_json_parse
    raise InvalidArgumentValueError(msg, recommendation=recommendation) from json_ex
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
 
Error detail: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 514, in update_app_settings
    setting_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

### Related command

az webapp config appsettings set 

### Errors

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 503, in update_app_settings
    temp = shell_safe_json_parse(s)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 600, in shell_safe_json_parse
    raise InvalidArgumentValueError(msg, recommendation=recommendation) from json_ex
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
 
Error detail: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 514, in update_app_settings
    setting_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

### Issue script & Debug output

instrumentationKey=$(az monitor app-insights component show --app appi..... --resource-group .... --query  "instrumentationKey"  | cut -f2 -d"\"")

az webapp config appsettings set --name app-.... --resource-group .... \
     --settings APPINSIGHTS_INSTRUMENTATIONKEY=$instrumentationKey APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=$instrumentationKey \ 
     ApplicationInsightsAgent_EXTENSION_VERSION=~2 

### Expected behavior

Successfully enabling App Insights for the App Service.  This did work at one point the day before.

### Environment Summary

azure-cli                         2.61.0 *

core                              2.61.0 *
telemetry                          1.1.0

Extensions:
account                            0.2.5
ai-examples                        0.2.5
application-insights               1.2.1
bastion                            1.0.1
ml                                2.26.1
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/home/norbert/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ts0491** [comment]
Seems like user error.  Did not realize that entry had to be JSON.  Working on it now.  I would recommend better error messaging, however.

**Comment by ts0491** [comment]
Confirmed.  All worked well once converted to JSON format input.
