### ISSUE TITLE
vnet-integration add fails with Site.FunctionAppConfig is invalid

### ISSUE THREAD

**Issue by Joelith** [Azure/azure-cli#29410]
### Describe the bug

When running this command `az functionapp vnet-integration add --<function name> --vnet <vnet name> --subnet <subnet name> -g <group>` it errors with:
```
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.","Target":null,"Details":[{"Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Site.FunctionAppConfig","It is only supported for 2023-12-01 api-version or newer."],"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."}}],"Innererror":null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
    raise ex
knack.util.CLIError: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.

cli.azure.cli.core.azclierror: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
az_command_data_logger: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
```
I've run with debug and verbose and nothing actually tells me what is wrong with the function definition. If I run this command in the UI portal it executes no problems. My local.settings.json for this function is effectively empty:
```
{
  "IsEncrypted": false,
  "Values": {
  }
}
```
Is there anyway to actually see what the issue is?

### Related command

az functionapp vnet-integration add --<function name> --vnet <vnet name> --subnet <subnet name> -g <group>

### Errors

az_command_data_logger: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.

### Issue script & Debug output

azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.","Target":null,"Details":[{"Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Site.FunctionAppConfig","It is only supported for 2023-12-01 api-version or newer."],"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."}}],"Innererror":null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
    raise ex
knack.util.CLIError: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.

cli.azure.cli.core.azclierror: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
az_command_data_logger: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.

### Expected behavior

Either this command should just work or it should actually tell me what the issue is. saying the configuration is invalid and then not actually telling me which part it doesn't like is not very helpful

### Environment Summary

azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
aks-preview                      6.0.0b1
containerapp                      0.3.53
front-door                         1.2.0
webpubsub                          1.4.0

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.62.0/libexec/bin/python'
Extensions directory '/Users/joelnation/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by pete-intranel** [comment]
I have also seen the described issue, as well as with the following command:
`az functionapp update --name $(appName) -g $(resourceGroup) --set publicNetworkAccess=Disabled`

The function is using a flex consumption plan.

When run as a "AzureCLI@2" script in Azure DevOps using pscore, I get the following error:
```
/usr/bin/az --version
azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1
...
Your CLI is up-to-date.
...
ERROR: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.

If using '--plan', a consumption plan may be unable to migrate to a given premium plan. Please confirm that the premium plan exists in the same resource group and region. Note: Not all functionapp plans support premium instances. If you have verified your resource group and region and are still unable to migrate, please redeploy on a premium functionapp plan.
```

If I run it from an Azure CloudShell instance, it succeeds without issue.

**Comment by rokicool** [comment]
In my configuration the same command:

`az functionapp vnet-integration add --resource-group <> --name <> --vnet <> --subnet <> --debug`

- fails with that "Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer." error when executed using service principal credentials.

OR

- works perfectly well when executed with my credentials. 

The permissions are the same: Contributor Role.

```
# az --version
azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.9.19 (main, Aug 23 2024, 00:08:10) 
[GCC 11.2.0]
```

**Comment by Boboltus** [comment]
I have the exact same problem when running this command: `az functionapp vnet-integration add --resource-group '$(resourceGroupName)' --name '$(functionAppName)' --subnet 'SubnetName' --vnet "/subscriptions/$(subscriptionId)/resourceGroups/$(virtualNetworkResourceGroupName)/providers/Microsoft.Network/virtualNetworks/$(virtualNetworkName)" --debug`

Response/output:
```
2024-10-18T08:32:05.3872755Z DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$functionAppName?api-version=2023-01-01'
2024-10-18T08:32:05.3873738Z DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'PUT'
2024-10-18T08:32:05.3874063Z DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
2024-10-18T08:32:05.3874503Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
2024-10-18T08:32:05.3874941Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '2090'
2024-10-18T08:32:05.3875374Z DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
2024-10-18T08:32:05.3875902Z DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '***'
2024-10-18T08:32:05.3876420Z DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'functionapp vnet-integration add'
2024-10-18T08:32:05.3876977Z DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --subnet --vnet --debug'
2024-10-18T08:32:05.3877786Z DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.64.0 (DEB) azsdk-python-core/1.28.0 Python/3.11.8 (Linux-6.5.0-1025-azure-x86_64-with-glibc2.35) VSTS_3778f03e-6991-4a59-9a3b-bc1508b80ce3_build_1069_0'
2024-10-18T08:32:05.3878367Z DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
2024-10-18T08:32:05.3878684Z DEBUG: cli.azure.cli.core.sdk.policies: Request body:
2024-10-18T08:32:05.3883362Z DEBUG: cli.azure.cli.core.sdk.policies: **
2024-10-18T08:32:07.0432803Z DEBUG: urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$functionAppName?api-version=2023-01-01 HTTP/1.1" 400 609
2024-10-18T08:32:07.0440651Z DEBUG: cli.azure.cli.core.sdk.policies: Response status: 400
2024-10-18T08:32:07.0441217Z DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
2024-10-18T08:32:07.0445443Z DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
2024-10-18T08:32:07.0449584Z DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
2024-10-18T08:32:07.0450201Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '609'
2024-10-18T08:32:07.0450716Z DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
2024-10-18T08:32:07.0460425Z DEBUG: cli.azure.cli.core.sdk.policies: Response content:
2024-10-18T08:32:07.0462161Z DEBUG: cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.","Target":null,"Details":[{"Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Site.FunctionAppConfig","It is only supported for 2023-12-01 api-version or newer."],"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."}}],"Innererror":null}
2024-10-18T08:32:07.1329703Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
2024-10-18T08:32:07.1331669Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
2024-10-18T08:32:07.1332187Z     result = cmd_copy(params)
2024-10-18T08:32:07.1332529Z              ^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1333000Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
2024-10-18T08:32:07.1333426Z     return self.handler(*args, **kwargs)
2024-10-18T08:32:07.1333759Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1334563Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2024-10-18T08:32:07.1335059Z     return op(**command_args)
2024-10-18T08:32:07.1335380Z            ^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1335924Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/appservice/custom.py", line 6308, in add_functionapp_vnet_integration
2024-10-18T08:32:07.1336466Z     return _add_vnet_integration(cmd, name, resource_group_name, vnet, subnet, slot, skip_delegation_check)
2024-10-18T08:32:07.1336889Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1337823Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/appservice/custom.py", line 6338, in _add_vnet_integration
2024-10-18T08:32:07.1338484Z     _generic_site_operation(cmd.cli_ctx, resource_group_name, name, 'begin_create_or_update', slot,
2024-10-18T08:32:07.1339197Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/appservice/_appservice_utils.py", line 21, in _generic_site_operation
2024-10-18T08:32:07.1339690Z     if extra_parameter is None else operation(resource_group_name,
2024-10-18T08:32:07.1340097Z                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1340578Z   File "/opt/az/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
2024-10-18T08:32:07.1341001Z     return func(*args, **kwargs)
2024-10-18T08:32:07.1341323Z            ^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1341899Z   File "/opt/az/lib/python3.11/site-packages/azure/mgmt/web/v2023_01_01/operations/_web_apps_operations.py", line 17008, in begin_create_or_update
2024-10-18T08:32:07.1342386Z     raw_result = self._create_or_update_initial(
2024-10-18T08:32:07.1343119Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1343755Z   File "/opt/az/lib/python3.11/site-packages/azure/mgmt/web/v2023_01_01/operations/_web_apps_operations.py", line 16870, in _create_or_update_initial
2024-10-18T08:32:07.1344599Z     raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
2024-10-18T08:32:07.1345234Z azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
2024-10-18T08:32:07.1346980Z Content: {"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.","Target":null,"Details":[{"Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.  {1}","Parameters":["Site.FunctionAppConfig","It is only supported for 2023-12-01 api-version or newer."],"Code":"BadRequest","Message":"Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer."}}],"Innererror":null}
2024-10-18T08:32:07.1348073Z 
2024-10-18T08:32:07.1348379Z During handling of the above exception, another exception occurred:
2024-10-18T08:32:07.1348541Z 
2024-10-18T08:32:07.1348852Z Traceback (most recent call last):
2024-10-18T08:32:07.1349367Z   File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
2024-10-18T08:32:07.1349783Z     cmd_result = self.invocation.execute(args)
2024-10-18T08:32:07.1350124Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1350585Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
2024-10-18T08:32:07.1350983Z     raise ex
2024-10-18T08:32:07.1351463Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
2024-10-18T08:32:07.1351924Z     results.append(self._run_job(expanded_arg, cmd_copy))
2024-10-18T08:32:07.1352281Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1352747Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 725, in _run_job
2024-10-18T08:32:07.1353172Z     return cmd_copy.exception_handler(ex)
2024-10-18T08:32:07.1353522Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-18T08:32:07.1354249Z   File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
2024-10-18T08:32:07.1354742Z     raise ex
2024-10-18T08:32:07.1355404Z knack.util.CLIError: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
2024-10-18T08:32:07.1355681Z 
2024-10-18T08:32:07.1358061Z ERROR: cli.azure.cli.core.azclierror: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
2024-10-18T08:32:07.1359109Z ERROR: az_command_data_logger: Site.FunctionAppConfig is invalid.  It is only supported for 2023-12-01 api-version or newer.
2024-10-18T08:32:07.1359648Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcacb776020>]

```

I've also tried doing the same thing via the AZ REST command, but that just results in a HTTP 500 (internal server error). That seems to be unrelated, but it might help solve the issue. And on top of this AZ REST command, I also tried it with Bicep, but that also response with the same HTTP 500 error.

```
$url = 'https://management.azure.com/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Web/sites/$(functionAppName)?api-version=2023-12-01'
$returnContent = @{
    properties = @{
       virtualNetworkSubnetId = "/subscriptions/$(subscriptionId)/resourceGroups/$(virtualNetworkResourceGroupName)/providers/Microsoft.Network/virtualNetworks/$(virtualNetworkName)/subnets/SubnetName"
    }
}

$body = $returnContent | ConvertTo-Json -Compress -Depth 5
      
az rest --method patch --url $url --body $body --headers "{'Content-Type': 'application/json'}"
```

Response/output:
```
ERROR: Internal Server Error(<Error><Message>An error has occurred.</Message></Error>)
```
