### ISSUE TITLE
CI fails because of setuptools change

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#29421]
MarkupSafe 2.0.1 and pycparser 2.19 fails to build.

I seems that it tried to build source code with wheel 0.30.0, but the source code is not compatible with wheel 0.30.0.
```
2024-07-18T03:38:39.8924845Z Building wheels for collected packages: MarkupSafe, pycparser
2024-07-18T03:38:39.8925107Z   Building wheel for MarkupSafe (setup.py): started
2024-07-18T03:38:39.8925480Z   Building wheel for MarkupSafe (setup.py): finished with status 'error'
2024-07-18T03:38:39.8925810Z   error: subprocess-exited-with-error
2024-07-18T03:38:39.8925999Z   
2024-07-18T03:38:39.8926307Z   × python setup.py bdist_wheel did not run successfully.
2024-07-18T03:38:39.8926577Z   │ exit code: 1
2024-07-18T03:38:39.8926831Z   ╰─> [27 lines of output]
2024-07-18T03:38:39.8927061Z       Traceback (most recent call last):
2024-07-18T03:38:39.8927300Z         File "<string>", line 2, in <module>
2024-07-18T03:38:39.8927649Z         File "<pip-setuptools-caller>", line 34, in <module>
2024-07-18T03:38:39.8928138Z         File "/tmp/pip-install-dviqlpkb/markupsafe_202a0ce88dd04bccaa8b4ccc00947489/setup.py", line 61, in <module>
2024-07-18T03:38:39.8928412Z           run_setup(True)
2024-07-18T03:38:39.8928847Z         File "/tmp/pip-install-dviqlpkb/markupsafe_202a0ce88dd04bccaa8b4ccc00947489/setup.py", line 41, in run_setup
2024-07-18T03:38:39.8929122Z           setup(
2024-07-18T03:38:39.8929525Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/__init__.py", line 106, in setup
2024-07-18T03:38:39.8929826Z           return distutils.core.setup(**attrs)
2024-07-18T03:38:39.8930040Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-18T03:38:39.8930463Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 171, in setup
2024-07-18T03:38:39.8930758Z           ok = dist.parse_command_line()
2024-07-18T03:38:39.8930953Z                ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-18T03:38:39.8931394Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 478, in parse_command_line
2024-07-18T03:38:39.8931715Z           args = self._parse_command_opts(parser, args)
2024-07-18T03:38:39.8931930Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-18T03:38:39.8932359Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/dist.py", line 876, in _parse_command_opts
2024-07-18T03:38:39.8932689Z           nargs = _Distribution._parse_command_opts(self, parser, args)
2024-07-18T03:38:39.8932925Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-18T03:38:39.8933380Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 537, in _parse_command_opts
2024-07-18T03:38:39.8933701Z           cmd_class = self.get_command_class(command)
2024-07-18T03:38:39.8933913Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-18T03:38:39.8934341Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/dist.py", line 715, in get_command_class
2024-07-18T03:38:39.8934672Z           from .command.bdist_wheel import bdist_wheel
2024-07-18T03:38:39.8935170Z         File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 29, in <module>
2024-07-18T03:38:39.8935483Z           from wheel.wheelfile import WheelFile
2024-07-18T03:38:39.8935847Z       ModuleNotFoundError: No module named 'wheel.wheelfile'
2024-07-18T03:38:39.8936073Z       [end of output]
```

Ref: https://dev.azure.com/azclitools/public/_build/results?buildId=173601&view=logs&jobId=168ccbe3-da49-5c0b-6478-08f7016e4bf5&j=168ccbe3-da49-5c0b-6478-08f7016e4bf5&t=5102475c-9f36-53bb-ee2b-856291a96d5a

Previous setuptools change: https://github.com/Azure/azure-cli/issues/27047

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
In 70.0.0 (https://github.com/Azure/azure-cli-extensions/pull/7739)
run `python setup.py bdist_wheel`: Use installed wheel (or install new)
Install package from source code: install latest wheel

After 70.1.0, in https://github.com/pypa/setuptools/pull/4369
run `python setup.py bdist_wheel`： use vendored wheel
Install package from source code: install latest wheel

After 71.0.0, in https://github.com/pypa/setuptools/pull/4457
run `python setup.py bdist_wheel`: Use installed wheel or vendored wheel
Install package from source code: Use installed wheel or vendored wheel

**Comment by jiasli** [comment]
Latest [`MarkupSafe`](https://pypi.org/project/MarkupSafe/) is 2.1.5  but we are using

https://github.com/Azure/azure-cli/blob/fbe0addc214c857fc67d89266aede50c21970705/src/azure-cli/requirements.py3.Linux.txt#L107

Latest [`pycparser`](https://pypi.org/project/pycparser/) is 2.22 but we are using

https://github.com/Azure/azure-cli/blob/fbe0addc214c857fc67d89266aede50c21970705/src/azure-cli/requirements.py3.Linux.txt#L120
