### ISSUE TITLE
empty environments when using 'az pipelines release definition list' 

### ISSUE THREAD

**Issue by Davi-DemK** [Azure/azure-cli#29450]
### Describe the bug

When you are trying to get all release definitions from a given project, the json which is returned always have the key `"environment": null` Even if the definition have a lot of stages/environments.

But if you get the same definition using `az pipelines release show --id {id}` it gets all environments from the respective definition as expected.

### Related command

az pipelines release definition list

### Errors

N/A

### Issue script & Debug output

DEBUG: cli.knack.cli: Command arguments: ['pipelines', 'release', 'definition', 'list', '--project', 'TesteDevOps', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000206D252B880>, <function OutputProducer.on_global_arguments at 0x00000206D26B60C0>, <function CLIQuery.on_global_arguments at 0x00000206D26E3C40>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
DEBUG: cli.azure.cli.core: Command index has been invalidated.
DEBUG: cli.azure.cli.core: No module found from index for '['pipelines', 'release', 'definition', 'list', '--project', 'TesteDevOps', '--debug']'
DEBUG: cli.azure.cli.core: Loading all modules and extensions
DEBUG: cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'compute_recommender', 'config', 'configure', 'consumption', 'container', 'containerapp', 'cosmosdb', 'databoxedge', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'mysql', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: acr                       0.089        36       149
DEBUG: cli.azure.cli.core: acs                       0.031        14        76
DEBUG: cli.azure.cli.core: advisor                   0.005         3         6
DEBUG: cli.azure.cli.core: ams                       0.021        22       100
DEBUG: cli.azure.cli.core: apim                      0.010        14        69
DEBUG: cli.azure.cli.core: appconfig                 0.004         9        47
DEBUG: cli.azure.cli.core: appservice                0.104        79       270
DEBUG: cli.azure.cli.core: aro                       0.018         1        10
DEBUG: cli.azure.cli.core: backup                    0.006        16        60
DEBUG: cli.azure.cli.core: batch                     0.043        34       102
DEBUG: cli.azure.cli.core: batchai                   0.004        10        30
DEBUG: cli.azure.cli.core: billing                   0.025        19        53
DEBUG: cli.azure.cli.core: botservice                0.004        12        42
DEBUG: cli.azure.cli.core: cdn                       0.163         8        49
DEBUG: cli.azure.cli.core: cloud                     0.003         1         7
DEBUG: cli.azure.cli.core: cognitiveservices         0.003        10        33
DEBUG: cli.azure.cli.core: compute_recommender       0.008         1         1
DEBUG: cli.azure.cli.core: config                    0.003         2         7
DEBUG: cli.azure.cli.core: configure                 0.002         2         5
DEBUG: cli.azure.cli.core: consumption               0.028         8         9
DEBUG: cli.azure.cli.core: container                 0.017         1        11
DEBUG: cli.azure.cli.core: containerapp              0.184        37       123
DEBUG: cli.azure.cli.core: cosmosdb                  0.022        58       199
DEBUG: cli.azure.cli.core: databoxedge               0.016         5        28
DEBUG: cli.azure.cli.core: dla                       0.007        23        62
DEBUG: cli.azure.cli.core: dls                       0.006         7        41
DEBUG: cli.azure.cli.core: dms                       0.003         3        22
DEBUG: cli.azure.cli.core: eventgrid                 0.008        25        96
DEBUG: cli.azure.cli.core: eventhubs                 0.027        13        19
DEBUG: cli.azure.cli.core: extension                 0.002         1         7
DEBUG: cli.azure.cli.core: feedback                  0.002         1         2
DEBUG: cli.azure.cli.core: find                      0.002         1         1
DEBUG: cli.azure.cli.core: hdinsight                 0.014         8        39
DEBUG: cli.azure.cli.core: identity                  0.004         2        11
DEBUG: cli.azure.cli.core: interactive               0.001         1         1
DEBUG: cli.azure.cli.core: iot                       0.167        19        82
DEBUG: cli.azure.cli.core: keyvault                  0.014        20       113
DEBUG: cli.azure.cli.core: kusto                     0.003         3        14
DEBUG: cli.azure.cli.core: lab                       0.005        11        34
DEBUG: cli.azure.cli.core: managedservices           0.003         3         8
DEBUG: cli.azure.cli.core: maps                      0.003         5        13
DEBUG: cli.azure.cli.core: marketplaceordering       0.005         1         2
DEBUG: cli.azure.cli.core: monitor                   0.437        18        61
DEBUG: cli.azure.cli.core: mysql                     0.142        15        52
DEBUG: cli.azure.cli.core: netappfiles               0.061         8        17
DEBUG: cli.azure.cli.core: network                   0.081       103       338
DEBUG: cli.azure.cli.core: policyinsights            0.022         9        17
DEBUG: cli.azure.cli.core: privatedns                0.032        14        60
DEBUG: cli.azure.cli.core: profile                   0.003         2         8
DEBUG: cli.azure.cli.core: rdbms                     0.032        49       202
DEBUG: cli.azure.cli.core: redis                     0.005         7        38
DEBUG: cli.azure.cli.core: relay                     0.051         7         8
DEBUG: cli.azure.cli.core: resource                  0.031        51       231
DEBUG: cli.azure.cli.core: role                      0.006        17        61
DEBUG: cli.azure.cli.core: search                    0.018         7        19
DEBUG: cli.azure.cli.core: security                  0.015        48        98
DEBUG: cli.azure.cli.core: servicebus                0.022        12        15
DEBUG: cli.azure.cli.core: serviceconnector          0.054        20       307
DEBUG: cli.azure.cli.core: servicefabric             0.027        27        80
DEBUG: cli.azure.cli.core: signalr                   0.003         9        34
DEBUG: cli.azure.cli.core: sql                       0.019        56       215
DEBUG: cli.azure.cli.core: sqlvm                     0.098         4        20
DEBUG: cli.azure.cli.core: storage                   0.053        59       273
DEBUG: cli.azure.cli.core: synapse                   0.021        54       246
DEBUG: cli.azure.cli.core: util                      0.002         3         7
DEBUG: cli.azure.cli.core: vm                        0.061        58       269
DEBUG: cli.azure.cli.core: Total (66)                2.383      1206      4729
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: azure-devops              0.125        60       192  C:\Users\davi\.azure\cliextensions\azure-devops
DEBUG: cli.azure.cli.core: Total (1)                 0.125        60       192
DEBUG: cli.azure.cli.core: Loaded 1252 groups, 4921 commands.
DEBUG: cli.azure.cli.core: Updated command index in 0.004 seconds.
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000206D559C180>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\davi\.azure\commands\2024-07-23.15-41-51.pipelines_release_definition_list.16752.log'.
INFO: az_command_data_logger: command args: pipelines release definition list --project {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000206D591C680>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000206D591C720>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000206D591C860>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x00000206D7F58C20>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000206D26B6160>, <function CLIQuery.handle_query_parameter at 0x00000206D26E3CE0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000206D591C7C0>, <function DevCommandsLoader.post_parse_args at 0x00000206DCB49DA0>]
INFO: az_command_data_logger: extension name: azure-devops
INFO: az_command_data_logger: extension version: 0.26.0
INFO: cli.azext_devops.dev.common.git: GitDetect: Could not detect current remotes based on current working directory.
DEBUG: cli.azext_devops.dev.common.git: Command '['git', 'remote', '-v']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "C:\Users\davi\.azure\cliextensions\azure-devops\azext_devops\dev\common\git.py", line 106, in get_git_remotes
    output = subprocess.check_output([_GIT_EXE, 'remote', '-v'], stderr=subprocess.STDOUT)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['git', 'remote', '-v']' returned non-zero exit status 128.
INFO: cli.azext_devops.dev.common.services: Detect: Url discovery took 0:00:00.110990
DEBUG: cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://dev.azure.com/[org]
DEBUG: cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli: default
DEBUG: cli.azure.cli.core: Current cloud config:
AzureCloud
DEBUG: cli.azext_devops.dev.common.services: trying to get token (temp) for tenant [id] and user *******
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\davi\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\davi\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
INFO: msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/[id]
DEBUG: msal.authority: openid_config("https://login.microsoftonline.com/[id]/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/[id]/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/[id]/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/[id]/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/[id]/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/[id]/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/[id]/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/[id]/kerberos', 'tenant_region_scope': 'SA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? True
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('*******/.default',), claims=None, kwargs={}
DEBUG: msal.application: Found 1 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': '********.[id]', 'family_id': '1'}
DEBUG: msal.telemetry: Generate or reuse correlation_id: 368b8b71-7e1b-4b8e-be0a-57d01aa0780e
DEBUG: msal.application: Cache attempts an RT
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG: urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /[id]/oauth2/v2.0/token HTTP/1.1" 200 5045
DEBUG: msal.token_cache: event={
    "client_id": "[client_id]",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "refresh_token": "********",
        "scope": [
            "profile",
            "*******/.default",
            "openid",
            "offline_access"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "**",
        "expires_in": 4301,
        "ext_expires_in": 4301,
        "foci": "1",
        "id_token": "********",
        "scope": "*******/user_impersonation *******/.default",
        "token_type": "Bearer"
    },
    "scope": [
        "*******/user_impersonation",
        "*******/.default"
    ],
    "skip_account_creation": true,
    "token_endpoint": "https://login.microsoftonline.com/[id]/oauth2/v2.0/token"
}
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: cli.azext_devops.dev.common.telemetry: Azure devops telemetry enabled.
DEBUG: cli.azext_devops.dev.common.telemetry: Logging telemetry to azure devops server.
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\davi\.azure-devops\python-sdk\cache\options.json
DEBUG: azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\davi\.azure-devops\python-sdk\cache\options.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.client: File cache hit for options on: https://dev.azure.com/[org]
DEBUG: azext_devops.devops_sdk.client: Route template: _apis/{area}/{resource}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0-preview.1'
DEBUG: azext_devops.devops_sdk.client: POST https://dev.azure.com/[org]/_apis/CustomerIntelligence/Events
DEBUG: azext_devops.devops_sdk.client: Request content: [{'area': 'AzureDevopsCli', 'feature': 'pipelines', 'properties': {'Command': 'release definition list', 'Args': 'project', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': False, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False, 'OrgPickedFromGit': False, 'OrgPickedFromConfig': True, 'ProjectIgnoredFromConfig': True}}]
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\davi\.azure-devops\python-sdk\cache\resources.json
DEBUG: azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\davi\.azure-devops\python-sdk\cache\resources.json as utf-8-sig
DEBUG: azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/[org]
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
DEBUG: azext_devops.devops_sdk.client: File cache hit for options on: https://vsrm.dev.azure.com/[org]
DEBUG: azext_devops.devops_sdk.client: Route template: {project}/_apis/{area}/{resource}/{definitionId}
DEBUG: azext_devops.devops_sdk.client: Api version '5.0'
DEBUG: azext_devops.devops_sdk.client: GET https://vsrm.dev.azure.com/[org]/TesteDevOps/_apis/Release/definitions?queryOrder=nameAscending
DEBUG: azext_devops.devops_sdk.client: Request content: None
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): vsrm.dev.azure.com:443
DEBUG: urllib3.connectionpool: https://dev.azure.com:443 "POST /[org]/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
DEBUG: urllib3.connectionpool: https://vsrm.dev.azure.com:443 "GET /[org]/TesteDevOps/_apis/Release/definitions?queryOrder=nameAscending HTTP/1.1" 200 1351
DEBUG: azext_devops.devops_sdk.client: Response content: b'{"count":4,"value":[{"source":"userInterface","revision":1,"description":null,"createdBy":{"displayName":"user","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/*******","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/*********"}},"id":"******","uniqueName":"marcelo.costa@promovesolucoes.com","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/*********","inactive":true,"descriptor":"*******"},"createdOn":"2021-08-10T13:59:56.627Z","modifiedBy":{"displayName":"marcelo.costa","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/*******","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/******"}},"id":"***********","uniqueName":"marcelo.costa@promovesolucoes.com","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/*******","inactive":true,"descriptor":"aad.NzA5NzA0MTAtZDM2Ni03Nzk2LTk5Y2UtNGE3MTU2ZWZhZDAw"},"modifiedOn":"2021-08-10T13:59:56.627Z","isDeleted":false,"isDisabled":false,"variableGroups":null,"releaseNameFormat":"Release-$(rev:r)","comment":"","properties":{},"id":1,"name":"Utils_branch_develop","path":"\\\\","projectReference":null,"url":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/1","_links":{"self":{"href":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/1"},"web":{"href":"https://dev.azure.com/[org]/[project]/_release?definitionId=1"}}},{"source":"userInterface","revision":2,"description":null,"createdBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/***********","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"createdOn":"2022-08-22T14:12:01.397Z","modifiedBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/********","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"modifiedOn":"2022-08-22T14:12:15.613Z","isDeleted":false,"isDisabled":false,"variableGroups":null,"releaseNameFormat":"Release-$(rev:r)","comment":"","properties":{},"id":2,"name":"WorkItem Pipe","path":"\\\\","projectReference":null,"url":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/2","_links":{"self":{"href":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/2"},"web":{"href":"https://dev.azure.com/[org]/[project]/_release?definitionId=2"}}},{"source":"userInterface","revision":1,"description":null,"createdBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/********","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"createdOn":"2024-07-23T16:17:25.54Z","modifiedBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/********","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"modifiedOn":"2024-07-23T16:17:25.54Z","isDeleted":false,"isDisabled":false,"variableGroups":null,"releaseNameFormat":"Release-$(rev:r)","comment":"","properties":{},"id":3,"name":"exemplo_no_ameron","path":"\\\\","projectReference":null,"url":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/3","_links":{"self":{"href":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/3"},"web":{"href":"https://dev.azure.com/[org]/[project]/_release?definitionId=3"}}},{"source":"userInterface","revision":2,"description":null,"createdBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/*********","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"createdOn":"2024-07-23T16:27:53.653Z","modifiedBy":{"displayName":"Davi Alves","url":"https://spsprodsbr1.vssps.visualstudio.com/[org]/_apis/Identities/*************","_links":{"avatar":{"href":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"}},"id":"d6550380-8f10-6a2e-b447-db2856367062","uniqueName":"*******","imageUrl":"https://dev.azure.com/[org]/_apis/GraphProfile/MemberAvatars/aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy","descriptor":"aad.ZDY1NTAzODAtOGYxMC03YTJlLWI0NDctZGIyODU2MzY3MDYy"},"modifiedOn":"2024-07-23T16:28:08.917Z","isDeleted":false,"isDisabled":false,"variableGroups":null,"releaseNameFormat":"Release-$(rev:r)","comment":"","properties":{},"id":4,"name":"example_1","path":"\\\\","projectReference":null,"url":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/4","_links":{"self":{"href":"https://vsrm.dev.azure.com/[org]/[project]/_apis/Release/definitions/4"},"web":{"href":"https://dev.azure.com/[org]/[project]/_release?definitionId=4"}}}]}'
DEBUG: cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x00000206D55CB7E0>, <function _x509_from_base64_to_hex_transform at 0x00000206D55CB880>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnFilterResult []
DEBUG: cli.knack.cli: Event: Cli.SuccessfulExecute []
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x00000206D559C400>]
INFO: az_command_data_logger: exit code: 0
INFO: cli.__main__: Command ran in 4.697 seconds (init: 0.952, invoke: 3.745)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3684 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\davi\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command should return the environments from each definition which was found.

### Environment Summary

azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\davi\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
