### ISSUE TITLE
Customer feedback | az vmss create | SpotRestorePolicy Error: "InvalidParameter"

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29461]
### Describe the bug

This GitHub issue is being moved from azure-docs-cli [4474](https://github.com/MicrosoftDocs/azure-docs-cli/issues/4474).

Here is a customer screen print of the reference command parameters and error:
![image](https://github.com/user-attachments/assets/649da2fd-7945-4dea-9384-6d4a6968b333)

***************************************
**Type of issue**
Code doesn't work

**Feedback**
When using this example code (with changed values for Image and ResourceGroup)

"az vmss create -n MyVmss -g MyResourceGroup --location NorthEurope --instance-count 2 --image CentOS85Gen2 --priority Spot --eviction-policy Deallocate --single-placement-group --enable-spot-restore True --spot-restore-timeout PT1H"

I get the Error "DeploymentFailed" and the details:

"code":"InvalidParameter","target":"spotRestorePolicy","message":"The value of parameter spotRestorePolicy is invalid."

(On Cloud-Shell with az --version = 2.62.0)

I also tried to set "--single-placement-group false --enable-spot-restore false" - this then worked and a vmss was deployed.

(I also tried " --single-placement-group false --enable-spot-restore true" yielding the same invalid parameter response.)

**Page URL**
https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest

**Content source URL**
https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vmss.yml
***************************************

### Related command

az vmss create

### Errors

Invalid parameter, spotRestorePolicy...The value of parameter spotRestorePolicy is invalid.

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Cloud-Shell with az --version = 2.62.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@Raphael1313 Could you please send your debug log *(add `--debug` parameter)* to my email, my email address is Zhou.Xing@microsoft.com, thanks~

**Comment by AMEvers** [comment]
@zhoxing-ms I'm also seeing this issue with relation to the azurerm terraform module when trying to enable spot instances for scalesets on usGovCloud. Azure is returning a 400 error with the exact same error message. I'm unfortunately unable to provide direct logs from the environment.

**Comment by TravisCragg-MSFT** [comment]
@dbradish-microsoft Please direct the individuals here and do not open on their behalf. They do not get notifications if you open the issue, and I cannot mention them. 

@AMEvers This SDK is specific to the Azure CLI, and I would recommend opening a support request or posting on the Terraform SDK page for assistance. I would also make sure that you are using VMSS Uniform and not VMSS Flex, as this is not supported for VMSS Flex

**Comment by dbradish-microsoft** [comment]
@TravisCragg-MSFT, as stated in the description, this GitHub issue was moved from MicrosoftDocs/azure-docs-cli [4474](https://github.com/MicrosoftDocs/azure-docs-cli/issues/4474) as the feedback was on autogenerated reference content. This is the SOP as modifications to reference content must be made in the source code.

**Comment by weltonrodrigo** [comment]
Just to let you know that az vmss update --enable-spot-restore also gives error:

```console
$ az vmss update --name scaleset-marcamodelo -g maquinas-virtuais --enable-spot-restore        
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'enabled'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 240, in handler
    result = cached_put(self.cmd, setter, **setterargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 455, in cached_put
    return _put_operation()
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 449, in _put_operation
    result = operation(**kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.67.0_1/libexec/lib/python3.12/site-packages/azure/cli/command_modules/vm/custom.py", line 4106, in update_vmss
    vmss.spot_restore_policy.enabled = enable_spot_restore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'enabled'
```

**Comment by smereczynski** [comment]
Is it planned to be fixed? azure-cli 2.68.0, still the same problem.

**Comment by smereczynski** [comment]
It is not the CLI case. It does not work even in clear REST.

**Comment by smereczynski** [comment]
It does not work for flexible orchestration, which is the default one when creating VMSS from CLI. The documentation is saying any word about that. Azure Copilot is saying that it does work for Flexible - so it is misinforming users.
