### ISSUE TITLE
Wheel 0.30.0 is not compatible with latest setuptools

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#29467]
After 71.0.0, in https://github.com/pypa/setuptools/pull/4457
(Not compatible with old version of wheel)
run python setup.py bdist_wheel: Use installed wheel or vendored wheel
Install package from source code: Use installed wheel or vendored wheel

setuptools's code is not compatible with 0.30.0. If the package does not provide wheel and must compile from source code, you'll see this error:
```
# install cffi 1.15.1 in Python 3.12
2024-07-25T03:43:04.0552476Z Building wheels for collected packages: cffi
2024-07-25T03:43:04.0552668Z   Building wheel for cffi (setup.py): started
2024-07-25T03:43:04.0552985Z   Building wheel for cffi (setup.py): finished with status 'error'
2024-07-25T03:43:04.0553397Z   error: subprocess-exited-with-error
2024-07-25T03:43:04.0553554Z   
2024-07-25T03:43:04.0553792Z   × python setup.py bdist_wheel did not run successfully.
2024-07-25T03:43:04.0554013Z   │ exit code: 1
2024-07-25T03:43:04.0554207Z   ╰─> [25 lines of output]
2024-07-25T03:43:04.0554371Z       Traceback (most recent call last):
2024-07-25T03:43:04.0554525Z         File "<string>", line 2, in <module>
2024-07-25T03:43:04.0554796Z         File "<pip-setuptools-caller>", line 34, in <module>
2024-07-25T03:43:04.0555161Z         File "/tmp/pip-install-7jczthn1/cffi_1b5c114d59cc470d96d4d51c40a16d1f/setup.py", line 179, in <module>
2024-07-25T03:43:04.0555433Z           setup(
2024-07-25T03:43:04.0555800Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
2024-07-25T03:43:04.0556032Z           return distutils.core.setup(**attrs)
2024-07-25T03:43:04.0556194Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T03:43:04.0556572Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 171, in setup
2024-07-25T03:43:04.0556824Z           ok = dist.parse_command_line()
2024-07-25T03:43:04.0556969Z                ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T03:43:04.0557375Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 478, in parse_command_line
2024-07-25T03:43:04.0557637Z           args = self._parse_command_opts(parser, args)
2024-07-25T03:43:04.0557809Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T03:43:04.0558199Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/dist.py", line 858, in _parse_command_opts
2024-07-25T03:43:04.0558478Z           nargs = _Distribution._parse_command_opts(self, parser, args)
2024-07-25T03:43:04.0558656Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T03:43:04.0559069Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 537, in _parse_command_opts
2024-07-25T03:43:04.0559333Z           cmd_class = self.get_command_class(command)
2024-07-25T03:43:04.0559500Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T03:43:04.0559869Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/dist.py", line 697, in get_command_class
2024-07-25T03:43:04.0560127Z           from .command.bdist_wheel import bdist_wheel
2024-07-25T03:43:04.0560547Z         File "/mnt/vss/_work/1/s/env/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 29, in <module>
2024-07-25T03:43:04.0560801Z           from wheel.wheelfile import WheelFile
2024-07-25T03:43:04.0561094Z       ModuleNotFoundError: No module named 'wheel.wheelfile'
2024-07-25T03:43:04.0561275Z       [end of output]
2024-07-25T03:43:04.0561395Z   
2024-07-25T03:43:04.0561577Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-07-25T03:43:04.0561805Z   ERROR: Failed building wheel for cffi
2024-07-25T03:43:04.0561973Z   Running setup.py clean for cffi
2024-07-25T03:43:04.0562141Z Failed to build cffi
2024-07-25T03:43:04.0562350Z ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cffi)
```

Ref:
https://github.com/Azure/azure-cli/issues/29421#issuecomment-2238008833
https://dev.azure.com/azclitools/public/_build/results?buildId=175588&view=logs&jobId=914f4ebc-22d2-5549-b4a9-559bc8a45a5c&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=5096328f-22b9-5257-6ae4-9181ac2094cd

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by wangzelin007** [comment]
I just encountered this issue, the actual test result is: setuptools>72.1.0 not compatible with old version of wheel, we may need to pin the setuptools version at 72.1.0 in azdev.
Upgrading setuptools and wheel is not an easy task and cannot be done in the short term, we have no choice.

![image](https://github.com/user-attachments/assets/e2ad6601-9c4a-47b7-84e8-eec8303f705d)
![image](https://github.com/user-attachments/assets/bec3ab31-e313-4e46-9747-e0a3c92028d4)
---------------------
![image](https://github.com/user-attachments/assets/7e0307af-7192-438e-b2dc-a5d97ede1421)
![image](https://github.com/user-attachments/assets/d1d41171-0018-4083-9d60-66f34aaafae5)

**Comment by Elsie4ever** [comment]
I'm also getting the same issue in github runner
![image](https://github.com/user-attachments/assets/375f33d1-e610-4296-81bd-4e9fc324b8db)

**Comment by bebound** [comment]
For now, we have to pin `setuptools` to 70.0.0 like https://github.com/Azure/azure-cli-extensions/pull/7739

I hope the extension can stop using wheel 0.30.0 someday.

**Comment by saisankargochhayat** [comment]
Also impacted by this, had to pin to 70.0.0

**Comment by mainred** [comment]
Hit the same issue in https://github.com/Azure/azure-cli-extensions/pull/8990
We depend on an opensource project which relies on setuptools 80.0.0. Trying to see if pinning the setuptools to 70.0.0 works
