### ISSUE TITLE
Execution error with az oracle-database autonomous-database create | The command failed with an unexpected error.

### ISSUE THREAD

**Issue by sebherd** [Azure/azure-cli#29485]
### Describe the bug

Hi, 
I tried to create an Oracle Autonomous Database with this how-to:
https://learn.microsoft.com/en-us/cli/azure/oracle-database/autonomous-database?view=azure-cli-latest#az-oracle-database-autonomous-database-create

Unfortunately, I run into the described error in the "error-section". 

BR

### Related command

1st command:
`az oracle-database autonomous-database create --location 'Germany West Central' --autonomousdatabasename 'Test' --resource-group 'Oracle'`

2nd command as a further test:
`az oracle-database autonomous-database create -n 'Test' -g 'Oracle'`

### Errors

If I execute the example I run into the following error:
`The command failed with an unexpected error. Here is the traceback:
"Model 'AAZObjectType' has no field named 'dataBaseType'"
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1039, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 358, in _execute_operations
    yield self.AutonomousDatabasesCreateOrUpdate(ctx=self.ctx)()
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 377, in __call__
    request = self.make_request()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 318, in make_request
    self.content, self.form_content, self.stream_content)
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 498, in content
    properties.discriminate_by("dataBaseType", "Clone")
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_content_builder.py", line 159, in discriminate_by
    schema.discriminate_by(prop_name, prop_value)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 243, in discriminate_by
    raise AAZUnknownFieldError(self, key)
azure.cli.core.aaz.exceptions.AAZUnknownFieldError: "Model 'AAZObjectType' has no field named 'dataBaseType'"`

### Issue script & Debug output

` $ az oracle-database autonomous-database create -n 'Test' -g 'Oracle' --debug
cli.knack.cli: Command arguments: ['oracle-database', 'autonomous-database', 'create', '-n', 'Test', '-g', 'Oracle', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7ff29bd5a160>, <function OutputProducer.on_global_arguments at 0x7ff29bc74d30>, <function CLIQuery.on_global_arguments at 0x7ff29bc0b310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'oracle-database': ['azext_oracle_database']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.196         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: oracle-database           0.107        12        19  /home/<sensitive>/.azure/cliextensions/oracle-database
cli.azure.cli.core: Total (2)                 0.303        13        20  
cli.azure.cli.core: Loaded 13 groups, 20 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : oracle-database autonomous-database create
cli.azure.cli.core: Command table: oracle-database autonomous-database create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7ff29b0b9820>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/<sensitiv>/.azure/commands/2024-07-26.08-09-24.oracle-database_autonomous-database_create.1912.log'.
az_command_data_logger: command args: oracle-database autonomous-database create -n {} -g {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7ff29b062430>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7ff29b088430>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7ff29b02c310>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7ff29bc74dc0>, <function CLIQuery.handle_query_parameter at 0x7ff29bc0b3a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7ff29b02c280>]
az_command_data_logger: extension name: oracle-database
az_command_data_logger: extension version: 1.0.0b1
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2258
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2258
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1721984665' -> 1721984665
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<sub_id>/resourcegroups/Oracle?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5ecb8200-4b26-11ef-841f-00155dde8d47'
cli.azure.cli.core.sdk.policies:     'CommandName': 'oracle-database autonomous-database create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (RPM) azsdk-python-core/1.28.0 Python/3.9.19 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<sub_id>/resourcegroups/Oracle?api-version=2022-09-01 HTTP/1.1" 200 231
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '231'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '249'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '3749'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3c45ef60-8202-423f-a829-31987e7c896a'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '3c45ef60-8202-423f-a829-31987e7c896a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20240726T080925Z:3c45ef60-8202-423f-a829-31987e7c896a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: CA15607DE86B4EF198B011B54EAFBE0F Ref B: VIEEDGE2613 Ref C: 2024-07-26T08:09:24Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 26 Jul 2024 08:09:25 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/<sub_id>/resourceGroups/Oracle","name":"Oracle","type":"Microsoft.Resources/resourceGroups","location":"germanywestcentral","tags":{},"properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.aaz._arg_fmt: using location 'germanywestcentral' from resource group 'Oracle'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2258
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1039, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 358, in _execute_operations
    yield self.AutonomousDatabasesCreateOrUpdate(ctx=self.ctx)()
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 377, in __call__
    request = self.make_request()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 318, in make_request
    self.content, self.form_content, self.stream_content)
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 498, in content
    properties.discriminate_by("dataBaseType", "Clone")
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_content_builder.py", line 159, in discriminate_by
    schema.discriminate_by(prop_name, prop_value)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 243, in discriminate_by
    raise AAZUnknownFieldError(self, key)
azure.cli.core.aaz.exceptions.AAZUnknownFieldError: "Model 'AAZObjectType' has no field named 'dataBaseType'"

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: "Model 'AAZObjectType' has no field named 'dataBaseType'"
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1039, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 358, in _execute_operations
    yield self.AutonomousDatabasesCreateOrUpdate(ctx=self.ctx)()
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 377, in __call__
    request = self.make_request()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 318, in make_request
    self.content, self.form_content, self.stream_content)
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 498, in content
    properties.discriminate_by("dataBaseType", "Clone")
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_content_builder.py", line 159, in discriminate_by
    schema.discriminate_by(prop_name, prop_value)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 243, in discriminate_by
    raise AAZUnknownFieldError(self, key)
azure.cli.core.aaz.exceptions.AAZUnknownFieldError: "Model 'AAZObjectType' has no field named 'dataBaseType'"
az_command_data_logger: "Model 'AAZObjectType' has no field named 'dataBaseType'"
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1039, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 358, in _execute_operations
    yield self.AutonomousDatabasesCreateOrUpdate(ctx=self.ctx)()
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 377, in __call__
    request = self.make_request()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_operation.py", line 318, in make_request
    self.content, self.form_content, self.stream_content)
  File "/home/<sensitive>/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 498, in content
    properties.discriminate_by("dataBaseType", "Clone")
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_content_builder.py", line 159, in discriminate_by
    schema.discriminate_by(prop_name, prop_value)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/aaz/_field_type.py", line 243, in discriminate_by
    raise AAZUnknownFieldError(self, key)
azure.cli.core.aaz.exceptions.AAZUnknownFieldError: "Model 'AAZObjectType' has no field named 'dataBaseType'"
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7ff29b0b9a60>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.702 seconds (init: 0.189, invoke: 1.513)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 8438 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/<sensitive>/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.`

### Expected behavior

I expecting that the Autonomous Database will be created with the example-command from: https://learn.microsoft.com/en-us/cli/azure/oracle-database/autonomous-database?view=azure-cli-latest#az-oracle-database-autonomous-database-create

### Environment Summary

az --version
azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.28.0
oracle-database                  1.0.0b1
ssh                                2.0.4

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/home/<sensitive>/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bthan00** [comment]
I am also facing the exact issue. In addition, on the front end azure portal there seems to be a bug preventing me from adding the database version:

![image](https://github.com/user-attachments/assets/427ddec6-5e53-4f33-8d47-9f2c5d361d49)

**Comment by sebherd** [comment]
Not directly, but some hints I found out so far...

If I check the following [link](https://docs.oracle.com/en-us/iaas/Content/database-at-azure/getting-started.htm), I think you need a "private offer" to setup the autonomous db in the way we want:

Private offer: With this option, you first contact [Oracle's sales team](https://www.oracle.com/corporate/contact/) to negotiate a contract for Oracle Database@Azure. To use Oracle Exadata Database Service, you must purchase Oracle Database@Azure using a private offer. You can also provision Oracle Autonomous Database after purchasing a private offer.

Pay As You Go offer: You can purchase this offer in the Azure Marketplace without contacting Oracle Sales. Oracle offers Autonomous Database for customers purchasing the Pay As You Go offer. Pay as You Go offers the most flexibility, letting you start and stop using the service at any time.

So currently I am in contact with an oracle account manager to get the private offer enabled. In the meantime I will check the autonomous db from the marketplace with pay-as-you-go

**Comment by rwagnergit** [comment]
FYI, I'm encountering the original issue, as well.  I do have a private offer and am able to create an ADB in the Azure portal.  But the az cli command is yielding the same error:

azure.cli.core.aaz.exceptions.AAZUnknownFieldError: Model 'AAZObjectType' has no field named 'dataBaseType'

**Comment by rwagnergit** [comment]
```
rob@Azure:~$ az version
{
  "azure-cli": "2.75.0",
  "azure-cli-core": "2.75.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ml": "2.37.2",
    "oracle-database": "1.0.0",
    "ssh": "2.0.6"
  }
}
rob@Azure:~$ az oracle-database autonomous-database create --autonomousdatabasename rowagnc2 --resource-group rowagn_autonomous
The command failed with an unexpected error. Here is the traceback:
Model 'AAZObjectType' has no field named 'dataBaseType'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 714, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 1072, in __call__
    result = poller.result()
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_poller.py", line 108, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_poller.py", line 130, in wait
    raise self._exception
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_poller.py", line 83, in _start
    for polling_method in self._polling_generator:
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rob/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 358, in _execute_operations
    yield self.AutonomousDatabasesCreateOrUpdate(ctx=self.ctx)()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rob/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 377, in __call__
    request = self.make_request()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_operation.py", line 313, in make_request
    self.content, self.form_content, self.stream_content)
    ^^^^^^^^^^^^
  File "/home/rob/.azure/cliextensions/oracle-database/azext_oracle_database/aaz/latest/oracle_database/autonomous_database/_create.py", line 498, in content
    properties.discriminate_by("dataBaseType", "Clone")
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_content_builder.py", line 151, in discriminate_by
    schema.discriminate_by(prop_name, prop_value)
  File "/usr/lib64/az/lib/python3.12/site-packages/azure/cli/core/aaz/_field_type.py", line 295, in discriminate_by
    raise AAZUnknownFieldError(self, key)
azure.cli.core.aaz.exceptions.AAZUnknownFieldError: Model 'AAZObjectType' has no field named 'dataBaseType'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

**Comment by rwagnergit** [comment]
FYI, if I include --regular in the az command, it works.  No idea what --regular does.

az oracle-database autonomous-database create --name blah --display-name blah --resource-group blah --regular --admin-password 'blah' --schedule-type Regular --retention-days blah --compute-count blah --compute-model ECPU --cpu-auto-scaling false --storage-tbs 1 --database-edition EnterpriseEdition --db-workload DW --store-auto-scaling false --mtls-reqd false --license-model BringYourOwnLicense --location 'East US' --vnet-id /subscriptions/blah --subnet-id /subscriptions/blah

This succeeds.
