### ISSUE TITLE
az ml online-deployment create give me error

### ISSUE THREAD

**Issue by yogesh9630** [Azure/azure-cli#29792]
### Describe the bug

The command failed with an unexpected error. Here is the traceback:
cannot access local variable 'debug' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 71, in ml_online_deployment_create
    deployment = load_online_deployment(source=file, params_override=params_override)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 646, in load_online_deployment
    return cast(OnlineDeployment, load_common(OnlineDeployment, source, relative_origin, params_override, **kwargs))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 105, in load_common
    return _load_common_raising_marshmallow_error(cls, yaml_dict, relative_origin, params_override, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 165, in _load_common_raising_marshmallow_error
    res: Resource = cls._load(
                    ^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_deployment\online_deployment.py", line 362, in _load
    res_manage: OnlineDeployment = load_from_dict(ManagedOnlineDeploymentSchema, data, context, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_util.py", line 192, in load_from_dict
    return schema(context=context).load(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 726, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 865, in _do_load
    result = self._deserialize(
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 668, in _deserialize
    value = self._call_and_store(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 496, in _call_and_store
    value = getter_func(data)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 661, in getter
    return field_obj.deserialize(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\fields.py", line 367, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_schema\core\fields.py", line 484, in _deserialize
    return schema.deserialize(value, attr, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\fields.py", line 367, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\fields.py", line 671, in _deserialize
    return self._load(value, data, partial=partial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\fields.py", line 654, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 726, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 855, in _do_load
    processed_data = self._invoke_load_processors(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 1095, in _invoke_load_processors
    data = self._invoke_processors(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\marshmallow\schema.py", line 1222, in _invoke_processors
    data = processor(data, many=many, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_schema\core\schema.py", line 74, in trim_dump_only
    if data.get(schema_key, None) is not None:
       ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\yogeshyadav01\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 132, in ml_online_deployment_create
    log_and_raise_error(err, debug, yaml_operation=yaml_operation)
                             ^^^^^
UnboundLocalError: cannot access local variable 'debug' where it is not associated with a value
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

deployment.yml
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my-deployment
endpoint_name: my-endpoint-1
model:
  - name: my-model
    version: 1
code_configuration:
  scoring_script: score.py
instance_type: Standard_DS11_v2
instance_count: 1

### Related command

az ml online-deployment create --name my-deployment --file deployment.yml --workspace-name Test-ML-Workspace --resource-group Test-ML-RG --local
when running this command getting error 

### Errors

  .

### Issue script & Debug output

   ..

### Expected behavior

Running az ml online-deployment create getting error

### Environment Summary

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
ml                                2.29.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\yogeshyadav01\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
route to service team

**Comment by TommyKihle** [comment]
Hi we are experiencing the same problem. What is the timeline on this issue?

This is our error message:
Creating Azure Machine Learning deployment 'reservedelsalesforecast7deployment'.

ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: cannot access local variable 'debug' where it is not associated with a value

Traceback (most recent call last):

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 71, in ml_online_deployment_create

    deployment = load_online_deployment(source=file, params_override=params_override)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 646, in load_online_deployment

    return cast(OnlineDeployment, load_common(OnlineDeployment, source, relative_origin, params_override, **kwargs))

                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 99, in load_common

    yaml_dict = _try_load_yaml_dict(source)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 135, in _try_load_yaml_dict

    yaml_dict = load_yaml(source)

                ^^^^^^^^^^^^^^^^^

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\utils.py", line 339, in load_yaml

    return yaml.safe_load(f)

           ^^^^^^^^^^^^^^^^^

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 125, in safe_load

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 79, in load

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/loader.py", line 34, in __init__

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 85, in __init__

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 124, in determine_encoding

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 178, in update_raw

  File "<frozen codecs>", line 322, in decode

  File "encodings\utf_8_sig.py", line 69, in _buffer_decode

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__

  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler

  File "C:\Users\tommy\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 132, in ml_online_deployment_create

    log_and_raise_error(err, debug, yaml_operation=yaml_operation)

                             ^^^^^

UnboundLocalError: cannot access local variable 'debug' where it is not associated with a value

To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

Invoke-AzCliCommand : The command '

            az ml online-deployment create `

                --resource-group $ResourceGroupName `

                --workspace-name $WorkspaceName `

                --file $OnlineDeploymentYamlFile `

                --skip-script-validation `

                --all-traffic

        ' failed with exit code 1.

At C:\Users\tommy\Documents\AL\SalesForecastMachineLearning\BCTech\samples\MachineLearning\DeployMachineLearningResourcescopy.ps1:150 char:9

+         Invoke-AzCliCommand {

+         ~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AzCliCommand

**Comment by tsr-kmanson** [comment]
Hello,

we are currently facing the exact same problem when trying to set up a machine learning environment.
Any info on this ? Or is there a manual workaround ?

The command failed with an unexpected error. Here is the traceback:
cannot access local variable 'debug' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 71, in ml_online_deployment_create
    deployment = load_online_deployment(source=file, params_override=params_override)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 646, in load_online_deployment
    return cast(OnlineDeployment, load_common(OnlineDeployment, source, relative_origin, params_override, **kwargs))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 99, in load_common
    yaml_dict = _try_load_yaml_dict(source)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\entities\_load_functions.py", line 135, in _try_load_yaml_dict
    yaml_dict = load_yaml(source)
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\vendored_curated_sdk\azure\ai\ml\_utils\utils.py", line 339, in load_yaml
    return yaml.safe_load(f)
           ^^^^^^^^^^^^^^^^^
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 125, in safe_load
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/__init__.py", line 79, in load
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/loader.py", line 34, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 85, in __init__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 124, in determine_encoding
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\yaml/reader.py", line 178, in update_raw
  File "<frozen codecs>", line 322, in decode
  File "encodings\utf_8_sig.py", line 69, in _buffer_decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\kma\.azure\cliextensions\ml\azext_mlv2\manual\custom\online_deployment.py", line 132, in ml_online_deployment_create
    log_and_raise_error(err, debug, yaml_operation=yaml_operation)
                             ^^^^^
UnboundLocalError: cannot access local variable 'debug' where it is not associated with a value
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Comment by VerdantForge** [comment]
Any updates on this issue? I've just run into the same one when trying to debug a failed azure ML deployment
