### ISSUE TITLE
Cannot create a new api (with versionset) using `az apim api import`

### ISSUE THREAD

**Issue by QuickScoP3s** [Azure/azure-cli#29917]
### Describe the bug

I'm trying to create a new api with versionsets using `az apim api import`

The command fails with the following error:
```
cli.azure.cli.core.azclierror: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found.
az_command_data_logger: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found
```

The api does not exist yet, so obviously the versionset also does not, but I would expect it to create the version set in that case.
Am I missing any parameters or information? Does this command not support creating version sets directly?

### Related command

```ps
az apim api import `
 --path "employee" `
 --resource-group "<our resourcegroup>" `
 --display-name "employee-api" `
 --service-name "<our apim>" `
 --specification-format OpenApiJson `
 --api-id "employee-apiv1" `
 --api-revision 1 `
 --api-type http `
 --protocols https `
 --api-version v1 `
 --api-version-set-id "employee-apiversionset" `
 --specification-path "<localpath>\service.employee-openapi-definition.json"
```

### Errors

cli.azure.cli.core.azclierror: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found.
az_command_data_logger: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['apim', 'api', 'import', '--path', 'employee', '--resource-group', '...', '--display-name', 'employee-api', '--service-name', '...', '--specification-format', 'OpenApiJson', '--api-id', 'employee-apiv1', '--api-revision', '1', '--api-type', 'http', '--protocols', 'https', '--api-version', 'v1', '--api-version-set-id', 'employee-apiversionset', '--specification-path', '...', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001E3437CF920>, <function OutputProducer.on_global_arguments at 0x000001E343956160>, <function CLIQuery.on_global_arguments at 0x000001E343983CE0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'apim': ['azure.cli.command_modules.apim']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: apim                      0.005        14        69
cli.azure.cli.core: Total (1)                 0.005        14        69
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 14 groups, 69 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : apim api import
cli.azure.cli.core: Command table: apim api import
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001E345BB3F60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '...\.azure\commands\2024-09-17.09-04-05.apim_api_import.35384.log'.
az_command_data_logger: command args: apim api import --path {} --resource-group {} --display-name {} --service-name {} --specification-format {} --api-id {} --api-revision {} --api-type {} --protocols {} --api-version {} --api-version-set-id {} --specification-path {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001E345BE68E0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001E345C289A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001E345C28AE0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x000001E345C28B80>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001E343956200>, <function CLIQuery.handle_query_parameter at 0x000001E343983D80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001E345C28A40>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ApiManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='...\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: ...\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/...
msal.authority: openid_config("https://login.microsoftonline.com/.../v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/.../oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/.../discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/.../v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/.../oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/.../oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/.../oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/.../kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 93797959-1ddd-4899-8a8d-233e5aacc602
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis/employee-apiv1%3Brev%3D1?api-version=2022-08-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '11475'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '06f1d7fe-74c3-11ef-a24c-6c2f8032c93a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'apim api import'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--path --resource-group --display-name --service-name --specification-format --api-id --api-revision --api-type --protocols --api-version --api-version-set-id --specification-path --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.64.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
... <body>
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis/employee-apiv1%3Brev%3D1?api-version=2022-08-01 HTTP/1.1" 202 0
cli.azure.cli.core.sdk.policies: Response status: 202
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Location': 'https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis/employee-apiv1;rev=1?api-version=2022-08-01&asyncId=66e929e60a23231720d8a13d&asyncCode=201'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd029c565-3fb5-4d29-bd96-8788829a8fcf'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '399'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '5999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd029c565-3fb5-4d29-bd96-8788829a8fcf'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20240917T070406Z:d029c565-3fb5-4d29-bd96-8788829a8fcf'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 582CDE42DFD541D5B6ABAE7E5C708F15 Ref B: AMS231022012053 Ref C: 2024-09-17T07:04:06Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 17 Sep 2024 07:04:06 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '0'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies:
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis/employee-apiv1;rev=1?api-version=2022-08-01&asyncId=66e929e60a23231720d8a13d&asyncCode=201'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '06f1d7fe-74c3-11ef-a24c-6c2f8032c93a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'apim api import'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--path --resource-group --display-name --service-name --specification-format --api-id --api-revision --api-type --protocols --api-version --api-version-set-id --specification-path --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.64.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis/employee-apiv1;rev=1?api-version=2022-08-01&asyncId=66e929e60a23231720d8a13d&asyncCode=201 HTTP/1.1" 404 89
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '89'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'adac9f8c-a465-4e16-afee-ae58abf650b1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '499'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '7499'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'adac9f8c-a465-4e16-afee-ae58abf650b1'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20240917T070407Z:adac9f8c-a465-4e16-afee-ae58abf650b1'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: A9078302927E4F8684B5F808A123EEE7 Ref B: AMS231022012053 Ref C: 2024-09-17T07:04:06Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 17 Sep 2024 07:04:06 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceNotFound","message":"ApiVersionSet not found.","details":null}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 730, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 756, in _poll
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 782, in update_status
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 156, in _raise_if_bad_http_status_and_method
azure.core.polling.base_polling.BadStatus: Invalid return status 404 for 'GET' operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1075, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 242, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 261, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 176, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 734, in run
azure.core.exceptions.HttpResponseError: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found.

cli.azure.cli.core.azclierror: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found.
az_command_data_logger: (ResourceNotFound) ApiVersionSet not found.
Code: ResourceNotFound
Message: ApiVersionSet not found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001E345BB4220>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 1.602 seconds (init: 0.159, invoke: 1.442)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4039 in cache file under C:\Users\wautw\.azure\telemetry\20240917090407067
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc ...\.azure ...\.azure\telemetry\20240917090407067"
telemetry.process: Return from creating process 27840
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

I expect the import command to create an api + version set if none exists

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Extensions:
arcdata                           1.5.18

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\wautw\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date

### Additional context

We've already been using this command for a while to import existing api's, but this is the first time trying to use it to create a new api...

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by QuickScoP3s** [comment]
Apologies. I misunderstood the infrastructure setup of APIM:
I thought a version set exists **under** an API, but I now discovered it exists **above** an api.

I'm now creating the version set first, and then importing the api on top.
