### ISSUE TITLE
az storage copy stopped working for wildcard copy

### ISSUE THREAD

**Issue by spalberg** [Azure/azure-cli#29929]
### Describe the bug

We use the azure cli to copy a directory recursively on the same azure file share.
So we've got the following setup:
```
parent/
├─ source/
│  ├─ a.txt
│  ├─ b.txt
```
and we want to copy `parent/source` to `parent/target` so that the file system looks like this:
 ```
parent/
├─ source/
│  ├─ a.txt
│  ├─ b.txt
├─ target/
│  ├─ a.txt
│  ├─ b.txt
```

Our script does this by using the following command:
`az storage copy --source-share share-name --source-file-path parent/source/* --destination-share share-name --destination-file-path parent/target --recursive`
which copies all children of the `source` dir into the `target` dir. This worked great until github updated their runners to include the latest version of azure cli (`2.64.0`). 

Since `2.64.0`  we get an `The specifed resource name contains invalid characters` error when using a wildcard as shown above. We think that [this PR](https://github.com/Azure/azure-cli/pull/29779) introduced the bug. With the changes from this PR, the [source path including the wildcard is matched against the azure api](https://github.com/calvinhzy/azure-cli/blob/da216c8912d63cb203bf5c4653c5e556a0543929/src/azure-cli/azure/cli/command_modules/storage/operations/fileshare.py#L110) to get an sas token which results in the exception.

We also checked if there is another way to copy a folder and rename it at the same time but could not find any without iterating over its contents ourselfs.

### Related command

az storage copy --source-share share-name --source-file-path parent/source/* --destination-share share-name --destination-file-path parent/target --recursive

### Errors

```
cli.azure.cli.core.azclierror: The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z
ErrorCode:InvalidResourceName
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z</Message></Error>
az_command_data_logger: The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z
ErrorCode:InvalidResourceName
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z</Message></Error>
```

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['storage', 'copy', '--source-share', 'share-name', '--source-file-path', 'parent/source/*', '--destination-share', 'share-name', '--destination-file-path', 'parent/target', '--recursive', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000267E91437E0>, <function OutputProducer.on_global_arguments at 0x00000267E92CA020>, <function CLIQuery.on_global_arguments at 0x00000267E92F3BA0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.925        59       273
cli.azure.cli.core: Total (1)                 0.925        59       273
cli.azure.cli.core: Loaded 59 groups, 273 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage copy
cli.azure.cli.core: Command table: storage copy
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000267E9DB7E20>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '<redacted>'.
az_command_data_logger: command args: storage copy --source-share {} --source-file-path {} --destination-share {} --destination-file-path {} --recursive --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000267E9DE67A0>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 660, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_05_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 660, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_05_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 660, in _get_attr
AttributeError: module 'azure.mgmt.storage.v2023_05_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000267E9E28860>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000267E9E289A0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x00000267E9E28A40>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000267E92CA0C0>, <function CLIQuery.handle_query_parameter at 0x00000267E92F3C40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000267E9E28900>]
Positional argument '<EXTRA_OPTIONS>' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage account value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage connection_string value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
urllib3.connectionpool: Starting new HTTPS connection (1): <redacted>.file.core.windows.net:443
urllib3.connectionpool: https://<redacted>.file.core.windows.net:443 "GET /<redacted>/parent%2Ftarget?restype=directory HTTP/1.1" 200 0
cli.azure.cli.command_modules.storage._validators: Try to get storage connection_string value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
urllib3.connectionpool: Starting new HTTPS connection (1): <redacted>.file.core.windows.net:443
urllib3.connectionpool: https://<redacted>.file.core.windows.net:443 "GET /<redacted>/parent%2Fsource%2F%2A?restype=directory HTTP/1.1" 400 243
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/invocation.py", line 111, in _validation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 911, in _validate_cmd_level
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_validators.py", line 2082, in validate_azcopy_credential
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/_validators.py", line 2010, in get_url_with_sas
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/file.py", line 112, in create_file_url
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/storage/operations/fileshare.py", line 110, in _get_client
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/fileshare/v2024_08_04/_directory_client.py", line 786, in exists
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storagev2/fileshare/v2024_08_04/_shared/response_handlers.py", line 182, in process_storage_error        
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z
ErrorCode:InvalidResourceName
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:<redacted>
Time:2024-09-18T15:08:00.4211471Z</Message></Error>
```

### Expected behavior

The contents of the source dir should be recursively copied into the target dir:

```
parent/
├─ source/
│  ├─ a.txt
│  ├─ b.txt
```

->

 ```
parent/
├─ source/
│  ├─ a.txt
│  ├─ b.txt
├─ target/
│  ├─ a.txt
│  ├─ b.txt
``` 

### Environment Summary

az --version
azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<redacted>\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

### Additional context

Works fine with 2.63.0 and below.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by spalberg** [comment]
This is definitly a bug and it breaks all the wildcard examples in the docs. Is there any hope of a quick fix or should everyone just downgrade and pin the previous version?

**Comment by calvinhzy** [comment]
Since the new release is already in the process of being built, the fix will be ready in the next sprint, please pin to the previous version for now.

**Comment by spalberg** [comment]
Thanks for the quick update!

**Comment by spalberg** [comment]
any update on this?
