### ISSUE TITLE
az aks install-cli:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by bavneetsingh16** [Azure/azure-cli#29948]
### Describe the bug
Trying to use az connectedk8s cmd which internally uses `az aks install-cli --install-location <path_to_kubectl.exe>` to install kubectl.exe file. The cmd fails with the below error.

### Related command

az aks install-cli --install-location <path_to_kubectl.exe> --debug

### Errors

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

### Issue script & Debug output

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1298, in request
  File "http\client.py", line 1344, in _send_request
  File "http\client.py", line 1293, in endheaders
  File "http\client.py", line 1052, in _send_output
  File "http\client.py", line 990, in send
  File "http\client.py", line 1470, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

### Expected behavior

It should be able to download the kubectl file.

### Environment Summary

azure-cli                         2.63.0 *

core                              2.63.0 *
telemetry                          1.1.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jagadishmurugan** [comment]
the issue can be easily repro's on Azure VM with following specs:
![image](https://github.com/user-attachments/assets/2473080b-7d30-48f2-9b7c-bc181770a04c)
Security Type: Standard
![image](https://github.com/user-attachments/assets/c1c4eb68-cb9b-4077-b40d-bea2e04d2312)

**Comment by jagadishmurugan** [comment]
the following workaround helped resolve the issue;
1. install python
2. pip install pip-system-certs

**Comment by mbifeld** [comment]
@bavneetsingh16 I believe this issue can be closed based on https://github.com/Azure/azure-cli/pull/30561 being merged. Please let me know if this remains an active issue.

**Comment by mbifeld** [comment]
Closing as resolved based on the above comment. Please reopen / tag me if this issue is still present. Thank you.
