### ISSUE TITLE
Failed execution of az functionapp connection create sql 

### ISSUE THREAD

**Issue by gcp0703** [Azure/azure-cli#29942]
### Describe the bug

Trying to create connection on Mac using updated CLI, 

### Related command

az functionapp connection create sql --connection sql_33fxxxx --source-id /subscriptions/xxxxx/resourceGroups/ATS/providers/Microsoft.Web/sites/xxxxxx --target-id /subscriptions/xxxxx/resourceGroups/ATS/providers/Microsoft.Sql/servers/xxxxxx/databases/xxxxx --client-type nodejs --system-identity

### Errors

The command failed with an unexpected error. 
AttributeError: 'CommandResultItem' object has no attribute 'stdout'

### Issue script & Debug output

The command failed with an unexpected error. Here is the traceback:
'CommandResultItem' object has no attribute 'stdout'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py", line 35, in connection_create_ext
    return connection_create_func(cmd, client, connection_name, client_type,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/serviceconnector/custom.py", line 501, in connection_create_func
    new_auth_info = enable_mi_for_db_linker(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 88, in enable_mi_for_db_linker
    source_object_id = source_handler.get_identity_pid()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 1069, in get_identity_pid
    identity = run_cli_cmd(
               ^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_utils.py", line 40, in run_cli_cmd
    return run_cli_cmd_base(cmd + ' -o json', retry, interval, should_retry_func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_utils.py", line 61, in run_cli_cmd_base
    if output.error or (should_retry_func and should_retry_func(output)):
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jerry/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 992, in output_is_none
    return not output.stdout
               ^^^^^^^^^^^^^
AttributeError: 'CommandResultItem' object has no attribute 'stdout'

### Expected behavior

Success, create connection

### Environment Summary

azure-cli                         2.64.0
core                              2.64.0
telemetry                          1.1.0
Extensions:
serviceconnector-passwordless               3.1.0
Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/bin/python'
Extensions directory '/Users/jerry/.azure/cliextensions'

Python (Darwin) 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yungezz** [comment]
hi @xfz11 , could you pls help to look at the passwordless error? thanks.
