### ISSUE TITLE
Authentication error when downloading artifact

### ISSUE THREAD

**Issue by madslund93** [Azure/azure-cli#29995]
### Describe the bug

I want to download an artifact from a feed in the project artifact store. I am using the command copied from the artifact page in the browser. 

Before this command, I used 'az devops login' to login using a valid PAT with full access. I have access to the artifact page in the browser, so my user is authorized. 

### Related command

az artifacts universal download

### Errors

cli.azext_devops.dev.common.artifacttool: Encountered an unexpected error.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.RequestHandler.<>c__DisplayClass19_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.RequestHandler.<>c__DisplayClass18_0.<<HandleRedirectAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.ExceptionExtensions.ReThrow(Exception ex)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass38_2.<<GetDedupGettersAsync>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadToFileAsync(DedupIdentifier dedupId, String fullPath, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadSingleManifestAsync(DownloadDedupManifestArtifactOptions downloadOptions, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsync(DownloadDedupManifestArtifactOptions downloadOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Packaging.UPackClientShared.UPackSharedClient.DownloadAsync(String projectNameOrId, String feedNameOrId, String packageName, String packageVersion, String targetDirectory, IEnumerable`1 minimatchPatterns, CancellationToken cancellationToken)
   at ArtifactTool.Commands.UPack.UPackDownloadCommandBase.<>c__DisplayClass2_0.<<DownloadPackageAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommandBase.cs:line 26
--- End of stack trace from previous location ---
   at ArtifactTool.Commands.UPack.UPackExceptionMapper.WithExceptionHandlingAsync(Func`1 act) in D:\a\_work\1\s\src\ArtifactTool\Commands\UPack\UPackExceptionMapper.cs:line 39
   at ArtifactTool.Commands.UPack.UPackDownloadCommandBase.DownloadPackageAsync(UPackSinglePackageDownloadRequest request) in D:\a\_work\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommandBase.cs:line 23
   at ArtifactTool.Commands.UPackDownloadCommand.ExecuteAsync() in D:\a\_work\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommand.cs:line 41
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in D:\a\_work\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 105
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 57
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 112

### Issue script & Debug output

az artifacts universal download --debug --organization "https://dev.azure.com/ORGANIZATION/" --project "PROJECT_ID" --scope project --feed "FEED_NAME" --name "ARTIFACT_NAME" --version "VERSION" --path

cli.knack.cli: Command arguments: ['artifacts', 'universal', 'download', '--debug', '--organization', 'https://dev.azure.com/ORGANIZATION/', '--project', 'PROJECT_ID', '--scope', 'project', '--feed', 'internal', '--name', 'ARTIFACT_NAME', '--version', '0.0.131', '--path', '.']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7dbb41b0c040>, <function OutputProducer.on_global_arguments at 0x7dbb41ab6200>, <function CLIQuery.on_global_arguments at 0x7dbb41af3ce0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'artifacts': ['azext_devops']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-devops              0.053        60       192  /home/madslund/.azure/cliextensions/azure-devops
cli.azure.cli.core: Total (1)                 0.053        60       192  
cli.azure.cli.core: Loaded 60 groups, 192 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : artifacts universal download
cli.azure.cli.core: Command table: artifacts universal download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7dbb40dcdda0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/madslund/.azure/commands/2024-09-27.12-59-54.artifacts_universal_download.21847.log'.
az_command_data_logger: command args: artifacts universal download --debug --organization {} --project {} --scope {} --feed {} --name {} --version {} --path {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7dbb40e08540>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7dbb40e1e480>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7dbb40e1e5c0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x7dbb40e1e660>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7dbb41ab62a0>, <function CLIQuery.handle_query_parameter at 0x7dbb41af3d80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7dbb40e1e520>, <function DevCommandsLoader.post_parse_args at 0x7dbb40c7cea0>]
az_command_data_logger: extension name: azure-devops
az_command_data_logger: extension version: 1.0.1
cli.azext_devops.dev.common.artifacttool_updater: Checking for a new ArtifactTool
cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: trying to get token (temp) for tenant 668a2343-cf58-461a-8ea8-d2b20966356c and user mads.lund@d-i-s.dk 
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/madslund/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/madslund/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c
msal.authority: openid_config("https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
msal.application: Found 1 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': '********.668a2343-cf58-461a-8ea8-d2b20966356c', 'family_id': '1'}
msal.telemetry: Generate or reuse correlation_id: 13ca1730-ee30-4ac8-b5eb-39335ca29d4e
msal.application: Cache attempts an RT
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/token HTTP/1.1" 200 4700
msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "refresh_token": "********",
        "scope": [
            "499b84ac-1321-427f-aa17-267ca6975798/.default",
            "openid",
            "offline_access",
            "profile"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ1aWQiOiI1M2VkYjc5NS0wMjg3LTQ3YTUtOTcyOC1jMzk1ZjFmYzNjNWQiLCJ1dGlkIjoiNjY4YTIzNDMtY2Y1OC00NjFhLThlYTgtZDJiMjA5NjYzNTZjIn0",
        "expires_in": 5158,
        "ext_expires_in": 5158,
        "foci": "1",
        "id_token": "********",
        "scope": "499b84ac-1321-427f-aa17-267ca6975798/user_impersonation 499b84ac-1321-427f-aa17-267ca6975798/.default",
        "token_type": "Bearer"
    },
    "scope": [
        "499b84ac-1321-427f-aa17-267ca6975798/user_impersonation",
        "499b84ac-1321-427f-aa17-267ca6975798/.default"
    ],
    "skip_account_creation": true,
    "token_endpoint": "https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/token"
}
cli.azext_devops.dev.common.services: instance recieved in validate_token_for_instance https://dev.azure.com/ORGANIZATION/
cli.azext_devops.dev.common.services: instance processed in validate_token_for_instance https://dev.azure.com/ORGANIZATION/
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache: Loading cache file: /home/madslund/.azure-devops/python-sdk/cache/resources.json
azext_devops.devops_sdk._file_cache: attempting to read file /home/madslund/.azure-devops/python-sdk/cache/resources.json as utf-8-sig
azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/ORGANIZATION
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache: Loading cache file: /home/madslund/.azure-devops/python-sdk/cache/options.json
azext_devops.devops_sdk._file_cache: attempting to read file /home/madslund/.azure-devops/python-sdk/cache/options.json as utf-8-sig
azext_devops.devops_sdk.client: File cache hit for options on: https://dev.azure.com/ORGANIZATION
azext_devops.devops_sdk.client: Route template: _apis/{resource}/{*projectId}
azext_devops.devops_sdk.client: Api version '5.0'
azext_devops.devops_sdk.client: GET https://dev.azure.com/ORGANIZATION/_apis/projects?stateFilter=all&$top=1&$skip=0
azext_devops.devops_sdk.client: Request content: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
urllib3.connectionpool: https://dev.azure.com:443 "GET /ORGANIZATION/_apis/projects?stateFilter=all&$top=1&$skip=0 HTTP/1.1" 200 336
azext_devops.devops_sdk.client: Response content: b'{"count":1,"value":[{"id":"563704e2-b573-4534-9b38-34fbc00927fd","name":"Internal","url":"https://dev.azure.com/ORGANIZATION/_apis/projects/563704e2-b573-4534-9b38-34fbc00927fd","state":"wellFormed","revision":120,"visibility":"private","lastUpdateTime":"2024-04-23T07:12:20.827Z"}]}'
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.telemetry: Azure devops telemetry enabled.
cli.azext_devops.dev.common.telemetry: Logging telemetry to azure devops server.
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client: File cache hit for options on: https://dev.azure.com/ORGANIZATION
azext_devops.devops_sdk.client: Route template: _apis/{area}/{resource}
azext_devops.devops_sdk.client: Api version '5.0-preview.1'
azext_devops.devops_sdk.client: POST https://dev.azure.com/ORGANIZATION/_apis/CustomerIntelligence/Events
azext_devops.devops_sdk.client: Request content: [{'area': 'AzureDevopsCli', 'feature': 'artifacts', 'properties': {'Command': 'universal download', 'Args': 'feed name version path scope organization project', 'ShellType': '/bin/bash', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False}}]
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/ORGANIZATION
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.artifacttool_updater: Looking up current version of ArtifactTool...
azext_devops.devops_sdk.client: File cache hit for options on: https://vsblob.dev.azure.com/ORGANIZATION
azext_devops.devops_sdk.client: Route template: _apis/{area}/{toolName}/{resource}
azext_devops.devops_sdk.client: Api version '5.0-preview'
azext_devops.devops_sdk.client: GET https://vsblob.dev.azure.com/ORGANIZATION/_apis/clienttools/ArtifactTool/release?osName=Linux&arch=x86_64&distroName=ubuntu&distroVersion=22.04
azext_devops.devops_sdk.client: Request content: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): vsblob.dev.azure.com:443
urllib3.connectionpool: https://dev.azure.com:443 "POST /ORGANIZATION/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool: https://vsblob.dev.azure.com:443 "GET /ORGANIZATION/_apis/clienttools/ArtifactTool/release?osName=Linux&arch=x86_64&distroName=ubuntu&distroVersion=22.04 HTTP/1.1" 200 441
azext_devops.devops_sdk.client: Response content: b'{"name":"ArtifactTool","rid":"linux-x64","version":"0.2.350","uri":"https://050vsblobprodweu241.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.350.zip?sv=2019-07-07&sr=b&sig=JMokQ1WOkHkAUEjlOWFWXc2xoT68I1gwCO9n3b0imbY%3D&se=2024-09-27T11%3A59%3A56Z&sp=r&P1=1727438096&P2=11&P3=2&P4=tfAc%2fk3kj3Fm%2bbMQvzZYNbPR%2f905BEalbHCb78ib%2f%2f8%3d"}'
cli.azext_devops.dev.common.artifacttool_updater: Checking if we already have ArtifactTool release 'ArtifactTool_linux-x64_0.2.350'
cli.azext_devops.dev.common.artifacttool_updater: Not updating ArtifactTool because the current release already exists at '/home/madslund/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.350'
cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: trying to get token (temp) for tenant 668a2343-cf58-461a-8ea8-d2b20966356c and user mads.lund@d-i-s.dk 
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c
msal.authority: openid_config("https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/668a2343-cf58-461a-8ea8-d2b20966356c/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: e0859d72-94fd-48a7-96e5-764490ff9a97
cli.azext_devops.dev.common.services: instance recieved in validate_token_for_instance https://dev.azure.com/ORGANIZATION/
cli.azext_devops.dev.common.services: instance processed in validate_token_for_instance https://dev.azure.com/ORGANIZATION/
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/ORGANIZATION
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client: Route template: _apis/{resource}/{*projectId}
azext_devops.devops_sdk.client: Api version '5.0'
azext_devops.devops_sdk.client: GET https://dev.azure.com/ORGANIZATION/_apis/projects?stateFilter=all&$top=1&$skip=0
azext_devops.devops_sdk.client: Request content: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
urllib3.connectionpool: https://dev.azure.com:443 "GET /ORGANIZATION/_apis/projects?stateFilter=all&$top=1&$skip=0 HTTP/1.1" 200 336
azext_devops.devops_sdk.client: Response content: b'{"count":1,"value":[{"id":"563704e2-b573-4534-9b38-34fbc00927fd","name":"Internal","url":"https://dev.azure.com/ORGANIZATION/_apis/projects/563704e2-b573-4534-9b38-34fbc00927fd","state":"wellFormed","revision":120,"visibility":"private","lastUpdateTime":"2024-04-23T07:12:20.827Z"}]}'
cli.azext_devops.dev.common.external_tool: Running external command: /home/madslund/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.350/artifacttool universal download --service https://dev.azure.com/ORGANIZATION/ --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed internal --package-name ARTIFACT_NAME --package-version 0.0.131 --path . --project PROJECT_ID
cli.azext_devops.dev.common.artifacttool: ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session d0be1947-eaed-4d16-beff-7f817f75a9cb
cli.azext_devops.dev.common.artifacttool: Obtained package metadata
cli.azext_devops.dev.common.artifacttool: DedupManifestArtifactClient will correlate http requests with X-TFS-Session d0be1947-eaed-4d16-beff-7f817f75a9cb
cli.azext_devops.dev.common.artifacttool: ApplicationInsightsTelemetrySender did not correlate any events with X-TFS-Session d0be1947-eaed-4d16-beff-7f817f75a9cb

### Expected behavior

I expected the artifact to be downloaded to my current location.

### Environment Summary

{
  "azure-cli": "2.64.0",
  "azure-cli-core": "2.64.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "1.0.1"
  }
}
Operating System: Ubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.8.0-45-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 PRO 5875U with Radeon Graphics
Memory: 61,6 GiB of RAM
Graphics Processor: RENOIR

### Additional context

This works on other PC's (both windows and ubuntu) with the same PAT.
azure cli is installed as in option #2 in this guide: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
