### ISSUE TITLE
Error with az ssh vm command

### ISSUE THREAD

**Issue by philoderkirk** [Azure/azure-cli#30020]
### Describe the bug

When using Azure client to login to a Azure Virtual Machine that is reachable from my local machine I'm getting the errors included below.

Before attempting to ssh login the VM I'm entering the following az commands to login to our subscription:
az login
az account set --subscription 24422345-aba2-4d54-9738-a32cda9e0067

### Related command

az ssh vm -n 'corp-dev-007-pppwtest-cc-vm-99' -g 'corp-dev-007-32ks-cc-rg'

### Errors

PS C:\Users\philip.fakelastname01> az ssh vm -n 'corp-dev-007-pppwtest-cc-vm-99' -g 'corp-dev-007-32ks-cc-rg'
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\ip_utils.py", line 17, in get_ssh_ip
    network_client = client_factory.get_mgmt_service_client(cmd.cli_ctx, profiles.ResourceType.MGMT_NETWORK)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 223, in _get_mgmt_service_client
AttributeError: 'NoneType' object has no attribute '__name__'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
PS C:\Users\philip.fakelastname01>

### Issue script & Debug output

PS C:\Users\philip.fakelastname01> az ssh vm -n 'corp-dev-007-pppwtest-cc-vm-99' -g 'corp-dev-007-32ks-cc-rg'
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\custom.py", line 66, in ssh_vm
    _do_ssh_op(cmd, ssh_session, op_call)
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\custom.py", line 159, in _do_ssh_op
    op_info.ip = op_info.ip or ip_utils.get_ssh_ip(cmd, op_info.resource_group_name,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\philip.fakelastname01\.azure\cliextensions\ssh\azext_ssh\ip_utils.py", line 17, in get_ssh_ip
    network_client = client_factory.get_mgmt_service_client(cmd.cli_ctx, profiles.ResourceType.MGMT_NETWORK)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 83, in get_mgmt_service_client
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 223, in _get_mgmt_service_client
AttributeError: 'NoneType' object has no attribute '__name__'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
PS C:\Users\philip.fakelastname01>

### Expected behavior

Expecting to login to Azure VM with az sh command.

### Environment Summary

> az version
{
  "azure-cli": "2.64.0",
  "azure-cli-core": "2.64.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ssh": "1.1.3"
  }

### Additional context

na

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by philoderkirk** [comment]
Issue resolved now.  SSH upgrade via 'az upgrade' command resolved this, so likely SSH version was out of date.  Thanks though!
