### ISSUE TITLE
Cannot create a Bing Search resource via az CLI

### ISSUE THREAD

**Issue by shane-au-wade** [Azure/azure-cli#30029]
### Describe the bug

I've logged into my azure account and a subscription has been created. 

I've manually created a bing resource via the Azure Portal and now I'd like to create these resource programmatically. 

I've looked through a number of guides and produced the command below.  I'm aware of the transfer from the Cognitive Services platform to the Azure Marketplace platform. 

```
az resource create --resource-group search --resource-type Microsoft.Bing/accounts --name bing-search-developement-staging --location global \
--properties '{"statisticsEnabled": false}'
```

This command results in the following error message, which does not indicate how to fix the issue.

```bash
(InternalServerError) Unexpected error.
Code: InternalServerError
Message: Unexpected error.
Command ran in 1.503 seconds (init: 0.118, invoke: 1.385)
```

The goal is to programmatically create a bing search resource, any advice is welcome.  

### Related command

az resource create --resource-group search --resource-type Microsoft.Bing/accounts --name bing-search-developement-staging --location global \
--properties '{"statisticsEnabled": false}'

### Errors

(InternalServerError) Unexpected error.
Code: InternalServerError
Message: Unexpected error.
Command ran in 1.503 seconds (init: 0.118, invoke: 1.385)

### Issue script & Debug output

cli.knack.cli: Command arguments: ['resource', 'create', '--resource-group', 'search', '--resource-type', 'Microsoft.Bing/accounts', '--name', 'bing-search-developement-staging', '--location', 'global', '--properties', '{"statisticsEnabled": false}', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105103560>, <function OutputProducer.on_global_arguments at 0x105470a40>, <function CLIQuery.on_global_arguments at 0x10548e520>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'resource': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.092        51       231
cli.azure.cli.core: Total (1)                 0.092        51       231
cli.azure.cli.core: Loaded 51 groups, 231 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : resource create
cli.azure.cli.core: Command table: resource create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1066aa3e0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/shane/.azure/commands/2024-10-03.16-44-34.resource_create.69382.log'.
az_command_data_logger: command args: resource create --resource-group {} --resource-type {} --name {} --location {} --properties {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1066dff60>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x106703560>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1067036a0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x106703740>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x105470ae0>, <function CLIQuery.handle_query_parameter at 0x10548e5c0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x106703600>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/shane/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/shane/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4
msal.authority: openid_config("https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/1ca22a46-5538-42df-ac8d-3bde50ab01c4/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: cd08e1db-e27b-44db-a86d-2a75bf84e544
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/079673bb-cff2-4900-a66f-7e350f0a2dbc/providers/Microsoft.Bing?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '71c894c8-81e1-11ef-8050-d627217ab1d3'
cli.azure.cli.core.sdk.policies:     'CommandName': 'resource create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --resource-type --name --location --properties --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.64.0 (HOMEBREW) azsdk-python-core/1.28.0 Python/3.11.10 (macOS-14.5-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/079673bb-cff2-4900-a66f-7e350f0a2dbc/providers/Microsoft.Bing?api-version=2022-09-01 HTTP/1.1" 200 1229
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1229'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '249'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '3749'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '71d43af5-2cec-4c00-a7ad-fba4f83c34df'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '71d43af5-2cec-4c00-a7ad-fba4f83c34df'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS:20241003T234435Z:71d43af5-2cec-4c00-a7ad-fba4f83c34df'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: D977EF703D984AAC953FBB4E2E79B77E Ref B: SJC211051204037 Ref C: 2024-10-03T23:44:35Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 03 Oct 2024 23:44:34 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/079673bb-cff2-4900-a66f-7e350f0a2dbc/providers/Microsoft.Bing","namespace":"Microsoft.Bing","authorizations":[{"applicationId":"c19490b5-c092-426f-b1a2-674b279d4975","roleDefinitionId":"7963cd60-9634-4abc-9a64-2482a3ef6373"}],"resourceTypes":[{"resourceType":"locations","locations":["global"],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"accounts/skus","locations":["global"],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"accounts/usages","locations":["global"],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"registeredSubscriptions","locations":["global"],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"operations","locations":[],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"locations/operationStatuses","locations":["West US","East US","West Europe","Southeast Asia"],"apiVersions":["2020-06-10"],"capabilities":"None"},{"resourceType":"accounts","locations":["global"],"apiVersions":["2020-06-10"],"capabilities":"CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SupportsTags, SupportsLocation"}],"registrationState":"Registered","registrationPolicy":"RegistrationRequired"}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/079673bb-cff2-4900-a66f-7e350f0a2dbc/resourcegroups/search/providers/Microsoft.Bing//accounts/bing-search-developement-staging?api-version=2020-06-10'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '66'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '71c894c8-81e1-11ef-8050-d627217ab1d3'
cli.azure.cli.core.sdk.policies:     'CommandName': 'resource create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --resource-type --name --location --properties --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.64.0 (HOMEBREW) azsdk-python-core/1.28.0 Python/3.11.10 (macOS-14.5-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "global", "properties": {"statisticsEnabled": false}}
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/079673bb-cff2-4900-a66f-7e350f0a2dbc/resourcegroups/search/providers/Microsoft.Bing//accounts/bing-search-developement-staging?api-version=2020-06-10 HTTP/1.1" 400 70
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-store, must-revalidate, no-cache, max-age=0'
cli.azure.cli.core.sdk.policies:     'Content-Length': '70'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Set-Cookie': '_EDGE_S=F=1&SID=30C3E5997FEE67471739F0947EA2665A; path=/; httponly; domain=bingapis.com, _EDGE_V=1; path=/; httponly; expires=Tue, 28-Oct-2025 23:44:35 GMT; domain=bingapis.com, MUID=1480C1FFC45563881A4CD4F2C519622A; path=/; expires=Tue, 28-Oct-2025 23:44:35 GMT; domain=bingapis.com, MUIDB=1480C1FFC45563881A4CD4F2C519622A; path=/; httponly; expires=Tue, 28-Oct-2025 23:44:35 GMT'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '59765B6E4DCB47EF885F0EFEC8B676F8'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c0283e9f-b811-4f56-b969-858ae0a6f3e9'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'Accept-CH': 'Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 2277CF8FF033404BBD7FC4DEE1C23FF4 Ref B: SJC211051204037 Ref C: 2024-10-03T23:44:35Z'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS:20241003T234435Z:c0283e9f-b811-4f56-b969-858ae0a6f3e9'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 03 Oct 2024 23:44:35 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Unexpected error."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 2018, in create_resource
    return res.create_resource(properties, location, is_full_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 4395, in create_resource
    resource = self.rcf.resources.begin_create_or_update(self.resource_group_name,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 9492, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 9350, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InternalServerError) Unexpected error.
Code: InternalServerError
Message: Unexpected error.

cli.azure.cli.core.azclierror: (InternalServerError) Unexpected error.
Code: InternalServerError
Message: Unexpected error.
az_command_data_logger: (InternalServerError) Unexpected error.
Code: InternalServerError
Message: Unexpected error.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1066aa660>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.253 seconds (init: 0.124, invoke: 1.129)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3990 in cache file under /Users/shane/.azure/telemetry/20241003164435991
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /Users/shane/.azure /Users/shane/.azure/telemetry/20241003164435991"
telemetry.process: Return from creating process 69387
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

A new resource in the azure portal is created.

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/bin/python'
Extensions directory '/Users/shane/.azure/cliextensions'

Python (Darwin) 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by arafattehsin** [comment]
Do we have any updates on this please?
