### ISSUE TITLE
az acr command failed with "multiple values for keyword argument" error when running on SAW

### ISSUE THREAD

**Issue by thophan-microsoft** [Azure/azure-cli#30041]
### Describe the bug

When running command `az acr login --name $acrName --expose-token` with AzureCLI v2.55.0 on the SAW, it returned error "got multiple values for keyword arguments". This behavior is not seen when running the same AzureCLI version on a non-SAW machine.

### Related command

az acr login --name $acrName --expose-token

### Errors

The command failed with an unexpected error. Here is the traceback:
__init__() got multiple values for keyword argument 'headers'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 259, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 464, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 408, in _get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 239, in _get_aad_token
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 166, in _get_aad_token_after_challenge
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/vendored_sdks/winrequests/api.py", line 164, in wrapper
  File "http_WinHTTPSession.pxi", line 206, in http.AsyncSession.post
  File "http_WinHTTPSession.pxi", line 198, in http.AsyncSession.request
  File "http_WinHTTPRequest.pxi", line 23, in http.Request.__init__
TypeError: __init__() got multiple values for keyword argument 'headers'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['acr', 'login', '--name', 'registryName', '--expose-token', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000002C9CC3FF560>, <function OutputProducer.on_global_arguments at 0x000002C9CC5822A0>, <function CLIQuery.on_global_arguments at 0x000002C9CC5B7D80>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.168        36       149
cli.azure.cli.core: Total (1)                 0.168        36       149
cli.azure.cli.core: Loaded 36 groups, 149 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : acr login
cli.azure.cli.core: Command table: acr login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000002C9CDD65EE0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\THOPHAN\.azure\commands\2024-10-07.17-16-26.acr_login.17904.log'.
az_command_data_logger: command args: acr login --name {} --expose-token --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000002C9CDDBA340>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000002C9CF28C400>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000002C9CF28C540>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000002C9CC582340>, <function CLIQuery.handle_query_parameter at 0x000002C9CC5B7E20>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000002C9CF28C4A0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\THOPHAN\\.azure\\msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: C:\Users\THOPHAN\.azure\msal_http_cache.bin
cli.azure.cli.core.auth.binary_cache: C:\Users\THOPHAN\.azure\msal_http_cache.bin not found. Using a fresh one.
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
msal.authority: openid_config = {'token_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/token'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/token%27), 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': '[https://login.microsoftonline.com/tenantId/discovery/v2.0/keys'](https://login.microsoftonline.com/tenantId/discovery/v2.0/keys%27), 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': '[https://login.microsoftonline.com/tenantId/v2.0'](https://login.microsoftonline.com/tenantId/v2.0%27), 'request_uri_parameter_supported': False, 'userinfo_endpoint': '[https://graph.microsoft.com/oidc/userinfo'](https://graph.microsoft.com/oidc/userinfo%27), 'authorization_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/authorize'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/authorize%27), 'device_authorization_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/devicecode'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/devicecode%27), 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/logout'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/logout%27), 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': '[https://login.microsoftonline.com/tenantId/kerberos'](https://login.microsoftonline.com/tenantId/kerberos%27), 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('[https://management.core.windows.net//.default',)](https://management.core.windows.net//.default%27,)), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('[https://management.core.windows.net//.default',)](https://management.core.windows.net//.default%27,)), claims=None, kwargs={}
msal.application: Found 1 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': '********.tenantId', 'family_id': '1'}
msal.telemetry: Generate or reuse correlation_id: 9a4a6946-453a-49ba-90f8-5666bf6cabbd
msal.application: Cache attempts an RT
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
msal.token_cache: event={
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "refresh_token": "********",
        "scope": [
            "offline_access",
            "openid",
            "profile",
            "[https://management.core.windows.net//.default"](https://management.core.windows.net//.default%22)
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "clientInfo",
        "expires_in": 4681,
        "ext_expires_in": 4681,
        "foci": "1",
        "id_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation [https://management.core.windows.net//.default"](https://management.core.windows.net//.default%22),
        "token_type": "Bearer"
    },
    "scope": [
        "[https://management.core.windows.net//user_impersonation"](https://management.core.windows.net//user_impersonation%22),
        "[https://management.core.windows.net//.default"](https://management.core.windows.net//.default%22)
    ],
    "skip_account_creation": true,
    "token_endpoint": "[https://login.microsoftonline.com/tenantId/oauth2/v2.0/token"](https://login.microsoftonline.com/tenantId/oauth2/v2.0/token%22)
}
cli.azure.cli.core.sdk.policies: Request URL: '[https://management.azure.com/subscriptions/subscriptionId/resources?$filter=resourceType%20eq%20%27Microsoft.ContainerRegistry%2Fregistries%27&api-version=2022-09-01'](https://management.azure.com/subscriptions/subscriptionId/resources?$filter=resourceType%20eq%20%27Microsoft.ContainerRegistry%2Fregistries%27&api-version=2022-09-01%27)
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8eee8a86-850a-11ef-a3f4-9b12625a3dfa'
cli.azure.cli.core.sdk.policies:     'CommandName': 'acr login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --expose-token --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.7 (Windows-10-10.0.22621)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 08 Oct 2024 00:16:30 GMT'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '12'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '1099'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '16499'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '8e1605a5-5eea-4036-b6fc-c8e73028a63b'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8e1605a5-5eea-4036-b6fc-c8e73028a63b'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS2:20241008T001631Z:8e1605a5-5eea-4036-b6fc-c8e73028a63b'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 440058A9ED154F3D9C626580EFCD5318 Ref B: CO6AA3150218037 Ref C: 2024-10-08T00:16:31Z'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[]}
cli.azure.cli.command_modules.acr._docker_utils: Could not get registry from service. Exception: The resource with name 'devcenterpublicexternal' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'subscriptionName (subscriptionId)'.
cli.azure.cli.command_modules.acr._docker_utils: 2024-10-08 00:16:31.960382 Sending a HTTP Get request to https://devcenterpublicexternal.azurecr.io/v2/
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
cli.azure.cli.command_modules.acr._docker_utils: Attempting to retrieve AAD refresh token...
cli.azure.cli.command_modules.acr._docker_utils: 2024-10-08 00:16:32.499837 Sending a HTTP Get request to https://devcenterpublicexternal.azurecr.io/v2/
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
cli.azure.cli.core.auth.binary_cache: load: C:\Users\THOPHAN\.azure\msal_http_cache.bin
cli.azure.cli.core.auth.binary_cache: C:\Users\THOPHAN\.azure\msal_http_cache.bin not found. Using a fresh one.
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
asyncio: Using proactor: IocpProactor
msal.authority: openid_config = {'token_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/token'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/token%27), 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': '[https://login.microsoftonline.com/tenantId/discovery/v2.0/keys'](https://login.microsoftonline.com/tenantId/discovery/v2.0/keys%27), 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': '[https://login.microsoftonline.com/tenantId/v2.0'](https://login.microsoftonline.com/tenantId/v2.0%27), 'request_uri_parameter_supported': False, 'userinfo_endpoint': '[https://graph.microsoft.com/oidc/userinfo'](https://graph.microsoft.com/oidc/userinfo%27), 'authorization_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/authorize'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/authorize%27), 'device_authorization_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/devicecode'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/devicecode%27), 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': '[https://login.microsoftonline.com/tenantId/oauth2/v2.0/logout'](https://login.microsoftonline.com/tenantId/oauth2/v2.0/logout%27), 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': '[https://login.microsoftonline.com/tenantId/kerberos'](https://login.microsoftonline.com/tenantId/kerberos%27), 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('[https://management.core.windows.net//.default',)](https://management.core.windows.net//.default%27,)), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 66148140-d13c-45b7-93a5-ffdd71353f4c
cli.azure.cli.command_modules.acr._docker_utils: 2024-10-08 00:16:33.795249 Sending a HTTP Post request to https://devcenterpublicexternal.azurecr.io/oauth2/exchange
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 259, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 464, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 408, in _get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 239, in _get_aad_token
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 166, in _get_aad_token_after_challenge
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/vendored_sdks/winrequests/api.py", line 164, in wrapper
  File "http_WinHTTPSession.pxi", line 206, in http.AsyncSession.post
  File "http_WinHTTPSession.pxi", line 198, in http.AsyncSession.request
  File "http_WinHTTPRequest.pxi", line 23, in http.Request.__init__
TypeError: __init__() got multiple values for keyword argument 'headers'
 
cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: __init__() got multiple values for keyword argument 'headers'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 259, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 464, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 408, in _get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 239, in _get_aad_token
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 166, in _get_aad_token_after_challenge
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/vendored_sdks/winrequests/api.py", line 164, in wrapper
  File "http_WinHTTPSession.pxi", line 206, in http.AsyncSession.post
  File "http_WinHTTPSession.pxi", line 198, in http.AsyncSession.request
  File "http_WinHTTPRequest.pxi", line 23, in http.Request.__init__
TypeError: __init__() got multiple values for keyword argument 'headers'
az_command_data_logger: __init__() got multiple values for keyword argument 'headers'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 259, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 464, in get_login_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 408, in _get_credentials
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 239, in _get_aad_token
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 166, in _get_aad_token_after_challenge
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/vendored_sdks/winrequests/api.py", line 164, in wrapper
  File "http_WinHTTPSession.pxi", line 206, in http.AsyncSession.post
  File "http_WinHTTPSession.pxi", line 198, in http.AsyncSession.request
  File "http_WinHTTPRequest.pxi", line 23, in http.Request.__init__
TypeError: __init__() got multiple values for keyword argument 'headers'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002C9CDD66160>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 7.641 seconds (init: 0.390, invoke: 7.251)

### Expected behavior

Returns the access token to the registry

### Environment Summary

azure-cli                         2.55.0
 
core                              2.55.0
telemetry                          1.1.0
 
Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2
 
Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\THOPHAN\.azure\cliextensions'
 
Python (Windows) 3.11.7 (remotes/origin/3.11.7/msft-spython:be2aebf208, Dec 11 2023, 22:59:37) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thophan-microsoft** [comment]
> Hi @thophan-microsoft,
> 
> 2.55.0 is not the latest Azure CLI(2.64.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Additional context, v2.55.0 is the latest version on SAW, and the issue doesn't seems to be related to version as the same version works on a non-SAW machine.

**Comment by dhr-verma** [comment]
[celebrate]     Dhruv Verma reacted to your message:
________________________________

**Comment by terencet-dev** [comment]
We are still waiting for the new version to be published in SAW

**Comment by terencet-dev** [comment]
New version on SAW was released.
