### ISSUE TITLE
Unable to create new network rule in firewall policy - Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)

### ISSUE THREAD

**Issue by r4hulp** [Azure/azure-cli#30070]
### Expected Behavior
The command should accept a string or list of strings for the `--protocols` argument, as documented in the Azure CLI reference.

### Steps to Reproduce
1. Set up an Azure Firewall Policy and a Rule Collection Group
2. Run the following command (or a similar variant):
   ```
   az network firewall policy rule-collection-group collection rule add \
     --resource-group <resource-group-name> \
     --policy-name <policy-name> \
     --rcg-name <rule-collection-group-name> \
     --collection-name <collection-name> \
     --name <rule-name> \
     --rule-type NetworkRule \
     --protocols TCP \
     --source-addresses <source-addresses> \
     --destination-addresses <destination-addresses> \
     --destination-ports <destination-ports>
   ```

### Environment
- Azure CLI version: 2.65.0

### Related command

az network firewall policy rule-collection-group collection rule add --resource-group rg-connectivity-dev-01 --policy-name azfwpolicy-connectivity-dev-01_test --rcg-name test --collection-name network-rc --name IP-to-IPAddresses-Rule --rule-type NetworkRule --protocols TCP UDP --description 'Sample network rule' --source-addresses 10.0.0.0/24 192.168.1.0/24 --destination-addresses 20.30.40.0/24 50.60.70.80/32 --no-wait --debug

### Errors

```
cli.azure.cli.core.azclierror: Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)
az_command_data_logger: Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)
```

### Issue script & Debug output

```
cli.knack.cli: Command arguments: ['network', 'firewall', 'policy', 'rule-collection-group', 'collection', 'rule', 'add', '--resource-group', 'rg-connectivity-dev-01', '--policy-name', 'azfwpolicy-connectivity-dev-01_test', '--rcg-name', 'test', '--collection-name', 'network-rc', '--name', 'IP-to-IPAddresses-Rule', '--rule-type', 'NetworkRule', '--protocols', 'TCP', 'UDP', '--description', 'Sample network rule', '--source-addresses', '10.0.0.0/24', '192.168.1.0/24', '--destination-addresses', '20.30.40.0/24', '50.60.70.80/32', '--no-wait', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001E5B188FE20>, <function OutputProducer.on_global_arguments at 0x000001E5B1A38180>, <function CLIQuery.on_global_arguments at 0x000001E5B1A5DD00>]    
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_firewall', 'azext_vwan']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.775       117       459
cli.azure.cli.core: privatedns                0.022        14        60
cli.azure.cli.core: Total (2)                 0.797       131       519
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-firewall            0.046        21        75  C:\Users\rp\.azure\cliextensions\azure-firewall
cli.azure.cli.core: virtual-wan               0.122        21        77  C:\Users\rp\.azure\cliextensions\virtual-wan
cli.azure.cli.core: Total (2)                 0.168        42       152
cli.azure.cli.core: Loaded 170 groups, 671 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network firewall policy rule-collection-group collection rule add
cli.azure.cli.core: Command table: network firewall policy rule-collection-group collection rule add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001E5B24CC180>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\rp\.azure\commands\2024-10-11.13-36-16.network_firewall_policy_rule-collection-group_collection_rule_add.58608.log'.
az_command_data_logger: command args: network firewall policy rule-collection-group collection rule add --resource-group {} --policy-name {} --rcg-name {} --collection-name {} --name {} --rule-type {} --protocols {} {} --description {} --source-addresses {} {} --destination-addresses {} {} --no-wait --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001E5B2558C20>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001E5B2558CC0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001E5B2558E00>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x000001E5B2558EA0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_action.py", line 89, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_action.py", line 189, in setup_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_action.py", line 324, in format_data
azure.cli.core.aaz.exceptions.AAZInvalidValueError: dict type value expected, got 'TCP'(<class 'str'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 591, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/parser.py", line 261, in parse_args
  File "argparse.py", line 1869, in parse_args
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2096, in _parse_known_args
  File "argparse.py", line 2073, in consume_positionals
  File "argparse.py", line 1978, in take_action
  File "argparse.py", line 1241, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "argparse.py", line 1902, in parse_known_args
  File "argparse.py", line 2114, in _parse_known_args
  File "argparse.py", line 2054, in consume_optional
  File "argparse.py", line 1978, in take_action
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_arg_action.py", line 95, in __call__
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)

cli.azure.cli.core.azclierror: Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)
az_command_data_logger: Failed to parse '--protocols' argument: dict type value expected, got 'TCP'(<class 'str'>)
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001E5B24CC400>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.618 seconds (init: 0.360, invoke: 1.258)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3832 in cache file under C:\Users\rp\.azure\telemetry\20241011133617217
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\rp\.azure C:\Users\rp\.azure\telemetry\20241011133617217"
telemetry.process: Return from creating process 28736
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

The Azure CLI documentation suggests that the `--protocols` argument should accept either a single protocol or a space-separated list of protocols. However, the current implementation seems to expect a dictionary type instead of a string or list of strings.

### Environment Summary

{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "1.0.1",
    "azure-firewall": "1.2.0",
    "virtual-wan": "1.0.1"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
from https://learn.microsoft.com/en-us/cli/azure/network/firewall/policy/rule-collection-group/collection/rule?view=azure-cli-latest#az-network-firewall-policy-rule-collection-group-collection-rule-add, we can find:
```text
--protocols

Space-separated list of protocols and port numbers to use, in PROTOCOL=PORT format. Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
```

**Comment by r4hulp** [comment]
Hi @necusjz, I understand what you meant here.. but how would you translate Any from the options in the Network Rule with the port? 

![Image](https://github.com/user-attachments/assets/a8cd58b9-ec83-49e6-8da8-f82aedd8142c)

**Comment by necusjz** [comment]
what's the port number for TCP protocol? if it's 65535, then input TCP=65535.
