### ISSUE TITLE
az network local-gateway update - Operation not found error message

### ISSUE THREAD

**Issue by robtomlinson** [Azure/azure-cli#30169]
### Describe the bug

Using the latest version of the Azure CLI (2.65.0), I am trying to update the gateway ip address of a local gateway via the following command:
`az network local-gateway update -g "XXXX" -n "XXXX" --gateway-ip-address 0.0.0.0`
The command keeps returning the following message:
> (None) Operation e258be13-88f3-426d-96ef-e62a16493f1b not found.
> Code: None
> Message: Operation e258be13-88f3-426d-96ef-e62a16493f1b not found.

When I append the `--debug` flag, I get more detail. After making a series of successful GET calls, it fails on this particular GET (partial debug output below) and returns a status 404 which then prompts the `Operation xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx not found` error message. The guid in this error message appears to be an internally generated guid and does not match any of the parameters I have provided, and it changes each time I repeat the command.

> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'network local-gateway update'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --gateway-ip-address --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.65.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.20348-SP0)'

I have verified the user principal has access and permissions to this resource, and also tested this with an elevated user/role and receive the same results.

### Related command

Resource group, name, and ip address are redacted below.

`az network local-gateway update -g "XXXX" -n "XXXX" --gateway-ip-address 0.0.0.0`
or
`az network local-gateway update --resource-group "XXXX" --name "XXXX" --gateway-ip-address 0.0.0.0`

### Errors

> (None) Operation e258be13-88f3-426d-96ef-e62a16493f1b not found.
> Code: None
> Message: Operation e258be13-88f3-426d-96ef-e62a16493f1b not found.

### Issue script & Debug output

Here is the response and traceback from `--debug`:

cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '94'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c268cda4-7cb2-4364-9786-8be213bc0d33'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '5e3cdf0f-fd52-4dc2-acc6-2f94530402a9'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '9226790b-00c8-471f-a7d5-03b0ee0a59da'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '249'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-reads': '3749'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHCENTRALUS:20241023T170859Z:5e3cdf0f-fd52-4dc2-acc6-2f94530402a9'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: F5A552DADBF54164A3B5DC31A2509109 Ref B: SN4AA2022305033 Ref C: 2024-10-23T17:08:59Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 23 Oct 2024 17:08:58 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"message":"Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.","details":[]}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 730, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 756, in _poll
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 782, in update_status
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 156, in _raise_if_bad_http_status_and_method
azure.core.polling.base_polling.BadStatus: Invalid return status 404 for 'GET' operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 45, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 734, in run
azure.core.exceptions.HttpResponseError: (None) Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
Code: None
Message: Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1075, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 94, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 86, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 50, in run
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 329, in on_error
azure.core.exceptions.ResourceNotFoundError: (None) Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
Code: None
Message: Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.

cli.azure.cli.core.azclierror: (None) Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
Code: None
Message: Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
az_command_data_logger: (None) Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
Code: None
Message: Operation bc032843-83e0-4b0e-b37d-97e441a64159 not found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001FA04CC4040>]
az_command_data_logger: exit code: 3

### Expected behavior

Following the CLI documentation for this az command, I would expect to be able to update the gateway ip address of the local gateway via the CLI tool.

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Administrator\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I also tried a workaround by calling the Azure REST API to perform the same update and received a similar error there as well. However, I did not test this as extensively (different users/roles, etc.)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
