### ISSUE TITLE
azure-iot: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' - 2.65.0 - 0.25.0

### ISSUE THREAD

**Issue by emibcn** [Azure/azure-cli#30209]
### Describe the bug

Erroor thrown when executing a `du update stage` command

After some checks, same issue occurs in extension azure-iot version 0.24.0 and 0.23.0. It occurs -at least- with core version 2.61.0 and 2.65.0.

I'm using az cli installed in an Ubuntu system using `apt install azure-cli` (from [Microsoft repo](https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.65.0-1~focal_amd64.deb) ):
- OS: Ubuntu 20.04.6 LTS - Focal
-  Python: 3.11

### Related command

`az iot du update stage`

### Errors

```
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 432, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/commands_update.py", line 486, in stage_update
    from azext_iot.deviceupdate.providers.storage import StorageAccountManager
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/providers/storage.py", line 7, in <module>
    from azure.identity import AzureCliCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/__init__.py", line 10, in <module>
    from ._credentials import (
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/authorization_code.py", line 7, in <module>
    from azure.core.credentials import AccessToken, AccessTokenInfo, TokenRequestOptions
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

cli.knack.cli: Command arguments: ['iot', 'du', 'update', 'stage', '--debug', '--account', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.DeviceUpdate/accounts/*****', '--instance', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.DeviceUpdate/accounts/*****/instances/*****', '--storage-account', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.Storage/storageAccounts/*****', '--storage-container', 'stage', '--manifest-path', 'manifest.json', '--overwrite', '--then-import']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f17a6522700>, <function OutputProducer.on_global_arguments at 0x7f17a6261bc0>, <function CLIQuery.on_global_arguments at 0x7f17a629b6a0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
cli.azure.cli.core: Command index has been invalidated.
cli.azure.cli.core: No module found from index for '['iot', 'du', 'update', 'stage', '--debug', '--account', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.DeviceUpdate/accounts/*****', '--instance', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.DeviceUpdate/accounts/*****/instances/*****', '--storage-account', '/subscriptions/*****/resourceGroups/*****/providers/Microsoft.Storage/storageAccounts/*****', '--storage-container', 'stage', '--manifest-path', 'manifest.json', '--overwrite', '--then-import']'
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'compute_recommender', 'config', 'configure', 'consumption', 'container', 'containerapp', 'cosmosdb', 'databoxedge', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'mysql', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.150        36       149
cli.azure.cli.core: acs                       0.021        14        77
cli.azure.cli.core: advisor                   0.001         3         6
cli.azure.cli.core: ams                       0.006        22       100
cli.azure.cli.core: apim                      0.005        14        69
cli.azure.cli.core: appconfig                 0.003         9        47
cli.azure.cli.core: appservice                0.052        79       270
cli.azure.cli.core: aro                       0.009         1        10
cli.azure.cli.core: backup                    0.025        16        60
cli.azure.cli.core: batch                     0.032        34       102
cli.azure.cli.core: batchai                   0.003        10        30
cli.azure.cli.core: billing                   0.012        20        53
cli.azure.cli.core: botservice                0.003        12        42
cli.azure.cli.core: cdn                       0.141         8        50
cli.azure.cli.core: cloud                     0.002         1         7
cli.azure.cli.core: cognitiveservices         0.003        10        33
cli.azure.cli.core: compute_recommender       0.005         1         1
cli.azure.cli.core: config                    0.001         2         7
cli.azure.cli.core: configure                 0.001         2         5
cli.azure.cli.core: consumption               0.018         8         9
cli.azure.cli.core: container                 0.008         1        11
cli.azure.cli.core: containerapp              0.107        37       123
cli.azure.cli.core: cosmosdb                  0.017        58       199
cli.azure.cli.core: databoxedge               0.007         5        28
cli.azure.cli.core: dla                       0.004        23        62
cli.azure.cli.core: dls                       0.003         7        41
cli.azure.cli.core: dms                       0.002         3        22
cli.azure.cli.core: eventgrid                 0.006        25        96
cli.azure.cli.core: eventhubs                 0.008        12        18
cli.azure.cli.core: extension                 0.001         1         7
cli.azure.cli.core: feedback                  0.001         1         2
cli.azure.cli.core: find                      0.001         1         1
cli.azure.cli.core: hdinsight                 0.006         9        42
cli.azure.cli.core: identity                  0.002         2        11
cli.azure.cli.core: interactive               0.000         1         1
cli.azure.cli.core: iot                       0.095        19        82
cli.azure.cli.core: keyvault                  0.072        20       113
cli.azure.cli.core: kusto                     0.002         3        14
cli.azure.cli.core: lab                       0.027         9        29
cli.azure.cli.core: managedservices           0.011         3         8
cli.azure.cli.core: maps                      0.002         5        13
cli.azure.cli.core: marketplaceordering       0.002         1         2
cli.azure.cli.core: monitor                   0.499        18        60
cli.azure.cli.core: mysql                     0.114        16        56
cli.azure.cli.core: netappfiles               0.037         8        17
cli.azure.cli.core: network                   0.129       103       338
cli.azure.cli.core: policyinsights            0.011         9        17
cli.azure.cli.core: privatedns                0.018        14        60
cli.azure.cli.core: profile                   0.002         2         8
cli.azure.cli.core: rdbms                     0.129        49       202
cli.azure.cli.core: redis                     0.003         7        38
cli.azure.cli.core: relay                     0.022         7         8
cli.azure.cli.core: resource                  0.015        51       231
cli.azure.cli.core: role                      0.003        17        61
cli.azure.cli.core: search                    0.006         7        19
cli.azure.cli.core: security                  0.009        47        98
cli.azure.cli.core: servicebus                0.008        13        15
cli.azure.cli.core: serviceconnector          0.059        20       309
cli.azure.cli.core: servicefabric             0.012        27        80
cli.azure.cli.core: signalr                   0.002         9        34
cli.azure.cli.core: sql                       0.020        56       215
cli.azure.cli.core: sqlvm                     0.023         4        20
cli.azure.cli.core: storage                   0.055        59       273
cli.azure.cli.core: synapse                   0.013        54       246
cli.azure.cli.core: util                      0.001         3         7
cli.azure.cli.core: vm                        0.060        58       233
cli.azure.cli.core: Total (66)                2.127      1206      4697
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-devops              0.088        60       192  /opt/az/azcliextensions/azure-devops
cli.azure.cli.core: azure-iot                 0.020        97       325  /opt/az/azcliextensions/azure-iot
cli.azure.cli.core: Total (2)                 0.108       157       517  
cli.azure.cli.core: Loaded 1344 groups, 5214 commands.
cli.azure.cli.core: Updated command index in 0.005 seconds.
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f17a56bdee0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2024-10-28.16-12-08.iot_du_update_stage.5453.log'.
az_command_data_logger: command args: iot du update stage --debug --account {} --instance {} --storage-account {} --storage-container {} --manifest-path {} --overwrite --then-import
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f17a56f4680>]
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f17a57125c0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f17a5712700>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x7f17a57127a0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f17a3ae2020>]
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f17a6261c60>, <function CLIQuery.handle_query_parameter at 0x7f17a629b740>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f17a5712660>, <function DevCommandsLoader.post_parse_args at 0x7f179f8787c0>]
az_command_data_logger: extension name: azure-iot
az_command_data_logger: extension version: 0.25.0
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 432, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/commands_update.py", line 482, in stage_update
    from azext_iot.deviceupdate.providers.storage import StorageAccountManager
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/providers/storage.py", line 7, in <module>
    from azure.identity import AzureCliCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/__init__.py", line 10, in <module>
    from ._credentials import (
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/authorization_code.py", line 7, in <module>
    from azure.core.credentials import AccessToken, AccessTokenInfo, TokenRequestOptions
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 432, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/commands_update.py", line 482, in stage_update
    from azext_iot.deviceupdate.providers.storage import StorageAccountManager
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/providers/storage.py", line 7, in <module>
    from azure.identity import AzureCliCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/__init__.py", line 10, in <module>
    from ._credentials import (
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/authorization_code.py", line 7, in <module>
    from azure.core.credentials import AccessToken, AccessTokenInfo, TokenRequestOptions
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
az_command_data_logger: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 363, in handler
    show_exception_handler(ex)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 432, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 361, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/commands_update.py", line 482, in stage_update
    from azext_iot.deviceupdate.providers.storage import StorageAccountManager
  File "/opt/az/azcliextensions/azure-iot/azext_iot/deviceupdate/providers/storage.py", line 7, in <module>
    from azure.identity import AzureCliCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/__init__.py", line 10, in <module>
    from ._credentials import (
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "/opt/az/azcliextensions/azure-iot/azure/identity/_credentials/authorization_code.py", line 7, in <module>
    from azure.core.credentials import AccessToken, AccessTokenInfo, TokenRequestOptions
ImportError: cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f17a56be160>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.530 seconds (init: 0.161, invoke: 2.369)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 8181 in cache file under /*****/.azure/telemetry/20241028161208876
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /root/.azure /root/.azure/telemetry/20241028161208876"
telemetry.process: Return from creating process 5458
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The Update manifest is pushed without errors.

### Environment Summary

```
az --version
azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1
azure-iot                         0.25.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.11.8 (main, Sep 25 2024, 11:34:06) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by emibcn** [comment]
Hi @yonzhan and thanks for your response.
Is there a workaround in the meanwhile, until it's resolved? Like `az rest` command(s), for example?

Thanks in advance.

**Comment by emibcn** [comment]
Hi again @yonzhan ,
I have just tested using resource names instead of IDs, with the same error thrown:
```
az iot du update stage \
    --subscription ***** \
    --resource-group ***** \
    --account ***** \
    --instance ***** \
    --manifest-path manifest.json \
    --storage-account ***** \
    --storage-container ***** \
    --overwrite \
    --then-import
```

I have also tested both executions (with IDs or with names) on an Ubuntu 22.04.5 LTS, with same results.

**Comment by bebound** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/29940

**Comment by emibcn** [comment]
Hi @bebound ,
I was able to run the command by manually upgrading the core and identity packages (ugly as hell), as explained in https://github.com/Azure/azure-cli/issues/29940#issuecomment-2367218626 :

```shell
sudo /opt/az/bin/python3 -m pip install azure-core==1.31.0 azure-identity==1.18.0
```

I guess  the APT packages would need to be fixed?

**Comment by bebound** [comment]
Yes, in 2.66.0, we'll bump azure-core to 1.31.0: https://github.com/Azure/azure-cli/pull/29944

**Comment by emibcn** [comment]
And when is #29944 going to be available in APT repositories (just curious)?

**Comment by bebound** [comment]
Nov 11
