### ISSUE TITLE
az login - No module named 'ctypes'

### ISSUE THREAD

**Issue by shahzaibtx** [Azure/azure-cli#30280]
### Describe the bug

Not able to use AZ CLI on SAW

### Related command

az login

### Errors

The command failed with an unexpected error. Here is the traceback:
The command failed with an unexpected error. Here is the traceback:
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 212, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/_win_vt.py", line 11, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 212, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/_win_vt.py", line 11, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

The command failed with an unexpected error. Here is the traceback:
The command failed with an unexpected error. Here is the traceback:
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 212, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/_win_vt.py", line 11, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 212, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/_win_vt.py", line 11, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Expected behavior

az login should allow me to login

### Environment Summary

az --version gives me the same error as above. I installed AzureCLI v2.55.0 from Software Center

**Comment by bebound** [comment]
Please see known issue 2 in https://ppe.eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/azure_cli_on_saw

**Comment by bebound** [comment]
Run az command in Terminal App using PowerShell. That the only valid method.
