### ISSUE TITLE
Managed HSM SKU defaults to B family

### ISSUE THREAD

**Issue by Cherrett** [Azure/azure-cli#30292]
### Describe the bug

I am a part of the Azure Managed HSM team. When creating a new Managed HSM resource using az keyvault create, the SKU defaults to the B family, irrespective of the SKU name specified. This is not correct since we have certain SKUs in the C family. 

[Source Code](https://github.com/Azure/azure-cli/blob/6a1c3ca773310263a8a1bf48a370e84e6127b471/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L572C29-L572C69)

### Related command

az keyvault create --hsm-name "test" --resource-group "test" --sku Custom_C42

### Errors

(BadRequest) The Managed HSM SKU is invalid.
Code: BadRequest
Message: The Managed HSM SKU is invalid.

### Issue script & Debug output

cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"BadRequest","message":"The Managed HSM SKU is invalid."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 509, in create_vault_or_hsm
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/custom.py", line 584, in create_hsm
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 710, in sdk_no_wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/keyvault/v2023_07_01/operations/_managed_hsms_operations.py", line 537, in begin_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/keyvault/v2023_07_01/operations/_managed_hsms_operations.py", line 408, in _create_or_update_initial
azure.core.exceptions.HttpResponseError: (BadRequest) The Managed HSM SKU is invalid.
Code: BadRequest
Message: The Managed HSM SKU is invalid.

cli.azure.cli.core.azclierror: (BadRequest) The Managed HSM SKU is invalid.
Code: BadRequest
Message: The Managed HSM SKU is invalid.
az_command_data_logger: (BadRequest) The Managed HSM SKU is invalid.
Code: BadRequest
Message: The Managed HSM SKU is invalid.

### Expected behavior

These are all of the valid Managed HSM SKUs:

B SKU family: Standard_B1, Custom_B32, Custom_B6
C SKU family: Custom_C42, Custom_C10

For Custom_C42 and Custom_C10, the SKU family passed to ARM should be C instead of B.

This can be determined by checking the letter following the underscore in the SKU name.

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dcherrett\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Azure CLI is using 2023-07-01 API version for MHSM operations and from [the swagger](https://github.com/Azure/azure-rest-api-specs/blob/766fbdcae199a5b2a3b7d2910f32b37cac7947de/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2023-07-01/managedHsm.json#L912-L916) there're only skus for B family: `Standard_B1`,`Custom_B32`,`Custom_B6`. We are not aware of any C family. If there's feature added, can you pls update swagger to generate SDK new version and then file a feature request for CLI team?

**Comment by Cherrett** [comment]
Will re-open once new API version is released
