### ISSUE TITLE
az iot ops check - the command failed with an unexpected error.

### ISSUE THREAD

**Issue by nassiharel** [Azure/azure-cli#30324]
### Describe the bug

I get an error when running
```
az iot ops check
```

### Related command

az iot ops check

### Errors

```
Command group 'iot ops' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'serviceName'
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/commands_edge.py", line 87, in check
    return run_checks(
           ^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/providers/checks.py", line 69, in run_checks
    service_result = service_check_dict[ops_service](
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/providers/check/summary.py", line 76, in check_summary
    result = check.check_func(
             ^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/providers/check/mq.py", line 61, in check_mq_deployment
    return check_post_deployment(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/providers/check/base/deployment.py", line 80, in check_post_deployment
    results.append(evaluate_func(detail_level=detail_level, as_list=as_list, resource_name=resource_name))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.azure/cliextensions/azure-iot-ops/azext_edge/edge/providers/check/mq.py", line 146, in evaluate_broker_listeners
    listener_spec_service_name: str = listener_spec["serviceName"]
                                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'serviceName'
```

### Issue script & Debug output

sensitive data

### Expected behavior

should run iot checks

### Environment Summary

azure-cli                         2.66.0

core                              2.66.0
telemetry                          1.1.0

Extensions:
azure-iot-ops                    0.8.0b1
connectedk8s                      1.10.1
customlocation                     0.1.3
k8s-extension                      1.6.2

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/azureuser/.azure/cliextensions'
Python (Linux) 3.12.7 (main, Oct 30 2024, 03:56:40) [GCC 11.4.0]
Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vilit1** [comment]
This should have been fixed a couple of versions ago - please try running the latest version and if you still have the error, reopen the issue.
