### ISSUE TITLE
az ssh config - windows - missing rpds python module

### ISSUE THREAD

**Issue by mbehnke** [Azure/azure-cli#30320]
## Describe the bug
 
**Command Name**
`az ssh config`
 
**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```
 
## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
 
- _Put any pre-requisite steps here..._
- `az ssh config --ip {} --file {} --keys-dest-folder {}`
 
## Environment Summary
```
Windows-11-10.0.22631-SP0
Python 3.12.7
Installer: MSI
 
azure-cli 2.66.0
 
Extensions:
aks-preview 9.0.0b7
azure-iot 0.25.0
interactive 1.0.0b1
 
Dependencies:
msal 1.31.0
azure-mgmt-resource 23.1.1
```
## Additional Context
 

 

INTERNAL

### Related command

az ssh config --ip {} --file {} --keys-dest-folder {}

### Errors

No module named "rpds.rpds"

### Issue script & Debug output

No module named "rpds.rpds"

### Expected behavior

creating keys

### Environment Summary

azure-cli                         2.66.0
 
core                              2.66.0
telemetry                          1.1.0
 
Extensions:
aks-preview                      9.0.0b7
azure-iot                         0.25.0
interactive                      1.0.0b1
 
Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by isamsaroia** [comment]
> Thank you for opening this issue, we will look into it.

Thank you so much!
Strangely, 32 bit version of azure-cli (2.66.0) does not seem to have this problem on windows platform.

**Comment by elestedt** [comment]
I have the same issue on Linux (Ubuntu 22.04) after upgrading the azure-cli package yesterday

```
❯ az --version
azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
ssh                                2.0.6

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/felested/.azure/cliextensions'

Python (Linux) 3.12.7 (main, Nov 13 2024, 04:02:11) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by Laffs2k5** [comment]
Experiencing this on 2 different arm platforms;

From where I'm sitting it looks like there are missing dependencies in some of the Az CLI distributions.

Failing configuration: ubuntu 24.04 on arm with az cli `2.67.0`:

```shell
$ az version
{
  "azure-cli": "2.67.0",
  "azure-cli-core": "2.67.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "bastion": "1.3.1",
    "ssh": "2.0.5"
  }
}

$ uname --operating-system 
GNU/Linux

$ uname --hardware-platform 
aarch64
```

Failing configuration: windows 11 on arm with az cli `2.66.0`:

```powershell
> az version
{
  "azure-cli": "2.66.0",
  "azure-cli-core": "2.66.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "bastion": "1.3.1",
    "ssh": "2.0.6"
  }
}

> Get-ComputerInfo | Select-Object OsName, OsArchitecture, OsHardwareAbstractionLayer, WindowsUBR, WindowsBuildLabEx
OsName                     : Microsoft Windows 11 Pro
OsArchitecture             : ARM 64-bit Processor
OsHardwareAbstractionLayer : 10.0.26100.1
WindowsUBR                 : 2314
WindowsBuildLabEx          : 26100.1.arm64fre.ge_release.240331-1435
```

Failing configuration: just updated the cli on the windows 11 on arm system, also did `az upgrade` after, but the error is still there with az cli `2.67.0`:

```powershell
> az version
{
  "azure-cli": "2.67.0",
  "azure-cli-core": "2.67.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "bastion": "1.3.1",
    "ssh": "2.0.6"
  }
}
```

Working configuration: windows 10 on x64 with az cli `2.65.0`:

```powershell
> az version
{
  "azure-cli": "2.65.0",
  "azure-cli-core": "2.65.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "4.0.0b2",
    "bastion": "0.3.0",
    "devcenter": "4.0.1",
    "ssh": "2.0.2"
  }
}

> Get-ComputerInfo | Select-Object OsName, OsArchitecture, OsHardwareAbstractionLayer, WindowsUBR, WindowsBuildLabEx

OsName                     : Microsoft Windows 10 Pro
OsArchitecture             : 64-bit
OsHardwareAbstractionLayer : 10.0.19041.5072
WindowsUBR                 : 5131
WindowsBuildLabEx          : 19041.1.amd64fre.vb_release.191206-1406
```

Working configuration: just upgraded to az cl i `2.67.0` on the windows 10 system and it still works:

```powershell
> az version
{
  "azure-cli": "2.67.0",
  "azure-cli-core": "2.67.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "13.0.0b2",
    "bastion": "1.3.1",
    "devcenter": "6.1.0",
    "ssh": "2.0.6"
  }
}
```

**Comment by vthiebaut10** [comment]
Thank you for raising this issue. We are able to repro this behavior and are currently investigating how to best fix. Will update this issue once I have an estimate for a fix.

**Comment by bebound** [comment]
Python version bumped to 3.12 in 2.66.0.
`ssh` extension's dependency `rpds-py` does not have a cross-platform wheel, which means Python 3.11 package isn't compatible with Python 3.12.

Reinstalling the `ssh` extension should fix the issue: `az extension remove -n ssh && az extension add -n ssh`

**Comment by marcoaversanoigt** [comment]
> > Python version bumped to 3.12 in 2.66.0. `ssh` extension's dependency `rpds-py` does not have a cross-platform wheel, which means Python 3.11 package isn't compatible with Python 3.12.
> > Reinstalling the `ssh` extension should fix the issue: `az extension remove -n ssh && az extension add -n ssh`
> 
> Reinstalling ssh extension fix it in az cli 2.67.0 on WSL Ubuntu. Thank you very much indeed [@bebound](https://github.com/bebound)!

Found that it solves the WSL Ubuntu AZ CLI but breaks Windows AZ CLI.
Reinstalling ssh extension into Windows fix AZ CLI Windows BUT breaks WSL Ubuntu AZ CLI (-__-)

**Comment by bebound** [comment]
@marcoaversanoigt This should not happen.
Are you using az.exe in WSL, what's the output of `az -v` in WSL?

**Comment by marcoaversanoigt** [comment]
But it happens. I was forced to uninstall it from Windows, in linux is where I need it most, but it is a real issue to not have it in Windows..

```
~$ az -v

azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
ssh                                2.0.6

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/marcox/.azure/cliextensions'

Python (Linux) 3.12.7 (main, Nov 13 2024, 04:02:11) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.```

**Comment by bebound** [comment]
The last log indicates that you're using Windows' `az` on Linux.

Please see https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313 and https://github.com/Azure/azure-cli/issues/13573#issuecomment-1547125916. This is an issue caused by the `C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az`.

Workaround: change the `PATH` to ensure `/usr/bin/` precedes `/mnt/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin`.

**Comment by marcoaversanoigt** [comment]
> The last log indicates that you're using Windows' `az` on Linux.
> 
> Please see [#13573 (comment)](https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313) and [#13573 (comment)](https://github.com/Azure/azure-cli/issues/13573#issuecomment-1547125916). This is an issue caused by the `C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az`.
> 
> Workaround: change the `PATH` to ensure `/usr/bin/` precedes `/mnt/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin`.

I apologize, let me clear it: 
I installed az cli in Windows (again) and ran the az.exe from there, so the log you see is from Windows' az, does it makes sense now?

**Comment by bebound** [comment]
Weird, I can't repro.

What's the output of thess on Windows?
```
cd "C:\Program Files\Microsoft SDKs\Azure\CLI2"
./python.exe -m site
```

```
cd "C:\Program Files\Microsoft SDKs\Azure\CLI2"
$env:PYTHONPATH=''C:\Users\ryl34905\.azure\cliextensions\ssh'
./python.exe -c "from rpds import HashTrieMap, HashTrieSet, List"
```

**Comment by marcoaversanoigt** [comment]
> Weird, I can't repro.
> 
> What's the output of thess on Windows?
> 
> ```
> cd "C:\Program Files\Microsoft SDKs\Azure\CLI2"
> ./python.exe -m site
> ```
> 
> ```
> cd "C:\Program Files\Microsoft SDKs\Azure\CLI2"
> $env:PYTHONPATH=''C:\Users\ryl34905\.azure\cliextensions\ssh'
> ./python.exe -c "from rpds import HashTrieMap, HashTrieSet, List"
> ```

I had to correct it cause you wrote in linux syntax, so:

```
Microsoft SDKs\Azure\CLI2
❯ python.exe -m site
sys.path = [
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\python312.zip',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\Lib',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\win32',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\win32\\lib',
    'C:\\Program Files\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\Pythonwin',
]
USER_BASE: 'C:\\Users\\ryl34905\\AppData\\Roaming\\Python' (doesn't exist)
USER_SITE: 'C:\\Users\\ryl34905\\AppData\\Roaming\\Python\\Python312\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```
```
Microsoft SDKs\Azure\CLI2
❯ set PYTHONPATH=C:\Users\ryl34905\.azure\cliextensions\ssh


Microsoft SDKs\Azure\CLI2 󰌾
❯ python.exe -c "from rpds import HashTrieMap, HashTrieSet, List"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ryl34905\.azure\cliextensions\ssh\rpds\__init__.py", line 1, in <module>
    from .rpds import *
ModuleNotFoundError: No module named 'rpds.rpds'
```
