### ISSUE TITLE
az ml workspace list fails on v2.32.0

### ISSUE THREAD

**Issue by PranshuBansalDev** [Azure/azure-cli#30327]
### Describe the bug

With version 2.31.1 this is fine

$ az extension remove -n ml
$ az extension add -n ml --version 2.31.1
The default value of '--allow-preview' will be changed to 'false' from 'true' in next breaking change release(2.67.0).
Default enabled including preview versions for extension installation now. Disabled in future release. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
$ az ml workspace list --subscription $SUB_ID
[
  {
    "allow_roleassignment_on_rg": true,
    "application_insights": "/subscriptions/b72743ec-8bb3-453f-83ad-a53e8a50712e/resourceGroups/summarization-test/providers/Microsoft.insights/components/dahungtest7112216684",
    "description": "",
... OUTPUT_TRUNCATED

With version 2.32.0 this is broken

$ az extension remove -n ml
$ az extension add -n ml --version 2.32.0
The default value of '--allow-preview' will be changed to 'false' from 'true' in next breaking change release(2.67.0).
Default enabled including preview versions for extension installation now. Disabled in future release. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
$ az ml workspace list --subscription $SUB_ID
Met error <class 'TypeError'>:'NoneType' object is not subscriptable
Please check log by running the command with '--debug' for more details.

### Related command

`az ml workspace list --subscription $SUB_ID`

### Errors

```
Met error <class 'TypeError'>:'NoneType' object is not subscriptable
Please check log by running the command with '--debug' for more details.
```

### Issue script & Debug output

```
Traceback (most recent call last):
  File "/home/MY_USERNAME/.azure/cliextensions/ml/azext_mlv2/manual/custom/workspace.py", line 29, in ml_workspace_list
    return list(map(lambda x: _dump_entity_with_warnings(x), results))  # pylint: disable=unnecessary-lambda
  File "/home/MY_USERNAME/MY_DIR/.setup_venv/lib/python3.10/site-packages/azure/core/paging.py", line 123, in __next__
    return next(self._page_iterator)
  File "/home/MY_USERNAME/MY_DIR/.setup_venv/lib/python3.10/site-packages/azure/core/paging.py", line 83, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/home/MY_USERNAME/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_restclient/v2024_07_01_preview/operations/_workspaces_operations.py", line 761, in extract_data
    list_of_elem = cls(list_of_elem)
  File "/home/MY_USERNAME/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_workspace_operations.py", line 115, in <lambda>
    cls=lambda objs: [Workspace._from_rest_object(obj) for obj in objs],
  File "/home/MY_USERNAME/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_workspace_operations.py", line 115, in <listcomp>
    cls=lambda objs: [Workspace._from_rest_object(obj) for obj in objs],
  File "/home/MY_USERNAME/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/entities/_workspace/workspace.py", line 340, in _from_rest_object
    mlflow_tracking_uri = get_mlflow_tracking_uri_v2(rest_obj, v2_service_context)
  File "/home/MY_USERNAME/MY_DIR/.setup_venv/lib/python3.10/site-packages/azureml/mlflow/__init__.py", line 96, in get_mlflow_tracking_uri_v2
    subscription_id=v2_service_context_arg['subscription_id'],
TypeError: 'NoneType' object is not subscriptable
```

### Expected behavior

The details here - With version 2.31.1 this is fine

### Environment Summary

```
azure-cli                         2.66.0

core                              2.66.0
telemetry                          1.1.0

Extensions:
ml                                2.32.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/home/pranbansal/git/Language-ZCode/projects/Prompt2Model/.setup_venv/bin/python'
Extensions directory '/home/pranbansal/.azure/cliextensions'

Python (Linux) 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
We are routing this to the appropriate team for follow-up. cc @azureml-github.
