### ISSUE TITLE
`--boot-diagnostics-storage` does not support managed boot diagnostics for `az vm create`

### ISSUE THREAD

**Issue by vmarcella** [Azure/azure-cli#30340]
### Describe the bug

In order to provision a virtual machine with managed boot diagnostics enabled, [our documentation](https://learn.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#enable-managed-boot-diagnostics-using-cli) states that we must use the flag `--boot-diagnostics-storage` without any parameters passed to it. However, using `--boot-diagnostics-storage` without passing anything into it isn't allowed.

### Related command

`az vm create`

### Errors

argument --boot-diagnostics-storage: expected one argument

### Issue script & Debug output

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.12/argparse.py", line 1931, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/argparse.py", line 2168, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/argparse.py", line 2089, in consume_optional
    arg_count = match_argument(action, selected_patterns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/argparse.py", line 2264, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument --boot-diagnostics-storage: expected one argument

cli.azure.cli.core.azclierror: argument --boot-diagnostics-storage: expected one argument

### Expected behavior

`az vm create ... --boot-diagnostics-storage` should create a virtual machine with managed boot diagnostics enabled

### Environment Summary

{
  "azure-cli": "2.66.0",
  "azure-cli-core": "2.66.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "7.0.0b3",
    "amg": "1.3.6",
    "azure-devops": "1.0.1",
    "k8s-extension": "1.6.1"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vmarcella** [comment]
@yonzhan why was the bug tag from this issue removed? This isn't just a question for the azure-cli team, our customer facing documentation states that you should be able to create a VM with managed boot diagnostics using azure-cli >= 2.11.0, but it is physically impossible to do so because `--boot-diagnostics-storage` requires a parameter in order for the vm create to execute.
