### ISSUE TITLE
az functionapp - fails with ModuleNotFoundError: No module named 'ctypes' in SAW

### ISSUE THREAD

**Issue by JuanP-EscobarZ** [Azure/azure-cli#30379]
### Describe the bug

Not able to use any `az functionapp` command in my saw, always gets the `ModuleNotFoundError: No module named 'ctypes'` even after running the `az` alone in the terminal as the [wiki](https://ppe.eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/azure_cli_on_saw) says in the point 2 of the _Known Issues_ section

### Related command

az functionapp

### Errors

The command failed with an unexpected error. Here is the traceback:
No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 588, in execute
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/parser.py", line 261, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 1870, in parse_args
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 1903, in parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 2118, in _parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 2074, in consume_positionals
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 1979, in take_action
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 1242, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/parser.py", line 281, in parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 1903, in parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\argparse.py", line 2143, in _parse_known_args
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/parser.py", line 157, in error
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/parser.py", line 198, in get_examples
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/_help.py", line 185, in get_examples
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/help.py", line 253, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/_help.py", line 296, in load
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/_help_loaders.py", line 154, in versioned_load
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/help.py", line 198, in load
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/parser.py", line 241, in __getattribute__
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 133, in description_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 23, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/__init__.py", line 2, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/collection.py", line 6, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/config.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/runners.py", line 29, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/terminals.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['functionapp', 'deployment', 'source', 'config-zip', '-g', 'metrics', '-n', 'msbmetricsfunctionscp-wu2', '--src', 'C:\\Users\\juane\\Work Folders\\Documents\\msbmetricsfunctionscp-wu2\\function_app.zip', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000015258F5F560>, <function OutputProducer.on_global_arguments at 0x00000152590E22A0>, <function CLIQuery.on_global_arguments at 0x0000015259117D80>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'functionapp': ['azure.cli.command_modules.appservice', 'azure.cli.command_modules.serviceconnector']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: appservice                0.135        73       260
cli.azure.cli.core: serviceconnector          0.021        16       235
cli.azure.cli.core: Total (2)                 0.156        89       495
cli.azure.cli.core: Loaded 87 groups, 495 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : functionapp deployment source config-zip
cli.azure.cli.core: Command table: functionapp deploy
cli.azure.cli.core: remaining    :                    ent source config-zip
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001525A8E9EE0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\juane\.azure\commands\2024-11-18.12-37-37.functionapp_deployment_source_config-zip.20968.log'.
az_command_data_logger: command args: functionapp deployment source config-zip -g {} -n {} --src {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001525A91A200>]
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/__init__.py", line 523, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 23, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/__init__.py", line 2, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/collection.py", line 6, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/config.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/runners.py", line 29, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/terminals.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/__init__.py", line 523, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 23, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/__init__.py", line 2, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/collection.py", line 6, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/config.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/runners.py", line 29, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/terminals.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
az_command_data_logger: No module named 'ctypes'
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 561, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/__init__.py", line 523, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/__init__.py", line 318, in load_arguments
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\knack/commands.py", line 104, in load_arguments
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 23, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/__init__.py", line 2, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/collection.py", line 6, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/config.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/runners.py", line 29, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-target-6cbhvr91\lib\python\invoke/terminals.py", line 32, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\Python\Lib\site-packages\azure/cli/__main__.py", line 28, in skip_imports
ModuleNotFoundError: No module named 'ctypes'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001525A8EA160>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.503 seconds (init: 0.215, invoke: 0.288)

### Expected behavior

az functionapp should allow to manage azure function apps

### Environment Summary

azure-cli  v2.55.0

**Comment by yonzhan** [comment]
route to service team

**Comment by ElizabethPhippen** [comment]
Hi, has there been any update on this? I'm experiencing the same issue.

**Comment by qiqimico** [comment]
I'm also having the same issue, is there any update? @yonzhan

**Comment by kamperiadis** [comment]
This is not a Functions specific issue, but rather an Az CLI @yonzhan

**Comment by xlrshubham** [comment]
Run az command in Terminal App using PowerShell. That the only valid method.
Solution provided here: https://github.com/Azure/azure-cli/issues/30280

**Comment by AnotherJob** [comment]
I am having the same problem and I am using Terminal App and PowerShell.

I am using the latest version of AzureCLI published for SAW (v 2.55.0). I see the same error even if I do "az help".
Unlike in https://github.com/Azure/azure-cli/issues/30280, I do not get this with "az login". But "az functionapp" fails with this error.

**Comment by AnotherJob** [comment]
@xlrshubham , note I am doing what you said is "the only valid method", and I still have this error.

**Comment by AnotherJob** [comment]
@yonzhan I see the same error with "az help", this is not specific to "az functionapp". But for me it doesn't happen with "az login", so it seems different from https://github.com/Azure/azure-cli/issues/30280.

**Comment by agrawalamit31** [comment]
I am also facing this issue running az cli command on terminal. Please provide solution.

**Comment by PTaladay** [comment]
This is still an issue for me as well. I can use az login, but the az aks get-credentials gives me the ctypes missing module error.

**Comment by adrian05-ms** [comment]
If anyone else is still experiencing this issue, on the start menu type "Terminal" and the app that has that exact name and has a logo similar to a console is the one that lets you run the CLI commands without issue. It will prompt a powershell console, the az commands should run smoothly here even if you get the ctypes module error.

I tested this on Win 11 and with version 2.70.0

**Comment by clarkbreyman-yammer** [comment]
Restricting `az` to only run in terminal is very limiting for SAW and other workflows. Specifically, I can not use az inside the git-bash shell to run bash scripts.

**Comment by yingfangdu** [comment]
I still see this issue today, but I use https://portal.azure.com/#cloudshell/ to solve my problem.

**Comment by smfpride** [comment]
I'm still seeing the issue today as well, even when using terminal or powershell 7 on a SAW.
