### ISSUE TITLE
az containerapp update - cannot take environment variables with values containing spaces

### ISSUE THREAD

**Issue by Mek7** [Azure/azure-cli#30396]
### Describe the bug

It's not possible to pass environment variables with values that contain spaces to az containerapp update command with --replace-env-vars parameter.

### Related command

az containerapp update

### Errors

ERROR: Environment variables must be in the format "<key>=<value> <key>=secretref:<value> ...".

### Issue script & Debug output

```
        RESOURCE_GROUP='some-rg'
        CONTAINER_APP_NAME='some-container-app'
        LOCATION='West Europe'
        ACR_NAME='some-acr'
        IMAGE_TAG='$(transformedDockerTag)'
        ENV_FILE_PATH='$(Pipeline.Workspace)/BuildArtifact/Configuration/environment-variables.acc.env'

        # az containerapp command cannot take environment variables from file directly, only via command line, such as:
        # key1="value1" key2="value2" key3="value3"
        # convert .env file to Azure CLI-compatible environment variables format
        # remove \r from .env file because these Linux commands expect \n only as newline character
        # trim trailing spaces
        REPLACE_ENV_VARS=$(awk -F= 'NF==2 {
          gsub(/\r/, "");
          printf "%s=%s ", $1, $2
        }' $ENV_FILE_PATH | tr -d '\r' | tr '\n' ' ')
        REPLACE_ENV_VARS=$(echo $REPLACE_ENV_VARS | sed 's/[[:space:]]*$//')
        
        echo The environment variables were successfully read from .env file and will be passed as --replace-env-vars argument of az command as follows:
        echo $REPLACE_ENV_VARS

        # deploy a new revision of the container app
        az containerapp update \
          --name $CONTAINER_APP_NAME \
          --resource-group $RESOURCE_GROUP \
          --image $ACR_NAME/censored:$IMAGE_TAG \
          --debug \
          --replace-env-vars $REPLACE_ENV_VARS
```
Environment variables are read from an .env file in my solution where one line is one variable in key="value" format (quotes included)
The `echo $REPLACE_ENV_VARS` echoes the variables correctly, such as:
`ActiveDirectoryClientId="someguid" ActiveDirectoryClientSecret="something" OAuthUserExpirationFrom="Test User 07"`
but the az containerapp update command fails when there are spaces in the value of an environment variable. I have confirmed that removing spaces fixes the problem but I need the spaces there.
Also I need double quotes in the value, such as `"Test User 07" <testuser07@something.com>` (this should be the environment variable value) and at first I thought that the double quotes are the culprit, but no, it's the spaces. I hope passing double quotes in variable value is also possible...

### Expected behavior

No error, just environment value being passed as is, along with spaces and other characters between double quotes.
Also it would be best to have support for reading environment variables from a file, avoiding this CLI hassle.

### Environment Summary

==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.248.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
WARNING: You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.66.0 *

core                              2.66.0 *
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.12.7 (main, Oct 30 2024, 03:56:40) [GCC 11.4.0]

### Additional context

az is run inside a linux build agent on devops (ubuntu-latest) in an Azure CLI build task.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Mek7** [comment]
I inserted the `az upgrade --yes` command before my `az containerapp update` command. It didn't help. Besides, az version is outside my control, as this is a devops hosted build agent by Microsoft. MS should take care to update its own tooling.
Passing --debug to az containerapp update provided more information - that the value is split on spaces like this:
`<snip>, 'OAuthUserExpirationFrom="Test', 'User', '07"',<snip>`
by some cli.knack.cli
Debug info contains A LOT of text that I should censor before posting... at the end there is this:
```
2024-11-21T11:07:15.9812727Z DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
2024-11-21T11:07:15.9814568Z   File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
2024-11-21T11:07:15.9814854Z     cmd_result = self.invocation.execute(args)
2024-11-21T11:07:15.9815096Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9815360Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
2024-11-21T11:07:15.9815644Z     raise ex
2024-11-21T11:07:15.9815923Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
2024-11-21T11:07:15.9816233Z     results.append(self._run_job(expanded_arg, cmd_copy))
2024-11-21T11:07:15.9817873Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9818175Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 725, in _run_job
2024-11-21T11:07:15.9818482Z     return cmd_copy.exception_handler(ex)
2024-11-21T11:07:15.9818732Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9819024Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/containerapp/_client_factory.py", line 28, in _polish_bad_errors
2024-11-21T11:07:15.9819326Z     raise ex
2024-11-21T11:07:15.9819594Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
2024-11-21T11:07:15.9819863Z     result = cmd_copy(params)
2024-11-21T11:07:15.9820059Z              ^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9820319Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
2024-11-21T11:07:15.9820622Z     return self.handler(*args, **kwargs)
2024-11-21T11:07:15.9821243Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9821511Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2024-11-21T11:07:15.9821788Z     return op(**command_args)
2024-11-21T11:07:15.9822019Z            ^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9822301Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/containerapp/custom.py", line 748, in update_containerapp
2024-11-21T11:07:15.9822615Z     return update_containerapp_logic(cmd=cmd,
2024-11-21T11:07:15.9822838Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9823150Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/containerapp/custom.py", line 458, in update_containerapp_logic
2024-11-21T11:07:15.9823491Z     _add_or_update_env_vars(c["env"], parse_env_var_flags(replace_env_vars))
2024-11-21T11:07:15.9823735Z                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-21T11:07:15.9824024Z   File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/containerapp/_utils.py", line 350, in parse_env_var_flags
2024-11-21T11:07:15.9824416Z     raise ValidationError("Environment variables must be in the format \"<key>=<value> <key>=secretref:<value> ...\".")
2024-11-21T11:07:15.9824913Z azure.cli.core.azclierror.ValidationError: Environment variables must be in the format "<key>=<value> <key>=secretref:<value> ...".
2024-11-21T11:07:15.9825077Z 
2024-11-21T11:07:15.9909483Z ERROR: cli.azure.cli.core.azclierror: Environment variables must be in the format "<key>=<value> <key>=secretref:<value> ...".
2024-11-21T11:07:15.9909910Z ERROR: az_command_data_logger: Environment variables must be in the format "<key>=<value> <key>=secretref:<value> ...".
2024-11-21T11:07:15.9910235Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f1230556d40>]
2024-11-21T11:07:15.9910528Z INFO: az_command_data_logger: exit code: 1
2024-11-21T11:07:15.9910825Z INFO: cli.__main__: Command ran in 2.097 seconds (init: 0.162, invoke: 1.935)
2024-11-21T11:07:16.0798372Z INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
2024-11-21T11:07:16.0798958Z INFO: telemetry.client: Accumulated 0 events. Flush the clients.
2024-11-21T11:07:16.0799369Z INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
2024-11-21T11:07:16.0804197Z INFO: telemetry.save: Save telemetry record of length 3976 in cache file under /home/vsts/work/_temp/.azclitask/telemetry/20241121110716079
2024-11-21T11:07:16.0804685Z INFO: telemetry.main: Begin creating telemetry upload process.
2024-11-21T11:07:16.0808072Z INFO: telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.12/site-packages/azure/cli/telemetry/__init__.py /home/vsts/work/_temp/.azclitask /home/vsts/work/_temp/.azclitask/telemetry/20241121110716079"
2024-11-21T11:07:16.0817487Z INFO: telemetry.process: Return from creating process 2582
2024-11-21T11:07:16.0818180Z INFO: telemetry.main: Finish creating telemetry upload process.
2024-11-21T11:07:16.2419612Z 
2024-11-21T11:07:16.2423272Z ##[error]Script failed with exit code: 1
2024-11-21T11:07:16.2426939Z [command]/usr/bin/az account clear
```
Maybe this is related: https://github.com/Azure/azure-cli/issues/25327 and #4142 as suggested, is years old and closed.

**Comment by Greedygre** [comment]
Hi @Mek7 

I tested following command which works fine:
- About space , need to use `""` to wrap your value, for example: key="vaule     value"
- About quote, I tested and with `quote='\"Test User 07\" <testuser07@something.com>'` it looks fine.

```
az containerapp create -g {rg-name} -n {containerapp-name} --environment {env-id} --env-vars GREETING="Hello,    world" space="space include" quote='\"Test User 07\" <testuser07@something.com>' --debug 
```

You can use --debug to check if the input value as your expect:
```
cli.knack.cli: Command arguments: ['containerapp', 'create', '-g', '<rg-name>', '-n', '<ontainerapp-name>', '--environment', '<env>', '--env-vars', 'GREETING=Hello,    world', 'space=space include', 'quote="Test User 07" <testuser07@something.com>', '--debug']
```

**Comment by Mek7** [comment]
Hi @Greedygre can you please test with az containerapp update with `--replace-env-vars` argument?
And on a linux build agent in devops (image ubuntu-latest) from AzureCLI bash script as I did?
Also, thev documentation needs an update with these examples (spaces, quotes). I couldn't find any on the internet and spent a few days experimenting only to find out it is due to how the command line is parsed...

**Comment by Greedygre** [comment]
> Hi [@Greedygre](https://github.com/Greedygre) can you please test with az containerapp update with `--replace-env-vars` argument? And on a linux build agent in devops (image ubuntu-latest) from AzureCLI bash script as I did? Also, the documentation needs an update with these examples (spaces, quotes). I couldn't find any on the internet and spent a few days experimenting only to find out it is due to how the command line is parsed...

Sure, I tested, they works fine. 
- About space , need to use " or ' to wrap your value, for example: key="vaule value"
- About quote, I tested and with quote='\"Test User 07\" <testuser07@something.com>' it looks fine.
```
az containerapp update -g client.env_rg_eastus -n xinyutest --replace-env-vars GREETING='Hello,    world' space='This is a string with a single quote: '"'" quote='\"Test User 07\" <testuser07@something.com>' --debug
```

**Comment by Mek7** [comment]
I did as you suggested, and unfortunately, it didn't work.
I am loading environment variables from .env file, its content is:
```
ActiveDirectoryClientId="someguid"
ActiveDirectoryClientSecret="something"
... other variables...
OAuthUserExpirationFrom='\"Test User 08\" <testuser08@something.com>'
... other variables...
```
wrapped in single qoutes and escaped double quotes as you suggested.
Still the same error.
From debug output:
`DEBUG: cli.knack.cli: Command arguments: ['containerapp', 'update', '--name',...etc..., 'OAuthUserExpirationFrom=\'\\"Test', 'User', '08\\"', "<testuser08@something.com>'", ...etc...`
My Azure CLI task to read the file and then pass variables as command line arguments:
```
  - task: AzureCLI@2
    displayName: 'Deploy Docker Image to Azure Container App'
    inputs:
      azureSubscription: 'Azure service for pipeline (ACC)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        IMAGE_TAG='$(transformedDockerTag)'
        ENV_FILE_PATH='$(Pipeline.Workspace)/BuildArtifact/Configuration/environment-variables.acc.env'

        # az containerapp command cannot take environment variables from file directly, only via command line, such as:
        # key1="value1" key2="value2" key3="value3"
        # convert .env file to Azure CLI-compatible environment variables format
        # remove \r from .env file because these Linux commands expect \n only as newline character
        # trim trailing spaces
        REPLACE_ENV_VARS=$(awk -F= 'NF==2 {
          gsub(/\r/, "");
          printf "%s=%s ", $1, $2
        }' $ENV_FILE_PATH | tr -d '\r' | tr '\n' ' ')
        REPLACE_ENV_VARS=$(echo $REPLACE_ENV_VARS | sed 's/[[:space:]]*$//')
        
        echo The environment variables were successfully read from .env file and will be passed as --replace-env-vars argument of az command as follows:
        echo $REPLACE_ENV_VARS

        # deploy a new revision of the container app
        az containerapp update \
          --name <something> \
          --resource-group <something> \
          --image<something>.azurecr.io/<something>:$IMAGE_TAG \
          --debug \
          --replace-env-vars $REPLACE_ENV_VARS
```
The `echo $REPLACE_ENV_VARS` statement echoes all variables correctly.
Maybe there is some bash stuff mishandling quotes here?

**Comment by Greedygre** [comment]
@Mek7 

My suggestion is wrap the values for **az containerapp command** argument
- About space , need to use " or ' to wrap your value in , for example: key="vaule value"
- About quote, I tested and with quote='\"Test User 07\" <testuser07@something.com>' it looks fine. (need to escape double quotes and use '.)


> I am loading environment variables from .env file, its content is:
> 
> ActiveDirectoryClientId="someguid"
> ActiveDirectoryClientSecret="something"
> ... other variables...
> OAuthUserExpirationFrom='\"Test User 08\" <testuser08@something.com>'
> ... other variables...
> wrapped in single quotes and escaped double quotes as you suggested.


Base on the argument value in the debug log `, 'OAuthUserExpirationFrom=\'\\"Test', 'User', '08\\"', "<testuser08@something.com>'",`
It is not correct, in the debug log it should be `, 'OAuthUserExpirationFrom="Test User 08" <testuser08@something.com>',`

The original command should looks like following:

```
az containerapp update -g {rg-name} -n {containerapp-name}  --replace-env-vars GREETING='Hello,    world'  quote='\"Test User 08\" <testuser07@something.com>' --debug
```


No matter how you handle these env values, azure-cli has similar input requirements for spaces and single and double quotes as Linux. Please check the values ​​you enter to the command. 
You can test your commands with something like cloud shell. Thanks.

**Comment by Mek7** [comment]
Yes, I know all that...
As I wrote, my echo command echoes the correct string as read from env file:
```
2024-11-25T07:40:32.0007152Z The environment variables were successfully read from .env file and will be passed as --replace-env-vars
argument of az command as follows:
2024-11-25T07:40:32.0012220Z ActiveDirectoryClientId="someguid" ActiveDirectoryClientSecret="something" ...etc... OAuthUserExpirationFrom='\"Test User 08\" <testuser08@qics.nl>' ..etc...
```
But when passed to az command, it is misinterpreted.

**Comment by Greedygre** [comment]
> Yes, I know all that... As I wrote, my echo command echoes the correct string as read from env file:
> 
> ```
> 2024-11-25T07:40:32.0007152Z The environment variables were successfully read from .env file and will be passed as --replace-env-vars
> argument of az command as follows:
> 2024-11-25T07:40:32.0012220Z ActiveDirectoryClientId="someguid" ActiveDirectoryClientSecret="something" ...etc... OAuthUserExpirationFrom='\"Test User 08\" <testuser08@something.com>' ..etc...
> ```
> 
> But when passed to az command, it is misinterpreted.

Your env values pattern are the same as my suggestion. What pipeline environment you are using?

**Comment by Mek7** [comment]
I just tried passing the arguments as-is via the command line (just like you did), not reading from the env file.
The deployment was successful.
So, something is wrong when passed from a bash variable.

**Comment by Mek7** [comment]
OK, so this is clearly not a bug with AZ, but with bash misinterpreting the command line.
Please support reading environment values from a (preferably JSON) file to avoid this hassle! It has cost me a few days of fiddling to get this right!
In the meantime, for anyone having the same problem, I solved it like this.
My env file (excerpt):
```
# Environment variables are set here.
# Lines starting with # are ignored.
# Format is key="value", double quotes must be escaped with a backslash.
ActiveDirectoryClientId="someguid"
OAuthUserExpirationFrom="\"Test User 08\" <testuser08@something.com>"
```
And my Azure CLI build step (key point - use eval to pass your variable properly):
```
        ENV_FILE_PATH='$(Pipeline.Workspace)/BuildArtifact/Configuration/environment-variables.acc.env'

        # az containerapp command cannot take environment variables from file directly, only via command line, such as:
        # key1="value1" key2="value2" key3="value3"
        # convert .env file to Azure CLI-compatible environment variables format
        # remove \r from .env file because these Linux commands expect \n only as newline character
        # ignore lines starting with # and empty lines
        # trim trailing spaces
        REPLACE_ENV_VARS=$(awk -F= '!/^#/ && NF==2 {
            gsub(/\r/, "");
            printf "%s=%s ", $1, $2
        }' "$ENV_FILE_PATH" | tr -d '\r' | tr '\n' ' ')

        REPLACE_ENV_VARS=$(echo "$REPLACE_ENV_VARS" | sed 's/[[:space:]]*$//')
        
        echo The environment variables were successfully read from .env file and will be passed as --replace-env-vars argument of az command as follows: $REPLACE_ENV_VARS

        # deploy a new revision of the container app
        eval az containerapp update \
          --name <something> \
          --container-name <something> \
          --resource-group <something> \
          --image <something>.azurecr.io/<something>:$IMAGE_TAG \
          --debug \
          --replace-env-vars $REPLACE_ENV_VARS
```

**Comment by Greedygre** [comment]
> Please support reading environment values from a (preferably JSON) file to avoid this hassle! It has cost me a few days of fiddling to get this right!

Hi @Mek7 

Thanks for the suggestion, we will consider refine it for complex env vars support.

**Comment by Bodewes** [comment]
Thanks for the hints in this thread. But it still took a lot of trial and error. Even for my partner-in-crime (CoPilot). Please please please consider making documention more complete. Don't just post the trivial example! This took way too long.

I ended up with this in my Azure Pipeline. (posting here for visibility for others struggling with this).

``` YAML
  - task: AzureCLI@2
    displayName: 'Set Secrets'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        SECRETS_JSON='${{ convertToJson(parameters.secrets) }}'
        # echo "DEBUG - Secrets JSON: $SECRETS_JSON"
        SECRETS=$(echo "$SECRETS_JSON" | jq -r '[.[] | "\(.name)=\(.value)"] | join(" ")')
        # echo "DEBUG - Secrets string: $SECRETS"
        az containerapp secret set \
          --name ${{ parameters.containerAppName }} \
          --resource-group ${{ parameters.resourceGroup }} \
          --secrets $SECRETS

  - task: AzureCLI@2
    displayName: 'Replace Environment Variables'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Build regular environment variables
        ENV_VARS_JSON='${{ convertToJson(parameters.environmentVariables) }}'
        # echo "DEBUG - Env Vars JSON: $ENV_VARS_JSON"
        
        # Build secret references
        SECRETS_JSON='${{ convertToJson(parameters.secrets) }}'
        # echo "DEBUG - Secrets JSON for refs: $SECRETS_JSON"
        
        # Providing multi-env-vars with spaces is super annoying:
        # https://github.com/Azure/azure-cli/issues/30396

        # Combine both into single env vars string
        # Use jq's @sh formatter to properly escape values for shell
        # This handles spaces, quotes, and special chars safely
        ALL_ENV_VARS=$(jq -rn \
          --argjson envVars "$ENV_VARS_JSON" \
          --argjson secrets "$SECRETS_JSON" \
          '($envVars // [] | map("\(.name)=\(.value | @sh)")) + ($secrets // [] | map("\(.envVarName)=\("secretref:\(.name)" | @sh)")) | join(" ")')
        
        # echo "DEBUG - Combined env vars string: $ALL_ENV_VARS"
        
        # Use eval so bash properly interprets the shell-escaped strings from jq
        eval az containerapp update \
          --name ${{ parameters.containerAppName }} \
          --resource-group ${{ parameters.resourceGroup }} \
          --replace-env-vars $ALL_ENV_VARS
```
