### ISSUE TITLE
Error in Azure CLI 'account create' Command: AttributeError 'dict' object has no attribute 'object_id'

### ISSUE THREAD

**Issue by YutaSugino** [Azure/azure-cli#30390]
### Describe the bug

Unable to create a subscription when I use az account create command
azure-cli 2.67.0
![Image](https://github.com/user-attachments/assets/627af6c5-4d55-482c-a351-16ecb5436aca)

### Related command

az account create --enrollment-account-object-id %ENROLLMENT% --offer-type "MS-AZR-0017P" --display-name "Test" --owner-upn %OWNER%

### Errors

The command failed with an unexpected error. Here is the traceback:
'dict' object has no attribute 'object_id'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\aaz\latest\account\_create.py", line 84, in _execute_operations
    self.pre_operations()
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 106, in pre_operations
    owner_upn = [_object_id_args_helper(self.cli_ctx, upn=x) for x
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 68, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 60, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 41, in _get_object_id_by_upn
    return accounts[0].object_id
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'object_id'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

C:\Users\yutasugino>az account create --enrollment-account-object-id %ENROLLMENT% --offer-type "MS-AZR-0017P" --display-name "Test" --owner-upn %OWNER% --debug
cli.knack.cli: Command arguments: ['account', 'create', '--enrollment-account-object-id', 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', '--offer-type', 'MS-AZR-0017P', '--display-name', 'Test', '--owner-upn', 'test.nit_test.jp#EXT#@test.test.com', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000023DBE5AF2E0>, <function OutputProducer.on_global_arguments at 0x0000023DBE94C040>, <function CLIQuery.on_global_arguments at 0x0000023DBE971440>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'account': ['azure.cli.command_modules.profile', 'azure.cli.command_modules.resource', 'azext_subscription']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.008         2         8
cli.azure.cli.core: resource                  0.738        52       232
cli.azure.cli.core: Total (2)                 0.746        54       240
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: subscription              0.014         1         1  C:\Users\yutasugino\.azure\cliextensions\subscription
cli.azure.cli.core: Total (1)                 0.014         1         1
cli.azure.cli.core: Loaded 53 groups, 241 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : account create
cli.azure.cli.core: Command table: account create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000023DC0C41C60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\yutasugino\.azure\commands\2024-11-21.10-47-52.account_create.37176.log'.
az_command_data_logger: command args: account create --enrollment-account-object-id {} --offer-type {} --display-name {} --owner-upn {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000023DC0D45800>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000023DC0D458A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000023DC0D459E0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x0000023DC0D45A80>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000023DBE94C0E0>, <function CLIQuery.handle_query_parameter at 0x0000023DBE9714E0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000023DC0D45940>]
az_command_data_logger: extension name: subscription
az_command_data_logger: extension version: 1.0.0b1
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.util: Retrieving token for resource https://graph.microsoft.com/
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\yutasugino\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\yutasugino\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
msal.authority: openid_config("https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/kerberos', 'tenant_region_scope': 'JPR', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
cli.azure.cli.core.auth.msal_credentials: UserCredential.get_token: scopes=('https://graph.microsoft.com//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxcli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/users?$filter=userPrincipalName%20eq%20%27sugino.nittest.jp%23EXT%23%40suginonitest.com%27'
cli.azure.cli.core.util: Request method: 'GET'
cli.azure.cli.core.util: Request headers:
cli.azure.cli.core.util:     'User-Agent': 'python/3.12.7 (Windows-11-10.0.26100-SP0) AZURECLI/2.67.0 (MSI)'
cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
cli.azure.cli.core.util:     'Accept': '*/*'
cli.azure.cli.core.util:     'Connection': 'keep-alive'
cli.azure.cli.core.util:     'x-ms-client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
cli.azure.cli.core.util:     'CommandName': 'account create'
cli.azure.cli.core.util:     'ParameterSetName': '--enrollment-account-object-id --offer-type --display-name --owner-upn --debug'
cli.azure.cli.core.util:     'Authorization': 'Bearer eyJ0eXAiOiJKV...'
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: None
urllib3.connectionpool: Starting new HTTPS connection (1): graph.microsoft.com:443
urllib3.connectionpool: https://graph.microsoft.com:443 "GET /v1.0/users?$filter=userPrincipalName%20eq%20%27sugino.test.jp%23EXT%23%40testnit.test.com%27 HTTP/1.1" 200 None
cli.azure.cli.core.util: Response status: 200
cli.azure.cli.core.util: Response headers:
cli.azure.cli.core.util:     'Cache-Control': 'no-cache'
cli.azure.cli.core.util:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.util:     'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8'
cli.azure.cli.core.util:     'Content-Encoding': 'gzip'
cli.azure.cli.core.util:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000'
cli.azure.cli.core.util:     'request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
cli.azure.cli.core.util:     'client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
cli.azure.cli.core.util:     'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"Japan East","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"TY1PEPF000119A7"}}'
cli.azure.cli.core.util:     'x-ms-resource-unit': '2'
cli.azure.cli.core.util:     'OData-Version': '4.0'
cli.azure.cli.core.util:     'Date': 'Thu, 21 Nov 2024 01:47:52 GMT'
cli.azure.cli.core.util: Response content:
cli.azure.cli.core.util: {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users","value":[{"businessPhones":[],"displayName":"testYuta","givenName":"Yuta","jobTitle":null,"mail":null,"mobilePhone":null,"officeLocation":null,"preferredLanguage":"en","surname":"test","userPrincipalName":"sugino.test.jp#EXT#@test.test.com","id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}]}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\aaz\latest\account\_create.py", line 84, in _execute_operations
    self.pre_operations()
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 106, in pre_operations
    owner_upn = [_object_id_args_helper(self.cli_ctx, upn=x) for x
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 68, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 60, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 41, in _get_object_id_by_upn
    return accounts[0].object_id
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'object_id'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'dict' object has no attribute 'object_id'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\aaz\latest\account\_create.py", line 84, in _execute_operations
    self.pre_operations()
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 106, in pre_operations
    owner_upn = [_object_id_args_helper(self.cli_ctx, upn=x) for x
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 68, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 60, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 41, in _get_object_id_by_upn
    return accounts[0].object_id
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'object_id'
az_command_data_logger: 'dict' object has no attribute 'object_id'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 714, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1062, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\aaz\latest\account\_create.py", line 84, in _execute_operations
    self.pre_operations()
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 106, in pre_operations
    owner_upn = [_object_id_args_helper(self.cli_ctx, upn=x) for x
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 68, in _object_id_args_helper
    object_id = _get_object_id(graph_client, spn=spn, upn=upn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 60, in _get_object_id
    return _get_object_id_by_upn(graph_client, upn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yutasugino\.azure\cliextensions\subscription\azext_subscription\custom.py", line 41, in _get_object_id_by_upn
    return accounts[0].object_id
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'object_id'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000023DC0C41EE0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.691 seconds (init: 0.638, invoke: 2.053)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 8029 in cache file under C:\Users\yutasugino\.azure\telemetry\20241121104753764
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\yutasugino\.azure C:\Users\yutasugino\.azure\telemetry\20241121104753764"
telemetry.process: Return from creating process 15460
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

**a subscription created**
I'm guessing that the fact that _get_object_id_by_upn() in custom.py returns an object_id is the cause of the error.

https://github.com/Azure/azure-cli/blob/dc3ba8c18c736c3571f53438ad2bab54bcdfded3/src/azure-cli/azure/cli/command_modules/servicefabric/custom.py#L1670

In addition, I can find that _get_object_id_by_upn() in util.py returns an id.

https://github.com/Azure/azure-cli/blob/dc3ba8c18c736c3571f53438ad2bab54bcdfded3/src/azure-cli/azure/cli/command_modules/role/util.py#L27

### Environment Summary

**Local Machine(wiondws 11)**
azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
ssh                                2.0.5
subscription                     1.0.0b1

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\yutasugino\.azure\cliextensions'

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Azure Cloud Shell**
az --version
azure-cli                         2.65.0 *

core                              2.65.0 *
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.30.1
ssh                                2.0.5

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/home/sugino/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Aug 23 2024, 00:07:48) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

I checked on local machine (Windows 11) and Azure Cloud Shell.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
