### ISSUE TITLE
get-credentials password prompt should indicate system password required

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#3049]
When running `az acs get-credentials` for the first time, I always seem to forget whether the tool wants my system (OS) password, az user password, SSH key passphrase, etc. Might just be me experiencing this, but it would be helpful if the prompt could be more explicit which password is required. 

The error on a wrong password raises an SSHException which could give users the wrong idea about the actual failure (wrong system/sudo password, in this case). 
```
$ az acs kubernetes get-credentials -g $RESOURCE_GROUP -n $CLUSTER_NAME
Password:
Could not deserialize key data.
Traceback (most recent call last):
  File "/Users/seanknox/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/seanknox/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/Users/seanknox/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 403, in _execute_command
    raise ex
SSHException: Could not deserialize key data.
```

**Comment by squillace** [comment]
+1

**Comment by seanknox** [comment]
Thanks!
