### ISSUE TITLE
Deserialization error with az guestconfig guest-configuration-assignment create

### ISSUE THREAD

**Issue by Dieff** [Azure/azure-cli#30528]
### Describe the bug

Attempting to create a new azure machine configuration guest configuration assignment will fail immediately with a deserialization error. This occurs even when using the example create command [from the azure docs](https://learn.microsoft.com/en-us/cli/azure/guestconfig/guest-configuration-assignment?view=azure-cli-latest#az-guestconfig-guest-configuration-assignment-create).

### Related command

`az guestconfig guest-configuration-assignment create`

### Errors

```
The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>")), DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>"))', DeserializationError("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>")))
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1653, in deserialize_iter
azure.core.exceptions.DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1406, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1415, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1637, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1653, in deserialize_iter
azure.core.exceptions.DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\dieffenbache2\.azure\cliextensions\guestconfig\azext_guestconfig\generated\custom.py", line 47, in guestconfig_guest_configuration_assignment_create
    return sdk_no_wait(no_wait,
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 708, in sdk_no_wait
  File "C:\Users\dieffenbache2\.azure\cliextensions\guestconfig\azext_guestconfig\vendored_sdks\guestconfig\operations\_guest_configuration_assignment_operations.py", line 185, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dieffenbache2\.azure\cliextensions\guestconfig\azext_guestconfig\vendored_sdks\guestconfig\operations\_guest_configuration_assignment_operations.py", line 97, in _create_or_update_initial
    body_content = self._serialize.body(_parameters, 'GuestConfigurationAssignment')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 624, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 622, in body
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1406, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1415, in _deserialize
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1637, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/exceptions.py", line 51, in raise_with_traceback
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1626, in deserialize_data
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/serialization.py", line 1653, in deserialize_iter
azure.core.exceptions.SerializationError: ('Unable to build a model: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>")), DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>"))', DeserializationError("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>")))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

```
az guestconfig guest-configuration-assignment create --guest-configuration-assignment-name "WhitelistedApplication" --guest-configuration-name "WhitelistedApplication" --location "westcentralus" --context "Azure policy" --guest-configuration-name "WhitelistedApplication" --guest-configuration-configuration-parameter name="[InstalledApplication]bwhitelistedapp;Name" value="NotePad,sql" --guest-configuration-configuration-setting action-after-reboot="ContinueConfiguration" configuration-mode="MonitorOnly" configuration-mode-frequency-mins=15 reboot-if-needed="False" --guest-configuration-version "1.*" --resource-group "myResourceGroupName" --vm-name "myVMName"
```

### Expected behavior

Even if the wrong parameters are given, the error message should explain the problem with the argument. It should not be a Python stack trace.

### Environment Summary

❯ az --version
azure-cli                         2.66.0 *

core                              2.66.0 *
telemetry                          1.1.0

Extensions:
account                            0.2.5
bastion                            1.0.1
guestconfig                        0.1.1
log-analytics-solution               1.0.0
monitor-control-service               1.1.0
storage-preview                  1.0.0b4

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dieffenbache2\.azure\cliextensions'

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by keisari-ch** [comment]
I reproduced the issue with last version of cli and extension.

This was a troubleshooting attempt, because in our case, creating a guest config for a VM via the portal triggers the erasure of the VM resource group tags ...  

Logs below :

```json 
$ az version
{
  "azure-cli": "2.68.0",
  "azure-cli-core": "2.68.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "1.0.1",
    "containerapp": "1.1.0b1",
    "guestconfig": "0.1.1",
    "quota": "1.0.0"
  }
}
```


```
$ az guestconfig guest-configuration-assignment create --guest-configuration-assignment-name "WhitelistedApplication" --guest-configuration-name "WhitelistedApplication" --location "westcentralus" --context "Azure policy" --guest-configuration-name "WhitelistedApplication" --guest-configuration-configuration-parameter name="[InstalledApplication]bwhitelistedapp;Name" value="NotePad,sql" --guest-configuration-configuration-setting action-after-reboot="ContinueConfiguration" configuration-mode="MonitorOnly" configuration-mode-frequency-mins=15 reboot-if-needed="False" --guest-configuration-version "1.*" --resource-group "rg-tmp-vm" --vm-name "vm-tmp"

Command group 'guestconfig guest-configuration-assignment' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
('Unable to build a model: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>")), DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>"))', DeserializationError("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>")))
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1653, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
azure.core.exceptions.DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 622, in body
    data = deserializer._deserialize(data_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1406, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1415, in _deserialize
    return self.deserialize_data(data, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.12/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1653, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
azure.core.exceptions.DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 734, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 120, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/cesar/.azure/cliextensions/guestconfig/azext_guestconfig/generated/custom.py", line 47, in guestconfig_guest_configuration_assignment_create
    return sdk_no_wait(no_wait,
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/util.py", line 742, in sdk_no_wait
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/.azure/cliextensions/guestconfig/azext_guestconfig/vendored_sdks/guestconfig/operations/_guest_configuration_assignment_operations.py", line 185, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/.azure/cliextensions/guestconfig/azext_guestconfig/vendored_sdks/guestconfig/operations/_guest_configuration_assignment_operations.py", line 97, in _create_or_update_initial
    body_content = self._serialize.body(_parameters, 'GuestConfigurationAssignment')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 624, in body
    raise_with_traceback(
  File "/opt/az/lib/python3.12/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 622, in body
    data = deserializer._deserialize(data_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1406, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1415, in _deserialize
    return self.deserialize_data(data, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1637, in deserialize_data
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.12/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1626, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/msrest/serialization.py", line 1653, in deserialize_iter
    raise DeserializationError("Cannot deserialize as [{}] an object of type {}".format(
azure.core.exceptions.SerializationError: ('Unable to build a model: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>")), DeserializationError: ("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class \'str\'>"))', DeserializationError("Unable to deserialize response data. Data: {}, [AssignmentReportResource], DeserializationError: Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>", DeserializationError("Cannot deserialize as [AssignmentReportResource] an object of type <class 'str'>")))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues 
```
