### ISSUE TITLE
AttributeError: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'

### ISSUE THREAD

**Issue by abenn135** [Azure/azure-cli#30545]
### Describe the bug

I tried to create an AKS cluster but the command failed with an "unexpected error" and a traceback. I appear to be using aks-preview.

### Related command

`az aks create -g foo-test -n foo-test-c1 --location eastus`

N.B. group `foo-test` already exists in location `eastus`.

### Errors

```
The behavior of this command has been altered by the following extension: aks-preview
The new node pool will enable SSH access, recommended to use '--ssh-access disabled' option to disable SSH access for the node pool to make it more secure.
The command failed with an unexpected error. Here is the traceback:
'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 580, in aks_create
    mc = aks_create_decorator.construct_mc_profile_preview()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3656, in construct_mc_profile_preview
    mc = self.construct_mc_profile_default(bypass_restore_defaults=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6462, in construct_mc_profile_default
    mc = self.set_up_sku(mc)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3533, in set_up_sku
    if self.context.get_uptime_sla() or tier == CONST_MANAGED_CLUSTER_SKU_TIER_STANDARD:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'. Did you mean: '_get_uptime_sla'?
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

### Issue script & Debug output

script

```
az aks create -g alexbenn-test -n alexbenn-test-c1 --location eastus --debug
```

output (entra ID and sub ID have been redacted):

```
cli.knack.cli: Command arguments: ['aks', 'create', '-g', 'alexbenn-test', '-n', 'alexbenn-test-c1', '--location', 'eastus', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f16421137e0>, <function OutputProducer.on_global_arguments at 0x7f1641e5e660>, <function CLIQuery.on_global_arguments at 0x7f1641ea3ba0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azext_aks_preview', 'azure.cli.command_modules.acs', 'azure.cli.command_modules.serviceconnector']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.036        14        77
cli.azure.cli.core: serviceconnector          0.029        20       315
cli.azure.cli.core: Total (2)                 0.064        34       392
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: aks-preview               0.003        21        95  /home/abenn/.azure/cliextensions/aks-preview
cli.azure.cli.core: Total (1)                 0.003        21        95
cli.azure.cli.core: Loaded 42 groups, 421 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks create
cli.azure.cli.core: Command table: aks create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f16410dec00>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/abenn/.azure/commands/2024-12-19.11-57-35.aks_create.39424.log'.
az_command_data_logger: command args: aks create -g {} -n {} --location {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f1641117ec0>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f1640fbe2a0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f1640fbe3e0>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x7f1640fbe480>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f1641e5e700>, <function CLIQuery.handle_query_parameter at 0x7f1641ea3c40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f1640fbe340>]
az_command_data_logger: extension name: aks-preview
az_command_data_logger: extension version: 9.0.0b8
cli.azure.cli.core.commands: The behavior of this command has been altered by the following extension: aks-preview
cli.azext_aks_preview._validators: Use existing SSH public key file: /home/abenn/.ssh/id_rsa.pub
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/abenn/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/abenn/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/<redacted-entra-id>
msal.authority: openid_config("https://login.microsoftonline.com/<redacted-entra-id>/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/<redacted-entra-id>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<redacted-entra-id>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<redacted-entra-id>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<redacted-entra-id>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<redacted-entra-id>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<redacted-entra-id>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<redacted-entra-id>/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_credentials: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: fe491d4d-c2b1-4372-bb55-0691ebbec2f1
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<redacted-subscription-id>/resourceGroups/alexbenn-test/providers/Microsoft.ContainerService/managedClusters/alexbenn-test-c1?api-version=2024-07-02-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '583cbc2a-be2a-11ef-9159-690a6bcc62c0'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --location --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.67.0 (DEB) azsdk-python-core/1.31.0 Python/3.12.7 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<redacted-subscription-id>/resourceGroups/alexbenn-test/providers/Microsoft.ContainerService/managedClusters/alexbenn-test-c1?api-version=2024-07-02-preview HTTP/1.1" 404 244
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '244'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '79be55de-fb23-4623-a161-9b378a1e230b'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '79be55de-fb23-4623-a161-9b378a1e230b'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20241219T165736Z:79be55de-fb23-4623-a161-9b378a1e230b'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: BC9A9D7D6B8B44C4ABD4A72C12324C80 Ref B: MNZ221060618037 Ref C: 2024-12-19T16:57:35Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 19 Dec 2024 16:57:35 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.ContainerService/managedClusters/alexbenn-test-c1' under resource group 'alexbenn-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
cli.azext_aks_preview.custom: failed to get cluster, error: (ResourceNotFound) The Resource 'Microsoft.ContainerService/managedClusters/alexbenn-test-c1' under resource group 'alexbenn-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.ContainerService/managedClusters/alexbenn-test-c1' under resource group 'alexbenn-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azext_aks_preview.agentpool_decorator: The new node pool will enable SSH access, recommended to use '--ssh-access disabled' option to disable SSH access for the node pool to make it more secure.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'snapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'managedclustersnapshot' does not exist. Return default value 'None'.
cli.azure.cli.command_modules.acs.base_decorator: The intermediate 'subscription_id' does not exist. Return default value 'None'.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 580, in aks_create
    mc = aks_create_decorator.construct_mc_profile_preview()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3656, in construct_mc_profile_preview
    mc = self.construct_mc_profile_default(bypass_restore_defaults=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6462, in construct_mc_profile_default
    mc = self.set_up_sku(mc)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3533, in set_up_sku
    if self.context.get_uptime_sla() or tier == CONST_MANAGED_CLUSTER_SKU_TIER_STANDARD:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'. Did you mean: '_get_uptime_sla'?

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 580, in aks_create
    mc = aks_create_decorator.construct_mc_profile_preview()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3656, in construct_mc_profile_preview
    mc = self.construct_mc_profile_default(bypass_restore_defaults=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6462, in construct_mc_profile_default
    mc = self.set_up_sku(mc)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3533, in set_up_sku
    if self.context.get_uptime_sla() or tier == CONST_MANAGED_CLUSTER_SKU_TIER_STANDARD:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'. Did you mean: '_get_uptime_sla'?
az_command_data_logger: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'
Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 580, in aks_create
    mc = aks_create_decorator.construct_mc_profile_preview()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3656, in construct_mc_profile_preview
    mc = self.construct_mc_profile_default(bypass_restore_defaults=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/acs/managed_cluster_decorator.py", line 6462, in construct_mc_profile_default
    mc = self.set_up_sku(mc)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/abenn/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 3533, in set_up_sku
    if self.context.get_uptime_sla() or tier == CONST_MANAGED_CLUSTER_SKU_TIER_STANDARD:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AKSPreviewManagedClusterContext' object has no attribute 'get_uptime_sla'. Did you mean: '_get_uptime_sla'?
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f16410dee80>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.140 seconds (init: 0.105, invoke: 1.035)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 8137 in cache file under /home/abenn/.azure/telemetry/20241219115736087
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.12/site-packages/azure/cli/telemetry/__init__.py /home/abenn/.azure /home/abenn/.azure/telemetry/20241219115736087"
telemetry.process: Return from creating process 39429
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Creates AKS cluster with the specified name in the specified subscription and location.

### Environment Summary

```
azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
aks-preview                      9.0.0b8
azure-devops                       1.0.1

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/abenn/.azure/cliextensions'

Python (Linux) 3.12.7 (main, Nov 13 2024, 04:02:11) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

### Additional context

I am a Microsoft employee logged in with my corporate credentials.

**Comment by abenn135** [comment]
Update: I had an old version of `aks-preview`. Running

`az extension update --name aks-preview`

appears to have fixed the issue. Perhaps this is instead a FR to automatically update extensions?

**Comment by mbifeld** [comment]
Hi @abenn135, glad a newer version fixed the issue for you! If you still have a feature request for opt-ins to auto-updated extensions, I'd recommend making a new issue, so it gets better tracked and hopefully routed to the right people. I'm going to close this issue since the original problem is now resolved. Please reopen / tag me if there's still issues with the original problem. Thanks!
