### ISSUE TITLE
az eventgrid partner namespace create

### ISSUE THREAD

**Issue by alexander-kastil** [Azure/azure-cli#30560]
### Describe the bug

When executing az eventgrid partner namespace create with the id for MicrosoftGraphAPI (c02e0126-707c-436d-b6a1-175d2748fb58) or even the sample from docs on gets the following error message:

(LinkedInvalidPropertyId) Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

### Related command

az eventgrid partner namespace create

### Errors

(LinkedInvalidPropertyId) Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['eventgrid', 'partner', 'namespace', 'create', '-g', 'rg1', '--name', 'namespaceName1', '-l', 'westus2', '--partner-registration-id', 'c02e0126-707c-436d-b6a1-175d2748fb58', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000015EF44CB2E0>, <function OutputProducer.on_global_arguments at 0x0000015EF486C040>, <function CLIQuery.on_global_arguments at 0x0000015EF4891440>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'eventgrid': ['azure.cli.command_modules.eventgrid']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: eventgrid                 0.003        25        96
cli.azure.cli.core: Total (1)                 0.003        25        96
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 25 groups, 96 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : eventgrid partner namespace create
cli.azure.cli.core: Command table: eventgrid partner namespace create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x0000015EF6BD1C60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\AlexanderKastil\.azure\commands\2024-12-20.10-16-12.eventgrid_partner_namespace_create.13504.log'.
az_command_data_logger: command args: eventgrid partner namespace create -g {} --name {} -l {} --partner-registration-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0000015EF6C0F420>]
cli.knack.commands: Configured default 'westeurope' for arg location
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0000015EF6C3D800>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0000015EF6C3D940>, <function register_upcoming_breaking_change_info.<locals>.update_breaking_change_info at 0x0000015EF6C3D9E0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000015EF486C0E0>, <function CLIQuery.handle_query_parameter at 0x0000015EF48914E0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0000015EF6C3D8A0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=EventGridManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\AlexanderKastil\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\AlexanderKastil\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a
msal.authority: openid_config("https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_credentials: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 490b8ee4-5887-47fa-9713-c604675208d7
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/78033352-805c-4acd-af80-f8f95083268d/resourceGroups/rg1/providers/Microsoft.EventGrid/partnerNamespaces/namespaceName1?api-version=2021-10-15-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '196'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0ec9850e-beb3-11ef-a473-010101010000'
cli.azure.cli.core.sdk.policies:     'CommandName': 'eventgrid partner namespace create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --name -l --partner-registration-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.67.0 (MSI) azsdk-python-core/1.31.0 Python/3.12.7 (Windows-11-10.0.26100-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westus2", "properties": {"partnerRegistrationFullyQualifiedId": "c02e0126-707c-436d-b6a1-175d2748fb58", "disableLocalAuth": false, "partnerTopicRoutingMode": "SourceEventAttribute"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/78033352-805c-4acd-af80-f8f95083268d/resourceGroups/rg1/providers/Microsoft.EventGrid/partnerNamespaces/namespaceName1?api-version=2021-10-15-preview HTTP/1.1" 400 307
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '307'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '75566a17-6f6a-47bd-98a6-10dcfdd9900c'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '75566a17-6f6a-47bd-98a6-10dcfdd9900c'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'POLANDCENTRAL:20241220T091614Z:75566a17-6f6a-47bd-98a6-10dcfdd9900c'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: AC82C9B850D149AA8DE428E57E0E1B90 Ref B: VIEEDGE2115 Ref C: 2024-12-20T09:16:14Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 20 Dec 2024 09:16:13 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"LinkedInvalidPropertyId","message":"Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 666, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 703, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 336, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventgrid/custom.py", line 956, in cli_partner_namespace_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/eventgrid/operations/_partner_namespaces_operations.py", line 519, in begin_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/eventgrid/operations/_partner_namespaces_operations.py", line 466, in _create_or_update_initial
azure.core.exceptions.HttpResponseError: (LinkedInvalidPropertyId) Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

cli.azure.cli.core.azclierror: (LinkedInvalidPropertyId) Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
az_command_data_logger: (LinkedInvalidPropertyId) Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
Code: LinkedInvalidPropertyId
Message: Property id 'c02e0126-707c-436d-b6a1-175d2748fb58' at path 'properties.partnerRegistrationFullyQualifiedId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x0000015EF6BD1EE0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.837 seconds (init: 0.147, invoke: 0.690)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4395 in cache file under C:\Users\AlexanderKastil\.azure\telemetry\20241220101613558
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\AlexanderKastil\.azure C:\Users\AlexanderKastil\.azure\telemetry\20241220101613558"
telemetry.process: Return from creating process 3756
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

A partner configuration should be created.

### Environment Summary

azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
application-insights               1.2.2
azure-devops                       1.0.1
rdbms-connect                      1.0.7

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\AlexanderKastil\.azure\cliextensions'

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
