### ISSUE TITLE
Microsoft Azure CLI not compatible with device state conditional access

### ISSUE THREAD

**Issue by magic-happenz** [Azure/azure-cli#30575]
### Describe the bug

Hello,

I just setup a new WSL instance and noticed that `az login` seems no longer work.
The first problem I encounter is the missing browser opening already mentioned in multiple open issues such as: https://github.com/Azure/azure-cli/issues/27879.
But worse is the incompatibility with conditional access policies that check on device state. 

### Related command

az login

### Errors

In Browser:
Authentication failed access_denied: $error_description. ($error_uri)

In Console:
Operation not supported
None
Interactive authentication is needed. Please run:
az login

### Issue script & Debug output

msal.oauth2cli.authcode: Got auth response: {'error': 'access_denied', 'error_subcode': 'cancel', 'state': 'bIADrGdEnUwiemoN'}
msal.oauth2cli.authcode: "GET /?error=access_denied&error_subcode=cancel&state=bIADrGdEnUwiemoN HTTP/1.1" 200 -
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
    raise ex
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/command_modules/profile/custom.py", line 173, in login
    subscriptions = profile.login(
                    ^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/_profile.py", line 176, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/auth/identity.py", line 173, in login_with_auth_code
    return check_result(result)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/auth/util.py", line 149, in check_result
    aad_error_handler(result, **kwargs)
  File "/opt/az/lib/python3.12/site-packages/azure/cli/core/auth/util.py", line 53, in aad_error_handler
    raise AuthenticationError(error_description, msal_error=error, recommendation=recommendation)
azure.cli.core.azclierror.AuthenticationError: None

cli.azure.cli.core.azclierror: None
az_command_data_logger: None
Interactive authentication is needed. Please run:
az login
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f31bb8bae80>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 16.640 seconds (init: 0.138, invoke: 16.503)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3546 in cache file under /home/user/.azure/telemetry/20241224113051999
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.12/site-packages/azure/cli/telemetry/__init__.py /home/user/.azure /home/user/.azure/telemetry/20241224113051999"
telemetry.process: Return from creating process 1255
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Successfully login to the CLI.

### Environment Summary

azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.12.7 (main, Nov 13 2024, 04:06:34) [GCC 13.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

To reproduce:

- Install Azure CLI on WSL
- Run `az login`
- Note ` Operation not supported`
- Click the link from the console anyways
- Sign in
- Get the following message
![Image](https://github.com/user-attachments/assets/85ab530d-e2fb-4d25-91e2-13b99c31a3eb)
- On click `Ok` receive error: `Authentication failed access_denied: $error_description. ($error_uri)`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
The error message indicates your device is not registered:

![Image](https://github.com/user-attachments/assets/85ab530d-e2fb-4d25-91e2-13b99c31a3eb)

The error is returned by Microsoft Entra ID, not Azure CLI, so I don't think it is related to running Azure CLI in WSL. If you install Azure CLI directly on Windows (https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and run `az login`, it is very likely you will see the same error message.

I would recommend double check your organization's policy and register your device accordingly.

**Comment by magic-happenz** [comment]
@jiasli thank you for the reply. My device is registered actually and as I am administrator of my company's policies I can tell you that the policy is not supposed to apply to this use case. Browser Auth is excluded. That means something in the Auth process of Azure CLI is telling Entra that it's a client app and not a browser. So why is that?
Works with device login flow by the way.

**Comment by magic-happenz** [comment]
> If you install Azure CLI directly on Windows (https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and run `az login`, it is very likely you will see the same error message.
Nope, just tried. A little window opens which asks me to pick my account and then I am logged in. Why this was changed? What was wrong with simple browser window? I don't know when and what was changed but you broke the possibility to use it in WSL, any ways to fix this?

**Comment by kaplik** [comment]
We are experiencing the same issue, WSL2 on a Windows machine. `az login` is not able to open a browser and triggers device code workflow, the user opens `/devicelogin` and pastes the code and is stopped by the conditional access policy, because " the device is not compliant". The same user, from the same device/browser, can login into the Azure portal with no issue. I can also see in the AAD Singin logs that the device ID (in both cases) is the same and that the device is in fact compliant.

**Conditional access policy settings**
![Image](https://github.com/user-attachments/assets/7ffad10d-3b52-458f-b67c-d8521b73dc81)
![Image](https://github.com/user-attachments/assets/447c0b5d-2af4-4d5a-b468-5bd57dc830e4)


**Login from Azure CLI in WSL (via device code from browser)**
![Image](https://github.com/user-attachments/assets/83c79db2-d7f3-4777-b8e8-1f36ae081ea9)
![Image](https://github.com/user-attachments/assets/a4de235c-b7fd-4db8-a745-c8c48f59e5c4)


**Login to Azure portal (for comparison from the same browser/device):**
![Image](https://github.com/user-attachments/assets/05986292-7616-4b03-bb71-e7dc46453097)
![Image](https://github.com/user-attachments/assets/dda24bd6-7c8c-4478-a05a-06dbdb303b07)

**Comment by GimmeDaKitty** [comment]
I dont know whether this is relevant or helps. But if using device code auth is not really a requierement here I have a solutio  that works for me.

In wsl I need to define the location of my browser through the BROWSER env variable, then restart wsl. When I do so I am able to use az login, wsl opens a browser window and Im able to authenticate using the oauth flow.

Source and details:
https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux

**Comment by magic-happenz** [comment]
So what worked for me is signing into Edge with my work profile. I don't really get the way it works honestly as the app that was blocked before can not be found in my tenant which in turn means I can even not exclude it from conditional access.

That does not fix the lack of browser support in WSL. However, the solution from @GimmeDaKitty looks very promising.
