### ISSUE TITLE
az ad group create fails with "Property  should not be set." 

### ISSUE THREAD

**Issue by grahamsk** [Azure/azure-cli#3162]
### Description
**Outline the issue here:**
az ad group create fails with "Property  should not be set." 
Full command: az ad group create --verbose --mail-nickname=XXX --display-name=YYY
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Installed using the interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.4)

**OS Version:** What OS and version are you using?  
Answer here:
OSX 10.11.6 (15G31) (El Capitan)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by grahamsk** [comment]
Also tried in the latest azure cli docker container and got this error message:

```
bash-4.3# az ad group create --verbose --mail-nickname=XXX --display-name=YYY
Property  should not be set.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 276, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 475, in _execute_command
    raise client_exception
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 469, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 443, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/graphrbac/operations/groups_operations.py", line 314, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Property  should not be set.
```

**Comment by mayurid** [comment]
I tried this and its working for me on the same build. Could we get a the log with --debug as an option?
@yugangw-msft as Fyi

**Comment by yugangw-msft** [comment]
Not repro, Note, it is a server error
Please reopen it with more details
