### ISSUE TITLE
Add msrest.exceptions.ValidationError to core exception handling logic

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3271]
### Description
```
$ az group create -lwestus -n mysqltest
$ az mysql server create -g mysqltest -n name -u username -p password
$ az mysql server firewall-rule create -g mysqltest -s name -n rulename --start-ip-address * --end-ip-address *
Parameter 'FirewallRule.start_ip_address' must conform to the following pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 482, in _execute_command
    raise client_exception
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 476, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/rdbms/mysql/operations/firewall_rules_operations.py", line 95, in create_or_update
    body_content = self._serialize.body(parameters, 'FirewallRule')
  File "/usr/local/lib/python3.5/dist-packages/msrest/serialization.py", line 302, in body
    return self._serialize(data, data_type, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/msrest/serialization.py", line 245, in _serialize
    target_obj, data_type, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/msrest/serialization.py", line 431, in serialize_data
    return self._serialize(data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/msrest/serialization.py", line 265, in _serialize
    orig_attr, debug_name, **validation)
  File "/usr/local/lib/python3.5/dist-packages/msrest/serialization.py", line 390, in validate
    raise ValidationError(key, name, value)
msrest.exceptions.ValidationError: Parameter 'FirewallRule.start_ip_address' must conform to the following pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'.
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: n/a

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
$ az --version
azure-cli (2.0.5)

acr (2.0.3)
acs (2.0.5)
appservice (0.1.5)
batch (2.0.3)
cdn (0.0.1)
cloud (2.0.2)
cognitiveservices (0.1.1)
command-modules-nspkg (2.0.0)
component (2.0.3)
configure (2.0.5)
core (2.0.5)
dla (0.0.5)
dls (0.0.5)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.0)
iot (0.1.5)
keyvault (2.0.3)
lab (0.0.4)
monitor (0.0.3)
network (2.0.5)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.2)
resource (2.0.5)
role (2.0.3)
sf (1.0.0)
sql (2.0.2)
storage (2.0.5)
vm (2.0.5)

Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

Python location '/usr/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here: n/a

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `bash`

**Comment by mayurid** [comment]
@Suna-MS : incoming issue assigned to upcoming sprint.

**Comment by Suna-MS** [comment]
In swagger specs,  the validation pattern of IP address was added to the firewall rule schema definition, and the auto generated python sdk will has this pattern validation, which is a common usage and I was suggested to do validation like this.  Not sure how to avoid the too long stack trace, any suggestions?
 Maybe we need autorest team' s help for the improvement?

**Comment by tjprescott** [comment]
It may just be we should catch this type of exception in addition to the CloudError exception as part of core. @derekbekoe thoughts?

**Comment by derekbekoe** [comment]
Yes that makes sense.
