### ISSUE TITLE
[CDN] Stacktrace for 404

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3304]
When I run `cdn profile delete` on a profile that doesn't exist, I get a stack trace:

```
Operation returned an invalid status code 'Not Found'
Traceback (most recent call last):
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/command_modules/azure-cli-interactive/azclishell/app.py", line 536, in cli_execute
    result = self.app.execute(args)
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 478, in _execute_command
    raise client_exception
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/mnt/c/Users/trpresco/Documents/github/env3/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/mnt/c/Users/trpresco/Documents/github/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/mnt/c/Users/trpresco/Documents/github/env3/lib/python3.5/site-packages/azure/mgmt/cdn/operations/profiles_operations.py", line 212, in get
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.cdn.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Not Found'
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: latest master

**OS Version:** What OS and version are you using?  
Answer here: Win10 CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on Windows

**Comment by devigned** [comment]
I verified the response from the REST API is actually a 204 rather than a 404 when DELETE was called on a profile that doesn't exist. I'll add a test, but I think this no longer an issue.

Even under 404s, the CLI will not respond with a stacktrace.

**Comment by tjprescott** [comment]
Yep. This is no longer an issue!
