### ISSUE TITLE
Error when trying to retrieve plans in a resource group

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-cli#3343]
### Description
**Outline the issue here:**

Error when trying to retrieve plans in a resource group. Note that this is when running as part of the VSCode extension, it doesn't seem to be specific to that though.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: azure-cli-0.2.8.msi

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.6

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\devel\ms-vscode-azurecli\service\azservice\__main__.py", line 335, in <module>
    main()
  File "c:\devel\ms-vscode-azurecli\service\azservice\__main__.py", line 326, in main
    response_data = get_completions(group_index, command_table, snippets, request['data'], True)
  File "c:\devel\ms-vscode-azurecli\service\azservice\__main__.py", line 114, in get_completions
    return get_argument_value_completions(command_table, query, verbose)
  File "c:\devel\ms-vscode-azurecli\service\azservice\__main__.py", line 182, in get_argument_value_completions
    list = get_argument_value_list(command_table, query, verbose) + \
  File "c:\devel\ms-vscode-azurecli\service\azservice\__main__.py", line 200, in get_argument_value_list
    values = run_argument_value_completer(command, argument, query['arguments'])
  File "c:\devel\ms-vscode-azurecli\service\azservice\tooling.py", line 130, in run_argument_value_completer
    return argument.completer('', '', args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\parameters.py", line 83, in completer
    return [r.name for r in get_resources_in_resource_group(rg, resource_type=resource_type)]
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\parameters.py", line 69, in get_resources_in_resource_group
    return list(rcf.resource_groups.list_resources(resource_group_name, filter=filter_str))
AttributeError: 'ResourceGroupsOperations' object has no attribute 'list_resources'
```

**Comment by yugangw-msft** [comment]
This was broken by we pulling in the latest resource sdk

**Comment by vivsriaus** [comment]
@chrmarti Thanks for reporting this issue. Should be fixed in the upcoming release.
