### ISSUE TITLE
az storage blob list --num-results: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by mmacy** [Azure/azure-cli#3430]
### Description

When limiting the result set with the `az storage blob list` command's `--num-results` argument to any number less than the number of blobs in a container, I receive the following error:
 
**unsupported operand type(s) for -: 'str' and 'int'**
 
Here's output from both a successful list operation and a failed operation (there are 10 blobs in the container):
 
```
marsma@marsma-02:~$ az storage blob list --account-name azstorage002 --container-name mystoragecontainer --num-results 10 --output table
Name                               Blob Type      Length  Content Type              Last Modified
---------------------------------  -----------  --------  ------------------------  -------------------------
container_size_sample_file_1.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_10.txt  BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_2.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:38+00:00
container_size_sample_file_3.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_4.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_5.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_6.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_7.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_8.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
container_size_sample_file_9.txt   BlockBlob          33  application/octet-stream  2017-05-23T15:37:37+00:00
```

```
marsma@marsma-02:~$ az storage blob list --account-name azstorage002 --container-name mystoragecontainer --num-results 9 --output table
unsupported operand type(s) for -: 'str' and 'int'
Traceback (most recent call last):
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 456, in _execute_command
    return transform_result(result)
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/storage/_transformers.py", line 101, in transform_storage_list_output
    return list(result)
  File "/home/marsma/lib/azure-cli/local/lib/python2.7/site-packages/azure/multiapi/storage/v2016_05_31/models.py", line 102, in __iter__
    max_results = max_results - len(self.items)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
marsma@marsma-02:~$ 
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  

interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

```
marsma@marsma-02:~$ az --version
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.1)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

Python location '/home/marsma/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  

```
marsma@marsma-02:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

bash

**Comment by troydai** [comment]
Found the issue, I'm working on a solution.
