### ISSUE TITLE
az interactive errors out with the profile 2017-03-09-profile-preview

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3467]
### Description
after updating the default profile as 2017-03-09-profile-preview,  az interactive  errors out with the following
```
No module named 'azure.mgmt.network.v2015_06_15.operations.packet_captures_operations'
Traceback (most recent call last):
  File "d:\github\azure-cli\src\azure-cli\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\application.py", line 210, in execute
    result = expanded_arg.func(params)
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 488, in _execute_command
    reraise(*sys.exc_info())
  File "D:\github\azure-cli\env\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 465, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "d:\github\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\custom.py", line 13, in start_shell
    from azclishell.__main__ import main
  File "d:\github\azure-cli\src\command_modules\azure-cli-interactive\azclishell\__main__.py", line 12, in <module>
    import azclishell._dump_help
  File "d:\github\azure-cli\src\command_modules\azure-cli-interactive\azclishell\_dump_help.py", line 8, in <module>
    dump_command_table()  # because need to write to files before read them
  File "d:\github\azure-cli\src\command_modules\azure-cli-interactive\azclishell\_dump_commands.py", line 51, in dump_command_table
    install_modules()
  File "d:\github\azure-cli\src\command_modules\azure-cli-interactive\azclishell\_dump_commands.py", line 27, in install_modules
    CMD_TABLE[cmd].load_arguments()
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 250, in load_arguments
    self.arguments.update(self.arguments_loader())
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 515, in arguments_loader
    return extract_args_from_signature(get_op_handler(operation), no_wait_param=no_wait_param)
  File "d:\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 399, in get_op_handler
    op = import_module(mod_to_import)
  File "D:\github\azure-cli\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'azure.mgmt.network.v2015_06_15.operations.packet_captures_operations'
```
---

### Environment summary

**Install Method:** 
pip install nightly builds

**OS Version:** 
Windows

**Shell Type:** 
cmd

**Comment by mayurid** [comment]
@oakeyc to take a look in upcoming sprint.
@derekbekoe as FYI
