### ISSUE TITLE
az fails when running in parallel threads

### ISSUE THREAD

**Issue by dmitsh** [Azure/azure-cli#3468]
### Description
**Outline the issue here:**

When running az in parallel threads, observing the following randomly appearing error:

ERROR: Error loading command module 'acr'
ERROR: Error loading command module 'acs'
ERROR: Error loading command module 'appservice'
ERROR: Error loading command module 'cdn'
ERROR: Error loading command module 'dla'
ERROR: Error loading command module 'dls'
ERROR: Error loading command module 'iot'
ERROR: Error loading command module 'keyvault'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'monitor'
ERROR: Error loading command module 'network'
ERROR: Error loading command module 'rdbms'
ERROR: Error loading command module 'redis'
ERROR: Error loading command module 'resource'
ERROR: Error loading command module 'sf'
ERROR: Error loading command module 'sql'
ERROR: Error loading command module 'storage'
ERROR: Error loading command module 'vm'
ERROR: az: error: argument _command_package: invalid choice: group
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {interactive,ad,feedback,cognitiveservices,cloud,account,batch,component,logout,role,login,cosmosdb,find,configure}
          ...

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip install "azure-cli==2.0.6

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.6

**OS Version:** What OS and version are you using?  
Answer here:
Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
az login

**Comment by dmitsh** [comment]
Another randomly observed error:

ERROR: The cloud 'AzureCloud' is not registered.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/resource/custom.py", line 229, in deploy_arm_template
    deployment_name, parameters, mode, no_wait=no_wait)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/resource/custom.py", line 333, in _deploy_arm_template_core
    smc = get_mgmt_service_client(ResourceType.MGMT_RESOURCE_RESOURCES)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/client_factory.py", line 32, in get_mgmt_service_client
    api_version=api_version, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/client_factory.py", line 66, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/_profile.py", line 314, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/_profile.py", line 291, in get_subscription
    subscriptions = self.load_cached_subscriptions()
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/_profile.py", line 276, in load_cached_subscriptions
    active_cloud = get_active_cloud()
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/cloud.py", line 283, in get_active_cloud
    return get_cloud(get_active_cloud_name())
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/cloud.py", line 278, in get_cloud
    raise CloudNotRegisteredException(cloud_name)
CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.

**Comment by derekbekoe** [comment]
Closing as this is the same as https://github.com/Azure/azure-cli/issues/3255
