### ISSUE TITLE
CLI fails to import "requests" package

### ISSUE THREAD

**Issue by ericvanwijk** [Azure/azure-cli#3497]
### Description
**Outline the issue here:**
az login: 'ValueError: need more than 2 values to unpack'

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.6

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: terminal/bash

EVW-MBA-2013:~ eric$ az login 
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 23, in <module>
    exit_code = azure.cli.main.main(args)
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 52, in main
    error_code = handle_exception(ex)
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/util.py", line 34, in handle_exception
    from msrestazure.azure_exceptions import CloudError
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/msrestazure/__init__.py", line 28, in <module>
    from .azure_configuration import AzureConfiguration
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/msrestazure/azure_configuration.py", line 33, in <module>
    from msrest import Configuration
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/msrest/__init__.py", line 27, in <module>
    from .configuration import Configuration
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/msrest/configuration.py", line 36, in <module>
    import requests
  File "/Users/eric/lib/azure-cli/lib/python2.7/site-packages/requests/__init__.py", line 49, in <module>
    major, minor, patch = urllib3.__version__.split('.')[:3]
ValueError: need more than 2 values to unpack

**Comment by KylieLiang** [comment]
met same problem. How to resolve it?

**Comment by KylieLiang** [comment]
I met this problem on FreeBSD 11.0 though curl -L https://aka.ms/InstallAzureCli | bash

**Comment by du8die** [comment]
Same here.

**Comment by dazzur** [comment]
Exactly the same problem as ericvanwijk; exactly same environment.


Darrens-MacBook-Pro:~ dazzur$ az login
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 23, in <module>
    exit_code = azure.cli.main.main(args)
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 52, in main
    error_code = handle_exception(ex)
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/util.py", line 34, in handle_exception
    from msrestazure.azure_exceptions import CloudError
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/msrestazure/__init__.py", line 28, in <module>
    from .azure_configuration import AzureConfiguration
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/msrestazure/azure_configuration.py", line 33, in <module>
    from msrest import Configuration
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/msrest/__init__.py", line 27, in <module>
    from .configuration import Configuration
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/msrest/configuration.py", line 36, in <module>
    import requests
  File "/Users/dazzur/lib/azure-cli/lib/python2.7/site-packages/requests/__init__.py", line 49, in <module>
    major, minor, patch = urllib3.__version__.split('.')[:3]
ValueError: need more than 2 values to unpack

**Comment by floresboy** [comment]
Same here on Raspberry03
File "/home/pi/lib/azure-cli/local/lib/python2.7/site-packages/requests/__init__.py", line 49, in <module>
    major, minor, patch = urllib3.__version__.split('.')[:3]
ValueError: need more than 2 values to unpack

Please resolve cause having a CLI on Raspi would be great!

**Comment by yugangw-msft** [comment]
This issue is not `az login` specific, rather any commands sending http request on the wire should trigger this. Of course, `az login` usually is the first command you would run.

**Comment by floresboy** [comment]
your totally right, nonetheless a solution is greatly appreciated 
Thanks Kamiel

**Comment by yugangw-msft** [comment]
We have made a new release with a fix that likely resolves this issue. Please verify, if still repro's please reactivate it

**Comment by KylieLiang** [comment]
verified on FreeBSD 11. Works. Thank you.

**Comment by ericvanwijk** [comment]
Verfied in macOS, thx.
