### ISSUE TITLE
Error when installing on mac os

### ISSUE THREAD

**Issue by bargitta** [Azure/azure-cli#3500]
### Description
**Outline the issue here:**
I got error when installing azure-cli2.0 on macos, 
I installed it via this : curl -L https://aka.ms/InstallAzureCli | bash
here is the error

Traceback (most recent call last):
  File "/var/folders/zw/49g51ryj2nbcp8w6csnwrc8c0000gn/T/azure_cli_install_tmp_XXXX.cvoL0rkx", line 370, in <module>
    main()
  File "/var/folders/zw/49g51ryj2nbcp8w6csnwrc8c0000gn/T/azure_cli_install_tmp_XXXX.cvoL0rkx", line 355, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/var/folders/zw/49g51ryj2nbcp8w6csnwrc8c0000gn/T/azure_cli_install_tmp_XXXX.cvoL0rkx", line 122, in create_virtualenv
    download_location)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 65] No route to host
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: 
I followed this document: 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
and install via:
curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:2.0

**OS Version:** What OS and version are you using?  
Answer here: mac os Sierra 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
This is a generic network issue, not CLI particularly. Can you try it again?

**Comment by yugangw-msft** [comment]
please reactivate if you still reproduce it
