### ISSUE TITLE
az interactive -> vm create --size throws

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-cli#3552]
### Description
Using the AZ Interactive shell to create a vm with size parameter throws:

az>> vm create --size Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python3.5/site-packages/azclishell/az_completer.py", line 156, in get_completions------------------------------------
    for val in sort_completions(self.gen_dynamic_completions(text)):  *
  File "/usr/local/lib/python3.5/site-packages/azclishell/az_completer.py", line 86, in sort_completions
    for comp in gen:------------------------------------------------------------------------------------------------------------------------
  File "/usr/local/lib/python3.5/site-packages/azclishell/az_completer.py", line 219, in gen_dynamic_completions
    prefix=prefix, action=None, parsed_args=parse_args):S
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/_params.py", line 38, in get_vm_size_completion_list
    result = get_vm_sizes(location)VM with a private IP address.
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/_actions.py", line 152, in get_vm_sizes
    return list(_compute_client_factory().virtual_machine_sizes.list(location))
  File "/usr/local/lib/python3.5/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()custom managed image (see `az image create` for generation information).
  File "/usr/local/lib/python3.5/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/lib/python3.5/site-packages/azure/mgmt/compute/compute/v2016_04_30_preview/operations/virtual_machine_sizes_operations.pg
    'location': self._serialize.url("location", location, 'str', pattern='^[-\w\._]+$'),
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 313, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/msrest/serialization.py", line 380, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'location' can not be None.

---

### Environment summary

**Install Method:** 
Docker pull, apt-get upgrade on Bash on Widnows

**CLI Version:** 

***WSL:***

az>> --version
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.6.1 (default, May 30 2017, 16:59:26)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

az>>

***Docker:***

az>> --version
azure-cli (2.0.7+dev)

acr (2.0.5+dev)
acs (2.0.7+dev)
appservice (0.1.7+dev)
batch (3.0.0+dev)
billing (0.1.0+dev)
cdn (0.0.3+dev)
cloud (2.0.3+dev)
cognitiveservices (0.1.3+dev)
command-modules-nspkg (2.0.0+dev)
component (2.0.5+dev)
configure (2.0.7+dev)
consumption (0.1.0+dev)
core (2.0.7+dev)
cosmosdb (0.1.7+dev)
dla (0.0.7+dev)
dls (0.0.7+dev)
feedback (2.0.3+dev)
find (0.2.3+dev)
interactive (0.3.3+dev)
iot (0.1.6+dev)
keyvault (2.0.5+dev)
lab (0.0.5+dev)
monitor (0.0.5+dev)
network (2.0.7+dev)
nspkg (3.0.0+dev)
profile (2.0.5+dev)
rdbms (0.0.2+dev)
redis (0.2.4+dev)
resource (2.0.7+dev)
role (2.0.5+dev)
sf (1.0.2+dev)
sql (2.0.4+dev)
storage (2.0.7+dev)
taskhelp (0.1.2+dev)
vm (2.0.7+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'

az>>

**OS Version:** 
Ubuntu 16.04 and Windows 10

**Shell Type:** 
Bash and Powershell

**Comment by tjprescott** [comment]
It seems to vomit when it tries to get the completions.
