### ISSUE TITLE
ML should handle missing RSA keys better

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3578]
### Description
```
$ az ml service view realtime -n asdf
[Errno 2] No such file or directory: '/Users/jasonsha/.ssh/acs_id_rsa'
Traceback (most recent call last):
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 210, in execute
    result = expanded_arg.func(params)
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/jasonsha/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 488, in _execute_command
```

This should instead direct the user to the command or process to create the acs_id_rsa file.

**Comment by tjprescott** [comment]
Shouldn't this be in the ML team's repo?

**Comment by mayurid** [comment]
@JasonRShaver : I dont believe ML is looking at this repo. Can you shoot them a mail?
