### ISSUE TITLE
az acs browse (Kubernetes) fails if using an encrypted ssh key

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3605]
### Description
If you create an ACS cluster using an encrypted SSH key and then try to browse to cluster, the operation fails:
`az acs browse --name [value] `

```
Private key file is encrypted
Traceback (most recent call last):
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 210, in execute
    result = expanded_arg.func(params)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 488, in _execute_command
    reraise(*sys.exc_info())
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 465, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 129, in acs_browse
    ssh_key_file)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 138, in _acs_browse_internal
    return k8s_browse(name, resource_group, disable_browser, ssh_key_file=ssh_key_file)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 152, in k8s_browse
    _k8s_browse_internal(name, acs_info, disable_browser, ssh_key_file)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 162, in _k8s_browse_internal
    _k8s_get_credentials_internal(name, acs_info, browse_path, ssh_key_file)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 727, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 49, in SecureCopy
    ssh.connect(host, username=user, pkey=pkey)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/paramiko/client.py", line 381, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/Users/joe/lib/azure-cli/lib/python2.7/site-packages/paramiko/client.py", line 622, in _auth
    raise saved_exception
PasswordRequiredException: Private key file is encrypted

```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by devigned** [comment]
@binderjoe #3612 should fix this.

**Comment by mayurid** [comment]
@brendanburns to review.

**Comment by mayurid** [comment]
@devigned : The PR is merged so closing the issue. Please reopen if you disagree
@lostintangent : Try latest docker image. It will be in upcoming release as well
