### ISSUE TITLE
'vm image list' Too many open files

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3649]
### Description

Running `$ az vm image list --all -otable` fails with `Too many open files` errors.

I wanted to create a Debian 7 VM and so needed the URN but didn't know what publisher it was under (turns out it's `credativ`) so I wanted to list **all** images.

The full command I ran: `$ az vm image list --all -otable | grep debian`.

This is possibly due to the logic we have to make concurrent API calls.

Error 1:
```
[Errno 24] Too many open files
Traceback (most recent call last):
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 210, in execute
    result = expanded_arg.func(params)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 488, in _execute_command
    reraise(*sys.exc_info())
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 465, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 211, in list_vm_images
    all_images = load_images_thru_services(publisher_name, offer, sku, image_location)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/_actions.py", line 67, in load_images_thru_services
    t.result()  # don't use the result but expose exceptions from the threads
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/_actions.py", line 50, in _load_images_from_publisher
    images = client.virtual_machine_images.list(location, publisher, o.name, s.name)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/mgmt/compute/compute/v2016_04_30_preview/operations/virtual_machine_images_operations.py", line 172, in list
    response = self._client.send(request, header_parameters, **operation_config)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 440, in wrap_socket
    rd = util.wait_for_read(sock, sock.gettimeout())
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/selectors.py", line 581, in DefaultSelector
    return _DEFAULT_SELECTOR()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/selectors.py", line 461, in __init__
    self._kqueue = select.kqueue()
IOError: [Errno 24] Too many open files
```

Error 2:
```
[('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
Traceback (most recent call last):
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 210, in execute
    result = expanded_arg.func(params)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 488, in _execute_command
    reraise(*sys.exc_info())
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 465, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 211, in list_vm_images
    all_images = load_images_thru_services(publisher_name, offer, sku, image_location)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/_actions.py", line 67, in load_images_thru_services
    t.result()  # don't use the result but expose exceptions from the threads
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/vm/_actions.py", line 42, in _load_images_from_publisher
    offers = client.virtual_machine_images.list_offers(location, publisher)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/azure/mgmt/compute/compute/v2016_04_30_preview/operations/virtual_machine_images_operations.py", line 235, in list_offers
    response = self._client.send(request, header_parameters, **operation_config)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 309, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 413, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/OpenSSL/SSL.py", line 669, in load_verify_locations
    _raise_current_error()
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
Traceback (most recent call last):
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/site.py", line 67, in <module>
    import os
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/Users/debekoe/lib/azure-cli/lib/python2.7/posixpath.py", line 15, in <module>
    import stat
ImportError: No module named stat
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
`curl/interactive script`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
$ az --version
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/debekoe/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  
`macOS Sierra Version 10.12.5`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
`bash`

**Comment by yugangw-msft** [comment]
The opened socket number exceeded the process limitation. It turned out Azure SDK creates a new session object for each SDK call, so underlined connections (and sockets) are not reused at all. There are tracking issue already at runtime, https://github.com/Azure/msrestazure-for-python/issues/6
For now I will shrink the threads from 40 down to 5. The perf loss is not that much(around 40~ seconds to get back 4300 images). At least this gets thing stabilized. Also I will output a warning if the `--all` is used w/o any other filters. `az image list` supports partial matching, so using server filter is highly suggested to get result faster.
