### ISSUE TITLE
 updated but still: gcc error, Failed building wheel for cryptography  &  Failed building wheel for scandir on Fedora

### ISSUE THREAD

**Issue by onyiny-ang** [Azure/azure-cli#3781]
### Description 
errors when installing azure-cli on Fedora 25

**Outline the issue here:**
Coming across these errors on Fedora despite updating and installing gcc libffi-devel python-devel openssl-devel prior to install.

some code omitted:

```
Collecting azure-mgmt-sql==0.5.1 (from azure-cli-sql->azure-cli)
  Downloading azure_mgmt_sql-0.5.1-py2.py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 1.5MB/s 
Collecting azure-common~=1.1.5 (from azure-batch==3.0.0->azure-cli-batch->azure-cli)
  Downloading azure_common-1.1.6-py2.py3-none-any.whl
Collecting azure-mgmt-nspkg>=2.0.0 (from azure-mgmt-keyvault==0.31.0->azure-cli-batch->azure-cli)
  Downloading azure_mgmt_nspkg-2.0.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->azure-cli-sf->azure-cli)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->azure-cli-sf->azure-cli)
  Downloading pbr-3.1.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 1.4MB/s 
Collecting cryptography>=1.1.0 (from adal>=0.4.3->azure-cli-sf->azure-cli)
  Downloading cryptography-1.9.tar.gz (409kB)
    100% |████████████████████████████████| 419kB 1.2MB/s 
Collecting python-dateutil>=2.1.0 (from adal>=0.4.3->azure-cli-sf->azure-cli)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.7MB/s 
Collecting PyJWT>=1.0.0 (from adal>=0.4.3->azure-cli-sf->azure-cli)
  Downloading PyJWT-1.5.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit->azure-cli-interactive->azure-cli)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting idna>=2.0.0; python_version <= "2.7" and extra == "secure" (from urllib3[secure]>=1.18->azure-cli-appservice->azure-cli)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 3.2MB/s 
Collecting certifi; extra == "secure" (from urllib3[secure]>=1.18->azure-cli-appservice->azure-cli)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 1.4MB/s 
Collecting ipaddress; python_version <= "2.7" and extra == "secure" (from urllib3[secure]>=1.18->azure-cli-appservice->azure-cli)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting futures (from azure-multiapi-storage==0.1.0->azure-cli-storage->azure-cli)
  Downloading futures-3.1.1-py2-none-any.whl
Collecting azure-mgmt-datalake-nspkg>=2.0.0 (from azure-mgmt-datalake-analytics==0.1.4->azure-cli-dla->azure-cli)
  Downloading azure_mgmt_datalake_nspkg-2.0.0-py2.py3-none-any.whl
Collecting pynacl>=1.0.1 (from paramiko->azure-cli-vm->azure-cli)
  Downloading PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl (539kB)
    100% |████████████████████████████████| 542kB 1.2MB/s 
Collecting bcrypt>=3.1.3 (from paramiko->azure-cli-vm->azure-cli)
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Collecting pyasn1>=0.1.7 (from paramiko->azure-cli-vm->azure-cli)
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 4.1MB/s 
Collecting monotonic; python_version == "2.6" or python_version == "2.7" or python_version == "3.0" or python_version == "3.1" or python_version == "3.2" (from humanfriendly->azure-cli-core->azure-cli)
  Downloading monotonic-1.3-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.5.0 (from msrest>=0.4.4->azure-cli-core->azure-cli)
  Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting enum34>=1.0.4; python_version < "3.4" (from msrest>=0.4.4->azure-cli-core->azure-cli)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting isodate>=0.5.4 (from msrest>=0.4.4->azure-cli-core->azure-cli)
  Downloading isodate-0.5.4.tar.gz
Collecting keyring>=5.6 (from msrestazure>=0.4.7->azure-cli-core->azure-cli)
  Downloading keyring-10.3.3-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->azure-cli-core->azure-cli)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.8MB/s 
Collecting cffi (from azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
  Downloading cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl (392kB)
    100% |████████████████████████████████| 399kB 1.7MB/s 
Collecting pathlib2 (from azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
  Downloading pathlib2-2.3.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1.0->adal>=0.4.3->azure-cli-sf->azure-cli)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 3.4MB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.5.0->msrest>=0.4.4->azure-cli-core->azure-cli)
  Downloading oauthlib-2.0.2.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 3.3MB/s 
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring>=5.6->msrestazure>=0.4.7->azure-cli-core->azure-cli)
  Downloading SecretStorage-2.3.1.tar.gz
Collecting pycparser (from cffi->azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 2.3MB/s 
Collecting scandir; python_version < "3.5" (from pathlib2->azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
  Downloading scandir-1.5.tar.gz
Building wheels for collected packages: applicationinsights, pyyaml, vsts-cd-manager, azure-datalake-store, sshtunnel, cryptography, isodate, oauthlib, secretstorage, pycparser, scandir
  Running setup.py bdist_wheel for applicationinsights ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/5d/00/c9/6cae03c0f0dd766574b08bee1a05f91f88d68e6990a1e4282b
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for vsts-cd-manager ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/6f/69/58/23fc80b987a15698bee59dcd3595eabb7f838396c0cc4cc0a6
  Running setup.py bdist_wheel for azure-datalake-store ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/ec/7d/03/2bcf90974682d841c8c2d58d17e2cf0a6e0765968acdf965ba
  Running setup.py bdist_wheel for sshtunnel ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/2f/92/75/a2db92ad2905bfc8663e980b8963625b4dd728fd64523f1da9
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /home/lt/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E8fKHZ/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpuLEM4Wpip-wheel- --python-tag cp27:
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  
      No working compiler found, or bogus compiler options
      passed to the compiler from Python's distutils module.
      See the error messages above.
      (If they are about -mno-fused-madd and you are on OS/X 10.8,
      see http://stackoverflow.com/questions/22313407/ .)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-E8fKHZ/cryptography/setup.py", line 321, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
      return self.obtain(req, installer)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
      return installer(requirement)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 445, in fetch_build_egg
      return cmd.easy_install(req)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1107, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /home/lt/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E8fKHZ/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  
      No working compiler found, or bogus compiler options
      passed to the compiler from Python's distutils module.
      See the error messages above.
      (If they are about -mno-fused-madd and you are on OS/X 10.8,
      see http://stackoverflow.com/questions/22313407/ .)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-E8fKHZ/cryptography/setup.py", line 321, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
      replace_conflicting=True,
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
      return self.obtain(req, installer)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
      return installer(requirement)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/dist.py", line 445, in fetch_build_egg
      return cmd.easy_install(req)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/home/lt/lib/azure-cli/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1107, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with 1
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for isodate ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/61/c0/d2/6b4a10c222ba9261ab9872a8f05d471652962284e8c677e5e7
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/84/98/7a/fba7268f61097bea6081cbe5480bc439b38975748ea7684fd5
  Running setup.py bdist_wheel for secretstorage ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/c7/58/c5/d09bed2136a4e88ed403f68c91f86293b46eecb719c00ef0d6
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /tmp/tmptMGoQa/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
  Running setup.py bdist_wheel for scandir ... error
  Complete output from command /home/lt/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E8fKHZ/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpMV3xD1pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying scandir.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_scandir' extension
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for scandir
  Running setup.py clean for scandir
Successfully built applicationinsights pyyaml vsts-cd-manager azure-datalake-store sshtunnel isodate oauthlib secretstorage pycparser
Failed to build cryptography scandir
Installing collected packages: azure-nspkg, azure-common, idna, six, asn1crypto, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, certifi, urllib3, chardet, requests, oauthlib, requests-oauthlib, isodate, msrest, secretstorage, keyring, python-dateutil, PyJWT, adal, msrestazure, azure-batch, azure-cli-nspkg, azure-cli-command-modules-nspkg, azure-mgmt-nspkg, azure-mgmt-keyvault, monotonic, humanfriendly, pyyaml, applicationinsights, tabulate, pygments, colorama, argcomplete, jmespath, azure-cli-core, azure-mgmt-batch, azure-cli-batch, azure-servicefabric, funcsigs, pbr, mock, azure-cli-sf, azure-mgmt-authorization, azure-mgmt-resource, azure-cli-resource, azure-keyvault, azure-cli-keyvault, wcwidth, prompt-toolkit, azure-cli-interactive, azure-mgmt-cdn, azure-cli-cdn, whoosh, azure-cli-find, azure-mgmt-web, vsts-cd-manager, xmltodict, azure-cli-appservice, futures, azure-multiapi-storage, azure-mgmt-storage, azure-cli-storage, azure-mgmt-iothub, azure-cli-iot, azure-mgmt-datalake-nspkg, azure-mgmt-datalake-analytics, azure-mgmt-datalake-store, azure-cli-dla, azure-mgmt-network, pynacl, bcrypt, pyasn1, paramiko, azure-mgmt-compute, azure-cli-vm, azure-cli-profile, azure-cli-cloud, azure-mgmt-cognitiveservices, azure-cli-cognitiveservices, scandir, pathlib2, azure-datalake-store, azure-cli-dls, azure-mgmt-containerregistry, azure-cli-acr, azure-mgmt-redis, azure-cli-redis, azure-cli-component, azure-mgmt-rdbms, azure-cli-rdbms, azure-mgmt-consumption, azure-cli-consumption, azure-graphrbac, pytz, azure-cli-role, azure-mgmt-monitor, azure-monitor, azure-cli-monitor, pydocumentdb, azure-mgmt-documentdb, azure-cli-cosmosdb, azure-mgmt-trafficmanager, azure-mgmt-dns, azure-cli-network, azure-mgmt-devtestlabs, azure-cli-lab, azure-mgmt-billing, azure-cli-billing, azure-cli-feedback, sshtunnel, scp, azure-cli-acs, azure-mgmt-sql, azure-cli-sql, azure-cli-configure, azure-cli
  Running setup.py install for cryptography ... error
    Complete output from command /home/lt/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E8fKHZ/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IUUOY4-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/lt/lib/azure-cli/include/site/python2.7/cryptography:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-2.7/cryptography
    creating build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/lt/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-E8fKHZ/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IUUOY4-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/lt/lib/azure-cli/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-E8fKHZ/cryptography/
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_Wl50", line 370, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_Wl50", line 356, in main
    install_cli(install_dir, tmp_dir)
  File "/tmp/azure_cli_install_tmp_Wl50", line 140, in install_cli
    exec_command(cmd)
  File "/tmp/azure_cli_install_tmp_Wl50", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/lt/lib/azure-cli/bin/pip', 'install', '--cache-dir', '/tmp/tmptMGoQa', 'azure-cli', '--upgrade']' returned non-zero exit status 1

```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: none successfully

**OS Version:** What OS and version are you using?  
Answer here: Fedora 25

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by onyiny-ang** [comment]
This is a red hat issue
running
```sudo dnf install redhat-rpm-config```
solved the problem.
