### ISSUE TITLE
sql server create - Consistently too many 504 error responses

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#3783]
### Description
I consistently see failures with the `az sql server create` command. I run dozens of az cli commands throughout a day, but this one command is consistently the most failure prone. I have contemplated running retry logic on it but figured would bubble this up as an issue.

**To Repro:**
(in quick succession - time appears to be relevant here)
1. Create resource group `az group create -n $rsgroup -l $region`
1. Create SQL server `az sql server create -n ${sqlsrvname} -g {$rsgroup} -l ${region} -u ${sqlaccnt} -p ${sqlpass}` attached to that resource group
1. Delete resource group `az group delete --name $rsgroup --yes`
1. Create resource group
1. Create SQL server `az sql server create -n ${sqlsrvname} -g {$rsgroup} -l ${region} -u ${sqlaccnt} -p ${sqlpass}` attached to that resource group
1. Observe failure to create, with following error:
```
ERROR: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/${subscriptionID}/resourceGroups/${resourcegroup}/providers/Microsoft.Sql/servers/sql-${resourcegroup}?api-version=2014-04-01 (Caused by ResponseError('too many 504 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/${subscriptionID}/resourceGroups/${resourcegroup}/providers/Microsoft.Sql/servers/sql-${resourcegroup}?api-version=2014-04-01 (Caused by ResponseError('too many 504 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/${subscriptionID}/resourceGroups/${resourcegroup}/providers/Microsoft.Sql/servers/sql-${resourcegroup}?api-version=2014-04-01 (Caused by ResponseError('too many 504 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 352, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 561, in _execute_command
    raise client_exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 551, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 528, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/sql/operations/servers_operations.py", line 152, in create_or_update
    request, header_parameters, body_content, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 206, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 180, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/${subscriptionID}/resourceGroups/${resourcegroup}/providers/Microsoft.Sql/servers/sql-${resourcegroup}?api-version=2014-04-01 (Caused by ResponseError('too many 504 error responses',))
```

**Workaround:**
1. Delete SQL server (if exists)
1. Wait a period of time (~5 minutes?)
1. Attempt to recreate. Sometimes works, other times have to repeat.

---

### Environment summary

**Install Method:** How did you install the CLI?  
`apt-get`

**CLI Version:** What version of the CLI and modules are installed?
```
azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.8)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Linux) 3.6.1 (default, Jun 14 2017, 11:33:22)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'
```

**OS Version:** What OS and version are you using?  
`Ubuntu 16.04.2 LTS`

**Shell Type:** What shell are you using?
`bash`

**Comment by jaredmoo** [comment]
Thanks for the report @iyerusad . Creating server can take ~15 seconds longer since a few weeks ago, and this does occasionally cause create server to timeout. This will be fixed for Azure CLI with #3717 - the new API uses async polling to avoid timeout.

**Comment by iyerusad** [comment]
@jaredmoo Thank you. I see the experience is now improved, SQL is no longer "timing out"/504ing out and my runs of this command are now more consistent in deleting and creating SQL instances. Been using this piece a bit today and feel confident enough to close this issue out.

**Comment by jaredmoo** [comment]
Great to hear, thanks for the confirmation!
