### ISSUE TITLE
Telemetry errors in CI

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3786]
### Description
**Outline the issue here:**

```
Telemetry upload begins
Traceback (most recent call last):
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-core/azure/cli/core/telemetry_upload.py", line 68, in <module>
    upload(sys.argv[1])
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-core/azure/cli/core/decorators.py", line 86, in _wrapped_func
    raise ex
TypeError: can't multiply sequence by non-int of type 'str'
```

**Comment by troydai** [comment]
Can you provide a link to the failed build?

**Comment by JasonRShaver** [comment]
no repro
