### ISSUE TITLE
KeyError: 'status value'

### ISSUE THREAD

**Issue by jsilberm** [Azure/azure-cli#3787]
### Description
**Outline the issue here:**

+ ./acs-engine generate dcos.json
INFO[0000] Generating assets...
wrote _output/jssportworx/apimodel.json
wrote _output/jssportworx/azuredeploy.json
wrote _output/jssportworx/azuredeploy.parameters.json
+ az group deployment create --name jssportworx --resource-group jssportworx --template-file ./_output/jssportworx/azuredeploy.json --parameters @./_output/jssportworx/azuredeploy.parameters.json
'status value'
Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 352, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 551, in _execute_command
    reraise(*sys.exc_info())
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 538, in _execute_command
    return LongRunningOperation('Starting {}'.format(name))(result)
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 220, in __call__
    self._template_progress(correlation_id)
  File "/root/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 198, in _template_progress
    if deploy_values['status value'] != 'Started':
KeyError: 'status value'
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
[root@jeff-dev acs-engine]# az --version
azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.9)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Linux) 2.7.5 (default, Aug  2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

Python location '/root/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here:
Linux jeff-dev 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
RHEL 7.2

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by tjprescott** [comment]
Thank for you for the report. This has been fixed by PR #3744 and will be available in the next release.
