### ISSUE TITLE
Regression: Latest az cli version 2.0.8 deployment fails with stack trace

### ISSUE THREAD

**Issue by anhowe** [Azure/azure-cli#3798]
### Description
**Outline the issue here:**

Latest az cli version 2.0.8 fails with the following stack trace:

az group deployment create --name "anhowe0621b" --resource-group "anhowe0621b" --template-file "_output/anhowe0621b/azuredeploy.json" --parameters "_output/anhowe0621b/azuredeploy.parameters.json"
'status value'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 352, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 551, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 538, in _execute_command
    return LongRunningOperation('Starting {}'.format(name))(result)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 220, in __call__
    self._template_progress(correlation_id)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 198, in _template_progress
    if deploy_values['status value'] != 'Started':
KeyError: 'status value'

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip install 

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: We tried to specify 2.0.7, but that version disappeared 15 hours ago, and it installed 2.0.8.  Since then we have seen stack trace

**OS Version:** What OS and version are you using?  
Answer here: working in Docker image "buildpack-deps:xenial"

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

Can you restore the old 2.0.7 version while you fix this?

**Comment by squillace** [comment]
@yugangw-msft @johanste FYI

**Comment by tjprescott** [comment]
Thank for you for the report. This has been fixed by PR #3744 and will be available in the next release.
