### ISSUE TITLE
Latest (0.2.10) Bundled installer does not work

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#3800]
### Description
**Outline the issue here:**

* 0.2.9 bundle installs fine
* 0.2.10 bundle fails to install due to error(s)
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: bundled installer

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 0.2.10 bundle

**OS Version:** What OS and version are you using?  
Answer here: Linux (docker container with `FROM buildpack-deps:xenial`.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---
Result from trying to install the 0.2.10 bundle:

```
...
Collecting isodate>=0.5.4 (from msrest>=0.4.4->azure-cli-core->azure-cli)
Collecting keyring>=5.6 (from msrestazure>=0.4.7->azure-cli-core->azure-cli)
Collecting monotonic; python_version == "2.6" or python_version == "2.7" or python_version == "3.0" or python_version == "3.1" or python_version == "3.2" (from humanfriendly->azure-cli-core->azure-cli)
Collecting pycparser (from cffi->azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
Collecting scandir; python_version < "3.5" (from pathlib2->azure-datalake-store==0.0.9->azure-cli-dls->azure-cli)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1.0->adal>=0.4.3->azure-cli-sf->azure-cli)
Collecting packaging (from cryptography>=1.1.0->adal>=0.4.3->azure-cli-sf->azure-cli)
   Could not find a version that satisfies the requirement packaging (from cryptography>=1.1.0->adal>=0.4.3->azure-cli-sf->azure-cli) (from versions: )
No matching distribution found for packaging (from cryptography>=1.1.0->adal>=0.4.3->azure-cli-sf->azure-cli)
Traceback (most recent call last):
  File "azure-cli_bundle_0.2.10/installer", line 210, in <module>
    args.override_native_check)
  File "azure-cli_bundle_0.2.10/installer", line 175, in main
    install_cli(tmp_dir, install_dir)
  File "azure-cli_bundle_0.2.10/installer", line 97, in install_cli
    _exec_command(cmd)
  File "azure-cli_bundle_0.2.10/installer", line 50, in _exec_command
    subprocess.check_call(command_list, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by mayurid** [comment]
@derekbekoe to take a look

**Comment by derekbekoe** [comment]
@colemickens PR has been created.
I have also published https://azurecliprod.blob.core.windows.net/bundled/azure-cli_bundle_0.2.10-1.tar.gz.
