### ISSUE TITLE
azure-cli - malfunctioning on Suse Linux 12

### ISSUE THREAD

**Issue by joefromct** [Azure/azure-cli#3805]
### Description
**Outline the issue here:**

`azure-cli` presents errors on the `login` sub command on Suse Linux, SLES 12.

The install (from curl script) completes without error, however I am however presented with this warning on install:

```` bash 
-- One or more of the following native dependencies are not currently installed and may be required.
"zypper refresh && zypper --non-interactive install gcc libffi-devel python-devel openssl-devel"

===> Missing native dependencies. Attempt to continue anyway? (y/N): 
````

However, we have run that `zypper` command previously and can confirm that each of the packages are installed: 

```` bash
me@my-host:~> zypper search gcc libffi-devel python-devel openssl-devel
Loading repository data...
Reading installed packages...

S | Name              | Summary                                                           | Type   
--+-------------------+-------------------------------------------------------------------+--------
i | gcc               | The system GNU C Compiler                                         | package
i | gcc-c++           | The system GNU C++ Compiler                                       | package
i | gcc48             | The GNU C Compiler and Support Files                              | package
i | gcc48-c++         | The GNU C++ Compiler                                              | package
i | libffi-devel-gcc5 | Foreign Function Interface library development files              | package
i | libgcc43-32bit    | C compiler runtime library                                        | package
i | libgcc_s1         | C compiler runtime library                                        | package
i | libgcc_s1-32bit   | C compiler runtime library                                        | package
i | libopenssl-devel  | Include Files and Libraries mandatory for Development             | package
i | python-devel      | Include Files and Libraries Mandatory for Building Python Modules | package
me@my-host:~> 

````

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

A number of different ways, however the base line way was with the installer script and curl command.

`curl -L https://aka.ms/InstallAzureCli | bash`

I've also tried with pip, and even some downloaded releases from this git repo. 

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

````
azure-cli (2.0.8)
acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.9)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Linux) 2.7.12 (default, May  8 2017, 16:18:14) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]]
````

**OS Version:** What OS and version are you using?  
Answer here:
````
me@my-host:~> cat /etc/os-release 
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"
me@my-host:~> 
````
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

```` bash
me@my-host:~> echo $0
-bash
me@my-host:~> 
````

**Comment by derekbekoe** [comment]
@joefromct Sometimes one or more of the dependencies may be already installed through some other dependency (transitive dep.). So the message in the install script is a warning that may not always apply and if the install succeeds, you should be good.

> azure-cli presents errors on the login sub command on Suse Linux, SLES 12.

What was the error exactly with `az login`?

**Comment by joefromct** [comment]
Hi, thanks for the quick reply.

Below is the error.  Also, things like `az help` and `az configure` work without issue.

```` bash
me@my-host:~/bin> ./az login 
[]
Traceback (most recent call last):
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 352, in __call__
    return self.handler(*args, **kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 551, in _execute_command
    reraise(*sys.exc_info())
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 528, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 102, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 125, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 423, in find_through_interactive_flow
    code = context.acquire_user_code(resource, _CLIENT_ID)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/adal/authentication_context.py", line 244, in acquire_user_code
    return code_request.get_user_code_info(language)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/adal/code_request.py", line 66, in get_user_code_info
    return self._get_user_code_info(oauth_parameters)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/adal/code_request.py", line 46, in _get_user_code_info
    return client.get_user_code_info(oauth_parameters)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/adal/oauth2_client.py", line 293, in get_user_code_info
    verify=self._call_context.get('verify_ssl', None))
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 250, in create_urllib3_context
    context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 376, in __init__
    self._ctx = OpenSSL.SSL.Context(self.protocol)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/OpenSSL/SSL.py", line 614, in __init__
    _openssl_assert(res == 1)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/OpenSSL/_util.py", line 67, in openssl_assert
    exception_from_error_queue(error)
  File "/home/me/lib/azure-cli/lib/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: []
me@my-host:~/bin> 
````

**Comment by derekbekoe** [comment]
I don't see an immediate solution and haven't seen this before.
Can you provide the output of:
`/home/me/lib/azure-cli/bin/pip freeze`

**Comment by joefromct** [comment]
I got this to work.

I noticed that `openssl` was built on gcc 4.3, and python was built on 4.8 and that seemed as though it should work, however it was worth looking into.

This is what i did to fix the issue:

- I recompiled a new python (python 3.6) with the same version of `gcc` that was used for `python-devel` and `openssh-devel`.  I did this with a `make altinstall` like so (because i don't have root):

```` bash
me@my-host:~/joes_python/src/Python-3.6.1> pwd
/home/me/joes_python/src/Python-3.6.1
me@my-host:~/joes_python/src/Python-3.6.1> ./configure && make altinstall prefix=/home/me/joes_python exec-prefix=/home/me/joes_python  
```` 

Once this finished I had newly compiled python3.6 binaries in `~/joes_python/bin`.

----

In order to see if `azure-cli` worked with the newly compiled python, i did the following:

1. create a `virtualenv` pointing to my newly created python:
````
me@my-host:~/joes_az> pwd
/home/me/joes_az
me@my-host:~/joes_az> virtualenv -p /home/me/joes_python/bin/python3.6 ~/joes_az/venv
```` 
2. activate this venv:
````
me@my-host:~/joes_az> source venv/bin/activate
(venv) me@my-host:~/joes_az> 
````
3. pip install `azure-cli`:
```` bash
(venv) me@my-host:~/joes_az> python --version ; pip --version
Python 3.6.1
pip 9.0.1 from /home/me/joes_az/venv/lib/python3.6/site-packages (python 3.6)
(venv) me@my-host:~/joes_az> 
(venv) me@my-host:~/joes_az> pip install azure-cli 
#.... clip .... 
````
4. After that, i have a new binary with for `az` in the path below, and i can see login works:
```` bash
(venv) me@my-host:~/joes_az> ./venv/bin/az login 
To sign in, use a web browser to open the page https://the-web-site/loginpage and enter the code *******  to authenticate.

````

----

So, the issue didn't have anything to do with suse.  With this info i should be able to help my sys admin clean up the system and get me a working install.  Thanks for your help, 

@derekbekoe let me know if you still want a `pip freeze` but i think I am in good shape for the time being.
