### ISSUE TITLE
[Test] Cannot playback or records tests on Python 2

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3883]
Created a new Python 2 virtual environment and tried playing back a test:

`nosetests azure.cli.command_modules.resource.tests.test_resource.DeploymentTest -c nose.cfg`

Output:
```
----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
```

This works on Python 3 but not Python 2 (anymore).

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.9+dev)

acr (2.0.7+dev)
acs (2.0.9+dev)
appservice (0.1.9+dev)
batch (3.0.2+dev)
billing (0.1.2+dev)
cdn (0.0.5+dev)
cloud (2.0.5+dev)
cognitiveservices (0.1.5+dev)
component (2.0.6+dev)
configure (2.0.9+dev)
consumption (0.1.2+dev)
core (2.0.10+dev)
cosmosdb (0.1.9+dev)
dla (0.0.9+dev)
dls (0.0.9+dev)
feedback (2.0.5+dev)
find (0.2.5+dev)
interactive (0.3.5+dev)
iot (0.1.8+dev)
keyvault (2.0.7+dev)
lab (0.0.7+dev)
monitor (0.0.7+dev)
network (2.0.9+dev)
nspkg (3.0.0+dev)
profile (2.0.7+dev)
rdbms (0.0.4+dev)
redis (0.2.6+dev)
resource (2.0.9+dev)
role (2.0.7+dev)
sf (1.0.4+dev)
sql (2.0.6+dev)
storage (2.0.9+dev)
taskhelp (0.1.4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.9+dev)

Python (Windows) 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by troydai** [comment]
does this form work for you?
```
python -m unittest <module>
```

**Comment by tjprescott** [comment]
No because I want to play back a single test case, not the entire module.  If I wanted to play the module, I would just run `run_tests --module <module>`

**Comment by troydai** [comment]
More traces
```
09:09 $ nosetests azure.cli.command_modules.resource.tests.test_resource.DeploymentTest.test_group_deployment -v
Failure: TypeError (None is a built-in class) ... ERROR
Failure: TypeError (issubclass() arg 1 must be a class) ... ERROR
Failure: TypeError (issubclass() arg 1 must be a class) ... ERROR

======================================================================
ERROR: Failure: TypeError (None is a built-in class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 570, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 494, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/Users/troydai/code/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/base.py", line 59, in __init__
    recording_dir=recording_dir or find_recording_dir(inspect.getfile(self.__class__)),
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 407, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: None is a built-in class
-------------------- >> begin captured logging << --------------------
az.azure.cli.core.application: DEBUG: Registered application event handler 'GlobalParser.Created' at <function _register_builtin_arguments at 0x10c77f7d0>
az.azure.cli.core.application: DEBUG: Registered application event handler 'CommandParser.Parsed' at <bound method Application._handle_builtin_arguments of <azure.cli.core.application.Application object at 0x10c77aa50>>
az.azure.cli.core.application: DEBUG: Registered application event handler 'GlobalParser.Created' at <function _register_global_parameter at 0x10c6d36e0>
az.azure.cli.core.application: DEBUG: Registered application event handler 'CommandParser.Parsed' at <function handle_query_parameter at 0x10c77fc08>
az.azure.cli.core.application: DEBUG: Registered application event handler 'Application.TransformResults' at <function _resource_group_transform at 0x10c6d39b0>
az.azure.cli.core.application: DEBUG: Registered application event handler 'Application.TransformResults' at <function _x509_from_base64_to_hex_transform at 0x10c6d3a28>
az.azure.cli.core.application: DEBUG: Application event 'GlobalParser.Created' with event data {'global_group': <argparse._ArgumentGroup object at 0x10c77ad10>}
az.azure.cli.core._profile: DEBUG: Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: TypeError (issubclass() arg 1 must be a class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 576, in _makeTest
    if issubclass(parent, unittest.TestCase):
TypeError: issubclass() arg 1 must be a class

======================================================================
ERROR: Failure: TypeError (issubclass() arg 1 must be a class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/troydai/code/azure-cli/env/lib/python2.7/site-packages/nose/loader.py", line 576, in _makeTest
    if issubclass(parent, unittest.TestCase):
TypeError: issubclass() arg 1 must be a class

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
```

**Comment by troydai** [comment]
Sorry. Didn't make it clear. I meant:
```
python -m unittest azure.cli.command_modules.resource.tests.test_resource.DeploymentTest.test_group_deployment
```

**Comment by troydai** [comment]
I'll take a look the nosetest abnormal.

**Comment by tjprescott** [comment]
That works, sort of.  The problem is if I don't run it with nosetests I don't get the debugging output when it fails.  On Python3 I get at least something, but on Python 2, not so much.

**Comment by tjprescott** [comment]
Example (I introduced a typo in the last command):

Python 3:
```
:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\azure_devtools\scenario_tests\preparers.py:54: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, _, kw, _ = inspect.getargspec(fn)  # pylint: disable=deprecated-method
az group: error: argument subcommand: invalid choice: deplooyment
usage: az group [-h]
                {create,deployment,delete,update,export,show,exists,list,wait}
                ...
E
======================================================================
ERROR: test_group_deployment (azure.cli.command_modules.resource.tests.test_resource.DeploymentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1816, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 2267, in _get_values
    self._check_value(action, value[0])
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\parser.py", line 188, in _check_value
    raise argparse.ArgumentError(action, msg)
argparse.ArgumentError: argument subcommand: invalid choice: deplooyment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\trpresco\Documents\github\azure-cli\env\lib\site-packages\azure_devtools\scenario_tests\preparers.py", line 60, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "c:\users\trpresco\documents\github\azure-cli\src\command_modules\azure-cli-resource\azure\cli\command_modules\resource\tests\test_resource.py", line 337, in test_group_deployment
    JCheck('[0].resourceGroup', resource_group)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 76, in cmd
    return execute(command, expect_failure=expect_failure).assert_with_checks(checks)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 89, in __init__
    self._in_process_execute(command)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 141, in _in_process_execute
    self.exit_code = cli_main(shlex.split(command), file=output_buffer) or 0
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\application.py", line 183, in execute
    args = self.parser.parse_args(argv)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 1765, in parse_known_args
    self.error(str(err))
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\parser.py", line 170, in error
    self.exit(2)
  File "C:\Users\trpresco\AppData\Local\Programs\Python\Python35-32\lib\argparse.py", line 2372, in exit
    _sys.exit(status)
SystemExit: 2

----------------------------------------------------------------------
Ran 1 test in 3.925s

FAILED (errors=1)
```

Python 2
```
az group: error: argument subcommand: invalid choice: deplooyment
usage: az group [-h]
                {create,deployment,delete,export,show,update,wait,exists,list}
                ...
```

If I ran this with nosetests I'd get the full debugging results as well as the stacktrace.

**Comment by troydai** [comment]
`inspect.getfile(self.__class__)` is the problem as far as I can see.

**Comment by tjprescott** [comment]
If #3885 is implemented, this becomes moot.  We should have an interface for running select tests so that running them isn't so dependent on these implementation or project structure details.

**Comment by troydai** [comment]
Good suggestion and will do.

**Comment by troydai** [comment]
This is the tested solution: `python -m unittest azure.cli.command_modules.resource.tests.test_resource.DeploymentTest.test_group_deployment`

I'd rather not to wrestle with nose's issue with Python 2 but move on to implement #388..

**Comment by troydai** [comment]
I'll see if I can fix this in limited timeframe.

**Comment by tjprescott** [comment]
I agree with focusing on #3885.  The whole point is one syntax for running a specific test that works on all platforms and Python versions.  If I had that I wouldn't care about using this long syntax.
