### ISSUE TITLE
Problems with 'AzureCloud' in non-concurrent scenarios

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#3897]
### Description
**Outline the issue here:** We have a Jenkins job. It never runs in parallel. Each instance starts up in a fresh docker container with no `~/.azure` and each then has a non-interactive login with Service Principal creds.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Used a bundled installer

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: n/a (using 0.2.9 of the bundled installer, so whatever it contains)

**OS Version:** What OS and version are you using?  
Answer here: (docker) `buildpack-deps:xenial`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `bash`

# Failure 1

```
ERROR: The cloud 'AzureCloud' is not registered.
Traceback (most recent call last):
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 229, in deploy_arm_template
    deployment_name, parameters, mode, no_wait=no_wait)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 333, in _deploy_arm_template_core
    smc = get_mgmt_service_client(ResourceType.MGMT_RESOURCE_RESOURCES)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/client_factory.py", line 32, in get_mgmt_service_client
    api_version=api_version, **kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/client_factory.py", line 66, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 314, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 291, in get_subscription
    subscriptions = self.load_cached_subscriptions()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 276, in load_cached_subscriptions
    active_cloud = get_active_cloud()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 283, in get_active_cloud
    return get_cloud(get_active_cloud_name())
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 278, in get_cloud
    raise CloudNotRegisteredException(cloud_name)
CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.
```

# Failure 2

```
Error [create_resource_group:x-managed-identity-kubernetes-westcentralus-169-0-0] exit status 1
Output: ERROR: The cloud 'AzureCloud' is already registered.
Traceback (most recent call last):
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/resource/custom.py", line 66, in create_resource_group
    rcf = _resource_client_factory()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/resource/_client_factory.py", line 10, in _resource_client_factory
    return get_mgmt_service_client(ResourceType.MGMT_RESOURCE_RESOURCES)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/client_factory.py", line 32, in get_mgmt_service_client
    api_version=api_version, **kwargs)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/client_factory.py", line 66, in _get_mgmt_service_client
    cred, subscription_id, _ = profile.get_login_credentials(subscription_id=subscription_id)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 314, in get_login_credentials
    account = self.get_subscription(subscription_id)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 291, in get_subscription
    subscriptions = self.load_cached_subscriptions()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 276, in load_cached_subscriptions
    active_cloud = get_active_cloud()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 283, in get_active_cloud
    return get_cloud(get_active_cloud_name())
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 276, in get_cloud
    cloud = _get_cloud(cloud_name)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 224, in _get_cloud
    return next((x for x in get_clouds() if x.name == cloud_name), None)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 243, in get_clouds
    init_known_clouds()
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 238, in init_known_clouds
    _save_cloud(c, overwrite=force)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 350, in _save_cloud
    raise CloudAlreadyRegisteredException(cloud.name)
CloudAlreadyRegisteredException: The cloud 'AzureCloud' is already registered.
```

**Comment by colemickens** [comment]
(Similar symptoms as in #3617)

**Comment by colemickens** [comment]
Just hit this in another job, this time with `AzureChinaCloud`.

**Comment by derekbekoe** [comment]
@colemickens How frequently does this happen?

**Comment by colemickens** [comment]
I've had nearly 300 runs and 3 of the failures have been due to CLI.

Today I saw this:

```
ERROR: Error loading command module 'acr'
ERROR: Error loading command module 'acs'
ERROR: Error loading command module 'appservice'
ERROR: Error loading command module 'cdn'
ERROR: Error loading command module 'dla'
ERROR: Error loading command module 'dls'
ERROR: Error loading command module 'iot'
ERROR: Error loading command module 'keyvault'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'monitor'
ERROR: Error loading command module 'network'
ERROR: Error loading command module 'rdbms'
ERROR: Error loading command module 'redis'
ERROR: Error loading command module 'resource'
ERROR: Error loading command module 'sf'
ERROR: Error loading command module 'sql'
ERROR: Error loading command module 'storage'
ERROR: Error loading command module 'vm'
ERROR: az: error: argument _command_package: invalid choice: group
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {interactive,ad,feedback,cognitiveservices,cloud,account,batch,component,logout,role,login,cosmosdb,find,configure}
          ...
```

We're on the latest released bundle.
