### ISSUE TITLE
az acs kubernetes get-credentials does not work behind socks proxy

### ISSUE THREAD

**Issue by grawcho** [Azure/azure-cli#3947]
### Description
**trying to get credentials into .kube/config fails on timeout when ssh runs behind a socks proxy using .ssh/config:**

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: CLI Bash for RHEL 7 (on Fedora)

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.9)
acr (2.0.7)
acs (2.0.9)
appservice (0.1.9)
batch (3.0.2)
billing (0.1.2)
cdn (0.0.5)
cloud (2.0.5)
cognitiveservices (0.1.5)
command-modules-nspkg (2.0.0)
component (2.0.6)
configure (2.0.9)
consumption (0.1.2)
core (2.0.10)
cosmosdb (0.1.9)
dla (0.0.9)
dls (0.0.9)
feedback (2.0.5)
find (0.2.5)
interactive (0.3.5)
iot (0.1.8)
keyvault (2.0.7)
lab (0.0.7)
monitor (0.0.7)
network (2.0.9)
nspkg (3.0.0)
profile (2.0.7)
rdbms (0.0.4)
redis (0.2.6)
resource (2.0.9)
role (2.0.7)
sf (1.0.4)
sql (2.0.6)
storage (2.0.9)
vm (2.0.9)

Python (Linux) 2.7.13 (default, May 10 2017, 20:04:36) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

Python location '/opt/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: Linux Fedora 24

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

** console output: **

```bash
[Errno 110] Connection timed out
Traceback (most recent call last):
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 346, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 545, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 522, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 705, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 726, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 62, in secure_copy
    ssh.connect(host, username=user, pkey=pkey)
  File "/opt/azure-cli/lib/python2.7/site-packages/paramiko/client.py", line 310, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/opt/azure-cli/lib/python2.7/site-packages/paramiko/util.py", line 276, in retry_on_signal
    return function()
  File "/opt/azure-cli/lib/python2.7/site-packages/paramiko/client.py", line 310, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 110] Connection timed out
```

**Comment by rjtsdl** [comment]
@grawcho can you close this. I think you change is merged.

**Comment by grawcho** [comment]
thanks for accepting my changes, this closes the issue.
