### ISSUE TITLE
Misleading error message when resetting SSH key on a VM

### ISSUE THREAD

**Issue by agolomoodysaada** [Azure/azure-cli#3995]
### Description

The following command works on all my VMs except for one particular one show below.
NOTE: 
`az` is an alias to `docker run --rm -v /Users/$(whoami):/root -it azuresdk/azure-cli-python az`
```sh
$ az vm user update -u moody -g myGroup -n myVM --ssh-key-value "$(cat ~/.ssh/id_rsa.pub)"=""
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 619, in set_user
    return _set_linux_user(vm, resource_group_name, username, password, ssh_key_value, no_wait)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 676, in _set_linux_user
    protected_settings)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 727, in _update_linux_access_extension
    _ACCESS_EXT_HANDLER_NAME)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 751, in _get_extension_instance_name
    if x.type.lower() == full_type_name.lower()), None)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/vm/custom.py", line 751, in <genexpr>
    if x.type.lower() == full_type_name.lower()), None)
AttributeError: 'NoneType' object has no attribute 'lower'
```

I tried checking the Azure console and found the following message on this particular VM when resetting SSH key
```
The VM agent is either unavailable, or not installed, which may prevent VMAccess from running.
```

Screenshot
![screen shot 2017-07-10 at 2 21 44 pm](https://user-images.githubusercontent.com/29459870/28033152-250c7f6c-657b-11e7-8098-eede273c66ef.png)

_It would be a lot more useful to see that error in the CLI as well instead of a python dump._

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.10+dev)

acr (2.0.8+dev)
acs (2.0.10+dev)
appservice (0.1.10+dev)
batch (3.0.3+dev)
billing (0.1.3+dev)
cdn (0.0.6+dev)
cloud (2.0.6+dev)
cognitiveservices (0.1.6+dev)
command-modules-nspkg (2.0.1+dev)
component (2.0.6+dev)
configure (2.0.10+dev)
consumption (0.1.3+dev)
core (2.0.11+dev)
cosmosdb (0.1.10+dev)
dla (0.0.10+dev)
dls (0.0.10+dev)
feedback (2.0.6+dev)
find (0.2.6+dev)
interactive (0.3.6+dev)
iot (0.1.9+dev)
keyvault (2.0.8+dev)
lab (0.0.8+dev)
monitor (0.0.8+dev)
network (2.0.10+dev)
nspkg (3.0.1+dev)
profile (2.0.8+dev)
rdbms (0.0.5+dev)
redis (0.2.7+dev)
resource (2.0.10+dev)
role (2.0.8+dev)
sf (1.0.5+dev)
sql (2.0.7+dev)
storage (2.0.10+dev)
taskhelp (0.1.5+dev)
vm (2.0.10+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.5 (16F2104)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by agolomoodysaada** [comment]
Awesome. Thanks!
