### ISSUE TITLE
[Service Fabric] Application Upload does not honor certificat settings

### ISSUE THREAD

**Issue by bertschneider** [Azure/azure-cli#4048]
### Description
I am using the Azure CLI 2.0 on MacOS to connect to a secured Azure Service Fabric Cluster (self signed certificate). The connection and some commands work just fine but the `application upload` command seems to not honor the certificate settings from the `cluster selection`.

Is there a way to add the `—no-verify` flag to other commands or to add the certificate to the python certificate store?

```shell

————————
Cluster select
————————
$ az sf cluster select --endpoint https://XXX.cloudapp.azure.com:19080 --no-verify --key key --cert crt

————————
Successful commands
————————
$ az sf cluster manifest
/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{
  "manifest": „<ClusterManifest …..
}

$ az sf cluster health
/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{
  "aggregatedHealthState": "Ok",
  "applicationHealthStates": [
    {
      "aggregatedHealthState": "Ok",
      "name": "fabric:/System"
    }
  ],….
}

$ az sf application list
/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{
  "continuationToken": "",
  "items": []
}

————————
Unsuccessful command
————————
$ az sf application upload --path . --show-progress --debug
Command arguments ['sf', 'application', 'upload', '--path', '.', '--show-progress']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x10bb708c0>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x10bb708c0>
Successfully loaded command table from module 'sf'.
Application event 'CommandTable.Loaded' with event data {'command_table': {'sf application upload': <azure.cli.core.commands.CliCommand object at 0x10bb48e50>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'sf application upload': <azure.cli.core.commands.CliCommand object at 0x10bb48e50>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['sf', 'application', 'upload', '--path', '.', '--show-progress']}
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='sf', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az sf application upload', usage=None, description='Copies a Service Fabric application package to the image store.  The cmdlet copies a Service Fabric application package to the image store. After copying the application package, use the sf application provision cmdlet to register the application type.  Can option [...]
urllib3.connectionpool : Starting new HTTPS connection (1): XXX.cloudapp.azure.com
("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
Traceback (most recent call last):
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/sf/custom.py", line 238, in sf_upload_app
    verify=ca_cert)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/norbert/lib/azure-cli/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Via `curl` with the default settings/paths

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```shell
$ az --version

azure-cli (2.0.10)
acr (2.0.8)
acs (2.0.10)
appservice (0.1.10)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.6)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
core (2.0.11)
cosmosdb (0.1.10)
dla (0.0.10)
dls (0.0.10)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.6)
iot (0.1.9)
keyvault (2.0.8)
lab (0.0.8)
monitor (0.0.8)
network (2.0.10)
nspkg (3.0.1)
profile (2.0.8)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.10)
role (2.0.8)
sf (1.0.5)
sql (2.0.7)
storage (2.0.10)
vm (2.0.10)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

**OS Version:** What OS and version are you using?  
`macOS Sierra 10.12.5`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
`zsh`

**Comment by bertschneider** [comment]
I had a look at the code and created a small fix. It works for my case but surely needs a review if it fits the overall architecture.

**Comment by samedder** [comment]
Thanks for reporting and fixing this @bertschneider, do you want to create a PR for this so you get contribute credit, or would you rather we take your fix?

**Comment by bertschneider** [comment]
I already created PR #4077 with the fix. Feel free to merge it or take the code in some other way.

Beware that I didn't (had no time to) check all the other commands if they honor the flag.
