### ISSUE TITLE
Error to create Redirect Config (new feature) in Application Gateway

### ISSUE THREAD

**Issue by matiasma** [Azure/azure-cli#4063]
### Description
**Outline the issue here:**

I’m trying with no success to create Redirect Config (new AppGW feature) using the latest AZ CLI version (network - 2.0.10).

Command line:
az network application-gateway redirect-config create --gateway-name appgw03 --name https --resource-group vmss --type Permanent --target-listener appGatewayHttpListener --include-query-string true --include-path true

Error Message:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 450, in create_ag_redirect_configuration
    include_query_string=include_query_string)
TypeError: 'NoneType' object is not callable

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.10)

acr (2.0.8)
acs (2.0.10)
appservice (0.1.10)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.6)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
core (2.0.11)
cosmosdb (0.1.10)
dla (0.0.10)
dls (0.0.10)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.6)
iot (0.1.9)
keyvault (2.0.8)
lab (0.0.8)
monitor (0.0.8)
network (2.0.10)
nspkg (3.0.1)
profile (2.0.8)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.10)
role (2.0.8)
sf (1.0.5)
sql (2.0.7)
storage (2.0.10)
vm (2.0.10)

Python (Linux) 3.6.1 (default, Jul  7 2017, 17:58:08)
[GCC 4.8.4]

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 version 1703

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by tjprescott** [comment]
Hi @matiasma thank you for the report. The fix will be in the upcoming release.
