### ISSUE TITLE
az storage container raises exceptions

### ISSUE THREAD

**Issue by ad-m** [Azure/azure-cli#4102]
### Description
Hello,

I am would like achieve summary of capacity usage of each container.  I have a few. 

I run:
 ```
az>> az storage container  --verbose
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azclishell/app.py", line 667, in cli_execute
    result = self.app.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
TypeError: 'NoneType' object is not callable
```

It crashes.

---

### Environment summary

**Install Method:** 
deb repository
**CLI Version:** 
```
~$ az --version
azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Linux) 3.6.1 (default, Jul 28 2017, 00:18:58) 
[GCC 4.8.4]

Python location '/opt/az/bin/python3'
```
**OS Version:**
```
adas@adam3-Latitude-E7450:~$ uname -a
Linux adam3-Latitude-E7450 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
adas@adam3-Latitude-E7450:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Shell Type:** bash && az interactive

**Comment by troydai** [comment]
@ad-m I'm not able to repo this issue:
```
10:14 $ az storage container  -verbose
az storage container: error: the following arguments are required: subcommand
usage: az storage container [-h]
                            {list,delete,show,create,generate-sas,metadata,lease,exists,set-permission,show-permission,policy}
                            ...
```

Note that `az storage container` itself requires further sub command. 

Close this issue for now

**Comment by ad-m** [comment]
This problem occurs after some time using "az interactive". I can not repeat it now.
