### ISSUE TITLE
az acs kubernetes get-credentials cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by dewolfs** [Azure/azure-cli#4123]
### Description
**Outline the issue here:**
Trying to get credentials from new create ACS cluster via azure CLI. Create a new ssh-key and logged in as root.

**Output console:**

```
/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/root/lib/azure-cli/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/custom.py", line 779, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/custom.py", line 800, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/acs_client.py", line 57, in secure_copy
    keys = _load_keys(key_filename, allow_agent)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/acs_client.py", line 45, in _load_keys
    key = _load_key(default_key_path)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/acs_client.py", line 23, in _load_key
    pkey = paramiko.RSAKey.from_private_key_file(key_filename, None)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/pkey.py", line 205, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/rsakey.py", line 47, in __init__
    self._from_private_key_file(filename, password)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/rsakey.py", line 173, in _from_private_key_file
    self._decode_key(data)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/rsakey.py", line 182, in _decode_key
    data, password=None, backend=default_backend()
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
```

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

Python location '/root/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 version 1703

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by dewolfs** [comment]
eval $(ssh-agent)
**is running**

ssh-add ~/.ssh/id_rsa

ssh-add -L
**output of id_rsa**

Re-created the ACS K8S cluster and now I get:

```
[Errno None] Unable to connect to port 22 on 40.68.186.207
Traceback (most recent call last):
  File "/root/lib/azure-cli/lib/python3.5/site-packages/azure/cli/command_modules/acs/acs_client.py", line 62, in secure
_copy
    ssh.connect(host, username=user, pkey=pkey)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/client.py", line 366, in connect
    t.start_client(timeout=timeout)
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/transport.py", line 510, in start_client
    raise e
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/transport.py", line 1843, in run
    self.kex_engine.start_kex()
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py", line 32, in start_kex
    self._generate_key_pair()
  File "/root/lib/azure-cli/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py", line 51, in _generate_key_pair
    self.P = ec.generate_private_key(self.curve, default_backend())
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_b
ackend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <m
odule>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <m
odule>
    from cryptography.hazmat.bindings.openssl import binding
  File "/root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <m
odule>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/lib/azure-cli/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enabl
e executable stack as shared object requires: Invalid argument
```

**Comment by derekbekoe** [comment]
Possibly related to https://github.com/Azure/azure-cli/issues/4106

**Comment by dewolfs** [comment]
when i looked at https://github.com/Azure/azure-cli/tree/master/packaged_releases/pip_requirements i tried to install cli via the txt file, i got an error about missing openssl.  Installed openssl and now I get the following error:

```
No module named graphrbac.models
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 167, in execute
    self.configuration.load_params(command)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 49, in load_params
    commands.load_params(command)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 289, in load_params
    command_table[command].load_arguments()
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 239, in load_arguments
    self.arguments.update(self.arguments_loader())
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 495, in arguments_loader
    return extract_args_from_signature(get_op_handler(operation), no_wait_param=no_wait_param)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 388, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/acs/custom.py", line 41, in <module>
    from azure.graphrbac.models import (ApplicationCreateParameters,
ImportError: No module named graphrbac.models
```

The following python versions are installed:
Python 2.7.12
Python 3.5.2

Something to do with cross matching of libraries between python versions?

**Comment by dewolfs** [comment]
Completely removed bash from Windows and re-installed. Reinstalled Azure CLI
ssh-keygen -t rsa -> keys generated in default location in Linux filesystem
created acs kubernetes cluster without specifying the location of the ssh keys. -> cluster gets correct created.

When I want to get the credentials:


```
msrest.http_logger : Response content:
msrest.http_logger : Body contains chunked data.
paramiko.transport : starting thread (client mode): 0xdceb9940
paramiko.transport : Local version/idstring: SSH-2.0-paramiko_2.2.1
paramiko.transport : Remote version/idstring: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
paramiko.transport : Connected (version 2.0, client OpenSSH_7.2p2)
paramiko.transport : kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
paramiko.transport : Kex agreed: ecdh-sha2-nistp256
paramiko.transport : HostKey agreed: ssh-ed25519
paramiko.transport : Cipher agreed: aes128-ctr
paramiko.transport : MAC agreed: hmac-sha2-256
paramiko.transport : Compression agreed: none
paramiko.transport : Unknown exception: /opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
paramiko.transport : Traceback (most recent call last):
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 1843, in run
paramiko.transport :     self._handler_table[ptype](self, m)
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 1940, in _negotiate_keys
paramiko.transport :     self.kex_engine.start_kex()
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 32, in start_kex
paramiko.transport :     self._generate_key_pair()
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 51, in _generate_key_pair
paramiko.transport :     self.P = ec.generate_private_key(self.curve, default_backend())
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
paramiko.transport :     from cryptography.hazmat.backends.openssl.backend import backend
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
paramiko.transport :     from cryptography.hazmat.backends.openssl.backend import backend
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
paramiko.transport :     from cryptography.hazmat.bindings.openssl import binding
paramiko.transport :   File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
paramiko.transport :     from cryptography.hazmat.bindings._openssl import ffi, lib
paramiko.transport : ImportError: /opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
paramiko.transport :
/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 779, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 800, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/acs_client.py", line 62, in secure_copy
    ssh.connect(host, username=user, pkey=pkey)
  File "/opt/az/lib/python3.6/site-packages/paramiko/client.py", line 366, in connect
    t.start_client(timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 510, in start_client
    raise e
  File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 1843, in run
    self._handler_table[ptype](self, m)
  File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 1940, in _negotiate_keys
    self.kex_engine.start_kex()
  File "/opt/az/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 32, in start_kex
    self._generate_key_pair()
  File "/opt/az/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py", line 51, in _generate_key_pair
    self.P = ec.generate_private_key(self.curve, default_backend())
  File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
```

**Comment by derekbekoe** [comment]
@dewolfs you can install an older version of the CLI.
See https://github.com/Azure/azure-cli/issues/4106#issuecomment-320795635

**Comment by rjtsdl** [comment]
@dewolfs, i just tried it in the latest az cli. I can successfully get-credentials without any error. 
So I encourage you to try out the latest az cli (There is a release on 8/15/2017). Let me know if the error still persists.

**Comment by derekbekoe** [comment]
Closing so we can track the conversation all in https://github.com/Azure/azure-cli/issues/4154
