### ISSUE TITLE
Crash during Interactive mode

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4126]
ML team is having issues getting az interactive to work;

![image](https://user-images.githubusercontent.com/10146011/28889987-8e45fd9e-777a-11e7-8f90-5faa2d1dd516.png)

Here’s my pip freeze:
```
azure-cli==2.0.12
azure-cli-acr==2.0.9
azure-cli-acs==2.0.11
azure-cli-appservice==0.1.11
azure-cli-batch==3.0.3
azure-cli-billing==0.1.3
azure-cli-cdn==0.0.6
azure-cli-cloud==2.0.7
azure-cli-cognitiveservices==0.1.6
azure-cli-command-modules-nspkg==2.0.1
azure-cli-component==2.0.6
azure-cli-configure==2.0.10
azure-cli-consumption==0.1.3
azure-cli-container==0.1.7
azure-cli-core==2.0.12
azure-cli-cosmosdb==0.1.11
azure-cli-dla==0.0.10
azure-cli-dls==0.0.11
azure-cli-feedback==2.0.6
azure-cli-find==0.2.6
azure-cli-interactive==0.3.7
azure-cli-iot==0.1.10
azure-cli-keyvault==2.0.8
azure-cli-lab==0.0.9
azure-cli-machinelearning==0.0.11+dev
azure-cli-ml==0.1.0a17
azure-cli-monitor==0.0.8
azure-cli-network==2.0.11
azure-cli-nspkg==3.0.1
azure-cli-profile==2.0.9
azure-cli-rdbms==0.0.5
azure-cli-redis==0.2.7
azure-cli-resource==2.0.11
azure-cli-role==2.0.9
azure-cli-sf==1.0.5
azure-cli-sql==2.0.8
azure-cli-storage==2.0.11
azure-cli-vm==2.0.11
```

**Comment by tjprescott** [comment]
If they remove their module and run it, does it still crash?  If so, then it's a bug in az interactive. If not, then it's a bug in their ML module.

**Comment by tjprescott** [comment]
From the stack trace, it looks like their module might have errors in the help.py file.

**Comment by tjprescott** [comment]
Closing due to inactivity. Reopen if still an issue.

**Comment by mountainbrother** [comment]
Get an exepction an an Azure VM 
az 2.062 works but if i try to install an extenstion like the interactive i run in this error i never ever seen bevor:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\aatv\.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "C:\Users\aat\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 88, in dump_command_table
    main_loader.load_arguments(None)-----------------------------------------------------------------------------------
  File "C:\Users\aat\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 49, in load_arguments--------------------------------------------------------------------------------------------------------
    command.load_arguments()
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 130, in load_arguments  : use commands outside the application
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\commands.py", line 89, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 454, in default_arguments_loader : do a step by step tutorial of example
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 494, in get_op_handler           : set a scope, and scopes can be chained with spaces
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                Hit [enter] to refresh
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-servicefabric\azure\cli\command_modules\servicefabric\custom.py", line 43, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\models.py", line 10, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\compute_management_client.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\disks_operations.py", line 18, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\compute\v2018_09_30\models\__init__.py", line 56, in <module>
    from ._compute_management_client_enums import StorageAccountTypes
ImportError: cannot import name 'StorageAccountTypes'
