### ISSUE TITLE
Install fails on macOS Sierra

### ISSUE THREAD

**Issue by haakoo** [Azure/azure-cli#4153]
### Description
I tried to install azure-cli using the recommended method from [Install Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

```bash
curl -L https://aka.ms/InstallAzureCli | bash
```

The install fails for `scandir` and then again at the build step (`gcc`).

From the terminal:
```
...
running build_ext
  building '_scandir' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _scandir.c -o build/temp.macosx-10.6-x86_64-2.7/_scandir.o
  unable to execute gcc-4.2: No such file or directory
  error: command 'gcc-4.2' failed with exit status 1

  ----------------------------------------
  Failed building wheel for scandir
  Running setup.py clean for scandir
  Running setup.py bdist_wheel for oauthlib ... done
...
```

Then a bit later:

```
...
running build_ext
    building '_scandir' extension
    creating build/temp.macosx-10.6-x86_64-2.7
    gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _scandir.c -o build/temp.macosx-10.6-x86_64-2.7/_scandir.o
    unable to execute gcc-4.2: No such file or directory
    error: command 'gcc-4.2' failed with exit status 1

    ----------------------------------------
Command "/Users/haakoo/lib/azure-cli/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/pip-build-6B7K4P/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/pip-OEq8G2-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/haakoo/lib/azure-cli/bin/../include/site/python2.7/scandir" failed with error code 1 in /private/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/pip-build-6B7K4P/scandir/
Traceback (most recent call last):
  File "/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/azure_cli_install_tmp_XXXX.eO5Eveib", line 370, in <module>
    main()
  File "/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/azure_cli_install_tmp_XXXX.eO5Eveib", line 356, in main
    install_cli(install_dir, tmp_dir)
  File "/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/azure_cli_install_tmp_XXXX.eO5Eveib", line 140, in install_cli
    exec_command(cmd)
  File "/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/azure_cli_install_tmp_XXXX.eO5Eveib", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/haakoo/lib/azure-cli/bin/pip', 'install', '--cache-dir', '/var/folders/lr/smcqct191kqbz3_17v0m4sjm0000gq/T/tmpVAvl7A', 'azure-cli', '--upgrade']' returned non-zero exit status 1
```

---

### Environment summary

**Install Method:**
Answer here: Using bash command `curl -L https://aka.ms/InstallAzureCli | bash`

**CLI Version:**
Answer here: N/A

**OS Version:**
Answer here: macOS Sierra version 10.12.6

**Shell Type:**  
Answer here: terminal with bash

**Other information:**
I do have homebrew installed, and updated.

**Comment by derekbekoe** [comment]
This issue is with `scandir`. Run `xcode-select --install` as in https://github.com/Azure/azure-cli/issues/3473#issuecomment-304298948.

If that doesn't work provide the full output from the CLI install script.

Closing. Please comment if you're still seeing issues here.

**Comment by rordaz** [comment]
This worked for my thanks!
