### ISSUE TITLE
Exception thrown for "az vm list -d" with IPv6-enabled adapter

### ISSUE THREAD

**Issue by snobu** [Azure/azure-cli#4188]
Probably same as https://github.com/Azure/azure-cli/issues/2543

Looks like a NoneType is returned for adapters that are IPv6 enabled.

```
$ az vm list -d (or az vm show -n v6linux -g summer -d)

sequence item 1: expected string or Unicode, NoneType found
Traceback (most recent call last):
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 550, in _execute_command
    reraise(*sys.exc_info())
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 527, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 160, in list_vm
    return [get_vm_details(_parse_rg_name(v.id)[0], v.name) for v in vm_list]
  File "/home/snobu/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/vm/custom.py", line 197, in get_vm_details
    setattr(result, 'private_ips', ','.join(private_ips))
TypeError: sequence item 1: expected string or Unicode, NoneType found
```

It trips somewhere here:
https://github.com/Azure/azure-cli/blob/620f0d2ce03b4a296b59eeb86d554e314d4bc585/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/custom.py#L183

I can work around it if i try around the `setattr()` line:

````python
try:
    setattr(result, 'private_ips', ','.join(private_ips))
except TypeError:                                                                                                                   
    print('Got TypeError from setattr')
````

Result:
```
~ % az vm list -d -o table
DEBUG public_ips= [u'13.80.31.188']
Got TypeError from setattr
DEBUG public_ips= [u'13.95.26.138']
Name                   ResourceGroup    PowerState      Location    Fqdns                                     PublicIps
---------------------  ---------------  --------------  ----------  ----------------------------------------  ------------
k8s-agent-ABF7096D-0   ACS-KUBE         VM deallocated  westeurope
k8s-agent-ABF7096D-1   ACS-KUBE         VM deallocated  westeurope
k8s-master-ABF7096D-0  ACS-KUBE         VM deallocated  westeurope
[...MORE VMs...]
```

I would send a PR but i'm not sure how you want to deal with this particular case.
I mean we could just do something like:

```python
setattr(result, 'private_ips', ','.join(filter(None, private_ips)))  
```

or a more elegant

```python

    # We may get a NoneType from IPv6-enabled network adapters
    private_ips = filter(None, private_ips)

    setattr(result, 'power_state',
            ','.join([s.display_status for s in result.instance_view.statuses if s.code.startswith('PowerState/')]))
    setattr(result, 'public_ips', ','.join(public_ips))
    setattr(result, 'fqdns', ','.join(fqdns))
    setattr(result, 'private_ips', ','.join(private_ips))
    ...
```

but i mean.. is that the Pythonesque way to handle this conundrum? :)

`/providers/Microsoft.Network/networkInterfaces/ipv6nic?api-version=2017-06-01`, looks like this in my case:

```
{
  "name": "ipv6nic",
  "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/networkInterfaces/ipv6nic",
  "etag": "W/\"373a1489-8fb6-476e-8faf-f278cd16bb56\"",
  "location": "westeurope",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "96ce11b3-3766-4389-99bd-2eeb3ee6dce3",
    "ipConfigurations": [
      {
        "name": "ipconfig1",
        "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/networkInterfaces/ipv6nic/ipConfigurations/ipconfig1",
        "etag": "W/\"373a1489-8fb6-476e-8faf-f278cd16bb56\"",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "10.90.9.7",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/publicIPAddresses/v6linux-ip"
          },
          "subnet": {
            "id": "/subscriptions/<SUB_ID>/resourceGroups/VNET/providers/Microsoft.Network/virtualNetworks/MilkyWay/subnets/iaas-subnet"
          },
          "primary": true,
          "privateIPAddressVersion": "IPv4",
          "loadBalancerBackendAddressPools": [
            {
              "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/loadBalancers/LB-with-ipv6/backendAddressPools/v6linux-overv4"
            }
          ]
        }
      },
      {
        "name": "ipv6",
        "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/networkInterfaces/ipv6nic/ipConfigurations/ipv6",
        "etag": "W/\"373a1489-8fb6-476e-8faf-f278cd16bb56\"",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAllocationMethod": "Dynamic",
          "privateIPAddressVersion": "IPv6",
          "loadBalancerBackendAddressPools": [
            {
              "id": "/subscriptions/a<SUB_ID>/resourceGroups/summer/providers/Microsoft.Network/loadBalancers/LB-with-ipv6/backendAddressPools/v6linux"
            }
          ]
        }
      }
    ],
    "dnsSettings": {
      "dnsServers": [],
      "appliedDnsServers": []
    },
    "enableAcceleratedNetworking": false,
    "enableIPForwarding": false,
    "primary": true,
    "virtualMachine": {
      "id": "/subscriptions/<SUB_ID>/resourceGroups/summer/providers/Microsoft.Compute/virtualMachines/v6linux"
    }
  },
  "type": "Microsoft.Network/networkInterfaces"
}
```

```
azure-cli (2.0.12+1.dev20170809)

acr (2.0.9+1.dev20170809)
acs (2.0.11+1.dev20170809)
appservice (0.1.11+1.dev20170809)
batch (3.1.0+1.dev20170809)
billing (0.1.3+1.dev20170809)
cdn (0.0.6+1.dev20170809)
cloud (2.0.7+1.dev20170809)
cognitiveservices (0.1.6+1.dev20170809)
command-modules-nspkg (2.0.1+1.dev20170809)
component (2.0.6+1.dev20170809)
configure (2.0.10+1.dev20170809)
consumption (0.1.3+1.dev20170809)
container (0.1.7+1.dev20170809)
core (2.0.12+1.dev20170809)
cosmosdb (0.1.11+1.dev20170809)
dla (0.0.10+1.dev20170809)
dls (0.0.11+1.dev20170809)
feedback (2.0.6+1.dev20170809)
find (0.2.6+1.dev20170809)
interactive (0.3.7+1.dev20170809)
iot (0.1.10+1.dev20170809)
keyvault (2.0.8+1.dev20170809)
lab (0.0.9+1.dev20170809)
monitor (0.0.8+1.dev20170809)
network (2.0.11+1.dev20170809)
nspkg (3.0.1+1.dev20170809)
profile (2.0.9+1.dev20170809)
rdbms (0.0.5+1.dev20170809)
redis (0.2.7+1.dev20170809)
resource (2.0.11+1.dev20170809)
role (2.0.9+1.dev20170809)
sf (1.0.5+1.dev20170809)
sql (2.0.8+1.dev20170809)
storage (2.0.11+1.dev20170809)
vm (2.0.11+1.dev20170809)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]
```

**Comment by snobu** [comment]
Would you take a PR with this in?

```python
    # We may get a NoneType from IPv6-enabled network adapters
    private_ips = filter(None, private_ips)
```
