### ISSUE TITLE
az cognitiveservices account create error and documentation

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-cli#4295]
### Description
**Issue 1** - help on `az cognitiveservices account create` appears incorrect and incomplete. The provided example is this:

```
az cognitiveservices create -n myresource -g myResourceGroup --kind Face --sku S0 -l WestEurope --yes
```

Should it not be:

```
az cognitiveservices account create -n myresource -g myResourceGroup --kind Face --sku S0 -l WestEurope --yes
```

**Issue 2** - When running `az cognitiveservices account create` I am met with an error. I am assuming my command is good, but it may not be. Can I get confirmation that this is a. my issue or b. a bug?

Command:

```
az cognitiveservices account create --name $AZURE_ANALYTICS --resource-group $AZURE_RESOURCE_GROUP --location eastus --kind TextAnalytics --sku S0
```

Output:

```
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "/Users/neilpeterson/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/neilpeterson/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "/Users/neilpeterson/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/neilpeterson/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 565, in _execute_command
    raise client_exception
ErrorException: Operation returned an invalid status code 'Bad Request'
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

Script from docs.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

```
azure-cli (2.0.14)

acr (2.0.10)
acs (2.0.13)
appservice (0.1.13)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)
```

**OS Version:** What OS and version are you using?  

Mac OS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

Bash

**Comment by tjprescott** [comment]
@pchoudhari
