### ISSUE TITLE
Cannot download-batch when file and folder have the same name

### ISSUE THREAD

**Issue by vlaskinvlad** [Azure/azure-cli#4371]
### Description

When download folders from Azure Blob Storage as:
`az storage blob download-batch --connection-string $CS -d /mnt -s export`

If in the container (`export` from the example above)  I have a folder and a file with the same name, I got an error with stack-trace below.

This situation happens naturally when folder is created with Spark or Hadoop jobs
(e.g. there is a folder AND 0B file satellite having the same name).
After I delete file-satellite download works normally.

For the trace below: `gt` is the name of the folder and the file.

```
[Errno 20] Not a directory: '/mnt/locations/gt' 
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 556, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 533, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/blob.py", line 124, in storage_blob_download_batch
    return list(_download_blob(client, source_container_name, destination, blob) for blob in source_blobs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/blob.py", line 124, in <genexpr>
    return list(_download_blob(client, source_container_name, destination, blob) for blob in source_blobs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/blob.py", line 250, in _download_blob
    blob = blob_service.get_blob_to_path(container, blob_name, destination_path)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/blob/baseblobservice.py", line 1765, in get_blob_to_path
    with open(file_path, open_mode) as stream:
NotADirectoryError: [Errno 20] Not a directory: '/mnt/locations/gt'
```
---
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Docker via 2 commands:
```
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | \
     tee /etc/apt/sources.list.d/azure-cli.list
RUN apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893 \
    && apt-get install -y apt-transport-https \
    && apt-get update && apt-get install -y azure-cli
```

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.16-1

**OS Version:** What OS and version are you using?  
16.04.2 LTS (Xenial Xerus)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by williexu** [comment]
This is a limitation of the OS. It is not possible to create a file and folder of the same name in the same directory.

**Comment by sdecri** [comment]
There's something we can do to avoid the creation of file-satellite?
I'm persisting a dataframe classifying the output according to a specific column. The result is one folder for each distinct value of this column, this means that is not possible to manually delete all the file-satellite.
