### ISSUE TITLE
Test test_acr_create_webhook is randomly failing on CI.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4481]
```
======================================================================
ERROR: test_acr_create_webhook (azure.cli.command_modules.acr.tests.test_acr_commands.AcrCommandsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure_devtools/scenario_tests/preparers.py", line 42, in _preparer_wrapper
    **kwargs
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/preparers.py", line 38, in create_resource
    execute(template.format(self.location, name))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 106, in __init__
    ('Logging ' + self.applog) if self.applog else '')
AttributeError: 'ExecutionResult' object has no attribute 'applog'
----------------------------------------------------------------------
```

**Comment by troydai** [comment]
@djyou

**Comment by troydai** [comment]
Reopen

this issue still persists, but in a different form:
```
======================================================================
FAIL: test_acr_create_webhook (azure.cli.command_modules.acr.tests.test_acr_commands.AcrCommandsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure_devtools/scenario_tests/preparers.py", line 42, in _preparer_wrapper
    **kwargs
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/preparers.py", line 38, in create_resource
    execute(template.format(self.location, name))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 110, in __init__
    raise AssertionError('The command failed. Exit code: {}'.format(self.exit_code))
AssertionError: The command failed. Exit code: 1
-------------------- >> begin captured logging << --------------------
azure.cli.testsdk: ERROR: Command "az group create --location eastus --name clitest.rg000001 --tag use=az-test" => 1. Output: . 
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

**Comment by djyou** [comment]
This error seems to be from the test sdk `ResourceGroupPreparer`? Is it only showing for acr tests or showing for all `group create` but just because acr tests are the first ones to run?

**Comment by troydai** [comment]
That's what I was thinking, therefore I unassigned you from this issue.
