### ISSUE TITLE
Invalid metric-names option render unintuitive error message in az monitor metric list-definitions command.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4554]
```
10:59 $ az resource list --query [10].id -otsv | xargs -I {} az monitor metrics list-definitions --resource {} -ojson --metric-names '/subscriptions/6b085460-5f21-477e-ba44-1035046e9101/resourceGroups/101/providers/Microsoft.Compute/virtualMachines/00/providers/microsoft.insights/metricdefinitions/CPU Credits Consumed'
'HTTPError' object has no attribute 'message'
Traceback (most recent call last):
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/command_modules/monitor/custom.py", line 146, in list_metric_definitions
    return list(metric_definitions)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/monitor/operations/metric_definitions_operations.py", line 98, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.monitor.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Not Found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 623, in _execute_command
    exception_handler(ex)
  File "/Users/troydai/code/alpha-env/env/lib/python3.6/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 11, in monitor_exception_handler
    if hasattr(ex, 'inner_exception') and 'MonitoringService' in ex.inner_exception.message:
AttributeError: 'HTTPError' object has no attribute 'message'
```

**Comment by tjprescott** [comment]
Can confirm this has been addressed.
