### ISSUE TITLE
Service Fabric Upload Package Fails with 104 ECONNRESET

### ISSUE THREAD

**Issue by brian-l-coker** [Azure/azure-cli#4583]
### Description
az sf application upload results in a 104 ECONNRESET when connected to a secure cluster.

Note: this works fine using the new sfctl modules.

```
[bcoker XXXX]$ az sf cluster select --endpoint https://10.44.24.172:19080 --no-verify --pem ~/.azure/certificates/certificate.pem

[bcoker XXXX]$ az sf application upload --path ../spring_config_server/target/deploy/configApplication
(104, 'ECONNRESET')
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 304, in _send_until_done
    return self.connection.send(data)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1540, in send
    self._raise_ssl_error(self._ssl, result)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1448, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/adapters.py", line 463, in send
    low_conn.send(i)
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/http/client.py", line 885, in send
    self.sock.sendall(data)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 556, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 533, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/command_modules/sf/custom.py", line 232, in sf_upload_app
    verify=ca_cert)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (104, 'ECONNRESET')

```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

yum

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.16)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.15)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.15)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.9)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.10)
storage (2.0.14)
vm (2.0.13)

Python (Linux) 3.5.1 (default, Sep 15 2016, 08:30:32) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

Python location '/opt/rh/rh-python35/root/usr/bin/python3'

Legal docs and information: aka.ms/AzureCliLegal

**OS Version:** What OS and version are you using?  
Answer here:
RHEL 7.4
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
BASH

**Comment by peterpogorski** [comment]
Thank you for the feedback! 

I am closing as this cmdlet does not currently exist. In the future we are looking at expanding the application cmdlet to support more functionality.
