### ISSUE TITLE
Kubernetes get-credentails fails if known_hosts is malformatted 

### ISSUE THREAD

**Issue by peterj** [Azure/azure-cli#4633]
### Description
Not sure how/when my known_hosts file got messed up, but running ```az acs kubernetes get-credentials``` fails (I think paramiko tries to load the known_hosts file and throws an exception -
 this could be caught and CLI could fail nicely):   

```
Password for private key:
('[known_hosts_entry]', Error('Incorrect padding',))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 626, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 814, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 835, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 60, in secure_copy
    ssh.load_system_host_keys()
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 102, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 97, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 366, in from_line
    raise InvalidHostKey(line, e)
InvalidHostKey: ('[ACTUAL_HOST_KEY]', Error('Incorrect padding',))
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip install azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.18)

**OS Version:** What OS and version are you using?  
Answer here: MacOS 10.13

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by rjtsdl** [comment]
the ask here is, how to get exceptions nicely.
@troydai, do we have any tactic in general in handling exception?

**Comment by peterj** [comment]
I think the fix here would be as simple just catching the specific exception e.g.:
```
...
except InvalidHostKey:
...
```

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
