### ISSUE TITLE
Cannot export resource group in azure-cli 2.0.19

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-cli#4669]
### Description
When running 'az group export -n "foo"', I get the following error message regardless of the resource group specified

```
Refuse str type as a valid iter type.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 630, in _execute_command
    raise client_exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 236, in export_group_as_template
    result = rcf.resource_groups.export_template(resource_group_name, '*', options=options)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py", line 442, in export_template
    body_content = self._serialize.body(parameters, 'ExportTemplateRequest')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 448, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 374, in _serialize
    target_obj, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 583, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 394, in _serialize
    orig_attr, attr_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 576, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 627, in serialize_iter
    raise SerializationError("Refuse str type as a valid iter type.")
msrest.exceptions.SerializationError: Refuse str type as a valid iter type.
```

The error message is being thrown from: https://github.com/Azure/msrest-for-python/blame/master/msrest/serialization.py#L627

And was introduced very recently in https://github.com/Azure/msrest-for-python/pull/54 for corresponding issue https://github.com/Azure/msrest-for-python/issues/41

Also possible that other features are unknowingly failing since this is being raised from the core serializer code

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.19)

acr (2.0.13)
acs (2.0.17)
appservice (0.1.18)
backup (1.0.1)
batch (3.1.5)
batchai (0.1.1)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.18)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.15)
eventgrid (0.1.4)
extension (0.0.4)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.12)
lab (0.0.11)
monitor (0.0.10)
network (2.0.16)
nspkg (3.0.1)
profile (2.0.14)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.16)
role (2.0.13)
servicefabric (0.0.4)
sql (2.0.13)
storage (2.0.17)
vm (2.0.16)
```

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise 1709.16299.15

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by tjprescott** [comment]
cc/ @lmazuel  as this may be related to the MSrest change. 

However, for what it's worth, I am able to repro this. I can export resource groups without issue.

**Comment by richeney** [comment]
I am seeing this error message on both CLI 2.0 on Windows 10 Bash subsystem (installed with apt-get) and also in the Cloud Shell.  (Same az --versions as above.) 

I reverted the msrest version to 0.4.14 in Bash(using "sudo --set-home pip install msrest==0.4.14 --ignore-installed") with no success.
