### ISSUE TITLE
'az monitor metrics list' doesn't accept multiple metrics names.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4697]
```
00:07 $ az monitor metrics list --resource /subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/troy-permanent/providers/Microsoft.Storage/storageAccounts/trdaitest01 --time-grain PT1M --start-time 2017-10-17T07:58:00Z --end-time 2017-10-17T08:16:00Z --metric-names Egress Ingress
Overriding dimensionName AccountResourceId already in the query
Traceback (most recent call last):
  File "/home/troydai/code/azure-cli/src/azure-cli/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/troydai/code/azure-cli/src/azure-cli-core/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/home/troydai/code/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/home/troydai/code/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 630, in _execute_command
    raise client_exception
  File "/home/troydai/code/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "/home/troydai/code/azure-cli/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_exception_handler.py", line 18, in monitor_exception_handler
    reraise(*sys.exc_info())
  File "/home/troydai/code/azure-cli/env/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/troydai/code/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/home/troydai/code/azure-cli/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/custom.py", line 176, in list_metrics
    return list(metrics)
  File "/home/troydai/code/azure-cli/env/lib/python3.5/site-packages/msrest/paging.py", line 109, in __next__
    self.advance_page()
  File "/home/troydai/code/azure-cli/env/lib/python3.5/site-packages/msrest/paging.py", line 95, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/troydai/code/azure-cli/env/lib/python3.5/site-packages/azure/monitor/operations/metrics_operations.py", line 110, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
azure.monitor.models.error_response.ErrorResponseException: Overriding dimensionName AccountResourceId already in the query

```

**Comment by javimb** [comment]
Hi,

I think that's not a problem with the CLI but with the monitoring API (which I suppose that the CLI is using), because I'm getting the same error using the Java SDK.

**Comment by troydai** [comment]
@javimb, thank you for confirming this. We're in contact with monitoring team trying to address this issue. I will leave this issue open till the problem is fixed.

**Comment by ferrandiaz** [comment]
Getting the same error when using the LB api. 
`az monitor metrics list --resource {resource} --metric-names ByteCount DipAvailability PacketCount SnatConnectionCount VipAvailability --time-grain PT1M --start-time {date}`

**Comment by troydai** [comment]
Moving forward the metrics list command will only accept one metric.

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/4974

**Comment by Ilanak** [comment]
So now 2017-05-01-preview api version accepts only one metric?

**Comment by troydai** [comment]
Yes.
