### ISSUE TITLE
Azure AD App Update Reply URL

### ISSUE THREAD

**Issue by brian-l-coker** [Azure/azure-cli#4703]
I'm trying to update an Azure AD App with a list of Reply URLs

The documentation says the URI's should be space separated values, but I'm unable to successfully issue the update command. 

This doesn't seem to do anything:
```
az ad app update --id XXXXXXXXXXXXXXXXXXXX --reply-urls https://10.44.25.45:19080/Explorer/index.html https://10.44.24.218:19080/Explorer/index.html https://10.44.24.228:19080/Explorer/index.html https://10.44.25.200:19080/Explorer/index.html 
```

Wrapping the values in quotes throws a Graph Exception

```
az ad app update --id XXXXXXXXXXXXXXXXXXXX --reply-urls "https://10.44.25.45:19080/Explorer/index.html https://10.44.24.218:19080/Explorer/index.html https://10.44.24.228:19080/Explorer/index.html https://10.44.25.200:19080/Explorer/index.html"

One or more properties contains invalid values.
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 566, in _execute_command
    raise client_exception
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 556, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 533, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/cli/command_modules/role/custom.py", line 398, in update_application
    return client.patch(object_id, app_patch_param)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/azure/graphrbac/operations/applications_operations.py", line 338, in patch
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: One or more properties contains invalid values.
```
---

### Environment summary

azure-cli (2.0.16)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.15)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.15)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.9)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.10)
storage (2.0.14)
vm (2.0.13)

Python (Linux) 3.5.1 (default, Sep 15 2016, 08:30:32) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

Python location '/opt/rh/rh-python35/root/usr/bin/python3'

```
```

**Comment by brian-l-coker** [comment]
Looks like this works after all. Browser caching in the portal made it appear as if the reply urls were not updated. The correct syntax is no quotes.
