### ISSUE TITLE
Flaky ACR tests

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4773]
```
======================================================================
FAIL: test_acr_create_replication (azure.cli.command_modules.acr.tests.test_acr_commands.AcrCommandsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure_devtools/scenario_tests/preparers.py", line 42, in _preparer_wrapper
    **kwargs
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/preparers.py", line 37, in create_resource
    execute(template.format(self.location, name))
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/azure/cli/testsdk/base.py", line 110, in __init__
    raise AssertionError('The command failed. Exit code: {}'.format(self.exit_code))
AssertionError: The command failed. Exit code: 1
-------------------- >> begin captured logging << --------------------
azure.cli.testsdk: ERROR: Command "az group create --location westus --name clitest.rg000001 --tag use=az-test" => 1. Output: . 
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 803 tests in 598.201s

FAILED (SKIP=34, failures=1)
```

cc: @djyou

**Comment by djyou** [comment]
This error seems to be from the test sdk `ResourceGroupPreparer`? I guess it might just be that acr tests are the first ones to run and fail?

Similar issue https://github.com/Azure/azure-cli/issues/4481

**Comment by derekbekoe** [comment]
Thanks @djyou. @troydai is this on your radar?

**Comment by troydai** [comment]
I'm aware of it but didn't look into it yet.
