### ISSUE TITLE
`az ad user show` has an error when used with guest AAD account

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-cli#4775]
When I try to use `az ad user show` with a guest account, I get an error stating `The specified api-version is invalid`

```
az ad user show --upn-or-object-id 'testuser1_nobun.onmicrosoft.com#EXT#@microsoft.onmicrosoft.com'
The specified api-version is invalid. The value must exactly match a supported version.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 630, in _execute_command
    raise client_exception
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 49, in empty_on_404
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/users_operations.py", line 220, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: The specified api-version is invalid. The value must exactly match a supported version.
```

`az ad user list` is an acceptable workaround, so this is a non-blocking issue

```
az ad user list --upn 'testuser1_nobun.onmicrosoft.com#EXT#@microsoft.onmicrosoft.com'
```

`az ad user show` for a member originating in the same tenant works, so this seems to be isolated to certain accounts:

```
az ad user show --upn-or-object-id 'nobun@microsoft.com'
```

---

### Environment summary

apt-get / 2.0.20 / Windows 10 Build 17017 / Bash on Windows  

Full version info:
```
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/opt/az/bin/python3'
Extensions directory '/home/noel/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct 18 2017, 20:41:18)
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yugangw-msft** [comment]
@lmazuel, this is not a CLI issue, rather the [generated code](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-graphrbac/azure/graphrbac/operations/users_operations.py#L196) doesn't encode the `#`
Could you please recommend what needs to be fixed either at the graphrbac spec or the code-gen?

**Comment by lmazuel** [comment]
@noelbundick could you reexecute in debug mode (`--debug`) and drop the result here? Thanks!

**Comment by yugangw-msft** [comment]
@lmazuel, here is the relevant verbose log in my box:

```bash
msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/users/yugangw_microsoft.com#EXT#@AzureSDKTeam.onmicrosoft.com?api-version=1.6'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/3.5.3 (Windows-10-10.0.10586-SP0) requests/2.18.4 msrest/0.4.18 msrest_azure/0.4.15 graphrbacmanagementclient/0.31.0 Azure-SDK-For-Python AZURECLI/2.0.21'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'CommandName': 'ad user show'
msrest.http_logger :     'x-ms-client-request-id': '3fb3eb6c-bdda-11e7-9ccd-f4b7e2e85440'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'private'
msrest.http_logger :     'Content-Type': 'application/json; odata=verbose'
msrest.http_logger :     'Server': 'Microsoft-IIS/8.5'
msrest.http_logger :     'ocp-aad-diagnostics-server-name': '7akEoJBB3jXdCcddmuqIriGupZolWpVIrAvUTJndNgo='
msrest.http_logger :     'request-id': 'f0a723df-6e3b-48c3-844f-eab8badfc2aa'
msrest.http_logger :     'client-request-id': 'b48e6918-1277-409a-8f61-30d89c8bb92a'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Access-Control-Allow-Origin': '*'
msrest.http_logger :     'X-Powered-By': 'ASP.NET, ASP.NET'
msrest.http_logger :     'Duration': '349835'
msrest.http_logger :     'Date': 'Tue, 31 Oct 2017 01:24:32 GMT'
msrest.http_logger :     'Content-Length': '183'
msrest.http_logger : Response content:
msrest.http_logger : b'{"odata.error":{"code":"Request_DataContractVersionMissing","message":{"lang":"en","value":"The specified api-version is invalid. The value must exactly match a supported version."}}}'
msrest.exceptions : The specified api-version is invalid. The value must exactly match a supported version.
```

**Comment by lmazuel** [comment]
In my understanding, following this link:
https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/users-operations#performing-rest-operations-on-users

> /users/{user_id} targets an individual user in your tenant. You specify the user_id either as the object ID (GUID) or the user principal name (UPN) of the target user. You can use this resource path to get the declared properties of a user, to modify the declared properties of a user, or to delete a user. **Note: For an external user, you must specify the user’s object ID (GUID).**

If I understand correctly and "external user" == "guest user", even encoding the URL it will not work :/

But I didn't actually tried, so let me try first if it works.

**Comment by yugangw-msft** [comment]
I tried with encoding through fiddler and it worked
`/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/users/yugangw_microsoft.com%23EXT%23%40AzureSDKTeam.onmicrosoft.com?api-version=1.6 HTTP/1.1`
My concern is whether we are encoding everything which can appear as part of the url. I think we should

**Comment by lmazuel** [comment]
The Swagger explicitly says to do NOT encode:
https://github.com/Azure/azure-rest-api-specs/blob/8844dc849f917785e7722e4fe492dd8143c111a7/specification/graphrbac/data-plane/1.6/graphrbac.json#L1235

I need to test a little more, since changing this behavior will impact all SDK

**Comment by yugangw-msft** [comment]
Yep, this is why I originally asked whether the spec should change. Please give it enough thinking :)

**Comment by lmazuel** [comment]
Note that you can workaround this by encoding yourself whatever data the user passes to "az ad user show". Since the SDK will never touch the string and pass it "as-is". If in a future version, I decide to finally encode the string, you will just have to remove the code to avoid double-encoding.

**Comment by lmazuel** [comment]
```shell
> az ad user create --user-principal-name lmazuel#EXT@AzureSDKTeam.onmicrosoft.com --display-name LMazuel#TEST --password Hush456!
{
  "displayName": "LMazuel#TEST",
  "mail": null,
  "mailNickname": "lmazuel#EXT",
  "objectId": "beef7378-be23-4942-bea9-8a1a61fe6b22",
  "objectType": "User",
  "signInName": null,
  "usageLocation": null,
  "userPrincipalName": "lmazuel#EXT@AzureSDKTeam.onmicrosoft.com"
}
> az ad user show --upn-or-object-id beef7378-be23-4942-bea9-8a1a61fe6b22
{
  "displayName": "LMazuel#TEST",
  "mail": null,
  "mailNickname": "lmazuel#EXT",
  "objectId": "beef7378-be23-4942-bea9-8a1a61fe6b22",
  "objectType": "User",
  "signInName": null,
  "usageLocation": null,
  "userPrincipalName": "lmazuel#EXT@AzureSDKTeam.onmicrosoft.com"
}
> az ad user show --upn-or-object-id lmazuel#EXT@AzureSDKTeam.onmicrosoft.com
The specified api-version is invalid. The value must exactly match a supported version.
Traceback (most recent call last):
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\commands\__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\commands\__init__.py", line 630, in _execute_command
    raise client_exception
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\commands\__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\util.py", line 49, in empty_on_404
    raise ex
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\cli\core\commands\__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Users\lmazuel\Git\AzureCli\lib\site-packages\azure\graphrbac\operations\users_operations.py", line 220, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: The specified api-version is invalid. The value must exactly match a supported version.
> az ad user show --upn-or-object-id lmazuel%23EXT%40AzureSDKTeam.onmicrosoft.com
{
  "displayName": "LMazuel#TEST",
  "mail": null,
  "mailNickname": "lmazuel#EXT",
  "objectId": "beef7378-be23-4942-bea9-8a1a61fe6b22",
  "objectType": "User",
  "signInName": null,
  "usageLocation": null,
  "userPrincipalName": "lmazuel#EXT@AzureSDKTeam.onmicrosoft.com"
}
```

**Comment by lmazuel** [comment]
@yugangw-msft Since encoding manually when calling the CLI works, any fix might break people that figured this out and manually encoded the call :/
Thoughts?

**Comment by lmazuel** [comment]
I tried using online GraphAD tester:
https://msdn.microsoft.com/Library/Azure/Ad/Graph/api/users-operations#GetAUser
![image](https://user-images.githubusercontent.com/1050156/32237393-1697b97e-be22-11e7-8cb5-959f247108ce.png)

The official RestAPI tester is encoding the UPN, so I'm 100% sure now that the Swagger is incorrect.

**Comment by yugangw-msft** [comment]
> @yugangw-msft Since encoding manually when calling the CLI work, any fix might break people that figured this out and manually encoded the call :/

Agreed. We should not workaround in CLI

**Comment by lmazuel** [comment]
Fixed in https://pypi.python.org/pypi/azure-graphrbac/0.33.0

**Comment by troydai** [comment]
@lmazuel can we close issue? Is there any pending action on CLI side?

**Comment by lmazuel** [comment]
@troydai , yes CLI needs to update the dependency from 0.31.0 to 0.33.0 and check that everything is ok. Best scenario it's just a dependency update, but since it's critical package that impact a lot of commands, should be done carefully.

**Comment by troydai** [comment]
@yugangw-msft are you taking up the CLI side action?

**Comment by yugangw-msft** [comment]
CLI has been updated to use newer graphrabc package. 
Please reactivate if you still see the issue.
