### ISSUE TITLE
'az monitor diagnostic-settings create' gives 'HTTPError' object has no attribute 'message''

### ISSUE THREAD

**Issue by jochenvw** [Azure/azure-cli#4856]
Hi all,

I'm trying to configure my CosmosDB to log against Log Analytics. Pretty much the scenario described here: [https://docs.microsoft.com/en-us/azure/cosmos-db/logging](https://docs.microsoft.com/en-us/azure/cosmos-db/logging) but using the new CLI.

I think the command I need is the following:
`az monitor diagnostic-settings create --resource-id "[ID]" --resource-group "[GROUP]" --workspace "WORKSPACEID"`

But that gives me the following exception:
```
'HTTPError' object has no attribute 'message'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\monitor\custom.py", line 381, in create_diagnostics_settings
    return client.create_or_update(target_resource_id, parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\monitor\operations\service_diagnostic_settings_operations.py", line 149, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: 404 Client Error: Not Found for url: https://management.azure.com/%[stuff]%2Fproviders%2FMicrosoft.DocumentDb%2FdatabaseAccounts%2Fjvwcosmos/providers/microsoft.insights/diagnosticSettings/service?api-version=2016-09-01

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azclishell\app.py", line 623, in cli_execute
    result = self.app.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\monitor\_exception_handler.py", line 11, in monitor_exception_handler
    if hasattr(ex, 'inner_exception') and 'MonitoringService' in ex.inner_exception.message:
AttributeError: 'HTTPError' object has no attribute 'message'
```

Screenshot:

![image](https://user-images.githubusercontent.com/17111555/32605299-3d8210ee-c551-11e7-9920-823e94259881.png)

Running this on Windows 10 with latest CLI installed - and was also able to reproduce in cloud BASH from within the portal.

![image](https://user-images.githubusercontent.com/17111555/32605427-a3e2cebe-c551-11e7-9331-0dca0c0dd402.png)

**Comment by troydai** [comment]
@jochenvw thank you for reporting this issue. The message you got came from an issue of CLI which prevents the error message from being interrupted correctly. The root cause is [SDK issue 1556](https://github.com/Azure/azure-sdk-for-python/issues/1556)

The issue is addressed recently but not released yet. The next release is on 2017/11/15.

Beneath it, the error message hides the real issue seems to be a 404 error. For that could you please double check if the resources referenced in the command exist and the identifier are in the correct format?

**Comment by tjprescott** [comment]
This fix should have been released already. Please reopen if this is still an issue.
