### ISSUE TITLE
az login ERROR CompiledFFI object returned NULL without setting an error

### ISSUE THREAD

**Issue by berney** [Azure/azure-cli#4884]
I try to login using `az login` and I get this error: -

```
alpine:~$ docker run --rm  azuresdk/azure-cli-python az login
ERROR: <built-in method callback of CompiledFFI object at 0x69cd549ff870> returned NULL without setting an error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/profile/custom.py", line 130, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 134, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/_profile.py", line 614, in find_through_interactive_flow
    code = context.acquire_user_code(resource, _CLIENT_ID)
  File "/usr/local/lib/python3.5/site-packages/adal/authentication_context.py", line 244, in acquire_user_code
    return code_request.get_user_code_info(language)
  File "/usr/local/lib/python3.5/site-packages/adal/code_request.py", line 66, in get_user_code_info
    return self._get_user_code_info(oauth_parameters)
  File "/usr/local/lib/python3.5/site-packages/adal/code_request.py", line 46, in _get_user_code_info
    return client.get_user_code_info(oauth_parameters)
  File "/usr/local/lib/python3.5/site-packages/adal/oauth2_client.py", line 293, in get_user_code_info
    verify=self._call_context.get('verify_ssl', None))
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 274, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/usr/local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 400, in verify_mode
    _verify_callback
  File "/usr/local/lib/python3.5/site-packages/OpenSSL/SSL.py", line 971, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/usr/local/lib/python3.5/site-packages/OpenSSL/SSL.py", line 247, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: <built-in method callback of CompiledFFI object at 0x69cd549ff870> returned NULL without setting an error
```

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Azure CLI Version: -

```
$ docker run --rm  azuresdk/azure-cli-python az --version
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Legal docs and information: aka.ms/AzureCliLegal
```

I am using Docker.

```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
azuresdk/azure-cli-python   latest              5ca2862fa69d        2 weeks ago         352MB
```

Docker version 17.07.0-ce.

```
alpine:~$ docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.9
 Git commit:   4988d311db
 Built:        Thu Sep 28 08:20:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   v17.07.0-ce
 Built:        Thu Sep 28 08:20:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

More Docker info: -

```
alpine:~$ docker info
Containers: 15
 Running: 1
 Paused: 0
 Stopped: 14
Images: 226
Server Version: 17.07.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.9.60-0-hardened
Operating System: Alpine Linux v3.6
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.771GiB
Name: alpine
ID: M3J7:25ME:GWPN:YSYP:VODN:HEES:DG6I:GRMJ:ARVB:SB62:ZNZL:NX6Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: berne
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Running on Alpine Linux 3.6.2 `Linux alpine 4.9.60-0-hardened #1-Alpine SMP Fri Nov 3 14:13:45 GMT 2017 x86_64 Linux`. It's a VM running the virt-hardened version of Alpine Linux.

This is my first time trying Azure CLI, not off to a good start 💩

**Comment by derekbekoe** [comment]
Does `docker run --it  azuresdk/azure-cli-python bash` then `az login` work?

**Comment by berney** [comment]
No, same crash if I start bash then python. I will try another Linux. My guess is it's related to the hardening features enabled in the kernel like GR Security / PAX.

**Comment by berney** [comment]
I built a custom azure-cli Docker image. I had tried compiling libffi with PAX kernel support but I still go the issue. So I resorted to marking the python executable to disable MPROTECT using `paxctl`, after this I can now run the image. I then tried enabling EMUTRAMP instead of disabling MPROTECT and that also worked. My image is berne/azure-cli, it's on Docker Hub. It's leaner than the official one but some things are broken like interactive mode. I'm not sure what dependencies are missing.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
I tested on an Azure VM running Ubuntu 18.04.4 LTS with the latest [Docker Engine - Community for Ubuntu](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and followed [Run Azure CLI in a Docker container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest). `az login` works correctly. 

`azuresdk/azure-cli-python` is not maintained anymore:

```
$ sudo docker run --rm azuresdk/azure-cli-python az -v
azure-cli (2.0.57)
```

Please install the latest version from `mcr.microsoft.com/azure-cli`. If you are still facing the issue, please let us know the system version and docker version you are using. Thanks.
