### ISSUE TITLE
Scenario tests all failing trying to decode `None` as JSON

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-cli#4886]
I'm trying to add to the scenario tests for ACS/AKS, but they all error out for me now. This same setup was working fine previously, so I'm wondering if some underlying library broke, or if any `az` folks have ideas.

---

### Environment summary

macOS High Sierra 10.13.1, python 3.6.3 installed with `brew`, azure-cli checked out from GitHub and virtualenv configured as per developer docs. I'm running the HEAD of the `dev` branch. Here's one example, but all ScenarioTests fail similarly:

```bash
$ run_tests --module acs --test test_aks_commands.AzureKubernetesServiceScenarioTest.test_aks_create_default_service
Run automation
Modules: acs
Drive test by unittest
E
======================================================================
ERROR: test_aks_create_default_service (azure.cli.command_modules.acs.tests.test_aks_commands.AzureKubernetesServiceScenarioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/matt/Projects/azure-cli/env/lib/python3.6/site-packages/azure_devtools/scenario_tests/preparers.py", line 60, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "/Users/matt/Projects/azure-cli/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/test_aks_commands.py", line 30, in test_aks_create_default_service
    JMESPathCheck('properties.provisioningState', 'Succeeded')
  File "/Users/matt/Projects/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/base.py", line 76, in cmd
    return execute(command, expect_failure=expect_failure).assert_with_checks(checks)
  File "/Users/matt/Projects/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/base.py", line 128, in assert_with_checks
    c(self)
  File "/Users/matt/Projects/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/checkers.py", line 34, in __call__
    json_value = execution_result.get_output_in_json()
  File "/Users/matt/Projects/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/base.py", line 134, in get_output_in_json
    self.json_value = json.loads(self.output)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 12.038s

FAILED (errors=1)
```

**Comment by derekbekoe** [comment]
Has your default output type changed?
Change it back to json.
Does that work?

**Comment by mboersma** [comment]
@derekbekoe that's it exactly--my bad. I changed my `az` defaults recently because table output is so useful, not realizing it affects testing:

```
$ cat ~/.azure/config 
[cloud]
name = AzureCloud

[core]
output = table
```

Removing `output = table` reverts to JSON and everything's happy again. Thanks!

**Comment by derekbekoe** [comment]
It's not great that modifying the default output type breaks tests.
https://github.com/Azure/azure-cli/issues/2283
cc: @troydai @tjprescott

**Comment by mboersma** [comment]
I could add an explicit `-o json` to the scenario tests as a workaround.

**Comment by derekbekoe** [comment]
I would rather not have this in the tests.
