### ISSUE TITLE
Create group with mail nickname other then null fails

### ISSUE THREAD

**Issue by jan-gazda** [Azure/azure-cli#4896]
---

### Environment summary

Install Method: `pip`
Shell: `bash`
OS: `OSx`

```
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

Python (Darwin) 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

Does anybody have any idea why is this failing?

First command went through without problems:

```
(azure)$ az ad group create --display-name="_cli_group1" --mail-nickname="null"
{
  "displayName": "_cli_group1",
  "mail": null,
  "objectId": "6532bb66-a58a-4ac6-9de0-398eeea46400",
  "objectType": "Group",
  "securityEnabled": true
}
```

However second command gave me an exception:

```
(azure) $ az ad group create --display-name="_cli_group2" --mail-nickname="cli2@payconiq.com"

Invalid value specified for property 'mailNickname' of resource 'Group'.
Traceback (most recent call last):
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _execute_command
    raise client_exception
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 626, in _execute_command
    reraise(*sys.exc_info())
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Users/jangazda/.virtualenvs/jupyter/lib/python3.6/site-packages/azure/graphrbac/operations/groups_operations.py", line 333, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Invalid value specified for property 'mailNickname' of resource 'Group'.
```

**Comment by yugangw-msft** [comment]
Looks like you can't have a nick name with `@` or space

**Comment by yugangw-msft** [comment]
please reactivate if you are still blocked
