### ISSUE TITLE
"az ad sp show --id" gives message that Resource does not exist, also Python errors

### ISSUE THREAD

**Issue by isaacsgi** [Azure/azure-cli#4899]
For Service Principals that I can see in my Azure Portal, AZ CLI 2.0 says Resource is not found.  I am using the Object ID for the Service Principal that I copy from the Azure Portal.

Command I'm using: az ad sp show --id "<ObjectID>"

Errors:
Resource xxx does not exist or one of its queried reference-property objects are not present.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 630, in _execute_command
    raise client_exception
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\util.py", line 49, in empty_on_404
    raise ex
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 479, in show_service_principal
    return client.get(object_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\graphrbac\operations\service_principals_operations.py", line 276, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Resource  xxx does not exist or one of its queried reference-property objects are not present.

### Environment summary
Running on Windows 10, using msi install of az cli 2.0 

az --version
azure-cli (2.0.21)

acr (2.0.15)
acs (2.0.19)
appservice (0.1.20)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.13)
core (2.0.21)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.12)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.18)
role (2.0.14)
servicefabric (0.0.6)
sql (2.0.15)
storage (2.0.19)
vm (2.0.18)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxxx\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yugangw-msft** [comment]
Please copy and use the `Application Id` field, instead of the "Object Id". What you saw in the Portal is the `Graph Application` which is closely related with SP, but a different entity. `Application ID` is a shared property between them, but not with Object ID

**Comment by isaacsgi** [comment]
Where would I see the Application Id

**Comment by yugangw-msft** [comment]
Based on the context, the best way is to first run `az ad app show --id "<same id you tried>"`. In the output, take the `appId` field value and use it with the `az ad sp show --id` you tried. Please notice the 2 command paths diffs at `app` vs `sp`
In portal, you can see it through "Azure Active Directory" blad
![image](https://user-images.githubusercontent.com/6014209/32908276-f3b2f5ca-cab7-11e7-8132-b4f6cacc13f8.png)

**Comment by isaacsgi** [comment]
I need this for a User type of Service Principal

**Comment by yugangw-msft** [comment]
I believe we have exchanged through emails, that using both object id and app id should work. The case which doesn't work was the object id of application, which I don't think we need to support as we have not got other users who ran into the same issue.
