### ISSUE TITLE
`az webapp log tail` with slot option always get 403 forbidden error

### ISSUE THREAD

**Issue by mattohoh** [Azure/azure-cli#4953]
---

### Environment summary
Windows 10
Install by MSI
Powershell
Azure CLI 2.0.21

I have multiple webapp, every time I tried to get log stream of slots of the webapps, I got the following errors
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\appservice\custom.py", line 1246, in _get_log
    url, r.status, r.reason))
azure.cli.core.util.CLIError: Failed to connect to 'https://xxx-slot.scm.azurewebsites.net/logstream' with status code '403' and reason 'Forbidden'
```

I tried it on every my webapp, always get the same results, but every thing is ok on the production slots.

**Comment by wy193777** [comment]
Log steam on browser also always got HTML 403. Not sure is they are the same issue.

**Comment by panchagnula** [comment]
@wy193777 i am not sure what you mean by Log stream on browser? the bug in the CLI was we were not using the credentials of the slot for obtaining the log stream & this will be fixed soon.

**Comment by Kannaj** [comment]
I'm unfortunately still seeing this error
```
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1222, in _get_log
    url, r.status, r.reason))
azure.cli.core.util.CLIError: Failed to connect to 'https://xxx.scm.azurewebsites.net/logstream' with status code '403' and reason 'Forbidden'

```

**Comment by panchagnula** [comment]
@Kannaj this means you don't have the right RBAC access on the app to access, that is failing connecting to your scm site. One thing you can try is navigate to your scm site using this link & see if you have access https://xxx.scm.azurewebsites.net

**Comment by Kannaj** [comment]
@panchagnula  - yes , i do have access to via KUDU. Currently streaming logs from there but its really slow :(
