### ISSUE TITLE
Error Trying to Create Storage Account

### ISSUE THREAD

**Issue by akamalov** [Azure/azure-cli#4954]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
Install type: homebrew
CLI version: 2.0.21
OS: OSX Sierra 10.12.6

```
Command and failure:

```
az storage account create --name storacc1 --resource-group storGRP1 --location eastus --sku Standard_LRS --encryption blob
'NoneType' object has no attribute 'Include'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 177, in execute
    self.configuration.load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 50, in load_params
    commands.load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 404, in load_params
    import_module(module_to_load).load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 10, in load_params
    import azure.cli.command_modules.storage._params  # pylint: disable=redefined-outer-name, unused-variable
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 251, in <module>
    delete_snapshot_types = {'include': DeleteSnapshot.Include, 'only': DeleteSnapshot.Only}
AttributeError: 'NoneType' object has no attribute 'Include'
```

**Comment by troydai** [comment]
@akamalov , thank you for taking time reporting this issue. However, I'm not able to repo it in the same environment. With that being said, I notice through the log, it indicates a basic component can't be parsed from the SDK. It could be caused by glitch during the brew installation. Could you please try uninstall the azure-cli and install again and keep an eye on the brew installation output?

**Comment by akamalov** [comment]
@troydai 

Thanks for the response. Did uninstall / install, the same result:

```
az storage account create --name storacc5 --resource-group storGRP5 --location eastus --sku Standard_LRS --encryption blob
'NoneType' object has no attribute 'Include'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 177, in execute
    self.configuration.load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 50, in load_params
    commands.load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 404, in load_params
    import_module(module_to_load).load_params(command)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 10, in load_params
    import azure.cli.command_modules.storage._params  # pylint: disable=redefined-outer-name, unused-variable
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/command_modules/storage/_params.py", line 251, in <module>
    delete_snapshot_types = {'include': DeleteSnapshot.Include, 'only': DeleteSnapshot.Only}
AttributeError: 'NoneType' object has no attribute 'Include'
```

I'll try to install it using pip, see if it makes any difference.

Alex

**Comment by derekbekoe** [comment]
```
$ export PYTHONPATH="/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages"
$ python3.6 -m pip freeze
```
Or `python3` if `python3.6` doesn't work.

Also, is the CLI or any Azure SDKs installed elsewhere on the machine?

**Comment by akamalov** [comment]
```
$ export PYTHONPATH="/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages"
$ python3.5 -m pip freeze
adal==0.4.7
applicationinsights==0.11.1
argcomplete==1.9.2
asn1crypto==0.23.0
azure-batch==4.0.0
azure-batch-extensions==1.0.1
azure-cli==2.0.21
azure-cli-acr==2.0.15
azure-cli-acs==2.0.19
azure-cli-appservice==0.1.20
azure-cli-backup==1.0.3
azure-cli-batch==3.1.7
azure-cli-batchai==0.1.3
azure-cli-billing==0.1.6
azure-cli-cdn==0.0.10
azure-cli-cloud==2.0.10
azure-cli-cognitiveservices==0.1.9
azure-cli-command-modules-nspkg==2.0.1
azure-cli-component==2.0.8
azure-cli-configure==2.0.12
azure-cli-consumption==0.1.6
azure-cli-container==0.1.13
azure-cli-core==2.0.21
azure-cli-cosmosdb==0.1.15
azure-cli-dla==0.0.15
azure-cli-dls==0.0.18
azure-cli-eventgrid==0.1.5
azure-cli-extension==0.0.6
azure-cli-feedback==2.0.6
azure-cli-find==0.2.7
azure-cli-interactive==0.3.11
azure-cli-iot==0.1.14
azure-cli-keyvault==2.0.14
azure-cli-lab==0.0.13
azure-cli-monitor==0.0.12
azure-cli-network==2.0.18
azure-cli-nspkg==3.0.1
azure-cli-profile==2.0.15
azure-cli-rdbms==0.0.9
azure-cli-redis==0.2.10
azure-cli-reservations==0.1.0
azure-cli-resource==2.0.18
azure-cli-role==2.0.14
azure-cli-servicefabric==0.0.6
azure-cli-sql==2.0.15
azure-cli-storage==2.0.19
azure-cli-vm==2.0.18
azure-common==1.1.8
azure-datalake-store==0.0.17
azure-graphrbac==0.31.0
azure-keyvault==0.3.7
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.1.0
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==0.30.2
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==0.1.0
azure-mgmt-containerinstance==0.2.0
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==2.0.0
azure-mgmt-cosmosdb==0.2.1
azure-mgmt-datalake-analytics==0.2.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.2.0
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.2.0
azure-mgmt-iothub==0.4.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-monitor==0.3.0
azure-mgmt-network==1.5.0rc3
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==4.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.1
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.3
azure-mgmt-storage==1.4.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-monitor==0.3.0
azure-multiapi-storage==0.1.6
azure-nspkg==2.0.0
azure-storage==0.34.3
bcrypt==3.1.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.3
humanfriendly==4.4.1
idna==2.6
isodate==0.6.0
jmespath==0.9.3
keyring==10.5.0
mock==2.0.0
msrest==0.4.18
msrestazure==0.4.16
oauthlib==2.0.6
paramiko==2.3.1
pbr==3.1.1
prompt-toolkit==1.0.15
pyasn1==0.3.7
pycparser==2.18
pydocumentdb==2.3.0
Pygments==2.2.0
PyJWT==1.5.3
PyNaCl==1.2.0
pyOpenSSL==17.3.0
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
scp==0.10.2
SecretStorage==2.3.1
six==1.11.0
sshtunnel==0.1.2
tabulate==0.7.7
urllib3==1.22
vsts-cd-manager==1.0.1
wcwidth==0.1.7
Whoosh==2.7.4
xmltodict==0.11.0
```

**Comment by akamalov** [comment]
Do we have any update on this ?

**Comment by troydai** [comment]
does the pip installed CLI works for you? Did you install it in a virtualenv? Unfortunately we can't repo your issue and our hands are tied.

**Comment by troydai** [comment]
@chewong

**Comment by troydai** [comment]
@akamalov We're not able to reproduce your issue and haven't heard from anyone else of a similar issue. The logs you shared previously indicate there is an unmatched SDK installed causing the problem. Unfortunately, there is little we can do now. 

Please try to install the latest Azure CLI through other channels, apt or brew depends on your environment, instead of pip.

I'm going to close this issue for now. Please feel free if the issue persists and you have other logs or facts to share. Thanks for reporting this issue.
