### ISSUE TITLE
az role definition delete failed

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#4976]
### Environment summary

* Install Method: brew
* CLI version`azure-cli (2.0.21)`
 * OS version: mac high siera
* Shell Type: bash

When trying to delete a role, I've encountered an error: 
```
'NoneType' object has no attribute 'error'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 112, in delete_role_definition
    definitions_client.delete(role_definition_id=r.name, scope=scope)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/azure/mgmt/authorization/operations/role_definitions_operations.py", line 84, in delete
    exp = CloudError(response)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 148, in __init__
    self._build_error_data(response)
  File "/usr/local/Cellar/azure-cli/2.0.21/libexec/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 164, in _build_error_data
    self.error = self.deserializer('CloudErrorRoot', response).error
AttributeError: 'NoneType' object has no attribute 'error'
```

I think there is a problem with Azure, I played with the role (delete/create/update) but no changes on the UI.

**Comment by yugangw-msft** [comment]
This is a service end issue, since we have not further reports, let us close it
