### ISSUE TITLE
(Error handling) webapp/ function app create command should validate if the ASP/RG exist & show appropriate error message

### ISSUE THREAD

**Issue by liv3d** [Azure/azure-cli#5008]
### Stack trace
```
dan@Azure:~$ az webapp create --resource-group resource-group --plan hosting-plan-eun --name site-name --deployment-container-image-name fiorix/freegeoip:latest
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _execute_command
    exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 63, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 52, in create_webapp
    is_linux = plan_info.reserved
AttributeError: 'NoneType' object has no attribute 'reserved'
dan@Azure:~$
```

The expected output was a json object similar to the one [within the docs](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#deploy-app-to-azure)

---

### Environment summary

This is happened with both the az client under Windows using powershell (`azure-cli (2.0.21)`) and under the Bash Shell within the Azure web portal.

```
dan@Azure:~$ az --version
azure-cli (2.0.21)

acr (2.0.15)
acs (2.0.19)
appservice (0.1.20)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.13)
core (2.0.21)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.12)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.18)
role (2.0.14)
servicefabric (0.0.6)
sql (2.0.15)
storage (2.0.19)
vm (2.0.18)

Python location '/opt/az/bin/python3'
Extensions directory '/home/dan/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Nov 10 2017, 16:23:17)
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal

dan@Azure:~$
```

**Comment by ahmedelnably** [comment]
@liv3d can you please check if the app service plan that you are using is a linux app service plan or not?

**Comment by liv3d** [comment]
@ahmedelnably So, I retried now that I've got home by copy/pasting names out of the portal and it worked as expected.

What I believe I may have done earlier on today is typo the resource group name as testing that now does give the stack trace above.

**Comment by yugangw-msft** [comment]
It is a fall out from SDK/azure-mgmt-web breaking change that 404 is not longer treated as an error. I have updated CLI to add a client side verification for this. Please use newer CLI release
