### ISSUE TITLE
Azure password not working if started with special characters

### ISSUE THREAD

**Issue by jimyjohny** [Azure/azure-cli#5058]
Azure login doesn't works if the password is started with special characters. (same works with azure 0.10.1)

OS = Centos 6.x
az version = azure-cli (2.0.22 )

root@xxx:~  /opt/rh/python27/root/usr/bin/az login -u  username@domain.com -p @X123456x!
[Errno 2] No such file or directory: 'X123456x!'
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 143, in execute
    argv = Application._expand_file_prefixed_files(unexpanded_argv)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 310, in _expand_file_prefixed_files
    return list([Application._expand_file_prefix(arg) for arg in argv])
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 306, in _expand_file_prefix
    return Application._maybe_load_file(arg_split[0])
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 295, in _maybe_load_file
    return Application._load_file(poss_file)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/application.py", line 318, in _load_file
    allow_binary=True)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/azure/cli/core/util.py", line 132, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
  File "/opt/rh/python27/root/usr/lib64/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'X123456x!'
root@xxx:~

**Comment by yugangw-msft** [comment]
The special character gets handled by shell. To prevent that, please apply quote:
```bash
az login -u username@domain.com -p '@x123456x!'
```

**Comment by jimyjohny** [comment]
Its already tried using both single and double quotes. The result is same error message.

**Comment by yugangw-msft** [comment]
@jimyjohny, thanks for the information, this could be caused by that the CLI pre-processed the `@` character with the assumption that the subsequent string would be a file name
