### ISSUE TITLE
Account: avoid crashing on entities w/o state information  

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5136]
An account/subscription from ASM world through `azure login` (CLI 1.0) will not have state info.

mluser@mradmilaub3:~$ az account list
'state'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 37, in list_subscriptions
    enabled_ones = [s for s in subscriptions if s['state'] == 'Enabled']
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 37, in <listcomp>
    enabled_ones = [s for s in subscriptions if s['state'] == 'Enabled']
KeyError: 'state'

**Comment by yugangw-msft** [comment]
fixed
