### ISSUE TITLE
az storage account list gives error "Standard_LRS is not valid enum" 

### ISSUE THREAD

**Issue by stacker2017** [Azure/azure-cli#5149]
---

```
OS version: Linux ubuntu-VirtualBox 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

pip freeze:
adal==0.4.7
adium-theme-ubuntu==0.3.4
ansible==2.4.2.0
applicationinsights==0.11.1
argcomplete==1.9.3
asn1crypto==0.24.0
awx==3.2.2
azure==2.0.0
azure-batch==4.0.0
azure-batch-extensions==1.0.1
azure-cli==2.0.23
azure-cli-acr==2.0.17
azure-cli-acs==2.0.22
azure-cli-advisor==0.1.0
azure-cli-appservice==0.1.22
azure-cli-backup==1.0.3
azure-cli-batch==3.1.7
azure-cli-batchai==0.1.3
azure-cli-billing==0.1.6
azure-cli-cdn==0.0.10
azure-cli-cloud==2.0.10
azure-cli-cognitiveservices==0.1.9
azure-cli-command-modules-nspkg==2.0.1
azure-cli-configure==2.0.12
azure-cli-consumption==0.2.0
azure-cli-container==0.1.15
azure-cli-core==2.0.23
azure-cli-cosmosdb==0.1.15
azure-cli-dla==0.0.15
azure-cli-dls==0.0.18
azure-cli-eventgrid==0.1.5
azure-cli-extension==0.0.6
azure-cli-feedback==2.0.6
azure-cli-find==0.2.7
azure-cli-interactive==0.3.11
azure-cli-iot==0.1.15
azure-cli-keyvault==2.0.15
azure-cli-lab==0.0.13
azure-cli-monitor==0.0.13
azure-cli-network==2.0.19
azure-cli-nspkg==3.0.1
azure-cli-profile==2.0.16
azure-cli-rdbms==0.0.9
azure-cli-redis==0.2.10
azure-cli-reservations==0.1.0
azure-cli-resource==2.0.19
azure-cli-role==2.0.15
azure-cli-servicefabric==0.0.7
azure-cli-sql==2.0.17
azure-cli-storage==2.0.21
azure-cli-vm==2.0.20
azure-common==1.1.8
azure-datalake-store==0.0.17
azure-graphrbac==0.31.0
azure-keyvault==0.3.7
azure-mgmt==1.0.0
azure-mgmt-advisor==0.1.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.1.0
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==0.30.2
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==3.1.0rc2
azure-mgmt-consumption==1.0.0
azure-mgmt-containerinstance==0.2.0
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.0
azure-mgmt-cosmosdb==0.2.1
azure-mgmt-datalake-analytics==0.2.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.2.0
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-documentdb==0.1.3
azure-mgmt-eventgrid==0.2.0
azure-mgmt-iothub==0.4.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==4.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.1
azure-mgmt-scheduler==1.1.3
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.4
azure-mgmt-storage==1.5.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-multiapi-storage==0.1.7
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.34.3
bcrypt==3.1.4
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.4
ecdsa==0.13
enum34==1.1.6
funcsigs==1.0.2
futures==3.2.0
gyp==0.1
httplib2==0.9.1
humanfriendly==4.4.1
idna==2.6
ipaddress==1.0.19
isodate==0.6.0
Jinja2==2.8
jmespath==0.9.3
keyring==10.5.1
MarkupSafe==0.23
meld3==1.0.2
mercurial==3.7.3
mock==2.0.0
monotonic==1.4
msrest==0.4.22
msrestazure==0.4.19
oauthlib==2.0.6
packaging==16.8
paramiko==2.4.0
pathlib==1.0.1
pathlib2==2.3.0
pbr==3.1.1
prompt-toolkit==1.0.15
psycopg2==2.6.1
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
pydocumentdb==2.3.0
Pygments==2.2.0
PyJWT==1.5.3
PyNaCl==1.2.1
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-apt==1.1.0b1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
scandir==1.6
scp==0.10.2
SecretStorage==2.3.1
six==1.11.0
sshtunnel==0.1.2
supervisor==3.2.0
tabulate==0.7.7
unity-lens-photos==1.0
urllib3==1.22
virtualenv==15.0.1
vsts-cd-manager==1.0.1
wcwidth==0.1.7
Whoosh==2.7.4
xmltodict==0.11.0
```

azure cli version:
```azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.23)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
vm (2.0.20)

Python location '/usr/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609]

```

when I type az storage account list I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 381, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 640, in _execute_command
    raise client_exception
DeserializationError: u'Standard_LRS' is not valid value for enum <enum 'SkuName'>
```

**Comment by williexu** [comment]
Hi, are you still seeing this problem? If so, can you try updating your installation of the CLI and retrying? 
Make sure to run Scripts/dev_setup.py as well.

**Comment by stacker2017** [comment]
Thanks the is resolved, you can find further info in
https://github.com/Azure/msrest-for-python/issues/75
