### ISSUE TITLE
Parameter 'LogProfileResource.retention_policy' can not be None.

### ISSUE THREAD

**Issue by paulpc** [Azure/azure-cli#5151]
### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build): N/A
 CLI version (`az --version`): (web shell) az --version
azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.23)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
vm (2.0.20)

OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  Web Shell
When trying to create a new logger profile, it seems to just error out with this message:
Command:
```
az monitor log-profiles create --debug -n default --days 0 --categories 'Write' 'Delete' 'Actions' --enabled false -l [redacted] --locationsaustraliaeast australiasoutheast brazilsouth canadacentral canadaeast centralindia centralus eastasia eastus eastus2 japaneast japanwest koreacentral koreasouth northcentralus northeurope southcentralus southindia southeastasia uksouth ukwest westcentralus westeurope westindia westus westus2 global --service-bus-rule-id [redacted] --storage-account-id [redacted]
```
Application event 'CommandParser.Parsed' with event data {'command': 'monitor log-profiles create', 'args': Namespace(_command_package='monitor', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az monitor log-profiles create', usage=None, description='Create or update a log profile in Azure Monitoring REST API.', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[<function get_complex_argument_processor.<l [...]
Getting management service client client_type=MonitorManagementClient
msrest.exceptions : Parameter 'LogProfileResource.retention_policy' can not be None.
Parameter 'LogProfileResource.retention_policy' can not be None.

**Comment by sebastus** [comment]
+1 - trying to create a log profile directing activity logs to an event hub using az cli v2.

**Comment by OguzPastirmaci** [comment]
Having the same issue.

Tried az cli version 2.0.21, 2.0.22, 2.0.23, and 2.0.24.

**Comment by sagarchavan6210** [comment]
I am also getting the same issue while creating log-profiles. 
`az monitor log-profiles create --categories 'Write' --enabled ENABLED --days 1095 --location North Europe --locations East US,West US,South Central US,East Asia,Japan East,Southeast Asia,Japan West,North Central US,Central US,Brazil South,East US 2,Australia Southeast,Australia East --name <PROFILE NAME>`

**Comment by tjprescott** [comment]
@troydai can you take a look?

**Comment by sprab** [comment]
2.025 and 2.025 are also having the same issues:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 292, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\monitor\operations\log_profiles_operations.py", line 186, in 
create_or_update
    body_content = self._serialize.body(parameters, 'LogProfileResource')
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 474, in body
    raise errors[0]
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 179, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 557, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'LogProfileResource.retention_policy' can not be None.

**Comment by troydai** [comment]
Looking into this.

**Comment by troydai** [comment]
It's a breaking change caused by the SDK. I'll roll out a fix today.

**Comment by troydai** [comment]
PR #5498 will address this issue.
