### ISSUE TITLE
az vm image list fails

### ISSUE THREAD

**Issue by austinlparker** [Azure/azure-cli#5178]
When running az vm image list, we encounter the following error:

```
You are viewing an offline list of images, use --all to retrieve an up-to-date list
HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/apprenda/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/apprenda/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/home/apprenda/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 368, in _execute_command
    raise ex
HTTPError: HTTP Error 404: Not Found
```

We did some digging, and it appears this is occurring because the following gist (https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json) which is referenced in the specs has been made private.

Is this the appropriate repository to file such an issue? Two, could we get some sort of ETA? This is breaking our CI.

**Comment by austinlparker** [comment]
We're unable to create VM's using the CLI as well, with the same 404 error.

**Comment by johanste** [comment]
The issue should have been resolved. We intend to make sure that we are more resilient to this problem.
