### ISSUE TITLE
[2.0.24 release & stack profile] az network application-gateway ssl-policy Error

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5237]
```
$ az network application-gateway ssl-policy -h
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 265, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 1020, in __call__
    parser.print_help()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/parser.py", line 116, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/parser.py", line 175, in format_help
    is_group)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/_help.py", line 69, in show_help
    help_file = CliCommandHelpFile(delimiters, parser) if not is_group else GroupHelpFile(delimiters, parser)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/help.py", line 173, in __init__
    child.load(options)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/help.py", line 119, in load
    description = getattr(options, 'description', None)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/parser.py", line 166, in __getattribute__
    if callable(self._description) else self._description
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 344, in default_description_loader
    self._apply_doc_string(op, kwargs)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 258, in _apply_doc_string
    (path, model_name) = doc_string_source.split('#', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
I will fix this as part of #5239.
