### ISSUE TITLE
[2.0.24 release / stack-profile] 'az network watcher list' group error

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5238]
```
$ az network watcher list -h
No module named 'azure.mgmt.network.v2015_06_15.operations.network_watchers_operations'
Traceback (most recent call last):
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 241, in execute
    self.commands_loader.load_arguments(command)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 201, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 142, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 332, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 375, in get_op_handler
    op = import_module(mod_to_import)
  File "/Users/debekoe/Repos/derekbekoe-azure-cli/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.network.v2015_06_15.operations.network_watchers_operations'
```

  This appears to affect the whole group.

**Comment by tjprescott** [comment]
I will fix this as part of #5239.
