### ISSUE TITLE
az acr repository list AttributeError 'bool' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by novaterata** [Azure/azure-cli#5262]
Ubuntu 17.10 x64
azure-cli-2.0.24
I believe my ACR was empty when this happens

I run `az acr repository list -g foo -n Bar` and get the following stacktrace:

```
'bool' object has no attribute 'rstrip'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/repository.py", line 166, in acr_repository_list
    password=password)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 219, in get_access_credentials
    permission=permission)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 150, in _get_credentials
    password = _get_aad_token(login_server, only_refresh_token, repository, permission)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 35, in _get_aad_token
    login_server = login_server.rstrip('/')
AttributeError: 'bool' object has no attribute 'rstrip'

```

**Comment by novaterata** [comment]
This occurs even if there is an image in the ACR

**Comment by mmacy** [comment]
Hi @novaterata, thanks for the report. This is a known issue, reported in #5229, and there is a fix in the works (linked in that issue).

**Comment by novaterata** [comment]
@mmacy I was able to login, but that does seem to be the same issue.
