### ISSUE TITLE
'az sf cluster list' throwing exceptions instead of error messages

### ISSUE THREAD

**Issue by brusMX** [Azure/azure-cli#5279]
---

### Environment summary

Install Method - apt-get on bash on Windows
 OS version / Shell Type -  **Bash on Windows**
```bash
$ az --version

azure-cli (2.0.24)

acr (2.0.18)
acs (2.0.23)
advisor (0.1.1)
appservice (0.1.23)
backup (1.0.4)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.24)
cosmosdb (0.1.16)
dla (0.0.16)
dls (0.0.19)
eventgrid (0.1.7)
extension (0.0.7)
feedback (2.0.7)
find (0.2.8)
interactive (0.3.12)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.14)
monitor (0.0.14)
network (2.0.20)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.10)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.20)
role (2.0.16)
servicefabric (0.0.8)
sql (2.0.18)
storage (2.0.22)
vm (2.0.23)

Python location '/opt/az/bin/python3'
Extensions directory '/home/brusmx/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jan  5 2018, 21:18:08)
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
```

The command I am running is the following:
```
$ az sf cluster list 
```

```bash
list_cluster() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
TypeError: list_cluster() missing 1 required positional argument: 'client'
```

But even if I specify the resource group it shows me the error.

**Comment by tjprescott** [comment]
@QingChenmsft to take a look
