### ISSUE TITLE
az acr repository delete fails with exception

### ISSUE THREAD

**Issue by Trepliev** [Azure/azure-cli#5290]
azure-cli (2.0.24) installed via curl -L https://aka.ms/InstallAzureCli |bash on the Mac OS X.

```
az acr repository delete -n dockerregistry01 --repository aci-helloworld

'bool' object has no attribute 'rstrip'
Traceback (most recent call last):
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acr/repository.py", line 241, in acr_repository_delete
    permission='*')
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 219, in get_access_credentials
    permission=permission)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 150, in _get_credentials
    password = _get_aad_token(login_server, only_refresh_token, repository, permission)
  File "/Users/trepliev/lib/azure-cli/lib/python2.7/site-packages/azure/cli/command_modules/acr/_docker_utils.py", line 35, in _get_aad_token
    login_server = login_server.rstrip('/')
AttributeError: 'bool' object has no attribute 'rstrip'
```
SKU is Premium
I tried to add --tag and --manifest values but no luck.

Thank you for your help!

**Comment by tjprescott** [comment]
Seems related to #5229. May already be fixed.

**Comment by terjetyl** [comment]
Also get the same error on az acr repository list

v2.0.24 installed via brew

**Comment by djyou** [comment]
This is the same issue as https://github.com/Azure/azure-cli/issues/5229 and has been fixed in https://github.com/Azure/azure-cli/pull/5257. Please update to the more recent release `2.0.25`.
