### ISSUE TITLE
az aks create fails with `msrest.exceptions : User was not found.`

### ISSUE THREAD

**Issue by korovaisdead** [Azure/azure-cli#5300]
Hello,

I'm trying to create aks with 

`az aks create --resource-group rg1 --name clstr1 --node-count 1 --generate-ssh-keys `

Logged into azure with `az login` and followed all that workflow with entering the code.. 

and got the next error: 

```
User was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1296, in aks_create
    location=location, name=name)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1397, in _ensure_service_principal
    service_principal = _build_service_principal(rbac_client, cli_ctx, name, url, client_secret)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 434, in _build_service_principal
    result = create_application(rbac_client.applications, name, url, [url], password=client_secret)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1081, in create_application
    return client.create(app_create_param)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 87, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: User was not found.
```
---

### Environment summary

brew install / azure-cli (2.0.24) / MacOS 10.13.2 / bash  

```
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x10e9a2488>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10f5a1ae8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10e3707b8>, <function CLIQuery.handle_query_parameter at 0x10e392400>]
Use existing SSH public key file: /Users/Pavel/.ssh/id_rsa.pub
Getting management service client client_type=ContainerServiceClient
Getting management service client client_type=ResourceManagementClient
attempting to read file /Users/Pavel/.azure/accessTokens.json as utf-8-sig
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - Authority:Performing instance discovery: https://login.microsoftonline.com/b478ee14-30c0-4213-8802-1d577417c2f9
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - Authority:Performing static instance discovery
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - Authority:Authority validated via static instance discovery
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:finding with query: {"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "pavel.shtanko@gmail.com"}
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:Looking for potential cache entries:
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:{"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "pavel.shtanko@gmail.com"}
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:Found 4 potential entries.
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:Resource specific token found.
adal-python : 6d929abd-95d5-48c5-8f01-8a69be8f6547 - OAuth2Client:Returning token from cache lookup, AccessTokenId: b'YkCtpmt8gsRKwpLd/SOkRnD/nWj2BkUqt+yx5Yk7ciQ=', RefreshTokenId: b'eAxFnnKRLW1op4pdBE9c8oSgFEA9/HJqJHezH2P+Mx8='
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/ea5e4a4b-0a2e-41f2-82d6-2e0d90b0866c/resourcegroups/call-dev?api-version=2017-05-10 HTTP/1.1" 200 257
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/ea5e4a4b-0a2e-41f2-82d6-2e0d90b0866c/resourcegroups/call-dev?api-version=2017-05-10'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.4 (Darwin-17.3.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.4.24 msrest_azure/0.4.19 resourcemanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.24'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': 'd4099c70-f93c-11e7-b14c-34363bd2ebfc'
msrest.http_logger :     'CommandName': 'aks create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14998'
msrest.http_logger :     'x-ms-request-id': 'e553cdaa-3a0d-4eb5-9f54-9e02ef82160c'
msrest.http_logger :     'x-ms-correlation-request-id': 'e553cdaa-3a0d-4eb5-9f54-9e02ef82160c'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTEUROPE:20180114T150851Z:e553cdaa-3a0d-4eb5-9f54-9e02ef82160c'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Sun, 14 Jan 2018 15:08:51 GMT'
msrest.http_logger :     'Content-Length': '257'
msrest.http_logger : Response content:
msrest.http_logger : b'{"id":"/subscriptions/ea5e4a4b-0a2e-41f2-82d6-2e0d90b0866c/resourceGroups/bla-bla","name":"bla-bla","location":"westeurope","properties":{"provisioningState":"Succeeded"}}'
Creating service principal
msrest.serialization : Datetime with no tzinfo will be considered UTC.
msrest.serialization : Datetime with no tzinfo will be considered UTC.
attempting to read file /Users/Pavel/.azure/accessTokens.json as utf-8-sig
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - Authority:Performing instance discovery: https://login.microsoftonline.com/b478ee14-30c0-4213-8802-1d577417c2f9
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - Authority:Performing static instance discovery
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - Authority:Authority validated via static instance discovery
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:finding with query: {"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "pavel.shtanko@gmail.com"}
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:Looking for potential cache entries:
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:{"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "bla-bla@gmail.com"}
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:Found 4 potential entries.
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:Resource specific token found.
adal-python : 7cb6088b-8e28-4ea3-a3e7-c3de4d19f8a1 - OAuth2Client:Returning token from cache lookup, AccessTokenId: b'bla-bla'
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): graph.windows.net
urllib3.connectionpool : https://graph.windows.net:443 "POST /b478ee14-30c0-4213-8802-1d577417c2f9/applications?api-version=1.6 HTTP/1.1" 403 108
msrest.http_logger : Request URL: 'https://graph.windows.net/b478ee14-30c0-4213-8802-1d577417c2f9/applications?api-version=1.6'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.4 (Darwin-17.3.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.4.24 msrest_azure/0.4.19 graphrbacmanagementclient/0.31.0 Azure-SDK-For-Python AZURECLI/2.0.24'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': 'd4099c70-f93c-11e7-b14c-34363bd2ebfc'
msrest.http_logger :     'CommandName': 'aks create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '440'
msrest.http_logger : Request body:
msrest.http_logger : {"availableToOtherTenants": false, "displayName": "call-cluster", "homepage": "http://406091.call-clust-call-dev-ea5e4a.westeurope.cloudapp.azure.com", "identifierUris": ["http://406091.call-clust-call-dev-ea5e4a.westeurope.cloudapp.azure.com"], "passwordCredentials": [{"startDate": "2018-01-14T15:08:51.965818Z", "endDate": "2019-01-14T15:08:51.965818Z", "keyId": "4ffe8f5e-e050-47b2-aa34-09572ed46402", "value": "7c8d8ae92274a2b5702a"}]}
msrest.http_logger : Response status: 403
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'private'
msrest.http_logger :     'Content-Type': 'application/json; odata=minimalmetadata; charset=utf-8'
msrest.http_logger :     'Server': 'Microsoft-IIS/8.5'
msrest.http_logger :     'ocp-aad-diagnostics-server-name': 'teJXCKiXkExTYCdIPI7/pc9RmCbdSinOEvmyjTvxVlY='
msrest.http_logger :     'request-id': '8d3aff0d-52b1-4013-a96e-d4a795e128b1'
msrest.http_logger :     'client-request-id': '4c7b185c-a2c3-42f1-b39c-ac7a85530267'
msrest.http_logger :     'x-ms-dirapi-data-contract-version': '1.6'
msrest.http_logger :     'ocp-aad-session-key': 'Yt3n08cdk00ltpEZDDzPgbfYz085iGq0OUH8DtV5ryNQ4nowGKPnrgI95DwwoQ0u1CvUgCXZFoPPg9w7MTsK66kkynNIRvPp7XkUDIRh1F-UQkldcm105OzUp0p4XZU6.sYlbakjhHU7AazW8hEv2cHUlzrGgp5WRdtD4g5RyhX8'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Access-Control-Allow-Origin': '*'
msrest.http_logger :     'X-AspNet-Version': '4.0.30319'
msrest.http_logger :     'X-Powered-By': 'ASP.NET, ASP.NET'
msrest.http_logger :     'Duration': '243251'
msrest.http_logger :     'Date': 'Sun, 14 Jan 2018 15:08:51 GMT'
msrest.http_logger :     'Content-Length': '108'
msrest.http_logger : Response content:
msrest.http_logger : b'{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}'
msrest.exceptions : User was not found.
User was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1296, in aks_create
    location=location, name=name)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1397, in _ensure_service_principal
    service_principal = _build_service_principal(rbac_client, cli_ctx, name, url, client_secret)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 434, in _build_service_principal
    result = create_application(rbac_client.applications, name, url, [url], password=client_secret)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1081, in create_application
    return client.create(app_create_param)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/graphrbac/operations/applications_operations.py", line 87, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: User was not found.
```

**Comment by Zimmergren** [comment]
I'm getting this on one of my subscriptions as well. While everything works fine on my other 3 subscriptions, my fourth (a subscription that's been around since the incarnation of Azure) is having exactly this issue as well. 

Ideas welcome.

**Comment by mboersma** [comment]
We've never been able to reproduce this issue, and I don't know what to attribute it to other than a transient service error. @tjprescott let's close this old issue and if it recurs it can be reopened with current information.
