### ISSUE TITLE
Creating a custom domain on cdn doesn't work

### ISSUE THREAD

**Issue by cdelmas** [Azure/azure-cli#5305]
When I try to create a custom domain on a cdn endpoint, I get the following error:

```
create_custom_domain() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
TypeError: create_custom_domain() missing 1 required positional argument: 'client'
```
It looks like the client param is not passed to ```create_custom_domain```.

To reproduce, use the following commands (replace the names ^^):
```
# az login
az group create -l westeurope -n h-RG
az storage account create -g h-RG -l westeurope --sku Standard_LRS --https-only -n hdata

# create cdn
az group create -l westeurope -n c-RG
az cdn profile create -l westeurope --sku Standard_Verizon -n cprofile -g c-RG
az cdn endpoint create -g c-RG -l westeurope -n ch --profile-name cprofile --no-http --enable-compression --origin hdata.blob.core.windows.net

# custom domain (prerequisite: have dns zone declared in a resource group named d-RG)
az network dns record-set cname create -g d-RG -z "yourdomain.com" -n h1 --ttl 3600
az network dns record-set cname set-record -c ch.azureedge.net -n help -z yourdomain.com -g d-RG
az cdn custom-domain create -g c-RG -l westeurope --endpoint-name ch --hostname h1.yourdomain.com -n h1 --profile-name cprofile
```

---

### Environment summary

Install Method: Docker, 2.0.24/latest

```
```

**Comment by tjprescott** [comment]
Thank you @cdelmas for your report. This is indeed a bug and we will issue a fix for the 2.0.26 release.
