### ISSUE TITLE
Certain interactive commands complete with 'NoneType' object has no attribute 'init_progress'

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-cli#5306]
Install Method: apt-get

CLI Version: 

```
azure-cli (2.0.24)

acr (2.0.18)
acs (2.0.23)
advisor (0.1.1)
appservice (0.1.23)
backup (1.0.4)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.24)
cosmosdb (0.1.16)
dla (0.0.16)
dls (0.0.19)
eventgrid (0.1.7)
extension (0.0.7)
feedback (2.0.7)
find (0.2.8)
interactive (0.3.12)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.14)
monitor (0.0.14)
network (2.0.20)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.10)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.20)
role (2.0.16)
servicefabric (0.0.8)
sql (2.0.18)
storage (2.0.22)
vm (2.0.23)

Python location '/opt/az/bin/python3'
Extensions directory '/home/tda/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jan  5 2018, 21:18:08)
[GCC 4.8.4]
```

OS Version:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

Shell: bash

Issue:

1. `az interactive`. Output:

```
az>> Command: provider list not in Command Table
Command: sql db op cancel not in Command Table
Command: storage account generate-sas not in Command Table
```

2. Hit enter and create a new group:

`az>> group create -n test -l westeurope -o json`

3. Try and delete the group:
```
az>> group delete -n test -y
'NoneType' object has no attribute 'init_progress'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 303, in execute
    result = LongRunningOperation(self.cli_ctx, 'Starting {}'.format(cmd.name))(result)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 438, in __call__
    self.cli_ctx.get_progress_controller().begin()
  File "/opt/az/lib/python3.6/site-packages/azclishell/app.py", line 679, in progress_patch
    self.cli_ctx.progress_controller.init_progress(ShellProgressView())
AttributeError: 'NoneType' object has no attribute 'init_progress'
'int' object has no attribute 'result'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azclishell/app.py", line 660, in cli_execute
    if result and result.result is not None:
AttributeError: 'int' object has no attribute 'result'
az>>
```

Additional Information:

The group is deleted but the it exits immediately without waiting for the completion (without `--no-wait`)
The intellisence / autocompletion does not seem to work either

**Comment by paraita** [comment]
I have the same problem running some commands like creation of vm(ss):

```
azure-cli (2.0.27)

acr (2.0.21)
acs (2.0.26)
advisor (0.1.2)
appservice (0.1.26)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.1)
container (0.1.18)
core (2.0.27)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.18)
lab (0.0.17)
monitor (0.1.2)
network (2.0.23)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.23)
role (2.0.19)
servicefabric (0.0.10)
sql (2.0.21)
storage (2.0.25)
vm (2.0.26)

Python location '/home/paraita/lib/azure-cli/bin/python'
Extensions directory '/home/paraita/.azure/cliextensions'

Python (Linux) 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224]

Legal docs and information: aka.ms/AzureCliLegal

```

I'm running Archlinux, the cli has been installed with:
```bash
curl -L https://aka.ms/InstallAzureCli | bash
```

The commands works but I kinda lose the progress character animation.
