### ISSUE TITLE
Specifying start-range/end-range when downloading blob fails

### ISSUE THREAD

**Issue by markwaldkat** [Azure/azure-cli#5308]
---

### Environment summary
Ubuntu 16, bash:

```
sudo pip install virtualenv --upgrade
virtualenv  --no-site-packages --python python3 az_virtenv
source bash az_virtenv/bin/activate
pip install azure-cli --upgrade
$ az --version
azure-cli (2.0.24)
```

When I want to download ranges of a blob storage file I get an error:
```
az --verbose storage blob download --name test.csv --file a --start-range 0 --end-range 10 --container-name *** --connection-string 'DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=***;AccountKey=***'

unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "az_virtenv/lib/python3.4/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "az_virtenv/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "az_virtenv/lib/python3.4/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "az_virtenv/lib/python3.4/site-packages/azure/multiapi/storage/v2017_04_17/blob/baseblobservice.py", line 1784, in get_blob_to_path
    timeout)
  File "az_virtenv/lib/python3.4/site-packages/azure/multiapi/storage/v2017_04_17/blob/baseblobservice.py", line 1915, in get_blob_to_stream
    if end_range and end_range - start_range < first_get_size:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

Trying with string arguments:

```
az --verbose storage blob download --name test.csv --file a --start-range "0" --end-range "10" --container-name *** --connection-string 'DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=***;AccountKey=***'

unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "az_virtenv/lib/python3.4/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "az_virtenv/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "az_virtenv/lib/python3.4/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "az_virtenv/lib/python3.4/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "az_virtenv/lib/python3.4/site-packages/azure/multiapi/storage/v2017_04_17/blob/baseblobservice.py", line 1784, in get_blob_to_path
    timeout)
  File "az_virtenv/lib/python3.4/site-packages/azure/multiapi/storage/v2017_04_17/blob/baseblobservice.py", line 1915, in get_blob_to_stream
    if end_range and end_range - start_range < first_get_size:
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Comment by troydai** [comment]
Thank you for reporting this issue, we will look into this.

**Comment by markwaldkat** [comment]
Cool, thanks for fixing!
