### ISSUE TITLE
does not return value `az monitor activity-log list --resource-group <RESOURCE-GROUP>` 

### ISSUE THREAD

**Issue by sagarchavan6210** [Azure/azure-cli#5339]
When I used below command 3-4 times then its return [ ] as output. I am unable to fetch log (original output of command)
`az monitor activity-log list --resource-group <RESOURCE-NAME>`
[ ]
Please let me know, why this happened ? how do I retrieve activity log  for specific resource group?

**Comment by arukaene** [comment]
When I have experienced this, it was because the default --start-time is set 1 Hour prior to the current time.  I had no logs associated with that Resource Group in that period.

    --start-time       : The start time of the query. In ISO format with explicit indication of
                         timezone: 1970-01-01T00:00:00Z, 1970-01-01T00:00:00-0500. Defaults to 1
                         Hour prior to the current time.

**Comment by fepere** [comment]
anyone get figure out this issue ?

I got this error now:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 13, in monitor_exception_handler
    error_payload = ex.response.json()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tjprescott** [comment]
This question has been answered and is the result of not specifying a start time and having no logs within the default hour window. Closing.

@fepere I would recommend ensuring you have the latest version of the module. If you still experience an issue, please open a new bug report and provide the requested details.
