### ISSUE TITLE
Can't connect to AKS by az aks get-credentials

### ISSUE THREAD

**Issue by yantang-msft** [Azure/azure-cli#5372]
I'm using Azure CLI 2.0.24, running az aks get-credentials gives me such error

```'ManagedCluster' object has no attribute 'properties'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 31
9, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 29
2, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 16
9, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 328, in def
ault_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", lin
e 1329, in aks_get_credentials
    access_profiles = mc.properties.access_profiles
AttributeError: 'ManagedCluster' object has no attribute 'properties'```

**Comment by yantang-msft** [comment]
And I can't login to Azure Container Registry, which seems to be the same issue.

**Comment by yantang-msft** [comment]
Looks like it's already fixed at here:
https://github.com/Azure/azure-cli/blob/8a0bb2ab4e9af1083ed5c70e3ced8af92df9b2c0/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py#L154
