### ISSUE TITLE
Fail to install on Mac: npm failed to pack

### ISSUE THREAD

**Issue by deliriousrhino** [Azure/azure-cli#5373]
The cli failed to install on mac
---
### Environment summary

npm -v 3.10.8
node -v7.0.0

```
 brew install azure-cli
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/node.rb:29:in `<class:Node>'
Please report this to the homebrew/core tap!

Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/python.rb:28:in `block in <class:Python>'
Please report this to the homebrew/core tap!

==> Downloading https://github.com/Azure/azure-xplat-cli/archive/v0.10.1-June2016.tar.gz
Already downloaded: /Users/rhino/Library/Caches/Homebrew/azure-cli-0.10.1.tar.gz
Error: npm failed to pack /private/tmp/azure-cli-20180123-82567-15nzww5/azure-xplat-cli-0.10.1-June2016
Ryans-MBP:form-example rhino$ 

```

**Comment by derekbekoe** [comment]
Have you updated brew itself recently with `brew update`?
`brew install azure-cli` no longer points to `azure-xplat-cli` and hasn't done so for several release now.

**Comment by derekbekoe** [comment]
Closing as this doesn't seem related to Azure CLI 2.0 which is python-based.
