### ISSUE TITLE
There is a wrong url mistake when I execute "az storage blob upload" in azure-cli 2.0

### ISSUE THREAD

**Issue by Gary-Xie** [Azure/azure-cli#5429]
I have upgraded azure cli from 0.10 to 2.0. But I failed to upload files to my blob storage. I found in the debug log there was a change in the url which was used by cli to conect blob storage.
When I used cli 0.10, the url was https://azrcneeprsadgt001.blob.core.chinacloudapi.cn:443/test4gir/test1.csv'.
But when I use cli 2.0, the url was changed to azrcneeprsadgt001.blob.core.windows.net.
So I failed to connect the wrong url with connection timeout error.
And the log did not tell me how to correct or verify my args. I mean if there is a connection issue, the log may tell the user how to verify the input, especially the connection url and how to update it.

---

### Environment summary
I have run it in Window 7 64bit, Ubuntu 16 64bit, and centos 7.2 64bit. The current Azure Cli version is 2.0.25.

```
```

**Comment by Gary-Xie** [comment]
The part of log is below.

HTTPSConnectionPool(host='azrcneeprsadgt001.blob.core.windows.net', port=443): Max retries exceeded with url: /test4gir/test2.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x048C3770>, 'Connection
 to azrcneeprsadgt001.blob.core.windows.net timed out. (connect timeout=20)'))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 141, in _new_con
n
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\connection.py", line 83, in crea
te_connection
    raise err
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\connection.py", line 73, in crea
te_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 601, in urlo
pen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 346, in _mak
e_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 850, in _val
idate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connection.py", line 146, in _new_con
n
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x048C3770>, 'Connection
to azrcneeprsadgt0001.blob.core.windows.net timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\connectionpool.py", line 639, in urlo
pen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\util\retry.py", line 388, in incremen
t
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='azrcneeprsadgt001.blob.core.windows.net', port=443): Max re
tries exceeded with url: /qr4giraf/test2.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection
object at 0x048C3770>, 'Connection to azrcneeprsadgt001.blob.core.windows.net timed out. (connect timeout=20)'))

**Comment by Gary-Xie** [comment]
Sorry，I need to clarify I also find the same issue in azure cli 0.10.17 when I setup 0.10.17 in my windows7 64bit. So the problem is changed to how to fix the connection timeout issue if there is a wrong url. How to correct the url to connect blob storage? Does it need to login first?

**Comment by tobydrake7** [comment]
For CLI 2.0. 
You may need to export a new storage connection string.

1. Log in to Azure using CLI 2.0.

2. Get the storage account connection string.

     az storage account show-connection-string -n _storage-account-name_ -g _resource-group_

3. Export the connection string.

    export AZURE_STORAGE_CONNECTION_STRING=_"storage-connection-string"_

4. Work with your Azure resources.

**Comment by derekbekoe** [comment]
You need to switch to the correct cloud.
```
az cloud set -n AzureChinaCloud 
```
