### ISSUE TITLE
vm disk encryption: fail nicely when checking encryption status

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5436]
Don't crash with unhandled exception

az vm encryption show --name somevm --resource-group someresourcegroup
'NoneType' object has no attribute 'enabled'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 316, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 40, in empty_on_404
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 293, in show_vm_encryption_status
    if (encryption_status['osDiskEncryptionSettings'].enabled and
AttributeError: 'NoneType' object has no attribute 'enabled'

**Comment by ejarvi** [comment]
experimenting with a try/except fix here:  
https://github.com/ejarvi/azure-cli/commit/6e26905dacc173eedd1e21439a08665c3a7729dd
