### ISSUE TITLE
Azure CLI Error httpsconnectionpool

### ISSUE THREAD

**Issue by Kalanamith** [Azure/azure-cli#5437]
I'm using the following syntax to download a file from azure fileshare

`az storage file delete --path config.yaml  --share-name my-share-name  --account-key my-account-key --account-name my-account-name --debug
`
Unfortunately it keeps trying and fails

`Client-Request-ID=<> Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='my-account.file.core.windows.net', port=443): Max retries exceeded with url: /my-account-name/config.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10c9199b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))`

HTTPSConnectionPool
---

I am using Locally-redundant storage (LRS) and azure cli version 2.0.21. Is there a fix for this issue?

**Comment by tjprescott** [comment]
Please try the lastest release and confirm if this is still an issue for you.

**Comment by Kalanamith** [comment]
Upgraded to version 2.0.25  though facing the same issue

`(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1054ff240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1054ff240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<>', port=443): Max retries exceeded with url: /<>/config.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1054ff240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 260, in _perform_request
    response = self._httpclient.perform_request(request)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/_http/httpclient.py", line 101, in perform_request
    proxies=self.proxies)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='<>.file.core.windows.net', port=443): Max retries exceeded with url: /<>/config.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1054ff240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/file/fileservice.py", line 1540, in delete_file
    self._perform_request(request)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 362, in _perform_request
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 302, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: HTTPSConnectionPool(host='<>', port=443): Max retries exceeded with url: /<>/config.yaml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1054ff240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))`

@tjprescott

**Comment by williexu** [comment]
@Kalanamith I can't seem to reproduce your error. What environment are you using?
In addition can I see the part of your debug log that contains the request and response received?
Look for `Outgoing request:` and `Receiving Response`

**Comment by Kalanamith** [comment]
@williexu I am using macos and the whole operation is failing can view the file store but it wont allow me to update delete or  download a file

**Comment by Kalanamith** [comment]
@tjprescott  seems it's working now

**Comment by isaac-gs** [comment]
I am getting this error too. It's based on building a docker image and trying to call a python script. I can't share the code here, but let me know who within Microsoft I should reach out to if they want to see it.

**Comment by roymoran** [comment]
Initially created storage account type as `StorageV2 (general purpose v2)` but re-creating it as `Storage (general purpose v1)` resolved the issue. 

Saw the same issue when executing 
`az storage blob download --account-name workflowparameters --account-key xxx --container-name parameters --name LogicApp.paramters.json --file LogicApp.paramaters.json --output table`

Running azure cli on
Distributor ID: Ubuntu
Description: Ubuntu 16.04.5 LTS
Release: 16.04
Codename: xenial

Some output: 
`HTTPSConnectionPool(host='workflowparameters.blob.core.windows.net', port=443): Max retries exceeded with url: /parameters/LogicApp.paramters.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f32b66e3a58>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f32b66e3a58>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:`

**Comment by tjprescott** [comment]
@williexu can you take a look?

**Comment by limingu** [comment]
#8161

**Comment by limingu** [comment]
The Storage api should give out more meaningful error message for such cases.

**Comment by artkpv** [comment]
Having this issue again. 

```
[I] ➜ az storage blob upload --container-name '$web' --name index.html --file index.html
HTTPSConnectionPool(host='cs23906ccfd8633x469fxad.blob.core.windows.net', port=443): Max retries exceeded with url: /$web/index.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0dd5f25d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))

artkpv.github.io on  master took 1m 1s 
[I] ➜ az storage container list 
HTTPSConnectionPool(host='cs23906ccfd8633x469fxad.blob.core.windows.net', port=443): Max retries exceeded with url: /?comp=list&maxresults=5000 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f715e8aafd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

artkpv.github.io on  master took 56s 
[I] ➜ az storage container create --name sample-container
HTTPSConnectionPool(host='cs23906ccfd8633x469fxad.blob.core.windows.net', port=443): Max retries exceeded with url: /sample-container?restype=container (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f222b588310>: Failed to establish a new connection: [Errno -2] Name or service not known'))

artkpv.github.io on  master took 55s 
[I] ➜ az --version
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4

Extensions:
interactive                        0.4.3

Python location '/usr/bin/python'
Extensions directory '/home/art/.azure/cliextensions'

Python (Linux) 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

artkpv.github.io on  master took 3s 
[I] ➜ uname --all
Linux artpc 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux

artkpv.github.io on  master 
[I] ➜ echo $AZURE_STORAGE_ACCOUNT 
# Present. And $AZURE_STORAGE_KEY 
```
