### ISSUE TITLE
ValueError: field 6 out of range (need a 48-bit value) in 2.0.26

### ISSUE THREAD

**Issue by alexsergin** [Azure/azure-cli#5448]
After last update of HighSierra getting these error for most az command. For example az aks list returns:

```
~  az aks list
 field 6 out of range (need a 48-bit value)
 Traceback (most recent call last):
   File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
     cmd_result = self.invocation.execute(args)
   File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 198, in execute
     args = _pre_command_table_create(self.cli_ctx, args)
   File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 100, in _pre_command_table_create
     cli_ctx.refresh_request_id()
   File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 67, in refresh_request_id
     self.data['headers']['x-ms-client-request-id'] = str(uuid.uuid1())
   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 606, in uuid1
     clock_seq_hi_variant, clock_seq_low, node), version=1)
   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 168, in __init__
     raise ValueError('field 6 out of range (need a 48-bit value)')
 ValueError: field 6 out of range (need a 48-bit value)
```

---

### Environment summary

```
 ✘  ~  az --version
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/imac04/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

**Comment by alexsergin** [comment]
**az** command without any arguments returns the same error also

**Comment by alexsergin** [comment]
Hmm... Strange behaviour. After reboot it works properly. But python3 and azure-cli versions are the same.

**Comment by nickb834** [comment]
same here, however - this occurs from time to time meaning I need to reboot from time to time to get az cli to work :-( I *think* this is an issue with the waking a mac from sleep as a clean boot I don't have this problem - yet as I put my mac to sleep every night and wake it the next - boom az cli no worky.

**Comment by jpascalw** [comment]
I also get this error.

**Comment by iLoreto** [comment]
Hi, rebooting does not help in my case.  Did evertyhing by the book and no joy. Opened a new tix https://github.com/Azure/azure-cli/issues/5546 
Python bins and all the things checkout ok. Going thru journalctl logs for moar details. 👓

**Comment by derekbekoe** [comment]
For anyone else running into this, add comments to https://github.com/Azure/azure-cli/issues/5184

**Comment by mkalkere** [comment]
Hi, I am getting the same error:

field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 200, in execute
    args = _pre_command_table_create(self.cli_ctx, args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 101, in _pre_command_table_create
    cli_ctx.refresh_request_id()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 67, in refresh_request_id
    self.data['headers']['x-ms-client-request-id'] = str(uuid.uuid1())
  File "/opt/az/lib/python3.6/uuid.py", line 592, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/opt/az/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

**Comment by derekbekoe** [comment]
@mkalkere Please add your comments to https://github.com/Azure/azure-cli/issues/5184.
Also, please provide the following.

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)
