### ISSUE TITLE
403 Error when using az acs kubernetes install-cli

### ISSUE THREAD

**Issue by brharr** [Azure/azure-cli#5497]
I am trying to install the kubectl command line tools using the Azure CLI and everytime that I try, I get a large 403 Forbidden error. The entire stack trace can be found below. 

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Ubuntu on Windows Bash Shell
Latest Azure CLI installed
Have tested this on straight Windows as well with the same results.
I have tested this with and without the "install-location" parameter without any success.
```
HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 318, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 291, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 348, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 289, in k8s_install_cli
    context=context).read()
  File "/opt/az/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/az/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/az/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/az/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/az/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

This is completely preventing me from working with the Kubernetes orchestrator within ACS. 

Thanks,
Brian

**Comment by mboersma** [comment]
@brharr I think this was kubernetes/kubernetes#59430. That repository was apparently set to private temporarily. It should be fixed now--let us know if this still doesn't work for you.

**Comment by brharr** [comment]
You are correct. This has been resolved.
