### ISSUE TITLE
az login exception field 6 out of range (need a 48-bit value) on macOS (cli 2.0.26)

### ISSUE THREAD

**Issue by iLoreto** [Azure/azure-cli#5546]
Command fails for az login on macOS. 
Rebooting does not resolve the issue.  Is downgrading the only option or is there be a fix for 2.0.26?
```
field 6 out of range (need a 48-bit value)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 198, in execute
    args = _pre_command_table_create(self.cli_ctx, args)
  File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 100, in _pre_command_table_create
    cli_ctx.refresh_request_id()
  File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 67, in refresh_request_id
    self.data['headers']['x-ms-client-request-id'] = str(uuid.uuid1())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
```

### Environment summary

brew install azure-cli
```
az --version
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/drh4k0r/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```
###OS Summary
macOS high Sierra 10.13.3 on bash shell 
`mbp.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

**Comment by derekbekoe** [comment]
@iLoreto thanks for the bug report.
Please add your comments to https://github.com/Azure/azure-cli/issues/5184
