### ISSUE TITLE
Error loading command module 'ml'

### ISSUE THREAD

**Issue by terrymccarthy3000** [Azure/azure-cli#5612]
---

### Environment summary
Linux UbuntuDesktop01 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Install Method:
https://docs.microsoft.com/en-us/azure/machine-learning/preview/deployment-setup-configuration
sudo -i
pip install azure-cli
pip install azure-cli-ml

```
Issue description:
Following instructions at https://docs.microsoft.com/en-us/azure/machine-learning/preview/deployment-setup-configuration
-----------------------------------
Step: Environment Setup - To start the setup process, you need to register a few environment providers by entering the following commands:
az provider register -n Microsoft.MachineLearningCompute

Result of above command: Error loading command module 'ml'
------------------------------------
Command: az --debug
Result of above command:
Error loading command module 'ml'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/__init__.py", line 129, in _update_command_table_from_modules
    module_command_table = _load_module_command_loader(self, args, mod)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 549, in _load_module_command_loader
    return _load_command_loader(loader, args, mod, 'azure.cli.command_modules.')
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 523, in _load_command_loader
    module = import_module(prefix + name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/ml/__init__.py", line 8, in <module>
    import azure.cli.command_modules.ml._help #pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/ml/_help.py", line 6, in <module>
    from azure.cli.core.help_files import helps
ImportError: No module named help_files
------------------------------
/usr/local/lib/python2.7/dist-packages/azure/cli/command_modules/ml/_help.py
Line 6: from azure.cli.core.help_files import helps


```

**Comment by tjprescott** [comment]
@trangevi for comment

**Comment by trangevi** [comment]
@terrymccarthy3000 There is currently a version mismatch that is causing this issue. If you run ‘pip install -r https://aka.ms/az-ml-o16n-cli-requirements-file’ it should get your environment in a working state. I will work on updating our documentation to avoid this error.
