### ISSUE TITLE
vm extension list on vm with no extensions throws error

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#564]
expected: empty return object
actual:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\azure-cli\src\azure\cli\main.py", line 55, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\azure-cli\src\azure\cli\application.py", line 117, in execute
    result = expanded_arg.func(params)
  File "C:\azure-cli\src\azure\cli\commands__init__.py", line 212, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "c:\azure-cli\src\command_modules\azure-cli-vm\azure\cli\command_modules\vm\custom.py", line 491, in list_extensions
    result = [r for r in vm.resources if r.type == extension_type]
TypeError: 'NoneType' object is not iterable

**Comment by mayurid** [comment]
I have verified it does not return an error now. here is an output 

(env) Mayuris-MacBook-Pro:azure-cli mayuridiwan$ az vm extension list -g <testrg> --vm-name <name>
[]
