### ISSUE TITLE
az storage container create --name MyStorageContainer issue

### ISSUE THREAD

**Issue by gsee2000** [Azure/azure-cli#5653]
Hi

Wondered if anyone else has encountered similar. I am currently following through the Azure Stack cli documentation:

https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-2017-03-09-profile#az_storage_container_create

I have attempted to create a storage container on Azure stack without joy. Before running the command I am using the following:

az cloud register -n AzureStack (relevant parameters)
az cloud set -n AzureStack
az cloud update --profile 2017-03-09-profile
az login -u username -p password

Once I run the below command I encounter the following:

az storage container create --name MyStorageContainer
'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 117, in get_data_service_client
    client = service_type(**client_kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2015_04_05/blob/blockblobservice.py", line 116, in __init__
    custom_domain, request_session, connection_string)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2015_04_05/blob/baseblobservice.py", line 158, in __init__
    connection_string=connection_string)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2015_04_05/_connection.py", line 109, in get_service_parameters
    raise ValueError(_ERROR_STORAGE_MISSING_INFO)
ValueError: You need to provide an account name and either an account_key or sas_token when creating a storage service.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 304, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 168, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 342, in default_command_handler
    client = client_factory(self.cli_ctx, command_args) if client_factory else None
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 68, in blob_data_service_factory
    sas_token=kwargs.pop('sas_token', None))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 29, in generic_data_service_factory
    return get_storage_data_service_client(cli_ctx, service, name, key, connection_string, sas_token)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_client_factory.py", line 24, in get_storage_data_service_client
    endpoint_suffix=cli_ctx.cloud.suffixes.storage_endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/client_factory.py", line 121, in get_data_service_client
    if _ERROR_STORAGE_MISSING_INFO in str(exc):
TypeError: 'in <string>' requires string as left operand, not NoneType

Is there something else that should be set beforehand, or in the command itself I am missing?

az --version
azure-cli (2.0.27)

acr (2.0.21)
acs (2.0.26)
advisor (0.1.2)
appservice (0.1.26)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.1)
container (0.1.18)
core (2.0.27)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.18)
lab (0.0.17)
monitor (0.1.2)
network (2.0.23)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.23)
role (2.0.19)
servicefabric (0.0.10)
sql (2.0.21)
storage (2.0.25)
vm (2.0.26)

Cheers

**Comment by gsee2000** [comment]
Update on this, I have been able to run the following command with success:

az storage container create --name MyStorageContainer --account-name MyStorageAccount
{
  "created": true
}

Reading the documentation at:

https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-2017-03-09-profile#az_storage_container_create

It states '--account-name' is an optional parameter, and that only '--name' is a required parameter. Should this be updated to reflect this is in fact required? Or is it just assumed?

Cheers

**Comment by williexu** [comment]
@gsee2000 `--account-name` is optional in that there are other options:
-you can set the environment variable `AZURE_STORAGE_ACCOUNT`
-you can use `--connection-string` (or set `AZURE_STORAGE_CONNECTION_STRING`)

You should, however, not be seeing that large stack trace and error
