### ISSUE TITLE
CLI dies if output pipe is broken.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#58]
If cli output is attached to a broken pipe, it will crash.  Example: 'az vm list | jfhksfh'
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/joe/azure-cli/src/azure/cli/__main__.py", line 5, in <module>
    sys.exit(azure.cli.main.main(sys.argv[1:]))
  File "/Users/joe/azure-cli/src/azure/cli/main.py", line 47, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result.result)
  File "/Users/joe/azure-cli/src/azure/cli/_output.py", line 62, in out
    print(self.formatter(obj), file=self.file)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by JasonRShaver** [comment]
Example from recent build:
```
jasonsha@JasonShaMBP: ~ $ az vm list | asdfasdf
-bash: asdfasdf: command not found
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/main.py", line 55, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/_output.py", line 74, in out
    print(output, file=self.file, end='')
IOError: [Errno 32] Broken pipe
```

**Comment by mayurid** [comment]
Closing as #770 is tracking this
