### ISSUE TITLE
Starting interactive mode with --style fails and throws AssertionError

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#5807]
---
```
(env36b) C:\Users\wilx\azure-cli>az interactive -s primary

Traceback (most recent call last):
  File "C:\Users\wilx\azure-cli\env36b\lib\site-packages\knack\cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Users\wilx\azure-cli\env36b\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Users\wilx\azure-cli\env36b\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\__init__.py", line 13, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\azclishell\app.py", line 144, in __call__
    self.run()
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\azclishell\app.py", line 690, in run
    self.cli.buffers['symbols'].reset(
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\azclishell\app.py", line 151, in cli
    self._cli = self.create_interface()
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\azclishell\app.py", line 369, in create_interface
    application=self.create_application(),
  File "c:\users\wilx\azure-cli\src\command_modules\azure-cli-interactive\azure\cli\command_modules\interactive\azclishell\app.py", line 362, in create_application
    buffers=buffers,
  File "C:\Users\wilx\azure-cli\env36b\lib\site-packages\prompt_toolkit\application.py", line 121, in __init__
    assert style is None or isinstance(style, Style)
AssertionError
```
### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
As part of the fix, it would be good to remove the bald assert statement entirely.

**Comment by williexu** [comment]
@tjprescott the assert statement is in the library we depend on, not our cli :)

**Comment by tjprescott** [comment]
Ah, gross.
