### ISSUE TITLE
Issue az storage blob upload

### ISSUE THREAD

**Issue by sudhakaranrajendran** [Azure/azure-cli#5835]
### Environment summary

Install Method (apt-get) / CLI version (`azure-cli (2.0.27)`) / Ubuntu 14.04 LTS/ Shell Type (bash)  

/usr/bin/az storage blob upload --account-name "$AZURE_ACCOUNT" --account-key "$AZURE_ACCOUNT_KEY" --container-name "$AZURE_CONTAINER" --file "$UPLOAD_FILE" --max-connections 1 --name "$AZURE_BLOB"

StackTrace 
```
utf-8
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/storageclient.py", line 238, in _perform_request
    self.authentication.sign_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/_auth.py", line 78, in sign_request
    self._add_authorization_header(request, string_to_sign)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/_auth.py", line 57, in _add_authorization_header
    signature = _sign_string(self.account_key, string_to_sign)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/_common_conversion.py", line 91, in _sign_string
    key = _decode_base64_to_bytes(key)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/_common_conversion.py", line 80, in _decode_base64_to_bytes
    data = data.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcfb' in position 1: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 304, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 168, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 348, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 257, in upload_blob
    return type_func[blob_type]()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 250, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/blob/blockblobservice.py", line 404, in create_blob_from_path
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/blob/blockblobservice.py", line 523, in create_blob_from_stream
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/blob/blockblobservice.py", line 912, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/storageclient.py", line 354, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_07_29/common/storageclient.py", line 294, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: utf-8
```

**Comment by williexu** [comment]
The description is confusing. 

According to the [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/snapshot-blob#request-headers):
"The conditional x-ms-lease-id header is specified, and the active lease ID for the base blob is included in the request. This condition specifies that the snapshot be created only if the lease is active and the specified lease ID matches that associated with the blob."

This doc is coming from the sdk and i assume it was meant to be read as:
"Require- "if the blob has an active lease"'

Regardless, this can definitely be clarified.

**Comment by williexu** [comment]
@sudhakaranrajendran the problem seems to be with the argument provided to `--account-key`. 
Seems there are problems with some of the characters.

Where did you get your account-key from?

**Comment by troydai** [comment]
@subbarayudukamma please double check your account key. The error message indicates it containing invalidate character. I'll close this for now as not repo.

**Comment by sudhakaranrajendran** [comment]
@williexu : Got the account key from azure portal and its worked well in third party tools like azure storage explorer.

**Comment by williexu** [comment]
@sudhakaranrajendran yes, that's a common scenario; not sure why it's not working for you.
Did you try using your account key again recently? If not, can you?
Also you can try upgrading your version of the CLI.

**Comment by sudhakaranrajendran** [comment]
Updated Azure CLI to latest version and it worked @williexu : Thanks for the help.
