### ISSUE TITLE
[CognitiveServices] account show on nonexistent account throws stack trace

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5875]
```
(env2) C:\Users\trpresco\Documents\github\azure-cli>az cognitiveservices account show -g tjp-rg -n nonexist
(ResourceNotFound) The Resource 'Microsoft.CognitiveServices/accounts/nonexist' under resource group 'tjp-rg' was not found.
Traceback (most recent call last):
  File "C:\Users\trpresco\Documents\github\env2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Users\trpresco\Documents\github\env2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\trpresco\documents\github\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "c:\users\trpresco\documents\github\env2\lib\site-packages\azure\mgmt\cognitiveservices\operations\cognitive_services_accounts_operations.py", line 289, in get_properties
    raise models.ErrorException(self._deserialize, response)
ErrorException: (ResourceNotFound) The Resource 'Microsoft.CognitiveServices/accounts/nonexist' under resource group 'tjp-rg' was not found.
```

The recommended fix would be an exception handler for these commands as it is likely common throughout the service. 

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.30)
cosmosdb (0.1.19)
dev-tools (0.1.1)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.19)
monitor (0.1.3)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.1)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.28)
testsdk (0.1.0)
utility-automation (0.1.1)
vm (2.0.29)

Extensions:
alias (0.3.0)
rdbms (0.0.3)
subscription (0.1.0)

Python location 'C:\Users\trpresco\Documents\github\env2\Scripts\python.exe'
Extensions directory 'C:\Users\trpresco\.azure\cliextensions'

Python (Windows) 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
```

**Comment by tjprescott** [comment]
@pchoudhari
