### ISSUE TITLE
Unable to reset ad sp credentials

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-cli#6016]
az --version: 2.0.30

Created sp with:
`az ad sp create-for-rbac -n "rgtest"
`
Trying to reset creds with:

`az ad sp credential reset --name "http://rgtest"
`
Get this error:

```
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 1165, in reset_service_principal_credential
    app = show_application(client.applications, aad_sps[0].app_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 644, in show_application
    object_id = _resolve_application(client, identifier)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 654, in _resolve_application
    result = list(client.list(filter="identifierUris/any(s:s eq '{}')".format(identifier)))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 121, in __next__
    self.advance_page()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 107, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\graphrbac\operations\applications_operations.py", line 158, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Insufficient privileges to complete the operation.
```

**I can however reset the credentials via shell.azure.com**

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
This error from the graph service end is legit. Are you logging in as a service principal in CLI? Please share the output of `az account show`

**Comment by jonbgallant** [comment]
I'm unable to repro this today.  Will re-open if I see it again.

**Comment by dluc** [comment]
I'm experiencing the same problem, any suggestion?

Repro:
`az login --service-principal --username ..... --password ..... --tenant .....`

output:
```json
[
  {
    "cloudName": "......",
    "homeTenantId": "......",
    "id": "......",
    "isDefault": true,
    "managedByTenants": [],
    "name": "......",
    "state": "Enabled",
    "tenantId": "......",
    "user": {
      "name": "......",
      "type": "servicePrincipal"
    }
  }
]
```

`az ad sp credential reset --name ......`

output

```
Insufficient privileges to complete the operation.
```

**Comment by Darktaelb** [comment]
Why this ticket was closed???

**Comment by jiasli** [comment]
@dluc, in order to reset password for another Service Principal, you need to add some permissions to the setter Service Principal, please see https://github.com/Azure/azure-cli/issues/7656#issuecomment-574020898. The required permissions may change once we move to MS Graph https://github.com/Azure/azure-cli/issues/12946.
