### ISSUE TITLE
az web delete slot error

### ISSUE THREAD

**Issue by lpxavi** [Azure/azure-cli#6063]
Hi,

we have an error running following command :

`az webapp delete --name webapp_name --resource-group webapp_group --slot webapp_slot`

> delete_slot() missing 1 required positional argument: 'slot'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 328, in delete_webapp
    skip_dns_registration=False if keep_dns_registration else None)
TypeError: delete_slot() missing 1 required positional argument: 'slot'

Are you please able to help about this issues ?

Tks,

---

### Environment summary

Install method: apt-get
CLI version : azure-cli (2.0.30)
OS version: Ubuntu 16.04.3 LTS
Shell Type: bash  

```
```

**Comment by yugangw-msft** [comment]
the end to end test should have caught this, let me figure out the root cause.

**Comment by yugangw-msft** [comment]
@lpxavi , for now, please use the `az webapp deployment slot delete` to workaround this
