### ISSUE TITLE
Problem with logging in

### ISSUE THREAD

**Issue by DawidCh** [Azure/azure-cli#6085]
Hi.
Sometimes we are getting error as follows, during logging in:
```
az login --service-principal -u **** -p **** -t ****
08:39:34 Traceback (most recent call last):
08:39:34   File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
08:39:34     "__main__", mod_spec)
08:39:34   File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
08:39:34     exec(code, run_globals)
08:39:34   File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 22, in <module>
08:39:34     az_cli = get_default_cli()
08:39:34   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 399, in get_default_cli
08:39:34     help_cls=AzCliHelp)
08:39:34   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 48, in __init__
08:39:34     ensure_dir(azure_folder)
08:39:34   File "/opt/az/lib/python3.6/site-packages/knack/util.py", line 39, in ensure_dir
08:39:34     os.makedirs(d)
08:39:34   File "/opt/az/lib/python3.6/os.py", line 220, in makedirs
08:39:34     mkdir(name, mode)
08:39:34 FileExistsError: [Errno 17] File exists: '/home/ubuntu/.azure'
```
---

### Environment summary

Install Method - apt-get
CLI version azure-cli (2.0.24)
Python (Linux) 3.6.1
OS version Linux ip-172-16-0-99 4.4.0-1048-aws #57-Ubuntu SMP Tue Jan 9 21:45:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Shell Type - bash

**Comment by tjprescott** [comment]
First suggestion would be to update your CLI. Latest release is 2.0.31.

**Comment by DawidCh** [comment]
Hi.
Thanks for quick response. 
@1. No, just one.
@2. No.
I'm calling multiple times following sequences:
- az login
- some stuff
- az logout
So maybe sth is not cleaned properly. I have even tried rm -rf /home/ubuntu/.azure,  az login after that and the error still sometimes occurs.
Regards, Dawid.

**Comment by yugangw-msft** [comment]
@DawidCh, for @1, sorry if i didn't make it clear, i meant do you run several azure-cli at the same time, which could introduce a racing issue? Say, when 2 CLIs both see the folder is missing and will try to create the folder at the same time. CLI can work with existing folder w/o any problems though, or can be configured to use non-default data folder

**Comment by DawidCh** [comment]
There is always one az login at time. Those operations are being performed on aws jenkins node set up on demand and killed after that.

**Comment by yugangw-msft** [comment]
Are you able to capture OS level trace on this directory and see which process created this folder first? 
Please note, this is not `az login` issue, rather a generic CLI launching issue.
Also I would suggest you retry the `login` command in your script  and see whether it would work at the 2nd time.

**Comment by DawidCh** [comment]
>> Also I would suggest you retry the login command in your script and see whether it would work at the 2nd time.
This is our workaround. We implemented bash loop in /usr/bin/az script and just call the azCli twice. Since then we didn't get the error again (yet; 3 days).
>> Are you able to capture OS level trace on this directory and see which process created this folder first?
I will try it on Monday, as we have weekend already;)
