### ISSUE TITLE
az login --service-principal gives 'NoneType' object is not callable

### ISSUE THREAD

**Issue by nicklan** [Azure/azure-cli#6091]
Trying to log in a sp gives me an error.  Just before I successfully ran:
`az ad sp create-for-rbac --role="Contributor"  --scopes="/subscriptions/${SUBSCRIPTION_ID}" -n [user] -p [pass]`

The command I ran and the error:
```
az login --service-principal -u [user] -p [pass] --tenant [tenant]
'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 135, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 162, in find_subscriptions_on_login
    username, sp_auth, tenant, self._ad_resource_uri)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 687, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
  File "/usr/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 732, in _find_using_specific_tenant
    client = self._arm_client_factory(token_credential)
  File "/usr/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 649, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
```
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.31)
installed via pacaur
shell: bash
```

**Comment by yugangw-msft** [comment]
If you run `az cloud show`, what you get?

**Comment by nicklan** [comment]
```
{
  "endpoints": {
    "activeDirectory": "https://login.microsoftonline.com",
    "activeDirectoryDataLakeResourceId": "https://datalake.azure.net/",
    "activeDirectoryGraphResourceId": "https://graph.windows.net/",
    "activeDirectoryResourceId": "https://management.core.windows.net/",
    "batchResourceId": "https://batch.core.windows.net/",
    "gallery": "https://gallery.azure.com/",
    "management": "https://management.core.windows.net/",
    "resourceManager": "https://management.azure.com/",
    "sqlManagement": "https://management.core.windows.net:8443/",
    "vmImageAliasDoc": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json"
  },
  "isActive": true,
  "name": "AzureCloud",
  "profile": "latest",
  "suffixes": {
    "azureDatalakeAnalyticsCatalogAndJobEndpoint": "azuredatalakeanalytics.net",
    "azureDatalakeStoreFileSystemEndpoint": "azuredatalakestore.net",
    "keyvaultDns": ".vault.azure.net",
    "sqlServerHostname": ".database.windows.net",
    "storageEndpoint": "core.windows.net"
  }
}
```

**Comment by yugangw-msft** [comment]
I can't reproduce it. You mentioned `installed via pacaur`, can you elaborate the installation steps to get CLI installed? Since you have logged in as a user account in the same machine before so to run `az ad sp create-for-rabc`, I can't think of any reasons that would cause this error, which has nothing to do with the account types.

**Comment by nicklan** [comment]
the AUR is the arch linux repository of user contributed build scripts.  the one I used to get `az` installed is this one: https://aur.archlinux.org/packages/python-azure-cli/

Is there another preferred way to install on a non-apt linux system?  I'd be fine to try that.

**Comment by yugangw-msft** [comment]
Can you check out  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest and see whether  `yum and zipper` would work for you?
Please note we never maintained the AUR, and it is the first time I know this.

**Comment by nicklan** [comment]
yeah, yum and zipper are no go on arch, but I installed via the InstallAzureCli script and that worked.  Feel free to close this.  I'll follow up with the AUR maintainer.

Thanks

**Comment by yugangw-msft** [comment]
Thanks. Good to know you found a way to unblock yourself.
