### ISSUE TITLE
'Permission denied' error after running 'az login'

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#613]
I have seen the following error after running `az login -u <USER> -p <PASS>`.

The accessTokens.json file is owned by a different user and the current user does not have write permissions.

```
[Errno 13] Permission denied: '/home/ubuntu/.azure/accessTokens.json'
Traceback (most recent call last):
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/main.py", line 55, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/application.py", line 117, in execute
    result = expanded_arg.func(params)
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/commands/__init__.py", line 212, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 68, in login
    tenant)
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/_profile.py", line 109, in find_subscriptions_on_login
    self._creds_cache.persist_cached_creds()
  File "/usr/local/az/envs/default/local/lib/python2.7/site-packages/azure/cli/_profile.py", line 324, in persist_cached_creds
    with codecs_open(self._token_file, 'w', encoding='ascii') as cred_file:
  File "/usr/local/az/envs/default/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: '/home/ubuntu/.azure/accessTokens.json'
```

You can see that the file owner is root but the current user is 'ubuntu'. So 'ubuntu' doesn't have access to write to the file. It looks like the file owner should be 'ubuntu'.

```
$ id
uid=1000(ubuntu) gid=1000(ubuntu) 
$ ls -la /home/ubuntu/.azure/
total 24
drwxr-xr-x 2 root   root   4096 Aug  3 19:24 .
drwxr-xr-x 9 ubuntu ubuntu 4096 Jul 22 23:26 ..
-rw-r--r-- 1 root   root      2 Aug  3 19:25 accessTokens.json
-rw-r--r-- 1 root   root      5 May 23 23:40 az.json
-rw-r--r-- 1 root   root      5 May 23 23:40 az.sess
-rw-r--r-- 1 root   root    292 Aug  3 19:24 azureProfile.json
```

It makes sense that the file owner is 'root' as to install the CLI globally, `sudo` is required. But then ideally, the owner of the accessToken file should be 'ubuntu' (especially since the file is in the user directory).

**Comment by krishnakumarq** [comment]
Getting below error while trying to login using azure CLI command

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 492, in get_default_cli
    help_cls=AzCliHelp)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 50, in __init__
    ensure_dir(azure_folder)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/util.py", line 38, in ensure_dir
    os.makedirs(d)
  File "/usr/lib64/az/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/dsadm/.azure'
Can anyone please help on this

and in home/dsadm/ directory I dont have a directory named .azure

**Comment by wdrdres3qew5ts21** [comment]
**Sorry but this problem still persistent if you using "Jenkins Docker in Docker"** 

![image](https://user-images.githubusercontent.com/25000903/86135028-7da61d80-bb14-11ea-932e-49c851da5c9a.png)

![image](https://user-images.githubusercontent.com/25000903/86134254-97933080-bb13-11ea-8a40-2f8f4f825519.png)

![image](https://user-images.githubusercontent.com/25000903/86134392-c14c5780-bb13-11ea-9760-af5da654239e.png)

![image](https://user-images.githubusercontent.com/25000903/86134621-112b1e80-bb14-11ea-9d22-e55cd7c52590.png)]

because Jenkins didn't give you "root user" to the container because security issues in privilege escalation attack !
So if you type anycommand relate to "root user" you will get broken output even "whoami" command !!!
The way to fix is you give additional user argument to container while run it on Jenkins pipeline
```
agent {
   docker {
        image 'mcr.microsoft.com/azure-cli:2.8.0'
        args "--user root --privileged"
    }
}
```

![image](https://user-images.githubusercontent.com/25000903/86135462-0cb33580-bb15-11ea-8928-a91a1c73680e.png)

You will fix this problem !!! But why do "Azure CLI need root user ?"
I don't know about internal code in Azure CLI so hope Microsoft Team can help to fix this problem.
Thank you very much 😭😭😭
