### ISSUE TITLE
Argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-cli#6147]
When trying to run any `az provider`, `az group`  or `az appservice` (and I assume others too) commands, I get `argument of type 'NoneType' is not iterable`.

This seems similar to #5548, except that I have this issue with all subscriptions, not just specifically free trial ones.

I'm on Windows 7 x64, and installed the version 2.0.31 from an MSI installer (I actually had the same problem with a previous version too). I've tried it from both the Windows command line and bash, with the same result.

Relevant part of `az --version` output:

```
azure-cli (2.0.31)
...
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\136335\Home\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
```

Full stack trace:
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\adal_authentication.py", line 24, in signed_session
    scheme, token, _ = self._token_retriever()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 449, in _retrieve_token
    account[_TENANT_ID], resource)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 784, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 134, in acquire_token
    return self._acquire_token(token_func)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 117, in _acquire_token
    return token_func(self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 132, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 349, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\cache_driver.py", line 196, in find
    entry, is_resource_tenant_specific = self._load_single_entry_from_cache(query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\cache_driver.py", line 124, in _load_single_entry_from_cache
    raise AdalError('More than one token matches the criteria. The result is ambiguous.')
adal.adal_error.AdalError: More than one token matches the criteria. The result is ambiguous.

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 333, in execute
    result = list(result)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 121, in __next__
    self.advance_page()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\paging.py", line 107, in advance_page
    self._response = self._get_next(self.next_link)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\resource\resources\v2017_05_10\operations\providers_operations.py", line 222, in internal_paging
    request, header_parameters, **operation_config)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\service_client.py", line 191, in send
    session = self.creds.signed_session()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\adal_authentication.py", line 33, in signed_session
    if 'AADSTS70008:' in (getattr(err, 'error_response', None) or {}).get('error_description') or '':
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by yugangw-msft** [comment]
can you do the following and see whether it gets you back on track?
```bash
   az account clear
   az login
   (az group list or any other cli command)
```

**Comment by cocowalla** [comment]
No, the same issue remains

**Comment by yugangw-msft** [comment]
The first error is the real one: `adal.adal_error.AdalError: More than one token matches the criteria. The result is ambiguous.`
Do you mind send a copy of `c:\users\<user>\.azure\accessTokens.json` to me at yugangw at microsoft dot com? You can redact the `refreshToken` and `accessToken` field values, but please leave the rest intact. I need to understand how CLI ended up having 2 token entries for the same resource under the same tenant after a clean login...

**Comment by yugangw-msft** [comment]
Feel free to reactivate it with more information

**Comment by cocowalla** [comment]
@yugangw-msft reactivating :)

I did send you an email with the file you requested way back in April, but I never heard anything back from you. I still have this issue.

**Comment by yugangw-msft** [comment]
@cocallaw, do you mind sending the file to me again. I am still at yugangw at microsoft dot com.
You can add a new comment here after you did, so I will make sure to get it from outlook.
I do apologize for missing the initial mail.

**Comment by cocallaw** [comment]
@cocowalla can you please resend the file to @yugangw-msft, thanks.

**Comment by cocowalla** [comment]
@yugangw-msft no problem, I've send it again

**Comment by tjprescott** [comment]
Have you tried updating your CLI installation?  It shows you using version 2.0.31. The current version is 2.0.46.

**Comment by yugangw-msft** [comment]
correct, the issue is still there

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
We are migrating to MSAL. Hope this issue will be covered by MSAL. We are aiming to release the first version with MSAL in July 2020.

**Comment by sachamicrosoft** [comment]
@jiasli  - what version of the az cli carries the new MSAL feature? Is it out?

**Comment by jiasli** [comment]
@sachamicrosoft, you may try out the [Beta release](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli#install-or-update) which uses MSAL internally and see if this issue still happens.
