### ISSUE TITLE
Error using --cert with new ad sp credential reset

### ISSUE THREAD

**Issue by Dromadon** [Azure/azure-cli#6274]
`azure-cli (2.0.31) installed with pip on Python 3.6.3. Ubuntu 16.04 amd64 with bash`

When running `az ad sp credential reset --name http://test-sp-name --cert @/tmp/cert.pem` I get the following error:
```'str' object has no attribute 'digest'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1176, in reset_service_principal_credential
    password, keyvault)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 836, in _process_service_principal_creds
    logger.debug("normalizing x509 certificate with fingerprint %s", cert.digest("sha1"))
AttributeError: 'str' object has no attribute 'digest' 
```

It works perfectly fine when using the deprecated `reset-credentials` command : 
`az ad sp reset-credentials --name http://ecosys-dev-sp-spark --cert @/tmp/cert.pem`

**Comment by Dromadon** [comment]
I tried to investigate this by myself and forked the code, and I found out that when running with the `2.0.32` release, it works.
I may have missed something in the changelog, I suppose I will have to wait the `2.0.32` to be released on pypi in order to get it working.

Thanks for your work anyway!
