### ISSUE TITLE
Error listing deployments

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#628]
```
$ az resource group deployment list -g demo100
expected string or bytes-like object
Traceback (most recent call last):
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/main.py", line 55, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/application.py", line 127, in execute
    self.raise_event(self.TRANSFORM_RESULT, event_data=event_data)
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/application.py", line 139, in raise_event
    func(**kwargs)
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 36, in _resource_group_transform
    _add_resource_group(kwargs['event_data']['result'])
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 24, in _add_resource_group
    _add_resource_group(array_item)
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 33, in _add_resource_group
    _add_resource_group(obj[item_key])
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 33, in _add_resource_group
    _add_resource_group(obj[item_key])
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 29, in _add_resource_group
    obj['resourceGroup'] = _parse_id(obj['id'])['resource-group']
  File "/Users/jasonsha/code/azure-cli/src/azure/cli/extensions/transform.py", line 13, in _parse_id
    parts = re.split('/', strid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 203, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```

**Comment by mayurid** [comment]
Tried it with a few scenarios and seems to be working.
Let me know if you still see it
