### ISSUE TITLE
az ad sp list just hangs

### ISSUE THREAD

**Issue by yorek** [Azure/azure-cli#6291]
Tested on az version 2.0.31 on all platforms (Mac OSX, Ubuntu, Windows 10).

Log in via

`az login`

and then try to execute 

`az ad sp list`

to list the application registered in the Tenant. The execution will never finish, and the command will just hand there forever.

Not sure it this helps but sometimes, after stopping the execution with CTRL+C I got the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/telemetry_upload.py", line 8, in <module>
    import urllib2 as HTTPClient
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/telemetry_upload.py", line 12, in <module>
    import urllib.request as HTTPClient
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode KeyboardInterrupt
```

I doesn't happen always, though.

**Comment by yugangw-msft** [comment]
@yorek  if you are in Microsoft tenant, the more likely cause is this command tries to get 200,000+ sp which would take a while. Can you use some filters like `--display-name` to narrow the result? BTW, we are improving the command, e.g. to list your own sps instead of across the tenant.

**Comment by derekbekoe** [comment]
The telemetry issue is also known https://github.com/Azure/azure-cli/issues/6265
cc: @troydai

**Comment by yorek** [comment]
@yugangw-msft you got this, using the --display-name filter worked. Thanks! Looking forward to the improved version :)
