### ISSUE TITLE
Unable to find modules during test execution.

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/azure-cli#6316]
**Describe the bug**
When trying to run the CLI tests for our command module in both the terminal and vs code, we either get an error that it cannot find the "polling" module (when running from the terminal) or an error that it cannot find the "automation" module (when running from vs code). 

`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\base.py", line 140, in setUp
    patch(self)
  File "f:\projects\ecosystem\azure-cli-fork\src\azure-cli-testsdk\azure\cli\testsdk\patches.py", line 75, in patch_long_run_operation_delay
    _shortcut_long_run_operation)
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1199, in _dot_lookup
    __import__(import_path)
  File "C:\Python27\lib\site-packages\msrestazure\polling\arm_polling.py", line 34, in <module>
    from msrest.polling import PollingMethod
ImportError: No module named polling`

**To Reproduce**
Go through dev setup. Attempt to run the iot tests.

**Expected behavior**
I expect the tests to be able to find modules that have already existed. I expect tests to potentially break due to changes in functionality, but not because of missing modules.

**Environment summary**
Install Method: VSCode instructions [here](https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md)
OS version: Windows 10
Shell Type 1: integrated vs code terminal
Shell Type 2: vs code test runner configuration

**Additional context**
I should not that all of this is happening when trying to run the tests inside of vs code with both the integrated terminal as well as in the vs code debug view.

**Comment by tjprescott** [comment]
Please provide the rest of the requested information when reporting a bug:

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  


**Additional context**
Add any other context about the problem here.

**Comment by tjprescott** [comment]
FWIW I didn't have any issue running the IoT tests.

**Comment by andrew-buckley** [comment]
I updated the bug to describe that this is happening inside of VS Code.

**Comment by andrew-buckley** [comment]
No, I get similar output:

```
$ azdev test iot --discover
The tests are set to run against current profile latest.
==================
  Discover Tests
==================

Module 'component' has no tests.
Module 'documentdb' has no tests.
Module 'cloud' has no tests.
Module 'configure' has no tests.
Module 'feedback' has no tests.
Unable to import azure.cli.command_modules.vm.tests.latest.test_vm_actions. Reason: No module named polling
Unable to import azure.cli.command_modules.rdbms.tests.latest.test_rdbms_commands. Reason: No module named latest.test_rdbms_commands

COLLISION: Test 'TestStorageValidators' exists in both 'core' and 'command_modules'. Resolve using <MOD_NAME>.<NAME>

COLLISION: Test 'test_storage_validators' exists in both 'core' and 'command_modules'. Resolve using <MOD_NAME>.<NAME>

COLLISION: Test 'test_no_extensions_dir' exists in both 'command_modules' and 'core'. Resolve using <MOD_NAME>.<NAME>

COLLISION: Test 'test_no_extensions_in_dir' exists in both 'command_modules' and 'core'. Resolve using <MOD_NAME>.<NAME>
ERROR: These modules do not exist: command_modules.

=============
  Run Tests
=============

Drive test by nosetests
test_certificate_lifecycle (azure.cli.command_modules.iot.tests.latest.test_iot_certificate_commands.IotHubCertificateTest) ... ERROR
test_generate_sas_token (azure.cli.command_modules.iot.tests.latest.test_sas_token_auth.TestSasTokenAuth) ... ok
test_dps_lifecycle (azure.cli.command_modules.iot.tests.latest.test_iot_dps_commands.IoTDpsTest) ... ERROR
test_iot_hub (azure.cli.command_modules.iot.tests.latest.test_iot_commands.IoTHubTest) ... ERROR

======================================================================
ERROR: test_certificate_lifecycle (azure.cli.command_modules.iot.tests.latest.test_iot_certificate_commands.IotHubCertificateTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\base.py", line 140, in setUp
    patch(self)
  File "f:\projects\ecosystem\azure-cli-fork\src\azure-cli-testsdk\azure\cli\testsdk\patches.py", line 75, in patch_long_run_operation_delay
    _shortcut_long_run_operation)
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1199, in _dot_lookup
    __import__(import_path)
  File "C:\Python27\lib\site-packages\msrestazure\polling\arm_polling.py", line 34, in <module>
    from msrest.polling import PollingMethod
ImportError: No module named polling

======================================================================
ERROR: test_dps_lifecycle (azure.cli.command_modules.iot.tests.latest.test_iot_dps_commands.IoTDpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\base.py", line 140, in setUp
    patch(self)
  File "f:\projects\ecosystem\azure-cli-fork\src\azure-cli-testsdk\azure\cli\testsdk\patches.py", line 75, in patch_long_run_operation_delay
    _shortcut_long_run_operation)
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1199, in _dot_lookup
    __import__(import_path)
  File "C:\Python27\lib\site-packages\msrestazure\polling\arm_polling.py", line 34, in <module>
    from msrest.polling import PollingMethod
ImportError: No module named polling

======================================================================
ERROR: test_iot_hub (azure.cli.command_modules.iot.tests.latest.test_iot_commands.IoTHubTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\base.py", line 140, in setUp
    patch(self)
  File "f:\projects\ecosystem\azure-cli-fork\src\azure-cli-testsdk\azure\cli\testsdk\patches.py", line 75, in patch_long_run_operation_delay
    _shortcut_long_run_operation)
  File "C:\Python27\lib\site-packages\azure_devtools\scenario_tests\patches.py", line 36, in mock_in_unit_test
    mp.__enter__()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1199, in _dot_lookup
    __import__(import_path)
  File "C:\Python27\lib\site-packages\msrestazure\polling\arm_polling.py", line 34, in <module>
    from msrest.polling import PollingMethod
ImportError: No module named polling

----------------------------------------------------------------------
Ran 4 tests in 6.846s

FAILED (errors=3)


==========
  FAILED
==========

test_certificate_lifecycle
test_dps_lifecycle
test_iot_hub
```

**Comment by yugangw-msft** [comment]
Tried in 2 machines and both work.
I suggest recreate a virtualenv and run the dev-setup. The `msrest` is too old in your machine
