### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib2'

### ISSUE THREAD

**Issue by brandonmcclure** [Azure/azure-cli#6317]
I am getting the error in the title (and below in the full traceback) when I attempt to run any `az` commands.

I run `az login` from powershell or cmd and I am prompted to open a web browser and enter the code. I do so and associate with my work account, and then from my local prompt I get a json response with the 2 VS subscriptions associated with my account, then I get this error. I started running other commands (`disk list`, `consumption usage list`, 'interactive')

When I entered interactive mode it prompted me to send telemetry and based on the error I said no. I kept getting the error inside interactive mode, but when I exited I do not get the error any more. 

I don't mind sending telemetry, but I am going to keep it turned off as that seems to workaround getting this exception. 
---

### Environment summary

MSI installer 
Windows 10
Powershell and cmd

CLI version output:
azure-cli (2.0.32)

acr (2.0.24)
acs (2.0.32)
advisor (0.5.1)
ams (0.1.0)
appservice (0.1.32)
backup (1.1.1)
batch (3.2.2)
batchai (0.2.2)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.23)
core (2.0.32)
cosmosdb (0.1.21)
dla (0.0.19)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.13)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.20)
iot (0.1.20)
keyvault (2.0.21)
lab (0.0.22)
monitor (0.1.6)
network (2.1.0)
nspkg (3.0.2)
profile (2.0.24)
rdbms (0.2.2)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.28)
role (2.0.23)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.32)
vm (2.0.31)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\brandon\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

C:\Users\brandon>Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\telemetry_upload.py", line 8, in <module>
    import urllib2 as HTTPClient
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\telemetry_upload.py", line 12, in <module>
    import urllib.request as HTTPClient
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.
```
```

**Comment by tjprescott** [comment]
Closing due to inactivity. Please open if this is still an issue.
