### ISSUE TITLE
Unable to delete ACR Image by manifest

### ISSUE THREAD

**Issue by novaterata** [Azure/azure-cli#6325]
**Describe the bug**

I'm unable to delete dangling, i.e. tagless, docker images by manifest without a stacktrace

```
PS C:\Program Files\PowerShell\6.0.2> az acr repository delete --name ILLContainerRegistry --image avid/illuminate@sha256:07f1dee110013901be8866c89d8c7829fb3c75072fcbd836f7d6b07bdd15f94a
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\repository.py", line 316, in acr_repository_delete
    yes=yes)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\repository.py", line 469, in _delete_manifest_confirmation
    images = ", ".join(["'{}:{}'".format(repository, str(x)) for x in tags])
TypeError: 'NoneType' object is not iterable


PS C:\Program Files\PowerShell\6.0.2> az acr repository delete --name ILLContainerRegistry --repository avid/illuminate --manifest sha256:07f1dee110013901be8866c89d8c7829fb3c75072fcbd836f7d6b07bdd15f94a
This command is deprecated. The new command for this operation is 'az acr repository delete --name ILLContainerRegistry --image avid/illuminate@sha256:07f1dee110013901be8866c89d8c7829fb3c75072fcbd836f7d6b07bdd15f94a'.
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\repository.py", line 282, in acr_repository_delete
    yes=yes)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\repository.py", line 423, in _legacy_delete
    yes=yes)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acr\repository.py", line 469, in _delete_manifest_confirmation
    images = ", ".join(["'{}:{}'".format(repository, str(x)) for x in tags])
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
Delete an un-tagged image in a registry by manifest digest

**Expected behavior**
The image is deleted

**Environment summary**
Installed with Chocolatey
version 2.0.30
Windows 10 1709 64-bit

**Comment by djyou** [comment]
@novaterata A quick workaround is to add `--yes` to bypass confirmation that's causing the error. Fix is being checked in.
