### ISSUE TITLE
Adding a tag that begins with `@` causes a `FileNotFoundError`

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#6344]
**Describe the bug**
What the title says. :P

**To Reproduce**

```
$ az group create --location canadacentral --resource-group sam-test-rg --tags 'Owner_Slack_Username=@sam' 'Owner=Sam' 'Environment=Dev'
[Errno 2] No such file or directory: 'Sam'
Traceback (most recent call last):
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
cmd_result = self.invocation.execute(args)
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 215, in execute
args = _pre_command_table_create(self.cli_ctx, args)
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 109, in _pre_command_table_create
return _expand_file_prefixed_files(args)
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 104, in _expand_file_prefixed_files
return list([_expand_file_prefix(arg) for arg in args])
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 104, in 
return list([_expand_file_prefix(arg) for arg in args])
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 100, in _expand_file_prefix
return '='.join([arg_split[0], _maybe_load_file(arg_split[1])])
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 92, in _maybe_load_file
return _load_file(poss_file)
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 79, in _load_file
content = read_file_content(os.path.expanduser(path), allow_binary=True)
File "/usr/local/Cellar/azure-cli/2.0.31/libexec/lib/python3.6/site-packages/azure/cli/core/util.py", line 125, in read_file_content
with codecs_open(file_path, encoding=encoding) as f:
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 897, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'Sam'
```

**Expected behavior**
The command should not fail, or should fail gracefully if this is not supported by Azure.

**Environment summary**
Unknown.

**Additional context**
From Azure/azure-docs-cli-python#790.

**Comment by twitchax** [comment]
@samispurs, FYI.

**Comment by yugangw-msft** [comment]
//CC: @tjprescott @troydai, I would vote we proceed with the content instead of raising `file not found`, because  CLI has no firm ways to determine the user is indeed using a file here. Saw similar issue was reported before on passwords.

**Comment by tjprescott** [comment]
Whatever we do, a big funky stack trace isn't the right approach, but I think @yugangw-msft's idea is reasonable.

**Comment by twitchax** [comment]
Nice turn around, all: thanks!
