### ISSUE TITLE
Recently azure-cli is throwing an arguement "nonetype error" for az interactive

### ISSUE THREAD

**Issue by jayctd** [Azure/azure-cli#6370]
Starting roughly 2 weeks ago when attempting to launch the interactive shell from my workstation I get the following error. 

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

This happened before the 18.04 update as well, it also happened roughly at the same time on a virtual machine of mine at home at roughly the same time. 

Subsequent attempts at removing the packages, and resetting up the repository and re-installation have proved unsuccessful 

jaycd@desktop:~$ az interactive
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 332, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/__init__.py", line 13, in start_shell
    AzInteractiveShell(cmd.cli_ctx, style)()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/app.py", line 93, in __init__
    gathered_commands = GatherCommands(self.config)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/gather_commands.py", line 91, in __init__
    self._gather_from_files(config)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/gather_commands.py", line 140, in _gather_from_files
    if '==SUPPRESS==' not in command_params[param]['help']:
TypeError: argument of type 'NoneType' is not iterable

---

### Environment summary
Install method apt-get 
Ubuntu 18.04

azure-cli (2.0.32)

acr (2.0.24)
acs (2.0.32)
advisor (0.5.1)
ams (0.1.0)
appservice (0.1.32)
backup (1.1.1)
batch (3.2.2)
batchai (0.2.2)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.23)
core (2.0.32)
cosmosdb (0.1.21)
dla (0.0.19)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.13)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.20)
iot (0.1.20)
keyvault (2.0.21)
lab (0.0.22)
monitor (0.1.6)
network (2.1.0)
nspkg (3.0.2)
profile (2.0.24)
rdbms (0.2.2)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.28)
role (2.0.23)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.32)
vm (2.0.31)

Python location '/opt/az/bin/python3'
Extensions directory '/home/jeredr/.azure/cliextensions'

Python (Linux) 3.6.1 (default, May  1 2018, 18:23:09) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal

```
```

**Comment by williexu** [comment]
Please clear your help_dump cache.
This will likely be in the `.azure-shell` directory from your home directory.

**Comment by jayctd** [comment]
clearing the help_dump.json file worked no more errors when launching az interactive THANKS!

**Comment by williexu** [comment]
@jayctd no problem I've also raised an issue to make interactive more resilient towards this:
https://github.com/Azure/azure-cli/issues/6382
