### ISSUE TITLE
Azure Cloud Shell CLI Data lake error

### ISSUE THREAD

**Issue by kbaig109** [Azure/azure-cli#6406]
**Describe the bug**
Connected to the Azure Portal Cloud shell Bash .. 

**To Reproduce**
Type: az dls fs list --id "datalake-account-id" --path "/"

**Expected behavior**
list of files or folders in that directory

**Environment summary**
az --version
azure-cli (2.0.32)

acr (2.0.24)
acs (2.0.32)
advisor (0.5.1)
ams (0.1.0)
appservice (0.1.32)
backup (1.1.1)
batch (3.2.2)
batchai (0.2.2)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.23)
core (2.0.32)
cosmosdb (0.1.21)
dla (0.0.19)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.13)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.20)
iot (0.1.20)
keyvault (2.0.21)
lab (0.0.22)
monitor (0.1.6)
network (2.1.0)
nspkg (3.0.2)
profile (2.0.24)
rdbms (0.2.2)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.28)
role (2.0.23)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.32)
vm (2.0.31)

Python location '/opt/az/bin/python3'
Extensions directory '/home/mirza/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Apr 30 2018, 23:14:03)
[GCC 5.4.0 20160609]

**Additional context**
Error reported on the console :: 
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 332, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/custom.py", line 122, in list_adls_items
    return cf_dls_filesystem(cmd.cli_ctx, account_name).ls(path, detail=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/_client_factory.py", line 37, in cf_dls_filesystem
    url_suffix=cli_ctx.cloud.suffixes.azure_datalake_store_file_system_endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 68, in __init__
    self.connect()
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 85, in connect
    self.azure = DatalakeRESTInterface(token=self.token, **self.kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/lib.py", line 249, in __init__
    self.head = {'Authorization': token.signed_session().headers['Authorization']}
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 24, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 451, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 305, in _get_token_from_cloud_shell
    auth.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 693, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
mirza@Azure:~$ az dls fs list --id "086b3d2c-d0ed-4991-aa13-a46fd27965bf" --path "/"
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 332, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/custom.py", line 122, in list_adls_items
    return cf_dls_filesystem(cmd.cli_ctx, account_name).ls(path, detail=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/dls/_client_factory.py", line 37, in cf_dls_filesystem
    url_suffix=cli_ctx.cloud.suffixes.azure_datalake_store_file_system_endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 68, in __init__
    self.connect()
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/core.py", line 85, in connect
    self.azure = DatalakeRESTInterface(token=self.token, **self.kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/datalake/store/lib.py", line 249, in __init__
    self.head = {'Authorization': token.signed_session().headers['Authorization']}
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 24, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 451, in _retrieve_token
    return self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 305, in _get_token_from_cloud_shell
    auth.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 693, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:

**Comment by yugangw-msft** [comment]
@kbaig109 it is by design that DLS commands don't work out of box in cloud shell because shell is not able to provide the token for CLI users to access the data lake resources. This has been a known issue for a while. Same problem exists with Azure Batch.
Your workaround is to run `az login` to login and run the command like on a regular desktop.
