### ISSUE TITLE
az command line on Ubuntu gave ERR

### ISSUE THREAD

**Issue by Powerhelmsman** [Azure/azure-cli#6416]
Describe the bug
Running az shell command on my own ubuntu host gave ERR:
== START
$ VM1_IP_ADDR=$(az network public-ip show --ids $IP_ID \
-g TutorialResources 
--query ipAddress 
-o tsv)
argument of type 'int' is not iterable
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
cmd_result = self.invocation.execute(args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 275, in execute
parsed_args = self.parser.parse_args(args)
File "/opt/az/lib/python3.6/argparse.py", line 1730, in parse_args
args, argv = self.parse_known_args(args, namespace)
File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
positionals_end_index = consume_positionals(start_index)
File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
take_action(action, args)
File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
action(self, namespace, argument_values, option_string)
File "/opt/az/lib/python3.6/argparse.py", line 1133, in call
subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
positionals_end_index = consume_positionals(start_index)
File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
take_action(action, args)
File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
action(self, namespace, argument_values, option_string)
File "/opt/az/lib/python3.6/argparse.py", line 1133, in call
subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
positionals_end_index = consume_positionals(start_index)
File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
take_action(action, args)
File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
action(self, namespace, argument_values, option_string)
File "/opt/az/lib/python3.6/argparse.py", line 1133, in call
subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
File "/opt/az/lib/python3.6/argparse.py", line 1968, in _parse_known_args
start_index = consume_optional(start_index)
File "/opt/az/lib/python3.6/argparse.py", line 1908, in consume_optional
take_action(action, args, option_string)
File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
action(self, namespace, argument_values, option_string)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 199, in call
if 'id' in json_val:
TypeError: argument of type 'int' is not iterable

The issue is from https://github.com/MicrosoftDocs/feedback/issues/390#

**Comment by tjprescott** [comment]
There is insufficient information for us to do anything with this. Please reopen the issue and provided the requested details.

**Comment by Powerhelmsman** [comment]
@tjprescott what's kind of information you want? @maheoasic is the user to submit the issue.

**Comment by tjprescott** [comment]
@maheoasic please open a new bug report in this repo and provide as much of the information in the template that you can.
