### ISSUE TITLE
[Stack] 'az role'  commands and 'az ad sp create-for-rbac' commands are broken for azure stack

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#6433]
**Describe the bug**
When we did the profile 2017-03-09-profile, we never really consideredroleassignments/roledefintions resource types  for customization  as azurestack was in parity with azure.  In a April release azure-mgmt-authorization pumped up the api-version and the CLI is broken for azure stack

**To Reproduce**
switch to 2017-03-09 profile and then run az role commands

**To  Fix**
 we need the multi-api versioned azure-mgmt-authorization package as a pre-req , SDK issue here https://github.com/Azure/azure-sdk-for-python/issues/2623

**WorkAround**
Using an older version of the azure-cli should work.  https://azurecliprod.azureedge.net/msi/azure-cli-2.0.25.msi

**Comment by cblackuk** [comment]
Any update on this guys please? This has been broken for months and is preventing users consuming Azure Stack service. @bganapa

**Comment by cblackuk** [comment]
Also, it is worth noting that despite the new azure-mgmt-authorization 50.0 was released and if you manually install it, then change manually the API version in python authorization_management_client_py all you get is:

```azurecli
bash-4.4# az role assignment list
'RoleAssignment' object has no attribute 'scope'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 176, in list_role_assignments
    include_inherited, include_groups)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 437, in _search_role_assignments
    assignments = [a for a in assignments if (
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 440, in <listcomp>
    a.scope.lower() == scope.lower()
AttributeError: 'RoleAssignment' object has no attribute 'scope'
```

**Comment by viananth** [comment]
Fixed with Multi-Api Authorization package released.
