### ISSUE TITLE
az cli unable to create service principal for multi tenant applications

### ISSUE THREAD

**Issue by dharshanr** [Azure/azure-cli#6439]
AD service prinical creation fails from the az cli when the application is a multi tenant application in a different tenant. It works if the application is in the same tenant.

az ad sp create --id <redacted>
Resource '<redacted>' does not exist or one of its queried reference-property objects are not present.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 697, in create_service_principal
    return _create_service_principal(cmd.cli_ctx, identifier)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\role\custom.py", line 711, in _create_service_principal
    result = [client.applications.get(identifier)]
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\graphrbac\operations\applications_operations.py", line 265, in get
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Resource 'redactted' does not exist or one of its queried reference-property objects are not present.

**To Reproduce**
CLI version is 2.0.30
az ad sp create --id <redacted>

**Expected behavior**
The service pricipal should get created

**Environment summary**
Windows server, installed with the msi
CLI version is 2.0.30

**Additional context**

**Comment by colemickens** [comment]
cc: @yugangw-msft

**Comment by dharshanr** [comment]
Thanks for the fix - which version of the CLI can I expect to test the fix in?

**Comment by yugangw-msft** [comment]
Once related PR is merged, it will be released around June 19.
Before that, you can use developer builds: https://github.com/Azure/azure-cli#docker
