### ISSUE TITLE
az sql db list-editions doesn't work @ shell.azure.com

### ISSUE THREAD

**Issue by nporaMep** [Azure/azure-cli#6450]
**Describe the bug**
If I run **az sql db list-editions --location "Australia East"** at shell.azure.com it throws exception.
Works from local PowerShell.

**Stack trace is this:**
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\commands\__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\commands\__init__.py", line 310, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\commands\__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\sql\custom.py", line 729, in db_list_capabilities
    editions = _get_default_capability(capabilities.supported_server_versions).supported_editions
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\sql\custom.py", line 77, in _get_default_capability
    next(c for c in capabilities if c.status == CapabilityStatus.available))
StopIteration

**Expected behavior**
To work same as on local machine in PowerShell = return list of SQL DB editions info.

**Environment summary**
https://shell.azure.com in Chrome

**Additional context**
Tried for Australia and Europe. Tried with short name and display name of location. Doesn't work with either.

**Comment by nporaMep** [comment]
Narrowed it down to version. It's broken in 2.0.33 on local machine. Works in 2.0.32.

**Comment by jaredmoo** [comment]
This doesn't repro for me, (probably because my subscription has access to more Azure regions), but I think I know what caused this. In 2.0.32 and earlier the capability logic was hardcoded to always get server version 12.0, I changed this to get the default server version. But if you don't have access to that Azure region then there is no default server version, which will give you this StopIteration error.

Fixing this issue in https://github.com/Azure/azure-cli/pull/6471

**Comment by jaredmoo** [comment]
Forgot to mention: thanks for reporting this issue!
