### ISSUE TITLE
Connect to AzureStack failed using version 2.0.34

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-cli#6507]
**Describe the bug**
Use azure cli 2.0.34 to connect azure stack hit issue, use azure cli 2.0.33, no such issue

The authority url must be of the format https://login.microsoftonline.com/your_tenant
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 131, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 167, in find_subscriptions_on_login
    username, sp_auth, tenant, self._ad_resource_uri)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 706, in find_from_service_principal_id
    context = self._create_auth_context(tenant, False)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 722, in _create_auth_context
    return self._auth_context_factory(self.cli_ctx, tenant, token_cache)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 78, in _authentication_context_factory
    return adal.AuthenticationContext(authority_url, cache=cache, api_version=None, validate_authority=(not is_adfs))
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 88, in __init__
    self.authority = Authority(authority, validate_authority is None or validate_authority)
  File "/opt/az/lib/python3.6/site-packages/adal/authority.py", line 49, in __init__
    self._validate_authority_url()
  File "/opt/az/lib/python3.6/site-packages/adal/authority.py", line 74, in _validate_authority_url
    raise ValueError("The authority url must be of the format https://login.microsoftonline.com/your_tenant")
ValueError: The authority url must be of the format https://login.microsoftonline.com/your_tenant

**To Reproduce**
Follow steps here to connect azure stack using azure cli
https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles-azurecli2#connect-to-azure-stack

**Expected behavior**
login in azure stack successfully using azure cli

**Environment summary**
Install azure cli from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest on ubuntu against azure stack env
For workaround I install specified azure cli version 2.0.33

**Additional context**

**Comment by yugangw-msft** [comment]
Fixed by #6500
