### ISSUE TITLE
TypeError: new_cluster() missing 1 required positional argument: 'client' ServiceFabric cluster create

### ISSUE THREAD

**Issue by Dawny33** [Azure/azure-cli#6549]
I get the following error when trying to create an Azure Fabric Cluster from the CLI:

Command:
`az sf cluster create --resource-group 'datasciencesdev' --location "southeastasia"   --template-file template.json --parameter-file parameters.json
`

Error Trace:
```
new_cluster() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
TypeError: new_cluster() missing 1 required positional argument: 'client'

```

OS: Ubuntu 16 (Azure VM)
Environment: A python3 virtualenv with sfctl installed

**Comment by a-santamaria** [comment]
Are you still experiencing this issue? we were unable to reproduce it.
