### ISSUE TITLE
Policy assignment - Scope: resource group

### ISSUE THREAD

**Issue by jorgecotillo** [Azure/azure-cli#6616]
**Describe the bug**
Assigning a policy definition to a resource group

**To Reproduce**

1. az login

2. Create any policy (I am using the one from this [website](https://docs.microsoft.com/en-us/azure/azure-policy/create-manage-policy):

az policy definition create --name 'denyCoolTiering' --description 'Deny cool access tiering for storage' --rules '{
    "if": {
        "allOf": [{
                "field": "type",
                "equals": "Microsoft.Storage/storageAccounts"
            },
            {
                "field": "kind",
                "equals": "BlobStorage"
            },
            {
                "not": {
                    "field": "Microsoft.Storage/storageAccounts/accessTier",
                    "equals": "cool"
                }
            }
        ]
    },
    "then": {
        "effect": "deny"
    }
}'

3. Then create an assignment to a resource group (scope):

az policy assignment create --name 'assignment test' --display-name 'testing rg assignment' --scope "/subscriptions/{your_subscription}{your_resource_group_name}" --policy "/subscriptions/{your_subscription}/providers/Microsoft.Authorization/policyDefinitions/denyCoolTiering"

**Expected behavior**
Successful policy assignment to a resource group

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Python version**:
Python (Darwin) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Az cli version**:
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

**Additional context**
Assigning a policy to a subscription works.
I tried the assignment via the cli and the python sdk and same error. 
It works using powershell though.

**Error stack trace**
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 337, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 311, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 421, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 935, in create_policy_assignment
    assignment)
  File "/usr/local/Cellar/azure-cli/2.0.38/libexec/lib/python3.6/site-packages/azure/mgmt/resource/policy/v2017_06_01_preview/operations/policy_assignments_operations.py", line 162, in create
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.resource.policy.v2017_06_01_preview.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Comment by yugangw-msft** [comment]
@jorgecotillo, sorry for the delay, but I tried out the examples and both commands worked fine. Please note the latest CLI is using newer api-version at `2018-05-01` which might contain bug fixes towards  the error you mentioned. If it still doesn't work, please run with `--debug` and send the trace to me at yugangw at microsoft dot com.
I will keep the issue active for a few day and will close unless we find a repro
