### ISSUE TITLE
invoices_operations.py generating a stack trace

### ISSUE THREAD

**Issue by Matty9191** [Azure/azure-cli#6657]
**Describe the bug**

I am getting a Python stack trace when I run `az billing invoice list`:

(UnsupportedSubscriptionType) Offer id XXXXX is not supported.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 323, in execute
    result = list(result)
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/paging.py", line 121, in __next__
    self.advance_page()
  File "/usr/lib64/az/lib/python2.7/site-packages/msrest/paging.py", line 107, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/mgmt/billing/operations/invoices_operations.py", line 119, in internal_paging
    raise models.ErrorResponseException(self._deserialize, response)
ErrorResponseException: (UnsupportedSubscriptionType) Offer id XXXXXX is not supported.

I was expecting a one line error message instead of the stack trace. Thought I would let you know.

**Comment by tjprescott** [comment]
Stack trace no longer displayed.
