### ISSUE TITLE
az eventhubs eventhub create throws BadRequest when I specify only the mandatory parameters

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-cli#6676]
**Describe the bug**
When I try `az eventhubs eventhub create` command it returns BadRequest, however, when I added the `--message-retention` and `--partition-count` it works.  However, these two parameters is not required. 

**To Reproduce**

To cause an error. 

```bash
$ az eventhubs eventhub create --name downtime --namespace-name  dooh2tsushisome -g dooh2tsushipro0109-rg
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/eventhubs/custom.py", line 91, in cli_eheventhub_create
    parameters=eventhubparameter1)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/eventhub/operations/event_hubs_operations.py", line 168, in create_or_update
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.eventhub.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'
```

To success. 

```bash
az eventhubs eventhub create --name downtime --namespace-name dooh2tsushisome -g dooh2tsushipro0109-rg --message-retention 1 --partition-count 15
```

**Expected behavior**

The first one should work. or `--message-retention` and `--partition-count` should be required

```
$ az eventhubs eventhub create --help

Command
    az eventhubs eventhub create: Creates the Event Hubs Eventhub.

Arguments
    --name -n           [Required]: Name of Eventhub.
    --namespace-name    [Required]: Name of Namespace.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
    --enable-capture              : A boolean value that indicates whether capture description is
                                    enabled.  Allowed values: false, true.
    --message-retention           : Number of days to retain events for this Event Hub, value should
                                    be 1 to 7 days.
    --partition-count             : Number of partitions created for the Event Hub, allowed values
                                    are from 1 to 32 partitions.
    --status                      : Status of Eventhub.  Allowed values: Active, Disabled,
                                    ReceiveDisabled, SendDisabled.
```

**Environment summary**

```bash
$ az --version
azure-cli (2.0.31)

acr (2.0.23)
acs (2.0.31)
advisor (0.5.1)
appservice (0.1.31)
backup (1.1.1)
batch (3.2.0)
batchai (0.2.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.12)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.0)
container (0.1.22)
core (2.0.31)
cosmosdb (0.1.20)
dla (0.0.19)
dls (0.0.21)
eventgrid (0.1.12)
eventhubs (0.1.2)
extension (0.0.12)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.19)
iot (0.1.19)
keyvault (2.0.21)
lab (0.0.21)
monitor (0.1.5)
network (2.0.28)
nspkg (3.0.2)
profile (2.0.22)
rdbms (0.2.1)
redis (0.2.12)
reservations (0.1.2)
resource (2.0.27)
role (2.0.22)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.31)
vm (2.0.30)

Python location '/opt/az/bin/python3'
Extensions directory '/home/ushio/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Apr  6 2018, 15:16:25)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by jleach** [comment]
So here is the problem: If you have a Basic tier namespace then ` --message-retention` is not applicable, however, you can't leave the parameter blank in the CLI command. You must set it to ` --message-retention 1` for the create command to work. You can leave the `--partition-count` parameter empty. Also, the error message is not helpful.

Tested with azure-cli (2.0.43).

**Comment by jfggdl** [comment]
@dsouzaarun, would you please validate the behavior and provide clarity to @TsuyoshiUshio.

Thanks.
