### ISSUE TITLE
New `az login` feature throws error in python 2 environment

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#6707]
**Describe the bug**
From: https://github.com/Azure/azure-cli/pull/6689/files
the python2 `platform.uname()` returns a tuple, not a uname object like in python3.
code for opening browser expects the latter.

**To Reproduce**
```
(env2) root@36ed089dae23:~/azure-cli# az login
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/azure-cli/src/azure-cli-core/azure/cli/core/_profile.py", line 1033, in _get_authorization_code_worker
    succ = open_page_in_browser(url)
  File "/root/azure-cli/src/azure-cli-core/azure/cli/core/util.py", line 262, in open_page_in_browser
    platform_name = uname.system.lower()
AttributeError: 'tuple' object has no attribute 'system'

Login failed
```
**Expected behavior**
No failure, either browser or previous device code login fallback.

**Comment by yugangw-msft** [comment]
Released 2.0.41 works fine, it is just the current dev branch is not working. I will submit a PR with test coverage.
