### ISSUE TITLE
python error when entering interactive mode on macos

### ISSUE THREAD

**Issue by drum7** [Azure/azure-cli#6715]
**Describe the bug**
When entering interactive (az interactive) - shell throws several errors seemingly related to python.

**To Reproduce**
Install azure-cli following homebrew installation method discussed [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
type "az interactive" to enter interactive mode

**Expected behavior**
should be able to run in interactive mode with shell complete

**Environment summary**
Install Method: Homebrew
CLI version: 2.0.38
OS version: macOS 10.13.5 (High Sierra)
Shell Type: bash (Terminal)

**Additional context**
See attached log for error.
[azurecli-error.txt](https://github.com/Azure/azure-cli/files/2161203/azurecli-error.txt)

Also attempted to perform the Python relink mentioned in the [troubleshooting section](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#troubleshooting) of the Microsoft guide has no effect / is incorrect syntax.
[azurecli-pythonrelinkerror.txt](https://github.com/Azure/azure-cli/files/2161204/azurecli-pythonrelinkerror.txt)

**Comment by drum7** [comment]
Continues to happen on CLI ver 2.0.41 when entering Interactive Session.

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/command_modules/interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/command_modules/interactive/azclishell/_dump_commands.py", line 85, in dump_command_table
    main_loader.load_arguments(None)----------------------------------------------------------------------------------------------------------------------------------
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/command_modules/interactive/azclishell/_dump_commands.py", line 48, in load_arguments--------------------------------------------------------------------------------------------------------------------------------------------------------------
    command.load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 140, in load_arguments----------------------
    super(AzCliCommand, self).load_arguments()side the application
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader() query of the previous command
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 425, in default_arguments_loader
    op = handler or self.get_op_handler(operation) the previous command
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 469, in get_op_handler
    op = import_module(mod_to_import) a scope
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                Hit [enter] to refresh
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.maps'

**Comment by torbjornvatn** [comment]
I have a similar issue, but the error message is `ModuleNotFoundError: No module named 'azure.mgmt.botservice'`

**Comment by jlucktay** [comment]
> I have a similar issue, but the error message is `ModuleNotFoundError: No module named 'azure.mgmt.botservice'`

Had the same issue just now, when running `az find -q vm extension list`:
```
No module named 'azure.mgmt.botservice'
```

[Here is the full stack trace](https://gist.github.com/jlucktay/e4b30ef896d5b10331a6954d63de2060).
