### ISSUE TITLE
Service bus queue create - Stacktrace on name not found

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#6728]
A red stacktrace is shown when `az servicebus queue create` throws an `Operation returned an invalid status code 'Not Found'` not clearly indicating what was 'Not Found'.

**To Reproduce**
Create an empty resource group then attempt to immediately create a queue in that RG.

```
$ az servicebus queue create -g myrg --namespace-name mynamespace -n myname
Operation returned an invalid status code 'Not Found'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 337, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 311, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 170, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 421, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/cli/command_modules/servicebus/custom.py", line 102, in cli_sbqueue_create
    parameters=queue_params)
  File "/usr/local/Cellar/azure-cli/2.0.41/libexec/lib/python3.7/site-packages/azure/mgmt/servicebus/operations/queues_operations.py", line 167, in create_or_update
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.servicebus.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Not Found'
```

**Expected behavior**
No stacktrace and the name that was not found should be returned. e.g. Was it the queue that was not found?

**Environment summary**
Homebrew install.

```
~ debekoe$ az --version
azure-cli (2.0.41)

acr (2.0.28)
acs (2.1.3)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.36)
backup (1.1.2)
batch (3.2.4)
batchai (0.3.1)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.15)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.17)
consumption (0.3.1)
container (0.2.1)
core (2.0.41)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.1.0)
feedback (2.1.3)
find (0.2.11)
interactive (0.3.25)
iot (0.1.21)
keyvault (2.0.23)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.8)
network (2.1.5)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.27)
rdbms (0.2.5)
redis (0.2.14)
reservations (0.2.1)
resource (2.0.32)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.35)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/debekoe/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jul  5 2018, 10:19:34) 
[Clang 9.1.0 (clang-902.0.39.2)]
```

**Additional context**
Turns out it was the namespace that was not found and I needed to use `az servicebus namespace create` to create the namespace first.

**Comment by v-Ajnava** [comment]
This should be Resolved. I verified by creating the queue In non-existing namespace, got the below error message.

ParentResourceNotFound - Can not perform requested operation on nested resource. Parent resource 'testingqueuecreationNS' not found.

I am closing the issue. 
Please let us know if you have any more questions.
