### ISSUE TITLE
az container create from yaml gives 'LROPoller' error

### ISSUE THREAD

**Issue by tmakin** [Azure/azure-cli#6830]
**Describe the bug**
When I try and create a container from a yaml definition I get a python error.
```
AttributeError: 'LROPoller' object has no attribute 'output'
```
However, the deployment does appear to succeeed. Full trace below:
```
PS D:\Docker> az container create -g BackendServices -f test.yaml

'LROPoller' object has no attribute 'output'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-core\azure\cli\core\commands\__init__.py", line 337, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-core\azure\cli\core\commands\__init__.py", line 311, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-core\azure\cli\core\commands\__init__.py", line 170, in __call__
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-core\azure\cli\core\__init__.py", line 421, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-container\azure\cli\command_modules\container\custom.py", line 101, in create_container
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-pfctf_lg\azure-cli-container\azure\cli\command_modules\container\custom.py", line 251, in _create_update_from_file
AttributeError: 'LROPoller' object has no attribute 'output'

PS D:\Docker> az container list -g BackendServices -o table
Name        ResourceGroup    ProvisioningState    Image                           IP:ports                  CPU/Memory       OsType    Location
----------  ---------------  -------------------  ------------------------------  ------------------------  ---------------  --------  ----------
test1234    BackendServices  Succeeded            nginx                                                     1.0 core/1.5 gb  Linux     westeurope
```

**To Reproduce**
test.yaml
```
apiVersion: 2018-06-01
location: westeurope
name: test1234
properties:
  containers:
  - name: mycontainer
    properties:
      image: nginx
      ports: []
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
  osType: Linux
  restartPolicy: Always
tags: null
type: Microsoft.ContainerInstance/containerGroups
```

**Expected behavior**
No error on successful deployment

**Environment summary**
* azure-cli (2.0.41)
* windows 10
* installed from msi:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

**Comment by samkreter** [comment]
@tmakin This was a bug in that version of the CLI from upgrading to long-running operations. It is fixed in the current release of the CLI.
