### ISSUE TITLE
'NoneType' object is not iterable on az acr repository list --name

### ISSUE THREAD

**Issue by xadag-yogarik** [Azure/azure-cli#6885]
Hello,

**Describe the bug**
On mac os x el capitan got an error when trying this command 

az acr repository list --name xxxx --output table

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acr/repository.py", line 255, in acr_repository_list
    top=top)
  File "/usr/local/Cellar/azure-cli/2.0.42/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acr/repository.py", line 212, in _obtain_data_from_registry
    result_list += result
TypeError: 'NoneType' object is not iterable

**Environment summary**

Darwin mac-343.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64  

Thanks !

**Comment by mmacy** [comment]
I can confirm that this error is thrown if there are **no images** (and thus, no repositories) in the specified registry. Error is thrown in local install of 2.0.43 as well as Cloud Shell.

@xadag-yogarik Do you know if you had any images in your registry when this error was thrown?

Cc: @sajayantony

**Comment by sajayantony** [comment]
@yugangw-msft  - can you tag this as acr?

**Comment by djyou** [comment]
This has been fixed in https://github.com/Azure/azure-cli/pull/6980

**Comment by tjprescott** [comment]
Thanks @djyou
