### ISSUE TITLE
az consumption usage list does not accept --billing-period-name or -p

### ISSUE THREAD

**Issue by louspringer** [Azure/azure-cli#6902]
**Describe the bug**
```bash
az consumption usage list --billing-period-name 201808-1
```
Produces error:
```
list_by_billing_period() missing 1 required positional argument: 'billing_period_name'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 333, in execute
    cmd.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/command_modules/consumption/_exception_handler.py", line 17, in consumption_exception_handler
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.37/libexec/lib/python3.6/site-packages/azure/cli/command_modules/consumption/custom.py", line 30, in cli_consumption_list_usage
    return list(client.list_by_billing_period(expand=expand, filter=filter_expression))
TypeError: list_by_billing_period() missing 1 required positional argument: 'billing_period_name'
```
**To Reproduce**
```bash
az consumption usage list --billing-period-name 201808-1
```

**Expected behavior**
A list of usage for the specified billing period. 

**Environment summary**
macos 10.13.6
installed via brew

az --version
azure-cli (2.0.42)

acr (2.1.0)
acs (2.2.0)
advisor (0.6.0)
ams (0.2.0)
appservice (0.2.0)
backup (1.2.0)
batch (3.3.0)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.0)
core (2.0.42)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.0)
extension (0.2.0)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.26)
iot (0.2.0)
keyvault (2.2.0)
lab (0.1.0)
maps (0.3.0)
monitor (0.2.0)
network (2.2.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.0)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.0)
resource (2.1.0)
role (2.1.0)
servicebus (0.2.0)
servicefabric (0.1.0)
sql (2.1.0)
storage (2.1.0)
vm (2.1.0)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/lou/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)]

**Additional context**
None.

**Comment by gisle** [comment]
Got it to work by applying the following patch:

```patch
--- /usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/consumption/custom.py	2018-11-01 21:31:58.000000000 +0100
+++ custom.py	2018-12-07 14:16:43.000000000 +0100
@@ -27,7 +27,7 @@
     if billing_period_name and top:
         return list(client.list_by_billing_period(billing_period_name, expand=expand, filter=filter_expression, top=top).advance_page())
     elif billing_period_name and not top:
-        return list(client.list_by_billing_period(expand=expand, filter=filter_expression))
+        return list(client.list_by_billing_period(billing_period_name=billing_period_name, expand=expand, filter=filter_expression))
     elif not billing_period_name and top:
         return list(client.list(expand=expand, filter=filter_expression, top=top).advance_page())
     return client.list(expand=expand, filter=filter_expression)
```

**Comment by aheumaier** [comment]
Same thin is still valid for 
``` bash
user@host:~$ az --version 
azure-cli                         2.0.64
(...)
consumption                        0.4.2
```
