### ISSUE TITLE
Error- running az login post sudo apt-get install azure-cli following steps https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

### ISSUE THREAD

**Issue by RajSelv** [Azure/azure-cli#6947]
**Error- running az login **
Issue while connecting to azure via cli 2.0 installed on Ubuntu-linux following steps from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**To Reproduce**
The following commands are successful -
sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install azure-cli
When i run az login it leads to error.

**Expected behavior**
Trying to connect with azure via CLI 2.0 from my Vbox linux/Ubuntu VM.

**Environment summary**
Install Method (Virtualbox 5.2.16, Ubuntu LTS-Linux- Azure cli 2.0 )  

**Additional context**
raja@raja-VirtualBox:~$ az login
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/raja/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 509, in get_default_cli
    help_cls=AzCliHelp)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 299, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 236, in get_active_cloud_name
    _set_active_cloud(cli_ctx, AZURE_PUBLIC_CLOUD.name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 229, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 91, in set_value
    self.set(config)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 78, in set
    with open(self.config_path, 'w') as configfile:
IOError: [Errno 13] Permission denied: '/home/raja/.azure/config'
raja@raja-VirtualBox:~$ sudo az login
[sudo] password for raja: 
sudo: az: command not found

**Comment by yugangw-msft** [comment]
can you run `sudo az login --debug` and share the trace?

**Comment by RajSelv** [comment]
well couldnot get any info on running the above, hence sharing the sequence of commands ran through..
Just to re-iterate the context, am trying to install CLI 2.0 on Vbox- ubuntu 18.04desktopamd64.iso
**********************************
raja@raja-VirtualBox:~$ echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |     sudo tee /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main
raja@raja-VirtualBox:~$ curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   2671      0 --:--:-- --:--:-- --:--:--  2671
OK
raja@raja-VirtualBox:~$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.6.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
raja@raja-VirtualBox:~$ sudo apt-get update && sudo apt-get install azure-cli
Ign:1 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic InRelease
Hit:2 http://fi.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease                
Get:4 http://fi.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]   
Get:5 https://packages.microsoft.com/repos/azure-cli bionic InRelease [2 808 B]
Err:6 http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release         
  404  Not Found [IP: 91.189.95.83 80]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Get:8 http://fi.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB] 
Get:10 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages [2 264 B]
Get:11 http://fi.archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [138 kB]
Get:12 http://fi.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [31,4 kB]
Get:13 http://fi.archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [53,7 kB]
Get:14 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [156 kB]
Get:15 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [156 kB]
Get:16 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [69,6 kB]
Get:17 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [149 kB]
Get:18 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [150 kB]
Hit:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease        
Get:19 http://fi.archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [255 kB]
Get:20 http://fi.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2 464 B]
Get:21 http://fi.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [5 100 B]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]
Get:23 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [46,6 kB]
Get:24 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [46,7 kB]
Get:25 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [26,1 kB]
Get:26 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [5 796 B]
Get:27 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 48x48 Icons [6 962 B]
Get:28 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 64x64 Icons [8 064 B]
Reading package lists... Done               
E: The repository 'http://ppa.launchpad.net/chris-lea/node.js/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
raja@raja-VirtualBox:~$ az login
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/raja/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 509, in get_default_cli
    help_cls=AzCliHelp)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 299, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 236, in get_active_cloud_name
    _set_active_cloud(cli_ctx, AZURE_PUBLIC_CLOUD.name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 229, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 91, in set_value
    self.set(config)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 78, in set
    with open(self.config_path, 'w') as configfile:
IOError: [Errno 13] Permission denied: '/home/raja/.azure/config'
raja@raja-VirtualBox:~$ sudo az login
sudo: az: command not found
raja@raja-VirtualBox:~$ sudo az login --debug
sudo: az: command not found
raja@raja-VirtualBox:~$

**Comment by yugangw-msft** [comment]
could you refresh the shell? If you are on bash, maybe try one of the options mentioned in this [SO thread](https://stackoverflow.com/questions/2518127/how-do-i-reload-bashrc-without-logging-out-and-back-in)?

**Comment by yugangw-msft** [comment]
Also, based on the error you posted, can you give the non root account the permission to the `/home/raja/.azure`? If you do, then `az` should just work. Do you have to run `az` under root?

**Comment by RajSelv** [comment]
Execution as suggested, not sure if it made any difference,
Think this is how you want me to try here, please say otherwise.

1. execution to refresh shell
raja@raja-VirtualBox:~$ source ~/.bashrc
raja@raja-VirtualBox:~$ sudo az login
sudo: az: command not found
2. az login from /home/raja/.azureraja@raja-VirtualBox:~$ sudo cd /home/raja/.azure
sudo: cd: command not found
raja@raja-VirtualBox:~$ cd /home/raja/.azure
raja@raja-VirtualBox:~/.azure$ az login
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/raja/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 509, in get_default_cli
    help_cls=AzCliHelp)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 299, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 236, in get_active_cloud_name
    _set_active_cloud(cli_ctx, AZURE_PUBLIC_CLOUD.name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 229, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 91, in set_value
    self.set(config)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 78, in set
    with open(self.config_path, 'w') as configfile:
IOError: [Errno 13] Permission denied: '/home/raja/.azure/config'
raja@raja-VirtualBox:~/.azure$ sudo az login
sudo: az: command not found
raja@raja-VirtualBox:~/.azure$ sudo az login --debug 
sudo: az: command not found
raja@raja-VirtualBox:~/.azure$ az login --debug 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/raja/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 32, in <module>
    az_cli = get_default_cli()
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 509, in get_default_cli
    help_cls=AzCliHelp)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 299, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 236, in get_active_cloud_name
    _set_active_cloud(cli_ctx, AZURE_PUBLIC_CLOUD.name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/cloud.py", line 229, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 91, in set_value
    self.set(config)
  File "/home/raja/lib/azure-cli/local/lib/python2.7/site-packages/knack/config.py", line 78, in set
    with open(self.config_path, 'w') as configfile:
IOError: [Errno 13] Permission denied: '/home/raja/.azure/config'
raja@raja-VirtualBox:~/.azure$ bash -r
raja@raja-VirtualBox:~/.azure$ sudo az login --debug
sudo: az: command not found

**Comment by yugangw-msft** [comment]
I suggest you fix the error of `IOError: [Errno 13] Permission denied: '/home/raja/.azure/config'`. Can you  manually create the folder `~/.azure` and `~/.azure/config`? The error means you have pretty generic file permission issues here.

**Comment by RajSelv** [comment]
The az login error is fixed after granting permission to folder ~/.azure/config.
The login issue can be closed now, good to have this documented may be troubleshoot section, may be some commands via Terminal can help.

Now have progressed till pushing the docker image but getting below error.
Good if you can suggest here--
raja@raja-VirtualBox:~$ docker push apicexecutables.azurecr.io/ibmcom/datapower:v1
The push refers to a repository [apicexecutables.azurecr.io/ibmcom/datapower]
5976c339a0d8: Preparing 
dca99b5572ad: Preparing 
unauthorized: authentication required

**Comment by yugangw-msft** [comment]
This usually means the problem with authenticating or proxying to Docker Hub. Please go to `https://forums.docker.com/` and post questions over there
