### ISSUE TITLE
az aks get-credentials --resource-group <resource> --name <name> - argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by maxmus** [Azure/azure-cli#6957]
Hi all,

I have a issue with getting credentials on Win10. Here is a error stack:

argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\adal_authentication.py", line 25, in signed_session
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\_profile.py", line 494, in _retrieve_token
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\_profile.py", line 857, in retrieve_token_for_user
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\token_request.py", line 352, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\cache_driver.py", line 196, in find
    entry, is_resource_tenant_specific = self._load_single_entry_from_cache(query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\cache_driver.py", line 124, in _load_single_entry_from_cache
    raise AdalError('More than one token matches the criteria. The result is ambiguous.')
adal.adal_error.AdalError: More than one token matches the criteria. The result is ambiguous.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 324, in send
    self.creds.signed_session(http_driver.session)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\adal_authentication.py", line 36, in signed_session
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\adal_authentication.py", line 25, in signed_session
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\_profile.py", line 494, in _retrieve_token
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\_profile.py", line 857, in retrieve_token_for_user
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\token_request.py", line 352, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\cache_driver.py", line 196, in find
    entry, is_resource_tenant_specific = self._load_single_entry_from_cache(query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\adal\cache_driver.py", line 124, in _load_single_entry_from_cache
    raise AdalError('More than one token matches the criteria. The result is ambiguous.')
adal.adal_error.AdalError: More than one token matches the criteria. The result is ambiguous.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 1501, in aks_get_credentials
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-mgmt-containerservice\azure\mgmt\containerservice\operations\managed_clusters_operations.py",
 line 299, in get_access_profile
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 326, in send
    http_driver.session = self.creds.signed_session()
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\adal_authentication.py", line 36, in signed_session
TypeError: argument of type 'NoneType' is not iterable

My version is:
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<userId>\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by palma21** [comment]
Looks due to the python version the CLI expects and the one installed.
This should not happen on 2.0.77. Let us know if it's not the case.
