### ISSUE TITLE
az acr list is empty

### ISSUE THREAD

**Issue by TamasSzerb** [Azure/azure-cli#6977]
$ az acr repository list --name "xxx" --output table
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acr/repository.py", line 255, in acr_repository_list
    top=top)
  File "/home/toma/lib/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/acr/repository.py", line 212, in _obtain_data_from_registry
    result_list += result
TypeError: 'NoneType' object is not iterable

$ az --version
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location '/home/toma/lib/azure-cli/bin/python'
Extensions directory '/home/toma/.azure/cliextensions'

Python (Linux) 3.6.3 (default, Dec  4 2017, 10:49:19)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by samkreter** [comment]
This looks like an ACR issue. @djyou might be able to help.

**Comment by tjprescott** [comment]
Ugh, sorry @samkreter  I just got back from vacation.
