### ISSUE TITLE
az ad sp create-for-rbac: --years not working

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#700]
looks like a parsing issue.

```
az ad sp create-for-rbac --years 2
ERROR: Non-integer years and months are ambiguous and not currently supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 55, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/application.py", line 117, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/commands/__init__.py", line 216, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/role/custom.py", line 464, in create_service_principal_for_rbac
    end_date = start_date + relativedelta(years=years)
  File "/usr/local/lib/python3.5/site-packages/dateutil/relativedelta.py", line 127, in __init__
    raise ValueError("Non-integer years and months are "
ValueError: Non-integer years and months are ambiguous and not currently supported.
```

**Comment by mariojacobo** [comment]
Seeing this issue again 

az ad sp create-for-rbac -n test-group --years 99 

The command failed with an unexpected error. Here is the traceback:

Non-integer years and months are ambiguous and not currently supported.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 400, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1211, in create_service_principal_for_rbac
    app_end_date = app_start_date + relativedelta(years=years or 1)
  File "/opt/az/lib/python3.6/site-packages/dateutil/relativedelta.py", line 173, in __init__
    raise ValueError("Non-integer years and months are "
ValueError: Non-integer years and months are ambiguous and not currently supported.

**Comment by mjisaak** [comment]
Same issue within the Azure Cloud Shell!

**Comment by Eragra3** [comment]
I think I see similar issue with Blob Storage, showing me tracebacks on `az storage blob download`

```
The command failed with an unexpected error. Here is the traceback:

The specified blob does not exist. ErrorCode: BlobNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:6f266c99-701e-0014-4547-1d5e4b000000
Time:2020-04-28T10:29:09.2191258Z</Message></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 578, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 627, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\storage\__init__.py", line 240, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\storage\__init__.py", line 183, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 606, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\baseblobservice.py", line 1984, in 
get_blob_to_path
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\baseblobservice.py", line 2156, in 
get_blob_to_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\baseblobservice.py", line 2124, in 
get_blob_to_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\blob\baseblobservice.py", line 1862, in 
_get_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 430, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 358, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\storageclient.py", line 344, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-multiapi-storage\azure\multiapi\storage\v2018_11_09\common\_error.py", line 115, in _http_error_handler
azure.common.AzureMissingResourceHttpError: The specified blob does not exist. ErrorCode: BlobNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:6f266c99-701e-0014-4547-1d5e4b000000
Time:2020-04-28T10:29:09.2191258Z</Message></Error>
```

Blob missing is actually _sort of expected_ behavior in our case, I think it should be handled with regular error and nice message.

**Comment by jiasli** [comment]
@Eragra3, this doesn't seem to be related to `az sd`. Please submit a new issue and share the necessary information.
