### ISSUE TITLE
`az webapp deployment source config-zip` gives error stack trace after success

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-cli#7008]
**Describe the bug**
`az webapp deployment source config-zip` deploys successfully but gives a Python error stack trace as output.

**To Reproduce**
Use the above command to deploy a zip file to an App Service site. Example with output:

```
nick@Azure:~/KeyVaultDemoApp$ az webapp deployment source config-zip --src site.zip --name nw-keyvault --resource-group keyvault-exercise-group

Object of type 'frozenset' is not JSON serializable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 201, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 134, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 40, in format_json
    separators=(',', ': ')) + '\n'
  File "/opt/az/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/az/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/az/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 32, in default
    return json.JSONEncoder.default(self, o)
  File "/opt/az/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'frozenset' is not JSON serializable
```

**Expected behavior**
Should get logs indicating a successful deployment.

**Environment summary**
Running in bash Cloud Shell. `az --version` output:

```
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location '/opt/az/bin/python3'
Extensions directory '/home/nick/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 26 2018, 17:46:59)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yugangw-msft** [comment]
PR #6951 should address this problem. Since you are at it, can you run with --debug and share with me the response payload which broke the command? I will then double check

**Comment by nickwalkmsft** [comment]
Hm, no longer able to reproduce. If I manage to get it I'll paste it here.

**Comment by panchagnula** [comment]
hey @nickwalkmsft :) yes please do let us know if you still see this. The zip deploy command doesn't set the app setting to build by default - recommended is to set the app setting if needed.

**Comment by nickwalkmsft** [comment]
Yes - I only mentioned that detail in case someone knew of some specific issue. As @yugangw-msft called out, it's probably some service call somewhere in the overall process that unexpectedly gets back a response that's not JSON.

**Comment by panchagnula** [comment]
@nickwalkmsft i am closing this if you are still seeing with the latest version please do re-activate
