### ISSUE TITLE
`az acr build` UnicodeEncodeError from log output causes CLI error

### ISSUE THREAD

**Issue by bacongobbler** [Azure/azure-cli#7011]
During a build with `az acr build`, I received the following error while the build was occurring:

```
Step 6/11 : RUN $(npm bin)/ng build --prod --build-optimizer
 ---> Running in 906cfc7aa4ca
 10% building modules 3/3 modules 0 active'charmap' codec can't encode character u'\u2026' in position 85: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 343, in execute
    result = cmd(params)
  File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Python27\lib\site-packages\azure\cli\core\__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acr\build.py", line 334, in acr_build
    return acr_build_show_logs(client, build_id, registry_name, resource_group_name, True)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acr\build.py", line 73, in acr_build_show_logs
    raise_error_on_failure=raise_error_on_failure)
  File "C:\Python27\lib\site-packages\azure\cli\command_modules\acr\build.py", line 134, in _stream_logs
    print(flush.decode('utf-8', errors='ignore'))
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position 85: character maps to <undefined>
```

The unicode character in particular from the log output is an ellipsis:

```
 10% building modules 11 active …-app/
```

The CLI errors out, but the build continues and eventually succeeds, as shown here:

```
><> az acr build -r brigcharts -t test:latest .
><> az acr repository list -n brigcharts
[
  "test"
]
```

The expected outcome here is for the CLI to be able to handle log output similar to `docker build`, as the same context returns no error with `docker build`:

```
><> docker build .
Sending build context to Docker daemon  20.05MB
...
Successfully built f1bc92eb08cd
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

**Comment by ehotinger** [comment]
@bacongobbler is this a dup of https://github.com/Azure/azure-cli/issues/6408 - ping me on slack

**Comment by tjprescott** [comment]
Closing dupe.
