### ISSUE TITLE
azureProfile.json got corrupt and shown empty

### ISSUE THREAD

**Issue by harryzsh** [Azure/azure-cli#7051]
**Describe the bug**
azureProfile.json recently in the test environment got corrupted and contains nothing inside. This will lead none of the az command work and the following exception will be thrown

```
Traceback (most recent call last):
  File 'runpy.py', line 193, in _run_module_as_main
  File 'runpy.py', line 85, in _run_code
  File 'C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-8jgnm5o1\\azure-cli\\azure\\cli\\__main__.py', line 32, in <module>
  File 'C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-8jgnm5o1\\azure-cli-core\\azure\\cli\\core\\__init__.py', line 509, in get_default_cli
  File 'C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-8jgnm5o1\\azure-cli-core\\azure\\cli\\core\\__init__.py', line 52, in __init__
  File 'C:\\Users\\trdai\\AppData\\Local\\Temp\\pip-install-8jgnm5o1\\azure-cli-core\\azure\\cli\\core\\_session.py', line 40, in load
  File 'json\\__init__.py', line 299, in load
  File 'json\\__init__.py', line 354, in loads
  File 'json\\decoder.py', line 339, in decode
  File 'json\\decoder.py', line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
The way to fix it is to delete the .azure folder in the user folder so the .azure folder will be re-created during az command execution but it would be better if RCA of why the azureProfile.json is corrupted can be found

**Comment by jpoon** [comment]
Interesting, I see the exact same error:

```
Interesting. I see the exact same error:

```
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli\azure\cli\__main__.py", line 32, in <module>
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 509, in get_default_cli
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 52, in __init__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\_session.py", line 40, in load
  File "json\__init__.py", line 299, in load
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

As in, why is it showing that same path when we are on two different machines.... `C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1`.

**Comment by troydai** [comment]
@jpoon this issue will be fixed in the incoming release. And the stack path is a static snapshot of the paths of the environment where we built the CLI package. It is irrelevant to your local environment. It is unfortunately misleading but harmless.
