### ISSUE TITLE
az role assignment list: bad error if the --assignee has invalid input

### ISSUE THREAD

**Issue by mmacy** [Azure/azure-cli#7058]
**Describe the bug**

Issuing `az role assignment list --assignee` on a resource yields the following error:

```
Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.
```

**To Reproduce**

1. Obtain the full resource ID of a resource in your subscription
1. Execute `az role assignment list --assignee YOUR_RESOURCE_ID` to pull the assigned roles for the resource

Example:

```console
$ az role assignment list --assignee $ACR_REGISTRY_ID
Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 231, in list_role_assignments
    include_inherited, include_groups)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 485, in _search_role_assignments
    assignee_object_id = _resolve_object_id(cli_ctx, assignee, fallback_to_object_id=True)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1312, in _resolve_object_id
    filter="servicePrincipalNames/any(c:c eq '{}')".format(assignee)))
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 131, in __next__
    self.advance_page()
  File "/opt/az/lib/python3.6/site-packages/msrest/paging.py", line 117, in advance_page
    self._response = self._get_next(self.next_link)
  File "/opt/az/lib/python3.6/site-packages/azure/graphrbac/operations/service_principals_operations.py", line 159, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Unsupported or invalid query filter clause specified for property 'servicePrincipalNames' of resource 'ServicePrincipal'.
```

**Expected behavior**

The roles assigned to the resource should be returned.

**Environment summary**

* Install Method: **apt**
* CLI version: **2.0.44**
* OS version: **Ubuntu 18.04**
* Shell Type: **bash**

**Additional context**

The `--all` argument works as expected:

```console
$ az role assignment list --all
[
  {
    "canDelegate": null,
    "id": "/subscriptions/875cbdd8
...
```

**Comment by yugangw-msft** [comment]
`--assignee` is supposed to be an identity say a user, service principal, etc. Resource id will not be valid.
I will submit a PR to make the error better w/o stack traces, but you still need to put in the right value

**Comment by mmacy** [comment]
@yugangw-msft Ah, of course. You know, think I actually knew that at one point, and had since forgotten. Thanks!

**Comment by yugangw-msft** [comment]
The uncaught exception has been fixed.
