### ISSUE TITLE
"az acs kubernetes get-credentials" raises "PasswordRequiredException" after "aks get-credentials"

### ISSUE THREAD

**Issue by apjanke** [Azure/azure-cli#7071]
**Describe the bug**

I'm working through the examples in the O'Reilly book "Kubernetes: Up and Running".

I created a cluster using `az aks create`, and got its credentials using `az aks get-credentials`. Then I created a different cluster using `az acs create`, and did an `az acs kubernetes get-credentials` to switch to that cluster. It threw an exception and displayed a stack trace, complaining about an encrypted private key.

```
[~] $ az acs kubernetes get-credentials --resource-group=kuar --name=kuar-cluster
Private key file is encrypted
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 955, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 976, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 72, in secure_copy
    ssh.connect(host, username=user, pkey=pkey, sock=proxy)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/client.py", line 686, in _auth
    filename, pkey_class, passphrase,
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/client.py", line 551, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/rsakey.py", line 48, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/rsakey.py", line 169, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/pkey.py", line 279, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/paramiko/pkey.py", line 328, in _read_private_key
    raise PasswordRequiredException('Private key file is encrypted')
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

**To Reproduce**

The commands from my shell history:

```
az group create --name=kuar-aks --location=eastus
az aks create --resource-group=kuar-aks --name=kuar-cluster-2
az aks get-credentials --resource-group=kuar-aks --name=kuar-cluster-2 
[...]
az group create --name=kuar --location=eastus
az acs create --orchestrator-type=kubernetes --resource-group=kuar --name=kuar-cluster --agent-count=1
az acs kubernetes get-credentials --resource-group=kuar --name=kuar-cluster
```

**Expected behavior**

I would expect the updating of the credentials to work, even when switching between `az aks get-credentials` and `az acs kubernetes get-credentials`. Or if there is an error, a friendly-formatted error message, instead of a Python stacktrace. Possibly including the path or name of the private key it's trying to read; I can't tell what it's trying to do here.

**Environment summary**

* macOS 10.13.6
* azure-cli installed via Homebrew
* shell is a mix of zsh and bash

```
$ az --version
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
iotcentral (0.1.0)
keyvault (2.2.2)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
telemetry (1.0.0)
vm (2.2.1)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/janke/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]

```

**Additional context**

Moving my ~/.kube directory out of the way and re-getting the credentials made the error go away.

Calling `az acs ... get-credentials` and then `az aks get-credentials` seems to work:

```
[~] $ az acs kubernetes get-credentials --resource-group=kuar --name=kuar-cluster
[~] $ az acs kubernetes get-credentials --resource-group=kuar --name=kuar-cluster
Merged "kuar-clust-kuar-ef4a67mgmt" as current context in /Users/janke/.kube/config
[~] $ az aks get-credentials --resource-group=kuar-aks --name=kuar-cluster-2
Merged "kuar-cluster-2" as current context in /Users/janke/.kube/config
[~] $ az acs kubernetes get-credentials --resource-group=kuar --name=kuar-cluster
Merged "kuar-clust-kuar-ef4a67mgmt" as current context in /Users/janke/.kube/config
```

**Comment by apjanke** [comment]
This might be a variant of https://github.com/Azure/azure-cli/issues/5080; I'm not sure, since the stack traces are different.

**Comment by yugangw-msft** [comment]
closing as `az  acs` is deprecating
