### ISSUE TITLE
az bot show - No module named '_cffi_backend'

### ISSUE THREAD

**Issue by poul-kg** [Azure/azure-cli#7092]
**Describe the bug**
* I have an error while running `az bot show` command on MacOS

```Bash
az bot show
No module named '_cffi_backend'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
    op = import_module(mod_to_import)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/pavel/.azure/cliextensions/botservice/azext_bot/custom.py", line 14, in <module>
    from azure.cli.command_modules.appservice.custom import (enable_zip_deploy, config_source_control, get_app_settings,
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 19, in <module>
    import OpenSSL.crypto
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

**To Reproduce**
* `brew update && brew install azure-cli`
* `az login`
* `az extension add -n botservice` - it gives me `The installed extension 'botservice' is in preview.`
* `az bot show`

**Expected behavior**
* there should be no error, and I should see my bots, or what should be there?

**Environment summary**

* `MacOS High Sierra 10.13.6 (17G65)`
* `NodeJS v8.11.2`
* `Homebrew 1.7.1 Homebrew/homebrew-core (git revision 0792f; last commit 2018-08-18)`
* Shell Type: standard Mac's Terminal

```
az --version
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
iotcentral (0.1.0)
keyvault (2.2.2)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
telemetry (1.0.0)
vm (2.2.1)

Extensions:
botservice (0.0.3)

Python location '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3'
Extensions directory '/Users/pavel/.azure/cliextensions'

Python (Darwin) 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
* Tried az command previously 2-3 times, it never works on mac :(

**Comment by tjprescott** [comment]
`Tried az command previously 2-3 times, it never works on mac :(`

Do you mean no commands work on your Mac, or just the bot service commands?

**Comment by tjprescott** [comment]
@poul-kg in the next release, bot service will switch from being an extension to being in the CLI proper. Please give that new module a try and let us know if you get the same issue.

**Comment by stevengum** [comment]
@poul-kg, Are you still running into this issue with the latest release? Additionally two arguments are required for the command to work, `--name` and `--resource-group` (or `-n` and `-g`, respectively).

```bash
Command
    az bot show : Get an existing bot.

--name -n           [Required] : The resource name of the bot.
--resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
```

**Comment by tjprescott** [comment]
I believe this should be working now. If not, please re-open.
