### ISSUE TITLE
`az batchai cluster create` with --user-auto-storage option does not create cluster

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-cli#7129]
Unable to create Batch AI cluster using the following command (worked in some some previous versions):
`az batchai cluster create  --name mycluster2     --workspace myworkspace    --resource-group myrg2  --vm-size Standard_NC6  --use-auto-storage    --target 1 --user-name myusername --generate-ssh-keys`

Returns following error output:
```
Reusing existing ssh public key from ~/.ssh
Creating batchaiautostorage resource group for auto-storage account
__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-batchai\azure\cli\command_modules\batchai\custom.py", line 685, in create_cluster
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-batchai\azure\cli\command_modules\batchai\custom.py", line 546, in _configure_auto_storage
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-batchai\azure\cli\command_modules\batchai\custom.py", line 578, in _create_auto_storage_account
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Expected behavior**
Command should return with properties of Batch AI cluster that is being provisioned. In background, cluster is provisioned with an automatically generated blob storage account that is linked to the cluster. Auto-storage account should be generated automatically in a new or existing resource group called `batchaiautostorage`

If I remove the `--use-auto-storage` parameter from the `az batchai cluster create` command, the command returns normally and cluster is provisioned - and without the auto-storage account, as expected for this case.

**Environment summary**
* CLI v 2.0.44. Tried both local Windows installation (via MSI) and through Azure CloudShell. Version of batchai module is 0.4.1.

**Additional context**
* Tried creating resource group for Batch AI workspace/cluster in several different regions: East US, East US2, West US2. No difference in result - issue observed in all Batch AI regions.

**Comment by dlepow** [comment]
Closing
