### ISSUE TITLE
Brew installation issue with az policy event list command

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#7139]
Homebrew, Mac Installation, 2.0.44

```
$ az policy event list
No module named 'azure.mgmt.policyinsights'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 427, in default_command_handler
    client = client_factory(self.cli_ctx, command_args) if client_factory else None
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/policyinsights/_client_factory.py", line 15, in policy_events_operations
    return _cf_policy_insights(cli_ctx).policy_events
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/policyinsights/_client_factory.py", line 9, in _cf_policy_insights
    from azure.mgmt.policyinsights import PolicyInsightsClient
ModuleNotFoundError: No module named 'azure.mgmt.policyinsights'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/policyinsights/_exception_handler.py", line 10, in policy_insights_exception_handler                                                                                                                                                                            
    from azure.mgmt.policyinsights.models import QueryFailureException
ModuleNotFoundError: No module named 'azure.mgmt.policyinsights'
```

**Comment by tjprescott** [comment]
Fixed.
