### ISSUE TITLE
Redis cache export problems

### ISSUE THREAD

**Issue by nuclear0wl** [Azure/azure-cli#7161]
**Describe the bug**
When I try to execute Azure CLI command `az redis export` I got that error: 
```
ERROR: 'RedisOperations' object has no attribute 'export'
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke cmd_result = self.invocation.execute(args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute six.reraise(*sys.exc_info())
File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise raise value
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute result = cmd(params)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__ return self.handler(*args, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler result = op(**command_args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/redis/custom.py", line 33, in cli_redis_export return client.export(resource_group_name, name, parameters)
AttributeError: 'RedisOperations' object has no attribute 'export'
```

I thought that source of an error might be here:
[Redis Operations](https://github.com/Azure/azure-sdk-for-python/blob/66b4ec24f07c78fe3de0bd5d995557c43f46ec96/azure-mgmt-redis/azure/mgmt/redis/operations/redis_operations.py#L880)
But reviewer redirected me to write here. [See that issue for more information](https://github.com/Azure/azure-sdk-for-python/issues/3198#issuecomment-416653378)

**To Reproduce**
Execute simple `az redis export` command.

**Expected behavior**
Redis Cache backup will be stored in my Blob Container. 

**Environment summary**
Installed using `apt-get` as described [here](https://docs.microsoft.com/ru-ru/cli/azure/install-azure-cli-apt?view=azure-cli-latest).
Cli version: azure-cli (2.0.44)
OS version: Ubuntu 16.04.5 LTS
Sell type: bash

**Comment by adewaleo** [comment]
should be fixed when #5523 is merged.

**Comment by tjprescott** [comment]
@adewaleo that PR was closed due to inactivity.

**Comment by adewaleo** [comment]
> @adewaleo that PR was closed due to inactivity.

@tjprescott I reached out to the Redis team about the PR / this issue, so they can fix the broken commands and add some unittest. However, if they aren't able to make the changes soon, we might need to do something about this issue.
