### ISSUE TITLE
Bad request - Error from Response not displayed when cmdlet fails

### ISSUE THREAD

**Issue by v-Ajnava** [Azure/azure-cli#7202]
**Describe the bug**
Bad request - Error from Response not displayed when cmdlet fails

**To Reproduce**
applies to all cmdlet from Service Bus and Eventhub (not tested other service cmdlets)
az eventhubs namespace create create -g {resourcegroup} -n 11121212121 (name should not start with numbers)

O/P
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "d:\azcli\azure-cli\env\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\azcli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "d:\azcli\azure-cli\env\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "d:\azcli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
    result = cmd(params)
  File "d:\azcli\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "d:\azcli\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "d:\azcli\azure-cli\src\command_modules\azure-cli-eventhubs\azure\cli\command_modules\eventhubs\custom.py", line 22, in cli_namespace_create
    maximum_throughput_units=maximum_throughput_units))
  File "d:\azcli\azure-cli\env\lib\site-packages\azure\mgmt\eventhub\operations\namespaces_operations.py", line 319, in create_or_update
    **operation_config
  File "d:\azcli\azure-cli\env\lib\site-packages\azure\mgmt\eventhub\operations\namespaces_operations.py", line 272, in _create_or_update_initial
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.eventhub.models.error_response_py3.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Expected behavior**
az eventhubs namespace create -g {resourcegroup} -n 11121212121 
Expected is the only the error message from response. which was there previous to couple of releases.
Expected : 
The specified service namespace is invalid. CorrelationId: f12c89e7-5087-4e34-a414-601f1b445519. [Code: "BadRequest"]

**Environment summary**
 MSI/ CLI version azure-cli (2.0.46) / Windows 10 Enterprise - version 1803 / cmd.exe

**Comment by adewaleo** [comment]
#7305 closes this issue.
