### ISSUE TITLE
az 

### ISSUE THREAD

**Issue by brbarnett** [Azure/azure-cli#7207]
**Describe the bug**
I have a Premium Verizon CDN profile (echosolutionsgroup-com) where I'm attempting to create an endpoint. I am receiving a Bad Request from the API.

**To Reproduce**
az version = azure-cli (2.0.45)

I have a Premium Verizon CDN profile (echosolutionsgroup-com) where I'm attempting to create an endpoint. I am receiving a Bad Request from the API. My command is:
`az cdn endpoint create -g echosolutionsgroup.com -n esgwebstg --profile-name echosolutionsgroup-com
--origin esgwebstg.z14.web.core.windows.net`

Error log:
Operation returned an invalid status code 'Bad Request'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-cdn\azure\cli\command_modules\cdn\custom.py", line 96, in create_endpoint
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-cdn\azure\mgmt\cdn\operations\endpoints_operations.py", line 271, in create
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-cdn\azure\mgmt\cdn\operations\endpoints_operations.py", line 217, in _create_initial
azure.mgmt.cdn.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Bad Request'

**Expected behavior**
Expecting command to succeed

**Environment summary**
az version = azure-cli (2.0.45)

**Additional context**
N/A

**Comment by brbarnett** [comment]
OK I got it -- not an issue with the CLI directly, although a more useful error message would be nice. Here's the message I found in the Azure portal activity log: `We couldn’t configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. You’ll need to manage these endpoints in the supplemental portal.`

Passing `--query-string-caching NotSet` along with the rest of the command solved the issue. I do not believe I should have to do that. Maybe change the default?

**Comment by adewaleo** [comment]
I think #7305 might address this and other issues @tjprescott.

**Comment by tjprescott** [comment]
@adewaleo #7305 addresses the error message but not the question of the default for `--query-string-caching`

**Comment by adewaleo** [comment]
You are right @tjprescott. Are you going to look into this, or should I look into it?

**Comment by adewaleo** [comment]
So it seems this issue is occurring at the service level. If you create a premium verizon profile and then try to create an endpoint, you receive the following error:

```
BadRequest - We couldn’t configure QueryStringCachingBehavior, IsCompressionEnabled, ContentTypesToCompress, GeoFilters and DeliveryPolicy for premium profile endpoints. You’ll need to manage these endpoints in the supplemental portal.
```
It seems like premium profile endpoints (Verizon_Premium) are meant to be managed from the portal.

Which is why setting `--query-string-caching` to NotSet works. Other options fail with the same error message.

@tjprescott, what do you recommend we do to address this? 
Here are some thoughts...

1. Warn users to set `--query-string-caching` to `NotSet` in help text when creating a premium endpoint.
2. Retrieve the premium profile using the profile name and update `--query-string-caching` to `NotSet`

**Comment by adewaleo** [comment]
@tjprescott. I agree that changing the default value for IgnoreQueryString would be a breaking change and that making an extra api call is inefficient.

I just tested the Standard_Akamai, Standard_Verizon profiles and Premium_Verizon. By default, Premium Verizon sets the query string caching behavior to "NotSet". While the rest of the profiles set the behavior to "IgnoreQueryString". I was not able to test the Custom_Version and Standard_ChinaCdn profile skus.

Is it okay to go ahead and make the change?

**Comment by tjprescott** [comment]
I think so, yes.
