### ISSUE TITLE
az bot create "RequestBodyNotSupported" error

### ISSUE THREAD

**Issue by pdyck** [Azure/azure-cli#7235]
**Describe the bug**
When I want to create a bot, the CLI checks if a bot with this name already exists and then fails because there is a request body for a 'GET' request

**To Reproduce**
`az bot create -k registration -n my-bot -g MY_RESOURCE_GROUP`

**Expected behavior**
```
(RequestBodyNotSupported) The HTTP Verb 'GET' should not have a request body.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-botservice\azure\cli\command_modules\botservice\custom.py", line 84, in create
  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-botservice\azure\mgmt\botservice\operations\bots_operations.py", line 491, in get_check_name_availability
azure.mgmt.botservice.models.error.ErrorException: (RequestBodyNotSupported) The HTTP Verb 'GET' should not have a request body.
```

**Environment summary**
* MSI installer
* azure-cli (2.0.45)
* Python (Windows) 3.6.5
* cmder

**Additional context**
I don't know why there is the user 'troyd' in the stacktrace. There is no such user on my computer.

**Comment by swagatmishra2007** [comment]
@pdyck This is fixed in the upcoming release of the cli. For now, as a work around, use the botservice extension as follows - 
remove the extension (if already installed)
`az extension remove -n botservice`
install -
`az extension add -n botservice`

**Comment by pdyck** [comment]
Thanks!
