### ISSUE TITLE
append blob upload ignores --if-none-match

### ISSUE THREAD

**Issue by evictor** [Azure/azure-cli#7250]
**Describe the bug**
Using Azure CLI to upload a blob with `--if-none-match="*"` results in an error when the blob exists instead of the expected behavior which is an informative no-op success.

My command has not changed, but underlying Azure CLI version has. It is difficult for me to determine what the previous working version was because this is via a package manager buried in a Docker image. However, I can find the current buggy version.

**To Reproduce**
1. Upload a blob, e.g. `az storage blob upload -c my-container -f src/bar.txt -n dest/bar.txt`
2. Try to upload blob again or ignore if exists: `az storage blob upload -c my-container -f src/bar.txt -n dest/bar.txt --if-none-match="*"`

**Expected behavior**
Program exit code should be 0 (success). Even though the blob exists, the command was instructed to only attempt upload if no such blob exists.

**Environment summary**
```
# az --version
azure-cli (2.0.42)

acr (2.1.0)
acs (2.2.0)
advisor (0.6.0)
ams (0.2.0)
appservice (0.2.0)
backup (1.2.0)
batch (3.3.0)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.0)
core (2.0.42)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.0)
extension (0.2.0)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.26)
iot (0.2.0)
keyvault (2.2.0)
lab (0.1.0)
maps (0.3.0)
monitor (0.2.0)
network (2.2.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.0)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.0)
resource (2.1.0)
role (2.1.0)
servicebus (0.2.0)
servicefabric (0.1.0)
sql (2.1.0)
storage (2.1.0)
vm (2.1.0)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jul 13 2018, 23:13:29) 
[GCC 4.9.2]

Legal docs and information: aka.ms/AzureCliLegal
```

```
# uname -a
Linux 35f00f683648 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux
```

**Additional context**
Built within a Docker image `FROM node:8.11.1-slim`.

**Comment by evictor** [comment]
Upgraded to latest 2.0.45 CLI and bug still there. I am exploring now for older working version.

**Comment by evictor** [comment]
Downgraded to 2.0.26-1~jessie and bug still there. Is the underlying Python code tracked separately? The exception is from there so perhaps this is unaddressable by adjusting the azure-cli version. Here is the exception:

```
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 318, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 291, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 348, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 241, in upload_blob
    return type_func[blob_type]()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 234, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/blob/blockblobservice.py", line 413, in create_blob_from_path
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/blob/blockblobservice.py", line 532, in create_blob_from_stream
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/blob/blockblobservice.py", line 921, in _put_blob
    return self._perform_request(request, _parse_base_properties)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 362, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 297, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/storageclient.py", line 283, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2017_04_17/common/_error.py", line 118, in _http_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureConflictHttpError: The specified blob already exists.
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:214134d2-101e-00f8-1de5-466867000000
Time:2018-09-07T20:01:23.9528809Z</Message></Error>
```

**Comment by williexu** [comment]
@evictor why do you expect the command to pass? Here's the information from the help(az storage blob upload -h):
`
--if-none-match                : An ETag value, or the wildcard character (*). Specify this
                                     header to perform the operation only if the resource's ETag
                                     does not match the value specified. Specify the wildcard
                                     character (*) to perform the operation only if the resource
                                     does not exist, and fail the operation if it does exist.
`

**Comment by evictor** [comment]
I don't know. I think at some point that was the behavior, maybe unintentional, or maybe something in my CI changed to propagate the request failure up.

I guess I expected a no-op success rather than an out-and-out failure. Also it reminded me of a recent issue in Azure Python lib where checking blob exists() on a non-existent blob would cause a failure.

It would be nice to have an "upload ignore" option similar to SQL INSERT IGNORE, which is what I wanted—would azure-cli team be open to adding something like that? Basically it's "if none match * then do the upload, else do nothing."
