### ISSUE TITLE
`az login --service-principal` results in UnboundLocalError

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/azure-cli#7258]
**Describe the bug**
Running `az login --service-principal` with no other arguments results in a runtime error.

**To Reproduce**
1. run `az login --service-principal`
2. login in the browser window opened by CLI

Results in

```sh
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
local variable 'sp_auth' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/command_modules/profile/custom.py", line 128, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/usr/local/Cellar/azure-cli/2.0.45/libexec/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 209, in find_subscriptions_on_login
    self._creds_cache.save_service_principal_cred(sp_auth.get_entry_to_persist(username,
UnboundLocalError: local variable 'sp_auth' referenced before assignment
```
**Expected behavior**
Should have either succeeded or provided a friendly message about the missing parameters

**Environment summary**
Install Method: homebrew
CLI version: 2.0.45
OS version: macOS 10.13.6
Shell Type: bash

**Comment by yugangw-msft** [comment]
Fixed, you should see a better error now:
```bash
(env) D:\sdk\azure-cli>az login --service-principal
usage error: --service-principal --username NAME --password SECRET --tenant TENANT
```
