### ISSUE TITLE
az webapp deployment source config-zip fails from jenkins pipeline

### ISSUE THREAD

**Issue by swm7** [Azure/azure-cli#7282]
**Describe the bug**
We are using Jenkins integration with Azure. While trying to run az deploy webapp from jenkins pipeline it fails with the following error:

az webapp deployment source config-zip --debug --resource-group st-worker-test --name st-worker-test --slot stagedeploy --src /var/lib/jenkins/workspace/tore-backend-latest_develop@2/artifact/App.Store.Work_develop_549.zip
ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 188, in enable_zip_deploy
    response = response.json()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**To Reproduce**
Set to Azure serviceprincipal credentials 
use Azure cli commands for the below:
login to Azure with service principal
set to the azure subscription
run az webapp deployment source config-zip --debug --resource-group st-worker-test --name st-worker-test --slot stagedeploy --src /var/lib/jenkins/workspace/tore-backend-latest_develop@2/artifact/App.Store.Work_develop_549.zip

The command above fails with the error mentioned.

**Expected behavior**
It should deploy the zip file to Azure webapp sucessfully

**Environment summary**
Install Method  : sudo apt-get / CLI version (azure-cli (2.0.45)) / Ubuntu 16.0.4 / Shell Type  (bash)  

**Additional context**
If i run the same command manually by logging in to the Jenkins slave it works successfully. We need to get this working from Jenkins pipeline and need help in fixing the issue.

**Comment by swm7** [comment]
Also seeing that the deployment hangs sometimes. Attached is the debug log. I really need help on this. Could someone please look into it.
[azure-deploy-log.docx](https://github.com/Azure/azure-cli/files/2376032/azure-deploy-log.docx)

**Comment by tjprescott** [comment]
@panchagnula

**Comment by mattchenderson** [comment]
@panchagnula I think the right fix here is to make the timeout configurable with an optional flag. The current behavior is to be assumed as the default if no timeout is provided.

**Comment by holgerbrandl** [comment]
Same here using on a bash terminal under macos v10.14.1. When deploying the demo project under https://docs.microsoft.com/en-us/learn/modules/store-app-data-with-azure-blob-storage/7-blob-uploads-and-downloads it fails with a highly similar error:

```
az webapp deployment source config-zip --resource-group ${AZ_RES_GROUP} --name ${AZ_WEBAPP_NAME} --src ../site.zip

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 262, in enable_zip_deploy
    response = response.json()
  File "/usr/local/Cellar/azure-cli/2.0.48/libexec/lib/python3.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/brandl/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/brandl/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/brandl/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

My zip file seems legit, and my CLI version is `azure-cli (2.0.48)`

**Comment by panchagnula** [comment]
@holgerbrandl  - what is the python version  that is being used here? is it possible for you to upgrade the python version & try? Do Ptyhon --version, this is the version i have installed "Python 3.7.0". thank you.

**Comment by holgerbrandl** [comment]
Since I had deleted the corresponding resource group already, I've created the complete demo setup again (group, storage account, wegapp) and tried to reproduce the error. However now it seems fine and deployment works as expected. 
I'm not aware of any changes in my local setup. My python version has not changed since I have reported the ticket and is 3.6.3.

Not sure if this is compatible with the stacktrace, but it may have been also  some kind of connection timeout?

**Comment by panchagnula** [comment]
@holgerbrandl , thanks for the update. with the new setup has the version of azure-cli changed, especially since we have a newer version available now & we have had some code changes to the zip deployment command, so there might be some  bugfixes that would have infact fixed the problem you are seeing.

**Comment by panchagnula** [comment]
added a --timeout attribute to the command that can be used to change the default timeout if the package being deployed will take greater than 10mins to deploy
