### ISSUE TITLE
`az interactive` keeps crashing

### ISSUE THREAD

**Issue by mlda065** [Azure/azure-cli#7309]
**Describe the bug**
When trying to use az interactive, it keeps crashing upon trying to look up a list of suggestions.

**To Reproduce**
The first time it happened:

```
$ az interactive
> group --
```
I didn't press enter. When I pressed that second dash, Python threw an exception.

Then I quit and started again

```
$ az interactive
Encountered unrecognizable cache, interactive will create a new updated cache for use.
az>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/interactive/azclishell/_dump_commands.py", line 126, in dump_command_table--------------------------------------------------------------------------------------------
    json.dump(cmd_table_data, help_file)                   *
  File "/opt/az/lib/python3.6/json/__init__.py", line 179, in dump----------------------------------------------------
    for chunk in iterable:
  File "/opt/az/lib/python3.6/json/encoder.py", line 430, in _iterencode----------------------------------------------
    yield from _iterencode_dict(o, _current_indent_level)plication
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks       : Jmespath query of the previous command
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks       : get the exit code of the previous command
  File "/opt/az/lib/python3.6/json/encoder.py", line 376, in _iterencode_dictces
    raise TypeError("key " + repr(key) + " is not a string")
TypeError: key <knack.deprecation.Deprecated object at 0x7f11c19b7d30> is not a string
Loading... 
```

I can't type anything. I can't use ctrl-C to quit. I had to close the entire terminal window and make a new one.

**Expected behavior**

If something prevents the azure cli from fetching/generating a list of suggestions for something, it should use `try`/`except` to fail gracefully. I shouldn't have to close the entire window.

**Environment summary**
I have tried in the Azure Cloud Shell (bash) and also a Linux v16 machine.
The result is the same for both.

On my Linux Machine:

```
~$ az --version
azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

Python location '/opt/az/bin/python3'
Extensions directory '/home/matthew/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Aug 22 2018, 23:14:28)
[GCC 7.2.0]
```

**Comment by mlda065** [comment]
The impact of this bug means that I cannot use `az interactive` to achieve anything.

**Comment by tjprescott** [comment]
@williexu has fixed this for the upcoming release. In the meantime, if you power through the error by pressing Enter, the caching will eventually complete and it should resume working.

**Comment by williexu** [comment]
The bug cannot be powered through.
The fix will be available in our next release (ETA: 9/22). Apologies and thank you for your patience, everyone.
