### ISSUE TITLE
Create action group with email receiver with Azure CLI

### ISSUE THREAD

**Issue by asasine** [Azure/azure-cli#7370]
I am attempting to create an action group with an email receiver using Azure CLI. Is there any documentation on the schema for the `$receiver` variable during `az monitor action-group create --name $name --resource-group $rg --action $receiver`?

I have attempted the following:

```bash
#!/usr/bin/env bash
rg='my-resource-group'
name='my-email-action-group'
receiver='{"emailAddress":"me@company.com","name":"adam-work-email"}'
az monitor action-group create --resource-group $rg --name $name --action $receiver #does not work
receiver='"emailAddress":"me@company.com","name":"adam-work-email"'
az monitor action-group create --resource-group $rg --name $name --action $receiver #also does not work
receiver='{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}'
az monitor action-group create --resource-group $rg --name $name --action $receiver #also does not work
receiver='"emailReceivers":"[{"name":"adam-work-email","emailAddress":"me@company.com"}]'
az monitor action-group create --resource-group $rg --name $name --action $receiver #also does not work
```

All of those commands fail with the following error:

```
usage error: Failed to parse "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}" as object of type "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}". usage error: the type "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}" is not recognizable.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/actions.py", line 287, in __call__
    self.deserialize_object(type_name, type_properties),
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/actions.py", line 328, in deserialize_object
    raise ValueError('usage error: the type "{}" is not recognizable.'.format(type_name))
ValueError: usage error: the type "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}" is not recognizable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 286, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/actions.py", line 297, in __call__
    ' '.join(values), type_name, str(ex)))
ValueError: usage error: Failed to parse "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}" as object of type "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}". usage error: the type "{"emailReceivers":[{"name":"adam-work-email","emailAddress":"me@company.com"}]}" is not recognizable.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03d4ff4-4752-4ed4-2f6c-312ff3fd9fd8
* Version Independent ID: 822e4b3b-4079-9a88-2525-715c8d4ea90a
* Content: [az monitor action-group](https://docs.microsoft.com/en-us/cli/azure/monitor/action-group?view=azure-cli-latest#az-monitor-action-group-update)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by troydai** [comment]
Please try out the format specified in the help:
```
Command
    az monitor action-group create : Create a new action group.

Arguments
    --name -n           [Required] : The name of the action group.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    --short-name                   : The short name of the action group.
    --tags                         : Space-separated tags in 'key[=value]' format. Use '' to clear
                                     existing tags.

Actions Arguments
    --action -a                    : Add receivers to the action group during the creation.
        Usage:   --action TYPE NAME [ARG ...]
        Email:   --action email bob bob@contoso.com
        SMS:     --action sms charli 1 5551234567
        Webhook: --action webhook alert_hook https://www.contoso.com/alert
        Multiple actions can be specified by using more than one `--action` argument.

Global Arguments
    --debug                        : Increase logging verbosity to show all debug logs.
    --help -h                      : Show this help message and exit.
    --output -o                    : Output format.  Allowed values: json, jsonc, table, tsv, yaml.
                                     Default: table.
    --query                        : JMESPath query string. See http://jmespath.org/ for more
                                     information and examples.
    --subscription                 : Name or ID of subscription. You can configure the default
                                     subscription using `az account set -s NAME_OR_ID`.
    --verbose                      : Increase logging verbosity. Use --debug for full debug logs.

```
The command does not accept JSON.
