### ISSUE TITLE
Log Analytics extension: KeyError: 'text'

### ISSUE THREAD

**Issue by mmacy** [Azure/azure-cli#7403]
**Describe the bug**

Attempting to display help (`--help`) for the log-analytics extension (v0.1.2) results in a KeyError:

```console
$ az monitor log-analytics --help
'text'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 286, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1020, in __call__
    parser.print_help()
  File "/opt/az/lib/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 155, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 217, in format_help
    is_group)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 631, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 219, in __init__
    child.load(options)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 178, in load
    self._load_from_file()
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 183, in _load_from_file
    self._load_from_data(file_data)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 123, in _load_from_data
    self.examples.append(HelpExample(d))
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 331, in __init__
    self.text = _data['text']
KeyError: 'text'
```

**To Reproduce**

1. List available extensions, verify Log Analytics is available:

   ```
   $ az extension list-available --output table | grep log-analytics
   log-analytics                   0.1.2      Support for Azure Log Analytics query capabilities.
   ```
1. Install log-analytics extension

   ```
   az extension add -n log-analytics
   ```

1. Display help for `az monitor log-analytics` command and error is thrown:

   ```
   $ az monitor log-analytics --help
   'text'
   Traceback (most recent call last):
     File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
     File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 286, in execute
    parsed_args = self.parser.parse_args(args)
     File "/opt/az/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
   ...
   ``` 

**Expected behavior**

Log Analytics `--help` should display the help for the sub-command group.

**Environment summary**

Install Method: apt get
CLI version: 2.0.46
OS version: Ubuntu 18.04
Shell Type: Bash

**Additional context**

Was trying to list my workspaces and ran across the ref for the sub-command here:

https://docs.microsoft.com/cli/azure/ext/log-analytics/monitor/log-analytics

Installed the extension and hit the error while attempting to discover its syntax.

**Comment by yugangw-msft** [comment]
ported to https://github.com/Azure/azure-cli-extensions/issues/315
