### ISSUE TITLE
Azure storage SAS token not working in powershell

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/azure-cli#7414]
**Describe the bug**
az storage blob download with account name and sas token in failing with unable to parse sas token properly

**To Reproduce**
Download blob from az storage blob download with sas token pasted from portal

**Expected behavior**
It should have worked like it works on linux

**Environment summary**
MSI downloaded from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

**Additional context**
C:\Users\myuser> az storage blob download --container-name lol --name "deployabcd.zip" --file ".\deploy.zip" --account-name testms143 --sas-token 'sp=r&st=2018-09-25T10:37:01Z&se=2018-09-25T18:37:01Z&spr=https&sv=2017-11-09&sig=38O%2<sig>%3D&sr=b' --debug
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:1ad662a8-701e-0084-7ed6-54b4df000000
Time:2018-09-25T13:47:50.9175362Z</Message></Error>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 366, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 234, in new_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 177, in handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1872, in get_blob_to_path
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 2044, in get_blob_to_stream
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 2012, in get_blob_to_stream
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1750, in _get_blob
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureMissingResourceHttpError: The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:1ad662a8-701e-0084-7ed6-54b4df000000
Time:2018-09-25T13:47:50.9175362Z</Message></Error>
'st' is not recognized as an internal or external command,
operable program or batch file.
'se' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\myuser> az --version
azure-cli (2.0.46)

acr (2.1.5)
acs (2.3.4)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.4)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
botservice (0.1.1)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.4)
core (2.0.46)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.2.4)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.30)
iot (0.3.2)
iotcentral (0.1.2)
keyvault (2.2.3)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.5)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.5)
search (0.1.1)
servicebus (0.2.3)
servicefabric (0.1.3)
signalr (1.0.0)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.3)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\myuser\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by Kris824** [comment]
This didn't solve the problem, I;m facing thesame issue
