### ISSUE TITLE
No module named 'azure.mgmt.signalr'

### ISSUE THREAD

**Issue by bryce-klinker** [Azure/azure-cli#7467]
**Describe the bug**
Listing keys for Azure SignalR Service fails with: `No module named 'azure.mgmt.signalr'`

**To Reproduce**
1. Install Azure CLI
1. Login using `az login`
1. Execute `az signalr key list`

**Expected behavior**
Show error saying resource group, name, and SKU are required

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
- Mac OSX High Sierra: 10.13.5
- Install Method: brew install azure-cli
  - Installed: 2.0.46
- Python Version: 3.6.5

**Additional context**
Complete Error from `az signalr key list`:

```
No module named 'azure.mgmt.signalr'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/azure-cli/2.0.46/libexec/lib/python3.7/site-packages/azure/cli/command_modules/signalr/key.py", line 7, in <module>
    from azure.mgmt.signalr.models import KeyType
ModuleNotFoundError: No module named 'azure.mgmt.signalr'
```

**Comment by tjprescott** [comment]
@troydai  this looks a lot like the botservice issue.

**Comment by troydai** [comment]
I take a look.

**Comment by troydai** [comment]
https://github.com/Azure/azure-cli/pull/7475

**Comment by troydai** [comment]
Will be fixed in next release. The fix has been merged.
