### ISSUE TITLE
Linux CLI Fails to Create NodeJS Webapp

### ISSUE THREAD

**Issue by d-y-charpen** [Azure/azure-cli#7473]
Following the guide for deploying a nodejs webapp using CLI (https://docs.microsoft.com/en-ca/azure/app-service/containers/quickstart-nodejs), the following is outputted:
```
az webapp up -n app-name
Resource group 'appsvc_rg_Linux_CentralUS' already exists.
Creating App service plan 'appsvc_asp_Linux_CentralUS' ...
__init__() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/home/daniel/.azure/cliextensions/webapp/azext_webapp/custom.py", line 131, in create_deploy_webapp
    sku=sku_def, reserved=(is_linux or None))
TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
```
This occurred both when attempting to deploy my own app, and deploying the quickstart provided in the guide.

The expected behaviour was successful creation of the service plan, then zipping and deploying the app, as defined in the guide.

I am on Ubuntu 18.04.01, using the most updated version of the az tool.

**Comment by yugangw-msft** [comment]
port to https://github.com/Azure/azure-cli-extensions/issues/328
