### ISSUE TITLE
Azure CLI in Cloud Shell got ’Segmentation fault’ error

### ISSUE THREAD

**Issue by nmikuni** [Azure/azure-cli#7497]
**Describe the bug**
(on Cloud Shell)
$ az backup protection backup-now -g [Resource Group Name] -v [Vault Name] -c [Container Name] -i [Item Name] --retain-until 26-09-2018 

05:30:17   /usr/local/bin/az: line 13:    43 Segmentation fault      (core dumped) python -m azure.cli '$@'

**To Reproduce**
not reproduced

**Expected behavior**
when tried after 9 hours ago, the backup succeeded.

**Environment summary**
Cloud Shell

**Additional context**
Want to know what to do if it happens again. Can I debug and investigate the cause somehow?

**Comment by troydai** [comment]
`Segmentation fault` is memory violation. I can hardly see any CLI logic will cause this. It can be OS environmental issue.

**Comment by yugangw-msft** [comment]
This is not CLI issue, if you can reproduce, please reach to me at yugangw at microsoft dot com and I will connect you to the cloud shell team.

**Comment by supertzark** [comment]
I am trying a get a python script run on azure ml .. as I did I am getting this error 

Imported Needed libraries
Snowflake connection started
Data ingestion started..
Segmentation fault (core dumped)
azureuser@*********:~/*****/*****/Users/*********$

and if I want to run a notebook via  

jupyter nbconvert --execute HRE_Member_Ranking.ipynb it gives me 

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 478, in _poll_for_reply
    msg = self.kc.shell_channel.get_msg(timeout=timeout)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jupyter_client/blocking/channels.py", line 54, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 483, in _poll_for_reply
    self._check_alive()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 510, in _check_alive
    raise DeadKernelError("Kernel died")
nbconvert.preprocessors.execute.DeadKernelError: Kernel died



please help ..

**Comment by jiasli** [comment]
@supertzark, you issue doesn't seem to be related to Azure CLI. 

If you are using Cloud Shell, you may submit an issue at https://github.com/Azure/CloudShell/issues.

If you are using Azure ML, you may submit an issue at https://github.com/Azure/MachineLearningNotebooks/issues
