### ISSUE TITLE
Console azure Fails on " az role assignment list-changelogs"

### ISSUE THREAD

**Issue by ediazrod** [Azure/azure-cli#7507]
**Describe the bug**
use the console Azure to issue  az role assignment list-changelogs

**To Reproduce**
On console
 az role assignment list-changelogs

**Expected behavior**
The change logs.

**Environment summary**
AZ console Azure

**Additional context**
the error:

```
eduardo@Azure:~/clouddrive$ az role assignment list-changelogs
'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 354, in list_role_assignment_change_logs
    payload = payload['properties']
KeyError: 'properties'
```

**Comment by yugangw-msft** [comment]
A few related issues have been fixed through the refactoring made for the multi-api support. I am no longer able to reproduce this issue, but if you do, please use `--debug` and send the trace to me at yugangw at microsoft dot com
I am closing this issue, while I have to apologize for not getting to this issue in time.

**Comment by jeff-shepherd** [comment]
I had the same issue today.  I installed the latest Azure CLI but the issue was still there.  After installing the latest, the only difference was that it printed the message "To open an issue, please run: 'az feedback'"

I ran az feedback and it generated:
### **This is an autogenerated template. Please review and update as needed.**

## Describe the bug

**Command Name**
`az role assignment list-changelogs`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

'properties'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-role\azure\cli\command_modules\role\custom.py", line 300, in list_role_assignment_change_logs
KeyError: 'properties'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az role assignment list-changelogs --start-time {} --end-time {} --output {}`

## Expected Behavior

A clear and concise description of what you expected to happen.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

```
## Additional Context
Add any other context about the problem here.
