### ISSUE TITLE
az network lb frontend-ip update gets 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by suonto** [Azure/azure-cli#7552]
**Describe the bug**
When reproducing, please note that resource groups `yyyy` and `zzzz` represent 2 different resource groups.
```
az network lb frontend-ip update \
  --ids /subscriptions/xxxx/resourceGroups/yyyy/providers/Microsoft.Network/loadBalancers/kubernetes \
  --public-ip-address /subscriptions/xxxx/resourceGroups/zzzz/providers/Microsoft.Network/publicIPAddresses/foo

'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 469, in handler
    child_collection_key
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 335, in _get_child
    item_name.lower()), None)
  File "/home/foo/.virtualenvs/kubernetes/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 335, in <genexpr>
    item_name.lower()), None)
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Expected behavior**
frontend-ip address is changed to provided (existing) public ip.

**Environment summary**
```
% which pip
/home/foo/.virtualenvs/kubernetes/bin/pip
% which az
/home/foo/.virtualenvs/kubernetes/bin/az
% pip freeze
adal==1.1.0
antlr4-python3-runtime==4.7.1
applicationinsights==0.11.7
argcomplete==1.9.4
asn1crypto==0.24.0
azure-batch==5.0.0
azure-cli==2.0.47
azure-cli-acr==2.1.6
azure-cli-acs==2.3.6
azure-cli-advisor==0.6.0
azure-cli-ams==0.2.3
azure-cli-appservice==0.2.5
azure-cli-backup==1.2.1
azure-cli-batch==3.4.0
azure-cli-batchai==0.4.3
azure-cli-billing==0.2.0
azure-cli-botservice==0.1.1
azure-cli-cdn==0.1.1
azure-cli-cloud==2.1.0
azure-cli-cognitiveservices==0.2.3
azure-cli-command-modules-nspkg==2.0.2
azure-cli-configure==2.0.18
azure-cli-consumption==0.4.0
azure-cli-container==0.3.5
azure-cli-core==2.0.47
azure-cli-cosmosdb==0.2.1
azure-cli-dla==0.2.3
azure-cli-dls==0.1.3
azure-cli-dms==0.1.1
azure-cli-eventgrid==0.2.0
azure-cli-eventhubs==0.3.0
azure-cli-extension==0.2.2
azure-cli-feedback==2.1.4
azure-cli-find==0.2.12
azure-cli-interactive==0.3.30
azure-cli-iot==0.3.3
azure-cli-iotcentral==0.1.2
azure-cli-keyvault==2.2.4
azure-cli-lab==0.1.1
azure-cli-maps==0.3.2
azure-cli-monitor==0.2.4
azure-cli-network==2.2.6
azure-cli-nspkg==3.0.3
azure-cli-profile==2.1.1
azure-cli-rdbms==0.3.2
azure-cli-redis==0.3.2
azure-cli-reservations==0.4.0
azure-cli-resource==2.1.4
azure-cli-role==2.1.7
azure-cli-search==0.1.1
azure-cli-servicebus==0.3.0
azure-cli-servicefabric==0.1.4
azure-cli-signalr==1.0.0
azure-cli-sql==2.1.4
azure-cli-storage==2.2.2
azure-cli-telemetry==1.0.0
azure-cli-vm==2.2.4
azure-common==1.1.16
azure-datalake-store==0.0.31
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-mgmt-advisor==1.0.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.1.0
azure-mgmt-cdn==3.0.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-compute==4.3.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.1.0
azure-mgmt-containerregistry==2.2.0
azure-mgmt-containerservice==4.2.2
azure-mgmt-cosmosdb==0.4.0
azure-mgmt-datalake-analytics==0.2.0
azure-mgmt-datalake-nspkg==3.0.0
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==2.1.0
azure-mgmt-iotcentral==0.2.0
azure-mgmt-iothub==0.6.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-managementgroups==0.1.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0rc1
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.2.1
azure-mgmt-nspkg==3.0.2
azure-mgmt-rdbms==1.3.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-reservations==0.3.0
azure-mgmt-resource==2.0.0
azure-mgmt-search==2.0.0
azure-mgmt-servicebus==0.5.1
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0rc4
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.40.0
azure-multiapi-storage==0.2.2
azure-nspkg==3.0.2
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-nspkg==3.0.0
bcrypt==3.1.4
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
colorama==0.4.0
cryptography==2.3.1
enum34==1.1.6
funcsigs==1.0.2
futures==3.2.0
humanfriendly==4.16.1
idna==2.7
ipaddress==1.0.22
isodate==0.6.0
jmespath==0.9.3
knack==0.4.3
mock==2.0.0
monotonic==1.5
msrest==0.6.0
msrestazure==0.5.0
oauthlib==2.1.0
paramiko==2.4.2
pathlib2==2.3.2
pbr==4.3.0
portalocker==1.2.1
prompt-toolkit==1.0.15
pyasn1==0.4.4
pycparser==2.19
pydocumentdb==2.3.3
Pygments==2.2.0
PyJWT==1.6.4
PyNaCl==1.3.0
pyOpenSSL==18.0.0
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
requests==2.19.1
requests-oauthlib==1.0.0
scandir==1.9.0
scp==0.12.0
six==1.11.0
sshtunnel==0.1.4
tabulate==0.8.2
typing==3.6.6
urllib3==1.23
vsts-cd-manager==1.0.2
wcwidth==0.1.7
websocket-client==0.53.0
Whoosh==2.7.4
xmltodict==0.11.0
```

**Comment by tjprescott** [comment]
The problem is that you need to provide the ID to a load balancer frontend IP configuration. You are only providing the ID of the load balancer.

However, I will create a PR to add this validation so you don't get a stack trace.

**Comment by suonto** [comment]
Ah, stupid me. Thanks @tjprescott, impressive response time!

**Comment by tjprescott** [comment]
No worries--the command shouldn't throw a stack trace for something like this anyhow. Thanks for the report!
