### ISSUE TITLE
Container restart responses with Deployment failed. Error occurred in request

### ISSUE THREAD

**Issue by pawstern95** [Azure/azure-cli#7561]
**Describe the bug**
When I restart my container group I'm getting an error response:
```
Deployment failed. Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.ContainerInstance/locations/westeurope/operations/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?api-version=2018-06-01 (Caused by ResponseError('too many 500 error responses',))
```
Containers restart successfully anyway. 

**To Reproduce**
`az container restart -g <Resource-group> --name <Containers-group>`

**Environment summary**
Docker latest image.

**Comment by robo-tec** [comment]
I am having same problem

`robo@DESKTOP-BSU1TK0:~$ az container restart --name xxxxx --resource-group xxxxx
The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxx-xxxxx-xxxxx-xxxxx-xxxxx/resourceGroups/xxxxx/providers/Microsoft.ContainerInstance/containerGroups/xxxxx/restart?api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxx-xxxxx-xxxxx-xxxxx-xxxxx/resourceGroups/xxxxx/providers/Microsoft.ContainerInstance/containerGroups/xxxxx/restart?api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))`
