### ISSUE TITLE
Unable to update bot facebook channel

### ISSUE THREAD

**Issue by josephktcheung** [Azure/azure-cli#7563]
**Describe the bug**
I can create a facebook channel via `az bot facebook create`, but if I run it again to update the channel it fails.
**To Reproduce**
1. create a new bot using `az bot create`
2. create a FB channel using `az bot facebook create`
3. try to update FB channel using `az bot facebook create` again
**Expected behavior**
Can update channel successfully
**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
install: brew
macOS 10.13.6
azure-cli (2.0.33)
shell: zsh
**Additional context**
Error:
```
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9a0ad265-47aa-4d8c-849f-e314fa4bfdb6/resourceGroups/zeep-chat/providers/Microsoft.BotService/botServices/test-zeep-123/channels/FacebookChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9a0ad265-47aa-4d8c-849f-e314fa4bfdb6/resourceGroups/zeep-chat/providers/Microsoft.BotService/botServices/test-zeep-123/channels/FacebookChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/msrest/service_client.py", line 257, in send
    **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9a0ad265-47aa-4d8c-849f-e314fa4bfdb6/resourceGroups/zeep-chat/providers/Microsoft.BotService/botServices/test-zeep-123/channels/FacebookChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/Users/josephcheung/.azure/cliextensions/botservice/azext_bot/custom.py", line 337, in facebook_create
    return create_channel(client, channel, 'FacebookChannel', resource_group_name, resource_name)
  File "/Users/josephcheung/.azure/cliextensions/botservice/azext_bot/custom.py", line 323, in create_channel
    parameters=botChannel
  File "/Users/josephcheung/.azure/cliextensions/botservice/azext_bot/botservice/operations/channels_operations.py", line 96, in create
    request, header_parameters, body_content, **operation_config)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/msrest/service_client.py", line 290, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/msrest/service_client.py", line 257, in send
    **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.33/libexec/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9a0ad265-47aa-4d8c-849f-e314fa4bfdb6/resourceGroups/zeep-chat/providers/Microsoft.BotService/botServices/test-zeep-123/channels/FacebookChannel?api-version=2017-12-01 (Caused by ResponseError('too many 500 error responses',))
```

**Comment by sgellock** [comment]
behavior is by design.
