### ISSUE TITLE
az vm list-sizes produces an error (see stacktrace)

### ISSUE THREAD

**Issue by daniel-element-analytics** [Azure/azure-cli#7568]
**Describe the bug**
The vm list-sizes subcommands do not work.

**To Reproduce**
Run any vm list-sizes subcommand.

**Expected behavior**
A human readable error or success message is produced.

**Environment summary**
homebrew on Mac OS X Mojave 10.14

**Additional context**
```
daniel@daniel-mbp ~ $ az vm list-sizes
'NoneType' object has no attribute '__dict__'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 478, in get_op_handler
    get_versioned_sdk_path(self.cli_ctx.cloud.profile, rt, operation_group=operation_group))
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/profiles/_shared.py", line 368, in get_versioned_sdk_path
    api_version = getattr(api_version, operation_group)
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/profiles/_shared.py", line 176, in __getattr__
    self._resolve()
  File "/usr/local/Cellar/azure-cli/2.0.47/libexec/lib/python3.7/site-packages/azure/cli/core/profiles/_shared.py", line 163, in _resolve
    for operation_group_name, operation_type in self._client_type.__dict__.items():
AttributeError: 'NoneType' object has no attribute '__dict__'
```

```
azure-cli (2.0.47)

acr (2.1.6)
acs (2.3.6)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.5)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
botservice (0.1.1)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.5)
core (2.0.47)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.0)
extension (0.2.2)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.3.30)
iot (0.3.3)
iotcentral (0.1.2)
keyvault (2.2.4)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.4)
network (2.2.6)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.7)
search (0.1.1)
servicebus (0.3.0)
servicefabric (0.1.4)
signalr (1.0.0)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.4)

Python location '/Users/daniel/.pyenv/versions/3.7.0/bin/python3.7'
Extensions directory '/Users/daniel/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Aug  3 2018, 15:46:31) 
[Clang 8.0.0 (clang-800.0.42.1)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by tjprescott** [comment]
@yugangw-msft can you take a look? This fix should get into this release.

**Comment by tjprescott** [comment]
https://github.com/Homebrew/homebrew-core/pull/33054

**Comment by tjprescott** [comment]
The updated homebrew formula has been released. Please run `brew reinstall azure-cli` and your issue should be fixed.

**Comment by daniel-element-analytics** [comment]
Issue appears resolved. Thanks @tjprescott 

```
daniel@daniel-mbp$ az vm list-sizes --location westus2 -o table | head
MaxDataDiskCount    MemoryInMb    Name                    NumberOfCores    OsDiskSizeInMb    ResourceDiskSizeInMb
------------------  ------------  ----------------------  ---------------  ----------------  ----------------------
4                   4096          Standard_F2s_v2         2                1047552           16384
8                   8192          Standard_F4s_v2         4                1047552           32768
16                  16384         Standard_F8s_v2         8                1047552           65536
32                  32768         Standard_F16s_v2        16               1047552           131072
32                  65536         Standard_F32s_v2        32               1047552           262144
32                  131072        Standard_F64s_v2        64               1047552           524288
32                  147456        Standard_F72s_v2        72               1047552           589824
2                   2048          Standard_B1ms           1                1047552           4096
```

```
daniel@daniel-mbp$ brew info azure-cli
azure-cli: stable 2.0.48 (bottled), HEAD
Microsoft Azure CLI 2.0
```

```
daniel@daniel-mbp$ az --version
azure-cli (2.0.48)
```
