### ISSUE TITLE
az backup vault delete --ids XXXXXXXXX --force does not work.

### ISSUE THREAD

**Issue by gredondogc** [Azure/azure-cli#7619]
**Describe the bug**
`az backup vault delete --ids XXXXXXXXX --force`
cannot delete the vault as expected. 
It terminates with the error:
`Vault cannot be deleted as there are existing resources within the vault. Please ensure there are no backup items, protected servers or backup management servers associated with this vault. Unregister the following containers associated with this vault before proceeding for deletion : XXXX2`

**To Reproduce**
Try to delete a vault that still has a backup item of the kind "Azure Backup Agent".
I was finally able to delete the item using the portal but by deleting the protected server as I was unable to delete the protected item...

**Expected behavior**
I expected the --force option to delete all the existing resources within the vault.

**Environment summary**
azure-cli (2.0.30)
Python (Darwin) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)
MacOS High Sierra 10.13.6

Installed with brew

**Comment by christiankuhtz** [comment]
doesn't work and throws an exception

christian@lake:~$ az backup vault delete --resource-group vault --name vault --force
Are you sure you want to perform this operation? (y/n): y
Attemping to force delete vault: vault
Container not found. Please provide a valid container_name.
Traceback (most recent call last):                                                                                   
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 74, in delete_vault    
    client.delete(resource_group_name, vault_name)                                                                   
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/recoveryservices/operations/vaults_operations.py", line 359, in delete                                                                                                             
    raise exp                                                                                                        
msrestazure.azure_exceptions.CloudError: Azure Error: ServiceResourceNotEmptyWithContainerDetails                    
Message:  Vault cannot be deleted as there are existing resources within the vault. Please ensure there are no backup items, protected servers or backup management servers associated with this vault. Unregister the following containers associated with this vault before proceeding for deletion : Avi-Controller-0,Avi-se-aascb,Avi-se-ankin,Avi-se-bwayi,Avi-se-bxxzl                                                                                                        
Unregister all containers from the vault and then retry to delete vault                                              
                                                                                                                     
During handling of the above exception, another exception occurred:                                                  
                                                                                                                     
Traceback (most recent call last):                                                                                   
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke                                       
    cmd_result = self.invocation.execute(args)                                                                       
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute               
    raise ex                                                                                                         
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially    
    results.append(self._run_job(expanded_arg, cmd_copy))                                                            
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job              
    six.reraise(*sys.exc_info())                                                                                     
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise                                            
    raise value                                                                                                      
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job              
    result = cmd_copy(params)                                                                                        
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__              
    return self.handler(*args, **kwargs)                                                                             
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler        
    return op(**command_args)                                                                                        
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 77, in delete_vault    
    _force_delete_vault(cmd, vault_name, resource_group_name)                                                        
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 61, in _force_delete_vault                                                                                                                  
    cmd, backup_item_client, resource_group_name, vault_name, container_name)                                        
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 215, in list_items     
    _validate_container(container)                                                                                   
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 691, in _validate_container                                                                                                                 
    _validate_object(container, "Container not found. Please provide a valid container_name.")                       
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/backup/custom.py", line 704, in _validate_object                                                                                                                    
    raise ValueError(error_message)                                                                                  
ValueError: Container not found. Please provide a valid container_name.

**Comment by pvrk** [comment]
If "-force" is not given, the delete command will ask for consent from the user. Giving "-force" doesn't ask. It is NOT meant to forcefully delete ALL backup items in one call/command. I will treat this as an error where "Container not found. Please provide a valid container_name" should NOT have come up. The team will investigate and come back on this. Even after this is fixed, the expectation is that if the vault has backup items, the delete-vault command will fail with "Vault cannot be deleted as there are existing resources within the vault" error.
