### ISSUE TITLE
SSL Error when executing Azure Data Lake Store filesystem commands

### ISSUE THREAD

**Issue by rmatsun** [Azure/azure-cli#7636]
**Describe the bug**
When I execute any [Data Lake Store filesystem](https://docs.microsoft.com/en-us/cli/azure/dls/fs?view=azure-cli-latest)-related commands (e.g. `az dls fs list . . .`, `az dls fs create . . .`), an HTTP error is thrown:

```
HTTP error: SSLError(MaxRetryError("HTTPSConnectionPool(host='mydatalakestoragegen1.azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/bpt?OP=LISTSTATUS&api-version=2016-11-01&listSize=4000 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))",),)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-dls\azure\cli\command_modules\dls\custom.py", line 135, in list_adls_items
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-datalake-store\azure\datalake\store\core.py", line 148, in ls
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-datalake-store\azure\datalake\store\core.py", line 140, in _ls
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-datalake-store\azure\datalake\store\core.py", line 123, in _ls_batched
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-datalake-store\azure\datalake\store\lib.py", line 411, in call
azure.datalake.store.exceptions.DatalakeRESTException: HTTP error: SSLError(MaxRetryError("HTTPSConnectionPool(host='mydatalakestoragegen1.azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/bpt?OP=LISTSTATUS&api-version=2016-11-01&listSize=4000 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))",),)
```

**To Reproduce**
1. Install Azure CLI (in this case, [version 2.0.46](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#september-21-2018)).
2. Set the HTTP_PROXY and HTTPS_PROXY variables by executing the commands: `set HTTP_PROXY=https://<proxy-here>:<port-here>` and `set HTTPS_PROXY=https://<proxy-here>:<port-here>`.[<sup>1</sup>](#endnote-1)
3. Log in and set the subscription (`az login` and `az account set --subscription "<my-subscription>"`).
4. Execute any of the Azure Data Lake Store filesystem commands.
   * For example: `az dls fs list --account mydatalakestoragegen1 --path /test`)

**Expected behavior**
I expect the `az dls fs list ...` command to return a JSON object with the contents of the specified directory. I expect the `az dls fs create ...` command to create a file/directory (`--folder`) in the specified Azure Data Lake Store Gen1 resource.

**Environment summary**
* Installation method: MSI
* Version: 2.0.46
* OS: Windows 10 (64-bit)
* Shell: cmd.exe

**Additional context**
<span id="endnote-1">1. </span>I am behind my corporate network, and can't log in to Azure unless I specify the proxies.

**Comment by WeiLengUSC** [comment]
any progress on this issue?

**Comment by tjprescott** [comment]
@akharit for comment

**Comment by WeiLengUSC** [comment]
@akharit 

I am using this SDK to read from ADLS Gen2 dfs files. here is my simple example. I wonder whether this SDK support such functionality. 
https://XXXXXXXXXX.dfs.core.windows.net/XYZ/ABC/
```
import pandas as pd
from azure.datalake.store import core, lib, multithread
token = lib.auth()

adlsFileSystemClient = core.AzureDLFileSystem(token, store_name='XXXXXXXXX', url_suffix='dfs.core.windows.net')
```

**Comment by WeiLengUSC** [comment]
sounds good.

**Comment by tjprescott** [comment]
Thank you for answering the question @sachinsbigdata and @akharit. I will close this issue.
