### ISSUE TITLE
We should handle piping failures better

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#770]
When piping an AZ command to another command that does not exist, we get a broken pipe error.  

Example error:

```
root@3464c3e439a8:/# az vm list | jpterm
bash: jpterm: command not found
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 60, in main
    OutputProducer(formatter=formatter, file=file).out(cmd_result)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/_output.py", line 119, in out
    print(output, file=self.file, end='')
BrokenPipeError: [Errno 32] Broken pipe
root@3464c3e439a8:/# 
```

I would expect, after a fix, the following experience
```
root@3464c3e439a8:/# az vm list | jpterm
bash: jpterm: command not found
root@3464c3e439a8:/# 
```

**Comment by JasonRShaver** [comment]
Maybe?

```
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE,SIG_DFL) 
```

**Comment by tjprescott** [comment]
Do we need both this and #58? If not I'd close #58 since this actually describes what it should look like.
