### ISSUE TITLE
webapp:OpenSSL Crypto errors when trying to import a working/proven SSL certificate to Azure App Service

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#7707]
**Describe the bug**
When trying to upload an SSL certificate in PFX format to Azure App Service, using Azure CLI v2.0.49, I am instead thrown an OpenSSL.crypto.error and the command fails.

Here's the full error I'm getting:
_(Note that the striked-out lines are caused by Github, as there are multiple '~' in the error message)_
> [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-appservice\azure\cli\command_modules\appservice\commands.py", line 54, in _polish_bad_errors
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 346, in execute
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 1620, in upload_ssl_cert
>   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 1634, in _get_cert
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\OpenSSL\crypto.py", line 3055, in load_pkcs12
>     _raise_current_error()
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]

The certificate works perfectly: I can install it on my computer, and using Azure CLI I can even upload it to a Key Vault. But it doesn't work when trying to import into Azure App Service.

**To Reproduce**
- Download PFX file from Azure Blob Storage
- Set WebApp, ResourceGroup and CertPassword in Powershell variables
- Use the following command to upload the certificate: `az webapp config ssl upload --certificate-file "$ENV:TEMP\filename.pfx" --certificate-password $CertPWD --name $WebApp --resource-group $RG`
- Get Python/OpenSSL crypto error.

**Expected behavior**
The command should simply work.

**Environment summary**
Install Method: MSI 
CLI version: 2.0.49 
OS version: Windows 10 Pro v1803
Shell Type: Powershell v5.1.17134.228

**Comment by alexpilon666** [comment]
Haven't heard anything back in over a week.
Any idea what's going on there and why it isn't accepting my certificate ?
Thanks!

**Comment by tjprescott** [comment]
@panchagnula

**Comment by viktors-telle** [comment]
I am experiencing the same issue.

**Comment by panchagnula** [comment]
@viktors-telle / @alexpilon666 does import certificate to app service work from portal & just fails from CLI ? you can also run the command with the --debug flag & check if you get a detailed error message?

**Comment by nerdingas1** [comment]
@panchagnula I am facing the same issue. 
The certificate upload works through the portal, but fails from CLI.

debug flag does not seem to provide any additional info:
`cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 560, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 618, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 609, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\commands.py", line 54, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 588, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 297, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\__init__.py", line 461,
in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\custom.py", line 1758, in upload_ssl_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\custom.py", line 1772, in _get_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\crypto.py", line 3067, in load_pkcs1
2
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_fro
m_error_queue
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
[('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 560, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 618, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 609, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\commands.py", line 54, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 588, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", l
ine 297, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\__init__.py", line 461,
in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\custom.py", line 1758, in upload_ssl_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-appservice\azure\cli\command_modules\appserv
ice\custom.py", line 1772, in _get_cert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\crypto.py", line 3067, in load_pkcs1
2
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\_util.py", line 54, in exception_fro
m_error_queue
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]`

**Comment by bookersysops** [comment]
Im having the same issue

**Comment by BevanG** [comment]
I'm having the same issue on Windows 10 in CMD and Powershell. Azure CLI v2.0.74

```OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_check_tlen', 'wrong tag'), ('asn1 encoding routines', 'asn1_item_embed_d2i', 'nested asn1 error')]```

**Comment by panchagnula** [comment]
@ThejaChoudary / @Kotasudhakarreddy can we check if this repros on the latest CLI version and get more info if needed from customers facing this.

**Comment by Kotasudhakarreddy** [comment]
@alexpilon666 - I am unable to repro this issue in CLI latest version `2.16.0` .  Please try with latest CLI version and let us know with `-debug` logs if you still face the issue.
