### ISSUE TITLE
Exception when calling `az webapp config container set -i <image> ...`

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-cli#7730]
**Describe the bug**
I was attempting to modify the Docker container used for a linux FunctionApp deployment. I was using the command:
```
az webapp config container set -i "<MY IMAGE>" -n $FunctionAppName -g $ResourceGroupName
```
where "MY IMAGE" is a valid container image from MCR.

When doing so, I get the following exception:
```
'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 372, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 805, in update_container_settings
    return _mask_creds_related_appsettings(_filter_for_container_settings(cmd, resource_group_name, name, settings))
  File "/usr/local/Cellar/azure-cli/2.0.49/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 843, in _filter_for_container_settings
    fx_version = _get_fx_version(cmd, resource_group_name, name, slot).strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
I checked the FunctionApp to see if the setting was applied and unfortunately it was not. I noticed that I only get this exception when run this on a FunctionApp that I created with `--runtime` set instead of `-i` set. More details below.

**To Reproduce**

This is my script that I'm running. You should set the following parameters:
`FunctionAppName`, `ResourceGroupName`, `StorageName`, `PlanName`, `Location`
```shell
az group create -l $Location -n $ResourceGroupName
az appservice plan create -g $ResourceGroupName -n $PlanName --is-linux
az storage account create -n $StorageName -g $ResourceGroupName -l $Location --sku Standard_LRS
az functionapp create -g $ResourceGroupName -n $FunctionAppName -s $StorageName -p $PlanName --os-type linux --runtime dotnet
az functionapp config appsettings set -n $FunctionAppName -g $ResourceGroupName --setting FOO=bar
az webapp config container set -i "<MY IMAGE>" -n $FunctionAppName -g $ResourceGroupName
```

**Expected behavior**
The command should succeed and the image used in the Azure Function App should be updated.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Installed with Homebrew on macOS Mojave. Using PowerShell Core for macOS.

```
az --version
azure-cli (2.0.49)

acr (2.1.7)
acs (2.3.9)
advisor (0.6.0)
ams (0.2.4)
appservice (0.2.5)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.7)
core (2.0.49)
cosmosdb (0.2.2)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.0)
extension (0.2.2)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.3.31)
iot (0.3.3)
iotcentral (0.1.3)
keyvault (2.2.5)
lab (0.1.2)
maps (0.3.2)
monitor (0.2.5)
network (2.2.7)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.5)
role (2.1.8)
search (0.1.1)
servicebus (0.3.1)
servicefabric (0.1.6)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.3)
telemetry (1.0.0)
vm (2.2.6)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/tyler/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Oct  2 2018, 09:18:58)
[Clang 10.0.0 (clang-1000.11.45.2)]
```

**Additional context**
None at this time.

**Comment by tylerl0706** [comment]
cc @asavaritayal @SteveL-MSFT @joeyaiello  for awareness

**Comment by omerlh** [comment]
I'm experiencing the same issue with `az webapp config container show`

**Comment by patricklee2** [comment]
the appservice plan needs to be a linux plan
az appservice plan create -g $ResourceGroupName -n $PlanName --is-linux

**Comment by tylerl0706** [comment]
Yeah the app service plan I'm using is a linux plan for me. It's the only way to create Linux Function Apps.

That was a typo in my example above.

**Comment by patricklee2** [comment]
@TylerLeonhardt did the --is-linux option fix your problem?
