### ISSUE TITLE
az postgres server create: Doesn't say location is required. Throws exception when user does not put a location.

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/azure-cli#7773]
**Describe the bug**
The location argument is not marked as required. When I run `az postgres server create` without the `-l` command I get an ugly exception. (Not a nice reminder of the required arguments, which is what happens if I normally forget an argument). Once I add `-l westus` it works.

The `--help` printout does not say it is required:
```
PS C:\Users\jafreebe> az postgres server create --help

Command
    az postgres server create : Create a server.

Arguments
    --name -n           [Required] : Name of the server.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    --sku-name          [Required] : The name of the sku, typically, tier + family + cores, e.g.
                                     B_Gen4_1, GP_Gen5_8.
    --backup-retention             : The number of days a backup is retained.
    --geo-redundant-backup         : Enable Geo-redundant or not for server backup.
    --location -l                  : Location. You can configure the default location using `az
                                     configure --defaults location=<location>`.
    --ssl-enforcement              : Enable ssl enforcement or not when connect to server.  Allowed
                                     values: Disabled, Enabled.
    --storage-size                 : The max storage size of the server. Unit is megabytes.
    --tags                         : Space-separated tags in 'key[=value]' format. Use "" to clear
                                     existing tags.
    --version                      : Server version.

Authentication Arguments
    --admin-user -u     [Required]
    --admin-password -p            : The password of the administrator login.

Global Arguments
    --debug                        : Increase logging verbosity to show all debug logs.
    --help -h                      : Show this help message and exit.
    --output -o                    : Output format.  Allowed values: json, jsonc, table, tsv.
                                     Default: json.
    --query                        : JMESPath query string. See http://jmespath.org/ for more
                                     information and examples.
    --subscription                 : Name or ID of subscription. You can configure the default
                                     subscription using `az account set -s NAME_OR_ID`.
    --verbose                      : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Create a PostgreSQL server with only required paramaters in North Europe.
        az postgres server create -l northeurope -g testgroup -n testsvr -u username -p password

    Create a PostgreSQL server with a Standard performance tier and 2 vcore in North Europe.
        az postgres server create -l northeurope -g testgroup -n testsvr -u username -p password \
        --sku-name GP_Gen4_2

    Create a PostgreSQL server with all paramaters set.
        az postgres server create -l northeurope -g testgroup -n testsvr -u username -p password \
        --sku-name B_Gen4_2 --ssl-enforcement Disabled \ --storage-size 51200 --tags "key=value"
        --version {server-version}
```

The command crashes when I forget the location.
```
PS C:\Users\jafreebe> az postgres server create -n somename -g somegroup --sku-name GP_Gen4_2 -u totallyusername -p realpassw0rd!
Parameter 'ServerForCreate.location' can not be None.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-rdbms\azure\cli\command_modules\rdbms\custom.py", line 53, in _server_create
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-mgmt-rdbms\azure\mgmt\rdbms\postgresql\operations\servers_operations.py", line 126, in create
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-mgmt-rdbms\azure\mgmt\rdbms\postgresql\operations\servers_operations.py", line 69, in _create_initial
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\serialization.py", line 569, in body
    raise errors[0]
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\serialization.py", line 216, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\serialization.py", line 652, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'ServerForCreate.location' can not be None.
```

Works when I add location:
```
PS C:\Users\jafreebe> az postgres server create -n freebergquickstart2 -g wildflyFreeberg --sku-name GP_Gen4_2 -u username1 -p password1! -l westus
 - Running ..
```

**Comment by pzerger** [comment]
It's more than whether it's required. If I don't put it far enough up in my list of parameters, I get an "Parameter 'ServerForCreate.location' can not be None.". When I move --location to the first parameter in the list, works like a champ. Put it 7 or 8 parameters down the list, and I get that error every time.

**Comment by rachel-msft** [comment]
Thank you for submitting feedback. 

@JasonFreeberg Azure Database for PostgreSQL has location not set to required because the command will pick up the location that has been set as default for the subscription. If no default has been set for the subscription, it defaults to the location of the resource group chosen. Previously (when you submitted this issue) we had a bug that caused the error you saw. This now resolved.

@pzerger I have tried to reproduce the issue you described, but was unable to. This is what I ran. I tried with different regions successfully.
`az postgres server create --admin-password B7b5f926! --admin-user theuser --name theserver --resource-group thegroup --sku-name GP_Gen5_2 --backup-retention 8 --geo-redundant-backup Enabled --ssl-enforcement Disabled --storage-size 5120 --location southeastasia` 

Can you send your code snippet that reproduces the error?

**Comment by rachel-msft** [comment]
We will now mark this issue as closed. If a problem reoccurs or you are able to create a repro, please let us know.

@tjprescott #please-close
