### ISSUE TITLE
Activity-log list does not work well with `--query`

### ISSUE THREAD

**Issue by samjudeh** [Azure/azure-cli#7816]
I'm using Azure CLI version azure-cli (2.0.50) from a PowerShell window or a command prompt.

I'm trying to retrieve activity logs based on a filter and a time period using the below command. When I run the command however it returns logs from today's date only even though there are many more entries that satisfy the criteria from previous days.

__az monitor activity-log list --query "[?ends_with(authorization.action, '/write')]" --start-time 2018-11-01 --end-time 2018-11-12_

I also noticed that if I replaced the ends_with function with a filter expression like the below command then it works just fine and returns the correct activity logs from the time period specified. There appears to be an issue with using the ends_with function. The same issue happens when I use the contains function instead of the ends_with function.

_az monitor activity-log list --query "[?authorization.action == 'Microsoft.Resources/deployments/write']" --start-time 2018-11-01 --end-time 2018-11-12_

**Comment by tjprescott** [comment]
I just tested this and it worked correctly for this command and these functions in both Powershell and CMD.exe.

**Comment by samjudeh** [comment]
Did you run the following command: **_az monitor activity-log list --query "[?ends_with(authorization.action, '/write')]" --start-time 2018-11-01 --end-time 2018-11-12**

And did it return deployments other than ones performed today?

Are you also using the latest 2.0.50 version of the Azure CLI?

**Comment by samjudeh** [comment]
Yes, I've tried with --max-events but still have the same issue.

This command is very inconsistent and seems buggy to me. I tried re-running the exact same command and got an exception:
`C:\>**az monitor activity-log list --query "[?ends_with(authorization.action, '/write')].{auth:authorization}" --start-time 2018-11-01 --end-time 2018-11-12**
In function ends_with(), invalid type for value: None, expected one of: ['string'], received: "null"
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\knack\knack\cli.py", line 197, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\knack\knack\cli.py", line 157, in raise_event
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\knack\knack\query.py", line 46, in filter_output
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\parser.py", line 509, in search
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\visitor.py", line 94, in visit
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\visitor.py", line 180, in visit_filter_projection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\visitor.py", line 94, in visit
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\visitor.py", line 171, in visit_function_expression
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\functions.py", line 80, in call_function
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\functions.py", line 91, in _validate_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\functions.py", line 98, in _type_check
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-jvxpk9ku\jmespath\jmespath\functions.py", line 113, in _type_check_single
jmespath.exceptions.JMESPathTypeError: In function ends_with(), invalid type for value: None, expected one of: ['string'], received: "null"a`

If I change the --end-time in the above query from 2018-11-12 to 2018-11-13 then it returns an empty array.

**Comment by tarry87** [comment]
how to give multiple conditions under --query ?

**Comment by tarry87** [comment]
like one below 
--query '[].{status: status.value,authorization: authorization.scope,eventTimestamp :eventTimestamp, caller: caller,Operation: operationName.localizedValue}'  && --query "[?ends_with(to_string(authorization.action), '/deallocate/action')]

**Comment by tjprescott** [comment]
@tarry87 the query parameter uses JMESPath syntax. Please see the following for reference: http://jmespath.org/

**Comment by tarry87** [comment]
how to put further filter on eventTimestamp format to look more decent like conversion from UTC to IST?
 2019-02-27T16:49:48.358829+00:00(UTC)  to IST format time.

**Comment by tarry87** [comment]
can anyone here .. please help.. how to convert eventimestamp which is in JSON format "az monitor activity-log list" --query filter from one format to another ? Im block here and need help.

**Comment by tjprescott** [comment]
Sorry @tarry87, there is no JMESPath function that will accomplish what you are asking and thus there isn't a query that will do that. You would need to pass the results to some kind of external script to do the conversion in your language of choice.

**Comment by MyronFanQiu** [comment]
@samjudeh Hello. Is this issue solved? Looks like the documentation for `--max-events` should be updated.

**Comment by yonzhan** [comment]
@samjudeh any update for this issue?

**Comment by yonzhan** [comment]
@samjudeh  any update for this issue?

**Comment by MyronFanQiu** [comment]
closed this issue since looks like this issue has been solved. `--max-event`'s description is correct.
