### ISSUE TITLE
NotImplementedError: APIVersion 2018-05-01 is not available

### ISSUE THREAD

**Issue by dashesy** [Azure/azure-cli#7838]
**Describe the bug**
This used to work:

    az acr login --name something

But after upgrading axure-cli (pip) I get this error:

```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py27\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\__init__.py", line 373, in execute
    six.reraise(*sys.exc_info())
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    result = cmd(params)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\custom.py", line 172, in acr_login
    password=password)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 218, in get_login_credentials
    only_refresh_token=True)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\_docker_utils.py", line 166, in _get_credentials
    registry, resource_group_name = get_registry_by_name(cli_ctx, registry_name, resource_group_name)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\_utils.py", line 92, in get_registry_by_name
    cli_ctx, registry_name, resource_group_name)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\_utils.py", line 73, in get_resource_group_name_by_registry_name
    arm_resource = _arm_get_resource_by_name(cli_ctx, registry_name, REGISTRY_RESOURCE_TYPE)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\command_modules\acr\_utils.py", line 34, in _arm_get_resource_by_name
    result = get_resources_in_subscription(cli_ctx, resource_type)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\parameters.py", line 136, in get_resources_in_subscription
    rcf = get_mgmt_service_client(cli_ctx, ResourceType.MGMT_RESOURCE_RESOURCES)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\client_factory.py", line 69, in get_mgmt_service_client
    **kwargs)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\cli\core\commands\client_factory.py", line 136, in _get_mgmt_service_client
    client = client_type(cred, subscription_id, **client_kwargs)
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\mgmt\resource\resources\resource_management_client.py", line 74, in __init__
    client_models = {k: v for k, v in self.models(api_version).__dict__.items() if isinstance(v, type)}
  File "C:\Anaconda3\envs\py27\lib\site-packages\azure\mgmt\resource\resources\resource_management_client.py", line 96, in models
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2018-05-01 is not available
```

**To Reproduce**
az acr login --name something

**Expected behavior**
No exceptions for a simple command

**Environment summary**
pip install -U azure-cli
Running on windows bash

**Comment by dashesy** [comment]
I also updated `pip install azure` (not sure why there is azure and azure-cli) and now I get a different error:

ImportError: No module named v2018_09_01.models

It is possible to set up dependencies correctly for pip, but it seems azure-cli pulls in many packages that are have incorrect dependencies.

**Comment by dashesy** [comment]
I had to manually remove everything azure (and msrest) and re install it:

    pip freeze | grep azure | xargs pip uninstall -y
    pip freeze | grep msrest | xargs pip uninstall -y

Then install azure-cli again:

    pip install azure-cli

Package dependency management is hard I think
