### ISSUE TITLE
az role assignment list Crash? 

### ISSUE THREAD

**Issue by juanjojulian** [Azure/azure-cli#7909]
**Describe the bug**
I got a crash while trying to list roles with "az role assignment list"
```
Parameter 'scope' can not be None.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 373, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 159, in list_role_assignments
    include_inherited, include_groups)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 449, in _search_role_assignments
    role_id = _resolve_role_id(role, scope, definitions_client)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/role/custom.py", line 478, in _resolve_role_id
    role_defs = list(definitions_client.list(scope, "roleName eq '{}'".format(role)))
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/mgmt/authorization/v2018_01_01_preview/operations/role_definitions_operations.py", line 258, in internal_paging
    'scope': self._serialize.url("scope", scope, 'str', skip_quote=True)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 594, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 664, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'scope' can not be None.
```
**To Reproduce**
` az role assignment list  --all --subscription YOURSUB --role contributor -o table
`**Expected behavior**
A list of users with role contributor for the queried subscription 
**Environment summary**
```
juanjo@Dune scripts$ az --version
azure-cli (2.0.50)

acr (2.1.8)
acs (2.3.11)
advisor (2.0.0)
ams (0.3.0)
appservice (0.2.6)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.8)
core (2.0.50)
cosmosdb (0.2.3)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.3)
keyvault (2.2.6)
lab (0.1.3)
maps (0.3.2)
monitor (0.2.6)
network (2.2.8)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.4)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.6)
role (2.1.9)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.7)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.4)
telemetry (1.0.0)
vm (2.2.7)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/juanjo/.azure/cliextensions'

Python (Darwin) 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Additional context**

**Comment by yugangw-msft** [comment]
you have out of sync lib, please rebuild your env

**Comment by juanjojulian** [comment]
> you have out of sync lib, please rebuild your env

Thanks @yugangw-msft 
I have a default Mac OS installation and a default and updated Azure CLI installation using "brew" which is one of the Microsoft recommended methods to install the CLI in a Mac.

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest
