### ISSUE TITLE
Error listing Service Fabric clusters: 'ClusterListResult' is not iterable

### ISSUE THREAD

**Issue by danvanderboom** [Azure/azure-cli#7910]
**Describe the bug**
Attempting to list the Service Fabric clusters in a resource group while using Azure CLI produces an error.

**To Reproduce**
Ensure resource group test-rg exists. Then:
az sf cluster list -g test-rg

**Expected behavior**
A list of 0 or more Service Fabric clusters is displayed.

**Environment summary**
Azure Cloud Shell

**Additional context**
dan@Azure:~$ az sf cluster list -g gamefabric-rg
'ClusterListResult' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 345, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/servicefabric/custom.py", line 106, in list_cluster
    return list(cluster_list)
TypeError: 'ClusterListResult' object is not iterable

**Comment by iharrington** [comment]
I was able to reproduce.

**Comment by drr3w** [comment]
i was able to get this working by removing the `list()` call from `return list(cluster_list)` in custom.py on line 106. per the stack trace.

**Comment by xuyuji9000** [comment]
Met the same problem

``` 
'ClusterListResult' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 441, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.57/libexec/lib/python3.7/site-packages/azure/cli/command_modules/servicefabric/custom.py", line 106, in list_cluster
    return list(cluster_list)
TypeError: 'ClusterListResult' object is not iterable
```
