### ISSUE TITLE
[Bug] TypeError in `az network lb outbound-rule update` with `--frontend-ip-configs`

### ISSUE THREAD

**Issue by justenwalker** [Azure/azure-cli#7973]
**Describe the bug**

Running an outbound rule update and supplying `--frontend-ip-configs` always results in a  `TypeError`

**To Reproduce**

1. Run an update on a standard-lb existing outbound rule to add a new frontend ip config

```
az network lb outbound-rule update -g my-rg --lb-name my-lb -n my-outrule --frontend-ip-configs my-feip0 my-feip1 my-feip2
```

Get a `TypeError`:

```
__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 373, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 471, in handler
    parent = custom_function(instance=instance, parent=parent, **custom_func_args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/network/custom.py", line 1955, in set_lb_outbound_rule
    [SubResource(x) for x in frontend_ip_configurations] if frontend_ip_configurations else None)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/network/custom.py", line 1955, in <listcomp>
    [SubResource(x) for x in frontend_ip_configurations] if frontend_ip_configurations else None)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Expected behavior**

Any non-runtime error response. (Probably either success or error response from remote API)

**Environment summary**

Install Method: `brew install azure-cli`
OS: MacOS 10.14.1
Shell Type: zsh

az --version

```
azure-cli (2.0.51)

acr (2.1.9)
acs (2.3.11)
advisor (2.0.0)
ams (0.3.0)
appservice (0.2.7)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.51)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.5)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.7)
lab (0.1.3)
maps (0.3.2)
monitor (0.2.7)
network (2.2.9)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.10)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.8)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.5)
telemetry (1.0.0)
vm (2.2.8)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/myself/.azure/cliextensions'

Python (Darwin) 3.7.1 (default, Nov 12 2018, 12:15:08) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by tjprescott** [comment]
@justenwalker thanks for reporting this. It will be fixed in the December release.
