### ISSUE TITLE
Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by dtizon** [Azure/azure-cli#7983]
**Describe the bug**
Installation of AzureCLI on CentOS doesn't work

**To Reproduce**
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
sudo yum -y install azure-cli

['rpm', '--import', 'https://packages.microsoft.com/keys/microsoft.asc']

['sh', '-c', 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo']

Error with cmd: ['yum', 'install', '-y', 'azure-cli']
Output: Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package azure-cli.x86_64 0:2.0.52-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
 Package           Arch           Version               Repository         Size

Installing:
 azure-cli         x86_64         2.0.52-1.el7          azure-cli          25 M

Transaction Summary

Install  1 Package

Total download size: 25 M
Installed size: 173 M
Downloading packages:
Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed

[stderr]

Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed
Traceback (most recent call last):
  File "cyclecloud_install.py", line 369, in <module>
    main()
  File "cyclecloud_install.py", line 354, in main
    install_pre_req()
  File "cyclecloud_install.py", line 300, in install_pre_req
    _catch_sys_error(["yum", "install", "-y", "azure-cli"])
  File "cyclecloud_install.py", line 29, in _catch_sys_error
    output = check_output(cmd_list)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['yum', 'install', '-y', 'azure-cli']' returned non-zero exit status 1
".;
DEBUG: Finish sending metric.
DEBUG: 10:21:14 PM - NewAzureResourceGroupDeploymentCmdlet end processing.
DEBUG: 10:21:14 PM - NewAzureResourceGroupDeploymentCmdlet end processing.

**Expected behavior**
The package is expected to be signed

**Environment summary**
Python, Bash

**Additional context**

**Comment by dtizon** [comment]
Thank you willexu.
However the workaround you proposed can't apply in my case, because it is a "production" environment.
A lot of existing scripts are relying on it.

we really need a fix ASAPS.

**Comment by dtizon** [comment]
I wanted to warmly thank you. It is working now.
BR,
Daniel
