### ISSUE TITLE
az login throws UnicodeDecodeError on PowerShell

### ISSUE THREAD

**Issue by tw0517tw** [Azure/azure-cli#7989]
**Describe the bug**

When I try to `az login`, azure-cli throws error as below. 
My computer name is in Chinese, is this related?

```
C:\Users\tw0517tw> az login
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\_profile.py", line 1057, in _get_authorization_code_worker
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte

Login failed
```

**To Reproduce**

Type `az login` into PowerShell.

**Expected behavior**

Opens default browser let me login.

**Environment summary**

Installed using MSI from https://aka.ms/installazurecliwindows
azure-cli (2.0.52)
Windows 10 64bit
PowerShell 6.1.0 64bit

**Comment by yugangw-msft** [comment]
@tw0517tw, sorry for being late in response. This is a python system's bug which is likely caused by you have a Chinese machine name. To narrow down, could you please run the following command and let me know what you get?
```bash
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python" -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
```

**Comment by tw0517tw** [comment]
Hi @yugangw-msft ,

I've tried that and getting the result below. It seems to be the python system bug.

```
C:\Users\tw0517tw> ."C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python" -c "import socket; print(socket.getfqdn()); print(socket.gethostbyaddr(socket.gethostname()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte
```

**Comment by AttoLee** [comment]
replace Chinese machine name with pinyin, that solved problem.

**Comment by yonzhan** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
Please use pure ASCII as computer name to avoid Python's decoding problems.
