### ISSUE TITLE
az find helps for commands where long summary is left empty

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#8044]
**Describe the bug**
az find helps for commands where long summary is left empty

**To Reproduce**
have a command in extension where long-summary is declared but left empty like
    helps['devops'] = """
    type: group
    short-summary: Commands to work with Azure DevOps Organization level operations.
    long-summary:
    """

**Expected behavior**
az find -q devops should be able to search this
but instead it fails
C:\CLI\azure-devops-extension>az find -q devops
Error loading command module 'storage'
`az devops`
    Commands to work with Azure DevOps Organization level operations.
'long_summary'
Traceback (most recent call last):
  File "D:\CLIWheelWorkingDirectory\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\cliwheelworkingdirectory\azure\cli\core\commands\__init__.py", line 346, in execute
    six.reraise(*sys.exc_info())
  File "D:\CLIWheelWorkingDirectory\six.py", line 693, in reraise
    raise value
  File "d:\cliwheelworkingdirectory\azure\cli\core\commands\__init__.py", line 320, in execute
    result = cmd(params)
  File "d:\cliwheelworkingdirectory\azure\cli\core\commands\__init__.py", line 169, in __call__
    return self.handler(*args, **kwargs)
  File "d:\cliwheelworkingdirectory\azure\cli\core\__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "c:\users\gsaral\appdata\local\programs\python\python37-32\lib\site-packages\azure\cli\command_modules\find\custom.py", line 116, in find
    _print_hit(hit)
  File "c:\users\gsaral\appdata\local\programs\python\python37-32\lib\site-packages\azure\cli\command_modules\find\custom.py", line 79, in _print_hit
    if hit['long_summary']:
  File "D:\CLIWheelWorkingDirectory\whoosh\searching.py", line 1513, in __getitem__
    raise KeyError(fieldname)
KeyError: 'long_summary'

**Environment summary**
Azure CLI from github in windows machine

**Comment by gauravsaralMs** [comment]
create PR #8045 to address this issue..
I think this should be handled here because knack allows empty value for long-summary so that declaration is valid

**Comment by gauravsaralMs** [comment]
@troydai @tjprescott @derekbekoe : Please take a look at this issue and the PR

**Comment by tjprescott** [comment]
PR #8045 merged.
