### ISSUE TITLE
webapp:Deployment is taking longer than expected. Stack trace dump + Exit 1

### ISSUE THREAD

**Issue by phawxby** [Azure/azure-cli#8048]
**Describe the bug**
We started having deployment issues, deployments frequently returning as failed which throws the rest of our build pipeline. 

```
#!/bin/bash -eo pipefail
az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_USER -p $AZURE_SERVICE_PRINCIPAL_PASS --tenant $AZURE_TENANT

if [ "${CIRCLE_BRANCH}" == "master" ]; then
  az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name SNIP --src /tmp/drop.zip --slot rc
fi
[
  {
    "cloudName": "AzureCloud",
    "id": "SNIP",
    "isDefault": true,
    "name": "SNIP",
    "state": "Enabled",
    "tenantId": "SNIP",
    "user": {
      "name": "SNIP",
      "type": "servicePrincipal"
    }
  }
]
Zip deployment failed status 
Deployment is taking longer than expected. Please verify
                            status at 'SNIP/api/deployments/latest' beforing launching the app
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 320, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 264, in enable_zip_deploy
    response = _check_zip_deployment_status(deployment_status_url, authorization, timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1985, in _check_zip_deployment_status
    status at '{}' beforing launching the app""".format(deployment_status_url))
ValueError: Deployment is taking longer than expected. Please verify
                            status at 'SNIP/api/deployments/latest' beforing launching the app
Exited with code 1
```

**To Reproduce**
Deploy a zip, see commands above

**Expected behavior**
A deployment with exit code 0. Deployment on 16th November returned the following.
```
az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_USER -p $AZURE_SERVICE_PRINCIPAL_PASS --tenant $AZURE_TENANT

if [ "${CIRCLE_BRANCH}" == "master" ]; then
  az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name brand-engine-europe-west --src /tmp/drop.zip --slot rc
fi
[
  {
    "cloudName": "AzureCloud",
    "id": "SNIP",
    "isDefault": true,
    "name": "SNIP",
    "state": "Enabled",
    "tenantId": "SNIP",
    "user": {
      "name": "SNIP",
      "type": "servicePrincipal"
    }
  }
]
Deployment is taking longer than expected. Please verify status at 'SNIP.scm.azurewebsites.net/api/deployments/latest'
            beforing launching the app
{
  "active": false,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2018-12-04T12:26:27.105418Z",
  "id": "SNIP",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": null,
  "log_url": "SNIP/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "received_time": "2018-12-04T12:25:24.351963Z",
  "site_name": "SNIP",
  "start_time": "2018-12-04T12:25:24.787419Z",
  "status": 3,
  "status_text": "",
  "url": "SNIP/api/deployments/latest"
}
```

**Environment summary**
Running [circleci/node:8](https://hub.docker.com/r/circleci/node/)

```
sudo apt-get -y install lsb-release
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
sudo apt-get -y install apt-transport-https
sudo apt-get -y update && sudo apt-get -y --force-yes install azure-cli
```

Edit: Updated dates to make it a more like for like comparison, IE same tier for same tier.

**Comment by phawxby** [comment]
Update, this is only effecting our RC/Production tier, dev and stage seem to be deploying just fine. I have no explanation as they use the exact same command. The only difference is RC/Prod run on different app service plans to dev and stage. But that doesn't explain the stack trace dump or the exit 1.

**Comment by panchagnula** [comment]
@phawxby - sorry for the delay on responding on this.
This PR https://github.com/Azure/azure-cli/pull/7828 , changed some default behavior of the  zip deployment command, earlier if the deployment doesn't complete within the default timeout, instead of the earlier warning message an error is returned. In order to override the default timeout an optional --timeout parameter was introduced so we recommend running this command with a high value of timeout, if the zip deployment finishes before the timeout, the command will exist with a success

Also please make sure to try this with the latest CLI version, just to make sure you have all the fixes EX. this one #8174

**Comment by phawxby** [comment]
@panchagnula the CLI is installed a fresh with every CircleCI build as it only takes a few seconds so we should always be on the very latest CLI install.

```
      - run:
          name: Install azure CLI
          command: |
            sudo apt-get -y install lsb-release
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
            sudo apt-get -y install apt-transport-https
            sudo apt-get -y update && sudo apt-get -y --force-yes install azure-cli
```

Regarding the PR, I don't think it's working properly. Using this deployment command

```
az webapp deployment source config-zip --timeout 30000 --resource-group $AZURE_RESOURCE_GROUP --name SNIP --src /tmp/drop.zip --slot rc --debug
```

The result is an exit code 1 after 44 seconds, so something is going wrong somewhere. Below is the last 30 or so lines from the log with the identifying information snipped out. 
```
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "POST /subscriptions/SNIP/resourceGroups/SNIP/providers/Microsoft.Web/sites/SNIP/slots/rc/publishxml?api-version=2018-02-01 HTTP/1.1" 200 1145
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '1145'
msrest.http_logger :     'Content-Type': 'application/xml'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Server': 'Microsoft-IIS/10.0'
msrest.http_logger :     'X-AspNet-Version': '4.0.30319'
msrest.http_logger :     'X-Powered-By': 'ASP.NET'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '438bdc50-461f-441b-9880-4826921fcdf1'
msrest.http_logger :     'x-ms-correlation-request-id': '438bdc50-461f-441b-9880-4826921fcdf1'
msrest.http_logger :     'x-ms-routing-request-id': 'EASTUS2:20190208T153150Z:438bdc50-461f-441b-9880-4826921fcdf1'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Fri, 08 Feb 2019 15:31:50 GMT'
msrest.http_logger : Response content:
msrest.http_logger : <publishData><publishProfile profileName="SNIP - Web Deploy" publishMethod="MSDeploy" publishUrl="SNIP.scm.azurewebsites.net:443" msdeploySite="SNIP__rc" userName="$SNIP__rc" userPWD="SNIP" destinationAppUrl="http://SNIP.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="SNIP - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-077.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="SNIP__rc\$SNIP__rc" userPWD="SNIP" destinationAppUrl="http://SNIP.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
urllib3.connectionpool : Starting new HTTPS connection (1): SNIP.scm.azurewebsites.net:443
urllib3.connectionpool : https://SNIP.scm.azurewebsites.net:443 "POST /api/zipdeploy?isAsync=true HTTP/1.1" 202 0
urllib3.connectionpool : Starting new HTTPS connection (1): SNIP.scm.azurewebsites.net:443
urllib3.connectionpool : https://SNIP.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 200 608
Zip deployment failed.
telemetry.save : Save telemetry record of length 2523 in cache
telemetry.check : Negative: The /home/circleci/.azure/telemetry.txt was modified at 2019-02-08 15:31:48.750017, which in less than 600.000000 s
Exited with code 1
```

I have had a Sev B premier support ticket (118121225002599) open for almost 2 months now, this used to work.

**Comment by nathanclemente** [comment]
Hi there,

I am getting a similar CLI error. I run mine through Azure DevOps and am getting the same type of error. Mine worked a week ago:

```2019-02-15T05:02:11.5562744Z D:\a\r1\a\<removed>\drop>az functionapp deployment source config-zip --timeout 40000 -g <group> -n <name> --src <zip>.zip 
2019-02-15T05:02:41.6550269Z WARNING: Zip deployment failed status 
2019-02-15T05:02:41.6551385Z ERROR: Deployment is taking longer than expected. Please verify
2019-02-15T05:02:41.6551873Z                             status at 'https://<func>.scm.azurewebsites.net/api/deployments/latest' beforing launching the app
2019-02-15T05:02:41.6552330Z Traceback (most recent call last):
2019-02-15T05:02:41.6552752Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\knack\knack\cli.py", line 206, in invoke
2019-02-15T05:02:41.6553260Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 346, in execute
2019-02-15T05:02:41.6553688Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\six\six.py", line 693, in reraise
2019-02-15T05:02:41.6554160Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 320, in execute
2019-02-15T05:02:41.6554595Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 169, in __call__
2019-02-15T05:02:41.6555057Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\__init__.py", line 440, in default_command_handler
2019-02-15T05:02:41.6555519Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 264, in enable_zip_deploy
2019-02-15T05:02:41.6555986Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 1985, in _check_zip_deployment_status
2019-02-15T05:02:41.6557623Z ValueError: Deployment is taking longer than expected. Please verify
2019-02-15T05:02:41.6558087Z                             status at 'https://<func>.scm.azurewebsites.net/api/deployments/latest' beforing launching the app
2019-02-15T05:02:41.7711253Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
2019-02-15T05:02:43.3254284Z ##[error]Script failed with error: Error: D:\a\_temp\azureclitaskscript1550206895248.bat failed with return code: 1
2019-02-15T05:02:43.3446333Z ##[section]Finishing: Azure CLI ```

**Comment by phawxby** [comment]
@nathanclemente out of interest are you deploying to an app service slot?

**Comment by panchagnula** [comment]
@nathanclemente can you share the command you are using here?
@phawxby is your failure happening on a slot?

**Comment by phawxby** [comment]
@panchagnula Yes. Deployment to our dev and stage tiers works fine and doesn't time out, I realised today that the thing they have in common is they are both individual app services without slots. 

The error only occurs when deploying to the RC tier which is a slot of our production app service. And the error occurs in all 3 deployment regions every time. (We never deploy directly to production as we use slot swapping to bring the latest release online).

**Comment by panchagnula** [comment]
> @panchagnula Yes. Deployment to our dev and stage tiers works fine and doesn't time out, I realised today that the thing they have in common is they are both individual app services without slots.
> 
> The error only occurs when deploying to the RC tier which is a slot of our production app service. And the error occurs in all 3 deployment regions every time. (We never deploy directly to production as we use slot swapping to bring the latest release online).

@phawxby that's good info let me check if there was intact a regression here. Sorry I missed this from your original message 'az webapp deployment source config-zip --timeout 30000 --resource-group $AZURE_RESOURCE_GROUP --name SNIP --src /tmp/drop.zip --slot rc --debug'

**Comment by nathanclemente** [comment]
@panchagnula I was just calling the basic Azure CLI command for function apps: `az functionapp deployment source config-zip -g <group> -n <name> --src <zip>.zip `

I ended up switching in Azure DevOps to using the Function App deploy that's in preview instead and that seemed to work fine. Was unsure on what was causing the basic CLI message to fail.

**Comment by panchagnula** [comment]
thanks for the update - both actually use the same underlying code so using web app over functional shouldn't matter. but thank you for the update

**Comment by phawxby** [comment]
@panchagnula did you deploy a code update? I'm not sure if it's a coincidence but I updated our RC tier to run Node 10 today.

I've not seen the deploy phase turn green since december!
![image](https://user-images.githubusercontent.com/1090602/53354923-cf86d400-391f-11e9-8c0f-a1f5146556de.png)

**Comment by panchagnula** [comment]
@phawxby , nope we haven't deployed any recent changes to the command. Is this working with the same CLI version?

**Comment by phawxby** [comment]
Yes. Well I assume yes, it's installed fresh with every run.

**Comment by panchagnula** [comment]
ok so if you run az --version you will get the core & other extension versions being used. Can you share that info, so that we know what the working version.

**Comment by panchagnula** [comment]
closing this due to inactivity. Please file a new issue if you see this error with the latest version of CLI
