### ISSUE TITLE
az interactive - ImportError: cannot import name 'ArgumentsContext'

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-cli#8073]
**Describe the bug**
Launching `az interactive` throws errors `ImportError: cannot import name 'ArgumentsContext'`.  The error doesn't seem to stop the interactive terminal from working as far as I can see.

`
az interactive
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/senthuran/.azure/cliextensions/interactive/azext_interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/home/senthuran/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 87, in dump_command_table
    main_loader.load_arguments(None)
  File "/home/senthuran/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 33, in load_arguments
    from azure.cli.core import ArgumentsContext
ImportError: cannot import name 'ArgumentsContext'
`

**To Reproduce**
rm -rf ~/.azure
sudo apt-get remove azure-cli
sudo apt-get install azure-cli
az interactive

**Expected behavior**
No errors.

**Environment summary**
```bash
azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.52)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.6)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.8)
lab (0.1.4)
maps (0.3.2)
monitor (0.2.7)
network (2.2.10)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.11)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.9)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.6)
telemetry (1.0.0)
vm (2.2.9)

Extensions:
interactive (0.4.1)

Python location '/opt/az/bin/python3'
Extensions directory '/home/senthuran/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Nov 29 2018, 21:51:02)
[GCC 4.8.4]
```

**Additional context**
Same error on Cloud Shell as well.  Cloud Shell is also on 2.0.52.

**Comment by daniel-rodas** [comment]
Any update on this issue? Still receiving same error message after uninstalling and reinstalling Azure CLI with Homebrew on Mac
