### ISSUE TITLE
Seeing errors in debug output with extensions installed

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#8082]
**Describe the bug**
```
Unable to get extension metadata: Traceback (most recent call last):
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 73, in metadata
    self._metadata = self._metadata or self.get_metadata()
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 127, in get_metadata
    if os.path.split(parsed_dist_info_dir)[-1] == self.name.replace('-', '_'):
  File "C:\Users\wilx\AppData\Local\Programs\Python\Python36-32\lib\ntpath.py", line 205, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Unable to get extension version: Traceback (most recent call last):
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 61, in version
    self._version = self._version or self.get_version()
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\extension\__init__.py", line 108, in get_version
    return self.metadata.get('version')
AttributeError: 'NoneType' object has no attribute 'get'
```
**To Reproduce**
Steps to reproduce the behavior.
Install a few extensions (I had 'aem', 'alias', 'interactive')
Run `az --debug`

**Expected behavior**
No errors

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
I'm not able to repro, so I think this was a transient error and will close for now.
