### ISSUE TITLE
'ServiceProperties' object has no attribute 'static_website'

### ISSUE THREAD

**Issue by equivalent** [Azure/azure-cli#8119]
**Describe the bug**

Given I run:
```
az storage blob service-properties update --account-name derrentest --static-website=true --404-document=index.html --index-document=index.html
```
I will get error:
```
'ServiceProperties' object has no attribute 'static_website'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 388, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 378, in _run_job
    cmd_copy.exception_handler(ex)
  File "/home/t/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 243, in new_handler
    handler(ex)
  File "/home/t/.azure/cliextensions/storage-preview/azext_storage_preview/__init__.py", line 190, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 357, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 515, in handler
    result = setter(**setterargs)
  File "/home/t/.azure/cliextensions/storage-preview/azext_storage_preview/operations/blob.py", line 21, in set_service_properties
    kwargs['static_website'] = parameters.static_website
AttributeError: 'ServiceProperties' object has no attribute 'static_website'
```

**To Reproduce**

run the command above

**Expected behavior**

I expect to create static hosting blob as described in CLI steps https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website

**Environment summary**

ubuntu 18.04 

```
az --version
azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.1)
container (0.3.10)
core (2.0.54)
cosmosdb (0.2.6)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.1.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.4)
maps (0.3.3)
monitor (0.2.7)
network (2.2.11)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.7)
role (2.2.0)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.10)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.7)
telemetry (1.0.0)
vm (2.2.11)

Extensions:
storage-preview (0.2.0)

Python location '/opt/az/bin/python3'
Extensions directory '/home/t/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Dec 20 2018, 01:00:18) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal

```

**Comment by equivalent** [comment]
ok I've found out why this is happening, the Storage account needs to be `general purpose v2` if otherwise this will fails with error described above 

so it would be nice if the CLI give back some meaningful message about this

also the documentation https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website is pretty vague about this information 

> Azure Storage GPv2 accounts allow you to serve static content

I get it that it's `general purpose v2` but junior developers are screwed :)

**Comment by williexu** [comment]
@equivalent, thanks for looking into this.
As the command is part of the storage-preview extension right now, we will try to make the experience better once it is incorporated into the core CLI.
