### ISSUE TITLE
Storage container create fails with 'NoneType' Attribute error

### ISSUE THREAD

**Issue by justoke** [Azure/azure-cli#8128]
**Describe the bug**
I'm trying to create the serverless sample web app. Failure occurs on the first command shown on the [Step 2](https://docs.microsoft.com/en-gb/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=2) of 7

**To Reproduce**
Run the command:
az storage container create -n images --account-name mystorageaccountname --public-access blob

**Expected behavior**
A blob called images should be created under my storage account

**Environment summary**
Bash shell on Azure

**Additional context**
This is a demo app - it should work as described. If I use the Azure Portal I am able to create the blob manually, but the Auzre CLI does not work.

The error returned to the console is as follows
> Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 311, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 388, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 378, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 234, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 177, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 357, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 442, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 630, in create_container
    self._perform_request(request, expected_errors=[_CONTAINER_ALREADY_EXISTS_ERROR_CODE])
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 360, in _perform_request
    retry_interval = self.retry(retry_context)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/retry.py", line 218, in retry
    return self._retry(context, self._backoff)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/retry.py", line 154, in _retry
    if hasattr(context.request.body, 'read'):
AttributeError: 'NoneType' object has no attribute 'body'

**Comment by williexu** [comment]
@justoke can you do `az --version` and check the version of the CLI being used in cloudshell? I cant seem to reproduce this, but my cloudshell is on 2.0.53 at the moment.
