### ISSUE TITLE
Cancelling a blob copy when the job already failed returns an exception

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#8189]
**Describe the bug**
Cancelling a blob copy when the job already failed returns an exception

**To Reproduce**
```
az storage blob copy cancel -c files -b myfile--copy-id c9a55d56-2557-4d18-9625-2736d0f07758
There is currently no pending copy operation. ErrorCode: NoPendingCopyOperation
<?xml version="1.0" encoding="utf-8"?><Error><Code>NoPendingCopyOperation</Code><Message>There is currently no pending copy operation.
RequestId:954392ae-201e-009e-51eb-a61d47000000
Time:2019-01-08T00:43:40.6921135Z</Message></Error>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 370, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 234, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 177, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler                                                                        08/01  09:43:30
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 3180, in abort_copy_blob
    self._perform_request(request)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 306, in _perform_request
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 292, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureConflictHttpError: There is currently no pending copy operation. ErrorCode: NoPendingCopyOperation
<?xml version="1.0" encoding="utf-8"?><Error><Code>NoPendingCopyOperation</Code><Message>There is currently no pending copy operation.
RequestId:954392ae-201e-009e-51eb-a61d47000000
Time:2019-01-08T00:43:40.6921135Z</Message></Error>
```

**Expected behavior**
Would expect it would return the error without generating an exception

**Environment summary**
```
 az --version | head
azure-cli (2.0.50)

acr (2.1.8)
acs (2.3.11)
advisor (2.0.0)
ams (0.3.0)
appservice (0.2.6)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
...
sql (2.1.5)
storage (2.2.4)
telemetry (1.0.0)
vm (2.2.7)

Python location '/opt/az/bin/python3'
Extensions directory '/home/dad/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Nov  1 2018, 22:26:35)
[GCC 4.7.2]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by williexu** [comment]
@johanburati if I understand the issue you would simply rather not see a stack trace correct?

**Comment by johanburati** [comment]
@williexu yes, correct
