### ISSUE TITLE
az vmss list-skus doesn't handle missing --resource-group gracefully

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8230]
**Describe the bug**
missing --resource-group throws traceback when executing 'az vmss list-skus'

(--resource-group --name | --ids) are required
_**Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 277, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 246, in parse_ids_arguments
    raise ValueError('({} | {}) are required'.format(missing_required, '--ids'))
ValueError: (--resource-group --name | --ids) are required**_

**To Reproduce**
az vmss list-skus

**Expected behavior**
 a simple line "az vmss list-skus: error: the following arguments are required: --resource-group/-g"

**Environment summary**
azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.1)
container (0.3.10)
core (2.0.54)
cosmosdb (0.2.6)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.1.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.4)
maps (0.3.3)
monitor (0.2.7)
network (2.2.11)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.7)
role (2.2.0)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.10)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.7)
telemetry (1.0.0)
vm (2.2.11)

Python location '/opt/az/bin/python3'
Extensions directory '/home/christian/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Dec 20 2018, 01:00:18)
[GCC 7.3.0]

**Additional context**

**Comment by christiankuhtz** [comment]
looks like it's not limited to --resource-group missing.

christian@entropy:~/Desktop$ az vmss list-skus --resource-group foo
(--name | --ids) are required
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 277, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 246, in parse_ids_arguments
    raise ValueError('({} | {}) are required'.format(missing_required, '--ids'))
ValueError: (--name | --ids) are required

**Comment by christiankuhtz** [comment]
this looks like a wider problem..

christian@entropy:~/Desktop$ az network vnet subnet show
(--resource-group --vnet-name --name | --ids) are required
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 277, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 246, in parse_ids_arguments
    raise ValueError('({} | {}) are required'.format(missing_required, '--ids'))
ValueError: (--resource-group --vnet-name --name | --ids) are required

**Comment by tjprescott** [comment]
Thanks @christiankuhtz, will take a look at this. It should wrap the "ValueError" in a CLIError to avoid the stack trace. This would affect *any* command that has `--ids`
