### ISSUE TITLE
Updating CLI to v2.0.54 results in broken CLI

### ISSUE THREAD

**Issue by jochenvanwylick** [Azure/azure-cli#8252]
**Describe the bug**
Hi all - I had a running CLI  - v2.0.40-something and downloaded the latest MSI, v2.0.54. Ever since, I get the following error message:

```
Microsoft Windows [Version 10.0.18312.1007]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Jochen>az
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli\azure\cli\__main__.py", line 32, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\__init__.py", line 516, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\__init__.py", line 60, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-4k1cipeg\azure-cli-core\azure\cli\core\commands\arm.py", line 179, in register_ids_argument
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\__init__.py", line 28, in <module>
    from .azure_configuration import AzureConfiguration
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_configuration.py", line 34, in <module>
    from msrest import Configuration
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\__init__.py", line 27, in <module>
    from .configuration import Configuration
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\configuration.py", line 36, in <module>
    import requests
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 157, in <module>
    Binding.init_static_locks()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 148, in init_static_locks
    res = lib._setup_ssl_threads()
AttributeError: cffi library '_openssl' has no function, constant or global variable named '_setup_ssl_threads'
```

**To Reproduce**
- I tried installation repair - that didn't work
- I tried removing the az cli - confirmed with running az in console and observed 'could not be found' - reinstalled - same error.

**Environment summary**
Win 10 - latest preview build, with latest CLI fresh from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

**Comment by tjprescott** [comment]
After uninstalling the MSI, can you confirm that `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` is deleted?

**Comment by jochenvanwylick** [comment]
I removed again - the folder you mention is not deleted

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10-10-2017     07:48                AzCopy
d-----        16-1-2019     19:31                CLI2
d-----        1-12-2018     10:32                Storage Emulator
-a----         3-8-2016     14:23            139 LaunchCmd.cmd
-a----         3-8-2016     14:23          82726 WAIcon.ico
-a----         3-8-2016     14:23             69 WelcomeMessage.txt
```

**Comment by jochenvanwylick** [comment]
UPDATE: manually deleting `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` + re-installing fixes the issue. Thanks for the help !

**Comment by tjprescott** [comment]
@jochenvanwylick glad to see that worked for you! If this recurs, please reopen since it means there's something in our MSI pipe that needs addressing.
