### ISSUE TITLE
[webapp ssh] fails after 20mins of idle

### ISSUE THREAD

**Issue by patricklee2** [Azure/azure-cli#8282]
, after idle for more than 20 minutes (maybe?), I got this: 
……………………………………..
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tunnel.py", line 168, in _listen_to_client
    nbytes = client.recv_into(buf, 4096)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tunnel.py", line 168, in _listen_to_client
    nbytes = client.recv_into(buf, 4096)
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fd195388700 (most recent call first):
  File "/opt/az/lib/python3.6/traceback.py", line 101 in print_exception
  File "/opt/az/lib/python3.6/traceback.py", line 159 in print_exc
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tunnel.py", line 181 in _listen_to_client
  File "/opt/az/lib/python3.6/threading.py", line 864 in run
  File "/opt/az/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/az/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fd19638a700 (most recent call first):
  File "/opt/az/lib/python3.6/threading.py", line 1072 in _wait_for_tstate_lock
  File "/opt/az/lib/python3.6/threading.py", line 1056 in join
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tunnel.py", line 137 in _listen
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/tunnel.py", line 186 in start_server
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2296 in _start_tunnel
  File "/opt/az/lib/python3.6/threading.py", line 864 in run
  File "/opt/az/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/az/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fd19eaad700 (most recent call first):
/usr/bin/az: line 2: 30043 Aborted                 (core dumped) /opt/az/bin/python3 -Im azure.cli "$@"

**Comment by patricklee2** [comment]
assign to @patricklee2

**Comment by patricklee2** [comment]
easier repro:
stop the webapp and wait for a timeout
