### ISSUE TITLE
[OSX] utils.format is not a function

### ISSUE THREAD

**Issue by yshahin** [Azure/azure-cli#831]
When trying to delete an auto scaling rule on a cloud service I get this error

info:    Executing command insights autoscale setting delete
error:   utils.format is not a function
error:   Error information has been recorded to <location>
error:   insights autoscale setting delete command failed

```
at insightsAutoscaleSettingCommand__executeDeleteCmd__8 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:281:49)
  at insightsAutoscaleSettingCommand__prepareAndExecuteDelete__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:93:10)
  at __2 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/insights/insights.autoscale.setting.js:45:39)
```

**Comment by tjprescott** [comment]
Hi @yshahin this repo is for the new CLI, written in Python. Your issue is for the CLI written in Node. Please open this issue in: https://github.com/Azure/azure-xplat-cli
