### ISSUE TITLE
az security auto-provisioning-setting update doesn't work

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-cli#8313]
**Describe the bug**
Unable to set auto-provisioning setting to "on" or "off" using CLI.

**To Reproduce**
`az security auto-provisioning-setting update -n default --auto-provision on` or
`az security auto-provisioning-setting update -n default --auto-provision off`

The error is
```bash
az security auto-provisioning-setting update -n default --auto-provision on
'on' is not a valid AutoProvision
Traceback (most recent call last):
  File "/home/senthuran/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 659, in cli_execute
    result = invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 441, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/security/custom.py", line 145, in update_security_auto_provisioning_setting
    new_auto_provision = AutoProvision(auto_provision)
  File "/opt/az/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/opt/az/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/opt/az/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'on' is not a valid AutoProvision
```

**Expected behavior**
The setting is changed and that I can view the update via 
`az security auto-provisioning-setting list`

**Environment summary**
```bash
az -v
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)

Extensions:
interactive (0.4.1)

Python location '/opt/az/bin/python3'
Extensions directory '/home/senthuran/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jan 11 2019, 04:47:05)
[GCC 4.8.4]
```

**Additional context**
I've also tested with Cloud Shell and got the same error.

**Comment by ChrisCalzaretta** [comment]
I some digging in the repo to see what the expected values really should be.
It seems that the case stated in the docs does not match what is really required.
Instead of "on" or "off" the values must be 
"On"
or
"Off"

**Comment by amitronen1** [comment]
> I did some digging in the repo to see what the expected values should be.
> The case stated in the docs does not match what is really required.
> Instead of "on" or "off" the values must be
> "On"
> or
> "Off"

that's correct. properties are case-sensitive.
closing issue due to client error.
