### ISSUE TITLE
Unable to install extension using azure-cli 2.0.55.

### ISSUE THREAD

**Issue by mxplusb** [Azure/azure-cli#8315]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

azure-firewall

### Description of issue (in as much detail as possible)

Cannot install the azure-firewall extension with azure-cli 2.0.55.

```
Command arguments: ['extension', 'add', '-n', 'azure-firewall', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f262c5c90d0>, <function OutputProducer.on_global_arguments at 0x7f262b6232f0>, <function CLIQuery.on_global_arguments at 0x7f262b648730>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.009 seconds.
Loaded module 'appservice' in 0.011 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.015 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.004 seconds.
Loaded module 'botservice' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.009 seconds.
Loaded module 'cloud' in 0.005 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.004 seconds.
Loaded module 'container' in 0.003 seconds.
Loaded module 'cosmosdb' in 0.006 seconds.
Loaded module 'dla' in 0.007 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.005 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.003 seconds.
Loaded module 'feedback' in 0.004 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.002 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.007 seconds.
Loaded module 'keyvault' in 0.026 seconds.
Loaded module 'lab' in 0.010 seconds.
Loaded module 'maps' in 0.005 seconds.
Loaded module 'monitor' in 0.011 seconds.
Loaded module 'network' in 0.039 seconds.
Loaded module 'policyinsights' in 0.006 seconds.
Loaded module 'profile' in 0.003 seconds.
Loaded module 'rdbms' in 0.011 seconds.
Loaded module 'redis' in 0.007 seconds.
Loaded module 'relay' in 0.005 seconds.
Loaded module 'reservations' in 0.004 seconds.
Loaded module 'resource' in 0.016 seconds.
Loaded module 'role' in 0.006 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.005 seconds.
Loaded module 'servicebus' in 0.006 seconds.
Loaded module 'servicefabric' in 0.010 seconds.
Loaded module 'signalr' in 0.003 seconds.
Loaded module 'sql' in 0.015 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.052 seconds.
Loaded module 'vm' in 0.024 seconds.
Loaded all modules in 0.416 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/mike/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f262c89c268>, <function register_ids_argument.<locals>.add_ids_arguments at 0x7f2628e93048>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f262695d598>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f262b623378>, <function CLIQuery.handle_query_parameter at 0x7f262b6487b8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f2628e930d0>, <function handler at 0x7f2626841d08>]
Extensions directory: '/home/mike/.azure/cliextensions'
urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 77478
Candidates ['azure_firewall-0.1.1-py2.py3-none-any.whl']
Candidates ['azure_firewall-0.1.1-py2.py3-none-any.whl']
Candidates ['azure_firewall-0.1.1-py2.py3-none-any.whl']
Candidates ['azure_firewall-0.1.1-py2.py3-none-any.whl']
Choosing the latest of the remaining candidates.
Chosen {'downloadUrl': 'https://azurecliprod.blob.core.windows.net/cli-extensions/azure_firewall-0.1.1-py2.py3-none-any.whl', 'filename': 'azure_firewall-0.1.1-py2.py3-none-any.whl', 'metadata': {'azext.isPreview': True, 'azext.minCliCoreVersion': '2.0.46', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'azpycli@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/master/src/azure-firewall'}}}, 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'azure-firewall', 'summary': 'Manage Azure Firewall resources.', 'version': '0.1.1'}, 'sha256Digest': 'f0e6114e5b4c08845a2ba0ea1d332d9f88d895ef122ef3a0fd2d960584b9feff'}
Extension source is url? True
Extensions directory: '/home/mike/.azure/cliextensions'
Downloading https://azurecliprod.blob.core.windows.net/cli-extensions/azure_firewall-0.1.1-py2.py3-none-any.whl to /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliprod.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliprod.blob.core.windows.net:443 "GET /cli-extensions/azure_firewall-0.1.1-py2.py3-none-any.whl HTTP/1.1" 200 845934
Downloaded to /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl
Validating the extension /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl
Checksum of /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl is OK
Extension compatibility result: is_compatible=True cli_core_version=2.0.55 min_required=2.0.46 max_required=None
Validation successful on /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl
Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
Linux distro check: An error occurred while checking linux distribution version source list consistency.
[Errno 2] No such file or directory: '/etc/apt/sources.list.d/azure-cli.list'
Executing pip with args: ['install', '--target', '/home/mike/.azure/cliextensions/azure-firewall', '/tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl']
Running: ['/home/linuxbrew/.linuxbrew/opt/python/bin/python3.7', '-m', 'pip', 'install', '--target', '/home/mike/.azure/cliextensions/azure-firewall', '/tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
Created temporary directory: /tmp/pip-target-n07msdzf
Created temporary directory: /tmp/pip-ephem-wheel-cache-48mibp2n
Created temporary directory: /tmp/pip-req-tracker-q3ozg6xs
Created requirements tracker '/tmp/pip-req-tracker-q3ozg6xs'
Created temporary directory: /tmp/pip-install-dw421am6
Processing /tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl
  Added azure-firewall==0.1.1 from file:///tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl to build tracker '/tmp/pip-req-tracker-q3ozg6xs'
  Removed azure-firewall==0.1.1 from file:///tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl from build tracker '/tmp/pip-req-tracker-q3ozg6xs'
Installing collected packages: azure-firewall
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-q3ozg6xs'
Exception:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/distutils/command/install.py", line 248, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both")
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

Command '['/home/linuxbrew/.linuxbrew/opt/python/bin/python3.7', '-m', 'pip', 'install', '--target', '/home/mike/.azure/cliextensions/azure-firewall', '/tmp/tmpd01rfdqv/azure_firewall-0.1.1-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 2.
Pip failed so deleting anything we might have installed at /home/mike/.azure/cliextensions/azure-firewall
An error occurred. Pip failed with status code 2. Use --debug for more information.
```

**Comment by gauravsaralMs** [comment]
This issue seems to be coming from latest pip version released 
![image](https://user-images.githubusercontent.com/43203065/51589464-180c3580-1f0d-11e9-8e13-eaa8adcbada7.png)

I created 2 scripts in one place we upgrade pip to latest and in other we are not doing that
the script where I have upgraded pip, there extension add fails
the script where I have *not* upgraded pip, their extension add passes without any issue

cc: @tjprescott

**Comment by tjprescott** [comment]
@mxplusb please update your pip installation. This was a problem with pip 19.0

**Comment by mxplusb** [comment]
@tjprescott I installed it with `brew install -v azure-cli`, that's not an option.

**Comment by gauravsaralMs** [comment]
> @tjprescott I installed it with `brew install -v azure-cli`, that's not an option.

Try this command
`python -m pip install --upgrade pip` 

This will upgrade pip and you should be unblocked post that
