### ISSUE TITLE
cannot deserialize properties in `az network lb update`

### ISSUE THREAD

**Issue by mxplusb** [Azure/azure-cli#8321]
**Describe the bug**

Internal serialization issue while trying to set custom properties.

```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 571, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1267, in _deserialize
    return self.deserialize_data(data, response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 388, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 381, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 357, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 515, in handler
    result = setter(**setterargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/network/v2018_10_01/operations/load_balancers_operations.py", line 269, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/network/v2018_10_01/operations/load_balancers_operations.py", line 215, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'LoadBalancer')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 574, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 571, in body
    data = deserializer._deserialize(data_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1267, in _deserialize
    return self.deserialize_data(data, response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1258, in _deserialize
    self._deserialize(local_type, value)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**To Reproduce**

Set up a Standard SKU load balancer with a Public IP. Then attempt to migrate the Frontend IP Configuration to a Private IP configuration.

```bash
$ az network lb update -n <lb> --set frontendIpConfigurations[0].privateIPAddress="10.0.0.5" --set frontendIpConfigurations[0].privateIPAllocationMethod="Static" --set frontendIpConfigurations[0].subnet="<snet>" -g <rg>
```

**Expected behavior**

The properties should've updated.

**Environment summary**

I was able to independently replicate this in the Azure Cloud Shell and my local machine. On the machine I verified the issue on, the az CLI was installed through Ubuntu packages on WSL 16.04.

**Additional context**

The problem seems specific to this property: `frontendIpConfigurations[0].subnet=<snet>`. If I pass the two other properties, it will throw configuration errors, which is good. I got the same results in both places.

**Comment by mxplusb** [comment]
User error.

The property I really needed was `frontendIpConfigurations[0].subnet.id` as `frontendIpConfigurations[0].subnet` is a struct with it's own properties.
