### ISSUE TITLE
Not able to login with PCS Login. Returns "Entry not found in cache"

### ISSUE THREAD

**Issue by pangar-ms** [Azure/azure-cli#8520]
I am running into login error, any guidance on resolving or troubleshooting this issue will help.

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BDUNS3J7W to authenticate.
Error: Entry not found in cache.
at Logger.createError (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\log.js:216:13)
at TokenRequest. (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\token-request.js:526:40)
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\token-request.js:148:20
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\cache-driver.js:366:7
at C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\cache-driver.js:301:7
at Request._callback (C:\Source\Farm Beats\pcs-cli\node_modules\adal-node\lib\util.js:130:7)
at Request.self.callback (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:185:22)
at Request.emit (events.js:189:13)
at Request. (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:1157:10)
at Request.emit (events.js:189:13)
at IncomingMessage. (C:\Source\Farm Beats\pcs-cli\node_modules\request\request.js:1079:12)
at Object.onceWrapper (events.js:277:13)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1103:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by yugangw-msft** [comment]
please log an bug at https://github.com/AzureAD/azure-activedirectory-library-for-nodejs
