### ISSUE TITLE
[Azdev, Extension] Having both a whl extension and dev extension of the same causes unhelpful error

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#8621]
```
(envnew) C:\Users\wilx\azure-cli>az mysql up -h
super(type, obj): obj must be an instance or subtype of type
Traceback (most recent call last):
  File "C:\Users\wilx\azure-cli\envnew\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 251, in execute
    self.commands_loader.load_arguments(command)
  File "c:\users\wilx\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 267, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "c:\users\wilx\azure-cli-extensions\src\db-up\azext_db_up\__init__.py", line 27, in load_arguments
    super(DbUpCommandsLoader, self).load_arguments(command)
TypeError: super(type, obj): obj must be an instance or subtype of type
```
We should output something that would help the user figure out why they are seeing an error.

**Comment by williexu** [comment]
Transferred :). Added it to the other repo at first because it was related.

**Comment by tjprescott** [comment]
Can you provide the methods you used to install the two conflicting extensions? I'm assuming one was via azdev. The other--was it direct with pip or using az extension add with a WHL?

**Comment by tjprescott** [comment]
I think this has been resolved. The non-dev extension will take precedence. Closing.
