### ISSUE TITLE
Errors installing on Mac OS 

### ISSUE THREAD

**Issue by ford-thomas-w** [Azure/azure-cli#8623]
**Describe the bug**
Errors when installing on Mac OS 10.14 Mojave

**To Reproduce**
==> Downloading https://homebrew.bintray.com/bottles/azure-cli-2.0.58.mojave.bot
Already downloaded: /Users/tford/Library/Caches/Homebrew/downloads/5b87260f640b0ea7b058b87bce6ea4d6fe50ac4553e7bd1b46adbe29bc2a3727--azure-cli-2.0.58.mojave.bottle.tar.gz
==> Pouring azure-cli-2.0.58.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/azure-cli/2.0.58: 21,305 files, 94.3MB
tford$ az

Welcome to Azure CLI!
---------------------
Use `az -h` to see available commands or go to https://aka.ms/cli.

Telemetry
---------
The Azure CLI collects usage data in order to improve your experience.
The data is anonymous and does not include commandline argument values.
The data is collected by Microsoft.

You can change your telemetry settings with `az configure`.

     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|

Welcome to the cool new Azure CLI!

Use `az --version` to display the current version.
Here are the base commands:

No module named 'pkg_resources'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 263, in execute
    self.help.show_welcome(subparser)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 656, in show_welcome
    help_file = self.group_help_cls(self, '', parser)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 219, in __init__
    child.load(options)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/help.py", line 163, in load
    description = getattr(options, 'description', None)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/parser.py", line 216, in __getattribute__
    if callable(self._description) else self._description
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 457, in default_description_loader
    op = handler or self.get_op_handler(operation)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 496, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/command_modules/interactive/custom.py", line 8, in <module>
    from azure.cli.core.extension.operations import (reload_extension, update_extension,
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/extension/operations.py", line 18, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

**Expected behavior**
no errors

**Environment summary**
Installed using brew on Mac OS 10.14 Mojave

**Additional context**

**Comment by marstr** [comment]
Howdy @ford-thomas-w, a fresh install on my 10.14 machine seems to work. Do you have any azure-cli extensions lingering from a previous install?

**Comment by marstr** [comment]
For other folks hitting this: If you've installed Python outside of `brew`, and have not forced brew to link over the existing Python installation there can be installation problems as seen above. This is a problem that we're aware of, and you can add your voice to the conversation by reacting-to or commenting on issue https://github.com/Azure/azure-cli/issues/8654. In the mean-time, you can execute `brew uninstall azure-cli` and try installing from our catch-all script instead: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest

**Comment by marstr** [comment]
I'm going to close this out, but if you're still having trouble after installing via the installer script I can open it back up.

**Comment by ford-thomas-w** [comment]
Thank you Martin.  This worked.
t
