### ISSUE TITLE
storage blob upload failed in cli interactive mode

### ISSUE THREAD

**Issue by softveda** [Azure/azure-cli#8635]
I was following the tutorial at https://docs.microsoft.com/en-us/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=2

I am using az cli interactive mode within windows subsystem for Linux. 
The following command failed
`storage blob upload -c \$web --account-name <storage account name> -f settings.js -n settings.js`

The error message was
`
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
  File "/home/pratik/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 659, in cli_execute
    result = invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 237, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 180, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 448, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 325, in upload_blob
    return type_func[blob_type]()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 318, in upload_block_blob
    return client.create_blob_from_path(**create_blob_args)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 463, in create_blob_from_path
    timeout=timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 567, in create_blob_from_stream
    progress_callback(0, count)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/_validators.py", line 702, in _update_progress
    hook = cmd.cli_ctx.get_progress_controller(det=True)
TypeError: progress_patch() got an unexpected keyword argument 'det'
`

It worked when I used the command from outside interactive mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4e415-fc8d-26d5-3213-da937fd6932c
* Version Independent ID: dcb2f2d6-fd80-495d-8582-8be859d68792
* Content: [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Please provide the output of `az --version`

**Comment by neuralspatial** [comment]
az: error: the following arguments are required: _command_package
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {acr,acs,aks,openshift,advisor,ams,webapp,appservice,functionapp,backup,batch,batchai,billing,bot,cdn,cloud,cognitiveservices,configure,consumption,container,cosmosdb,dla,dls,dms,eventgrid,eventhubs,extension,feedback,find,hdinsight,interactive,iot,iotcentral,keyvault,kusto,lab,maps,monitor,network,policy,login,logout,self-test,account,mariadb,mysql,postgres,redis,relay,reservations,group,resource,provider,feature,tag,deployment,lock,managedapp,role,ad,identity,search,security,servicebus,sf,signalr,sql,storage,disk,image,snapshot,vm,vmss,sig}

**Comment by tjprescott** [comment]
Since you are using the interactive extension, I will transfer this issue to the extensions repository.
