### ISSUE TITLE
Cancelling a login seems to invalidate my previous login

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#870]
I hit Ctrl+C during a login to cancel it, and it effectively logged me out.

```
jasonsha@JasonShaMBP: ~/temp $ az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BY668Y9DC to authenticate.
EnvironmentName    Name                           TenantId                              State      IsDefault
-----------------  -----------------------------  ------------------------------------  -------  -----------
AzureCloud         AzureCLI-Demo                  72f9xxbf-86f1-41af-xxxx-2d7cd011dxxx  Enabled            1
jasonsha@JasonShaMBP: ~/temp $ az login --out json | jpterm
To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BC6XCB41S to authenticate.
^CTraceback (most recent call last):
  File "/usr/local/bin/jpterm", line 6, in <module>
    jpterm.main()
  File "/Library/Python/2.7/site-packages/jpterm.py", line 221, in main
    input_json = _load_input_json(getattr(args, 'input-json', None))
  File "/Library/Python/2.7/site-packages/jpterm.py", line 188, in _load_input_json
    input_json = json.loads(sys.stdin.read())
KeyboardInterrupt
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/__main__.py", line 29, in <module>
    sys.exit(azure.cli.main.main(args))
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/main.py", line 57, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/application.py", line 117, in execute
    result = expanded_arg.func(params)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/commands/__init__.py", line 220, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 58, in login
    tenant)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/_profile.py", line 89, in find_subscriptions_on_login
    self._management_resource_uri)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/_profile.py", line 265, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, CLIENT_ID)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/adal/authentication_context.py", line 253, in acquire_token_with_device_code
    return self._acquire_token(token_func)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/adal/authentication_context.py", line 89, in _acquire_token
    return token_func(self)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/adal/authentication_context.py", line 246, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/adal/token_request.py", line 398, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/adal/oauth2_client.py", line 337, in get_token_with_polling
    time.sleep(refresh_internal)
KeyboardInterrupt
jasonsha@JasonShaMBP: ~/temp $ az vm list --out json
Could not retrieve token from local cache, please run 'login'.
```

**Comment by mayurid** [comment]
@JasonRShaver : You were already logged in and it went ahead and logged you out?

**Comment by mayurid** [comment]
@JasonRShaver : Dont see this behavior. I will close this but please feel free to reactivate if are still seeing it.

**Comment by lostintangent** [comment]
I'm seeing this same issue. If I log into the CLI, and then run and abort another login operation, I'll get the "Please run 'login'" message when trying to execute commands (e.g. `az resource group list`). Strangely enough, I can successfully run `az account list`, but nothing else works until I log out and log back in.
