### ISSUE TITLE
az container export does not work

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#8703]
**Describe the bug**
root@Alexey-HP:~# az container export \
> --resource-group centosresourcegroup \
> --name centoscontainergroup \
> --file centoscontainergroup.yaml
'NoneType' object has no attribute 'type'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 581, in container_export
    if 'identity' in resource and resource['identity'].type != ResourceIdentityType.none:
AttributeError: 'NoneType' object has no attribute 'type'

**To Reproduce**
az container export --resource-group centosresourcegroup --name centoscontainergroup --file centoscontainergroup.yaml

**Expected behavior**
I expect to run the command without the error message and with YAML file as a result

**Environment summary**
root@Alexey-HP:~# az --version | head -1
azure-cli                         2.0.59

Microsoft Windows [Version 10.0.18346.1]
(c) 2018 Microsoft Corporation. All rights reserved.

**Additional context**

**Comment by tjprescott** [comment]
I have repro'd this and have created a fix in #8696.

**Comment by alexeyshishkin01** [comment]
which CLI version is it going to be available in?

**Comment by tjprescott** [comment]
2.0.60

**Comment by alexeyshishkin01** [comment]
when?
