### ISSUE TITLE
Doing Ctrl+C while running a command results in a call stack on commandline

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-cli#872]
We should catch this and have a clean error

**Comment by mayurid** [comment]
example: 
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\azure-cli\src\azure-cli\azure\cli\__main__.py", line 29, in <module>
    sys.exit(azure.cli.main.main(args))
  File "c:\azure-cli\src\azure-cli\azure\cli\main.py", line 34, in main
    cmd_result = APPLICATION.execute(args)
  File "c:\azure-cli\src\azure-cli-core\azure\cli\core\application.py", line 122, in execute
    event_data = {'result': results}
KeyboardInterrupt
Terminate batch job (Y/N)? y
