### ISSUE TITLE
az webapp up -n <name> fails when package.json contains "node"

### ISSUE THREAD

**Issue by NOtherDev** [Azure/azure-cli#8721]
**Describe the bug**
The code parsing `package.json` (File `"/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 206, in parse_node_version`) is looking for "node" string occurences, takes whatever is after it and strips non-numeric characters. When I had a script called `run:nodemon` defined as `nodemon whatever blah.blah.blah`, the procedure interpreted `nodemon whatever blah.blah.blah` as a potential node version string, removed non-numeric chars leaving ".." and tried to parse it as a number, which failed. It should be ignored instead of blocking the whole process.

**To Reproduce**
1) create an Node.js project with package.json containing the script `"run:nodemon": "nodemon whatever blah.blah.blah"`
1) run `az webapp up -n failure`

**Expected behavior**
The webapp is created.

**Environment summary**
```
azure-cli                         2.0.59

acr                                2.2.1
acs                               2.3.18
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.14
backup                             1.2.1
batch                              4.0.0
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.7
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.14
core                              2.0.59
cosmosdb                           0.2.8
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.3
extension                          0.2.3
feedback                           2.1.4
find                              0.2.13
hdinsight                          0.3.1
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.12
kusto                              0.2.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.3
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.7
redis                              0.4.1
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.11
role                               2.4.1
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.13
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.16

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/adambar/.azure/cliextensions'

Python (Darwin) 3.7.2 (default, Mar  7 2019, 09:54:18) 
[Clang 10.0.0 (clang-1000.11.45.5)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by panchagnula** [comment]
@NOtherDev  az webapp up has moved to core cli command & will be removed from extensions, please delete the webapp extensions & use the core command directly & let us know if you are still seeing this issue. https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up

**Comment by NOtherDev** [comment]
@panchagnula Not sure what do you mean, I'm not using any extension. I've installed the fresh CLI today using Homebrew on macOS, as it is recommended in the guide, and I have the newest version.

**Comment by panchagnula** [comment]
can you check if you have any existing webapp extension installed.
az extension list https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-list. if you don't have please check you are running the command from the folder where the code is on your local machine.

Can you run the command with --debug flag & share the error. thank you.

**Comment by NOtherDev** [comment]
No, I don't have any extensions installed.

```
➜  backend git:(master) ✗ az extension list
[]
```

We don't need --debug flag to see the stack trace, it fails immediately the hard way.

```
could not convert string to float: '...'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 2203, in create_deploy_webapp
    data = get_runtime_version_details(xxx, language)
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 63, in get_runtime_version_details
    version_detected = parse_node_version(file_path)[0]
  File "/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 206, in parse_node_version
    version_detected = sorted(data, key=float, reverse=True)
ValueError: could not convert string to float: '...'
```

**Comment by panchagnula** [comment]
Got it, thanks for sharing this. Can you share your package.json contents? its failing trying to parse the version.

**Comment by NOtherDev** [comment]
Yes, this is exactly what I've noted in the issue description...

Minimal repro package.json, also as mentioned above:
```
{
  "scripts": {
    "run:nodemon": "nodemon --config ./main.nodemon.json"
  }
}
```

**Comment by panchagnula** [comment]
Good news is we have a change coming up that should fix this, since we changed our parsing logic, you can try the latest DEV build if you want to try this, https://github.com/Azure/azure-cli#edge-builds

**Comment by panchagnula** [comment]
@NOtherDev - we believe this should be fixed with the latest version of CLI - please re-activate if this is not the case. Thank you!
