### ISSUE TITLE
az aks get-credentials --resource-group X --name Y AttributeError: 'CredentialResults' object has no attribute 'kubeconfigs'

### ISSUE THREAD

**Issue by greguz** [Azure/azure-cli#8735]
**Describe the bug**
I'm trying to get the kubeconfig for AKS by running `az aks get-credentials --resource-group X --name Y`, but I always get this error:

```
'CredentialResults' object has no attribute 'kubeconfigs'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 346, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 320, in execute
    result = cmd(params)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1587, in aks_get_credentials
    kubeconfig = credentialResults.kubeconfigs[0].value.decode(encoding='UTF-8')
AttributeError: 'CredentialResults' object has no attribute 'kubeconfigs'
```

Not sure why, plus i haven't found any info about this error.

**Expected behavior**
Mu kubeconfig `~/.kube/config` file will be populated.

**Environment summary**
Arch Linux 5.0.0-arch1-1-ARCH

Clean install of [AUR python-azure-cli](https://aur.archlinux.org/packages/python-azure-cli/)

`~/.kube/config` does **not** exists.

```
azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.52)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.6)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.8)
lab (0.1.4)
maps (0.3.2)
monitor (0.2.7)
network (2.2.10)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.11)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.9)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.6)
vm (2.2.9)

Python location '/usr/bin/python'
Extensions directory '/home/greguz/.azure/cliextensions'

Python (Linux) 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by adewaleo** [comment]
@mboersma can you take a look, seems like the object does not have or always have the desired field `kubeconfigs`.

**Comment by palma21** [comment]
Is this still happening on the latest CLI?

**Comment by SaurabhSharma-MSFT** [comment]
@bsiegel Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by greguz** [comment]
The bug seems to be resolved with the current version.
