### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'NoneType' and 'str' when sku=None

### ISSUE THREAD

**Issue by allieus** [Azure/azure-cli#8752]
**Describe the bug**

Exception point is below.

```python
        sku = sku | 'F1'
```

https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L2187

Exception

```
unsupported operand type(s) for |: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 54, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2195, in create_deploy_webapp
    sku = sku | 'F1'
TypeError: unsupported operand type(s) for |: 'NoneType' and 'str'
```

**To Reproduce**

* python webapp on azure webapp on linux
* When the requirements.txt file is missing.

```sh
az webapp up --name "name" --location "location"
```

**Expected behavior**

Unsupport NoneType and str in Python.

I suggest the following code.

```python
        sku = sku or 'F1'
```

**Environment summary**

Ubuntu Linux and Mac OS-X.
azure-cli : 2.0.60

**Additional context**

May I PR?

**Comment by adewaleo** [comment]
@allieus Thanks for raising this issue. Yes you may make a PR.

CC: @panchagnula

**Comment by panchagnula** [comment]
@allieus thanks for reporting & also suggesting the fix - got some folks reporting the same so starting a PR for this
