### ISSUE TITLE
az storage blob show fails with auth-mode login

### ISSUE THREAD

**Issue by cbrooksmsft** [Azure/azure-cli#8759]
**Describe the bug**
az storage blob show fails with auth-mode login

**To Reproduce**
1. grant user permissions in RBAC to read blobs in an account.
2. az login
3. $ az storage blob show --account-name account --container-name container --name testfile.txt --auth-mode login

**Expected behavior**
show blob properties

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build): apt get 
CLI version:  
azure-cli                         2.0.60
...
storage                            2.3.1
...
OS version: Python (Linux) 3.6.5 (default, Mar  7 2019, 19:49:28) [GCC 5.4.0 20160609] 

Shell Type: Bash on Windows  

**Additional context**
Error message:
$ az storage blob show --account-name cbrooksportaltest --container-name container --name testfile.txt --auth-mode login
show_blob() got an unexpected keyword argument 'token_credential'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 241, in new_handler
    first(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 758, in show_exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 237, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 180, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
TypeError: show_blob() got an unexpected keyword argument 'token_credential'

**Comment by cbrooksmsft** [comment]
@williexu

**Comment by williexu** [comment]
https://github.com/Azure/azure-cli/pull/8760 should fix this, I've also added testing for `blob show` in the oauth suite of tests.
