### ISSUE TITLE
[az kusto database create] Database.soft_delete_period_in_days can not be None

### ISSUE THREAD

**Issue by niktho** [Azure/azure-cli#8839]
**Issue**
Creating database in Azure Data Explorer using Azure CLI throws an error with the message Database.soft_delete_period_in_days can not be None. 

This can be related to the Microsoft Azure SDK for python has a breaking change related to _**Model DatabaseUpdate no longer has parameter soft_delete_period_in_days**_. Reference: https://pypi.org/project/azure-mgmt-kusto/

This is tested on three different computers with Azure CLI version 2.0.60

**How to reproduce**
Run the following command on a provisioned Azure Data Explorer resource 
`az kusto database create --cluster-name <myCusterName> -g <myRgName> --soft-delete-period P365D --hot-cache-period P120D -n <myKustoDatabase>`

**Stack trace**
Parameter 'Database.soft_delete_period_in_days' can not be None.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 452, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-kusto\azure\cli\command_modules\kusto\custom.py", line 152, in database_create
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\util.py", line 325, in sdk_no_wait
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-mgmt-kusto\azure\mgmt\kusto\operations\databases_operations.py", line 337, in create_or_update
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-mgmt-kusto\azure\mgmt\kusto\operations\databases_operations.py", line 279, in _create_or_update_initial
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\msrest\msrest\serialization.py", line 579, in body
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\msrest\msrest\serialization.py", line 221, in validate
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\msrest\msrest\serialization.py", line 662, in validate
msrest.exceptions.ValidationError: Parameter 'Database.soft_delete_period_in_days' can not be None.

**Comment by tjprescott** [comment]
@oflipman for comment

**Comment by oflipman** [comment]
@tjprescott
I created a new PR to fix the issue [:#8865](https://github.com/Azure/azure-cli/pull/8865)

**Comment by JasonRShaver** [comment]
please ignore me on this issue, testing reporting logic
