### ISSUE TITLE
Connecting to Azure via CLI not working

### ISSUE THREAD

**Issue by eriksaetren** [Azure/azure-cli#8872]
**Describe the bug**
I'm attempting to connect to my Linux web app via the Azure CLI, however, attempting to run the following command causes an error: 
az webapp remote-connection create --resource-group <resource-group-name> --name <web-app-name>

**Error Message:**
cannot import name 'SnapshotRecoveryRequest'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 251, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 266, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 143, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\commands.py", line 76, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 455, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 495, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\esaetren\.azure\cliextensions\webapp\azext_webapp\custom.py", line 10, in <module>
    from azure.mgmt.web.models import (AppServicePlan, SkuDescription, SnapshotRecoveryRequest, SnapshotRecoveryTarget)
ImportError: cannot import name 'SnapshotRecoveryRequest'

**To Reproduce**
Install Azure CLI.  Run the following command: az webapp remote-connection create

**Expected behavior**
Establish a connection to the web app container

**Environment summary**
OS: Windows 10 Pro
Azure CLI version: 2.0.60
Powershell running as admin
Powershell Version: 5.1.17134.590

**Comment by Nking92** [comment]
I think you are using an old version of the webapp extension. Let's check that and see if updating it fixes the issue.

Please check the version of the extension:
`az extension list`

The latest version is 0.2.16. If you need to update it, please use this command:
`az extension update -n webapp`

Let me know if that helps!

**Comment by Nking92** [comment]
@tjprescott I think we can close this issue.
