### ISSUE TITLE
 az container create fail

### ISSUE THREAD

**Issue by Sviatik** [Azure/azure-cli#8899]
Hello,

I have a ci/cd on azure devops which deploy artifact (Image) to azure container instance.From yesterday evening it started fail. In CD pipeline first of all i delete container group and then create new one. 

**To Reproduce**
```
az container delete \
	--resource-group $(resource.group) \
	--name my-app-$(env)
```
--------------------------------------
```
az container create \
	--resource-group $(resource.group) \
	--name my-app-$(env) \
	--location $(azure.location) \
	--image $(acr.name).azurecr.io/$(env):$(release.artifacts.ts-ap-dev.buildid) \
	--cpu 1 \
	--memory 1 \
	--vnet my-vnet \
	--vnet-address-prefix 10.0.0.0/24 \
	--subnet ts-admin-portal-$(env)-private-subnet \
	--subnet-address-prefix $(subnet.prefix) \
	--registry-login-server $(acr.name).azurecr.io \
	--registry-username $(acr.name) \
	--registry-password $(acr.password) \
	--environment-variables myvar=${someApiBaseUri} \
	--ports 80
```

**Expected behavior**
Expect to create new container instance with the next version of artifact 

**Environment summary**
Docker base image: 
```FROM mcr.microsoft.com/dotnet/core/aspnet:2.2```
Tested in azure devops on linux and localy. Failed in both cases.
``` $  az --version
azure-cli                         2.0.60 *

acr                                2.2.2 *
acs                               2.3.19 *
advisor                            2.0.0
ams                                0.4.2 *
appservice                        0.2.15 *
backup                             1.2.1 *
batch                              4.0.0
batchai                            0.4.7 *
billing                            0.2.0 *
botservice                         0.1.8 *
cdn                                0.2.0 *
cloud                              2.1.0 *
cognitiveservices                  0.2.4 *
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.60 *
cosmosdb                           0.2.8 *
dla                                0.2.4 *
dls                                0.1.8
dms                                0.1.2 *
eventgrid                          0.2.1 *
eventhubs                          0.3.4
extension                          0.2.3 *
feedback                           2.1.4
find                               0.3.0 *
hdinsight                          0.3.2
interactive                        0.4.1 *
iot                                0.3.6 *
iotcentral                         0.1.6
keyvault                          2.2.12 *
kusto                              0.2.0 *
lab                                0.1.5 *
maps                               0.3.3 *
monitor                           0.2.10 *
network                            2.3.4 *
nspkg                              3.0.3
policyinsights                     0.1.1 *
profile                            2.1.3 *
rdbms                              0.3.8 *
redis                              0.4.1 *
relay                              0.1.3 *
reservations                       0.4.1 *
resource                          2.1.11 *
role                               2.4.2 *
search                             0.1.1
security                           0.1.0 *
servicebus                         0.3.3 *
servicefabric                     0.1.14 *
signalr                            1.0.0
sql                                2.1.9 *
sqlvm                              0.1.0 *
storage                            2.3.1 *
telemetry                          1.0.1 *
vm                                2.2.16 *

Python location '/opt/az/bin/python3'

Python (Linux) 3.6.5 (default, Mar  7 2019, 19:46:51)
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal


You have 43 updates available. Consider updating your CLI installation.
```

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
output from azure devops
```
2019-03-28T07:43:23.7109131Z [command]/usr/local/bin/az account set --subscription 9#############
2019-03-28T07:43:23.8930147Z [command]/bin/bash /vsts/agent/_work/_temp/azureclitaskscript1553759000817.sh
2019-03-28T07:46:28.3035062Z ERROR: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9#############/resourceGroups/my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-container-stage?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))
2019-03-28T07:46:28.3037639Z Traceback (most recent call last):
2019-03-28T07:46:28.3039834Z   File "/usr/local/lib/python2.7/dist-packages/knack/cli.py", line 206, in invoke
2019-03-28T07:46:28.3040746Z     cmd_result = self.invocation.execute(args)
2019-03-28T07:46:28.3042614Z   File "/usr/local/lib/python2.7/dist-packages/azure/cli/core/commands/__init__.py", line 328, in execute
2019-03-28T07:46:28.3043411Z     raise ex
2019-03-28T07:46:28.3046796Z ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/9#############/resourceGroups/my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-container-stage?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))
2019-03-28T07:46:28.3716607Z [command]/usr/local/bin/az account clear
2019-03-28T07:46:28.9482659Z ##[error]Script failed with error: Error: /bin/bash failed with return code: 1
2019-03-28T07:46:28.9557582Z ##[section]Finishing: Create container instance
```
.
Output from local machine:
```
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/#################-a434-d6aece020ebc/resourceGroups/ts-my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-dev?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/#################-a434-d6aece020ebc/resourceGroups/ts-my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-dev?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/#################-a434-d6aece020ebc/resourceGroups/ts-my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-dev?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 221, in create_container
    name, cgroup)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 325, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 337, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerinstance/operations/container_groups_operations.py", line 284, in _create_or_update_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/#################-a434-d6aece020ebc/resourceGroups/ts-my-rg/providers/Microsoft.ContainerInstance/containerGroups/ts-my-dev?api-version=2018-10-01 (Caused by ResponseError('too many 503 error responses',))
```

**Comment by Sviatik** [comment]
Also i found message in activity log
```
    "properties": {
        "statusCode": "ServiceUnavailable",
        "serviceRequestId": "westeurope:a351b0c6-6f1d-4725-8e15-3d4344e3e2c4",
        "statusMessage": "{\"error\":{\"code\":\"ServerTimeout\",\"message\":\"The request timed out. The tracking activity id is 'a351b0c6-6f1d-4725-8e15-3d4344e3e2c4', the correlation id is '298003c2-9066-4967-81ce-70a16d287139'.\"}}"
    },
```

**Comment by Sviatik** [comment]
Seems to be the issue was due azure failed.
They reported it on the status page.
