### ISSUE TITLE
az ad sp create-for-rbac --years broken

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-cli#8903]
**Describe the bug**
Specifying `--years` in the command `az ad sp create-for-rbac` makes the command fail with the following error on version 2.0.61:

```
The command failed with an unexpected error. Here is the traceback:

Non-integer years and months are ambiguous and not currently supported.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 351, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 409, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 400, in _run_job

  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-role\azure\cli\command_modules\role\commands.py", line 69, in graph_err_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job

  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__

  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-role\azure\cli\command_modules\role\custom.py", line 1211, in create_service_principal_for_rbac
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\python-dateutil\dateutil\relativedelta.py", line 173, in __init__
ValueError: Non-integer years and months are ambiguous and not currently supported.
```

**To Reproduce**
`az ad sp create-for-rbac --name "http://test-sp" --years 10`

**Expected behavior**
It doesn't fail.

**Environment summary**
azure-cli version 2.0.61

**Additional context**
This command worked as of version 2.0.57

**Comment by yugangw-msft** [comment]
@kyschouv, sorry for the breaking which I have submitted a PR to fix it. Meanwhile, can you please use `az ad sp credential reset  --end-date` for workaround before we release the change on May 9?

**Comment by mariojacobo** [comment]
+1, seeing same issue: 

az ad sp create-for-rbac -n test-group --years 99

The command failed with an unexpected error. Here is the traceback:

Non-integer years and months are ambiguous and not currently supported.
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
cmd_result = self.invocation.execute(args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 351, in execute
raise ex
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 409, in _run_jobs_serially
results.append(self._run_job(expanded_arg, cmd_copy))
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 400, in _run_job
cmd_copy.exception_handler(ex)
File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
raise ex
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 379, in _run_job
result = cmd_copy(params)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/init.py", line 171, in call
return self.handler(*args, **kwargs)
File "/opt/az/lib/python3.6/site-packages/azure/cli/core/init.py", line 451, in default_command_handler
return op(**command_args)
File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 1211, in create_service_principal_for_rbac
app_end_date = app_start_date + relativedelta(years=years or 1)
File "/opt/az/lib/python3.6/site-packages/dateutil/relativedelta.py", line 173, in init
raise ValueError("Non-integer years and months are "
ValueError: Non-integer years and months are ambiguous and not currently supported.

**Comment by kyschouv** [comment]
Thanks. I think I can workaround by just staying on an older version until the fix is released.
