### ISSUE TITLE
azure-cli-iot-ext 'No keys found for policy iothubowner of IoT Hub'

### ISSUE THREAD

**Issue by szmoon** [Azure/azure-cli#8926]
**Describe the bug**
I'm using a freshly created Azure account and am following this tutorial for IoT Hub and Android Things: [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-how-to-android-things](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-how-to-android-things)

I'm able to execute the first line of the following code using the Azure Cloud Shell (azure-cli version 2.0.61), but unable to execute the second line (I replaced the "YourIoTHubName" with my own hub name) :
```
az extension add --name azure-cli-iot-ext
az iot hub device-identity create --hub-name YourIoTHubName --device-id MyAndroidThingsDevice
```

When I execute the second line above, I get this error in red:

`No keys found for policy iothubowner of IoT Hub szmoon-android-iot-tutorial.`

I searched around and found this page ( [https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-use-metrics-and-diags](https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-use-metrics-and-diags) ) that recommends updating the extension if you run into that error. I assume that my fresh install is up to date, but I tried running the following update anyway:
`az extension update --name azure-cli-iot-ext`

When I run it, I get this error:
```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 409, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 402, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/operations.py", line 258, in update_extension
    cur_version = ext.get_version()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/__init__.py", line 115, in get_version
    return self.metadata.get('version')
AttributeError: 'NoneType' object has no attribute 'get'
```

When searching for a solution, I saw that some others were running into a similar issue in the past and it was caused by specific versions of the azure-cli-iot-ext: [https://github.com/Azure/azure-cli/issues/6969](https://github.com/Azure/azure-cli/issues/6969)
[https://github.com/Azure/azure-iot-cli-extension/issues/32](https://github.com/Azure/azure-iot-cli-extension/issues/32)
Is something similar happening here?

**Comment by tjprescott** [comment]
Relocating to the azure-cli-extensions repo since this deals with the IoT extension.
