### ISSUE TITLE
Unexpected error "JSONDecodeError("Expecting value", s, err.value) from None" using "az webapp deployment source config-zip"

### ISSUE THREAD

**Issue by gagnadref** [Azure/azure-cli#8939]
I'm using the following command to deploy my app to Azure App Service : 

``` 
az webapp deployment source config-zip --name {my-app} --resource-group {my-resource-group} --src {my-zip-file} --verbose
```

From this morning, I get the following error : 
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 448, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 289, in enable_zip_deploy
    response = _check_zip_deployment_status(deployment_status_url, authorization, timeout)
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 2098, in _check_zip_deployment_status
    res_dict = response.json()
  File "/usr/local/Cellar/azure-cli/2.0.58/libexec/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Looking at the source code, I realized that it was probably due to this url: `https://{my-app}.scm.azurewebsites.net/api/deployments/latest`, which indeed is not returning anything (I get a 504 Timeout).

Any recommendation?

**Comment by panchagnula** [comment]
Looks like this API is not returning a JSON https://{my-app}.scm.azurewebsites.net/api/deployments/latest which caused the command to fail. Are you still seeing this?  What happens when you re-try?
Do you have contributor permissions on the APP that you are trying to deploy to?  Try navigating to scm site directly https://{my-app}.scm.azurewebsites.net/ & see if this loads, once it loads you should see the a 'Deployments" link click that & check the response, a status value of '4' indicates success, & 3 indicates failure.

**Comment by panchagnula** [comment]
Closing since we haven't heard back on this issue for a while now. Please file new issue if this is still persists with the latest CLI version
