### ISSUE TITLE
acr says "Please verify if docker is installed" despite docker installed and running

### ISSUE THREAD

**Issue by dluc** [Azure/azure-cli#8960]
**Describe the bug**
I'm attempting to authenticate to my ACR, following [these instructions](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli) and when I execute `az acr login --name myregistry` I get an error suggesting Docker is not installed, which is incorrect:

```
# az acr login --name xxxxxx.azurecr.io
Please verify if docker is installed.
``` 

Both `az` and `docker` are up to date.

I'd be fine using `docker login xxxxxx.azurecr.io` but I can't get that to work with my Azure portal credentials either (I'm a subscription owner, and I've tried adding _ACRPull_ role just in case).

**Environment summary**
OS: MacOS 10.14.3 (Mojave)
Docker: Docker Desktop 2.0.0.3 stable, engine 18.09.2 
az install method: homebrew
azure-cli: 2.0.61
acr: 2.2.3
Python: (Linux) 3.6.4
Shell: GNU bash 5.0.3(1)-release (x86_64-apple-darwin18.2.0)

```
# which az
/usr/local/bin/az
```

```
# docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: IHAE:LXG4:QLOS:76VE:XXAD:PNST:NDZW:GS6C:OHVT:5CTJ:6TD2:237Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 54
 System Time: 2019-04-02T19:35:33.177404Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by djyou** [comment]
@dluc Could you provide a debug trace `az acr login -n myregistry --debug`, or send it to `acrsup@microsoft.com`? Thanks.

**Comment by yfried** [comment]
Hi, I'm hitting the same problem (`azure-cli` installed via snap)

**Comment by tjprescott** [comment]
@yfried the snap package of Azure CLI is incredibly outdated (19 January 2018). I would highly recommend installing via one of the Linux methods outlined here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.

cc/ @marstr

**Comment by yfried** [comment]
Thank you. Already figured this out. Is there any chance you guys can make
the snap package work? Snap is extremely convenient.

**Comment by yugangw-msft** [comment]
@dluc, we are closing this issue, but feel free to reactivate if you can provide a debug trace `az acr login -n myregistry --debug`

**Comment by gmfun** [comment]
```
Command arguments: ['acr', 'login', '--name', 'volterra', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f0e41ec1d90>, <function OutputProducer.on_global_arguments at 0x7f0e41aebb70>, <function CLIQuery.on_global_arguments at 0x7f0e41ed87b8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7f0e41ec1e18>]
Installed command modules ['acr', 'acs', 'advisor', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.003 seconds.
Loaded module 'acs' in 0.003 seconds.
Loaded module 'advisor' in 0.002 seconds.
Loaded module 'appservice' in 0.007 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.017 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.455 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.003 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'dla' in 0.087 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'lab' in 0.148 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.029 seconds.
Loaded module 'profile' in 0.010 seconds.
Loaded module 'rdbms' in 0.004 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.003 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'sql' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.077 seconds.
Loaded module 'vm' in 0.035 seconds.
Loaded all modules in 0.948 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/gauravmukherjee/snap/azure-cli/7/.azure/cliextensions'
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7f0e419e8840>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f0e41f49620>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f0e41aebbf8>, <function CLIQuery.handle_query_parameter at 0x7f0e41ed8840>]
Getting management service client client_type=ContainerRegistryManagementClient
```

@yugangw-msft Here is --debug trace. I am also using snap package for docker

**Comment by julisch94** [comment]
I get the same error inside my Ubuntu WSL 20.04 LTS on Win10. What am I missing?

Docker version 20.10.10:
```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

az version: 
```
{
  "azure-cli": "2.24.0",
  "azure-cli-core": "2.24.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

I am able to run `docker` inside my WSL. I even have a container running right now.

Still, I get this when running `az acr login -n my-registry --debug`

```
DEBUG: cli.knack.cli: Command arguments: ['acr', 'login', '-n', 'my-registry', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01FB4190>, <function OutputProducer.on_global_arguments at 0x02130028>, <function CLIQuery.on_global_arguments at 0x02146BF8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: acr                       0.007        27       113
DEBUG: cli.azure.cli.core: Total (1)                 0.007        27       113
DEBUG: cli.azure.cli.core: Loaded 27 groups, 113 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : acr login
DEBUG: cli.azure.cli.core: Command table: acr login
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03CEF0B8>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\julian.schmidt\.azure\commands\2021-11-11.11-01-32.acr_login.22388.log'.
INFO: az_command_data_logger: command args: acr login -n {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03D35148>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x03D457C0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03D45808>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03D45898>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02130070>, <function CLIQuery.handle_query_parameter at 0x02146C40>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x03D351D8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03D45850>]
DEBUG: cli.azure.cli.command_modules.acr.custom: Could not run 'docker' command. Exception: [WinError 2] The system cannot find the file specified
DEBUG: cli.azure.cli.command_modules.acr.custom: Could not run 'docker.exe' command. Exception: [WinError 2] The system cannot find the file specified
WARNING: cli.azure.cli.command_modules.acr.custom: You may want to use 'az acr login -n my-registry --expose-token' to get an access token, which does not require Docker to be installed.
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 315, in get_docker_command
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 322, in get_docker_command
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 249, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 246, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 328, in get_docker_command
knack.util.CLIError: An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.

ERROR: cli.azure.cli.core.azclierror: An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
ERROR: az_command_data_logger: An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03CEF1D8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 0.429 seconds (init: 0.181, invoke: 0.248)
INFO: telemetry.save: Save telemetry record of length 3025 in cache
WARNING: telemetry.check: Negative: The C:\Users\julian.schmidt\.azure\telemetry.txt was modified at 2021-11-11 10:59:33.449259, which in less than 600.000000 s
```

**Comment by julisch94** [comment]
To help others with the same issue:

I found my issue. `which az` showed that I was using the Azure CLI of my Windows host system.

Uninstalling Azure CLI on Windows and installing it inside my WSL fixed my issue.

**Comment by davehouser1** [comment]
Just to add to @yonzhan's post. You don't need to remove az. I found when I installed with the following instructions, it adjusted my path so the WSL instance used the local version before the Windows:

https://www.harveyramer.com/article/azure-cli-windows-11-linux-subsystem/
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions

**Comment by Kosaln** [comment]
This issue is because WSL is trying to use the AZ CLI from the base machine and not WSL. Try to install AZ CLI on WSL and its should work for you!!
