### ISSUE TITLE
az servicebus namespace authorization-rule breaks

### ISSUE THREAD

**Issue by mathwro** [Azure/azure-cli#8963]
**Describe the bug**
`az servicebus namespace authorization-rule keys list` breaks the tool. im getting a typeError

**To Reproduce**
Create an servicebus namespace and an authorization rule.
In Powershell now do `az servicebus namespace authorization-rule keys list` with the nessecary parameters. none additional parameters given.

**Expected behavior**
I expect a list of my authorization keys.

**Environment summary**
azure-cli 2.0.61 (Installed from chocolatey)

**Additional context**
```
az servicebus namespace authorization-rule keys list --resource-group BusTest2 --namespace-name mwifbustest2 --name "SendRead" --query primaryConnectionString
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 351, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 409, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 402, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-mgmt-servicebus\azure\mgmt\servicebus\operations\namespaces_operations.py", line 870, in list_keys
azure.mgmt.servicebus.models._models.ErrorResponseException: Operation returned an invalid status code 'Not Found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli\azure\cli\__main__.py", line 39, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli\azure\cli\__main__.py", line 29, in cli_main
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\knack\knack\cli.py", line 218, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\__init__.py", line 96, in exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\util.py", line 35, in handle_exception
TypeError: string indices must be integers
```

**Comment by mathwro** [comment]
After some futher testing, it looks like it only crashing upon requesting the premade authorization key, "RootManagedAccessKey". 

Authorization rules i have made my self, even with the same access (Read, Write, Manage) currently gives me the expected results

**Comment by v-Ajnava** [comment]
@mathwro , the default one is "RootManageSharedAccessKey" we tried to repo and the default one works fine, can you please try again with default name as "RootManageSharedAccessKey". 

please let us know it works or not. 

we also tried with below commands it works fine. Note we used the Latest CLI Version : 2.0.67

**Comment by mathwro** [comment]
@v-Ajnava I tried it with the default "RootManageSharedAccessKey" as well.

I did however just do some testing before and after of bumping my version of the Azure CLI just now. It seems to have been fixed in one of the latest versions as it is now working as expected in 2.0.67.

Much appreciated, thanks!

**Comment by v-Ajnava** [comment]
@mathwro, closing this issue, please let us know if have any questions.
