### ISSUE TITLE
KeyError exception when deleting resource that has a delete lock on it

### ISSUE THREAD

**Issue by judyanndixon** [Azure/azure-cli#9007]
Using the lock feature on resources and resource group to prevent accidentally deleting resource or resource group.  

Using az cli attempt to delete a resource with a lock at either the resource or resource group level and get this KeyError exception

To reproduce

Create a resource with a lock
Attempt to delete the resource using the az cli 

Receive this exception

 ERROR: 'subscription'
2019-04-05T13:50:49.8499564Z Traceback (most recent call last):
2019-04-05T13:50:49.8500366Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2019-04-05T13:50:49.8500578Z     cmd_result = self.invocation.execute(args)
2019-04-05T13:50:49.8501373Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in execute
2019-04-05T13:50:49.8501640Z     raise ex
2019-04-05T13:50:49.8502012Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 386, in _run_jobs_serially
2019-04-05T13:50:49.8502150Z     results.append(self._run_job(expanded_arg, cmd_copy))
2019-04-05T13:50:49.8502453Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 379, in _run_job
2019-04-05T13:50:49.8502586Z     six.reraise(*sys.exc_info())
2019-04-05T13:50:49.8502853Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2019-04-05T13:50:49.8502964Z     raise value
2019-04-05T13:50:49.8503256Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 356, in _run_job
2019-04-05T13:50:49.8503371Z     result = cmd_copy(params)
2019-04-05T13:50:49.8503665Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
2019-04-05T13:50:49.8503794Z     return self.handler(*args, **kwargs)
2019-04-05T13:50:49.8504101Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 452, in default_command_handler
2019-04-05T13:50:49.8504216Z     return op(**command_args)
2019-04-05T13:50:49.8504528Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 875, in delete_resource
2019-04-05T13:50:49.8504653Z     error_msg_builder.append(resource_dict_to_id(**id_dict))
2019-04-05T13:50:49.8504953Z   File "/opt/az/lib/python3.6/site-packages/msrestazure/tools.py", line 206, in resource_id
2019-04-05T13:50:49.8505259Z     rid_builder = ['/subscriptions/{subscription}'.format(**kwargs)]
2019-04-05T13:50:49.8505494Z KeyError: 'subscription'

Expected this type of error instead:
ERROR: The scope '/subscriptions/dc509b1b-e8fe-489c-a59e-357794ea9a03/resourcegroups/NewVN' cannot perform delete operation because following scope(s) are locked: '/subscriptions/dc509b1b-e8fe-489c-a59e-357794ea9a03/resourceGroups/NewVN'. Please remove the lock and try again.

I am running the az cli command in a shell script within an Azure DevOps az cli task.

019-04-05T13:50:09.7114019Z ##[section]Starting: Azure CLI $(System.DefaultWorkingDirectory)/_CleanUpSandbox/CleanUpSub.sh
2019-04-05T13:50:09.7390054Z ==============================================================================
2019-04-05T13:50:09.7390351Z Task         : Azure CLI
2019-04-05T13:50:09.7390447Z Description  : Run Azure CLI commands against an Azure subscription in a Shell script when runnning on Linux agent or Batch script when running on Windows agent.
2019-04-05T13:50:09.7390578Z Version      : 1.149.0
2019-04-05T13:50:09.7390640Z Author       : Microsoft Corporation
2019-04-05T13:50:09.7390773Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=827160)
2019-04-05T13:50:09.7390854Z ==============================================================================
2019-04-05T13:50:16.8550811Z [command]/usr/bin/az --version
2019-04-05T13:50:33.1062366Z WARNING: You have 46 updates available. Consider updating your CLI installation.
2019-04-05T13:50:33.1063166Z azure-cli                         2.0.59 *
2019-04-05T13:50:33.1370578Z 
2019-04-05T13:50:33.1375664Z acr                                2.2.1 *
2019-04-05T13:50:33.1376126Z acs                               2.3.18 *
2019-04-05T13:50:33.1376310Z advisor                            2.0.0
2019-04-05T13:50:33.1376438Z ams                                0.4.2 *
2019-04-05T13:50:33.1376556Z appservice                        0.2.14 *
2019-04-05T13:50:33.1376665Z backup                             1.2.1 *
2019-04-05T13:50:33.1376729Z batch                              4.0.0
2019-04-05T13:50:33.1376830Z batchai                            0.4.7 *
2019-04-05T13:50:33.1376936Z billing                            0.2.0 *
2019-04-05T13:50:33.1377042Z botservice                         0.1.7 *
2019-04-05T13:50:33.1377106Z cdn                                0.2.0 *
2019-04-05T13:50:33.1377167Z cloud                              2.1.0 *
2019-04-05T13:50:33.1377269Z cognitiveservices                  0.2.4 *
2019-04-05T13:50:33.1378000Z command-modules-nspkg               2.0.2
2019-04-05T13:50:33.1378137Z configure                         2.0.20
2019-04-05T13:50:33.1378197Z consumption                        0.4.2
2019-04-05T13:50:33.1378296Z container                         0.3.14 *
2019-04-05T13:50:33.1378356Z core                              2.0.59 *
2019-04-05T13:50:33.1378571Z cosmosdb                           0.2.8 *
2019-04-05T13:50:33.1378634Z dla                                0.2.4 *
2019-04-05T13:50:33.1378733Z dls                                0.1.8
2019-04-05T13:50:33.1378795Z dms                                0.1.2 *
2019-04-05T13:50:33.1378865Z eventgrid                          0.2.1 *
2019-04-05T13:50:33.1378963Z eventhubs                          0.3.3 *
2019-04-05T13:50:33.1379024Z extension                          0.2.3 *
2019-04-05T13:50:33.1379122Z feedback                           2.1.4
2019-04-05T13:50:33.1379183Z find                              0.2.13 *
2019-04-05T13:50:33.1379282Z hdinsight                          0.3.1 *
2019-04-05T13:50:33.1379406Z interactive                        0.4.1 *
2019-04-05T13:50:33.1379770Z iot                                0.3.6 *
2019-04-05T13:50:33.1379839Z iotcentral                         0.1.6
2019-04-05T13:50:33.1379942Z keyvault                          2.2.12 *
2019-04-05T13:50:33.1380272Z kusto                              0.2.0 *
2019-04-05T13:50:33.1380384Z lab                                0.1.5 *
2019-04-05T13:50:33.1380445Z maps                               0.3.3 *
2019-04-05T13:50:33.1380546Z monitor                           0.2.10 *
2019-04-05T13:50:33.1380872Z network                            2.3.3 *
2019-04-05T13:50:33.1380974Z nspkg                              3.0.3
2019-04-05T13:50:33.1381038Z policyinsights                     0.1.1 *
2019-04-05T13:50:33.1381099Z profile                            2.1.3 *
2019-04-05T13:50:33.1381200Z rdbms                              0.3.7 *
2019-04-05T13:50:33.1381263Z redis                              0.4.1 *
2019-04-05T13:50:33.1381362Z relay                              0.1.3 *
2019-04-05T13:50:33.1381558Z reservations                       0.4.1 *
2019-04-05T13:50:33.1381660Z resource                          2.1.11 *
2019-04-05T13:50:33.1381724Z role                               2.4.1 *
2019-04-05T13:50:33.1381823Z search                             0.1.1
2019-04-05T13:50:33.1381888Z security                           0.1.0 *
2019-04-05T13:50:33.1381949Z servicebus                         0.3.3 *
2019-04-05T13:50:33.1382051Z servicefabric                     0.1.13 *
2019-04-05T13:50:33.1382123Z signalr                            1.0.0
2019-04-05T13:50:33.1382222Z sql                                2.1.9 *
2019-04-05T13:50:33.1382283Z sqlvm                              0.1.0 *
2019-04-05T13:50:33.1382381Z storage                            2.3.1 *
2019-04-05T13:50:33.1382443Z telemetry                          1.0.1 *
2019-04-05T13:50:33.1382541Z vm                                2.2.16 *
2019-04-05T13:50:33.1382583Z 
2019-04-05T13:50:33.1382958Z Python location '/opt/az/bin/python3'
2019-04-05T13:50:33.1383262Z Extensions directory '/home/vsts/.azure/cliextensions'
2019-04-05T13:50:33.1383315Z 
2019-04-05T13:50:33.1383374Z Python (Linux) 3.6.5 (default, Feb 21 2019, 23:58:07) 
2019-04-05T13:50:33.1383478Z [GCC 5.4.0 20160609]
2019-04-05T13:50:33.1383516Z 
2019-04-05T13:50:33.1383613Z Legal docs and information: aka.ms/AzureCliLegal
2019-04-05T13:50:33.1383656Z 
2019-04-05T13:50:33.1383688Z 
2019-04-05T13:50:33.1384083Z Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
2019-04-05T13:50:33.1384548Z Setting active cloud to: AzureCloud
2019-04-05T13:50:33.1386440Z [command]/usr/bin/az cloud set -n AzureCloud

I get the same results running in Azure cloud shell as well.

judy@Azure:~/clouddrive/temp$ az --version
azure-cli                         2.0.61

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

Python location '/opt/az/bin/python3'
Extensions directory '/home/judy/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar 22 2019, 17:40:11)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

My guess is this is the same issue as [4653](https://github.com/Azure/azure-cli/issues/4653)
This [fix](https://github.com/Azure/azure-cli/pull/4661/files/559675e8a7190e73d9ee608fdfda630b374bd85e)

Needs to be made when building the error message below.

for _, id_dict in to_be_deleted:
            logger.debug(id_dict['exception'])
            error_msg_builder.append(resource_dict_to_id(**id_dict))

**Comment by tjprescott** [comment]
This occurs when using `az resource delete ...`. Strongly typed delete commands do not do this.
