### ISSUE TITLE
az interactive stopped working after 2.0.62 update

### ISSUE THREAD

**Issue by DMKmod** [Azure/azure-cli#9044]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

cannot import name 'DEFAULTS_SECTION'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-interactive\azure\cli\command_modules\interactive\custom.py", line 31, in start_shell
  File "C:\Users\dmpo\.azure\cliextensions\interactive\azext_interactive\__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "C:\Users\dmpo\.azure\cliextensions\interactive\azext_interactive\azclishell\app.py", line 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az interactive`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

Extensions:
interactive                        0.4.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dmpo\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

```

**Comment by tjprescott** [comment]
You have to update your extension. A new version was released compatible with 2.0.62.
