### ISSUE TITLE
please decide which characters that are valid when naming items in Azure

### ISSUE THREAD

**Issue by joakimrapp** [Azure/azure-cli#9048]
It is a mess naming stuff in Azure in general because you are not consistent through out the platform which characters are valid. Some times dash is allowed, some times it is not, the same with underscore.

It would be so much more pleasant to work with Azure if the same rules applies everywhere in Azure.

Just as an example, a resource group can be named with dashes, e.g. xxx-yyy-zzz, while a container registry cannot "Parameter 'registry_name' must conform to the following pattern: '^[a-zA-Z0-9]*$'."

I understand that different teams has developed different parts of Azure, but this is one of the first things you struggle with when using Azure for the first time. In our case we are still evaluating with cloud platform to use and every frustration influences our future decision.

Best Regards Joakim Rapp

## Describe the bug

**Command Name**
`az acr create`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

Parameter 'registry_name' must conform to the following pattern: '^[a-zA-Z0-9]*$'.Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acr/custom.py", line 104, in acr_create
    return client.create(resource_group_name, registry_name, registry)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 351, in create
    **operation_config
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 276, in _create_initial
    'registryName': self._serialize.url("registry_name", registry_name, 'str', max_length=50, min_length=5, pattern=r'^[a-zA-Z0-9]*$')
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 592, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 672, in validate
    raise ValidationError(key, name, value)
msrest.exceptions.ValidationError: Parameter 'registry_name' must conform to the following pattern: '^[a-zA-Z0-9]*$'.
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az acr create --resource-group {} --name {} --sku {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli                         2.0.62

```

**Comment by tjprescott** [comment]
Thanks for the feedback @joakimrapp. From the CLI side, there isn't anything we can do when it comes to the service-side restrictions on naming. However, this should not have printed a stack trace, so we will look at fixing our exception handling to ensure that this error at least displays in less frustrating way.

**Comment by tjprescott** [comment]
The stack trace has been fixed and will be in the upcoming release.
