### ISSUE TITLE
webapp update should validate the RG & Webapp exists before trying to run an update

### ISSUE THREAD

**Issue by jb289** [Azure/azure-cli#9052]
**Describe the bug**
The webapp update CLI command always returns ERROR - 'NoneType' object has no attribute 'kind'
when resource name does not exist.

**To Reproduce**
Example:

------------------------------
Where resource name 'waName' does not exist
```
az webapp update --resource-group rgName --name waName --client-affinity-enabled false

The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 512, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 362, in update_webapp
    if 'function' in instance.kind:
AttributeError: 'NoneType' object has no attribute 'kind'

To open an issue, please run: 'az feedback'
```
-----------------------------------

This happens on the PS cloud shell and PS locally (and on DevOps build servers). 

**Expected behavior**
A message that the resource is not found.

**Environment summary**
az cli version: 2.0.62

**Additional context**

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/9323 fixes this
