### ISSUE TITLE
az storage account check-name

### ISSUE THREAD

**Issue by varveti** [Azure/azure-cli#9061]
I am seeing issue when I try check if the storage account name exists or not with the following command
 az storage account check-name --name ryess

Error:
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/7d24b5bf-ffd4-4417-a35a-fd302310ed51/providers/Microsoft.Storage/checkNameAvailability?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))
Traceback (most recent call last):
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 342, in execute
    six.reraise(*sys.exc_info())
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 315, in execute
    result = cmd(params)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 175, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 349, in default_command_handler
    result = op(**command_args)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/mgmt/storage/v2017_10_01/operations/storage_accounts_operations.py", line 88, in check_name_availability
    request, header_parameters, body_content, **operation_config)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/msrest/service_client.py", line 231, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/7d24b5bf-ffd4-4417-a35a-fd302310ed51/providers/Microsoft.Storage/checkNameAvailability?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))

Az Verison: 
az --version
azure-cli (2.0.28)

acr (2.0.21)
acs (2.0.27)
advisor (0.1.2)
appservice (0.1.28)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.28)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.19)
lab (0.0.17)
monitor (0.1.2)
network (2.0.24)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.24)
role (2.0.20)
servicefabric (0.0.10)
sql (2.0.22)
storage (2.0.26)
vm (2.0.27)

Python location '/Users/varveti/lib/azure-cli/bin/python'
Extensions directory '/Users/varveti/.azure/cliextensions'

Python (Darwin) 2.7.10 (default, Feb 22 2019, 21:17:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]

Legal docs and information: aka.ms/AzureCliLegal

Please let me know how to resolve this.

**Comment by varveti** [comment]
I am seeing issue when I try check if the storage account name exists or not with the following command
 az storage account check-name --name ryess

Error:
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/7d24b5bf-ffd4-4417-a35a-fd302310ed51/providers/Microsoft.Storage/checkNameAvailability?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))
Traceback (most recent call last):
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 342, in execute
    six.reraise(*sys.exc_info())
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 315, in execute
    result = cmd(params)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 175, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 349, in default_command_handler
    result = op(**command_args)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/azure/mgmt/storage/v2017_10_01/operations/storage_accounts_operations.py", line 88, in check_name_availability
    request, header_parameters, body_content, **operation_config)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/msrest/service_client.py", line 231, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/Users/varveti/lib/azure-cli/lib/python2.7/site-packages/msrest/exceptions.py", line 48, in raise_with_traceback
    raise error
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/7d24b5bf-ffd4-4417-a35a-fd302310ed51/providers/Microsoft.Storage/checkNameAvailability?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))

Please let me know how to resolve this

**Comment by limingu** [comment]
@varveti, your az version is azure-cli (2.0.28). It is old and it is using /subscriptions/7d24b5bf-ffd4-4417-a35a-fd302310ed51/providers/Microsoft.Storage/checkNameAvailability?api-version=2017-10-01

We have newer CLI version and the Azure api version is also upgraded.

Can you upgrade your azure-cli and try again? Thanks.

**Comment by limingu** [comment]
Please reopen it if you have more details about the repro as a newer CLI version.
