### ISSUE TITLE
az aks install-cli failed

### ISSUE THREAD

**Issue by willierowe** [Azure/azure-cli#9066]
The command failed with an unexpected error. Here is the traceback:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.
c:841)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 964, in send
    self.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", li
ne 1400, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ssl.py", line 407,
in wrap_socket
    _context=self, _session=session)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ssl.py", line 814,
in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ssl.py", line 1068,
 in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\ssl.py", line 689,
in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cl
i.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", l
ine 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core
\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-acs\
azure\cli\command_modules\acs\custom.py", line 302, in k8s_install_cli
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py",
 line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certifica
te verify failed (_ssl.c:841)>

**Comment by brendandburns** [comment]
@tjprescott this should be closed as can not reproduce. The command works generally, I suspect some sort of network mis-configuration.

**Comment by mingxhzhu** [comment]
Still failing for me. Company intercepts SSL certificate, how can I turn verification off?
