### ISSUE TITLE
exception when setting a new container version for a functionapp

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-cli#9069]
## Describe the bug

When trying to push a new version of an image to an azure function, I encountered the following exception. 

**Command Name**
`az functionapp config container set`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'reserved'Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 894, in update_container_settings_functionapp
    multicontainer_config_file=None, slot=slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 869, in update_container_settings
    _add_fx_version(cmd, resource_group_name, name, docker_custom_image_name, slot)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 626, in _add_fx_version
    linux_fx = fx_version if web_app.reserved else None
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az functionapp config container set --docker-custom-image-name {} --name {} --resource-group {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli                         2.0.62

Extensions:
interactive                        0.4.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/<username>/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Apr  4 2019, 22:51:56) 
[GCC 7.3.0]

```

**Comment by panchagnula** [comment]
@ahmedelnably , @ankitkumarr can you look at this one?

**Comment by jubobs** [comment]
Same here... Very annoying...

**Comment by brandonmbanks** [comment]
Any news on this issue?

**Comment by RachelChen3** [comment]
I got the same problem .... Any updates?

**Comment by RakeshMohanMSFT** [comment]
This is working now. Please upgrade to latest version of az cli [2.40.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.
![image](https://user-images.githubusercontent.com/49954584/191164170-e3f39faf-d4af-4b4f-b5f9-1d37945823a0.png)
