### ISSUE TITLE
Incompatible name space package requirements (`azure-mgmt-nspkg`)

### ISSUE THREAD

**Issue by stevengum** [Azure/azure-cli#9073]
**Describe the bug**
Incompatible name space package requirements (`azure-mgmt-nspkg`) when running dev_setup script.

**To Reproduce**
1. Clone repo
2. Create new virtual environment
3. Activate virtual environment
4. Run `scripts/dev_setup.py`
5. Receive incompatible requirements message (See below screenshot)

![4-11-dev_setup py](https://user-images.githubusercontent.com/14935595/55980993-9940b200-5c4a-11e9-9742-506eb39aee63.jpg)

@tjprescott, @williexu

**Additional context**
Python 3.7.0

Output of `pip freeze`:

```bash
adal==1.2.1
antlr4-python3-runtime==4.7.2
applicationinsights==0.11.7
argcomplete==1.9.5
asn1crypto==0.24.0
astroid==2.2.5
azure-batch==6.0.0
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli&subdirectory=src\azure-cli
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_acr&subdirectory=src\command_modules\azure-cli-acr
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_acs&subdirectory=src\command_modules\azure-cli-acs
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_advisor&subdirectory=src\command_modules\azure-cli-advisor
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_ams&subdirectory=src\command_modules\azure-cli-ams
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_appservice&subdirectory=src\command_modules\azure-cli-appservice
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_backup&subdirectory=src\command_modules\azure-cli-backup
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_batch&subdirectory=src\command_modules\azure-cli-batch
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_batchai&subdirectory=src\command_modules\azure-cli-batchai
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_billing&subdirectory=src\command_modules\azure-cli-billing
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_botservice&subdirectory=src\command_modules\azure-cli-botservice
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_cdn&subdirectory=src\command_modules\azure-cli-cdn
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_cloud&subdirectory=src\command_modules\azure-cli-cloud
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_cognitiveservices&subdirectory=src\command_modules\azure-cli-cognitiveservices
azure-cli-command-modules-nspkg==2.0.2
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_configure&subdirectory=src\command_modules\azure-cli-configure
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_consumption&subdirectory=src\command_modules\azure-cli-consumption
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_container&subdirectory=src\command_modules\azure-cli-container
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_core&subdirectory=src\azure-cli-core
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_cosmosdb&subdirectory=src\command_modules\azure-cli-cosmosdb
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_dev_tools&subdirectory=tools
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_dla&subdirectory=src\command_modules\azure-cli-dla
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_dls&subdirectory=src\command_modules\azure-cli-dls
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_dms&subdirectory=src\command_modules\azure-cli-dms
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_eventgrid&subdirectory=src\command_modules\azure-cli-eventgrid
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_eventhubs&subdirectory=src\command_modules\azure-cli-eventhubs
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_extension&subdirectory=src\command_modules\azure-cli-extension
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_feedback&subdirectory=src\command_modules\azure-cli-feedback
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_find&subdirectory=src\command_modules\azure-cli-find
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_hdinsight&subdirectory=src\command_modules\azure-cli-hdinsight
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_interactive&subdirectory=src\command_modules\azure-cli-interactive
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_iot&subdirectory=src\command_modules\azure-cli-iot
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_iotcentral&subdirectory=src\command_modules\azure-cli-iotcentral
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_keyvault&subdirectory=src\command_modules\azure-cli-keyvault
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_kusto&subdirectory=src\command_modules\azure-cli-kusto
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_lab&subdirectory=src\command_modules\azure-cli-lab
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_maps&subdirectory=src\command_modules\azure-cli-maps
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_monitor&subdirectory=src\command_modules\azure-cli-monitor
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_network&subdirectory=src\command_modules\azure-cli-network
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_nspkg&subdirectory=src\azure-cli-nspkg
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_policyinsights&subdirectory=src\command_modules\azure-cli-policyinsights
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_privatedns&subdirectory=src\command_modules\azure-cli-privatedns
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_profile&subdirectory=src\command_modules\azure-cli-profile
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_rdbms&subdirectory=src\command_modules\azure-cli-rdbms
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_redis&subdirectory=src\command_modules\azure-cli-redis
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_relay&subdirectory=src\command_modules\azure-cli-relay
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_reservations&subdirectory=src\command_modules\azure-cli-reservations
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_resource&subdirectory=src\command_modules\azure-cli-resource
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_role&subdirectory=src\command_modules\azure-cli-role
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_search&subdirectory=src\command_modules\azure-cli-search
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_security&subdirectory=src\command_modules\azure-cli-security
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_servicebus&subdirectory=src\command_modules\azure-cli-servicebus
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_servicefabric&subdirectory=src\command_modules\azure-cli-servicefabric
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_signalr&subdirectory=src\command_modules\azure-cli-signalr
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_sql&subdirectory=src\command_modules\azure-cli-sql
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_sqlvm&subdirectory=src\command_modules\azure-cli-sqlvm
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_storage&subdirectory=src\command_modules\azure-cli-storage
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_telemetry&subdirectory=src\azure-cli-telemetry
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_testsdk&subdirectory=src\azure-cli-testsdk
-e git+https://github.com/stevengum/azure-cli@42b9f1e0e771e9d9d531e503f39eb2fbe2f1e646#egg=azure_cli_vm&subdirectory=src\command_modules\azure-cli-vm
azure-common==1.1.18
azure-datalake-store==0.0.39
azure-devtools==1.0.0
azure-functions-devops-build==0.0.14
azure-graphrbac==0.60.0
azure-keyvault==1.1.0
azure-mgmt-advisor==2.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==6.0.0
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.1.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-compute==4.5.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.7.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-datalake-analytics==0.2.1
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==2.0.0
azure-mgmt-eventhub==2.3.0
azure-mgmt-hdinsight==0.2.1
azure-mgmt-iotcentral==1.0.0
azure-mgmt-iothub==0.7.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-kusto==0.3.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-managementgroups==0.1.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.1.1
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.6.0
azure-mgmt-nspkg==1.0.0
azure-mgmt-policyinsights==0.2.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==1.7.1
azure-mgmt-recoveryservices==0.1.1
azure-mgmt-recoveryservicesbackup==0.1.2
azure-mgmt-redis==6.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.3.1
azure-mgmt-resource==2.1.0
azure-mgmt-search==2.0.0
azure-mgmt-security==0.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.12.0
azure-mgmt-sqlvirtualmachine==0.2.0
azure-mgmt-storage==3.1.1
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==0.41.0
azure-multiapi-storage==0.2.3
azure-nspkg==3.0.2
azure-storage-blob==1.3.1
azure-storage-common==1.4.0
azure-storage-nspkg==3.1.0
bcrypt==3.1.6
bleach==3.1.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
colorama==0.4.1
ConfigArgParse==0.14.0
coverage==4.5.3
cryptography==2.4.2
docutils==0.14
fabric==2.4.0
flake8==3.5.0
humanfriendly==4.18
idna==2.8
invoke==1.2.0
ipaddress==1.0.22
isodate==0.6.0
isort==4.3.17
Jinja2==2.10.1
jmespath==0.9.4
knack==0.5.4
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
mccabe==0.6.1
mock==2.0.0
msrest==0.6.6
msrestazure==0.6.0
multidict==4.5.2
nose==1.3.7
oauthlib==3.0.1
paramiko==2.4.2
pbr==5.1.3
portalocker==1.2.1
prompt-toolkit==1.0.15
psutil==5.6.1
pyasn1==0.4.5
pycodestyle==2.3.1
pycparser==2.19
pydocumentdb==2.3.3
pyflakes==1.6.0
Pygments==2.3.1
PyJWT==1.7.1
pylint==2.0.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyperclip==1.7.0
pypiwin32==223
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
pywin32==224
PyYAML==5.1
readme-renderer==24.0
requests==2.21.0
requests-oauthlib==1.2.0
scp==0.13.2
six==1.12.0
sshtunnel==0.1.4
tabulate==0.8.3
typed-ast==1.3.1
urllib3==1.24.1
vcrpy==2.0.1
vsts==0.1.25
vsts-cd-manager==1.0.2
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
wrapt==1.11.1
xmltodict==0.12.0
yarl==1.3.0
```

**Comment by stevengum** [comment]
I should note that after the failed setup, executing `az webapp -h` results in the following stack trace and `ModuleNotFoundError`:

```bash
The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt'
Traceback (most recent call last):
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 273, in execute
    parsed_args = self.parser.parse_args(args)
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\parser.py", line 256, in parse_args
    return super(CLICommandParser, self).parse_args(args)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1969, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1946, in consume_positionals
    take_action(action, args)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1152, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1037, in __call__
    parser.print_help()
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\parser.py", line 156, in format_help
    super(AzCliCommandParser, self).format_help()
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\parser.py", line 246, in format_help
    is_group)
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\_help.py", line 148, in show_help
    super(AzCliHelp, self).show_help(cli_name, nouns, parser, is_group)
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\help.py", line 664, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\help.py", line 219, in __init__
    child.load(options)
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\_help.py", line 242, in load
    loader.versioned_load(self, options)
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\_help_loaders.py", line 153, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\help.py", line 163, in load
    description = getattr(options, 'description', None)
  File "C:\Users\stgum\tools\carlos-fork\venv\s58\lib\site-packages\knack\parser.py", line 237, in __getattribute__
    if callable(self._description) else self._description
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\__init__.py", line 460, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "c:\users\stgum\tools\carlos-fork\src\azure-cli-core\azure\cli\core\__init__.py", line 494, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Users\stgum\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\stgum\tools\carlos-fork\src\command_modules\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 33, in <module>
    from azure.mgmt.storage import StorageManagementClient
ModuleNotFoundError: No module named 'azure.mgmt'

To open an issue, please run: 'az feedback'
```

**Comment by stevengum** [comment]
@lmazuel, @tjprescott any ideas? I noticed in the dev_setup.py it force installs the old azure-mgmt-nspkg to use the old style namespace...

[dev_setup.py [L54-L57]](https://github.com/Azure/azure-cli/blob/dev/scripts/dev_setup.py#L54-L57)
```python
# Ensure that the site package's azure/__init__.py has the old style namespace
# package declaration by installing the old namespace package
pip_command('install --force-reinstall azure-nspkg==1.0.0')
pip_command('install --force-reinstall azure-mgmt-nspkg==1.0.0')
```

**Comment by tjprescott** [comment]
Looks like this is related #9046.

**Comment by stevengum** [comment]
Thanks for linking that @tjprescott, downgrading pip to 9.0.1 via `pip install --upgrade pip==9.0.1` got rid of the error messages and problems when directly calling a command module (e.g. `az webapp -h`).

**Comment by tjprescott** [comment]
@stevengum instead of using scripts\dev_setup.py does it work if you do the following:

```
create and activate new venv
pip install azdev
azdev setup -c
```

**Comment by stevengum** [comment]
That worked, I tested running a couple of commands, the linter and recorded tests. Everything seems to be working great 👍

**Comment by jaredmoo** [comment]
If dev_setup.py is broken, can you please remove it or update it to point to the new method?

**Comment by tjprescott** [comment]
We will remove it in the future, but we have already updated our documentation to point to the new tooling:
https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md

**Comment by tjprescott** [comment]
I will note though that I did use `dev_setup.py` with the updated pip and it worked for me still.

**Comment by jaredmoo** [comment]
Understood, but I am sure that Steven and I will not be the only folks who run into this. A helpful note will save time.
