### ISSUE TITLE
Error when running command "az vm list -d --verbose -o table".

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#9089]
The issue has been copied to your clipboard. Paste it here!
To print out the issue body locally, run `az feedback --verbose`

## Describe the bug

When running command "az vm list -d --verbose -o table" within Windows Subsystem for Linux" using Ubuntu Linux, I receive the following error. This command ran OK until a few hours ago. Other variants run as expected - for example: "az vm list".

**Command Name**
`az vm list`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2bbeb556-fece-486c-9f29-43144203fd7d/resourceGroups/BAGVMRG/providers/Microsoft.Compute/virtualMachines/mgmt-syslogsrv?$expand=instanceView&api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2bbeb556-fece-486c-9f29-43144203fd7d/resourceGroups/BAGVMRG/providers/Microsoft.Compute/virtualMachines/mgmt-syslogsrv?$expand=instanceView&api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2bbeb556-fece-486c-9f29-43144203fd7d/resourceGroups/BAGVMRG/providers/Microsoft.Compute/virtualMachines/mgmt-syslogsrv?$expand=instanceView&api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 758, in list_vm
    return [get_vm_details(cmd, _parse_rg_name(v.id)[0], v.name) for v in vm_list]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 758, in <listcomp>
    return [get_vm_details(cmd, _parse_rg_name(v.id)[0], v.name) for v in vm_list]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 702, in get_vm_details
    result = get_instance_view(cmd, resource_group_name, vm_name)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 691, in get_instance_view
    return get_vm(cmd, resource_group_name, vm_name, 'instanceView')
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 696, in get_vm
    return client.virtual_machines.get(resource_group_name, vm_name, expand=expand)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/compute/v2018_10_01/operations/virtual_machines_operations.py", line 552, in get
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/2bbeb556-fece-486c-9f29-43144203fd7d/resourceGroups/BAGVMRG/providers/Microsoft.Compute/virtualMachines/mgmt-syslogsrv?$expand=instanceView&api-version=2018-10-01 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az vm list -d --verbose -o {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli                         2.0.62

```

**Comment by tjprescott** [comment]
This looks like a temporary service issue. @adewaleo, perhaps we should improve the generic exception handler to catch this error and emit a more useful error (and not a stack trace)

**Comment by adewaleo** [comment]
Closing this as this was a service error and the CLI more gracefully handles this error. see #9203
