### ISSUE TITLE
ImportError: cannot import name StorageAccountTypes

### ISSUE THREAD

**Issue by jdvor** [Azure/azure-cli#9103]
**Command Name**
`az sf cluster list`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

cannot import name 'StorageAccountTypes'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 248, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 265, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 130, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\commands.py", line 89, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 454, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 494, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-servicefabric\azure\cli\command_modules\servicefabric\custom.py", line 43, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\models.py", line 10, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\compute_management_client.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\disks_operations.py", line 18, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\compute\v2018_09_30\models\__init__.py", line 56, in <module>
    from ._compute_management_client_enums import StorageAccountTypes
ImportError: cannot import name 'StorageAccountTypes'
```

## To Reproduce:

- install az CLI on Windows using MSI installer (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
- `Run: az login -u ... -p ....` (successful)
- `Run: az sf cluster list -g ... --subscription ...` (fails)

## Expected Behavior

List SF cluster in the account

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

```
## Additional Context
`az --version`

```
azure-cli                         2.0.62

acr                                2.2.4
acs                               2.3.21
advisor                            2.0.0
ams                                0.4.4
appservice                        0.2.17
backup                             1.2.3
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                        0.1.10
cdn                                0.2.2
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.21
consumption                        0.4.2
container                         0.3.16
core                              2.0.62
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.5
feedback                           2.2.0
find                               0.3.2
hdinsight                          0.3.3
interactive                        0.4.3
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.14
kusto                              0.2.2
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.12
network                            2.3.6
nspkg                              3.0.3
policyinsights                     0.1.2
privatedns                         1.0.0
profile                            2.1.5
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.13
role                               2.5.0
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.16
signalr                            1.0.0
sql                                2.2.1
sqlvm                              0.1.1
storage                            2.4.0
telemetry                          1.0.2
vm                                2.2.18

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dvora\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by tjprescott** [comment]
@marstr it looks like the common thread here may be the Windows MSI installer.

**Comment by tjprescott** [comment]
This is being tracked by #9133. Please see that issue to be able to roll back your MSI installation.
