### ISSUE TITLE
webapp:Try stop webjob on a slot but not working

### ISSUE THREAD

**Issue by tuthan** [Azure/azure-cli#9116]
## Describe the bug

**Command Name**
`az webapp webjob continuous stop`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

dictionary update sequence element #0 has length 1; 2 is requiredTraceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 375, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-appservice\azure\cli\command_modules\appservice\commands.py", line 54, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 2223, in stop_continuous_webjob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-web\azure\mgmt\web\operations\web_apps_operations.py", line 3380, in stop_continuous_web_job
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az webapp webjob continuous stop --webjob-name {} --name {} --resource-group {} --slot {}`

## Expected Behavior

Stop webjob in a slot

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

```

**Comment by JesseDeBruijne** [comment]
@panchagnula Any update on this? I'm running into the same problem

**Comment by panchagnula** [comment]
Is this still an issue? @JesseDeBruijne / @tuthan can you let us know if you are still facing this? Thank you

**Comment by JesseDeBruijne** [comment]
Yeah, this issue still exists when I try to run the command:

```
az webapp webjob continuous stop --webjob-name {} --name {} --resource-group {} --slot {}
```

I get the error:

```
The command failed with an unexpected error. Here is the traceback:

dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 578, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 627, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 606, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\custom.py", line 2360, in stop_continuous_webjob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-mgmt-web\azure\mgmt\web\operations\web_apps_operations.py", line 3380, in stop_continuous_web_job
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by dirtygooback** [comment]
This still appears broken for me

PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
