### ISSUE TITLE
Stack trace using storage command in CLI 2.0.62.

### ISSUE THREAD

**Issue by tchachra** [Azure/azure-cli#9120]
The is

## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'copy'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-vm\azure\cli\command_modules\vm\custom.py", line 389, in create_snapshot
AttributeError: 'NoneType' object has no attribute 'copy'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az snapshot create --name {} --resource-group {} --source {} --output {} --tags {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

Extensions:
image-copy-extension               0.0.9

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'D:\Users\tarun\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

```

**Comment by tjprescott** [comment]
@marstr this may be related to the potential packaging issue we've seen reported.

**Comment by tamirkamara** [comment]
BTW, the docker image for version 62 works just fine.
I personally have the problem manifest on windows. Looks like @tchachra is also on widows, not sure about @gpin1120

**Comment by tjprescott** [comment]
On Windows, installed through... the MSI?

**Comment by tjprescott** [comment]
This is being tracked by #9133. Please see that issue to be able to roll back your MSI installation.
