### ISSUE TITLE
az webapp --help failure

### ISSUE THREAD

**Issue by ernani** [Azure/azure-cli#9129]
## Describe the bug

**Command Name**
`az webapp`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

cannot import name 'SnapshotRecoveryRequest'Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 273, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 256, in parse_args
    return super(CLICommandParser, self).parse_args(args)
  File "/opt/az/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1950, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1927, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1133, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.6/argparse.py", line 1020, in __call__
    parser.print_help()
  File "/opt/az/lib/python3.6/argparse.py", line 2362, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 156, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 246, in format_help
    is_group)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 148, in show_help
    super(AzCliHelp, self).show_help(cli_name, nouns, parser, is_group)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 664, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 219, in __init__
    child.load(options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help.py", line 242, in load
    loader.versioned_load(self, options)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_help_loaders.py", line 153, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/opt/az/lib/python3.6/site-packages/knack/help.py", line 163, in load
    description = getattr(options, 'description', None)
  File "/opt/az/lib/python3.6/site-packages/knack/parser.py", line 237, in __getattribute__
    if callable(self._description) else self._description
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 460, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 494, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ernani/.azure/cliextensions/webapp/azext_webapp/custom.py", line 10, in <module>
    from azure.mgmt.web.models import (AppServicePlan, SkuDescription, SnapshotRecoveryRequest, SnapshotRecoveryTarget)
ImportError: cannot import name 'SnapshotRecoveryRequest'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az webapp --help`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli                         2.0.62

Extensions:
aks-preview                        0.3.0
front-door                         0.1.1
storage-preview                    0.1.6
webapp                             0.2.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/ernani/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Apr  4 2019, 22:51:52) 
[GCC 5.4.0 20160609]

```

**Comment by panchagnula** [comment]
CC: @Nking92 
@ernani looks like you have an older version of a web app extension can you delete this & re-try
run
1. az extension list to confirm you have extensions installed
2. az extension remove -n webapp

& then re-try.

**Comment by ernani** [comment]
Sure thing, on it, will report back when done!

**Comment by panchagnula** [comment]
the error here is you had an older version of webapp extension installed, & the core cli had some SDK updates that caused the error you are seeing. Is there a specific command from extension you are trying to use? Some of the extension commands did get moved to core. 
this command however is still an extension command If you need this one please install the latest extension az extension add -n webapp. Thank you.
