### ISSUE TITLE
az create command fails on ubuntu-16.04

### ISSUE THREAD

**Issue by glenvillef** [Azure/azure-cli#9130]
Hey everyone: 

Following the Kubernetes tutorial found here:
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-acr

When getting to the az create acr part I get the below log:

The command failed with an unexpected error. Here is the traceback:

## Describe the bug

**Command Name**
`az acr create`

**Errors:**

:expressionless:

```The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/afddb0e0-37f7-438b-aa00-5ddf551b003c/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/acrName?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/afddb0e0-37f7-438b-aa00-5ddf551b003c/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/acrName?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 270, in user_hook_cb
    return user_hook(r, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/tools.py", line 62, in register_rp_hook
    return session.send(req)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/afddb0e0-37f7-438b-aa00-5ddf551b003c/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/acrName?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/custom.py", line 104, in acr_create
    return client.create(resource_group_name, registry_name, registry)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 351, in create
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerregistry/v2018_09_01/operations/registries_operations.py", line 300, in _create_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 270, in user_hook_cb
    return user_hook(r, *args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/tools.py", line 62, in register_rp_hook
    return session.send(req)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/afddb0e0-37f7-438b-aa00-5ddf551b003c/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/acrName?api-version=2017-10-01 (Caused by ResponseError('too many 503 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az acr create --resource-group {} --name {} --sku {}`

## Environment Summary
```
Linux-4.15.0-46-generic-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli                         2.0.62

```
## Additional Context

Thanks for your feedback!
command ran in 4.022 seconds.

Please advise :)

**Comment by glenvillef** [comment]
Sorted, think it was my naming convention. Sorry to bother. Ran this command instead: 
az acr create --resource-group myResourceGroup --name labDemoAcr --sku Basic
