### ISSUE TITLE
az login issue callback fails with NoneType

### ISSUE THREAD

**Issue by jeroendelooze** [Azure/azure-cli#9143]
## Describe the bug

**Command Name**
`az login`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object is not callableTraceback (most recent call last):
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/command_modules/profile/custom.py", line 133, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/_profile.py", line 190, in find_subscriptions_on_login
    tenant, self._ad_resource_uri, authority_url)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/_profile.py", line 787, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/_profile.py", line 829, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "/Users/jeroen/Library/Python/3.6/lib/python/site-packages/azure/cli/core/_profile.py", line 751, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az login`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.6.4
Shell: bash

azure-cli                         2.0.62

```

**Comment by yugangw-msft** [comment]
@jeroendelooze, do you remember how did you install the Azure CLI? To me, it appears the azure-mgmt-resource library is missing or at least not installed correctly.
CC @marstr

**Comment by dashesy** [comment]
Same issue, installed on Windows with `pip install azure-cli` in Anaconda. Seems `azure-cli` is broken, lots of errors like this now!

**Comment by jiasli** [comment]
It seems `azure-mgmt-resource` is missing. Please check https://github.com/Azure/azure-cli/issues/11236#issuecomment-564244983. As this issue is regarding an old version of Azure CLI. If the error persists, please create a new issue. Thanks.
