### ISSUE TITLE
cannot import name 'AppRole' from 'azure.graphrbac.models'

### ISSUE THREAD

**Issue by sdementen** [Azure/azure-cli#9160]
## Describe the bug

**Command Name**
`az ad app create`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

cannot import name 'AppRole' from 'azure.graphrbac.models' (C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\graphrbac\models\__init__.py)Traceback (most recent call last):
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\core\commands\__init__.py", line 248, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\core\__init__.py", line 265, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\core\commands\__init__.py", line 130, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\knack\commands.py", line 89, in load_arguments
    cmd_args = self.arguments_loader()
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\core\__init__.py", line 454, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\core\__init__.py", line 494, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\cli\command_modules\role\custom.py", line 29, in <module>
    from azure.graphrbac.models import (ApplicationCreateParameters, ApplicationUpdateParameters, AppRole,
ImportError: cannot import name 'AppRole' from 'azure.graphrbac.models' (C:\Users\gfj138\.virtualenvs\datchee-LjB_4OYu\lib\site-packages\azure\graphrbac\models\__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Run: az login`
- `Run: az ad app create --display-name {}`

## Expected Behavior

Command running and either executing or showing a user error message (not an import exception).

## Environment Summary
```
Windows-7-6.1.7601-SP1
Python 3.7.1
Shell: cmd.exe

azure-cli                         2.0.62

```

**Comment by yonzhan** [comment]
We will triage this issue.

**Comment by jiasli** [comment]
Currently we are not seeing anyone else reporting the same issue. Project structure also looks fine. Please [reinstall the latest version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) and retry the command.
