### ISSUE TITLE
azure cli gitbash - Anaconda

### ISSUE THREAD

**Issue by Denisnjeru** [Azure/azure-cli#9161]
## Describe the bug

**Command Name**
`az cognitiveservices account show`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

No module named 'azure.mgmt.cognitiveservices'Traceback (most recent call last):
  File "C:\Users\njeru\AppData\Roaming\Python\Python37\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\commands\__init__.py", line 248, in execute
    self.commands_loader.load_arguments(command)
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\__init__.py", line 265, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\commands\__init__.py", line 130, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "C:\Users\njeru\AppData\Roaming\Python\Python37\site-packages\knack\commands.py", line 89, in load_arguments
    cmd_args = self.arguments_loader()
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\commands\arm.py", line 703, in generic_show_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\commands\arm.py", line 388, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "c:\users\njeru\appdata\roaming\python\python37\site-packages\azure\cli\core\__init__.py", line 494, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Users\njeru\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.cognitiveservices'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az cognitiveservices account show --resource-group {} --name {} --query {} --output {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.7.1
Shell: bash.exe

azure-cli                         2.0.62

Extensions:
interactive                        0.4.1

Python location 'C:\Users\njeru\Anaconda3\python.exe'
Extensions directory 'C:\Users\njeru\.azure\cliextensions'

Python (Windows) 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

```
## Additional Context

out the issue body locally, run `az feedback --verbose`

**Comment by adewaleo** [comment]
From first glance, this might be a packaging issue @marstr, @tjprescott 
It appears that you are using **Anaconda** @Denisnjeru. (see file path for failed import)

Could you give us more information about your installation environment @Denisnjeru? How did you install the CLI? Are you using conda to manage CLI modules and dependencies?

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to open it if you still have the same issue with recent versions of azure cli.
