### ISSUE TITLE
az batch account show failed with unexpected error

### ISSUE THREAD

**Issue by DzonnyDZ** [Azure/azure-cli#9165]
**Command Name**
`az batch account show`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

No section: 'batch'Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'batch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 375, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-batch\azure\cli\command_modules\batch\_exception_handler.py", line 30, in batch_exception_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-batch\azure\cli\command_modules\batch\custom.py", line 54, in get_account
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\config.py", line 63, in get
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'batch'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az batch account show --subscription {} --name {}`

## Expected Behavior

I expected information about the batch account, no error.

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62

```

**Comment by bgklein** [comment]
This is an expected failure (albeit a bad error).

az batch account show has required arguments
```
Arguments
    --name -n           : Name of the batch account to show. If not specified will display currently
                          set account.
    --resource-group -g : Name of the resource group. If not specified will display currently set
                          account.
```

If these are both not specified we try to show you the current account you are logged into.

**Comment by marstr** [comment]
Thanks for responding to this @bgklein. Are you planning on following up by catching the NoSectionError and giving a more intuitive error message?

**Comment by bgklein** [comment]
Yea, I'll set aside some time this week to improve error handling for this and #8978 .
