### ISSUE TITLE
tutorial-static-website-serverless

### ISSUE THREAD

**Issue by EivydasKo** [Azure/azure-cli#9173]
Hi, 

I ran your tutorial to generate a static webpage app on azure storage as per:
https://docs.microsoft.com/en-us/azure/functions/tutorial-static-website-serverless-api-with-database?tutorial-step=1

I am getting the bellow error on the last step az storage blob upload-batch -s . -d \$web --account-name <storage account name>

## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

The requested URI does not represent any resource on the server. ErrorCode: InvalidUri<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:61e2c89c-101e-0001-57a6-f9addb000000
Time:2019-04-23T07:27:44.6218100Z</Message><UriPath>https://azueus2devsahqs.blob.core.windows.net///.nojekyll</UriPath></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 375, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 240, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 183, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 263, in storage_blob_upload_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 218, in wrapper
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 239, in _upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 352, in upload_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 345, in upload_block_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 463, in create_blob_from_path
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 582, in create_blob_from_stream
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\blockblobservice.py", line 971, in _put_blob
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureHttpError: The requested URI does not represent any resource on the server. ErrorCode: InvalidUri
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.
RequestId:61e2c89c-101e-0001-57a6-f9addb000000
Time:2019-04-23T07:27:44.6218100Z</Message><UriPath>https://azueus2devsahqs.blob.core.windows.net///.nojekyll</UriPath></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az storage blob upload-batch -s {} -d {} --account-name {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli                         2.0.62

```

**Comment by jessebarocio** [comment]
Hi, I ran into the same problem. This is a problem in the tutorial not the CLI. I can't find a repository to report issues to for the tutorial though.

The command in the tutorial assumes you're using the CLI in bash. The `$` in the $web container name is escaped with a `\`.

    az storage blob upload-batch -s . -d \$web --account-name <storage account name>

If you're using powershell you need to escape it with a backtick (`) instead. 

    az storage blob upload-batch -s . -d `$web --account-name <storage account name>

If you're using cmd on Windows you don't need to escape it:

    az storage blob upload-batch -s . -d $web --account-name <storage account name>

**Comment by limingu** [comment]
Thank you, @jessebarocio

@EivydasKo can you try the command like:
az storage blob upload-batch -s . -d $web --account-name <storage account name>

**Comment by limingu** [comment]
No response. Close now.
