### ISSUE TITLE
Error creating az network lb rule create

### ISSUE THREAD

**Issue by chris-camm** [Azure/azure-cli#9179]
The issue has been copied to your clipboard. Paste it here!
To print out the issue body locally, run `az feedback --verbose`

## Describe the bug

**Command Name**
`az network lb rule create`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

Unable to serialize value: '' as type: 'int'., ValueError: invalid literal for int() with base 10: ''Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 694, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 740, in serialize_basic
    return eval(data_type)(data)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/command_modules/network/custom.py", line 2289, in create_lb_rule
    poller = ncf.load_balancers.create_or_update(resource_group_name, load_balancer_name, lb)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/mgmt/network/v2018_12_01/operations/load_balancers_operations.py", line 269, in create_or_update
    **operation_config
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/mgmt/network/v2018_12_01/operations/load_balancers_operations.py", line 215, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'LoadBalancer')
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 580, in body
    return self._serialize(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 452, in _serialize
    target_obj, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 715, in serialize_data
    return self._serialize(data, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 489, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 708, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 783, in serialize_iter
    serialized.append(self.serialize_data(d, iter_type, **kwargs))
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 715, in serialize_data
    return self._serialize(data, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 489, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 713, in serialize_data
    SerializationError, msg.format(data, data_type), err)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 694, in serialize_data
    return self.serialize_basic(data, data_type, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/msrest/serialization.py", line 740, in serialize_basic
    return eval(data_type)(data)
msrest.exceptions.SerializationError: Unable to serialize value: '' as type: 'int'., ValueError: invalid literal for int() with base 10: ''
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az network lb rule create --resource-group {} --lb-name {} --name {} --protocol {} --frontend-port {} --backend-port {} --frontend-ip-name {} --backend-pool-name {} --probe-name {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli                         2.0.62

```

**Comment by tjprescott** [comment]
What actual values did you supply?

**Comment by chris-camm** [comment]
I created a function within a script to pass the values:

az network lb rule create             \
      --resource-group "${RG_NAME}"       \
      --lb-name "${LB_NAME}"              \
      --name "${RULE_NAME}"               \
      --protocol "${PROTOCOL}"            \
      --frontend-port "${FPORT_NBER}"     \
      --backend-port "${BPORT_NBER}"      \
      --frontend-ip-name "${FPOOL_NAME}"  \
      --backend-pool-name "${BPOOL_NAME}" \
      --probe-name "${PROBE_NAME}"

Where:

RG_NAME=inf
LB_NAME=xxx-infxxx-lb01
RULE_NAME=xxxx-https
PROTOCOL=tcp
FPORT_NBER=443
BPORT_NBER=443
FPOOL_NAME=xxxx-fp01
BPOOL_NAME=xxxx-bp01
PROBE_NAME=xxxx-probe01

**Comment by tjprescott** [comment]
If you run your command with `--debug`, what is the first line (which starts "Command arguments:")?

**Comment by tjprescott** [comment]
The issue is that it looks like one of those parameters that should be an integer is receiving empty string instead.

**Comment by chris-camm** [comment]
My system updated the az cli this morning and I have run the command now and its working with exactly the same parameters used.

az --version
azure-cli                         2.0.63

acr                                2.2.5
acs                               2.3.22
advisor                            2.0.0
ams                                0.4.5
appservice                        0.2.18
backup                             1.2.4
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                        0.1.10
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.22
consumption                        0.4.2
container                         0.3.16
core                              2.0.63
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.4
extension                          0.2.5
feedback                           2.2.1
find                               0.3.2
hdinsight                          0.3.3
interactive                        0.4.3
iot                                0.3.8
iotcentral                         0.1.6
keyvault                          2.2.14
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.13
network                            2.3.7
nspkg                              3.0.3
policyinsights                     0.1.2
privatedns                         1.0.0
profile                            2.1.5
rdbms                             0.3.10
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.14
role                               2.6.0
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.17
signalr                            1.0.0
sql                                2.2.2
sqlvm                              0.1.1
storage                            2.4.1
telemetry                          1.0.2
vm                                2.2.19

Python location '/usr/local/Cellar/azure-cli/2.0.63/libexec/bin/python'
Extensions directory '/Users/xxxxxxxx/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by lexuanquynh** [comment]
? can I fix it
