### ISSUE TITLE
"az sf application certificate add" failed

### ISSUE THREAD

**Issue by kjcho-msft** [Azure/azure-cli#9187]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.63

**Describe the bug**
"az sf application certificate add" failed.

The command failed with an unexpected error. Here is the traceback:

add_app_cert() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 581, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 574, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 551, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 289, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\__init__.py", line 453, in default_command_handler
TypeError: add_app_cert() missing 1 required positional argument: 'client'

**To Reproduce**
Run the following command
 az sf application certificate add --resource-group $resourceGroupName --cluster-name $clustername --secret-identifier $secretId

**Expected behavior**
A new certificate is added to the Virtual Machine Scale Sets that make up the cluster

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

apt-get/2.0.63/Ubuntu 16.04/bash

**Additional context**

**Comment by adewaleo** [comment]
@QingChenmsft looks like there is a bug in the command. The fix should be quick

**Comment by peterpogorski** [comment]
Thanks for your feedback. In this next release we are going to deprecate this cmdlet.

**Comment by sudo-n00b** [comment]
is there any alternate cmdlet that we can use?
