### ISSUE TITLE
az vm image accept-terms failing

### ISSUE THREAD

**Issue by ranokarno** [Azure/azure-cli#9196]
## Describe the bug

**Command Name**
`az vm image accept-terms`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subId>/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/checkpoint/offers/check-point-vsec-r80/plans/sg-byol/agreements/current?api-version=2015-06-01 (Caused by ResponseError('too many 500 error responses',))Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<subId>/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualmachine/publishers/checkpoint/offers/check-point-vsec-r80/plans/sg-byol/agreements/current?api-version=2015-06-01 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az vm image accept-terms --plan sg-byol --offer check-point-vsec-r80 --publish checkpoint --subscription <subId>`

## Environment Summary
```
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Python 2.7.5
Shell: bash

azure-cli                         2.0.62 *

```

**Comment by adewaleo** [comment]
I just tried this command out and it succeeded:

```
$ az vm image accept-terms --plan sg-byol --offer check-point-vsec-r80 --publish checkpoint --query "{accepted:accepted, name:name, plan:plan, privacyPolicyLink:privacyPolicyLink, product:product, type:type}"
{
  "accepted": true,
  "name": "sg-byol",
  "plan": "sg-byol",
  "privacyPolicyLink": "http://www.checkpoint.com/privacy",
  "product": "check-point-vsec-r80",
  "type": "Microsoft.MarketplaceOrdering/offertypes"
}
```

This seems like a (temporary) service side error similar to #9089 

Have you retried the command? @ranokarno

**Comment by ranokarno** [comment]
@adewaleo , yes issue resolved.
I will proceed to close this ticket now
