### ISSUE TITLE
Unable to create empty disk with 'az disk create' command

### ISSUE THREAD

**Issue by fkaksa** [Azure/azure-cli#9200]
## Describe the bug
Unable to create data disk following the sample on the official Azure site: https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-create 

**Command Name**
`az disk create`

**Errors:**

:confused:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'empty'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 326, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 384, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 354, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 145, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-vm\azure\cli\command_modules\vm\custom.py", line 263, in create_managed_disk
AttributeError: 'NoneType' object has no attribute 'empty'
```

## To Reproduce:
- `Run: az disk create -g <my-rg> --name <my-disk> --size-gb 10`

## Expected Behavior

Disk is created

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli                         2.0.62 *

```

**Comment by marstr** [comment]
Howdy @fkaksa, does this bug repro when you install 2.0.63? We had some trouble with the Windows installer in 2.0.62 that may be causing this behavior.

**Comment by fkaksa** [comment]
Hi! I can confirm that new version fixed the bug. Thanks!

**Comment by marstr** [comment]
Related to #9133
