### ISSUE TITLE
Azure interactive is broken with 2.063 on CentOS 7

### ISSUE THREAD

**Issue by mountainbrother** [Azure/azure-cli#9229]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


cannot import name DEFAULTS_SECTION
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    raise ex
ImportError: cannot import name DEFAULTS_SECTION
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.63

Extensions:
interactive 0.4.1

```

**Comment by tjprescott** [comment]
You need to update your extension to the version that is compatible with CLI core 2.0.63.
