### ISSUE TITLE
az storage blob download-batch fails with --sas-token

### ISSUE THREAD

**Issue by acl33** [Azure/azure-cli#9293]
## Describe the bug
az storage blob download-batch --sas-token fails whereas same with --account-key succeeds

**Command Name**
`az storage blob download-batch`

**Errors:**
```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:f635efb1-b01e-0074-0b23-019c1f000000
Time:2019-05-02T20:12:05.8062305Z</Message></Error>
Traceback (most recent call last):
pip-install-68v0_w99\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 523, in execute
...
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:f635efb1-b01e-0074-0b23-019c1f000000
Time:2019-05-02T20:12:05.8062305Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
First, to verify that download-batch works given the storage account key:
```
> $Env:STORAGE_ACCOUNT_NAME=...
> $KEY=...
> az storage blob download-batch --source 'build-20190502-3' --destination .\temp\ --dryrun --account-key $KEY
download action: from build-20190502-3 to .\temp\
    pattern None
  container build-20190502-3
      total 31
 operations
    ....
[]
```
(Note I specified dryrun). Now, generate an SAS token:
```
> $EXPIRY=Get-Date (Get-Date).AddDays(1) -uformat '+%Y-%m-%dT%H:%MZ'
> $EXPIRY
2019-05-03T20:05Z
> $sas=az storage container generate-sas --name 'build-20190502-3' --permissions 'rwl' --account-key $KEY --expiry $EXPIRY --output tsv
> $sas
se=2019-05-03T20%3A05Z&sp=rwl&sv=2018-03-28&sr=c&sig=HLT%2BZd0tSc9ISq5Yor1f199/p9rQYU0uR90u01Wuu1U%3D
> az storage blob download-batch --debug --source 'build-20190502-3' --destination .\temp\ --dryrun --sas-token $sas
Command arguments: ['storage', 'blob', 'download-batch', '--debug', '--source', 'build-20190502-3', '--destination', '.\\temp\\', '--dryrun', '--sas-token', 'se=2019-05-03T20%3A05Z']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03AFCDF8>, <function OutputProducer.on_global_arguments at 0x03C7EAE0>, <function CLIQuery.on_global_arguments at 0x03CA5738>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.012 seconds.
Loaded module 'acs' in 0.003 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.009 seconds.
Loaded module 'appservice' in 0.006 seconds.
Loaded module 'backup' in 0.009 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.021 seconds.
Loaded module 'batchai' in 0.007 seconds.
Loaded module 'billing' in 0.004 seconds.
Loaded module 'botservice' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.005 seconds.
Loaded module 'consumption' in 0.007 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.003 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.003 seconds.
Loaded module 'lab' in 0.007 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.005 seconds.
Loaded module 'network' in 0.022 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.012 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.011 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.006 seconds.
Loaded module 'role' in 0.013 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.004 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.005 seconds.
Loaded module 'sql' in 0.017 seconds.
Loaded module 'sqlvm' in 0.012 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.033 seconds.
Loaded module 'vm' in 0.012 seconds.
Loaded all modules in 0.326 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\allawr\.azure\cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03B7A7C8>]
az_command_data_logger : command args: storage blob download-batch --debug --source {} --destination {} --dryrun --sas-token {}
metadata file logging enabled - writing logs to 'C:\Users\allawr\.azure\commands'.
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03CC1738>, <function register_ids_argument.<locals>.add_ids_arguments at 0x03CD1030>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03CD1228>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04A56930>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03C7EB28>, <function CLIQuery.handle_query_parameter at 0x03CA5780>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03CD11E0>, <function handler at 0x04AFE108>]
Getting data service client service_type=BlockBlobService
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=9c5fe0ec-6d16-11e9-b24b-d89ef3290094 Outgoing request: Method=GET, Path=/build-20190502-3?se=2019-05-03T20%3A05Z, Query={'restype': 'container', 'comp': 'list', 'prefix': None, 'delimiter': None, 'marker': None, 'maxresults': None, 'include': None, 'timeout': None}, Headers={'x-ms-version': '2018-03-28', 'User-Agent': 'Azure-Storage/1.3.0-1.3.1 (Python CPython 3.6.6; Windows 10) AZURECLI/2.0.63', 'x-ms-client-request-id': '9be78ab4-6d16-11e9-8303-d89ef3290094', 'x-ms-date': 'Thu, 02 May 2019 20:12:29 GMT'}.
urllib3.connectionpool : Starting new HTTPS connection (1): knossosbuildpipeline.blob.core.windows.net:443
urllib3.connectionpool : https://knossosbuildpipeline.blob.core.windows.net:443 "GET /build-20190502-3?se=2019-05-03T20%3A05Z&restype=container&comp=list HTTP/1.1" 404 223
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=9c5fe0ec-6d16-11e9-b24b-d89ef3290094 Receiving Response: Server-Timestamp=Thu, 02 May 2019 20:12:29 GMT, Server-Request-ID=00397697-b01e-0016-6d23-015e38000000, HTTP Status Code=404, Message=The specified resource does not exist., Headers={'content-length': '223', 'content-type': 'application/xml', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '00397697-b01e-0016-6d23-015e38000000', 'x-ms-version': '2018-03-28', 'x-ms-error-code': 'ResourceNotFound', 'date': 'Thu, 02 May 2019 20:12:29 GMT'}.
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=9c5fe0ec-6d16-11e9-b24b-d89ef3290094 Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Thu, 02 May 2019 20:12:29 GMT, Server-Request-ID=00397697-b01e-0016-6d23-015e38000000, HTTP status code=404, Exception=The specified resource does not exist. ErrorCode: ResourceNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.RequestId:00397697-b01e-0016-6d23-015e38000000Time:2019-05-02T20:12:29.2988923Z</Message></Error>.
azure.multiapi.storage.v2018_03_28.common.storageclient : Client-Request-ID=9c5fe0ec-6d16-11e9-b24b-d89ef3290094 Retry policy did not allow for a retry: Server-Timestamp=Thu, 02 May 2019 20:12:29 GMT, Server-Request-ID=00397697-b01e-0016-6d23-015e38000000, HTTP status code=404, Exception=The specified resource does not exist. ErrorCode: ResourceNotFound<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.RequestId:00397697-b01e-0016-6d23-015e38000000Time:2019-05-02T20:12:29.2988923Z</Message></Error>.
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:00397697-b01e-0016-6d23-015e38000000
Time:2019-05-02T20:12:29.2988923Z</Message></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 581, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 572, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 240, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 183, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 551, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 289, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\__init__.py", line 453, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 165, in storage_blob_download_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 24, in collect_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1247, in list_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1322, in _list_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureMissingResourceHttpError: The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:00397697-b01e-0016-6d23-015e38000000
Time:2019-05-02T20:12:29.2988923Z</Message></Error>
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:00397697-b01e-0016-6d23-015e38000000
Time:2019-05-02T20:12:29.2988923Z</Message></Error>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 581, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 572, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 240, in new_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\__init__.py", line 183, in handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 551, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\commands\__init__.py", line 289, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\__init__.py", line 453, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\operations\blob.py", line 165, in storage_blob_download_batch
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-storage\azure\cli\command_modules\storage\util.py", line 24, in collect_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1247, in list_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\blob\baseblobservice.py", line 1322, in _list_blobs
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 381, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 306, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\storageclient.py", line 292, in _perform_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-multiapi-storage\azure\multiapi\storage\v2018_03_28\common\_error.py", line 115, in _http_error_handler
azure.common.AzureMissingResourceHttpError: The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:00397697-b01e-0016-6d23-015e38000000
Time:2019-05-02T20:12:29.2988923Z</Message></Error>
cli.azure.cli.core.util :
To open an issue, please run: 'az feedback'

To open an issue, please run: 'az feedback'
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2508 in cache
telemetry.check : Negative: The C:\Users\allawr\.azure\telemetry.txt was modified at 2019-05-02 21:12:07.421643, which in less than 600.000000 s
command ran in 1.040 seconds.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```
The "Command arguments" are clearly wrong, the rest of the sas having been lost. I note that if I put any of the other arguments to 'az storage blob download-batch' after the --sas-token, they don't show up in the list (putting --debug after --sas-token doesn't give debug output, either). Fearing maybe this was user error, I tried escaping the &'s in my SAS token with both ` (Powershell) and \ (python), to no avail, also using [System.Web.HttpUtility]::UrlEncode($sas), this printed a full (encoded) SAS string in the command-line arguments list, but still ResourceNotFound.

## Expected Behavior
Download the files, or list with `--dryrun`, just as it did with `--account-key` rather than `--sas-token`
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63

```
## Additional Context
```
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316
```

**Comment by acl33** [comment]
Ok, seems I need the $sas to contain double-quotes as first and last characters of the string.
