### ISSUE TITLE
Azure postgres server unreachable from cli and app service linux

### ISSUE THREAD

**Issue by moxplod** [Azure/azure-cli#9296]
My site that has access to azure postgres service stopped working all of a sudden.
I use app service linux that connects to azure postgres. That just suddenly stopped working as the application could not access the db server. 
I am able to access the server intermittently from my local client machine. 
Also not able to run azure cli commands. they are failing as well.

Internal logs are showing the following error -

`System.Net.Sockets.SocketException (11001): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081`

## Describe the bug

**Command Name**
`az postgres server restart`

**Errors:**
```
(--resource-group --name | --ids) are required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres server restart`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63

```

**Comment by yugangw-msft** [comment]
@moxplod can you please provide CLI error? `(--resource-group --name | --ids) are required` is not a postgres error; rather you didn't provide required arguments.

**Comment by panchagnula** [comment]
@moxplod are you still seeing this issue - there was an Azure Networking outage earlier today that impacted the availability of a # of Azure services - your issue timing matches the outage time. You can see the azure status here https://azure.microsoft.com/en-us/status/

**Comment by moxplod** [comment]
Nope - i think it coincided with that outage.
