### ISSUE TITLE
"az cosmosdb create" too many 503 error responses

### ISSUE THREAD

**Issue by john997301** [Azure/azure-cli#9300]
## Describe the bug
Error during cosmosdb create in West Central US.  Cosmos DB partially creates but the state is offline and Overview indicates Failed to refresh the collection list
**Command Name**
`az cosmosdb create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/[...]/resourceGroups/1st-sless-app/providers/Microsoft.DocumentDB/databaseAccounts/1stslessappdb/operationResults/[...]?api-version=2015-04-08 (Caused by ResponseError('too many 503 error responses',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/eb290dda-cf74-40ab-926b-691ffc1957e7/resourceGroups/1st-sless-app/providers/Microsoft.DocumentDB/databaseAccounts/1stslessappdb/operationResults/93eb5f6a-0d66-4f7a-be15-ee416528e3dc?api-version=2015-04-08 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/[...]/resourceGroups/1st-sless-app/providers/Microsoft.DocumentDB/databaseAccounts/1stslessappdb/operationResults/[...]?api-version=2015-04-08 (Caused by ResponseError('too many 503 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 574, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 551, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 289, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 453, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cosmosdb/custom.py", line 87, in cli_cosmosdb_create
    docdb_account = async_docdb_create.result()
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 183, in result
    self.wait(timeout)
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 201, in wait
    raise self._exception  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/polling/poller.py", line 152, in _start
    self._polling_method.run()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 390, in run
    self._poll()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 415, in _poll
    self.update_status()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 447, in update_status
    self._response = self.request_status(self._operation.location_url)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 470, in request_status
    return self._client.send(request, header_parameters, stream=False, **self._operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/opt/az/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/az/lib/python3.6/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443):Max retries exceeded with url: /subscriptions/[...]/resourceGroups/1st-sless-app/providers/Microsoft.DocumentDB/databaseAccounts/1stslessappdb/operationResults/[...]?api-version=2015-04-08 (Caused by ResponseError('too many 503 error responses',))
```

## To Reproduce:
Issue the command:
- `az cosmosdb create -g {} -n {}`

## Expected Behavior
Successful creation of Cosmos DB
## Environment Summary
```
Linux-4.15.0-1041-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63

```

**Comment by tjprescott** [comment]
This looks like a temporary service issue and I was not able to repro. If you are still seeing this error, please reopen.

**Comment by brianstringfellow** [comment]
I still see the problem when I deploy a new Cosmos DB account. Deployed using an ARM template from PowerShell that indicated a successful deployment.

![image](https://user-images.githubusercontent.com/22823524/65341316-ed9a7700-db84-11e9-9ca7-a9230e4fddf5.png)

Partial deployment output without giving up too much info about environment:
```
    "mode": "Incremental",
    "provisioningState": "Succeeded",
    "timestamp": "2019-09-19T23:04:19.4101361Z",
    "duration": "PT23M3.5751283S",
    "correlationId": "78a0d6e9-41e9-4ccf-84f5-b32c07c43133",
    "providers": [
      {
        "namespace": "Microsoft.DocumentDB",
        "resourceTypes": [
          {
            "resourceType": "databaseAccounts",
            "locations": [
              "westus"
            ]
          }
        ]
      }
    ],
```
and
```
    "operationId": "CAAE9BA31E33805A",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Succeeded",
      "timestamp": "2019-09-19T23:04:17.8095322Z",
      "duration": "PT22M55.9169518S",
      "trackingId": "3216843a-22d5-44ea-84ee-d50341eb84d3",
      "statusCode": "OK",
```
