### ISSUE TITLE
CLI fails with MissingSectionHeaderError

### ISSUE THREAD

**Issue by staff0rd** [Azure/azure-cli#9311]
v2.0.63

**Describe the bug**
cli doesn't work

**To Reproduce**
`az`

**Expected behavior**
Any non-error result

**Environment summary**
MSI, win10

**Additional context**
I'm getting the same error as mentioned [here](https://github.com/MicrosoftDocs/azure-docs-powershell/issues/827).  I've followed the workaround mentioned [here](https://github.com/Azure/azure-cli/issues/8252), including uninstalling, deleting that directory and reinstalling, but it still doesn't work.  For now I have to run az inside a docker container.

The output i'm getting from any `az` is as follows:
```cmd
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli\azure\cli\__main__.py", line 33, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\__init__.py", line 522, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\__init__.py", line 55, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\cloud.py", line 310, in get_active_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\cloud.py", line 299, in get_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\cloud.py", line 248, in _get_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-68v0_w99\azure-cli-core\azure\cli\core\cloud.py", line 270, in get_clouds
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\stafford\\.azure\\clouds.config', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by tjprescott** [comment]
@staff0rd it seems like your `clouds.config` file might be corrupt. If you delete `C:\Users\stafford\.azure\clouds.config` does the CLI run?

**Comment by staff0rd** [comment]
That solved it, thankyou!

**Comment by tjprescott** [comment]
Glad to hear it @staff0rd. Reopening this as I think we should catch this error and immediately reset the cloud config instead of dropping a stack trace.

**Comment by oc3lot** [comment]
I'm having this issue too, and on this thread's advice, I deleted clouds.config. Unfortunately, the stack trace still dumps. 
`Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 539, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 28, in <module>
    from azure.cli.core.extension import get_extension
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/__init__.py", line 16, in <module>
    az_config = CLIConfig(config_dir=GLOBAL_CONFIG_DIR, config_env_var_prefix=ENV_VAR_PREFIX)
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 65, in __init__
    self._config_file_chain.append(_ConfigFile(self.config_dir, self.config_path))
  File "/opt/az/lib/python3.6/site-packages/knack/config.py", line 145, in __init__
    self.config_parser.read(config_path)
  File "/opt/az/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/opt/az/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/kelvin/.azure/config', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`

**Comment by limingu** [comment]
@oc3lot , the '/home/kelvin/.azure/config' file is corrupt. You can try delete '/home/kelvin/.azure/config' and run the command again.
