### ISSUE TITLE
app service update issue with sku

### ISSUE THREAD

**Issue by doradoe1** [Azure/azure-cli#9318]
## Describe the bug

**Command Name**
`az appservice plan update`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'sku'Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/core/commands/arm.py", line 512, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.0.62/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1192, in update_app_service_plan
    sku_def = instance.sku
AttributeError: 'NoneType' object has no attribute 'sku'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az appservice plan update --name {} --number-of-workers {} --sku {} --resource-group {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.7.3
Shell: bash

azure-cli                         2.0.62 *

```

**Comment by panchagnula** [comment]
@doradoe1 what is the SKU value you are using in the command.

**Comment by doradoe1** [comment]
I tried F1 and B1.
________________________________

**Comment by panchagnula** [comment]
Please try Basic and Free for now & see if that unblocks you.

**Comment by panchagnula** [comment]
@doradoe1 I did try this out & wasn't able to repro it with either F1 or B1 . what is your original SKU of the AppService Plan , that you are trying to update this from? Also can you try the latest version of the CLI released. Thank you.

**Comment by doradoe1** [comment]
I solved it. Thanks!!
________________________________

**Comment by panchagnula** [comment]
@doradoe1 great that this is solved. Can you please share how you solved this & also close the issue if this not something we need to track as an issue anymore. Thank you.
