### ISSUE TITLE
Failed to Create Service Bus Topic on AZ cli as of 2.0.64

### ISSUE THREAD

**Issue by rachelvwood** [Azure/azure-cli#9319]
**Describe the bug**
When "az topic create" is run, it errors out, saying "get() missing 1 required positional argument: 'topic_name'

`> az servicebus topic create --subscription (subscription) --name (topic-name) --namespace-name (namespace-name) --resource-group (resource-group) --default-message-time-to-live (ttl) --max-size (size) --enable-duplicate-detection False --duplicate-detection-history-time-window (time-window) --output json
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: get() missing 1 required positional argument: 'topic_name'
Traceback (most recent call last):
  File "/tmp/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/tmp/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/tmp/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 453, in default_command_handler
    return op(**command_args)
  File "/tmp/lib/python3.6/site-packages/azure/cli/command_modules/servicebus/custom.py", line 188, in cli_sbtopic_create
    getnamespace = client.get(resource_group_name=resource_group_name, namespace_name=namespace_name)
TypeError: get() missing 1 required positional argument: 'topic_name'`

**To Reproduce**
Run "az topic create" with appropriate arguments

**Expected behavior**
Service bus creation with no errors

**Environment summary**
Install method: pip
cli version: 2.0.64
os version: VSTS Hosted agents, ubuntu 1604
shell: bash

**Additional context**
We pinned the cli to 2.0.63, and the same command runs successfully.

**Comment by jonbjo** [comment]
I get the exact same error.

**Environment summary**
Install method: brew
cli version: 2.0.64
os version: Mac OS X 10.14.4
shell: bash

**Comment by rachelvwood** [comment]
I did some further investigation, and I only see this problem when I specify --max-size

**Comment by v-Ajnava** [comment]
@v-Ajnava

**Comment by v-Ajnava** [comment]
@rachelvwood , the issue is in code. will fix and updated the thread.

**Comment by robinrogne** [comment]
I also have the same error. At the moment my deployment process is stalled. Please fix this asap.

**Comment by droessmj** [comment]
Can recreate as well, and can confirm dropping --max-size resolves the issue.
