### ISSUE TITLE
az storage blob upload-batch: error: too many values to unpack

### ISSUE THREAD

**Issue by priya0917** [Azure/azure-cli#9422]
Trying to upload .storybook folder using "az storage blob upload-batch --account-key $(StorageAccountKey) --destination $(StorageAccountDest) --source .storybook'"which is created  after npm run storybook(using VSTS)  but its saying "az storage blob upload-batch: error: too many values to unpack"

**Comment by adewaleo** [comment]
Please try to supply as much information as you can. It would help us help you!

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Add any other context about the problem here.

**Comment by limingu** [comment]
@priya0917 in your command there is no --account-name. Did you miss that? Or you have define the AZURE_STORAGE_ACCOUNT env, did you?
Also, can you rerun the command with --debug and sent the details to limgu@microsoft.com? So I can see what is issue. I can't repro this issue now.

**Comment by priya0917** [comment]
While ruuning the below mentioned script in VSTS to deploy storybook to azure blob:

resources:
- repo: self
trigger:
- master
queue:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Install Node JS'
  inputs:
    versionSpec: 10.14.2
- script: |
    npx -p @storybook/cli sb init
    yarn build-storybook --no-dll
  displayName: 'npm install, build story book'
- task: AzureCLI@1
  displayName: 'Deploy To Dev Blob'
  inputs:
    azureSubscription: 'dmp-arm'
    scriptLocation: inlineScript
    inlineScript: 'az storage blob upload-batch  --account-key $(StorageAccountKey)  --destination $(StorageAccountDest) --source .storybook --account-name dxpstorybook'


getting error : 
az storage blob upload-batch: error: too many values to unpack (expected 2)
INFO: telemetry.save : Save telemetry record of length 2562 in cache
WARNING: telemetry.check : Negative: The /home/vsts/work/_temp/.azclitask/telemetry.txt was modified at 2019-05-18 15:15:18.823185, which in less than 600.000000 s
##[error]Script failed with error: Error: /bin/bash failed with return code: 2
[command]/usr/bin/az account clear
##[section]Finishing: Deploy To Dev Blob

**Comment by priya0917** [comment]
az storage blob upload-batch: error: too many values to unpack (expected 2)
INFO: telemetry.save : Save telemetry record of length 2562 in cache
WARNING: telemetry.check : Negative: The /home/vsts/work/_temp/.azclitask/telemetry.txt was modified at 2019-05-18 15:15:18.823185, which in less than 600.000000 s
##[error]Script failed with error: Error: /bin/bash failed with return code: 2
[command]/usr/bin/az account clear
##[section]Finishing: Deploy To Dev Blob

**Comment by feltonjsd** [comment]
I recently had the same error : az storage blob upload-batch: error: too many values to unpack (expected 2)

--destination "https://xxfilesharename.filestore.file.core.windows.net\xxvolname" 

I found it to be a problem with my destination parameter as I had an "\" instead of a "/" in my URL. Double check your destination parameter is set up correctly. Hope it helps

**Comment by Juliehzl** [comment]
@priya0917 I try to reproduce your problem in Azure DevOps. But I don't have your issues during my reproduction. I think the difference is the definition of variables. Can you double check your definition like @feltonjsd  said?

**Comment by Juliehzl** [comment]
@priya0917 Do you still have the problem? If not, I may close this issue.

**Comment by cforce** [comment]
I have the same issue an np explanation why it happens..

2022-01-13T07:06:28.8065550Z DEBUG: cli.knack.cli: Command arguments: ['storage', 'blob', 'copy', 'start-batch', '--subscription', 'XXXXXXXXXXXXXXXXXXXXXX', '--destination-container', 'vhds', '--account-name', 'XXXXXXXXXXXXXXXX', '--account-key', 'XXXXXXXXXXXXXXXX', '--source-uri', 'https://XXXXXXXX.z8.blob.storage.azure.net/XXXXXXX/abcd?sv=2018-03-28&sr=b&si=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', '--query', 'id', '-o', 'tsv', '--debug']
2022-01-13T07:06:28.8067902Z DEBUG: cli.knack.cli: __init__ debug log:
2022-01-13T07:06:28.8068515Z Cannot enable color.
2022-01-13T07:06:28.8069118Z DEBUG: cli.knack.cli: Event: Cli.PreExecute []
2022-01-13T07:06:28.8070289Z DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fcb7bd0ec80>, <function OutputProducer.on_global_arguments at 0x7fcb7bc40730>, <function CLIQuery.on_global_arguments at 0x7fcb7bbd0840>]
2022-01-13T07:06:28.8258011Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
2022-01-13T07:06:28.8260766Z DEBUG: cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
2022-01-13T07:06:28.8262159Z DEBUG: cli.azure.cli.core: Loading command modules:
2022-01-13T07:06:28.8263491Z DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
2022-01-13T07:06:28.8664746Z DEBUG: cli.azure.cli.core: storage                   0.040        54       251
2022-01-13T07:06:28.8666038Z DEBUG: cli.azure.cli.core: Total (1)                 0.040        54       251
2022-01-13T07:06:28.8666776Z DEBUG: cli.azure.cli.core: Loaded 54 groups, 251 commands.
2022-01-13T07:06:28.8667863Z DEBUG: cli.azure.cli.core: Found a match in the command table.
2022-01-13T07:06:28.8669142Z DEBUG: cli.azure.cli.core: Raw command  : storage blob copy start-batch
2022-01-13T07:06:28.8670241Z DEBUG: cli.azure.cli.core: Command table: storage blob copy start
2022-01-13T07:06:28.8671134Z DEBUG: cli.azure.cli.core: remaining    :                         batch
2022-01-13T07:06:28.8671994Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fcb7b6de0d0>]
2022-01-13T07:06:28.8673701Z DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/app/.azure/commands/2022-01-13.07-06-28.storage_blob_copy_start-batch.9450.log'.
2022-01-13T07:06:28.8675217Z INFO: az_command_data_logger: command args: storage blob copy start-batch --subscription {} --destination-container {} --account-name {} --account-key {} --source-uri {} --query {} -o {} --debug
2022-01-13T07:06:28.8676538Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fcb7b68b048>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fcb7b66c7b8>]
2022-01-13T07:06:29.2055349Z DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
2022-01-13T07:06:29.2057513Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 597, in _get_attr
2022-01-13T07:06:29.2058601Z     op = getattr(op, part)
2022-01-13T07:06:29.2060417Z AttributeError: module 'azure.mgmt.storage.v2021_06_01.models' has no attribute 'AccountType'
2022-01-13T07:06:29.2060886Z 
2022-01-13T07:06:29.2078235Z DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
2022-01-13T07:06:29.2079928Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 597, in _get_attr
2022-01-13T07:06:29.2080720Z     op = getattr(op, part)
2022-01-13T07:06:29.2081837Z AttributeError: module 'azure.mgmt.storage.v2021_06_01.models' has no attribute 'ListKeyExpand'
2022-01-13T07:06:29.2082289Z 
2022-01-13T07:06:29.2701615Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
2022-01-13T07:06:29.2702605Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fcb7b66c840>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fcb7b66c950>]
2022-01-13T07:06:29.2725712Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
2022-01-13T07:06:29.2726359Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
2022-01-13T07:06:29.2773087Z DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fcb7bc407b8>, <function CLIQuery.handle_query_parameter at 0x7fcb7bbd08c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fcb7b66c730>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fcb7b66c8c8>]
2022-01-13T07:06:29.2775256Z INFO: cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
2022-01-13T07:06:29.2776554Z INFO: cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
2022-01-13T07:06:29.2810695Z ERROR: cli.azure.cli.core.azclierror: too many values to unpack (expected 2)
2022-01-13T07:06:29.2811647Z ERROR: az_command_data_logger: too many values to unpack (expected 2)
2022-01-13T07:06:29.2812602Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcb7b6de2f0>]
2022-01-13T07:06:29.2816669Z INFO: az_command_data_logger: exit code: 2
2022-01-13T07:06:29.2817541Z INFO: cli.__main__: Command ran in 0.604 seconds (init: 0.128, invoke: 0.476)
2022-01-13T07:06:29.3069081Z INFO: telemetry.save: Save telemetry record of length 3156 in cache
2022-01-13T07:06:29.3070595Z WARNING: telemetry.check: Negative: The /home/app/.azure/telemetry.txt was modified at 2022-01-13 07:05:49.067858, which in less than 600.000000 s
