### ISSUE TITLE
az network vnet show command fails with `ImportError: No module named v2019_02_01.operations`

### ISSUE THREAD

**Issue by bigmyx** [Azure/azure-cli#9446]
## Describe the bug

**Command Name**
`az network vnet show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


No module named v2019_02_01.operations
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 482, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 275, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 282, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/lib/python2.7/site-packages/knack/commands.py", line 92, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 707, in generic_show_arguments_loader
    cmd_args = get_arguments_loader(context, getter_op, operation_group=kwargs.get('operation_group'))
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 388, in get_arguments_loader
    getter_args = dict(extract_args_from_signature(context.get_op_handler(getter_op, operation_group=operation_group),
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 504, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named v2019_02_01.operations
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet show -g {} -n {}`

## Environment Summary
```
Linux-4.9.125-linuxkit-x86_64-with
Python 2.7.14
Shell: bash

azure-cli 2.0.61 *

```

**Comment by tjprescott** [comment]
It looks like you tried to selectively update your network module, which is not supported. You must update the entire CLI.
