### ISSUE TITLE
az storage blob sync error: File is not a zip file

### ISSUE THREAD

**Issue by richardmansfield** [Azure/azure-cli#9525]
## Describe the bug

**Command Name**
`az storage blob sync`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


File is not a zip file
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 609, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 240, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 183, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 36, in storage_blob_sync
    azcopy = _azcopy_blob_client(cmd, client)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/azcopy.py", line 54, in _azcopy_blob_client
    return AzCopy(creds=blob_client_auth_for_azcopy(cmd, client))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 48, in __init__
    _urlretrieve(file_url, install_location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/azcopy/util.py", line 187, in _urlretrieve
    zip_file = zipfile.ZipFile(io.BytesIO(req.read()))
  File "/opt/az/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/opt/az/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage blob sync -c {} --account-name {} -s {} -d {}`

## Expected Behavior
Files in the local source path are transferred to the destination path in the container

## Environment Summary
```
Linux-4.4.0-142-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.65

```
Tested using the mcr.microsoft.com/azure-cli docker image, and using an ubuntu 18.04 docker with azure-cli package installed from the packages.microsoft.com apt repo.

**Comment by adewaleo** [comment]
@limingu we should catch this exception and handle it properly.

@richardmansfield it seems like your source file should be a zip file but it is not...

**Comment by richardmansfield** [comment]
I'm not sure why it thinks my source file should be a zip file, does az
storage blob sync command only work on zip files? I thought it would sync a
whole folder. It'd be good to clear this up in the documentation; "az
storage blob sync --help" doesn't mention zip files at all.

**Comment by Arnavion** [comment]
It's not that `az storage blob sync` only works with zip files. It's that it downloads `azcopy` and expects that download to be a zip file (that it then extracts `azcopy` from).

**Comment by limingu** [comment]
This is bug for Linux. I will fix it soon.
