### ISSUE TITLE
az login --identity fails in AKS with aad-pod-identity

### ISSUE THREAD

**Issue by Bowbaq** [Azure/azure-cli#9537]
**Describe the bug**
`az login --identity` sometimes fails with a stacktrace when used in AKS in combination with [`aad-pod-identity`](https://github.com/Azure/aad-pod-identity)

```
az login --identity
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 111, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 318, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthentication(resource=resource)
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 576, in __init__
    self.set_token()
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 584, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 632, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 669, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

**To Reproduce**
- Setup an AKS cluster (we're on K8S 1.11.9) with aad-pod-identity (we use the helm chart)
- Start a pod using the `microsoft/azure-cli:latest` docker image, with the proper labeling to assign a MSI on startup, and run `az login --identity` as the command

**Expected behavior**
`az login --identity` should always succeed on a node with a MSI attached. If the MSI is not yet attached due to lag in `aad-pod-identity`, `azure-cli` should exit cleanly with a non-zero exit code

**Environment summary**
- `microsoft/azure-cli:latest`
- `bash`

**Additional context**
May be related to https://github.com/Azure/aad-pod-identity/issues/206

**Comment by brendandburns** [comment]
I don't think this is a bug in the CLI per-se (though perhaps there could be better error handling) but I think aad-pod-identity is returning an HTTP error for some reason (which may be a bug in AAD Pod Identity

**Comment by palma21** [comment]
@kkmsft @aramase

**Comment by AdilOoze** [comment]
Any update on this?

**Comment by yonzhan** [comment]
@kkmsft @aramase any update?

**Comment by aramase** [comment]
Opened an issue to track the required change - https://github.com/Azure/aad-pod-identity/issues/584

**Comment by anshupitlia** [comment]
do we have an update on this?

**Comment by yonzhan** [comment]
@aramase

**Comment by vsabella** [comment]
We are reproducing this issue as well. The issue is in the delay in assigning the identity.

**Comment by SaurabhSharma-MSFT** [comment]
@aramase @vsabella Any latest developments on this issue.

**Comment by aramase** [comment]
@SaurabhSharma-MSFT What is the issue you're facing? The changes for error response codes have been merged and released at least a year back and this is a really old issue. If you're having issues with pod identity I would recommend opening an issue with details here: https://github.com/Azure/aad-pod-identity/issues. If it's with azure-cli then maybe provide more information for the error in the issue here?

**Comment by SaurabhSharma-MSFT** [comment]
@aramase Thanks for your response. I am not facing any issues however wanted to check on the status of this issue and no updates were made to this issue. Thanks for the confirmation.
@Bowbaq It looks like this issue has been resolved and so we are proceeding with the closure of this issue. Please open a new issue if you have any other questions.

Thanks
Saurabh
