### ISSUE TITLE
public access container creation fails

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#9542]
## public access container creation fails

**Command Name**
`sudo docker run -it -v /nix:/nix -v /tmp/azure-cli:/tmp/azure-cli -e AZURE_CONFIG_DIR=/tmp/azure-cli -e 'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=nixos0westus2aff271ee;AccountKey=pizza==' microsoft/azure-cli:latest az storage container create --name vhds --public-access container --subscription aff271ee-e9be-4441-b9bb-42f5af4cbaeb`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


One of the headers specified in the request is not supported. ErrorCode: UnsupportedHeader
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>UnsupportedHeader</Code><Message>One of the headers specified in the request is not supported.
RequestId:dae3ef53-601c-0045-3cf6-198066000000
Time:2019-06-03T10:25:30.5783114Z</Message><HeaderName>x-ms-blob-public-access</HeaderName></Error>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 609, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 240, in new_handler
    handler(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 183, in handler
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 633, in create_container
    _dont_fail_on_exist(ex)
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_error.py", line 88, in _dont_fail_on_exist
    raise error
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 630, in create_container
    self._perform_request(request, expected_errors=[_CONTAINER_ALREADY_EXISTS_ERROR_CODE])
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 381, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 306, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 292, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: One of the headers specified in the request is not supported. ErrorCode: UnsupportedHeader
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>UnsupportedHeader</Code><Message>One of the headers specified in the request is not supported.
RequestId:dae3ef53-601c-0045-3cf6-198066000000
Time:2019-06-03T10:25:30.5783114Z</Message><HeaderName>x-ms-blob-public-access</HeaderName></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

see above

## Environment Summary
```
Linux-4.19.34-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.65

```

**Comment by limingu** [comment]
@colemickens can you confirm that you pass the correct account key in the command? In the issue, 'AccountKey=pizza==' is that you replace the real key with 'pizza=='.

**Comment by colemickens** [comment]
Yes, I'm using the right key, the command works fine without that flag.

**Comment by limingu** [comment]
That flag is referred to 'AccountKey'? If it works fine, why do you add that flag?

**Comment by colemickens** [comment]
What? I am setting the account key correctly. The error message has nothing to do with the account key being wrong.

The az storage commands execute fine. The container create commands works fine, unless I add the `--public-access` flag, as I wrote in the Issue, and which the error message is referencing.

**Comment by limingu** [comment]
I can't reproduce the issue.

@colemickens can you please rerun the command with --debug and send the logs to limgu@microsoft.com? So I can look into. Thanks.

**Comment by colemickens** [comment]
Another azure edge case:

>Public access to a container containing page blobs in Premium Storage is not permitted. Calling Set Container ACL with the x-ms-blob-public-access header returns error code 400 (UnsupportedHeader). You can, however, obtain public access for Premium Storage by creating a SAS URI with the right permissions and an infinite expiration time.

I guess if I want to distribute public images I'm forced to use slow storage.
