### ISSUE TITLE
az aks get-credentials --resource-group aimcorecluster --name aimcoreresourcegrp

### ISSUE THREAD

**Issue by eashweragero101** [Azure/azure-cli#9572]
error 

 command failed with an unexpected error. Here is the traceback:

argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 535, in _retrieve_token
    account[_TENANT_ID], resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 905, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 352, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 177, in _refresh_entry_if_necessary
    return self._refresh_expired_entry(entry)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 153, in _refresh_expired_entry
    token_response = self._refresh_function(entry, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 138, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 344, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 37, in signed_session
    if 'AADSTS70008:' in (getattr(err, 'error_response', None) or {}).get('error_description') or '':
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 26, in signed_session
    scheme, token, _ = self._token_retriever()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 535, in _retrieve_token
    account[_TENANT_ID], resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 905, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 352, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 177, in _refresh_entry_if_necessary
    return self._refresh_expired_entry(entry)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 153, in _refresh_expired_entry
    token_response = self._refresh_function(entry, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 138, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 344, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1667, in aks_get_credentials
    credentialResults = client.list_cluster_user_credentials(resource_group_name, name)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py", line 429, in list_cluster_user_credentials
    response = self._client.send(request, stream=False, **operation_config)
  File "/opt/az/lib/python3.6/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/requests.py", line 68, in send
    request.context.session = session = self._creds.signed_session()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 37, in signed_session
    if 'AADSTS70008:' in (getattr(err, 'error_response', None) or {}).get('error_description') or '':
TypeError: argument of type 'NoneType' is not iterable

**Comment by seanmck** [comment]
No clear repro. Please reopen if you have one.
