### ISSUE TITLE
All az openshift commands fail with a python traceback with 2.0.66

### ISSUE THREAD

**Issue by mgahagan73** [Azure/azure-cli#9667]
## Describe the bug
All az openshift commands fail with a python traceback. This appeared to start with 2.0.66 and I've observed it on both Fedora 30 and RHEL 7.6. In both cases az cli was installed from the Microsoft Azure yum repo. Other az sub-commands do not appear to be affected. 
**Command Name**
`az openshift -h`
commands such as `az openshift scale` are also affected and the traceback is similar. 
 
**Errors:**
```
The operation 'azure.cli.command_modules.acs.custom#openshift_scale' is invalid.
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 507, in execute
    parsed_args = self.parser.parse_args(args)
python2.7/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
usr/lib64/python2.7/argparse.py, ln 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
azure/cli/core/__init__.py, ln 470, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
azure/cli/core/__init__.py, ln 511, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#openshift_scale' is invalid.
```

## To Reproduce:

Install latest az-cli on Fedora 30 or RHEL 7.6. I have not confirmed if other Red Hat/Fedora releases are affected but I can test those if needed. 

run: (or any other az openshift command)
- `az openshift -h`

## Expected Behavior
no traceback, help information is displayed in the case of `az openshift -h`

## Environment Summary
```
Linux-5.1.8-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 2.7.16
Shell: bash

azure-cli 2.0.66

```

**Comment by julienstroheker** [comment]
@marstr can this be related to #7523 ? thanks

**Comment by marstr** [comment]
Nope! #7523 only impacts SUSE based distributions, Fedora is more directly related to Red Hat than that.

**Comment by mgahagan73** [comment]
azure-cli-2.0.64-1.el7.x86_64 appears to work fine on Fedora 30:
I installed it via:
dnf -y install https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.0.64-1.el7.x86_64.rpm

I noticed one difference in installing this package is that it did not pull in python-wheel-wheel and python2-virtualenv as dependancies while 2.0.66 did. 
 
[m@localhost OCP-23927]$ rpm -q azure-cli
azure-cli-2.0.64-1.el7.x86_64
[m@localhost OCP-23927]$ az openshift -h

Group
    az openshift : Manage Azure Red Hat OpenShift Services.

Commands:
    create : Create a new managed OpenShift cluster.
    delete : Delete a managed OpenShift cluster.
    list   : List managed OpenShift clusters.
    scale  : Scale the compute pool in a managed OpenShift cluster.
    show   : Show the details for a managed OpenShift cluster.
    wait   : Wait for a managed OpenShift cluster to reach a desired state.

**Comment by marstr** [comment]
Curious, I just switched over to my Fedora 29 machine to try to repro this. `az openshift -h` seemed to behave fine for me on my main machine. I also tried installing 2.0.66 of the CLI on a fedora:30 container image in podman, seemed to work for me there to. Anything else you can tell me about your environment, @mgahagan73?

For the moment I'm going to assume this is a packaging/installation error, not directly related to the ACS command_module. I'll reassign this issue to myself for the time being.

**Comment by mgahagan73** [comment]
@marstr Thanks for the quick response, it turns out that I installed a number of python2 packages on both my F30 system and the RHEL 7.6VM as they were required for some testing I was doing. One of those packages broke all the azure-cli openshift commands. There were quite a few packages and dependences and once I removed them I was able to get 'az openshift -h' working again. I think you are correct in that it is some sort of installation or packaging issue. I saved the list of packages I removed to "fix" the problem, but at the moment I don't have they cycles to go through each one to find what broke az openshift. In the F30 case it was something from the distro, in the 7.6 case it came from pip. I can share the list of packages here if you want but if you need to close this out as a one-off installation issue then I understand. Prior to removing the python packages the last version of azcli that worked for me on those two environments was 2.0.65.

**Comment by dcfsc** [comment]
On CentOS Linux release 7.6.1810 (Core)

```
az aks get-credentials --resource-group ...rg \
    --name ...aks01 --subscription xxxx-xxxx-xxx-xxx 
```
failed with a very similar error.

`yum remove azure-cli` and `yum install azure-cli-2.0.64-1.el7` seems to have fixed the issue, so 2.0.66 seems problematic for everything, not just `az openshift`.

**Comment by marstr** [comment]
@dcfsc, can you tell me anything more about your environment? I just install fresh on a Centos 7 container, and am able to use `aks` commands as expected.

**Comment by dcfsc** [comment]
Mine has been upgraded several times, so def not fresh.  Last system update was month ago?

I have pyenv installed (!), and 
$ pyenv versions
  system
  3.5.6
  3.6.7
* 3.7.1 (set by /home/dc/.pyenv/version)
$ pyenv global  system
$ python --version
Python 2.7.5

So system == 2.7.5
I am not a Python guy, so anything else that might be helpful?

**Comment by marstr** [comment]
Thanks for getting back to me, @dcfsc. That all looks to be in order.

Could you run the following commands and show me the output?

``` bash
pip check
pip list | grep virtualenv
```
Also, if you could run `az --version` and use the absolute path of the python version it mentions to run:

``` bash
${AZURE_CLI_PYTHON} -m pip list 
```

**Comment by dcfsc** [comment]
Sure no problem. Thanks for the help!

```
$ pip check
No broken requirements found.
$ pip list | grep virtualenv
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ az --version
...
Python location '/usr/bin/python2'
Extensions directory '/home/dchwalis/.azure/cliextensions'
Python (Linux) 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
$ export AZURE_CLI_PYTHON='/usr/bin/python2'
$ ${AZURE_CLI_PYTHON} -m pip list 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package                          Version   
-------------------------------- ----------
adal                             1.2.1     
ansible                          2.7.10    
ansible-container                0.9.2     
ansible-tower-cli                3.2.0     
argcomplete                      1.9.4     
azure-cli-nspkg                  3.0.2     
azure-nspkg                      2.0.0     
Babel                            0.9.6     
backports.ssl-match-hostname     3.5.0.1   
Beaker                           1.5.4     
blivet                           0.61.15.72
Brlapi                           0.6.0     
cachetools                       2.0.1     
certifi                          2018.1.18 
cffi                             1.6.0     
chardet                          3.0.4     
click                            6.7       
colorama                         0.3.9     
configobj                        4.7.2     
configparser                     3.7.3     
configshell-fb                   1.1.23    
coverage                         3.6b3     
cryptography                     1.7.2     
cupshelpers                      1.0       
decorator                        3.4.0     
di                               0.3       
dictdiffer                       0.7.0     
dnspython                        1.12.0    
docker                           2.6.1     
docker-py                        1.10.6    
docker-pycreds                   0.3.0     
docker-squash                    1.0.6     
ecdsa                            0.13      
EditorConfig                     0.12.1    
entrypoints                      0.3       
enum34                           1.0.4     
ethtool                          0.8       
firstboot                        19.5      
fros                             1.0       
funcsigs                         1.0.2     
futures                          3.1.1     
google-auth                      1.3.0     
gssapi                           1.2.0     
gyp                              0.1       
httplib2                         0.9.2     
idna                             2.8       
iniparse                         0.4       
initial-setup                    0.3.9.43  
iotop                            0.6       
ipaddr                           2.1.11    
ipaddress                        1.0.19    
IPy                              0.75      
isodate                          0.6.0     
javapackages                     1.0.0     
Jinja2                           2.10      
jmespath                         0.9.3     
jsbeautifier                     1.6.14    
jsonpointer                      1.9       
jwcrypto                         0.4.2     
kerberos                         1.1       
keyring                          18.0.0    
kitchen                          1.1.1     
kmod                             0.1       
knack                            0.3.3     
kubernetes                       6.0.0     
langtable                        0.0.31    
libvirt-python                   4.5.0     
lxml                             3.2.1     
M2Crypto                         0.21.1    
Mako                             0.8.1     
MarkupSafe                       1.0       
mercurial                        2.6.2     
mock                             2.0.0     
msrest                           0.4.29    
msrestazure                      0.4.31    
netaddr                          0.7.5     
netifaces                        0.10.4    
nose                             1.3.7     
ntplib                           0.3.2     
numpy                            1.7.1     
oauthlib                         2.1.0     
openlmi                          0.5.0     
openshift                        0.6.1     
packaging                        16.8      
paramiko                         1.16.1    
passlib                          1.7.1     
Paste                            1.7.5.1   
pbr                              1.10.0    
pcp                              4.1       
perf                             0.1       
Pillow                           2.0.0     
pip                              19.0.3    
ply                              3.4       
policycoreutils-default-encoding 0.1       
pyasn1                           0.4.2     
pyasn1-modules                   0.2.1     
pycparser                        2.14      
pycrypto                         2.6.1     
pycups                           1.9.63    
pycurl                           7.19.0    
Pygments                         2.2.0     
pygobject                        3.22.0    
pygpgme                          0.3       
pyinotify                        0.9.4     
PyJWT                            1.7.1     
pykickstart                      1.99.66.19
pyliblzma                        0.5.3     
pyOpenSSL                        0.13.1    
pyparsing                        1.5.6     
pyparted                         3.9       
pysmbc                           1.0.13    
python-augeas                    0.5.0     
python-dateutil                  2.6.1     
python-dmidecode                 3.10.13   
python-keyczar                   0.71rc0   
python-ldap                      2.4.15    
python-linux-procfs              0.4.9     
python-meh                       0.25.2    
python-nss                       0.16.0    
python-string-utils              0.6.0     
python-yubico                    1.2.3     
pytz                             2016.10   
pyudev                           0.21.0    
pyusb                            1.0.0b1   
pywbem                           0.7.0     
pyxattr                          0.5.1     
PyYAML                           3.12      
qrcode                           5.0.1     
requests                         2.21.0    
requests-oauthlib                1.0.0     
rsa                              3.4.2     
rtslib-fb                        2.1.63    
ruamel.ordereddict               0.4.13    
ruamel.yaml                      0.15.35   
scdate                           1.10.6    
schedutils                       0.4       
SecretStorage                    2.3.1     
seobject                         0.1       
sepolicy                         1.1       
setroubleshoot                   1.1       
setuptools                       38.5.1    
six                              1.10.0    
slip                             0.4.0     
slip.dbus                        0.4.0     
SSSDConfig                       1.16.2    
structlog                        18.1.0    
subprocess32                     3.2.6     
tabulate                         0.8.2     
targetcli-fb                     2.1.fb46  
Tempita                          0.5.1     
typing                           3.6.6     
urlgrabber                       3.10      
urllib3                          1.24.1    
urwid                            1.1.1     
virtualenv                       16.0.0    
websocket-client                 0.35.0    
wheel                            0.31.1    
yum-langpacks                    0.4.2     
yum-metadata-parser              1.1.4     
```

I updated to the latest azure-cli
```
--> Running transaction check
---> Package azure-cli.x86_64 0:2.0.64-1.el7 will be updated
---> Package azure-cli.x86_64 0:2.0.67-1.el7 will be an update
--> Finished Dependency Resolution
...
Updating:
 azure-cli                                        x86_64                                        2.0.67-1.el7                                           azure-cli                                         27 M
...
  Updating   : azure-cli-2.0.67-1.el7.x86_64 1/2 
  Cleanup    : azure-cli-2.0.64-1.el7.x86_64  2/2 
  Verifying  : azure-cli-2.0.67-1.el7.x86_64  1/2 
  Verifying  : azure-cli-2.0.64-1.el7.x86_64  2/2 
Updated:
  azure-cli.x86_64 0:2.0.67-1.el7      
```

and got the original error:
```
$ az aks get-credentials  --resource-group XXXrg --name prduse2aks  --subscription XXXX-XXX
The command failed with an unexpected error. Here is the traceback:

The operation 'azure.cli.command_modules.acs.custom#aks_get_credentials' is invalid.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 488, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 276, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 288, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 473, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 520, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_get_credentials' is invalid.
```
I used pyenv to flip back to Python 3.7.1
The `get-credentials` failed with the same stack.

I also tried using a new K8S cluster in a different subscription, same result.

**Comment by marstr** [comment]
I _think_ I figured it out. I have some experiments to run with how to resolve it, but basically if you look here:
https://github.com/Azure/azure-cli/blob/7c5f44151010b4b64d822f8cbe3e725f3525a448/scripts/release/rpm/azure-cli.spec#L40-L65

I'm creating a virtual environment, but throwing away bits of it that don't play nice with `rpm`. I think that the `pip` reinstalls of our namespace packages aren't getting invoked correctly. I'll need to experiment with some fixes. In the meantime, RPM based Linux users (myself included unfortunately, as I'm a Fedora user) should probably stick to 2.0.65 of the Azure CLI. I'll see if I can't figure out a work around for folks who need the latest functionality.

**Comment by marstr** [comment]
Reassigning to @zikalino as I've moved to the Notification Hubs team.

**Comment by yonzhan** [comment]
add to S166.

**Comment by fengzhou-msft** [comment]
RPM is now using python 3 and this issue can not be replicated with azure cli 2.2.0.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen it if you still have the same issue with the latest Azure CLI version.
