### ISSUE TITLE
Running "az webapp --help" causes python error.  Installed extension - same result.

### ISSUE THREAD

**Issue by rturnbull1977** [Azure/azure-cli#9673]
## Describe the bug

**Command Name**
`az webapp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


The operation 'azure.cli.command_modules.appservice.custom#start_webapp' is invalid.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 507, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/parser.py", line 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
  File "/usr/lib64/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1908, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python2.7/argparse.py", line 1885, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python2.7/argparse.py", line 1794, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 1090, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1926, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python2.7/argparse.py", line 1866, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 1794, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 994, in __call__
    parser.print_help()
  File "/usr/lib64/python2.7/argparse.py", line 2327, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/parser.py", line 156, in format_help
    super(AzCliCommandParser, self).format_help()
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/parser.py", line 249, in format_help
    is_group)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/_help.py", line 148, in show_help
    super(AzCliHelp, self).show_help(cli_name, nouns, parser, is_group)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/help.py", line 691, in show_help
    else self.group_help_cls(self, delimiters, parser)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/help.py", line 232, in __init__
    child.load(options)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/_help.py", line 242, in load
    loader.versioned_load(self, options)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/_help_loaders.py", line 153, in versioned_load
    super(CliHelpFile, help_obj).load(parser)  # pylint:disable=bad-super-call
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/help.py", line 177, in load
    description = getattr(options, 'description', None)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/parser.py", line 240, in __getattribute__
    if callable(self._description) else self._description
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 470, in default_description_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 511, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.appservice.custom#start_webapp' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp --help`

## Environment Summary
```
Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.66

Extensions:
storage-preview 0.2.2

```

**Comment by panchagnula** [comment]
Closing this since this is not something we are able to repro on our end
