### ISSUE TITLE
Failed to establish a new connection: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by makokui** [Azure/azure-cli#9693]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

From 'https://github.com/Azure/azure-cli/issues/9515', I got detailed information and repost it with the appropriate template.
It is regularly executing below Azure CLI commands from Azure Virtual Machine. This command was executed from March 2019, and the error occurred about once or twice a month before 5/19, but the error frequency has recently increased rapidly.

**Describe the bug**
The following az command fail frequently.
```
az monitor metrics list --resource /subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Cache/Redis/xxxxxxxxxx --start-time 2019-06-12T07:05:53Z --end-time 2019-06-12T07:06:53Z --metrics cachehits cachemisses cacheRead cacheWrite connectedclients percentProcessorTime evictedkeys expiredkeys getcommands operationsPerSecond serverLoad setcommands totalkeys totalcommandsprocessed usedmemory usedmemoryRss -o table --debug
```

Error message:
```
Failed to establish a new connection: [Errno 110] Connection timed out',))
```

When it specify the debug option and get the details of the error, it looks like an error has occurred in authentication. I would like to improve the occurrence of the error. How can I improve it?

**To Reproduce**
na

**Expected behavior**
The az command is executed without error.

**Environment summary**
**Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)**
azure-cli-2.0.31-1.el7.x86_64.rpm

**CLI version (`az --version`)**
```
# az --version
azure-cli (2.0.31)
acr (2.0.23)
acs (2.0.31)
advisor (0.5.1)
appservice (0.1.31)
backup (1.1.1)
batch (3.2.0)
batchai (0.2.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.12)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.0)
container (0.1.22)
core (2.0.31)
cosmosdb (0.1.20)
dla (0.0.19)
dls (0.0.21)
eventgrid (0.1.12)
eventhubs (0.1.2)
extension (0.0.12)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.19)
iot (0.1.19)
keyvault (2.0.21)
lab (0.0.21)
monitor (0.1.5)
network (2.0.28)
nspkg (3.0.2)
profile (2.0.22)
rdbms (0.2.1)
redis (0.2.12)
reservations (0.1.2)
resource (2.0.27)
role (2.0.22)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.31)
vm (2.0.30)

Python location '/usr/lib64/az/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

Legal docs and information: aka.ms/AzureCliLegal
```

**OS version**
/etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Shell Type (e.g. bash, cmd.exe, Bash on Windows)**  
bash

**Additional context**
```
# cat az.sh
date
/bin/az monitor metrics list --resource /subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Cache/Redis/xxxxxxxxxx --start-time 2019-06-12T07:05:53Z --end-time 2019-06-12T07:06:53Z --metrics cachehits cachemisses cacheRead cacheWrite connectedclients percentProcessorTime evictedkeys expiredkeys getcommands operationsPerSecond serverLoad setcommands totalkeys totalcommandsprocessed usedmemory usedmemoryRss -o table --debug
date

# sh -x az.sh
+ date
Wed Jun 12 15:55:54 JST 2019
+ /bin/az monitor metrics list --resource /subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Cache/Redis/xxxxxxxxxx --start-time 2019-06-12T07:05:53Z --end-time 2019-06-12T07:06:53Z --metrics cachehits cachemisses cacheRead cacheWrite connectedclients percentProcessorTime evictedkeys expiredkeys getcommands operationsPerSecond serverLoad setcommands totalkeys totalcommandsprocessed usedmemory usedmemoryRss -o table --debug
Command arguments: ['monitor', 'metrics', 'list', '--resource', '/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Cache/Redis/xxxxxxxxxx', '--start-time', '2019-06-12T07:05:53Z', '--end-time', '2019-06-12T07:06:53Z', '--metrics', 'cachehits', 'cachemisses', 'cacheRead', 'cacheWrite', 'connectedclients', 'percentProcessorTime', 'evictedkeys', 'expiredkeys', 'getcommands', 'operationsPerSecond', 'serverLoad', 'setcommands', 'totalkeys', 'totalcommandsprocessed', 'usedmemory', 'usedmemoryRss', '-o', 'table', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x172df50>, <function on_global_arguments at 0x1824aa0>, <function on_global_arguments at 0x18361b8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function remove_logger_flags at 0x172e050>]
Installed command modules ['acr', 'acs', 'advisor', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicebus', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.002 seconds.
Loaded module 'acs' in 0.002 seconds.
Loaded module 'advisor' in 0.001 seconds.
Loaded module 'appservice' in 0.004 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.007 seconds.
Loaded module 'batchai' in 0.001 seconds.
Loaded module 'billing' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.002 seconds.
Loaded module 'dla' in 0.003 seconds.
Loaded module 'dls' in 0.002 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.003 seconds.
Loaded module 'keyvault' in 0.003 seconds.
Loaded module 'lab' in 0.002 seconds.
Loaded module 'monitor' in 0.003 seconds.
Loaded module 'network' in 0.018 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.002 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.005 seconds.
Loaded module 'role' in 0.002 seconds.
Loaded module 'servicebus' in 0.004 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'sql' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.020 seconds.
Loaded module 'vm' in 0.010 seconds.
Loaded all modules in 0.124 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/root/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x1eb7cf8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x213f668>]
Event: CommandInvoker.OnPostParseArgs [<function handle_output_argument at 0x1824b18>, <function handle_query_parameter at 0x1836230>, <function handler at 0x228ca28>]
Getting management service client client_type=MonitorManagementClient
attempting to read file /root/.azure/accessTokens.json as utf-8-sig
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - Authority:Performing instance discovery: ...
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - Authority:Performing static instance discovery
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - Authority:Authority validated via static instance discovery
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - TokenRequest:Getting token with client credentials.
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - TokenRequest:No user_id passed for cache query
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - CacheDriver:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
adal-python : 5f877713-0009-4ae3-a506-e811d330095a - OAuth2Client:Get Token request failed
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/adal/oauth2_client.py", line 267, in get_token
    timeout=self._call_context.get('timeout', None))
  File "/usr/lib64/az/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /e546ca04-20ab-465c-9378-592ab55daafd/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x39383d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /e546ca04-20ab-465c-9378-592ab55daafd/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x39383d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
+ date
Wed Jun 12 16:12:52 JST 2019
```

**Comment by tjprescott** [comment]
You are running an extremely out-of-date version of the CLI. You have 2.0.31 and the current release is 2.0.66. Please update and reopen if this is still a problem.
