### ISSUE TITLE
TypeError: unexpected 'default_completer' when running az

### ISSUE THREAD

**Issue by irl** [Azure/azure-cli#973]
With all the modules installed with "python3 setup.py install --install-layout=deb", and /usr/bin/az replaced with `python3 -m azure.cli`, I get the following error:

```
Error loading command module 'storage'
__init__() got an unexpected keyword argument 'default_completer'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azure/cli/main.py", line 35, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/application.py", line 84, in execute
    self.parser.load_command_table(command_table)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 91, in load_command_table
    enable_autocomplete(self)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 33, in enable_autocomplete
    argcomplete.autocomplete = EmptyDefaultCompletionFinder()
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 30, in __init__
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_completer'
```

**Comment by irl** [comment]
Ok, so this is nothing to do with the storage module then. Removing the storage module from the build only causes that first line to go away.

**Comment by irl** [comment]
This may be related to the version of argcomplete I am using, python-argcomplete 1.0.0-1 (from Debian). Looking into updating the Debian package.

**Comment by irl** [comment]
```
(Reading database ... 229983 files and directories currently installed.)
Preparing to unpack python3-argcomplete_1.4.1-0.1_all.deb ...
Unpacking python3-argcomplete (1.4.1-0.1) over (1.0.0-1) ...
Setting up python3-argcomplete (1.4.1-0.1) ...
```

That was the problem. Ignore this issue. (:
