### ISSUE TITLE
Cannot deploy python to webapp

### ISSUE THREAD

**Issue by wryczko** [Azure/azure-cli#9730]
**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\commands\__init__.py", line 560, in execute
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\commands\__init__.py", line 618, in _run_jobs_serially
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\commands\__init__.py", line 611, in _run_job
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\six\six.py", line 693, in reraise
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\commands\__init__.py", line 588, in _run_job
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\commands\__init__.py", line 297, in __call__
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-core\azure\cli\core\__init__.py", line 461, in default_command_handler
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 296, in enable_zip_deploy
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\azure-cli-appservice\azure\cli\command_modules\appservice\custom.py", line 2203, in _check_zip_deployment_status
  File "C:\Users\...\AppData\Local\Temp\pip-install-ygnynjtx\requests\requests\models.py", line 889, in json
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Expected Behavior
Python Web App is deployed to Azure Web App

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66 *

```
## Additional Context
The case I presented above is for Windows, but I have expierience same behaviour on Linux

```
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 296, in enable_zip_deploy
    authorization, timeout)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2203, in _check_zip_deployment_status
    res_dict = response.json()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by panchagnula** [comment]
@wryczko can you. please re-try let us know if you still see this.

**Comment by wryczko** [comment]
> @wryczko can you. please re-try let us know if you still see this.

Today I have no problems, thanks, but on Wednesday deployment was nondeterministic (it succeded once per 10 retries).

**Comment by panchagnula** [comment]
thanks for the update @wryczko we did have a minor outage which was causing high latency in API calls for a brief time you could have been impacted by it. Closing this issue now.

**Comment by arjunDhanAi** [comment]
Hi,
I am seeing the same issue today i.e (october 2nd IST). I am using the azure devops to deploy my app, but it is continously throwing the same error.
2019-10-02T08:43:21.5488443Z WARNING: Starting zip deployment. This operation can take a while to complete ...
2019-10-02T08:48:01.9385853Z ERROR: The command failed with an unexpected error. Here is the traceback:
2019-10-02T08:48:01.9386555Z 
2019-10-02T08:48:02.0307343Z ERROR: Expecting value: line 1 column 1 (char 0)
2019-10-02T08:48:02.0308203Z Traceback (most recent call last):
2019-10-02T08:48:02.0309918Z   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
2019-10-02T08:48:02.0310349Z     cmd_result = self.invocation.execute(args)
2019-10-02T08:48:02.0310974Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
2019-10-02T08:48:02.0311237Z     raise ex
2019-10-02T08:48:02.0311800Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
2019-10-02T08:48:02.0312072Z     results.append(self._run_job(expanded_arg, cmd_copy))
2019-10-02T08:48:02.0312610Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
2019-10-02T08:48:02.0312866Z     six.reraise(*sys.exc_info())
2019-10-02T08:48:02.0313986Z   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
2019-10-02T08:48:02.0314300Z     raise value
2019-10-02T08:48:02.0315737Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
2019-10-02T08:48:02.0316152Z     result = cmd_copy(params)
2019-10-02T08:48:02.0316739Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
2019-10-02T08:48:02.0317037Z     return self.handler(*args, **kwargs)
2019-10-02T08:48:02.0317572Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
2019-10-02T08:48:02.0317855Z     return op(**command_args)
2019-10-02T08:48:02.0318401Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 353, in enable_zip_deploy
2019-10-02T08:48:02.0318667Z     authorization, timeout)
2019-10-02T08:48:02.0319766Z   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2356, in _check_zip_deployment_status
2019-10-02T08:48:02.0320158Z     res_dict = response.json()
2019-10-02T08:48:02.0320718Z   File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 897, in json
2019-10-02T08:48:02.0320982Z     return complexjson.loads(self.text, **kwargs)
2019-10-02T08:48:02.0321228Z   File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
2019-10-02T08:48:02.0321456Z     return _default_decoder.decode(s)
2019-10-02T08:48:02.0321647Z   File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
2019-10-02T08:48:02.0321839Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-10-02T08:48:02.0322053Z   File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
2019-10-02T08:48:02.0322269Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2019-10-02T08:48:02.0322488Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Can some one help me, please.

**Comment by arjunDhanAi** [comment]
Hi @panchagnula,

Can you please look into the above issue and help. We are stuck in the middle of deployment and i am finding no answers to this problem on the net.
just point me in the direction where I can find the solution, I will try to get it on.

Thanks
Arjun Narasimha K

**Comment by krynn1** [comment]
Anyone get a resolution or alternative for this? I'm getting this error from multiple machines and have updated to the most recent version of azure cli.
