### ISSUE TITLE
az interactive barfs!

### ISSUE THREAD

**Issue by bob-the-forestor** [Azure/azure-cli#9768]
## Describe the bug

was on 2.0.60 az interactive ran fine
ran brew update && brew upgrade azure-cli

az interactive now borked

**Command Name**
`az interactive`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/_config.py)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 624, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 617, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 594, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 303, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 470, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/nevellj/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/Users/nevellj/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/core/_config.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67

Extensions:
interactive 0.4.1

```

**Comment by tjprescott** [comment]
`az interactive --update`
