### ISSUE TITLE
ProtocolError when following logs when tailing webapp logs

### ISSUE THREAD

**Issue by gamesbrainiac** [Azure/azure-cli#9860]
## Description
When trying to follow the logs of a webapp, there was a ProtocolError.

**Command Name**
`az webapp log tail --resource-group <rg> --name <name>`

**Errors:**

```
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 601, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 605, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1732, in _get_log
    for chunk in r.stream():
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/azure-cli/2.0.63/libexec/lib/python3.7/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail --resource-group {} --name {}`

## Expected Behavior
I would expect that this kind of error is recovered from, and also errors such as these are in a different format or color, because for a minute I thought it was an exception in the application itself.

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63 *

Extensions:
webapp 0.2.20
interactive 0.4.2
find 0.3.0

```

**Comment by btardif** [comment]
@panchagnula please review this item

**Comment by panchagnula** [comment]
@gamesbrainiac i am unable to repro this, if you still repro this can you  run the command with --debug flag & share the details. Please free to share via email to sisirap@microsoft.com incase you don't prefer to share it here. Thank you!

**Comment by gamesbrainiac** [comment]
@panchagnula You need to wait for a little bit for the problem to crop up.

**Comment by panchagnula** [comment]
@gamesbrainiac I did have the command running for a while ~15mins before I decided to terminate - if you have repro steps or if this is happening for a specific kind of app or with some specific setting that would be useful info as well.

**Comment by gamesbrainiac** [comment]
@panchagnula I had it running for a few hours before this happened.

**Comment by panchagnula** [comment]
@gamesbrainiac after keeping it running for a few hours & the command failing what happens if you restart the command? In general we have new changes coming in the API level for log tail when we will make improvements to the commands  as well . I closing this for now due to lack of a repro.
