### ISSUE TITLE
nic is not added to a lb backend pool if the nic is referenced by the id

### ISSUE THREAD

**Issue by tspascoal** [Azure/azure-cli#9861]
## Describe the bug

**Command Name**
`az network nic ip-config address-pool add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'child_name_1'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 508, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 162, in raise_event
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\arm.py", line 310, in parse_ids_arguments
KeyError: 'child_name_1'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nic ip-config address-pool add --ids {} --address-pool {}`

The problem seems to lie in the use of id, because if --nic-name  and --name are specified the command works as expect. 

The id is correct, the problem not a malformed id, it was extracted using 

## Expected Behavior

the referenced NIC on ids parameter is added to the LB pool

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.65 *

Extensions:
azure-devops 0.10.0
resource-graph 0.1.8

```

**Comment by tjprescott** [comment]
The real issue here is that `--ids` should not even be exposed. You are expected to provide the name components.
