### ISSUE TITLE
az disk delete

### ISSUE THREAD

**Issue by MRTX3100** [Azure/azure-cli#9924]
The issue has been copied to your clipboard. Paste it here!
To print out the issue body locally, run `az feedback --verbose`

## Describe the bug

**Command Name**
`az disk delete`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

cannot import name 'StorageAccountTypes'Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 248, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 265, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\commands\__init__.py", line 130, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\knack\knack\commands.py", line 89, in load_arguments
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 454, in default_arguments_loader
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-cli-core\azure\cli\core\__init__.py", line 494, in get_op_handler
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\compute_management_client.py", line 16, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\__init__.py", line 12, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-z6u9vbmn\azure-mgmt-compute\azure\mgmt\compute\v2018_09_30\operations\disks_operations.py", line 18, in <module>
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\compute\v2018_09_30\models\__init__.py", line 56, in <module>
    from ._compute_management_client_enums import StorageAccountTypes
ImportError: cannot import name 'StorageAccountTypes'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az disk delete --name {} --resource-group {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62 *

```

**Comment by tjprescott** [comment]
I belive this issue has been fixed. Please update your CLI. If the issue recurs, please reopen.

**Comment by MRTX3100** [comment]
Confirming that AFTER updating the CLI, I was successfully able to delete the disks. Thank you.
