### ISSUE TITLE
`az webapp config ssl upload` dumps stack trace when it can't find the web app

### ISSUE THREAD

**Issue by Lewis-Kelley** [Azure/azure-cli#9947]
**Describe the bug**
Running `az webapp config ssl upload` dumps a stack trace when it can't find the described web app. For details, see the full dump below.

**To Reproduce**
1. Create a `.pfx` certificate with a password. Mine was self-signed, though I doubt it matters.
2. `az login`
3. `az webapp config ssl upload --certificate-file <cert>.pfx --certificate-password <secret> --resource-group <does not exist> --name <does not exist>` where all details related to the certificate are entered correctly.

**Expected behavior**
Instead of dumping, a nice error message along the lines of `"Cannot find web app <name> in resource group <rg> in the current subscription."` My personal issue was that I was in the wrong subscription, so it might be helpful to include that bit in the message.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

I installed via the [described manual installation process](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions) for `apt`. I am running on bash in Ubuntu 18.04.2. Below is the full output of `az --version`:

```
azure-cli                         2.0.69

command-modules-nspkg               2.0.3
core                              2.0.69
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/beckman/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 11 2019, 08:41:35) 
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**
Full output:
```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'hosting_environment_profile'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 578, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 627, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 606, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1836, in upload_ssl_cert
    if webapp.hosting_environment_profile else '')
AttributeError: 'NoneType' object has no attribute 'hosting_environment_profile'

To open an issue, please run: 'az feedback'
```

**Comment by panchagnula** [comment]
@Lewis-Kelley thanks for the feedback, yes we do need some good error handling here. Will look into this. In general if you run the command with --debug flag, you *might* some useful info here.

**Comment by btardif** [comment]
Triage this for next sprint.

**Comment by panchagnula** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/9985
