### ISSUE TITLE
az acr pack build command fails: "The command failed with an unexpected error"

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-cli#9952]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Unable to build/push images with `az acr pack build` command as of CLI version 2.0.68.

**To Reproduce**
Run the following command, essentially the same one prompted as an online help example:

```
az acr pack build -r <myregistry> \
  -t {{.Run.Registry}}/node-app:{{.Run.ID}} \
  --pull --builder heroku/buildpacks:18 https://github.com/Azure-Samples/nodejs-docs-hello-world.git
```

Command error returned:

```
This command group is in preview. It may be changed/removed in a future release.
Sending context to registry: <myregistry>...
The command failed with an unexpected error. Here is the traceback:

'RegistriesOperations' object has no attribute 'schedule_run'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 578, in execute
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 629, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 606, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/azure/cli/command_modules/acr/pack.py", line 89, in acr_pack_build
    queued = LongRunningOperation(cmd.cli_ctx)(client_registries.schedule_run(
AttributeError: 'RegistriesOperations' object has no attribute 'schedule_run'
```
**Expected behavior**
Command successfully builds and pushes image `node-app:<runID>` to my registry

**Environment summary**
CLI installed on MacOS or in Azure Cloud Shell

**Additional context**
Command is in preview.
Example command runs successfully in CLI v. 2.0.67

cc/ @sajayantony @dorfire

**Comment by ehotinger** [comment]
@jaysterp is looking

**Comment by sajayantony** [comment]
@dlepow - Should this issue be closed?

**Comment by dlepow** [comment]
@sajayantony - Yes, I'll close. Thanks!
