### ISSUE TITLE
az functionapp config ssl upload failed with 'NoneType' object has no attribute 'hosting_environment_profile'

### ISSUE THREAD

**Issue by bhanush3** [Azure/azure-cli#9975]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az functionapp config ssl upload failed with 'NoneType' object has no attribute 'hosting_environment_profile'

**To Reproduce**

az functionapp config ssl upload --certificate-file "C:\Users\goswami\Downloads\dev.pfx" --certificate-passwor "password" --name "Function1" --resource-group "rg1"

The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'hosting_environment_profile'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 578, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 627, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\commands.py", line 55, in _polish_bad_errors
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 606, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli\azure\cli\command_modules\appservice\custom.py", line 1836, in upload_ssl_cert
AttributeError: 'NoneType' object has no attribute 'hosting_environment_profile'

**Expected behavior**
It should upload .pfx file to ssl setting of Azure Function

**Environment summary**
C:\Scripts\B2C Automation> az --version
azure-cli                         2.0.69

command-modules-nspkg               2.0.3
core                              2.0.69
nspkg                              3.0.4
telemetry                          1.0.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\BhanushGoswami\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by zikalino** [comment]
There should me more checks in function app implementation. 
I just ran exactly the same command and I got exactly the same error. (without even creating function app beforehand).

**Comment by bhanush3** [comment]
I didn't get what do you mean by "There should me more checks in function app implementation." could you please elaborate it?

**Comment by zikalino** [comment]
I mean I tried exactly the command you used:

az functionapp config ssl upload --certificate-file "C:\Users\goswami\Downloads\dev.pfx" --certificate-passwor "password" --name "Function1" --resource-group "rg1"

without creating functionapp first, and it just crashed in the same way. It should tell me that function app "Function1" doesn't exist.

**Comment by bhanush3** [comment]
what do you assume the issue here?

**Comment by bhanush3** [comment]
its resolved
